### ISSUE TITLE
Code block horizontal scroll not easily scrollable by mouse for step 12 Responsive Web Design track

### ISSUE THREAD

**Issue by ARodriguezHacks** [freeCodeCamp/freeCodeCamp#51750] opened 2023-10-02 03:20 UTC
### Describe the Issue

On step 12 of the Responsive Web Design (RWD) Certification, the code block containing the html and text "I think freecodecamp is great" is not easily scrollable horizontally by mouse. The code block's contents are not 100% visible unless a user focuses on the code block and presses the left and right arrow keys with a keyboard. Developer tools reveal there is more html code in the code block not displaying unless scrolling by left and right arrow keys.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Steps to Reproduce

1. Navigate to Step 12 of the RWD curriculum: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12
2. Scroll to the code block containing the html `<p>I think <a href="https://www.freecodecamp.org">freeCodeCamp</a> is great.</p>`
3. Try to use your mouse to scroll horizontally to the right to reveal the rest of the code, including the closing `</a>` tag

### Expected behavior

User should have no difficulty scrolling that code block to see the code in its entirety. User should be able to use their mouse to scroll horizontally without needing to use right and left arrow keys on their keyboard. This could be especially useful to anyone brand new to coding who may be having issues seeing the entire code and /or do not know how to fully create an anchor tag. 

### Screenshots

(Brave Browser)

![fcc_issue](https://github.com/freeCodeCamp/freeCodeCamp/assets/22532097/97c09011-6c35-4f35-a4ec-35c01ce1ddff)

### System

- Device: Laptop (Macbook Air)
- OS: Mac
- Browser(s): Chrome, Firefox, Brave
- Version (Chrome): 117.0.5938.132 (Official Build) (x86_64)

### Additional context

Issue was created on the basis that someone brand new to coding may not immediately know how to use the `<a>` anchor tag with just the example code alone (which looks incomplete on first sight but in fact needs to be scrolled into view). The question also raised is whether it is obvious there is more code than what the code block initially displays AND whether the user knows right away they can try scrolling horizontally and see the rest of the code. As a non-beginner who is reviewing the fundamentals, the code did not look complete to me and that is when I discovered these user experience issues.

**Comment by bbsmooth** [comment] 2023-10-02 03:36
> ...the code block containing the html and text "I think freecodecamp is great" is not easily scrollable horizontally by mouse

Can you be more specific by what you mean? I see a horizontal scroll bar on the code block (and I see one in the screen snap you provided above). I am able to scroll horizontally by using my mouse. I drag the mouse pointer over the scroll bar and then hold down the left mouse button and move the mouse right/left to scroll. 

> The question also raised is whether it is obvious there is more code than what the code block initially displays

I think this might be a legitimate concern. My browser does not show the horizontal scroll bar on the code example by default. I only see the scroll bar if I hover over any part of the code example box with the mouse. Granted, this is controlled by a setting in my browser. I can set it to always show scroll bars if I desire. But if anyone doesn't have scroll bars set to show all the time then they may not recognize that the code block is scrollable and then they won't see the hidden code. Perhaps we should add something to signal that there is more code to see?

**Comment by ARodriguezHacks** [comment] 2023-10-02 05:28
> ...the code block containing the html and text "I think freecodecamp is great" is not easily scrollable horizontally by mouse
> 
> Can you be more specific by what you mean? I see a horizontal scroll bar on the code block (and I see one in the screen snap you provided above). I am able to scroll horizontally by using my mouse. I drag the mouse pointer over the scroll bar and then hold down the left mouse button and move the mouse right/left to scroll.

----

Yes, let me try to be more specific. I am using a Macbook Air, and my mouse is actually a mouse pad. When I try to scroll over the code block to see the rest of the code, I can only do so by clicking on that section as best I can (assuming I clicked or focused on that element, because there's no immediate indicator like an outline). Then I test to see that I did in fact select the code block by pressing down on my right and left keyboard arrows (which is when the focus outline appears). 

If you notice my original screenshot, I can only see the scroll bar easily in the dev tools for Brave browser, but my new video below shows that's not the case (for Chrome browser). This issue was tested on 3 separate browsers, the last one being Firefox. Adding these details to the issue description as well.

https://github.com/freeCodeCamp/freeCodeCamp/assets/22532097/779a4e39-bfb8-479b-8cdb-aab38a8bb5ad

**Comment by Axikop** [comment] 2023-10-02 11:47
Hey, can i please solve this issue? i have got the gist of it.

**Comment by jeremylt** [comment] 2023-10-02 12:05
> Hey, can i please solve this issue? i have got the gist of it.

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by bbsmooth** [comment] 2023-10-02 15:40
Thank you for the video @ARodriguezHacks. That is very interesting. I don't have a mac so I can't replicate this. Perhaps someone else with a mac will be able to chime in on whether they can replicate this, or even provide a solution.

The code example isn't doing anything special as far as scrolling is concerned. It is relying on the browser to provide the scroll bar when needed. I can tell you that I am able to use the scroll bar with a mouse on both my linux and Win11 systems with Chrome and Firefox. This leads me to believe that this is an issue specific to your mac, or maybe macs in general. But I'm not a mac person so I'm really just guessing here. I did google "macos horizontal scroll" and found a bunch of links explaining how to do horizontal scroll on macs, which sort of implies that this is/was an issue, but I have no idea if those are still relevant. 

If you have the time, would you test a different page to see if you are able to horizontal scroll with your mouse? 

https://cdpn.io/aardrian/debug/MWeRJWd

This is a codepen from a very well-known and reputable accessibility expert. You must narrow your browser window all the way in so that the right edge of the table gets cut-off. The table is built to horizontal scroll on purpose when you do that. Are you able to scroll the table horizontally when this happens?

**Comment by bbsmooth** [comment] 2023-10-02 15:56
>  I can only do so by clicking on that section as best I can (assuming I clicked or focused on that element, because there's no immediate indicator like an outline). 

By design the focus outline does not show up when you are using the mouse (it only shows up when you use the keyboard). But perhaps we need to add it back for mouse clicks on these code example boxes to make it clear that the box has focus and can be scrolled.

**Comment by ARodriguezHacks** [comment] 2023-10-03 00:09
@bbsmooth I tested the link you shared and followed your steps. The horizontal scrolling works as expected, and I am able to scroll with my mouse pad without issue. I can't say the same thing, though, for the code block in the affected freeCodeCamp page.

https://github.com/freeCodeCamp/freeCodeCamp/assets/22532097/2cba20df-dbd3-44e4-95de-ab4afd4f353e

**Comment by bbsmooth** [comment] 2023-10-03 01:46
Thank you for the testing and video @ARodriguezHacks. I will have to compared the website with the table to the code block example in fCC and see if I can find a difference that might be causing your scrolling problem with the code blocks.

For the page with the table, are you having to click on the table (or page) first before you can scroll? Or is it enough just to hover your mouse cursor over the table?

**Comment by mmatsumoto1026** [comment] 2023-10-03 11:34
> I will have to compare the website with the table to the code block example in fCC and see if I can find a difference that might be causing your scrolling problem with the code blocks.

I also don't have mac so I've not tested, but it seems that the fCC code block (I think this is `pre[class*=language-]` in css) does not have `overflow: auto;`, while the example table block (this is `[role="region"][aria-labelledby][tabindex]` in css) has the property.

**Comment by mmatsumoto1026** [comment] 2023-10-03 14:07
> Perhaps we should add something to signal that there is more code to see?

I agree with you because even someone completely new to coding needs to be able to notice at first glance that only a portion of the code is originally visible within a code block, especially on mobile devices.
`text-overflow: ellipsis;` may be able to provide the signal, as shown in video below.
But the property should be overwritten the value `clip` when the code is scrolled.
This is merely an idea, and I don't know this is the best practice.
Because I haven't seen any concrete, proven examples.

<details><summary>example: display the ellipsis in the code and remove it when scrolling (windows11 PC, Firefox)</summary>

https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/7dfd705f-63e3-4538-b04c-5833df8cb89f
</details>

**Comment by bbsmooth** [comment] 2023-10-03 19:25
> it seems that the fCC code block (I think this is `pre[class*=language-]` in css) does not have overflow: auto;

My dev tools is showing that `pre[class*=language-]` has `overflow` set to `auto`.

**Comment by mmatsumoto1026** [comment] 2023-10-03 22:58
> My dev tools is showing that pre[class*=language-] has overflow set to auto.

Sorry, I simply overlooked the property in dev tools and also the codebase so you are definetely correct.

**Comment by ARodriguezHacks** [comment] 2023-10-04 21:34
> Thank you for testing and the video @ARodriguezHacks. I will have to compare the website with the table to the code block example in fCC and see if I can find a difference that might be causing your scrolling problem with the code blocks.
> 
> For the page with the table, are you having to click on the table (or page) first before you can scroll? Or is it enough just to hover your mouse cursor over the table?

@bbsmooth apologies for the late reply, but to answer this question, Yes, it is enough for me to just hover over the table with my mouse pad to scroll horizontally.

**Comment by ARodriguezHacks** [comment] 2023-10-04 22:17
> Since the main difference appears to be that one is using a `div` and the other is using `pre`, I've put together some examples of both in a [codepen](https://codepen.io/bbsmooth/pen/MWZPwwy). @ARodriguezHacks, if you, or anyone else using macOS has the time, I would appreciate it if you could test the four examples in my [codepen](https://codepen.io/bbsmooth/pen/MWZPwwy) and see which (if any) you are able to scroll with your mouse and report back. I don't think videos are necessary, just yes/no for each one. Also, if you have both an actual mouse and a trackpad, please test with both of them.

@bbsmooth The 4 Codepen examples are all scrollable via hovering (as well as non-hovering) with my Mac laptop's mouse pad. However, I'm confused about the 'actual' mouse test. With an actual mouse, I'm not able to hover and scroll, I don't believe that's possible, Mac or otherwise, unless you meant if using an actual mouse works as expected too. Which it does, by the way., by the usual dragging of the scrollbar since it's clearly visible. 

I do wonder if the code in the freeCodeCamp page has any z-index issues? I will do additional testing as well, but I wonder if the code for that code block is too nested, so when a user hovers over the section with their mouse, the mouse cannot easily detect that the code block exists and that there's more content by scrolling.

**Comment by ARodriguezHacks** [comment] 2023-10-04 22:29
UPDATE: I'm not entirely sure if the codebase has been updated but I checked 3 browsers on my Mac, but now the scrollbar is visible for the code block.

I still cannot scroll by hovering with my mouse pad, but this seems like an appropriate fix from at least a user experience perspective, because now we can see the scrollbar to indicate there is more to the code block than what my previous video was displaying. I even checked on my Ubuntu desktop, and it's showing the same thing.

![fcc_step_12_update](https://github.com/freeCodeCamp/freeCodeCamp/assets/22532097/5337edf5-e58b-4336-a156-7a76a95b044f)

**Comment by lasjorg** [comment] 2023-10-04 22:51
It is still broken for me with WebKit (using Playwright on Windows).

![webkit](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/06407f6b-19b8-4c05-9ddd-43fedebecf4d)


It has the "Scroll" badge in the Element Inspector (same as how Firefox does it) but no scroll bar. Setting it directly to `scroll` also doesn't do anything. I also tried creating an overflow using fixed width on both the pre and code elements and it still does not create a scroll bar.

**Comment by bbsmooth** [comment] 2023-10-05 00:05
@ARodriguezHacks 

> unless you meant if using an actual mouse works as expected too. Which it does, by the way.

Yes, this is exactly what I meant, just using an actual physical mouse. I just wanted to verify that that was working OK and it was just the trackpad mouse that wasn't working.

**Comment by bbsmooth** [comment] 2023-10-05 00:06
@ARodriguezHacks 

> UPDATE: I'm not entirely sure if the codebase has been updated but I checked 3 browsers on my Mac, and all of a sudden now the scrollbar is visible for the code block.

I'm not aware of any updates that would have an affect on this.

**Comment by bbsmooth** [comment] 2023-10-05 00:16
@ARodriguezHacks:
> The 4 Codepen examples are all scrollable via hovering (as well as non-hovering) with my Mac laptop's mouse pad. 

These four examples are not really doing anything different than what the fCC code blocks are doing. The main difference is that the fCC code block is embedded in a `div` that has absolute positioning. I'll create some more codepen tests emulating that and if you are willing to test again maybe we can figure out if that is the issue.

**Comment by lasjorg** [comment] 2023-10-05 01:04
@bbsmooth It is super simple to set up Playwright in case you want to test it.

https://joyofcode.xyz/test-your-site-in-every-browser

It might not be 100% the same as Safari on a Mac but it usually works just fine for testing.

**Comment by bbsmooth** [comment] 2023-10-05 18:57
@ARodriguezHacks 

> I still cannot scroll by hovering with my mouse pad

In Win11/linux, I can hold down the `Shift` key while scrolling with my middle mouse button and that will cause the mouse to scroll horizontally instead of vertically. When I try that with my four codepen examples then it works as expected. I do not need to put focus on the code blocks. I can just hover my mouse over each code block, hold down the `Shift` key, and them scroll the middle mouse wheel and the code block will scroll horizontally. I believe this is equivalent to what you are doing with your trackpad.

But when I try this with the fCC code block in step 12, instead of the code block scrolling horizontally, the entire editor window scrolls horizontally, even if I have focus set on the code block itself. I'm guessing that the monaco editor is hijacking the scroll event and preventing the code block from scrolling horizontally. I am not surprised by this, as it hijacks a lot of other events that we have had to work around in the past. So when you are trying to horizontal scroll with your trackpad it is actually scrolling, but its scrolling the entire editor window, not the code block.

The reason you are not seeing any scrolling is because you probably do not have the editor's accessibility mode turned on. When you turn accessibility mode on then the editor does not line wrap long lines and thus long lines will overflow on the right side of the editor, which will allow for horizontal scroll to be seen. You can toggle accessibility mode using `Ctrl + e` on Win/linux. I'm assuming it is something similar on mac. If you can't find it then while focus is in the editor hit `F1` on your keyboard and search for `Toggle Accessibility Mode`. Once you've enabled accessibility mode and try to horizontal scroll the code block I think you'll see that it is scrolling the editor instead.

So I think this solves the mystery of why horizontal scrolling with the trackpad isn't working. You'll just need to use the traditional method of clicking the actual scroll bar and dragging it to scroll. And it sounds like you are now seeing the scroll bar? Can you think of anything you might have done to make this happen?

**Comment by ARodriguezHacks** [comment] 2023-10-06 20:17
> But when I try this with the fCC code block in step 12, instead of the code block scrolling horizontally, the entire editor window scrolls horizontally, even if I have focus set on the code block itself. I'm guessing that the monaco editor is hijacking the scroll event and preventing the code block from scrolling horizontally. I am not surprised by this, as it hijacks a lot of other events that we have had to work around in the past. So when you are trying to horizontal scroll with your trackpad it is actually scrolling, but it's scrolling the entire editor window, not the code block.

@bbsmooth I have no idea off the top of my head how to enable accessibility mode on my Macbook Air. I looked it up, and it looks like a number of steps to enable that. Also, it doesn't look like my Accessibility Keyboard is turned on, per my search results on how to toggle accessibility on a mac. 

> You'll just need to use the traditional method of clicking the actual scroll bar and dragging it to scroll. And it sounds like you are now seeing the scroll bar? Can you think of anything you might have done to make this happen?

But yes, I can now see the scroll bar on 3 separate browsers. It may have had to do with something accessibility related, but I didn't go out of my way to enable that. I raised this issue because from a user experience standpoint, it was not obvious that there was more code without the ability scroll that code block nor see a scrollbar. The fact that a scrollbar is now visible I think is enough to no longer keep this issue open, though I'm not sure how it appeared from one day to the next. 

I'll this to up to the FCC maintainers, but I don't think this issue needs to be open any longer. The original scope was for a Macbook Air, so I can't say for certain whether this issue persists in other environments.

**Comment by bbsmooth** [comment] 2023-10-06 20:55
@ARodriguezHacks 

> I have no idea off the top of my head how to enable accessibility mode on my Macbook Air. 

Sorry, I might not have been clear enough. You don't enable it on your macbook. You enable it in the editor itself. The editor's accessibility mode is completely independent from your OS.

**Comment by ARodriguezHacks** [comment] 2023-10-06 21:28
@bbsmooth it doesn't matter, I checked both my OS and the editor in the exercise. Whenever I toggle that setting it doesn't even affect that code block but rather lines 7-8. Also, I highly doubt I went in and toggled accessibility in the editor for 3 separate browsers by complete accident, on Macbook I'd have to press down fn + F1 to get it to show up.

**Comment by bbsmooth** [comment] 2023-10-06 21:43
@ARodriguezHacks 

> Also, I highly doubt I went in and toggled accessibility in the editor for 3 separate browsers by complete accident

Sorry, I guess I didn't explain things too well.

I agree, you did not turn on accessibility mode. That's why you weren't seeing any horizontal scrolling. I only mentioned accessibility mode so you could see for yourself that the editor is horizontal scrolling (instead of the code block example in the instruction) if you wanted to confirm that what I was explaining above is correct. 

> Whenever I toggle that setting it doesn't even affect that code block but rather lines 7-8.

Correct, accessibility mode only affects the lines of code in the editor, not the code example blocks in the instructions. When you do have accessibility mode turned on and there are lines of code overflowing the right side of the editor then you should be able to see the entire horizontal editor scroll horizontally when using your trackpad.

**Comment by bbsmooth** [comment] 2023-10-11 22:44
We've had a second person in the forum bring up the issue that the horizontal scroll bar is not showing when the code overflows the block and thus they didn't realize it was scrollable. This was one of the issues that @ARodriguezHacks was initially having on macOS, but now it appears to have been fixed, but I don't think we know why. I don't know the OS of the second person yet (but I'm guessing macOS by the looks of the pic they provided). 

I'm not sure this is something that we can solve from our end, unless we want to switch from relying on the browser to supply the scroll bar (which is triggered by `overflow: auto`) and instead implement our own scroll bar from scratch (which is what monaco does with the vertical scrollbar in the editor). Or we get lucky enough to figure out that there is some obscure bug that is causing a certain browser on a certain OS to not display the scrollbar when needed and we are able to figure out a workaround for it. (This assumes that the issue is due to a bug and not the configuration of the OS/browser.)

Another option would be to add some sort of visual cue that the code block is scrollable so anyone who isn't seeing a scrollbar will at least know it is scrollable. I'm not sure what that would be, I'll leave it up to the designers.

I thinks that's where we are on this issue. The other issue of not being able to horizontally scroll the code block on mouse hover only has been explained and I'm guessing we are not going to try and fix that.

**Comment by Supravisor** [comment] 2024-03-31 01:42
The scroll bar is now apparently appearing for MacOS (see above).
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/2bab26bc-839d-4227-8510-07868aabdefb)

Is the scroll bar not appearing for other browsers or OS?

**Comment by Supravisor** [comment] 2024-06-25 10:59
Looks like there was an update to the way code is displayed in the editor.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/ace16ed1-eb19-46bb-9f0a-50aac3e3c270)

Has anyone reported or had issues with horizontal scrolling since the update?

**Comment by Mehdi1972** [comment] 2024-07-30 23:11
scroll bar woks fine and you can easily access the overflowing text

**Comment by ilenia-magoni** [comment] 2024-09-17 19:30
this issue doesn't seem to still be present. If you find again this issue or have additional infos please comment and we can reopen this issue.

**Closed by ilenia-magoni** 2024-09-17 19:30 UTC
Labels: type: bug, help wanted, platform: learn
