### ISSUE TITLE
Footer image is misplaced when zooming in the tab

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#41071] opened 2020-12-29 04:26 UTC
Browser: Firefox 84
OS: Linux
Environment: Production and dev

Here is how it looks when I increase the zoom level to 133%.

![Screenshot from 2020-12-29 11-17-24](https://user-images.githubusercontent.com/25715018/103258527-eab54580-49c7-11eb-83e8-8e2cd101240e.png)

**Comment by Ismailtlem** [comment] 2021-02-26 21:13
I am not sure that this issue is still present 
![Screenshot (1232)](https://user-images.githubusercontent.com/34961373/109355700-e13d4200-787f-11eb-8a4b-5d13501a76ca.png)

**Comment by huyenltnguyen** [comment] 2021-02-27 10:54
@Ismailtlem Could you help check with the player being played? That's when the image appears. I'm currently on a different machine with a different screen resolution, but can reproduce the issue with zoom level being 150%.

**Comment by Ismailtlem** [comment] 2021-02-27 15:09
It's quite a strange bug. I succeeded to reproduce the issue on ubuntu on a zoom level 133%
![Uploading Screenshot (1233).png…]()

**Comment by ahmadabdolsaheb** [comment] 2021-03-01 08:00
Same here on macbook chrome 125%

**Comment by ahmadabdolsaheb** [comment] 2021-03-04 12:43
Additionally, the image of he related album is not showing. Must be because of internet speed miscalculation, but I though I should mentioned here so we could address the ui and the functionality of that element at the same time.

**Comment by ahmadabdolsaheb** [comment] 2021-03-04 12:47
I think we would need to restyle the footer using flexbox, so the elements are flexible and we could keep a certain order in the same row.

**Comment by Ismailtlem** [comment] 2021-03-06 16:29
Hi @ahmadabdolsaheb 

- Is the footer not already styled with flexbox ? https://github.com/freeCodeCamp/coderadio-client/blob/main/src/css/App.css#L29
- For the problem mentionned in this issue regarding the footer image that has a height that goes over the footer container, would a solution like this works ? (this solution is only about making the album image height equal to the footer height as I mentionned earlier)
![image](https://user-images.githubusercontent.com/34961373/110213212-4d7efd80-7e9f-11eb-896b-730c0697dbdf.png)
- Do you have some solution to suggest for this problem ? 
![image](https://user-images.githubusercontent.com/34961373/110213437-515f4f80-7ea0-11eb-891c-409f2e242ee6.png)
I thought about keeping the current functionning for the album image but only if the width is over some value (something like 900 px and if the width is between 750 px and 900px, we either don't show the album image or replace it in the extreme left of the screen like the default behavior, and we keep the existing behavior of the album image if the width is less than 750 px)
- For the image of the album that is not showing, I think I found the problem. It's related to a misusage of props between the App and the Footer component. I will make a PR for that.

**Comment by ahmadabdolsaheb** [comment] 2021-03-08 13:43
- It is flex, but some of the inner elements are absolutely positioned.

- If I understand you correctly, we want to have the height of the album image be the same as footer for certain widths and have it larger and located above the div with #nowPlaying id. ideally it would be the same breakpoint that we change the background image.

- a pr would be appreciated for displaying the album image.

**Comment by Ismailtlem** [comment] 2021-03-17 20:52
Is it not better to keep the album image on the left when height is <  650 px ? I am not sure it is very nice from a web design perspective.
![image](https://user-images.githubusercontent.com/34961373/111536865-11834c80-876b-11eb-8025-99b8a5fab96d.png)

**Comment by ahmadabdolsaheb** [comment] 2021-03-18 07:36
Yes, so we would have a break point between two layout (show below).
They layout should completely change around 750px, since the face of the character in the animation is the focal point of the page. Smaller screens would cover her face.

In the screenshot you shared above the corner is centered by mistake, it should be to the left if the animation is shown.

Please let me know if my explanation is not clear.
layout: 1
<img width="1919" alt="Screen Shot 2021-03-18 at 10 30 56 AM" src="https://user-images.githubusercontent.com/4591597/111588833-1ed52100-87d5-11eb-819d-45c6d0cb235f.png">
layout: 2
<img width="737" alt="Screen Shot 2021-03-18 at 10 31 19 AM" src="https://user-images.githubusercontent.com/4591597/111588868-2c8aa680-87d5-11eb-9968-ce2203eac5b5.png">

**Comment by Ismailtlem** [comment] 2021-05-02 21:00
Is this still an issue ? Is it not resolved ?

**Comment by ahmadabdolsaheb** [comment] 2021-05-03 05:08
Closing this issue since the footer works as expected. thanks for noticing it.

**Closed** 2021-05-03 05:08 UTC
Labels: platform: coderadio
