### ISSUE TITLE
Mismatch between text and practice projects sequence

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47740] opened 2022-10-01 11:00 UTC
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md

In this step it says 
> You will learn about [flexbox] in more detail on another project.

but the flexbox practice project comes before this one. This has to be removed or changed to indicate a previosu project.

**Comment by shardul08** [comment] 2022-10-01 11:39
I think removing it would be better

**Comment by rahulraheja49** [comment] 2022-10-01 12:35
I think replacing it with a line like **"You have learnt about this in the challenge [challenge-name]"** and then linking the challenge link would be a good idea so that a learner can directly go to that challenge by clicking on the link.

This was the challenge where it was taught: **learn-css-flexbox-by-building-a-photo-gallery**

**Comment by jeremylt** [comment] 2022-10-01 13:54
**if** we replace instead of remove, perhaps

>You learned about flexbox in the [photo gallery project]

Though I'm not sure we need this line

**Comment by Sboonny** [comment] 2022-10-02 10:47
I think, it's better to say,

> You can revamp what you have learned about flexbox in [photo gallery project]

but, the description should be about the current issue, and it's easy to navigate between projects, so I vote delete it

**Comment by ieahleen** [comment] 2022-10-02 16:36
I mean, yeah, deleting is maybe better!

An improvement for the project could be to change the instructions to use flexbox to consider that it has been already introduced in an other project. That may be for an other issue tho

**Comment by nayabatir1** [comment] 2022-10-03 12:08
Unless we need to remind the user that this topic was taught in this section, deletion is preferable choice for me.

**Comment by Sboonny** [comment] 2022-10-03 12:15
Okay, I am opening the issue. 

The description should be changed to this.

> Try to center your `.bb1` element, using these style properties: `display: flex;`, `flex-direction: column;`, and `align-items: center;`.

**Comment by moT01** [comment] 2022-10-03 15:25
This looks like a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/47555 - there's a few more suggestions over there we should consider. One example that just changes the instructions, and another that breaks this up into three steps.

**Closed** 2022-10-03 15:34 UTC
Labels: type: bug, first timers only, hacktoberfest
