### ISSUE TITLE
Open the sample projects on a new window ( project section )

### ISSUE THREAD

**Issue by medaminefh** [freeCodeCamp/freeCodeCamp#43387] opened 2021-09-05 18:05 UTC
#### Actually I think all the project pages, Like this one
[Build a survey Form](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-survey-form)

## System

- Device: Laptop
- OS: Ubuntu 20.4
- Browser: chrome
- Version: 93

**Comment by ayangupta9** [comment] 2021-09-06 14:29
Hi! Can I look into this issue?

**Comment by ShaunSHamilton** [comment] 2021-09-06 14:46
Hey @ayangupta9 Thank you, for your interest in contributing. However, this issue has not been discussed yet.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ShaunSHamilton** [comment] 2021-09-06 14:48
@medaminefh Thank you, for taking the time to open this.

However, I am closing this as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/39739

**Closed by ShaunSHamilton** 2021-09-06 14:48 UTC
Labels: type: bug, status: waiting triage

**Comment by ayangupta9** [comment] 2021-09-06 15:08
@ShaunSHamilton  Thanks a lot for the clarification! Looking forward to becoming a long-time contributor in the near future 😃
