### ISSUE TITLE
Heat Map Without Heat

### ISSUE THREAD

**Issue by ayushshah2120** [freeCodeCamp/freeCodeCamp#34968] opened 2019-01-27 17:51 UTC
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/shahayush

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit) 
* Operating System: Windows 10 Pro N

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/40225091/51925359-e0bded00-2414-11e9-88d9-57a38614c9dd.png)

**Comment by RandellDawson** [comment] 2019-01-29 17:01
Can you please provide more information such as exactly what you are expect to see and why?

**Comment by ayushshah2120** [comment] 2019-01-29 17:08
The Heat Map with heat signatures which are supposed to show on the profile about the profile curriculum being completed day-wise is not being shown on the profile.

**Comment by RandellDawson** [comment] 2019-01-29 18:14
Can you tell us what days you are expecting to see on the map?  Which days?

**Comment by ayushshah2120** [comment] 2019-01-30 06:16
Take Jan 29th 2019,
It has 17 items done on that day, there is no heat on that day.
Similarly Jan 27th 2019 has 4 items done but no heat

**Comment by icatat** [comment] 2019-01-30 22:48
Hi! I would be interested to work on this issue, but I would first like to clarify it. Did those challenges never show up on the heat map? Or it was a delay?

**Comment by ayushshah2120** [comment] 2019-01-31 13:37
> Hi! I would be interested to work on this issue, but I would first like to clarify it. Did those challenges never show up on the heat map? Or it was a delay?

The Challenges Never Showed Up on heat map, Not Even One.
Even The ones I Completed Recently aren't showing up on Heat Map.

**Comment by icatat** [comment] 2019-01-31 18:38
I would like to work on this. Could you assign this issue to me?

**Comment by RandellDawson** [comment] 2019-01-31 18:48
This appears to be a duplicate of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/17822.  I am closing this one.  Please use the existing issue to report your findings.

**Closed by RandellDawson** 2019-01-31 18:48 UTC
