### ISSUE TITLE
[beta] D3: add-inline-styling-to-elements test case won't pass

### ISSUE THREAD

**Issue by becausealice2** [freeCodeCamp/freeCodeCamp#12787] opened 2017-01-23 22:15 UTC
Challenge [add-inline-styling-to-elements](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/add-inline-styling-to-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Similar to issues mentioned in issues within #12762, I can't get the `Your h2 elements should have a font-family of verdana.` test to pass in Firefox. I have refreshed the page, reset the code, cleared local storage--in all permutations, several times each--verified that each h2 element has the correct attribute and value, and checked to see what FCC JS code's test was asserting. The only error being logged throughout any of this is `Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.` on page refresh. At least one other person has tried and had the same problem in Firefox, but were able to pass after a few refreshes in Chrome after a few page refreshes.

Additional challenges that appear to have this same problem:
[Change Styles Based on Data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data)
[Change the Presentation of a Bar Chart](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-the-presentation-of-a-bar-chart)
[Change the Color of an SVG Element](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-the-color-of-an-svg-element)
[Style D3 Labels](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/style-d3-labels)

A recurring theme is that the solution to the failing test cases are all in element attributes, if that helps any...

**Comment by benschac** [comment] 2017-01-31 18:14
I had the same issue on my end.  I cleared localStorage and submitted the correct solution on the first try and it worked.  It looks like there's an issue with the dataset being over written.

**Comment by benschac** [comment] 2017-01-31 18:47
@OFFLlNE I think the localStorage just needs to be tweaked a little bit to not re-initalize the const dataset and this should work.  Can someone just confirm this and I'll submit a PR.  I deleted the const dataset in my local storage and it worked just fine.

**Comment by srini5** [comment] 2017-02-09 14:30
Came here to report this same issue (Identifier "dataset" has already been declared) on multiple D3 exercise pages. I was able to proceed by changing the name of the const identifier and resubmitting, or reloading the page.

**Comment by fonsecapontes** [comment] 2017-03-05 02:46
See the comments about this issue in main #10749

**Comment by systimotic** [comment] 2017-03-16 20:27
Hi everyone! Thank you all for reporting and investigating this issue.

The style test issues are indeed caused by #10749 (an issue so many people are having that I know that number by heart now, and won't forget it for the rest of my life 😅)

The issue @benschac is talking about is being tackled in #12762.

I'm closing this issue as a duplicate of those issues. Happy coding!

**Closed by systimotic** 2017-03-16 20:27 UTC
Labels: beta, tests
