### ISSUE TITLE
An Issue With the "alt" Attribute

### ISSUE THREAD

**Issue by CuriousQuestion** [FreeCodeCamp/FreeCodeCamp#11751] opened 2016-11-21 16:57 UTC
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22Author%20standing%20on%20a%20beach%20with%20two%20thumbs%20up.%20%22%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<img src="https://bit.ly/fcc-relaxing-cat" alt="Author standing on a beach with two thumbs up. ">
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
If anyone else comes across the issue where they create and "alt" attribute but the lesson doesn't accept it, it's because there's a weird bug where you have to put "Author standing on a beach with two thumbs up. " within the "alt"; not whatever you want. :)

**Comment by no-stack-dub-sack** [comment] 2016-11-21 17:52
Hi @CuriousQuestion, I am unable to reproduce this issue. I replaced "Author standing on a beach with two thumbs up. " with text of my choice and the challenge passed fine. It's possible that something may have been off with your other approach?

For issues like this, unless you are sure it's a bug, it's always best to go to the [Help Chatrooms](https://gitter.im/FreeCodeCamp/HelpFrontEnd)  or [Forum](https://forum.freecodecamp.com) first. If someone else can reproduce your issue and you are sure it's a bug, then here is the place to let us know. When reporting an issue, always show us the code that _didn't_ work, rather than the code that did, that way we can more easily see what's going on and reproduce the problem. 

For now, since I am unable to reproduce this, I am closing the issue. If you are sure it is a big, please re-open the issue with further clarification and the code that produced a failing test.

Thanks and Happy Coding!

**Closed** 2016-11-21 17:53 UTC

**Comment by CuriousQuestion** [comment] 2016-11-21 17:56
Hello Peter! No, if you put in "Author standing on a beach with two thumbs
up. " it works perfecty, the issue is if you try and put anything else. And
the only reason this may be confusing and frustrating to some is because it
doesn't specifically say you need to add "Author standing on a beach with
two thumbs up," it just says make sure you include and "alt" tag :)

**Comment by CuriousQuestion** [comment] 2016-11-21 17:58
Oh, I apologize, I just reread your email and understand that you put in
your own text, haha. Okay, that's great to hear! Thank you for taking the
time to check the issue :) Happy Holidays, Peter!

**Comment by no-stack-dub-sack** [comment] 2016-11-21 18:09
@CuriousQuestion No problem! Did you try to reproduce the issue again? If you can reproduce it, please post the failing code.

**Comment by CuriousQuestion** [comment] 2016-11-21 18:39
So, I attempted to reproduce it and lo and behold it worked with an
arbitrary description! Thanks again, Peter, haha. Is there any place I can
give you a good review? You're very thorough :)

**Comment by no-stack-dub-sack** [comment] 2016-11-21 18:54
@CuriousQuestion Nope, but it's all good - no worries! Not necessary. Good luck in your continued coding journey!

**Comment by CuriousQuestion** [comment] 2016-11-21 19:25
Haha, thank you! Good luck in any journeys you partake in, as well!

**Comment by 0x4d1** [comment] 2016-11-23 11:05
text is alt attribute doesnt work , whats problem ? What ever I write inside alt="... "  still same

**Comment by no-stack-dub-sack** [comment] 2016-11-23 23:45
@0x4d1 This is a standard message notifying you that this issue seems to be a  request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our `[full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)`.

**Comment by portaljacker** [comment] 2016-12-08 05:51
I have a concrete example here: http://tinyurl.com/ztjdbyc

The solution was changing the alt text to "cat".
