### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by jmc3720** [FreeCodeCamp/FreeCodeCamp#11782] opened 2016-11-23 20:56 UTC
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--h1>Hello World</h1-->
<h2>CatPhotoApp</h2>

<!--p>Hello Paragraph</p-->


```
When I click submit it gives me an error saying i changed the order
Do not change the order of the h1 h2 or p in the code.
and wont let me get past this please advise?

**Comment by jmc3720** [comment] 2016-11-23 21:00
I think its a bug

**Comment by jmc3720** [comment] 2016-11-23 21:00
but I maybe wrong:)

**Comment by Manish-Giri** [comment] 2016-11-23 21:08
@jmc3720 It's not a bug, your code is incorrect. You've partially removed the opening and closing tags for both `<h1>` and `<p>`. For instance, this - 
```
<!--h1>Hello World</h1-->
```
should be 
```
<!--<h1>Hello World</h1>-->
```

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first if you need help with issues like these. Happy Coding!

**Comment by CherryPlaysRoblox1** [comment] 2016-11-23 21:44
You included the h1 in your comment

**Comment by erictleung** [comment] 2016-11-23 22:55
@jmc3720 thanks for the issue but as others have pointed out, you've commented out your HTML elements incorrectly. Please use the help rooms for questions in the future. Happy coding!

**Closed by erictleung** 2016-11-23 22:55 UTC
Labels: question

**Comment by lynxumba** [comment] 2019-03-09 14:20
Hello World-->

**Comment by RandellDawson** [comment] 2019-03-09 14:22
@lynxumba Please only make comments relevant to the discussion of this issue.

**Comment by lynxumba** [comment] 2019-03-09 19:53
ok
