### ISSUE TITLE
Incorrect Wording as part of the task

### ISSUE THREAD

**Issue by owencampbell** [FreeCodeCamp/FreeCodeCamp#2309] opened 2015-08-20 12:23 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

First target your **div** element with the id target3 by using the $("#target3") selector.

**div** needs changing to **button**.

**Comment by meecoder** [comment] 2015-08-20 14:05
This is a duplicate of issue #2170.

**Closed** 2015-08-21 03:58 UTC
