### ISSUE TITLE
[beta] Project challenge page layout broken upon successive login

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#12674] opened 2017-01-21 03:39 UTC
#### Issue Description

Upon login, the user is brought back to the next challenge. If the challenge happens to be a project, the page layout is broken and clicking on Map has no effect.

Steps to reproduce: log out of the beta site, close browser window, and log in again using email and password.

#### Browser Information

* Browser Name, Version: Google Chrome v55.0.2883.95
* Operating System: macOS 10.12.2
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![screen shot 2017-01-21 at 07 24 46](https://cloud.githubusercontent.com/assets/241553/22171677/8d69470c-dfac-11e6-894d-c8856df0aded.png)

**Comment by no-stack-dub-sack** [comment] 2017-01-21 16:45
@leonfeng you beat me to it! I was also going to report this issue. Nice catch! 😄

**Comment by systimotic** [comment] 2017-01-26 10:29
Thanks for reporting @leonfeng! There has since been opened an issue that is a duplicate of this, but it has a bit more info, so I'll close this in favour #12801. Feel free to continue the conversation there!

**Closed by systimotic** 2017-01-26 10:29 UTC
Labels: beta
