### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by mrdavidfriedman** [FreeCodeCamp/FreeCodeCamp#2270] opened 2015-08-20 02:50 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It's great that we can create random decimal numbers, but it's even more useful if we lot more useful to generate a random whole number.

Should read:
It's great that we can create random decimal numbers, but it's even more useful if we use it to generate a random whole number.

**Comment by dokkillo** [comment] 2015-08-20 07:03
working in this issue

**Comment by issyl0** [comment] 2015-08-22 16:53
Thanks for reporting this. It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:

**Comment by issyl0** [comment] 2015-08-22 17:02
Duplicate of #2086.

**Closed** 2015-08-22 17:03 UTC
