### ISSUE TITLE
[beta] Not registering teal color in hsl

### ISSUE THREAD

**Issue by noone396** [freeCodeCamp/freeCodeCamp#13442] opened 2017-02-19 05:18 UTC
Challenge [adjust-the-tone-of-a-color](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-tone-of-a-color) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  header {
    background-color: hsl(178, 90%, 35%);
    color: #FFFFFF;
  }
  nav {
    background-color: hsl(180, 100%, 25%);
  }
  h1 {
    text-indent: 10px;
    padding-top: 10px;
  }
  nav ul {
    margin: 0px;
    padding: 5px 0px 5px 30px;
  }
  nav li {
    display: inline;
    margin-right: 20px;
  }
  a {
    text-decoration: none;
    color: inherit;
  }
</style>
<header>
  <h1>Cooking with FCC!</h1>
  <nav>
    <ul>
      <li><a href="">Home</a></li>
      <li><a href="">Classes</a></li>
      <li><a href="">Contact</a></li>
    </ul>
  </nav>
</header>

```

**Comment by Greenheart** [comment] 2017-02-19 18:58
@noone396 Thanks for reporting this issue!

I can confirm that the previous challenge uses `hsl(180, 100%, 50%)` while the one you reported the issue for only accepts `hsl(178, 80%, 25%)`. There are two things I find confusing:

1. [Adjust the Hue of a Color](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hue-of-a-color) presents the describes the color as "cyan", while [Adjust the Tone of a Color](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-tone-of-a-color) uses "teal". This should probably be consistent.
2. The second challenge explicitly tells campers to use "the same teal hue" as the challenge before, while testing for a completely different value. This should be consistent as well.

@noone396 Since you spotted this, would you like to create a PR with a fix for this? Me and other contributors would be happy to guide you through the process :blush:

**Comment by noone396** [comment] 2017-02-19 20:18
Awesome! I would love you guys to teach me. I've never done a PR before.
Although, I think the issue has already been fixed. I just checked and it's
been updated from cyan to teal.

**Comment by Greenheart** [comment] 2017-02-19 21:13
@noone396 Glad to hear that! 

The previous challenge ([Adjust the Hue of a Color](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hue-of-a-color)) still uses "cyan".

#### There's potentially two things to fix:
1. Do you think we should update [these lines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1638-L1680) to use "teal" instead of "cyan"? Or maybe this *hue* of the color is better described as cyan, and should be called cyan in the first challenge.?

2. For the next challenge ((Adjust the Tone of a Color)[http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-tone-of-a-color]), [This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1700) and [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1735) should have all occurrences of `178` replaced with `180` to make the tests follow the instructions.

[CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) can help get started.

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding! :smile:

**Comment by noone396** [comment] 2017-02-19 21:59
I think we should keep the color "cyan" in both challenges to keep it
consistent. Overall, I think "cyan" blends better than "teal" in the
"Applied Visual Design: Adjust the Tone of a Color" challenge.

Thanks for the contributing guide. I'll update the changes as soon as
possible.

Thanks again for the help :).

**Comment by Greenheart** [comment] 2017-02-19 23:14
@noone396 Sure, let's go with cyan!

No problem! Good luck :)

**Comment by noone396** [comment] 2017-02-21 03:56
Hi Samuel,

I'm having a bit of trouble setting up my environment in order to
contribute. I feel like I'm holding up the closure of this ticket since the
change is so basic. You can go ahead and make the change. When I eventually
complete my setup I will start contributing to future issues.  I haven't
asked for help yet on the contributing chat because I want to figure it out
as much as I can. Thanks again for the help and contributing documentation.

Sophie

**Comment by Greenheart** [comment] 2017-02-21 07:14
@noone396 No problem, I think you should do it if you want to contribute! Tell us about your issue in the chat room - and take your time :blush:

**Comment by noone396** [comment] 2017-02-21 13:20
Okay sounds good. I also wanted to make sure I understood what I was doing
as well. Hopefully I can get it done this week and I'll be sure to ask for
help if I can't figure out.

**Closed** 2017-03-16 14:56 UTC
Labels: beta, confirmed, tests
