### ISSUE TITLE
Autopassing challenges

### ISSUE THREAD

**Issue by SrebniukNik** [FreeCodeCamp/FreeCodeCamp#2757] opened 2015-08-26 21:54 UTC
Hi there,
Challenge http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

During "Run code" my browser (Mozilla 39.0) hung and asked to wait or stop running scenario. Meanwhile my page began continuously refreshing, after refresh challenge was marked as "Successfully passed" and moved to next challenge, and so on!!! 

Then I quickly closed browser tab. Sorry I haven't screenshot but seems, for every challenge some script generating POST request with new URI and code "successfully passed". 

Thanks for your good job and cool material. Wish you money richness ))))))

Wbr,
Nik

**Comment by Mansuro** [comment] 2015-08-27 10:11
Duplicate of #2709

**Comment by bugron** [comment] 2015-09-01 18:23
@SrebniukNik thanks for posting this issue!
Note that your issue is a duplicate:
#2709

This should be fixed now. Closing as a duplicate.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-01 18:23 UTC
