### ISSUE TITLE
Insert-Pointer-Issue in Chrome macOS fullscreen

### ISSUE THREAD

**Issue by girlboss558** [freeCodeCamp/freeCodeCamp#13146] opened 2017-02-04 22:50 UTC
I have had this insert-pointer-issue throughout the challenges, but I am stuck on challenge 80(Style Text Inputs as Form Controls). I can't insert the pointer to the part of the page I need to add code.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment] 2017-02-05 10:14
Hey @girlboss558 !

This is a duplicate of #7847, there is a work around mentioned there, that you can use, the fix is live on the beta site, but we do not have a date right now for the release to the main website yet.

We request your patience, and apologise for the inconveniences.

Thanks, and happy coding!

**Closed by raisedadead** 2017-02-05 10:14 UTC
