### ISSUE TITLE
Random formula

### ISSUE THREAD

**Issue by diddierh** [FreeCodeCamp/FreeCodeCamp#4439] opened 2015-11-14 22:12 UTC
I think You should not be so strict with the expression with which the random number must be generated, forcing to use the expression `Math.floor(Math.random( * (3 - 1 + 1)) + 1` (by the way is very silly -1+1 ) cuts creativity and interest in thinking in how to solve the problem the expression `Math.floor(Math.random()*3)+1` is also valid but not accepted.

**Comment by faizaanceg** [comment] 2015-11-15 04:02
Already discussed and considered in #4009.

**Comment by SaintPeter** [comment] 2015-11-15 08:09
Closing as duplicate of  #4009

**Closed by SaintPeter** 2015-11-15 08:09 UTC
