### ISSUE TITLE
TypeError: string is not a function

### ISSUE THREAD

**Issue by maximumpeaches** [FreeCodeCamp/FreeCodeCamp#9430] opened 2016-06-28 14:49 UTC
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22.%22%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "I am a \"double quoted\" string inside \"double quotes\"."


```
For some reason this game me a string is not a function error as seen in the screenshot,
![image](https://cloud.githubusercontent.com/assets/10927490/16420090/0200ed72-3d1e-11e6-8140-41f96c0e5ff3.png)

**Comment by raisedadead** [comment] 2016-06-28 15:32
You are almost there. Please check, is something missing at the end of the line?
Thanks for reporting, if you need any assistance, [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript). 

Closing as not a bug, on website.

**Closed by raisedadead** 2016-06-28 15:32 UTC
