### ISSUE TITLE
Editor - cursor repositioning issue

### ISSUE THREAD

**Issue by Dhrumilcse** [FreeCodeCamp/FreeCodeCamp#9296] opened 2016-06-22 17:20 UTC
Having issue with cursor repositioning, while loading a new challenge.

**Comment by ramir141974** [comment] 2016-06-22 17:28
I don't know how to fixed it this issue if somebody help me to organized this issue it must be great thank you.

I am biggener that's all...

**Comment by BKinahan** [comment] 2016-06-22 17:31
This is a duplicate of #7847, feel free to take a look at that issue and add any additional information or insight you may have :)

**Comment by atjonathan** [comment] 2016-06-22 17:47
@Dhrumilcse, thanks for reporting this issue, feel free to follow along with #7847 and leave a comment :smile: 
@BKinahan, thanks for that :tada:

**Closed** 2016-06-22 17:46 UTC
Labels: duplicate
