### ISSUE TITLE
Use HTTPS for codepen demos

### ISSUE THREAD

**Issue by viruzx** [FreeCodeCamp/FreeCodeCamp#9703] opened 2016-07-13 03:51 UTC
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.

I didn't manually mess with most challenges but I doubt this is the only instance of this. Like most privacy aware users, I run HTTPS-Everywhere and it makes codepens fail when they load insecure ressources.

Change http: for https:

**Comment by qmikew1** [comment] 2016-07-13 05:05
Not a lot of detail about (other than an extension) what API, or what browser, is being used. It might be [chrome itself](https://www.reddit.com/r/FreeCodeCamp/comments/4erevj/no_https_then_say_goodbye_to_geolocation_in/)  (independent of the security extension) and/or possibly trying another API. Though, fcc recommends codepen for projects, it (codepen) is not affiliated with fcc nor do they have any control over it.  You might want to link the pen and ask for assistance in [help room](https://gitter.im/freecodecamp/HelpFrontEnd)

**Comment by viruzx** [comment] 2016-07-13 05:17
It is with everything rather. Often mixed active content protection is there by default, others use extensions. The moment you load JS, CSS and so on over http while on a https page, it breaks. While https on a http page works fine.

It's not an issue with codepen, it's an issue with how files are included in the codepens such as querying for the IP via http instead of https.

I am not asking for assistance, I am asking for a 1-character long change on a multi demos for them to work properly for everybody.

If I could submit a pull request, I would but I can't submit pull requests for codepens as they are not in this repo to my knowledge.

**Comment by qmikew1** [comment] 2016-07-13 05:44
I'll leave it to others to comment. But you're describing changing url of the actual example link (to https) and its behavior on load (as well as url within a call in the code itself). As you say that breaks with mixed content (if done over https). I can recreate with a manual https link on the pen and it breaks on on ipinfo.io (as expected). - I've used extensions in the past; however, I know that their usage might break functionality in some sites and would think most people would know that as well. - But again, others might disagree. But before doing a PR I'd a) test whether ipinfo.io can be served over https - because many of their examples (on [dev page](https://ipinfo.io/developers) ) look like this:
```
$.getJSON('http://ipinfo.io', function(data){
  console.log(data)
})
```
and b) wait for feedback from other folks

**Comment by erictleung** [comment] 2016-07-13 15:20
@viruzx thanks for the issue. I too am conscious of HTTPs statuses of sites I visit. For this CodePen, however, I think the API which retrieves the weather information (unfortunately) uses/requires a HTTP connection. If you change the CodePen address to HTTPS, it no longer works. Closing this issue as it's a duplicate of #9145. Happy coding!

**Closed by erictleung** 2016-07-13 15:20 UTC
