### ISSUE TITLE
Margin should require unit specified with value used

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1020] opened 2015-06-20 07:10 UTC
Challenge http://www.freecodecamp.org/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

CSS spec requries the unit for the value provided.
Check here: http://jigsaw.w3.org/css-validator/#validate_by_input
Give it this as an example: .green-box { margin: 40 20 20 40;
}
Result is this: Value Error : margin only 0 can be a length. You must put a unit after your number : 40 20 20 40
Example of what will pass: .green-box { margin: 40px 20px 20px 40px; } 
Same applies if you do margin-top: 40; as well... it needs a unit as well to pass specification

![waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element](https://cloud.githubusercontent.com/assets/3256176/8266365/a53750f4-16e0-11e5-8aa9-0010de0da687.png)

**Comment by zeffii** [comment] 2015-08-18 09:15
confirmed... the margin / padding shorthands should specify a unit, if the scalar is not 0. Right now it accepts:
```javascript
margin: 20 40 20 40;
```
but accodring to https://developer.mozilla.org/en/docs/Web/CSS/padding it should not.

**Comment by awesomeaniruddh** [comment] 2015-09-11 07:18
```js
"tests": [
        "assert($(\".green-box\").css(\"margin-top\") === \"40px\", 'Your <code>green-box</code> class should give the top of elements <code>40px</code> of <code>margin</code>.')",
        "assert($(\".green-box\").css(\"margin-right\") === \"20px\", 'Your <code>green-box</code> class should give the right of elements <code>20px</code> of <code>margin</code>.')",
        "assert($(\".green-box\").css(\"margin-bottom\") === \"20px\", 'Your <code>green-box</code> class should give the bottom of elements <code>20px</code> of <code>margin</code>.')",
        "assert($(\".green-box\").css(\"margin-left\") === \"40px\", 'Your <code>green-box</code> class should give the left of elements <code>40px</code> of <code>margin</code>.')"
      ]
```

The current tests (^^^) suggest that the unit is being auto-added by the browser.

Looking at the tests for other JS sections, I'm not sure how we could assert a unit. Maybe @BerkeleyTrue can help?

**Comment by zeffii** [comment] 2015-09-11 07:45
i read that Jquery automatically adds the 'px' units to the return value if none is specified. 
.. so if
```js
$(".green-box").css("margin-top")
```
by that logic it would return `40px`  if
```html
   margin: 40 20 20 40;
```
but it returns `0px`  maybe it's changed

http://stackoverflow.com/a/15747592/1243487

**Comment by BerkeleyTrue** [comment] 2015-09-11 15:19
The browser is auto correcting.

**Comment by awesomeaniruddh** [comment] 2015-09-12 13:19
@BerkeleyTrue so is this fixable?

**Comment by BerkeleyTrue** [comment] 2015-09-12 17:44
Not without a lot of regex.

**Comment by awesomeaniruddh** [comment] 2015-09-13 01:40
Closing this because doesn't seem worthwhile. The challenge instructions instruct the user to include the units.

**Closed by awesomeaniruddh** 2015-09-13 01:40 UTC
Labels: confirmed, Test Improvement
