### ISSUE TITLE
Spec tests disappears after editing code

### ISSUE THREAD

**Issue by jnewman12** [FreeCodeCamp/FreeCodeCamp#2724] opened 2015-08-26 05:23 UTC
Challenge http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. 

When you edit the code or make any changes to it, the entire spec suite disappears. The only way around it was to keep running the code, but as soon as you change it, it goes back.

**Comment by BerkeleyTrue** [comment] 2015-08-26 05:36
Closing as duplicate of #2723 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-26 05:36 UTC
