### ISSUE TITLE
Challenge Completes without proper code.

### ISSUE THREAD

**Issue by natac13** [FreeCodeCamp/FreeCodeCamp#1390] opened 2015-07-27 00:09 UTC
On challenge 55 I found that if you only name the indoor radio name='indoor-outdoor' it allows the user to continue. This assume everything else is right but the name= is missing for the outdoor radio. I suppose pretty minor.

**Comment by eabedrapo** [comment] 2015-08-17 19:10
Here's a screenshot that shows that to pass the waypoint **only one radio button needs a name and the other can stay blank**, but the second test asks both radio buttons having the same name.
![image](https://cloud.githubusercontent.com/assets/1670763/9313536/d9cccd7a-44f9-11e5-9c37-f52e2e67fd98.png)

**Comment by eabedrapo** [comment] 2015-08-17 19:22
Similar issue is occurring for 
http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes

In this case the checkboxes must have the shared name "personality", but the test passes just by having at least one of three checkboxes with that name.

Here's an screenshot showing that (notice I used radio button's name to name other checkboxes):
![image](https://cloud.githubusercontent.com/assets/1670763/9313844/ac1ac7cc-44fb-11e5-961b-8995b5fcd4bf.png)

**Comment by bugron** [comment] 2015-08-23 06:39
Dear camper, your issue is related to these ones:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1307
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1017

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by natac13** [comment] 2015-08-23 10:41
Should this one just be closed then?

**Comment by bugron** [comment] 2015-08-23 10:51
@natac13 It seems your issue is not a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1307 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1017 so you shouldn't close the issue if you didn't get answer to your question. But in future please start opening your issue with reading this article [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug). Thank you.

**Closed** 2015-09-07 23:56 UTC
Labels: QA
