### ISSUE TITLE
Semicolon on while statement causes challenge failure

### ISSUE THREAD

**Issue by restartedwill** [FreeCodeCamp/FreeCodeCamp#9652] opened 2016-07-10 00:07 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/smallest-common-multiple

#### Issue Description

Using the sample solution in the wiki article for this algorithm, for a do...while loop, if you include the required semicolon after the while, you get "SyntaxError: Unexpected token ;". If you take the semicolon out, you get a stop sign on the line saying that the semicolon is missed, but the challenge passes.

#### Browser Information
* Browser Name, Version: Chrome, 52.0.2743.60 beta-m
* Operating System: WIndows 10 Home
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```js
   do {
    quot = newArr[0] * loop * newArr[1];
    for (n = 2; n < newArr.length; n++) {
      if (quot % newArr[n] !== 0) {
        break;
      }
    }

    loop++;
  } while (n !== newArr.length);
```

#### Screenshot
![scm](https://cloud.githubusercontent.com/assets/19537557/16710923/0afad190-45f7-11e6-926d-4f13cdb5e8a9.jpg)

**Comment by dhcodes** [comment] 2016-07-10 02:12
I've confirmed this in Chrome. The full solution code is:
`function smallestCommons(arr) {
  // Sort array from greater to lowest
  // This line of code was from Adam Doyle (http://github.com/Adoyle2014)
  arr.sort(function(a, b) {
    return b - a;
  });

  // Create new array and add all values from greater to smaller from the
  // original array.
  var newArr = [];
  for (var i = arr[0]; i >= arr[1]; i--) {
    newArr.push(i);
  }

  // Variables needed declared outside the loops.
  var quot = 0;
  var loop = 1;
  var n;

  // Run code while n is not the same as the array length.
  do {
    quot = newArr[0] * loop * newArr[1];
    for (n = 2; n < newArr.length; n++) {
      if (quot % newArr[n] !== 0) {
        break;
      }
    }

    loop++;
  } while (n !== newArr.length);

  return quot;
}

// test here
smallestCommons([1,5]);`

FWIW, MDN shows the do...while as having the semicolon.

**Comment by raisedadead** [comment] 2016-07-11 08:52
This is possibly due to a bug in looprotect (A library that we use to check for infinite conditions).

**Comment by restartedwill** [comment] 2016-07-11 12:51
Can the error message also be updated to report the line where the supposed error (extra semicolon) exists? Debugging is a matter of removing and running for each semicolon otherwise (in this case) since the code was valid, and this is bad development practise. Or is looprotect an unchangeable module?

**Comment by raisedadead** [comment] 2016-07-11 13:29
The current workaround is to add `//noprotect` on top of the code for this specific solution. However, yeah we do need a fix for this condition.

```js
//noprotect 

function smallestCommons(arr) {
...
...
  arr.sort(function(a, b) {
   ...
  });
...
...
...
```

**Comment by raisedadead** [comment] 2016-07-11 13:30
Taging as a bug, because this can potentialy affect any solution on any challenge that uses syntax similar to the Opening Post.

**Comment by flipsyde606** [comment] 2016-07-12 06:35
Shall I look into this?

**Comment by raisedadead** [comment] 2016-07-12 06:38
@flipsyde606:
By all means, any issue that's tagged as Help Wanted is open to all for a fix. 
You needn't request permission. Thanks a lot.

**Comment by flipsyde606** [comment] 2016-07-13 11:29
@raisedadead sure, but I need help with issue though. The final rendered code after loopProtect looks like the one below:

` };loopProtect.protect({ line: 32, reset: true }); while (n !== newArr.length){
if (loopProtect.protect({ line: 32 })) break;
;
}`

loopProtect seems to treat while part of do-while as a seperate while. I am not sure how to fix this without fixing loopProtect itself.
Should we:

1. Ask the camper to remove the semicolon and provide him/her with the line number?
 (Sends out the wrong message as the code is actually right)
2. Use regex to find do-while pairs and remove semicolon before passing it to loopProtect?
(Costly, error-prone and hacky solution)
3. Provide a hint in the challenges to use //noprotect if they get this particular error.

If there is a better solution, please feel free to pitch in.

**Comment by raisedadead** [comment] 2016-07-13 14:32
@flipsyde606: If this is a bug in the  loop-protect library then we can log a issue on their repo. 
But I am not sure that its very well maintained. The published fork on npm is a fork of the original.

Anyways:
Option 1 and Option 2 are a strict NO GO.

Option 3 is a work around, but we still would need to detect this for do...while loops. Of course we can tell the campers to use this in all algorithm challenges but then that beats the purpose of having it in the first place.

/cc @FreeCodeCamp/issue-moderators thoughts?

**Closed** 2016-08-12 05:43 UTC
Labels: bug, confirmed, help wanted
