### ISSUE TITLE
can't login or register!

### ISSUE THREAD

**Issue by bottled-ant** [FreeCodeCamp/FreeCodeCamp#12101] opened 2016-12-18 17:34 UTC
#### Issue Description
I don't know how to help, but I can't fint a way to register or login...

tryed to login with github -> ups, something went wrong
tryed to register with email -> email already exists
tryed to reset password -> ups, something went wrong
tryed to login -> invalid user or pass

counting 3 days now that I try to register or login, for noobies like me this is highly upsetting and a turn away.

I only have basic knowledge in HTML CSS php MySQL and was looking to use this platform to expand my skills and knowledge.

#### Browser Information
* Firefox50.x
* LinuxMint18 and Android
* Mobile, Desktop and Tablet

**Comment by raisedadead** [comment] 2016-12-18 18:10
Hi, @bottled-ant thanks once again for reporting. 

Your profile at https://www.freecodecamp.com/bottled-ant which has been created via GitHub.
From the issue above, I understand that you facing the problem on all of your devices, i.e LinuxMint18 and Android?

I tried the steps for my own account on the main website and can't reproduce the problem.
Can you help us with some screenshots?

If you could also check the Developer Console on firefox (Press F12) for any errors?

If you prefer you can ping me on the chat: https://gitter.im/raisedadead for more help as well.

**Comment by bottled-ant** [comment] 2016-12-19 15:31
#### this issue (#12106) is the same as mine... [issue link](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12106#) Yes I'm unable to login in any device or os I try to.
#### I'm not on my computer right now but as soon i can i will sen screenshots and check the console.

**Comment by raisedadead** [comment] 2016-12-20 05:50
@QuincyLarson can you look up and fix the user identity and the user id for @bottled-ant in the backend when you have a moment?

@bottled-ant do you have any updates with screenshots?

**Comment by QuincyLarson** [comment] 2016-12-20 05:55
@raisedadead thanks for bringing this to my attention. @bottled-ant You sent me an email, so I'm already working on figuring out what happened with your account. I'm closing this issue and we can debug this over email.

**Closed by QuincyLarson** 2016-12-20 05:55 UTC
Labels: accounts

**Comment by bottled-ant** [comment] 2017-02-01 22:09
@QuincyLarson would you please remove me from free code camp mailing list. I would appreciate it.
I'm unable to login through github account or any other way to edit my account settings

tried to login with github -> ups, something went wrong
tried to register with email -> email already exists
tried to reset password -> ups, something went wrong
tried to login with email -> invalid user or pass

It as nothing to do with my browser, system or whatever
I have tried with multiple browsers, systems and devices
I get the same result, as explained before, in all of them

**Comment by bottled-ant** [comment] 2017-02-01 22:12
![a map to learn to code and become a software engineer free code camp - mozilla firefox_001](https://cloud.githubusercontent.com/assets/16694358/22528499/791a73c0-e8cb-11e6-86b1-fabb6b0eb209.png)

**Comment by bottled-ant** [comment] 2017-02-01 22:13
![sign in to free code camp using your email address free code camp - mozilla firefox_002](https://cloud.githubusercontent.com/assets/16694358/22528524/9fd3c84a-e8cb-11e6-810c-35ba213b00a7.png)

**Comment by bottled-ant** [comment] 2017-02-01 22:14
these are the only to screens I see... It makes no sense and is plain annoying can't login in any way...
