### ISSUE TITLE
you can't type on line 71 at all and that i on all

### ISSUE THREAD

**Issue by Octopiman** [FreeCodeCamp/FreeCodeCamp#11965] opened 2016-12-08 00:30 UTC
Challenge [Style Text Inputs as Form Controls](https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by Octopiman** [comment] 2016-12-08 00:31
It's not the code it's that i can't type on line 71 or further down.

**Comment by erictleung** [comment] 2016-12-08 06:13
@Octopiman sorry to hear about your issue. Your issue sounds similar to this one https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. Can you take a look and see if pressing enter or typing a little bit before typing again will solve the issue?

**Comment by kilocycle** [comment] 2016-12-11 22:50
@erictleung @Octopiman I am having the same issue. Can only scroll to the beginning of line 71. I'm using Firefox on Win10. Pressing 'Enter' allows me to proceed further.

**Comment by raisedadead** [comment] 2016-12-12 08:59
Closing as a duplicate of #7847

**Closed by raisedadead** 2016-12-12 08:59 UTC
