### ISSUE TITLE
[python]: bad script fails wrong test

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52448] opened 2023-11-29 17:13 UTC
I do not really know how to word the problem other than:

1) Follow instructions of challenge to best of ability
<img width="516" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/eae059d6-314b-40cf-8ab4-d812c2fe5164">

2) Run tests
3) See hint given does not correspond to issue
<img width="489" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/b88d053f-efdc-46f1-9fe2-2ee64c556497">

**Expected Behaviour**

When tests do not rely on Camper code "compiling", the tests should still be allowed to pass/run.

OR

When Camper code does not "compile", a different error should appear other than defaulting to the **first hint**

**Comment by ojeytonwilliams** [comment] 2023-11-29 17:20
I'm going to need some more context. Which challenge is this and where is the code?

**Comment by ieahleen** [comment] 2023-11-29 17:44
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/52411

**Comment by ShaunSHamilton** [comment] 2023-11-29 19:12
Thanks @ieahleen 🚀 

@ojeytonwilliams As also shown in #52411 , if I have a test `assert.match(code, /a = 1/)`, but a Camper has a syntax/logic error in their Python:

```py
a = 1
b =
```

The tests will fail, and the first hint text will be given to the Camper. That hint text could be `You should have "a = 1" in your code` (which it clearly does). So, the hint does not make sense.

**Comment by ojeytonwilliams** [comment] 2023-11-29 20:35
Thanks for clarifying, @ieahleen and @ShaunSHamilton. Is the desired behaviour: if the python script raises an exception, show a hint like "something went wrong in your python script, please see the console for more information"?

**Comment by ShaunSHamilton** [comment] 2023-11-30 06:31
> Is the desired behaviour:

I would say we should have the option to:
a) Allow an invalid script to pass all tests (what if we want to show what happens with errors) - just test the code string
b) Manually check the code exceptions or not

**Comment by ShaunSHamilton** [comment] 2024-01-10 05:48
Closed by #53040

**Closed** 2024-01-10 05:48 UTC
Labels: type: bug, scope: curriculum, platform: learn
