### ISSUE TITLE
 code portfolio page shows mostly empty lines for challenges done since 2 days ago

### ISSUE THREAD

**Issue by roygrubb** [FreeCodeCamp/FreeCodeCamp#10670] opened 2016-09-10 09:42 UTC
#### Issue Description

As of today, the challenges I completed yesterday have no challenge description, or link to "View Solution" - see image.  Ones prior to that, i.e. Sep 07 2016, are as before.

In addition, my code for those nine challenges has all been lost.  (I guess have a revision session coming up!)
#### Browser Information

Chrome 52.0.2743.116 m (64-bit)
Win 7 64-bit Desktop, fully up to date
#### Screenshot

![fccissues](https://cloud.githubusercontent.com/assets/17702836/18409574/aedb0710-777c-11e6-8cc9-ee03fa4a1a42.jpg)

**Comment by EssaAlshammri** [comment] 2016-09-10 11:17
I'm having the same thing :)

**Comment by atjonathan** [comment] 2016-09-10 12:42
Can't reproduce.

**Comment by P1xt** [comment] 2016-09-10 13:14
Reproduced - Chrome (latest) Mac Osx
![camper p1xt s code portfolio free code camp](https://cloud.githubusercontent.com/assets/322175/18410708/8808f172-772e-11e6-82dd-e788228237ce.png)

**Comment by puntje** [comment] 2016-09-10 13:39
Can confirm this as well and add that yesterday the new entries were fine, although instead of "View solution" it displayed "View this challenge".

**Comment by QuincyLarson** [comment] 2016-09-10 16:32
This seems to be related to Friday's deployment of new code. @BerkeleyTrue do you know what could have caused this? Were there any changes to the way completed challenges are stored on user objects?

**Comment by tricksyshedevil** [comment] 2016-09-10 21:29
My challenges from yesterday are showing up as N/A on the portfolio but are checked on the map. I also completed about 30 challenges earlier today that aren't on the portfolio or map checklist. I had noticed my points stuck at 31 but didn't look into it until the challenges stopped working properly.

![image](https://cloud.githubusercontent.com/assets/22060356/18413630/291a8b90-77a5-11e6-9339-895d15c006a0.png)

**Comment by bcondron** [comment] 2016-09-10 23:05
Experiencing the same difficulties as @tricksyshedevil . A couple of results from the time period when the new system was deployed are recorded as blank lines with NAs, but most of them are not recorded at all.

**Comment by P1xt** [comment] 2016-09-10 23:14
@QuincyLarson the cache reset you mentioned in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678 did NOT fix this issue, just confirmed, my portfolio renders with N/As exactly as it did earlier.

**Comment by QuincyLarson** [comment] 2016-09-11 03:17
@roygrubb @tricksyshedevil @puntje @EssaAlshammri @P1xt This is due to a change in how we store completed challenges. I believe this will be fixed next Friday when we push the React application again (we had to roll it back yesterday: http://forum.freecodecamp.com/t/weve-rolled-back-to-the-non-single-page-app-version-of-freecodecamp-com/35587

I will leave this issue open until next Friday, when this issue should resolve itself. Thanks for your patience.

**Comment by raisedadead** [comment] 2016-12-15 06:25
Closing as resolved.

**Closed by raisedadead** 2016-12-15 06:25 UTC
