### ISSUE TITLE
appends #target5 to the #left-well twice

### ISSUE THREAD

**Issue by vertechnology** [FreeCodeCamp/FreeCodeCamp#10700] opened 2016-09-11 17:02 UTC
Challenge [Target the Parent of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");

  });
</script>

<!-- Only change code above this line. -->

<body>
  <div class="container-fluid">
    <h3 class="text-primary text-center">jQuery Playground</h3>
    <div class="row">
      <div class="col-xs-6">
        <h4>#left-well</h4>
        <div class="well" id="left-well">
          <button class="btn btn-default target" id="target1">#target1</button>
          <button class="btn btn-default target" id="target2">#target2</button>
          <button class="btn btn-default target" id="target3">#target3</button>
        </div>
      </div>
      <div class="col-xs-6">
        <h4>#right-well</h4>
        <div class="well" id="right-well">
          <button class="btn btn-default target" id="target4">#target4</button>
          <button class="btn btn-default target" id="target5">#target5</button>
          <button class="btn btn-default target" id="target6">#target6</button>
        </div>
      </div>
    </div>
  </div>
</body>

```

**Comment by BKinahan** [comment] 2016-09-11 18:30
Thanks for reporting @vertechnology. This is a duplicate of #5072 which will be fixed in the upcoming update when the site moves to React. You can see that it's already fixed on the [beta site](https://beta.freecodecamp.com/en/challenges/jquery/clone-an-element-using-jquery).

**Closed by BKinahan** 2016-09-11 18:30 UTC
Labels: duplicate, resolved in beta
