### ISSUE TITLE
[ISSUE] Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by kziembla** [FreeCodeCamp/FreeCodeCamp#2874] opened 2015-08-30 10:37 UTC
Hi,

Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Unit tests cannot be executed.

**Comment by kkingsbu** [comment] 2015-08-30 11:28
+1

Ran into this problem this morning.

**Comment by Chikrix** [comment] 2015-08-30 12:12
Same thing here, I'm having the same issue.

**Comment by jmanders85** [comment] 2015-08-30 14:19
Currently hung up on this problem as well.

**Comment by natac13** [comment] 2015-08-30 17:19
I am working on fixing this right now

**Comment by natac13** [comment] 2015-08-30 17:27
I have submitted a PR for this.

**Comment by dting** [comment] 2015-08-30 19:48
This is fixed in this PR also https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2575

**Comment by natac13** [comment] 2015-08-30 20:14
@dting I have removed my PR

**Comment by dting** [comment] 2015-08-30 20:47
@natac13 I totally didn't mean that you needed to close your PR. Sorry for the misunderstanding. I was just was mentioning that the other PR also includes a fix. Since it is a larger change, keeping your PR open for an immediate fix is perfectly fine.

**Comment by natac13** [comment] 2015-08-30 20:51
@dting oh no worries. I did it only to clean up some pull request for the main contributors. You really went to town on the changes. I am just really happy I was able to fix it as well!

**Comment by ECadorniga** [comment] 2015-08-31 10:35
+1
Currently stuck up with this one.

**Comment by samirprakash** [comment] 2015-08-31 12:20
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

GO to http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays

Check the unit test section. Script error being reported.

Not able to proceed with the test.

![image](https://cloud.githubusercontent.com/assets/4006402/9578557/a934167c-5008-11e5-969d-280f99c04f5b.png)

**Comment by zoorz** [comment] 2015-08-31 13:41
Maybe can help you! https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879

**Comment by Dr-Turner** [comment] 2015-08-31 15:08
+1 

Me too. Utterly stuck.

**Comment by andyshephard** [comment] 2015-08-31 17:18
Had an issue where the code wouldn't compile either. Tried in several other IDEs, all working fine.

<img width="1289" alt="screen shot 2015-08-31 at 10 18 05" src="https://cloud.githubusercontent.com/assets/3307650/9585114/ab47fa3a-4fc9-11e5-83c9-990dfd8736b5.png">

**Comment by BerkeleyTrue** [comment] 2015-08-31 19:28
Fixed

**Closed by BerkeleyTrue** 2015-08-31 19:28 UTC
Labels: QA

**Comment by Alikdv** [comment] 2015-09-02 21:10
function largestOfFour(arr) {
    return arr.reduce(function(p, c, index, arr){
      p.push(Math.max.apply(null, c));
      return p;
    }, []);
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
