### ISSUE TITLE
Issue after claiming full stack certificate - legacy full stack shows error

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#18253] opened 2018-10-04 12:57 UTC
I recently claimed my full stack certificate after having all the other certificates (including the 3 non full stack legacy ones) - When I claimed the cert, it showed up on my profile in two spots, the legacy area and the new area - so my profile looks like this...

<img width="406" alt="screen shot 2018-10-04 at 7 46 09 am" src="https://user-images.githubusercontent.com/20648924/46475040-06f6b780-c7aa-11e8-8943-96b3a39e54cd.png">

I'm not sure if that's intentional or not but the issue is that when I try to open the legacy full stack cert it does not open and I get a flash message that looks like this...

<img width="1333" alt="screen shot 2018-09-29 at 11 54 37 am" src="https://user-images.githubusercontent.com/20648924/46475156-62c14080-c7aa-11e8-9e95-ae2b83a4a955.png">

The one at the top opens as expected 
https://www.freecodecamp.org/mot01 <= my profile if you want to see the problem

**Comment by qualitymanifest** [comment] 2018-10-06 18:02
This issue is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/18128

**Comment by nischaldutt** [comment] 2018-10-12 11:00
I would like to take a shot at this if anyone else has not taken it up yet?

**Comment by moT01** [comment] 2018-10-12 12:16
@nischaldutt give it a shot - @qualitymanifest that other issue seems to be two different issues in one, so I will leave this open for now, and if it gets fixed we can close this and post over there that the second problem is fixed - thanks for posting where the problem is

**Comment by nischaldutt** [comment] 2018-10-12 17:22
I'm on it

**Comment by qualitymanifest** [comment] 2018-10-12 18:41
@moT01 You're right, I should have said they are related, rather than calling it a duplicate. Better to address this issue individually.

Thank you @nischaldutt for taking this

**Comment by nischaldutt** [comment] 2018-10-12 18:46
I cannot find the specified file path `common/app/routes/Profile/components/Certificates.jsx`.
Can you help me figure out where is it located?

**Comment by qualitymanifest** [comment] 2018-10-12 19:03
Ah. That was from the `next` branch, but it looks like that branch got removed during the major repo overhaul that happened a few days ago described here https://www.freecodecamp.org/forum/t/hacktoberfest-2018-update/231160

I'll see if I can find where that code lives now

**Comment by nischaldutt** [comment] 2018-10-12 19:38
Thanks for responding! I got it :+1: 
How much longer will it take to be live any idea?

**Comment by qualitymanifest** [comment] 2018-10-12 20:20
Okay, I think I finally get it now. It's pretty confusing with all these changes. After the repo overhaul, the `production` branch is the live site (this is pretty obvious, I just didn't think to look for it). FWIW, here is the problem file in the `production` branch
https://github.com/freeCodeCamp/freeCodeCamp/blob/production/common/app/routes/Profile/components/Certificates.jsx

I am not sure how often the current `master` branch (what used to be the `next` branch) will be merged into `production`, but I believe the problem will no longer exist when it is merged.

**Comment by nischaldutt** [comment] 2018-10-14 16:15
I have a problem. When I forked the repository, every file and folder is copied except for the `common` folder, where I have to commit the changes.
<img src="https://user-images.githubusercontent.com/25385285/46919229-01933b80-cffa-11e8-909c-b2b360ecb21f.png" />

Am I missing something?

**Comment by thecodingaviator** [comment] 2018-11-21 16:03
Is the problem still there @moT01 ?

**Comment by moT01** [comment] 2018-11-22 12:45
Yes @thecodingaviator, this problem still persists - you can see it by clicking the link to my profile I put in the issue description, then clicking the full stack cert under the legacy area.

**Comment by thecodingaviator** [comment] 2018-11-22 14:49
On a side note, when did you claim the Full Stack Certification?

**Comment by thecodingaviator** [comment] 2018-11-22 15:04
Okay, I've figured out the problem, we're using one and the same variable for the legacy and 2018 Full-Stack certs, this is somewhere messing up

**Comment by scissorsneedfoodtoo** [comment] 2019-04-05 06:14
I believe https://github.com/freeCodeCamp/freeCodeCamp/pull/35608 will address this.

**Comment by thecodingaviator** [comment] 2019-04-05 07:10
@scissorsneedfoodtoo I guess so, I'll close my PR.

@ahmadabdolsaheb I'm assigning you to the issue

**Closed** 2019-06-11 11:46 UTC
Labels: status: ready for QA
