### ISSUE TITLE
The code seems right to me but the test fails

### ISSUE THREAD

**Issue by carpben** [freeCodeCamp/freeCodeCamp#15294] opened 2017-06-10 15:18 UTC
The code seems fine to me but the test fails. 
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables

#### Browser Information
Chrome, Windows 10

#### Screenshot

![image](https://user-images.githubusercontent.com/13496178/27003924-a17ef4ac-4e2a-11e7-990e-8287a8fd42b2.png)

Is it Test Suite related?

**Comment by tstusr441** [comment] 2017-06-12 17:51
Potentially related to #14990 (uncofirmed).
`.blog-post h2` color seems to only change when using plain css `text-color: red;`

**Comment by jantonioavalos** [comment] 2017-06-14 05:36
The same case with me...
I used a similar code to #14990:
`
<style>
  $text-color: red;
  
  .header{
    text-align: center;
  }
  .blog-post {
    color: $text-color;
    color: red;
  }
</style>`

**Comment by jmintb** [comment] 2017-06-19 19:39
I have encountered the same issue on chromium arch linux.

**Comment by alicankaralar** [comment] 2017-06-22 20:43
same here

**Comment by gregorywong** [comment] 2017-07-19 08:46
Same here.

macOS 10.11.6
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by systimotic** [comment] 2017-09-03 19:21
Hi all! Thanks for reporting and looking into this issue. I'm closing this as a duplicate of #12699. Happy coding!

**Closed by systimotic** 2017-09-03 19:21 UTC
Labels: beta
