### ISSUE TITLE
Need to a way to prevent infinite loops in users' challenge code from crashing Chrome browsers 

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37837] opened 2019-11-26 19:10 UTC
**Issue:** We need a way to stop code which creates an infinite loop from running long enough to crash a browser. Since master was deployed to production a few weeks back, we have seen an uptick in the number of forum questions for certain challenges (like the while loop and for loop challenges) where they inadvertently create an infinite loop with their code and it crashes the browser. I know there was something in place that used to prevent a single test from running more than 100ms, but obviously that feature was removed at some point.

If a single test takes longer than say 500ms, then the test runner should stop and a message like the following should appear in the FCC console.

> The code you have written is taking longer than the 500ms our test runner allows. You may have created an infinite loop or need to refactor an inefficient algorithm.

How to reproduce:  Using Chrome (on Windows 10), if I enter the following code for the [Iterate with JavaScript While Loops](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops) challenge:
```js
// Setup
var myArray = [];

var i = 0;
while(i < 5) {
  myArray.push(i);
  i--;
}
```

the following occurs:

![Video](https://files.gitter.im/RandellDawson/Ns6B/ezgif.com-video-to-gif-4-.gif)

We have seen a significant increase in the number of forum topics/post where users are experiencing this issue.

**Comment by moT01** [comment] 2019-11-26 19:47
This seems to be a chrome specific issue, other browsers seem to allow whatever we have in place to run long enough to time itself out. I tried to find more info about how long chrome gives before throwing that error. I found some unconfirmed info that it is 3600ms.

**Comment by arjunnij** [comment] 2019-11-26 22:45
Additionally, this seems to continue even after rebooting Chrome and my computer. When I log back in and go to those challenges, my entire browser still freezes up, even without running the code again.

**Comment by ojeytonwilliams** [comment] 2019-11-27 00:53
This one's on me: #37621. The preview doesn't time out until 5 seconds have passed, so there's enough time for the array to grow out of control.  To compare, try

```js
var ourArray = [];
var i = 0;
while(i < 5) {
  i--;
}
```

This is infinite in time, but not in memory usage.  The challenge (at least on my machine) just reports `timeout` and does not crash.

It's hard to create a perfect solution, since we still want the user's code to be able to run for a while, just not long enough that common mistakes will crash the browser.  I'll try a shorter duration, but we might need to tune the number in future.

**Comment by raisedadead** [comment] 2019-11-27 17:57
Hold on, is this happening after Oliver's console logging pull-request (merged last week) or is this from our platform launch earlier in mid October?

If later (reading the OP), we are probably looking in the wrong place?

I can see our [loop-protect](https://github.com/jsbin/loop-protect) based protection is implemented here: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/cd5131b07c42cc80350cabff37c9873d0944be64/client/src/templates/Challenges/rechallenge/transformers.js#L25-L26

Is this working correctly?

**Comment by ojeytonwilliams** [comment] 2019-11-27 18:08
My PR created the problem. It made the users code execute every time they changed something.  It also used a 5 second timeout (same as the tests) which was plenty of time to create memory leaks and crash Chrome.

The silver lining is that the tests were already crashing the browser (before my PR landed), but we didn't know.  Now we know this is happening and https://github.com/freeCodeCamp/freeCodeCamp/pull/37841 should mitigate that somewhat.  In that PR code like Randell's will fail immediately and tell the user where the problem is.

> https://github.com/freeCodeCamp/freeCodeCamp/blob/cd5131b07c42cc80350cabff37c9873d0944be64/client/src/templates/Challenges/rechallenge/transformers.js#L25-L26
> 
> Is this working correctly?

Yep, but it wasn't being applied to js challenges, only jsx.

**Comment by raisedadead** [comment] 2019-11-27 18:14
> The silver lining is that the tests were already crashing the browser (before my PR landed), but we didn't know.

Thanks for clarifying.

**Closed** 2019-12-20 13:58 UTC
Labels: scope: curriculum, type: bug
