### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by anthkris** [FreeCodeCamp/freecodecamp#708] opened 2015-05-28 17:27 UTC
Challenge wouldn't accept border in shorthand; also wouldn't accept border in longhand
![add border around element](https://cloud.githubusercontent.com/assets/10858542/7866412/e2e890e2-0534-11e5-97fe-99eb3252721e.PNG)

**Comment by matejhegedus** [comment] 2015-05-28 20:34
This is a duplicate of #704.

**Comment by QuincyLarson** [comment] 2015-05-31 21:15
Thanks for pointing this out, @anthkris. We've now fixed this.

**Closed by QuincyLarson** 2015-05-31 21:15 UTC
