### ISSUE TITLE
Broken link for json.org

### ISSUE THREAD

**Issue by dmatt** [FreeCodeCamp/FreeCodeCamp#9767] opened 2016-07-17 20:30 UTC
#### Manipulating Complex Objects

https://www.freecodecamp.com/challenges/manipulating-complex-objects#

#### Issue Description

The link to json.org is broken. 

https://json.org/ does not work.
Should be http://www.json.org/.

**Comment by alayek** [comment] 2016-07-17 20:32
@dmatt thanks for reporting this.

**Comment by BKinahan** [comment] 2016-07-17 20:37
@alayek This is actually a duplicate of #9704, which has already been addressed.

**Comment by alayek** [comment] 2016-07-17 20:40
Ok, my bad. @dmatt as @BKinahan said, it has already been fixed in #9710. Once we merge `staging` to `master` and deploy, it would be on the live site.

Closing this issue. Happy coding!

**Closed by alayek** 2016-07-17 20:40 UTC
Labels: bug, first-timers-only, help wanted
