### ISSUE TITLE
Regular Expressions: Restrict Possible Usernames - Test not working

### ISSUE THREAD

**Issue by Arronk** [freeCodeCamp/freeCodeCamp#17772] opened 2018-06-30 13:37 UTC
#### Describe your problem and - if possible - how to reproduce it

You can cheat this exercise by simply entering /../gi as all the "should match" tests have even digits and all the "should not match" tests are odd. I suggest this is updated so people like myself can not game the system.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

#### Tell us about your browser and operating system

Using Chrome on Windows 10 - Don't think this will make a difference to the issue though

#### If possible, add a screenshot here

I don't think it requires one the problem is pretty self explanatory.

**Comment by Ashish34** [comment] 2018-11-08 08:57
The answer that work for is this:-
let username = "JackOfAllTrades";
let userCheck = /\w\D/; // Change this line
let result = userCheck.test(username);

**Comment by bikingbadger** [comment] 2018-12-11 13:41
Duplicate of #17733

**Comment by moT01** [comment] 2018-12-11 13:50
Closing in favor of the duplicate mentioned

**Closed by moT01** 2018-12-11 13:50 UTC

**Comment by aligaber** [comment] 2019-03-07 08:32
this answer works well:
let userCheck = /^[^0-9][^0-9]\w./; // Change this line

**Comment by RandellDawson** [comment] 2019-03-07 16:10
@aligaber Please do not post comments which are not related to the issue.

**Comment by Abhi9935** [comment] 2019-05-09 20:16
```
let username = "JackOfAllTrades";
let userCheck = /^[A-Za-z]+[A-Za-z]+[0-9]*$/; // Change this line
let result = userCheck.test(username);
```
it works
