### ISSUE TITLE
It doesnt read that ive completed the task, its not submitting even though its correct

### ISSUE THREAD

**Issue by Prathyum** [FreeCodeCamp/FreeCodeCamp#10123] opened 2016-08-07 12:56 UTC
It doesnt read that ive completed the task, its not submitting even though its correct

#### Challenge Name
[https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-element](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%3Cp%3Ehrer%20%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E%3C%2Fp%3E%0A%20%20%3E)

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Win 10 Pro
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<p> Yo <a href='http://freecatphotoapp.com'> cat photos </a> click this </p>
  >
 
```

**Comment by BKinahan** [comment] 2016-08-07 13:24
The code you have shared in the link above seems to pass all the tests. Have you tried refreshing the page and submitting the code again? Are you having some other issue?

**Comment by Prathyum** [comment] 2016-08-07 13:27
That's my concern, everything's fine but it doesn't submit.

**Comment by erictleung** [comment] 2016-08-08 17:03
@Prathyum can you clarify more on the issue you're having? Are all of the tests checked with green when you click on the Submit button? What happens when you click on the submit button? Are any of the tests not checked green? I'm unable to reproduce your issue as your code appears to pass all the tests for me as well.

**Comment by FCCMrJokee** [comment] 2016-08-08 17:08
I am having the same issue as Parthyum is having. When I run tests, the "You need an a element that links to http://freecatphotoapp.com" fails. Even though I have <a herf="http://freecatphotoapp.com"> cat photos</a> in it, already checked as correct in the help channel.

I tried resetting, twice, refreshing, twice, resetting after refreshing. And nothing.

**Comment by Prathyum** [comment] 2016-08-08 17:11
Exactly the problem, the code is correct but the boxes don't become green.

**Comment by FCCMrJokee** [comment] 2016-08-08 17:22
Prathyum check your spelling. My error was that my tag reads a herf, instead of a href. Once I fixed it, it worked.

**Comment by Prathyum** [comment] 2016-08-08 17:26
Oh wow, damn.
Thank you.

**Comment by qmikew1** [comment] 2016-08-08 17:45
@FCCMrJokee your issue was easily caught as part of the test explicitly looks for href (attr(\"href\")) - But @Prathyum 's was also, problematic (and now solved which is great) with an extra p tag with some text and an errant ```>```
ex: 
```
<p>hrer <a href="http://freecatphotoapp.com">cat photos</a></p>
  >
```
His code also passed for me with all green checks. Though I'm wondering (don't know if it's worth it to open another issue but @erictleung , @BKinahan) if tests should be passing with errant things like closing/opening tags/braces/parenthesis what have you. Thoughts?

**Comment by raisedadead** [comment] 2016-08-09 14:12
@qmikew1 we could add more tests or add checks to existing ones, but it's virtually impossible to add checks for thousands of combination for tags completion and things like in this case, we have linters inbuilt on the editor, that can check this, for instance if you add `< >` then it would be immediately highlighted.

But as seen in this case even that fails, because its interpreted as plain text `<`, i.e lesser than symbol.
Then are cases where sometimes garbage whitespace characters creep in, if campers work on a text editor of their choice and copy paste it on the codemirror editor that we use.

They lead to tons of similar issues like this, IMHO it's not worthwhile to pursue such checks, considering the fact that these tests currently just ensure that user stories are met and campers get a understanding of the concept.

Remember that the DOM won't throw you an error anyway, the browser may just not render a malformed node (tags, elements) that it couldn't parse, so it's best left as it. 

Yet, I am looking forward to comments from others as well

**Comment by qmikew1** [comment] 2016-08-09 14:38
I was thinking about that, actually, and the intent was 'don't let sloppy code pass' which might be too severe in noob stages. But, it's also true that if people get used to that (stuff just working so long as the user stories or basic tests pass) that can create problems later on. Yes, they get near real time visual feedback from linting in codemirror - but that's probably ignored 60% of time. I actually wasn't thinking dom rendering but secondary checks on static lengths of example code as comparison - but really, way too much overhead vs. gain. So, yeah, I agree @raisedadead

**Comment by bendh** [comment] 2016-08-10 19:51
I had the same issue with a valid <a> tag definition. did not work. embedded in a <p> tag did not work eater. It finally worked when adding the tag to a existing <p> tag

**Comment by raisedadead** [comment] 2016-08-10 20:11
Closing as we will not be pursuing further checks, as discussed. Please feel free to continue the conversation though. Happy Coding!

**Closed by raisedadead** 2016-08-10 20:11 UTC

**Comment by myCODERjourney** [comment] 2016-10-07 05:47
I have the same issue, and it is driving me nuts!

**Comment by kitapsiz** [comment] 2016-10-26 20:34
This page has error and did not occur by novicer/me. And no one knows this step how to pass to next one.
