### ISSUE TITLE
False positive on Cafe Menu Steps 88 and 90

### ISSUE THREAD

**Issue by avelican** [freeCodeCamp/freeCodeCamp#52182] opened 2023-10-30 21:46 UTC
### Describe the Issue

False positive on Cafe Menu steps 88 and 90
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-88
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-90
(and possibly others?)
This code passes, i.e. without the >
```
<img src="https://cdn.freecodecamp.org/curriculum/css-cafe/coffee.jpg" alt="coffee icon"
```
```
<img alt="pie icon" src="https://cdn.freecodecamp.org/curriculum/css-cafe/pie.jpg"
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-90

### Your code

```
<img alt="pie icon" src="https://cdn.freecodecamp.org/curriculum/css-cafe/pie.jpg"
```

### Expected behavior

Tests should fail

### System

- Device: Laptop
- OS: Windows 10
- Browser: Brave
- Version: 1.59.124 (Chromium 118.0.5993.117)

**Comment by bbsmooth** [comment] 2023-10-30 22:52
This is most likely passing because the browser is automatically fixing the HTML behind the scenes (i.e. the browser is adding the closing angle bracket). Seems like we might have to add a regex check to the tests if we want to enforce this.

**Comment by ieahleen** [comment] 2023-10-31 09:29
Considering it's the second practice project, it's early enough that probably we still want to enforce good practices and good syntax (I would say up to the first final project is a good rule of thumb)

**Comment by hardyal-singh** [comment] 2023-11-02 10:29
bro ,it's working ...

**Comment by ieahleen** [comment] 2023-11-03 08:12
@hardyal-singh nothing has been changed so the issue is still present

**Comment by naomi-lgbt** [comment] 2024-01-10 01:08
I think that testing every occurrence of malformed HTML that browsers can "fix" is going to be a very large task.

In my opinion, we should stick to testing the specific syntax when the challenge asks for it, rather than testing every time the camper creates an element.

**Comment by naomi-lgbt** [comment] 2024-04-26 06:44
Going to go ahead and close this. We've already got an overabundance of regex tests in the new curriculum.

**Closed by naomi-lgbt** 2024-04-26 06:44 UTC
Labels: type: bug, status: discussing, scope: curriculum
