### ISSUE TITLE
Indicating why several translations missing in the Spanish pages

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#10555] opened 2016-09-09 09:29 UTC
Just to confirm that there are numerous translations that are missing in the Spanish translation. I think a message asking for help for translation or any indication of why some of them are not still completed should be considered?

**Comment by evaristoc** [comment] 2016-09-09 09:30
Well done, varCI-bot!

**Comment by erictleung** [comment] 2016-09-09 13:40
@evaristoc duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9697. Closing in favor of that issue. Thanks!

**Closed by erictleung** 2016-09-09 13:40 UTC
Labels: question
