### ISSUE TITLE
Create Bootstrap Row (84)

### ISSUE THREAD

**Issue by mobiproducts** [FreeCodeCamp/FreeCodeCamp#9178] opened 2016-06-16 15:36 UTC
Challenge [Create a Bootstrap Row](https://www.freecodecamp.com/challenges/create-a-bootstrap-row#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%0A%20%20%3C%2Fh3%3E%0A%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground
  </h3>

  <div class="row">
    
  </div>
</div


```

**Comment by mobiproducts** [comment] 2016-06-16 15:37
Error when Run Test: Make sure your div element has a closing tag.

**Comment by erictleung** [comment] 2016-06-16 15:40
@mobiproducts your code is incorrect. Check your code for closing tags and make sure they are truly closed. If you are still stuck with the challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Closed by erictleung** 2016-06-16 15:40 UTC

**Comment by GurdyWef** [comment] 2016-06-25 09:45
same problem here....

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="well col-xs-6"></div>
  
    <div class="well col-xs-6"></div>
 
  </div>
</div>

**Comment by 003lions** [comment] 2016-12-07 20:30
The problem is looking for this:
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
      </div>    </div>
  </div>
</div>
