### ISSUE TITLE
Show the Local Weather - getCurrentPosition not working over http

### ISSUE THREAD

**Issue by pedrosaisse** [FreeCodeCamp/FreeCodeCamp#9145] opened 2016-06-15 01:52 UTC
#### Challenge Name
Show the Local Weather

https://www.freecodecamp.com/challenges/show-the-local-weather

#### Issue Description

getCurrentPosition does not work over http. I think that changing the url to codepen.io in that particular challenge would help others campers not thinking their code isn't correct.

#### Browser Information

* Browser Name, Version: Chrome 51.0.2704.84 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/507366/16065574/6c4c6126-3282-11e6-94cf-4396a1040fcd.png)

**Comment by DealPete** [comment] 2016-06-15 15:53
You're right, that message is little confusing. Usually you label something as "deprecated" to communicate to your users that it still works, but may be removed in the future. Here these two functions just don't work over http. However, I expect anyone reading this message will figure out themselves to change their url to "https".

**Comment by raisedadead** [comment] 2016-06-16 12:58
>  I think that changing the url to codepen.io in that particular challenge would help others campers not thinking their code isn't correct.

The pen in the challenge uses a resource that itself is served over http. Hence the URL to the challenge is kept as http.

Although it would be great if someone can point to http resource. Or an alternate pen that does the job.

**Comment by stricknein** [comment] 2016-06-16 17:06
Google will not allow you to get geo location anymore over http. And unfortunately the free version of the suggested API to use (Openweathermap) cannot use https unless you pay for it. Instead I would suggest bypassing google altogether to get geolocation and use **http://ip-api.com/json** to get the information you need based off the IP address.

**Comment by raisedadead** [comment] 2016-06-17 11:23
@stricknein that is precisely the resource that is used in the pen

**Comment by stricknein** [comment] 2016-06-17 16:21
@raisedadead Ok? Point is people are trying to complete the challenge going off what they were taught prior to the challenge and they will not be able to unless the pay for open weather map and know that the issue is from using http and not https. Some one with some time on their hands should add that as a note on the challenge in order to ease people's frustration. I was just pointing out another API that would work with OWM. That was the only one out of several that I tried that was free and got the job done.

**Comment by sthodup1** [comment] 2016-06-20 17:36
@stricknein There are some other weather APIs available, but they seem to have the same http issue. I think an easy fix to this issue would be to tell people not to use Chrome just for this challenge. Otherwise, is there some API provider that could donate resources to FreeCodeCamp?

**Comment by stricknein** [comment] 2016-06-20 17:41
As I said earlier just use the one I mentioned. Free and works well. No
need to worry if that is the one used in the example project. Obviously
right your own implementation.

**Comment by pedrosaisse** [comment] 2016-06-20 17:46
As @sthodup1 said, to complete this challenge, avoid Chrome. I used Firefox and set the urls to http and everything was fine for now.

**Comment by stricknein** [comment] 2016-06-20 17:51
I'm not installing Mozilla just to complete a challenge and many others
will not either. Good thing the API I linked will work as well. I'm not
sure why you guys are making a big deal out of nothing.

**Comment by pedrosaisse** [comment] 2016-06-20 17:57
I know this isn't the best solution. And in my opinion you won't be installing just to complete a challenge but as a frontend developer you have to be sure that your code will work exactly the same in all the major browsers.

**Comment by sthodup1** [comment] 2016-06-20 18:01
If you're using OS X/Windows, you should have Safari/IE available. I agree that the ip-based geolocation is a good solution for people that want to use Chrome.

**Comment by stricknein** [comment] 2016-06-20 18:04
Right... Which mine does... Like I said not sure why you guys are so
against using that API. Works well for on browsers and gets the job done
for free. No need to try and make it more complicated then it needs to be.
I mean technically your guys approach will only work for Mozilla. Meanwhile
everyone with chrome will not be able to use your app. And with cross
browser compatabilty being important to web developers I don't see how how
can say just use Mozilla as an answer. Pretty hypocritical statement
considering your suggestion.

**Comment by RayBB** [comment] 2016-06-25 00:04
I have found another weather api that is free and works over https.
[https://developer.forecast.io/docs/v2](https://developer.forecast.io/docs/v2)
I found it after doing some research but have no idea how reputable the website is. However, the api seems to work well.

In my opinion, it would be better to encourage campers to use the geolocation tools over https and then a secure api rather than having them use a workaround (the ip lookup api).

**Comment by raisedadead** [comment] 2016-06-25 07:17
@RayBB thanks a lot for finding these for us. 

Just in case if you have been able to use them in a project, we could quickly fork that and replace the existing one.

Let us know!

**Comment by RayBB** [comment] 2016-06-25 15:01
@raisedadead I managed to make a simple working example.
https://codepen.io/RayBB/full/ZOQpoN/

**Comment by dhcodes** [comment] 2016-06-28 12:27
As discussed in #9079, forecast.io (Dark Sky) doesn't have city/country in the API, which limits some appeal by showing the user where it's pulling weather from. Also, I'm getting a 500 error on your example @RayBB. 

So far, the workaround I've found to work best is to prepend: `https://crossorigin.me/` to the openweather API as shown in this quickly thrown together: https://codepen.io/dhcodes/pen/RRaGjG?editors=1111

**Comment by dhcodes** [comment] 2016-06-28 12:50
Disregard what I just said as I see in another open issue that FCC won't recommend using `https://crossorigin.me/` so maybe forecast.io is the only option. As mentioned, forecast.io does lack a city record so the best users could get is a timezone unless they want to use the Google geocoder API too. Here's a quick example I made with forecast.io: https://codepen.io/dhcodes/pen/GqWEaQ

Note that users will also need to add `?callback=?` to the end of the URL (similar to the wikipedia project) in order to avoid a 'Access-Control-Allow-Origin' header error.

**Comment by LuisGonzaga** [comment] 2016-07-27 23:28
Hi, just finished the code (will now start the design), the solution was easy enough, https://www.wunderground.com API, it's free (but requires registration to get the API Key ... 500 free connections a day if I remember well) and it's easy to get the weather conditions using coordinates using this address (but I didn't it on their instructions):
https://api.wunderground.com/api/YOUR_KEY_HERE/conditions/q/38.72187429,-9.2286898.json
... and I'll have to include their logo too with very precise instructions for doing it.
Best regards,

**Comment by atjonathan** [comment] 2016-10-11 19:03
@raisedadead, update on this in regards to updating codepen?
I have merged in #10341 😃

**Closed** 2016-10-11 19:35 UTC
Labels: codepen, help wanted, QA

**Comment by jaketripp** [comment] 2017-05-18 04:13
For any of my friends having trouble with this:

I was using the IP api and using openweathermap.org, and when i ran it locally as a file saved on my computer it worked fine, when i tried to run it off of codepen, it threw errors at me. 

Mixed Content: The page at 'https://codepen.io/jaketripp/full/gWdKXz/' was loaded over HTTPS, but requested an insecure script 'http://ip-api.com/json/?callback=blah blah blah'. This request has been blocked; the content must be served over HTTPS.

Guess what worked? I went up to the url bar of my codepen and MANUALLY REMOVED THE S from the url. Now it works. go figure. good enough for me.
