### ISSUE TITLE
Instructions !== tests

### ISSUE THREAD

**Issue by OFFLlNE** [FreeCodeCamp/FreeCodeCamp#12201] opened 2016-12-24 15:17 UTC
Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%0Afunction%20isPrime(acc)%20%7B%0A%20%20%20%20if(acc%20%3C%202)%20return%20false%3B%0A%20%20%20%20for%20(var%20i%20%3D%202%3B%20i%20%3C%20acc%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if(acc%20%25%20i%20%3D%3D%3D0)%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20true%3B%0A%7D%0A%0Afunction%20sumPrimes(num)%20%7B%0A%20%20sum%20%3D%200%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20num%3B%20i%2B%2B)%7B%0A%20%20%20%20if(isPrime(i))%7B%0A%20%20%20%20%20%20sum%2B%3D%20i%3B%0A%20%20%20%20%7D%20%0A%20%20%7D%0A%20%20return%20sum%3B%0A%7D%0A%0A%0AsumPrimes(977)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isPrime(acc) {
    if(acc < 2) return false;
    for (var i = 2; i < acc; i++) {
        if(acc % i ===0)
            return false;
    }
    return true;
}

function sumPrimes(num) {
  sum = 0;
  for(var i = 0; i < num; i++){
    if(isPrime(i)){
      sum+= i;
    } 
  }
  return sum;
}


sumPrimes(977);

```

Inside the instructions it is written `The provided number may not be a prime.` But [977](https://en.wikipedia.org/wiki/List_of_prime_numbers) IS a prime number. And since 1 of the tests is based on that it won't pass.
I know how to fix it so it would work with 977, but there needs to be some changes either in the description or tests

**Comment by erictleung** [comment] 2016-12-24 17:15
@OFFLlNE thanks for the issue. The wording is meant to suggest the *possibility* (`"..number may..."`) of the number *not* being prime. This does not mean the number cannot be a prime number. It would be different if the challenge more directly said `The provided number will not be prime`. I hope that make sense. Closing as not a bug issue. Happy coding!

**Closed by erictleung** 2016-12-24 17:15 UTC
