### ISSUE TITLE
Different behavior between chromium and firefox

### ISSUE THREAD

**Issue by 3vbo** [freeCodeCamp/freeCodeCamp#14834] opened 2017-05-12 05:39 UTC
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This challenge on the beta was tested on both Chromium 58.0.3029.110 and Firefox 53.0.2. On Chromium it submits successfully. On Firefox it does not, claiming that "Your h2 element should be blue."

```html

<style>
  h2 {color: blue;}
</style>

<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by ooade** [comment] 2017-05-16 18:05
@raisedadead I tried working on this but didn't work out fine. I don't know if you've tried tested css properties using the jQuery `.css()` method before because it keeps returning `undefined` on firefox.

**Comment by etasi** [comment] 2017-05-19 13:40
I can confirm the test does not pass in Firefox.

**Comment by Monochrome19** [comment] 2017-05-21 19:55
Just tried using firefox, and it didn't work.

**Comment by systimotic** [comment] 2017-05-27 09:25
Hi everyone! Thanks for reporting and looking into this issue.

We're aware that CSS tests are broken in Firefox. For more info, please take a look at #10749

I'm closing this as a duplicate. Happy coding!

**Closed by systimotic** 2017-05-27 09:25 UTC
Labels: beta, bug, firefox, help wanted
