### ISSUE TITLE
[beta] Completed challenges don't display proper data on profile page

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9970] opened 2016-07-29 10:54 UTC
[![https://gyazo.com/34f611dc15cbf4f756b835338504e63f](https://i.gyazo.com/34f611dc15cbf4f756b835338504e63f.png)](https://gyazo.com/34f611dc15cbf4f756b835338504e63f)

**Comment by SamAI-Software** [comment] 2016-07-29 11:07
ref #9954

**Comment by raisedadead** [comment] 2016-07-29 11:19
Closing as duplicate of the former.

**Closed by raisedadead** 2016-07-29 11:19 UTC
Labels: beta
