### ISSUE TITLE
Browser hanging while editing code.

### ISSUE THREAD

**Issue by robjloranger** [FreeCodeCamp/FreeCodeCamp#1981] opened 2015-08-18 02:24 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. 

When trying to edit the code to update the slot boxes with appropriate values the browser will crash when trying to run the code half complete.

**Comment by jbmartinez** [comment] 2015-08-18 02:51
Duplicate of #1960

**Closed** 2015-08-25 16:29 UTC
