### ISSUE TITLE
Clicking on help does nothing

### ISSUE THREAD

**Issue by raintan** [FreeCodeCamp/FreeCodeCamp#2455] opened 2015-08-21 20:31 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-where-art-thou has an issue. 

When I click on the help button, the popup displays asking if I want to go to the help room. When I click on the help room button, the popup closes and I'm back where I started.

**Comment by benschenker** [comment] 2015-08-21 21:11
Thank you for posting this!

Confirmed that the help button on the help modal does not actually open the gitter help room.  The HTML for the button looks like:
```
<a href="https://gitter.im/FreeCodeCamp/help" data-dismiss="modal" aria-hidden="true" target="_blank" class="btn btn-lg btn-primary btn-block">Take me to the help room</a>
```
If I remove the `data-dismiss="modal"` from the element it loads the help page in a new tab as it should (but it doesn't close the modal).

The help chat room is: https://gitter.im/FreeCodeCamp/Help

**Comment by BerkeleyTrue** [comment] 2015-08-21 22:00
Closing as duplicate #2445

**Closed by BerkeleyTrue** 2015-08-21 22:00 UTC
