### ISSUE TITLE
ditch-custom-css-for-bootstrap btn-danger text not in center

### ISSUE THREAD

**Issue by saimon494** [FreeCodeCamp/FreeCodeCamp#7172] opened 2016-02-21 11:31 UTC
I`ve noticed that [ditch-custom-css-for-bootstrap](http://www.freecodecamp.com/challenges/ditch-custom-css-for-bootstrap) challenge has a small bug. 
Text in "danger button" is not in center. I reboot the page and my browser, but it does not help.

Goole Chrome 48.0.2564.116 m, Windows 7 x64.
(Is there any command to write info about browser and OS? I use search, but can not find.)

My Code:

```js
 <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary">Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
```
![1](https://cloud.githubusercontent.com/assets/17360765/13202156/e58343c0-d8a0-11e5-8566-bd10adc921e4.JPG)

**Comment by ltegman** [comment] 2016-02-24 05:04
It's a slightly different symptom when the icon isn't there yet, but ultimately this is a duplicate of #2802. Thanks and happy coding!

**Closed by ltegman** 2016-02-24 05:04 UTC
