### ISSUE TITLE
Local Scope and Functions (Bug)

### ISSUE THREAD

**Issue by mathfreak1129** [FreeCodeCamp/FreeCodeCamp#7843] opened 2016-04-01 07:04 UTC
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20'use%20strict'%3B%0A%20%0A%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%20var%20myVar%3D%22Hieu%22%3B%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%2F%2Fconsole.log(myVar)%3B%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am stuck I did the following and still stuck on the page
My code:
```javascript
function myFunction() {
  'use strict';
 

  
  console.log(myVar);
}
myFunction();
 var myVar="Hieu";
// run and check the console 
// myVar is not defined outside of myFunction
//console.log(myVar);

// now remove the console log line to pass the test


```

**Comment by kalunlee136** [comment] 2016-04-01 07:18
@mathfreak1129 so what's the bug?

**Comment by BKinahan** [comment] 2016-04-01 10:27
Probable duplicate of #6259

**Comment by raisedadead** [comment] 2016-04-01 10:31
Thanks @BKinahan 

@mathfreak1129 Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
before reporting a issue and refer #6259

**Closed by raisedadead** 2016-04-01 10:31 UTC

**Comment by huysh3** [comment] 2016-04-28 06:45
Just use Safari and try again : )
