### ISSUE TITLE
HTML Waypoint

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2456] opened 2015-08-21 20:37 UTC
Challenge http://freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not 100% sure if its designed like this but it jumps from UL to forms skipping OL challenge...

Also brought to my attention was the fact that there is no way back to your previous challenge (besides browser back button)

-Goran

**Comment by benschenker** [comment] 2015-09-03 04:58
Thanks for posting this @dgoran!

Looks like a duplicate of #2986 which seems to have been fixed.  Please reopen if this issue is still problematic for you

**Closed by benschenker** 2015-09-03 04:58 UTC
