### ISSUE TITLE
Little error?

### ISSUE THREAD

**Issue by s3ned** [FreeCodeCamp/FreeCodeCamp#4715] opened 2015-11-25 18:24 UTC
The explanation says 

If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.

truncate("A-", 1) should return "A...". 

While the original string is less then 3 character, the outcome is less than 3 characters, still the result should be A.... Seems not really logical to me.

**Comment by raisedadead** [comment] 2015-11-25 18:26
Duplicate of #4706

**Comment by ltegman** [comment] 2015-11-25 18:28
Yes, please continue conversation in #4706

**Closed by ltegman** 2015-11-25 18:28 UTC
