### ISSUE TITLE
Wrap Radio Buttons in a Fieldset Element for Better Accessibility(JavaScript raw code is showing)

### ISSUE THREAD

**Issue by RoniqueRicketts** [freeCodeCamp/freeCodeCamp#13004] opened 2017-01-31 14:34 UTC
#### Challenge Name

Wrap Radio Buttons in a Fieldset Element for Better Accessibility

#### Issue Description

The raw JavaScript code is showing in the output field on this challenge. I have taken a screenshot of this issues.

#### Browser Information

* Browser Name, Version: Google Chrome V56.0.2924.76
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

![backend capture](https://cloud.githubusercontent.com/assets/17409035/22468987/7295a42c-e798-11e6-889e-3411be994995.jpg)

**Comment by raisedadead** [comment] 2017-01-31 15:59
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12683

@RoniqueRicketts Thanks a lot for the QA and feedback on beta site. At the same time just a request if you can check for open issues before reporting.

**Closed by raisedadead** 2017-01-31 15:59 UTC
