### ISSUE TITLE
Challenge (Check Radio Buttons and Checkboxes by Default): Device issue

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45216] opened 2022-02-22 22:30 UTC
The last two tests for the label text are incorrectly failing.

Looks like some kind of device issue (with iPads) and this challenge. Not sure what the problem is. I tried on lambdatest with an iPad pro in Safari and it worked. Can't really test it much though.

If someone with a device that is failing the two tests can look at this and figure it out maybe it can be fixed.

Challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/check-radio-buttons-and-checkboxes-by-default

Some iPad users
https://forum.freecodecamp.org/t/checked-by-default-button-checkbox-ide-errors/497694
https://forum.freecodecamp.org/t/buttons-ticked-by-default-not-working/498151

**Comment by ieahleen** [comment] 2022-02-23 12:22
on my iPad it works 🤷

**Comment by lasjorg** [comment] 2022-02-23 15:56
As I said, it worked for me as well with the one test I did. But I do not have access to good cross-browser testing. Does the dev team have access to something like BrowserStack or LambdaTest?

The two user agents from the forum are:

```
Mozilla/5.0 (X11; CrOS x86_64 12239.92.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.136 Safari/537.36

Mozilla/5.0 (iPad; CPU OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
```

**Comment by raisedadead** [comment] 2022-02-24 06:19
We have access to BrowserStack. I remember asking someone in @freeCodeCamp/dev-team to get it integrated before our free access expired. Anyways, should you be interested in helping us out, I can totally send an invite your way.

**Comment by nhcarrigan** [comment] 2022-02-24 13:21
@lasjorg I think you were correct and it's the optional chaining.

Checking both of those forum posts, the useragent values are for browser versions pre-2020 and do not have support for optional chaining.

**Comment by lasjorg** [comment] 2022-02-24 14:54
@nhcarrigan I thought so too, but the thing is I made a Codepen for one of the users with optional chaining and they said it worked for them. But maybe the code is babel transpiled differently by Codepen than by us?

Doesn't babel @babel/preset-env with our settings transpile optional chaining into ternaries? [Babel online](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBCBGArGBeGBvAUDGAzEIAXBtjjPAIYBOxWZZlAXsQCwBMANKTgL5e9ceAbkyZQkWE1RwkAfgB0-EAspUVFRkJgB6bTHaYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D) (I might have gotten the settings wrong?)

Or maybe I just don't understand how the test code runs in the browser.

**Comment by moT01** [comment] 2022-02-24 15:43
I gave this some quick testing...

Works on 
Safari 13.1.2 + OSX 10.13.6 (macbook)
Safari 15.2.1 + IOS 15.2.1 (iphone)

Not working
Safari 12.4.5 + IOS 12.4.5 (iPad)

I couldn't narrow down why it's not working. I can dig a little deeper at some point - I may not be able to figure out the problem, but I can probably at least find an alternative way to write the tests that will pass - hopefully.

**Comment by nhcarrigan** [comment] 2022-02-24 15:45
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/63889819/155557667-c106f0d6-39c8-432b-b3ce-26dcd69ab4b2.png">

Those versions line up with the optional chaining support.

> Doesn't babel @babel/preset-env with our settings transpile optional chaining into ternaries?

Yes but the tests aren't actually transpiled - my understanding is they're basically `eval`ed.

**Comment by lasjorg** [comment] 2022-02-24 16:02
> Yes but the tests aren't actually transpiled - my understanding is they're basically `eval`ed.

I see, well that makes more sense then. For some reason, I thought the code got transpiled first.

---

I'm guessing this isn't the only place optional chaining is used so maybe fixing this is a bit of a lost cause?

**Comment by moT01** [comment] 2022-02-24 16:04
Yea, I tried a few other challenges with the optional chaining quick and they fail too. So that seems to be the cause. A quick search shows quite a few tests that use it:
![Screen Shot 2022-02-24 at 9 59 40 AM](https://user-images.githubusercontent.com/20648924/155560981-a05dea61-e98b-4a87-bd25-516e25005951.png)
4276 results in the english files - most of them appear to be optional chaining, some are in regex though

**Comment by nhcarrigan** [comment] 2022-02-24 16:09
Yeah we rely heavily on optional chaining to ensure that the browser console isn't flooded with "cannot read property X of undefined" errors.

That being said, browser support for this is almost universal as of early 2020 - IMHO it's unrealistic to restrict our tests for the sake of supporting versions that are two years old.

**Comment by ojeytonwilliams** [comment] 2022-02-24 17:15
The only thing that comes to mind is we could run the tests themselves through Babel when we're building the preview/test iframes.

We already pipe the user's code through Babel, so I don't see an in-principle reason not to do this with the tests.

**Comment by ARMEL250** [comment] 2022-03-13 17:50
fail testing

**Comment by moT01** [comment] 2022-08-17 14:30
Closing as wont fix.

**Closed by moT01** 2022-08-17 14:30 UTC
Labels: type: bug, status: wontfix, scope: curriculum, other: device specific
