### ISSUE TITLE
oops! something went wrong please try again later

### ISSUE THREAD

**Issue by asmteja** [FreeCodeCamp/FreeCodeCamp#6960] opened 2016-02-13 09:24 UTC
@BerkeleyTrue can you do something to sort out this issue .. Thanks in advance

**Comment by VillniProtes** [comment] 2016-02-13 10:33
I got the same issue

**Comment by jslirola** [comment] 2016-02-13 10:54
Me too.

**Comment by iwanjunaid** [comment] 2016-02-13 12:54
i am having the same issue

**Comment by anabol322** [comment] 2016-02-13 13:29
Same thing happening

**Comment by snhmlt** [comment] 2016-02-13 13:34
Same thing. I'm using Oauth to sign in using GitHub.

**Comment by benninkcorien** [comment] 2016-02-13 14:56
Same problem.

**Comment by BerkeleyTrue** [comment] 2016-02-13 15:34
Thanks for reporting. Can y'all give details on what you where doing when this error occurred? So far I see one person was trying to sign in.

**Comment by jamigibbs** [comment] 2016-02-13 15:36
I can only seem to reproduce it in the map view:

<img width="788" alt="screen shot 2016-02-13 at 9 36 01 am" src="https://cloud.githubusercontent.com/assets/872479/13028460/46e3f88e-d235-11e5-934c-d24f10b1dbeb.png">

**Comment by BerkeleyTrue** [comment] 2016-02-13 15:38
@jamigibbs When the server errors, this is the page you are redirect to. What were you doing beforehand?

**Comment by snhmlt** [comment] 2016-02-13 15:38
I can reproduce it like @jamigibbs. The "Oops!..." error occurs after trying to click on a challenge in the map view. Or after completing a challenge and having it try to load the next one.

**Comment by jamigibbs** [comment] 2016-02-13 15:39
I'm logged in using Github. Simply navigating to "Map" from the navigation results in that error.

**Comment by bogomazon** [comment] 2016-02-13 15:39
When I complete a challenge it shows the same error as @jamigibbs  in "Map". 
I'm logged in using Github as well.

**Comment by bitblitter** [comment] 2016-02-13 15:40
I used my email before, but forgot my password, so I logged in with github. I deleted my previous account but the error persists. Thank you.

**Comment by abhisekp** [comment] 2016-02-13 15:41
@BerkeleyTrue this has been happening since 6 hrs as far as I know...
Just clicking any challenge on the map shows that error. I'm unable to access anything in map.

**Comment by bogomazon** [comment] 2016-02-13 15:42
@abhisekp it's actually possible. But you have to click on challenge like 10 times :)

**Comment by bogomazon** [comment] 2016-02-13 16:04
I think it works now for me. No errors for 20 minutes.

**Comment by jbmartinez** [comment] 2016-02-13 16:07
I got some errors just about 5 minutes ago. It seems a random error. When I click some item on the map, I sometimes get a 302 redirection to the map with the message.

**Comment by BerkeleyTrue** [comment] 2016-02-13 16:11
Apologies, seems there was weird connection issue with the database around 2AM PST, which caused some of the servers a weird state. I've restarted the servers.

**Comment by bogomazon** [comment] 2016-02-13 16:14
@BerkeleyTrue thank you!

**Comment by BerkeleyTrue** [comment] 2016-02-13 16:15
@jbmartinez You may have been trying while I was restarting the servers

**Comment by jbmartinez** [comment] 2016-02-13 16:16
Yep, working now. Thank you @BerkeleyTrue

**Comment by BerkeleyTrue** [comment] 2016-02-13 16:17
Closing as resolved.

Happy Coding!

**Comment by snhmlt** [comment] 2016-02-13 16:22
@BerkeleyTrue Thank you!

**Comment by co083121** [comment] 2016-02-14 08:08
I'm experiencing this problem as well, I tried to leave github open but it continues to act like this.
Why does this seem to affect everybody and yet it can't be fixed all at one time? Please help.

**Comment by QuincyLarson** [comment] 2016-02-14 08:37
@co083121 Please confirm - are you still having this issue?

**Comment by co083121** [comment] 2016-02-14 09:47
i'm still having the problem, it doesn't happen so often anymore. at first it was happening
almost every time that i tried to click on the map button or go onto a challenge. now, it
works more often than it messes up. but it's not completely fixed yet.

**Comment by benninkcorien** [comment] 2016-02-14 11:01
I still have this issue. I think this is the same one too https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6958

**Comment by Skaddicted** [comment] 2016-02-14 11:09
I'm having the same problem, but it appears just randomly.

**Comment by FrancoisDemilly** [comment] 2016-02-14 14:28
Hello, I am having the same problem, I cant ' go through the next challenge... Thanks

**Comment by FrancoisDemilly** [comment] 2016-02-14 14:30
erratum, I can go through the next challenge.

**Comment by hallaathrad** [comment] 2016-02-14 14:33
We are working on a fix, everyone. Please bear with us as we figure out what the problem is.

**Closed** 2016-02-14 14:56 UTC

**Comment by allieh84** [comment] 2016-02-17 21:11
I am having trouble moving on with my challenges yesterday and today. It's hit or miss after I press run test. When I do it will tell me there is a problem and I get the same error message as **jamigibbs** who commented commented ~4 days ago. It either spits me out back at map view or I have to go in to map view to see if the test went through or not. Luckily it saves my work so I have not had to start over. Yesterday I could at least navigate though the Map tab to get to my challenges but today even that is going crazy. I can't scroll up or down to get to the next challenge when it crashes!! I tried a hard refresh, and anything I could do on my end but to no avail. Help!!!

**Comment by TBlank72** [comment] 2016-05-09 01:25
experiencing same problems.  This happened for me after clicking "sign up with Github" instead of "sign in with Github" by mistake.

**Comment by heldersepu** [comment] 2016-06-14 22:00
Getting the same here...
This happens after clicking "sign up with Github" instead of "sign in with Github"

**Comment by Jan-Andre** [comment] 2016-10-17 22:45
Hello, I am also  having difficulties signing in  due to renaming accounts, Thanks in advance!

**Comment by nikhiltom** [comment] 2017-01-27 19:11
@BerkeleyTrue I am also having the same problem. Could you help me please. Thanks in advance.

**Comment by pinknoodlehair** [comment] 2017-03-26 14:52
I am having this problem and I am using the beta version so I thought it was that. It doesn't happen every time, I went through the HTML exercises just fine. Once I got to CSS the troubles started to arise. I didn't rename my account but I'm having this problems.

**Comment by GMSyrimis** [comment] 2017-05-03 17:11
Having issues creating pull requests online
