### ISSUE TITLE
target same element with multiple jquery selector: passing function for checkmarks not working when completing tasks appropriately

### ISSUE THREAD

**Issue by JonathanKreiter** [FreeCodeCamp/freecodecamp#1626] opened 2015-08-07 02:10 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. 

Completed task appropriately, though was not able to continue due to code not being recognized properly by the code checking for the right answers. 

in BETA FCC

**Comment by BerkeleyTrue** [comment] 2015-08-11 21:08
closing as duplicate of #1529

**Closed by BerkeleyTrue** 2015-08-11 21:08 UTC
