### ISSUE TITLE
"i" is not defined in the for loop

### ISSUE THREAD

**Issue by najmieh** [freeCodeCamp/freeCodeCamp#39438] opened 2020-08-20 04:45 UTC
** "i" is not defined in the for loop. Also, the underneath comment is wrong. it should say: "return false if it is divisible by any number that is not itself. **

**https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-sum-all-primes/16085**

**Tell us about your browser and operating system:**
* Browser Name: chrome 
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment] 2020-08-20 11:47
Hello there,

Could you please provide more information about what the problem is:
- In which loop is `i` not defined?
- Which _"underneath comment"_ is wrong?

There are a lot of solutions, and hints on the referenced guide post. So, more information would be useful.

**Comment by scoaband** [comment] 2020-08-20 12:00
nested loops

**Comment by najmieh** [comment] 2020-08-20 13:53
Yes, this part. the first for loop
`function sumPrimes(num) {
  // function to check if the number presented is prime
  function isPrime(number) {
    for (i = 2; i <= number; i++) {
      if (number % i === 0 && number != i) {
        // return true if it is divisible by any number that is not itself.
        return false;
      }
    }
    // if it passes the for loops conditions it is a prime
    return true;
  }
  // 1 is not a prime, so return nothing, also stops the recursive calls.
  if (num === 1) {
    return 0;
  }
  // Check if your number is not prime
  if (isPrime(num) === false) {
    // for non primes check the next number down from your maximum number, do not add anything to your answer
    return sumPrimes(num - 1);
  }

  // Check if your number is prime
  if (isPrime(num) === true) {
    // for primes add that number to the next number in the sequence through a recursive call to our sumPrimes function.
    return num + sumPrimes(num - 1);
  }
}
// test here
sumPrimes(10);`

**Comment by Sky020** [comment] 2020-08-20 14:13
Thank you, for reporting this, and providing the extra detail.

I have edited the guide post, to reflect these changes. As such, I am closing this issue.

**Closed by Sky020** 2020-08-20 14:13 UTC
Labels: scope: learn, status: needs help for triage
