### ISSUE TITLE
Reset this lesson doesn't reset on projects

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55354] opened 2024-06-27 14:56 UTC
If I press Reset this lesson on final projects, the saved code is restored instead of the starting code.

Can we have two different buttons?

**Comment by akshithere** [comment] 2024-06-30 12:10
Hey can you please elaborate more? On which page are you requesting this.

**Comment by ilenia-magoni** [comment] 2024-06-30 17:20
On certification projects, all of the ones that are written in the in-browser editor, if you have saved code, and press Reset this lesson, the saved code is restored, instead of the starting code

**Comment by Iteratum** [comment] 2024-07-13 04:39
> On certification projects, all of the ones that are written in the in-browser editor, if you have saved code, and press Reset this lesson, the saved code is restored, instead of the starting code

Can we get a short clip of the issue and a little clue on how to reproduce the error.

**Comment by a2937** [comment] 2024-07-15 15:05
Which part of the curriculum can I reproduce the error in, because in some the projects become completely empty.

**Comment by RaviSadam** [comment] 2024-07-17 06:33
Can I contribute to issues

**Comment by arantebw** [comment] 2024-07-23 17:39
@ilenia-magoni I think this is what you're referring to, right?

https://github.com/user-attachments/assets/3fc93982-a8cf-43b4-8a1e-c5c5a524aac9

I think the expected behavior she's asking for is that upon clicking the `Reset this lesson` button, it will clear out the editor of any code previously saved by the user -- i.e. "starting code".

Currently, the `Reset this lesson` button will restore the last saved code by the user.

https://github.com/user-attachments/assets/dfdc4b7f-d9f8-4f77-af84-1fc783135c23

**Comment by nayelimdejesus** [comment] 2024-07-25 21:36
I can work on this issue.

**Comment by ujjwal502** [comment] 2024-07-28 09:50
@ilenia-magoni So I did some debugging here! I don't think this is an issue but rather a feature request. I agree that "Reset this lesson" should reset even the saved code, but that's not how the current functionality is implemented. Reasons for the above deduction:

1. When you save your code, a POST call is fired with the save-challenge endpoint, which updates the contents of the file in the DB and fetches the updated contents.
2. But when you hit the reset button, no network call is fired to clear the contents and update the DB. In the code (i.e., the editor component), it checks for the isresetting prop (which is true while resetting), finds the initial contents of the file, and updates the editor with that content.
3. However, since the initial content is still the saved code (that we updated through the save-challenge call), it is setting the code as the updated code itself, and hence you are seeing your last saved code.

I think it's intentional, but to give clear expectations to the user, it should be shown in the reset modal like "It will revert/reset to the saved values" or something similar.

If it is not intentional, then a better solution would be to introduce an API call (something like 'reset-challenge') which should reset/empty the content of that particular file and update the DB. With this solution, no change would be required on the client side.

**Comment by ojeytonwilliams** [comment] 2024-07-29 08:13
Thanks for the detailed breakdown @ujjwal502. And, yes, you're correct: it is intentional. When working on lesson it's tricky to reset (you have to know what you're going back to). However, it's trivial when working on a project: just delete everything.

I agree that a UX fix is in order. As well as changing the modal text, I recommend updating the button to say "Revert to saved code", to clarify what is about to happen.

**Comment by ujjwal502** [comment] 2024-07-30 06:56
Agreed! I will raise a PR to update the text

**Comment by Sembauke** [comment] 2024-09-16 10:39
Hey @ojeytonwilliams,

Can we come to a solution that makes it clear for the contributors on what needs to happen? Thanks.

**Comment by ojeytonwilliams** [comment] 2024-09-16 12:00
Sure, I think we need to replace that "Reset this lesson" with "Revert to saved code" on the button and in the modal itself. This should only happen on projects, not normal challenges.

**Closed** 2024-10-08 20:47 UTC
Labels: help wanted, platform: learn
