### ISSUE TITLE
Vertical scroll bar issues in /learn steps and challenges

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#48183] opened 2022-10-21 22:46 UTC
### Describe the Issue

In the steps/challenges there is a vertical scroll bar on the body which is mildly annoying on the desktop layout but rather annoying on the mobile layout since the code editor in the steps and the info panel in the legacy challenges have their own vertical scroll bar and thus you have two vertical scroll bars side by side. This is also causing the tool panel buttons at the bottom of the view port in the mobile layout to be hidden on initial page load.

Additionally, in Chrome-based browsers there is significant extra vertical space created below the tool panel buttons in the mobile layout which, depending on the height of the view port, allows the user to basically scroll the buttons off the top of the screen.

### Affected Page

All steps/challenges

### Steps to Reproduce

Let's use the first basic JS challenge: [Comment Your JavaScript Code](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code)

Please note, I am only testing on Linux/Windows 11/Android as I don't have access to any mac devices at the moment.

**Deskop:**

Using Chrome in desktop layout:
- On page load, notice there is a vertical scroll bar on the body. (It doesn't scroll much.)
- Using the mouse pointer, scroll the info pane down as far as it will go. Notice that you can't read the entire last test.
- Scroll the body down in order to read the rest of the last test.
- Now narrow the browser all the way in and reload the page. (Or you can widen your browser all the way and then zoom in 400%) Notice that there are two vertical scroll bars side by side.
- Using the mouse pointer, scroll the inner bar for the info pane. Notice that the tool panel buttons are still not visible.
- Scroll the outer bar for the body down to bring the tool panel buttons into view. Depending on the height of your view port you will also be able to scroll the buttons above the bottom of the view port. Shorten your view port to simulate a small mobile device (if you are not zoomed in already) if needed to see this.

Using Firefox, the above desktop layout behavior is the same but the mobile layout behavior is slightly different. I am only seeing one vertical scroll bar in the mobile layout, which seems to be the scroll bar for the body (I'm assuming the scroll bar for the info pane is hidden beneath it) and thus I must use my middle mouse scroll button to scroll the info pane. Also, I am not able to scroll the tool panel buttons above the bottom of the view port.

**Mobile Device** (assuming in portrait mode for mobile layout)

On the info panel:

Chrome: You will only see one vertical scroll bar (similar to Firefox above) but otherwise, all of the above scrolling issues are there.

Firefox: Since Firefox adds extra chrome at the bottom of the view port it is covering up the tool panel buttons most of the time on the info panel. I basically have to scroll all the way down to the bottom of the page to see them.

On the code panel:

With both Chrome and Firefox, in order to see the tool panel buttons at the bottom you must swipe up on the tabs or breadcrumb links above the editor. When you do this then the tabs/breadcrumbs disappear off the top of the screen. In order to get them back you must swipe down on the buttons at the bottom. If you are good enough you might be able to scroll just enough either way to have both the tabs and the tool panel buttons showing at the same time. But I think that amount of coordination is probably too much to ask of our users.

### Expected behavior

I'm assuming that we don't want the scroll bar on the body to ever show up since each pane itself can scroll. And I'm assuming that in mobile view the tool panel buttons at the bottom should always be fixed to the bottom of the view port with no scrolling needed to access them. And the breadcrumbs and tab buttons should always be visible at the top with no scrolling needed to access them.

### Screenshots

I can provide screenshots/videos if needed.

### System

Firefox 106 on Win 11/Linux
Chrome 106 on Win 11/Linux
Firefox 106 on Android 9
Chrome 106 on Android 9

### Additional context

This should probably be fixed before we worry about fixing #47597.

**Comment by Jaya-sys** [comment] 2022-10-22 18:13
Hi! can you please this issue to me?

**Comment by jatinmark** [comment] 2022-10-22 20:21
Hello @raisedadead i want to work on this issue can you assign it to me

**Comment by nayabatir1** [comment] 2022-10-22 20:44
Hey, is there any documentation how `.md` files are rendered. Having hard time understanding it.

**Comment by Jagrutiti** [comment] 2022-10-23 14:12
Hey @nayabatir1 

Here is the markdown language syntax: https://www.markdownguide.org/basic-syntax/

If you use Visual Studio Code IDE you can preview your document here: https://code.visualstudio.com/docs/languages/markdown

**Comment by nayabatir1** [comment] 2022-10-23 17:17
@Jagrutiti This is not what I meant. I know how `.md` works. 
What I meant was how `.md` files are rendered on browser with description, instruction and test cases etc.

**Comment by VisShon** [comment] 2022-10-23 20:14
I think its a css related problem for hiding the scroll bar we can limit the page height first and then use ::scrollbar{display:none} to get rid of the scrollbar

**Comment by ojeytonwilliams** [comment] 2022-10-24 07:39
@nayabatir1 it's a little involved, but the short version is they're parsed into JavaScript objects and sourced by Gatsby. Gatsby then uses that data to build the pages.

I don't think that's the right place to look, though.  As @VisShon pointed out, the problem is to do with the page height.  At least one component is too tall meaning the page needs to be scrollable.

**Comment by ojeytonwilliams** [comment] 2022-10-26 14:20
https://github.com/freeCodeCamp/freeCodeCamp/issues/46810 appears to be a duplicate of this

**Comment by mmatsumoto1026** [comment] 2022-10-27 01:12
Hello,

As @SaintPeter (at [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/46810#issuecomment-1179202071)) and @bbsmooth mention, I agree that the vertical bar on the body should be removed as it may confuse users. I think it should, especially in the desktop view.


But, after some coding effort, I noticed that perhaps in mobile view, the vertical scrollbar of `body` provides the following functionality somewhat smoothly while still providing the clean design that @ahmadabdolsaheb shows in [the comments here](https://github.com/freeCodeCamp/freeCodeCamp/issues/47597#issuecomment-1256266759).(I don't know if the functionality is what DevTeam intended)

1. User reads the instructions carefully from top to very bottom in "Info" pane => They couldn't figure out the solution for the challenge => Scrolling down further reveals a tool panel buttons, where users can get tips or ask for help from the "Help" button.

1. User writes long code in the "Code" pane, confirm all the way to the bottom, and then the user tries to run a test or reset the code => Scrolling down further reveals a tool panel buttons that allows the user to press the "Run" or "Reset" buttons to do what they want.

1. After the user runs the test, see the test results in the "Test" pane => They couldn't figure out how to fix the part that failed in the test => Scrolling down further reveals a tool panel buttons, where users can get tips or ask for help from the "Help" button.

1. User previews the results of coding in the "Preview" pane => User tries to run the test or reset the code after seeing the preview all the way to the bottom => Scrolling down further reveals a tool panel buttons that allows the user to press the "Run" or "Reset" buttons to do what they want.


Therefore, with considering @ahmadabdolsaheb's design idea, there is an idea of removing the vertical scrollbar on the current body, and changing the behavior of how tool panel buttons appear so that the tool panel buttons are displayed when each panel is scrolled to the bottom. 
This is different from having the tools panel button fixed to the bottom always in mobile view, as my PR now indicates.

**Comment by ahmadabdolsaheb** [comment] 2022-10-27 11:58
Thanks for looking into the issue everyone and helping with solution.
I believe the scrollbar issue surfaced when we moved around the breadcrumbs.

Here is the expected behaviour:
- The challenge/project ui does not need to have a scroll bar. 
-  Each pane can have a scroll bar of their own based on their content.
- Mobile tool panel should be displayed at all times.

We had a solution that worked in the past that altered the css using JS. It worked, but it was not responsive.

Ideally we need to be able to add and remove element to the DOM without recalculating and resetting the height of DOM elements.

We could use Flexbox or Grid to expand the mobile/desktop layout to the rest of the available space on the page.

Here is the a quick Demo:
https://codepen.io/abdolsa/pen/XWqvRjj

**Closed** 2022-11-22 08:18 UTC
Labels: type: bug, help wanted
