### ISSUE TITLE
Beta RWD: Test too strict on self-closing link tag

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#45215] opened 2022-02-22 20:56 UTC
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-4

There are most likely other steps affected as well.

## Discussion

The test for this step fails if the `<link>` tag does not include the forward slash before the ending `>`. According to [whatwg.org 13.1.2.1 Start tags](https://html.spec.whatwg.org/multipage/syntax.html#start-tags), point 6:

"Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there **may** be a single U+002F SOLIDUS character (/). **This character has no effect on [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements)**, but on foreign elements it marks the start tag as self-closing."

This seems to imply that the forward slash is optional on the `<link>` tag and thus the test should pass if the user does not include it. There are 14 void elements that this applies to:

[area](https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element), [base](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element), [br](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element), [col](https://html.spec.whatwg.org/multipage/tables.html#the-col-element), [embed](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element), [hr](https://html.spec.whatwg.org/multipage/grouping-content.html#the-hr-element), [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element), [input](https://html.spec.whatwg.org/multipage/input.html#the-input-element), [link](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element), [meta](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element), [param](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-param-element), [source](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element), [track](https://html.spec.whatwg.org/multipage/media.html#the-track-element), [wbr](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element)

**Comment by lasjorg** [comment] 2022-02-22 21:31
The trailing slash on empty elements is completely optional. They are ignored when parsed. The only effect the specs allowing for it has is validation (as far as I can tell) i.e. it isn't an error when checking if the HTML is valid.

**Comment by ieahleen** [comment] 2022-02-23 12:30
I think the issue is that it is not an element that can be selected, so everything is tested with regex

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/step-004.md

There is a couple of tests that check for the slash, so maybe those can be reworked

**Comment by lasjorg** [comment] 2022-02-23 16:26
Does it matter if the seed code for the next challenges still contains the slash? If it does we have to change every single challenge after this one to remove the slash.

Personally, I don't think it matters and we can just leave it as is. Having the slash and not are both valid, but requiring it isn't.

**Comment by lasjorg** [comment] 2022-02-23 16:39
I just noticed that you can place the attributes outside the element and still pass.

```
<head>
  <title>freeCodeCamp Registration Form Project</title>
  <link /> href="styles.css" rel="stylesheet" type="text/css"
</head>
<body>
</body>
```

**Comment by ieahleen** [comment] 2022-02-23 19:24
ok, that maybe is to fix

**Comment by wbenarto** [comment] 2022-02-23 23:54
Hi all, I'll try to pick this up and fix for step-4. I'll rework the test to check for closing tag of > or /> to be passed on the test. 

As I understood the conversation, we will leave the seed code for next challenges as is?

**Comment by Ne0nWinds** [comment] 2022-04-25 19:47
@HenMoshe Are you still working on the last PR? If not, I can pick up this bug where you left off

**Comment by Ne0nWinds** [comment] 2022-04-25 20:00
Is this issue a duplicate of this another bug? #44616

**Comment by HenMoshe** [comment] 2022-04-25 23:49
Hi, I ran into a tight schedule, so sure go ahead! Thank you 

נשלח מה-iPhone שלי

**Comment by clarkdh** [comment] 2022-05-14 02:02
not sure if this is of any help but I just spent 20 minutes trying to figure this out until I found this thread.

**Comment by Dorsalus** [comment] 2022-06-01 03:00
The forward slash seems like can come at the end of any tag within the head after the link and test as valid, the below code passed the check with the additional trailing forward slash in the closing title tag
```
<head>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <title>Registration Form</title/>
  </head>
```
This also tests as valid
```
<head>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <title/>Registration Form</title>
  </head>
```

**Closed** 2022-06-29 07:08 UTC
Labels: type: bug, help wanted, scope: curriculum
