### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5625] opened 2015-12-31 07:15 UTC
Waypoint: Passing Values to Functions with Arguments

I get a RangeError with this code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(a, b){
  console.log(a + b);
}
myFunction(1, 2);
```

**Comment by ltegman** [comment] 2015-12-31 07:20
Closing as a duplicate of #5560. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 07:20 UTC
