### ISSUE TITLE
Cannot pass unit test I am dodger blue in "Use Hex Code to Mix Colors"

### ISSUE THREAD

**Issue by chenzhendong** [FreeCodeCamp/FreeCodeCamp#10576] opened 2016-09-09 13:51 UTC
Give your h1 element with the text I am dodger blue! the color dodger blue.
keep failure, I suspect that the unit test could have bug.

Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by djglife22** [comment] 2016-09-09 13:56
Having same issue

**Comment by ArielLeslie** [comment] 2016-09-09 14:01
```js
        "assert($('.dodger-blue-text').css('color') === '#1E90FF', 'message: Give your <code>h1</code> element with the text <code>I am dodger blue!</code> the <code>color</code> dodger blue.');",
```
I believe `.css('color')` gives an RGB value.  `#1E90FF` is `rgb(30, 144, 255)`

**Comment by chenzhendong** [comment] 2016-09-09 14:03
Agree the change should be made on 
seed/challenges/01-front-end-development-certification/html5-and-css.json

**Comment by erictleung** [comment] 2016-09-09 14:13
@chenzhendong closing as duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Happy coding!

**Closed by erictleung** 2016-09-09 14:13 UTC

**Comment by Yerza10** [comment] 2016-09-09 15:29
same issue
