### ISSUE TITLE
JSON APIs and Ajax: Post Data with the JavaScript XMLHttpRequest Method - URL Missing

### ISSUE THREAD

**Issue by andyhorn** [freeCodeCamp/freeCodeCamp#18123] opened 2018-09-12 05:57 UTC
#### Describe your problem and - if possible - how to reproduce it
In this challenge, we are tasked with creating a POST request to a server but are not given the URL to do so. No information about this challenge or URL can be found, and one post has already been made to the forums asking for the URL.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 69.0.3497.81
* Operating System: Mac OS High Sierra 10.13.6

#### If possible, add a screenshot here
![screenShot](https://user-images.githubusercontent.com/13260228/45404968-e8bbf280-b615-11e8-9030-a22b0230f22d.png)

**Comment by parramorej** [comment] 2018-09-12 15:14
See the last comment on ["ReferenceError: url is not defined" in challenge "Post Data with the JavaScript XMLHttpRequest Method"](https://github.com/freeCodeCamp/freeCodeCamp/issues/14002).

**Comment by QuincyLarson** [comment] 2019-01-04 06:14
Closing this as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14002

**Closed by QuincyLarson** 2019-01-04 06:14 UTC
