### ISSUE TITLE
Basic HTML and HTML5: Add Images to Your Website - Allows to proceed without closing bracket

### ISSUE THREAD

**Issue by gezzalou88** [freeCodeCamp/freeCodeCamp#17719] opened 2018-06-25 18:39 UTC
On the first page of the Basic HTML and HTML5: Add Images to Your Website it allows you to proceed when you have incorrectly missed of the closing bracket from the text as below

<img src="https://bit.ly/fcc-relaxing-cat" alt="a cat"

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-images-to-your-website

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.87
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/13235085/41868938-61891098-78af-11e8-803b-fb0f8ba4c84b.png)

![image](https://user-images.githubusercontent.com/13235085/41868963-7322b7fa-78af-11e8-8c32-4c952be5bea6.png)

**Comment by Flemo7** [comment] 2018-06-26 07:05
Hello,

You don't have to close it, its whats called a void element. 

You can if you want to, but it makes no difference if you do or not. 

Please see: http://dev.w3.org/html5/markup/syntax.html

Thank you!

**Comment by thecodingaviator** [comment] 2018-11-21 10:52
@gezzalou88 / @scissorsneedfoodtoo Please close the issue :)

**Comment by aditijoshi14** [comment] 2018-12-13 18:20
@gezzalou88 This issue can be close as <img> tag doesn't need to be closed as mentioned by @ghost. Hence this is not a bug. :)

**Comment by scissorsneedfoodtoo** [comment] 2018-12-14 10:49
@gezzalou88, thank you for reporting this. While it's definitely best practice to use a closing tag, I'll close this since it's optional and would be difficult to test for the different ways to close the img tag.

**Closed by scissorsneedfoodtoo** 2018-12-14 10:49 UTC
