### ISSUE TITLE
UI bug: Last lesson panel widens view

### ISSUE THREAD

**Issue by digilou** [freeCodeCamp/freeCodeCamp#35106] opened 2019-02-08 16:18 UTC
On the Curriculum page, when opening the last panel (Project Euler) under Coding Interview Prep, the column widens almost twice the size of the original column width when other panels are open or closed.

Viewing on a MacBook Pro with Firefox.

<img width="610" alt="Screenshot of Project Euler panel opened" src="https://user-images.githubusercontent.com/8865558/52490563-7b36d280-2b71-11e9-8ec4-ae14afe9c19e.png">

**Comment by tspeed90** [comment] 2019-02-08 21:07
I'd be interested in working on this if you aren't, @digilou! 

There are a couple options for how this can be fixed, I suppose. Should the width be consistently that wide on the page or should the long titles that are pushing the width out be wrapped instead?

**Comment by digilou** [comment] 2019-02-10 02:53
I'm not working on it @tspeed90.

The weird thing is that I don't think that section had wide titles, However, I'd wrap them, if there were.

**Comment by ronaldcs** [comment] 2019-02-11 04:29
From my understanding, this seems to be working as intended. Based on the CSS, the width will expand based on the content, up to 960px - https://github.com/freeCodeCamp/freeCodeCamp/blob/9b75c1965a2f624388584b407ed749b7cc4a98cc/client/src/pages/learn.css#L6 - which is the reason why it's shifting like that. You'd probably want to get @QuincyLarson's feedback on this.

**Comment by QuincyLarson** [comment] 2019-02-13 10:54
@digilou Thanks for spotting this and creating the issue! I've reproduced this and agree - we should fix this.

@ronaldcs Yes - that line is probably the guilty line, but it's not intentional. We should find a better way of implementing this to prevent the widening from happening. This could be an HTML element that's outside of a certain div, or perhaps an off-by-one array problem (since it only affects the last element on the page).

@digilou You mentioned you're working on this so I'm going to apply the "in progress" label. Thanks for keeping us posted!

**Comment by moT01** [comment] 2019-02-13 15:26
This seems to happen in any section that has a challenge with a long title.... applied visual design, applied accessibility, flexbox... there's many others.

**Comment by DzmitryUr** [comment] 2019-02-18 16:07
I have added PR for this issue.
As @moT01 mentioned this issue happens in any section that has a challenge with a long title

It seems the best way to prevent widening to set `max-width` for wide title of map challenge. The width is depended on the content and without setting `max-width` or `width` it would be some tricky CSS solution or dynamically changes in `JavaScript` code.
 
![test_widening](https://user-images.githubusercontent.com/13452441/52963231-4536f100-33b0-11e9-8d33-f78b27b0aad1.png)

**Comment by digilou** [comment] 2019-02-21 05:22
Actually @tspeed90 said she’d be interested in working on this, which sounds great. I can help, if needed.

**Comment by moT01** [comment] 2019-02-21 14:06
@digilou, there's an open PR to fix this, you can see it two comments above yours. It hasn't been reviewed yet and may or may not get merged. But you might want to wait until that gets reviewed.

**Closed** 2019-03-01 14:50 UTC
Labels: status: ready for QA
