### ISSUE TITLE
Streaks Broken?

### ISSUE THREAD

**Issue by Jorgixhallo** [FreeCodeCamp/freecodecamp#1636] opened 2015-08-07 10:35 UTC
It should be 7 day streak right on both right?
![fcc](https://cloud.githubusercontent.com/assets/5603445/9134008/392e1e86-3cf8-11e5-88a9-2ae32fa6f7d9.jpg)

**Comment by BerkeleyTrue** [comment] 2015-08-07 15:57
hello @Jorgixhallo 

This is a duplicate of #1075 and is current being fixed.

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-07 15:57 UTC
