### ISSUE TITLE
Just starting to learn how to code. Not sure what I'm doing wrong here !

### ISSUE THREAD

**Issue by BinaryEagleScout** [FreeCodeCamp/FreeCodeCamp#10605] opened 2016-09-09 16:45 UTC
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dhcodes** [comment] 2016-09-09 16:47
Thanks for the issue @BinaryEagleScout. I think this may be a Firefox-related issue and a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10588.

**Closed by dhcodes** 2016-09-09 16:47 UTC
