### ISSUE TITLE
Video challenges: Completed challenges not saved

### ISSUE THREAD

**Issue by undefinedsymbol** [FreeCodeCamp/FreeCodeCamp#6962] opened 2016-02-13 10:38 UTC
After completing a video challenge, I first see my brownie points increment by 1 and I am directed to the next challenge, but when I havigate away and come back, my recently gained brownie point(s) has/have disappeared and the recently completed challenge(s) is/are not marked as complete.

**Comment by ltegman** [comment] 2016-02-13 17:58
Closing as a duplicate of #6912. Thanks and happy coding!

**Closed by ltegman** 2016-02-13 17:58 UTC

**Comment by undefinedsymbol** [comment] 2016-02-13 19:24
Sorry for the duplicate posting, I did not see it in the issues list when I checked. Thank you!
