### ISSUE TITLE
Not giving error when semicolon is missing at the return statement

### ISSUE THREAD

**Issue by Bijay-Panthi** [freeCodeCamp/freeCodeCamp#15304] opened 2017-06-10 23:37 UTC
Challenge [dynamically-change-the-height-of-each-bar](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/dynamically-change-the-height-of-each-bar) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    const w = 500;
    const h = 100;
    
    const svg = d3.select("body")
                  .append("svg")
                  .attr("width", w)
                  .attr("height", h);
    
    svg.selectAll("rect")
       .data(dataset)
       .enter()
       .append("rect")
       .attr("x", (d, i) => i * 30)
       .attr("y", 0)
       .attr("width", 25)
       .attr("height", (d, i) => {
         // Add your code below this line
         
         return d * 3
         
         // Add your code above this line
       });
  </script>
</body>

```

**Comment by lynxlynxlynx** [comment] 2017-08-05 15:46
Semicolons are optional (context-dependent) in javascript, so this is not a bug. Someone please close it.

**Comment by systimotic** [comment] 2017-09-04 12:47
Thanks for reporting this issue!

As mentioned, semicolons aren't required in most cases, so this isn't a bug.

Happy coding!

**Closed by systimotic** 2017-09-04 12:47 UTC
Labels: beta
