### ISSUE TITLE
Navigation Switching Bug

### ISSUE THREAD

**Issue by aniveshpandey** [freeCodeCamp/freeCodeCamp#16618] opened 2018-02-01 10:37 UTC
#### Issue Description

The camper profile page can be opened by clicking on the top-right corner in the navigation bar.
While switching from camper profile page back to the challenges page by clicking on the freeCodeCamp.org logo on the left of the navigation bar, the next challenge opens up even if the previous challenge is not solved.

#### Browser Information

* Browser Name, Version: Google Chrome 63.0.3239.132
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet:  Desktop

**Comment by vkWeb** [comment] 2018-02-01 15:28
@aniveshpandey Nice find 😄. This is a very critical. We need to fix this. 
@raisedadead Bug confirmed.

**Comment by raisedadead** [comment] 2018-02-02 06:24
Unfortunately this is by design on the production. You can check that if you are on any page, the click on logo would take you to "next-challenge".

I agree its a inconvenience, but not a bug.

We have fixed this in beta, to be "current-challenge". Closing as we are only fixing work stoppers on production while we focus on beta.

**Closed by raisedadead** 2018-02-02 06:24 UTC
