### ISSUE TITLE
This is bug in Test ?   (After updateRecords(2548, "tracks", ""), tracks should not be set) ?

### ISSUE THREAD

**Issue by Shiyinq** [freeCodeCamp/freeCodeCamp#38530] opened 2020-04-12 09:56 UTC
**Describe your problem and how to reproduce it:**
Hi guys, i have been write some code for the challenge

> https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

but just the test updateRecords(2548, “tracks”, “”) always return error
i have done delete prop tracks but why is not pas ?

this is my code 

```
// Setup
var collection = {
  2548: {
    album: "Slippery When Wet",
    artist: "Bon Jovi",
    tracks: [
      "Let It Rock",
      "You Give Love a Bad Name"
    ]
  },
  2468: {
    album: "1999",
    artist: "Prince",
    tracks: [
      "1999",
      "Little Red Corvette"
    ]
  },
  1245: {
    artist: "Robert Palmer",
    tracks: [ ]
  },
  5439: {
    album: "ABBA Gold"
  }
};

// Only change code below this line
function updateRecords(id, prop, value) {
  
  var myCol = collection[id];

  if(prop == "tracks") {
    if(myCol.hasOwnProperty(prop)) {
      if(value != "") {
        myCol[prop].push(value);
      }else {
        console.log(id);
        console.log(value == "");
        console.log("Prop '" + prop + "' has been deleted");
        console.log("But why the test is wrong ??");
        delete myCol[prop];
      }
    }else {
      myCol[prop] = [];
      myCol[prop].push(value);
    }
  }else {
    if(value != "") {
      myCol[prop] = value;
    }else {
      delete myCol[prop];
    }
  }
  // collection = myCol;

  return collection;
}


console.log(updateRecords(2548, "tracks", ""));
```

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name:   Microsoft Edge Chromium
* Browser Version:  Version 80.0.361.111
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
this is some screenshot 

![error](https://user-images.githubusercontent.com/25049562/79065988-8f7ae000-7cde-11ea-90ea-c540b2856c91.png)
![error1](https://user-images.githubusercontent.com/25049562/79065992-943f9400-7cde-11ea-9028-3a91c59b57e3.png)

**Comment by Sky020** [comment] 2020-04-12 14:11
Hello @Shiyinq ,

This type of problem is, generally, first discussed on the [freeCodeCamp](https://www.freecodecamp.org/forum) forum, by using the Ask for Help button on the referenced lesson's page.

The reason for this is that the problem is likely to do with your code, **not** the freeCodeCamp source code.

For example, note that you are returning the original `collection` variable. The `"tracks"` property is not deleted, because you are not mutating the original `collection` variable, but you are returning it. That being said, you must not mutate the original `collection` variable.

**Comment by ojeytonwilliams** [comment] 2020-04-15 08:22
I'm closing this for the reasons @Sky020 went through.  @Shiyinq if you discuss this on the forum and the consensus is that this is a bug, please reopen this.

**Closed by ojeytonwilliams** 2020-04-15 08:22 UTC
Labels: scope: curriculum, status: needs investigation
