### ISSUE TITLE
Current streak bug

### ISSUE THREAD

**Issue by syedsuhail** [FreeCodeCamp/FreeCodeCamp#2588] opened 2015-08-23 15:12 UTC
Even though my profile shows 6 continous green box for 6 days of streaks, The current streak is shown as 1 day.

![streak-bug](https://cloud.githubusercontent.com/assets/1938009/9428782/5e679718-49d7-11e5-85a5-f9922b6e66db.png)

**Comment by jbmartinez** [comment] 2015-08-23 17:20
Duplicate of #2290. Thanks for reporting

**Closed** 2015-08-25 04:55 UTC
