### ISSUE TITLE
Cannot scroll through wiki article titles

### ISSUE THREAD

**Issue by efaryna** [FreeCodeCamp/FreeCodeCamp#8778] opened 2016-05-23 17:31 UTC
#### Issue Description

The new Wiki search does not allow scrolling through the article titles. Only the first title in the list is clickable.

#### Browser Information

* Browser Name, Version: Chrome, Firefox, Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by theflametrooper** [comment] 2016-05-23 17:47
@efaryna Are you talking about `https://www.freecodecamp.com/wiki/`? If so this is a duplicate of FreeCodeCamp/wiki-generator#44 and FreeCodeCamp/wiki-generator#45

**Comment by ltegman** [comment] 2016-05-23 18:54
Closing as a duplicate of the bugs on the wiki repo.

**Closed by ltegman** 2016-05-23 18:54 UTC
Labels: blocked, wiki
