### ISSUE TITLE
freecodecamp.com and www.freecodecamp.com sessions are different

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3949] opened 2015-10-28 04:51 UTC
If I am logged in to freecodecamp.com or www.freecodecamp.com my session/login is not shared when I visit the other.

I don't know if this is a "bug", but I notice it occasionally, when I catch a link from another user in chat.

**Comment by abhisekp** [comment] 2015-10-28 04:56
I guess, they should redirect the **www** to non-www.

**Comment by abhisekp** [comment] 2015-10-28 06:34
Related to #3949

**Comment by BerkeleyTrue** [comment] 2015-10-28 16:07
@SaintPeter thanks. Closing as duplicate of #3902 

Happy Coding!

**Closed by BerkeleyTrue** 2015-10-28 16:07 UTC
