### ISSUE TITLE
Font size accepted for 16 or 16px

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/freecodecamp#1010] opened 2015-06-20 05:11 UTC
Challenge http://www.freecodecamp.org/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

CSS spec for font-size says only unitless measure allowed is 0, so for the test to be valid it should be 16px and not accepting 16.

For an example go to: http://jigsaw.w3.org/css-validator/validator
Try: "p { font-size: 16;}" 
And you will get the following result: 
Value Error : font-size only 0 can be a length. You must put a unit after your number : 16

![waypoint-change-the-font-size-of-an-element](https://cloud.githubusercontent.com/assets/3256176/8266112/ff62252e-16cf-11e5-84c3-ddf5d1884854.png)

**Comment by GrumpyOldTroll** [comment] 2015-07-03 08:26
This had a 2nd possibly-related problem. I added font-size: 16px to the red-text class, and the challenge marked itself as complete, even though the 2nd paragraph was not yet 16px.

I don't yet know how to upload a screen shot here, but I have one if you have trouble reproducing.

**Comment by LumenTeun** [comment] 2015-07-03 09:48
I think, although I'm not sure, that this is an "error" on the browser side, that the browsers JS interpreter is lenient enough to add `px` to simple number values. Could be fixed by using a check similar to the one used for checking the existence of closing tags.

**Comment by BerkeleyTrue** [comment] 2015-08-11 19:28
Using `px` units for font-size is valid css. 
http://www.w3schools.com/cssref/playit.asp?filename=playcss_font-size&preval=10px

Since the instructions clearly state to use `px` this is not an issue.

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-11 19:28 UTC

**Comment by BerkeleyTrue** [comment] 2015-08-11 19:34
Actually, just realized I misread this issue. The test does check of px units. But, it seams regardless of the spec browsers and jQuery infer px units, so this issue is still not an issue.
