### ISSUE TITLE
Navbar loading in map's sidecar

### ISSUE THREAD

**Issue by FreakDroid** [FreeCodeCamp/FreeCodeCamp#7017] opened 2016-02-15 04:37 UTC
Today When I opened the map section I got

![fcc](https://cloud.githubusercontent.com/assets/5360335/13039913/ba1afd1e-d377-11e5-9ce9-3d59cee7a0cb.jpg)

Some Buttons are one over others, also I watched 3 scrollbar. I'm using Chrome version Versión 48.0.2564.109 m.

Cheers

**Comment by hallaathrad** [comment] 2016-02-15 16:02
That's because the navbar is loading inside the map's sidecar. 
Would you please tell me what screen resolution you're working on? Also, is this a constant thing? or an occasional glitch?

**Comment by FreakDroid** [comment] 2016-02-15 20:14
Sure, that happened in my laptop 1280x800 and my monitor 1920x1080. The 3 scrollbars is something ocasional, but the buttons one over others always is happening.

**Comment by bugron** [comment] 2016-02-16 05:00
@hallaathrad, agreed with @FreakDroid. My screen is 1366x768.

**Comment by hallaathrad** [comment] 2016-02-19 00:54
For all those interested: I am still working on a fix for this, which includes rebuilding the actual layout for the map and the new wiki. Thanks for your patience!

**Comment by FreakDroid** [comment] 2016-02-21 14:26
@hallaathrad Don't worry I know that It's a little complex :+1:

**Comment by BerkeleyTrue** [comment] 2016-02-23 00:35
This was caused by the oops error causing /map-aside to redirect to /map. It should be resolved now.

**Comment by ltegman** [comment] 2016-02-27 00:49
Closing as resolved. Please leave a comment if you are still experiencing this.

**Closed by ltegman** 2016-02-27 00:49 UTC
Labels: blocked
