### ISSUE TITLE
[beta] Generate Random Whole Numbers within a Range - failing tests

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13064] opened 2017-02-02 07:45 UTC
Challenge [generate-random-whole-numbers-within-a-range](http://beta.freecodecamp.com/en/challenges/basic-javascript/generate-random-whole-numbers-within-a-range) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Another challenge which fails tests if coming from previous challenge but passes if I exit the challenge and come back in directly from the Map.

Notice in the screenshot the two variables it says are not defined, even though they do not exist in my code.

![image](https://cloud.githubusercontent.com/assets/5313213/22540963/35e5f0f4-e8d8-11e6-8892-8da14653f50e.png)

```js


// Example
function ourRandomRange(ourMin, ourMax) {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

  return Math.floor(Math.random() * (myMax - myMin + 1)) + myMin;// Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

```

**Comment by Greenheart** [comment] 2017-02-02 09:40
@rmdawson71 Thanks for reporting this!

I'm not sure I can reproduce this. There might be a problem with the [`tail` section](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L5546-L5561) of this challenge.

**Comment by billy-reilly** [comment] 2017-02-09 18:05
@rmdawson71 @Greenheart 

I've reproduced this with the following user agents 

- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36`
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12`

When I navigated straight to the challenge my code passed:
<img width="1270" alt="screen shot 2017-02-09 at 17 00 45" src="https://cloud.githubusercontent.com/assets/22368483/22795519/de3a1142-eeee-11e6-8f00-7765c11ea3ce.png">

but when I reset the challenge and cleared local browser storage, then went back to the previous challenge and did them both consecutively the same code failed:
<img width="1272" alt="screen shot 2017-02-09 at 16 59 48" src="https://cloud.githubusercontent.com/assets/22368483/22795527/e2538ede-eeee-11e6-8314-f22e5eb5dd5d.png">

Is there anywhere that explains how the site runs the challengeSeed / tail / tests and what gets saved to the local browser storage?

**Comment by rmdawson71** [comment] 2017-02-09 20:53
You experienced exactly what we did.  I do not know how the site runs the challengeSeed / tail / tests.  Would love to know for future reference.

**Comment by Greenheart** [comment] 2017-02-12 23:21
@billy-reilly Thanks for the information!

This is how I think it runs, based on working with new challenges for the past month or so:
1. **"Run Tests"** activated.
2. The `head` and `tail` are stringified code snippets coming from the JSON-file of the current section. They are used for setup/shutdown tasks that FCC runs in the background but don't need to show as part of the challengeSeed. I think of them as a few extra lines before or after the user's code.
3. The user's code is read from the editor.
4. The code that should be executed for the tests  is the result of concatenating the three strings `head + userCode + tail`
5. The prepared code is sent to the test framework, executing the combination from the previous step as one big code snippet.
6. The result gets sent back to the main interface and the user is notified of the result.

Hope that makes any sense :smile:

(/cc @rmdawson71)

**Comment by tommygebru** [comment] 2017-05-11 17:33
Confirming: the challenge still behaves the same, requires a tab force-reload

**Comment by systimotic** [comment] 2017-09-05 21:35
I can't reproduce this issue on the latest beta, neither when coming from the previous challenge or after reload, so I'm closing this. If anybody does run into this issue again or can still reproduce this, please comment to let us know and we'll reopen.

Happy coding!

**Closed by systimotic** 2017-09-05 21:35 UTC
Labels: beta
