### ISSUE TITLE
width is being converted to floating point

### ISSUE THREAD

**Issue by ratracegrad** [freeCodeCamp/freeCodeCamp#12954] opened 2017-01-29 18:05 UTC
Challenge [adjust-the-width-of-an-element-using-the-width-property](https://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
h4 {
  text-align: center;
}
p {
  text-align: justify;
}
.links {
  margin-right: 20px;
  text-align: left; */
}
.fullCard {
  width: 245px;
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 10px 5px;
  padding: 4px;
}
.cardContent {
  padding: 10px;
}
</style>
<div class="fullCard">
<div class="cardContent">
  <div class="cardText">
    <h4>Google</h4>
    <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
  </div>
  <div class="cardLinks">
    <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
    <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
  </div>
</div>
</div>

    ```
    
When you press check tests it fails because the call to verify test of
$('.fullCard').css('width')
is returning a floating point number instead of the decimal value entered:
"244.98295020214843px"

**Comment by erictleung** [comment] 2017-01-29 21:56
@ratracegrad I can verify that this causes an issue on Firefox. This runs just fine on Chrome. How were you able to verify the floating point number?

**Comment by ratracegrad** [comment] 2017-01-29 22:01
I am using Chrome and it did not work for me. I did try Firefox before reporting issue and had the same problem with it too.
I verified that it was a floating point number by opening up the developer console and entering:
$('.fullCard').css('width')
and this returned "244.98295020214843px". This will of course make the test assert fail which is the problem I am encountering.

**Comment by erictleung** [comment] 2017-01-30 01:49
@ratracegrad thanks for the information. This issue appears to be a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12687. So I'll be closing this issue in favor of that one. Happy coding!

**Closed by erictleung** 2017-01-30 01:49 UTC
Labels: beta, bug, firefox
