### ISSUE TITLE
Issues loading the remote environment for the relational database course 

### ISSUE THREAD

**Issue by tomimarche** [freeCodeCamp/freeCodeCamp#50170] opened 2023-04-24 13:58 UTC
Hi! I’ve tried with three different browsers and I cannot start with the build a boiler plate course. I allowed the third-party cookies and installed what was supposed to but no idea how to get through. If you have any ideas please let me know. Thanks

![image](https://user-images.githubusercontent.com/131622458/234018477-b4837d50-e2c4-4c1f-98cd-4cdf40ffe286.png)

**Comment by ShaunSHamilton** [comment] 2023-04-24 16:29
Hello there,

Thank you for taking the time to open this. We are aware of an issue with the RDB course. For the moment, we recommend running the course locally: https://www.freecodecamp.org/news/how-to-run-freecodecamps-relational-databases-curriculum-using-docker-vscode-and-coderoad

Closing as duplicate of: https://github.com/freeCodeCamp/freeCodeCamp/issues/50161

**Closed by ShaunSHamilton** 2023-04-24 16:29 UTC
