### ISSUE TITLE
Some features are missing while setting the project in local.

### ISSUE THREAD

**Issue by sadikn** [freeCodeCamp/freeCodeCamp#36312] opened 2019-06-21 09:02 UTC
I've cloned and setup the project in local and its working fine. But I was not able to find some features like latest login mechanism by using just the email in the "**Production Current**" branch. Anyone has faced such an issue and resolved it? Thanks in advance.

**Comment by moT01** [comment] 2019-06-21 16:14
I believe this is just how the site works in development. More details here - https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#how-to-sign-in-when-working-locally

Was there other things you found missing? If not, we can probably close this.

**Comment by sadikn** [comment] 2019-06-24 11:37
I was not able to find the current login system in the master branch using just the email.

**Comment by moT01** [comment] 2019-06-24 12:39
yes, I believe that's by design - and won't be changing. Can anyone confirm this?

**Comment by sadikn** [comment] 2019-06-28 05:08
So I was trying to create a username/password login for application and I was checking to get the current implementation which is just by using the email and change the same. But unfortunately I wasn't able to find that. Also I am fairly new to the passport authentication and can you give me possible pointers on that?

**Comment by raisedadead** [comment] 2019-07-17 15:21
The authentication on the local setup is different than what is and will be deployed in production. The implementation based on a conditional in code.

Can you elaborate on what you are trying to do with the authentication?

I am closing this, for now for lack of information, will re-open if this is found to be a legitimate bug.

We can continue to discuss in the thread or over our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) and [Contributors category on the Forum](https://www.freecodecamp.org/forum/c/contributors) if this is just some general query about freeCodeCamp's codebase.

**Closed by raisedadead** 2019-07-17 15:21 UTC
