### ISSUE TITLE
Client-ID Required for Kraken API calls

### ISSUE THREAD

**Issue by genkibit** [FreeCodeCamp/FreeCodeCamp#10740] opened 2016-09-15 03:08 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description

JSONP calls to the channels API result in a bad request. This is due to an update to the Twitchtv API which now requires a client id, which means creating an account and registering your application with the service. Details can be read from the official developer blog:  

https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.pm46cq40d

I confirmed this by console logging the response object from the channels API on my application and comparing it with the example provided by Free Code Camp (see screenshots).

#### Browser Information

N/A

#### Your Code

```js
 
 
 
```
#### Screenshot

![screen shot 2016-09-14 at 10 44 41 pm](https://cloud.githubusercontent.com/assets/6819989/18536972/f54ebea2-7acf-11e6-9745-eba5e79136d3.png)

![screen shot 2016-09-14 at 10 45 05 pm](https://cloud.githubusercontent.com/assets/6819989/18536976/fcf2e7d2-7acf-11e6-81fc-39571f44818c.png)

**Comment by dhcodes** [comment] 2016-09-15 13:29
Confirmed, at least to the extent that my (previously-working) Twitch app is now yielding `Bad Request` as well. Should we update the instructions on this challenge to have campers create a Twitch Developer account and read the blog post about setting a Client ID?

**Comment by zelite** [comment] 2016-09-15 17:33
On the codepen it should be an easy fix. Freecodecamp already has a twitch account. Whoever is in charge if that needs to get a client ID. Then just add this to the js before the other code: 

    $.ajaxSetup({
      headers : {
        "Client-ID": "<clientID>"
      }});

**Comment by dhcodes** [comment] 2016-09-15 19:13
cc @FreeCodeCamp/issue-moderators

**Comment by genkibit** [comment] 2016-09-17 00:54
Yup, looks like all heck is breaking loose:

https://github.com/justintv/Twitch-API/issues/609

Wish I copied the response object before the change. It would be nice to use a mock response data instead of having to create an account for just learning purposes..

**Comment by QuincyLarson** [comment] 2016-09-17 06:34
@genkibit yes - it definitely would have helped! 

We are getting ready to semi-retire this challenge anyway (we're moving it to the optional practice projects section).

@dhcodes I've created a gist with an array of 5 responses (two live, two offline, one invalid). This is an array instead of a series of API calls, but it should work fine for the purpose of the challenge: https://gist.github.com/QuincyLarson/2ff6892f948d0b7118a99264fd9c1ce8

Could one of you create a PR that tells links campers to that gist and tells them to use that JSON for their responses?

**Comment by genkibit** [comment] 2016-09-17 14:22
@QuincyLarson - Ok. Just made the pull request. Hope I did it right..

**Comment by Manish-Giri** [comment] 2016-09-17 20:29
I'm about to complete the two remaining projects for my Front End certification. Do I need to redo the Twitch App (that I submitted a while back) based on the new client ID requirement?

**Comment by dhcodes** [comment] 2016-09-17 21:11
@manish-giri probably so it will work going forward, or you could make a twitch dev account and get your own client id

**Comment by Manish-Giri** [comment] 2016-09-17 21:28
@dhcodes you mean it's fine if I leave it as-is, from the certification POV?

**Comment by dhcodes** [comment] 2016-09-17 21:37
I'm saying I recommend updating it because if you ever use it in a portfolio, you would want it to function.

**Comment by Manish-Giri** [comment] 2016-09-17 21:39
Okay, I didn't really get the first part of your message before. Thanks.

**Comment by phyrenight** [comment] 2016-09-17 23:06
Would [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-Twitchtv-JSON-API) need to be updated then?

**Comment by mones-cse** [comment] 2016-09-17 23:17
please update the [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-Twitchtv-JSON-API) cause it's misleading. spent lots of time figuring out what is the problem :(

**Comment by QuincyLarson** [comment] 2016-09-18 07:27
@mones-cse we have deprecated that wiki and will delete it completely. The current article is here: http://forum.freecodecamp.com/t/use-the-twitchtv-json-api/19541

**Comment by anarchyrucks** [comment] 2016-09-28 10:55
![screenshot](https://cloud.githubusercontent.com/assets/8762472/18910951/fc1240c4-8597-11e6-8b13-3ae746145f77.jpg)

There is no link provided for the sample API response.

**Comment by QuincyLarson** [comment] 2016-09-28 17:26
@anarchyrucks I've included it: http://forum.freecodecamp.com/t/use-the-twitchtv-json-api/19541

**Closed** 2016-09-28 17:26 UTC
Labels: confirmed, Discussing

**Comment by genkibit** [comment] 2016-09-28 20:31
Ah, apologies. I forgot to close the <a> tag. Should I submit a PR with correction?

**Comment by QuincyLarson** [comment] 2016-09-29 05:41
@genkibit yes please

**Comment by jonataswalker** [comment] 2016-10-06 13:03
It's being a hard time to finish "Twitchtv JSON API" challenge.

@QuincyLarson  said:

> I've created a gist with an array of 5 responses (two live, two offline, one invalid).

But [Twitch-API docs](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#example-response) says, if offline:

```
{
  "stream": null
}
```
And in @QuincyLarson's gist there's no `stream` property. Maybe in the meantime they've changed their API?

If I understood, to complete this challenge we won't use Twitchtv JSON API, we will use @QuincyLarson's gist instead. But what is **_online/offline/invalid_** in this fake response?

**Comment by QuincyLarson** [comment] 2016-10-06 19:40
@jonataswalker Yes - you should use my gist instead of using the API. We plan to retire this challenge as soon as we can launch our expanded curriculum.

**Comment by jonataswalker** [comment] 2016-10-06 20:43
Right @QuincyLarson but what is **_online/offline/invalid_** in your (kinda) json?

**Comment by QuincyLarson** [comment] 2016-10-07 01:21
@jonataswalker I'm not sure I understand you. I retrieved these directly from queries to Twitch using an API key. These are the raw responses, concatenated into a single JSON document.

**Comment by anarchyrucks** [comment] 2016-10-07 07:17
@QuincyLarson your gist doesn't have a stream property anywhere which is used to know if someone is online/offline

**Comment by jonataswalker** [comment] 2016-10-07 09:52
> your gist doesn't have a stream property anywhere which is used to know if someone is online/offline

That's what I meant in my first comment. The gist (guessing here) must be out-of-date.

**Comment by QuincyLarson** [comment] 2016-10-07 21:26
@anarchyrucks @jonataswalker I just made this gist a few days ago, but if it's out of date for some reason (maybe I used an older version of the API?) then could one of you create a version that's up to date? I can then update my gist based on it.

**Comment by Em-Ant** [comment] 2016-10-08 14:44
@QuincyLarson if someone has some good data we can make a fake API on Hyperdev or Heroku that works only for the 7-8 accounts that we use in the project. I don't know if it's worth it since we are retiring the project.

**Comment by QuincyLarson** [comment] 2016-10-08 23:39
@Em-Ant Yes - let's do that. Let's create a pass-through API on HyperDev with an API key in its .env file. Would you be interested in building this? I know you are quite busy writing tests for the back end challenges still though.

**Comment by Em-Ant** [comment] 2016-10-09 07:11
@QuincyLarson  I don't know if the **pass-through** is a good idea. We had the same discussion about the Open Wheater Map service some times ago. See [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3714#issuecomment-148113892) and Berkeley's answer below...

**Comment by zelite** [comment] 2016-10-09 08:50
My opinion is that there should be one static JSON version for those who do not want to create a twitch account and leave instructions about the requirement for a Client ID, for those who don't mind creating a twitch account. 

The privacy of the Client ID is a non-issue, as I wrote here ( https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11015#issuecomment-250957089 )

> from here: https://github.com/justintv/Twitch-API/blob/master/authentication.md

> > Client IDs are public and can be shared (e.g. embedded in the source of a web page),

I think everyone is making a big fuss over this project, since it is very easy to create a client ID and there is no problem in having it public. The only issue I see is the objection of some people in creating an account in a third party website (which is also an issue for using the OpenWeather API and there making the API key public is actually sensitive).

**Comment by jonataswalker** [comment] 2016-10-09 19:54
@QuincyLarson 

Here's your gist forked and modified to reflect the actual response from Twitch API.
```shell
curl -H 'Client-ID: .....' -X GET https://api.twitch.tv/kraken/streams/ESL_SC2
```
So, **offline** is `stream == null` and **online** is a valid stream object.

`display_name` is present when channel is offline just for the sake of simplicity, it's not part of original response.

**Comment by QuincyLarson** [comment] 2016-10-09 20:32
@zelite Yes, it's easy enough to create the API key, but it is a bad practice to expose private API keys in a public space, so we should discourage this. 

@jonataswalker OK - great! I've updated my original gist with the text of your gist. Thank you for doing this. So to be 100% clear, the gist you created will mimic the actual API responses? Could you incorporate it into your own twitch.tv viewer or the one we're using here: https://codepen.io/FreeCodeCamp/pen/Myvqmo/

**Comment by jonataswalker** [comment] 2016-10-09 21:39
That's it, @QuincyLarson!

http://codepen.io/jonataswalker/pen/EgEbEo

Cheers.

**Comment by zelite** [comment] 2016-10-10 11:26
@QuincyLarson 

But the client ID is **not** a private API key. It is part of the OAuth2 authentication protocol  ( https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2 )

> **Client ID and Client Secret**

> Once your application is registered, the service will issue "client credentials" in the form of a client identifier and a client secret. The **Client ID** is a publicly exposed string that is used by the service API to identify the application, and is also used to build authorization URLs that are presented to users. The **Client Secret** is used to authenticate the identity of the application to the service API when the application requests to access a user's account, and must be kept private between the application and the API.

That's why I don't understand all the fuss. You don't need the Client Secret for the kinds of queries that are necessary for this project.

**Comment by jgresalfi** [comment] 2016-11-21 02:45
I'm a bit of a newb at API-fu so someone please educate me if I'm wrong, but I'm able to get data from the Twitch API using my client id in a custom request header, so it's not showing up as a query string in the URL. Is that an acceptable way to complete the project while still using the API as originally intended? Cheers!

**Comment by Em-Ant** [comment] 2016-11-21 17:30
@jgresalfi I think it's ok if you use the original API.
We set up the pass-through server to allow people who don't want to create an API key to keep working on this challenge as before. On codepen your code is public, so anyone could access your key reading the code, even if you put it in a header. I think it's not a big problem (read the comment above). Anyway you can switch to our server in the future, if you feel uncomfortable exposing your key in a public space.

**Comment by jgresalfi** [comment] 2016-11-21 17:58
@Em-Ant Thanks for the reply...my brain cells weren't totally firing on that one. Of course people can see my key in Codepen. I'm not a Twitch user and there is nothing at all in my user profile so, unless there's something nefarious someone can do with my key and my blank profile, I'm comfortable putting it out there. I'm tempted to try an get OAuth to work, but also want to stay focused on getting my app done. Thanks again.
