### ISSUE TITLE
bug on challenge #17: Resize your image 

### ISSUE THREAD

**Issue by tbraden30** [FreeCodeCamp/FreeCodeCamp#3937] opened 2015-10-27 19:09 UTC
I don't know what else can be done. I've checked various other codes to confirm that I'm right. I even copied and pasted from the prompt; adjusting wherever necessary. Can someone please look at my code or fix this bug so i can progress. 

![untitled](https://cloud.githubusercontent.com/assets/15311351/10769444/1f9ea5c0-7cb4-11e5-87a7-8223ae75947c.png)
Challenge [Waypoint: Size your Images](http://www.freecodecamp.com/challenges/waypoint-size-your-images#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
 .smaller-image {
    width: 100px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by awesomeaniruddh** [comment] 2015-10-27 20:22
The issue is that you didn't add the `smaller-image` class to the `img` element.

I'm closing the issue because I believe this resolves it. In the future, please ask questions regarding your code itself at gitter.im/FreeCodeCamp/Help.

Happy Coding :)

**Closed by awesomeaniruddh** 2015-10-27 20:22 UTC

**Comment by Varedis** [comment] 2015-10-27 20:36
Your image doesn't actually use the class. 

i.e. <img class="smaller-image" src="...">

**Comment by debiro1** [comment] 2015-10-28 03:21
I spent an hour trying to get off #17 until finally I just got tired and cheated. You've probably figured it out by now.  But if you haven't, go to the top of the page and click on "Map."  Then go to #18 (one lesson beyond where you are).  Remember the lessons build on each other.  There you will find the code for what you need.  You have to add one before the </style> [.smaller-image {
   width: 100px; }] and then incorporate the other one into the img src that's already there.  i.e. <img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">.  Hey, we tried it the honest way.  Like you, I even found another way to do it.  But, alas, the program wouldn't let me move on unless I did it THEIR way.  :-)

**Comment by debiro1** [comment] 2015-10-28 03:21
Oops. Sorry about the big fat upside down cat pic!  Just go to #18 and copy and paste!

**Comment by carmeister** [comment] 2016-09-16 09:24
Thanks guys! I got myself stuck on this one after having spent a couple of days away from coding. Usually, for a newbie, we are told what to do in the earlier stages but maybe it's just me and I need it to be drilled into my head haha

**Comment by KV144** [comment] 2016-09-28 22:53
Can you explain. Just show a picture

**Comment by texas2010** [comment] 2016-09-28 23:15
@KV144, this issue is old.  
if you need a help. Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by datom55** [comment] 2017-05-01 15:06
The questions are a bit vague
