### ISSUE TITLE
Scrimba Video for Basic HTML and HTML5: Create a Set of Radio Buttons needs updating

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38426] opened 2020-03-24 01:35 UTC
Challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons
Video: https://scrimba.com/c/cNWKvuR

The HTML in the video does not have the proper nesting of input elements inside labels. A student can not pass the challenge using code from the video.

Test that fails using the code in the video:
> Each of your two radio button elements should be nested in its own label element.

@beaucarnes If it's possible to get this updated that would be great.

**Comment by dmcnaughtond** [comment] 2020-04-23 23:07
Hi-
The following code gets the test to pass.
<label>
    <input type="radio" id="indoor" name="indoor-outdoor" /> Indoor 
  </label>
  <label>
    <input type="radio" id="outdoor" name="indoor-outdoor" /> Outdoor
  </label>

However, I think the solution in the video is better code. Is it possible that the problem is with the test?

**Comment by dmcnaughtond** [comment] 2020-04-29 17:45
@beaucarnes here you go--sorry!
```html
<label>
    <input type="radio" id="indoor" name="indoor-outdoor" /> Indoor 
  </label>
  <label>
    <input type="radio" id="outdoor" name="indoor-outdoor" /> Outdoor
  </label>

**Comment by lasjorg** [comment] 2020-08-13 22:24
@beaucarnes If we can get this video update it would be great.

It is confusing some campers that the code in the video does not match the requirements for the challenge. We do see a few forum posts about this now and then, so it would be nice to get this fixed if possible.

**Comment by moT01** [comment] 2020-09-15 16:01
It has been decided that the videos are too difficult to keep updated so we are going to be removing links to them in the challenges. Fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/39559 - so we can close this. Thanks and happy coding 🎉

**Closed by moT01** 2020-09-15 16:01 UTC
Labels: scope: learn, type: bug
