### ISSUE TITLE
[beta] In jQuery challenges: bootstrap, jquery and animate.css aren't loaded in

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9974] opened 2016-07-29 11:26 UTC
[![https://gyazo.com/3644a25b78339407d0a14c37426258fa](https://i.gyazo.com/3644a25b78339407d0a14c37426258fa.png)](https://gyazo.com/3644a25b78339407d0a14c37426258fa)

**Comment by raisedadead** [comment] 2016-07-29 11:30
Duplicate of #9957 Please search existing issues. :sweat:

**Closed by raisedadead** 2016-07-29 11:30 UTC
Labels: beta
