### ISSUE TITLE
Getting a warning message ( in console ) on submitting the solution

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50725] opened 2023-06-16 03:06 UTC
### Describe the Issue

There are some modules ( e.g: [Create a Controlled Form](https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-controlled-form) module ) within the [React](https://www.freecodecamp.org/learn/front-end-development-libraries/) section of the [Front End Development Libraries](https://www.freecodecamp.org/learn/front-end-development-libraries/) course where, when the user submits their solution ( whether correct or incorrect ), then they end up with the following warning within the console:

> act(...) is not supported in production builds of React, and might not behave as expected.

Since this warning is not relevant to the solution submitted by the user, I think it could make the user feel confused.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-controlled-form

### Expected behavior

In order to avoid any sort of ambiguity and to keep things as clear as possible, I believe when the user submits their solution and if their submitted solution is not correct ( partially or completely ), then they should only be getting relevant error messages printed onto the console which can help them in debugging their solution, or if their submitted solution is entirely correct, then they should be getting the following messages only ( within the console ):

> // running tests
> // tests completed

### Screenshots

![act_issue](https://github.com/freeCodeCamp/freeCodeCamp/assets/36872756/9c12bbd3-96b0-4b2d-b97f-f33533e0db18)

### System

- Device: Laptop
- OS: macOS 13.0.1
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by CallmeHongmaybe** [comment] 2023-06-16 04:22
I can see that the error message is pretty cryptic even though it happened somewhere along the stack trace. 
If you don't mind, can you comment your JSX element  so that me and other people can paste the code immediately in the editor and see it for ourselves ?

**Comment by Bhavyaatrivedi** [comment] 2023-06-16 05:59
Can you provide the path of this file.

**Comment by purnimanagpal23** [comment] 2023-06-16 18:12
If you want i can work on this issue. Can you assign this to me. I am expert in react but first timer in open source community. So apologize in advance if i am going out of way in asking this on the thread 🙏

**Comment by lasjorg** [comment] 2023-06-16 18:23
Pretty sure that has been there forever. It looks to be caused by running tests with the production builds of React. Maybe we can just use the dev builds.

```
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/react/meta.json
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/react-and-redux/meta.json
```


```
https://unpkg.com/react@16.4.0/umd/react.production.min.js
https://unpkg.com/react-dom@16.4.0/umd/react-dom.development.min.js
```

Tested it briefly and it didn't seem to break anything, but I'm not sure what the reason for using the production builds is.

Or maybe the error message can be silenced somehow.

---

`https://github.com/vercel/next.js/discussions/35676`

**Comment by lasjorg** [comment] 2023-06-28 20:08
I'm pretty sure I have seen this error on other React (maybe React/Redux) challenges as well.

I'm not sure if it is just because the prod build is smaller/faster or what?

I see no real harm in using the dev build and it would/should make the error go away. But someone from the dev team will have to look at this and approve it.

@naomi-lgbt is using the dev build of React an option here?

**Comment by naomi-lgbt** [comment] 2023-07-11 17:18
I'm not entirely sure, tbh. Maybe something @ojeytonwilliams can provide insight on.

**Comment by ojeytonwilliams** [comment] 2023-07-12 11:22
So, the problem is that we currently bundle react-dom-test-utils into the script that runs the tests, so changing the meta doesn't help us.

However, once https://github.com/freeCodeCamp/freeCodeCamp/pull/49281/ is in, we will have full control over the scripts that we import and can choose which build we want for the react lessons.

I propose we revisit this issue once that's in main and experiment with development builds then.

**Comment by KSSaiTeja** [comment] 2023-09-17 02:31
I am interested to work on this issue. can anyone explain me more clearly what to do next?

**Comment by Amit-Morade** [comment] 2023-10-17 11:34
Can I work on this?

**Closed** 2024-01-30 20:50 UTC
Labels: type: bug, help wanted, scope: curriculum
