### ISSUE TITLE
Flash of the next question after finish a video questionnaire.

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#7521] opened 2016-03-12 14:50 UTC
#### Issue Description
* After finish the questions in Computer Basics videos for example: **Computer Basics: Measuring Data Speed** I can see a flash with the first question of the next questionnaire.

#### Steps To Reproduce
 
1. Go to http://www.freecodecamp.com/videos/computer-basics-measuring-data-speed
2. Click in `Take me to the questions`.
3. Finish the questionnaire successful

Actual: View a flash with the first question of the next questionnaire and then redirect to the next video.
Expected: Go to the next video.

#### Browser Information
* Google Chrome, Version 48.0.2564.116 (64-bit)
* OSX El Capitan 10.11.3

#### Screenshot 
![bug-free-code-camp](https://cloud.githubusercontent.com/assets/11529571/13723577/5013125e-e861-11e5-90b8-7cf849c993a5.gif)

**Comment by raisedadead** [comment] 2016-03-12 15:11
Closing as duplicate of #7480 

@aluzardo Please follow the discussion there.

**Closed by raisedadead** 2016-03-12 15:11 UTC
