### ISSUE TITLE
Public portfolio page doesn't update the 'commits graph'

### ISSUE THREAD

**Issue by pcatana** [freeCodeCamp/freeCodeCamp#17809] opened 2018-07-03 11:14 UTC
#### Describe your problem and - if possible - how to reproduce it
When being on my personal public portfolio page the 'commit graph' doesn't have the latest activity.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/username

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows 10 latest

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/19393057/42216599-9e6ea162-7ec2-11e8-822f-fbdaf7034401.png)

**Comment by RandellDawson** [comment] 2019-02-22 09:37
Closing as this is a duplicate of issue #17822.  Please use this other issue to discuss further.

Thank you.

**Closed by RandellDawson** 2019-02-22 09:37 UTC
Labels: duplicate
