### ISSUE TITLE
Small Bug

### ISSUE THREAD

**Issue by akhilnandu** [freeCodeCamp/freeCodeCamp#15582] opened 2017-07-02 05:23 UTC
Guys, I found a small issue in the program. In one of the sections, it is given like we cannot pass the single quotas to the program but I have passed single quotas and none of the error raised. Also the program is compliled and I moved forward to the next lesson. Please look into this.

#### Challenge Name

Its in the first animation section, that is for **animated bounce.**

#### Issue Description

I just tried passing single quotas and it moved forward.

#### Browser Information

Latest Version of Google Chrome

* Browser Name, Version:  Google Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot

![photo](https://user-images.githubusercontent.com/8075048/27767404-95464cb2-5f14-11e7-90f4-1e751fb3a22a.png)

**Comment by erictleung** [comment] 2017-07-02 16:56
@akhilnandu thanks for the issue, but I'm closing this as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14207. Happy coding!

**Closed by erictleung** 2017-07-02 16:56 UTC
