### ISSUE TITLE
Solution correct, but button "Submit and go to my next challenge (ctrl + enter)" not active

### ISSUE THREAD

**Issue by alexwander** [FreeCodeCamp/FreeCodeCamp#10124] opened 2016-08-07 20:31 UTC
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20myStorage.car.inside%5B%22glove%20box%22%5D%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = myStorage.car.inside["glove box"]; // Change this line


```

**Comment by BKinahan** [comment] 2016-08-07 21:18
Hi @alexwander, your code looks to be correct and I was able to enter it on the challenge page and have the tests all pass, so I'm unable to reproduce your issue.

Do you still have a problem if you refresh the page and/or try a new browser window?

**Comment by alexwander** [comment] 2016-08-10 18:48
it was some problem with Chrome caching .js files. In new private window all OK

**Comment by BKinahan** [comment] 2016-08-10 18:57
Closing as resolved 👍

**Closed by BKinahan** 2016-08-10 18:57 UTC
Labels: blocked
