### ISSUE TITLE
Typo in Bonfire: Slasher Fic

### ISSUE THREAD

**Issue by megazver** [FreeCodeCamp/FreeCodeCamp#3709] opened 2015-10-11 12:41 UTC
Pretty sure that "slasher([1, 2, 3], 2, [3]) should return [3]."    

should actually be  

"slasher([1, 2, 3], 2) should return [3]."

**Comment by bugron** [comment] 2015-10-11 13:04
@megazver thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3687 so I'll close this one. You can continue further discussion there or create a PR if you want, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-11 13:04 UTC
