### ISSUE TITLE
Error with "Fing the Lenght of a String"

### ISSUE THREAD

**Issue by DemianKost** [freeCodeCamp/freeCodeCamp#13776] opened 2017-03-06 15:28 UTC
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%2010%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AlastNameLength%20%3D%20lastName.length%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 10;
var lastName = "Lovelace";

// Only change code below this line.

lastNameLength = lastName.length;



```

**Comment by Manish-Giri** [comment] 2017-03-06 16:40
@DemianKost This is caused by the fact that you assigned `10` to `lastNameLength` -  
`var lastNameLength = 10;`
The default challenge code has it assigned to 0 - `var lastNameLength = 0;`

You don't need to change value of `lastNameLength` like that, as the default code suggests, you only write your new code after the comment `// Only change code below this line.`

**Comment by systimotic** [comment] 2017-03-07 11:24
As mentioned, the comment is there for a reason 🙂
I'm closing this as resolved/issue in the code. Happy coding!

**Closed by systimotic** 2017-03-07 11:24 UTC
