### ISSUE TITLE
Comments are getting parsed as part of the actual code.

### ISSUE THREAD

**Issue by hugoivankm** [FreeCodeCamp/FreeCodeCamp#11635] opened 2016-11-13 00:10 UTC
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20studlyCapVar%3B%20%0A%2F*var%20StUdLyCapVaR%3B%20%3C---%20it%20is%20parsing%20%20comments%20as%20javascript%20code%20so%20a%20comment%20can%20cause%20the%20solution%20to%20appear%20wrong%20even%20if%20the%20answer%20is%20right.%20*%2F%20%20%20%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%20%2F%2Fvar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0A%20studlyCapVar%20%3D%2010%3B%2F%2FSTUDLYCAPVAR%20%3D%2010%3B%3C--same%20bug%20here%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var studlyCapVar; 
/*var StUdLyCapVaR; <--- it is parsing  comments as javascript code so a comment can cause the solution to appear wrong even if the answer is right. */   
var properCamelCase;
var titleCaseOver; //var TitleCaseOver;

// Assignments
 studlyCapVar = 10; //STUDLYCAPVAR = 10;<--same bug here
properCamelCase = "A String";
titleCaseOver = 9000;

```

**Comment by atjonathan** [comment] 2016-11-13 00:24
@hugoivankm, your code passes fine for me. Try resetting the editor, or clearing your local-storage.

**Comment by hugoivankm** [comment] 2016-11-13 03:54
It still keeps happening randomly in chrome and firefox. The code runs but suddenly some comments that with code in them cause the challenge's tests to fail. I am sure it is that because once I erase the comments It works perfectly fine.

**Comment by atjonathan** [comment] 2016-11-13 13:07
cc @FreeCodeCamp/moderators, can anyone reproduce?

**Comment by Bouncey** [comment] 2016-11-13 13:12
@hugoivankm your code passes for me in both chrome and firefox

**Comment by Bouncey** [comment] 2016-11-14 17:38
@hugoivankm if you have any more information, please reopen this issue. 

Closing as can't reproduce

**Closed by Bouncey** 2016-11-14 17:38 UTC

**Comment by hugoivankm** [comment] 2016-11-19 20:46
Here is my code:
`
function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
    switch(val){
    case "bob":
      answer="Marley";
      break;
    case 42:
      answer="The Answer";
      break;
    case 1:
      answer ="There is no #1";
      break;
    case 99:
      answer="Missed me by this much!";
      break;
    case 7:
      answer="Ate Nine";
      break;
    default:
      answer = "NARF";
    
}
  /*
  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7) {
    answer = "Ate Nine";
  }
  */
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);

It just happens randomly and it's to reproduce reliably. You can work around it not using comments with code in them but it's pretty annoying.

![bug](https://cloud.githubusercontent.com/assets/22568065/20458302/cf7a55c2-ae66-11e6-8819-0a1761f54217.jpg)
