### ISSUE TITLE
d3 Beta Local Storage isn't working correctly

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#13008] opened 2017-01-31 18:08 UTC
#### Data Visualization with D3: Work with Data in D3
http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-data-in-d3

#### Issue Description

Submit and incorrect answer then submit the correct answer.  The tests and output will say the solution is incorrect.

Clear your localStorage and try the correct solution and the challenge will pass.

#### Browser Information
* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Solution Code

```js
 
 
 
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    // Add your code below this line
    d3.select('body').selectAll('h2')
      .data(dataset)
      .enter()
      .append('h2')
      .text('New Title')
    
    
    // Add your code above this line
  </script>
</body>

```

**Comment by systimotic** [comment] 2017-03-16 21:04
Thanks for reporting this @benschac! I'm closing this as a duplicate of #12762

**Closed by systimotic** 2017-03-16 21:04 UTC
Labels: beta
