### ISSUE TITLE
Headline with the h2 Element

### ISSUE THREAD

**Issue by computerluca** [FreeCodeCamp/FreeCodeCamp#10986] opened 2016-09-29 22:02 UTC
Challenge [headline-with-the-h2-element](http://beta.freecodecamp.com/en/challenges/html5-and-css/headline-with-the-h2-element) has an issue.

If i click run test i can't see the text of the test cases and i can ALWAYS pass the challenge even if the code is not correct!

**Comment by erictleung** [comment] 2016-09-29 23:34
@computerluca closing as duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10966. Happy coding!

**Closed by erictleung** 2016-09-29 23:34 UTC
