### ISSUE TITLE
"Create my Github issue" button is not working

### ISSUE THREAD

**Issue by iamads** [FreeCodeCamp/FreeCodeCamp#3772] opened 2015-10-16 13:23 UTC
"Create my Github issue" button is not working in Angularjs, git , node.js and express.js,MongoDB   and Full Stack JavaScript Projects  sections.

**Comment by awesomeaniruddh** [comment] 2015-10-17 12:06
Confirmed on Chrome for Windows 10.

**Comment by ankitaggarwal011** [comment] 2015-10-17 20:49
Hi,
This is because the editor is unavailable and not defined for challengeTypes (2-Video, 3-Zipline, 4-Basejump) and thus, accessing it would create a reference error.

Simply adding a check on whether it is defined before accessing it's member functions would solve this problem.
This is the point where it can be checked whether editor is defined (https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/main.js#L238).

I submitted a PR on this here (#) . Let me know what you think. @awesomeaniruddh @iamads .

**Comment by BerkeleyTrue** [comment] 2015-10-18 04:48
Fixed by #3784

**Closed by BerkeleyTrue** 2015-10-18 04:48 UTC
Labels: confirmed
