### ISSUE TITLE
An issue in the description of the WayPoint

### ISSUE THREAD

**Issue by MuhammadAsifMA** [FreeCodeCamp/FreeCodeCamp#4329] opened 2015-11-12 12:44 UTC
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0AmyCar.nickname%20%3D%20%22whatever%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The description text on the left-side of the page has an error in it. I'll mention the text here:

```
Now, once the myCar instance is created it can be used like any other object and can have its properties accessed and modified the same way you would usually. For example:

var myCar.turboType = "twin";     // This line has an extra keyword "var", which causes an error.

Our myCar variable now has a property turboType with a value of "twin".

**Comment by ltegman** [comment] 2015-11-12 16:33
Closing as a duplicate of #4324.

Next time please [Search for your issue on github](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github) before filing a bug.

Thanks and happy coding!

**Closed by ltegman** 2015-11-12 16:33 UTC
