### ISSUE TITLE
Input mismatch

### ISSUE THREAD

**Issue by brc1988** [FreeCodeCamp/FreeCodeCamp#4809] opened 2015-11-30 14:42 UTC
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=function%20largestOfFour(arr)%20%7B%0A%20%20var%20longestArray%20%20%3D%20%5B%5D%3B%0A%20%20var%20largeNumber%20%3D0%3B%0A%20%20for(var%20i%20%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%20%0A%20%20%20%20var%20subArray%20%3D%20arr%5Bi%5D%3B%0A%20%20%20%20for(var%20j%3D0%3B%20j%3CsubArray.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20if(largeNumber%20%3C%20subArray%5Bj%5D)%7B%0A%20%20%20%20%20%20%20%20largeNumber%20%3D%20subArray%5Bj%5D%3B%0A%20%20%20%20%20%20%7D%20%20%20%20%0A%20%20%7D%0A%20%20%20%20longestArray.push(largeNumber)%3B%0A%20%20%7D%0A%20%20return%20longestArray%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  var longestArray  = [];
  var largeNumber =0;
  for(var i =0; i<arr.length; i++){ 
    var subArray = arr[i];
    for(var j=0; j<subArray.length; j++){
      if(largeNumber < subArray[j]){
        largeNumber = subArray[j];
      }    
  }
    longestArray.push(largeNumber);
  }
  return longestArray;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

No big issue only there is a difference between input given in test case and input given in program. The test case(2nd one) says as below.
largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]) should return [27,5,39,1001].

But in the code input is different. Hence 2nd test case fails all the time.You can see the the 1st and 2nd index of input array got altered. 

Thanks,

**Comment by SaintPeter** [comment] 2015-11-30 17:56
The problem is that you are not resetting your `largeNumber` variable after each inner loop.  That means that it is retaining the last largest number.  If you copy and paste the failing test to the bottom of your input window you can see the output it is producing.

Issues are not for code help.  Please ask for help in the [Bonfires Help Room](https://gitter.im/FreeCodeCamp/HelpBonfires) instead.

Closing as this is not a site issue.

**Closed by SaintPeter** 2015-11-30 17:56 UTC

**Comment by brc1988** [comment] 2015-11-30 19:46
Thanks Peter. 
I got confused over the inputs.My mistake. 
Thanks again.
