### ISSUE TITLE
What does it mean "quotient should be assigned once"

### ISSUE THREAD

**Issue by marxcom** [freeCodeCamp/freeCodeCamp#14635] opened 2017-04-28 15:29 UTC
Challenge [divide-one-decimal-by-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var quotient = 4.4 / 2.0; // Fix this line



```

**Comment by texas2010** [comment] 2017-04-28 15:30
@marxcom 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by jeetsrs** [comment] 2017-05-01 14:34
I have the same issue... I think you might have closed this in error @texas2010 .
The bug seems to be with the question itself.

**Comment by texas2010** [comment] 2017-05-01 19:15
@jeetsrs, he asked a question.

**Comment by texas2010** [comment] 2017-05-01 19:17
@jeetsrs, he asked a question. 
we can't give provide a help on here.
because GitHub Issues are for reporting bugs on the website only in freeCodeCamp repo.

that is why he have to go chat room or forum for ask a question at there.

by the way, I tested this challenge. I could pass it.

**Comment by awildings** [comment] 2017-05-11 06:08
I think it's a bug.
so i tested it on chrome. it return quotient should be assigned once.
then i tested in firefox and solved.

**Comment by spieg** [comment] 2017-05-16 12:16
As awildings says:
var quotient = 4.4 / 2.0; // Fix this line
runs clean in firefox but gives said error in chrome.

**Comment by jeetsrs** [comment] 2017-05-16 14:50
I was able to move past this, and many others by doing a manual refresh (in Google chrome, pressing <Shift> Refresh)

**Comment by bobbidigi** [comment] 2017-05-23 09:42
This is definitely a bug.  Ol'Texas boy doesn't want to accept it. I'll try jeetsrs advice....

**Comment by texas2010** [comment] 2017-05-23 15:34
@bobbidigi how it could be the bug? can you explain?  I just test it on chrome. I could pass this challenge.

I didn't say I don't want to accept it. I just said I did test it. it seems it is fine to me.

**Comment by raisedadead** [comment] 2017-05-23 15:56
Hi guys, sorry for the confusion if any, I also fail to reproduce the issue as reported here. Can anyone amongst you post some screenshots?

We'll take a look.

Reopening and blocking meanwhile.

**Comment by spieg** [comment] 2017-05-23 17:18
![image](https://cloud.githubusercontent.com/assets/24204953/26366743/786347cc-3fec-11e7-9cae-cc7657c10b23.png)

And the solution is there again .....

**Comment by spieg** [comment] 2017-05-23 17:20
After CTRL-R, the solution will be accepted when submitted.

**Comment by raisedadead** [comment] 2017-05-23 18:36
@spieg Thanks for confirming, by the looks of it I believe this could be something related to the state of the solution being submitted.

I have a strong sense that, doing a hard refresh like you do (Ctrl + R or Cmd + R), reset's the state of the solution, which makes the assignment to be counted as once. While at the times as others report above the state is getting calculated as twice?

Weird.

/cc @freeCodeCamp/moderators any one seen such a case before?

**Comment by tanya53** [comment] 2017-05-29 10:25
I am using Chrome, same error as above, was just going from challenge to challenge, numerous resets of page using reset code option didn't help, tried at least 10 times.

**Comment by tanya53** [comment] 2017-05-29 10:27
tried going into problem from the map (progress) and it said loading saved work and then it passed write away.

**Comment by systimotic** [comment] 2017-07-26 22:21
Hi everyone! Thanks for reporting and confirming this issue.

I'm closing this issue in favour of #13400. It's about the same problem and has more information on steps towards a fix.
If anybody has more information that could be helpful, please add it there.

Happy coding!

**Closed by systimotic** 2017-07-26 22:21 UTC
Labels: beta, discussing, tests
