### ISSUE TITLE
Statistics Calculator: project form submit is triggering document event listener

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53197] opened 2024-01-15 20:17 UTC
### Describe the Issue

- Go to the last step and complete it.
- Use the form and check the browser console.

> Uncaught TypeError: Cannot read properties of null (reading 'match')

Client code throwing:

```
document.addEventListener('submit', function(e) {
  const action = e.target.getAttribute('action');
  e.preventDefault();
  if (action || action.match(/https?:\/\//)) {
    window.parent.window.alert(
      i18nContent.t('misc.iframe-form-submit-alert', { externalLink: action  })
    )
  }
}, false);
```

We can use `stopPropagation` in the project code to prevent this. But I guess as a fix for this it would be a little confusing for the camper. Not sure if we just silently add this code ourselves or if we need another solution to it.

Edit: As pointed out in the thread adding an empty `action` attribute will fix it as well and might be a less intrusive option. We can likely add that silently and not cause too much confusion.

I did not check if other projects using forms are affected by this, but I guess they might be.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator

### Your code

```



```

### Expected behavior

Not throwing errors.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-advanced-array-methods-by-building-a-statistics-calculator/664404

**Comment by jdwilkin4** [comment] 2024-01-15 23:10
> Edit: As pointed out in the thread adding an empty action attribute will fix it as well and might be a less intrusive option. We can likely add that silently and not cause too much confusion.

I vote for this option

**Comment by lasjorg** [comment] 2024-01-16 00:29
I agree, I also just realized they are not asked to write the HTML so it would be easy to add it without it causing any confusion.

**Comment by lasjorg** [comment] 2024-01-16 00:43
Also, does anyone know why we have `return false;` in some of the HTML for the `onsubmit` and if we actually need that?

`<form onsubmit="calculate(); return false;">`

**Comment by jdwilkin4** [comment] 2024-01-16 00:47
> Also, does anyone know why we have return false; in some of the HTML for the onsubmit and if we actually need that?

I think there might be a step to explain that but it has been a while since I went through this project.

I believe @naomi-lgbt would have more context on that cause I think she worked on this project.

**Comment by naomi-lgbt** [comment] 2024-01-16 20:14
The root cause was actually incorrect boolean logic in the injected code. I've pushed a PR to resolve that.

---

Outside of that, I am happy to discuss updating the project:

> I guess technically it is invalid HTML to leave it empty. But I'm not sure if that is a huge issue.

Yes, in HTML 4 the action attribute was required, but in HTML 5 it is optional. If provided, however, it must be non-empty. IMHO we should stick to the standard.

> Also, does anyone know why we have return false; in some of the HTML for the onsubmit and if we actually need that?

Likely not. It *does* call both `preventDefault()` and `stopPropagation()` all at once, AFAIK. I vaguely remember fighting `e.preventDefault()` when building this project (probably related to binding the attribute instead of using a dedicated listener?), but I'm not at all attached to the current implementation and would be happy to switch to a proper event listener.

**Comment by Sembauke** [comment] 2024-04-12 09:49
@naomi-lgbt Could we make a decision on this issue?

**Comment by naomi-lgbt** [comment] 2024-04-12 14:56
This issue was technically resolved by my earlier PR. I think we're fine to close this - we can create a separate issue if we'd like to discuss changing the project to teach different approaches.

**Closed by naomi-lgbt** 2024-04-12 14:56 UTC
Labels: type: bug, status: discussing, scope: curriculum, new javascript course
