### ISSUE TITLE
[beta] error:: Unable to Add my LinkedIn to my Portfolio 

### ISSUE THREAD

**Issue by owususamuel** [freeCodeCamp/freeCodeCamp#14652] opened 2017-04-30 15:08 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by erictleung** [comment] 2017-05-05 07:18
@real-gobs thanks for the issue. I'm unable to reproduce your issue with my own profile. Can you give more information on how you're unable to add your LinkedIn to your profile? Did it give you an actual error banner? Thanks!

**Comment by real-gobs** [comment] 2017-05-06 00:27
In the beta.freecodecamp.com site when I try to add linkedIn to my portfolio, it gives me error about some api issues.

**Comment by erictleung** [comment] 2017-05-06 00:40
@real-gobs ah this is on the beta site. Thanks. I was testing this on the production website. I do get an error.

![image](https://cloud.githubusercontent.com/assets/2754821/25768486/e5ab59f0-31b9-11e7-828b-2c08f42e6a4e.png)

cc/ @BerkeleyTrue

**Comment by IsaacAbrahamson** [comment] 2018-01-22 18:59
@erictleung, @raisedadead 

Adding LinkedIn to profile seems to be broken on the production site. I had a camper on the forums who wasn't able to connect their accounts, so I tried, and I can't either. The error is `failed to fetch user profile`.

Again, this is on the production site, not beta. I wasn't sure if I should start a new issue or not, so I just commented here.

**Comment by ReveurGAM** [comment] 2018-01-22 19:02
I am the camper who told Isaac, and that was my error.  Help!

**Comment by raisedadead** [comment] 2018-01-23 05:15
@IsaacAbrahamson @erictleung thanks for reporting. Can you help us with some screen shots and / or browser console logs?

@BerkeleyTrue @QuincyLarson Can you guys add / ping me details to the LinkedIn Developer Dashboard etc.?

I'll take a look.

**Comment by ReveurGAM** [comment] 2018-01-23 13:06
I was going to post a screenshot for you but, when I tried, instead of getting the error message "failed to fetch user profile" (which appears to be a cut & paste of the message), it returned me to my current exercise abruptly....??!!!

**Comment by raisedadead** [comment] 2018-01-23 13:17
Ah.. okay no worries. Will try and check this. Thanks for reporting, and sorry about the inconvenience.

**Comment by ReveurGAM** [comment] 2018-01-23 13:22
@raisedadead No inconvenience whatsoever.  If I remember, I'll try again later.  I believe someone is working on it, as the LinkedIn button has disappeared just now.
![image](https://user-images.githubusercontent.com/35181004/35277975-2a20be2c-000e-11e8-8009-2af36e0945c2.png)

**Comment by raisedadead** [comment] 2018-01-23 15:56
@ReveurGAM I can see on your profile, LinkedIn seems to correctly working. Can you confirm, that's indeed your profile?

To the best of my knowledge, no one is working on this. I'll check for any logs that may have been captured at our end about the original error.

**Comment by ReveurGAM** [comment] 2018-01-23 16:14
Woohoo!  Someone fixed it! Thanks @raisedadead

**Comment by raisedadead** [comment] 2018-01-23 16:15
> Woohoo! Someone fixed it!

Nope nobody did that...! Its working because of something more complex than this seems. Anyways, I am creating a new issue to track this.

Happy coding.

**Comment by QuincyLarson** [comment] 2018-01-24 04:22
@raisedadead @Bouncey is in the process of removing LinkedIn/Twitter/GitHub linking in favor of just having campers manually copy/paste their usernames or profile URLS. So we just need to fix this for the purpose of our deprecated authentication methods.

**Comment by QuincyLarson** [comment] 2018-01-24 04:38
@ReveurGAM OK - I set all the links associated with our LinkedIn API key to HTTPS (before they were HTTP and that may have been why this suddenly started failing). Could you try again and see if it works for you now?

**Comment by raisedadead** [comment] 2018-01-24 06:59
@QuincyLarson The issue for @ReveurGAM is different and is resolved. 

On beta, we are removing the profile linking as you said. Hence the only issue that remains in #16559 which is about deprecated logins.

We can go ahead and close this thread, if the removal of profile linking is done before beta, is launched.

**Comment by ReveurGAM** [comment] 2018-01-24 13:37
I would just like to comment that I thought having LI, T and GH "integrated" as it was a good idea.  It's a selling point...

@QuincyLarson I would like to try, but since the error was intermittent, it worked for me yesterday and the button no longer exists in my settings on pre-beta FCC.

I would like to note that when I tried to use the LI link to log on to beta, I got this error:
![image](https://user-images.githubusercontent.com/35181004/35334896-793faf24-00d9-11e8-85fa-99fe947209bf.png)

**Comment by ReveurGAM** [comment] 2018-01-24 13:39
I tried adding LI to my beta profile and got the above error, as well.

**Comment by raisedadead** [comment] 2018-01-24 14:39
Yup, this noted bug is getting resolved, by letting users just set a profile URL. As for authentication we have already a different email only approach.

**Comment by QuincyLarson** [comment] 2018-01-24 21:33
@ReveurGAM OK - thanks for your feedback. The account integration was more reliable than asking users to input their own URL, but it also makes it less clear to campers for how they should update these accounts should they create a new one or change the username. That ambiguity is side-stepped if we just have a field they can update.

@raisedadead OK - so it can close this issue then?

**Closed by QuincyLarson** 2018-01-24 21:34 UTC
Labels: beta, bug, status: confirmed
