### ISSUE TITLE
Confusing example in Cafe Menu Step 21

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51872] opened 2023-10-08 19:37 UTC
### Describe the Issue

I am seeing this over and over again in the forum. The example in the instructions uses the selector `#example-id` and for whatever reason people think they need to add `-id` to the end of the `#menu` selector in their solution. And the hint doesn't appear to help much because half the time they will paste the hint verbatim along with their code.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-21

### Your code

Example:

```
#example-id {
  width: 250px;
}
```

Camper solution:

```
#menu-id {
  width: 300px;
}
```

### Expected behavior

I think we need to get rid of the dash in the example. I also think we could improve the instructions by making it clearer how to use the `id` selector.

> The goal now is to make the `menu` `div` not take up the entire width of the page. The CSS `width` property is perfect for this.

> You can use the `id` selector to target a specific element by its `id` attribute. An `id` selector is defined by placing a hash symbol in front of the element's `id` value. For example, if an element has the `id` of `cat` then you would select it by its `id` like this: 

```
#cat {
  width: 250px;
}
```

I also think it might be helpful to answer the question "Why use an `id`?" so people know why we are introducing this selector. We do mention that it allows you to "target a specific element" but that doesn't explain why you would want to do that. But I understand that we want to keep reading down to a minimum so I'm not insisting :slightly_smiling_face: 

### System

N/A

**Comment by dheerajsingh01** [comment] 2023-10-09 08:45
I understand your concern. It seems that there might be some confusion due to the use of the #example-id selector in the instructions, which may lead learners to think that they should use a similar naming convention in their code.

To clarify, you should use the selector that matches the actual element you want to style. In your provided HTML, the element you want to style has the id attribute "menu." So, you should use the #menu selector to target that specific element or clarify with telling we are using instead of  id which is given in line no "10" of index.html. you can clarify with give reference of code you use.

**Comment by mukul-prasad-au9** [comment] 2023-10-09 10:59
Hi there,

I'm excited to contribute to this project, and I'd like to work on this issue. It seems like a great opportunity to dive into the codebase and make a meaningful contribution.

I'll start by reviewing the issue and the provided information. If there are any specific requirements or suggestions, please let me know. I'll be happy to follow the project's coding standards and guidelines.

Looking forward to your feedback and guidance. Thanks for the opportunity!

**Comment by jeremylt** [comment] 2023-10-09 15:13
I wouldn't use an example that is the answer though.

**Comment by lasjorg** [comment] 2023-10-10 21:55
I think the proposed update sounds reasonable.

Maybe we update the instructions as well.

> Create a `#menu` selector and give the selected element a `width` of `300px`.

And also update the test

> The `#menu` selector should set a `width` of `300px` on the element.

Maybe we also add `#` to the sentence?

> ...by placing a hash symbol `#` in front of the...

**Comment by jeremylt** [comment] 2023-10-10 22:20
I like the proposed changes. No question - what's the current convention for using a symbol in a sentence in the curriculum? In mathematical writing, that would be offset by parenthesis or commas, so 'the hash symbol (`#`)' or 'the hash symbol, `#`,' is the grammatically correct usage.

**Comment by lasjorg** [comment] 2023-10-10 23:18
I don't really know, but personally, I'm not a fan of when we use parentheses.

I have seen them being included in the code posted too often. It seems a lot of people can not tell the difference between the syntax inside the code block and the surrounding parentheses. For example (`a`) I have seen multiple times show up in the code as `(a)`.

**Comment by jeremylt** [comment] 2023-10-11 04:49
Yeah, I don't think it's the best option either. I see three choices

1) parenthesis

2) commas

3) just ignore the grammar rules

We should officially pick one and document it

**Comment by HarshitDevsainia** [comment] 2023-10-11 16:37
To Address this Issue .You could Consider the Following Improvement

Update the Example : Instead of Writing examle-id We can write idName so that it simple and more understandable.

Original : 
   #example-id{
        width:250px;
    }

Updated :
     #idName{
           250px;
       }

**Comment by HarshitDevsainia** [comment] 2023-10-11 16:38
To Address this Issue .You could Consider the Following Improvement

Update the Example : Instead of Writing examle-id We can write idName so that it simple and more understandable.

Original :
#example-id{
width:250px;
}

Updated :
#idName{
    width:250px;
}

**Comment by jeremylt** [comment] 2023-10-11 16:42
I think we have already settled on a fix. See the discussion above.

To summarize the proposal as I understand it:

---


Step 21

The goal now is to make the `div` not take up the entire width of the page. The CSS `width` property is perfect for this.

You can use the `id` selector to target a specific `div` element. An `id` selector is defined by a name with a hash symbol `#` directly in front of it, like this:

```
#cat {
  width: 250px;
}
```

Use the `#menu` selector to give your element a `width` of `300px`.

**Comment by jeremylt** [comment] 2023-10-11 16:57
Good catch, I forgot to add that part:

---

Step 21

The goal now is to make the `div` not take up the entire width of the page. The CSS `width` property is perfect for this.

You can use the `id` selector to target a specific element with an `id` attribute. An `id` selector is defined by a name with a hash symbol `#` directly in front of the element's `id` value. For example, if an element has the `id` of `cat` then you would target that element like this:

```
#cat {
  width: 250px;
}
```

Use the `#menu` selector to give your element a `width` of `300px`.

**Comment by naomi-lgbt** [comment] 2023-10-11 17:07
I'd be okay with that change.

**Comment by leftover19** [comment] 2023-10-11 17:35
This issue is not a bug. @bbsmooth I would urge you to close this issue now, not worth the time of other contributors.

**Comment by jeremylt** [comment] 2023-10-11 17:39
@leftover19, we will be making a wording change. Please do not spam this Issue with additional requests that we do not clarify the wording.

**Comment by naomi-lgbt** [comment] 2023-10-11 19:21
Going to go ahead and open this for contribution. An acceptable PR will implement [Jeremy's proposed fix](https://github.com/freeCodeCamp/freeCodeCamp/issues/51872#issuecomment-1758110315).

**Closed** 2023-10-13 12:06 UTC
Labels: type: bug, help wanted, scope: curriculum
