### ISSUE TITLE
RangeError: Maximum call stack size exceeded in "Waypoint: Passing Values to Functions with Arguments"

### ISSUE THREAD

**Issue by miguel550** [FreeCodeCamp/FreeCodeCamp#5607] opened 2015-12-31 02:38 UTC
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myFunction%20%3D%20function(param1%2C%20param2)%7B%0A%20%20console.log(param1%20%2B%20param2)%3B%0A%7D%3B%0AmyFunction(20%2C%2020)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

This is the error throwing "​RangeError: Maximum call stack size exceeded"
![image](https://cloud.githubusercontent.com/assets/3717689/12060409/691ed65c-af45-11e5-867e-a566f3b3edaf.png)

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
var myFunction = function(param1, param2){
  console.log(param1 + param2);
};
myFunction(20, 20);


```

**Comment by ltegman** [comment] 2015-12-31 02:51
Closing as a duplicate of #5560. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 02:51 UTC
