### ISSUE TITLE
X button won't close side Menu bar on iPhone 6

### ISSUE THREAD

**Issue by SAnthoni** [FreeCodeCamp/FreeCodeCamp#6557] opened 2016-01-28 23:54 UTC
Please help, the site changes and loads behind the menu bar, the "x" button will not close the side bar.  True for all safari, bing, chrome, and even using browsec Vpn. Not sure what could be causing this. Wanted to practice waypoints on the phone away from desktop to continue JavaScript lessons. 

P.s. Displayed fine before January 13 approximately. Thanks. 

Sent from my iPhone

**Comment by SAnthoni** [comment] 2016-01-29 00:18
I read issue #6256 which mentioned a possible transform issue with older browsers. I'm on iOS 8. Does anyone suspect that this issue is related to this in some way? Thanks.

**Comment by SaintPeter** [comment] 2016-01-29 02:13
I don't think that's the only problem in iOS.  There are also lots of issues with the sidebar not being able to scroll.  Part of the issue is that all browsers - Safari, Chrome, etc are all required to use Safari's rendering engine, so any problem there is a problem everywhere.

We'll log this as a device specific issue, though.

**Comment by SAnthoni** [comment] 2016-01-29 02:38
Thank you SaintPeter, much appreciated!

**Comment by HTMLNoob** [comment] 2016-01-30 21:48
I'm currently developing a solution for this. BTW, just to clarify, I assume you are using DOM for the click events?

**Comment by bugron** [comment] 2016-02-16 05:51
Thanks for posting. Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256.

**Closed by bugron** 2016-02-16 05:51 UTC
Labels: confirmed, device specific
