### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by SnakeByte2** [FreeCodeCamp/FreeCodeCamp#6148] opened 2016-01-14 06:25 UTC
I was testing different methods trying to grasp the objective. When I decided run  my next solution, I got a bunch of code right under the "run bar". What you see here is only just a part of it. It's fairly long.
I have had a few problems with some of my challenges were not getting validated until the next day when I logged back in. I still have one level that won't pass, unless I'm' missing something simple.

![codecamp screen shot](https://cloud.githubusercontent.com/assets/16656823/12317050/224707e2-ba5b-11e5-9366-5690df222216.PNG)

**Comment by sludge256** [comment] 2016-01-14 06:38
Apart from your last line of code (I assume it is only there for testing purposes) which you should remove, you are supposed to assign (the value of) your variable `a` to the variable `b`.
What you are currently doing is directly assigning the value of 7 to `b` when `a` already has that value.
There is also no need to redeclare the variables as they are declared in the setup code.



The code output window is a known issue.
Closing as duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6111

**Closed by sludge256** 2016-01-14 06:38 UTC
