### ISSUE TITLE
Regular Expressions: Specify Only the Lower Number of Matches

### ISSUE THREAD

**Issue by JS-goose** [freeCodeCamp/freeCodeCamp#34532] opened 2018-12-04 12:50 UTC
**Describe your problem and how to reproduce it:**
On the challenge entitled "Regular Expressions: Specify Only the Lower Number of Matches" the instructions say to "Change the regex haRegex to match the word "Hazzah" only when it has four or more letter z's."  

I provide the code to match 4 or more z's --> 
let haStr = "Hazzzzah";
let haRegex = /Haz{4,}zah/; 
let result = haRegex.test(haStr);

All tests except 'Your regex should match "Hazzzzah"' pass.

I change code to -->
let haStr = "Hazzzzah";
let haRegex = /Haz{3,}zah/; 
let result = haRegex.test(haStr);

And all tests pass.  This shouldn't happen as the instructions say 4 or more

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/specify-only-the-lower-number-of-matches

**Tell us about your browser and operating system:**
* Browser Name: FireFox Quantum 
* Browser Version: 63.0.3 (64-bit)
* Operating System: Windows10 (64-bit)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc-test](https://user-images.githubusercontent.com/30503684/49442908-7da33780-f790-11e8-96c6-60973619fb0b.png)

![fcc-test-1](https://user-images.githubusercontent.com/30503684/49443024-dc68b100-f790-11e8-9f57-650d6415dce4.png)

**Comment by ezioda004** [comment] 2018-12-04 15:32
Hi @JS-goose,

Thank you for opening this issue.
The regex `/Haz{3,}zah/` is also correct because it'll only match 4 z's or more. Note that `z{3,}` will match atleast 3 z's and the "z" after that would be another match. The only difference between `z{4,}` and `z{3,}z` is that in the latter one the last "z" is matched explicitly.

Hope this cleared it up.
Closing this issue, feel free to reopen if you think issue isnt fixed.

Happy contributing!

**Closed by ezioda004** 2018-12-04 15:32 UTC

**Comment by JS-goose** [comment] 2018-12-05 10:41
This makes sense to me know.  The wording on the challenge led me to believe that only 4 (explicitly) would be matched.  Thank you for clearing that up!

**Comment by rickvian** [comment] 2019-05-06 12:20
@ezioda004

Sorry, i was looking for this issue

here is my regex

`/Haz{4,}ah/g

it doesn't match 5 z 

<img width="859" alt="Screenshot_06_05_19_19_17" src="https://user-images.githubusercontent.com/8034141/57224472-c9a22300-7033-11e9-89ae-7eb8f308035e.png">

but when i test it on online regex tester, it should be a match
i think this is a bug, or did i miss something?
<img width="1037" alt="Regular_Expressions__Specify_Only_the_Lower_Number_of_Matches___Learn_freeCodeCamp-2" src="https://user-images.githubusercontent.com/8034141/57224473-c9a22300-7033-11e9-9752-5e92f418698d.png">

**Comment by RandellDawson** [comment] 2019-05-06 14:52
@rickvian You should really check the forum first with these kinds of issues and if those helping you on the forum believe it is a bug, you would report it over here.  The problem is your use of the `g` flag when using `test`.  When using the `g` flag with `test` multiple times (as our behind-the-scenes tests are doing), the lastIndex property of the regex does not get reset each time automatically.  See https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results for more information.  Just remove the `g` flag.

**Comment by VampSinatra** [comment] 2020-11-02 18:34
let haStr = "Hazzzzah";
let haRegex = /Haz{4,}ah/gi; // Change this line
let result = haRegex.test(haStr);
console.log(result);
