### ISSUE TITLE
I cannot click in certain regions of the text editor

### ISSUE THREAD

**Issue by abbygrills** [FreeCodeCamp/FreeCodeCamp#8564] opened 2016-05-11 06:02 UTC
Challenge [Create a Text Field](https://www.freecodecamp.com/challenges/create-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I cannot click anywhere beyond the </ol> on line 46 ( if I click anywhere beyond it, my cursor will fall in front of the </ol>.

I also have this issue on line 45. If I click anywhere beyond the <li, my cursor will just land after the "i" in <li

This has occurred on many of the challenges. Refreshing or restarting the browser has helped in most cases.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>

```

**Comment by raisedadead** [comment] 2016-05-11 11:29
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Closing as duplicate of #7847

**Closed by raisedadead** 2016-05-11 11:29 UTC
