### ISSUE TITLE
Code displaying issue

### ISSUE THREAD

**Issue by spestook** [FreeCodeCamp/FreeCodeCamp#3120] opened 2015-09-06 12:26 UTC
The Waypoint: Add Rounded Corners with a Border Radius challenge http://freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius has an issue. 

Screenshot 1 - on Google Chrome for Mac, Version 45.0.2454.85 (64-bit)
<img width="1265" alt="waypoint__add_rounded_corners_with_a_border_radius___free_code_camp" src="https://cloud.githubusercontent.com/assets/9061728/9704300/9c8f9f3a-54aa-11e5-9876-dd78b27200fb.png">

Screenshot 2 - Same browser as above
Action taken: I clicked inside the code editor
<img width="1267" alt="waypoint__add_rounded_corners_with_a_border_radius___free_code_camp" src="https://cloud.githubusercontent.com/assets/9061728/9704309/28b70b56-54ab-11e5-88fc-e8c002f0d2ac.png">

Note: Ad blocking, script blocking extensions were all disabled at that time. This issue has been found on Mozilla Firefox, Version 40.0.3

**Comment by bugron** [comment] 2015-09-06 12:47
@spestook thank you very much for such a detailed description of your issue! We are aware of this issue. Unfortunately, it is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2707 so I'll close it. You can continue further discussion there.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-06 12:47 UTC
