### ISSUE TITLE
E-mail is updated without appropriate verification

### ISSUE THREAD

**Issue by samanthakem** [FreeCodeCamp/FreeCodeCamp#11033] opened 2016-10-03 07:52 UTC
#### Issue Description

E-mail is updated without verification. (read steps below and see gif on the end of this description)
1. Sign in with your e-mail and password
2. Click on your image
3. Click on Update My Settings button
4. Click on Update My E-mail button
5. Type a random e-mail and click on Verify e-mail button
6. Sign out of Free Code Camp
7. Try sign in with the e-mail and password that you used on step 1. -> error
8. Click on Forgot password button
9. Type the e-mail you used on step 1 and click in Reset password
**ISSUE: It says your original e-mail is not found -> it means your account e-mail was updated without the verification. Try to sign in with the random e-mail you typed on step 5 and your original password -> YOU ARE ABLE TO SIGN IN :O 👎** 
#### Browser Information

- Browser Name, Version: Firefox 47.0
- Operating System: OS X El Capitan 10.11.6
- Mobile, Desktop, or Tablet:  Desktop

![bug](https://cloud.githubusercontent.com/assets/4277045/19030451/c569459a-8902-11e6-8274-5c9c22823150.gif)

**Comment by Munsterberg** [comment] 2016-10-03 16:57
Recreated this in Firefox 49.0.1

**Comment by Bouncey** [comment] 2016-10-05 12:22
@QuincyLarson @raisedadead Is this intended behaviour?

**Comment by raisedadead** [comment] 2016-10-17 13:21
Yes, in my opinion this is intended citing the following conditions:

1. While the email address is updated as soon as the user enters it in step 5, it's still flagged as **not verified** in the system.

2. The email can be updated only by an authenticated user, hence if at all the user randomly enter and email, (which would be weird.. why would you do that), we know its status and won't be sending the emails communications to any unverified mail id.

3. Of course a ideal fix is that we store the old as well as the new emails, and wait till the user verifies. But that's a additional cost at no real gain.

Now let's consider a actual use case where the user accidentally locked themselves by entering an "incorrect" (not being random) email and then before realizing the mistake logged themselves out as well. I feel this is real corner case which may be handled by support.

I am not denying that we could save old/new mails but considering the fact that we are moving to passwordless auth and this is a corner case it may be considered to be closed as a wontfix.

That's my two cents. Wait for other opinions please.

**Comment by raisedadead** [comment] 2016-11-29 17:20
Closing with the comment above.

/cc @BerkeleyTrue @QuincyLarson

**Closed by raisedadead** 2016-11-29 17:20 UTC
Labels: accounts
