### ISSUE TITLE
Restrict Possible Usernames: problem description is incorrect

### ISSUE THREAD

**Issue by quinetime** [freeCodeCamp/freeCodeCamp#18079] opened 2018-09-03 05:51 UTC
[The Restrict Possible Usernames assignment](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames) asks you to write a regexp for a username that meets the following criteria:

1. The only numbers in the username have to be at the end. There can be zero or more of them at the end.
2. Username letters can be lowercase and uppercase.
3. Usernames have to be at least two characters long. A two-letter username can only use alphabet letter characters.

But the check algorithm says “Your regex should not match 007”. This is incorrect. By the above criteria, 007 is a valid username. All the numbers are at the end. It’s at least two characters long. It is not a two-letter username and so it does not need to use only alphabet letter characters.

Currently, something like /^[a-z]{2,}\d*$|^[a-z]\d{2,}$|^\d{3,}$/i would work.  But I think the problem is with the problem description, not the check algorithm.  I think what’s intended in (3) is that the first two letters of the username should be alphabet letters. But that’s not what the problem says. So this should be changed. 

(Also, I note that the solution given in the hints section uses curly brackets, which haven’t been taught yet. I think the solution for the intended question should be given as /[a-z][a-z]+\d*$/i ).

**Comment by alhazen1** [comment] 2018-10-13 19:16
I've been looking at this one too and have run into a similar issue to @quinetime. 

Based on where this challenge lies in the curriculum  **I think that the password requirements need to be simplified so a solution can be found that only uses material already covered.**  A solution that handles all cases that meet the current requirements is probably beyond the scope of the lesson.

As the requirements stand now A11 and 007 _should  be_ valid usernames. Including these cases makes the regex much too complex for the lesson. 

Maybe something like this ( but reworked for clarity)
1. Must contain two or more letters - case insensitive
2. Must be at least two characters long
3. Can contain numbers but only at the very end of password
4. Cannot contain characters other than letters or numbers

Based on material already covered I think all cases would be adequately tested using a regular expression like `/^[a-z][a-z]+\d*$/i` 
^[a-z][a-z]+ - Two or more letters from start of string (quantity specifier has not been covered yet)
\d* followed by zero or more numbers
followed by end of string (insures entire string matched, no characters past numbers)

This would allow passwords such as
Slackmonkey
Slackmonkey123
Me
Me100
but not allow
A100
A
007
Sl@ckm@nkey
1Slackmonkey

That said, there is more wrong with the challenge than just the instructions. One can easily submit a 'passing' solution that does not check most cases. Right now pretty much any regex that matches two letters passes.
https://github.com/freeCodeCamp/freeCodeCamp/issues/17882#issue-341320968

Any passing regular expression should test that all numbers are only at the end of the string and should match the entire string, not just a portion of it.

**Comment by thecodingaviator** [comment] 2018-10-17 07:35
@QuincyLarson what do you suggest, either we can work on writing advanced RegEx tests for the repo or we can remove the rules from the challenge for now.

**Comment by bikingbadger** [comment] 2018-12-11 13:41
Duplicate of #17733

**Comment by moT01** [comment] 2018-12-11 13:50
Closing in favor of the duplicate mentioned

**Closed by moT01** 2018-12-11 13:50 UTC
