### ISSUE TITLE
I want to learn html,css and javascript but the website is not loading ! 

### ISSUE THREAD

**Issue by mohammadhani110** [freeCodeCamp/freeCodeCamp#17399] opened 2018-06-02 20:22 UTC
![asd](https://user-images.githubusercontent.com/34722336/40880555-b85d5d92-66cc-11e8-89c0-782db20662cb.PNG)
![capture](https://user-images.githubusercontent.com/34722336/40880556-b8903c94-66cc-11e8-90c2-6a67f01b9189.PNG)

**Comment by raisedadead** [comment] 2018-06-02 20:45
I think this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17360 Can you confirm your general region as in the other issue thread?

**Closed** 2018-06-02 20:46 UTC
Labels: support: general
