### ISSUE TITLE
code in practice area missing at first 

### ISSUE THREAD

**Issue by FizzyDre** [FreeCodeCamp/FreeCodeCamp#2944] opened 2015-09-01 04:51 UTC
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Upon first entering this page part of the code is missing at first. the top part p to Line 11 is present and everything past line 11 is missing . upon clicking in the actual black area in the page the code reappears. I was able to replicate this upon refreshing the page. additonally at the end of the page once done with the session and pressing CTRL +Enter. the pop up to get to the next page did not appear  Upon refreshing this issue resolved itself so a screen capture was not made. 
![code camp bug 1](https://cloud.githubusercontent.com/assets/13664999/9596476/2e9536a4-502a-11e5-8700-9057c7c5ad3f.png)

**Comment by iheartkode** [comment] 2015-09-01 15:15
![codemissing](https://cloud.githubusercontent.com/assets/7018580/9608097/7c9886e2-5081-11e5-8f2c-14e454452d1b.png)
I can confirm it seems it's missing code.. Not sure if the other code was intentionally left out?

**Comment by bugron** [comment] 2015-09-01 16:03
@FizzyDre thanks for posting this issue!
This issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2707, so I'm closing it.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-01 16:03 UTC

**Comment by FizzyDre** [comment] 2015-09-01 16:14
It was not intentionally missing code. that is how it appears when I first went  to the page. the Code re-appears quickly when you click anywhere in the black area. however it did cause confusion when first looking at the assignment and trying to comply only to realize that code is missing. i was happy when the code did reappear .And refreshing the page only caused the issue to occur again. So there is a bug or some sort of issue that is causing this.

**Comment by FizzyDre** [comment] 2015-09-01 16:15
thanks! glad you are aware :)
