### ISSUE TITLE
Fix typo and improve instruction.

### ISSUE THREAD

**Issue by marksist300** [freeCodeCamp/freeCodeCamp#48872] opened 2022-12-30 17:38 UTC
### Describe the Issue

The current explanation for the description of a binary Search is:
```
    Find the middle value of a sorted array. If value == target return (found it!).
    If middle value < target, search right half of array in next compare.
    If middle value > target, search left half of array in next compare.
```
Maybe for the top line we could rephrase the (found it!) part so people don't confuse this part with the coding challenge, also we could make it clearer with something more generic "return `true`. (The value has been found)."
I think we could also include the base case for when a value is not present in the given array, for example "return `false` (The value is not present in the array").

Also in the instruction there's a line:

```If value not is found, ``` 
Which should be:
```If the value is not found```

I'm happy to work on it: I'll submit a PR  linked to this issue. 🙂

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-binary-search

### Your code

Issue noted above

### Expected behavior

Remove typo and improve clarity of instructions

### System

Not a system error

**Comment by thebarshablog** [comment] 2022-12-31 06:12
Hi @marksist300 I'd like to take on the issue and solve this.

**Comment by marksist300** [comment] 2022-12-31 07:59
> this.

Thank you 😊, but I've already sent the pull request with the changes it's just awaiting approval.

**Comment by thebarshablog** [comment] 2022-12-31 08:20
Hey @marksist300, since you mentioned that the issue is still awaiting an approval, its better to keep it open. Once, the changes are approved, you may close it [suggestion].

**Comment by gikf** [comment] 2022-12-31 09:26
> return (found it!)

This is definitely worded in a strange way. Similarly _If value not is found_ should be corrected.


> Maybe for the top line we could rephrase the (found it!) part so people don't confuse this part with the coding challenge, also we could make it clearer with something more generic "return `true`. (The value has been found)."
> I think we could also include the base case for when a value is not present in the given array, for example "return `false` (The value is not present in the array").

Including specific returned value would make it less generic. The first time I looked at it, it appeared to me as a contradiction to what challenge wants to be returned.

What do you think about something like this:
> If `value == target` the search is finished.

Adding another step addressing not finding value in the array might be a good idea, but in a context when that happens exactly. At which point whole array was searched.

**Comment by marksist300** [comment] 2022-12-31 09:37
> > return (found it!)
> 
> This is definitely worded in a strange way. Similarly _If value not is found_ should be corrected.
> 
> > Maybe for the top line we could rephrase the (found it!) part so people don't confuse this part with the coding challenge, also we could make it clearer with something more generic "return `true`. (The value has been found)."
> > I think we could also include the base case for when a value is not present in the given array, for example "return `false` (The value is not present in the array").
> 
> Including specific returned value would make it less generic. The first time I looked at it, it appeared to me as a contradiction to what challenge wants to be returned.
> 
> What do you think about something like this:
> 
> > If `value == target` the search is finished.
> 
> Adding another step addressing not finding value in the array might be a good idea, but in a context when that happens exactly. At which point whole array was searched.

Yes, I agree. Have just added a little extra clarification around these point in my PR 👍🏻🙂

**Closed** 2023-01-11 15:11 UTC
Labels: type: bug, help wanted, scope: curriculum
