### ISSUE TITLE
After I complete the "Waypoint: Use a CSS Class to Style an Element", it keeps giving me a bad gateway error, and it won't let me continue.  

### ISSUE THREAD

**Issue by tlovett88** [FreeCodeCamp/freecodecamp#1603] opened 2015-08-06 15:48 UTC
I have completed the challenge, but no matter what network I am on, it gives me a bad gateway error and I am not able to continue with the next challenge.  Since I am new to coding, I don't know what to do 

Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by catapixel** [comment] 2015-08-06 17:22
@tlovett88 I saw that this was happening to others and that they are working to resolve it but in the meantime you should just use the map to move on to the next challenge.

**Comment by rtw314** [comment] 2015-08-06 18:42
I found that if you remove the / from one of the li element closing tags, the lesson considers that objective to be met

**Comment by BerkeleyTrue** [comment] 2015-08-11 20:05
This is a duplicate of #1386 

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-11 20:05 UTC
