### ISSUE TITLE
Enable deletion of solutions from Portfolio

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#1411] opened 2015-07-29 05:26 UTC
I've completed a couple of Bonfire's successfully and realized there was an issue that floated past the test. I'd love to be able to remove these solutions from my portfolio page.

**Comment by kurzninja** [comment] 2015-07-31 04:06
+1

**Comment by benschenker** [comment] 2015-08-26 06:47
Thanks for the suggestion!

This is a duplicate of #1342, keep track of that for updates on this request.

**Closed by benschenker** 2015-08-26 06:47 UTC
