### ISSUE TITLE
HTML - "Use Comments to Clarify Code" - Code Mirror Auto-Adds closing Mark

### ISSUE THREAD

**Issue by KrisVos130** [FreeCodeCamp/FreeCodeCamp#4453] opened 2015-11-15 13:27 UTC
On the challenge "Use Comments to Clarify Code" you are asked to make a comment. When you make a comment, the editor automatically puts the `-->` behind the `<!--` typed by the user. Then when you try to complete the challenge, it says you don't have a closing comment tag. It might have something to do with the character(s) looking like the same character(s) but actually being a different character(s).

**Comment by SaintPeter** [comment] 2015-11-15 17:21
This is pretty obnoxious.  It looks like our code editor, Code Mirror, is auto-adding the closing comment mark.  This is clearly an issue and needs to be corrected.

**Comment by BerkeleyTrue** [comment] 2015-11-15 21:00
This is expected behavior (in the commonFramework) to prevent other issues from cropping up. This is being removed in the refactor of the commonFramework.

**Comment by bugron** [comment] 2015-12-03 09:02
Unable to reproduce this anymore, closing.

**Closed by bugron** 2015-12-03 09:02 UTC
Labels: confirmed, on the roadmap
