### ISSUE TITLE
Editor bug - Cannot place cursor where I want to with the mouse

### ISSUE THREAD

**Issue by stefanos82** [FreeCodeCamp/FreeCodeCamp#8709] opened 2016-05-19 00:13 UTC
I'm using Firefox ESR 45.1.1 on GNU / Linux Debian 64-bit, testing.

I cannot place my cursor wherever I want to and not only that; if I press "Enter" key, instead of taking me on the next line, it skips 1 extra line.

Also, when this issue happens, the tab key stops working properly; it moves only at a single tab click and nothing more.

UPDATE: I have also noticed that Ctrl - arrow-left or arrow-right does not nagivate beyond two or three columns before it jumps to the immediate next line.

Is it something that has to do with code-completion mechanism?
END_OF_UPDATE

It happens on each test and at first I thought it was my idea.

Any suggestions?

Cheers.

**Comment by raisedadead** [comment] 2016-05-19 05:21
Thanks. Closing as a duplicate of #7847. Requesting you to continue the conversation there.

P.S: Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Closed by raisedadead** 2016-05-19 05:21 UTC
