### ISSUE TITLE
Errors when running `mongod` in local setup 

### ISSUE THREAD

**Issue by mjiang108** [freeCodeCamp/freeCodeCamp#45784] opened 2022-04-25 23:54 UTC
## Affected page

https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally

## To reproduce

I was trying to set up freeCodeCamp locally on my macOS machine. Already had prerequisites installed, did all steps with no problem until "Step 3: Start MongoDB and seed the database." I ran `mongod` and got error `NonExistentPath: Data directory /data/db not found. Create the missing directory or specify another path using (1) the --dbpath command line option, or (2) by adding the 'storage.dbPath' option in the configuration file.`

## Recommended fix, suggestions

Apparently this is [a common issue with an easy solution](https://stackoverflow.com/questions/58283257/mongodb-cant-find-data-directory-after-upgrading-to-mac-os-10-15-catalina). Solution: create a data/db directory and use the --dbpath flag, or start mongo using homebrew. I don't know anything about the technical details, but I prefer the latter because that's what's on the [official docs](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#run-mongodb-community-edition) for MongoDB. I tested this method and it works (I can finish the rest of the setup steps).

Since the dev likely installed mongo with homebrew, I propose changing the freeCodeCamp instructions like so

> Start the MongoDB server in a separate terminal:
> macOS/Linux
> ```
> # macOS
> brew services start mongodb-community@5.0
> # linux
> mongod
> ```
> Tip
> If you have problems starting MongoDB, or to install it as a background service to avoid having to start it every time, visit [their documentation for your OS](https://docs.mongodb.com/manual/administration/install-community/) for help

Note: I have not tested the linux command, but if it was previously correct then it should still be
## Screenshots

<img width="1108" alt="Screen Shot 2022-04-25 at 4 48 06 PM" src="https://user-images.githubusercontent.com/9983876/165192368-2e0eea26-f108-47e8-9add-95abfd6b63ae.png">

**Comment by ShaunSHamilton** [comment] 2022-04-26 10:26
Hello there,

Thank you, for taking the time to open this. However, this is not an issue with the freeCodeCamp repository/setup.

Whilst this is a common error, the `mongod` command still works on most machines as intended.

If you are getting errors when running any of the commands, it is likely an issue with your setup:
- File permissions are not what they need to be
- File permissions prevent the installation from being 100% successful
- One or more used packages need to be updated for a successful installation

The suggested verbiage changes look redundant to me, because we already expect Campers to go to the official docs to see how to download MongoDB for their specific device.

As such, I am going to close this issue. If you face any more issues, I suggest reaching out on the [forum](https://forum.freecodecamp.org/).

**Closed by ShaunSHamilton** 2022-04-26 10:26 UTC
Labels: other: device specific
