### ISSUE TITLE
The problem solve condition one makes it so that all the slots are the same

### ISSUE THREAD

**Issue by LuckyOreo** [FreeCodeCamp/FreeCodeCamp#2712] opened 2015-08-26 01:46 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In this challenge, the step one of the solve condition "Use the provided code three times. One for each slot" works on the premise the code `$($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');` is copied and entered three times.  The solution is not solved if the user directly enters in the correct solution without copying and pasting the code.
This seems like an unnecessary step.

**Comment by benschenker** [comment] 2015-09-03 05:02
Thanks for posting this!

This is a duplicate of #2111 please see that issue for updates on this.

**Closed by benschenker** 2015-09-03 05:02 UTC
