### ISSUE TITLE
Feature Request: Scroll to Top Button

### ISSUE THREAD

**Issue by JoT8ng** [freeCodeCamp/freeCodeCamp#56563] opened 2024-10-06 21:38 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When scrolling on pages on freeCodeCamp, reading articles, and accessing parts of the curriculum I feel like there is a lot of content and I have to scroll for a long time. It would be nice to have a scroll to top button on the bottom right corner to navigate back to the top of the page.

### Describe alternatives you've considered

Alternatively, some sort of navigation menu with the sections on the page to allow users to jump to certain sections instead of scrolling back and forth.

**Comment by akshaymishra-01** [comment] 2024-10-07 03:10
Hi @JoT8ng 

I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

I have experience with the required tech stack, I'm excited to work on building the code snippet generator.

Looking forward to your response!

Thanks,
Akshay Mishra

**Comment by chiragmalik2612** [comment] 2024-10-07 05:35
i want to work on this , please assign

**Comment by sameer6699** [comment] 2024-10-07 05:53
Steps to Implement the Scroll to Top Button:
1. Add Scroll to Top Button in the HTML (or JSX if using React)
You need to add a button that appears after the user has scrolled down the page. The button will be positioned at the bottom right corner.

2. Add Styling for the Button
To ensure the button is always visible at the bottom right of the screen and styled appropriately, add CSS. You can customize the appearance to match the freeCodeCamp theme.

3. Add JavaScript to Control Visibility and Scrolling
Now, add JavaScript to control when the button is displayed and how it behaves when clicked. The button will appear after the user scrolls down a certain amount, and on click, it will smoothly scroll the page back to the top.

4. Ensure Accessibility
Keyboard Accessibility: The button should be focusable using keyboard navigation (tabindex="0").
ARIA Label: Ensure proper accessibility labeling with the aria-label="Scroll to Top" attribute on the button.

I would like to work on this issue please guide me how can I solve this issue

**Comment by gikf** [comment] 2024-10-07 06:18
Hi @akshaymishra-01 @chiragmalik2612 @sameer6699,

Issue has not been triaged yet, and a solution has not been agreed upon. Until that the issue is not open for contribution.

Additionally we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by JacksonRoberts-Git** [comment] 2024-10-07 18:21
Hi! Is there any chance I could claim or otherwise be assigned to this bug? I am relatively new to GitHub but I want to see if I can help you with this

**Comment by gikf** [comment] 2024-10-07 18:30
Hey @JacksonRoberts-Git,

check out this comment - https://github.com/freeCodeCamp/freeCodeCamp/issues/56563#issuecomment-2395998807

**Comment by ilenia-magoni** [comment] 2024-10-07 19:14
only issues with the `help wanted` label are open for contribution

**Comment by lasjorg** [comment] 2024-10-08 15:43
Not sure if we need a scroll to top button. Maybe on mobile or a keyboard without a Home button it could be useful.

---

But I do think giving easier access to the table of content after you scroll past it would be nice.

It could be implemented as a sticky sidebar that triggers after you scroll past the TOC, maybe with a visual indication of what section you are scrolled to. It could have a scroll to top link as well. An example of this would be how Wikipedia has it.

Not sure how easy it is to implement without changing the current layout too much. The TOC would likely need to be implemented as a partial.

**Closed** 2024-10-28 13:39 UTC
Labels: scope: UI, status: waiting triage, type: feature request
