### ISSUE TITLE
ES6: Use export to Reuse a Code Block - fails looking for exports keyword instead of export

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16354] opened 2017-12-28 17:08 UTC
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/use-export-to-reuse-a-code-block

#### Issue Description

When attempting to export the variable in two different methods, the challenge fails with "exports is not defined"

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js


Method 1:

`"use strict()";
export const foo = "bar";
export const boo = "far";`

Method 2:

`"use strict()";
const foo = "bar";
const boo = "far";

export {foo, boo};`


```
#### Screenshot

Method 1:
![image](https://user-images.githubusercontent.com/22984739/34417647-9c01c74e-ebc7-11e7-8f1d-5a13650b27ce.png)

Method 2: 

![image](https://user-images.githubusercontent.com/22984739/34417682-bdef0e7a-ebc7-11e7-9fad-30fabb3c1893.png)

**Comment by systimotic** [comment] 2017-12-28 21:37
Thanks for all of the QA work @mstellaluna! I'm closing this as a duplicate of #16235

**Closed by systimotic** 2017-12-28 21:37 UTC
Labels: beta

**Comment by TazzyG** [comment] 2018-06-20 22:02
It looks like this issue is still not fixed..   export {foo, boo}; shows in results // running test
foo is exported.
bar is exported.
// tests completed 
but fails

**Comment by Crounty** [comment] 2018-06-25 01:42
Exactly.

If you export bar only it won't even show up as exported.

**Comment by Tirjasdyn** [comment] 2018-06-27 18:22
Neither option works. Nothing happens if you use the first option. The console can't even print the error, it's too long. The second option passes the test in the log window but both options are still gray X.

**Comment by badarshahzad** [comment] 2018-07-05 06:15
I think my code is correct but still, it gave me an error any suggestions?
![issue](https://user-images.githubusercontent.com/19945367/42305500-a2d9134e-8044-11e8-9cf8-8e8b90212cca.png)

**Comment by mohitsinghdz** [comment] 2018-07-10 06:16
why not "export {foo, bar}" working?

**Comment by Naxiden** [comment] 2018-07-10 11:38
challange is broken i suppose

**Comment by Amilight** [comment] 2018-07-11 11:48
@mohitsinghdz  @Naxiden In problem It is explicitly mentioned to use first method as opposed to second.

**Comment by QuanVOLEMINH** [comment] 2018-07-11 21:55
@badarshahzad's solution worked for me.
Please use `Alt Shift F` to format code.

**Comment by kalzimonium** [comment] 2018-07-14 02:20
This challenge along with others are broken. This is my solution and it doesn't even do anything when I run the test:
const export foo = "bar"
const export bar = "foo

I am leaving them for now until they're fixed. Going to contact Quincy or whoever.

**Comment by sedmo** [comment] 2018-07-15 21:10
@kalzimonium switch const and export

**Comment by kalzimonium** [comment] 2018-07-16 16:42
@sedmo. You’re right. I got it twisted, but still didn’t work. Not even export { foo, bar } work. I’ve tried different browsers and still the same.

**Comment by kalzimonium** [comment] 2018-07-17 04:08
@aryafathur nope, still didn’t work.

**Comment by BrNaka** [comment] 2018-07-22 23:09
@badarshahzad posted the solution. Add a space after the variable 'bar'.

Do not work: 
`export const foo = "bar";`
`export const bar= "foo";`

Works:
`export const foo = "bar";`
`export const bar = "foo";`

**Comment by malachimc** [comment] 2018-08-03 18:13
The answer is:

"use strict";
export const foo = "bar";
export const bar = "foo";
