### ISSUE TITLE
Rewrite same code

### ISSUE THREAD

**Issue by rohanayush** [FreeCodeCamp/FreeCodeCamp#12280] opened 2016-12-30 15:22 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by rohanayush** [comment] 2016-12-30 15:25
I have to again write the same code to work. First I have to delete a line in code suppose by using cut and then on pasting it ,the same code again works fine.

**Comment by raisedadead** [comment] 2016-12-30 15:44
Looks like a duplicate of #7847. Can you check and follow the workaround mentioned there?

**Comment by rohanayush** [comment] 2016-12-30 15:58
No its little different because just deleting one word or letter and then rewriting them doesn't works. I have to delete the whole line and write it again to work

**Comment by raisedadead** [comment] 2016-12-30 16:04
I would recommend you try the workaround about pressing <kbd>enter</kbd>, once or twice and report. (Not delete anything).

Also, please share screenshots, the OS and Browser details as requested in the issue template and developer console logs (F12) --> Console tab.

**Comment by rohanayush** [comment] 2016-12-30 17:15
![browserdetails](https://cloud.githubusercontent.com/assets/19414281/21569247/26881120-cee1-11e6-9315-1a5c4269803c.JPG)
![afteroneenterbeingpressed](https://cloud.githubusercontent.com/assets/19414281/21569260/425cb806-cee1-11e6-90b4-20fa446d4acc.JPG)
![state1](https://cloud.githubusercontent.com/assets/19414281/21569270/57eb64ce-cee1-11e6-9281-116e5f99e934.JPG)
State 1 is without any time enter being pressed,second one (AfterOneEnterBeingPressed.jpg) after hitting enter once .
I have Windows 8.

**Comment by rohanayush** [comment] 2016-12-30 17:17
For clarity: For above comment-
  1. Browser details
  2.After enter has been pressed once
  3.Without enter being pressed
OS-windows 8

**Comment by raisedadead** [comment] 2016-12-30 17:40
I am afraid the Screenshots do not help in understanding the issue... 😞 ! Do you have the console logs as stated in my comment above.

You can reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need help in reporting the issue.

**Comment by rohanayush** [comment] 2016-12-30 17:50
I had hit enter in the 10th line of code  i.e., after  ($(".target.nth-child(2)))              <enter pressed by me then>
.
.
").addClass("animated bounce");

Is this what you asked me for?

Excuse me, as I am new and thank you for your patience to look into the matter. :)

**Comment by raisedadead** [comment] 2016-12-30 17:52
@rohanayush lets switch to the chat: [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by systimotic** [comment] 2017-01-04 23:23
@rohanayush @raisedadead Any updates on this?

**Closed** 2017-01-05 07:16 UTC
