### ISSUE TITLE
Words are not contained within the code block on a smaller screen Solution in Technical documentation Project example

### ISSUE THREAD

**Issue by YagneshP** [freeCodeCamp/freeCodeCamp#40226] opened 2020-11-13 16:42 UTC
**Describe your problem and how to reproduce it:**
In the Technical documentation project, words are not contained within the code block, 

**Add a Link to the page with the problem:**
[Technical documentation Page](https://codepen.io/freeCodeCamp/full/NdrKKL)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version:  86.0.4240.183
* Operating System: Window10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![FCCproblem](https://user-images.githubusercontent.com/29221654/99096456-4789a780-25a4-11eb-811f-cb4eafeb02f9.PNG)

**solution**
~~~diff
- code{  white-space:  pre }

+code{  white-space: pre-line } /* for samller screen max-width:600px */
~~~

**Comment by sidram05** [comment] 2020-11-14 05:16
Can I work on this one ?

**Comment by ieahleen** [comment] 2020-11-14 07:33
@sidram05 I don't think you can, the issue is in the sample project on CodePen.

If you haven't done so, read our contributing docs contribute.freecodecamp.org, and look at the issues tagged with "first timers only" (if it's your first time contributing to freeCodeCamp) and "help wanted"

**Comment by RandellDawson** [comment] 2020-11-14 22:14
@ieahleen @sidram05 The source code that is used on Codepen is located https://github.com/freeCodeCamp/testable-projects-fcc/tree/master/src/projects/technical-documentation-page, so you can submit a PR to that repo and reference this issue if you want to contribute.  Once the PR is merged, we currently manually update the Codepen using the source code in the repo.

**Comment by gikf** [comment] 2021-03-12 19:30
Closing issue as this appears to be fixed a while ago in https://github.com/freeCodeCamp/testable-projects-fcc/pull/1250 and pen with project was updated for this.

**Closed by gikf** 2021-03-12 19:30 UTC
Labels: scope: learn
