### ISSUE TITLE
[RPG project] Unable to progress in Step 93

### ISSUE THREAD

**Issue by codewithkin** [freeCodeCamp/freeCodeCamp#52933] opened 2024-01-03 22:28 UTC
### Describe the Issue

The "Check your code" button is not working in this challenge.

I have finished the challenge, however when I click the "Check your code: button, nothing happens and I am unable to progress

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-93

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-93'
2. Click on 'Check your code'
3. Scroll down to anywhere
4. See error: Nothing happens

### Expected behavior

It should throw an error(if the code is incorrect), show tests running(when checking the code) or (if correct) let the user proceed

### System

- Device: HP Notebook 250G7
- OS: Kali Linux
- Browser: Firefox
- Version: 115.6

**Comment by Kashinathpat** [comment] 2024-01-04 06:37
@codewithkin I think Code You added to the solution is wrong I added `text.innerText += " In your inventory you have: ";` on line `96` and code passed Successfully.

**Comment by jdwilkin4** [comment] 2024-01-04 11:38
I tried out the lesson and was also able to pass and move onto the next lesson.

We are going to close this issue due to being unable to reproduce the error.

If you are experiencing issues with your code, then please open up a post on the forum or discord and people can assist you there 👍

**Closed by jdwilkin4** 2024-01-04 11:38 UTC
Labels: type: bug, scope: curriculum, status: waiting triage, new javascript course
