### ISSUE TITLE
stand in line

### ISSUE THREAD

**Issue by mwandama** [FreeCodeCamp/FreeCodeCamp#10216] opened 2016-08-15 16:23 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment] 2016-08-15 16:48
Closing as incomplete duplicate of #10217

**Closed by BKinahan** 2016-08-15 16:48 UTC
