### ISSUE TITLE
Miss md file when testing translations locally in chinese curriculum

### ISSUE THREAD

**Issue by masterX89** [freeCodeCamp/freeCodeCamp#47407] opened 2022-08-28 11:14 UTC
**Describe the bug**
I got an error about missing chinese `14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62cc5b1779e4d313466f73c5.md` file when I want to test the chinese localization of RespWebDesignNew in curriculum

**To Reproduce**
1. Go to `config/i18n/all-langs.ts` file
2. add `SuperBlocks.RespWebDesignNew` in `chinese` of `auditedCerts` following [how-to-test-translations-locally](https://contribute.freecodecamp.org/#/how-to-test-translations-locally?id=releasing-a-superblock) guide
3. run `npm run develop`

**Expected behavior**
will see chinese client and curriculum in localhost

**Screenshots**
<img width="900" alt="image" src="https://user-images.githubusercontent.com/8510146/187070446-1b658013-0a4e-4132-8131-89ed53b9271f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**How to fix it**
1. First we will find that there are only 58 md files in the `chinese/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/` folder, but there are 59 files in the english folder, so something must be missing.
2. After comparing the content, I found that the content of step-4 uses the content of step-5, so step-4 content is missing.
3. Add the correct content in step-4 file
4. Add content of step 5 in a new 62cc5b1779e4d313466f73c5.md file
5. Each step after step 5 is incremented by one
6. add `SuperBlocks.RespWebDesignNew` in `chinese` of `auditedCerts`
7. run `npm run develop`
8. will see the error is fixed

**Comment by ieahleen** [comment] 2022-08-29 07:52
The file needs to be translated and approved on crowdin, and then downloaded by the automatic pipelines, until then freecodecamp builds will fail

**Comment by ieahleen** [comment] 2022-08-30 10:33
it can be fixed by the chinese translators and proofreaders translating and approving those steps

**Comment by naomi-lgbt** [comment] 2022-09-08 19:02
Going to close this as this is intended behaviour. Our build validation fails if an audited certification does not have all of the challenges translated.

As noted in the contributing documentation, testing translations locally may require getting a download from Crowdin.

**Closed by naomi-lgbt** 2022-09-08 19:02 UTC
