### ISSUE TITLE
[beta] Flexbox challenge 3 issue

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12868] opened 2017-01-26 06:10 UTC
Css Flexbox: Using the Flex-direction Property to Make a Row
http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-flexdirection-property-to-make-a-row

The challenge passes without input or correct/requested solution.

**because**
`display:flex;`
is equivalent to 
```
display:flex;
flex-direction:row;
```

**Comment by ajain17** [comment] 2017-01-26 18:46
The fix for https://github.com/freeCodeCamp/freeCodeCamp/issues/12864 should fix this as well. I have a PR for the fix already. Let me know if I should create the PR ?

**Comment by HKuz** [comment] 2017-01-26 19:09
Thanks for pointing this out @tommygebru - this is actually a duplicate of issue #12814 for this challenge, so I'm going to close this issue. Also, I'm in the process of consolidating all the Flexbox section to-dos (I think we can address most of the outstanding issues in one PR). I'll post the action items in issue #12803, which will include the good points you make about the div sizes.

@ajain17 - awesome you've already started a fix for this! If you don't mind waiting a bit for me to grab a list of fixes for this section, you can help clear a number of issues at once. I'll tag you over on issue #12803 when I do this 👍

**Closed by HKuz** 2017-01-26 19:09 UTC
Labels: beta

**Comment by ajain17** [comment] 2017-01-26 19:12
@HKuz  sure. I'll wait to fix them all in on PR. Keep me posted.
