### ISSUE TITLE
unclear instructions or lack of explanatory content maybe?

### ISSUE THREAD

**Issue by NicolasVsa** [freeCodeCamp/freeCodeCamp#35002] opened 2019-01-30 16:15 UTC
so im doing the javascript challenges and i noticed:

In this ES6 [challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/) map(), filter(), and reduce() seem to come out of nowhere without an explanation on how they work or even how to use them and in the challenge itself you are expected to use them js this challenge maybe should be positioned somewhere else within the curriculum maybe?

**Comment by RandellDawson** [comment] 2019-01-31 20:06
This appears to be a duplicate of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/14903.  Please refer to the issue and make any additional comments/suggestions there.

Thank you.

**Closed by RandellDawson** 2019-01-31 20:06 UTC
