### ISSUE TITLE
Logo overlay on narrow screens

### ISSUE THREAD

**Issue by DiegoCascavita** [freeCodeCamp/freeCodeCamp#49985] opened 2023-04-06 16:12 UTC
### Describe the Issue

When the user uses FreeCodeCamp on narrow screens like the Samsung galaxy fold, the FreeCodeCamp logo overlaps with the drop-down menu button and profile picture at the top of the page.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23'
2. Open the developer tools
3. in dimensions select "Galaxy fold".
4. See the .png example in the screenshots section

### Expected behavior

As a suggestion in this type of screens <= 280px * 653px we could remove the FCC fire logo or remove the profile picture to follow the responsive design rules.

### Screenshots

![bug](https://user-images.githubusercontent.com/72409256/230436682-f44427bd-dc01-4d3c-a97c-9a914a0657b0.png)

### System

- Device: [Laptop, Samsung Galaxy Fold, Pc]
- OS: [Android 12L ,Windows 11]
- Browser: [Chrome, OperaGx]

**Comment by Sboonny** [comment] 2023-04-06 16:38
Bruce mentioned the possibility of changing the logo in this PR too https://github.com/freeCodeCamp/freeCodeCamp/pull/49942#issuecomment-1496285708

I am kinda in favor, because of how many people started to associate freeCodeCamp with fCC, so change in logo may be possible.

**Comment by Sboonny** [comment] 2023-04-06 16:40
btw, the logo is on higher stack above the menu, so it isn't possible to click it.

If we aren't changing the logo, changing the layout is the other option.

**Comment by DiegoCascavita** [comment] 2023-04-06 17:46
Hi @Sboonny, What do you think about leaving only the "FreeCodeCamp" logo and removing the `fire` symbol? I think it would look more aesthetic xD and all the space would be fixed.

**Comment by anuraghagawane** [comment] 2023-04-06 19:23
I have solved this issue by dropping the fire icon.
This is how it looks like.
https://user-images.githubusercontent.com/83091222/230474568-06e84d89-fe85-4131-b5b7-5f3470d5532e.mp4

**Comment by Sembauke** [comment] 2023-04-06 19:28
Hey @DiegoCascavita,

If you are working from a mobile Android device we recommend downloading the freeCodeCamp mobile app, which has a good mobile experience for the Responsive Web design certification.

**Comment by Sembauke** [comment] 2023-04-06 19:30
> I have solved this issue by dropping the fire icon. This is how it looks like. https://user-images.githubusercontent.com/83091222/230474568-06e84d89-fe85-4131-b5b7-5f3470d5532e.mp4

Hey @anuraghagawane,

Thank you for making this change, although this works, it is in violation of our style guidelines. Please see them here:
https://design-style-guide.freecodecamp.org/

**Comment by anuraghagawane** [comment] 2023-04-06 19:37
> > I have solved this issue by dropping the fire icon. This is how it looks like. https://user-images.githubusercontent.com/83091222/230474568-06e84d89-fe85-4131-b5b7-5f3470d5532e.mp4
> 
> Hey @anuraghagawane,
> 
> Thank you for making this change, although this works, it is in violation of our style guidelines. Please see them here: https://design-style-guide.freecodecamp.org/

yeah, I was thinking that it will go against the guidelines. I think putting the "sign in" button inside the "hamburger menu" for small screens can be a possible solution.

**Comment by bbsmooth** [comment] 2023-04-06 20:16
> it is in violation of our style guidelines

If I am reading the guidelines correctly then just the glyph can be used.

> we recommend downloading the freeCodeCamp mobile app

I'm sure the app is fine, but the web-based version should provide just as good an experience as the mobile app or we are doing something wrong.

**Comment by naomi-lgbt** [comment] 2023-04-07 04:11
> If I am reading the guidelines correctly then just the glyph can be used.

Yes. It probably wouldn't hurt to have a breakpoint that switched to the glyph, though I feel like this has been brought up (and turned down) before?

@ahmadabdolsaheb might have more insight.

**Comment by Aribaskar-jb** [comment] 2023-04-07 18:48
@Sembauke @DiegoCascavita  Hello, I am available to work on this issue. I believe I can solve this up

**Comment by Aribaskar-jb** [comment] 2023-04-08 00:21
@anuraghagawane you can help me to set up the project in my local system

**Comment by Aribaskar-jb** [comment] 2023-04-08 05:27
I have resolved the Navbar logo responsiveness bug in the Galaxy Fold
This is how it looks like.
![image](https://user-images.githubusercontent.com/85920362/230704869-04458620-485a-4e88-893e-270dc8278716.png)

**Comment by Vivekyadav-4321** [comment] 2023-04-09 05:44
```diff
- my name is vivek

**Comment by Vivekyadav-4321** [comment] 2023-04-09 05:45
```diff
- my name is vivek
+ my name is vivek yadav

**Comment by ahmadabdolsaheb** [comment] 2023-04-11 12:15
We could go with the glyph or make the logo a bit more responsive. Either way would work.

**Comment by Sboonny** [comment] 2023-04-12 20:45
Because there are 4 PRs opened doing the same thing, I want to clear the requirement to close this issue.

---

The CSS solution, the issue is cased by the existing property of `position: absolute` in `#universal-nav-logo`, removing it and refactoring the layout of the navbar, will sort the issue as shown below, without the need to add another break point.

[rec-screen.webm](https://user-images.githubusercontent.com/88248797/231577647-5bb8d2ac-59d7-47d2-83dd-b92429519b10.webm)

Why am I against adding a break point? because it's a solution to a side effect and not the solution to the real cause of the issue

---

The HTML solution, use `picture` element with fallback to glyph SVG.

**Comment by Sboonny** [comment] 2023-04-12 20:49
For context, either solution is an enhancement to the navbar, so if a PR is fixing the CSS, while the other is changing the picture element, I wouldn't mind approving both, as both will be an enhancement to the current navbar.

But maybe it's better to choose one option, before opening this for contribution so I am pushing it to triage again.

**Comment by lasjorg** [comment] 2023-04-18 15:49
@Sboonny Shouldn't the `universal-nav-left` element be conditionally rendered using the `Media` component instead of just being empty? That way it won't push the logo and the logo doesn't have to be position absolute.

`client/src/components/Header/components/universal-nav.tsx`

Code we have now
```
<div
  className={`universal-nav-left${displayMenu ? ' display-search' : ''}`}
>
  <Media minWidth={SEARCH_EXPOSED_WIDTH + 1}>{search}</Media>
</div>
```

`Media` wrapping the element instead.
```
<Media minWidth={SEARCH_EXPOSED_WIDTH + 1}>
  <div
    className={`universal-nav-left${
      displayMenu ? ' display-search' : ''
    }`}
  >
    {search}
  </div>
</Media>
```


I only looked at this briefly so I will admit I might have missed something.

**Comment by Sboonny** [comment] 2023-04-18 17:31
> @Sboonny Shouldn't the universal-nav-left element be conditionally rendered using the Media component instead of just being empty? That way it won't push the logo and the logo doesn't have to be position absolute.

Yeab, you are correct.

**Closed** 2023-04-19 10:43 UTC
Labels: type: bug, status: waiting triage
