### ISSUE TITLE
confusing description

### ISSUE THREAD

**Issue by JanMP** [FreeCodeCamp/FreeCodeCamp#2043] opened 2015-08-18 10:06 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the description
Let's take the code we had last time and unshiftthis value to the end: "Paul"

it should read "start" instead of "end"

**Comment by saadanerdetbare** [comment] 2015-08-21 17:19
duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1929

**Comment by dokkillo** [comment] 2015-08-21 17:35
@JanMP  if it is duplicate please close issue :)

**Closed** 2015-08-21 23:43 UTC
