### ISSUE TITLE
Ambiguous instructions for Reg Form Step 31

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51923] opened 2023-10-11 21:49 UTC
### Describe the Issue

The current instructions say:

> Add `I accept the terms and conditions` text to the newly added `label`, then link the text `terms and conditions` to the following location:

But they don't specifically say where the new text should be added within the `label`. If you add the text before the `input` (with the anchor correctly added to the text) then you get the following hint:

> You should use an a element to link to the terms and conditions.

This creates even more confusion since the anchor was added correctly.

I think these instructions are relying on the fact that the text for the radio buttons was added after the `input` and thus the assumption is that the text for the check box should also be added after the `input`. And I agree that usually the text for radio buttons/check boxes is placed after the `input`, but this is not a requirement. Also, in step 26 when we have them add the text for the radio buttons, we explicitly say "immediately after the `input` element", so it seems like this is important information to add.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-31

### Your code

N/A

### Expected behavior

Change the instructions to:

> Add the text `I accept the terms and conditions` immediately after the `input` element in the newly added label. Then link the text `terms and conditions` to the following location:

~~I also threw in the required space since the tests will complain if it isn't there.~~  I should have done better testing :slightly_smiling_face: The tests don't care if there is a space between the `input` and the text.

We might also want to update the tests so it gives a better hint if they put the text before the `input`.

### System

N/A

**Comment by jeremylt** [comment] 2023-10-12 16:03
I like the proposed change in wording.

**Comment by jeremylt** [comment] 2023-10-12 16:27
@shaikshahid98 the issue is not marked as ready for contribution yet.

**Comment by bbsmooth** [comment] 2023-11-20 03:37
This issue has been around for a while and I'm still seeing it come up in the forums. Do we need any more discussion on this? Two things to fix in this PR:
- Update instructions to make it clear that the text comes after the `input`
- Fix the test that is erroneously telling the user they need to add an anchor element when it is already there.

**Comment by ojeytonwilliams** [comment] 2023-11-20 09:14
>  Do we need any more discussion on this?

I don't think so, no. The requirements are nice and clear, thanks!

**Closed** 2023-11-28 21:57 UTC
Labels: type: bug, help wanted, scope: curriculum
