### ISSUE TITLE
myVar++ not updating when code is changed

### ISSUE THREAD

**Issue by khamp19** [freeCodeCamp/freeCodeCamp#14510] opened 2017-04-20 16:37 UTC
Challenge [increment-a-number-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myVar = 88;

// Only change code below this line
myVar = myVar++;


```

**Comment by jaynagpaul** [comment] 2017-04-21 02:07
myVar++ is the same as writing myVar = myVar + 1. So just writing myVar++ will set myVar to 89, while myVar = myVar will set it to undefined.

**Comment by JoolsMcFly** [comment] 2017-04-21 09:10
Instructions say

> The entire line becomes `i++;`, eliminating the need for the equal sign.

**Comment by erictleung** [comment] 2017-04-21 18:41
@khamp19 there are two things incorrect in your code. The one that others have mentioned, but also, you've manually changed the value of `myVar` to 88.

There is another bug for this challenge. I use the correct code and I can't get it to pass with

```js
var myVar = 87;

// Only change code below this line
myVar++;
```

And I had an issue with the second test

> `myVar = myVar + 1;` should be changed

The challenge test can be found on [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/2913c5c353de7bdf75e864d634b1c0415c9cc02e/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L523) and essentially has this regex test

```
/myVar\s*\=.*myVar\s*\+\s*1/.test(code) === false
```

**Comment by aliuk2012** [comment] 2017-04-22 10:41
I'm also getting the same error

**Comment by bobbi216** [comment] 2017-04-22 11:29
Same here

**Comment by X-T-G** [comment] 2017-04-26 11:50
this is my code,and i have passed this course,just like this :
var myVar = 87;

// Only change code below this line
myVar ++;
var myVar;

**Comment by ooade** [comment] 2017-05-08 07:50
@erictleung worked ere on Google Chrome 58.0.3029.96 (64-bit) and Opera 44.0.2510.1218 (64-bit)

**Comment by devsks** [comment] 2017-05-18 15:12
Is this bug resolved? or can I fix it?

**Comment by charlesBak** [comment] 2017-05-25 18:24
This challenge does not have any bug, solution of @erictleung pass the challenge.

**Comment by erictleung** [comment] 2017-05-30 06:27
@charlesBak thanks for checking up on this. I am now unable to reproduce the error I've posted above. If someone else can verify this is the case, I will go ahead and close this issue as resolved.

cc/ @freeCodeCamp/moderators

**Comment by charlesBak** [comment] 2017-05-30 06:35
hi @erictleung i am also unable to reproduce the error, tested on Chrome and firefox.

**Comment by anujsinghwd** [comment] 2017-05-30 07:24
this is the post increment so this incremented after assign for pre-increment use ++myVar

**Comment by fai3** [comment] 2017-06-01 19:33
@khamp19 @aliuk2012 
 apply this so that you can proceed to the next page:
var myVar = 87;

// Only change code below this line
myVar++ ;
myVar = 88;

**Comment by georgianole** [comment] 2017-06-05 17:55
I am also having this problem. It will not verify that the line is changed.

**Closed** 2017-09-02 01:32 UTC
Labels: bug

**Comment by nagendrababu2** [comment] 2019-01-21 18:49
var myVar = 87;

// Only change code below this line

myVar++;
 var myVar;


This works fine give a try
