### ISSUE TITLE
We were unable to verify your trophy from Microsoft's learning platform.

### ISSUE THREAD

**Issue by tawfiqkhalilieh** [freeCodeCamp/freeCodeCamp#51427] opened 2023-08-29 17:12 UTC
### Describe the Issue

When I'm trying to collect the trophies in the **Foundational C# with Microsoft** it's showing me that the backend is crashing ( 500 status code ) and showing me the message "We were unable to verify your trophy from Microsoft's learning platform.
"
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/f38443b8-4c95-4cdd-b60a-c0467997624a)

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/'
2. Solve the questions
3. Connect to your Microsoft account
4. collect your trophy 

### Expected behavior

To collect the trophy without errors or at least show me if I've done anything wrong.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/36577595-555a-4713-8932-2a195cc160f0)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/ffa2b58f-43fe-4684-ab36-5f43b04e109c)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/a57cb5a4-9cb3-426f-8d73-391f36d45ce0)

### System

- Device: PC
- OS: Windows 11
- Browser: Brave ( chromium )
- Version: Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)

**Comment by raisedadead** [comment] 2023-08-29 22:55
Duplicate of #51419

**Comment by tawfiqkhalilieh** [comment] 2023-08-30 07:02
Hello @raisedadead, I just want to mention that I don't think that there are any invalid URLs in this request. please let me know if I'm mistaken.
![freecodecamp-trophy-bug](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/5c2fba94-ea8a-45a4-8105-aab931db55a8)

**Comment by ShaunSHamilton** [comment] 2023-08-30 07:21
@tawfiqkhalilieh Did you complete the necessary modules on Microsoft's platform?

<img width="572" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/63f71fee-a872-436e-ac03-89bc34234d8f">

**Comment by tawfiqkhalilieh** [comment] 2023-08-30 08:40
Just double-checked and found that I was missing a module, Sorry for disturbing.

**Comment by ojeytonwilliams** [comment] 2023-08-30 08:49
Not at all, @tawfiqkhalilieh, this is useful info. Also, this seems to be a different issue to https://github.com/freeCodeCamp/freeCodeCamp/issues/51419 since that is about linking accounts and this is about claiming trophies, so I'm reopening it.

@moT01 is it possible to distinguish between the cases where the learner hasn't got that trophy (i.e. this case) and where something else failed in the verification process? If so, we could give a more specific message to guide the learner.

**Comment by RBercasio22** [comment] 2023-08-31 12:13
How to fix the issue?

**Comment by sametuca** [comment] 2023-08-31 12:33
I'm telling you how to solve it. on the microsoft learning page
Delete your profile from your profile picture/settings at the top right.
Then create a microsoft learning profile again and if you are asked to upload your old information, answer no. Start and finish with the "write your first c# code" tutorial as the first tutorial. then copy the link to your transcript page.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/15572023/266c7333-8c05-4ba0-ab13-a463ac5566b2)

**Comment by Khalid-Osman** [comment] 2023-08-31 12:40
Same issue here. I have 12 badges on Microsoft Learn profile page but 0 trophies.

**Comment by danielancines** [comment] 2023-09-01 09:28
Same here, We were unable to verify your trophy from Microsoft's learning platform. Any thoughts?

**Comment by raisedadead** [comment] 2023-09-01 09:58
<img width="843" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/4d1b1416-118c-4e0d-80af-39d05c6030c4">

**Closed by raisedadead** 2023-09-01 09:58 UTC
Labels: type: bug, scope: UI, type: showstopper

**Comment by raisedadead** [comment] 2023-09-01 10:09
For anyone arriving here please note you are likely missing a step that needs to be completed in the list of the sections for the certification.
