### ISSUE TITLE
[BETA] Seed code and lesson both don't load sometimes

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#16865] opened 2018-03-09 14:50 UTC
#### Issue Description
Please see the screenshot. I'm adding only the screenshot and a short description for now in case this issue is already reported and is a duplicate. A search for existing issues did not turn up anything, so if this really is a new issue I'll add any required details.

I haven't been able to figure out exactly how to reproduce this, but I have seen it in both the local dev environment as well as on the actual beta site. It seems like when the server has been restarted and I use a URL to get to specific challenge, then the challenge does not load and just says "Happy Coding".

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot
![image](https://user-images.githubusercontent.com/148813/37213202-0c939708-2390-11e8-8e8f-65784516c128.png)

**Comment by raisedadead** [comment] 2018-03-09 15:15
Hi @tchaffee thanks for reporting. Yes, this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/16865

**Closed by raisedadead** 2018-03-09 15:15 UTC
