### ISSUE TITLE
Border width not properly validated 

### ISSUE THREAD

**Issue by cheesethief** [FreeCodeCamp/FreeCodeCamp#1495] opened 2015-08-04 03:43 UTC
In Waypoint: Add Borders Around your Elements, the requirement is:

Give your image a border width of 10px.

However, this does not check for actual pixel width.  This test is passed with any border width (1px, 5px, 50px, etc.)

**Comment by jbmartinez** [comment] 2015-08-16 21:34
This is a duplicate of #1090

**Closed** 2015-08-26 00:14 UTC
