### ISSUE TITLE
Cannot pass <hr /> test in Applied Visual Design test

### ISSUE THREAD

**Issue by phavor** [freeCodeCamp/freeCodeCamp#18230] opened 2018-10-02 11:42 UTC
#### Describe your problem and - if possible - how to reproduce it
I have written the code to add the `<hr />` tag in the Visual Design exercise. But I won't pass the test. 

#### Add a Link to the page with the problem
This is the link https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element

#### Tell us about your browser and operating system

* Browser Name: Firefox Developer Edition and Chrome
* Browser Version: 63.0b10
* Operating System: Linux Ubuntu 16

#### If possible, add a screenshot here
![hr](https://user-images.githubusercontent.com/32136420/46346551-4e613480-c640-11e8-9bea-b068c041788e.png)
![hr_error](https://user-images.githubusercontent.com/32136420/46346552-4ef9cb00-c640-11e8-8e88-43865440b319.png)

**Comment by Dayfiri** [comment] 2018-10-02 13:49
Remove  `div class = "cardTitle" ></div>` and it will work. 
I know this is not place for helping but just pointing out it is not a bug.

![aasdas](https://user-images.githubusercontent.com/16082563/46352681-a9078a00-c65a-11e8-85b0-8dc1e01834d0.png)

**Comment by phavor** [comment] 2018-10-02 16:55
Thanks @Dayfiri . It's pretty easy to look over, I couldn't see any specific instruction on getting rid of that div.

**Comment by Nirajn2311** [comment] 2018-10-02 17:37
@phavor could you close this issue if it solved?

**Comment by RaspberryLime** [comment] 2018-10-03 08:52
> Thanks @Dayfiri . It's pretty easy to look over, I couldn't see any specific instruction on getting rid of that div.

The instructions never asked for it to be added to start with. If you reset the code on the challenge you’ll see it’s not there by default.

**Closed** 2018-10-03 09:16 UTC
