### ISSUE TITLE
Content issue - "Show the local weather" challenge.

### ISSUE THREAD

**Issue by Pixelbark** [freeCodeCamp/freeCodeCamp#8988] opened 2016-06-06 10:43 UTC
Hi all,

I'm going to be REALLY blunt about this.

Earlier this year, google made the following statement:
# 

"Chrome has public intent to deprecate powerful features like geolocation on non-secure origins, and we hope that others will follow.

Starting with Chrome 50, Chrome no longer supports obtaining the user’s location using the HTML5 Geolocation API from pages delivered by non-secure connections. This means that the page that’s making the Geolocation API call must be served from a secure context such as HTTPS."
# 

Between google blocking it, and adblocking extensions (wildly used by many people) blocking geolocation calls from external services like freegeoip.net. Should this assignment be reassessed?

I personally will be skipping this task, but if we're asking others to create a piece for their portfolio which has the potential to not work on their potential employer's website, then should a replacement task be implemented? 

P.S.
Apologies for not using the forum, I felt that this was a discussion that was more apt for the repo itself.

**Comment by erictleung** [comment] 2016-06-06 22:04
"Geolocation API removed from unsecured origins in Chrome 50"

Source: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

**Comment by fkingn00bGG** [comment] 2016-06-07 08:26
We could replace this but there are many ways around this and this is actually a perfect opportunity to show students one of the many difficulties of designing apps for the web. That is we will get incompatibility issues. For example you could degrade gracefully by telling users whose browser does not support `navigator.geolocation` to enter a zip code and country instead.

In saying so, it is possible other browsers will adopt secure connections only for `navigator.geolocation` which will render this exercise broken in its current state so something must be changed.

**Comment by MayankPratap** [comment] 2016-06-10 17:53
navigator.geolocation was never useful because everytime we run app browser asks confirmation.   There are other ways around.  I used ip-api.com to get user's coordinates.  Here is my project :- http://mayankpratap.github.io/local-weather-app/

**Comment by AbdiViklas** [comment] 2016-06-22 18:53
Just a little "bump" here to say that THE TEXT OF THIS PROJECT SHOULD BE ALTERED ASAP. As it stands, the syllabus first teaches you about navigator.geolocation, then drops you into this project with the comment, "We recommend using the Open Weather API." The student is left to bang their head over the problem before finding that the two can't work together, and it seems a bit silly to set them up for failure and then wait for them to find the answer here, or in the forum, or on Gitter (where everyone else gets tired of explaining it several hundred times per day).

Just to be clear, the problem is:

1. `navigator.geolocation` only works over https
2. openweather.org doesn't (for free)

Many suggest, and even the example pen shows, getting location by IP. I feel like this is not best practice, especially in a mobile-first age, because of [these kinds of issues](http://forum.freecodecamp.com/t/why-does-location-not-work/13501).

There is a solution that is functional and (comparitively) elegant.

1. Add `https` to your codepen URL. Make sure you share the URL that way, and maybe put an error alert in prompting the user to do so in case anybody gets hold of an http version
2. Use `navigator.geolocation`
3. Use Forecast.io. They work over https, they're free, and--best part--they have a matching set of gorgeous, animated icons!

As far as I know, this issue and its solutions have been known for over a month. Meanwhile, dozens of campers per day plow into it. I move that the wording of the page be changed IMMEDIATELY, at least to make people aware of the problem. I also move that a note be added to the [geolocation checkpoint](https://www.freecodecamp.com/challenges/get-geolocation-data) to mention that it won't work, in Chrome, without https.

**Comment by thoragio** [comment] 2016-07-20 14:38
I think the FCC folks are leaving "We recommend using the Open Weather API" in place just to give everyone completing this assignment a little taste of "real world challenges" :-).

I hit up against the same problem a few weeks ago and ended up just looking for another weather API that would give me HTTPS access for free.  I found wunderground.com as a result and it works fine.

That being said, I am left wondering why a simple change to the text on this challenge has been left untouched for so long.

**Comment by oliverjam** [comment] 2016-11-10 15:03
FYI Forecast.io (or Dark Sky as they seem to be known now) doesn't appear to work anymore. They don't allow CORS, so I keep getting this error: `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

**Comment by smiller171** [comment] 2016-12-22 18:20
I'll have an SSL proxy up before the end of the day for OpenWeatherMap. I'm happy to let others use this proxy and put it in the instructions for this challenge.

**Comment by smiller171** [comment] 2016-12-22 19:23
Use `https://weather.millergeek.xyz/` instead of `http://openweathermap.org/` Is just an SSL proxy

**Comment by greaneym** [comment] 2017-01-18 15:34
It's understandable that FCC wants people to experience the "this doesn't work, I wonder why" phenomenon about api interfaces.  But it is also important to get information that allows one to complete a task successfully and the wording of the challenge should be changed to say, "find a weather api" instead of suggesting using one that is known not to work.  I think that would provide a more positive experience.

**Comment by ArielLeslie** [comment] 2017-01-18 15:36
@greaneym No one is arguing that the challenge shouldn't be updated.  That's why this Issue shows "Open" and "confirmed".  It's on the list of things that need to be fixed.

**Comment by thoragio** [comment] 2017-01-18 16:09
Hi, it was fixed on 24 August in commit [fbf962f211d3a9227ada485c666d813f54c580af](https://github.com/freeCodeCamp/freeCodeCamp/commit/fbf962f211d3a9227ada485c666d813f54c580af) to the staging branch. Not sure why it has not made it to the live site though. I just checked the [challenge page](https://www.freecodecamp.com/challenges/show-the-local-weather) and it still is displaying the old text.

**Comment by tholman** [comment] 2017-05-22 15:37
CodePen is going to be going ALL `https` in the coming month or so.

Which will be breaking this pen and exercise completely (https://www.freecodecamp.com/challenges/show-the-local-weather),  since open weather map has SSL as a paid feature http://openweathermap.org/price (for shame, really!)

Wondering if there's anything I can do to help out here.

**Comment by edusantana** [comment] 2017-05-22 17:45
I was able to get the city name from `https://ipapi.co/json/`, I used it inside pen and it is working!

`curl https://ipapi.co/json/`

**Comment by kettultim** [comment] 2017-06-02 15:41
Confirmed @tholman's comment.. the example codepen is broken. Obviously we can glean what needs to be done for the task but the example is unnecessary at this point, especially regarding the rule of not copying any code.

**Closed** 2017-09-02 01:29 UTC
Labels: codepen, resolved in staging
