### ISSUE TITLE
Motivational quote quotation marks not showing up

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42937] opened 2021-07-20 02:58 UTC
Noticed this on a local build just now:

![Screen Shot 2021-07-19 at 9 51 27 PM](https://user-images.githubusercontent.com/20648924/126254906-987a6545-ac7a-4440-a64f-2c1eae717efa.png)

It's the quote on the `/learn` page. Not sure if it's something with my browser or machine - I've never noticed it before. Maybe I'll dig into it and see if I can find where the problem is.

**Comment by mrvishalsharma** [comment] 2021-07-20 05:07
sir, I understand the problem but can you guide me the exact path from were i can view this problem.

**Comment by Nirajn2311** [comment] 2021-07-20 06:09
I couldn't reproduce this in either Chrome, Edge, Firefox or Safari.

**Comment by Sembauke** [comment] 2021-07-20 08:50
> I couldn't reproduce this in either Chrome, Edge, Firefox or Safari.

Are you on the latest main?

**Comment by MonikaPatelIT** [comment] 2021-07-20 09:22
Checked on live site and quotes are working for me. Tested on Chrome, Edge, Firefox and even of IE 11
![image](https://user-images.githubusercontent.com/9668906/126295707-5a73e579-1071-4ef6-83ed-52ca4807d095.png)

I think we should close this issue.

**Comment by Nirajn2311** [comment] 2021-07-20 09:57
> > I couldn't reproduce this in either Chrome, Edge, Firefox or Safari.
> 
> Are you on the latest main?

Yup, I even checked through gitpod also.

**Comment by Sembauke** [comment] 2021-07-20 10:15
@Nirajn2311, They do appear on the Italian version.

**Comment by Nirajn2311** [comment] 2021-07-20 10:38
Ahh I dint check the other languages.

**Comment by raisedadead** [comment] 2021-07-20 10:52
Tom, I am fairly confident this is some encoding set locally to your browser/machine. Would you mind checking your "language and region", etc. or whatever their equivalent is on your machine(s)?

**Comment by Sembauke** [comment] 2021-07-20 11:00
> Tom, I am fairly confident this is some encoding set locally to your browser/machine. Would you mind checking your "language and region", etc. or whatever their equivalent is on your machine(s)?

It seems that this only appears on the Italian version of the freecodecamp website. Therefore I don't think it is something local. 
check it out here live on the website: https://www.freecodecamp.dev/italian/learn

**Comment by raisedadead** [comment] 2021-07-20 11:04
Life is simpler one google search away: https://italian.stackexchange.com/questions/69/should-one-prefer-or
@ieahleen what do we prefer? IMHO we leave it as is?

**Comment by ieahleen** [comment] 2021-07-20 11:32
@raisedadead can leave as it is, in Italian those angular quotes (or guillemet as I just learned they are called) are commonly used - so much that I was not understanding what was wrong in the first image

**Closed** 2021-07-20 11:42 UTC
Labels: status: discussing

**Comment by moT01** [comment] 2021-07-20 12:10
> It seems that this only appears on the Italian version of the freecodecamp website.

Nice catch @Sembauke - I knew I had Italian running, but it didn't occur to me that it might be the issue.
