### ISSUE TITLE
Again reload problem here

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#7829] opened 2016-03-31 18:16 UTC
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Link to page:

https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0A%0A

![javascript i f_ - https___www freecodecamp com_chall](https://cloud.githubusercontent.com/assets/10551051/14186192/1e993282-f74b-11e5-9a97-7c079d92125f.jpg)

**Comment by interglobalmedia** [comment] 2016-03-31 18:17
And it just keeps on trying to reload. I have various levels of this problem, sometimes better, sometimes much worse, sometimes the site crashes.  Thought I would share a screenshot so you would see what is going (or not going) on.

**Comment by raisedadead** [comment] 2016-03-31 18:56
Hi @interglobalmedia !

Thanks for reporting this.

We are sincerely sorry for the performance issues with regards to the website.
And as I mentioned yesterday, we are aware of this and are working on it. 

[Here is a post on our sub-reddit](https://www.reddit.com/r/FreeCodeCamp/comments/4cm7o7/has_fcc_become_very_slow/d1jzumi) by Quincy @QuincyLarson giving the details.

We understand and share your frustration with this issue. This is not a problem with specific challenges, but with the infrastructure of our site. We have a potential fix planned to roll out on Saturday. These issues are all related to one root problem so there's no need to file additional issues.

Of course please feel free to continue the discussion on this thread. Or ping us on the [Help Chat](https://gitter.im/FreeCodeCamp/Help) Room.

Closing as duplicate of #7818

**Closed by raisedadead** 2016-03-31 18:56 UTC
