### ISSUE TITLE
Error while typing solution (Chrome, tested 5 times, always breaks)

### ISSUE THREAD

**Issue by warkentien2** [FreeCodeCamp/FreeCodeCamp#2126] opened 2015-08-18 22:05 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

while trying to type $($(".slot")[0]).html(slotOne);
program freezes, having to close and reopen tab.

however pasting $($(".slot")[0]).html(slotOne); works fine.
something about $($) while typing messes everything up

**Comment by jbmartinez** [comment] 2015-08-21 21:29
Duplicate of #1960

**Closed** 2015-08-21 21:58 UTC
