### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue 

### ISSUE THREAD

**Issue by crowesam** [FreeCodeCamp/freecodecamp#610] opened 2015-05-27 03:27 UTC
Cleared to go to next challenge while teh tasks listed were still  showing red X circles instead of check mark of completion.

**Comment by terakilobyte** [comment] 2015-05-27 14:31
I've been unable to reproduce this. Closing the issue as I'm unable to duplicate this in both firefox and chrome. Thanks for the report, if you encounter it again please repoen this issue with a screenshot.

**Closed by terakilobyte** 2015-05-27 14:31 UTC
