### ISSUE TITLE
Commenting out the link to Lobster font-family doesn't render correctly.

### ISSUE THREAD

**Issue by TheDoctorsLife** [FreeCodeCamp/FreeCodeCamp#8022] opened 2016-04-10 04:13 UTC
#### Challenge Name
Specify How Fonts Should Degrade

https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade

#### Issue Description

The issue occurs when commenting out the link to the Lobster font family from googleapis.com. To reproduce just comment out that line of code and watch as it does degrade

#### Browser Information

* Browser Name, Version: Chromium version 49.0.2623.110 (64-bit)
* Operating System: Linux 4.4.6_1 Void Linux (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<!--
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family:  Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

#### Screenshot
![Exsample code removed #1](http://i.imgur.com/BoxJ9Fs.png)
![Exsample code removed #2](http://i.imgur.com/rn4msf4.png)
![Monospace Removed](http://i.imgur.com/GzcYTq0.png)

**Comment by erictleung** [comment] 2016-04-10 16:47
@TheDoctorsLife I'm not able to reproduce this. 

@FreeCodeCamp/issue-moderators any ideas on why this is happening?

**Comment by hallaathrad** [comment] 2016-04-10 18:39
Possibly already passed this challenge before? It seems to work well on all my setups.

**Comment by TheDoctorsLife** [comment] 2016-04-10 19:16
This issue showed before I passed, I just went back later so I could report it.

**Comment by raisedadead** [comment] 2016-04-11 04:21
@TheDoctorsLife Can you try this challenge in incognito mode and check if still persists? I just want to eliminate the network being a culprit here. I too can't seem to reproduce.

**Comment by jaytaix** [comment] 2016-04-11 16:01
I am getting the exact same error, on chrome and safari.  It retains the Lobster font even after commenting out the link.  I tried in incognito mode as well and I get the same result.  
![screen shot 2016-04-11 at 11 00 26 am](https://cloud.githubusercontent.com/assets/10500808/14433648/c1318b48-ffd4-11e5-9a15-9ee6f2c6b1f4.png)

**Comment by akkatracker** [comment] 2016-04-12 08:13
Chrome Canary: Not getting this issue.

**Comment by Purpleholik** [comment] 2016-04-18 16:38
+1

**Comment by hallaathrad** [comment] 2016-04-18 17:20
it is also possible you'd have that font installed in your systems? @jaytaix @TheDoctorsLife

**Comment by jaytaix** [comment] 2016-04-18 17:35
> is it also possible you'd have that font installed in your systems? @jaytaix @TheDoctorsLife

I do have it on my system.  I was thinking that was the case... just annoying not knowing exactly what was causing it, but it goes away after disabling the font.  So the two solutions so far are update Chrome and/or make sure you don't have Lobster enabled locally.

**Comment by hallaathrad** [comment] 2016-04-18 17:38
@jaytaix I guess it comes down to that, yes... however, those are real world issues, not exclusive to Free Code Camp. Your browser should ideally always be in its latest version, and if you have the font locally, you'll be able to see it in the browser without linking to external sources. (This happens to me a lot because of my visual design work).

Fact of life. Sorry we can't really help much. This however is beyond the scope of our site, so unless someone feels the need to reopen it, I deem this issue closed (albeit not technically "solved". I know...)

**Comment by Lolinder** [comment] 2016-07-09 22:07
I saw this same thing and also thought it was a bug. It's not really an issue, since it's expected behavior, but does confuse.

A simple "solution" would be to add a clarification to the challenge. Something along these lines:

**Note**
If you have the Lobster font installed on your computer, you wont see the degradation because your browser is able to find the font.

Similar to the Note on this task:
https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element

That way when people see this, they'll understand what's happening.

**Comment by erictleung** [comment] 2016-07-10 02:56
I like @Lolinder's suggestion note.

**Comment by Lolinder** [comment] 2016-07-10 04:59
I added the note in English and Spanish in a branch on my fork, but don't have everything set up yet to run npm before submitting a pull request. Will get back to this on Monday, if no one else beats me to it.

Either way, will need someone for the other languages.

**Comment by raisedadead** [comment] 2016-07-10 08:04
@Lolinder you may just fix the languages you are comfortable with. You can close the issue, the updates will be taken care in translation issues.

**Comment by ivantedja** [comment] 2016-09-05 14:28
it seems to be forgotten, I'll submit the PR :)

**Closed** 2016-09-05 18:30 UTC
Labels: help wanted
