### ISSUE TITLE
Site popup table

### ISSUE THREAD

**Issue by thanisha123** [FreeCodeCamp/FreeCodeCamp#6566] opened 2016-01-29 06:24 UTC
Every time I login to the site a popup shows up covering half the screen and I'm not able to work on any challenges or go into my profile because the popup won't go away. I try clicking on the "x" to close the box and it won't go away. Please help.

Challenge [Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by bugron** [comment] 2016-01-29 06:26
@thanisha123 thanks for posting. Can you comment here a screenshot, please?

**Comment by thanisha123** [comment] 2016-01-29 06:34
On Thursday, January 28, 2016 10:27 PM, Arsen Melikyan <notifications@github.com> wrote:
 

 @thanisha123 thanks for posting. Can you comment here a screenshot, please?—

**Comment by bugron** [comment] 2016-01-29 06:37
@thanisha123 Seems you forgot to sent a screenshot because I don't see any links/images.

**Comment by thanisha123** [comment] 2016-01-29 06:45
![screen shot 2016-01-28 at 10 32 36 pm](https://cloud.githubusercontent.com/assets/16159317/12668949/d6758822-c610-11e5-9d0d-42901b3f3606.png)

**Comment by bugron** [comment] 2016-01-29 06:47
@thanisha123 are there any errors in your browser's console?

**Comment by thanisha123** [comment] 2016-01-29 06:52
No, I've been having the issue since last week. I never had this problem before.

**Comment by thanisha123** [comment] 2016-01-29 06:53
here's another shot:

![screen shot 2016-01-28 at 10 52 41 pm](https://cloud.githubusercontent.com/assets/16159317/12669060/e9befdc2-c611-11e5-8b25-633be80b82ce.png)

**Comment by bugron** [comment] 2016-01-29 06:56
Since I'm not able to reproduce this issue the only thin I can suggest now is this article https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc. I don't know if it will help you but give a try.

**Comment by thanisha123** [comment] 2016-01-29 06:59
ok

**Comment by SaintPeter** [comment] 2016-01-29 07:02
Are you able to close the pop-up by clicking the x in the upper right?

**Comment by thanisha123** [comment] 2016-01-29 07:04
No.

**Comment by bugron** [comment] 2016-01-29 07:05
@thanisha123 are there any errors in your browser's console after you **cilck** that x button?

**Comment by SaintPeter** [comment] 2016-01-29 07:06
Try `Command-Option-I` to open your developer tools.  Open the "Console" tab.

**Comment by thanisha123** [comment] 2016-01-29 07:06
I went on the site using chrome and I don't have any issue with the pop-up, I was able to close it clicking x. I guess it has something to do with safari?

**Comment by SaintPeter** [comment] 2016-01-29 07:07
Maybe, but we have developers and staff on Mac/Safari and they're not having the issue.  We'd like to get to the bottom of it.

**Comment by thanisha123** [comment] 2016-01-29 07:09
I tried Command-Option-I and nothing happened

**Comment by SaintPeter** [comment] 2016-01-29 07:09
https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/KeyboardShortcuts/KeyboardShortcuts.html

Command-Option-C is supposed to open the console on Safari.  Dunno.

**Comment by sludge256** [comment] 2016-01-29 07:10
Seems to be related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6189

**Comment by thanisha123** [comment] 2016-01-29 07:13
still nothing
it seems it's related to #6189

**Comment by bugron** [comment] 2016-01-29 07:14
@sludge256 :+1: @thanisha123 I think Browsec or any other similar add-on should work here. The reporter of that issue was in school so I assume that some firewall is blocking things.

**Comment by thanisha123** [comment] 2016-01-29 07:17
I'll just log in from chrome for now

**Comment by sellis7** [comment] 2016-02-08 21:12
I just want to comment, because this is the closest issue I've seen to what I'm experiencing. It's the exact same phenomenon as "thanisha123" experienced - however I'm having this issue on my mobile devices...
iPad 2 (iOS 8.4), both Safari & Firefox, & I then attempted to pull up the site from my Samsung phone (Android 4.3) and had the exact same behavior.

I can't get the box to respond to tapping the "X" - it goes gray, but the window remains. I've also quit and restarted my devices, but no change.

Thanks

**Comment by bugron** [comment] 2016-02-16 05:52
Thanks for posting. Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256. You can continue further discussion there.

**Closed by bugron** 2016-02-16 05:52 UTC
Labels: blocked

**Comment by Jontwa** [comment] 2016-05-28 07:35
i have the same problem on my mac. but when i log in through win 7 everything is ok..... no pop up unless i want it to be there, and it closes smoothly when i want it to.
