### ISSUE TITLE
Range error when example code is duplicated

### ISSUE THREAD

**Issue by amanda-wong** [FreeCodeCamp/FreeCodeCamp#6662] opened 2016-02-01 22:06 UTC
Challenge [Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20myFunction(a%2Cb)%20%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0AmyFunction(10%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(a,b) {
  console.log(a + b);
}
myFunction(10, 5);

```

**Comment by sludge256** [comment] 2016-02-02 06:53
Try refreshing the page or restarting your browser.

**Comment by raisedadead** [comment] 2016-02-02 07:09
Duplicate of #6183

**Comment by sludge256** [comment] 2016-02-02 07:15
Closing as duplicate. Thanks @raisedadead

**Closed by sludge256** 2016-02-02 07:15 UTC
