### ISSUE TITLE
The instructions seem inappropriate for this activity

### ISSUE THREAD

**Issue by swapy** [FreeCodeCamp/FreeCodeCamp#8551] opened 2016-05-10 16:30 UTC
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%22Hi%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afunction%20reusableFunction1()%20%7B%0A%20%20console.log(%22Hi%20World%22)%3B%0A%7D%0AreusableFunction1()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();

// Only change code below this line

function reusableFunction1() {
  console.log("Hi World");
}
reusableFunction1();

```

Instructions
Create a function called reusableFunction which prints "Hi World" to the dev console.
Call the function.

But I found that objective was to make changes in existing reusableFunction() instead of creating new reusableFunction1().

Seems, Instructions are inappropriate.
Also have a look at comment in code, which says 
// Only change code below this line

However, the activity expects to modify exisitng reusableFunction which is above this line.

Thanks.

**Comment by erictleung** [comment] 2016-05-10 16:56
Somewhat related to #8526. General theme is that the instructions need to be updated.

**Comment by raisedadead** [comment] 2016-05-10 20:26
Yeah @erictleung I agree this one is a bit on the overwhelming side.
Looks like this challenge need refactoring.

How about something:

// Example
function reusableFunction() {
  console.log("Hi World");
}
reusableFunction();

// Only change code below this line
function greetFunction() {
reusableFunction();
}
greetFunction();
```

And of course change the instructions and the tests to reflect the same, that the `reusableFunction` is indeed being reused?

Or do you suggest something more intuitive for a camper.

**Comment by swapy** [comment] 2016-05-11 04:25
@raisedadead, as i said before 
**// Only change code below this line**
However, your approach still expects to modify exisitng reusableFunction which is above this line.

And it is too complicated for beginner to understand.

**Comment by raisedadead** [comment] 2016-05-11 07:38
Yes we could do that, the problem is our current testing framework would need some overhaul for this. For instance if we do not have a well defined function, then user would simply pass the challenge with 

```
console.log('Heya, World');
console.log('Hi World');
```

And the tests would be looking for these outputs.

I am not against this, but unless someone is up for modifying the way current infrastructure for detecting if a function was defined or not, which realistically speaking may not be happening soon.

So we need at least one well defined function for the challenge seed. Campers may define any no of re-usable functions and call them.

**Comment by pranayberry** [comment] 2016-05-15 18:30
@raisedadead @erictleung We can update the instructions as 
> Change the function called `reusableFunction` so that it prints `"Hello World` to the dev console.

**Comment by raisedadead** [comment] 2016-05-15 18:49
@pranayberry Umm tha'ts not gonna solve the objective, IMHO. Rather changing the instruction and seed is needed here. (BTW seed is that code which appears in the code editor)

**Comment by pranayberry** [comment] 2016-05-16 12:31
@raisedadead Will this work..?
![image](https://cloud.githubusercontent.com/assets/15723427/15289506/3ae65e92-1b90-11e6-8395-dc058dc29473.png)

**Comment by raisedadead** [comment] 2016-05-17 12:55
Okay, I went through this once again.
And here is what we need:

![image](https://cloud.githubusercontent.com/assets/1884376/15322867/c9c918ee-1c5c-11e6-932d-b5c0a9363490.png)

**Comment by pranayberry** [comment] 2016-05-17 16:18
@raisedadead I noticed same issue with the next challenge also ie the instructions are not clear.

**Comment by pranayberry** [comment] 2016-05-29 05:35
@raisedadead 
**Previous**
![screenshot from 2016-05-29 10 50 50](https://cloud.githubusercontent.com/assets/15723427/15631547/200f94f6-258d-11e6-96d4-1f624d1d127c.png)
![screenshot from 2016-05-29 10 53 16](https://cloud.githubusercontent.com/assets/15723427/15631549/238f9360-258d-11e6-8fea-07b147383d5f.png)

**Updated**
![screenshot from 2016-05-29 10 50 20](https://cloud.githubusercontent.com/assets/15723427/15631550/32f257de-258d-11e6-9dba-4d1613063b50.png)
![screenshot from 2016-05-29 10 53 38](https://cloud.githubusercontent.com/assets/15723427/15631551/372b91da-258d-11e6-939c-5e1454d674ff.png)

Should I proceed with the PR ?

**Comment by hrokr** [comment] 2016-06-06 18:56
@erictleung,  @pranayberry, @raisedadead, @ceejayoz  

**Either slightly renaming either function or saying "rewrite the function, changing the contents of the string to ..... " would be helpful in this case.**


#### Screenshot

![screen shot 2016-06-06 at 2 42 56 pm](https://cloud.githubusercontent.com/assets/9368785/15833479/fed4f920-2bf4-11e6-9d66-fd2e511f3610.png)

**Comment by erictleung** [comment] 2016-07-04 07:19
A recent PR #9485 has fixed this issue. The PR has been merged and will be pushed to the live site soon. So closing this issue as resolved. Happy coding all!

**Closed by erictleung** 2016-07-04 07:19 UTC
Labels: Discussing, enhancement

**Comment by hrokr** [comment] 2018-09-10 19:46
I know; I went there to tell you in person.
