### ISSUE TITLE
Help! I am Stuck, Thank you.

### ISSUE THREAD

**Issue by adhikarinetwork** [FreeCodeCamp/FreeCodeCamp#6892] opened 2016-02-11 13:33 UTC

**Comment by raisedadead** [comment] 2016-02-11 13:39
Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

Duplicate of #6893

**Closed** 2016-02-11 16:46 UTC

**Comment by W12S12E12** [comment] 2016-02-11 16:49
yes yes yes in here http://www.codeproject.com/Articles/20574/Open-Source-QRCode-Library
