### ISSUE TITLE
Image on side not showing

### ISSUE THREAD

**Issue by RayJaws** [freeCodeCamp/freeCodeCamp#13658] opened 2017-02-28 20:41 UTC
Image on the side is not showing. All I see is a "?" in a blue box. I am using a Mac computer. Should this be an issue?

Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image {
    width: 100px;
  }
  .red-text {
    color: red;
  }
  

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by systimotic** [comment] 2017-02-28 21:17
@RayJaws Thank you for reporting this issue. We're aware of this, it's caused by an outage at our image hosting provider, AWS S3. See https://github.com/freeCodeCamp/freeCodeCamp/issues/13653 for more details. I'm closing this as a duplicate.

**Closed by systimotic** 2017-02-28 21:17 UTC

**Comment by systimotic** [comment] 2017-02-28 21:20
**Update at 1:12 PM PST** from the AWS status page. Everything should be back to normal for us!
After refreshing your browser, images should load again. If not, please clear your cache and try again.

**Comment by t0cc** [comment] 2017-03-04 16:25
Image is loading **https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg** but _bit.ly_ redirection seems not to work with this exercise. Please don't use redirection services.

**Comment by iansibindi** [comment] 2017-03-04 17:32
Responsively Style Radio Buttons
