### ISSUE TITLE
All "Help" and "Pair" links broken

### ISSUE THREAD

**Issue by CoderNurse** [FreeCodeCamp/FreeCodeCamp#2474] opened 2015-08-22 03:52 UTC
All of the "Help" and "Pair" links in all Waypoints and Bonfires (as far as I've seen) are dead links. If you click either, you get a pop up window and then if you click on the "Take me to the help room" or "Take me to the pair programming room" the link is dead.

**Comment by BerkeleyTrue** [comment] 2015-08-22 17:26
Closing as duplicate of #2445

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-22 17:26 UTC
