### ISSUE TITLE
Typo error on class name. Should be .orange-text not .brown-text.

### ISSUE THREAD

**Issue by FaalVedtuz** [freeCodeCamp/freeCodeCamp#14196] opened 2017-04-01 20:34 UTC
Challenge [Override Class Declarations by Styling ID Attributes](https://www.freecodecamp.com/challenges/override-class-declarations-by-styling-id-attributes#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%7B%0A%20%20%20%20color%3Aorange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text{
    color:orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text">Hello World!</h1>

```

Hi, I noticed that there is a typo error in the instructions for this lesson,  I attached a screenshot showing the typo.
![lesson56](https://cloud.githubusercontent.com/assets/18550212/24582216/74320d80-175d-11e7-914b-77c96533e6ed.PNG)

As you can see it is stated as brown-text class where in to complete the lesson you should put a orange-text class and an orange color text.  As seen in this screen shot.
![lesson56a](https://cloud.githubusercontent.com/assets/18550212/24582236/ac6a6a76-175d-11e7-85ee-e1803a0ff7e0.PNG)

**Comment by texas2010** [comment] 2017-04-01 23:14
@FaalVedtuz 
but that is example code.   it said here's an example of what this look like:

you didn't notice?

**Comment by erictleung** [comment] 2017-04-02 23:36
@FaalVedtuz thanks for the issue. As @texas2010 has pointed out, this is just an example. We don't want to give you all the answers so we give a similar example to work off from. Hope this makes sense. Closing as not a bug. Happy coding!

**Closed by erictleung** 2017-04-02 23:36 UTC
