### ISSUE TITLE
Calling a component within itself causes and infinite loop and freezes the browser

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38344] opened 2020-03-08 17:45 UTC
to replicate:
- go to https://www.freecodecamp.org/learn/front-end-libraries/react/use-react-to-render-nested-components

- and nest TypesOfFood within itself as shown in the picture.

![image](https://user-images.githubusercontent.com/4591597/76168134-b4c77c00-617d-11ea-97ff-fec4af6b7eb9.png)

**Comment by ojeytonwilliams** [comment] 2020-03-08 18:07
I think this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36118.

**Comment by krishnadevz** [comment] 2020-03-08 18:07
```
const TypesOfFruit = () => {
  return (
    <div>
      <h2>Fruits:</h2>
      <ul>
        <li>Apples</li>
        <li>Blueberries</li>
        <li>Strawberries</li>
        <li>Bananas</li>
      </ul>
    </div>
  );
};

const Fruits = () => {
  return (
    <div>
      { /* change code below this line */ }
<Fruits/>
      { /* change code above this line */ }
    </div>
  );
};

class TypesOfFood extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <h1>Types of Food:</h1>
        { /* change code below this line */ }

        { /* change code above this line */ }
      </div>
    );
  }
};

```
With this thing one challenge is ✔ but when i type **<TypesOfFood/>** After returning component  everything is freezed/browserToo now i cleared the issue to much extent i think only problem is with **<TypesOfFood/>** it is going in infinite loop hope this helps now  and problem is fixed ASAP

**Closed** 2020-03-08 18:07 UTC
Labels: duplicate, scope: curriculum, status: needs investigation

**Comment by krishnadevz** [comment] 2020-03-08 18:24
**issue is solved now i called that component incorrectly everyone can use the below code and see the difference and working good but that infinite loop thing needs to fix ASAP**  
```
const TypesOfFruit = () => {
  return (
    <div>
      <h2>Fruits:</h2>
      <ul>
        <li>Apples</li>
        <li>Blueberries</li>
        <li>Strawberries</li>
        <li>Bananas</li>
      </ul>
    </div>
  );
};

const Fruits = () => {
  return (
    <div>
      { /* change code below this line */ }
<TypesOfFruit/>
      { /* change code above this line */ }
    </div>
  );
};

class TypesOfFood extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <h1>Types of Food:</h1>
        { /* change code below this line */ }
<Fruits/>
        { /* change code above this line */ }
      </div>
    );
  }
};

```
@ojeytonwilliams @ahmadabdolsaheb
