### ISSUE TITLE
My code worked perfect, but the program refused to accept one of the results. I reproduced what it wanted me to make and it worked everytime, definitely a bug.

### ISSUE THREAD

**Issue by graalcloud** [FreeCodeCamp/FreeCodeCamp#11880] opened 2016-12-01 00:32 UTC
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20arr%20%3D%20%5B%5D%3B%0Avar%20i%20%3D%200%3B%0Avar%20lengthArray%20%3D%20%5B%5D%3B%0A%0A%0Afunction%20findLongestWord(str)%20%7B%0A%20%20arr%20%3D%20str.split(%27%20%27)%3B%0A%20%20%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%2010%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(arr%5Bi%5D)%20%7B%0A%20%20%20%20%20%20lengthArray.push(arr%5Bi%5D.length)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20lengthArray.sort(function(a%2Cb)%20%7B%0A%20%20return%20b%20-%20a%3B%0A%7D)%3B%0A%20%20return%20lengthArray%5B0%5D%3B%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr = [];
var i = 0;
var lengthArray = [];


function findLongestWord(str) {
  arr = str.split(' ');
  
  for (i = 0; i < 10; i++) {
    if (arr[i]) {
      lengthArray.push(arr[i].length);
    }
  }
  lengthArray.sort(function(a,b) {
  return b - a;
});
  return lengthArray[0];
}

findLongestWord("May the force be with you");

```

**Comment by erictleung** [comment] 2016-12-01 00:55
@graalcloud thanks for the issue. This is a *feature* on how the tests work. They work by calling the function `findLongestWord()` over and over. All global variables are changed likewise. This is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9199. There's already been a call for adding some text about this "feature" in the curriculum somewhere https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9063.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Closed by erictleung** 2016-12-01 00:55 UTC

**Comment by EddyInWind** [comment] 2016-12-01 01:24
Put the "lengthArray" definition inside the function, a global shouldn't be used, cause multiple function call may pollute this array when it's global.
For example, when it's first called...
`findLongestWord("The quick brown fox jumped over the lazy dog");
// lengthArray now is [6, 5, 5, 4, 4, 3, 3, 3, 3]`

And the second time the function is called
`findLongestWord("May the force be with you");
// lengthArray now is [6, 5, 5, 5, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2]`
The answer now is '6' instead of '5' which you expect.

So you may need to modify it to ...
`function findLongestWord(str) {
      var lengthArray = [];  // The definition should be here.
      ......
      .....
}`
