### ISSUE TITLE
Encountering the same reload  issue I had yesterday on this page

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#7828] opened 2016-03-31 17:08 UTC
Challenge [Declare JavaScript Variables](https://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%2F%2F%20Example%0Avar%20ourName%3B%0A%0A%0A%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0Avar%20myName%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.

Today I actually received an error:

Error 504 Ray ID: 28c56387b0b90ecd • 2016-03-31 17:06:54 UTC
Gateway time-out

This is the link:

https://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%2F%2F%20Example%0Avar%20ourName%3B%0A%0A%0A%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0Avar%20myName%3B%0A%0A

**Comment by raisedadead** [comment] 2016-03-31 18:56
Hi @interglobalmedia !

Thanks for reporting this.

We are sincerely sorry for the performance issues with regards to the website.
And as I mentioned yesterday, we are aware of this and are working on it. 

[Here is a post on our sub-reddit](https://www.reddit.com/r/FreeCodeCamp/comments/4cm7o7/has_fcc_become_very_slow/d1jzumi) by Quincy @QuincyLarson giving the details.

We understand and share your frustration with this issue. This is not a problem with specific challenges, but with the infrastructure of our site. We have a potential fix planned to roll out on Saturday. These issues are all related to one root problem so there's no need to file additional issues.

Of course please feel free to continue the discussion on this thread. Or ping us on the [Help Chat](https://gitter.im/FreeCodeCamp/Help) Room.

Closing as duplicate of #7818

**Closed by raisedadead** 2016-03-31 18:56 UTC
