### ISSUE TITLE
ctrl + enter doesn't work on Chromium

### ISSUE THREAD

**Issue by elimisteve** [FreeCodeCamp/freecodecamp#383] opened 2015-04-28 03:18 UTC
I'm on Chromium + Linux + a Chromebook.

EDIT: `Version 41.0.2272.76 Ubuntu 14.04 (64-bit)` is where this isn't working for me.

Okay, I've tested this out in Firefox and it _does_ work.  So, it appears to be a Chromium (and almost certainly Chrome) browser issue.

**Comment by elimisteve** [comment] 2015-04-28 03:22
> terakilobyte: @elimisteve: which page in particular?

@terakilobyte: I've tried on the first ~5 or so exercises, to mark them complete, and it hasn't worked yet for me.

**Comment by elimisteve** [comment] 2015-04-28 03:22
> terakilobyte: @elimisteve: which page in particular?

@terakilobyte: I've tried on the first ~5 or so exercises, to mark them complete, and it hasn't worked yet for me.

**Comment by terakilobyte** [comment] 2015-04-28 03:26
This works on Chrome Version 42.0.2311.90 (64-bit), FireFox 37.0.2, and Safari Version 8.0.5 (10600.5.17) on OSX.

**Comment by QuincyLarson** [comment] 2015-04-28 18:09
@terakilobyte I couldn't find a straight answer as to whether Chromium is lumped in with Chrome on Google Analytics, but there could be a sizable portion of our campers who use Chromium: https://www.evernote.com/shard/s116/sh/9a7b3142-1db2-4de7-a402-0230a41f1a60/2f0185efc68fc12da15dce8e9fe911ca/deep/0/Audience-Overview---Google-Analytics.png

@elimisteve would you be interested in helping us diagnose why it's not working in Chromium? I don't know anyone else who actively uses Chromium at the moment.

**Comment by elimisteve** [comment] 2015-04-28 18:10
@QuincyLarson I'll try ctrl-enter in Chrome

**Comment by elimisteve** [comment] 2015-04-28 18:11
@QuincyLarson ...after I install it, and report back.  That should help figure this out.

**Comment by QuincyLarson** [comment] 2015-05-03 04:13
@elimisteve what were your results? Thanks for following up - we want to make sure this is working.

**Comment by denmch** [comment] 2015-05-03 04:42
I just tested this in the latest build of Chromium for OSX and it works as expected, so it seems to be Linux (or Ubuntu)-specific.

**Comment by PKMNinja** [comment] 2015-05-03 23:32
I can confirm it does not work on Chrome Canary Version 44.0.2390.0 canary on Windows Vista. It doesn't matter how many times I hit ctrl + enter it doesn't work.

**Comment by QuincyLarson** [comment] 2015-05-04 05:36
I'm going to close this item. It sounds like it's working in Chromium now. We don't need to support Canary as only a small minority of people (all of whom are developers) use it.

**Closed** 2015-05-04 05:36 UTC
Labels: bug
