### ISSUE TITLE
Map panel is blank in Safari 8.0.2

### ISSUE THREAD

**Issue by zhangkenny** [FreeCodeCamp/FreeCodeCamp#6943] opened 2016-02-12 21:31 UTC
Just resuming after a month of hiatus, only to find that my progress on FCC is inaccessible due to the new side panel layout. I can't get into my Maps because the side panel is consistently blank. The panel itself is intrusive and cannot be closed. I've attached a screenshot below.
![screen shot 2016-02-12 at 16 18 50](https://cloud.githubusercontent.com/assets/16676524/13020618/67c517ea-d1a4-11e5-8721-afbce3663692.png)

I've found that this issue has been brought up several times, yet somehow it's been dismissed as a user error. I'm using the same connection as I did when I began FCC last month, but have only encountered this issue now with this side panel. My console is displaying errors from the server as shown below:

![screen shot 2016-02-12 at 16 23 52](https://cloud.githubusercontent.com/assets/16676524/13020732/07adee4e-d1a5-11e5-82fc-aa4990ce119a.png)

Has there been any new discovery regarding this issue? I'm also hoping that my post will raise more flags so that it can be brought to the admins' attention.

**Comment by jamigibbs** [comment] 2016-02-12 21:43
I believe all of these issues are related: 
#6227
#6256
#6557

And PR #6908 addresses both the blank white sidebar and scrolling issue in iOS

**Comment by zhangkenny** [comment] 2016-02-12 22:15
Thanks @jamigibbs for listing all of the similar threads. Although I haven't experienced anything wrong with the scrolling.

#6699 is also having the same problem with the blank panel on Safari.

Seems like it's being deemed as a device-specific problem, but with Safari being the common culprit.

**Comment by bugron** [comment] 2016-02-16 05:49
Thanks for posting. Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256.

**Closed by bugron** 2016-02-16 05:49 UTC
