### ISSUE TITLE
Timezone breaks submission: "cannot read `join` of null.

### ISSUE THREAD

**Issue by DmitryGrigorov** [FreeCodeCamp/FreeCodeCamp#6633] opened 2016-02-01 09:00 UTC
I cann't press the button "Submit and go to my next challenge (ctrl + enter)". But if I clicked I only see the infinite loading. How to solve this problem?
![default](https://cloud.githubusercontent.com/assets/15948159/12712716/62a3c88c-c8db-11e5-9556-7183e96aa60b.PNG)

**Comment by AkiraLaine** [comment] 2016-02-01 09:01
What browser/OS are you using?

**Comment by DmitryGrigorov** [comment] 2016-02-01 09:01
Chrome

**Comment by AkiraLaine** [comment] 2016-02-01 09:02
What OS? Also, are you using a VPN?

**Comment by DmitryGrigorov** [comment] 2016-02-01 09:06
Windows 7 Ultimate.No I'm not using

**Comment by AkiraLaine** [comment] 2016-02-01 09:11
Ok, I'm not sure how that happens...weird.

Cc: @BerkeleyTrue @QuincyLarson

**Comment by park23** [comment] 2016-02-01 09:12
i have same issue (

**Comment by AkiraLaine** [comment] 2016-02-01 09:14
I can confirm. I am having the same issue.

**Comment by park23** [comment] 2016-02-01 09:21
@AkiraLaine still not working

**Comment by QuincyLarson** [comment] 2016-02-01 09:29
I can't reproduce on latest Chrome with OSX. @AkiraLaine are you on Windows? Can anyone with Windows confirm this is still a problem?
@park23 could you open up your browser console and take a screen shot of any errors you see? Also, which challenge are you experiencing this on?

**Comment by AkiraLaine** [comment] 2016-02-01 09:37
@QuincyLarson No I cannot reproduce it.

**Comment by DmitryGrigorov** [comment] 2016-02-01 09:38
![default](https://cloud.githubusercontent.com/assets/15948159/12713600/a561da42-c8e0-11e5-9c39-9a8ccc5d0de4.png)

**Comment by bugron** [comment] 2016-02-01 09:38
Also if you have this issue, please, comment here a screenshot of your browser's Network tab.

**Comment by park23** [comment] 2016-02-01 09:58
![wtfcode](https://cloud.githubusercontent.com/assets/1039281/12714053/e2a463ec-c8eb-11e5-9913-cf67c02275d0.JPG)

**Comment by bugron** [comment] 2016-02-01 10:01
@park23 is that all? Isn't there a POST request for `/completed-challenge/`?

**Comment by park23** [comment] 2016-02-01 10:08
@bugron it's all

**Comment by bugron** [comment] 2016-02-01 10:11
@park23 are you behind any VPN, anonymization soft, firewall? Are you browsing non from your school/internet cafe/any public place?

**Comment by park23** [comment] 2016-02-01 10:16
@bugron Just router in home, 2 hour later all was fine

**Comment by bugron** [comment] 2016-02-01 10:19
@park23 and the last question. Where are you located if you don't mind me asking?

**Comment by park23** [comment] 2016-02-01 10:22
@bugron Middle Asia)

**Comment by evaristoc** [comment] 2016-02-01 10:25
tried the registration challenges: can't replicate, @bugron
Windows 10; Amsterdam; Google Chrome

I did notice a short delay though

**Comment by bugron** [comment] 2016-02-01 10:31
@evaristoc I'm not able to repro too. Not sure what is the issue. I thought this is something related to their connection but I'm in doubt now after @park23 said that there isn't a POST request for `/completed-challenge/`. When you click that button script makes a `/completed-challenge/` POST request to send the data to the server. There is no such a request which means that something went wrong before a request has been made.

**Comment by evaristoc** [comment] 2016-02-01 10:37
That suggests that it could be broken at client...

@bugron we rencently introduced a change in the ga functionality (I wonder if that change is breaking the completion script...)

**Comment by bugron** [comment] 2016-02-01 10:38
This is what I'm talking about:
![](http://i.imgur.com/VtPzDd8.png)
The emphasized redirection takes place only when that POST request is successful.

**Comment by bugron** [comment] 2016-02-01 10:49
Also, I'm not sure that this is an issue on our end (I mean FCC). I see that jQuery isn't loaded for @park23. We send the POST request using jQuery's `$.post` so it will fail. @park23 if you still have this issue try to find out why jQuery isn't loading.

**Comment by evaristoc** [comment] 2016-02-01 10:56
@bugron yes, I couldn't find any reason why the ga change could have broken the post request...

**Comment by Omegadrone** [comment] 2016-02-01 11:12
Hi guys! Same here with "submit and go to my next challenge" screen hanging. Everything was fine until now. Chrome/Windows 7. Can this be a server lagging?

**Comment by bugron** [comment] 2016-02-01 11:15
@Omegadrone please, post here a screenshot of your browser's console and Network tab, thanks.

**Comment by Progern** [comment] 2016-02-01 11:17
Same issue
Windows 10/Chrome
![1](https://cloud.githubusercontent.com/assets/16916594/12715987/2b260aea-c8e6-11e5-8f1c-1505f264dd85.png)

**Comment by park23** [comment] 2016-02-01 11:19
@Progern it's not network tab

**Comment by Progern** [comment] 2016-02-01 11:19
@park23  how i can see Network Tab?

**Comment by park23** [comment] 2016-02-01 11:21
@Progern see your screenshot "network" after sources

**Comment by Progern** [comment] 2016-02-01 11:22
@park23  done. Thank you!

**Comment by bugron** [comment] 2016-02-01 11:24
@QuincyLarson @BerkeleyTrue I see that from line 30 in `vendor-main-00eff8238f.js` starts moment-timezone's script.

**Comment by Omegadrone** [comment] 2016-02-01 11:30
![issue1](https://cloud.githubusercontent.com/assets/16789510/12716279/51130a3a-c933-11e5-9b7c-34df32dcef07.png)
![issue2](https://cloud.githubusercontent.com/assets/16789510/12716280/5119576e-c933-11e5-8688-6d296f5f471e.png)
![issue3](https://cloud.githubusercontent.com/assets/16789510/12716281/511aa948-c933-11e5-938b-11e36c3e8d12.png)

**Comment by Progern** [comment] 2016-02-01 11:43
Guys! I've just downloaded fresh Mozilla Firefox browser, by the installing i didn't imported any settings from other browsers.
And it worked. The issue dissappeared, and I continued my styding.
I was using Chrome before.

Hope, it might help you :)

**Comment by Omegadrone** [comment] 2016-02-01 11:47
@Progern Hey, thanks for the hint!

**Comment by Omegadrone** [comment] 2016-02-01 11:57
@Progern Thanks for the hint!

**Comment by park23** [comment] 2016-02-01 12:03
look like a chrome bug, need a fix)

**Comment by bugron** [comment] 2016-02-01 12:05
@park23 is it fixed for you when you use Chrome?

**Comment by park23** [comment] 2016-02-01 12:10
@bugron no)

**Comment by Nikitaw99** [comment] 2016-02-01 12:12
Try using firefox!

**Comment by Omegadrone** [comment] 2016-02-01 12:13
I've found that there's no issues when signed out.

**Comment by park23** [comment] 2016-02-01 12:13
i dislike ff(

**Comment by Nikitaw99** [comment] 2016-02-01 12:14
@park23 It lags too much for me, but atleast it works.
There is no choice :(

**Comment by bugron** [comment] 2016-02-01 12:16
@Omegadrone thanks for that! Everyone, please, try using other browser than Chrome. If that won't help try to sign out and complete the challenge again. Report back any console errors you see. Thanks.

**Comment by park23** [comment] 2016-02-01 12:17
If I do not find a solution for chromium, then I will use firefox (all problem in Provisional headers)

**Comment by Omegadrone** [comment] 2016-02-01 12:18
@bugron runnig good on FireFox. Thank you for your trying to help )

**Comment by park23** [comment] 2016-02-01 12:22
browsec help me!) thx all

**Comment by shtau** [comment] 2016-02-01 12:44
Have the same problem. Used Opera and Chrome - both do not load now (yesterday it was fine). I'm in Ukraine, home wi-fi,no vpn and other stuff.

**Comment by shtau** [comment] 2016-02-01 12:45
![image](https://cloud.githubusercontent.com/assets/16965905/12717717/6892330c-c8f2-11e5-9772-6e33f114b65a.png)

**Comment by Omegadrone** [comment] 2016-02-01 12:48
@shtau Best solution for now is to use FireFox. I haven't found better one yet.

**Comment by shtau** [comment] 2016-02-01 12:54
@Omegadrone thanks. I hope it will be fixed somehow.

**Comment by Omegadrone** [comment] 2016-02-01 12:55
@shtau you are welcome.

**Comment by brutalcrozt** [comment] 2016-02-01 18:24
:heart_eyes: i also have some issue when using Chrome, which is got 404 when accessing npmcdn .
So this just happen in windows user?

**Comment by cannelflow** [comment] 2016-02-01 18:49
happened to me also but i closed it and refreshed the page worked for me

**Comment by zhylninc** [comment] 2016-02-02 08:14
err:
win10+chrome 

good:
win10+firefox

**Comment by zhylninc** [comment] 2016-02-02 08:14
#6642 
only after landing

//! moment-timezone.js
//! version : 0.5.0
//! author : Tim Wood
//! license : MIT
//! github.com/moment/moment-timezone

vendor-main-00eff8238f.js:formatted:17423Uncaught TypeError: Cannot read property 'join' of null

function i(a) {
var b = a.toTimeString()
, c = b.match(/(.+)/);
c = c && c[0] ? c[0].match(/[A-Z]/g).join("") : b.match(/[A-Z]{3,5}/g)[0], //error line

**Comment by iritu** [comment] 2016-02-02 09:51
It stucks in this position, not working, for 2 days, tried in Edge and Chrome, nothing helps, it worked perfectly a few days ago so please don't blame my WIN10 or my computer it something to do with your system, please do check it.


![1](https://cloud.githubusercontent.com/assets/8612743/12745624/f8b4ca98-c9a2-11e5-92a8-ea4220cb3845.GIF)

**Comment by raisedadead** [comment] 2016-02-02 10:09
@iritu Can you use Firefox meanwhile? seems to have worked for others in the comments above.

**Comment by iritu** [comment] 2016-02-02 10:11
Yes, this is what I did, try to fix the problem with Chrome, please....Tnks.

**Comment by sebbe88** [comment] 2016-02-02 19:45
Firefox works for me. Waiting for Chrome fix, please :)

**Comment by qmikew1** [comment] 2016-02-02 21:03
There are 64 and 32 bit Chrome versions. Saw Windows 7 mentioned. Any of the posts mention/ include this info? (i.e., which version of Win7 ( (32/64) not sure that it would be relevant though)

**Comment by noncasus** [comment] 2016-02-02 21:18
No issues here but I'm usually signed out so it could be that one must sign in to get past this issue.

Win10/Chrome 48.0.2564.97

**Comment by brutalcrozt** [comment] 2016-02-03 00:49
@sebbe88 can you try with closing the tab and try again with chrome?
or try with signed out and sign in again?

**Comment by YangLeda** [comment] 2016-02-03 11:59
Same problem. I have 2 computuers at my home, windows7 + chrome / windows10 + edge. Both have  the same problem. Home WiFi, no VPN. I'm in China. I haven't try firefox since I don't like it. Thanks a lot if anybody gonna fix this.

**Comment by aleksej3455** [comment] 2016-02-03 18:58
same error appear, win 7 + chrome
made 112 challanges in one day, took 4 days break and - Uncaught TypeError: Cannot read property 'join' of null

**Comment by BerkeleyTrue** [comment] 2016-02-03 19:24
Thanks everyone for reporting. This is a bug in moment-timezones code. I'll put together a patch shortly while we wait for an official fix from them.

**Comment by SaintPeter** [comment] 2016-02-03 19:29
Can everyone report if they have their OS language set to a non-English language and/or a non-western alphabet/character set (IE: Cyrillic)?

If so, does changing your language to english help?

**Comment by BerkeleyTrue** [comment] 2016-02-03 19:40
A patch is up on [beta](http://beta.freecodecamp.com/challenges/headline-with-the-h2-element). Give it a try and report back.

**Comment by brutalcrozt** [comment] 2016-02-03 19:44
@BerkeleyTrue will report if any user in gitter have this issue.

**Closed** 2016-02-03 19:56 UTC
Labels: confirmed

**Comment by BerkeleyTrue** [comment] 2016-02-03 20:17
A patch has been released to production. This patch will be removed when new version of moment-timezone is release with permanent fix.
