### ISSUE TITLE
Page went into some kind of infinite page refresh loop

### ISSUE THREAD

**Issue by AKWintermute** [FreeCodeCamp/FreeCodeCamp#2729] opened 2015-08-26 08:41 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Stiino0** [comment] 2015-08-26 09:31
Some extra data: the playground refreshes a dozen times and then the completed message is shown. This is apparently with (almost?) all JQuery waypoints.

**Comment by Mansuro** [comment] 2015-08-26 13:24
Same issue seems to happen in #2732

**Comment by BerkeleyTrue** [comment] 2015-08-26 17:59
Closing as duplicate of #2709 
 
Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-26 17:59 UTC
