### ISSUE TITLE
Waypoint: Target the Children of an Element Using jQuery (Excersice: 124)

### ISSUE THREAD

**Issue by AbhiChachan** [FreeCodeCamp/FreeCodeCamp#5991] opened 2016-01-09 08:46 UTC
Hi,

Once the code is run, the output shows #target5 button twice. There seems to be some bug in the system.
Screenshot Attached.

![screen shot 2016-01-09 at 2 16 36 pm](https://cloud.githubusercontent.com/assets/8476026/12215285/a147aed0-b6db-11e5-8955-1ad936f0d1a2.png)

**Comment by sludge256** [comment] 2016-01-09 08:49
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072

**Closed** 2016-01-09 16:38 UTC
