### ISSUE TITLE
expected ... to deeply equal [ Array(2) ]

### ISSUE THREAD

**Issue by warkentien2** [FreeCodeCamp/FreeCodeCamp#3037] opened 2015-09-03 20:26 UTC
On most bonfire tests, when result is a 2D-array
instead of displaying expected value we get a [Array(2)].
![freecodecamp](https://cloud.githubusercontent.com/assets/5117454/9670009/b2d95b6a-5260-11e5-8f30-81cdd50720b0.jpg)

Suggestion: (at least works for me at jsfiddle.net)
If using console.log( answer ), change it to console.log(JSON.stringify( answer ));

example problem: http://www.freecodecamp.com/challenges/bonfire-friendly-date-ranges

**Comment by ahstro** [comment] 2015-09-04 09:05
I'm not quite sure, but I think this might be caused by how the test suite, chai.js, works.

**Comment by awesomeaniruddh** [comment] 2015-09-06 22:22
Well, I don't know how to fix that, but here is a suggestion:

Look at the actual test code: `assert.deepEqual(friendly(['2015-07-01', '2015-07-04']), ['July 1st','4th'], 'ending month should be omitted since it is already mentioned');`

The first argument of `assert.deepEqual` is calling the function, while the second argument is an array with the expected output. Whenever the text below decides to shorten arrays to `[Array (n)]`, you can look at the test code.

**Comment by ahstro** [comment] 2015-09-07 18:59
@awesomeaniruddh Yes, that's how I've done it when working through the challenges myself. Don't take my word for it, but I think I've heard something about rewriting how tests are executed, so this might be an easier fix in the future, but I'm not sure it's too simple right now.

**Comment by warkentien2** [comment] 2015-09-07 21:21
@awesomeaniruddh I know expected value appears in assert.deepEqual()'s last parameter,
I'm familiar with tests from codewars.com
I was just suggesting a fix for the developers.

**Comment by BerkeleyTrue** [comment] 2015-09-07 21:43
Unfortunately that is how console.log prints arrays. The test could be changed to print the top level individual elements of the array

**Comment by warkentien2** [comment] 2015-09-07 21:49
@BerkeleyTrue try printing a 2D array with console.log() as I suggested
console.log(JSON.stringify( ... ));

**Comment by BerkeleyTrue** [comment] 2015-09-07 21:53
@warkentien2 Would you like to submit a PR? https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

**Comment by awesomeaniruddh** [comment] 2015-11-03 08:35
Closing because this is a non-issue in the new way we show tests.

**Closed by awesomeaniruddh** 2015-11-03 08:35 UTC
Labels: Discussing, feature request

**Comment by barak2018** [comment] 2019-09-07 10:21
hello, i want u to help me.
### 1.the instructions:

Given two numbers X and Y, write a function that:
1 returns even numbers between X and Y, if X is greater than Y else it returns odd numbers between x and y
For instance, take the integers 10 and 2 . the function would return all the even numbers between 2 and 10.

Specification
numberGame(x, y)
Return a list of odd or even number between two integers X and Y

Parameters
x: Number - The first integer provided

y: Number - The second integer provided

Return Value
Number - a list of odd or even numbers between x and y

**2.here is the sample test:**
let assert = require("chai").assert;
describe('Challenge', function() {
  it('should return the right array', function() {
    assert.deepEqual(number_game(2,12), [3, 5, 7, 9, 11]);
    assert.deepEqual(number_game(0,0), []);
  });
});


### then , here is my code:

const number_game = (x, y) => {
//   Code here
  let numbers = [];
  

  if (x > y) {
    for (let i = y + 1; i < x; i++) {
      if (i % 2 == 0) {
        numbers.push(i);
      }
    }
  } else {
    for (let i = x; i <= y; i++) {
      if (i % 2 == 1) {
        numbers.push(i);
      }
    }
  }

  return numbers;
}

console.log(JSON.stringify(number_game(12, 0)));

but it doesn't allow to pass THE TEST.
plz help
