### ISSUE TITLE
img element - confusing test output

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#45717] opened 2022-04-18 19:16 UTC
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website

## Your code

```
<h2>CatPhotoApp</h2>
<main>
<IMG src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="relaxing cat with orege fur">

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
```

## Expected behavior

Somewhat confusingly, this code passes the first test but fails the third test. It isn't immediately obvious to me why the capitalization doesn't seem to matter to the first test but does to the third. Changing the `IMG` to `img` gets this code passing, but that isn't obvious from the error message of "Your image element's `alt` attribute should not be empty."

**Comment by nhcarrigan** [comment] 2022-04-19 16:05
I'm honestly not sure why that regex in the test is even necessary. We already query the DOM to assert that the `alt` attribute exists and is not empty.

**Comment by Sboonny** [comment] 2022-04-24 09:41
I am wondering how should I tackle this bug. I can edit the third hint [add-images-to-your-website](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md), but I am wondering if anything should be done to regex expression, as nhcarrigan said in 
>I'm honestly not sure why that regex in the test is even necessary

**Comment by ShaunSHamilton** [comment] 2022-04-24 19:35
@Sboonny 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

I am in favour of allowing valid HTML to pass. That is, change the test to be case-insensitive.

**Comment by Sboonny** [comment] 2022-04-24 20:15
Interesting, I didn't know that HTML is case insensitive. I thought because the challenges didn't accept `<P>` as an answer, that HTML is case sensitive 😅https://stackoverflow.com/questions/4351857/is-html-case-sensitive

**Comment by zidanehammouda** [comment] 2022-05-08 10:57
Hello, can I work on this issue?

**Comment by Sboonny** [comment] 2022-05-08 11:16
You can send pull request, when they add label as `first-time-only`, `help-wanted`, or they comment that they will accept pull requests for this issue. On my part, I won't submit pull request when they open it, if you planning to tackle this issue

**Comment by raisedadead** [comment] 2022-05-13 13:19
What @ShaunSHamilton said:

> I am in favour of allowing valid HTML to pass. That is, change the test to be case-insensitive.

**Comment by Sboonny** [comment] 2022-05-13 14:13
@zidanehammouda the issue is up for grab, if you still interested

**Closed** 2022-05-23 14:53 UTC
Labels: type: bug, help wanted, scope: curriculum
