### ISSUE TITLE
Profile lookup

### ISSUE THREAD

**Issue by picsola** [FreeCodeCamp/FreeCodeCamp#9614] opened 2016-07-08 08:52 UTC
Hi, I'm not sure this is a  bug but I asked in help forum and was told that the code is right and it should work.

So this is my code:

```js
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUpProfile(firstName, prop){
    for (var x = 0; x < contacts.length; x++){
        if (contacts[x].firstName === firstName && contacts[x].hasOwnProperty(prop)===true) {
            return contacts[x][prop];
        } else if (contacts[x].firstName === firstName && contacts[x].hasOwnProperty(prop)===false) {
            return "No such property";
        } else if (contacts[x].firstName !== firstName && contacts[x].hasOwnProperty(prop)===true) {
            return "No such contact";
        }
    }
}
```
The code works well with both "else if" statements, when either firstName or prop are false; but it doesn't work when both are true. I even tried creating a new "else if" statement to cover the case where both conditions are false, but of course it doesn't work either.

Thank you for your help.

**Edit** (by @raisedadead)

Challenge Name : [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup)

**Comment by Dcolonel6** [comment] 2016-07-08 09:58
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  for(var person=0; person < contacts.length;person++){
    console.log(contacts[person].firstName);
    if(contacts[person]["firstName"] === firstName)
    {
      if(contacts[person].hasOwnProperty(prop)){
        return contacts[person][prop];
        
      }
      else        
      {
        return "No such property";
      }
      
    }
    else
      return "No such contact";
    
    
  }
 
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Sherlock", "likes");

**Comment by ChaituVR** [comment] 2016-07-08 09:58
Try knowing more about the challenge [here](https://freecodecamp.github.io/wiki/en/challenge-profile-lookup/) . But be careful it may contain a solution..

**Comment by Dcolonel6** [comment] 2016-07-08 09:59
mine doesnt even loop ...after i have  initialize person to 0 it doesnt increment accordingly

**Comment by raisedadead** [comment] 2016-07-08 10:01
Please discuss in the [Chat rooms ](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by picsola** [comment] 2016-07-08 10:18
Thanks for the clues (and the edit!). So I guess there is no bug and it's just me doing something wrong, right? I'll keep on working on it then.

**Comment by ChaituVR** [comment] 2016-07-08 10:23
@picsola your second else if statement `return "No such contact";` is not placed exactly where it should be .. which is making all the test cases pass through it  **Don't Return in loop... Be Sure to Check all the values check for the FirstName** and if you have any doubts in future please ask them in [Chat Rooms](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by raisedadead** [comment] 2016-07-08 12:26
Thanks everyone closing as not a bug.

**Closed by raisedadead** 2016-07-08 12:26 UTC

**Comment by jdeshaies1982** [comment] 2017-05-08 21:52
function lookUpProfile(firstName, prop){
// Only change code below this line

    var retVal = "No such contact";
  
    for (var x = 0; x < contacts.length; x++)
    {
      if (contacts[x].firstName === firstName)
      {
        if (contacts[x].hasOwnProperty(prop)===true) {
            retVal = contacts[x][prop];
        } 
        else if (contacts[x].hasOwnProperty(prop)===false) {
            retVal = "No such property";
        } 
        else {
            retVal = "No such contact";
        }
      }
    }  
    return retVal;
// Only change code above this line
}

**Comment by mshaheel** [comment] 2021-07-22 17:23
###**This_Snippets_seems_great**


// Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["JavaScript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(name, prop) {
  // Only change code below this line
    for(var x=0; x<contacts.length; x++){
        if(contacts[x]["firstName"]==name){
            if(contacts[x].hasOwnProperty(prop)===true){
                return contacts[x][prop];
            }
            
            else if(prop==contacts[x].hasOwnProperty(prop)===false){
                return "No such property";
            }
        }
    }
    return "No such contact";
  // Only change code above this line
}
var a = lookUpProfile("Harry", "likes");
console.log(a)
