### ISSUE TITLE
js bundle file does not exist

### ISSUE THREAD

**Issue by juandesouza** [freeCodeCamp/freeCodeCamp#17923] opened 2018-07-25 15:07 UTC
On the Tribute page, the first Responsive Web Design project, is given the address of a CDN that we should use in order to test the project. The address of the CDN is: https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js
Two problems here. First, it is not informed how to implement the CDN in the project. Second, the bundle.js file does not exist, so it will never work. If you try to access the CDN address, it will say: 404: not found.
The page of the project is: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by Nirajn2311** [comment] 2018-07-25 18:00
The issue for your second question occurs as the learn website is not yet updated to use the current version of curriculum, so the issue is fixed but it is not yet implemented.

**Comment by SubhrajyotiSen** [comment] 2018-07-25 18:19
The CDN link issue has been fixed in https://github.com/freeCodeCamp/curriculum/commit/a311e06e4e98818b0a8cef6429b2d5e49fbe5fbe

It just needs to go live on the website.

**Closed** 2018-07-31 23:19 UTC
