### ISSUE TITLE
Exercise Tracker App: 5th test times out

### ISSUE THREAD

**Issue by vstoyanoff** [freeCodeCamp/freeCodeCamp#38735] opened 2020-05-05 08:46 UTC
**Describe your problem and how to reproduce it:**
I can't figure out why the 5th test times out with this error:
```
I can retrieve a full exercise log of any user by getting /api/exercise/log with a parameter of userId(_id). App will return the user object with added array log and count (total exercise count). (Test timed out)
// tests completed
```
The strange thing is that all other tests are passing including the last one which is using the same endpoint as the 5th one.
I also test it manually and it is working fine. I even added a middleware to check all incoming requests and used the same endpoints to clarify that there is no problem with the code.

I am using Glitch for the challenge.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker

**Comment by Sky020** [comment] 2020-05-07 12:37
Hello there,

In general, I recommend an issue like this be opened as a topic on the [forum](https://www.freecodecamp.org/forum). Be sure to include a link to your project. Unfortunately, the tests do not align perfectly with the challenge descriptions, and are extremely specific.

If it is determined, on the forum, that the issue is with the tests (source code), then I welcome you to reopen this issue.

For now, I am closing this.

Thank you.

**Comment by Sky020** [comment] 2020-05-09 22:41
Following on from this thread: https://www.freecodecamp.org/forum/t/exercise-tracker-test-times-out/383763

It has been determined that the issue is to do with the tests.

**Comment by Sky020** [comment] 2020-05-09 22:41
Following on from this thread: https://www.freecodecamp.org/forum/t/exercise-tracker-test-times-out/383763

It has been determined that the issue is to do with the tests.

**Comment by pinglinh** [comment] 2020-06-14 15:38
Is this the actual test file being used for the project? https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.english.md

**Comment by Sky020** [comment] 2020-06-14 16:13
@pinglinh , Yes, it is.

**Comment by pinglinh** [comment] 2020-06-14 16:16
@Sky020 What framework is it? I was trying to work out how I could potentially add a fix to this so that it fixes the timeout issue. I also have this problem on my project and would really like this to be marked as done 😅

**Comment by Sky020** [comment] 2020-06-14 16:47
@pinglinh , Well, the file is a MarkDown file with the tests written in a yaml syntax, but that is parsed before being run. The tests are run using [Chai](https://www.chaijs.com/) asserts, but most of it is plain JS.

It may help to go through the above mentioned forum post.

**Comment by nhcarrigan** [comment] 2020-12-16 18:54
Between our refactors of the boilerplates, challenge tests, and markdown parser, is this issue still present?

**Comment by ShaunSHamilton** [comment] 2020-12-16 19:33
@nhcarrigan I am going to close this, as it has not come up again since (that I have experienced or seen). It can simply be reopened if we manage to replicate it.

**Closed by ShaunSHamilton** 2020-12-16 19:33 UTC
Labels: scope: learn, scope: projects-backend, status: needs help for triage
