### ISSUE TITLE
Pass variable (You should use the *= operator for each variable) appears wrong when correct (doesnt effect passing)

### ISSUE THREAD

**Issue by Dman89** [FreeCodeCamp/FreeCodeCamp#7572] opened 2016-03-16 06:23 UTC
Challenge [Assignment with Times Equals](http://www.freecodecamp.com/challenges/assignment-with-times-equals#?solution=var%20a%20%3D%205%3B%0Avar%20b%20%3D%2012%3B%0Avar%20c%20%3D%204.6%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20*%3D%205%3B%0Ab%20*%3D%203%3B%0Ac%20*%3D%2010%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var a = 5;
var b = 12;
var c = 4.6;

// Only modify code below this line

a *= 5;
b *= 3;
c *= 10;



```

**Comment by raisedadead** [comment] 2016-03-16 12:21
@livinglegendparagon Your code passes for me. 

Can you please be more specific? Can you post some screen shots here?
Please visit our [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you are stuck.

Thanks.

**Comment by livinglegendparagon** [comment] 2016-03-16 19:45
it is very specific, let me decode it for you.

When you do a challenge you have variables you need to pass, (passVariable)

this particular passVariable with the string value of "You should use the *= operator for each variable".

displays a red 'X' compared to a green check mark.

But I am still able to pass.

Solution: check the if/else statements for the passVariable that displays the string "You should use the *= operator for each variable" to have it correspond.

Note: if you stay on page and ctrl+enter again, it resets. something about the first time you run the code.

plan human terms, when i passed my quiz the side bar said i failed one objective on the quiz.

**Comment by raisedadead** [comment] 2016-03-17 05:16
@livinglegendparagon 

Thanks I believe this is down to your browser, I tested this use case and can't seem to reproduce.
Can you please test if you are getting this on any other browser and if possible on any other device as well?

Since you are the only person so far getting this I guess we need some help in analyzing from you.

Also it would be really helpful if you could post some screenshots as I mentioned earlier.

Thanks again.

**Comment by livinglegendparagon** [comment] 2016-03-19 15:50
Yeah, give me a chance. Seems like is has to do with the javascript
updating. I'll be home in a couple of hours

**Comment by 3316** [comment] 2016-03-20 15:56
I do not own a MacMac. I do not have Windows windowswindows nor do I use browser listed

**Comment by raisedadead** [comment] 2016-03-28 13:43
@Dman89 Any updates on this? If this is resolved or not reproducible, would you mind closing?

**Comment by raisedadead** [comment] 2016-03-29 12:58
Closing as stale. Please comment if you are facing still facing this.

**Closed by raisedadead** 2016-03-29 12:58 UTC
Labels: blocked
