### ISSUE TITLE
My outputs are exactly the ones requested by the challenge. None accepted.  :((((

### ISSUE THREAD

**Issue by fuecisla** [FreeCodeCamp/FreeCodeCamp#11230] opened 2016-10-16 00:02 UTC
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%0Afunction%20uniteUnique(arr)%20%7B%0A%20%20%0A%20%20%0A%20%20%2F%2FLong%20loop%20used%20to%20concat%20-I%20am%20sure%20a%20reduce%20would%20have%20worked%20better%20but%20I%20don%C2%B4t%20get%20well%20along%20with%20it.%0A%20%20len%3Darguments.length%3B%0A%20%20arr%3D%5B%5D%3B%0A%20%20for%20(var%20i%3D0%3Bi%3Clen%3Bi%2B%2B)%20%7B%0A%20%20%20%20arr%3Darr.concat(arguments%5Bi%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20len%3D%20arr.length%3B%0A%20%20var%20toSplice%2C%20j%3B%0A%20%20for%20(i%3D0%2C%20j%3D0%3B%20i%3Clen-1%20%26%26%20j%3C30%3B%20i%2B%2B%2Cj%2B%2B)%20%7B%2F%2Fincludes%20j%20as%20a%20measure%20against%20infinite%20loop%0A%20%20%20%20if(arr.indexOf(arr%5Bi%5D%2C%20i%2B1)%20%3Ei)%20%7B%0A%20%20%20%20%20%20%20toSplice%3Darr.indexOf(arr%5Bi%5D%2C%20i%2B1)%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20arr.splice(toSplice%2C1)%3B%0A%20%20%20%20%20%20%20%20i--%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0A%20%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B1%2C%20%5B5%5D%5D%2C%20%5B2%2C%20%5B4%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi, I get the correct output in all test cases but it does mark them all as wrong. I have looked for similar problems in this forum but haven´t found anything. I am reproducing here (see under the my code section) the results I get with the most complex test of the 4 the challenge provides. I honestly can't see a difference between the output is asked for and what I get... any ideas??

My code:
```javascript

function uniteUnique(arr) {
  
  
  //Long loop used to concat -I am sure a reduce would have worked better but I don´t get well along with it.
  len=arguments.length;
  arr=[];
  for (var i=0;i<len;i++) {
    arr=arr.concat(arguments[i]);
  }
  
  len= arr.length;
  var toSplice, j;
  for (i=0, j=0; i<len-1 && j<30; i++,j++) {//includes j as a measure against infinite loop
    if(arr.indexOf(arr[i], i+1) >i) {
       toSplice=arr.indexOf(arr[i], i+1);
      
        arr.splice(toSplice,1);
        i--;
    }
    
  }
  
  return arr;
}

 

uniteUnique([1, 3, 2], [1, [5]], [2, [4]]);

```
I cant see what is the difference between the output asked for and the one produced by my program. Maybe I was just expected to program in a different way?

![image](https://cloud.githubusercontent.com/assets/19933562/19414154/9c5dd036-934c-11e6-8cf3-9f896b89484d.png)

**Comment by yasserhussain1110** [comment] 2016-10-16 03:14
> uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]) should return [1, 3, 2, **5**, 4].

At position number 3 the of the output array, the value is expected to be a number.  
Your output seems to be an array
> [1, 3, 2, **[5]**, 4].

So your code's output does not match the system's expectation.  
That has resulted in the error, most likely.

**Comment by yasserhussain1110** [comment] 2016-10-16 04:20
I think I found the cause of this issue.  
When I ran the above code in my node terminal,

```js
uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
```

This is what I got - 
> [ 5, 2, 1, 4 ]

When I ran it within the FCC challenge environment, I got this - 

> [1,3,2,5,4]

Clearly there is a disconnect here.

**Comment by Bouncey** [comment] 2016-10-16 07:37
@fuecisla There is an error in your code, and can be easily made. 

By assinging `[]` to arr, you are mutating the `arguments` object before you start working on it. 

See if you can resolve the issue now, if you are still having issues, please use the `Help` button.

----

@yasserhussain1110 I agree there is some disconnect between the FCC output and node. With corrections made to the code, I receive the correct output from node and FCC. 

We need to check if this is still the case with the `staging` branch, as `staging` and `master` are very different at the minute (`staging` hold the react version), and I don't know if the code evaluation part of the code base has been changed.

**Comment by yasserhussain1110** [comment] 2016-10-16 07:47
@Bouncey If you point me in the right direction I could try to find out if the code evaluation part has changed or if it is working just like node.

**Comment by Bouncey** [comment] 2016-10-16 07:49
@yasserhussain1110 It works like node.

On the react version of the site, the output from your function call does not appear in the output window, however, `console.logs` do.

**Comment by Bouncey** [comment] 2016-10-16 07:50
@fuecisla I am closing this issue because it is for code help.

You are so close! Keep trying :+1: 

Happy coding!

**Closed by Bouncey** 2016-10-16 07:50 UTC

**Comment by fuecisla** [comment] 2016-10-16 15:43
Thank you for your help! As per your advice I erased the statement converting arr into an array -leaving it as the string it was- and then all lights became green. :))))
