### ISSUE TITLE
css not checking for valid css (missing semi-colon passes tests)

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#865] opened 2015-06-08 18:56 UTC
![screenshot 9](https://cloud.githubusercontent.com/assets/12790960/8042643/9103674e-0dee-11e5-960c-e903e6f9ae2e.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-margins-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by treece** [comment] 2015-06-09 01:26
@BerkeleyTrue @QuincyLarson This is an issue with all the waypoints and bonfires and would require all of them to be redone. Are you guys considering tightening up the loose matching system then? I know @QuincyLarson talked about this on Twitch one night and I thought this was how it was intended to work.   Just curious so I'll know for future issues. Thanks!

**Comment by BerkeleyTrue** [comment] 2015-06-09 01:39
Yes, this is due to the fact that our test only test for very specific things.

Testing for valid html/css is something I have talk to quincy about before when we got blasted with `test passing with no closing tag` issues. While not good looking html doesn't always require a closing tag for it to render correctly, let alone be valid spec (i.e. the img/a tags are self-closing tags).

I think the reason that didn't get implemented is due to how forgiving html/css is. For instance the example above still renders correctly. So it might be counter-productive to force campers into a strict cage and this kind of stuff veers into the `linting code` area instead of the `not valid html/css`

**Comment by treece** [comment] 2015-06-09 02:59
Good point and I agree. :+1:

**Comment by QuincyLarson** [comment] 2015-06-09 05:36
@treece @kesb4aspire yes, this is as designed. We don't want new campers to get hung up on tiny details like semicolons. Yes, they are important, but it's not worth scaring off new beginners when the CSS is technically valid.

**Closed** 2015-06-09 05:36 UTC
