### ISSUE TITLE
First test in "Bootstrap wells" waypoint is confusing.

### ISSUE THREAD

**Issue by eabedrapo** [FreeCodeCamp/FreeCodeCamp#2438] opened 2015-08-21 17:47 UTC
The instructions of the waypoint read "Nest one div element with the class well within each of your col-xs-6 div elements." Which I understand it requires something like this:
```html
<div class="col-xs-6">
      <div class="well"></div>
</div>
<div class="col-xs-6">
      <div class="well"></div>
</div>
```

However the first test require "Add two div elements inside your div class="well"> element both with the class col-xs-6" which I understand is asking this:
```html
<div class="well">
      <div class="col-xs-6"></div>
</div>
<div class="well">
      <div class="col-xs-6"></div>
</div>
```

In other hand, that very test is fulfilled by just nesting *one* "well" div inside *one* of the "col-xs-6" (see the screenshot below).

Waypoint URL:
http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells

![image](https://cloud.githubusercontent.com/assets/1670763/9414901/37057c1a-4812-11e5-946a-f308e3e5d0a4.png)

**Comment by benschenker** [comment] 2015-08-21 18:06
Thanks for posting an issue.

It looks like this is a duplicate of #1968 and others, so keep an eye there for fixes.

**Comment by BerkeleyTrue** [comment] 2015-08-21 18:39
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 18:39 UTC

**Comment by eabedrapo** [comment] 2015-08-21 19:19
Oh! sorry... this time I raised it in rush and I didn't verify if it was previously reported.
Thank you anyways ;)

**Comment by BerkeleyTrue** [comment] 2015-08-21 19:44
@eabedrapo no worries. Happy Coding!
