### ISSUE TITLE
Freecodecamp emission issue

### ISSUE THREAD

**Issue by Eddy-edd** [freeCodeCamp/freeCodeCamp#39373] opened 2020-08-04 18:10 UTC
I believe there is an issue with the Testing Objects for Properties test on basic JavaScript. The coding section omits the setup section that should detail the values of myObj global variable. One has to rely on the result section to check which values are needed to construct the required code and pass the test. 
![image](https://user-images.githubusercontent.com/24062280/89327530-c19cbd00-d694-11ea-8f00-e72781ac21db.png)

**Comment by nhcarrigan** [comment] 2020-08-04 18:11
Hello~!

The function should be written to check the value of any property on any object - you should not need to see what the object would be in order to write this function. 🙂

**Comment by RandellDawson** [comment] 2020-08-04 18:23
@Eddy-edd There is no need for a setup object, as the tests pass various objects with different property names.  The example in the challenge description shows one possible object and the results of what the function should return for that particular object when specific property names are passed as the second argument of the function.

I am closing this issue for now as this is not a bug with the challenge.  Instead, it is intended not to have a setup object.

Thank you for understanding.

**Closed by RandellDawson** 2020-08-04 18:23 UTC

**Comment by Eddy-edd** [comment] 2020-08-04 18:58
Thanks RandellDawson.
