### ISSUE TITLE
Instruction code visible

### ISSUE THREAD

**Issue by sunilpaig** [FreeCodeCamp/FreeCodeCamp#2992] opened 2015-09-02 11:44 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

* When you go to a new challenge, you see the code besides the check on the left hand side. I have attached a screenshot and marked the code that is visible in it.
![bug](https://cloud.githubusercontent.com/assets/13588103/9630106/97b8a696-5180-11e5-921e-15af69fa8eba.png)

**Comment by awesomeaniruddh** [comment] 2015-09-02 12:24
That's the test FCC uses to validate your code. It is not a bug.

The test is public because it helps you debug your code, especially the bonfires because you know exactly which conditions the code fails under.

I hope that solves your issue. If it does, please close it :)

**Comment by bugron** [comment] 2015-09-02 14:12
@sunilpaig thanks for posting this issue!
Closing this as a duplicate. For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2818#issuecomment-135908153).
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-02 14:12 UTC
