### ISSUE TITLE
Display and Run Tests Not Working

### ISSUE THREAD

**Issue by alephaseffa** [FreeCodeCamp/FreeCodeCamp#10678] opened 2016-09-10 16:22 UTC
#### Challenge Name

All

#### Issue Description

After passing a few exercises, the display on the phone on the right hand side of the code doesn't work (phone remains blank). Also, the text under run text where it normally shows which criteria have to be met for the code to be accepted is also missing. These issues are fixed after multiple refreshes of the page.

#### Browser Information

Same error appears on both Google Chrome (Version 52.0.2743.116 m), and Microsoft Edge (25.10586.0.0). Haven't tried any other browsers.

* Browser Name, Version: Google Chrome (Version 52.0.2743.116 m) and Microsoft Edge (25.10586.0.0)
* Operating System: Windows 10 Version 1511
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

http://imgur.com/yV3BNJ1

**Comment by JesterMan** [comment] 2016-09-10 19:01
I'm also experiencing this issue. Refreshing the browser used to work, but stopped working.



<img width="1413" alt="screen shot 2016-09-10 at 11 58 42 am" src="https://cloud.githubusercontent.com/assets/5865674/18412853/ff41bc32-774d-11e6-959d-bd11fce7506c.png">

**Comment by ScottDevs** [comment] 2016-09-10 19:44
Something to add to this. I have experienced the same issue, the one repeating factor though is yes I am using Chrome but it only appears to occur when I am using a Fast Food's Wifi or my Public Library's Wifi. When I use my home wifi I never run into the issue.

**Comment by mpaunovic** [comment] 2016-09-10 19:49
Confirmed. Refreshing the page a few times helps.
- Firefox v48 & Chromium v52
- Linux Mint x64.

**Comment by brt898** [comment] 2016-09-10 20:13
same error..
mozilla v48
ubuntu 16.04

**Comment by QuincyLarson** [comment] 2016-09-10 20:22
Does a hard refresh solve the problem? http://forum.freecodecamp.com/t/refresh-your-browser-cache/19365

**Comment by lorenbr** [comment] 2016-09-10 20:26
Clearing the cache and doing a hard refresh worked for me.  But I just cleared the cache 20 minutes ago to try to fix the problem and it came back again.

**Comment by brt898** [comment] 2016-09-10 20:45
A hard refresh solves the problem. but the problem repeats for each challenge

**Comment by lorenbr** [comment] 2016-09-10 20:50
The output box which shows you the results of your function returns (I am working on javascript algorithms) also has disappeared for me.  And the hard reset doesn't seem to fix the problem.  Instead, when I switched back and forth between exercises, I was able to get the output box to return.

I assume the issues are related.

Firefox 48.0.2

**Comment by zumruduanka** [comment] 2016-09-10 20:58
I cleared the cache and refreshed. This only worked for one challenge, then the issue repeated in the next challenge. And after clearing the cache via the **Settings-->Clear Browsing History** menu, it seems that my solutions to the challenges have been deleted although there  is not a problem with the progress check.

**Comment by mpaunovic** [comment] 2016-09-10 21:12
@zumruduanka
Have you tried to do a hard refresh?
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by zumruduanka** [comment] 2016-09-10 21:24
@mpaunovic It didn't help, either. Thanks anyways. :)

**Comment by brt898** [comment] 2016-09-10 21:38
@zumruduanka using another browser might help

**Comment by JesterMan** [comment] 2016-09-10 22:20
This seems to be the best thread for dealing with this issue. 

I'm no expert on CSP, but it seems from reading here: http://www.html5rocks.com/en/tutorials/security/content-security-policy/

that some policies don't default to 'self'.

If that's the case, we need to add '*.optimizely.com', to the scriptSrc: array in csp.js.

I'm going to create a pull request as soon as github is done downloading. I hope that the right way to do it, this will be my first time contributing to open source.

**Comment by DarrenfJ** [comment] 2016-09-10 22:31
Hard refreshes were my goto work-around when people had this issue in the help chat room but they're not working anymore.. just reloading the same exercise without the test cases and the right hand side fake phone for output is blank.. this is just an fyi for symptoms...

**Comment by QuincyLarson** [comment] 2016-09-10 22:49
@BerkeleyTrue just completely reset all of our caches and that may have fixed it (I can no longer reproduce it on my local computer). Is anyone still experiencing these issues?

**Comment by ndrsrv** [comment] 2016-09-10 23:23
@QuincyLarson , I had this error half an hour ago on chrome 53, and i clear local.storage, clear browser history, press ctrl+f5 and it did not help. After i download portable version chrome and this error was also there. But now all challenges work. I think that this error depends on the time.

**Comment by ntdd** [comment] 2016-09-10 23:38
I've noticed I've been getting the same errors while going through some intermediate algorithm challenges today. At first, the challenge pages weren't displaying the output box or the objectives below it. A couple refreshes would fix the issue for each challenge as others have stated, but I've noticed these console messages have persisted, not only on challenge pages but also other pages on freecodecamp not including the forum. I attached the images of the console logs for Edge, Chrome and Firebug/Firefox.

firebug mentions a an issue with frame-src being deprecated btw. maybe these will help you guys out.

![chrome-console-log](https://cloud.githubusercontent.com/assets/17624180/18414131/026412f4-7774-11e6-9a74-90f2be27835a.png)
![edge-console-log-1](https://cloud.githubusercontent.com/assets/17624180/18414130/0262f4d2-7774-11e6-886c-67ee7222d42e.png)
![edge-console-log-2](https://cloud.githubusercontent.com/assets/17624180/18414132/02655d6c-7774-11e6-97fa-6e6ad2f72f5e.png)
![firebug-console-log](https://cloud.githubusercontent.com/assets/17624180/18414133/02664876-7774-11e6-8cfd-678933c653c1.png)

**Comment by QuincyLarson** [comment] 2016-09-11 03:20
@ndrsrv thanks for confirming this is now working for you. 

@ntdd Those errors are due to our Contest Security Policy. I don't think they are related to this issue, but they are things we intend to eventually fix. They shouldn't affect your experience at all.

Since we haven't had any other new reports for the last few hours, I am going to close this issue as resolved. If anyone sees this and is still having issues, feel free to re-open it.

**Closed by QuincyLarson** 2016-09-11 03:20 UTC

**Comment by abs73129** [comment] 2017-02-10 01:31
"Run tests" button not working on most Basic CSS problems.
