### ISSUE TITLE
Language change after refreshing the introductory page of a certification

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#46618] opened 2022-06-22 10:12 UTC
### Describe the Issue

If you go on the introductory page of **any** certification (such as https://www.freecodecamp.org/italian/learn/javascript-algorithms-and-data-structures/), including the introductory page of the whole curriculum (https://www.freecodecamp.org/italian/learn/), and you have set **a non-english language**, after refreshing the page it comes back to the english page. No matter which language you choose (except for simplified chinese). 

### Affected Page

https://www.freecodecamp.org/italian/learn/

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/italian/learn/'
2. 'Refresh'
3. See that the page has changed language

### Expected behavior

It shouldn't change language after refreshing the page.

### Screenshots

In this I have refreshed the page
https://drive.google.com/file/d/1M9bi7x7wF30K7YKU7MEYTJGZrwtLElk4/view

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [102.0.5005.115]

**Comment by ojeytonwilliams** [comment] 2022-06-22 10:45
Hey @Dario-DC I'm closing this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/44818.

We do plan to fix this, but it's currently waiting for us to Dockerize learn since that will involve a large change in the infra. With luck, those changes will fix this, but if not we can revisit the problem then.

**Closed by ojeytonwilliams** 2022-06-22 10:45 UTC
Labels: type: bug, status: waiting triage
