### ISSUE TITLE
freeCodeCamp weather API always shows minimum temperature & maximum temperatures same

### ISSUE THREAD

**Issue by RitikPatni** [freeCodeCamp/freeCodeCamp#15768] opened 2017-08-16 09:09 UTC
#### Challenge Name

https://www.freecodecamp.org/challenges/show-the-local-weather

#### Issue Description

https://fcc-weather-api.glitch.me/
API output 
{ "coord":{ "lon":159, "lat":35 }, "weather":[ { "id":500, "main":"Rain", "description":"light rain", "icon":"https://cdn.glitch.com/6e8889e5-7a72-48f0-a061-863548450de5%2F10n.png?1499366021399" } ], "base":"stations", "main":{ **"temp":22.59**, "pressure":1027.45, "humidity":100, **"temp_min":22.59**, **"temp_max":22.59**, "sea_level":1027.47, "grnd_level":1027.45 }, "wind":{ "speed":8.12, "deg":246.503 }, "rain":{ "3h":0.45 }, "clouds":{ "all":92 }, "dt":1499521932, "sys":{ "message":0.0034, "sunrise":1499451436, "sunset":1499503246 }, "id":0, "name":"", "cod":200 }

#### Browser Information

* Google Chrome,Version 60.0.3112.78 (Official Build) (64-bit): 
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: Desktop

**Comment by DusanSacha** [comment] 2017-08-16 12:43
Hi @RitikPatni, thank you for opening the issue.

I reviewed the weather API and I don't think there is an issue in it. There are definitely some cases which show temp_max equal to temp_min. But I found a lot of cases where this two values are different.
For example [here](https://fcc-weather-api.glitch.me/api/current?lat=99&lon=99)
(Please, keep in mind that measured data can vary. By the time when I was writing this comment temp_min was equal to 26 and temp_max was 31 in the example I posted.)

We can wait for somebody, who is responsible for this API to confirm, however from my point of view this issue can be closed for now.

**Comment by RitikPatni** [comment] 2017-08-16 15:55
Hi @DusanSacha I think that working in one or a few cases is not good for any API it should have a success rate of at-least more than 60% and failure in most cases doesn't justify it.So I don't think that closing this issue is a good idea I think if there is a bug then you can't just ignore that it works in few cases It should at-least work in most cases if not all.

We can wait for somebody, who is responsible for this API to confirm, however from my point of view this issue shouldn't be closed now.

**Comment by joshua-fogg** [comment] 2017-08-18 02:59
Hey I just checked the API feed and that particular point is showing a consistent reading. as it is located in the middle of the North Pacific Sea, I would think it would be due to a lack of data for that area. Rather than it being a faulty API i think it's due to a lack of data input for the algorithm for that location.

**Comment by RitikPatni** [comment] 2017-08-18 07:52
It is showing wrong data for my location and I'm not located in the middle of North Pacific Sea, I'm in India and the issue was coming from another person who wasn't from India So I think if the issue is real than there is a huge lack of data and it would be bad for the API

**Comment by systimotic** [comment] 2017-09-20 08:10
Thanks for reporting this issue and looking into it! 
I can confirm that there are definitely some problems with this API, both in getting the correct location and in getting the right temperatures. We're going to work on resolving this through #15878, so I'm closing this issue in favor of that. If anybody has more information, please post it there.

Happy coding!

**Closed by systimotic** 2017-09-20 08:10 UTC
