### ISSUE TITLE
"Oops! Something went wrong. Please try again later" when trying to update my email

### ISSUE THREAD

**Issue by iroshanAV** [freeCodeCamp/freeCodeCamp#16076] opened 2017-11-03 04:11 UTC
When i try to change/update my email one FCC, it says "Oops! Something went wrong. Please try again later"

![screenshot 520](https://user-images.githubusercontent.com/16167479/32360360-15e51750-c07b-11e7-8702-ac3198e8e4de.png)

What could be the reason?

**Comment by raisedadead** [comment] 2017-12-06 17:44
Duplicate of #15876

**Closed by raisedadead** 2017-12-06 17:44 UTC
