### ISSUE TITLE
Maximum call stack size exceeded error even when trying to compile example code

### ISSUE THREAD

**Issue by classact1** [FreeCodeCamp/FreeCodeCamp#5637] opened 2015-12-31 12:01 UTC
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.



```

**Comment by abhisekp** [comment] 2015-12-31 12:22
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5560

**Closed** 2015-12-31 17:53 UTC
