### ISSUE TITLE
calendar color bug in the profile page

### ISSUE THREAD

**Issue by LouayNasr** [freeCodeCamp/freeCodeCamp#17444] opened 2018-06-05 14:41 UTC
#### Describe your problem and - if possible - how to reproduce it
the calendar that appears on my profile is rotated 90 degrees...and non of the days which i have items in is green...all days color is gray

#### Add a Link to the page with the problem
https://www.freecodecamp.org/portfolio/fcce4387b0c-5ac5-46f9-8777-33f6c49dcf69

#### Tell us about your browser and operating system
* Browser Name: chrome 
* Browser Version: 68.0.3440.7 (Official Build) dev (32-bit)
* Operating System: windows 7

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/25098982/40982998-47066702-68e7-11e8-9802-e43e5e1af04f.png)

**Comment by aditijoshi14** [comment] 2018-12-13 07:01
I agree with @chaomt . This issue can be closed as the rotation is not a bug. It is just a way the calendar is designed.

**Closed** 2018-12-13 08:37 UTC
