### ISSUE TITLE
Passing Parameters to a Constructor

### ISSUE THREAD

**Issue by nasainlee** [FreeCodeCamp/FreeCodeCamp#4432] opened 2015-11-14 06:59 UTC
Challenge [Waypoint: Make Unique Objects by Passing Parameters to our Constructor](http://www.freecodecamp.com/challenges/waypoint-make-unique-objects-by-passing-parameters-to-our-constructor?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2FChange%20this%20constructor%0A%20%20this.wheels%20%3D%203%3B%0A%20%20this.seats%20%3D%201%3B%0A%20%20this.engines%20%3D%202%3B%0A%7D%3B%0A%0A%2F%2FTry%20it%20out%20here%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%7B%0A%20%20wheels%3A%203%2C%0A%20%20seats%3A%201%2C%0A%20%20engines%3A%202%2C%0A%7D%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A(function()%20%7Breturn%20JSON.stringify(myCar)%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  //Change this constructor
  this.wheels = 4;
  this.seats = 1;
  this.engines = 1;
};

//Try it out here
var myCar = new Car(3, 1, 2);

// Only change code above this line

(function() {return JSON.stringify(myCar);})();

```
I only modified the code within the // parameters and no matter the attempt I would get errors. I tried to pass parameters individually and would still receive errors. After asking for help on chat I was able to pass it, but not within the parameters set. I used multiple variations given, but none of them worked within the instructions. The constructor doesn't appear to be able to be modified as is, the other people stated the same thing. Maybe the instructions weren't as clear or this could be a bug. Error stated 
"Calling new Car(3,1,2) should produce an object with a wheels property of 3, a seats property of 1, and an engines property of 2."

**Comment by faizaanceg** [comment] 2015-11-14 07:14
I don't see what the problem is. The instructions are very clear

>  Alter the Car **constructor to use parameters** to assign values to the wheels, seats, and engines properties.
> Then call your new constructor with three number arguments and assign it to myCar to see it in action.

You need to change the code to 

```
var Car = function() {
  this.wheels = 4;
  this.seats = 1;
  this.engines = 1;
};
````

to 

```
var Car = function(wheels, seats, engines) {
  this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};
```

and then assign it to `var myCar` with the constructor.

**Comment by SaintPeter** [comment] 2015-11-14 08:00
Thanks @faizaanceg.

@nasainlee - In the future I encourage you to ask for help in the [Help Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) on Gitter.  There are many helpful folks who can answer your questions there.

**Comment by faizaanceg** [comment] 2015-11-14 08:01
:+1:

**Closed by SaintPeter** 2015-11-14 08:00 UTC

**Comment by gaizik** [comment] 2016-03-02 07:30
thanks

**Comment by martinsl30** [comment] 2016-08-25 00:17
Just follow the steps.
my code look like this:

var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};

//Try it out here
var myCar = new Car(4, 5, 1);

**Comment by KtfwyCJ** [comment] 2016-11-27 01:15
var Car = function(wheels,seats,engines) {
  this.wheels=wheels;
  this.seats = seats;
  this.engines = engines;
};

var myCar = new Car(1,2,3);

**Comment by Kristi92** [comment] 2017-07-10 01:24
chat room doesn't help a lot!!
