### ISSUE TITLE
Lesson pane should always be called "Lesson" in navigation

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16453] opened 2018-01-09 21:43 UTC
On Step challenges, it should be changed from "Step" to "Lesson":

![basic_html_and_html5__learn_how_freecodecamp_works___freecodecamp](https://user-images.githubusercontent.com/985197/34743964-3f713f08-f551-11e7-9d48-b232a570de4b.png)

On System Design Question challenges, it should be changed from "Main" to "Lesson":

![system_design_and_concept_questions__array_prototype_map___freecodecamp](https://user-images.githubusercontent.com/985197/34743945-3320a9b4-f551-11e7-9112-2042c8cedf48.png)

**Comment by warborn** [comment] 2018-01-10 07:10
I can work on this issue :)

**Comment by vkWeb** [comment] 2018-01-10 09:05
@QuincyLarson Shouldn't we do same with React & Redux challenges. "Side Panel" & "index" should be renamed to "Lesson" & "Editor" respectively.
![2018-01-10](https://user-images.githubusercontent.com/26724128/34763562-a7d21d90-f611-11e7-8ae4-052f24cb76f8.png)

### Also, I've few issues in my mind:
- The recent PR by @BerkeleyTrue made the map blazingly fast! but it takes few seconds in the initial loading so adding a spinning loader will prevent app crash if someone clicks on the map before it has fully loaded. What do you think? 

- The links on navigation bar are not rendering properly. We should reduce their font-weight to `100` for better text rendering across all devices. 

_Before_
![2018-01-10 1](https://user-images.githubusercontent.com/26724128/34763851-9828ab38-f612-11e7-9d74-e311a3f383a1.png)
_After_
![2018-01-10 2](https://user-images.githubusercontent.com/26724128/34763864-9e35e630-f612-11e7-962a-2a933a6c6a4e.png)

- The search bar should be functional before shipping.

**Comment by no-stack-dub-sack** [comment] 2018-01-13 18:55
#16459 will take care of renaming "Side Panel" to "Lesson" for the Modern challenges. 

@BerkeleyTrue I saw your note on my PR about "index" - I know the name comes from the challenge, and that this is by design, but are we going to keep that name in the nav? Or are we considering another way to make the Nav link names consistent?

**Comment by no-stack-dub-sack** [comment] 2018-01-14 18:13
@vkWeb Yes, the above PR also covers the React/Redux challenges, at least for the Side Panel -> Lesson change, this does not yet cover changing 'index' to 'Editor' as that is a bit more complex, and affects a functionality that is baked into how the modern challenges work.

**Comment by warborn** [comment] 2018-01-14 18:30
@no-stack-dub-sack no problem, i'm happy to help

**Comment by vkWeb** [comment] 2018-01-15 05:57
@no-stack-dub-sack I understand. It's okay we'll look into that later on.

**Comment by BerkeleyTrue** [comment] 2018-01-16 17:56
fixed in 62e079c7215fc13296e934ff304b6894e4a45dca

**Closed by BerkeleyTrue** 2018-01-16 17:56 UTC
Labels: beta, help wanted
