### ISSUE TITLE
clearing browser cache on chrome signs me out of curriculum indefinitely.

### ISSUE THREAD

**Issue by M-Michelini** [freeCodeCamp/freeCodeCamp#34877] opened 2019-01-15 17:58 UTC
**Describe the bug**
If you clear your cached images and files on google chrome, you are never signed in when on the curriculum page, hence all progress appears to be lost, despite it telling you that you have progressed in the settings and on the homepage. Sign in functionality seems to work as usual on all routes except curriculum.

**To Reproduce**
1. Sign into FCC on google chrome.
2. Clear your cached images and files on google chrome (found where you clear history).
3. Sign back into FCC on google chrome if necessary.
4. Go to curriculum and find that you are signed out.

**Expected behavior**
To be signed into curriculum when you are signed into the rest of FCC.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
I was doing the url-shortener project for the api and microservices certificate and i was playing around with my app on google chrome. I was having an issue where the Express response.redirect was redirecting to sites from a collectionI had dropped and restarted Eg. [mysiteurl]/api/shortenurl/0 would redirect to free code camp, which used to be correct in the database, however i cleared it and set the url with short_url:0 to www.google.com. so it should have been redirecting to google. It seemed like chrome had some sort of memory of that redirect path. so i decided to clear my cookies and cache and it fixed the problem. [mysiteurl]/api/shortenurl/0 now redirected to google.com as expected, so i was ready to submit my solution. I went to the curriculum to submit and had this problem.

**Comment by raisedadead** [comment] 2019-01-16 11:46
Hi @M-Michelini 

Thanks for the issue report. I can reproduce the issue. We have got this fixed as well on our `master`, however the fixes will not reach the production website at least for a few more weeks due the internal rewrite of the platform that is underway.

For now here is a workaround that seems to work:

![2019-01-16 17 08 44](https://user-images.githubusercontent.com/1884376/51247096-1d6bfc00-19b2-11e9-8313-1cea4939ecb5.gif)

We understand that this is annoying, and share your frustration. That said, we are working toward resolving this as soon as we are able to go with deployement.

Thanks for your patience!

**Comment by ahmadabdolsaheb** [comment] 2019-02-05 11:18
Thank you for reporting this issue. Since this issue has been addressed in the master branch and we are getting close to ship master I will close this issue for now.

**Closed by ahmadabdolsaheb** 2019-02-05 11:18 UTC
Labels: platform: client, status: resolved \ shipping, type: bug
