### ISSUE TITLE
Broken setting page

### ISSUE THREAD

**Issue by crazycat9x** [freeCodeCamp/freeCodeCamp#17531] opened 2018-06-11 00:28 UTC
#### Describe your problem and - if possible - how to reproduce it
Setting page is broken:
All buttons are either unclickable or throw `TypeError: n is null` when being click on
All sections for progress and claim certification is lost
#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Tested on all major browser
* Operating System: Tested on IOS, MacOS

**Comment by Kornelijus** [comment] 2018-06-11 08:39
Probably duplicate of #17278 
I've provided a [workaround](https://github.com/freeCodeCamp/freeCodeCamp/issues/17278#issuecomment-395690575) there, for anyone who's willing to play around with curl.

**Closed** 2018-06-12 15:50 UTC
