### ISSUE TITLE
"Night mode" button bug in Settings

### ISSUE THREAD

**Issue by Wishnia** [freeCodeCamp/freeCodeCamp#34727] opened 2018-12-23 00:30 UTC
**Describe the bug**
When you change your username, save it, and then switch on night mode, the theme doesn't change to dark. Except that, both states of night mode switch are active (there should be only currently active state). 

But when you are already using night mode and try to reproduce this bug, night mode switch doesn't work at all.

I was reproducing this bug on every device within my reach, and every time with positive results.

**To Reproduce**
1. Go to "Settings"
2. Change your username
3. Click "Save"
4. Switch on/off "Night mode" 
5. Oops, there is some bug :wink: 

**Expected behavior**
1. When I change my username, save it, and then switch on night mode, a theme should change to dark, night mode "on" state should be active and night mode "off" state should be inactive.
2. When I am using dark mode, I change my username and then switch off night mode, the theme should change to bright, night mode "on" state should be inactive and night mode "off" state should be active.

**Screenshots**
- First case
![1](https://user-images.githubusercontent.com/44586513/50379526-e40ecd80-064b-11e9-99b9-26df86877a7e.png)
1. As you can see, I changed my username (added extra "a") and everything worked.
![2](https://user-images.githubusercontent.com/44586513/50379538-49fb5500-064c-11e9-89aa-535ef6f4723d.png)
2. I tried to change the theme and I spotted this bug.

- Second case
![3](https://user-images.githubusercontent.com/44586513/50379563-f63d3b80-064c-11e9-807f-ceaba4dc1c52.png)
1. In this case, I was using dark mode. I removed extra "a" from my username and it changed properly. But when I was trying to switch off night mode, nothing happened. Night mode switch seems to be frozen.

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 65.0b6

**Smartphone:**
1. First device
 - Device: Xiaomi Redmi 6
 - OS: Android 8.1
 - Browser: Firefox
 - Version: 64.0.1

2. Second device
 - Device: Sony Xperia E4g
 - OS: Android 4.4.4
 - Browser: Firefox
 - Version: 64.0.1

**Comment by chaomt** [comment] 2019-02-28 19:13
We would like to work on it!

**Comment by Fordco** [comment] 2019-02-28 22:30
I was also able to reproduce this bug on Chrome Version 72.0.3626.119 (Official Build) (64-bit).
Also I agree to the color comment @reolander. I'm not sure if that should be filed as a separate issue from the Night mode button though.

**Comment by Fordco** [comment] 2019-03-25 00:41
I was not able to reproduce this issue on https://www.freecodecamp.rocks/ on the same version of Chrome as above. I can still produce it on the live site though.

**Comment by chaomt** [comment] 2019-03-31 21:33
I think this issue should be closed since it was already fixed in the beta version, freeCodeCamp.rocks.

**Comment by ojeytonwilliams** [comment] 2019-04-17 14:09
I've verified this is resolved on master, so I'm closing it.  Thanks for the report and checks!

**Closed by ojeytonwilliams** 2019-04-17 14:09 UTC
Labels: status: resolved/shipping
