### ISSUE TITLE
Why I cannot use dot to access object property in such situation? Thank you.

### ISSUE THREAD

**Issue by renewu0707** [FreeCodeCamp/FreeCodeCamp#9494] opened 2016-07-01 19:10 UTC
#### Challenge Name
Everything Be True
Check if the predicate (second argument) is truthy on all elements of a collection (first argument).

#### Issue Description
I was wondering why the codes below cannot pass all tests if I access the object property using dot instead of using []? i.e. if i change collection[i][pre] to collection[i].pre, something went wrong.

Thank you so much for anyone who knows the answer.

#### Your Code
function truthCheck(collection, pre) {
  // Is everyone being true?
  for(var i = 0; i < collection.length; i++){
    //why use dot notation to access object property here cause problems? collection[i].pre
    if(!Boolean(collection[i][pre])){
      return false;
    }
  }
  return true;
}

truthCheck([{"user": "Tinky-Winky", "sex": "male"}, {"user": "Dipsy", "sex": "male"}, {"user": "Laa-Laa", "sex": "female"}, {"user": "Po", "sex": "female"}], "sex");

**Comment by HassHz** [comment] 2016-07-01 20:00
When using variables to access object properties, bracket notation is required.
`collection[i].pre` is the equivalent to `collection[i]["pre"]`, which checks for a property `"pre"` in object, and not what the variable `pre` is equal to (which is what you want).

Note: Ask in the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript), if you are wondering about these things.

**Comment by raisedadead** [comment] 2016-07-02 07:49
@renewu0707 Thanks for reporting. and @HassHz thanks you are correct in the explanation.

Closing as not a bug on the website.

**Closed by raisedadead** 2016-07-02 07:49 UTC

**Comment by renewu0707** [comment] 2016-07-04 19:30
Thank you Hassaan for your answers. It helps me a lot.


Thank you.

Best regards
Rene
