### ISSUE TITLE
getting maximum call stack exceeded

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/FreeCodeCamp#5640] opened 2015-12-31 12:44 UTC
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0A%2F%2FourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(arg1%2C%20arg2)%20%7B%0A%20%20console.log(arg1%20%2B%20arg2)%3B%0A%7D%0A%0AmyFunction(4%2C5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
//ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(arg1, arg2) {
  console.log(arg1 + arg2);
}

myFunction(4,5);

```

**Comment by DDaems** [comment] 2015-12-31 13:31
Duplicate of #5560

**Comment by BerkeleyTrue** [comment] 2015-12-31 17:32
@DDaems Thanks

Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-12-31 17:32 UTC
