### ISSUE TITLE
Synchronization Issue in between multiple computers.

### ISSUE THREAD

**Issue by Aeolionx** [FreeCodeCamp/FreeCodeCamp#12236] opened 2016-12-26 20:04 UTC
If while I have freecodecamp opened on my main computer and I complete anything on another computer, whatever I complete on the other computer does not sync up with other computers. In order to synchronize the completed lessons I have to go to my profile and click 'view solution' and resubmit it. Not a huge issue but might scare some people before they figure out how to sync it up.

I believe this only happens when Im logged on in two locations.
logging out and clearing my Cache does not fix this issue.

Other Info:
Main computer: **Windows** 10 with a chrome browser.
Other computer: **Linux** Xubuntu with Firefox browser.

**Comment by erictleung** [comment] 2016-12-28 00:14
@Aeolionx thanks for the issue. Your code solutions are saved in cache and in the database. So switching computers should not (as of now) show your code, unless you go to our profile, as you've mentioned. So this is the intended behavior of the website. It would be convenient if your code was just pulled down from the database.

cc/ @FreeCodeCamp/moderators this is probably a low priority change if a change were needed. But I'll put this issue up for discussing in case there has been a decision on this.

**Comment by raisedadead** [comment] 2016-12-28 14:13
Yes, that is the intended behavior. And yeah, I am not sure that this can be taken up soon enough, but Pull requests are welcome, I vote this can be tagged help wanted, post we deploy react challenges, so for now, I will just go ahead and tag blocked.

**Comment by Archknight93** [comment] 2016-12-28 16:24
hello


On Wed, Dec 28, 2016 at 3:14 PM, mrugesh mohapatra <notifications@github.com

**Comment by QuincyLarson** [comment] 2016-12-28 23:09
@raisedadead this is a known long-time issue. @BerkeleyTrue thinks we can solve this as part of our move to a multi-file editor interface by writing changes to the database as they happen. I'm closing this issue since addressing this is already on our roadmap.

**Closed by QuincyLarson** 2016-12-28 23:09 UTC
Labels: blocked, discussing
