### ISSUE TITLE
More a Question on Exact change:  

### ISSUE THREAD

**Issue by mcole1976** [FreeCodeCamp/FreeCodeCamp#9867] opened 2016-07-23 22:00 UTC
#### Issue Description

Exact Change
#### Browser Information

Windows Firefox Laptop

: 
#### Your Code

on the penultimate question, there is 1.01 in the till and it states the solution is insufficient funds.  The instructions state that if you have the monetary amount in the till you pass back the change and the array, not a string.  Have I misunderstood the instructions?  Or where the instructions meant to read if you are able to render change then return the change and the array if not render insufficient funds?

``` javascript
var change = cash - price;
  var reply;
  var tillTotal = 0;
  // Here is your change, ma'am.
  for(i = 0; i < cid.length; i++) 

    {
      var monies = cid[i];
      var money = monies[1];

      alert(money);
      tillTotal = tillTotal + money;

      alert(tillTotal);
    }

  if (change < tillTotal)
    {

      reply = [change,cid];
    }
 else if (change == tillTotal)
   {
     reply="closed";
   }
  else if (change > tillTotal)
    {
      reply ="Insufficient Funds";
    }

  alert (change);
  return reply;

'''
#### Screenshot
<!-- Add a screenshot of your issue -->


```

**Comment by pnahratow** [comment] 2016-07-27 07:40
Could you please format your code [See Formatting Help](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

And also concisely rephrase what the problem is "expected behaviour vs. actual behaviour"

**Comment by systimotic** [comment] 2016-11-30 20:51
Hi @mcole1976!
If you there's enough money in the till, you should return an array of change.
If there's not enough money in the till, or the amount in the till is equal to the required amount of changed, you should return a string with the correct message.
You never have to return the cash that is currently in the drawer.

I hope that clears things up.
If you need coding help in the future, please click the "Help" button on the challenge.

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!

**Closed by systimotic** 2016-11-30 20:51 UTC
