### ISSUE TITLE
Autonomous sidebar scrolling

### ISSUE THREAD

**Issue by paulmotz** [FreeCodeCamp/FreeCodeCamp#2360] opened 2015-08-20 20:48 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The sidebar (for clarity, I am referring to the area shown in the attached screenshot) seems to scroll with a mind of its own. I have noticed this on several of the Bootstrap challenges (I did not see this on any HTML challenges). This is usually just a minor nuisance, but can be quite annoying when you are trying to hit a button to go to the next challenge (or submit a bug!).

In addition, the cursor seems to be off in the text editor portion. Typing and selecting text can be off by one line.

![screen shot 2015-08-20 at 4 44 33 pm](https://cloud.githubusercontent.com/assets/7483609/9395155/c307f084-475a-11e5-82cf-49d3f772a8f4.png)

**Comment by BerkeleyTrue** [comment] 2015-08-21 00:45
Duplicate of #2137

**Closed by BerkeleyTrue** 2015-08-21 00:45 UTC
