### ISSUE TITLE
Beta - Define the Head and Body of an HTML Document - Guide Page 404 Not Found

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16817] opened 2018-03-02 04:46 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/define-the-head-and-body-of-an-html-document

#### Issue Description

When selecting the 'Get Hint' button, it re-directs you to the guides but there is no guide page for this challenge.
Returns Page not found.
https://guide.freecodecamp.org/certificates/define-the-head-and-body-of-an-html-document

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36883796-bcefa1a0-1daa-11e8-91e7-e5c2710b7857.png)

**Comment by raisedadead** [comment] 2018-03-02 20:15
Probably worth moving tonthe guides repo if its just a case of the article missing? Or is the article URL incorrect? 

What was the intended behaviour here @QuincyLarson ?

We did have an issue to track the movement of forum wiki to the guides.

**Comment by mstellaluna** [comment] 2018-03-02 20:23
@raisedadead there are other lessons that point to guides these ones seem to be missing. They could be just misplaced into the Miscellaneous category of the guides which seems to hold a large amount of guides or they are stuck in the approval backlog.

**Comment by QuincyLarson** [comment] 2018-03-02 22:41
@raisedadea @mstellaluna this is as-intended. 

We have an open PR to add stubs for all of these challenges to the freeCodeCamp Guide. We are waiting on @Bouncey to figure out a way to be able to merge it, since it will involve us handling more than 4,000 pages on the Guide. This number of files is currently overwhelming Netlify and we're working on a work-around.

Hopefully we'll have this fixed in time to merge these articles before beta goes live.

**Closed** 2018-03-02 22:41 UTC
Labels: beta, status: wontfix

**Comment by mstellaluna** [comment] 2018-03-02 23:38
@QuincyLarson okay i'll close out the other ones referencing this one . thanks !

**Comment by QuincyLarson** [comment] 2018-03-03 01:16
@mstellaluna Awesome - thanks for creating these issues and for closing them.
