### ISSUE TITLE
React PropTypes Challenge Unclear

### ISSUE THREAD

**Issue by jonathanihm** [freeCodeCamp/freeCodeCamp#39204] opened 2020-07-08 02:33 UTC
https://www.freecodecamp.org/learn/front-end-libraries/react/use-proptypes-to-define-the-props-you-expect

In the instructions and unit tests are ambiguous with the word "required".

It states:
"The Items component should include a propTypes check that requires quantity to be a number."

This is unclear as "requires" could mean that this check just simply needs to exist for the test to pass or that quantity should be a number that is required. 

I suggest either changing the above wording, or adding an additional unit test:
"The Items component should include a quantity propType that is required."

**Comment by nhcarrigan** [comment] 2020-07-08 02:37
![image](https://user-images.githubusercontent.com/63889819/86868275-40e4a400-c089-11ea-8c77-b6801fa7d4f3.png)

I think the lesson instructions are pretty clear, but I do agree that the test case wording is ambiguous. I would propose that the test message be edited to mirror this instruction.

**Comment by RandellDawson** [comment] 2020-07-08 06:36
I do not think the test text should just be a duplicate of the instruction.  That would be redundant.  Instead, we need to rewrite the text to reflect was is being tested.  See below for the current testString prettified:

```yml
assert((function() {
  const noWhiteSpace = getUserInput('index').replace(/ /g, '');
  return noWhiteSpace.includes('quantity:PropTypes.number.isRequired') && noWhiteSpace.includes('Items.propTypes=');
})());
```
The important part of the test in the return statement.  We are validating that we see the text "quantity:PropTypes.number.isRequired" and "Items.propTypes='" after removing whitespaces from the code.  There probably is a better testString that could be written also.

**Comment by nhcarrigan** [comment] 2020-07-08 06:44
I cannot think of a more effective testString, personally. But for the test text, perhaps something like "The `Items` component should include a `propTypes` check to require a value for quantity and ensure that value is a number."

**Comment by jonathanihm** [comment] 2020-07-09 01:02
https://www.freecodecamp.org/learn/front-end-libraries/react/review-using-props-with-stateless-functional-components

Has the same clarity issue, thanks!

**Comment by jp-sauve** [comment] 2020-09-24 15:46
I agree that the text should be updated. I just got caught up by the unclear instructions. The way it is, I thought that what was 'required' was that quantity be a number. It doesn't suggest to me that a quantity is required.

**Comment by RandellDawson** [comment] 2020-09-24 19:33
Opening this PR for contributions.  The test text should be changed to:
>The Items component should include a <code>propTypes</code> check to require a value for <code>quantity</code> and ensure that its value is a number.

**Closed** 2020-09-25 06:11 UTC
Labels: first timers only, scope: learn
