### ISSUE TITLE
Can't pass even though variables are correct. 

### ISSUE THREAD

**Issue by VrianSinth** [FreeCodeCamp/FreeCodeCamp#9253] opened 2016-06-20 22:01 UTC
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0A%0Avar%20studlyCapVar%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0AstudlyCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

var studlyCapVar;
var properCamelCase;
var titleCaseOver;

studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

```

![image](https://cloud.githubusercontent.com/assets/13907305/16211653/18778f76-3700-11e6-8803-efb9f4cb7f50.png)

**Comment by arun1595** [comment] 2016-06-20 22:15
The issue is that the test asserts that `code.match(/properCamelCase/g).length === 2`
ie. it makes sure that there's only two `properCamelCase` in the code. It expects you to modify the existing code but since you added your own versions, the count of `properCamelCase` is 3. A quickfix would be to change `var properCamelCase` in the challengeSeed.

**Comment by erictleung** [comment] 2016-06-20 22:19
@VrianSinth please reread the instructions:

> **Fix** the variable declarations and assignments so their names use camelCase.

And as @arun1595 has pointed out, you'll need to fix the variable declarations in the editor rather than write your own. Closing as not a bug on the site. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Closed by erictleung** 2016-06-20 22:19 UTC

**Comment by Kodin24** [comment] 2016-11-13 03:27
arun1595   A quickfix would be to change var properCamelCase in the challengeSeed. how do you do that?

**Comment by ar94952** [comment] 2017-03-11 06:40
i'm slightly baffled by this challenge.  the studlyCapVar already has a value of 10, but the challenge states that it isn't declared.

**Comment by hasmukhgagal** [comment] 2017-03-29 13:42
are you declare studlyCapVar two times ?

if you are not assign the studlyCapVar second time so please assign.

**Comment by Vicneswari** [comment] 2017-05-18 08:14
![capture](https://cloud.githubusercontent.com/assets/28776853/26192595/feece610-3be4-11e7-83d1-5c684d920122.PNG)



TRY THIS -->


// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
properCamelCase = "A String";
tITLEcASEoVER = 9000;

var studlyCapVar;
var PRoperCAmelCAse;
var titleCaseOver;

studlyCapVar = 10;
PRoperCAmelCAse = "A String";
titleCaseOver = 9000;

**Comment by texas2010** [comment] 2017-05-18 15:08
@Vicneswari 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!
