### ISSUE TITLE
Emoji picker in the preference section of the forum profile is out of place

### ISSUE THREAD

**Issue by torates** [freeCodeCamp/freeCodeCamp#38417] opened 2020-03-23 00:07 UTC
**Describe the bug**
When in the forum's profile settings, and trying to change your 'about me' status in the preferences section, it's impossible to add Emojis thanks to the emoji-picker being out of place, and out of the website's flow.

**To Reproduce**
1. Go to freeCodeCamp forum
2. Click on 'Profile'
3. Click in your username left to the bell
4. Click 'Preferences;
5. Click 'Profile' at the left of the page.
6. Click on the emoji icon that's over the 'About me' text field.

**Expected behavior**
The emoji picker should have been in the right place, not to the top of the whole page and out of the flow, but just in the perfect spot over the 'About me' text field.

**Screenshots**
![image](https://user-images.githubusercontent.com/59488791/77267267-5c769b00-6ca2-11ea-9564-0c9d64018b50.png)

**Desktop (please complete the following information):**
 - OS: Windows 64 bits
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by moT01** [comment] 2020-03-23 01:18
I'm not seeing it on High Sierra + Firefox...
<img width="604" alt="Screen Shot 2020-03-22 at 8 13 45 PM" src="https://user-images.githubusercontent.com/20648924/77270534-350bd800-6c7a-11ea-9bd4-a9d0bc948320.png">


Are there any browser extensions you are using that might be altering styles? Have you tried any other browsers by chance?

**Comment by PATHAKABHISHEK** [comment] 2020-03-23 04:39
# I am seeing this bug in Firefox and Chrome


![Screenshot (7)](https://user-images.githubusercontent.com/34957434/77281839-3e368c80-6cee-11ea-97e2-97f3d01540c3.png)

![Screenshot (8)](https://user-images.githubusercontent.com/34957434/77281841-40005000-6cee-11ea-8ae6-2f4fb52a04f3.png)

**Comment by ahmadabdolsaheb** [comment] 2020-06-06 06:49
I cannot reproduce this on chrome on Catalina.

**Comment by nhcarrigan** [comment] 2020-06-06 06:53
I am also unable to reproduce this bug.

**Comment by ahmadabdolsaheb** [comment] 2020-06-08 11:23
seems like it is being reported from windows machines. @nhcarrigan, what OS are you using?

**Comment by Sky020** [comment] 2020-06-08 12:15
Just to add my experience - this is what I get in my console on that page:
![image](https://user-images.githubusercontent.com/51722130/84028624-f9cf9a00-a988-11ea-908b-2dcbf4aad086.png)

When I click on the emoji picker, nothing shows up anywhere on the page.

Also, every few seconds this request is made and errored out:
![image](https://user-images.githubusercontent.com/51722130/84028723-24b9ee00-a989-11ea-9c5b-ec07fed2101f.png)

**Comment by nhcarrigan** [comment] 2020-06-08 15:02
@ahmadabdolsaheb I am running Windows 10 Home, updated to the latest version.

**Comment by ojeytonwilliams** [comment] 2020-06-08 18:40
I've also been unable to reproduce this using Firefox and Chrome on both Windows and Linux.

One possibility is that it could be clashing with a browser extension.  @PATHAKABHISHEK @torates, could you try with the extensions disabled (via an incognito window, for example)?

**Comment by ahmadabdolsaheb** [comment] 2020-06-10 04:10
Hmm, it is possible that this is a discourse issue and not something caused by our theme modifications. If you have access to the default theme or have a meta.discourse.org/ account, you could double check that.

**Comment by moT01** [comment] 2020-09-15 16:17
bump

**Comment by ahmadabdolsaheb** [comment] 2020-11-26 18:54
I am unable to reproduce this issue, and we are reverting most of our theme customizations; Therefore I will be closing this issue accordingly.

Please re-open this issue if the problem persists.

**Closed by ahmadabdolsaheb** 2020-11-26 18:54 UTC
Labels: platform: forum, type: bug
