### ISSUE TITLE
Rangeerror : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eranmor** [FreeCodeCamp/FreeCodeCamp#6665] opened 2016-02-02 05:08 UTC
Challenge [Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(c%2C%20d)%7B%0A%20%20console.log(c%20%2B%20d)%3B%0A%7D%0AmyFunction(1%2C2)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Put this code in Chrome dev tools and got 3. Run it on FCC and get this error, please advise.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(c, d){
  console.log(c + d);
}
myFunction(1,2);
```

**Comment by sludge256** [comment] 2016-02-02 06:52
Try refreshing the page or restarting your browser.

**Comment by raisedadead** [comment] 2016-02-02 07:07
Duplicate of #6183

**Comment by sludge256** [comment] 2016-02-02 07:15
Closing as duplicate. Thanks @raisedadead

**Closed by sludge256** 2016-02-02 07:15 UTC
