### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by w280561543** [FreeCodeCamp/FreeCodeCamp#6647] opened 2016-02-01 14:16 UTC
Challenge [Say Hello to HTML Elements](http://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

```
 Uncaught TypeError: Cannot read property 'join' of null

vendor-main-00eff8238f.js:30

**Comment by bugron** [comment] 2016-02-01 14:18
@w280561543 thanks for posting this issue!
I'm going to close this issue as a duplicate of #6633 but, please, comment there your issue and post a screenshot of your browser's console and Network tab too, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-02-01 14:18 UTC
