### ISSUE TITLE
Spanish translation of Get Started with Free Code Camp Site 

### ISSUE THREAD

**Issue by pcimagenca** [FreeCodeCamp/FreeCodeCamp#8327] opened 2016-04-28 08:22 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by alistermada** [comment] 2016-04-28 09:07
There's already a Spanish translation for Get Started with Free Code Camp. Duplicate of #4539.

**Comment by theflametrooper** [comment] 2016-04-28 09:08
Thanks @alistermada !!

**Closed** 2016-04-28 09:08 UTC
Labels: duplicate, translation
