### ISSUE TITLE
Items are getting clipped off top of screen when viewing my portfolio 

### ISSUE THREAD

**Issue by zcarroll4** [freeCodeCamp/freeCodeCamp#37517] opened 2019-10-24 20:55 UTC
**To Reproduce**
1. Click Learn Button
2. Click View My Portfolio
3. See error

**Issue**
If you navigate to your portfolio page, the items at the top of the screen will be getting clipped.

**Screenshots**
![image](https://user-images.githubusercontent.com/38516457/67524433-b127d280-f67e-11e9-8178-880bd89e4ad0.png)

**Comment by raisedadead** [comment] 2019-10-24 21:02
Thanks for your report, closing duplicate of #37395

**Closed by raisedadead** 2019-10-24 21:02 UTC
Labels: type: bug
