### ISSUE TITLE
Challenge [Create Decimal Numbers with JavaScript]

### ISSUE THREAD

**Issue by p1xtcode** [FreeCodeCamp/FreeCodeCamp#6324] opened 2016-01-19 18:00 UTC
Challenge [Create Decimal Numbers with JavaScript](http://www.freecodecamp.com/challenges/create-decimal-numbers-with-javascript#?solution=var%20ourDecimal%20%3D%205.7%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myDecimal%20%3D%201.1%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDecimal = 5.7;

// Only change code below this line
var myDecimal = 1.0;


```
The value 1.0 contains a decimal and is thus a floating point number, yet fails the test case.

**Comment by ltegman** [comment] 2016-01-19 18:09
Closing as a duplicate of #6306. In the future please [Search for your Issue on Github](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github) before creating a new issue.

**Closed by ltegman** 2016-01-19 18:09 UTC
