### ISSUE TITLE
Code works, won't pass. Firefox, works on chrome

### ISSUE THREAD

**Issue by notunderground** [FreeCodeCamp/FreeCodeCamp#3494] opened 2015-09-25 11:55 UTC
Challenge  Waypoint: Add Borders Around your Elements  http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements  has an issue. User Agent is: code>Mozilla/5.0  Windows NT 6.3; WOW64; rv:41.0  Gecko/20100101 Firefox/41.0 /code>. Please describe how to reproduce this issue, and include links to screenshots if possible. My code:    html link href  http://fonts.googleapis.com/css?family Lobster rel  stylesheet type  text/css > style> .red-text { color: red; } h2 { font-family: Lobster, Monospace; } p { font-size: 16px; font-family: Monospace; } .smaller-image { width: 100px; } .thick-green-border { border-style: solid; border-color: green; border-width: 10px; }  /style> h2 class  red-text >CatPhotoApp /h2> img class  thick-green-border smaller-image src  https://bit.ly/fcc-relaxing-cat > p class  red-text >Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. /p> p class  red-text >Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. /p>

**Comment by jhealy86** [comment] 2015-09-25 13:23
Could you please repost your code using the code tags? That will help readability, and in this case there are some characters getting lost. Just copy and paste this:

\`\`\`html
Your code goes here
\`\`\`

**Comment by notunderground** [comment] 2015-09-25 14:13
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by notunderground** [comment] 2015-09-25 14:14
border-width: 10px; is the test that doesn't pass

**Comment by bugron** [comment] 2015-09-25 14:26
@notunderground thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3204 so I'll close it. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-25 14:26 UTC
