### ISSUE TITLE
FreeCodeCamp - create a Form is not letting me "clear" the excercise, not trusting the code(Chrome issue?)

### ISSUE THREAD

**Issue by Flammendeingo-85** [freeCodeCamp/freeCodeCamp#14793] opened 2017-05-09 11:56 UTC
#### Challenge Name

[https://www.freecodecamp.com/challenges/create-a-form-element](https://www.freecodecamp.com/challenges/create-a-form-element#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%3E%0A%3Cform%20action%3D%22%22%0A)

#### Issue Description

When you fill in the HTML code: <form action=""></form>, Freezes and on the right it gives me he explanaition that : "Chrome heeft ongebruikelijke code op deze pagina gedetecteerd en heeft de code geblokkeerd om je persoonlijke gegevens (zoals wachtwoorden, telefoonnummers en creditcards) te beschermen."( it blocked the code, and it doesnt trust it, and is doing it to protect my personal info and more).

#### Browser Information

* Browser Name, Version: Google Chrome Versie 58.0.3029.96 (64-bit)
* Operating System: Wndows 10 Pro NL 64 Bit
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot
![image](https://cloud.githubusercontent.com/assets/21306832/25849339/6088bff8-34be-11e7-8c43-2521f57edb66.png)

**Comment by Margaret2** [comment] 2017-05-09 14:39
It's because you haven't completed your `<form>` element. You need to type in the complete `<form></form>` and refresh the page to get it working again. Happy coding!

**Comment by raisedadead** [comment] 2017-05-09 15:17
Duplicate of #13727 
Please look for open issues before reporting.

**Closed by raisedadead** 2017-05-09 15:17 UTC
