### ISSUE TITLE
[beta] challenge html/css output not visible until code is run

### ISSUE THREAD

**Issue by Talkingbaby** [freeCodeCamp/freeCodeCamp#12859] opened 2017-01-25 23:58 UTC
Challenge [change-the-position-of-overlapping-elements-with-the-zindex-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/change-the-position-of-overlapping-elements-with-the-zindex-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The content from the previous exercise is shown but not the content from the current exercise. The content only reveals itself when the challenge is completed.

```html
    
    
<style>
div {
  width: 60%;
  height:200px;
  margin-top: 20px;
}

.first {
  background-color: red;
  position: absolute;
  z-index: 2;
}
.second {
  background-color: blue;
  position: absolute;
  left: 40px;
  top: 50px;
  z-index: 1;
}
</style>

<div class="first"></div>
<div class="second"></div>

    ```

**Comment by tommygebru** [comment] 2017-01-26 00:39
Works well for me!
Working on MBP with Google Chrome

**Comment by no-stack-dub-sack** [comment] 2017-01-26 04:23
@Talkingbaby I can confirm this, when I loaded the challenge, the instructions refer to a red rectangle and a blue rectangle, but neither element is visible for me until I complete the challenge. I jumped right to this challenge and did not complete the one prior to it. 

I am on Chrome, latest version, on Mac OSX 10.11.6 

@tommygebru When you loaded the challenge, could you see the rectangles in the smartphone element before you adjusted the z-index?

**Comment by tommygebru** [comment] 2017-01-26 04:27
Will the issue repeat if i reset the exercise?
otherwise it is pretty much an elusive bug to catch 😜

**Comment by no-stack-dub-sack** [comment] 2017-01-26 04:30
@tommygebru the bug does not seem to repeat even if the code is cleared, so it is a bit elusive. I think if local storage was cleared it might reset the issue, but I wouldn't recommend doing that since other FCC data is likely stored there as well. So, it would seem this only occurs the first time the challenge is run, which of course is the most important time 😄

**Comment by no-stack-dub-sack** [comment] 2017-01-26 04:43
Actually, this was reported in #12807, please see that issue, closing this as duplicate

**Closed by no-stack-dub-sack** 2017-01-26 04:43 UTC
Labels: beta

**Comment by tommygebru** [comment] 2017-01-26 05:01
So I reset my browser history, the beta.fcc saved my points and map,
**the challenge page actually loaded without any divs!**
Applied Visual Design: Change the Position of Overlapping Elements with the Z-index Property

![screen shot 2017-01-25 at 8 56 29 pm](https://cloud.githubusercontent.com/assets/7606025/22320395/fd85ecb0-e340-11e6-85a1-45960cf6dd97.png)

**I reset the exercise and the divs appeared**

and the divs changed indexes exactly as the modal appeared or I ran the test....

**Comment by tommygebru** [comment] 2017-01-26 05:12
@no-stack-dub-sack  after re-reading your earlier posts

"@tommygebru When you loaded the challenge, could you see the rectangles in the smartphone element before you adjusted the z-index?"

In short, no.

**Comment by no-stack-dub-sack** [comment] 2017-01-26 18:12
@tommygebru cool, thanks for double-confirming, I've closed this one though since it was reported elsewhere and we can continue the conversation there. :+1:
