### ISSUE TITLE
Test failing with correct input.

### ISSUE THREAD

**Issue by haleybear** [freeCodeCamp/freeCodeCamp#17423] opened 2018-06-03 21:12 UTC
#### Describe your problem and - if possible - how to reproduce it
On the "Applied Visual Design - Adjust the Height of an Element Using the height Property" changing the height to 25px does not pass the test.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/36253327/40891282-dce90934-6750-11e8-90fd-bb60c2e1df29.png)

**Comment by moT01** [comment] 2018-06-11 21:39
@haleybear I cannot reproduce this - it may have been fixed - do you want to try again and close this if it seems to be working now

**Comment by moT01** [comment] 2018-07-27 14:14
Thank you for reporting this issue.

    I am closing this issue as it seems to be fixed now.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Closed by moT01** 2018-07-27 14:14 UTC
