### ISSUE TITLE
Passing 'class-getters-and-setters' with insufficient code.

### ISSUE THREAD

**Issue by AWulkan** [freeCodeCamp/freeCodeCamp#12988] opened 2017-01-30 20:56 UTC
Challenge [class-getters-and-setters](https://beta.freecodecamp.com/en/challenges/es6/class-getters-and-setters) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The tests for this challenge appears to not be working correctly. I was able to pass it by only typing this code:

```js

/* Alter code below this line */
class Thermostat {
  
}
/* Alter code above this line */
const thermos = new Thermostat(76); // setting in Farenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C
```

It appears that other people can also pass it with that code, so it's not just a problem for me. Also, when actually trying to solve it correctly it crashes, leaving this as a result:

```
"Maximum call stack size exceeded"
"Maximum call stack size exceeded"
"Maximum call stack size exceeded"
```

**Comment by Greenheart** [comment] 2017-01-30 23:03
@AWulkan Thanks for reporting this, and for the good information to help triaging!

The ES6 challenges are known to be a bit buggy at the moment due to some problems with the transpiled code. However this particular issue is caused by the lack of tests. As you can see [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L847-L849), the test cases are actually nothing more than comments.

(Technically, strings evaluate to the boolean `true`, which makes them pass in the test framework).

I'm closing this as it's being discussed in #12698 

Thanks again, and happy bug hunting! :smile:

**Closed by Greenheart** 2017-01-30 23:03 UTC
