### ISSUE TITLE
Loading data from http://www.freecodecamp.com/news/hot error

### ISSUE THREAD

**Issue by linuxenko** [FreeCodeCamp/FreeCodeCamp#7748] opened 2016-03-27 11:33 UTC
Demo http://codepen.io/FreeCodeCamp/full/KVNNXY of https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph challenge

```
XMLHttpRequest cannot load http://www.freecodecamp.com/news/hot. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.
```

Challenge [Show Relationships with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by raisedadead** [comment] 2016-03-27 13:20
Closing as duplicate of #7617 
Request you to please search thru open issues before opening new issues.

**Closed by raisedadead** 2016-03-27 13:20 UTC

**Comment by raisedadead** [comment] 2016-03-27 13:23
Also refer #7700 for ongoing fixes
