### ISSUE TITLE
bug Your p element should contain the first few words of the provided additional kitty ipsum text.

### ISSUE THREAD

**Issue by ngnam** [freeCodeCamp/freeCodeCamp#14557] opened 2017-04-23 16:22 UTC
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20text.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%20text.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum text.</p>

<p>Kitty ipsum text.</p>

```

**Comment by rholinshead** [comment] 2017-04-23 19:37
This is not a bug. The additional text is: 

> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

**Comment by erictleung** [comment] 2017-04-23 20:39
@ngnam Thank you for reporting this issue. As @rholinshead has pointed out, you're using the wrong text.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Closed by erictleung** 2017-04-23 20:39 UTC

**Comment by Don-E-S** [comment] 2017-06-04 08:20
Here is some additional info that may help.

Firefox does not have a 100% setting. To get this exercise to pass it was necessary to go to "view" - "full screen" before  the system would accept the second paragraph of 'Kitty ipsum' text. Then I had to close Firefox to get out of full screen mode.
