### ISSUE TITLE
Helpful link URL directs to FCC instead of MDN

### ISSUE THREAD

**Issue by Murkrage** [FreeCodeCamp/FreeCodeCamp#8430] opened 2016-05-03 17:54 UTC
#### Challenge Name
https://www.freecodecamp.com/challenges/missing-letters

#### Issue Description
The link that should direct to 'String.charCodeAt()', directs to the FCC map instead of the MDN page.

#### Browser Information
* Chrome, Version: 50
* Operating System: OSX

**Comment by raisedadead** [comment] 2016-05-03 18:06
Duplicate of #8423 
Fixed in #8425

**Comment by raisedadead** [comment] 2016-05-03 18:07
HOLD your horses!

**Closed by raisedadead** 2016-05-03 18:06 UTC
Labels: easy, help wanted

**Comment by sludge256** [comment] 2016-05-03 18:07
:hand: :horse_racing:

**Comment by sludge256** [comment] 2016-05-03 18:10
@Murkrage Thanks for the report, we have a fix for it already. Don't mind my incompetence with the labels :stuck_out_tongue_winking_eye:

**Comment by Murkrage** [comment] 2016-05-03 18:20
@sludge256 Haha no problem. For some reason I didn't see the duplicate. My bad :)
