### ISSUE TITLE
Iterate Through an Array with a For Loop - Multiple Initializations

### ISSUE THREAD

**Issue by alexalexson143** [freeCodeCamp/freeCodeCamp#12012] opened 2016-12-12 14:26 UTC
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%0A%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afor%20(var%20total%20%3D%200%2C%20i%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20total%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line

for (**var total = 0**, i = 0; i < myArr.length; i++) {
  total += myArr[i];
}


```

Multiple initialization not accepted as correct solution.

**Comment by ajain17** [comment] 2016-12-12 15:44
Its a valid issue, can verify it at my end. Can we add the tag help needed?

**Comment by ajain17** [comment] 2016-12-12 15:45
We can go two ways, either allow multiple initialization, or include in instructions that 'total' needs to be declared and initialized separately at the top along with other declarations.

**Comment by raisedadead** [comment] 2016-12-12 16:04
@alexalexson143 thanks for the issue report. @ajain17 thanks a lot for the triage.

We would be more interested in this
> allow multiple initialization

Anyone up for analyzing the cause? This is potenitally a candidate for fixes with way code runner and the tests evaluate the for loops?

Maybe have a look at the loopProtect code as well?

Here is a link that will help in debugging the code in the Crome Dev tools.
https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps

**Comment by erictleung** [comment] 2016-12-12 17:10
@raisedadead this should have been fixed with my PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9529. It looks like these changes haven't been pushed up yet (or they got lost somewhere) because I changed the example code from `var i=0` to `var i = 0` doesn't exist on the live site.

**Comment by raisedadead** [comment] 2016-12-12 17:22
Darn... that's sad. Given the fact that I completely forgot about this having merged it. I am taking a look at the blame, will update soon. 

@erictleung thanks for bringing this to notice.

**Comment by raisedadead** [comment] 2016-12-12 17:31
Okay, just confirmed. The changes are on staging via https://github.com/FreeCodeCamp/FreeCodeCamp/commit/f8425780ec0f9866354e5ce23e745a2d5e9f6ebc

And the blame on Line 5268 and others is still yours.

https://github.com/FreeCodeCamp/FreeCodeCamp/blame/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L5268

Basically this should get fixed when we merge to master during future release?

**Comment by zaki1993** [comment] 2016-12-18 15:47
You can do this
`c++
 int a[] = {0, 1, 2, 3, 4, 5};
    for (int n : a) // the initializer may be an array
        std::cout << n << ' ';
    std::cout << '\n';
 
    for (int n : a)  
        std::cout << 1 << ' '; // the loop variable need not be used
    std::cout << '\n';
```
Then if your server support c++ converting to html or to javascript its much easier ;)

**Comment by raisedadead** [comment] 2016-12-18 16:02
@zaki1993 thanks but, we execute all of the challenges client side (in the user's browser). We do not have any support for C++ or other languages.

**Comment by AaronOB7** [comment] 2016-12-21 19:47
// Setup
var myArray = [];

// Only change code below this line.
for (var i = 1; i<6;i++)
{
  myArray.push(i);
}

**Comment by systimotic** [comment] 2017-09-05 20:05
Closing as this has been resolved in the beta. Happy coding!

**Closed by systimotic** 2017-09-05 20:05 UTC
Labels: resolved in staging
