### ISSUE TITLE
Missing Challenges

### ISSUE THREAD

**Issue by RoniqueRicketts** [freeCodeCamp/freeCodeCamp#12941] opened 2017-01-28 17:53 UTC
#### Issue Description
Open Map and go to the Basic Algorithm Scripting.
Api and Microservices Project first challenge is also missing

#### Browser Information

* Browser Name, Version:  55.0.2883.87 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

![one](https://cloud.githubusercontent.com/assets/17409035/22398545/b841e3ce-e558-11e6-837c-bf25ac7bc816.jpg)
![two](https://cloud.githubusercontent.com/assets/17409035/22398546/b84587a4-e558-11e6-8d25-95f9f1114df5.jpg)

**Comment by Greenheart** [comment] 2017-01-28 21:21
@RoniqueRicketts Thanks for reporting!

Looking at the source for the links, there's no content in the second expanded `p.challenge-title > a > span` and empty links without content are not rendered.

![missing-link](https://cloud.githubusercontent.com/assets/6125097/22399908/ad7ff44a-e5a7-11e6-8851-565f4c87880a.png)

I guess this problem is caused by some faulty data used to generate this link. I'll continue the search in the seed for this challenge and see if something is out of place.

**Comment by tommygebru** [comment] 2017-01-29 17:11
[CLOSED] 
Duplicate issues:
 #12919 
 #12842

**Comment by QuincyLarson** [comment] 2017-01-31 22:20
Thanks everyone. We've now fixed this on staging.

**Closed by QuincyLarson** 2017-01-31 22:20 UTC
