### ISSUE TITLE
Weather data in Local Weather App example is not displaying

### ISSUE THREAD

**Issue by ashi2014** [FreeCodeCamp/FreeCodeCamp#3726] opened 2015-10-13 05:27 UTC
In the The Local Weather App example (http://codepen.io/AdventureBear/pen/yNBJRj), the weather information (temperature, current weather, and wind speed) is no longer showing up. The reason appears to be that the Open Weather Map API where the app is pulling the data from now requires you to sign up for an API key. I tested this out on my own version and once I added the key, the page worked again.

![image](https://cloud.githubusercontent.com/assets/7401767/10446162/3ee7c6ee-7130-11e5-8f2e-f1a5dbccd867.png)

**Comment by BerkeleyTrue** [comment] 2015-10-13 06:02
Closing as duplicate of #3714 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-10-13 06:02 UTC
