### ISSUE TITLE
Links in the "Email" portion of the "Settings" page kick back errors

### ISSUE THREAD

**Issue by lazarillo** [FreeCodeCamp/FreeCodeCamp#7822] opened 2016-03-31 05:23 UTC
#### Issue Description
* When:  whenever I try to opt out (click off the green "on" button) of any of the e-mail options on my personal settings
* When:  every time.  I refreshed the site several times, tried all of the e-mail buttons (all 3).
* Steps to reproduce:  go to the settings page (my user ID is lazarillo, in case it is user-specific), move down to "e-mail settings", click on any of the green "on" buttons.  It will spin for a while, and then kick back an error page that says "Oops, something went wrong!  Try again later!", and the remainder of the page will list all of my accomplishments to date.

#### Browser Information
* Browser Name, Version:  Google Chrome Version 49.0.2623.87 (64-bit)
* Operating System:  Mac OS X 10.11.3

#### Screenshot

<img width="1362" alt="screen shot 2016-03-30 at 10 21 04 pm" src="https://cloud.githubusercontent.com/assets/636798/14166192/0a7d1334-f6c6-11e5-9b1a-c297de9bb607.png">
<img width="1360" alt="screen shot 2016-03-30 at 10 20 47 pm" src="https://cloud.githubusercontent.com/assets/636798/14166191/0a7d0ab0-f6c6-11e5-9b6c-fb0876eb67bb.png">

**Comment by erictleung** [comment] 2016-04-05 06:52
I was unfortunately unable to reproduce this. There was an update to the main site recently so maybe try again to see if it is fixed?

**Comment by raisedadead** [comment] 2016-04-17 08:54
Hi @lazarillo This may have been resolved with #7690 
Can you confirm that this still issue still exists for you?

**Comment by raisedadead** [comment] 2016-04-20 10:51
Closing. Please feel free to comment below if you are still facing this.

**Closed by raisedadead** 2016-04-20 10:51 UTC
Labels: accounts, blocked

**Comment by lazarillo** [comment] 2016-04-22 19:31
Apologies for slow reply, yes, things are all working OK for me now.  Thank you for closing.

**Comment by taintttickler49** [comment] 2016-04-23 04:12
My balls in your browser window 

Deez Nuts....

-----Original Message-----
