### ISSUE TITLE
Spelling error in Basic Node and Express - Get Route Parameter Input from the Client

### ISSUE THREAD

**Issue by sheikheddy** [freeCodeCamp/freeCodeCamp#17991] opened 2018-08-08 12:38 UTC
#### Describe your problem and - if possible - how to reproduce it
it says 'communicate us' instead of 'communicate to us'
How to reproduce it? Just go to the page :P

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/get-route-parameter-input-from-the-client

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/30148602/43837262-0119f56e-9b29-11e8-86d0-f7f85f29656b.png)

**Comment by moT01** [comment] 2018-08-08 13:17
its missing an `m` in communicate as well, - this is where the problem is => https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/05-apis-and-microservices/basic-node-and-express.json#L190

**Comment by RyanPisuena** [comment] 2018-08-08 17:18
Hello all parties involved,

Below is a pull request for the grammar edit for you two.

**Comment by halcyondays22** [comment] 2018-08-11 03:14
Is this issue still needing to be solved?  I'd like to work on it if so!

**Comment by fatimah5** [comment] 2018-08-15 00:13
This is my first contribution, I would like to try to fix this problem by replacing the word 
"comunicte us" to "communicate us".

Thank you.

**Comment by krbrennan** [comment] 2018-08-17 16:40
This is a duplicate of issue #244. I submitted changes to this one but some other zealot fixed 50 typos so this current issue is either fixed or will be fixed very shortly.

**Closed** 2018-08-21 10:11 UTC
Labels: first timers welcome
