### ISSUE TITLE
Use Clockwise Notation - Tests fail if you add any comment code.

### ISSUE THREAD

**Issue by T4JC** [freeCodeCamp/freeCodeCamp#34861] opened 2019-01-12 20:44 UTC
On the Basic CSS: Use Clockwise Notation to Specify the Padding of an Element Lesson.

If you fulfil the course as instructed but also add comments in a multi-line format  such as: 
/* 
aaaa
*/
Placed outside of the relevant style block and also within it will cause one of the tests will fail and state 'You should use the clockwise notation to set the padding of blue-box class.' 

Even though the provided  answer is correct, the commenting breaks the test, this is not the case on previous CSS lessons as I usually add comments.
<img width="1428" alt="screenshot 2019-01-12 at 20 41 28" src="https://user-images.githubusercontent.com/32134629/51078297-cc56c200-16aa-11e9-9392-c7209f44857c.png">
<img width="1428" alt="screenshot 2019-01-12 at 20 41 28" src="https://user-images.githubusercontent.com/32134629/51078301-d5479380-16aa-11e9-9172-4f80f4ca6c39.png">

https://learn.freecodecamp.org/responsive-web-design/basic-css/use-clockwise-notation-to-specify-the-padding-of-an-element

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Mac OSX Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment] 2019-01-16 06:39
I'm not able to reproduce this, it passes for me:
![image](https://user-images.githubusercontent.com/34807532/51230870-7f633c00-1987-11e9-8bf2-1df2f717d518.png)

**Comment by Fordco** [comment] 2019-01-27 21:48
I also was unable to reproduce this issue. 
![image](https://user-images.githubusercontent.com/21327614/51807278-013e4980-2253-11e9-9490-943ee9e55e28.png)
![image](https://user-images.githubusercontent.com/21327614/51807293-23d06280-2253-11e9-86e8-e91465f44cb9.png)

@T4JC  could you show us your solution for the blue box?

**Comment by thecodingaviator** [comment] 2019-01-28 15:37
@ezioda004 I think we can close this

**Comment by ronaldcs** [comment] 2019-02-06 03:43
Note, this issue **is** reproducible. All it takes is having the comment text contain `padding-top` or any padding-* variant to cause the issue. The issue occurs anywhere within the code (e.g. inside or outside the `<style>` block.

![image](https://user-images.githubusercontent.com/4138434/52319285-e5475000-2996-11e9-8d13-5482bad843b5.png)

**Comment by ronaldcs** [comment] 2019-02-07 01:54
Pretty much edge case, but created a PR for it (shrug).

**Comment by paulywill** [comment] 2019-02-21 20:53
Should there not be another test for not including comments?

**Closed** 2019-03-13 17:55 UTC
Labels: scope: curriculum, status: ready for QA
