### ISSUE TITLE
General glitchiness to code editor in exercises

### ISSUE THREAD

**Issue by lacroixpool** [FreeCodeCamp/FreeCodeCamp#8877] opened 2016-05-31 19:59 UTC
#### Issue Description

This has been happening to me since I began using the built in code camp code editor during the exercises.

When I try to click on a particular line of code, I am unable to click on half of that line. Also, when I try to highlight any code, it sometimes won't allow me to. And sometimes when I click on the area I wish to enter code, the cursor will end up two lines down. I have been able to work around this by hitting the browser resize button (on chrome) with every new exercise. However, it gets a bit tiresome.

I tried using the site in Firefox, with the same problem.

#### Browser Information

* Browser Name, Version: Chrome Version 50.0.2661.102 (64-bit)
* Operating System: Mac OS X 10.11.3 (15D21)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by BattleToads** [comment] 2016-05-31 20:30
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847

**Comment by raisedadead** [comment] 2016-05-31 20:37
@lacroixpool Closing as duplicate of #7847, please follow the discussion there.
Also please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

@BattleToads thanks.

**Closed by raisedadead** 2016-05-31 20:37 UTC
