### ISSUE TITLE
Bonfire: Factorialize a Number - interface did't pass me further

### ISSUE THREAD

**Issue by Heretic888** [FreeCodeCamp/FreeCodeCamp#5290] opened 2015-12-14 17:43 UTC
Challenge [Bonfire: Factorialize a Number](http://www.freecodecamp.com/challenges/bonfire-factorialize-a-number#?solution=var%20z%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for(var%20i%20%3D%201%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20z%20%3D%20z%20*%20i%3B%20%20%0A%20%20%7D%0A%20%20return%20z%3B%0A%7D%0A%0Afactorialize(20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
I wrote the code below a I got true result. But the interface did't pass me further. I think it is a bug.
![freecodecamp_bugscreen](https://cloud.githubusercontent.com/assets/13378337/11788615/04955e6c-a2a3-11e5-98ae-28aa401d0b79.jpg)

My code:
```javascript
var z = 1;
function factorialize(num) {
  for(var i = 1; i <= num; i++) {
    z = z * i;  
  }
  return z;
}

factorialize(20);

```

**Comment by sludge256** [comment] 2015-12-14 17:58
Code passes if you move `var z = 1;` into the function.
Someone with more expertise will probably be able explain why it's not passing.

**Comment by Heretic888** [comment] 2015-12-14 18:12
I understand this. But in all cases I got a proper response. Something wrong.

**Comment by SaintPeter** [comment] 2015-12-14 18:43
The problem is that your `z` definition is global.  It never gets reset to 1.  So the first time it runs, everything is fine, but for each subsequent test it gets larger and larger and larger, since it is never reset to `1`.

For code questions you should always ask in [Help Chat](https://gitter.im/FreeCodeCamp/Help) first.

Closing as this is not a site issue.

**Closed by SaintPeter** 2015-12-14 18:43 UTC

**Comment by sludge256** [comment] 2015-12-14 18:48
I had a suspicion that it had to do with variable scope but didn't see why it wouldn't still work. Forgot that the code tests are done all in one go.

**Comment by Heretic888** [comment] 2015-12-15 12:03
SaintPeter, thank you. I just thought that it is a global programm bug.
