### ISSUE TITLE
Going directly to "freecodecamp.org/learn" causes an SSL error in Chrome

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#55189] opened 2024-06-14 05:35 UTC
**Describe the bug**
If you open up Chrome and type in "freecodecamp.org/learn" in the address bar, you may get this error:
<img width="774" alt="freecodecamp_org_and_Site_is_not_secure" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/985197/55152af7-523a-44fd-baec-fb67568232b6">

**Expected behavior**
It should just load without error.

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - Version: Latest

**Additional context**

**Comment by ShaunSHamilton** [comment] 2024-06-14 05:53
I am unable to reproduce this. Could this be location-based?

**Comment by raisedadead** [comment] 2024-06-14 07:19
`freecodecamp.org/learn` correctly redirects to `www.freecodecamp.org/learn` (notice the www subdomain) for me and the certs are valid on bot the homepage and the learn page.

<img width="895" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/8955f20b-b183-4c78-92da-47ed05381432">

<img width="1001" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/dc20c0cc-47ab-4a3a-a234-8176b30ab621">

This has to be user-related config issue (DNS resolver, proxy, vpn, ISP, etc.).

**Comment by raisedadead** [comment] 2024-06-14 07:30
Confirming the redirection behavior using `curl` to eliminate any "browser DNS caching".

<img width="1055" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/dbe93c27-c1f2-4eca-a7fd-5fcf04c6ddba">

Can't repro. If you are still seeing the error, we will have to debug on your machine.

**Comment by raisedadead** [comment] 2024-06-14 13:05
Closing as still a can't-repro. Haven seen any reports in our forums or discord.

**Closed by raisedadead** 2024-06-14 13:05 UTC
Labels: status: blocked, other: device specific
