### ISSUE TITLE
cat JSON API Not working

### ISSUE THREAD

**Issue by prakhargvp** [freeCodeCamp/freeCodeCamp#17591] opened 2018-06-15 03:15 UTC
Previously the website is in https://www.freecodecamp.org so json api working fine.
Now its shifted to https://learn.freecodecamp.org so its unable to load json/api.

https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api

![screenshot from 2018-06-15 08-47-32](https://user-images.githubusercontent.com/7056772/41448549-c6c028fa-7078-11e8-85e7-4510002be4d1.png)

**Comment by raisedadead** [comment] 2018-06-15 06:10
Hi @prakhargvp thanks for the issue report.

Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17395
We request you to check for existing open issues while reporting.

Thanks and happy coding.

**Closed by raisedadead** 2018-06-15 06:10 UTC
