### ISSUE TITLE
Build a Tribute Page - update instructions for adding Bootstrap to CodePen?

### ISSUE THREAD

**Issue by emdashv** [freeCodeCamp/freeCodeCamp#14169] opened 2017-03-31 10:55 UTC
#### Challenge Name
[Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page)

#### Issue Description
Please update [this step](https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects) in the instructions for setting up CodePen? [Also in the video](https://youtu.be/qqrnzmqCGDw?t=3m53s). 

Adding Bootstrap to CodePen now defaults to the alpha of V4 of Bootstrap, so the Bootstrap V3 code that I learned on FCC (like my columns) wasn't working originally. Maybe let others know and encourage them to add Bootstrap to CodePen with this link?: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css Might save them some time. Thank you!

#### Browser Information

* Browser Name, Version: Chrome Version 57.0.2987.98 (64-bit)
* Operating System: Mac OS 10.12.3 (16D32)
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js



```

**Comment by erictleung** [comment] 2017-04-03 03:02
@emdashv thanks for the issue. This is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/13787, and there has been a fix proposed in https://github.com/freeCodeCamp/freeCodeCamp/pull/13895. This will soon enough be added to the production site. Happy coding!

**Closed by erictleung** 2017-04-03 03:02 UTC

**Comment by ngoduyangit** [comment] 2017-04-03 14:32
Thanks you <3
