### ISSUE TITLE
Correct results not accepted in Diff Two Arrays

### ISSUE THREAD

**Issue by andmkv** [FreeCodeCamp/FreeCodeCamp#9691] opened 2016-07-12 16:28 UTC
#### Challenge Name

Diff Two Arrays

#### Issue Description

Hi,
I have a problem with the Diff Two Arrays challenge - my code seems to give the following expected results, however they're not accepted by some reason:
[1, "calf", 3, "piglet", 7, "filly"]
["diorite", "pink wool"]

other results are accepted.

Thanks in advance!

#### Browser Information

* Browser Name, Version: Chrome, Internet Explorer
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
 var toRemove = [];

function diffArray(arr1, arr2) {
  var newArr = arr1.concat(arr2);
  
  for (var i = 0; i < newArr.length; i++) {
    if (arr1.indexOf(newArr[i]) !== -1 && arr2.indexOf(newArr[i]) !== -1) {
      toRemove.push(newArr[i]);
    }
  }
  
  // Same, same; but different.
  return newArr.filter(filterOutNewArr);
  //return toRemove;
}

function filterOutNewArr(value) {
  var pass = true;
  
  for (var i = 0; i < toRemove.length; i++) {
    if (toRemove[i] == value) {
      pass = false;
    }
  }
  
  return pass;
  
}

diffArray([1, "calf", 3, "piglet"], [7, "filly"]);

```

**Comment by Bouncey** [comment] 2016-07-12 18:17
Please see #9199

Although your code is correct. Manipulating global variables invalidates your code when we come to test it. We are discussing this in the linked-to-issue above

**Comment by raisedadead** [comment] 2016-07-12 18:22
@andmkv 

Your code is 100% valid. And apologies that we currently do not have a mechanism to support global variables. Please follow the thread mentioned by @Bouncey above.

Alternatively you may pass this with some tactical approach like this
```js
function diffArray(arr1, arr2) {
    var toRemove = [];
    function filterOutNewArr(value) {
    ...
    ...
    }
    ...
    ...
    return newArr.filter(filterOutNewArr);
}
```

Closing as a duplicate of #9199

**Closed by raisedadead** 2016-07-12 18:22 UTC

**Comment by andmkv** [comment] 2016-07-13 06:24
Thanks for clarification!
