### ISSUE TITLE
Create a Priority Queue Class: possible discrepancy between published tests and actual test execution

### ISSUE THREAD

**Issue by waycroft** [freeCodeCamp/freeCodeCamp#51648] opened 2023-09-25 01:46 UTC
### Describe the Issue

I submitted a version of `PriorityQueue()` for "Data Structures: Create a Priority Queue" (from the "Coding Interview Prep" course) that won't pass the tests in-app, but if I copy the [tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-priority-queue-class.md) verbatim and run them using `mocha`, my solution (as well as the official solution) passes.

Context: I wanted to challenge myself and essentially created my own implementation of `Array.prototype.splice()` (since when implementing data structures, I'm used to not relying on methods like that, whereas when doing algorithms I'll use those methods) to accomplish the sub-task of inserting an item into the queue at the right index, based on priority. 

Functionally, it achieves the same effect—in addition to the test suite used by FCC, I also ran several of my own custom test cases which all produced the expected behavior. The only issue is that submitting my solution in-app won't pass! Unfortunately I couldn't find the actual tests being executed (other than what I found in the .md for the challenge), otherwise I'd have gone further to pick them apart + find the issue + propose a revision if needed.

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-priority-queue-class

### Your code

```

function PriorityQueue() {
  this.collection = []
  this.printCollection = function () {
    console.log(this.collection)
  }
  // Only change code below this line
  this.size = function () {
    return this.collection.length
  }

  this.isEmpty = function () {
    return this.size() === 0
  }

  this.shiftRight = function (index) {
    // shifts all elements, including the element
    // at arr[index], one position right,
    // leaving behind a placeholder value.

    // first extend array by one
    this.collection.push(null)

    // Then, starting from the rear, we shift
    // elements over to the right
    let finalIndex = this.collection.length - 1
    for (let i = finalIndex; i > index; i--) {
      let previousValue = this.collection[i - 1]
      this.collection[i] = previousValue
    }
    // Optional, but: use null as a placeholder
    // value for the "gap" created in the array
    this.collection[index] = null
  }

  this.enqueue = function (item) {
    const value = item[0]
    const priority = item[1]

    if (this.isEmpty()) {
      this.collection.push(item)
      return
    }

    for (i = 0; i < this.collection.length; i++) {
      let nextPriority = this.collection[i][1]

      // if the item to enqueue needs to be added further back
      if (priority >= nextPriority) {
        // if on last iteration
        if (i === this.collection.length - 1) {
          this.collection.push([value, priority])
          // this return (or break) is required, otherwise
          // we'll keep extending the array ad-infinitum
          // before the loop exits
          return
        } else {
          continue
        }

        // if the item to enqueue is ready to be inserted
      } else {
        // shift everything from this pointer onward
        // to the right to make room for insertion,
        // then insert element.
        // *(I could use .splice(), but that would be too easy.)
        this.shiftRight(i)
        this.collection[i] = [value, priority]
        return
      }
    }
  }

  this.front = function () {
    return this.collection[0][0]
  }

  this.dequeue = function () {
    const itemToReturn = this.front()
    this.collection = this.collection.slice(1)
    return itemToReturn
  }
  // Only change code above this line
}

```

### Expected behavior

I expected all tests to pass, which is what happens when copying the [tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-priority-queue-class.md) verbatim, pasting into a local environment, and running mocha. 

### Screenshots

<img width="1175" alt="Screenshot 2023-09-24 at 6 42 09 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/69917602/bbf866f8-49f2-4f56-a549-786da3fd8168">

### System

- Device: Macbook Air 2020 (M1)
- OS: macOS Ventura 13.4.1
- Browser: Arc
- Version: Version 1.8.1 (41651), Chromium Engine Version 116.0.5845.187

### Additional context

As a sanity check, here's the official solution code I'm comparing to + also running FCC's mocha tests against:
```
function PriorityQueue() {
  this.collection = [];
  this.printCollection = function () {
    console.log(this.collection);
  };
  // Only change code below this line
  this.enqueue = function (newitem) {
    if (this.isEmpty()) {
      return this.collection.push(newitem);
    }

    this.collection = this.collection.reverse();
    var found_index = this.collection.findIndex(function (item) {
      return newitem[1] >= item[1];
    });
    if (found_index === -1) {
      this.collection.push(newitem);
    } else {
      this.collection.splice(found_index, 0, newitem);
    }
    this.collection = this.collection.reverse();
  };
  this.dequeue = function () {
    if (!this.isEmpty()) {
      return this.collection.shift()[0];
    } else {
      return "The queue is empty.";
    }
  };
  this.size = function () {
    return this.collection.length;
  };
  this.front = function () {
    return this.collection[0][0];
  };
  this.isEmpty = function () {
    return this.size() > 0 ? false : true;
  };
  // Only change code above this line
}
```

**Comment by gikf** [comment] 2023-09-25 05:51
Hey @waycroft

Thank you for reporting this issue.

I've used your code in the challenge, and added the following at the end:
```javascript
const q = new PriorityQueue();
q.enqueue(['kitten', 2]);
q.enqueue(['dog', 1]);
console.log(q);
```

This resulted with displayed error:
> ReferenceError: i is not defined

Editor on page runs in a strict mode. This means all variables have to be declared. After declaring the missing `i` tests are passing as intended.

Because this doesn't seem to be a bug I'm going to close the issue.

Thank you and happy coding.

**Closed by gikf** 2023-09-25 05:51 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
