### ISSUE TITLE
React: Use Advanced JavaScript in React Render Method

### ISSUE THREAD

**Issue by LearnerSamuelX** [freeCodeCamp/freeCodeCamp#36781] opened 2019-09-11 14:05 UTC
**Describe your problem and how to reproduce it:**
So I wrote my own code on this one, and tried several times with the same result: **When text is entered into the input element and the button is clicked, the MagicEightBall component should return a p element that contains a random element from the possibleAnswers array.** didnt pass. Ran the solution code and the same thing happened. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/use-advanced-javascript-in-react-render-method

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 
* Operating System: Mojave Version 10.14.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1280" alt="Screen Shot 2019-09-11 at 10 04 12 AM" src="https://user-images.githubusercontent.com/50002791/64704033-93f6c600-d47b-11e9-8ee6-6adf5f2ca781.png">

**Comment by anujsoni08** [comment] 2019-09-12 04:45
I also did the same thing and it is working.

I am attaching code that i have written

const inputStyle = {
  width: 235,
  margin: 5
}

class MagicEightBall extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      userInput: '',
      randomIndex: ''
    }
    this.ask = this.ask.bind(this);
    this.handleChange = this.handleChange.bind(this);
  }
  ask() {
    if (this.state.userInput) {
      this.setState({
        randomIndex: Math.floor(Math.random() * 20),
        userInput: ''
      });
    }
  }
  handleChange(event) {
    this.setState({
      userInput: event.target.value
    });
  }
  render() {
    const possibleAnswers = [
      'It is certain',
      'It is decidedly so',
      'Without a doubt', 
      'Yes, definitely',
      'You may rely on it',
      'As I see it, yes',
      'Outlook good',
      'Yes',
      'Signs point to yes',
      'Reply hazy try again',
      'Ask again later',
      'Better not tell you now',
      'Cannot predict now',
      'Concentrate and ask again',
      'Don\'t count on it', 
      'My reply is no',
      'My sources say no',
      'Most likely',
      'Outlook not so good',
      'Very doubtful'
    ];
    const answer = possibleAnswers[this.state.randomIndex];
    return (
      <div>
        <input
          type="text"
          value={this.state.userInput}
          onChange={this.handleChange}
          style={inputStyle} /><br />
        <button onClick={this.ask}>
          Ask the Magic Eight Ball!
        </button><br />
        <h3>Answer:</h3>
        <p>{
answer
        }
        </p>
      </div>
    );
  }
};

![Screenshot from 2019-09-12 10-13-58](https://user-images.githubusercontent.com/25316052/64754727-21065180-d546-11e9-99b3-a419ea91f90b.png)

**Comment by raisedadead** [comment] 2019-09-16 08:18
Hi @LearnerSamuelX can you try the regular troubleshooting steps and reachout to the forum for help. I could not reproduce this. I am closing this for now, however please comment back to get this re-opened once someone has confirmed on the forum that its indeed an issue with challenege

**Closed by raisedadead** 2019-09-16 08:18 UTC
Labels: scope: curriculum
