### ISSUE TITLE
Step Challenges:  Menu Button disappears on second step on Mobile

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5300] opened 2015-12-15 03:23 UTC
On devices which display the "Mobile" view, the Menu button disappears when you navigate to the second slide.  Going back to the first slide brings it back.

Confirmed on Chrome on a Galaxy Tab Pro and Galaxy S3.

**Comment by gasperno** [comment] 2016-01-08 21:47
I worked on identifying what this mysterious disappearance is. You will get a clear idea of what's happening when you do the following.
1) In developer tools, select any tab/mobile as model. I selected Apple iPhone.
2) I opened [step-challenge](http://www.freecodecamp.com/challenges/waypoint-create-a-github-account-and-join-our-chat-rooms)
3) Click and Open the Menu  
4) Navigate to second slide. 
I am attaching a screenshot to show the result. 
![hamburger menu](https://cloud.githubusercontent.com/assets/7889179/12210368/65f92908-b627-11e5-8ad4-fab1a4d286c2.png)

It is little bizarre to me. But these are my findings related to this issue.

**Comment by bugron** [comment] 2016-02-16 16:04
I'm able to reproduce this only in Chrome. @hallaathrad another issue that you may want to take a look.

**Comment by hallaathrad** [comment] 2016-02-16 16:10
it does help a whole lot, @gasperno! I know exactly what is generating the issue. 
Now let's see if we can fix it without breaking a nail!

**Comment by ltegman** [comment] 2016-03-01 19:20
@hallaathrad I am able to repro in Chrome on a Galaxy S6. The menu disappears forever unless I scroll the page and then release my finger.

**Comment by hallaathrad** [comment] 2016-03-01 19:24
yeah, it's something in the way jQuery refreshes, it seemed to be... going to work on this one after lunch, shouldn't be too complex to deal with.

**Comment by dwd2010** [comment] 2016-04-19 00:02
@hallaathrad, is this issue still going on?  if not then we could close this issue.

**Comment by hallaathrad** [comment] 2016-04-19 22:48
@dwd2010 I believe it's still happening. haven't quite figured out how to solve it. 
Please leave it open, I'll close it asap.

**Comment by dwd2010** [comment] 2016-04-20 00:07
@hallaathrad, no problem. I did test that on the chrome on my iPhone. I dont see any problem.  oh well.  menu button didnt disappears on me.

**Comment by atjonathan** [comment] 2016-06-01 15:44
@hallaathrad, I can't reproduce. Is anyone still having this issue?

**Comment by ltegman** [comment] 2016-06-02 05:35
@atjonathan I can still repro.

**Comment by BerkeleyTrue** [comment] 2016-08-15 03:08
Is this reproducible on beta?

**Closed** 2016-08-29 18:36 UTC
Labels: blocked, chrome
