### ISSUE TITLE
Cursor jumps one line down for first keyboard input.

### ISSUE THREAD

**Issue by JesterMan** [FreeCodeCamp/FreeCodeCamp#10685] opened 2016-09-10 20:10 UTC
#### Challenge Name
All challenges

#### Issue Description

Cursor appears in the position a user clicks. But when a keyboard button is pressed, the curser jumps one line down. In the linked video I press "enter".

https://dl.dropboxusercontent.com/u/79449416/one%20line%20off%20error.mov

You can also detect this when the line below is shorter than the line you are clicking on, it won't let you place the cursor past the length of the line below.

#### Browser Information

* Chrome, Version 52.0.2743.116 (64-bit)
* OSX, El Capitan, Ver: 10.11.4 (15E65)
* MacBook Pro (Retina, Mid 2012)

**Comment by BKinahan** [comment] 2016-09-11 10:57
Closing as a duplicate of #7847.

Please follow the issue there.

Happy coding!

**Closed by BKinahan** 2016-09-11 10:57 UTC
Labels: duplicate
