### ISSUE TITLE
b should be assigned to a rather than a assigned to b

### ISSUE THREAD

**Issue by bradleybossard** [FreeCodeCamp/FreeCodeCamp#12266] opened 2016-12-29 20:48 UTC
The last requirement of this challenge reads

a should be assigned to b with =

Shouldn't it read

b should be assigned to a with =

Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Aa%20%3D%207%3B%0Ab%20%3D%20a%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a;
var b = 2;

// Only change code below this line

a = 7;
b = a;
```

**Comment by almightyjokerr** [comment] 2016-12-29 21:35
// Setup
var a;
var b = 2;
var a= 7;
var b=7;

// Only change code below this line
b = a = 7;

should look like this

**Comment by revisualize** [comment] 2016-12-29 22:31
The verbiage is correct on the challenge.

How do you assign the value of 7 to a variable `num`? ... `var num = 7;`
Now if you want you can use a variable to store values.
Like in mathmatics. `num` + 3 = 10 What is the value of `num`?
`var x = num + 3;` ... That outputs 10
So, you can do several things with variables. But, you need to understand that variables hold values and variables can be used with other variables.
So, how do you assign the value of 5 to a variable `x`? ... `x = 5;` (Which is also overwriting the previous value of 10 from above.
How do you assign the value of `x` to a variable `y`?
Look at the way things are written. `var y = x;`
How do you assign the value of 42 to a variable `answer`? ... What is the answer?
`var answer = 42;`

**Comment by dhcodes** [comment] 2016-12-30 03:21
@revisualize is correct. Closing as resolved. Thanks @revisualize

**Closed by dhcodes** 2016-12-30 03:21 UTC

**Comment by sahilkatia1** [comment] 2017-01-07 03:50
simple
var a =7;
var b =7;
b = a;

**Comment by revisualize** [comment] 2017-01-09 01:49
People are giving incorrect answers to this challenge OP stated the answer.
The issue is not about the answer to the challenge the issue is about the verbiage for the challenge.
Focus on the issue. Also, don't give incorrect answers. That's just rude.

**Comment by RexfordK** [comment] 2018-02-14 19:26
I had this same problem, the OP's answer is correct, except for the fact that the top part of the code should not be changed but all changes should be on the bottom half.  There is also  a slight bug with the page. I solved this by refreshing the page and trying again.

**Comment by konsoul** [comment] 2018-06-06 04:46
var a = 7;
var b = a;
var a = b;

**Comment by revisualize** [comment] 2018-06-09 03:05
@konsoul 
```
var a = 7;
var b = a; // b is now a which is 7.
a = b; // a is now b which is a which is 7.
```
you don't need to do the extra `var` definition again because `a` has already been declared and defined.

**Comment by konsoul** [comment] 2018-06-09 15:29
@revisualize yes of course! Duh, thank you for pointing that out.  I guess unless you wanted to store the value of a into b as a variable and call that later. Which in this case is not a thing.
