### ISSUE TITLE
Challenge Title CSS

### ISSUE THREAD

**Issue by ClockworkOrange605** [freeCodeCamp/freeCodeCamp#41123] opened 2021-02-15 09:27 UTC
Some challenge titles are not fit a single line:

![freecodecamp_before](https://user-images.githubusercontent.com/4686891/107926565-eef0ee80-6f86-11eb-9df3-13013a336079.jpg)

So I think it would be helpful to add a wrap to a new line for a better perception of content:

![freecodecamp_after](https://user-images.githubusercontent.com/4686891/107926581-f2847580-6f86-11eb-8037-42a02a879797.jpg)

**Comment by ShaunSHamilton** [comment] 2021-02-15 10:06
Hello there,

Thank you, for taking the time to open this. However I am closing it as a Duplicate of #41090 

For future reference, before opening a PR for an issue, it is best to let the issue be triaged first by a member. Then, once a course of action is determined, and the issue is opened for contribution, then open a PR.

**Closed by ShaunSHamilton** 2021-02-15 10:06 UTC
Labels: type: bug
