### ISSUE TITLE
Editor doesn't let you remove trailing comment

### ISSUE THREAD

**Issue by ptsurbeleu** [FreeCodeCamp/FreeCodeCamp#1973] opened 2015-08-18 02:01 UTC
Challenge http://freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Steps to repro:
- Start the challenge from scratch;
- Try to remove the closing comment element by using Backspace or Delete button
- The editor will try to balance the closing comment by adding end of the comment element to the text

![image](https://cloud.githubusercontent.com/assets/3822219/9320743/4d9c4f60-4512-11e5-9563-2262e6f31bd4.png)

**Comment by benschenker** [comment] 2015-08-26 16:33
Thanks @ptsurbeleu,

Confirmed!

**Comment by sJhonny-e** [comment] 2015-08-27 08:18
(note: I'm looking at the framework-merger branch currently, so function names / lines might differ a little from staging)
The cause of this bug is that there's a functionality implemented to auto-close HTML comments.
You can see in function `updatePreview` that it checks whether there's an unterminated comment, and if so- adds a closing tag:
```
if (failedCommentTest) {
                 editor.setValue(editor.getValue() + "-->");
                 editorValueForIFrame = editorValueForIFrame + "-->";
            }
```

 this can be solved by either:
1. removing this functionality altogether; of course, I don't know why it's there in the first place, so I don't know if it's a good idea to remove it.
2. adding some property to the challenge model (i.e `autoCloseComments`) that will be read by the framework. 

Let me know what you think.

**Comment by benschenker** [comment] 2015-08-27 19:06
@BerkeleyTrue or @benmcmahon100, any thoughts?

**Comment by benmcmahon100** [comment] 2015-08-27 22:59
Yes as the editor is trying to compensate for another error that was caused by comments. I'll be able to tweak it so that ti doesn't continuously add it on the html challenges and only on clicking the run button

**Comment by awesomeaniruddh** [comment] 2015-10-18 22:13
@benmcmahon100 what's your progress with the fix?

**Comment by bugron** [comment] 2015-12-03 08:56
This is fixed now. Closing.

**Closed by bugron** 2015-12-03 08:56 UTC
Labels: bug, confirmed, in progress
