### ISSUE TITLE
Comment challenge on JavaScript is not working

### ISSUE THREAD

**Issue by hendrawd** [FreeCodeCamp/FreeCodeCamp#10189] opened 2016-08-13 10:11 UTC
Challenge [Comment your JavaScript Code](https://www.freecodecamp.com/challenges/comment-your-javascript-code#?solution=%2F%2FI%20don't%20agree%20that%20a%20comment%20is%20good%20to%20clarify%20the%20function%20of%20parts%20of%20your%20code%0A%0A%2F*%0A%20A%20good%20code%20can%20be%20determined%20with%20just%20the%20name%20of%20the%20functions%2C%20variables%2C%0A%20how%20it's%20easy%20to%20understand%20even%20without%20leaving%20comments.%0A%20If%20you%20need%20to%20leave%20a%20comment%20to%20the%20code%2C%20it's%20not%20a%20%22good%20enough%20code%22%0A%20*%2F) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
When i tried to Run tests(ctrl+enter), it shows a message "Error: SyntaxError: Unsafe or unfinished function declaration". With a simple comments, there is no problem, but if use that comment, the problem exist. I think it has to do with the symbols, although it is a valid comment.

My code:
```javascript
//I don't agree that a comment is good to clarify the function of parts of your code

/*
 A good code can be determined with just the name of the functions, variables,
 how it's easy to understand even without leaving comments.
 If you need to leave a comment to the code, it's not a "good enough code"
 */
```

**Comment by hendrawd** [comment] 2016-08-13 10:25
Looks like i have found the problem. We can't use word "function" here

**Comment by BKinahan** [comment] 2016-08-13 11:28
Thanks for the report, @hendrawd. 

This is a duplicate of issue #8774. The issue is resolved in the beta version of FCC so it won't be a problem any longer when that goes live, due to changes in the way tests are run.

For now you can work around the issue by not using the word `function` in comments, or by adding parentheses after the word as in `function()`

Happy coding!

**Closed by BKinahan** 2016-08-13 11:28 UTC
