### ISSUE TITLE
Not possible to claim certificate, even though all required challenges are marked completed

### ISSUE THREAD

**Issue by GCa** [freeCodeCamp/freeCodeCamp#16091] opened 2017-11-13 10:25 UTC
#### Challenge Name

Claim Your Front End Development Certificate 

#### Issue Description

I've completed all * marked challenges but I've been unable to claim the certificate. When I try to follow the steps I'm stopped at the third step by the message _Looks like you have not completed the neccessary steps. Please return to the challenge map._
However, there is no indication on which challenge is missing.
I tried three weeks ago, and on the Gitter Help channel I've been advised to do the Advanced Algorithms even though they were not marked as required, but with no result.
Then on the forums the last suggestion is to open an issue here on GitHub.

Any help would be appreciated.

Manu thanks,
G

#### Browser Information

* Browser Name, Version: Firefox and Chrome
* Operating System:  Windows 8 and Linux Mint 18.2
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

This is the issue I'm experiencing:
![screenshot6](https://user-images.githubusercontent.com/9579583/32720738-b92196aa-c864-11e7-9bf5-98d430404feb.png)

I had completed the  * marked items in the map:
![screenshot2](https://user-images.githubusercontent.com/9579583/32720791-dd66a6ea-c864-11e7-99ab-7c1202e41e4e.png)
![screenshot3](https://user-images.githubusercontent.com/9579583/32720800-e5f627ae-c864-11e7-8cc2-9ff4a279ba58.png)
![screenshot4](https://user-images.githubusercontent.com/9579583/32720834-fe24d14a-c864-11e7-85a9-ee64466a651e.png)

And then I did the advanced algorithm challenges too:
![screenshot5](https://user-images.githubusercontent.com/9579583/32720862-0ecf8ad0-c865-11e7-9b52-54a0bf280974.png)

**Comment by raisedadead** [comment] 2017-11-15 07:10
Hi @GCa ,

Thanks for reporting. And sorry about the issue you are facing.
I am tagging along @freeCodeCamp/moderators for this for help.

Here is their profile https://www.freecodecamp.org/Gca

@QuincyLarson can you maybe check in the backend if we have something missing?

**Comment by QuincyLarson** [comment] 2017-11-25 21:37
@GCa I checked out your projects and they look solid. I'm not sure what bug caused you to be unable to claim the cert, because other people aren't having trouble doing that. We're overhauling these certs for beta, and it should be fixed then.

I went in and manually granted you the cert in the database. Congratulations!

**Comment by QuincyLarson** [comment] 2017-11-25 21:44
@BerkeleyTrue When I checked this camper's database record, there was no `"isFrontEndCert": false` property. I think this is what was preventing him from being able to claim the cert. Can you update the code to create such a property if it doesn't exist?

**Comment by hamza-hajji** [comment] 2017-11-25 23:19
I'm also facing this problem, should I complete the advanced algorithms too?

**Comment by GCa** [comment] 2017-11-26 01:03
@QuincyLarson, @raisedadead, many thanks for your help :smiley: 
I'm really glad this was solved. I was going crazy trying to find what I still had missing. :sweat_smile:

**Comment by QuincyLarson** [comment] 2017-11-26 22:41
@hamza-hajji I've fixed this for you manually, too. We'll wait for @BerkeleyTrue to fix the underlying issue.

**Comment by BerkeleyTrue** [comment] 2017-11-26 22:46
@hamza-hajji and @GCa can you now claim your certificate?

@QuincyLarson This would not fix the issue as the api nor does mongodb require the property to be defined in order to be updated.

**Comment by GCa** [comment] 2017-11-27 11:46
@BerkeleyTrue 
I'm sorry, the error message _Looks like you have not completed the neccessary steps. Please return to the challenge map_ is still there. If I try to follow the steps to claim the certificate I'm stopped at the third step of [this](https://www.freecodecamp.org/challenges/claim-your-front-end-development-certificate).

However, my profile shows the certificate because it has been manually granted by @QuincyLarson 

Thanks.

**Comment by BerkeleyTrue** [comment] 2017-11-27 15:44
@QuincyLarson Did you manually give them their certificates?

**Comment by QuincyLarson** [comment] 2017-12-01 21:40
@BerkeleyTrue Yes - I manually reviewed their work and toggled their "is___Cert" properties to true for the sake of expedience while we fix this bug.

**Comment by BerkeleyTrue** [comment] 2017-12-01 21:50
> When I checked this camper's database record, there was no "isFrontEndCert": false property. I think this is what was preventing him from being able to claim the cert.

> Yes - I manually reviewed their work and toggled their "is___Cert" properties to true for the sake of expedience while we fix this bug.

> If I try to follow the steps to claim the certificate I'm stopped at the third step of this.

The second two statements disprove your initial claim. More investigation is need to find the root cause.

**Comment by lunadendron** [comment] 2017-12-04 20:25
Hi! I just wanted to let you all know that I'm having he exact same problem.

**Comment by QuincyLarson** [comment] 2017-12-04 22:28
@BerkeleyTrue To be clear, in situations where campers didn't have a "isFrontEndCert" property I manually added one to their profile, then set it to true. 

A lot of people are reporting this issue. When you say "More investigation is needed to find the root cause" does that mean you're actively working on this?

**Comment by BerkeleyTrue** [comment] 2017-12-04 22:32
> When you say "More investigation is needed to find the root cause" does that mean you're actively working on this?

No, this just means that the root issue is not having that field initially undefined. A quick way to test this is to set the field to false and asking the camper to attempt to login again.

**Comment by QuincyLarson** [comment] 2017-12-08 14:03
@BerkeleyFalse OK - next time I encounter a situation like that I'll do this and ask them to try again, and report back here with the results.

**Comment by raisedadead** [comment] 2017-12-08 14:52
@QuincyLarson FYI, Berkeley**False** is a zombie! Berkeley**True** is the ninja. :man_shrugging:

**Comment by QuincyLarson** [comment] 2017-12-12 05:06
@BerkeleyTrue OK - next time I encounter a situation like that I'll do this and ask them to try again, and report back here with the results. 👍

**Comment by GCa** [comment] 2017-12-19 22:54
Hello,
I'm not sure if this may be related to the issue, but I was looking at the certificate link, and it appears that the issue date keeps being changed.

When the certificate was issued, the date was 25 November.
I checked today, and the certificate date has been changed to 19 December.

https://www.freecodecamp.org/gca/front-end-certification

Shall I open a new issue?

**Comment by raisedadead** [comment] 2017-12-20 05:29
@GCa yes please, with the steps that you followed.

**Comment by oluwatomigbekele** [comment] 2018-02-04 08:06
Hi! I'm  having he same problem.

**Comment by sonutiwari** [comment] 2018-02-12 22:54
sonutiwari has not yet agreed to our Academic Honesty Pledge.

This message is coming along while I have completed each step. Kindly help @QuincyLarson

**Comment by Oyelowo** [comment] 2018-04-09 19:56
I am presently having similar issue with the responsive web design certification.

**Comment by Oyelowo** [comment] 2018-04-09 19:56
![image](https://user-images.githubusercontent.com/31687368/38519662-41cda496-3c49-11e8-89e5-484098036350.png)

**Comment by mstellaluna** [comment] 2018-04-09 23:03
@Oyelowo Hello. This issue is for production freecodecamp.org certificates. A separate issue has already been opened for the Beta certificates which you are having an issue with. Please refer to issue https://github.com/freeCodeCamp/freeCodeCamp/issues/17031 and https://github.com/freeCodeCamp/freeCodeCamp/issues/16923. Thank you!

**Closed** 2018-04-17 04:12 UTC
Labels: support: accounts

**Comment by WayneRyan** [comment] 2018-08-20 21:43
I am having the same problem. I have completed all tasks and projects and the "Responsive Web Design Certification" but did not get a certificate. My projects are at wayneryan.net
I'd like to advertise my cert on Facebook and LinkedIn. Can someone get this fixed for me?
