### ISSUE TITLE
Global declaration of vars conflict with test cases.

### ISSUE THREAD

**Issue by cloudasim** [FreeCodeCamp/FreeCodeCamp#11978] opened 2016-12-09 07:16 UTC
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20factor%20%3D1%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(var%20i%3D1%3B%20i%3C%3Dnum%3B%20i%2B%2B)%7B%0A%20%20%20%20factor%20*%3Di%3B%0A%20%20%7D%0A%20%20return%20factor%3B%0A%7D%0A%0Afactorialize(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.26.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var factor =1;
function factorialize(num) {
  for (var i=1; i<=num; i++){
    factor *=i;
  }
  return factor;
}

factorialize(10);

```

**Comment by raisedadead** [comment] 2016-12-09 07:16
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by cloudasim** [comment] 2016-12-09 07:17
i think the code is correct but it is showing wrong

**Comment by raisedadead** [comment] 2016-12-09 07:23
Apologies, please have a proper title and description on the issue next time, screenshots are appreciated. I closed because this appeared like an issue seeking help with the challenge.

And yes your code is correct, but unfortunately is using the `var factor =1;` in global scope.
This conflicts with the test cases.

If you move the same inside the scope of the function, it should work fine.

**Comment by raisedadead** [comment] 2016-12-09 07:25
Closing again as duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9199

**Closed by raisedadead** 2016-12-09 07:25 UTC
Labels: bug
