### ISSUE TITLE
This let me pass even though it only reversed hello, when the others were required as well.

### ISSUE THREAD

**Issue by jebalert** [FreeCodeCamp/FreeCodeCamp#4227] opened 2015-11-07 06:37 UTC
Challenge [Bonfire: Reverse a String](http://www.freecodecamp.com/challenges/bonfire-reverse-a-string#?solution=function%20reverseString(str)%20%7B%0A%20%20return%20str.split('').reverse().join('')%3B%0A%7D%0A%0AreverseString(%22hello%22%2C%22Howdy%22%2C%22Greetings%20from%20Earth%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function reverseString(str) {
  return str.split('').reverse().join('');
}

reverseString("hello","Howdy","Greetings from Earth");

```

**Comment by bugron** [comment] 2015-11-07 07:03
@jebalert thanks for posting this issue!
The problem is in your code. This is the first string from the challenge's description:
>Reverse the provided string.

and not strings. You've provided multiple arguments (separated by commas) for your `reverseString` function, so `str` will be equal to your first argument (which is `hello`). If you want to reverse all string arguments you may want to use [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) object.
Closing this issue. Feel free to reopen if you still experience problems, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-11-07 07:03 UTC

**Comment by jebalert** [comment] 2015-11-07 07:07
@bugron the purpose of reporting this bug is because I was able to proceed even though my code was not correct - you should probably open the issue back up.

**Comment by bugron** [comment] 2015-11-07 07:10
@jebalert I don't think the code is incorrect. It just does what it does only with the first argument.

**Comment by jebalert** [comment] 2015-11-07 07:11
@bugron The objective of the lesson is to reverse each word. It only reverses the first word within the array, yet it checks off each of them and rewards the user and lets them proceed on to the next segment. Clearly. . . this is a bug.

**Comment by bugron** [comment] 2015-11-07 07:13
As I said 
>Reverse the provided string.

So the objective of the lesson is to reverse **a** word and not **each** words provided.

**Comment by jebalert** [comment] 2015-11-07 07:15
<img width="304" alt="screen shot 2015-11-07 at 2 14 19 am" src="https://cloud.githubusercontent.com/assets/12172545/11014083/4f03009c-84f5-11e5-84e1-6fb977295c73.png">

@bugron please review the screenshot from within the lesson. Go beyond the title of the lesson.

**Comment by bugron** [comment] 2015-11-07 07:17
So what are you pointing to?
The title is "Bonfire: Reverse a String". If you're pointing to "Greetings from Earth" it is still a string.

**Comment by jebalert** [comment] 2015-11-07 07:19
I pointing to the fact that it claims I revered each value within the array, when in reality using the original code, I only reversed the first string "hello" not the strings the followed; which include "Howdy" and "Greetings from Earth".

**Comment by SaintPeter** [comment] 2015-11-07 07:21
@jebalert -
I don't think you understand how the tests work.

Your function is called multiple times with each of the 4 different inputs.  The result of your function (the value returned) is then compared against a second value.

The call that you make to the function:
```js
reverseString("hello","Howdy","Greetings from Earth");
```
Is only for your personal testing.  You can even delete it and it doesn't affect the outcome of the tests which run.

Your code IS correct and complete.  You might want to drop by the /Help rooms and get more explanation.

**Comment by jebalert** [comment] 2015-11-07 07:23
But by removing the quotes and commas from around "hello","Howdy","Greetings from Earth"

I get the expected output which, is all the words reversed. @SaintPeter
