### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-visually-separate-elements-with-line-breaks has an issue 

### ISSUE THREAD

**Issue by dmcscript** [FreeCodeCamp/freecodecamp#548] opened 2015-05-26 18:16 UTC
It marked the answer as correct when i put "br" between "h1" and "h2" tags when the prompt ask for something else

**Comment by BerkeleyTrue** [comment] 2015-05-26 18:31
@dmcscript Thanks for filing!
Could you clarify the issue as it seems to work fine for me.

Adding
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<br>
<p>Hello Paragraph</p>
```
Passes.

**Comment by QuincyLarson** [comment] 2015-05-26 18:51
@dmcscript We are just checking for the presence of a BR, not the actual position of the BR. I'm not sure how we'd do that. I'm going to mark this as wontfix since we won't be able to fix this any time soon. That said, thank you for bringing it to our attention.

**Closed** 2015-05-26 18:51 UTC

**Comment by BerkeleyTrue** [comment] 2015-05-26 21:00
I think the issue is the info in more info states `<br />` but since break is self closes by speck the backslash is not required and ignored by browsers (expect when using xhtml where it is required, but no one does that anymore).

This may be confusing to some users and can be easily fixed by updating the copy in `more info` by remove the backslashes in br.
