### ISSUE TITLE
Waypoint: Use Hex Code for Specific Colors

### ISSUE THREAD

**Issue by Phumphie** [FreeCodeCamp/FreeCodeCamp#4829] opened 2015-12-01 04:30 UTC
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: #000000;
  }
</style>

```
Correct code does not run test properly. Cannot move on.

**Comment by ltegman** [comment] 2015-12-01 04:43
Closing as a duplicate of #4825

Thanks and happy coding!

**Closed by ltegman** 2015-12-01 04:43 UTC
