### ISSUE TITLE
Issue in Bonfire: Diff Two Arrays

### ISSUE THREAD

**Issue by roma-derski** [FreeCodeCamp/FreeCodeCamp#1176] opened 2015-07-01 19:41 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-diff-two-arrays has an issue. It seems that last asset always fails:

assert.deepEqual(diff([], ['snuffleupagus', 'cookie monster', 'elmo']), ['snuffleupagus', 'cookie monster', 'elmo'], 'empty array');empty array: expected [] to deeply equal [ Array(3) ]

If i get it right, Array(3) is expected to be "empty array" but olso equal to ['snuffleupagus', 'cookie monster', 'elmo'].

I fail to pass this Bonfire as it treats as "wrong" both answers: empty array and ['snuffleupagus', 'cookie monster', 'elmo']
![image](https://cloud.githubusercontent.com/assets/11859195/8463353/4c53a558-2042-11e5-8c98-1a7706bf41e8.png)

**Comment by LumenTeun** [comment] 2015-07-01 20:20
Could you post your code please? Remember to wrap it in ```.

**Comment by roma-derski** [comment] 2015-07-02 16:43
Sure. First version, gives ['snuffleupagus', 'cookie monster', 'elmo'] for the last asset: 
"
function diff(arr1, arr2) {
  var resArr = [];
  var newArr = arr1.concat(arr2);
  newArr.sort();
  for (var i=0; i<newArr.length; i++){
    if (newArr.indexOf(newArr[i]) === i) {
      resArr.push(newArr[i]);
    }
    else if (newArr.indexOf(newArr[i]) === i-1){
      resArr.pop();
    }
  }
  return resArr;
}
diff([], ['snuffleupagus', 'cookie monster', 'elmo']);
"

And 2nd version, gives [] for the last asset: 
"
function diff(arr1, arr2) {
  if (arr1.length * arr2.length > 0) {
    var resArr = [];
    var newArr = arr1.concat(arr2);
    newArr.sort();
    for (var i=0; i<newArr.length; i++){
      if (newArr.indexOf(newArr[i]) === i) {
        resArr.push(newArr[i]);
      }
      else if (newArr.indexOf(newArr[i]) === i-1){
        resArr.pop();
      }
    }
    return resArr;
  }
  else {
    return [];
  }
}
diff([], ['snuffleupagus', 'cookie monster', 'elmo']);
"

**Comment by benmcmahon100** [comment] 2015-07-02 16:44
```
function diff(arr1, arr2) {
var resArr = [];
var newArr = arr1.concat(arr2);
newArr.sort();
for (var i=0; i<newArr.length; i++){
if (newArr.indexOf(newArr[i]) === i) {
resArr.push(newArr[i]);
}
else if (newArr.indexOf(newArr[i]) === i-1){
resArr.pop();
}
}
return resArr;
}
diff([], ['snuffleupagus', 'cookie monster', 'elmo']);
"

And 2nd version, gives [] for the last asset: 
"
function diff(arr1, arr2) {
if (arr1.length * arr2.length > 0) {
var resArr = [];
var newArr = arr1.concat(arr2);
newArr.sort();
for (var i=0; i<newArr.length; i++){
if (newArr.indexOf(newArr[i]) === i) {
resArr.push(newArr[i]);
}
else if (newArr.indexOf(newArr[i]) === i-1){
resArr.pop();
}
}
return resArr;
}
else {
return [];
}
}
diff([], ['snuffleupagus', 'cookie monster', 'elmo']);
```

**Comment by 1hella** [comment] 2015-07-04 22:27
@roma-derski It's the 'backtick' key rather than a quotation mark. It's on the same key as '~'.

**Comment by roma-derski** [comment] 2015-07-05 19:37
https://github.com/1hella ah, thanks!

**Comment by theharlotfelon** [comment] 2015-07-15 18:55
I'm also having this same problem. I'm unsure of what the final requirement is asking for. 

```
function diff(arr1, arr2) {
  var newArr = [];
  var remove = 0;
  for (var i = arr2.length; i >= 1; i--) {
    var j = i -1;
    if (arr1.indexOf(arr2[j]) === -1) {
      newArr.push(arr2[j]);
    } else {
      remove = arr1.indexOf(arr2[j]);
      arr1.splice(remove, 1);
    }
    arr2.pop();
  }
  newArr = newArr.concat(arr1);
  return newArr;
}


diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);
```

**Comment by henkekm** [comment] 2015-07-17 05:22
I was just about to post this same issue. I believe it's because .deepEqual() requires the order to be the same, and since @roma-derski has used the .sort() method, his final array is returned `['cookie monster', 'elmo', 'suffleupagus']`, not `['snuffleupagus', 'cookie monster', 'elmo']`.

May I humbly recommend the .sameDeepMembers() method instead?

**Comment by roma-derski** [comment] 2015-07-17 11:49
@henkekm, 
thanks, I didn't notice that!

**Comment by henkekm** [comment] 2015-07-18 17:01
@roma-derski No problem. Sadly my method relies on the sort, so it's not as simple as commenting out the .sort(). Ha ha haha. I was recommending to the devs that they use .sameDeepMembers() instead of .deepEqual(), since it doesn't appear that the order is important. Maybe I'll open a new ticket.

Glad I could help .sort() things out. Eh? Eh?

**Comment by roma-derski** [comment] 2015-07-18 17:56
@henkekm reopened this issue) let's try to make them use .sameDeepMembers() instead of .deepEqual()

**Comment by animsaj** [comment] 2015-07-18 18:14
well it looks like cheating, but Its the only solution I found. Use .sort() conditionally, when arr1 is not empty.

**Comment by roma-derski** [comment] 2015-07-18 18:26
now I just check if one of the arrays is empty, if so - than return not empty one intact)

**Comment by animsaj** [comment] 2015-07-18 18:29
if (newArr.length > arr2.length)
newArr.sort();
 instead of plain 
newArr.sort();

**Comment by roma-derski** [comment] 2015-07-18 19:16
@animsaj looks good and simple)

**Comment by kalivara** [comment] 2015-07-25 10:04
@animsaj, yes I think that is the only way to make the test pass. 
Anyway I´m pretty sure that is not what was intended by the people who made the Bonfire! The exercise is about returning the elements that don´t appear in both arrays, it doesn't say anything about order.

**Comment by jthrons69** [comment] 2015-07-25 11:22
I guess so Q only way

**Comment by vancovver** [comment] 2015-08-05 03:39
![screen shot 2015-08-04 at 8 37 58 pm](https://cloud.githubusercontent.com/assets/13059946/9077908/cfb9918a-3ae8-11e5-8bc8-e94fb3aa34fe.jpg)

**Comment by vancovver** [comment] 2015-08-05 05:07
More refined:
![screen shot 2015-08-04 at 10 05 53 pm](https://cloud.githubusercontent.com/assets/13059946/9078583/27413ff0-3af5-11e5-9ed2-2f662ed0c5c5.jpg)

**Comment by Stiino0** [comment] 2015-08-14 15:02
Hey guys,

I think I'm running into the same issue... I know I have weird code... But could anyone please assist where I can use .sort() in my code?

```
function diff(arr1, arr2) {
  var array = arr1.concat(arr2).sort(); //.sort() apparently gives issues
  var a = [], b = [];
  var prev;
  var result = [];
  
  for (i=0;i<array.length;i++){ //loop to find unique values in a and count the values in b
    if (array[i] !== prev){
      a.push(array[i]);
      b.push(1);
    } else {
      b[b.length-1]++;
    }
    prev = array[i];
  }
  
  for (i=0;i<b.length;i++){ //loop to push the "unique" elements in result array
    if (b[i]<=1){
      result.push(a[i]);
    }
  }
  
  return result;
}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);
```

**Comment by benmcmahon100** [comment] 2015-08-14 19:13
I'm 99% sure that this has been fixed on staging. If someone who is here on this issue wants to test the code they know that should work in beta and if the issue persists Then can said person open a brand new issue. This one has been open a long time and no one has posted a solutipn. We are currently rushing the deploy of the beta version so help from someone else in the form of a fix would be much appreciated in the form of a pull request if someone had the time. I'm going to close this issue on the assumption that it is fixed on the beta site but if it's not feel free to open an issue and tag me in it and we'll see what can be done. Thanks in advance folks!

**Closed by benmcmahon100** 2015-08-14 19:13 UTC

**Comment by benmcmahon100** [comment] 2015-08-14 19:19
@Stiino0  also just as a heads up copy pasting someone else's code is a bad idea as it may cause issues when applying for non-profits. It will also mean that you may not fully understand what the code does meaning you won't learn anything from it. If you're stuck you should check out http://gitter.im/freecodecamp/help for assistance on exactly this!
