### ISSUE TITLE
Repl env does not setup properly because of missing description tag

### ISSUE THREAD

**Issue by mirceachira** [freeCodeCamp/freeCodeCamp#39698] opened 2020-09-26 07:54 UTC
**Describe your problem and how to reproduce it:**
The repl environment for python projects doesn't install the dependencies properly for python challenges.

The problem is a missing description from the pyproject.toml file, under [tool.poetry].

This one I think has a 1 line fix, any value for description gets the env setup working, but I couldn't find another report of this issue. I hope here is the right place to report it. I'd be happy to submit a fix if possible as well.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome/85.0
* Operating System: Windows
Full user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc](https://user-images.githubusercontent.com/20253064/94335781-8c528280-ffe6-11ea-80fe-b6c670137a93.PNG)

**Comment by Sky020** [comment] 2020-09-26 09:40
Thanks for reporting this. The issue has already been reported: 

Duplicate of #39175 

As such, I am closing this.

**Closed by Sky020** 2020-09-26 09:40 UTC
Labels: duplicate, scope: learn
