### ISSUE TITLE
Introduction to the MongoDB and Mongoose Challenges: Glitch link to boilerplate broken

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#17972] opened 2018-08-03 11:58 UTC
#### Describe your problem and - if possible - how to reproduce it
The Glitch link to the boilerplate in the challenge gives error sometimes 
```
Project Not Found
Maybe a typo? Or maybe it's been renamed?
```
Issue seems similar to #17971 

#### Add a Link to the page with the problem
Challenge link: https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/
Glitch link: https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-mongomongoose/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  68.0.3440.84
* Operating System: Windows 10

#### If possible, add a screenshot here

![screenshot 127](https://user-images.githubusercontent.com/20020273/43641726-61e9d4c6-9742-11e8-818c-870c0a9c472c.png)

**Comment by moT01** [comment] 2018-08-08 13:29
@ezioda004 The link worked for me, perhaps it has been fixed - are you still having problems?

**Comment by ezioda004** [comment] 2018-08-08 17:41
@moT01 No, but it happens sometimes I suspect its because as mentioned in this thread https://github.com/freeCodeCamp/freeCodeCamp/issues/17586 all the boilerplates have node engine explicitly set at 4.4.5 which is no longer supported by glitch. 
![screenshot 130](https://user-images.githubusercontent.com/20020273/43854321-32cbe1c6-9b60-11e8-97b3-013a5df65f42.png)

There's also bunch of errors in the console due to this
 Maybe thats why it happens?
![screenshot 131](https://user-images.githubusercontent.com/20020273/43854385-533d32e8-9b60-11e8-940b-f8a709b1455d.png)

**Comment by gpedro34** [comment] 2019-08-11 16:39
The link is not broken anymore but I would suggest changing the link color previous to being clicked or to put some text decoration like underline or so, in order to jump to eyesight easily.

I lost so much time in this challenge due to not using the correct boilerplate as the tests did not pass even if my code was correct for the exercise. I'm sure I'm not the first one with this issue.

Also, the engines portion of package.json should definitely be changed to at least node 10 or completely removed so glitch can run the code.

**Comment by Sky020** [comment] 2020-09-01 19:04
I am closing this issue as the link and page have changed completely, and the issue is no longer present.

**Closed by Sky020** 2020-09-01 19:04 UTC
Labels: scope: learn
