### ISSUE TITLE
challenge not submitting

### ISSUE THREAD

**Issue by gememerald** [FreeCodeCamp/FreeCodeCamp#10572] opened 2016-09-09 13:15 UTC
Challenge [use-rgb-values-to-color-elements](https://www.freecodecamp.com/en/challenges/html5-and-css/use-rgb-values-to-color-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

``` html

<style>
body {
  background-color: rgb(0, 0, 0);
}
</style>

```

**Comment by ArielLeslie** [comment] 2016-09-09 15:34
![image](https://cloud.githubusercontent.com/assets/6234475/18392786/4ec6b8b8-7670-11e6-8146-098e67964721.png)

This isn't a bug in the specific challenge but the occasional need-to-reset issue.  
@gememerald - Try resetting your challenge and submitting your solution again.

**Comment by erictleung** [comment] 2016-09-09 16:27
@gememerald I'm unable to reproduce your issue. Can anyone with Firefox try to reproduce this phenomenon?

**Comment by dhcodes** [comment] 2016-09-09 16:43
@gememerald Thanks for the issue. I believe this is specifically related to your browser (Firefox).

**Comment by QuincyLarson** [comment] 2016-12-23 06:42
It sounds like these issues are no longer reproducable so I'm closing this.

**Closed by QuincyLarson** 2016-12-23 06:42 UTC
Labels: firefox
