### ISSUE TITLE
Printing object Object instead of the object and all it's properties

### ISSUE THREAD

**Issue by awashbur** [FreeCodeCamp/FreeCodeCamp#5435] opened 2015-12-24 09:38 UTC
Challenge [Waypoint: Delete Properties from a JavaScript Object](http://www.freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object#?solution=var%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%2C%0A%20%20%22bark%22%3A%20%22bow-wow%22%0A%7D%3B%0A%0Adelete%20ourDog.bark%3B%0A%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Happy%20Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%2C%0A%20%20%22bark%22%3A%20%22woof%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Adelete%20myDog.tails%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(z)%7Breturn%20z%3B%7D)(myDog)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"],
  "bark": "bow-wow"
};

delete ourDog.bark;

var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"],
  "bark": "woof"
};

// Only change code below this line.

delete myDog.tails;

// Only change code above this line.

(function(z){return z;})(myDog);

```

**Comment by raisedadead** [comment] 2015-12-24 17:55
Whats the issue?

**Comment by awashbur** [comment] 2015-12-24 18:08
The lesson I was playing with was how to add and remove properties from an object.  You want the print to do a toString and print all the properties to see your new property got added or removed.

Andrew

**Comment by ltegman** [comment] 2015-12-24 21:50
This display function should be moved to the tail section of the JSON and hand-coded to display something friendly to the console since Object.prototype.toString just displays `[object Object]`

**Comment by BerkeleyTrue** [comment] 2015-12-25 22:31
Closing as duplicate of #5097

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-12-25 22:31 UTC
Labels: confirmed, help wanted
