### ISSUE TITLE
Responsively Style Radio Buttons

### ISSUE THREAD

**Issue by Richbward** [FreeCodeCamp/FreeCodeCamp#11860] opened 2016-11-29 15:41 UTC
Responsively Style Radio Buttons

In the challenge you state that the user should nest each radio button with the following class:
`<div class="col-xs-6">`

However, the two lists:
1.  Things cats love:
2.  Top 3 things cats hate:

each have three radio buttons.

Because the Bootstrap grid system is based on twelve columns per row this wouldn't add up (it would be eighteen).

Each of the three radio buttons for each list should be nested with the following class:
`<div class="col-xs-4">`

As in:

```html
<div class="row">
  <ul>
    <div class="col-xs-4">
    <li>cat nip</li>
    </div>
    <div class="col-xs-4">
    <li>laser pointers</li>
    </div>
    <div class="col-xs-4">
    <li>lasagna</li>
      </div>
  </ul>
  </div>
  <p>Top 3 things cats hate:</p>
  <div class="row">
  <ol>
    <div class="col-xs-4">
    <li>flea treatment</li>
    </div>
    <div class="col-xs-4">
    <li>thunder</li>
    </div>
    <div class="col-xs-4">
    <li>other cats</li>
    </div>
  </ol>
  </div>
```

![image](https://cloud.githubusercontent.com/assets/6508768/20716478/585cabcc-b620-11e6-9f18-24a5ca990005.png)

**Comment by Richbward** [comment] 2016-11-29 15:46
Presently, this challenge fails if I try to have a row for the unordered and ordered lists with the three radio buttons each in a single row...

**Comment by t3h2mas** [comment] 2016-11-29 15:51
Hi @Richbward, could you please link to the challenge/post the description? Thank you

**Comment by erictleung** [comment] 2016-11-29 15:51
@Richbward Thank you for reporting this issue. I can see how this might be confusing but please read the instructions carefully.

> Nest all of your **radio** buttons...

The math still adds up to twelve. Please head over to one of the help rooms for more clarification, if needed.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Closed by erictleung** 2016-11-29 15:51 UTC

**Comment by Richbward** [comment] 2016-11-29 16:11
Hi Eric -

Thanks for the prompt response.

Yes, you're right - this is confusing.  I see two lists (one unordered, one ordered) each with three items.  The only way I can see 6 adding up to 12 would be if you had the list title and three items for each in a single row split by two  <div class="col-xs-6"> like so:

  <div class="row">
        <div class="col-xs-6">
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
    </div>
          <div class="col-xs-6">
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
    </div>
  </div>

**Comment by Richbward** [comment] 2016-11-29 16:12
Hi @t3h2mas -

Here is the link:
https://www.freecodecamp.com/challenges/responsively-style-radio-buttons#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-8%22%3E%0A%20%20%20%20%20%20%3Ch2%20class%3D%22text-primary%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22img-responsive%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%3C%2Fa%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-running-cats%22%20class%3D%22img-responsive%22%20alt%3D%22Three%20kittens%20running%20towards%20the%20camera.%20%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3E%3C%2Fi%3E%20Like%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3E%3Ci%20class%3D%22fa%20fa-info-circle%22%3E%3C%2Fi%3E%20Info%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3E%3Ci%20class%3D%22fa%20fa-trash%22%3E%3C%2Fi%3E%20Delete%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%3Cp%3EThings%20cats%20%3Cspan%20class%3D%22text-danger%22%3Elove%3A%3C%2Fspan%3E%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A

**Comment by Richbward** [comment] 2016-11-29 16:30
@erictleung -

I tried to reopen this issue but it appears I do not have the right to do so. I would appreciate a response.

**Comment by erictleung** [comment] 2016-11-29 16:37
@Richbward GitHub issues are for bug reporting, not for coding help. I believe this GitHub issue is about coding help because my interpretation of the issue is that the column widths aren't adding up. However, they do add up correctly.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Feel free to tag me there and I or others can explain it there. Happy coding!

**Comment by Richbward** [comment] 2016-11-29 16:41
@erictleung -

Then I guess I simply disagree that three radio buttons with six columns each adds up to twelve.

I don't see this as a coding issue at all.  I know how to use Bootstrap.

The best scenario I can see here is that the question is very poorly worded.

I thought Free Code Camp was to help users code - not play word games.

**Comment by Pothinus** [comment] 2016-12-24 14:59
Hello @Richbward,
I don't know if you figured this out or not. I just completed this challenge, and I was initially stumped until I realized that I wasn't fully understanding the question. 
First, the class of row has already been created (After the second image), so for your "Info, like, delete" button you need to specify the col change(col-xs-6) as required in the challenge.  Next, you need to add the col change to the remaining buttons. Hint: They are in your form element. I hope this helps. Good luck, and happy coding.

**Comment by HowdyHero** [comment] 2017-02-23 21:12
Hello, I just finished this challenge. I did it correct adding the div classes as requested, to the ''RADIO'' buttons which are at the bottom of the code and not to the Like, Info and Delete buttons. Here is an example: 

<div class="row">
      <div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
