### ISSUE TITLE
Heat map example project errors 

### ISSUE THREAD

**Issue by cw66786** [freeCodeCamp/freeCodeCamp#47073] opened 2022-07-28 19:38 UTC
### Describe the Issue

The data visualization heat map project example does not pass all the tests. It looks like the y_axis is messed up. December is in January's spot causing everything to be off by 1 month. 

### Affected Page

https://codepen.io/freeCodeCamp/full/JEXgeY

### Steps to Reproduce

1. Go to 'https://codepen.io/freeCodeCamp/full/JEXgeY'
2. Click on 'run test then 17/18'
3. Scroll down to 'test 9'
4. See error code 
5. Close test box look at y_axis 

### Expected behavior

Heat map data should correspond with y_axis 

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 
- also tested on Firefox and Microsoft edge

**Comment by gikf** [comment] 2022-07-28 19:47
I've tried it on two browsers and didn't have any test fails.

Could you include screenshot of the issue for reference? Is there any more information that you can provide?

**Comment by naomi-lgbt** [comment] 2022-07-28 20:52
<img width="769" alt="image" src="https://user-images.githubusercontent.com/63889819/181635324-222c4030-aa74-420e-859d-2a0ba4287bea.png">

I can reproduce it on Chrome.

**Comment by cw66786** [comment] 2022-07-28 21:01
@naomi-lgbt beat me to it, I get the same results as you on my phone using safari as well as my pc using  Firefox

**Comment by gargi-09** [comment] 2022-07-29 04:26
Tried it on chrome
![image](https://user-images.githubusercontent.com/85283030/181682644-78f7a026-f92e-440b-97ab-e47403f61cbd.png)

**Comment by cw66786** [comment] 2022-08-10 02:21
I have completed my heat map and along the way figured out a solution for this. I'm unsure what to do about it though because its a codepen.

**Comment by cw66786** [comment] 2022-08-22 05:34
I have forked the original and fixed this issue as well as issue  #47290 
link here:  https://codepen.io/cw66786/full/wvmxeyw

Also forked the version submitted in #47290 and only fixed the y axis
link here:  https://codepen.io/cw66786/pen/GRxejmO

`  var yAxis = d3
    .axisLeft()
    .scale(yScale)
    .tickValues(yScale.domain())
    .tickFormat(function (month) {
      var date = new Date(0);
      date.setUTCMonth(month+1);//added plus one here to properly set months 
      var format = d3.timeFormat('%B');
      return format(date);
    })
    .tickSize(10, 1);`

**Comment by cw66786** [comment] 2022-08-30 23:53
Whoever runs the free code camp codepen.io has full permission to fork and use either of those. I'm assuming that is the only way to get this closed. If I am wrong and there is a way to fix this via pull request id gladly do that.

**Comment by ieahleen** [comment] 2022-10-11 14:39
The project is now at heat-map.freecodecamp.rocks, and the issue doesn't seem present.

![image](https://user-images.githubusercontent.com/26656284/195121637-41c36866-a5e2-486d-8cc1-74e0dd79149c.png)

As such I am closing this issue, you can request to have it reopened if you think it needs more work

**Comment by cw66786** [comment] 2022-10-11 21:47
![image](https://user-images.githubusercontent.com/103803383/195204368-3defac59-224d-43cf-9638-a6284723650c.png)

when I go to heat-map.freecodecamp.rocks, the prolems are still present on the x and y axis

**Comment by ninjaboy667** [comment] 2022-10-11 21:59
> 

Yes, I m still getting the same issue. @ieahleen I noticed that for your graph they start at 60, 70, 80 instead of 59,69,79. Is this screenshot from an update that has not been pushed yet?

**Comment by ieahleen** [comment] 2022-10-12 07:53
@ninjaboy667 no, I took the screenshot at https://heat-map.freecodecamp.rocks/

**Comment by biometricPsychography** [comment] 2022-12-12 19:24
> The project is now at heat-map.freecodecamp.rocks, and the issue doesn't seem present.
> 
> ![image](https://user-images.githubusercontent.com/26656284/195121637-41c36866-a5e2-486d-8cc1-74e0dd79149c.png)
> 
> As such I am closing this issue, you can request to have it reopened if you think it needs more work

The issue is still present on Firefox and Chrome.

**Comment by gikf** [comment] 2022-12-12 20:11
There must be something else impacting this than browser.

@biometricPsychography could you see how this one displays for you? https://codepen.io/sanityto/full/gOKJQae

**Comment by cw66786** [comment] 2022-12-12 21:23
@gikf yours is correct for me ... the one at https://heat-map.freecodecamp.rocks/ is still incorrect on the x and y for me though

**Comment by biometricPsychography** [comment] 2022-12-13 01:39
@gikf Yes that one is correct!

**Comment by gikf** [comment] 2022-12-13 07:42
@cw66786 @biometricPsychography Thank you for confirmation.

It appears that issue is caused by the method interpreting data, as being in local time. I've created PR changing used method, to use _Coordinated Universal Time (UTC)_ instead.

**Closed** 2022-12-14 22:23 UTC
Labels: type: bug, status: discussing
