### ISSUE TITLE
It seems with all waypoints I can get unlimited points even after done

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#3267] opened 2015-09-12 17:16 UTC
Challenge http://freecodecamp.com/challenges/waypoint-add-different-margins-to-each-side-of-an-element has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

It appears that I can redo a waypoint an unlimited amount of times, and thus get an unlimited amount of points. It doesn't appear to matter which waypoint it is. I have tried with the HTML5/CSS section. If you redo the waypoint, you will still get a point.

**Comment by bugron** [comment] 2015-09-12 17:52
@tesla809 thanks for posting this issue!
Yes, this is a problem. Anyway, I'll close this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3009, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-12 17:52 UTC
