### ISSUE TITLE
jQuery All Chapter don't show required task until you click on " Run Test " 

### ISSUE THREAD

**Issue by aslamweb** [FreeCodeCamp/FreeCodeCamp#3145] opened 2015-09-07 08:43 UTC
jQuery All Chapter don't show required task until you click on " Run Test " 
I'll submit two screenshots one before clicking on Run Test One After Clicking on Run Test Button.

<h1> screenshot  Before Clicking On " Run Test Button " </h1>
![image](https://cloud.githubusercontent.com/assets/14052934/9712758/562e367a-5566-11e5-99b1-c1c0d9f86408.png)
<h1> screenshot after clicking on " Run Test button"</h1>
![image](https://cloud.githubusercontent.com/assets/14052934/9712759/56cfb716-5566-11e5-9fc2-974f47209eab.png)

Challenge http://freecodecamp.com/challenges/waypoint-delete-your-jquery-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment] 2015-09-07 08:49
That is by design. The tests are supposed to help you in case the description itself is not clear enough for you to do the challenge.

**Comment by bugron** [comment] 2015-09-07 17:09
@aslamweb thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-07 17:09 UTC
