### ISSUE TITLE
"The quotient variable should only be assigned once"

### ISSUE THREAD

**Issue by kev0587** [freeCodeCamp/freeCodeCamp#14025] opened 2017-03-20 20:15 UTC
Challenge [divide-one-decimal-by-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var quotient = 4.4 / 2.0; // Fix this line



```

Challenge won't pass because of a "The quotient variable should only be assigned once" error.  The quotient var isn't assigned anywhere else and this is the only line of code on the editor.

I tried editing the error to remove any whitespace so there was only 1 line on the editor, but it still didn't pass.

**Comment by kev0587** [comment] 2017-03-20 20:19
This seemed to only fail when going through the Map progression (running test and clicking "Submit and go to next challenge".  Out of curiously, I clicked on the auto-generated link to the challenge above when creating the bug and opened the test in a separate tab and it passed.  I navigated back to my original tab and it failed using the same code.

**Comment by kev0587** [comment] 2017-03-20 22:28
@erictleung I ran into more challenges that has this same issue.  I'm sure you guys don't want to clog up the issues tab with the same issue for different challenges, so should I just include all challenges that I run into that generates a failed test using the same steps to reproduce on this ticket?

For example => Finishing the [Declare String Variables](http://beta.freecodecamp.com/challenges/basic-javascript/declare-string-variables) challenge and moving on to the [Escaping Literal Quotes in Strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) challenge also generates a fail when running the tests.

`
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

`

This produces the error "message: You should use two double quotes (&quot;</code>) and four escaped double quotes (<code>&#92;&quot;)."

If you copy the link to this challenge and open it on a new tab, you will see the same code (since it's saved in the editor), but the tests will pass and you'll be able to move on to the next challenge.

Let me know if you'd like me to include all challenges that have this issue on this ticket, or if 1 example will be enough.

**Comment by macengr** [comment] 2017-03-31 23:42
This is still an issue as of 31 March 2017

**Comment by phillipeb** [comment] 2017-04-02 13:31
I used a random query param to clear my local cache and to reset the page:
https://beta.freecodecamp.com/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript?fgdgdfg  and then resubmitted my work, this allowed me to save and continue.

**Comment by Bouncey** [comment] 2017-04-02 14:16
Could we modify the test to look only for assignments? `/quotient\s*?=/g`

**Comment by Bouncey** [comment] 2017-04-02 14:17
Or remove the tail code and look for a `length === 1`?

**Comment by knight2** [comment] 2017-06-28 13:16
This is still an issue as of June 28th 2017. 

http://beta.freecodecamp.com/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript

code submitted:
var quotient = 4.4 / 2.0;

passing tests: 
"The variable quotient should equal 2.2
You should use the / operator to divide 4.4 by 2"

failing test "The quotient variable should only be assigned once"

**Comment by EmmaGX** [comment] 2017-07-11 12:20
still an issue as of July 11th 2017

**Comment by QuincyLarson** [comment] 2017-07-20 17:38
@knight2 can you verify whether you're still experiencing this issue? Is anyone else experiencing this still?

**Comment by knight2** [comment] 2017-07-20 18:25
@QuincyLarson Just tested it again and now it passes without any problems.

**Comment by augmt** [comment] 2017-07-20 18:57
@QuincyLarson I can still reproduce this issue via [erictleung's procedure](https://github.com/freeCodeCamp/freeCodeCamp/issues/14025#issuecomment-287895294), mentioned above. I think the culprit is #14252.

**Comment by QuincyLarson** [comment] 2017-07-22 06:03
@augmt Awesome - thanks for tracking that down. It looks like after 3 months, we have movement on your issue again. Here's hoping we can fix it quickly :)

**Comment by anasey01** [comment] 2017-07-26 16:10
I am having a similar issue. I'm trying out the Beta Version and it wouldn't let me pass to the next challenge. 

`var quotient = 4.4 / 2.0; // Fix this line`

//The quotient variable should only be assigned once

**Comment by systimotic** [comment] 2017-07-28 14:41
Hi everyone! Thanks for looking into this issue. #13400 discusses the same problem, I'm closing this as a duplicate. If anybody has more information on the cause of or solution to this issue, please post it there.

Happy coding!

**Closed by systimotic** 2017-07-28 14:41 UTC
Labels: beta, bug, tests
