### ISSUE TITLE
Text Editor Bug (video)

### ISSUE THREAD

**Issue by mariusbuciuman** [freeCodeCamp/freeCodeCamp#12621] opened 2017-01-19 18:40 UTC
#### Browser Information

* Browser Name, Version: Chrome 55
* Operating System: Mac OS X 10
* Mac Book Pro

#### Video

http://d.pr/v/9Ggi/qaGt102x

**Comment by raisedadead** [comment] 2017-01-19 18:57
@mariusbuciuman 

Thanks a lot for the report, this is a known issue, and has been fixed since in our development branch.

Unfortunately, we are waiting for this to be in production (which is the main website). Request you to follow the workaround mentioned in the other thread referred below.

Duplicate of #7847

**Closed by raisedadead** 2017-01-19 18:57 UTC

**Comment by mariusbuciuman** [comment] 2017-01-19 19:01
Thank you for your quick responce
