### ISSUE TITLE
Accessing Objects Properties with Variables completes with an Invalid Response.

### ISSUE THREAD

**Issue by revisualize** [freeCodeCamp/freeCodeCamp#14291] opened 2017-04-07 20:33 UTC
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Code:
```js
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};
// Only change code below this line;
var playerNumber;       // Change this Line
var player = testObj;   // Change this Line
```

If you use this code:
```js
var playerNumber = 16;// Change this Line
testObj[playerNumber]
var player;   // Change this Line
```
The challenge will pass.
...
...
However, the correct response is:
```js
var playerNumber = 16;// Change this Line
var player = testObj[playerNumber];   // Change this Line
```

**Comment by Manish-Giri** [comment] 2017-04-07 20:53
Doesn't pass for me - 

![untitled](https://cloud.githubusercontent.com/assets/11348778/24819419/860cd3c4-1bb2-11e7-902b-8f1a52835f7d.png)

**Comment by Shan11812** [comment] 2017-04-07 20:55
Not passing on:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by Manish-Giri** [comment] 2017-04-07 21:01
I think he missed assigning the value in his code - `var player = "Montana";`, as reported in #14290.

**Comment by revisualize** [comment] 2017-04-07 23:44
Correct. I was testing and yes. You need to supply both the

```js
var playerNumber = 16;// Change this Line
testObj[playerNumber]
var player = "Montana";   // Change this Line
```
And then it will pass. I think there were some troubleshooting issues on my part.

**Comment by erictleung** [comment] 2017-04-08 18:06
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14290. Happy coding!

**Closed by erictleung** 2017-04-08 18:06 UTC

**Comment by ResatMemis01** [comment] 2017-08-01 10:44
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;    // Change this Line

var player = testObj[playerNumber];   // Change this Line
