### ISSUE TITLE
code passes all the test cases in browser console(chrome) but fails in free code camp page.

### ISSUE THREAD

**Issue by UXsree** [FreeCodeCamp/FreeCodeCamp#11517] opened 2016-11-04 16:33 UTC
[Inventory Update](https://www.freecodecamp.com/challenges/inventory-update) has an issue.

#### Issue Description

code passes all the test cases in browser console(chrome) but fails in free code camp page.

#### Browser Information

chrome

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
function updateInventory(arr1, arr2) {
              var tempArray = [];
  curInv.forEach(function(elem, index) {
              newInv.forEach(function(elem1, index1) {
                      if(elem1[1] === elem[1]){
                         // console.log("found a match");
                         // console.log(index1, index);
                         tempArray.push([elem[0]+elem1[0],elem[1]]);
                          curInv.splice(index,1);
                          newInv.splice(index1,1);
                      }

                  })
  })
  curInv.forEach(function(element,ind){
    tempArray.push(element);
  })
    newInv.forEach(function(element,ind){
    tempArray.push(element);
  })
    console.log(tempArray);
    tempArray.sort(function(a, b) {
  if (a[1] < b[1]) {
    return -1;
  }
  if (a[1] > b[1]) {
    return 1;
  }

  return 0;
});
    console.log(tempArray);
}

// Example inventory lists
var curInv = [];
var newInv =  [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]];
updateInventory(curInv, newInv);
```
 
 

#### Screenshot

Edit (@raisedadead) : Formatted for redability, original text can found [here](https://gist.githubusercontent.com/raisedadead/70519ec07dcdbefbc5224a194ae85636/raw/26117a9c47e6274c55e96b44a916905d44aa99f5/Free%2520Code%2520Camp%2520-%2520Issue%2520Description%2520(11517).md)

**Comment by Dayfiri** [comment] 2016-11-06 10:32
This is what is console.log when running your code in FCC.
![screenshot from 2016-11-06 11-25-53](https://cloud.githubusercontent.com/assets/16082563/20036836/f12b4864-a413-11e6-904c-792dae2ba1b8.png)

This is the other testing in Codepen with this result.
![codepen](https://cloud.githubusercontent.com/assets/16082563/20036853/56e240e0-a414-11e6-80eb-49ae66e1e0f3.png)

And only one that worked was on [repl.it](https://repl.it/languages).
![repl](https://cloud.githubusercontent.com/assets/16082563/20036859/9277db92-a414-11e6-9ccb-674bedb8b743.png)

**Comment by UXsree** [comment] 2016-11-06 11:03
thank you!  but I'm still not clear how to pass this on FCC

**Comment by Dayfiri** [comment] 2016-11-06 11:22
@UXsree 
Well, from all that outputs, the one that is important to us is FCC one.
Assignment expects to get a return value of:
```
[[88, "Bowling Ball"], [2, "Dirty Sock"], [3, "Hair Pin"], [3, "Half-Eaten Apple"], [5, "Microphone"], [7, "Toothpaste"]]
```
But it receives:
```
after sorting:
Array [ Array[2], Array[2], Array[2], Array[2] ]
```
I don't know at the moment what solution would it be but let moderators or other members see this and give some feedback.

**Comment by Pasayadaan** [comment] 2016-11-15 03:41
@UXsree, @Dayfiri 
I understand that the code runs fine in browser and repl.it but I feel using splice on curInv and newInv may be causing the problem while testing in FCC as it may be checking the result (in your case tempArray) with those arrays.

Just to get results in FCC - 
1. In function updateInventory(arr1, arr2)
Instead of using curInv use the function parameter arr1 and for newInv use the function parameter arr2
2. Also make sure to return tempArray
This should clear the test.

**Comment by systimotic** [comment] 2016-11-17 22:04
I can confirm that this appears to be an issue in the code. After replacing all of the instances of `curInv` inside the function with `arr1` and all of the `newInv` ones with `arr2`, as well as returning the `tempArray`, the code shared above works fine.

I'm closing this issue because it's not a problem with FreeCodeCamp, but an issue in the user's code. If you believe I'm wrong in closing this issue, please add additional information and reopen.
Happy coding!

**Closed by systimotic** 2016-11-17 22:04 UTC

**Comment by UXsree** [comment] 2016-11-18 09:33
thanks guys!
