### ISSUE TITLE
Issue with geolocation over insecure HTTP (Deprecation)

### ISSUE THREAD

**Issue by stephengarn** [freeCodeCamp/freeCodeCamp#14620] opened 2017-04-27 21:35 UTC
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/7065107/25505384/bb253540-2b5e-11e7-96e6-e7703c7b5052.png)

Can't use powerful features such as geolocation anymore with HTTP. 

Possible solution: launching chome with --unsafely-treat-insecure-origin-as-secure="http://example.com" flag.

**Comment by raisedadead** [comment] 2017-04-28 13:32
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/8988

**Closed by raisedadead** 2017-04-28 13:32 UTC
