### ISSUE TITLE
Testing bug

### ISSUE THREAD

**Issue by JechtTyre** [freeCodeCamp/freeCodeCamp#15592] opened 2017-07-03 19:37 UTC
Challenge [use-a-retina-image-for-higher-resolution-displays](http://beta.freecodecamp.com/en/challenges/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![error1](https://user-images.githubusercontent.com/7410189/27805906-62bc04ca-6005-11e7-818c-6d56cb9b7386.png)

```html


<style>
  img {height:100px;width:100px;}
</style>

<img src="https://s3.amazonaws.com/freecodecamp/FCCStickers-CamperBot200x200.jpg" alt="freeCodeCamp sticker that says 'Because CamperBot Cares'">

```

**Comment by texas2010** [comment] 2017-07-03 22:29
I test it on Firefox on the Mac. it won't pass with his code. I confirmed.

**Comment by lynxlynxlynx** [comment] 2017-08-05 15:36
Duplicate of #15259, so can be closed.

**Closed** 2017-08-06 19:41 UTC
Labels: beta, firefox
