### ISSUE TITLE
"Run Test" not loading

### ISSUE THREAD

**Issue by MShaffer1** [FreeCodeCamp/FreeCodeCamp#12112] opened 2016-12-19 07:55 UTC
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("button").addclass("animated");
    $(".btn").addclass("shake");
    $("#target1").addclass("btn-primary");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

Beneath the "Run Test" button, the check mark list is no longer loading.  It loaded when I first opened the page, but now it's gone.  I have no idea if my code is right or wrong as it won't let me know.  I tried reloading the page, but that didn't help.  I don't know if "reset" will help because I don't know if it will erase everything or just what I entered during that challenge.

**Comment by raisedadead** [comment] 2016-12-19 09:21
> I don't know if "reset" will help because I don't know if it will erase everything or just what I entered during that challenge.

Yes, that is correct, this will reset the code completely and remove your code. You can copy and save the code somewhere, for example in a notepad or text editor of your choice.

But, this is worth a try, to help you fix the issue.

**Comment by erictleung** [comment] 2016-12-19 20:09
@MShaffer1 for the jQuery challenges, if you type in incorrect code, the parser will throw a type error or something similar, which will throw off rendering for some reason.

@raisedadead the error here is the code is using a `.addclass()` rather than `.addClass()`. I've seen this error several times before. The console throws `Uncaught TypeError` with `$(...).addclass is not a function` error. Not sure how deep of a problem it is to fix so that the tests will still render even with bad code.

**Comment by raisedadead** [comment] 2016-12-20 05:24
Oh yes, I completely missed it. Thanks @erictleung !

@MShaffer1 closing this as not a bug with the codebase, please reach out to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help), for more help.

**Closed by raisedadead** 2016-12-20 05:24 UTC
