### ISSUE TITLE
Challenge passed but not moving forward after (new format? black ribbon) submit clicked

### ISSUE THREAD

**Issue by pathgeek** [FreeCodeCamp/FreeCodeCamp#10606] opened 2016-09-09 16:48 UTC
Challenge [target-html-elements-with-selectors-using-jquery](https://www.freecodecamp.com/en/challenges/jquery/target-html-elements-with-selectors-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have completed this challenge successfully but am not able to move forward after hitting "submit" in the (newly formatted?) black ribbon strip. 

```html
    
    
<script>
$(document).ready(function() {
$("button").addClass("animated bounce");
});
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
<h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row">
  <div class="col-xs-6">
    <h4>#left-well</h4>
    <div class="well" id="left-well">
      <button class="btn btn-default target" id="target1">#target1</button>
      <button class="btn btn-default target" id="target2">#target2</button>
      <button class="btn btn-default target" id="target3">#target3</button>
    </div>
  </div>
  <div class="col-xs-6">
    <h4>#right-well</h4>
    <div class="well" id="right-well">
      <button class="btn btn-default target" id="target4">#target4</button>
      <button class="btn btn-default target" id="target5">#target5</button>
      <button class="btn btn-default target" id="target6">#target6</button>
    </div>
  </div>
</div>
</div>

    ```

**Comment by ltegman** [comment] 2016-09-11 21:42
Closing as a duplicate of #10572. Thanks and happy coding!

**Closed by ltegman** 2016-09-11 21:42 UTC
