### ISSUE TITLE
This solution is correct but it shows errors

### ISSUE THREAD

**Issue by sepehr-y** [FreeCodeCamp/FreeCodeCamp#3866] opened 2015-10-23 21:06 UTC
Challenge [Bonfire: Factorialize a Number](http://freecodecamp.com/challenges/bonfire-factorialize-a-number#?solution=function%20factorialize(num)%20%7B%0A%20%20var%20i%20%3D%20num%3B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20while(i%3E0)%20%7B%0A%20%20%20%20if(typeof%20val%20!%3D%20'undefined')%20%7B%0A%20%20%20%20%20%20val%20%3D%20val%20*%20i%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20val%20%3D%20i%3B%0A%20%20%20%20%7D%0A%20%20i--%3B%20%20%0A%20%20%7D%0A%20%20num%20%3D%20val%3B%0A%20%20return%20num%3B%0A%7D%0A%0Afactorialize(5)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function factorialize(num) {
  if(num === 0) {
    return 1;
  }
  var i = num;
  var arr = [];
  while(i>0) {
    if(typeof val != 'undefined') {
      val = val * i;
    } else {
      val = i;
    }
  i--;  
  }
  num = val;
  return num;
}

factorialize(5);


```

**Comment by natac13** [comment] 2015-10-23 21:55
@sepehr-y try running your solution through http://www.pythontutor.com/javascript.html#mode=edit and you may find the problems that way.

**Comment by natac13** [comment] 2015-10-23 22:01
So I tired running this through http://www.pythontutor.com/javascript.html#mode=edit and got an error about `val` not being defined and wonder if this is the same reason it will not pass the test. I was able to declare `val` outside the `while` loop however it then does not pass the last test. 
I will agree with @sepehr-y that the code is right since running though Chrome dev tools the code works great even when running `factorialize(0)`

**Comment by natac13** [comment] 2015-10-23 22:05
In order to pass the tests I added two lines to @sepehr-y code which passes
```
function factorialize(num) {
  var i = num;
  var arr = [];
  var val;
  if(num === 0) return 1;
  while(i>0) {
    if(typeof val != 'undefined') {
      val = val * i;
    } else {
      val = i;
    }
  i--;  
  }
  num = val;

  return num;
}
```

**Comment by ltegman** [comment] 2015-10-24 03:36
This solution seems correct if you only run the code once, but when you run the same function call twice in a row you'll see you don't get the same result both times. The problem is that because in @sepehr-y's code `val` is never declared inside the function with the `var` keyword in front of it. This means it gets declared as a global variable and sticks around after the function call ends, so any second run of the function is using a `val` variable that is already assigned.

Closing as not an issue with the tests but feel free to reply if you need further clarification.

Thanks and happy coding!

**Closed by ltegman** 2015-10-24 03:36 UTC

**Comment by sepehr-y** [comment] 2015-10-24 10:54
Thanks a lot guys :)

**Comment by jctan** [comment] 2015-12-12 05:21
Where are you using var arr = []?

**Comment by natac13** [comment] 2015-12-12 10:09
@jctan for me I just grabbed the code and worked with it. Looking back that line can be removed. Sorry for any confusion
