### ISSUE TITLE
Implementing the Luhn Algorithm - Step-23 - connecting reversed card number to `card_number_reversed`

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#55669] opened 2024-07-26 09:57 UTC
### Describe the Issue

at tips 
```
Step 23
Create a variable even_digits and assign it the even digits of the reversed card number.
```
 `reversed card number` is hard to know  it is  var `card_number_reversed`.

It sholud be ：
Create a variable `even_digits` and assign it the even digits of the  variable  `card_number_reversed`

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/step-23

### Your code

```
even_digits = card_number_reversed[1::2]


```

### Expected behavior

It should easy to get info

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

OS: Windows 10

**Comment by naomi-lgbt** [comment] 2024-07-29 17:12
The purpose of instructions like this is to get learners to reflect on the code they are writing.

There are quite a few steps that explain how to reverse a string and ultimately assign it to the `card_number_reversed` variable, so this step encourages you to recall the code you wrote.

The hints (re: tests) for this challenge clarify what code you are specifically supposed to write. I'm not sure there's anything to fix here.

**Comment by v-aibhavbajaj2520** [comment] 2024-10-15 17:28
Hi @luojiyin1987 ,
I hope you're doing well!

I came across your repository and noticed it's open for Hacktoberfest contributions. I'm excited about the opportunity to contribute to this project and would love to help out. Could you please assign me an issue to work on? I’m eager to dive in and help solve problems!

Looking forward to contributing and collaborating with you.

Best regards,
Vaibhav

**Comment by ilenia-magoni** [comment] 2024-10-15 17:56
Hi @v-aibhavbajaj2520 ,

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Closed** 2024-11-18 11:03 UTC
Labels: status: discussing, scope: curriculum, new python course
