### ISSUE TITLE
The "view the curriculum" button shows white screen after going to next challenge & clicking it.

### ISSUE THREAD

**Issue by rajatkantinandi** [freeCodeCamp/freeCodeCamp#17350] opened 2018-05-31 18:52 UTC
#### Describe your problem and - if possible - how to reproduce it

When I complete a challenge and go to next challenge by pressing Ctrl + Enter, then If I click the "view the curriculum" button then the whole screen turns white & the app supposedly crashes.
When I looked at the JS console of the browser, It shows the following error:
```JS
Uncaught TypeError: Cannot read property 'id' of undefined
    at Block.js:24
    at Array.map (<anonymous>)
    at Block.js:24
    at index.js?646b*:76
    at index.js?646b*:36
    at index.js?646b*:90
    at index.js?646b*:36
    at Function.q [as mapToProps] (Block.js:24)
    at r (wrapMapToProps.js:54)
    at Function.r.mapToProps (wrapMapToProps.js:63)

 Uncaught (in promise) DOMException: Quota exceeded.
```

#### Tell us about your browser and operating system

* Browser Name: Chromium 
* Browser Version: 66.0.3359.181
* Operating System: Ubuntu 18.04

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/17743895/40801928-d6975480-6531-11e8-8bb8-6e10a2941a95.png)

**Comment by mstellaluna** [comment] 2018-05-31 19:54
https://github.com/freeCodeCamp/freeCodeCamp/issues/17339 <- similar issue

**Comment by mstellaluna** [comment] 2018-05-31 19:56
duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17309

**Closed** 2018-06-01 00:01 UTC
