### ISSUE TITLE
Challenge count bug

### ISSUE THREAD

**Issue by Frasspira** [freeCodeCamp/freeCodeCamp#16549] opened 2018-01-21 01:08 UTC
On FreecodeCamp I have completed 206 challenges, but when I look at my profile, it displays that I've only completed 2 challenges.Can someone please fix this?

![capture](https://user-images.githubusercontent.com/28991947/35189643-54a8a918-fe1d-11e7-84b8-6dc5229b3a82.PNG)

**Comment by raisedadead** [comment] 2018-01-21 06:33
Hi @Frasspira 

Just to note a confusion around the points, its not the no of challenges, but the brownie points (XP) earned.

You are awarded 1 point, per challenge when successful in passing, and also when receiving a thanks from someone in our chat rooms.

https://forum.freecodecamp.org/t/free-code-camp-brownie-points/18380

That said, this needs to be looked backend to confirm your claim.

/cc @QuincyLarson

**Comment by QuincyLarson** [comment] 2018-01-22 00:15
@raisedadead Yes - the cause of this is when a camper has a duplicate account. The navbar seems to look up the score based on the username, and the profile itself seems to look it up based on the email address, hence the two different values. 

If fixed this by deleting @Frasspira's duplicate account.

This is pretty rare, and considering we're completely changing the navbar on beta, I'm just going to close this issue as wontfix.

**Closed by QuincyLarson** 2018-01-22 00:15 UTC
Labels: support: accounts
