### ISSUE TITLE
A Link needs updated.

### ISSUE THREAD

**Issue by bhuz** [FreeCodeCamp/FreeCodeCamp#6987] opened 2016-02-14 05:58 UTC
Challenge [Use the Twitchtv JSON API](http://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The current link for step 8 is : https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Zipline-Use-the-Twitchtv-JSON-API

I believe it should be : https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-the-Twitchtv-JSON-API

**Comment by ltegman** [comment] 2016-02-14 05:59
Closing as a duplicate of #6961. Thanks and happy coding!

**Closed by ltegman** 2016-02-14 05:59 UTC
