### ISSUE TITLE
Passing the Sass Variable Challenge without using the variable

### ISSUE THREAD

**Issue by 524119574** [freeCodeCamp/freeCodeCamp#14990] opened 2017-05-22 02:41 UTC
#### Challenge Name

https://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables

#### Issue Description

I can pass the challenge without using the Sass Variable. The test suite dosen't seem to work well.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Microsoft Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<style>
  
  $text-color: red;
  
  .header{
    text-align: center;
  }
  .blog-post h2 {
    color: red;
  }
  
  .blog-post {
    color: red;
  }

  
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>



```

**Comment by systimotic** [comment] 2017-09-03 19:21
Hi @524119574! Thanks for reporting this issue. I'm closing this as a duplicate of #12699. Happy coding!

**Closed by systimotic** 2017-09-03 19:21 UTC
Labels: beta
