### ISSUE TITLE
Waypoint: Filter Arrays with filter GLITCH

### ISSUE THREAD

**Issue by redpill19** [FreeCodeCamp/FreeCodeCamp#4493] opened 2015-11-17 05:31 UTC
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This particular lesson in unresponsive and does not allow me to alter any of the code.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray;

 Array = newArray.filter(function(val) {

  return val > 5;

});
// Only change code above this line.

(function() { return newArray; })();

```

**Comment by SaintPeter** [comment] 2015-11-17 06:52
We have had various reports of freezing.  Were you able to do a hard-refresh to get it going again?  Have you checked your dev-console (F12 on most PC browsers) for any error/warning messages?

**Comment by redpill19** [comment] 2015-11-17 07:32
I tried to reset the code with the reset button within the lesson but it does not do anything.


When tapping the F12 key I received these 2 errors:

(1)_____________________________________________________________
jshint.js:17839 Uncaught TypeError: Cannot read property 'slice' of undefined:

   } catch (err) {
      if (err && err.name === "JSHintError") {
        var nt = state.tokens.next || {};
        JSHINT.errors.push({
          scope     : "(main)",
          raw       : err.raw,
          code      : err.code,
          reason    : err.message,
          line      : err.line || nt.line,
          character : err.character || nt.from
        }, null);
      } else {
          throw err;     *******<--- error was on this line: 17839*****

(2)______________________________________________________________
Uncaught TypeError: Cannot read property 'slice' of undefined:

  var signal = CodeMirror.signal = function(emitter, type /*, values...*/) {
    var arr = emitter._handlers && emitter._handlers[type];
    if (!arr) return;
    var args = Array.prototype.slice.call(arguments, 2);  *******<--- error was on this line: 7330 *****
    for (var i = 0; i < arr.length; ++i) arr[i].apply(null, args);
  };
_______________________________________________________________________

**Comment by redpill19** [comment] 2015-11-17 07:56
I completed this area by using safari on my Mac.  Not sure why the browser on my PC was causing this.

**Comment by redpill19** [comment] 2015-11-17 07:56
Thanks!

**Comment by bugron** [comment] 2015-11-17 12:00
@redpill19 thanks for posting this issue!
Closing as resolved but feel free to reopen if you still experience problems with this, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-11-17 12:00 UTC

**Comment by venkatraj** [comment] 2015-12-12 10:24
OP is assigning filtered array to Array constructor. That may be the cause?
```
 Array = newArray.filter(function(val) {
  return val > 5;
});
```
