### ISSUE TITLE
Algorithms: Implement Quick Sort not accepting an answer

### ISSUE THREAD

**Issue by adnan333bd** [freeCodeCamp/freeCodeCamp#36844] opened 2019-09-25 09:57 UTC
for this problem: https://learn.freecodecamp.org/coding-interview-prep/algorithms/implement-quick-sort

the following answer is not being accepted [this test case fails ' quickSort returns an array that is unchanged except for order. '], I have included verification code below the answer ... In my opinion it should be accepted. some thing is wrong in your test code.
```
//answer starts
function quickSort(array, p = 0, r = array.length) {
    if (p < r) {
        const q = partition(array, p, r);
        quickSort(array, p, q - 1);
        quickSort(array, q + 1, r);
    }
    return array;
}

function partition(array, p, r) {
    const pivot = array[r];
    let j = p - 1;
    for (let i = p; i < r; i++) {
        if (array[i] < pivot) {
            j = j + 1;
            exchange(j, i);
        }
    }
    exchange(j + 1, r);

    function exchange(a, b) {
        let temp = array[a];
        array[a] = array[b];
        array[b] = temp;
    }
    return j + 1;
}
//answer ends

function randomArray() {
    let l = Math.random() * 10;
    let ranArray = [];
    for (let i = 0; i < l; i++) {
        ranArray.push(Math.round(Math.random() * 10));
    }
    return ranArray;
}
function verify(array, sortedArray) {
    let yes = true;
    for (let i = 0; i < array.length - 1; i++) {
        if (array[i] > array[i + 1]) {
            yes = false;
        }
    }
    return yes && array === sortedArray;
}
function test() {
    for (let i = 0; i < 1000; i++) {
        const ranArray = randomArray(); // input case generation
        
        const sorted = quickSort(ranArray); // execution        
        
        if (!verify(ranArray, sorted)) { // verification
            console.log('wrong answer');
            return;
        }
    }
    console.log('accepted');
}

test();
```

**Comment by RandellDawson** [comment] 2019-09-25 15:10
@adnan333bd Please use [our forum](https://www.freecodecamp.org/forum) when you are having trouble with your code passing a challenge's tests.  If the users on the forum determine there is nothing wrong with your code, that is when you should open up an issue (and link to the applicable forum thread).

Your `quicksort` function does not return an array with all the same values for the test array shown in the challenge seed code. The following call using your code:
```js
quickSort([1,4,2,8,345,123,43,32,5643,63,123,43,2,55,1,234,92]);
```
returns:
```js
[undefined, 1, 1, 2, 2, 4, 8, 32, 43, 43, 55, 63, 92, 123, 123, 234, 345, 5643]
```
instead of the correct array (shown below):
```js
[1, 1, 2, 2, 4, 8, 32, 43, 43, 55, 63, 92, 123, 123, 234, 345, 5643]
```
I am closing this issue as it is not a bug in the tests and instead is a bug in your code.

**Closed by RandellDawson** 2019-09-25 15:10 UTC

**Comment by adnan333bd** [comment] 2019-09-26 12:28
Thanks RandellDawson, the default value of r should be array.length - 1.
My mistake
