### ISSUE TITLE
Night Mode: Close/expand button color

### ISSUE THREAD

**Issue by MAshrafM** [FreeCodeCamp/FreeCodeCamp#8066] opened 2016-04-12 07:18 UTC
#### Issue Description

Night Mode: map-aside
the close and expand buttons are the same color as the background.

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/10391294/14452463/0b897a74-008f-11e6-8d7e-33bd519d8435.PNG)

**Comment by erictleung** [comment] 2016-04-12 07:29
@hallaathrad I thought this was fixed with #8000? Berkeley pushed this update to `master` with #8052. Also, this is a possible duplicate of #8001.

**Closed** 2016-04-12 07:48 UTC
