### ISSUE TITLE
Beta - ARWD Projects - Tribute Page - Tests failing with assert errors when using CDN

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16808] opened 2018-03-01 14:43 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page

#### Issue Description

On my codepen I have a partially coded tribute page. 
[Tribute Page](https://codepen.io/mstellaluna/full/wyNBNJ/)

There are no 'user stories' that I can find on the project description (this will be another issue).

I took the CDN https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js provided on the project page and linked it into my project with the script tag and executed the tests

When attempting to view the results of the tests, I get the screenshot below

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

SELECTING UNIT TEST:
![image](https://user-images.githubusercontent.com/22984739/36850386-a08780ee-1d34-11e8-878c-49984256a6e3.png)

AFTER EXECUTING UNIT TEST:
![image](https://user-images.githubusercontent.com/22984739/36850419-be6c76f0-1d34-11e8-874f-8064e996db3e.png)

AFTER SELECTING RED TEST BUTTON TO VIEW RESULTS:
![image](https://user-images.githubusercontent.com/22984739/36849491-2fe7ca26-1d32-11e8-8db2-c90220c22a06.png)

**Comment by QuincyLarson** [comment] 2018-03-05 23:51
@tchaffee @tbushman any idea what could be causing this issue?

**Comment by QuincyLarson** [comment] 2018-03-05 23:53
@tchaffee @tbushman any idea what could be causing this issue?

**Comment by tbushman** [comment] 2018-03-06 00:08
@mstellaluna It looks like a closing curly bracket (or two maybe) is missing after an Object in the embedded json. The console logs that the bracket was opened at line 334, which is an Object within the `keyframes' array.

**Comment by tbushman** [comment] 2018-03-06 00:13
@QuincyLarson We've been looking into ways to encapsulate the test suite's scripts and styles. Unfortunately, the Mocha reporter modal won't run in an iframe as far as has been tried. ShadowDOM isn't working in all browsers.

**Comment by mstellaluna** [comment] 2018-03-06 00:49
@tbushman hmm...I didn't notice... , i'll re-do the tribute page without the effect and try it again.

**Comment by mstellaluna** [comment] 2018-03-06 02:50
@tbushman  I made a fork of the original one and I cleaned up the effects off of the tribute page. So it wouldn't interfere in any way. All you see now is just the image, titles and links.
I modified some of the content so i now pass 3/10 tests and let the other 7 fail on purpose.

this is the modified pen [Simplified Pen](https://codepen.io/mstellaluna/full/bLPWQe/)
this is what i am now seeing

![image](https://user-images.githubusercontent.com/22984739/37011642-05416206-20bf-11e8-992b-453b8b427d3c.png)

To see what the green checkmarks are i need to click on them 

![image](https://user-images.githubusercontent.com/22984739/37011672-20d727bc-20bf-11e8-9d13-d14c8e357fe0.png)

Am i doing something wrong or ?

**Comment by tbushman** [comment] 2018-03-06 03:39
@mstellaluna You've got it right. Thanks. The problem is that CSS styles given directly to tags (`button`, `h1`) interfere with the test suite ui's respective tags. It is similar to this, # 269 at freeCodeCamp/testable-projects-fcc (https://github.com/freeCodeCamp/testable-projects-fcc/issues/269). Looking into ways to best encapsulate the test suite ui from Student projects (# 279 , # 270). In the meantime, using className in the css selectors will fix this in your project. Thank you.

**Comment by mstellaluna** [comment] 2018-03-06 03:51
@tbushman thanks for the reply. I will fix the 2nd copy as per your instructions and see what happens.Greatly Appreciated

**Comment by tbushman** [comment] 2018-03-06 03:53
@mstellaluna OK cool. Thanks for your feedback.

**Comment by tbushman** [comment] 2018-03-29 02:31
This was fixed by @tchaffee in https://github.com/freeCodeCamp/testable-projects-fcc/pull/298 He used more specific css selectors and overrides. Thank you!

**Comment by QuincyLarson** [comment] 2018-04-10 04:30
@tbushman Thanks for confirming this is now fixed! I'll close it. 👍

**Closed** 2018-04-10 04:30 UTC
Labels: beta
