### ISSUE TITLE
Issue occurs when using the back button to repeat a lesson, lessons are skipped 

### ISSUE THREAD

**Issue by FizzyDre** [FreeCodeCamp/FreeCodeCamp#2986] opened 2015-09-02 05:34 UTC
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screenshots if possible. This issue I noticed can occur on ANY page and its not applicable to only this page, however on this page I decided to report it. If You press the back button to repeat a lesson or just review the information. And you then click on the Run Code button again on that lesson, instead of taking you to the next lesson, it acts as if you completed that next lesson ( since you were on that page last when you pressed the back button ) and takes you to the lesson after that one, even though you never completed the previous page.. for example. on the page http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list which is waypoint 26, I did not do this lesson and instead pressed the back button to go to the waypoint 25 again. I completed 25 again, press Run Code and am then taken directly to Waypoint 27. To try and get back to 26 , i press back again and it goes to Waypoint 25 again, I complete and press run code ,and this time it takes me to Waypoint 28, thus skipping both 26 AND 27 in this next attempt .

**Comment by shaikhatik0786** [comment] 2015-09-02 07:16
@FizzyDre Well, I re-constructed the same situation, and I didn't face any such problem. It was working completely fine.
Sequesnce : 26>25>26>27

**Comment by benschenker** [comment] 2015-09-03 04:56
@FizzyDre I am also unable to reproduce this.  I'll close this now, but feel free to reopen if you experience this issue after performing a [Hard Refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)

**Closed by benschenker** 2015-09-03 04:56 UTC
