### ISSUE TITLE
Sass: Store Data with Sass Variables

### ISSUE THREAD

**Issue by jowaynejosephs** [freeCodeCamp/freeCodeCamp#14500] opened 2017-04-19 20:45 UTC
Challenge [store-data-with-sass-variables](http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am getting an error for the last 2 parts of the challenge (Your .blog-post element should have a color of red.) and (Your h2 elements should have a color of red.) The variable seems to be buggy

```html


<style>
  $text-color:red;
  
  .header{
    text-align: center;
  }
  .blog-post h2 {
    color: $text-color;
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>

```

**Comment by erictleung** [comment] 2017-04-21 18:27
@jowaynejosephs thanks for the issue. Yes, there seems to be something wrong with the use of the variable and how it is being translated. But I'm not sure how to fix it. I'll leave this open for others to investigate as well.

![image](https://cloud.githubusercontent.com/assets/2754821/25291084/7b294450-2685-11e7-9694-b1adb02dba68.png)

**Comment by masters-george** [comment] 2017-04-22 21:13
I am also getting the same issue with chrome on a Linux-mint community.

**Comment by cotolany** [comment] 2017-05-13 17:38
Same. in Chrome win7. 
Have workaround :
.blog-post, h2 {
    color: $text-color;
    color: red;     /* This is just a workaround to pass lesson untill tests will be corrected. */
  }

**Comment by BtheGit** [comment] 2017-06-21 18:09
This threw an error for me. Even cotolany's workaround didn't satisfy all test (the third failed). Kind of a bummer to have the very first exercise of the section not work.

**Comment by systimotic** [comment] 2017-09-03 19:16
Hi all! Thanks for reporting and looking into this issue. I'm closing this as a duplicate of #12699. Happy coding!

**Closed by systimotic** 2017-09-03 19:16 UTC
Labels: beta, bug, tests

**Comment by mirkocoppola80** [comment] 2018-07-16 14:42
I am getting the same error:
Your .blog-post element should have a color of red.) and (Your h2 elements should have a color of red.

**Comment by zohaib9613** [comment] 2018-07-27 20:42
I have same problem with this challenge.

**Comment by mohandast52** [comment] 2018-07-29 16:51
<style type='text/sass'>
  $text-color: red;
  
  .header{
    text-align: center;
  }
  .blog-post{
    color: $text-color;
  }
  h2 {
    color: $text-color;
  }
</style>
/* try this */

**Comment by mohandast52** [comment] 2018-07-29 16:53
```sass
$text-color: red;
  .header{
    text-align: center;
  }
  .blog-post{
    color: $text-color;
  }
  h2 {
    color: $text-color;
  }
```

**Comment by Maram-RBK** [comment] 2018-07-29 23:30
Delete the type of style; I try it and it works!

**Comment by varshap22** [comment] 2018-08-10 07:35
I am getting the error:
Your .blog-post element should have a color of red.) and (Your h2 elements should have a color of red

**Comment by Fanon316** [comment] 2018-08-12 12:25
<p> I used the work-arounds described above, and was able to complete the challenge.</p>

**Comment by varshap22** [comment] 2018-08-12 15:43
But I can't complete the problem. Can you help me

**Comment by Fanon316** [comment] 2018-08-12 16:00
<p>I will be glad to assist. What code have you written for the challenge?</p>

**Comment by varshap22** [comment] 2018-08-12 16:05
Actually which questions is asked I completely according that I code. But
after run test it's shows 2 things which is not completed.

**Comment by varshap22** [comment] 2018-08-12 16:06
Can I send u code tommorow. Is it OK to help me? Because now its not
possible to send because I'm in outside.

**Comment by Asjas** [comment] 2018-08-12 16:09
@varshap22 Github Issues aren't used for support queries. It's used to report issues with the codebase.

Please use the [freeCodeCamp Forum](https://forum.freecodecamp.org/) or the [freeCodeCamp Gitter](https://gitter.im/FreeCodeCamp/HelpFrontEnd) for support questions.

Please stop posting on old issues.
