### ISSUE TITLE
Curser jumping around

### ISSUE THREAD

**Issue by matthewbryancurtis** [FreeCodeCamp/FreeCodeCamp#8321] opened 2016-04-27 23:25 UTC
I click in the block of code where I need to make an edit, but when I begin typing it appears randomly somewhere else in the block of code.

Problem on many pages. Mac/Chrome

Thanks.

Challenge [Use the Bootstrap Grid to Put Elements Side By Side](https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <button class="btn btn-block btn-danger">Delete</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by erictleung** [comment] 2016-04-28 00:00
@matthewbryancurtis closing as duplicate of #8253 and #7847. This issue is about the editor that we use in FCC. Please read [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8253#issuecomment-214134315) for more info.

**Closed by erictleung** 2016-04-28 00:00 UTC
