### ISSUE TITLE
Test not working in "Create a Horizontal Line Using the hr Element"

### ISSUE THREAD

**Issue by pdavidp** [freeCodeCamp/freeCodeCamp#18041] opened 2018-08-22 23:17 UTC
#### Describe your problem and - if possible - how to reproduce it
The test "The hr tag should come between the title and the paragraph." is always failing in Applied Visual Design: Create a Horizontal Line Using the hr Element. I tried adding \<hr>, \<hr/> and \<hr /> in line 31 but that doesn't work.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: 68.0.3440.106
* Operating System: Linux

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/12395023/44495924-f77b3f00-a63f-11e8-8bed-e1dbeefafd7e.png)

**Comment by mustafa-mustafa** [comment] 2018-08-23 01:10
تئكد من وجود الفوارز والنقط غير مرغوب بها

**Comment by Nirajn2311** [comment] 2018-08-23 04:29
<hr /> is for xhtml but over here we are using html.

Duplicate of #17944 , so could you please close this issue?

**Comment by scissorsneedfoodtoo** [comment] 2018-08-23 05:06
@pdavidp, thank you for reporting this. Will close this since it's a duplicate of #17944 where a workaround is also posted.

**Closed by scissorsneedfoodtoo** 2018-08-23 05:06 UTC
