### ISSUE TITLE
Getting No-Access-Control-Origin error on previously working/completed Camper News Project

### ISSUE THREAD

**Issue by Ramon-Carroll** [FreeCodeCamp/FreeCodeCamp#7744] opened 2016-03-27 06:15 UTC
#### Issue Description
* I have noticed that when I return to view my completed Camper News project, I am failing to get access to the API via AJAX, as I'm now getting the "No-Access-Control-Origin" error in the console. This has been working from the moment I completed it (2015), but for reason, it does not work anymore, so no news info is populating the page as I designed. Not sure if FCC server still accepts CORS or if I'm doing something wrong?
* I tried pulling up the project on codepen via Firefox Browser, as well as my iPhone's Safari browser. Same results.

#### My Browser Information
* Chrome Version 49.0.2623.87 (64-bit)
* Linux, Ubuntu Mate 15.10 

#### My Code

[My codepen](http://codepen.io/Ramon-Carroll/full/ZbgmGB/)

```js
var req = new XMLHttpRequest();
req.open("GET", "http://www.freecodecamp.com/news/hot", true);
req.onload = function() {
  var fcc;
  fcc = JSON.parse(req.responseText);
  var amountToDisplay = 40;
  for (var i = 0; i < amountToDisplay; i++) {
    var storySection = document.querySelector(".story-section");
    var story = document.createElement("div");
    var headline = document.createElement("a");
    var img = document.createElement("img");[GitHub](http://github.com)
    var author = document.createElement("a");
    var likes = document.createElement("p");
    story.classList.add("story"); 
    headline.classList.add("headline");
    headline.setAttribute("href", fcc[i].link);
    headline.innerHTML = fcc[i].headline;
    headline.setAttribute("target", "_blank");
    img.setAttribute("src", fcc[i].author.picture);
    author.classList.add("author");
    author.setAttribute("href", "http://www.freecodecamp.com/" + fcc[i].author.username);
    author.innerHTML = "By " + fcc[i].author.username;
    likes.innerHTML = "♥ " + fcc[i].upVotes.length;
    likes.classList.add("likes");
    story.appendChild(headline);
    story.appendChild(img);
    story.appendChild(author);
    story.appendChild(likes);
    storySection.appendChild(story);
  };

};
req.send();
```

**Comment by raisedadead** [comment] 2016-03-27 07:01
@Ramon-Carroll We have recently switched to SSL everywhere on the FreeCodeCamp website, the requests now need to be made over `https`. 

Try changing your call to the `http://www.freecodecamp.com/news/hot` to `https`
This should fix your issue.

However on a side note we have retired Camper news, and perhaphs the API will be turned off soon, The challenge would be updated with a alternate data source/api when that happens.

Refer #7700 and #7082

**Comment by raisedadead** [comment] 2016-03-27 13:23
Closing as duplicate of #7617

**Closed by raisedadead** 2016-03-27 13:23 UTC
Labels: blocked

**Comment by Ramon-Carroll** [comment] 2016-03-27 16:53
@raisedadead Yep, that was all to it. Thanks for that! :)

Also, I'm aware that we dropped Camper news, but I wasn't aware that the API would be dropped too. I have a fully built portfolio, and that basically means that one of the projects that I have on display will break, and I'll have to replace it. While I understand that there's not much of a way around that inconvenience, I'd hope that we are notified of the new project long before the API is turned off, so I have sufficient time to replace it on my website.

Either way, thank you for all that you guys do. It's highly appreciated! :)
