### ISSUE TITLE
Learn Bash module not checking if tests are being passed

### ISSUE THREAD

**Issue by TMHermes** [freeCodeCamp/freeCodeCamp#50750] opened 2023-06-18 17:05 UTC
### Describe the Issue

Learn Bash Scripting by Building Five Programs stopped checking if the tests are going through.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-scripting-by-building-five-programs/build-five-programs

### Your code

```

touch questionnaire.sh

```

### Expected behavior

Check test run.

### Screenshots

![test failed](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/5d71ea21-9a72-49a5-a5a2-7d6ded0a0722)
![test erro2](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/e6dbcf10-8d09-4a34-9289-ff26fdae0ff3)
![test error](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/a1ec8783-44a9-44e9-949e-aa2859fd41fe)

### System

- Device: Desktop
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 114

**Comment by rahulsiloniya** [comment] 2023-06-19 03:35
Did you try to close chrome and restart the codeally server? It may help fixing it because I tried to reproduce this on Windows 11 with Chrome and it is working as expected.

**Comment by TMHermes** [comment] 2023-06-19 17:55
Thanks for your answer! Thats odd cause I tried in two different computers and for several days in a row, so no, it doesnt work for me =/ I tried reseting the codeally, undoing the changes in the mocharc.json, I actually tried a lot of stuff rsrs maybe I messed up something, idk Is there any way to full or hard reset this challenge or some? I'm almost finishing the database courses and this will stay back.

**Comment by ojeytonwilliams** [comment] 2023-06-20 09:46
@moT01 any idea what's going wrong here?

**Comment by moT01** [comment] 2023-06-20 16:15
I'm not quite sure what is happening here. The mocharc file in the screenshot says it's still testing `10.test.js`, which is the step before the one @TMHermes is on. [See the steps here.](https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs/blob/main/TUTORIAL.md) He said he tried "undoing the changes in the mocharc.json" - so perhaps it says `10.test.js` because he reverted it, but that's supposed to change to `20.test.js` after you pass the first step. You could try changing that to `20.test.js` @TMHermes - or maybe try completing the task from the first step again (enter `echo hello bash` in the terminal). Maybe doing one of those will get things back on track for you.

There's a few things you could look at in the "output". Open a terminal and click the output tab, then find the CodeRoad options in the dropdown menu:

<details><summary>image</summary>

![cr](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/cfd5ceff-dc29-472a-abcf-50f10a7da7dc)

</details>

And you could share what you see in those two outputs. It may say that the commit for 20 failed to load or something, or give a reason the test is failing.

An additional problem I see it that the dark the me isn't being applied - which didn't used to happen much, but it seems to be happening a lot lately, like every time. When you start a course, files are copied to the workspace, including some vscode settings - those aren't being applied, but it does look like the files are being copied. I'm not sure if that's related to this - I will look into it.

**Comment by TMHermes** [comment] 2023-06-20 20:03
Hey @moT01 thanks for passing by. I still dont know whats happening. The dark theme thing you brought up I remember noticing, it used to be realy dark rsrsrs. 
Well, I tried both things to fix, but none of that worked, im sharing the prints below.
![output](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/23cfba58-fe84-49af-8db1-237c7515a955)
![terminal](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/a19b0182-5ff9-44fc-8213-9b0cf728c8d1)
![output2](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/63a495d5-ef1b-4e10-9996-7333fbc716b3)
![reset](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/7ac2a0a9-f7c5-494e-92e0-165b5a437780)
![tess2](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/a9092a1b-c736-47a4-864b-c0882fdfbc0e)

I also tried to hard code fix the mocharc.json, like this:
![mocharc](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/4dc58da5-9ef5-45fe-bc91-3fdc6eeb0f89)
[
Any other ideas? Tks again

**Comment by TMHermes** [comment] 2023-06-20 20:06
Actually I just saw sth funny, I dont have the CodeRoad (Tests) in the dropdown menu as you do, check it out:
![coderoadtests](https://github.com/freeCodeCamp/freeCodeCamp/assets/101218962/4942c383-f730-4fa3-824a-5fd77a14fa69)

**Comment by moT01** [comment] 2023-06-22 16:04
Since you are on the second step, I would recommend deleting your container and starting over @TMHermes - you can [learn how here.](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#last-resort-18)

Once you start up your new container, I would close it and open it back up - the settings should then take effect. I have created [an issue in another repo describing that problem.](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/61)

If you come across this problem again. I would recommend posting on the forum first. There are times where something just goes wrong with the container or the course and it's tough to debug/fix or get back on track. Many times, a problem like this won't come up again after restarting. If the problem is consistent, maybe then we can try to look into it more.

**Closed by moT01** 2023-06-22 16:04 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
