### ISSUE TITLE
Add a warning that browser extensions may cause issues

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38353] opened 2020-03-11 02:23 UTC
More than a few times, someone has had issues passing a challenge because of interference from a browser extension(s). Seems to mostly happen in the CSS section or other areas where users are changing styles. [Original discussion here](https://github.com/freeCodeCamp/freeCodeCamp/issues/37774). We could probably add a warning about this.

**Comment by snigo** [comment] 2020-03-12 16:17
Ok, I actually installed uBlock and was able to re-create the problem. It removes containing `div` based on `fanboy-social` filter, particularly `##.follow-btn` rule and it causes test to fail.

I guess we need to rename it to something without "follow" in the class name

**Comment by ojeytonwilliams** [comment] 2020-03-12 17:13
If it is just classes with `follow-`, that's not so bad.  I could only find 5 challenges like that.  

Any idea if `btn-follow` would be okay?  That would be a trivial fix.

**Comment by snigo** [comment] 2020-03-12 17:28
I would rather use `.action-button-container`

**Comment by ojeytonwilliams** [comment] 2020-03-12 17:34
Sure, both seem fine to me.

**Comment by lasjorg** [comment] 2020-03-17 23:09
Some dark mode/reader extensions also cause issues with color related CSS challenges. The problem is if we check the computed styles and the extension changes the colors.

**Comment by lasjorg** [comment] 2020-04-11 13:36
I think we should add a note to the start of the [CSS curriculum](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/) about extensions that change the look of the page (e.g. dark mode extensions) and how they can interfere. We can also inform the user that we have a dark mode under the profile settings.

This issue is pretty common and we get forum threads created because of it all the time.

**Comment by ahmadabdolsaheb** [comment] 2020-04-12 14:09
If it is common, I am for adding a note.

**Comment by ojeytonwilliams** [comment] 2020-04-14 09:59
Why not do both?  We can never be sure that all extensions have been accounted for, so the note makes sense.  However, @snigo's already investigated `uBlock` and found [the list](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt) that includes `follow-btn` so that might as well be changed.

@snigo would you be up for implementing that fix?

**Comment by moT01** [comment] 2020-04-14 11:36
How about this... 

###  _**Some browser extensions maybe interfere with elements on the page causing the tests to fail unexpectedly. For the most reliable experience, disable all browser extensions.**_

**Comment by lasjorg** [comment] 2020-04-14 15:51
@ojeytonwilliams Just remember both the video and the hint will need to be updated if we make that kind of change.

The issue is mainly with the videos which seem to have gotten harder to get updates for.

**Comment by ojeytonwilliams** [comment] 2020-04-14 16:01
@lasjorg thanks for the reminder, somehow I keep forgetting that.  How about we just go with Tom's text?

**Comment by lasjorg** [comment] 2020-04-15 21:14
Maybe simplify the text a bit?

> **Note**: Browser extensions may interfere with curriculum challenges. For the most reliable experience, disable all browser extensions.

Not sure if we want to expand on this to make it a little less "_hey please disable your 50 extensions by hand every time you do a fCC challenge_". Maybe a quick note on what extensions to look out for?

> Extensions that are known to cause issues are ad-block and dark mode extensions. For a dark mode experience, use the dark mode found under the profile settings.

Or something like that.

**Comment by moT01** [comment] 2020-04-16 00:56
Here's another option that's a little cleaner maybe...

**Note:** Some browser extensions may cause tests to fail unexpectedly. For the most reliable experience, disable your browser extensions.

Any of these will work I think, as long as the message gets across.

**Comment by lasjorg** [comment] 2020-05-10 19:32
@moT01 A PR for this would be blocked by the current code freeze, correct? Do you know how long that is going to be in place?

We really need to get this implemented as soon as possible, we constantly get forum posts about this.

**Comment by moT01** [comment] 2020-05-11 13:04
Yes, it would be blocked at the moment. Although the warning would be in the introduction - maybe we can make an exception here. What do you think @freeCodeCamp/dev-team?

**Comment by raisedadead** [comment] 2020-05-11 13:07
Yes, We can make the exception for this. A PR is welcome.

**Comment by moT01** [comment] 2020-05-11 13:20
@ojeytonwilliams & @snigo, I'm assuming the fix you mentioned about the `follow` classes are part of the code in challenges themselves right? And not part of our components - just making sure.

If that's the case. For now, I would probably go for just adding the warning.

**Comment by luqven** [comment] 2020-05-12 23:32
@moT01 hope it’s alright I PRd a quick fix for this, #38806. Assuming that 1) warning should only be displayed on into page and 2) warning should be displayed for every new session where an ad-blocking extension was detected.

**Closed** 2020-05-19 08:35 UTC
Labels: scope: learn, status: fix in progress
