### ISSUE TITLE
Wrong description for challenge completion - Nesting anchor elements.

### ISSUE THREAD

**Issue by azhz** [FreeCodeCamp/FreeCodeCamp#6551] opened 2016-01-28 18:36 UTC
Challenge [Nest an Anchor Element within a Paragraph](http://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EView%20more%20%3Ca%20href%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The description is clear but the line doesn't have a fullstop after the sentence - 'View more cat photos' which is required for the test cases to pass. Please correct it!

**Comment by hallaathrad** [comment] 2016-01-28 18:47
Forgive me but I don't seem to understand what the bug is. Would you please post a screen capture, as it was suggested in the [guide to create an issue report](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue)?

**Comment by sludge256** [comment] 2016-01-28 18:49
I'll chime in. There is no space in the instructions after "photos" in "View more cat photos"
>Now nest your existing a element within a new p element (just after the existing h2 element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text.

but one of the tests are
>Your p element should have the text "View more " (with a space after it).

**Comment by raisedadead** [comment] 2016-01-28 18:49
@hallaathrad I was just checking @azhz 's code:

He has this:
```
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a>.</p>
```
Note the period he has added. I don't think that's necessary for the test case to pass. It's passing without it. Should be something else.

**Comment by raisedadead** [comment] 2016-01-28 18:51
@sludge256 but his code still passes for me! Lol, not sure what the trouble is.

**Comment by hallaathrad** [comment] 2016-01-28 18:52
@raisedadead That's the way I have mine too... I'm just struggling to understand what the issue is in the way he's described it.
<img width="1231" alt="screen shot 2016-01-28 at 13 51 00" src="https://cloud.githubusercontent.com/assets/2107110/12655291/35a1e4bc-c5c6-11e5-8e7a-fb010711a16b.png">

furthermore... according to your recent responses, he may want to copy all the code, press reset and paste it back instead.

**Comment by sludge256** [comment] 2016-01-28 18:52
Yea my train of though was incorrect. We'll wait until he posts more details.

**Comment by azhz** [comment] 2016-01-29 03:28
Hi,

@raisedadead correctly noticed I added a period after closing anchor tag.

@hallaathrad Right. But there's is no screenshot as such for this. The issue is with the description given in the challenge which says

> Now nest your existing a element within a new p element (just after the existing h2 element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text.

Here, there is no period after the line 'View more cat photos'. Due to which I didn't add any period while writing HTML and my code didn't pass the tests. But as soon as I added period after closing the anchor tag, the tests passed!

@sludge256 No issues after adding the period. But it was difficult to figure out why the tests were not passing.

I thought it will also be difficult for anyone else who is new and trying to solve this challenge and that is why posted this as a bug.

**Comment by hallaathrad** [comment] 2016-01-29 03:33
oh, ok. now I get what you mean... let me go check this and submit a correction if necessary

**Comment by sludge256** [comment] 2016-01-29 03:34
You can pass without a `.`

**Comment by hallaathrad** [comment] 2016-01-29 03:35
hahaha I was about to say that.
I've just run a test without the . in my own machine and it works just fine.

**Comment by azhz** [comment] 2016-01-29 03:37
Somehow, it did not work for me! @sludge256 and @hallaathrad

**Comment by hallaathrad** [comment] 2016-01-29 03:39
As I responded earlier, it may have been some issue with the browser... not uncommon. 
My solution when that happens has been to copy all, reset, and paste. No idea why.
I'm glad you could get past it, though. 
And at least we know now the description doesn't really need to be modified.

**Comment by sludge256** [comment] 2016-01-29 03:41
Since it appears this issue is resolved I'll close it.

**Comment by azhz** [comment] 2016-01-29 03:41
@hallaathrad My bad. Just checked now again and it worked without the period. You can close the issue.

**Closed by sludge256** 2016-01-29 03:41 UTC
Labels: blocked

**Comment by hallaathrad** [comment] 2016-01-29 03:43
:+1: I'm glad it worked out, @azhz happy coding

**Comment by Ah-d** [comment] 2017-01-05 19:40
I know this is a year old, but I had the same problem running Chromium browser. I switched to Firefox and immediately passed this part.

**Comment by drazahazard** [comment] 2017-05-03 19:33
it also fails for me in chrome canary. Seems to be a browser issue. Firefox works just fine.

**Comment by samah20** [comment] 2018-07-22 08:14
<h2>CatPhotoApp</h2>
<main>
  <p>View more cat photos
    <a src="https://bit.ly/fcc-relaxing-cat">cat photos</a>
    </p> 
  <a href="http://freecatphotoapp.com" target="_blank">cat photos</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
الخطأ 
Your a element should be nested within your new p element.
