### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kirilllog** [FreeCodeCamp/FreeCodeCamp#10607] opened 2016-09-09 16:59 UTC
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = "I am a \"double quoted\" string inside \"double quotes\".";




```

**Comment by ArielLeslie** [comment] 2016-09-09 17:05
![image](https://cloud.githubusercontent.com/assets/6234475/18395754/47969ab0-767d-11e6-80d6-54649b54ef9e.png)
Reproduced in Chrome.

**Comment by dhcodes** [comment] 2016-09-09 17:10
@kirilllog Thanks for the issue. Closing this as a duplicate of #10258

**Comment by BerkeleyTrue** [comment] 2016-09-09 17:11
@dhcodes you beat me to it!

**Closed by dhcodes** 2016-09-09 17:10 UTC
Labels: question
