### ISSUE TITLE
Certificate section sometimes disappears from settings page

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17369] opened 2018-06-01 13:25 UTC
I don't know how to reproduce this, but someone showed me a video of it on Twitter (which I unfortunately can't embed here). The certificate claiming section sometimes disappears entirely from the settings page.

**Comment by JMVL64** [comment] 2018-06-01 13:48
Mine does not appear anymore. I have the academic honesty part, which I signed, and then the delete account details danger zone. I have no clue how to register my certificates now. Google chrome, firefox, tried it all.
![screen shot 2018-06-01 at 15 47 48](https://user-images.githubusercontent.com/23399217/40844043-2a372a44-65b3-11e8-96d5-19a459b0c711.png)

**Comment by ahmadabdolsaheb** [comment] 2018-06-01 13:50
I could not reproduce it from Mac OS high sierra Chrome 66.0

**Comment by JMVL64** [comment] 2018-06-01 13:58
i have the same settings as you, MacOS high sierra and chrome 66.0, but i really don't see the certificates. Yesterday I did see them, but today they have disappeared for me

**Comment by MarioLema** [comment] 2018-06-01 15:04
Same here, although it was showing at first, it disappeared after I had tried to claim the responsive certificate, got the message saying I was missing some steps, clicked to accept the academic responsibility policy and when I refreshed the page all the projects/certificates section was gone.

There's an open issue referring to the same thing: [https://github.com/freeCodeCamp/freeCodeCamp/issues/17278](url)
but my console gives an error to a different bundle file which is minified so I guess it is just a collection of all js files needed that's created with the server request.

`Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at bundle-071d8ac….js:1
    at Array.filter (<anonymous>)
    at t.value (bundle-071d8ac….js:1)
    at s._renderValidatedComponentWithoutOwnerOrContext (bundle-071d8ac….js:1)
    at s._renderValidatedComponent (bundle-071d8ac….js:1)
    at s.performInitialMount (bundle-071d8ac….js:1)
    at s.mountComponent (bundle-071d8ac….js:1)
    at Object.mountComponent (bundle-071d8ac….js:1)
    at Z.mountChildren (bundle-071d8ac….js:1)`

Buttons for my privacy settings do not work either, everything is ticked as public but you can toggle between them.

I've also had a look at my data in the json file you can download in the settings. I assume it is the same used to build the page so it might be of use to identify why only a few of the users have this problem:

-A great amount of the challenges are listed as such on the json file:
`{"completedDate":1508537148979,"id":"bad87fee1348bd9aedf08822","solution":null,"challengeType":null}` or `{"completedDate":1516885289176,"id":"56533eb9ac21ba0edf2244bb","solution":null,"challengeType":1},`
In fact, almost all of them are null but 12 with the links to the codepen projects I have completed.
I thought it'd be of use as the typeError refers to converting null or undefined to an object and I guess <anonymous> is the json file of whatever user is loged in.

Also, everything seems to be fine in the UI bit:
`profileUI":{"isLocked":false,"showAbout":true,"showCerts":true,"showHeatMap":true,"showLocation":true,"showName":true,"showPoints":true,"showPortfolio":true,"showTimeLine":true}`

Wish I could help more but it is a bit too advanced for me yet.

**Comment by ChristianBeach** [comment] 2018-06-01 19:01
I believe that this and issue #17278 are the exact same
https://github.com/freeCodeCamp/freeCodeCamp/issues/17278

**Comment by Xivik** [comment] 2018-06-01 21:28
I've got the exact same issue.

Shortly after the update, I could see all the different certificates and links in my settings page. But that page is now completely broken, nothing saves, I can’t submit changes, fill in my name and city and stuff like that. The overview of the certificates and challenges is also completely missing, I can only see my basic info, and the signed academic honesty agreement, reset and delete account. That’s my entire settings page.

Issue remains over different browsers(chrome and edge latest version) both on my desktop and laptop, same problem on mobile.

my settings page only has the following elements now:
username/name/location/picture/about

privacy settings (these are all set to public)

download all your data

email settings
internet presence

portfolio settings
academic honesty policy
danger zone (reset/delete account)

I think the problem started after I added a portfolio item.

**Comment by ChristianBeach** [comment] 2018-06-01 23:02
@Xivik We have all the same problems, however I have never uploaded a portfolio item.

**Comment by utkarshsingh99** [comment] 2018-06-03 20:32
I would like to add another thing in addition to this. 
Even I cannot claim my certificate, but a peculiar thing I noticed was that I was unable to make any changes to my profile. I can type the name, save it, update the settings, but nothing actually gets saved.

This is another related bug to this settings activity.

**Comment by wangtian78** [comment] 2018-06-04 22:45
Same problem here. No certificate section in the settings.

**Comment by johnkennedy9147** [comment] 2018-06-05 13:46
@QuincyLarson as suggested by @ChristianBeach this is a duplicate of #17278.

**Comment by johnkennedy9147** [comment] 2018-06-05 13:47
symptoms - certificate section disappears and buttons on settings page stop working. I've successfully recreated in multiple accounts. More details on other issue.

**Closed** 2018-06-06 17:34 UTC
