### ISSUE TITLE
SASS Challenges not working at all 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16380] opened 2017-12-30 22:09 UTC
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/sass/store-data-with-sass-variables

#### Issue Description

None of the SASS challenges are passing tests.
It seems it can't detect the syntax.
On the first challenge it picks up the variable declaration but doesn't pickup the variable when assigned in an element.
Checking the dev console 42 errors are reported for document's frame is sandboxed .. 
I tried multiple variations, spaces, no spaces, 
Other campers in the main room also tried the challenge and its failing for them also
they also tried subsequent challenges and it also failing for them

I found these but not sure if related, I can't find an open issue for SASS challenges.

https://github.com/freeCodeCamp/freeCodeCamp/issues/15830
https://github.com/freeCodeCamp/freeCodeCamp/issues/16214
https://github.com/freeCodeCamp/freeCodeCamp/pull/14113
#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
FAILING CODE: 
`<style>
  
  $text-color: red;
  
  .header{
    text-align: center;
  }
  .blog-post h2 {
    color: $text-color;
  }
</style>`

PASSING CODE:
`<style>
  :root {
  --text-color: red;
}

  $text-color: red;

  .header{
    text-align: center;
  }
  .blog-post{
    color: var(--text-color);
    color: $text-color;
  }

</style>`
```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34457609-d2958f9e-ed83-11e7-96fa-10e9aae01d1f.png)

![image](https://user-images.githubusercontent.com/22984739/34457613-df163c0a-ed83-11e7-94ae-aa524c7a6fdd.png)

**Comment by joker314** [comment] 2017-12-30 22:15
Your code shouldn't work because (reading from your fail message)

> Your `.blog-post` element should have a color of red.

You have only styled elements with the selector of `.blog-post h2`. This is only `h2` elements contained within `.blog-post` elements; leaving out, for example, the paragraphs within the `.blog-post` element, as well as any `h2` elements outside of the `.blog-post` element.

To fix, you should at least try to place a comma in the selector.

I hear you've already tried it but it didn't work. If so, I'll admit this might be an error in the code.

**Comment by vkWeb** [comment] 2017-12-31 10:45
Confirmed.

**Comment by a7mam7ma** [comment] 2018-01-02 19:49
i think it is related to issue #16305

**Comment by vkWeb** [comment] 2018-01-03 07:24
@QuincyLarson, @BerkeleyTrue This is Important. This needs to be addressed before shipping.

**Comment by QuincyLarson** [comment] 2018-01-03 23:22
@BerkeleyTrue do you know what might be causing these Sass challenges to not work at all? We won't be able to QA the challenges until we get these working. Adding this to our critical path in the project.

**Comment by BerkeleyTrue** [comment] 2018-01-05 20:13
@QuincyLarson no I've had very little time to dedicate to SASS in the past. I'll also note that the errors/warnings in the console are unrelated.

**Comment by r1chard5mith** [comment] 2018-01-23 01:35
This looks like a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12699 ?

**Comment by QuincyLarson** [comment] 2018-01-24 04:27
@r1chard5mith Yes good catch. Closing in favor of #12699.

**Closed by QuincyLarson** 2018-01-24 04:27 UTC
Labels: beta
