### ISSUE TITLE
Use the reduce Method to Analyze Data, weak tests checks

### ISSUE THREAD

**Issue by ritikramuka** [freeCodeCamp/freeCodeCamp#42317] opened 2021-05-31 16:52 UTC
**Affected page**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

**Your code**

```
function getRating(watchList) {
  // Only change code below this line
  
  var averageRating = watchList
  .filter(e => e.Director === "Christopher Nolan")
  .map(e => Number(e.imdbRating))
  .reduce((sum, e) => sum + e, 0) / watchList.filter(e => e.Director === "Christopher Nolan").length;

  // Only change code above this line
  return averageRating;
}

```

**Expected behavior**
All test cases should pass, but showing that reduce function is not used

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.
![Screenshot from 2021-05-31 22-17-26](https://user-images.githubusercontent.com/56073559/120222976-77f21400-c25e-11eb-8452-a653ba58add2.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu 20.4
 - Browser: chromium

**Comment by ShaunSHamilton** [comment] 2021-05-31 18:11
Hello there,

Thank you, for taking the time to open this issue. The crux of the issue is outline here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/41951#issuecomment-830219649

The issue has been re-opened as it contains a lot more information about the problem, as well as all the affected challenges. So, I am closing this as a

Duplicate of #41951

**Closed by ShaunSHamilton** 2021-05-31 18:11 UTC
Labels: scope: curriculum, status: waiting triage, type: bug
