### ISSUE TITLE
Output Not Showing Up

### ISSUE THREAD

**Issue by codecycling** [freeCodeCamp/freeCodeCamp#17599] opened 2018-06-15 21:52 UTC
#### Describe your problem and - if possible - how to reproduce it
Every time I write the correct code and test it, I get the banner that I completed it correctly so that I can move on to the next exercise BUT my code output never displays in the following location: 
/**
* Your test output will go here.
*/
It only ever says the following so I can run all of the tests that are included in each exercise but I won't show me their output.  It only gives me the banner that it was completed successfully and the text below.   

// running test
// tests completed

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.79 (Official Build) (64-bit)
* Operating System: Windows 7 Enterprise  

#### If possible, add a screenshot here
![test complete](https://user-images.githubusercontent.com/8030188/41491010-86b9029e-70ab-11e8-9e5c-dae94986dc44.png)

**Comment by anku255** [comment] 2018-06-16 05:37
Hi! @codecycling This is not an issue. It says "Your **test output** will go here". It will not show the output of your javascript code.

Try running the test without writing any code and it will give you feedback saying
```
abTest(-2,2) should return undefined
abTest(2,-2) should return undefined
```

This is exactly how its designed to work. 

If you put any `console.log` in your code then you can see its output in the browser's console.

**Comment by StubRavi** [comment] 2018-06-16 09:07
![capture](https://user-images.githubusercontent.com/34769076/41497409-665c23c4-7172-11e8-97d0-762195c10f08.JPG)

console shows that the script is sandboxed but 'allow script' is not set.

**Comment by codecycling** [comment] 2018-06-16 14:39
How do I enable ‘allow script’?

Best, 

Rick

**Comment by texas2010** [comment] 2018-06-16 15:08
Duplicate of [#17356](https://github.com/freeCodeCamp/freeCodeCamp/issues/17356).

**Closed by texas2010** 2018-06-16 15:08 UTC
