### ISSUE TITLE
 myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10927] opened 2016-09-26 17:09 UTC
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0AmyStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; // Change this line

myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

```

> FirstLinenewlinebackslashSecondLinebackslashcarriage-returnThirdLine

It made me very confused!
I just can't  understand this, and why not directly show off the result effect of pic?
just like this!
![xxx](https://cloud.githubusercontent.com/assets/18028768/18844224/099fdd68-844f-11e6-8d85-3843e2e55fd4.PNG)

**Comment by dhcodes** [comment] 2016-09-26 17:25
Thanks for submitting this issue. I'm closing as I believe this is a duplicate of #10485. This should be fixed once a PR is made and merged from that thread and then pushed to the live site. In the meantime, please consider asking for help in the [Help Chat room](https://gitter.im/FreeCodeCamp/Help)

**Closed by dhcodes** 2016-09-26 17:25 UTC
