### ISSUE TITLE
Wrapping elements in div

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2583] opened 2015-08-23 13:59 UTC
Challenge http://freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When instructed to wrap all html elements in div this Waypoint gives you credit prematurely (by simply creating a div) not necessarily wrapping all the elements. 

It logical for me since I am very familiar with HTML but maybe for new html user it would not be obvious that you have to move closing tag to below all other tags since exercise validates without that action...

**Comment by benschenker** [comment] 2015-09-06 04:01
Hey @dgoran thanks for posting this issue!

It looks like it is a duplicate of #1983, so keep an eye there for updates.

**Closed by benschenker** 2015-09-06 04:01 UTC
