### ISSUE TITLE
Result from Editor is Incorrect

### ISSUE THREAD

**Issue by tylernathanreed** [FreeCodeCamp/FreeCodeCamp#8236] opened 2016-04-22 03:34 UTC
#### Challenge Name
https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E%0A%20%20CatPhotoApp%0A%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Issue Description
The result from the editor is incorrect.

I have a style declaration for the red-text class: `.red-text { color: red; }`, and an element which uses this class: `<h2 class="red-text">...</h2>`.

The grader recognizes both of these, yet the `h2` remains unstyled.

#### Browser Information
* Chrome for Android, V 49: 
* Operating System: Android 6.0.1
* Mobile, Desktop, or Tablet: Mobile (Nexus 5)

#### Your Code
```
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">
  CatPhotoApp
</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by theflametrooper** [comment] 2016-04-22 07:17
@tylernathanreed This isn't an issue for me?

**Comment by erictleung** [comment] 2016-04-22 07:42
Closing as duplicate of #7753.

**Closed by erictleung** 2016-04-22 07:42 UTC
Labels: blocked
