### ISSUE TITLE
Posting `Tweet a thanks` broken for single sign on twitter account

### ISSUE THREAD

**Issue by thatkid02** [freeCodeCamp/freeCodeCamp#51591] opened 2023-09-18 04:55 UTC
### Describe the Issue

I came across this bug while reading couple of articles and wanted to post a tweet.
When window opens with single sign on. The encoded redirect uri of the tweet content results in 400 with
`{"errors":[{"code":369,"message":"Invalid JSON syntax."}]}` from X/twitter

### Affected Page

https://www.freecodecamp.org/news/mycodeschool-youtube-channel-history/

### Steps to Reproduce

- Go to the mentioned link and click on **_Tweet a thanks_** button.
- Window will pop up
- Click on sign in with google or any single sign on. (Make sure you have not logged in to X/twitter)
- The window should have error code as it fails to process.
**tweet button**
![tweetathanks](https://github.com/freeCodeCamp/freeCodeCamp/assets/96950986/83ef7728-8deb-4a1a-ab0c-4443f6019f0a)

**Error from X/twitter**
![tweet400](https://github.com/freeCodeCamp/freeCodeCamp/assets/96950986/5d7dfbf4-3c07-40f9-bc22-4914c2821a78)

**Encoded URI**
![redirecturi](https://github.com/freeCodeCamp/freeCodeCamp/assets/96950986/e93957f9-0e28-413d-abab-a62e18a012a0)

### Recommended fix or suggestions

I gave a look into this issue, found following things:

- If the **_tweet a thanks_** 's content doesnt contain much encoded text then you may not get error
- Twitter redirection before login takes you to dashboard but fails to open pop up with content

**Comment by naomi-lgbt** [comment] 2023-09-18 16:44
I believe this is a twitter issue, not a freecodecamp issue

**Comment by DylanDevelops** [comment] 2023-09-18 21:31
Clicking on send a tweet works for me and doesn't have any issues.
<img width="1512" alt="Screenshot 2023-09-18 at 2 30 54 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/48571264/a100de53-2f04-4e8a-99c6-52e8a1227ab3">

Maybe you aren't logged in?

**Comment by RockyPukar1** [comment] 2023-09-20 11:10
@thatkid02   You should be logged in before you click on Tweet a thanks button. After you are logged and click tweet a thanks no issue will arise

**Comment by iminoaru** [comment] 2023-09-30 14:54
The issue extends beyond the specific article you mentioned, it appears to be affecting all articles.
This indicates a problem arising from Twitter's end.

Here's an attached screenshot.
![Screenshot from 2023-09-30 20-19-28](https://github.com/freeCodeCamp/freeCodeCamp/assets/115076922/06b56975-18fa-45b1-9405-ef43fc0659ce)

**Comment by raisedadead** [comment] 2023-11-06 13:28
Thanks for reporting this @thatkid02 - I tried the steps, and I can reproduce this with SSO accounts like Google, but the username/password (even with 2FA) logins seems to be okay.

While we see this is inconvenient, there is nothing we can do about this because the bug seems to be on X side. Chances are their URI encoding is broken. 

Going ahead and closing this, but please feel free to reach out to X support if you need further help.

**Closed by raisedadead** 2023-11-06 13:28 UTC
Labels: type: bug, status: waiting triage, platform: news

**Comment by paszkowskiDamian** [comment] 2024-08-19 14:24
changing url from `twitter.com` to `x.com` solved it for me.
