### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MikeH1990** [FreeCodeCamp/FreeCodeCamp#3163] opened 2015-09-08 14:33 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The numbers go into the right spots on the image and the 2nd checkmark still says its wrong even when i use other people's code and theirs works for them it doesnt for me.

<img src='http://i.imgur.com/nA0gfXq.png'>

**Comment by bugron** [comment] 2015-09-08 17:26
@MikeH1990 thanks for posting this issue!
This is caused by single quotes in your code, I mean: 
```javascript
$($('.slot')[0]).html(slotOne);
$($('.slot')[1]).html(slotTwo);
$($('.slot')[2]).html(slotThree);
```
Change them to double quotes and you'll be able to pass that test. This issue is actually fixed but not push to production yet.
Feel free to close this issue if your problem is solved now, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ahstro** [comment] 2015-09-08 17:26
This is a duplicate of #2522, the broader issue is being discussed in #3069.

Thank you for reporting, but please read [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug), specifically the `Have a useful title `-part of [Creating a New GitHub Issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue), to avoid future issue mishaps.

**Closed by ahstro** 2015-09-08 17:26 UTC
