### ISSUE TITLE
I dont have any objective buttons

### ISSUE THREAD

**Issue by Stinger25** [FreeCodeCamp/FreeCodeCamp#3099] opened 2015-09-05 20:33 UTC
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Stinger25** [comment] 2015-09-05 20:36
nevermind i fixed it

**Comment by bugron** [comment] 2015-09-06 03:51
Closing this issue as the problem is solved. Feel free to reopen if you still experience problems, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-06 03:51 UTC
