### ISSUE TITLE
Go to my next challenge link doesnt work in portrait mode 

### ISSUE THREAD

**Issue by AEA2002** [FreeCodeCamp/FreeCodeCamp#2554] opened 2015-08-23 03:11 UTC
Using a samsung 7 tablet
when doing challenges, "Go to my next challenge" link does not work when tablet is in portrait mode, but works fine in landscape

**Comment by benschenker** [comment] 2015-09-06 01:37
Hey thanks for posting this!

It looks like this is a duplicate of #1103, so keep an eye there for updates.

**Closed by benschenker** 2015-09-06 01:37 UTC
