### ISSUE TITLE
Contents of editor can not be reviewed by screen readers

### ISSUE THREAD

**Issue by mjanusauskas** [freeCodeCamp/freeCodeCamp#12431] opened 2017-01-08 21:17 UTC
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%20%20%20%20%20%20%20%20%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2976.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

        <h1>Hello</h1>

```
Tried both the free open source screen reader NVDA and also the commercial JAWS for Windows.
Neither screen reader is able to review the text in the editor by character, word, etc.
If you press CTRL + a to select the text then the screen readers are able to read the text.
This is currently quite unusable for blind and visually impaired screen reader users.

**Comment by Bouncey** [comment] 2017-01-08 22:30
\cc @FreeCodeCamp/moderators

**Comment by raisedadead** [comment] 2017-01-08 23:10
Yup, thanks a lot for bringing this up, we are very open to idea to make the website more accessible and supporting screen readers is an important part of this.

Opening up to community for suggestions on implementations.

**Comment by mjanusauskas** [comment] 2017-01-08 23:57
Comment from the NVDA screen reader lead developer:

**Comment by mjanusauskas** [comment] 2017-01-08 23:58
Comment from the NVDA screen reader lead developer:


This is due to accessibility problems in the code editor being used. 
These code editors choose to draw their content in a non-standard way, 
rather than using HTML contentEditable (which is the standard way to do 
editable content). Unfortunately, there's nothing we can do to support 
this; the issue needs to be fixed in the editor.
—

**Comment by raisedadead** [comment] 2017-01-09 06:48
@mjanusauskas Hey Mathew! Mind pointing us to the repo if this is opensource for raising a issue report?

**Comment by mjanusauskas** [comment] 2017-01-09 17:06
I'm not sure exactly which inaccessible editor is being used.

**Comment by raisedadead** [comment] 2017-01-09 18:05
Well we use https://github.com/codemirror/CodeMirror for the editor, but we would like to know if you could also help us with the repo for NVDA the open source screen reader to check with them as well?

**Comment by erictleung** [comment] 2017-01-09 18:05
@raisedadead this is probably it for the open source reader https://github.com/nvaccess/nvda

**Comment by raisedadead** [comment] 2017-01-09 18:05
Ah, thanks @erictleung!

**Comment by raisedadead** [comment] 2017-01-09 18:16
Okay, I don't see any issues with the repo that relates to CodeMirror specifically. I guess we should go about, opening issues in both repos, seeking assistance on this?

/cc @FreeCodeCamp/moderators

**Comment by mjanusauskas** [comment] 2017-01-09 18:30
The previous comment I shared from the NVDA lead developer came from the 
issue I opened in their repo. Their position is that there is nothing 
that can be done in the screen reader due to the non-standard approach 
being used and that the accessibility issue must be addressed in the editor.

**Comment by raisedadead** [comment] 2017-01-09 18:40
Can you help us with issue no, link, etc., we would love to understand what needs to be implemented? Without a clear technical idea of what's wrong, in the editor, it would be difficult to convince the maintainers of the editor for a fix.

Apologies, but without more info, it's tough to proceed with this, given that we would love to support as much accessibility as we can.

**Comment by mjanusauskas** [comment] 2017-01-09 18:51
The issue I reported to the NVDA screen reader developers is:

https://github.com/nvaccess/nvda/issues/6707


Thank you for anything you are able to do. I would love to be able to 
participate in Free Code Camp once the accessibility issue has been 
resolved.

**Comment by dhcodes** [comment] 2017-01-09 18:53
Some Googling led me to this: http://bgrins.github.io/codemirror-accessible/
Might be worth a look

**Comment by mjanusauskas** [comment] 2017-01-09 19:05
I'm not sure what editor is being used, or if it is helpful, but the 
experience using the html and css courses and code tests on 
www.w3schools.com was quite accessible as a screen reader user.

**Comment by raisedadead** [comment] 2017-01-09 19:12
@mjanusauskas Thanks a lot, Mathew. 

We are looking into this on priority and best of our abilities...we might be delayed a bit, but rest assured will try to come up with some fix as soon as we can... meanwhile we welcome you to check out the wiki articles on our forum at https://forum.freecodecamp.com and the video series to keep continuing with the learning.

/cc @QuincyLarson

**Comment by QuincyLarson** [comment] 2017-01-09 19:56
I just tried the CodeMirror Accessible demo that @dhcodes linked to. Supposedly it is lower-performance, though I didn't notice any slowdown when working with the ~10k line JavaScript file they had loaded in there. The largest projects I can imagine us having in a single CodeMirror text area would be maybe 1,000 lines, so I don't think the slowdown is all that bad.

This said, I'm on a desktop. 

Perhaps we should see whether we can have a button in the settings that toggles the use of CodeMirror Accessible?

CC @BerkeleyTrue @zersiax

**Comment by mjanusauskas** [comment] 2017-01-20 18:55
A very good example of how this type of thing can be made completely
accessible can be found at
https://teachaccess.github.io/tutorial/#/3

**Comment by zersiax** [comment] 2017-01-22 22:18
I like that resource, it does show a working example ...does it use contentEditable under the hood?

**Comment by mjanusauskas** [comment] 2017-01-22 22:48
I suspect so, but am not sure.
Currently the rather tedious work around I am using for each challenge is
to select all content in the CodeMirror editor > paste into NotePad++ >
make necessary edits > Select all and copy > Paste into CodeMirror editor >
 submit.
Obviously a very poor and inefficient experience for screen reader users.

**Comment by mjanusauskas** [comment] 2017-01-25 03:49
After using the mentioned tedious work around to complete the HTML, CSS 
and Bootstrap challenges I was disappointed to find that the next 
challenge of building a basic tribute web page uses CodePen.

CodePen appears to have similar major accessibility issues with it's 
editor. Very frustrating for a screen reader user.

**Comment by erictleung** [comment] 2017-01-25 05:10
@mjanusauskas we suggest Codepen for the integrated text editor and quick rendering. However, I don't think we limit it to just Codepen. To finish your project, all you need to submit is a URL to your project up and running. So feel free to use whatever hosting service to render your projects. An alternative is to use GitHub pages https://pages.github.com/.

Note for contributors wanting to help, here's a resource which may help alleviate this issue http://bgrins.github.io/codemirror-accessible/

**Comment by systimotic** [comment] 2017-01-25 12:35
I looked into this a bit. It seems like TeachAccess is using the [editor component from exerslide](https://github.com/facebookincubator/exerslide/blob/master/packages/exerslide/components/Editor.js). From what I can tell, what it's doing is copying all the content to the textarea.

Something else I ran into while working on #12828 is [CodeMirror's inputStyle option](https://codemirror.net/doc/manual.html#option_inputStyle). This allows us to switch the editor to use contentEditable. 
I thought [browser support for contentEditable](http://caniuse.com/#search=contentEd) shouldn't be an issue, but I did find [this comment on their discourse](https://discuss.codemirror.net/t/inputstyle-contenteditable-we-may-hope-for-browser-spell-checking/608/2), which states that it's buggy in old browsers. They do state that's it the default on mobile, however, and it's been working fine for us there. I think we should be fine using this option (they've had it for two years now).
The only difference I have been able to spot in my quick test is that the cursor changes colour based on the syntax highlighting.
I'm not an expert screen reader user, but from what I can tell this works fine with NVDA.

Should I submit this as a PR?

@mjanusauskas @zersiax Do you have any tips on things I should test? Would you be willing to help with QA?

**Comment by zersiax** [comment] 2017-01-25 12:40
If anyone needs another example on how this should work I just stumbled across the online Orion IDE which does a heck of a lot of what I would want from a system like this. I doubt its open source though

**Comment by zersiax** [comment] 2017-01-25 12:50
@QuincyLarson  yeah, send me a link to a sandbox where you have this running? I'll give it a whirl.

**Comment by systimotic** [comment] 2017-01-25 14:14
@zersiax Hi! I'm not sure how to deploy a sandbox version of freeCodeCamp. Maybe Quincy can get one up for you, or I'd be happy to guide you through installing it locally.

**Comment by zersiax** [comment] 2017-01-25 14:26
Either works :) I do have a node environment running, I would need to
dust it off though :)

**Comment by systimotic** [comment] 2017-01-25 14:49
@zersiax Local is probably the fasted solution 👍 Here is the shortened version of the setup guide (full guide is [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)):
1. Make sure Node v6 and MongoDB v3 are installed
2. Clone freeCodeCamp
3. Make sure MongoDB is running throughout all of this
4. Run the following commands inside the freeCodeCamp cl:
```
npm install
npm install -g gulp
npm install -g bower
bower install
cp sample.env .env
npm run only-once
gulp
```
5. Your local instance should now be running at `localhost:3000`
6. To check out my changes, stop gulp and run:
```
git remote add systimotic https://github.com/systimotic/FreeCodeCamp.git
git fetch systimotic
git checkout --track systimotic/fix/accessible-editor
```
7. Start gulp again, and you should be able to check out the changes again at localhost:3000

Oof, that was a bit more complicated than I imagined it to be.
I may have messed up, though. 😅 Feel free to message me anywhere if you run into any problems.

**Comment by mjanusauskas** [comment] 2017-01-25 19:30
Thank you for the information. I will investigate GitHub Pages as a 
possible alternative.

**Comment by mjanusauskas** [comment] 2017-01-25 19:31
Yes, I would be happy to help with testing and/ QA.

**Comment by miki123211** [comment] 2017-01-31 21:52
+1. For the time being, it would help to put a hidden instruction that only screen-readers can read that states how to deal with this issue (copy to another editor, edit there, copy back.)

**Comment by zersiax** [comment] 2017-01-31 22:00
How long do we expect this to take? You can add a .sr-only class to a
span that contains that text, but if we leave it in there for too long
someone somewhere is going to forget about it and it will be just sit
there because you guys aren't actually seeing that message :)

**Comment by mjanusauskas** [comment] 2017-02-04 03:46
I recently encountered this same issue both at CodePen.com and EdX.org

EdX appears to have an accessible solution in place and I am including 
their comments here:


We use an open source code editor called CodeMirror 
(https://codemirror.net/).  We had to make some modifications to it to 
make it work within edX Platform.  Some of those modifications included 
some accessibility improvements so the user may not have the same 
experience on other sites that use CodeMirror. Because we had to 
customize it for edX, we were not able to push our changes upstream. 
  However, CodeMirror is actively working to fix these issues, according 
to their github repository Issue tracker.  Another custom change we made 
to our fork of CodeMirror is the inclusion of screen reader and keyboard 
user-specific instructions that precede the editor in the TAB order. The 
user needs to be aware they they can hit the ESC key twice and then TAB 
to move focus beyond the editor.  This is necessary because in a code 
editor, it is very common for a user to want to insert a TAB sequence, 
and NOT move the current keyboard focus, which is what the TAB key does 
by default.

**Comment by mjanusauskas** [comment] 2017-02-05 22:14
Here is another example of a working solution to this critical issue:


https://github.com/jsbin/jsbin/issues/936

**Comment by kbekkeli** [comment] 2017-08-19 22:40
hi

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kbekkeli** [comment] 2017-08-19 22:40
_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jhomme** [comment] 2017-08-23 01:30
Hi,
I think I can follow these instructions now that I have the site set up locally. I'm pretty sure I need to follow the part that tells how to sync up this repository with mine. Is this correct? And if I do something wrong, I'm unsure how to back it out. A little anxious. :)

**Comment by jhomme** [comment] 2017-08-23 01:46
Just saw that this is the actual main issue. Since I have four screen readers, assuming I can follow the instructions to get this on my machine, I will be happy to test this. 

To cut down on the learning curve if you are interested in obtaining a screen reader to play with, please see below. And this is not meant as offensive in any way at all, but someone with site is not going to use a screen reader quickly on the first try, or even much after that, because the concepts are so foreign to you. I would be more than happy to test any accessibility issues involving anything other than color. just mention me or e-mail me. If I see the message I will make time.

For color contrast, look for a tool called Colour Contrast Analyzer, and see http://www.webaim.org for articles on how to use it.

On PC, the best screen reader and browser combination is going to be NVDA and Firefox, latest stable version. This is because NVDA is a screen reader that depends the most on the accessibility API, and Firefox is the PC browser that exposes the most pure implementatiion of the accessibility API. That's the short of that ecxplanation.

See http://www.nvda-project.org to download and set up NVDA. 

Once you have it set up, for easiest use, go into the Keyboard dialog and set the laptop layout, then go into the Browse mode dialog and turn off the checkbox for "Use screen layout."

Once you have all that taken care of, you no longer need to listen to NVDA speak to do testing with it as a sighted person. Start it up, open NVDA, choose Tools, then Speech Viewer. Park that window so that you can see the text in it and the content in your browser. Size the window as desired, and then, when you go to the web, use mostly up and down arrow keys to read line by line as if you were arrowing through a Notepad document. Watch the speech viewer window very carefully and you will see text update there. The text in the speech viewer matches what NVDA would say, if it were talking. 

All of this knowledge still will only be interesting, but not helpful to you, because honestly, you still do not know what should happen, so I would still be happy to test any accessibility fixes that I learn about here. 

Of course, this is for selfish reasons, because I want to be the first blind persn to go all the way through FCC, then I want to use that knowledge to help with accessibility for other blind deelopers, and see more of them become web developers, and help people with all types of disabilities. And who knows, I may even get a better job or make money outside my day job.

**Comment by QuincyLarson** [comment] 2017-08-23 03:48
@jhomme Thanks for the details on the screen readers you use. 

When I use the Fangs on FireFox, and visit this URL: https://www.freecodecamp.org/challenges/inform-with-the-paragraph-element

the screenreader output is:

> Page has one frame, four headings and twenty-five linksInform with the Paragraph Element vertical bar freeCodeCamp dash Internet ExplorerLinkGraphiclearn to code javascript at freeCodeCamp logoList of seven itemsbulletLink MapbulletbulletLink ForumbulletLink ContributebulletLink AboutbulletLink DonatebulletLink Sign inList endHeading level four Inform with the Paragraph Element p elements are the preferred element for normal dash sized paragraph text on websites. P is short for quote paragraph quote . You can create a p element like this colon less p greater I'm a p tag! less slash p greater Create a p element below your htwo element, and give it the text quote Hello Paragraph quote . Run tests left paren ctrl plus enter right paren Reset your codeLink Get a hint Ask for help on the forumLink Sign in so you can save your progress Create a p element. Your p element should have the text quote Hello Paragraph quote . Make sure your p element has a closing tag. EditEdit four one ​ two less hone greater Hello World less slash hone greater three less htwo greater CatPhotoApp less slash htwo greater four ​Heading level one Hello WorldHeading level two CatPhotoAppLinkLinkLink

If I'm understanding this correctly, this is the contents of the code editor as rendered by the screen reader:

> one ​ two less hone greater Hello World less slash hone greater three less htwo greater CatPhotoApp less slash htwo greater four

So this doesn't seem to be an issue for the Fangs screen reader. Are you experiencing this with all of the four screen readers or just some of them?

By the way, I applaud your ambition to become the first blind person to go all the way through freeCodeCamp! We will do what we can to help you make that goal a reality.

**Comment by jhomme** [comment] 2017-08-23 11:50
hi Quincy,

I am experiencing this with JAWS and NVDA on PC, voiceover on Mac. I am not experiencing this with VoiceOver on IOS. I don't understand why. So far I have not tried any other screen reader. I could try Narrator and TalkbBack.

On Aug 23, 2017, at 12:01 AM, Quincy Larson <notifications@github.com> wrote:

@jhomme Thanks for the details on the screen readers you use.

When I use the Fangs on FireFox, and visit this URL: https://www.freecodecamp.org/challenges/inform-with-the-paragraph-element

the screenreader output is:

Page has one frame, four headings and twenty-five linksInform with the Paragraph Element vertical bar freeCodeCamp dash Internet ExplorerLinkGraphiclearn to code javascript at freeCodeCamp logoList of seven itemsbulletLink MapbulletbulletLink ForumbulletLink ContributebulletLink AboutbulletLink DonatebulletLink Sign inList endHeading level four Inform with the Paragraph Element p elements are the preferred element for normal dash sized paragraph text on websites. P is short for quote paragraph quote . You can create a p element like this colon less p greater I'm a p tag! less slash p greater Create a p element below your htwo element, and give it the text quote Hello Paragraph quote . Run tests left paren ctrl plus enter right paren Reset your codeLink Get a hint Ask for help on the forumLink Sign in so you can save your progress Create a p element. Your p element should have the text quote Hello Paragraph quote . Make sure your p element has a closing tag. EditEdit four one ​ two less hone greater Hello World less slash hone greater three less htwo greater CatPhotoApp less slash htwo greater four ​Heading level one Hello WorldHeading level two CatPhotoAppLinkLinkLink

If I'm understanding this correctly, this is the contents of the code editor as rendered by the screen reader:

one ​ two less hone greater Hello World less slash hone greater three less htwo greater CatPhotoApp less slash htwo greater four

So this doesn't seem to be an issue for the Fangs screen reader. Are you experiencing this with all of the four screen readers or just some of them?

By the way, I applaud your ambition to become the first blind person to go all the way through freeCodeCamp! We will do what we can to help you make that goal a reality.

**Comment by zersiax** [comment] 2017-08-23 12:12
@jhomme For some reason I cannot find the comment where you explain what it is you are encountering. What seems to be the officer, problem?

**Comment by jhomme** [comment] 2017-08-23 12:56
Hi Florian,
Various screen eaders do not speak when attempting to navigate or type
in the editor on the site. They just say the word blank. They speak,
though, when selecting text.

Jim

On 8/23/17, Florian Beijers <notifications@github.com> wrote:
> @jhomme For some reason I cannot find the comment where you explain what it
> is you are encountering. What seems to be the officer, problem?
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/12431#issuecomment-324309958


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme

**Comment by zersiax** [comment] 2017-08-23 13:05
Ahh yup, that appears to be still be a problem. As you can see in this thread it has to do with CodeMirror not being accessible. Easiest way to get around it for now is to copy-paste the code into an editor like NotePad++ or EdSharp if you must :P , then make your edits, then paste it back into the fcc editor. Tedious, but it works I guess :)

**Comment by inscriptioelectronicaaustralia** [comment] 2017-12-27 22:14
I have just found an open-source HTML code editor that is fully accessible. Could the current one be replaced with this? https://pode.herokuapp.com/ For the CodePen challenges, as CodePen is not accessible, could there be alternate instructions for users of assistive technology to use this website instead?

**Comment by jhomme** [comment] 2017-12-28 02:04
Hi,
Please see the below post and the one it leads to. CodePen is doable, and improving. With constructive feedback, they will be better.

https://blog.codepen.io/2016/07/14/blind-accessibility-testers-society-guide-codepen/

On Dec 27, 2017, at 5:17 PM, inscriptioelectronicaaustralia <notifications@github.com> wrote:

I have just found an open-source HTML code editor that is fully accessible. Could the current one be replaced with this? https://pode.herokuapp.com/ For the CodePen challenges, as CodePen is not accessible, could there be alternate instructions for users of assistive technology to use this website instead?

**Comment by QuincyLarson** [comment] 2017-12-28 06:14
@zersiax Thanks for chiming in. I'm relived to hear this is just an issue with CodeMirror's accessibility, but that means we'll need to figure out a way to patch that.

@inscriptioelectronicaaustralia We will soon support building the projects right on freeCodeCamp, so CodePen's relatively inaccessible interface won't be so much of a problem. We just need to fix the issues with CodeMirror, which is an open source library we can potentially contribute to.

**Comment by inscriptioelectronicaaustralia** [comment] 2017-12-28 07:05
Quincy, it's good that the projects will soon be able to be built on Free Code Camp.

I have just looked at the Code Mirror GitHub threads pertaining to this, and they think that it is a lot of work to make this work with screen readers, so whether people contributing to this thread or them can sort out the problem will lead to a win-win situation for not only us, but also the other websites that use Code Mirror.

Looking at the situation hypothetically, are there many missing features from the Pode tool I referenced above that would affect Free Code Camp if it were to be implemented as a replacement for Code Mirror?

**Comment by JimHomme** [comment] 2017-12-28 13:43
Hi,
Expressing my sinsere appreciation for folks looking into this. I am moving toward actually finishing JavaScript right now, and can’t wait to be able to write real code that helps people, especially FreeCodeCamp.

Jim

**Comment by QuincyLarson** [comment] 2017-12-29 22:23
@inscriptioelectronicaaustralia CodeMirror is a widely-used project with tons of features that we use. I'm skeptical that Pode could do everything CodeMirror does. I think the best option is for us to patch CodeMirror.

**Comment by zersiax** [comment] 2017-12-30 00:46
Although I do agree that patching  CodeMirror is the most , let's call it effective, way of solving the problem,  we do have to stay somewhat realistic.
This issue has existed for the entirety of this year, it's a year old bar a few weeks, and I've been whining and growling about this problem for at least two, maybe even three years now. And it is a problem indeed; every single time I decide to give FCC a try again I'm put off by the sheer annoyance of having to work around these issues. The ease, low entry threshold and simplicity of coding and seeing your live preview update in the browser as you code just doesn't apply to people using screen readers at present, which is a lot of what makes freecodecamp effective and , dare I say, charming.
CodeMirror has shot itself in the foot by focusing on mainly rendering the code in a performant way graphically, almost completely relinquishing the standard DOM operation of yore. If you look around, even WordPress is suffering from this problem and they have not yet found a suitable way of getting around this; it has in fact stopped them from implementing codeMirror as WP's default WordPress editor and if that editor is indeed implemented as default, an opt-out for visually impaired WordPress administrators will need to be implemented to not completely break the admin experience for those people. CodeMirror isn't likely to get fixed any time soon.
Quickly looking at Pode, it seems to be primarily an editor for HTML and unfortunately does not come near to CodeMirror's functionality, so sadly I don't think it is feasible.
There's no simple solution to this problem, and patching is even less of a good idea looking at this issue: https://github.com/codemirror/CodeMirror/issues/4604
The only stop-gap measure I can think of is to have some way of rendering the CM content to a regular textarea and reflect the edits made into that textarea in CM, perhaps when a keydown of tab is being detected or when ctrl+enter is preseed to run code. Until CodeMirror is either fixed (which is uncertain looking at the issue referenced above but unlikely given the track record) or discarded for another , similarly featured editor, I don't think there's much more that can be done on short notice.

**Comment by inscriptioelectronicaaustralia** [comment] 2017-12-30 22:39
Quincy, I understand that CodeMirror is clearly the superior solution (I think Pode was made to be extremely simple as it was intended just for beginners), and it would be ideal to make it accessible if that is possible. The reason I asked what features Pode is lacking is that, once the text in CodeMirror edit fields can be read by screen readers, if CodeMirror uses any other visual features to assist in coding, these should also eventually be made accessible if possible.
I was thinking about other ways to tackle this issue, and I thought that someone could make some scripts for the JAWS for Windows screen reader, and/or if possible an add-on for the NVDA screen reader (VoiceOver for macOS does not allow scripting I think), that when the user entered a CodeMirror text field, the text that was already in there would be copied into a JAWS or NVDA text buffer, which could then be edited, and with a keystroke sent back to the editor. Ideally, this "special" text field would give access to any other important features that CodeMirror offers. JAWS uses a proprietary scripting language that does have the ability to make domain-specific scripts, and NVDA uses Python for making add-ons, but I am not sure if domain-specific ones can be made for that screen reader.

**Comment by QuincyLarson** [comment] 2018-01-01 04:19
@inscriptioelectronicaaustralia @zersiax @jhomme It sounds like from reading https://github.com/codemirror/CodeMirror/issues/4604#issuecomment-349920743 that @marijnh is planning to move to content editable, which should make CodeMirror significantly more usable. I commented on the issue asking whether there's anything we could do to help.

Worst case scenario, we might be able to build an "accessibility mode" that allows campers to switch from CodeMirror for Pode in the settings, thought that would be an indeterminately large amount of work. 

Let's wait and see what @marijnh has to say.

**Comment by inscriptioelectronicaaustralia** [comment] 2018-01-02 07:32
I read marijnh's response, and it seems like it might be a while until we get accessibility. One thing to also take into consideration is that unfortunately, even when people say "a few months", that is rarely the case for accessibility as it too often gets very low priority. I'm not saying that this is what the developers of CodeMirror think, but it is a very disturbing worldwide trend. I have seen examples when people say "a few months", and it turns into a few more months ... then a few more ... and I think you get the picture.
As it is still possible to use the code editor as it is, I think waiting for a few months is probably the best approach, but if we get to June and nothing has changed, perhaps looking into another solution is probably worth considering. What do others think?

**Comment by marijnh** [comment] 2018-01-02 08:54
>  I have seen examples when people say "a few months", and it turns into a few more months ... then a few more ...

No one promised anything in a few months, except that work would _start_ on a new approach, which will definitely take a while to build.

**Comment by raisedadead** [comment] 2018-01-02 10:59
Hi @marijnh 

Thanks for considering the re-archi of CodeMirror and we sincerely understand the efforts with everything being an open source effort.

Being a non-profit ourselves, please let us know, if you would need any coding assistance (pro-bono) from our community devs in this effort, we are around to help you in this effort, in any way we are able.

The battle tested knowledge of the project (and its contributors) is invaluable and hence we are dedicated  to help in this effort, should you guide us with specifics on issue logged over at the CodeMirror repo.

Hi @inscriptioelectronicaaustralia 

> ... but if we get to June and nothing has changed, perhaps looking into another solution is probably worth considering.

We sincerely understand and share the frustration, and we are prepared to dedicate efforts in any possible solution, but IMHO, helping CM become better at a11y, is the good thing to do.

I think that's an effort well spent, as we will not only be helping freeCodeCamp community, but anywhere CM is in use for greater good of a11y everywhere else as well.

**That said,** 

@zersiax analysis above is correct for the purposes of current state of our code base:

> Quickly looking at Pode, it seems to be primarily an editor for HTML and unfortunately does not come near to CodeMirror's functionality, so sadly I don't think it is feasible.

> The only stop-gap measure I can think of is to have some way of rendering the CM content to a regular textarea and reflect the edits made into that textarea in CM, perhaps when a keydown of tab is being detected or when ctrl+enter is preseed to run code. Until CodeMirror is either fixed (which is uncertain looking at the issue referenced above but unlikely given the track record) or discarded for another , similarly featured editor, I don't think there's much more that can be done on short notice.

We should start looking at implementing a interim solution, while we check with the CM team for how can we be of concrete help to them.

**Comment by marijnh** [comment] 2018-01-02 11:46
>  if you would need any coding assistance

The most useful type of contribution would be for screen-reader users and/or accessibility experts from your community to help test our new prototype, once we have it, so that issues can be spotted and addressed early on. We'll do an announcement when we have something to show—if you want to make sure you're notified, you can send me an email with contact data.

**Comment by Bouncey** [comment] 2018-01-02 13:06
@svinkle I would appreciated your input on this a11y issue.

Is the stop-gap suggested something that could work until the `content-editable` issue is resolved upstream? 

> The only stop-gap measure I can think of is to have some way of rendering the CM content to a regular textarea and reflect the edits made into that textarea in CM, perhaps when a keydown of tab is being detected or when ctrl+enter is preseed to run code. Until CodeMirror is either fixed (which is uncertain looking at the issue referenced above but unlikely given the track record) or discarded for another , similarly featured editor, I don't think there's much more that can be done on short notice.

**Comment by svinkle** [comment] 2018-01-03 04:52
If I understand the approach correctly, the CM editor content would load in a `textarea` and the `textarea` would be used to edit content. Then on update/save the `textarea` content would be reflected in the CM editor.

Would the CM editor be hidden from view? I assume there would only be the `textarea` viewable, otherwise having two editing areas would be confusing.

**Comment by raisedadead** [comment] 2018-01-03 05:58
Hi @QuincyLarson and everyone involved, 

Thanks a lot for the feedbacks and considerations, in finding a solution.

There is one more consideration that we have hit which I just happened to realise with some discussions with @BerkeleyTrue about [a separate topic on CM](#16397), before we go ahead with any of the monkey-patching with another textarea. 😓 

On beta (our new react front-end) we are not dependent on CodeMirror directly, but on a react component `react-codemirror` which is a light weight wrapper on top of CM. This is so, because we need it to work with our beta platform.

We may have to update that to a different component sometime in future, but that said none of those components in discussion have the a11y support same as in the parent CM on which wrap their functionality.

So a monkey-patch may not be trivial.

**Comment by QuincyLarson** [comment] 2018-01-09 19:37
@raisedadead Thanks for pointing this out. We will wait for CodeMirror to do their accessibility update, then evaluate the process of monkey patching from there.

**Comment by raisedadead** [comment] 2018-06-01 23:10
We are happy to announce that we have switched to [Monaco](https://microsoft.github.io/monaco-editor/) editor on our learn platform. It has a11y built in. 

We absolutely love CodeMirror and thanks to @marijnh for the awesome work that you and the team has done. Its been the de facto editor for all these years. We would still love to use it in future projects, because its just so light and simple.

Thanks @zersiax, @mjanusauskas, @inscriptioelectronicaaustralia and Everyone for chiming in and making the platform more accessible.

**Closed by raisedadead** 2018-06-01 23:10 UTC
Labels: status: blocked, ux: accessibility
