### ISSUE TITLE
[beta] Map reopens after completing a challenge

### ISSUE THREAD

**Issue by SanD94** [freeCodeCamp/freeCodeCamp#16309] opened 2017-12-23 22:23 UTC
#### Issue Description
Before each challenge I close the map part and solve the challenge. After completing it, in the new challenge, map is opened unexpectedly. I think it should be opened by the user not automatically.

#### Browser Information

* Browser Name, Version: 
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by no-stack-dub-sack** [comment] 2017-12-23 23:00
@SanD94 this is a duplicate of #16249. I went to go open the same issue and discovered both issues. Closing this in favor of the original issue.

**Closed by no-stack-dub-sack** 2017-12-23 23:00 UTC
