### ISSUE TITLE
Single quotes don't work

### ISSUE THREAD

**Issue by thomasvaeth** [FreeCodeCamp/FreeCodeCamp#3171] opened 2015-09-08 21:09 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
<img width="1440" alt="screen shot 2015-09-08 at 2 07 13 pm" src="https://cloud.githubusercontent.com/assets/10190995/9747535/ffa61854-5632-11e5-9065-8c8be9936b7e.png">
<img width="1440" alt="screen shot 2015-09-08 at 2 08 27 pm" src="https://cloud.githubusercontent.com/assets/10190995/9747556/1a00305e-5633-11e5-9144-25098dd47538.png">
Images:
Single quotes do not work, but double quotes work. From my understanding it should not matter which quotes are used.

**Comment by bugron** [comment] 2015-09-08 21:14
@thomasvaeth thanks for posting this issue!
This issue is actually fixed but not pushed to production yet. Anyway, your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2522 so I'll close it. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-08 21:14 UTC
