### ISSUE TITLE
Get A Hint Button generates 404-Page Cannot Be Found

### ISSUE THREAD

**Issue by emh1010** [freeCodeCamp/freeCodeCamp#34574] opened 2018-12-06 21:28 UTC
**Describe your problem and how to reproduce it:**
The Get A Hint Button generates a 404 error for the exercise:
Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement

<img width="430" alt="screen shot 2018-12-06 at 4 23 01 pm" src="https://user-images.githubusercontent.com/9804005/49612751-ab94a180-f973-11e8-82d8-90daf6f9226d.png">

**Add a Link to the page with the problem:**
This is the path to the exercise:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

This is the path to the 404 error:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement
**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 12.0.1
* Operating System: macOS Mojave 10.14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by demangejeremy** [comment] 2018-12-06 21:47
Can I take care of this problem? I made a pull request on a similar problem: https://github.com/freeCodeCamp/freeCodeCamp/pull/34575

**Comment by demangejeremy** [comment] 2018-12-07 19:43
Hello @emh1010. Thank you for reporting the problem. I proposed a PR to solve this problem which is in #34599.

**Comment by matkoniecz** [comment] 2018-12-09 16:53
This issue is duplicate of #29554 that can be found by searching for  https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement text

**Comment by procode200** [comment] 2018-12-10 02:02
This is an issue that isn't just on this exercise; This issue exists within about a couple dozen exercises in the JavaScript Certificate.

Hang 10 ;)

**Comment by RandellDawson** [comment] 2018-12-11 17:35
As @matkoniecz points out above, this has already been reported on an earlier issue #29554, so we are closing this issue.

Thank you.

**Closed by RandellDawson** 2018-12-11 17:35 UTC

**Comment by hungdzai** [comment] 2019-03-17 20:16
Though I was able to complete the challenge, I ran into this same issue today.

**Comment by aortiz1989** [comment] 2019-04-08 23:18
I see the issue has been closed, but I'm seeing this issue today 4/8/19

**Comment by RandellDawson** [comment] 2019-04-09 00:09
@aortiz1989 See issue https://github.com/freeCodeCamp/freeCodeCamp/issues/35155 for more information.  

FYI - You will note I commented on why this particular issue # was closed above.  It was a duplicate of one that had already been reported.
