### ISSUE TITLE
Beta - Waypoint: Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by pieterdeville** [FreeCodeCamp/freecodecamp#1553] opened 2015-08-05 12:05 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the description "button-primary" should be replaced with "btn-primary".
<blockquote>Use the addClass() jQuery function to give the element one new class for each selector: "animated", "shake", and "button-primary".</blockquote>

The first three validation also have some text issues (see screenshot):

<img width="1280" alt="screen shot 2015-08-05 at 14 04 28" src="https://cloud.githubusercontent.com/assets/13466453/9085201/0d8ea45e-3b7b-11e5-9bb7-0f1b1743211c.PNG">

**Comment by BerkeleyTrue** [comment] 2015-08-11 21:06
duplicate of #1529 
Happy Coding!

**Closed by BerkeleyTrue** 2015-08-11 21:06 UTC
Labels: Beta Site, duplicate

**Comment by haldav** [comment] 2015-08-16 18:06
I am having an issue with the #target1 id since the site was updated. It won't let me pass when I write the code as it is above. The requirement "Your #target1 element should have the classes animated‚ shake and btn-primary." goes unchecked. Any ideas?

**Comment by Ohillio** [comment] 2015-08-17 21:15
Same issue. I suspect there might be a problem with the test, have to go back and look though, I just kept moving after the error.

**Comment by danrhumphries** [comment] 2015-08-19 03:12
![image](https://cloud.githubusercontent.com/assets/13267128/9347947/3d05d120-45e5-11e5-865f-9866cd96136f.png)

The challenge seems to be contradicting itself. It asks you to add one each class using the different selectors but also asks you to have #target1 id have all 3. Can't seem to get all checkmarks no matter how I go about it.

**Comment by Ohillio** [comment] 2015-08-19 03:22
Try using "button-primary" instead. I read somewhere that the test code was
searching for "button" and not ".btn" Not sure if or when it was fixed.

**Comment by nardmacmke** [comment] 2015-08-19 03:33
I have run into the same problem here.  I would attach a screenshot, but now I can't connect to the site.  I tried the suggestion of using the "button" over "btn" even though it was fixed, and still didn't get my #target1 checked green.  I was going to head to the next lesson, see what code is there, and try and reproduce it back into this lesson.  But I can't connect for whatever reason at the moment.

**Comment by nardmacmke** [comment] 2015-08-19 03:50
GOT IT!!! They missed a space between the first two words (animated and shake)  Here is a screen shot. get your check and keep on trucking!! 

![image](https://cloud.githubusercontent.com/assets/13856495/9348369/716f0c7c-45fb-11e5-95e2-10537b28adc0.png)

**Comment by txguy87** [comment] 2015-08-19 04:04
I think they have corrected the error, I just tried "animatedshake" (with and without the space in between) and it accepted it.

**Comment by IamArtemis** [comment] 2015-08-19 12:10
Hi there, I'm having the same issue. I've tried all the above but can't get it..Here is the code: 
$("button")addClass("animated shake btn-primary");
$(".btn")addClass("animated shake btn-primary");
$("#target1")addClass("animated shake btn-primary");
I would appreciate any help.

**Comment by nardmacmke** [comment] 2015-08-19 12:48
Hello Diane!

I'm not in front of my laptop at the moment, but wanted to quick respond to you with what I found last night. 

I skipped to the next lesson to see if the proper code was listed, as that is sometimes the case.  It looked different but I cut and pasted it anyways, but of course didn't work.
I began to play with the #target1 line with those 3 words. I played with spacing, and stumbled upon it. But, in trying to recreated it, it wouldn't work again. I managed to get a screenshot though, and I have it on github and can forward you the link later this morning.

The thing I found was they missed a space between "animated" and "shake", so my #target1 line at the end looked like this

("animatedshake btn-primary")

I hope it works for you, and I will be online later this morning and find the screenshot for you if you would still like it.




Sent from my Samsung Epic™ 4G

Diane Primpas <notifications@github.com> wrote:

Hi there, I'm having the same issue. I've tried all the above but can't get it..Here is the code: 
$("button")addClass("animated shake btn-primary");
$(".btn")addClass("animated shake btn-primary");
$("#target1")addClass("animated shake btn-primary");
I would appreciate any help.

**Comment by nardmacmke** [comment] 2015-08-19 22:27
Here is the screen shot.  sorry it took so long.

**Comment by taraleeyork** [comment] 2015-08-20 15:57
I am having issues with them test as well.

**Comment by dev-diva** [comment] 2015-09-05 21:08
Try separating your classes for target1 with commas.  This worked for me:
$("#target1").addClass("animated, shake, btn-primary");

![fcc waypoint 105](https://cloud.githubusercontent.com/assets/10245306/9701301/b450bd26-53f0-11e5-9ba8-a1ec07a9b428.png)

**Comment by Jumpingjoly** [comment] 2015-10-16 14:25
here is what worked for me and what didn't work also...
![2015-10-16 15_23_18-windows shell experience host](https://cloud.githubusercontent.com/assets/12158968/10544215/14c6aabe-741a-11e5-835b-72d99521332d.jpg)

**Comment by tolgazafer74** [comment] 2016-02-28 01:01
You already target your #target1 by type button and class .btn , you don't have to write all to class of #target1 - just write btn-primary for it but as far as I see you have problems for punctutation. Use " not ' . That will solve your problem. Here is the code;
  $("button") .addClass("animated");
     $(".btn") .addClass("shake");
     $("#target1") .addClass("btn-primary");

**Comment by flyingpopdesign** [comment] 2016-03-20 10:51
Thaks @tolgazafer74
it works

**Comment by diana8** [comment] 2016-07-04 02:26
@tolgazafer74 - your suggestion worked for me as well, but it seems utterly inconsistent with the instructions.

**Comment by geraldinejns** [comment] 2016-07-06 02:16
worked for me as well.

**Comment by geraldinejns** [comment] 2016-07-06 02:16
deeeeeeeeeeeeeeeeeeeaaaaaammmm.
