### ISSUE TITLE
Pass test even with typing error

### ISSUE THREAD

**Issue by Dean-Foulds** [FreeCodeCamp/FreeCodeCamp#8137] opened 2016-04-15 15:38 UTC
Test allowed me to pass even though I had a typo on paragraph tag.

![2016-04-15 1](https://cloud.githubusercontent.com/assets/8842064/14566687/7a0d664a-0328-11e6-98b3-9ae8d5fae234.png)
![2016-04-15](https://cloud.githubusercontent.com/assets/8842064/14566691/7e446074-0328-11e6-9863-15ef7cdde1a2.png)

#### Browser Information

- Browser Name, Version: 
- Operating System: 
- Mobile, Desktop, or Tablet: 
#### Your Code

``` js
// If relevant, paste all of your challenge code in here

```

**Comment by theflametrooper** [comment] 2016-04-15 15:43
@Swiss-banker That's confirmed to be an issue! Can you update your issue description to include the link to a challenge and remove any unrelated sub-headings! Thanks :+1:

**Comment by Dutch5371** [comment] 2016-04-16 18:03
The issues are obvious please remove unrelated issues with unrelated headings

**Comment by rogaps** [comment] 2016-04-17 14:31
Please see [https://www.w3.org/TR/html5/syntax.html#parsing-main-inbody](url) and find for `An end tag whose tag name is "p"`. It says: 

> If the stack of open elements does not have a p element in button scope, then this is a parse error; insert an HTML element for a "p" start tag token with no attributes.

If you have `p` end tag without start tag, `p` start tag will be created for you.
I suggest that we also test whether the `p` element contains some text, because it is also semantically correct.

**Comment by erictleung** [comment] 2016-04-25 15:16
Possibly duplicate of #5533

**Comment by Bouncey** [comment] 2016-06-01 22:51
The challenge passing in this way represents what would happen in the 'real world' with regards to an automatically inserted `<p>` tag.

The editor used already has HTML lint-ing, and as shown in your screen-grab, has shown that there is an error in the syntax. It would be unreasonable to create `assert` tests for each HMTL challenge to check for what the HTML lint is already checking for.

**Closed** 2016-12-01 21:39 UTC
Labels: decayed
