### ISSUE TITLE
Learning CSS Variable By Building A City Skyline - Step 15

### ISSUE THREAD

**Issue by DHCJS** [freeCodeCamp/freeCodeCamp#47579] opened 2022-09-21 11:38 UTC
### Describe the Issue

Please kindly check below the instruction.

I've confirmed with the admin about this typo issue, but this is my first time using GitHub and pardon me if this comes out not correct.

I think the Add Variable should be --building-color1 without a dash (-) between color and 1 because that is what we coded for the last time.

Looking forward to the admin acknowledging it. Thank you!
![image](https://user-images.githubusercontent.com/80773310/191492668-738153dd-ba0a-4ccd-9c8a-e8c2020a63be.png)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-15

### Steps to Reproduce

Additional dash (-) between color and 1 which is not right

### Recommended fix or suggestions

Deleting the dash (-) between color and 1

### Screenshots

![Untitled design](https://user-images.githubusercontent.com/80773310/191494449-d4d8dcde-88b2-4342-98b4-df9b31827f60.png)

**Comment by ShaunSHamilton** [comment] 2022-09-21 11:59
To clarify, the issue is `--building-color-1` needs to be changed to `--building-color1`:

```diff
- --building-color-1
+ --building-color1
```

**Comment by ShaunSHamilton** [comment] 2022-09-21 12:00
An issue with the _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by DHCJS** [comment] 2022-09-21 13:49
Should I close this issue and create a new PR instead?

**Comment by Harry262530** [comment] 2022-09-21 15:05
--building-color-1 needs to be changed to --building-color1;

**Closed** 2022-09-21 16:18 UTC
Labels: type: bug, first timers only
