### ISSUE TITLE
Run Code Button -Dead

### ISSUE THREAD

**Issue by genesisjoec** [FreeCodeCamp/FreeCodeCamp#3005] opened 2015-09-02 22:34 UTC
Challenge http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm  hitting the 'run code' button and it does nothing. I've tried refreshing the page and same response. I can't progress past this challenge because of this.If in fact I have a syntax error, there needs to be some pop up telling me so, otherwise I have no idea.

**Comment by genesisjoec** [comment] 2015-09-02 22:34
![capture](https://cloud.githubusercontent.com/assets/11507581/9646400/db3425fe-5198-11e5-84c3-9e856d95ae0f.JPG)

**Comment by bugron** [comment] 2015-09-03 12:38
@genesisjoec thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2979
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2906
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-03 12:38 UTC
