### ISSUE TITLE
"Oops! Something went wrong. Please try again later" error on submitting already completed challenges

### ISSUE THREAD

**Issue by lgp171188** [FreeCodeCamp/FreeCodeCamp#6901] opened 2016-02-11 18:42 UTC
Please see the attached screenshot
![fcc error](https://cloud.githubusercontent.com/assets/218870/12986435/41dbf09e-d11d-11e5-9247-b9f95f9806ef.png)

Once this error appears even when I try to navigate to the home page, it redirects to the same page with the error.

**Comment by raisedadead** [comment] 2016-02-11 18:56
Confirmed.

![err](https://cloud.githubusercontent.com/assets/1884376/12986760/0b4856a6-d11f-11e5-84cf-fc6998c848cd.PNG)

Absolutely no errors on the console or network tabs.
Reproducible on all browsers.

**Comment by codeineart** [comment] 2016-02-11 18:58
Possible server overloading...?

**Comment by raisedadead** [comment] 2016-02-11 18:59
Looks like it.

**Comment by cannelflow** [comment] 2016-02-11 19:04
![klo](https://cloud.githubusercontent.com/assets/12219251/12987019/3653a692-d120-11e5-8a5d-e1e1e2934435.PNG)
![jj](https://cloud.githubusercontent.com/assets/12219251/12987058/6522f2ca-d120-11e5-838c-6368cddb563b.PNG)

**Comment by ltegman** [comment] 2016-02-11 19:13
This was due to our maintenance and should be resolved now. Please let me know if you are still experiencing this issue or not.

**Comment by codeineart** [comment] 2016-02-11 19:14
Ok. Thanks for clarifying it.

**Comment by raisedadead** [comment] 2016-02-11 19:16
@ltegman Resolved! :+1: 
BTW what did you do, even github loads slower than FCC now :wink:

**Comment by ltegman** [comment] 2016-02-11 19:18
@BerkeleyTrue worked some DB magic :sparkles: Closing as resolved, but don't hesitate to comment on this issue if the problem crops back up!

**Closed by ltegman** 2016-02-11 19:18 UTC

**Comment by danielkoller** [comment] 2016-02-15 20:30
I'm still experiencing this problem unfortunately..

**Comment by mdelgadonyc** [comment] 2016-03-13 22:40
Every time I visit FCC by going directly to www.freecodecamp.com it directs to www.freecodecamp.com/map and the error message "Oops! Something went wrong. Please try again later" appears as in the screenshot provided by @lgp171188 except it appears once (and not twice like in the screenshot). This happens both from my Fedora Linux desktop and my Chromebook.
