### ISSUE TITLE
"animated bounce" class instruction is not correct

### ISSUE THREAD

**Issue by rosemariel** [FreeCodeCamp/FreeCodeCamp#7706] opened 2016-03-23 15:36 UTC
#### Issue Description
Instructions say to apple the "animated bounce" class with double quotes but it should be single quotes. Otherwise, you get an error message.

#### Browser Information
* Google Chrome
* Windows 7

**Comment by raisedadead** [comment] 2016-03-23 15:44
@rosemariel I am unsure how is that an issue?
Are you getting any errors? Which challenge is this related to?

Is it [Target HTML Elements with Selectors Using jQuery](https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery) ?

Please elaborate.

**Comment by rosemariel** [comment] 2016-03-23 15:50
Yes, that's correct. I was getting an error and now it's been resolved so I
cannot replicate the issue. Oddly enough, the IDE replaces my single quotes
with double quotes for the add class behavior each time I go to the next
challenge.

My co-worker who is also doing FCC with me had the same issue.

**Comment by raisedadead** [comment] 2016-03-23 16:00
> Oddly enough, the IDE replaces my single quotes
with double quotes for the add class behavior each time I go to the next
challenge.

The IDE never stored your code from the previous challenge, each challenge has some code pre-filled in the code editor (related to the challenge). I agree that it should be giving you a illusion that your code is being carried forward but its actually not the case.

However, using double or single quotes either is okay for these challenges.

Closing as not a bug.

Thanks and Happy coding!

**Closed by raisedadead** 2016-03-23 16:00 UTC
Labels: blocked
