### ISSUE TITLE
Position where cursor clicked when starting a new level does not actually match where cursor is then placed

### ISSUE THREAD

**Issue by thpracticeweb** [FreeCodeCamp/FreeCodeCamp#9607] opened 2016-07-07 23:14 UTC
#### Challenge Name

All challenges are affected.

#### Issue Description

When you finish a level and then start a new one and click a position in the editor, often the cursor will appear to be in the correct position but actually will be one line below when one types a character. 

Arrow key navigation also is not working as expected until said character is typed, as the cursor jumps to and from the next line at positions that do not match the natural line breaks of the text. This behavior can be seen by holding the left or right arrow keys after the above first click.

#### Browser Information

* Browser Name: Firefox, Version: 47.0.1
* Operating System: Windows 10
* Desktop

**Comment by raisedadead** [comment] 2016-07-08 09:40
Closing as duplicate of #7847 
Please search issues before reporting.

**Closed by raisedadead** 2016-07-08 09:40 UTC
Labels: duplicate
