### ISSUE TITLE
Accessibility: Windows and Mac: Screen Reader Will Not Speak the Edit Box in the Code Window

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#15638] opened 2017-07-13 00:47 UTC
#### Issue Description

For all challenges, when a screen reader user enters the code window and presses any navigation key, such as arrows, PageUp, PageDown, etc., the screen reader says the word blank. The only way for a screen reader user to work with code is select all of the code, have a text editor on the computer ready to receive the code, paste, alter code, select all, copy or cut to clipboard, go to the site, and paste.

Platforms tried so far, Windows 10 with NVDA and Firefox, and Mac, using VoiceOver and Safari.

Interestingly, both set-ups speak the selected text in the edit window on the site before the user puts it on the clipboard.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by systimotic** [comment] 2017-08-19 22:06
@jhomme Thank you for reporting this issue! We have already noticed this and have been working on a fix in https://github.com/freeCodeCamp/freeCodeCamp/issues/12431

I think I can open a PR with a fix, but I need a screen reader user to test it first. Would you be willing to help with that? Instructions on how to test are here: https://github.com/freeCodeCamp/freeCodeCamp/issues/12431#issuecomment-275126985
If you could give me specific instructions on how I can test this myself, that would be great too.

I'm closing this issue as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12431 If you have any further input, please add it there. Happy coding!

**Closed by systimotic** 2017-08-19 22:06 UTC
Labels: accessibility
