### ISSUE TITLE
problem in html 5 

### ISSUE THREAD

**Issue by vanshdeepsingh1** [FreeCodeCamp/FreeCodeCamp#6800] opened 2016-02-07 09:58 UTC
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%7D%0A%20%20p%7Bfont-size%3A16px%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%2Cclass%3D%22p%22%20%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%20%2C%20class%3D%22p%22%3Epurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%20%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched%20%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;}
  p{font-size:16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text",class="p" >Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text" , class="p">purr jump eat the grass rip the couch scratched sunbathe , shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched </p>
```

**Comment by Greenheart** [comment] 2016-02-07 10:07
@vanshdeepsingh1 This doesn't seem to be a bug.

If you want help, you can go to any of the help-chatrooms in this list - [Official Free Code Camp Chatrooms](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Official-Free-Code-Camp-Chat-Rooms) where you'll find plenty of campers that want to help you!

Good luck and happy coding! :smile:

**Comment by cannelflow** [comment] 2016-02-07 10:09
@vanshdeepsingh1  agreed this is not a bug before reporting bug you should first ask at FCC chat room

**Comment by AkiraLaine** [comment] 2016-02-07 10:26
Closing this as this is not an issue

**Closed by AkiraLaine** 2016-02-07 10:26 UTC
