### ISSUE TITLE
Add additional unit test for Friendly Date Ranges.

### ISSUE THREAD

**Issue by planigan** [FreeCodeCamp/FreeCodeCamp#7873] opened 2016-04-03 23:28 UTC
`makeFriendlyDates(["2018-07-01", "2018-07-04"]);`

My solution, which I fixed for this test, originally returned` ["July 1st", "4th"]`, and passed all tests. I doubt that you want these dates formatted without a year when they occur in future years.

**Comment by erictleung** [comment] 2016-04-04 00:18
I don't think there needs to be any changes. The purpose of the challenge is just to put the date ranges in a friendlier/more readable format. If you were to account for current date, the answer would change per day. Maybe on a production system, you may want to check for that. Your code works and even the example you've given follows what was asked for:

> If the range ends in the same month that it begins, do not display the ending year or month.

Thanks for the issue but I'm closing the issue as it is not a bug on the site. Happy coding!

**Closed by erictleung** 2016-04-04 00:18 UTC

**Comment by planigan** [comment] 2016-04-04 00:21
Actually, it does not fulfill that line you quoted. It specifies ending year an month. It does not say to omit the starting year. No matter, just thought I would point that out.
