### ISSUE TITLE
Map is blank in Safari 8.0.8 

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6699] opened 2016-02-03 10:45 UTC
![](https://www.evernote.com/l/AqQQYulRD99Btps2JPAHudAfzs4SuGYw8-EB/image.png)

**Comment by bugron** [comment] 2016-02-03 10:50
@QuincyLarson any errors in browser's console? Is everything OK on Networks tab?

**Comment by bugron** [comment] 2016-02-16 05:50
Thanks for posting. Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256.

**Closed by bugron** 2016-02-16 05:50 UTC
