### ISSUE TITLE
Projects tests are broken

### ISSUE THREAD

**Issue by crossphoton** [freeCodeCamp/freeCodeCamp#39174] opened 2020-07-03 05:25 UTC
**Describe your problem and how to reproduce it:**

Submit any link in the submission and it'll accept it and this is not on the dev website. Happening on all courses after the Python courses are live. I was able to claim all the certificates.

**Add a Link to the page with the problem:**

All the courses projects. (I tried Data Vis., ML, Data Analysis, Quality Assurance, Scientific Computation, Information Security, Front-End Libs.)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 83
* Operating System: Windows and Android both

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot (120)](https://user-images.githubusercontent.com/38404790/86434257-a26be200-bd1a-11ea-812d-e55752c22b36.png)
![Screenshot (121)](https://user-images.githubusercontent.com/38404790/86434261-a435a580-bd1a-11ea-8651-8f7baa375501.png)

**Comment by raisedadead** [comment] 2020-07-03 05:54
This is known and users are expected to follow the Academic  honesty policy:

Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/37185

/cc @freeCodeCamp/staff

**Closed by raisedadead** 2020-07-03 05:54 UTC
Labels: scope: learn, status: needs help for triage
