### ISSUE TITLE
Ctrl + Enter bug

### ISSUE THREAD

**Issue by knox97** [FreeCodeCamp/FreeCodeCamp#9986] opened 2016-07-29 18:59 UTC
<h1>Is good old Ctrl + Enter getting tired?</h1>
#### Challenge Name

This is on JSON challenges that use button to write a message, maybe on others too
<b>It happend to me on the following challenges</b> (but i haven't yet tryed on others)
Change Text with Click Events Complete
Get JSON with the jQuery getJSON Method Complete   *
#### Issue Description

Here is whats going on, once you solve a challenge and hit Ctrl + Enter to submit and see if its correct if its correct you will get a message that you have passed with some cool text in the header but if you click on X to close that little pop up window and click a button that changes the content of your little iPhone look alike on the right or bottom depending on the device you are using then try Ctrl + Enter after that the window wouldn't pop-up

### Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
* Browser Name, Version: <em>Above</em>
* Operating System: <em>Above</em>
* Mobile, Desktop, or Tablet: I'm not sure if they have the same fature there somehow

#### Your Code

```js
 
```

**Comment by BKinahan** [comment] 2016-07-29 22:11
Hi @knox97, thanks for reporting this.

If I'm understanding you correctly, the issue is that the `Ctrl+Enter` shortcut doesn't trigger the expected behavior of running the tests if you click inside the mobile preview.

This isn't limited just to challenges with the mobile preview. In fact, if you click outside of the code editor on any challenge, it will lose focus and its shortcuts won't be functional. (See also the new "toggle comment" shortcut `Ctrl+/` or `Cmd+/`)

I don't think there's an easy way to make such shortcuts global in the browser, and it could be that users have their own shortcuts with the same key bindings that have different behaviors when the editor is not in focus, so this probably won't be changed.

As a workaround, make sure to click inside the editor whenever you want to submit code with the shortcut, or with only the keyboard you can use `Shift+Tab` to return focus to the editor after clicking within the mobile preview (you might have to use `Shift+Tab` multiple times).

**Comment by BKinahan** [comment] 2016-07-30 10:33
I'm going to close this issue for the reasons described above, but if you have more information to add or if I have misunderstood your initial report, please add another comment. Thanks again @knox97 and happy coding!

**Closed by BKinahan** 2016-07-30 10:33 UTC
