### ISSUE TITLE
Add Borders Around your Elements - not passing

### ISSUE THREAD

**Issue by diomed** [FreeCodeCamp/FreeCodeCamp#12057] opened 2016-12-15 15:18 UTC
#### Add Borders Around Your Elements

http://bit.ly/2gOUfF3

#### Issue Description
Code is not passing, even though it's correct

#### Browser Information

* Browser Name, Version: Vivaldi
* Operating System: Windows
* Desktop

#### Your Code

```
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
  .thick-green-border{
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

```
####

**Comment by texas2010** [comment] 2016-12-15 15:29
@diomed, try reset it and write it again.
I found a problem.  there has an issue with ` &nbsp;` in the code editor. that cause your code won't get passed. test realize it as not pass. sorry about that.

**Comment by raisedadead** [comment] 2016-12-15 15:34
Closing.

**Closed by raisedadead** 2016-12-15 15:34 UTC

**Comment by dhcodes** [comment] 2016-12-15 15:36
this is a duplicate of others, including https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11324

We should try to address it if possible. I asked in that thread if it's broken on staging, but will wait to hear back.

**Comment by texas2010** [comment] 2016-12-15 15:38
@dhcodes, someone did fix it. https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11472

**Comment by diomed** [comment] 2016-12-15 15:51
when are all these changes finally be applied to live FCC page???

**Comment by dhcodes** [comment] 2016-12-15 16:44
@diomed when they're ready :)

**Comment by eriksandall** [comment] 2016-12-23 21:56
Please apply the fix.
