### ISSUE TITLE
REMINDER: sync solutions after the floodfest is over

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#34609] opened 2018-12-08 20:34 UTC
Some of the hacktoberfest PRs added missing solutions to various challenges. Most were limited to a single language, not always English. So after the review is over, a cross-check between the languages is in order to copy over missing solutions to analogous challenges.

**Comment by matkoniecz** [comment] 2018-12-10 15:52
There is a script that will do it automatically, right?

**Comment by lynxlynxlynx** [comment] 2018-12-10 16:16
No idea, but I don't see anything relevant under tools/ .

**Comment by moT01** [comment] 2019-05-05 22:00
Is there any way to accomplish this? Have the translators go through them all? What we need is a way to translate from english to all the other languages automatically so we can keep the english versions of everything updated, and then just translate everything from time to time. Not sure how well that would work.

**Comment by RandellDawson** [comment] 2019-05-05 22:34
> What we need is a way to translate from english to all the other languages automatically so we can keep the english versions of everything updated, and then just translate everything from time to time. Not sure how well that would work.

With the current current challenges, we no longer have to worry about this, because they are never going to be seen on the site.  The next generation curriculum will supposedly be translated, but will run into the same issue that the last one did. 

We could easily set up an automatic machine translation of an English curriculum challenge to all 5 languages, but those translations would need to be placed on individual PRs (which can also be automated).  The problem is, if the non-English version of the challenge had already gone through many corrections through various PRs, then a new translation would wipe out the corrections made to the non-English challenge again and more PRs would need to be created by users to fix things that were already broke.   I @beaucarnes already had a PR a while back which can auto-translate and probably does not translate code sections, so adding solutions would not be a problem, but any other section would be touched.

I believe this current issue can be closed as we are no longer expecting the current curriculum challenges to make it into production.  See https://github.com/freeCodeCamp/freeCodeCamp/pull/35921 which no longer mentions the need to translate the challenge files.

**Note:** This does not affect the Guide articles as they have already diverged from the original versions so much, that there is no turning back.

**Comment by moT01** [comment] 2019-05-05 22:49
> we no longer have to worry about this, because they are never going to be seen on the site. 

You can reopen this if you want to keep the reminder up @lynxlynxlynx. But I don't think it's necessary.

**Closed by moT01** 2019-05-05 22:49 UTC
Labels: scope: curriculum, status: blocked, status: discussing

**Comment by lynxlynxlynx** [comment] 2019-05-06 06:45
#34955 would solve it, but I guess that one is almost obviated now too.
