### ISSUE TITLE
[beta][UX] New challenges should include a page/anchor jump

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13225] opened 2017-02-07 18:34 UTC
There is not enough indication that a change has occurred, after completing a challenge.

current challenge:
![screen shot 2017-02-07 at 10 31 57 am](https://cloud.githubusercontent.com/assets/7606025/22705545/b88f33f2-ed20-11e6-97a9-4f45747d4fd9.png)

next challenge:
![screen shot 2017-02-07 at 10 32 07 am](https://cloud.githubusercontent.com/assets/7606025/22705548/bce74f8e-ed20-11e6-8bae-c62d1509a8bb.png)

I suggest adding a **page jump** in the instructions panel, so that students can see a new Title and introduction for the challenge.

**Comment by raisedadead** [comment] 2017-02-07 18:52
There is a notification to address this already: 

> Your next challenge has arrived.

**Comment by Bouncey** [comment] 2017-02-07 19:15
@raisedadead the issue is that there is not enough of an indication that the next challenge has arrived. In a previous version of beta, the instruction panel (<SidePanel />) scrolled to the top when the challenge instructions changed. This functionality seems to have been removed. I would welcome it back

**Comment by tommygebru** [comment] 2017-02-07 19:38
@raisedadead i think that the notification only exists because of the issue I raised...
I have suggested other issues as well to help with the UX of the challenges like changing the nature of the notification itself and removing the modal window...

#13222 

and

#13203

**Comment by Bouncey** [comment] 2018-02-28 14:15
Closing as resolved in staging

**Closed by Bouncey** 2018-02-28 14:15 UTC
Labels: beta, enhancement, status: resolved in staging, ux
