### ISSUE TITLE
Failed test, Cannot read property 'length' of null when spacing encountered in solution

### ISSUE THREAD

**Issue by karn09** [FreeCodeCamp/FreeCodeCamp#2152] opened 2015-08-19 03:39 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-override-all-other-styles-by-using-important has an issue.

If there is a space between "!important" and ";" test will return:
```
Cannot read property 'length' of null
```
Having a space between last character and ";" on other lines do not provide a failed test case.
```
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink !important ;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>
```

**Comment by karn09** [comment] 2015-08-19 03:50
Issue appears to be with test assertion regex under https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json

Original:
```
"assert(editor.match(/pink.*\\!important/gi) && editor.match(/pink.*\\!important;/gi).length > 0, 'Your <code>pink-text</code> class should have the <code>!important</code> keyword to override all other declarations.')",
```

Proposed change:
```
"assert(editor.match(/pink.*\\!important/gi) && editor.match(/pink.*\\!important/gi).length > 0, 'Your <code>pink-text</code> class should have the <code>!important</code> keyword to override all other declarations.')",
```

**Comment by benschenker** [comment] 2015-08-28 04:27
Hey thanks for posting and doing some of that legwork @karn09!
It looks like someone beat you to it though, this is a duplicate of #2099.  I'll close this but follow the updates there.

**Closed by benschenker** 2015-08-28 04:27 UTC
Labels: confirmed, Discussing, Test Improvement

**Comment by karn09** [comment] 2015-08-28 19:45
Thanks for the note! Did not notice the duplicate.
