### ISSUE TITLE
RWD: Possibly too terse challenge step

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46186] opened 2022-05-28 00:18 UTC
### Describe the Issue

I feel like introducing two pseudo-class selectors without explaining anything might be a bit too terse. I have seen a few campers mistake the `of-type` part of the `:last-of-type` selector as something that should be replaced by the selector type. This isn't totally unreasonable considering the selector isn't explained and a complete example isn't given.

If it is the first time you see either of the selectors, not to mention both of them combined, it might be a little too terse an introduction (I should say I'm not sure if they have been introduced before this challenge).

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-41

### Your code

```

```

### Expected behavior

A complete example of the  `:last-of-type` selector with a "type" in front of it. It can still be in the hint.

Some more information about each selector would be nice but I realize that would make the text a lot longer. One option might have been to create another step that first introduced the  `:last-of-type` selector and then in the following step combined with the use of the `:not()` selector. I didn't really think of an exact example of how this might be done but I'm sure it would be possible.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum posts
https://forum.freecodecamp.org/t/not-last-fieldset-question/508578
https://forum.freecodecamp.org/t/not-last-of-type-in-style-css/512315

**Comment by jeremylt** [comment] 2022-05-28 18:27
Related to this issue?
https://github.com/freeCodeCamp/freeCodeCamp/issues/46003

**Comment by moT01** [comment] 2022-05-30 23:02
Yes, this is a duplicate of that one. We can close this and continue the conversation there.

**Closed by moT01** 2022-05-30 23:02 UTC
Labels: scope: curriculum, status: waiting triage
