### ISSUE TITLE
I think I've done right, but I can't pass this course.

### ISSUE THREAD

**Issue by AndreiLuca99** [FreeCodeCamp/FreeCodeCamp#12011] opened 2016-12-12 14:00 UTC
Challenge [DNA Pairing](https://www.freecodecamp.com/challenges/dna-pairing#?solution=%0Afunction%20pair(str)%20%7B%0A%20%20var%20ans%20%3D%20new%20Array(str.length)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(str%5Bi%5D%3D%3D%3D%27C%27)%20ans%5Bi%5D%3D%5B%22C%22%2C%22G%22%5D%3B%0A%20%20%20%20if%20(str%5Bi%5D%3D%3D%3D%27G%27)%20ans%5Bi%5D%3D%5B%22G%22%2C%22C%22%5D%3B%0A%20%20%20%20if%20(str%5Bi%5D%3D%3D%3D%27T%27)%20ans%5Bi%5D%3D%5B%22T%22%2C%22A%22%5D%3B%0A%20%20%20%20if%20(str%5Bi%5D%3D%3D%3D%27A%27)%20ans%5Bi%5D%3D%5B%22A%22%2C%22T%22%5D%3B%0A%20%20%7D%0A%20return%20ans%3B%0A%7D%0A%0A%0Apair(%22ATCGA%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function pair(str) {
  var ans = new Array(str.length);
  for (var i = 0; i < str.length; i++) {
    if (str[i]==='C') ans[i]=["C","G"];
    if (str[i]==='G') ans[i]=["G","C"];
    if (str[i]==='T') ans[i]=["T","A"];
    if (str[i]==='A') ans[i]=["A","T"];
  }
 return ans;
}


pair("ATCGA");

```

**Comment by raisedadead** [comment] 2016-12-12 14:08
@AndreiLuca99 thanks for the issue.

If you reset, the code on the editor:
```js
function pairElement(str) {
  return str;
}

pairElement("GCG");
```

The function name is `pairElement`.

- Did you happen to change the name?
- Did you solve this earlier (before we updated the function name), and visited your solution recently.
- Did you copy this from anywhere where it may have had the older name.

If any of the above is true, then the challenge wont pass.
Its mentioned in the test cases on the left that the tests are looking for `pairElement`.

Just update your solution and you should be good.

Closing as not a bug with the codebase. Please reachout to help chat for support with solutions. Thanks and happy coding.!

**Closed by raisedadead** 2016-12-12 14:08 UTC
