### ISSUE TITLE
Bonfires/challenges/waypoints infinite bouncing on scroll.

### ISSUE THREAD

**Issue by macbem** [FreeCodeCamp/FreeCodeCamp#7002] opened 2016-02-14 15:57 UTC
When I scroll when I'm on the top/bottom of a challenge/bonfire/waypoint page, the website tries to 'bounce' me back into the viewport, but it's too small and it keeps scrolling up and down until refreshed.

**Comment by hallaathrad** [comment] 2016-02-15 16:06
Hey @noczesc. Can you please provide us more information?
Please post a screen capture of the issue and hopefully your system specs?

[This link](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) may be able to help you help us help you in the future :+1: 

Let's get your issue fixed!

**Comment by noczesc** [comment] 2016-02-15 20:58
https://github.com/noczesc/FCC-issue-reproduction - a link to a recording showing the issue. I scrolled a little bit at the beginning, then in the middle of the video I scrolled back and it stopped the issue (usually it doesn't), then I fired the bug up again. I'm running an AMD x4 9650 (4x2.3GHz, not overclocked), 3gb of ddr2 ram and Nvidia 9800 GT 1gb on Ubuntu LTS with propietary GPU drivers. The issue occurs also on Windows - I've tested it in Firefox, Chromium and Chrome.

**Comment by bugron** [comment] 2016-02-16 05:04
@noczesc GitHub is a file sharing service now, nice ;) @hallaathrad any ideas why is this happening? @noczesc are you able to reproduce this issue on other computers?

**Comment by hallaathrad** [comment] 2016-02-16 15:40
@noczesc, very clever way to show us the issue! thanks!
I'll be working on this tonight when I get back home to my windows machine (currently on my MBP I cannot replicate it)

**Comment by noczesc** [comment] 2016-02-16 16:18
@bugron I don't have access to other machines, but since I tested it on two operating systems and on multiple browser, the issue seems to be legit and not related to my hardware. @hallaathrad notify me if you need more help.

**Comment by hallaathrad** [comment] 2016-02-16 16:28
@noczesc I shall :) thanks. I'm simply not near an affected machine in which I can replicate changes locally. It's something I'll only be able to address tonight back at home.

**Comment by noczesc** [comment] 2016-02-16 16:33
@hallaathrad I forgot to mention this and it might be helpful - I'm viewing the website on a 1920x1080 screen, but the issue also occurs on my second 1440x900 monitor.

**Comment by hallaathrad** [comment] 2016-02-16 16:36
:+1: I believe I have enough information now to run a few tests. I'll get back to you when I've managed a viable solution. Thank you @noczesc

**Comment by noczesc** [comment] 2016-03-05 21:33
@hallaathrad I stumbled upon the same issue while I was writing my own website - I solved it by removing overflow: auto from <body> - maybe it'll work for you as well.

**Comment by hallaathrad** [comment] 2016-03-06 00:08
hmmmm!!!! Thanks! Thought that would be the issue. The problem is the way the viewport is currently built requires that in order to work. 
I haven't been able to PR a solution to this because it involves rebuilding part of the template system.

To be continued...

**Comment by QuincyLarson** [comment] 2016-10-13 20:10
@macbem is this still an issue?

**Comment by macbem** [comment] 2016-10-13 20:18
@QuincyLarson I've switched to OS X and I can't replicate the issue, but I also can't confirm that it's not there anymore. You'd have to ask someone with Windows / Linux installed. I'll try to replicate it in my office tomorrow - I'll keep you updated.

**Comment by QuincyLarson** [comment] 2016-10-14 18:47
@macbem excellent! Thank you for your help with confirming whether this is still an issue. If it is an issue, could you try and capture a short video of the issue? That will better help us understand it.

**Comment by macbem** [comment] 2016-10-14 20:19
There was a video, but the repo probably got purged when I removed lots of my old *totally not spaghetti, not at all* code. I'm glad to announce that the issue is not there anymore on OS X El Capitan (Chrome, Safari) and Ubuntu 14.04 (Chromium, Chrome, Firefox, Opera). It was tested on the newest versions available, so yeah, good job, guys.

**Comment by atjonathan** [comment] 2016-10-14 20:31
@macbem, awesome! Thanks for confirming this. Closing as resolved.

**Closed by atjonathan** 2016-10-14 20:31 UTC
Labels: confirmed

**Comment by QuincyLarson** [comment] 2016-10-14 23:51
@macbem thanks again for confirming this! 🎊
