### ISSUE TITLE
Use Conditional Logic with If Statements - note how return statement works

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45181] opened 2022-02-19 01:00 UTC
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-conditional-logic-with-if-statements

## Your code

```



```

## Expected behavior

The curriculum hasn't explained so far the use of multiple "return"s inside a function, saying this I think that there should be a note explaining that the function terminated once it arrives at its first valid "return".
This should be added because new students can misunderstand how a return works in a function.

## Screenshots

![image](https://user-images.githubusercontent.com/92828033/154779028-9dae2b2a-1964-4a8f-ac4b-134925cc5bd9.png)

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by gikf** [comment] 2022-02-19 09:28
This is more explicitly explained in https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions. There's also couple different challenges where multiple returns are used before that.

I'd say the way it is currently is fine for me. It isn't explicitly explained in this challenge, but there's explanation what will happen.
> When `test` is called with a value of `true`, the `if` statement evaluates `myCondition` to see if it is `true` or not. Since it is `true`, the function returns `It was true`.

> When we call `test` with a value of `false`, `myCondition` is not `true` and the statement in the curly braces is not executed and the function returns `It was false`.

I think it's not necessarily bad to not try to explain everything the first time it's shown. This leaves room for curiosity and own tries. If this catches somebody attention, it's possible it will lead to some own explorations. _This looks weird, should it be like that? Is it like that further? Is this a mistake?_ Although I understand this might not work like that for everybody, and may give strange feelings if something turns out to be _correct_ after all.

**Comment by LuckyLolo123** [comment] 2022-02-19 20:27
I think that should be required to add at the end of the minichallenge two lines similar to this:

console.log(trueOrFalse(true));
console.log(trueOrFalse(false));

doing this the student can see the two outputs running his own program

**Comment by jeremylt** [comment] 2022-02-20 19:22
No need to turn this issue into a duplicate of your other one.

I also agree that we should favor briefer explanations. Not every challenge needs to say absolutely every factoid that may be relevant to the learner's understanding. That would make the descriptions too long and encourage people to read the less than they already do.

**Comment by abhijain2003** [comment] 2022-03-03 16:15
how can i fork it and update the code in affected area. please tell me

**Comment by ShubhraSuman** [comment] 2022-03-25 11:19
Can I start working on this one?

**Comment by ShaunSHamilton** [comment] 2022-03-25 11:33
@ShubhraSuman 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jeremylt** [comment] 2022-03-25 15:15
I think currently we have two votes against making this change.

**Comment by nhcarrigan** [comment] 2022-03-25 17:53
I'm in agreement as well, that nothing needs to be changed here. The purpose of this challenge is to introduce `if` statements, and the next few challenges build on that to teach conditional operators.

Adding an explanation about the `return` statement would just create noise, IMHO.

**Closed** 2022-03-25 18:50 UTC
Labels: status: discussing, scope: curriculum
