### ISSUE TITLE
Serious Problem using the FCC IDE, console showing error and check answer 

### ISSUE THREAD

**Issue by ryzokuken** [FreeCodeCamp/FreeCodeCamp#6122] opened 2016-01-13 12:50 UTC
Challenge [Waypoint: Using typeof](http://www.freecodecamp.com/challenges/waypoint-using-typeof) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is not a challenge-specific error. It shows up for each and every exercise which uses the FCC IDE (waypoints, bonfires, etc) I cleared browser cache, and even restarted my computer

![capture](https://cloud.githubusercontent.com/assets/13121330/12294691/52753ac6-ba22-11e5-84ee-ad6a504281f4.JPG)

**Comment by bugron** [comment] 2016-01-13 13:18
@ryzokuken thanks for posting this issue!
Do you have any errors in your console log?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ryzokuken** [comment] 2016-01-14 05:13
Thats a relief, @bugron . Although, it seems queer to me that it happens only to me and not to anyone else.

P.S. You were right, there were things being logged into the console, it might be the key to what exactly is going wrong.

Here you go:

![Error](https://cloud.githubusercontent.com/assets/13121330/12316348/85f042cc-baab-11e5-86e7-32708fd4475b.png)

**Comment by sludge256** [comment] 2016-01-14 05:25
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5999
@ryzokuken Feel free to look into the linked issue.
Closing for now.

**Closed by sludge256** 2016-01-14 05:25 UTC
