### ISSUE TITLE
Dot Notation is not working in this challenge!

### ISSUE THREAD

**Issue by umeshgmrl** [freeCodeCamp/freeCodeCamp#13801] opened 2017-03-08 06:00 UTC
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20if(myObj.hasOwnProperty(checkProp))%20return%20myObj.checkProp%3B%0A%20%20return%20%22Not%20Found%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22pet%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  if(myObj.hasOwnProperty(checkProp)) return myObj.checkProp;
  return "Not Found";
}

// Test your code by modifying these values
checkObj("pet");

```
The Dot Notation is not working in this challenge, but Bracket Notaion is working fine.
I am attaching a screenshot to this.
Thanks!
![fcc](https://cloud.githubusercontent.com/assets/23176540/23692091/96ed7cb6-03f2-11e7-80a3-75cf2134831c.PNG)

**Comment by Manish-Giri** [comment] 2017-03-08 06:26
@umeshgmrl That is [expected behavior](http://stackoverflow.com/questions/4968406/javascript-property-access-dot-notation-vs-brackets).

**Comment by erictleung** [comment] 2017-03-09 17:38
@umeshgmrl Thank you for reporting this issue. Take a look at the link @Manish-Giri as pointed out and also reach out to the Gitter community why dot notation doesn't work in this context.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Closed by erictleung** 2017-03-09 17:38 UTC

**Comment by umeshgmrl** [comment] 2017-03-10 09:13
@Manish-Giri  @erictleung  Thank you for correcting my mistake. I went to the links you've mentioned and they are helpful. Cheers!
