### ISSUE TITLE
console statements not displaying result

### ISSUE THREAD

**Issue by ajityadav83** [freeCodeCamp/freeCodeCamp#15300] opened 2017-06-10 21:28 UTC
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line

console.log(" Hello World ") // <--- This statement is not logged in the console window 

// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");

```

> there should be a way for a coder to check how control is flowing through my code. "console.log" statement is one such statement.

> But console.log statement is not showing any output

Edit (@raisedadead):
*Original code hidden here*

**Comment by raisedadead** [comment] 2017-06-11 04:56
Note: I think there is one more open issue for this same use case. That has to be tagged and attached to closing while addressing this.

**Comment by rnallu** [comment] 2017-06-11 08:01
Firstly, the representation of object in `if Condition` is wrong. To access the Object properties, we have two ways. ie. dot notation and bracket notation.
```
object.property
object['property']
```
Since, we have an array with objects, we use `object['property']`. In your case, property defined with Index, but it should be Object property in quotes. ie. `contacts[i]['firstName']`

Second, `for loop` to check all indexes under `if condition`, Then it should confirm. In your case, `for loop` consists of both If and else statements, which is wrong.

Hope this will helps in clsoing the issue.

**Comment by raisedadead** [comment] 2017-06-11 09:50
Hi @rnallu Thanks, I have removed your comment because it provides coding assistance to the challenge. We strictly discourage that on this issue tracker.

This issue is about console.log not logging output to the console window on the page.

We need to filter and pipe the output this from the console.log being used in the browser debugger to the console window as well.

This done for other challenges.

**Comment by ajityadav83** [comment] 2017-06-11 11:25
@raisedadead , thanks but how can I get tot the thread related to issue above... please guide me to correct thread

**Comment by F4ndomGh0st** [comment] 2017-07-15 13:53
Using return will print to the "console" under the instructions all the same.

**Comment by sanyamc** [comment] 2017-07-23 02:43
I am assuming you want to see console.log out put on the webpage itself.
Not sure why would we want to override a native browser api and show it on the webpage.
Instead we can clearly see the console.log statements in browser's dev tools. I have tried that in atleast 4 challenges and it works for various test cases. Using developer tools is an integral part of web development and we should use that instead of hacking console.log to display on the web page.

Above all i see following comment on the very first challenge which says that console.log is going to be in the dev tools.
![image](https://user-images.githubusercontent.com/1045176/28496049-cb49afc8-6f15-11e7-9f8f-888c59688e5b.png)

I suggest close it as by design.

**Closed** 2017-09-02 01:36 UTC
Labels: bug, confirmed, enhancement, help wanted
