### ISSUE TITLE
[Critical] Scientific Computing with Python Projects - The solution link accepts any valid URL and passes the challenge.

### ISSUE THREAD

**Issue by parresh77** [freeCodeCamp/freeCodeCamp#40041] opened 2020-10-19 20:31 UTC
For instance, I am taking the example of Budget App in Scientific Computing with Python Projects series(https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/budget-app).

When I type Google's URL as the solution link - 
![image](https://user-images.githubusercontent.com/35279064/96508103-b90d5900-1277-11eb-8fb8-56690967a343.png)

and click "I've completed this challenge", it says - 
![image](https://user-images.githubusercontent.com/35279064/96508221-e22de980-1277-11eb-8e99-cdd39d49d1ba.png)

I haven't tested the same on other series.

**Comment by Sky020** [comment] 2020-10-19 21:20
Hello there. Thank you, for taking the time to report this.

This is expected behaviour. The tests are supposed to be completed on the app's side. We are looking at ways to test for them on fCC's side, in the future

Duplicate of: https://github.com/freeCodeCamp/freeCodeCamp/issues/37185

**Closed by Sky020** 2020-10-19 21:20 UTC
Labels: scope: learn, status: needs help for triage
