### ISSUE TITLE
Testing Suite Error Message Unclear - Why Does it Not Run?

### ISSUE THREAD

**Issue by iarobinson** [freeCodeCamp/freeCodeCamp#37727] opened 2019-11-09 22:27 UTC
**Describe the bug**
Unclear error message for embedding test suite to front end projects

**To Reproduce**
1. Build a simple HTML page
2. Embed the testing javascript the head of that page

**Expected behavior**
Error message is unclear. Could be something like "ERROR: You're missing this element on your page"

**Screenshots**
![error_message](https://user-images.githubusercontent.com/7991933/68535748-53d98580-02fc-11ea-8703-3ab9ab6425f8.jpg)

![error_source](https://user-images.githubusercontent.com/7991933/68535749-53d98580-02fc-11ea-9990-de8db250416d.jpg)

**Desktop (please complete the following information):**
 - Browser Chrome
- [Here is the project live on GitHub Pages](https://iarobinson.github.io/jimi-hendrix-tribute-page/)
- [Here is the GitHub project and source code](https://github.com/iarobinson/jimi-hendrix-tribute-page)

**Additional context**
I was building the tribute page project. I added the JS for the test suite. The testing suite isn't opening and the error message isn't helpful.

**Comment by RandellDawson** [comment] 2019-11-09 23:37
@iarobinson GitHub issues are reserved when a bug has been validated by others (typically on the forum).  Always reach out to the [forum](https://www.freecodecamp.org/forum) first and if members determine the issue is not your code, then you can open an issue.

I am closing this issue as you just need to move the link to to the test suite from the `head` element to right before the closing `body` tag (like below):
```
    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
  </body>
</html>
```

**Closed by RandellDawson** 2019-11-09 23:37 UTC
Labels: type: bug
