### ISSUE TITLE
Zipline: Camper Leaderboard - API data discrepancy

### ISSUE THREAD

**Issue by noinkling** [FreeCodeCamp/FreeCodeCamp#5984] opened 2016-01-09 02:01 UTC
Challenge [Zipline: Build a Camper Leaderboard](http://www.freecodecamp.com/challenges/zipline-build-a-camper-leaderboard) has an issue.

The data being returned by the http://fcctop100.herokuapp.com/api/fccusers/top/recent endpoint has some users with more points in the last 30 days than they have all time, which doesn't really make sense, unless I'm missing something obvious. Visiting those users' profiles will show the correct value.

I know that the data is only refreshed for a user periodically - are the two values perhaps updated independently?

**Comment by SaintPeter** [comment] 2016-01-09 03:29
I agree, this doesn't make any sense.  Confirmed.

**Comment by sludge256** [comment] 2016-01-09 04:38
Related?
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5322

**Comment by abhisekp** [comment] 2016-01-15 04:19
Update the provided endpoints with the following
```text
GET https://fcctop100.herokuapp.com/api/fccusers/top100/recent
GET https://fcctop100.herokuapp.com/api/fccusers/top100/alltime
```

**Comment by bugron** [comment] 2016-02-16 09:02
@roelver can you take a look at this?

**Comment by roelver** [comment] 2016-02-17 19:06
Already fixed since 25 Jan 2016. 

Just use the endpoints in the challenge: 
[http://fcctop100.herokuapp.com/api/fccusers/top/recent](http://fcctop100.herokuapp.com/api/fccusers/top/recent)
[http://fcctop100.herokuapp.com/api/fccusers/top/alltime](http://fcctop100.herokuapp.com/api/fccusers/top/alltime)

Note that the counts are the helper score, so not related to the number of points or challenges, . Quincy asked for that. He also asked me to stop updating the scores for a while (by screen scraping), until the performance issues with the site are resolved.

This became a bug due to a misunderstanding when the new challenge was introduced. Also after the FCC site was restyled, breaking the score updates.

**Comment by ltegman** [comment] 2016-02-17 19:46
Awesome. Closing this then :+1:

**Closed by ltegman** 2016-02-17 19:46 UTC
Labels: bug, confirmed

**Comment by kumarchandan** [comment] 2016-06-19 12:02
Both the links are not up.
http://fcctop100.herokuapp.com/api/fccusers/top/recent
http://fcctop100.herokuapp.com/api/fccusers/top/alltime

**Comment by atjonathan** [comment] 2016-06-20 07:18
@kumarchandan, they work fine for me?

**Comment by kumarchandan** [comment] 2016-06-26 13:19
@atjonathan Yeah.. its working now. I think it was temporary issue. Thanks!
