### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Kafiil** [FreeCodeCamp/FreeCodeCamp#5772] opened 2016-01-02 18:51 UTC
Even if my code is working i get this error
Challenge [Checkpoint: Stand in Line](http://www.freecodecamp.com/challenges/checkpoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push(item)%3B%0A%20%20item%20%3D%20arr.shift()%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(myArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myArr = [1,2,3,4,5];

function queue(arr, item) {
  // Your code here
  arr.push(item);
  item = arr.shift();
  return item;  // Change this line
}

// Display Code
console.log("Before: " + JSON.stringify(myArr));
console.log(queue(myArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(myArr));

```

**Comment by ltegman** [comment] 2016-01-02 18:53
Closing as a duplicate of #5715. Thanks and happy coding!

**Closed by ltegman** 2016-01-02 18:53 UTC
