### ISSUE TITLE
Language switching option on news from the English language

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46569] opened 2022-06-19 18:02 UTC
### Is your feature request related to a problem? Please describe.

while browsing news platform, if you tried to change to the Spanish language, you have to search for a [English article](https://www.freecodecamp.org/news/learn-react-in-spanish-course-for-beginners/), translated to Spanish. 

From there, switching to the Spanish language is possible by clicking [the Spanish version of the article](https://www.freecodecamp.org/espanol/news/aprende-react-desde-cero-curso-de-react-con-proyectos/)

### Describe the solution you'd like

Add a menu, in the news. With language selector and how to contribute sections 

Kodus for raisethedead for the image

<img width="207" alt="image" src="https://user-images.githubusercontent.com/1884376/174583162-e4ee645b-8ac4-49b0-9825-0a36d00fafde.png">

**Comment by raisedadead** [comment] 2022-06-20 10:26
Your steps to reproduce this are not cohesive or clear to me. Can you write the issue as plainly as possible for a better understanding?

**Comment by raisedadead** [comment] 2022-06-20 10:31
I read this atleast three times and I understand all you are asking is we have a menu item like below 

<img width="207" alt="image" src="https://user-images.githubusercontent.com/1884376/174583162-e4ee645b-8ac4-49b0-9825-0a36d00fafde.png">


Correct?

**Comment by raisedadead** [comment] 2022-06-20 12:47
Thanks. 

It's highly unlikely that we will implement this because it has been discussed in the past and confirmed that the majority of the users reach news articles from outside news. 

I understand that we need to showcase more available languages, but I am not sure that we want a menu. I believe we do not want many options.

In fact, with the recent addition of "the thank you for supporting.." banner for donors on news, we got rid of any apparent way to even reach learn from the news.

**Comment by raisedadead** [comment] 2022-06-20 12:48
I am going to go ahead and close this and we can reopen this after discussing internally.

**Closed by raisedadead** 2022-06-20 12:48 UTC
Labels: type: feature request, platform: news
