### ISSUE TITLE
Console says "total is not defined" even without any piece of code.

### ISSUE THREAD

**Issue by freecates** [FreeCodeCamp/FreeCodeCamp#6052] opened 2016-01-11 13:14 UTC
Challenge [Waypoint: Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-through-an-array-with-a-for-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line



```
The console says "total is not defined" when without adding any piece of code. Tested on: Firefox 43.0.4, Chrome 48.0.2564.71 and 	34.0.2036.25.

**Comment by raisedadead** [comment] 2016-01-11 13:37
Hi @freecates,

This is interesting. Good catch I would say. With your link, or upon resetting the code, it should have the test cases, however it doesn't. Some how the test cases are not displayed below the console window, even when I opened in a fresh browser window (no cache-ed data).

![i](https://cloud.githubusercontent.com/assets/1884376/12234872/0141d8ae-b896-11e5-8604-38a8da69d523.PNG)

Needs looking into. :+1: 

It should have the test cases like below:

![i](https://cloud.githubusercontent.com/assets/1884376/12234962/7d16318c-b896-11e5-9e4f-ee0dcd4e43f3.PNG)

**Comment by bugron** [comment] 2016-01-11 14:06
@freecates thanks for posting this issue!
This is expected. Here is a part form the description:
> Instructions
Declare and initialize a variable **total** to 0. Use a for loop to add the value of each element of the myArr array to **total**.

So you haven't defined and used the variable `total` and that's why you get that error.
@raisedadead test cases doesn't show up because there is an error. Also `total is not defined` and `total is undefined` are totally different things.

Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-01-11 14:06 UTC

**Comment by raisedadead** [comment] 2016-01-11 14:16
> Also total is not defined and total is undefined are totally different things.

@bugron Yup I get that its clearly mentioned in the console output :smile: 

But I do feel that at the start, i.e **when the user lands on the challenge for first time** he should see the test cases as in other challenges, this may be a shocker to newbies especially when they are used to seeing the green and red icons and the test cases.

A sudden console error may be misleading to some, in comparison to the previous challenges.
Don't you agree?

**Comment by bugron** [comment] 2016-01-11 14:20
All I can say this is how things work. Follow instructions, if there are problems post in our Gitter chat room, only if others can reproduce the problem you're experiencing post an issue here.

**Comment by raisedadead** [comment] 2016-01-11 14:39
Haha... its okay @bugron. 

Never mind its any ways a small trivial issue, plus I am not the original one to report, just another contributor like you. @freecates will do the needful if he feels like. I was just highlighting the fact a newbie may face, with things he is used to.

Have a good one!

P.S: Have done a couple of contributions before, I am aware of the guidelines :wink:

**Comment by bugron** [comment] 2016-01-11 14:43
I'm posting the guidelines almost in every comment so it's not just for you ;)

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by raisedadead** [comment] 2016-01-11 14:45
Haha Sorry @bugron :laughing: ! My bad. Its actually a good idea..., I too see a lot of issues that could be solved by the chat.

Good work :+1:

**Comment by freecates** [comment] 2016-01-11 15:30
So sorry, but I haven't realized that I couldn't use any name for my 
variable to complete the Waypoint, so I got confused with an error even 
if I hadn't written any piece of code.

El 11/01/16 a les 15:46, Mrugesh Mohapatra ha escrit:
