### ISSUE TITLE
[BUG] - Back-end Project Boilerplates

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40365] opened 2020-12-02 21:42 UTC
One of our Discord members mentioned running in to issues with the `boilerplate-express` code. The `package.json` calls for a Node version of `4.x`, which is severely outdated. In this case, the camper was working on the code locally and deployed to Heroku for the live link to submit, and Heroku threw build errors because of the engine version.

While we specifically mention repl.it on the /learn pages as the go-to platform, we do include instructions for working on it locally. Would it be worth looking in to updating the boilerplates to use the LTS version of node (and verifying compatibility)?

**Comment by Sky020** [comment] 2020-12-02 21:53
I would imagine the easiest fix would be to remove the mention of which engine to use. I know some online IDEs do require it, but, AFAIAA, Repl.it uses its config file for this. So, we might as well remove it.

**Comment by nhcarrigan** [comment] 2020-12-02 21:58
AFAIK, the purpose of the `engine` field is to tell the environment what version of node to spin up, right? So the idea being that by specifying a node version, we ensure that campers don't run into issues where the latest version had breaking changes that we didn't account for when writing the lessons.

**Comment by Sky020** [comment] 2020-12-02 22:10
> tell the environment what version of node to spin up, right?

@nhcarrigan Right. The issue is how online IDEs (Repl.it, Glitch, CodeSandbox) handle this differently. That is, Repl.it does not listen, I did not think Glitch did either (permanently set on v10). So, it is used by the _more advanced_ environments, and I expect campers to handle the specifics like this env-by-env.

**Comment by nhcarrigan** [comment] 2020-12-02 22:11
> So, it is used by the more advanced environments, and I expect campers to handle the specifics like this env-by-env.

That's a fair expectation, I think. 🙂

**Comment by nhcarrigan** [comment] 2020-12-10 23:52
Hey @moT01 the 15 linked PRs should remove the `engine` fields from our boilerplates. Once they're all approved/merged, we can close this I believe.

**Comment by moT01** [comment] 2021-01-15 01:47
I think we are safe to close this. If I am mistaken, feel free to leave a comment and it can be reopened. Thanks and happy coding 🎉

**Closed by moT01** 2021-01-15 01:47 UTC
Labels: scope: projects-backend
