### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by mullachv** [FreeCodeCamp/FreeCodeCamp#2854] opened 2015-08-29 21:35 UTC
Challenge http://freecodecamp.com/challenges/bonfire-no-repeats-please has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The following description is incorrect, in my understanding of permutations:
"
Return the number of total permutations of the provided string that don't have repeated consecutive letters.

For example, 'aab' should return 2 because it has 6 total permutations, but only 2 of them don't have the same letter (in this case 'a') repeating.
"
Number of permutations possible is 3 not 6. Off that only 1 matches the question criteria:
Possible permutations:
aab
aba
baa

Only one, 'aba' matches the conditions. Please correct the bonfire question and the answer checking scripts

**Comment by natac13** [comment] 2015-08-29 23:59
I think we are suppose to treat the 'a' characters as different letter. Visually I mean like this so. Think of 'aab' as 'Aab' then the permutations are as such:
'Aab'
'Aba'
'bAa'
'aAb'
'abA'
'baA'

Giving 6 total permutations with 2 able to match the test criteria..... That is how I saw the problem. Hope this helps

**Comment by mullachv** [comment] 2015-08-30 00:11
Extending your line of thought, now, there are NO repeated occurrences, Sean. I don't see any letter repeated in any of the permutations. (a  is not A, per your statement). So the answer must be 6 and not 2 then.

**Comment by natac13** [comment] 2015-08-30 00:40
The difference in the 'a' and 'A' is only a visual for us to see how the two 'a' characters are treated as different objects when determining how many permutations. Then when it comes time to filter, since they 'look' the same then they are excluded from the count in the answer

**Comment by natac13** [comment] 2015-08-30 00:44
Left side is the visual for us humans and then right side is what computer will see:

|Human Visual|Computer version|
|------------------|----------------------|
|'Aab'     |'aab'
|'Aba'    | 'aba'
|'bAa'   |  'baa'
|'aAb'  |   'aab'
|'abA' |    'aba'
|'baA'|     'baa'

**Comment by mullachv** [comment] 2015-08-30 03:29
Thanks for that table, Sean. It's not that I do not *see* this; it is just that according to combinatorics, it is incorrect to say that the number of permutations of 'n' objects where each can occur r1, r2 ... etc. times is  n!, whereas it truly is n!/ (r1! r2!...) 

In my humble opinion, this question is poorly thought-out and worded.

**Comment by benschenker** [comment] 2015-09-08 06:05
Hey @mullachv and @natac13, it looks like this is a duplicate of #2524 so please continue this discussion there.  I think we all agree that the challenge is confusing.  We need to come up with language that makes it more clear.

Thanks!

**Closed by benschenker** 2015-09-08 06:05 UTC
