### ISSUE TITLE
Error "console.log never called" - Challenge "Local Scope and Functions"

### ISSUE THREAD

**Issue by dmsanchez86** [FreeCodeCamp/FreeCodeCamp#7813] opened 2016-03-30 14:42 UTC
![camp](https://cloud.githubusercontent.com/assets/8863296/14146427/203f62f8-f65d-11e5-8a4a-dbeff09fb11d.png)
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myFunction()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20var%20myVar%3B%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0Aconsole.log(myVar)%3B%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myFunction() {
  'use strict';
  var myVar = "";
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test


```

**Comment by dmsanchez86** [comment] 2016-03-30 14:44
The code is good, but the output console show "console.log never called",
I think that my code is correct because the instruction is "Declare a local variable myVar inside myFunction"

**Comment by we7d** [comment] 2016-03-30 15:05
Read the comments .

**Comment by raisedadead** [comment] 2016-03-30 15:48
Closing as a duplicate of #6259

PS: Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Closed by raisedadead** 2016-03-30 15:48 UTC

**Comment by dreysin82** [comment] 2016-06-23 06:58
o meu funcionou 
function myLocalScope() {
  'use strict';
  var myVar = "teste";
  
  console.log();
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log();

// Now remove the console log line to pass the test

**Comment by tanveer23** [comment] 2016-11-19 04:41
function myLocalScope() {
  'use strict';
   var  myVar;
  
  console.log("loc");
}
myLocalScope();
// Run and check the console
// myVar is not defined outside of myLocalScope
console.log("loc");
// Now remove the console log line to pass the test
