### ISSUE TITLE
Comments are checked in test cases for issues ....

### ISSUE THREAD

**Issue by swapy** [FreeCodeCamp/FreeCodeCamp#8641] opened 2016-05-15 13:00 UTC
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%2F*%20%20switch(val)%20%7B%0A%20%20%20%20case%20%22alpha%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Adams%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22bravo%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Boston%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22charlie%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Chicago%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22delta%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Denver%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22echo%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Easy%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22foxtrot%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Frank%22%3B%0A%20%20%7D*%2F%0A%20var%20lookup%3D%7B%0A%20%20%20alpha%3A'Adams'%2C%0A%20%20%20bravo%3A'Boston'%2C%0A%20%20%20charlie%3A'Chicago'%2C%0A%20%20%20delta%3A'Denver'%2C%0A%20%20%20echo%3A'Easy'%2C%0A%20%20%20foxtrot%3A'Frank'%0A%20%7D%3B%0A%20%20result%3D%20lookup%5Bval%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
/*  switch(val) {
    case "alpha": 
      result = "Adams";
      break;
    case "bravo": 
      result = "Boston";
      break;
    case "charlie": 
      result = "Chicago";
      break;
    case "delta": 
      result = "Denver";
      break;
    case "echo": 
      result = "Easy";
      break;
    case "foxtrot": 
      result = "Frank";
  }*/
 var lookup={
   alpha:'Adams',
   bravo:'Boston',
   charlie:'Chicago',
   delta:'Denver',
   echo:'Easy',
   foxtrot:'Frank'
 };
  result= lookup[val];
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

I was given error ***You cannot use if or switch statements***. However, if you look carefully, i have commented out switch case code.

I think freecodecamp test compiler even scans in commented code also.Ideally it should not.

**Comment by erictleung** [comment] 2016-05-15 16:24
@swapy thanks for the issue. I can't actually reproduce this, but I think I know the problem and I don't think there is a quick fix for this issue. It has been mentioned [before in a similar issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7901#issuecomment-205645055) that the editor is concatenating the code into a string before being evaluated. If you move that end comment to a new line, it should work.

```js
  // Only change code below this line
/*  switch(val) {
    case "alpha": 
      result = "Adams";
      break;
    ...
    case "foxtrot": 
      result = "Frank";
  }
*/
```

@raisedadead correct me if I'm wrong. I think this is a similar issue to the one I linked above. Please close this if you agree.

**Comment by raisedadead** [comment] 2016-05-15 16:32
@erictleung : Yes you are correct thing is we do not have a pure JavaScript parser, per say, and yes cases such as this sometimes give these false positives.

Suggested work around: Delete the commented code completely 
This can be closed, because implementing a complete JavaScript parser is not what we are looking into currently.

**Closed** 2016-05-15 16:58 UTC
