### ISSUE TITLE
Show me my public profile redirects to Map

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#13075] opened 2017-02-02 15:41 UTC
#### Challenge Name
Edit: http://beta.freecodecamp.com/en/offllne redirects to map

#### Issue Description
Edit: Seems that my account does not exist in beta :/

#### Browser Information

* Browser Name, Version: Chrome v56
* Operating System: OS X 10.10

Did not find any duplicates on that. Similar to #10880 but lil different

**Comment by ajain17** [comment] 2017-02-02 16:34
When I type http://beta.freecodecamp.com/ajain17, it redirects me to http://beta.freecodecamp.com/en/ajain17 and shows me my profile. Browser: Chrome, OS: OX X 10.11

Can anyone else verify this?

**Comment by OFFLlNE** [comment] 2017-02-02 16:36
@ajain17 yep. Your profile works for me! :D 
Seems that this is only me :'(

**Comment by ajain17** [comment] 2017-02-02 16:40
Try clearing cache or deleting cookies? I believe we can close this issue then.

**Comment by OFFLlNE** [comment] 2017-02-02 16:45
@ajain17 can you access my profile? It seems that my profile does not exist.
Do not think that this is closable yet

Clearing Cookies, cache did not help.
Console does not show any errors either. Under Network tab I am getting this:

**Comment by dhcodes** [comment] 2017-02-02 16:51
@OFFLlNE how did you make your account on the beta? Github connector or email?

**Comment by OFFLlNE** [comment] 2017-02-02 16:54
@dhcodes tbh I don't remember. Think by email
I think it was that I was trying to create it with my email, but then it said that I already have an account associated to that email. So I just managed to sign in w/ it. It might've been a little different than that, but not really sure anymore

**Comment by ajain17** [comment] 2017-02-02 17:02
@dhcodes  why does it matter how he created it? If he is using an invalid username, it will show him a message like this, not take him to map. Please tell me if I'm missing something.
<img width="1197" alt="screen shot 2017-02-02 at 12 02 01 pm" src="https://cloud.githubusercontent.com/assets/5581487/22559552/75793034-e93f-11e6-855b-97760ccf03ef.png">

**Comment by ajain17** [comment] 2017-02-02 17:03
@OFFLlNE What are you getting under network tab?

**Comment by OFFLlNE** [comment] 2017-02-02 17:06
@ajain17 you have a point with that non-existing username
Whoops, forgot to upload :D 
![image](https://cloud.githubusercontent.com/assets/8721312/22559704/a3cedb38-e97a-11e6-8997-8502c0c5fe00.png)

**Comment by OFFLlNE** [comment] 2017-02-02 17:07
@ajain17 it is OFFLLNE ;)

**Comment by dhcodes** [comment] 2017-02-02 17:09
@ajain17 because all the working accounts I've seen so far have Github attached.

**Comment by OFFLlNE** [comment] 2017-02-02 17:11
@dhcodes When I log out and then log in, I am connecting myself to b.fCC with Github

**Comment by ajain17** [comment] 2017-02-02 17:35
oh, I read it as offline. Ok, when I go to http://beta.freecodecamp.com/en/offllne, it takes me to map page, confirmed.

**Comment by Parad0xJ** [comment] 2017-02-18 16:50
Hi,
I have them problem with beta version. I can't see my public profil, when I click to "Shom my profil public" I go directly to map.
Google Chrome : Version 56.0.2924.87
Windows 10

**Comment by bomholt** [comment] 2017-05-04 23:21
http://beta.freecodecamp.com/en/bomholt

same issue...

**Closed** 2017-09-27 20:58 UTC
Labels: accounts, beta, decayed
