### ISSUE TITLE
imaginary anchor

### ISSUE THREAD

**Issue by ucrook** [FreeCodeCamp/FreeCodeCamp#3098] opened 2015-09-05 20:30 UTC
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

click the anchor then click the run test button and the instructions bellow dissepear and you cannot continue to the next challenge. refreshing the page and click on run test and submit helps.

**Comment by bugron** [comment] 2015-09-06 03:50
@ucrook thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717. You can continue further discussion there, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-06 03:50 UTC
