### ISSUE TITLE
Validation issue with the Responsive image waypoint

### ISSUE THREAD

**Issue by guptamo** [FreeCodeCamp/freecodecamp#932] opened 2015-06-15 08:20 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I've created the image tag for the cat (\<img class='smaller-image thick-green-border img-responsive' src='http://bit.ly/fcc-kittens2'/>) and set the source to the one indicated on the page but it doesn't seem to allow me to progress.

![screen shot 2015-06-15 at 4 17 34 pm](https://cloud.githubusercontent.com/assets/10948133/8155862/fae4a272-137a-11e5-826b-130c6bcb5ce5.png)

**Comment by sarad1p1ty** [comment] 2015-06-21 11:31
I'm having the same issue. I've tried with just the img-responsive class attribute as well as copying all three from the first image.

I'm working in Chrome Version 43.0.2357.124 m

**Comment by sarad1p1ty** [comment] 2015-06-21 11:38
Update:

The validation fails because I also added the img-responsive class attribute to the first image. If I leave the first img tag as it was, it will validate.

**Comment by digitaldak** [comment] 2015-06-21 15:44
Releated to #998 as both deal with this same issue.

**Comment by cshutchinson** [comment] 2015-08-04 13:52
Issue confirmed. The following HTML will work, but not what was intended by text of the challenge.

```

**Comment by BerkeleyTrue** [comment] 2015-08-11 18:59
should be fixed now. Please reopen if the issue still persists

**Closed by BerkeleyTrue** 2015-08-11 18:59 UTC
