### ISSUE TITLE
Streak not showing properly 

### ISSUE THREAD

**Issue by mamun2015** [FreeCodeCamp/FreeCodeCamp#3177] opened 2015-09-08 22:37 UTC
In my profile now showing Longest Streak: 9 days and Current Streak: 3 days.
But i think it should be both Longest/Current Streak= 13 days.

Here is the screenshot 
![screenshot_5](https://cloud.githubusercontent.com/assets/11602663/9749176/4cbaf294-56ac-11e5-9f6a-067a7fde51c8.png)

thanks

**Comment by BerkeleyTrue** [comment] 2015-09-08 23:17
Closing as duplicate of #2290

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-09-08 23:17 UTC
