### ISSUE TITLE
If unauthenticated, map doesn't show optional challenges notice

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7450] opened 2016-03-07 15:31 UTC
If you're authenticated, this notice shows up at the top of the map:
![](https://www.evernote.com/l/Ar-whao9HsFOqax-hCbEU0W9RFCrnQmrmMEB/image.png)
If you aren't unauthenticated, this notice is hidden for some reason. It shouldn't be.
![](https://www.evernote.com/l/Ar_bdNEUPDlCHYu_BFxFPilAh6dn_8jhU1cB/image.png)

**Comment by ltegman** [comment] 2016-03-07 15:44
@QuincyLarson I'm not able to repro this and I can't see anything in the jade that should do this. Maybe it was just a hiccup on your end. Does this happen consistently if you try again?

**Comment by BerkeleyTrue** [comment] 2016-03-07 19:46
Also cannot duplicate

![a_map_to_learn_to_code_and_become_a_software_engineer___free_code_camp_and_downloads](https://cloud.githubusercontent.com/assets/6775919/13581111/2f404426-e45a-11e5-853f-9b98626f040b.png)

**Comment by raisedadead** [comment] 2016-03-22 07:38
I checked as well confirmed can't reproduce.
Closing for now.

**Closed by raisedadead** 2016-03-22 07:38 UTC
Labels: blocked, Can't reproduce
