### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by jarrodyellets** [freeCodeCamp/freeCodeCamp#16290] opened 2017-12-23 08:36 UTC
#### Issue Description

When you click on the magic link after you entered your email, it states "Oops, something is not right, please request a fresh link to sign in / sign up".  I waited to request a new link, but same issue.

#### Browser Information

* Browser Name, Version: Chrome version 63, Safari on iOS 11.2.1
* Operating System: Mac OSX 10.13.1, iOS 11.2.1
* Mobile, Desktop, or Tablet: Laptop, iPhone

#### Screenshot

![image](https://user-images.githubusercontent.com/32344277/34318294-b0a7a72e-e7c4-11e7-969b-d9d427708c77.png)

**Comment by Bouncey** [comment] 2017-12-23 10:32
@jarrodyellets Did you sign up for the beta test?

**Comment by Asjas** [comment] 2017-12-23 12:05
@bouncy I can confirm that I'm receiving a similar problem when I receive my magic sign-in link. It get that same error.

I received the email from Quincy stating that I am a part of the beta test QA a few hours before trying to sign in.

**Comment by jarrodyellets** [comment] 2017-12-23 12:36
I have signed up.  I got the confirmation email from Quincy.

**Comment by raisedadead** [comment] 2017-12-23 14:19
Need to investigate this on the production, its not reproducible locally.

**Comment by raisedadead** [comment] 2017-12-23 14:23
Duplicate of #16288

**Closed by raisedadead** 2017-12-23 14:23 UTC
Labels: accounts, beta, confirmed

**Comment by jasonbunnell** [comment] 2017-12-23 18:05
I wanted to mention I received the same issue and add that last night I was able to log in successfully using magic link.  Completed several problems last night.  Today the tab was still open but looked like I had been logged out.  Tried to log in and the magic link was the only option I saw and tried it twice and neither time worked.
