### ISSUE TITLE
Error: Make sure your li element has a closing tag. When all li elements already have closing tag.

### ISSUE THREAD

**Issue by hugoender** [FreeCodeCamp/FreeCodeCamp#3382] opened 2015-09-20 20:35 UTC
The waypoint throws an error asking you to make sure your li element has a closing tag even though all of them do. The reason for this error is really the fact that the element has a class assigned to it. I read the waypoint instructions as saying to replace the <p> elements with <li> elements but keep the class. Maybe consider creating an additional check/error for <li> elements with classes assigned to them.

Challenge [Waypoint: Create a Bulleted Unordered List](http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
<ul>
  
  <li>Click here for <a href="#">cat photos</a>.</li>

  <li class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</li>
  <li class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</li>
</ul>

```

**Comment by bugron** [comment] 2015-09-20 20:43
@hugoender thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2791 so I'll close it. We have a submitted PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3365 which is pending for approvement and hopefully fixes this issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-20 20:43 UTC
