### ISSUE TITLE
Manage a Book Trading Club: probable bugs in example application

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#7219] opened 2016-02-24 13:59 UTC
#### Issue Description
1) [Home page](http://bookjump.herokuapp.com/) **Features** section:
links **Catalogue your books online**, **See all of the books our users own**, **Request to borrow other users' books**, **Easily manage books and requests from your dashboard** are not functional, nothing happens on click event, log is also empty; not sure if anything should happen at all; if nothing should, maybe it's reasonable not to use anchors;
2) [All books page](http://bookjump.herokuapp.com/allbooks):
some books don't have a symbol which should be clicked to request a trade - not sure if this is ok, because nothing is said about that in the task;
3) see attached screenshot.

#### Browser Information
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0

#### Screenshot
<a href="http://imgbox.com/9EWVi3pK" target="_blank"><img src="http://4.t.imgbox.com/9EWVi3pK.jpg" alt="image host"/></a>

**Comment by alistermada** [comment] 2016-02-28 09:31
@clnhll Can you check this one out?

**Comment by erictleung** [comment] 2016-03-30 01:39
The home page doesn't have to be functional, at least for the requirements of the challenge. So I think they were purposely dud links. 

The All Books page appears to work for me. There are some books that I guess you can't trade with but the ones that you can, you can click on the request trade button. I got to the page where your screenshot of the page where you can control requests and the X buttons worked for me. 

Closing because there doesn't appear to be any noticeable bugs right now. If you or others can reproduce the bugs, we can reopen this issue. Happy coding!

**Closed by erictleung** 2016-03-30 01:39 UTC
