### ISSUE TITLE
red crosses wrongly marked for tests

### ISSUE THREAD

**Issue by YashasSamaga** [freeCodeCamp/freeCodeCamp#16591] opened 2018-01-29 10:11 UTC
#### Compound Assignment With Augmented Subtraction
https://www.freecodecamp.org/challenges/compound-assignment-with-augmented-subtraction

Also happens in: https://www.freecodecamp.org/challenges/compound-assignment-with-augmented-addition

#### Issue Description
The challenge is completed and the success window (visible in the attached screenshot) does show up. However, the list of tasks in the challenge (shown at the bottom-left corner in the screenshot) shows a red cross mark for the task requiring the user to use the compound assignment operators. But this indication is not true; I have used the compound assignment operators in the code which was submitted.

I repeated the challenge and it did not happen.

#### Browser Information

* Browser Name, Version: Firefox, 54.0
* Operating System: Fedora 25
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
var a = 11;
var b = 9;
var c = 3;

// Only modify code below this line

a -= 6;
b -= 15;
c -= 1;
```

#### Screenshot
https://imgur.com/a/Ggxkt

**Comment by raisedadead** [comment] 2018-01-30 05:57
Hi @YashasSamaga thanks for reporting, I am unable to reproduce as well. This can happen occasionally and usually [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) solve the problem.

I'll close this, for now. However, if you still face such issues, and the troubleshooting doesn't solve the problem, please open a fresh issue.

Happy Coding!

**Closed by raisedadead** 2018-01-30 05:57 UTC
