### ISSUE TITLE
You did not solve this issue, you sent me instructions that are NOT on this page.

### ISSUE THREAD

**Issue by stutzro** [FreeCodeCamp/FreeCodeCamp#12158] opened 2016-12-21 23:00 UTC
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A16px%3B%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size:16px; 
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty ipsum dolor sit amet.</p>

```

**Comment by stutzro** [comment] 2016-12-21 23:02
Here is the response you sent me:

As the instruction says -

Create a second p element after the existing p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

But the instructions don't say that they say this:

Your p element should contain the first few words of the provided additional kitty ipsum text.

I tried to alter the text (leaving the first two words in tact) and it still did not work.  It tried altering the order of the paragraphs and it did not work.  I tried hand typing everything instead of copy and pasting, it did not work.  There is a problem with this page, it needs to be fixed.

**Comment by stutzro** [comment] 2016-12-21 23:03
...or you need to clarify the instructions...

**Comment by diomed** [comment] 2016-12-21 23:14
Lady, if you don't understand something click on Help button and people in Help chatroom shall explain you some things. Don't post in this repository. This is for reporting bugs, and this is not a bug.

**Comment by nicholashu** [comment] 2016-12-22 01:29
I can see that the instructions are correct, the key word in the test results is "**additional**". Take a look at the red text in the instructions. 

If you follow the instructions and use at least 3 words of the provided kitty ipsum "Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched." the test should pass.

**Comment by Marmiz** [comment] 2016-12-22 01:44
@stutzro as the challenge states:
>Create a second p element after the existing p element **with the following kitty ipsum text**: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

The program, to check for the correctness of your code will look for an exact match, so you NEED the text to be the exact same as the one provided in the instruction.

As @diomed suggested, next time you're having a difficulty remember the "mantra": READ - SEARCH - ASK.
If you don't know whee to ask the  [help chat room](https://gitter.im/FreeCodeCamp/Help) or the [forum](https://forum.freecodecamp.com/) are good place to start.

Happy coding 👍

**Comment by raisedadead** [comment] 2016-12-22 01:53
@stutzro Apologies if our response was not sufficient, or misunderstood. But please follow the code of conduct for this repository.

You can continue and comment, on the closed issue, and we would be happy to reopen after a valid discussion.

Having said that, we request you to confirm, if the issue you are facing is actually a but in the chat rooms before reporting.

Closing once again, as this is not a bug with the Free code camp code base, but a challenge help. 
Please head over to the chat rooms as suggested in the thread.

@diomed @nicholashu @Marmiz thanks a lot for your comments.

Happy coding everyone!

**Closed by raisedadead** 2016-12-22 01:53 UTC
