### ISSUE TITLE
Unclear instructions.

### ISSUE THREAD

**Issue by Stephen-254** [freeCodeCamp/freeCodeCamp#53307] opened 2024-01-22 03:36 UTC
### Describe the Issue

The instructions in this challenge are unclear, they talk of a `new line`, and most users end up using the new line character, which won't pass. It'd be better if `literal linebreak` is used as the keyword considering that some users are complete beginners in JS.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-44

### Your code

```

const HTMLString = `
  <label>Entry ${entryNumber} Name</label>`;

```

### Expected behavior

The code should display the use of the new line when consoled.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment] 2024-01-22 03:46
This is a duplicate of [issue #52741](https://github.com/freeCodeCamp/freeCodeCamp/issues/52741).

**Comment by Stephen-254** [comment] 2024-01-22 03:54
Thanks for the feedback, Bruce.

**Closed** 2024-01-22 03:54 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
