### ISSUE TITLE
Email Sign Up from a certain page raises an unexpected error

### ISSUE THREAD

**Issue by Brijesh2709** [freeCodeCamp/freeCodeCamp#42389] opened 2021-06-07 04:08 UTC
I have been trying to sign up [](https://www.freecodecamp.org/email-sign-up/) using this link for the past few days. However, I keep getting a "Something's not right" error every time I try to sign up. I have attached the image below. The user might get frustrated and may lead to a loss of potential customers willing to sign up. 

![signUp](https://user-images.githubusercontent.com/52804384/120957495-c2263a00-c723-11eb-979d-43d7f599189d.JPG)

The solution I would suggest is redirecting it to the regular sign up API. The regular sign up works but when I try to use this specific route I get the error. This is a solution that I have considered and have been working on. Please share your thoughts and ideas about this bug.

**Comment by ojeytonwilliams** [comment] 2021-06-07 05:38
Hi, @Brijesh2709 could you share a bit more context? Which page generates this error?

**Comment by Brijesh2709** [comment] 2021-06-07 15:19
Signing up from [https://www.freecodecamp.org/email-sign-up/](https://www.freecodecamp.org/email-sign-up/) triggers the error message above. When you are logged in this works fine. But when you are in a logged out state, trying to sign up for the email list I get this error message. Please do share your thought on a possible solution.

**Comment by raisedadead** [comment] 2021-06-08 07:28
Duplicate of #40772

**Closed by raisedadead** 2021-06-08 07:28 UTC
Labels: platform: client, type: bug
