### ISSUE TITLE
Application stuck on 'Using Objects for Lookups' challenge

### ISSUE THREAD

**Issue by Sliqric7053** [FreeCodeCamp/FreeCodeCamp#9898] opened 2016-07-26 16:43 UTC
#### Challenge
Using Objects for Lookups
https://www.freecodecamp.com/challenges/using-objects-for-lookups

#### Issue Description
Cannot progress to the next challenge although all conditions are met

#### Browser Information

* Google Chrome, Version: Version 51.0.2704.106 (64-bit)
* Operating System: Mac OSX v10.11.6
* Mobile, Desktop, or Tablet: Laptop

#### Your Code
```js
// Setup
function phoneticLookup(val) {
  var result = "";

  
  // Only change code below this line
  
  lookup = {
    alpha: 'Adams',
    bravo: 'Boston',
    charlie: 'Chicago',
    delta: 'Denver',
    echo: 'Easy',
    foxtrot: 'Frank'
  };
  
  result = lookup[val]; //must use [ ] notation if looking up variables
  // Only change code above this line
  
  return result;
}

// Change this value to test
phoneticLookup("alpha");

```

#### Screenshot

![screenshot 2016-07-26 18 39 56](https://cloud.githubusercontent.com/assets/7964516/17146887/78257330-5360-11e6-81a8-06921f7d636c.jpg)

**Comment by BKinahan** [comment] 2016-07-26 16:57
I can't reproduce this, your code runs fine and passes all of the tests. Can you try refreshing the page and running the tests again, @Sliqric7053 ?

**Comment by raisedadead** [comment] 2016-07-26 17:25
Isn't there one test case failing at the end.
> You should not use case, switch, or if statements

**Comment by Sliqric7053** [comment] 2016-07-26 17:46
Hi @BKinahan 

I refreshed the page, opened a new incognito window, and also tried Safari browser - the results are exactly the same as stated in the original issue.

However, I selected ALL the code and cut it, then submitted - the challenge passed!

Seems like a bug, but I am not sure if it's localized or general.

Anyway, thanks for the prompt response.

Best,
Rich

**Comment by qmikew1** [comment] 2016-07-26 17:58
Tested it as well (glad it self resolved) - I think the extra comment ```//must use [ ] notation if looking up variables``` was throwing it off. - Once that was removed tests passed

**Comment by raisedadead** [comment] 2016-07-26 18:27
Tagging as related duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9673
This will most likely get resolved soon with the new editor.

**Comment by Sliqric7053** [comment] 2016-07-26 18:41
Well that makes me happy to hear ;-)

**Comment by atjonathan** [comment] 2016-08-25 00:28
Closing as duplicate.

**Closed by atjonathan** 2016-08-25 00:28 UTC
Labels: blocked, duplicate
