### ISSUE TITLE
can't see the result of the codes

### ISSUE THREAD

**Issue by aa087159** [freeCodeCamp/freeCodeCamp#17319] opened 2018-05-31 05:50 UTC
I can't see the results of my codes  in the console on Freecodecamp.
The output of the function won't be showed on the console below the challenges.

**Comment by JustFly12** [comment] 2018-05-31 12:18
Please, can you provide information according to the issue template? Things like steps to reproduce, screenshots, challenge name you getting you seeing the issue on etc. Thank you!

**Comment by aa087159** [comment] 2018-05-31 13:06
Thank you for your reply, and the problem is that the console section won't
show the output of the function.
I want to see the sorted array [ 2,6,23,40,64 ] in the console, so it can
help me to see the problem clearer.

best regards,
Vivian

**Comment by jquint98** [comment] 2018-05-31 15:01
I am also having problems running my code on Microsoft edge. Whenever I press run the tests, it just stays on the same page and nothing happens.

**Comment by mstellaluna** [comment] 2018-05-31 19:28
@jquint98 MS Edge to my knowledge is not a supported browser. Please try in either Chrome or in FireFox and let us know if you are still having the issue.

**Comment by mstellaluna** [comment] 2018-05-31 23:59
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17356

**Closed by mstellaluna** 2018-05-31 23:59 UTC
