### ISSUE TITLE
Basic JavaScript: Escaping Literal Quotes in Strings - 1st test failing

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16331] opened 2017-12-27 00:17 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-javascript/escaping-literal-quotes-in-strings

#### Issue Description

the challenge code does not pass. 
Fails the first of the two tests.
Keeps stating "You should use two double quotes and found escaped double quotes.
I tried  browser refresh and tried challenge reset. Still same issue. 

As per @ncaron it also fails on the staging branch.

The same code does pass on the production version of the same challenge.

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js


`var myStr = "I am a \"double quoted\" string inside \"double quotes \"."; // Change this line`
```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34366899-6c8d47e8-ea70-11e7-9d94-dbc3cf351868.png)

**Comment by systimotic** [comment] 2017-12-28 23:05
Thanks for reporting this @mstellaluna! 

I accidentally opened a duplicate of this 😅 I'm closing this in favor of my duplicate #16344 because my duplicate has more background info and progress towards a fix.

Happy coding!

**Closed by systimotic** 2017-12-28 23:05 UTC
Labels: beta
