### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by mierla** [FreeCodeCamp/freecodecamp#639] opened 2015-05-27 15:10 UTC
First checkmark says: Wrap your all of your checkboxes inside one div with the class "row".
It should be: Wrap your text area and submit button inside one div with the class "row".

**Comment by terakilobyte** [comment] 2015-05-27 15:24
This is a duplicate of #621, but thanks for letting us know. It's been fixed and will go live soon.

**Closed by terakilobyte** 2015-05-27 15:24 UTC
