### ISSUE TITLE
multiple line comment invalid

### ISSUE THREAD

**Issue by CGDS** [FreeCodeCamp/FreeCodeCamp#3103] opened 2015-09-06 00:12 UTC
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code.

The regex used in the test won't match comments of the form
```javascript
/*
multiple line comment
*/
```

**Comment by bugron** [comment] 2015-09-06 04:00
@CGDS thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999 so I'll close this issue. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-06 04:00 UTC
