### ISSUE TITLE
Typed text starts on next line down from cursor click

### ISSUE THREAD

**Issue by Ascianous** [freeCodeCamp/freeCodeCamp#15092] opened 2017-05-28 07:55 UTC
Challenge [Create a Bootstrap Headline](https://www.freecodecamp.com/challenges/create-a-bootstrap-headline#?solution=%3Ch3%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This issue occurs on challenges where the code element occupies most of the height of the screen.
On loading a new challenge page, click on the coding window.  The vertical line indicating the current position of text writer appears.
Use any keyboard input.
Typing will jump to the line immediately below the original click and apparent position of the text writer (vertical line)

**Comment by raisedadead** [comment] 2017-05-28 14:21
Duplicate of #7847

**Closed by raisedadead** 2017-05-28 14:21 UTC
