### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by diyachetak** [FreeCodeCamp/FreeCodeCamp#6183] opened 2016-01-15 14:42 UTC
I am trying the exercise given for the above lesson. The link is given below:
http://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20myFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0A%0AmyFunction(1%2C%202)%3B

My solution looks to be correct but still the when the tests are run I get the error: "RangeError: Maximum call stack size exceeded"

I have googled this error and does not look to be possible for the below code which I have written in solution:
function myFunction(c, d){
  console.log(c + d);
 }
myFunction(1, 2);

**Comment by raisedadead** [comment] 2016-01-15 16:12
@diyachetak 

Your code passes all tests for me. I can't reproduce this.

Can you please try to:
1. Reset the code (Button on lest below Run tests).
2. Do a hard refresh of the page (Ctrl + 5).
3. Clear the browser cookies, and cache.

And see if this persists?
For further details you should have a look at [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) and the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

**Comment by diyachetak** [comment] 2016-01-15 16:40
Thanks. Miraculously it passed without doing any of the steps suggested.  Strange!

**Comment by raisedadead** [comment] 2016-01-15 17:09
Great!

**Comment by techjeffharris** [comment] 2016-01-16 13:19
I noticed this issue today with this particular challenge.  Refresh with F5 / Ctrl+r solved the problem for me with chrome Version 47.0.2526.106 (64-bit).

onward!

**Comment by hereswilson** [comment] 2016-01-16 17:42
Had same issue. Had to F5, then it worked.

**Comment by diyachetak** [comment] 2016-01-18 09:42
Thanks for the feedback. I will try this if I find the issue again elsewhere. In fact I tried "Reset" before logging this issue and that did not help. I should try F5 or Ctrl+r and see.

Thanks!

**Comment by bliski** [comment] 2016-01-20 09:10
Did already everything you mentioned above...but still `RangeError: Maximum call stack size exceeded` 
My code:
 function myFunction(w,y) {
  console.log(w + y);
}
myfunction(1,2);

**Comment by diyachetak** [comment] 2016-01-20 09:16
function myFunction(w,y) {
console.log(w + y);
}
myfunction(1,2); --> Is it a typo here?? It should be myFunction() rt?
Please check

**Comment by raisedadead** [comment] 2016-01-20 09:20
@bliski Yes @diyachetak Is correct, you do have a typo there.

However:
This issue is only reproducible when you try to visit someone else's solution link, like one in the issue description above, and replace their code with yours.

I checked this, and only way it works is if you visit a clean link, and do a HARD refresh, that's CTRL+F5.

A clean link for the challenge is : http://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments

Can you try that and confirm if my analysis is correct?

**Comment by bliski** [comment] 2016-01-20 09:28
Yes i passed through this link above, thanks a lot! But now i have issue with myself to understand this, can you please explain me why is it like this, i`m very curious! 
Thanks again!

**Comment by raisedadead** [comment] 2016-01-20 13:09
Yup, the scenario is when you visit someones solution link, your browser's cache gets pre-filled with a solution, that's fetched from, the URL you click, you can actually look at the URL an understand the solution is encoded in it, so what happens is when you replace your code in the editor, it may happen that there is an error while parsing the code, because some of the code was messed up due to the earlier link. 

But when you  do visit a clean link, and do a hard refresh, everything just resets, the code in the editor and cache, etc, is the actual code that should have come from the FCC servers, so when you replace your good code, it should pass.

My advice, is when you want to have a look at someone else's solution, prefer using the incognito mode, (right-click > open in incognito/private window).

With this your login wont be affected an you can still view the solutions, in a separate non conflicting window.

However, I want to stress that DO NOT use this as a trick to copy answers, its eventually going to be a lose at your end :wink: 

Happy coding!

**Comment by valbee** [comment] 2016-01-27 02:53
I just had this same issue. Refreshing the page helped solve the problem.

**Comment by Kachilero** [comment] 2016-01-29 22:05
Refreshing the page does clear this error, but contrary to @raisedadead it doesn't only happen when you visit someone else's answer. I got to this exercise from the "map" side menu and had this problem. I will concede however, that it is probably due to the browser cache.

May I suggest that perhaps the page could be set to catch "RangeError"s and display a notification that instructs people to refresh the page. This would save a lot of frustration for the users.

**Comment by raisedadead** [comment] 2016-01-30 05:57
@Kachilero Good point, this issue was probably before the UI change, when the Map Sidecar didn't exist if I am not mistaken. However, I can't seem to reproduce it, sadly. 

But, its definitely a good idea to give users some "form" of notification.
IMO, I would say, pop-overs or modals aren't good ideas, because I read in some of the discussions that we want to get rid of them.

Maybe, an alternate and simpler solution would be to give users the feedback in the console error message itself, along with the "RangeError" text.

But, since this is an UX thing, I guess it would take some approvals from @SaintPeter and others.

**Comment by PreciseAsteroid** [comment] 2016-01-30 18:14
had the same issue now. refresh solved the problem.

**Comment by cwkatzmann** [comment] 2016-02-03 03:04
+1 for this issue. Using the latest Chrome. Refresh solves the problem.

**Comment by raisedadead** [comment] 2016-02-04 18:16
Issue is fixed via #6681

**Comment by raisedadead** [comment] 2016-02-12 07:06
@BerkeleyTrue @erictleung Even this one is fixed :wink:

**Comment by BerkeleyTrue** [comment] 2016-02-12 07:09
@raisedadead :+1:

**Closed** 2016-02-12 07:09 UTC
