### ISSUE TITLE
Your form element should have the background-color of green.

### ISSUE THREAD

**Issue by navyvel** [FreeCodeCamp/FreeCodeCamp#3013] opened 2015-09-03 07:05 UTC
Challenge http://freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by navyvel** [comment] 2015-09-03 07:07
#cat-photo-element { 
    background-color: green;
  }

<form action="/submit-cat-photo" id="cat-photo-form">

all is good but the issue is
Your form element should have the background-color of green.
I think that it's no good!

**Comment by dmytroyarmak** [comment] 2015-09-03 07:28
Hello,
Your code is an example of using ID selector to add background:
```
#cat-photo-element { 
  background-color: green;
}
```

The solution for this challange is doing the same but with different ID like:
```
#cat-photo-form {
  background-color: green;
}
```

**Comment by navyvel** [comment] 2015-09-03 07:57
@Dmytro Yarmak
Right
thank's!

2015-09-03 10:28 GMT+03:00 Dmytro Yarmak <notifications@github.com>:

> Hello,
> Your code is an example of using ID selector to add background:
>
> #cat-photo-element {
>   background-color: green;
> }
>
> The solution for this challange is doing the same but with different ID
> like:
>
> #cat-photo-form {
>   background-color: green;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3013#issuecomment-137359557>
> .
>



-- 
ד"ר משה לוי
רופא פסיכיאטר
מנהל יחידת טיפול יום חיב"ה

**Comment by dmytro** [comment] 2015-09-03 09:02
@navyvel Apologies, you've probably got wrong Dmytro. You need  @dmytroyarmak

**Comment by bugron** [comment] 2015-09-03 11:56
@navyvel if your problem is solved feel free to close this issue, thanks!

**Comment by navyvel** [comment] 2015-09-03 12:02
ok

2015-09-03 14:56 GMT+03:00 Arsen Melikyan <notifications@github.com>:

> @navyvel <https://github.com/navyvel> if your problem is solved feel free
> to close this issue, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3013#issuecomment-137416523>
> .
>



-- 
ד"ר משה לוי
רופא פסיכיאטר
מנהל יחידת טיפול יום חיב"ה

**Closed** 2015-09-03 12:08 UTC

**Comment by saatishq** [comment] 2015-10-31 08:41
Hi! please check the snapshot. I have followed the instructions correct, but it still shows the error: "Your form element should have the background-color of green".
![codecamp_44](https://cloud.githubusercontent.com/assets/15331098/10862701/49519f9a-7fc4-11e5-9404-da35ae52e82d.JPG)

**Comment by ltegman** [comment] 2015-10-31 15:49
@saatishq It looks like you copied and pasted from the sidebar, which contains thin-space characters that invalidate your CSS markup. Try deleting that `#cat-photo-form` CSS declaration and typing it yourself.

Thanks and happy coding!

**Comment by rolikc** [comment] 2016-02-25 05:27
@saatishq and @ltegman Issue is not with Copy pasting, but rater with position of the id in the style. Move it in top of style, problem resolved. If you keep the id at the end of the style - problem is there
![image](https://cloud.githubusercontent.com/assets/17467157/13310702/51b3b5fe-db56-11e5-89f5-2eb5d786df14.png)

**Comment by mkhadnot** [comment] 2016-03-06 22:31
Can I get a shot of the form element section?

**Comment by saatishq** [comment] 2016-03-07 07:06
I have sorted the issue out. Thanks :)

**Comment by Wynterwolf** [comment] 2016-03-21 15:20
I don't know if this is the right place to ask or not, but why is it, when the code is placed at the top, it works but when placed at the bottom of the style section, it errors?

**Comment by ZGulman** [comment] 2016-06-19 14:36
I am running into the same issue. I have typed in on top, did not resolve the issue. please help.

**Comment by saatishq** [comment] 2016-06-19 15:16
@ZGulman  .. the key to solving the issue is, delete the custom lines and type it all over again. do not copy-paste any of the codes from the left panel. Hope it helps.

**Comment by 98newton** [comment] 2016-07-15 17:51
I'm having the same problem I've tried delete and retyping it and moving it to the top. Is there something in the form or Id area I should be typing in?

**Comment by Francesqua** [comment] 2016-07-19 22:55
![screen shot 2016-07-19 at 6 52 04 pm](https://cloud.githubusercontent.com/assets/20522523/16969308/f7eaa24a-4de1-11e6-8784-11f4d2896d92.png)

Add this code before the end of </style> -------->  #cat-photo-form {background-color: green;}
worked for me. :)

**Comment by Reicelo** [comment] 2016-08-20 14:26
it says make sure your form id has an attribute to me

**Comment by kayode16** [comment] 2016-09-15 23:13
@Francesqua it work ,thanks dear.

**Comment by iqu440** [comment] 2016-11-13 16:04
@saatishq  can u please give the screenshot of the assignment which has been done completly

**Comment by dhcodes** [comment] 2016-11-13 16:06
@iqu440 the issues area is not for discussing solutions to the coding challenges. Please ask for help in the [help chat room](https://gitter.im/FreeCodeCamp/Help)

**Comment by diegsoto6** [comment] 2016-11-22 21:47
the most important thing is to read what is ask, not about to copy and past, clear example this exercise 
show you this  ****#cat-photo-element {
  background-color: green;**** 

but is asking you to do give the FORM... here is
  #cat-photo-FORM {
    background-color: green;
}

READ FIRST AND THEN WORK :)

**Comment by NBrillhart10** [comment] 2016-11-30 21:31
All in the details thanks for the help

**Comment by astula01** [comment] 2017-01-17 01:26
diegsoto6, thanks for making me see that.  I can't believe I didn't notice after looking at it for so long.

**Comment by tka16** [comment] 2017-03-03 10:09
thanks s
