### ISSUE TITLE
"Title Case a Sentence" : strange outputs on two of the three tests while passing the all caps test case.

### ISSUE THREAD

**Issue by acarosell1** [freeCodeCamp/freeCodeCamp#13799] opened 2017-03-08 03:19 UTC
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
answer =[];  
var cased;
var fixed;
check = str.split(" ");


for (i=0; i<check.length; i++){ 
fixed = check[i].substr((1 - check.length),1).toUpperCase() + check[i].substr(1,(check.length -1)).toLowerCase();

  
answer.push(fixed);}

    

return answer.join(" ");
}
  
titleCase("sHoRt AnD sToUt");

```

**Comment by acarosell1** [comment] 2017-03-08 03:24
Hello.  It appears I may have found a bug on this challenge.  While my code passes the ALL CAPS test case,  The console outputs "Rho Nnd Uto" for the "sHoRt AnD sToUt" test case and "I'm A Tittl Tea Pot" for the "I'm a little tea pot" test case.  This really seems like a bug to me.  Please forgive me if I am mistaken here.

**Comment by Coby-T** [comment] 2017-03-08 05:32
The problem is not in the challenge. You have multiple instances of accessing the array/string indices that are inconsistent with what you are trying to do. You should use the help button in the challenge and ask for help in one of the chatrooms.

**Comment by erictleung** [comment] 2017-03-08 05:48
@acarosell1 Thank you for reporting this issue. Your code is slightly incorrect. Take a look at @Coby-T's advice.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Closed by erictleung** 2017-03-08 05:48 UTC

**Comment by acarosell1** [comment] 2017-03-08 23:43
Thank you.  I did visit the help chat room and did not receive any responses.  With some hesitation, I decided to report this issue as a potential bug.  While I am disappointed to discover that my code is erroneous, I appreciate you letting me know so I can attempt to create some fully correct code. Thanks again.
