### ISSUE TITLE
Challenge [Waypoint: Line up Form Elements Responsively with Bootstrap] - Text padding/margins off

### ISSUE THREAD

**Issue by trs4ece** [FreeCodeCamp/FreeCodeCamp#3815] opened 2015-10-20 06:01 UTC
Challenge [Waypoint: Line up Form Elements Responsively with Bootstrap](http://freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap)

The padding or margins around text in this challenge causes several issues.
* The text is not properly centered in the Like, Info, and Delete buttons in earlier parts of the waypoint before the FA icons are added
* The "delete" text runs off only showing "dele"
* The "loving" text overflows onto the next line

<img width="245" alt="capture" src="https://cloud.githubusercontent.com/assets/15202102/10599273/3f882dde-76b5-11e5-8316-4dbea7dbd0eb.PNG">

**Comment by bugron** [comment] 2015-10-24 17:43
@trs4ece thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2706 so I'll close this. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-24 17:43 UTC
