### ISSUE TITLE
I can't convert words into CSS style?

### ISSUE THREAD

**Issue by hianita** [FreeCodeCamp/FreeCodeCamp#7447] opened 2016-03-07 09:12 UTC
Challenge [Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by cannelflow** [comment] 2016-03-07 09:23
instructions are Delete your h2 element's style attribute and instead create a CSS style element. Add the necessary CSS to turn all h2 elements blue. and you deleted all of h2 tag reset the code and delete only style attribute there this is a basic question not a bug it is better to ask at FCC chat room https://gitter.im/FreeCodeCamp/Help before coming here

**Comment by hianita** [comment] 2016-03-07 09:44
Hi Kumar,

Thanks for  your help.
I am a beginner for programming, also the first time to join this group.
I am still not  clearly figure out the website.
Sorry for the bothering.
Thanks a lot!!!

​​
Anita

2016-03-07 17:25 GMT+08:00 Vinay Kumar <notifications@github.com>:

**Comment by bugron** [comment] 2016-03-07 09:46
@hianita thanks for posting. Closing as resolved.

**Closed by bugron** 2016-03-07 09:46 UTC

**Comment by cannelflow** [comment] 2016-03-07 11:08
np you are in right place happy coding journey
