### ISSUE TITLE
not clear statement

### ISSUE THREAD

**Issue by eliberator** [FreeCodeCamp/FreeCodeCamp#2042] opened 2015-08-18 09:34 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1- not clear statement "Add two div elements inside your div class="well"> element both with the class col-xs-6"
2 - the code checker works also if i put 2 <divs class=well" inside the first <div class="col-xs-6">

**Comment by saadanerdetbare** [comment] 2015-08-19 00:08
duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1968

**Closed** 2015-08-21 21:43 UTC
