### ISSUE TITLE
Foreign  language.

### ISSUE THREAD

**Issue by Maladez** [FreeCodeCamp/FreeCodeCamp#11639] opened 2016-11-13 08:23 UTC
From the beginning, you can make a choice of language. And then, the information will (could be)  appear according to the chosen language. If there is no translated information, then in English.

Probably it will be the Chaos

**Comment by erictleung** [comment] 2016-11-13 09:13
@Maladez thanks for the issue. This is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9697 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9696. Feel free to continue the conversation over on those issues and contribute if you can. Happy coding!

**Closed by erictleung** 2016-11-13 09:13 UTC
