### ISSUE TITLE
Sidebar map is distorted on high res monitors

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/FreeCodeCamp#6610] opened 2016-01-30 13:17 UTC
![image](https://cloud.githubusercontent.com/assets/10749142/12695900/c7545bd6-c753-11e5-9319-9502090c10c6.png)

**Comment by hallaathrad** [comment] 2016-01-30 13:37
being fixed right now at PR [#6592](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6592)... 
just waiting for the big boss to approve and merge :+1:

**Comment by bugron** [comment] 2016-01-30 13:39
@benmcmahon100 thanks for posting. Closing as a duplicate of #6564.

**Closed by bugron** 2016-01-30 13:39 UTC

**Comment by benmcmahon100** [comment] 2016-01-30 13:43
@bugron Oops! Awesome!
