### ISSUE TITLE
"color","orange" will fail, "color","FFa500" will pass.

### ISSUE THREAD

**Issue by MarcMcIntosh** [FreeCodeCamp/FreeCodeCamp#9311] opened 2016-06-23 05:36 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery

#### Issue Description

This will fail $("#right-well").children().css("color","orange");
This will pass $("#right-well").children().css("color","FFa500");

#### Browser Information

* Browser Name, Version: 
Chromium, 51
*user agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
* Operating System: 
Arch-Linux x86_64
* Mobile, Desktop, or Tablet:
Laptop

#### Your Code

```js
/* This will fail */
$("#right-well").children().css("color","orange");
/*This will pass */
$("#right-well").children().css("color","FFa500");

// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment] 2016-06-23 05:45
@MarcMcIntosh thanks for your issue. Unfortunately, I am unable to reproduce your error and both lines of code pass for me.

**Comment by heldersepu** [comment] 2016-06-23 15:38
Same here, I cannot  reproduce the error ...

**Comment by MarcMcIntosh** [comment] 2016-06-26 10:22
It works fine now that i've update chromium
userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by erictleung** [comment] 2016-07-01 08:31
@MarcMcIntosh sounds like your issue was resolve, so I'll close this issue. Happy coding!

**Closed by erictleung** 2016-07-01 08:31 UTC
Labels: blocked

**Comment by markymarc009** [comment] 2016-08-03 18:10
It would seem that this issue still exists, however I copy and pasted what was written here, (which is the same exact thing that I was typing in) and sure enough, I was able to continue.
