### ISSUE TITLE
Title Case a Sentence Bonfire not accepting my answer even though its correct. 

### ISSUE THREAD

**Issue by jorgon1022** [FreeCodeCamp/FreeCodeCamp#5362] opened 2015-12-19 07:05 UTC
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20a%3Dstr%3B%0A%20%20var%20lower%3Da.toLowerCase()%3B%0A%20%20var%20b%3Dlower.split('%20')%3B%0A%0A%20%20var%20result%3D'%20'%3B%0A%20%20for%20(var%20i%3D0%3Bi%3Cb.length%3Bi%2B%2B)%7B%0A%20%20%0A%20%20%0A%20%20c%3Db%5Bi%5D.charAt(0).toUpperCase()%2Bb%5Bi%5D.slice(1)%3B%0A%20%20%0A%20%20result%3Dresult%2B'%20'%2Bc%3B%0A%20%20%0A%7D%0A%20%20return%20result%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20liTtle%20tea%20pot%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var a=str;
  var lower=a.toLowerCase();
  var b=lower.split(' ');

  var result=' ';
  for (var i=0;i<b.length;i++){
  
  
  c=b[i].charAt(0).toUpperCase()+b[i].slice(1);
  
  result=result+' '+c;
  
}
  return result;
}

titleCase("I'm a liTtle tea pot");




```

When I enter this code, it is not accepting my cases. However, all my cases pass. Why wont it accept my answer?

Thank you

**Comment by SaintPeter** [comment] 2015-12-19 07:36
The problem is that you always have a leading space on your string.

For programming questions, please ask for help in the [Bonfire Help Room](https://gitter.im/FreeCodeCamp/HelpBonfires?utm_source=share-link&utm_medium=link&utm_campaign=share-link).  

Closing as this is not a site issue.  Thanks and happy coding!

**Closed by SaintPeter** 2015-12-19 07:36 UTC

**Comment by nethajireddy** [comment] 2016-06-21 04:24
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
