### ISSUE TITLE
Stand in line problem

### ISSUE THREAD

**Issue by kamilj62** [FreeCodeCamp/FreeCodeCamp#6342] opened 2016-01-20 07:56 UTC
Very confusing to understand what is required to answer this question.  The console.log statements should be removed or clarified what to do.  When I commented out the console.log statements it worked.  Very confusing

**Comment by erictleung** [comment] 2016-01-20 09:16
Duplicate of #5715.

**Closed** 2016-01-20 19:39 UTC
