### ISSUE TITLE
Video constantly buffers, will not play through (YouTube videos play well on my current internet connection)

### ISSUE THREAD

**Issue by kprenesti** [FreeCodeCamp/FreeCodeCamp#4808] opened 2015-11-30 14:11 UTC
Challenge [Zipline: Build a Random Quote Machine](http://www.freecodecamp.com/challenges/zipline-build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by SaintPeter** [comment] 2015-11-30 17:46
Unable to reproduce.  This is almost certainly related to your internet connection in some way.  Just refreshing the page may resolve the issue as well.

Closing as this is not a site issue.

Thanks and Happy Coding!

**Closed by SaintPeter** 2015-11-30 17:46 UTC
