### ISSUE TITLE
Music player - Step 70 - Adding example for ternary operator with an assignment

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55551] opened 2024-07-17 23:26 UTC
### Describe the Issue

in Step 70 of the music player project (js beta) the step requests a ternary statement that is assigned to a variable. People on the forum have a fair amount of struggles with this which is expected given that this may be the first time they are putting these two things together (ternary and assignment). But, now that I've personally moved  on to the spam filter project, I noted a curious thing. Step 5 of the spam filter project has a handy-dandy example of exactly the type of thing needed back in the music player project:

>Here is an example of assigning the result of a ternary operator to an element's text content:

>Example Code
>`el.textContent = condition ? "Use this text if the condition is true"`

We could have really used something like this example in step 70 of the music player!
So this issue is a request to consider adding a similar  example into step 70. A quick search for this step in the forum will show many examples of people struggling with this code's construction as further evidence of need.

I realise that this may make the text too long for step 70 though.

If the example is added, please modify it to include the 'else' section too. And maybe explain what is el. (el is the element reference)

Thanks for your help.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-70

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by naomi-lgbt** [comment] 2024-07-24 15:24
I think we can simplify the example to something like:

```js
const result = condition ? "I'm true" : "I'm false"
```

And say "here's an example of assigning the result of a ternary operator to a variable. now do this for the elements text contents."

**Comment by kevin-wu01** [comment] 2024-07-26 00:50
I started working on this and I was wondering how the localization is handled for the challenge markdowns? do I change one of the markdowns and run a script to apply it all?

**Comment by naomi-lgbt** [comment] 2024-07-28 21:50
You only need to update the English markdown. The rest are handled through Crowdin and our automated syncs.

However, this issue has not been marked as open for contribution yet.

**Comment by kevin-wu01** [comment] 2024-07-29 21:43
yeah I realized the issue is marked as discussing still, what more is needed to move the issue forward?

**Comment by naomi-lgbt** [comment] 2024-07-30 22:09
No one else has chimed in, so I'll go ahead and open it for contribution.

A PR which resolves this issue should apply my suggestion: https://github.com/freeCodeCamp/freeCodeCamp/issues/55551#issuecomment-2248297294

**Closed** 2024-08-07 03:42 UTC
Labels: type: bug, help wanted, scope: curriculum, new javascript course
