### ISSUE TITLE
Change the color of text

### ISSUE THREAD

**Issue by Tomaszenko** [FreeCodeCamp/FreeCodeCamp#10532] opened 2016-09-09 07:57 UTC
![bug](https://cloud.githubusercontent.com/assets/18270980/18379550/7454aae2-7673-11e6-9e98-7e8f340cd7ad.png)
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.

I've been trying to solve this, but I think everything is alright. I have no idea how to fix it.

`<h2 style="color:red">CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>`

**Comment by erictleung** [comment] 2016-09-09 08:17
@Tomaszenko your code works for me and looks good to me. Have you tried resetting your code and trying again? We've just pushed up changes to the site so it might be odd for a little bit.

**Comment by Tomaszenko** [comment] 2016-09-09 08:26
Yes, I tried reseting both by reseting code and clearing my browser but it has no effect.

**Comment by Akooij** [comment] 2016-09-09 10:03
I just encountered the same bug when using Firefox 48 on Ubuntu, but the same code works fine on Windows 10 with Chrome 53.

**Comment by erictleung** [comment] 2016-09-09 13:35
@Akooij thanks for checking with another browser. This and many of the other bugs may be because Firefox is unable to process the new changes pushed to the site. I don't have Firefox to reproduce this issue.

**Comment by dhcodes** [comment] 2016-09-09 17:25
Closed as duplicate of #10588

**Closed by dhcodes** 2016-09-09 17:25 UTC
Labels: blocked
