### ISSUE TITLE
Hex code Dodger Blue

### ISSUE THREAD

**Issue by OlivierCoq** [FreeCodeCamp/FreeCodeCamp#10612] opened 2016-09-09 18:09 UTC
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible. 

During the Hex Code challenge, the hex code for Dodger blue does not seem to be working. Multiple other Campers have reported the same issue on Gitter.

![dodgerbluebug](https://cloud.githubusercontent.com/assets/21243937/18397586/e1f6c71a-7696-11e6-8f84-226a88340bcf.png)

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1e90ff;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>



    ```

**Comment by Dave1089** [comment] 2016-09-09 18:21
Just adding up to it , took console log screenshot
![screen shot 2016-09-09 at 12 18 07 pm](https://cloud.githubusercontent.com/assets/5419729/18397986/e89d44c2-7687-11e6-866a-ee6eb1fdd45f.png)

**Comment by erictleung** [comment] 2016-09-09 19:11
@OlivierCoq thanks for the issue but this is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing in favor of older issue. Happy coding!

**Closed by erictleung** 2016-09-09 19:11 UTC

**Comment by OlivierCoq** [comment] 2016-09-09 21:07
Thank you Eric Leung!
