### ISSUE TITLE
Cant navigate through out the code window

### ISSUE THREAD

**Issue by BhaveshSGupta** [FreeCodeCamp/FreeCodeCamp#9788] opened 2016-07-19 13:30 UTC
Challenge [Style Text Inputs as Form Controls](https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am not able to navigate to the button tag of submit to add class there
It doesn't work when browser is initially loaded, and one try to navigate to the bottom. but if you delete any thing it can navigate to anywhere in the code. Even during this where ever the cursor is show when we type anything it gets typed at bottom.

The same problem is faced in next challenge too
My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by BhaveshSGupta** [comment] 2016-07-19 13:35
it doesn't work when browser is initially loaded, and one try to navigate to the bottom. but if you delete any thing it can navigate to anywhere in the code. Even during this where ever the cursor is show when we type anything it gets typed at bottom

**Comment by BKinahan** [comment] 2016-07-19 13:45
This is a duplicate of issue #7847. Please have a look through the comments there for more information and how to get around the problem.

**Comment by erictleung** [comment] 2016-07-19 15:06
@BhaveshSGupta as @BKinahan has mentioned, this is unfortunately a known bug. Please refer to the comments in that issue for work-arounds. Happy coding!

**Closed by erictleung** 2016-07-19 15:06 UTC
