### ISSUE TITLE
screen freezes with sass @while loop

### ISSUE THREAD

**Issue by pulamusic** [freeCodeCamp/freeCodeCamp#26252] opened 2018-10-22 18:42 UTC
**Describe your problem and how to reproduce it:**
Screen continually freezes when I try to do the @while challenge for sass. No matter how many times I close the page and then re-open, it freezes.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100
* Operating System: MacOS Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen shot 2018-10-22 at 2 39 32 pm](https://user-images.githubusercontent.com/25963105/47311730-84bf1d80-d608-11e8-84c0-7a973ba12dd6.png)

**Comment by pulamusic** [comment] 2018-10-22 18:50
I was finally able to do the challenge using Firefox. I am surprised Chrome let me down.

**Comment by Nirajn2311** [comment] 2018-10-22 18:53
@pulamusic according to the screenshot, you haven’t incremented the variable x so it ends up in an infinite loop. I’m not sure how you passed in Firefox, so could you post a screenshot or copy of your code here?

**Comment by procode200** [comment] 2018-10-23 00:47
I tried this in chrome and it works fine for me.

Issue should be closed.

**Comment by ArielLeslie** [comment] 2018-10-23 19:32
@Nirajn2311 - the problem is that the code auto-runs before the user has finished typing. If they write out the solution line-by-line in order the browser will freeze unless they type very quickly.

**Comment by procode200** [comment] 2018-10-23 20:56
This issue needs to be closed. just forget about it. Please close this issue.

**Comment by nathanhannig** [comment] 2018-10-23 23:41
sounds like the issue is resolved for user and workarounds have been given. Issue is related to user's code and not the challenge. Infinite loops are very common in coding.

**Closed by nathanhannig** 2018-10-23 23:41 UTC

**Comment by ArielLeslie** [comment] 2018-10-23 23:44
We have been getting complaints about this in the forum for months (this is the latest of a number of Issues created).

**Comment by procode200** [comment] 2018-10-24 00:18
@ArielLeslie We can all calm down now.

**Comment by nathanhannig** [comment] 2018-10-24 04:19
here is a forum post if it helps?
https://www.freecodecamp.org/forum/t/disable-code-auto-run-on-free-code-camp/19511
