### ISSUE TITLE
Show other ways to donate button style

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37310] opened 2019-10-15 14:58 UTC
**Describe the bug**
The 'Show other ways to donate' button looks like a link until you click on it, when it looks like a button.

**To Reproduce**
1. Go to /donate
2. Click on 'Show other ways to donate' 
3. See:
![ShowOtherDonate](https://user-images.githubusercontent.com/15801806/66843185-b729ff00-ef6c-11e9-97da-2b32c0c8e7ee.gif)

**Expected behavior**
I think it should always look like a button, since clicking on it modifies the page rather than takes you to a new one.

**Comment by vkWeb** [comment] 2019-10-15 18:20
@ojeytonwilliams I'll look into this.

**Comment by ojeytonwilliams** [comment] 2019-10-15 18:47
Thanks @vkWeb!  If you could check with Ahmad as to what he wants here before submitting a PR (since he's worked on the formatting very recently), that would be great.  I suspect he's a little busy right now, though, so I just put this issue here to keep track of it.

**Comment by vkWeb** [comment] 2019-10-15 19:17
@ojeytonwilliams Yeap. I'll talk to him after a day or two.

**Comment by vkWeb** [comment] 2019-10-15 20:16
@ojeytonwilliams Please assign this to me if possible.

**Comment by ahmadabdolsaheb** [comment] 2019-10-17 12:53
@ojeytonwilliams i see your concern with consistency, and this button looks like a link by design.

The behaviour is caused by the :focus state of the button.

@raisedadead, on a second thought this might not even be an issue. 
before the users click on the button, it looks like a link so they are not distracted from the main task.

but when users click on it, the focus state keeps the button more visible.
what do you think?

**Comment by raisedadead** [comment] 2019-10-17 13:03
The other ways to donate should be an actual link and styled as such not a button.

**Comment by ahmadabdolsaheb** [comment] 2019-10-17 13:15
@vkWeb, if you are still interested in working on this issue, could please go ahead with replacing the 'Show other ways to donate' button with an actual link with onClick={this.toggleOtherOptions}.

**Comment by vkWeb** [comment] 2019-10-17 13:20
@ahmadabdolsaheb Thanks! Going straight away to fix it.

**Closed** 2019-10-18 22:48 UTC
Labels: hacktoberfest, help wanted, platform: client, scope: user interface, type: bug
