### ISSUE TITLE
Show "Add this certification to your LinkedIn profile" button

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38195] opened 2020-02-10 19:06 UTC
As a camper, when I am logged in and viewing my own certification, I can see a button that says "Add this certification to your LinkedIn profile."

Once you've clicked it, it will use [the LinkedIn certification API](https://developer.linkedin.com/docs/guide/v2/people/profile-edit-api/certifications#) to add the certification to the campers' LinkedIn profile. And if possible, it should add freeCodeCamp to the education section of their profile so they are automatically added to freeCodeCamp's Alumni network: https://www.linkedin.com/school/free-code-camp/

**Comment by QuincyLarson** [comment] 2020-02-10 19:07
@ahmadabdolsaheb I am unsure of how much work this will require to incorporate it, so I am adding this to our roadmap and you can tackle it once you've finished more pressing features.

**Comment by raisedadead** [comment] 2020-02-11 07:25
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36277

**Closed by raisedadead** 2020-02-11 07:25 UTC
Labels: status: on the roadmap
