### ISSUE TITLE
Editor region not rendering after submitting a challenge

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49475] opened 2023-02-22 17:42 UTC
Originally reported by @hbar1st, the editor region doesn't render when camper submits a challenge.

https://user-images.githubusercontent.com/88248797/220710850-f7218e9b-d1b2-4372-a511-642b9bfbf5d9.mp4

This hide the instruction and lowerJaw, whenever this bug occurs

**Comment by bbsmooth** [comment] 2023-02-22 18:25
@Sboonny What browser/OS were you using to trigger this? I'm not able to replicate with either FF or Chrome on Windows/Linux. Or perhaps there is some trick to this that I'm not seeing in the video?

**Comment by Sboonny** [comment] 2023-02-22 18:46
To be honest, I don't think this is a browser specific. she mentioned that she used chrome, my guess is that somewhere in the JavaScript files, it has if statement that stop editor region from rendering, because previous PR do account for this failing.

The true solution is to findout, what changed and what isn't pleased.

Otherwise, we can add [error-boundry](https://github.com/bvaughn/react-error-boundary), that fallback to a basic component with instruction and submit button.

It won't have editor region, but it's better than the current nothing.

**Comment by hbar1st** [comment] 2023-02-22 19:16
my user agent info
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36</code>

**Comment by hbar1st** [comment] 2023-02-22 19:20
Here's a report on the forum with a similar issue (but on a different project) and the user had to move to their cell phone to complete the step https://forum.freecodecamp.org/t/i-cant-continue-my-progress-step-is-missing/591835/2

and a recent one with the same issue but again, different project and step:
https://forum.freecodecamp.org/t/building-a-coffee-menu-in-css/593693

**Comment by Sembauke** [comment] 2023-02-23 08:51
This should hopefully be fixed when #49281 gets in.

**Comment by hbar1st** [comment] 2023-02-23 09:16
Here is a brand new report of someone having the same issue on the forum

https://forum.freecodecamp.org/t/code-editor-is-not-showing/594091?u=hbar1st

**Comment by hbar1st** [comment] 2023-04-07 18:58
Another report of this issue:

https://forum.freecodecamp.org/t/bug-in-the-activity-impossible-to-perform/602758?u=hbar1st

**Comment by Stephen-254** [comment] 2023-11-23 06:59
The same issue has been reported.

https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-18/652151

**Comment by lasjorg** [comment] 2023-11-23 21:25
Usually, people can fix it by clearing the cache and closing and reopening the browser. Switching browsers also helps (likely for the same reason, fresh code).

I get the feeling that this bug might not be reproducible in dev mode. It also seems like skipping steps and returning to them later is somehow involved. But I'm not sure what the exact steps are.

Is there any information we can gather from people having this issue that can help debug it?

Should we try sending people to this issue so we can collect information?

**Comment by Sembauke** [comment] 2024-01-10 12:05
not reproducible. Feel free to open this issue again if it occurs.

**Comment by lasjorg** [comment] 2024-01-10 21:08
I don't think this is completed just because we can't reliably reproduce it.

It still happens, I have had it happen recently in one of the Python curriculum steps. I still have the step in the bugged state.

1. I'm not sure it is reproducible in dev mode.
2. I'm almost positive skipping steps, going back using the browser history (back button), and other such actions are involved.
3. It only affects a single step at a time. It is not like it happens and all your steps are broken. The one before and the next are fine.
4. Clearing the cache is not enough you have to clear the cookies and other site data (Chrome wording). The storage (`localStorage`, etc.) is cleared when doing so.


---

localStorage:


Chrome bugged - `editableContents` and `editableRegionBoundaries` are empty
```
[
    {
        "fileKey": "mainpy",
        "ext": "py",
        "name": "main",
        "contents": "my_graph = {\n    'A': [('B', 3), ('D', 1)],\n    'B': [('A', 3), ('C', 4)],\n    'C': [('B', 4), ('D', 7)],\n    'D': [('A', 1), ('C', 7)]\n}\n\ndef shortest_path(graph, start):\n    unvisited = list(graph)\n    distances = {node: 0 if node == start else float('inf') for node in graph}\n    paths = {node: [] for node in graph}\n    paths[start].append(start)\n    while unvisited:\n        current = min(unvisited, key=distances.get)\n        for node, distance in graph[current]:\n            if distance + distances[current] < distances[node]:\n                distances[node] = distance + distances[current]\n                if paths[node][-1] == node:\n                    paths[node] = paths[current]\n                else:\n                    paths[node].extend(paths[current])\n                paths[node].append(node)\n        unvisited.remove(current)\n    print(f'Unvisited: {unvisited}\\nDistances: {distances}\\nPaths: {paths}')\n    \n#shortest_path(my_graph, 'A')\n",
        "head": "",
        "tail": "",
        "editableRegionBoundaries": [],
        "history": [
            "main.py"
        ],
        "seed": "my_graph = {\n    'A': [('B', 3), ('D', 1)],\n    'B': [('A', 3), ('C', 4)],\n    'C': [('B', 4), ('D', 7)],\n    'D': [('A', 1), ('C', 7)]\n}\n\ndef shortest_path(graph, start):\n    unvisited = list(graph)\n    distances = {node: 0 if node == start else float('inf') for node in graph}\n    paths = {node: [] for node in graph}\n    paths[start].append(start)\n    while unvisited:\n        current = min(unvisited, key=distances.get)\n        for node, distance in graph[current]:\n            if distance + distances[current] < distances[node]:\n                distances[node] = distance + distances[current]\n                if paths[node][-1] == node:\n                    paths[node] = paths[current]\n                else:\n                    paths[node].extend(paths[current])\n                paths[node].append(node)\n    print(f'Unvisited: {unvisited}\\nDistances: {distances}\\nPaths: {paths}')\n    \n#shortest_path(my_graph, 'A')\n",
        "editableContents": "",
        "seedEditableRegionBoundaries": [
            12,
            23
        ]
    }
]
```

Chrome working - `editableContents` and `editableRegionBoundaries` have content.
```
[
    {
        "fileKey": "mainpy",
        "ext": "py",
        "name": "main",
        "contents": "my_graph = {\n    'A': [('B', 3), ('D', 1)],\n    'B': [('A', 3), ('C', 4)],\n    'C': [('B', 4), ('D', 7)],\n    'D': [('A', 1), ('C', 7)]\n}\n\ndef shortest_path(graph, start):\n    unvisited = list(graph)\n    distances = {node: 0 if node == start else float('inf') for node in graph}\n    paths = {node: [] for node in graph}\n    paths[start].append(start)\n    while unvisited:\n        current = min(unvisited, key=distances.get)\n        for node, distance in graph[current]:\n            if distance + distances[current] < distances[node]:\n                distances[node] = distance + distances[current]\n                if paths[node][-1] == node:\n                    paths[node] = paths[current]\n                else:\n                    paths[node].extend(paths[current])\n                paths[node].append(node)\n    print(f'Unvisited: {unvisited}\\nDistances: {distances}\\nPaths: {paths}')\n    \n#shortest_path(my_graph, 'A')\n",
        "head": "",
        "tail": "",
        "editableRegionBoundaries": [
            12,
            23
        ],
        "history": [
            "main.py"
        ],
        "seed": "my_graph = {\n    'A': [('B', 3), ('D', 1)],\n    'B': [('A', 3), ('C', 4)],\n    'C': [('B', 4), ('D', 7)],\n    'D': [('A', 1), ('C', 7)]\n}\n\ndef shortest_path(graph, start):\n    unvisited = list(graph)\n    distances = {node: 0 if node == start else float('inf') for node in graph}\n    paths = {node: [] for node in graph}\n    paths[start].append(start)\n    while unvisited:\n        current = min(unvisited, key=distances.get)\n        for node, distance in graph[current]:\n            if distance + distances[current] < distances[node]:\n                distances[node] = distance + distances[current]\n                if paths[node][-1] == node:\n                    paths[node] = paths[current]\n                else:\n                    paths[node].extend(paths[current])\n                paths[node].append(node)\n    print(f'Unvisited: {unvisited}\\nDistances: {distances}\\nPaths: {paths}')\n    \n#shortest_path(my_graph, 'A')\n",
        "editableContents": "    while unvisited:\n        current = min(unvisited, key=distances.get)\n        for node, distance in graph[current]:\n            if distance + distances[current] < distances[node]:\n                distances[node] = distance + distances[current]\n                if paths[node][-1] == node:\n                    paths[node] = paths[current]\n                else:\n                    paths[node].extend(paths[current])\n                paths[node].append(node)",
        "seedEditableRegionBoundaries": [
            12,
            23
        ]
    }
]
```


Is there anything else I should look at?

I'm almost positive if I clear the localStorage the bug will go away. But before I confirm that I will keep it as is in case someone has a suggestion for anything I should post that might help debug this.

Fairly sure, the order of the event was I skipped a step forward and used the back button. But I can't really remember and I don't know if I did anything else.

---


I suggest we keep this open to acknowledge the issue. As I suggested, it might be helpful if we gather information from people to help debug it.

**Comment by lasjorg** [comment] 2024-01-10 21:44
Weird, I just randomly reproduced it in my test browser. Clearing the `localStorage` fixed it. I can do it reliably.

With the dev tools open, completed the challenge, reset it, and resized the window by dragging the border.


https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/e373eef5-d5e9-4eeb-a75a-4f77a6ef018b



---

It looks like the same bug but it is triggered by the layout change which I hadn't seen before. I'm guessing the reload when going back to the previous challenge can trigger it as well.

**Comment by gikf** [comment] 2024-01-19 20:45
@lasjorg without your reliable way to reproduce, none of this would be possible. My findings doesn't show that submitting is necessary for the problem to appear. It's all in resetting challenge, with a twist. It's possible this is still not the original problem, but looking the same and caused by something different.

Reproducing:
1. Change anything in the initial contents.
2. Reset challenge.
3. `editableRegion` and `editableRegionBoundaries` are empty - invalid. This is the point when error _can_ appear.
4. Though everything still looks okay. At this point:
   - If anything is modified in editor contents - `editableRegion` and `editableRegionBoundaries` are going back to normal. Crisis averted! 
   - Any action that makes editor reload (if that's right word here) results in missing editable region. This includes layout change as shown above.


More code involved rundown:
1. Challenge is reset. `actionTypes.resetChallenge` action is performed - `editableContents` and boundaries are filled from seed. `isResetting` prop is set to `true`. https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/redux/index.js#L150-L173
2. Change of `isResetting` triggers effect https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/classic/editor.tsx#L1179-L1205
3. `resetEditorValues` is called. It changes the value (contents) of the _editor_ `model`, to the _initial text contents_. https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/classic/editor.tsx#L367-L377 
4. This triggers `onChange` of the Monaco editor.
https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/classic/editor.tsx#L1280-L1286 https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/classic/editor.tsx#L861-L888
5. `onChange` updates props of the challenge. Because `editableRegionBoundaries, the `getLinesCoveringEditableRegion` function uses the current state of the `model`, which just had contents changed. There's no editable regions (decoration ranges) that are relevant for that at this time. Therefore `editableRegionBoundaries` is empty array. https://github.com/freeCodeCamp/freeCodeCamp/blob/eaebde895d340458e0e1dc27657033bf4db11603/client/src/templates/Challenges/classic/editor.tsx#L955-L976
6. `actionTypes.updateFile` is performed, writing empty `editableRegion` and `editableRegionBoundaries` to props for the challenge.
7. I'm not entirely sure how's the timing for the other calls from the `isResetting` change effect. That effect triggers the change of `isResetting`. My tests suggests that `isResetting` is still `true` when `onChange` executes.
8. Bug is laying in wait.

**Closed** 2024-01-21 17:23 UTC
Labels: platform: learn
