### ISSUE TITLE
Add language translation missing message

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9697] opened 2016-07-12 18:35 UTC
As an user, when completing challenges in a non-english language and running into a challenge that does not have an active translation, I want a notification explaining that translation is being worked on, and the current one is missing. And invitation to contribute with it, perhaps?

Said notification should link to the translation repo's issues, with the respective language tags selected.

Active translations are translations of a challenge that is relatively up to date

**Comment by raisedadead** [comment] 2016-11-30 14:30
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9696 fixed via https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11545

**Closed by raisedadead** 2016-11-30 14:30 UTC
Labels: translation
