### ISSUE TITLE
Strange Code in Preview

### ISSUE THREAD

**Issue by cnfairfax** [freeCodeCamp/freeCodeCamp#12810] opened 2017-01-24 21:50 UTC
Challenge [standardize-times-with-the-html5-datetime-attribute](http://beta.freecodecamp.com/en/challenges/applied-accessibility/standardize-times-with-the-html5-datetime-attribute) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I'm not really sure how to recreate this. The preview is displaying information that isn't in the code-box. It appears to be doing this for several challenges. I've attached a snapshot from the lesson prior to this one. It's still persisting on this challenge.

[http://imgur.com/a/fcFRQ](http://imgur.com/a/fcFRQ)

```html
<body>
<header>
  <h1>Tournaments</h1>
</header>
<article>
  <h2>Mortal Combat Tournament Survey Results</h2>
  
  <!-- Add your code below this line -->
  
  <p>Thank you to everyone for responding to Master Camper Cat's survey. The best day to host the vaunted Mortal Combat tournament is Thursday, September 15<sup>th</sup>. May the best ninja win!</p>
  
  <!-- Add your code above this line -->
  
  <section>
    <h3>Comments:</h3>
    <article>
      <p>Posted by: Sub-Zero on <time datetime="2016-08-13T20:01Z">August 13<sup>th</sup></time></p>
      <p>Johnny Cage better be there, I'll finish him!</p>
    </article>
    <article>
      <p>Posted by: Doge on <time datetime="2016-08-15T08:12Z">August 15<sup>th</sup></time></p>
      <p>Wow, much combat, so mortal.</p>
    </article>
    <article>
      <p>Posted by: The Grim Reaper on <time datetime="2016-08-16T00:00Z">August 16<sup>th</sup></time></p>
      <p>Looks like I'll be busy that day.</p>
    </article>
  </section>
</article>
<footer>&copy; 2016 Camper Cat</footer>
</body>
```

**Comment by raisedadead** [comment] 2017-01-24 21:57
Yup confirmed. Thanks @cnfairfax !

![image](https://cloud.githubusercontent.com/assets/1884376/22268598/1ecdb2c4-e2ae-11e6-888d-f0242a59833d.png)

**Comment by patsul12** [comment] 2017-01-25 01:49
It looks like loop-protect is triggering on the copyright character towards the bottom of the exercise. Likely because of the semicolon.

With symbol:

![screenshot from 2017-01-24 19-47-40](https://cloud.githubusercontent.com/assets/6024604/22274806/37d0ba36-e26e-11e6-8ddb-8c075e04a2a3.png)

Without symbol:

![screenshot from 2017-01-24 19-46-58](https://cloud.githubusercontent.com/assets/6024604/22274807/3a80df4a-e26e-11e6-9f58-69f49ea31d8e.png)

**Comment by raisedadead** [comment] 2017-01-25 06:09
@patsul12 awesome! thanks for debugging this.

**Comment by tmashuang** [comment] 2017-01-25 10:19
In order to keep the symbol and not have loop-protect code I just removed the semicolon after the &copy.

**Comment by systimotic** [comment] 2017-01-25 11:17
I think there is a more fundamental issue with loopProtect running outside of Javascript code that should be fixed (see https://github.com/freeCodeCamp/freeCodeCamp/issues/12683, of which this issue is a duplicate, I think). 
@tmashuang Nice work on figuring out that the semicolon triggered loopProtect. We should probably dive into the source to see when it is activated.

**Comment by raisedadead** [comment] 2017-01-25 12:17
Yes, thanks @systimotic closing as a duplicate.

**Closed by raisedadead** 2017-01-25 12:17 UTC
Labels: beta, bug, help wanted
