### ISSUE TITLE
Bug in Line 3 not reading color blue " waypont

### ISSUE THREAD

**Issue by KeaDC** [FreeCodeCamp/FreeCodeCamp#4948] opened 2015-12-02 20:45 UTC
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

MY CODE :
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

ERROR: (Your h2 element should be blue.)

[Color blue issue.docx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/50173/Color.blue.issue.docx)

**Comment by ltegman** [comment] 2015-12-02 20:47
This is a duplicate of #4885. We have a PR in the works that will solve this.

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 20:47 UTC
