### ISSUE TITLE
iOS keyboard 

### ISSUE THREAD

**Issue by 7KAG7** [freeCodeCamp/freeCodeCamp#35078] opened 2019-02-06 17:23 UTC
When going from next challenge the next challenge won’t display the keyboard even after I click in the editor. iPhone 8+ iOS 12.2 beta

**Comment by raisedadead** [comment] 2019-02-06 17:35
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17386

**Closed by raisedadead** 2019-02-06 17:35 UTC
