### ISSUE TITLE
Chinese chat can't access to members-list

### ISSUE THREAD

**Issue by tianheg** [freeCodeCamp/freeCodeCamp#41322] opened 2021-03-01 11:44 UTC
**Describe the bug**
When access this [url](https://chat.freecodecamp.org/channel/zhongwen/members-list), it displays nothing.

**To Reproduce**
1. Go to '`https://chat.freecodecamp.org/channel/zhongwen/`'
2. Click on 'members-list'
3. See error

**Expected behavior**
Just display the members-list

**Screenshots**
<img width="950" alt="fcc" src="https://user-images.githubusercontent.com/52186032/109492585-29e63c80-7ac6-11eb-908c-6e6b584f758a.png">

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [chrome]
 - Version: [88(chrome), 20H2(win10)]

**Comment by nhcarrigan** [comment] 2021-03-01 13:48
Hey @tianheg thank you for reporting this. I am unable to reproduce this on my end. Could you confirm a couple of things for me:

Are you using the browser to access chat? Or are you using the desktop app? Have you tried a hard-refresh?

**Comment by tianheg** [comment] 2021-03-01 15:02
I'm using the browser to access chat. I am unable to reproduce it, too @nhcarrigan 😂

**Comment by gikf** [comment] 2021-03-02 10:44
This seems to happen when somebody is not in that certain channel  - didn't press the `Join` button.

It applies to other channels too. After opening members list after few seconds chat for that channel ends up blank, and page needs to be reloaded to be able to see chat (other channels displays normally).

**Comment by tianheg** [comment] 2021-03-02 11:10
@gikf Yes, what you said just same with my condition. I didn't click `Join`

**Comment by raisedadead** [comment] 2021-03-02 16:19
Not sure if we can do much about this until rocket chat adds a saner reload or something. I think we can close this for now?

**Comment by nhcarrigan** [comment] 2021-03-02 16:25
Yep - I think this one is out of our hands.

**Closed by nhcarrigan** 2021-03-02 16:25 UTC
Labels: platform: chat, type: bug
