### ISSUE TITLE
“Run the Tests” brings me two steps forward

### ISSUE THREAD

**Issue by DavidJamesAustin** [freeCodeCamp/freeCodeCamp#17709] opened 2018-06-24 17:52 UTC
#### Describe your problem and - if possible - how to reproduce it
I double clicked on the “run the tests” button and it brought me forward 2 steps when I clicked the button instead of just 1. It didn’t mark that skipped challenge as completed, just brought me to number 2.

#### Add a Link to the page with the problem
Happened on two pages so far. Doesn't seem to be a page specific issue.

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.0.3
* Operating System: Mac OS

**Comment by zsoltime** [comment] 2018-06-24 20:28
Do you click twice on the "Run the Tests" button or the "Submit and go ..." button? I could not reproduce it. Neither in Chrome, nor in Safari.

**Comment by DavidJamesAustin** [comment] 2018-06-24 20:33
Honestly, I forget.

**Comment by huyenltnguyen** [comment] 2018-10-27 09:52
Looks like the issue has been resolved, so I'm closing it now.
Thank you for reporting the issue and happy coding!

**Closed by huyenltnguyen** 2018-10-27 09:52 UTC
