### ISSUE TITLE
No image at coding challenge "Add a Text Alternative to Images for Visually Impaired Accessibility"

### ISSUE THREAD

**Issue by sondregi** [freeCodeCamp/freeCodeCamp#41130] opened 2021-02-15 15:24 UTC
**Describe your problem and how to reproduce it:**
No image at coding challenge 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility

**Tell us about your browser and operating system:**
* Browser Name: Brave
* Browser Version: V1.20.103
* Operating System:  MacOS Big Sur v11.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1365" alt="Skjermbilde 2021-02-15 kl  16 22 34" src="https://user-images.githubusercontent.com/18233699/107964845-0beae900-6faa-11eb-99fb-b8a18c903f01.png">

**Comment by RandellDawson** [comment] 2021-02-15 15:35
Duplicate of issue #41131, so closing.

**Closed by RandellDawson** 2021-02-15 15:35 UTC
Labels: duplicate, scope: learn
