### ISSUE TITLE
Improper behavior when we click on the "Submit" tab from the HTML section

### ISSUE THREAD

**Issue by adachenski** [freeCodeCamp/freeCodeCamp#18192] opened 2018-09-28 07:13 UTC
#### Preconditions
1. Navigate to "https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-form-field-accessibility-with-the-label-element/"
2. Or Navigate to: https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility/
3. Or Navigate to: https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/add-an-accessible-date-picker/

#### Steps To Reproduce
1.  See the HTML section on the right
2. Click on the "Submit" tab

#### Expected Result
On step 2 Nothing should happen

#### Actual Result
After we click on on the "Submit" tab
On our HTML section is open a brand new session of the same HTML page
If we keep clicking on the submit button we can have as many nested sessions as we want
#### Images
 [Initial screen img](https://drive.google.com/file/d/1uiuPoCvGaoJjf5p9DMoOwbv1EtOWDctr/view?usp=sharing)
 [one nesting img](https://drive.google.com/file/d/1gqhamP42eu_GYywxJQUFXx26BrmyuTWj/view?usp=sharing)
 [multiple nestings img](https://drive.google.com/file/d/18wL0PoGN6IPjr58JWjt7ugsPe0Ptf2hq/view?usp=sharing)

#### Operating system
* Browser Name: Chrome
* Browser Version: 69
* Operating System:  Windows 10

**Comment by siddhantvirus** [comment] 2018-10-02 16:38
The issue exists and is reproducible every time.
There seems to be an issue with the HTML compiler.

**Comment by ArielLeslie** [comment] 2018-10-02 20:46
What it's doing appears super weird because of how submit buttons work. Since this is just a lesson in creating HTML, there is no actual form handler defined. We *could* add a note in the instructions telling users not to worry about what happens when someone clicks "submit" yet.

**Comment by siddhantvirus** [comment] 2018-10-03 03:05
@ArielLeslie I understand the same .But if we could modify the form action attribute to not echo the and perhaps show the submitted date,it'll make it easier and not lead to recursions which might eventually crash if someone pulls in too many requests.

**Comment by RandellDawson** [comment] 2019-02-21 04:46
@adachenski, @siddhantvirus Can you test out the same challenges for this issue on our latest beta version?  We have made many improvements and are validating it before moving to the production site.

Here the same lessons on the beta site:

https://www.freecodecamp.rocks/learn/responsive-web-design/applied-accessibility/improve-form-field-accessibility-with-the-label-element

https://www.freecodecamp.rocks/learn/responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility

https://www.freecodecamp.rocks/learn/responsive-web-design/applied-accessibility/add-an-accessible-date-picker

Thanks.

**Comment by moT01** [comment] 2019-05-06 12:44
Thank you for reporting this issue.

This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed in staging. This means that the next time we push our staging branch to production, this problem should be fixed. Because of this, I’m closing this issue.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding.

Viewable on [beta](https://www.freecodecamp.rocks/learn/responsive-web-design/applied-accessibility/improve-form-field-accessibility-with-the-label-element)

**Closed by moT01** 2019-05-06 12:44 UTC
Labels: scope: curriculum, ux: user interface
