### ISSUE TITLE
Waypoint missing instructions

### ISSUE THREAD

**Issue by warkentien2** [FreeCodeCamp/FreeCodeCamp#2725] opened 2015-08-26 05:25 UTC
Object Oriented Waypoints, and many other http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce are missing the instructions,

I (as 99% of all other campers that completed it) am just deducing the instructions from the 'assert test error messages'. But, thinking on behalf of future campers, I'm just letting you know (and I believe you already do).

**Comment by BerkeleyTrue** [comment] 2015-08-26 05:37
Closing as duplicate of #2723

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-26 05:37 UTC

**Comment by LuckyOreo** [comment] 2015-09-17 02:40
I am not sure if this was fixed.  It is not a matter of the tests disappearing, but rather this waypoint description just being incomplete.  This description in this waypoint is just an example of reduce, but does not tell the user what the task at hand is.  It would be helpful to add at the end of the description something like "Use the reduce function to condense the array and store the result in singleVal variable"
