### ISSUE TITLE
Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement - Get A Hint - Missing Link

### ISSUE THREAD

**Issue by TantienHime** [freeCodeCamp/freeCodeCamp#36095] opened 2019-05-20 16:08 UTC
**Describe your problem and how to reproduce it:**
On the lesson for "Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement", when I click on the link for "Get A Hint", I get a 404 error. I also note, that when the page first loads, the message appears in the top left corner, and on hover, it recenters to the middle of the page, shown in the attached screenshot.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: MacOS Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2019-05-20 at 12 04 42](https://user-images.githubusercontent.com/6810025/58035805-906bb780-7af7-11e9-9017-61b6dccf1d3d.png)

**Comment by RandellDawson** [comment] 2019-05-20 19:52
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36062

This has been resolved on master but has not been deployed to production.

**Closed by RandellDawson** 2019-05-20 19:52 UTC
