### ISSUE TITLE
submit button in React's Create a Controlled Form Challenge renders new window

### ISSUE THREAD

**Issue by gunasai** [freeCodeCamp/freeCodeCamp#37212] opened 2019-10-11 14:52 UTC
**Describe the bug**
In the Create a Controlled Form Challenge, a new window with the challenge is rendered upon clicking on the submit button.

**To Reproduce**
1. Go to the challenge 'Create a Controlled  Form'
2. Click on Submit in the output window
3. See the new Challenge window render

**Expected behavior**
Expected behavior: Print the values entered in the form element.

**Screenshots**
<img width="1680" alt="Screen Shot 2019-10-11 at 10 46 54 AM" src="https://user-images.githubusercontent.com/32797567/66661336-d515fd80-ec14-11e9-8589-e62b1cb25cd4.png">

**Desktop (please complete the following information):**
 - MacOS 10.15
 - Firefox

**Comment by ojeytonwilliams** [comment] 2019-10-11 14:57
Hey @gunasai thanks for the report!  Could you see if the problem can be reproduced the beta site, [here ](https://www.freecodecamp.dev/learn/front-end-libraries/react/create-a-controlled-form)?  As far as I can see this problem has been fixed there, just not in production.

**Comment by gunasai** [comment] 2019-10-11 14:57
> Hey @gunasai thanks for the report! Could you see if the problem can be reproduced the beta site, [here ](https://www.freecodecamp.dev/learn/front-end-libraries/react/create-a-controlled-form)? As far as I can see this problem has been fixed there, just not in production.

**Comment by gunasai** [comment] 2019-10-11 14:58
Yes, It's not a problem in the beta site.

**Comment by ojeytonwilliams** [comment] 2019-10-11 15:11
Thanks for taking the time to confirm that.

I'm closing this since this problem will be fixed when master makes it into production.

**Closed by ojeytonwilliams** 2019-10-11 15:11 UTC
Labels: type: bug
