### ISSUE TITLE
Erroneous behavior in "Specify How Fonts Should Degrade" challenge

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#12350] opened 2017-01-04 02:19 UTC
#### Challenge Name

[Challenge Link](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20%3C!--h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D--%3E%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A)

#### Issue Description

The challenge aims to show how fonts degrade to the available one, if the specified fonts are not available. However, if you embed the `h2` styles inside the stylesheet within HTML comment tags, like so - 

```
  <!--h2 {
    font-family: Lobster, Monospace;
  }-->
```

The test passes. 

This seems odd, because HTML comments `<!--`> `-->` should have no effect inside embedded style sheet. Newer browsers just ignore the HTML comment tags in the stylesheet, [as per the spec](https://www.w3.org/TR/html4/present/styles.html#hiding), so placing comment tags in there shouldn't make any difference. This behavior can be seen in [this pen](http://codepen.io/anon/pen/QdWxEM), where placing comment tags around the `h2` in the stylesheet makes no difference to the `Lobster` font on `h2`. The same behavior is visible in the challenge page too.

Yet, it looks like placing the comment tags around `h2` inside style tags seems to have acheived the desired result.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 55.0.2883.87 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
 
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  <!--h2 {
    font-family: Lobster, Monospace;
  }-->

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
#### Screenshot

![aa](https://cloud.githubusercontent.com/assets/11348778/21629903/488408bc-d1fa-11e6-9f64-1de7f6187d08.png)

**Comment by systimotic** [comment] 2017-01-04 23:10
Good catch @Manish-Giri! 
The tests for this challenge are [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12366). The tests are only checking for an opening comment tag and a closing comment tag. They don't look at what's in between at all (apart from whether it's a comment automatically generated by our code).
The test should be adjusted to check whether it's actually the link element that is commented out.
These tests also use `regex.test(code)` rather than the usual `code.match()`. While we're at it, it would be a good idea to fix that too.

**Comment by systimotic** [comment] 2017-01-07 19:52
I was talking to @suhussai on Gitter. He's working on a fix for this.
While we were talking, we realised that instead of commenting out the link, it might be better to ask the campers to remove it. This makes the tests easier, and is probably also easier to do for campers. If they do comment it out, the test will still pass.
The description would also have to be changed from "Now comment out your call to Google..." to "Now remove your call to Google..."

I can't really think of any downsides to this approach, but I maybe missing something, so I'd like to confirm.

/cc @FreeCodeCamp/moderators

**Comment by raisedadead** [comment] 2017-01-08 13:03
Yup. This should be okay, and less confusing.

**Comment by erictleung** [comment] 2017-01-08 19:23
Agreed. I think the intention was to show the effects of quickly removing the font import with a comment. But changing it to just simply removing the font import should be easier on testing.

**Comment by Manish-Giri** [comment] 2017-01-08 19:30
Just a side note - the very next challenge does have the Lobster font and URL again, so maybe the current challenge could be reworded, so that removing the Lobster URL here and seeing it appear in the very next challenge does not lead to confusion.

**Comment by raisedadead** [comment] 2017-01-08 23:12
Should swapping the challenge be better?

**Comment by kcscott88** [comment] 2017-01-10 03:15
Update: This challenge now has mutually exclusive criteria, thus making it impossible to pass (it want's me to comment out Lobster while simultaneously making Lobster the primary font).

**Comment by yunder** [comment] 2017-01-10 04:11
I cannot get past this test. I have followed the instructions--is it a bug? (I have commented out the link to Google's Lobster font by surrounding the link with ; and I have specified that h2 should have Monospace as the alternate font should Lobster not be available

**Comment by kcscott88** [comment] 2017-01-10 06:43
yunder, I figured a workaround to get you to pass this challenge (probably not how you'd actually want to achieve this on a real-world project)

you need one line of code with  commented out and an additional (somewhat redundant) line that is the exact same, but without commenting out lobster.

**Comment by kcscott88** [comment] 2017-01-10 06:44
it should look like this

  h2 {
   font-family: Lobster, Monospace;
  }

  h2 {
    font-family: , Monospace;
  }

**Comment by raisedadead** [comment] 2017-01-10 07:34
@kcscott88 @yunder thanks for your comments, but the instructions are pretty clear in the challenge, and yes we have some buggy tests here, we are working on the best possible way to handle fix for this.

Requirements of the challenge are stated in the opening post. @kcscott88 apologies but I have removed your work around solution in the comments above, we do not seek to teach that to campers, partly because it's an incorrect approach for this issue.

The challenge not passing is a bug, and we would be fixing it.

**Comment by yunder** [comment] 2017-01-11 00:28
@raisedadead @kcscott88 Thanks to both of you. To be clear, there is now nothing I can do to move beyond this challenge at this time? I gave up last night because that seemed to be the case. I would really like to get back to work tonight! Last night was my first time learning html, css stuff. Ever. So I guess I should feel good that I knew I wasn't wrong :-) How will I know when I can get back to the challenge?

**Comment by raisedadead** [comment] 2017-01-11 02:51
@yunder no you should be able to pass the challenge with what the instructions state, we are discussing a special case over here that Manish has posted.

Can you share your code with us, to understand your specific issue?

**Comment by yunder** [comment] 2017-01-11 20:08
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by yunder** [comment] 2017-01-11 21:36
@raisedadead I don't know whether what I pasted above is what you wanted to see. I am sure I followed the instructions exactly. I made sure that my h2 listed Lobster and Monospace, and I commented out the link to Google's lobster font so that the font would "degrade" to Monospace. That is what the instructions said to do. I've tried everything: refreshing, asking for help in the chat room, and on here. Is it because I'm on a Mac?

**Comment by raisedadead** [comment] 2017-01-12 04:54
@yunder your code is 100% correct, it could be because you may have the font installed on your mac. In which case as you would see, the browser would locally find the font from your mac, and not bother about getting it from Google.

Can you check in your preferences, and uninstall the Lobster font if you have it installed?

**Comment by suhussai** [comment] 2017-01-12 05:40
@yunder, which test is it that's failing for you? I ran your code and all the tests passed. Or are you facing a different issue?

**Comment by yunder** [comment] 2017-01-12 15:09
@raisedadead I'll try to do that. @suhussai I cannot get past the "Specify How Fonts Should Degrade" challenge. raisedadead's suggestion makes a lot of sense. I'm very new to all this (as in this week is my first week doing anything like this), so I apologize for not understanding things like fonts in preferences, etc. To be clear, I would need to uninstall a font from my computer in order to move past this challenge, right?

**Comment by raisedadead** [comment] 2017-01-12 15:29
> To be clear, I would need to uninstall a font from my computer in order to move past this challenge, right?

Yes. Perfectly correct...! :sweat_smile: 

Goodluck and happy coding!

**Comment by yunder** [comment] 2017-01-12 15:29
@raisedadead The Lobster font is not installed on my Mac. I'm not sure what's wrong. Is there some other way I can get past this challenge (since my code is good)?

**Comment by Manish-Giri** [comment] 2017-01-12 15:38
@yunder Worth a shot, can you visit this [link](https://gitter.im/FreeCodeCamp/Help) and post your complete challenge URL from the browser? Click "run tests" first.

**Comment by systimotic** [comment] 2017-01-12 16:56
@yunder Manish's suggestion is great way to figure out what your problem is. If you want to continue working in the meantime, clicking the logo on the top left of the page should take you to the next challenge.

**Comment by yunder** [comment] 2017-01-13 00:17
@systimotic & @Manish-Giri I just posted it to the link you suggested. If I go onto the next challenge, will I be penalized for having not "officially" passed this one down the road?

**Comment by dhcodes** [comment] 2017-01-13 01:14
@yunder only the challenges with the asterisks are required to earn the certificates.

**Comment by zeyergit** [comment] 2017-01-25 22:49
@kcscott88 
thanks for your suggestion about adding the redundant line of code.
i added the following and was able to pass the test:
 h2 {
    font-family: , Monospace;
  }
  h2 {
    font-family: Lobster, Monospace;
  }

One of the questions I had was where to put the comma after Lobster - before the comment out characters or after. I did it this way and it worked.

**Comment by Scorialimit** [comment] 2018-01-03 05:36
Hello, I've been encountering the same problem on firefox and decided to switch to Chrome, and it worked like a charm. I think attempted it on Internet Explorer and did the same test to success there as well. 

[On Firefox (unsuccessful)](https://puu.sh/yTanM/76ad39526c.png)
[On Chrome (successful)](https://puu.sh/yTanf/8092bf38be.png)
[On IE (successful)](https://puu.sh/yTamP/ffa22a1b34.png)

I started on all three with the base code and simply commented out the link on all of them. I tested logged in and not logged in on all three browsers.

I'm effectively a newbie to code (started on C++ but didn't like the program as I felt I learned nothing) so I'm not of much use as to why the error happened, and I may be overlooking something, but I hope this information is helpful to somebody

**Comment by T1mL3arn** [comment] 2018-05-18 06:41
I finally have passed this challenge on a pure profile of Firefox. My main profile does not use page fonts but only fonts from my system (instead of the pure profile which certainly does). So I tried to disable page fonts for the pure profile and I could not pass the challenge again.

For Firefox users this can be a solution. There is [an instruction how to enable/disable using of page fonts in Firefox](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_custom-fonts).

**Comment by QuincyLarson** [comment] 2018-06-03 17:01
@Manish-Giri @systimotic This issue has been open for 18 months now. Is there a quick fix for this?

**Comment by convexhull** [comment] 2018-06-08 11:04
@QuincyLarson  Even I am facing the same problem. I have done everything and I am sure that my code is correct but it never passes the test.

**Comment by saifazmi** [comment] 2018-06-10 11:45
I'm facing a similar issue, where the font is not actually degrading on the browser preview i.e. still using the Lobster font and not monospace; even after commenting out the link to the Lobster font. The code is below:

```html
<!--
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
```

Should I create a new issue for this or is it part of this issue?

P.S. I have tested this behaviour on both firefox and chrome.

**Comment by Manish-Giri** [comment] 2018-06-12 02:37
@convexhull @saifazmi I just tried this challenge, and it passed for me -

![deg](https://user-images.githubusercontent.com/11348778/41266995-a0a337ba-6dc7-11e8-8ac0-a71a447fd38a.png)

![deg2](https://user-images.githubusercontent.com/11348778/41267063-f2daddc6-6dc7-11e8-93ab-3e794f9162da.png)


Could you attempt the challenge in a different browser and see if it works? If it still does not, post a screenshot of the challenge. It would help to identify the problem.

**Comment by saifazmi** [comment] 2018-06-13 09:38
@Manish-Giri the challenge does work for me, the issue is with the preview window itself. The tests work just fine.

**Firefox:**
![clipped-2018-06-13-10 34 16](https://user-images.githubusercontent.com/6190814/41343104-a0c95e66-6ef5-11e8-9086-0efab0edb33b.png)
**Chrome:**
![windowshot-2018-06-13-10 36 21](https://user-images.githubusercontent.com/6190814/41343131-b7af5d42-6ef5-11e8-8df5-04a2784c2b54.png)

In both the cases, you can see that it still renders the `Lobster` font.

**Comment by iamnijin** [comment] 2018-06-30 15:08
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  h2 { 
    font-family: Lobster;
  }
  h2
  {font-family:Lobster,monospace;}
  p {
    font-size: 16px;
    font-family: monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

**Comment by iamnijin** [comment] 2018-06-30 15:09
h2 { 
    font-family: Lobster;
  }
  h2
  {font-family:Lobster,monospace;}
  p {
    font-size: 16px;
    font-family: monospace;
  }

**Closed** 2018-10-21 15:11 UTC
Labels: help wanted
