### ISSUE TITLE
Duplicate element

### ISSUE THREAD

**Issue by shariquemaaz** [FreeCodeCamp/FreeCodeCamp#7660] opened 2016-03-20 07:54 UTC
After the clone() function challenge in JQuery, the button with ID target5 in #left-well is duplicated in all the challenges.

The first button is because of the JQuery statement whereas the second button is the duplicate copy
![capture1](https://cloud.githubusercontent.com/assets/17825112/13903395/d1516bc0-ee9e-11e5-8404-0013874573ac.PNG)

Browser: Google Chrome - version:49
OS: windows 7 ultimate

**Comment by N0bl3** [comment] 2016-03-20 14:00
Did you clear your browser cache?

**Comment by ltegman** [comment] 2016-03-20 14:34
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072. Thanks and happy coding!

**Closed by ltegman** 2016-03-20 14:34 UTC
