### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by kokuryu713** [FreeCodeCamp/freecodecamp#644] opened 2015-05-27 16:34 UTC
Although I followed instruction, it still shows error notification about syntax?

![screenshot 2015-05-27 23 28 54](https://cloud.githubusercontent.com/assets/12629852/7841687/a981cde4-04c8-11e5-80b1-aa539c49520f.png)

**Comment by terakilobyte** [comment] 2015-05-27 16:34
This is a duplicate of #585 and will be addressed soon, thanks for the report.

**Closed by terakilobyte** 2015-05-27 16:35 UTC
