### ISSUE TITLE
Problem with dead link??

### ISSUE THREAD

**Issue by Mohammadaliy00019** [freeCodeCamp/freeCodeCamp#13423] opened 2017-02-18 14:58 UTC
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a herf="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by atjonathan** [comment] 2017-02-18 17:03
Please provide more details on what challenge this issue is occurring, and what the issue is.

**Comment by JosephLivengood** [comment] 2017-02-20 23:35
Looks like an issue with the code supplied `<a herf="#">` should be `<a href="#">`. Going to go ahead and close this unless clarification of something else other than this comes up!

**Closed by JosephLivengood** 2017-02-20 23:35 UTC
