### ISSUE TITLE
Staging: Can't scroll all the way up map

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6564] opened 2016-01-29 05:51 UTC
![](https://www.evernote.com/l/AqT2LYIYAktANqbSoJ9VcRpJQdgyOO9cu90B/image.png)

**Comment by SaintPeter** [comment] 2016-01-29 05:59
Quincy, I can't reproduce this.

Are you certain that you rebuilt all the files when testing?  I think there may be an issue with the watcher in the gulpfile on some of the `*.less` files because sometimes when I was testing these changes I was not picking up new changes until I restarted gulp.

**Comment by SaintPeter** [comment] 2016-01-29 06:01
Here is what I see:
![image](https://cloud.githubusercontent.com/assets/553494/12668356/8d8a79a2-c60a-11e5-9e79-e4e21e71c3b8.png)

I note that the text in your screenshot looks too large to me.

**Comment by bugron** [comment] 2016-01-29 06:18
I can't reproduce this either:
![](http://i.imgur.com/6gMuQp6.png)

**Comment by hallaathrad** [comment] 2016-01-29 13:17
I can see the sidebar doesn't have the additional css changes to make things smaller, etc. It may be a previous commit, methinks... As I did amend the submission quite a few times.

**Comment by SaintPeter** [comment] 2016-01-29 17:36
@hallaathrad I checked on what was merged on Staging.  I don't believe those files are incorrect.  You can update your staging and check, but it looks right to me and Arsen.

**Comment by hallaathrad** [comment] 2016-01-29 17:39
Oh, I meant @QuincyLarson's local copy, @SaintPeter. The current staging should have what you and @bugron are seeing, based on your screen captures.
Double checking just in case, though.

**Closed** 2016-01-31 22:34 UTC
Labels: QA
