### ISSUE TITLE
It should be red

### ISSUE THREAD

**Issue by maxerd** [FreeCodeCamp/FreeCodeCamp#11964] opened 2016-12-07 20:09 UTC
I was doing a challenge and it keep saying I did not finish the challenge but I made no typos or misuse of code. I even asked it in the chat and even they said there was nothing wrong with it so I think there is a bug or something.

#### Challenge Name

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element

#### Browser Information

* Browser Name, Version: Chrome (version 54.0.2840.85)
* Operating System: android (CyanogenMod 12.1.1)
* Mobile, Desktop, or Tablet: mobile (OnePlus One)

#### Your Code

```html
 <style>
  .red-text {
    color: red;
 }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
 ```

**Comment by raisedadead** [comment] 2016-12-07 20:18
Your code is correct and passes for me. Please try resetting the code and typing it again, if your copy pasting for instance from a notepad, it's possible that some non-standard chars may creep in.

If it still doesn't work, try deleting your cache.

**Comment by systimotic** [comment] 2016-12-07 20:50
Hi @maxerd!
I see you're on a mobile device. We've had quite a few issues in the past with mobile devices inserting non-breaking spaces, which break the code. It was fixed recently in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11472, but it was not pushed to production yet. I believe this issue might be related to that same bug.

**Comment by raisedadead** [comment] 2016-12-08 07:22
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753

**Closed by raisedadead** 2016-12-08 07:22 UTC
