### ISSUE TITLE
(Failing Tests) Advanced Node and Express - Registration of New Users 

### ISSUE THREAD

**Issue by alexswiontek** [freeCodeCamp/freeCodeCamp#18201] opened 2018-09-30 20:55 UTC
#### Describe your problem and - if possible - how to reproduce it
My glitch app is failing for this section and is inconsistent. I even tried copying and pasting the code from [the GitHub Gist hint](https://gist.github.com/JosephLivengood/6c47bee7df34df9f11820803608071ed) and it fails differently each time. To replicate, I am clearing my db so that it is fresh for each time, however it fails for different reasons. See screenshots below.

#### Add a Link to the page with the problem
[Advanced Node and Express - Registration of New Users](https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 69.0.3497.100
* Operating System: macOS High Sierra 10.13.4

#### If possible, add a screenshot here
![screen shot 2018-09-30 at 1 53 54 pm](https://user-images.githubusercontent.com/15092959/46262608-5e4e0c80-c4b8-11e8-9ef1-e674793a6dcb.png)
![screen shot 2018-09-30 at 1 54 04 pm](https://user-images.githubusercontent.com/15092959/46262611-66a64780-c4b8-11e8-918c-81332962d548.png)
![screen shot 2018-09-30 at 1 54 18 pm](https://user-images.githubusercontent.com/15092959/46262613-6908a180-c4b8-11e8-8ab8-8dc03907c86d.png)

**Comment by alexswiontek** [comment] 2018-09-30 21:30
Additionally, [The Final Project](https://delicious-herring.glitch.me/) doesn't work either. After refactoring on the last step, the app no longer works 😕

**Comment by VulcanDev** [comment] 2018-09-30 22:46
+1 I have this issue as well and 'Create New Middleware' also fails to see the redirect that I even confirmed does happen by logging each visit in the console.

**Comment by alexswiontek** [comment] 2018-10-01 02:46
I think there are additional issues besides this tests, as have been addressed in #17068 and #17763.

For a clickable example you can see that in the challenge [Advanced Node and Express - Implementation of Social Authentication](https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/implementation-of-social-authentication) it provides starter code [on Glitch](https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-socialauth/) which when executed already starts with an error:

```js
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
```

**Comment by RistoYlem** [comment] 2018-10-30 20:04
I had the same problem, but after some searching I found a solution from stackoverflow https://stackoverflow.com/questions/19035373/how-do-i-redirect-in-expressjs-while-passing-some-context

Just add username to the session object, before the redirect line in the '/register' route,  like this:
`req.session.username = req.user.username;`

And then in the '/profile' route save the username into new variable and delete it from the session object.
`const username = req.session.username;
 delete req.session.username;
 res.render(process.cwd() + '/views/profile', {username: username});`

[Here's my Glitch project](https://glitch.com/edit/#!/node-express-pug-passport?path=server.js:83:68).
Hope it help, at least it worked for me.

**Comment by BTmathic** [comment] 2018-11-04 18:46
> +1
> 
> I have this issue as well and 'Create New Middleware' also fails to see the redirect that I even confirmed does happen by logging each visit in the console.
> 
> For reference, I am using the same version of Chrome but on Windows 10 Pro build 17763.1 with the project on Glitch.

I had this same problem but found a solution in the FCC [forums](https://www.freecodecamp.org/forum/t/advanced-node-and-express-create-new-middleware/212990/6?u=mathic) (and a linked, closed, GitHub issue). The test for checking if the page has redirected apparently does so by searching for the string 'Home Page' in the '/' route, so if you change your title variable to that it should work. (At least, it worked for the me and probably the other 11 people that 'liked' the post.)

**Comment by numoonchld** [comment] 2018-11-29 17:33
Facing the same issue, not passing all tests. 

<img width="925" alt="screenshot 2018-11-29 at 10 59 46 pm" src="https://user-images.githubusercontent.com/17598505/49240196-a6db6500-f42a-11e8-8846-fbc531e8b0b4.png">

Followed the code linked in the exercise: 
https://gist.github.com/JosephLivengood/6c47bee7df34df9f11820803608071ed

<img width="656" alt="screenshot 2018-11-29 at 11 02 47 pm" src="https://user-images.githubusercontent.com/17598505/49240328-eefa8780-f42a-11e8-9174-5a65d78b5db8.png">

**Comment by Farlokko** [comment] 2018-12-24 14:44
> > +1
> > I have this issue as well and 'Create New Middleware' also fails to see the redirect that I even confirmed does happen by logging each visit in the console.
> > For reference, I am using the same version of Chrome but on Windows 10 Pro build 17763.1 with the project on Glitch.
> 
> @VulcanDev
> 
> I had this same problem but found a solution in the FCC [forums](https://www.freecodecamp.org/forum/t/advanced-node-and-express-create-new-middleware/212990/6?u=mathic) (and a linked, closed, GitHub issue). The test for checking if the page has redirected apparently does so by searching for the string 'Home Page' in the '/' route, so if you **change your title variable to that** it should work. (At least, it worked for the me and probably the other 11 people that 'liked' the post.)

This solved the 'Create New Middleware' challange, thanks a lot!

**Comment by ibnthani2016** [comment] 2018-12-26 08:14
The problem 'solved' according to Farlokko above is not the challenge 'Registration of new users'

**Comment by JulianNF** [comment] 2019-04-02 16:27
I've spent the better part of the day trying to get my code to pass all the tests in the freeCodeCamp test suite for the Registration of New Users challenge, to no avail. 😢  Everything passes except for the "Registering should work" test. 😩 

I'm moving on to the other challenges as the code I have behaves perfectly well when tested manually. Hopefully this won't cause me even more frustration with the next challenges.

Before I move on however, I did notice something that I don't think I've seen anyone point out yet in any of the issue reports or FCC forum posts.

With a bunch of console logs at most of the critical steps along the way, I have noticed that in my code the failure seems to happen:

1. When the test suite creates a new user within the `/register` route handler, it is (as expected) redirected to the `/profile` route handler.
2. There, the first thing it encounters is the `ensureAuthenticated` function.
3. **When being redirected from the `/register` route handler to the `/profile` route handler, the test suite doesn't pass any user data (i.e. `req.user` is `undefined` within `ensureAuthenticated`)**. This does not happen when registering a new user manually.
4. As a result of this, the authentication fails because `ensureAuthenticated` has nothing to test.
5. Because of the authentication failure, the code redirects the newly created user to the `/` home page rather than to the desired `/profile` page.
6. (**This only happens with the test suite. This does not happen with manual testing**)

( I have tried enforcing delays on the request methods, I've updated the index and profile page titles and H1s, and tried to get the `req.session.username` "temporary" variable trick to work for me, etc.)

### Here's a copy of the log generated when running the test suite:
```
MongoDB successfully connected!
Listening on port 3000

requested
ensureAuthenticated called...
there's no req.user
... the user failed the authentication test. Redirecting to home page.
logging someone out.
User "freeCodeCampTester" tried to login.
We've created and added a new user to the DB: freeCodeCampTester
User "freeCodeCampTester" tried to login.
About to redirect new user "freeCodeCampTester" to /profile route handler.
ensureAuthenticated called...
there's no req.user
... the user failed the authentication test. Redirecting to home page.
```

### Here's a copy of the log when registering a new user manually:
(note that I have ternary operators on some console logs because of the aforementioned `undefined` issues)
```
MongoDB successfully connected!
Listening on port 3000

We've created and added a new user to the DB: Diana
User "Diana" tried to login.
About to redirect new user "Diana" to /profile route handler.
ensureAuthenticated called...
req.user.username is: Diana
... the user passed the authentication test.
Authenticated. Allowing "Diana" to access /profile .
```



(There are also a bunch of other annoyances with the testing for this challenge, among which is the need to use `res.render()` instead of `res.redirect()` in order for the `/login` route handler to pass one of the tests.)


PS: I'm quite frustrated by the later FCC certifications/modules and have found that I easily spend 50% of my time trying to understand the poorly written instructions or finding workarounds to pass faulty test suites. I've also noticed that unresolved issues about these topics have existed for at least 6 months now. Given that I don't like frustrating experiences, is there any way for myself and other users to actively contribute to improving the latter certifications/modules so that students after us don't also have to muddle their way through the (apologies, but frankly kinda terrible) last third of the curriculum? 😧

**Comment by ibnthani2016** [comment] 2019-04-04 07:52
hi JulianNF the 'solution'  to this problem is a workaround check #17820 for it .hope it helps.

**Comment by JulianNF** [comment] 2019-04-04 08:27
Hey @ibnthani2016, thanks for sharing that workaround. Unfortunately I tried @lucasMontenegro 's timeout trick and I couldn't get it to work for me, even after playing around with the delays extensively.

TBH though, by that point I was quite fed up of trying to get my code to work in a test suite when it works in the real world, you know?

As an update, not getting registration to work in the test suite for this challenge didn't cause me any problems with the following challenge's test suites.

**Comment by jeremyfiel** [comment] 2019-05-06 16:53
https://www.freecodecamp.org/forum/t/advanced-node-and-express-registration-of-new-users-updated-with-only-one-hack/274435

tons of missing requirements in the instructions provided on the challenge.  Hope it helps!

**Comment by moT01** [comment] 2019-05-06 18:03
Here's a hack I did a while back https://www.freecodecamp.org/forum/t/advanced-node-and-express-registration-of-new-users/208071/10 - This is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17820 - so this can be closed.

**Closed by moT01** 2019-05-06 18:03 UTC
Labels: scope: curriculum

**Comment by jeremyfiel** [comment] 2019-05-06 18:27
mine isn't a hack other than the delays by #17820.   The instructions were missing information about calling the req.logIn() method which returns the req.user data after serialization to populate the object which is passed to the front end.  Your hack of manually entering the username freeCodeCampTester works, but is incorrect because you are bypassing the middleware authentication and serialization of the user data. This is the entire point of using the middleware and authentication packages. 

To anyone else reading this:  If you are stuck on this challenge, I would encourage you to seek out the proper way to utilize the requirements presented in the challenge. You may learn a thing or two about how passport and serialization works rather than trying to blast through FCC challenges to get a certificate.

**Comment by tamerMarzouk** [comment] 2019-06-13 09:26
Here's how to pass those tests:
Add the word "Profile" in the body of profile.pug file. it will help you bypass this test:
`  - text: Registering should work
    testString: 'getUserInput => $.ajax({url: getUserInput(''url'')+ ''/register'',data: {username: ''freeCodeCampTester'', password: ''freeCodeCampTester''},crossDomain: true, type: ''POST'', xhrFields: { withCredentials: true }}) .then(data => { assert.match(data, /Profile/gi, ''I should be able to register and it direct me to my profile. CLEAR YOUR DATABASE if this test fails (each time until its right!)''); }, xhr => { throw new Error(xhr.statusText); })'`

If you are writing express route in a different format than this:
`app.route('/profile').post(`
The the following test will fail:
`  - text: Register route and display on home
    testString: 'getUserInput => $.get(getUserInput(''url'')+ ''/_api/server.js'') .then(data => { assert.match(data, /showRegistration:( |)true/gi, ''You should be passing the variable "showRegistration" as true to your render function for the homepage''); assert.match(data, /register[^]*post[^]*findOne[^]*username:( |)req.body.username/gi, ''You should have a route accepted a post request on register that querys the db with findone and the query being "username: req.body.username"''); }, xhr => { throw new Error(xhr.statusText); })'`
To bypass it you need to rewrite the post express handler in the form of `app.route('/profile').post(` or just add a comment in the post function that contain this `/profile post`
