### ISSUE TITLE
Closing tags indenting

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44620] opened 2021-12-30 00:58 UTC
## Affected page

Here are 2 examples:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-2
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-4

## Your code

Step 2
```

<head>
  </head>


```

Step 4
```

  <head>
    <meta charset="utf-8" />
    <title>Camper Cafe Menu</title>
  </head>
  <body>
    </body>

```

## Expected behavior

The closing tags do not align with the opening tag in some lessons after hitting ENTER. For example,  Steps 2 & 4. But the indenting is correct if you type the closing tag, insert your cursor between the two, then hit ENTER.

## Screenshots

![indent-bug](https://user-images.githubusercontent.com/66497948/147713383-79df68e6-04a6-4365-a73f-2ea1c3ae603b.PNG)

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

**Comment by gikf** [comment] 2021-12-30 05:49
This isn't limited to new curriculum or _Responsive Web Design_. This happens also in _Front End Development Libraries_. This seems to be how Monaco Editor behaves, I'm not sure if there's way to tune that.

**Comment by Kernix13** [comment] 2021-12-30 13:43
Got it. So should I click the Close issue button?

**Comment by gikf** [comment] 2021-12-30 15:07
I wouldn't close it just yet. I know just a little about the editor, others may know how this could be tackled. Just wanted to clarify the scope of the issue.

**Comment by ShaunSHamilton** [comment] 2022-01-03 11:53
Thank you, for taking the time to open this.

As @gikf mentioned, this is mostly expected behaviour, and we have not specifically coded this behaviour in the editor.

The only solution to this I am aware of is to include a plugin for HTML/CSS syntax. However, this would add unnecessary overhead to the build/client, and I do not think worth the effort.

Our general rule of thumb with the editor has been:
- Keep it as lightweight as possible

If you are interested in all the linting/autocompletion features that VSCode has, then we recommend using your local/offline editor for this. Some Campers like the autocompletion, others find it hinders their learning somewhat, and others find the numerous features too distracting.

As such, I am going to close this issue. Feel free to add more to this discussion, if you would like this issue reopened.

**Closed by ShaunSHamilton** 2022-01-03 11:53 UTC
Labels: status: discussing, platform: client
