### ISSUE TITLE
Issue with Golf Code Challenge

### ISSUE THREAD

**Issue by djokester** [FreeCodeCamp/FreeCodeCamp#12367] opened 2017-01-04 21:19 UTC
#### Challenge Name: Golf Code (JavaScript)

https://www.freecodecamp.com/challenges/golf-code

#### Issue Description

Challenge Solution is being accepted and passed despite missing semi-colon ";" in the code.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 55.0.2883.87 (64-bit)

* Operating System:  Ubuntu 16.10 
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js

function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes==1){return "Hole-in-one!";}
  else if(strokes <= par-2){return "Eagle";}
  else if(strokes == par-1){return "Birdie";}
  else if(strokes == par){return "Par";}
  else if(strokes == par+1){return "Bogey";}
  else if(strokes == par+2){return "Double Bogey";}
  else {return "Go Home!"}
  //Missing semicolon in the else statement above
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
 
 
```

**Comment by Dayfiri** [comment] 2017-01-04 22:38
@djokester 
[HERE](http://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi) you can see that JavaScript inserts semicolons automatically in specific cases.
That is not a bug but the way language works.

**Comment by systimotic** [comment] 2017-01-04 22:49
Hi @djokester! Thank you for reporting this issue.
Dayfiri's link has some good explanation as to why this can be seen as intended behaviour.
Bouncey responded in the other issue you opened about this (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12366), so I'm closing this as a duplicate. If you have any questions or anything else to say about this, it would be great if you could do it there, so that we have all the conversation in one place. Happy coding!

**Closed by systimotic** 2017-01-04 22:49 UTC
