### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by randyleighton** [FreeCodeCamp/freecodecamp#687] opened 2015-05-28 03:48 UTC
margin: 40px 20px 20px 40px;  this passed the test, this is not what it asked for,

**Comment by terakilobyte** [comment] 2015-05-28 11:02
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:03 UTC
