### ISSUE TITLE
React Challenge shouldComponentUpdate

### ISSUE THREAD

**Issue by SanD94** [freeCodeCamp/freeCodeCamp#16312] opened 2017-12-24 09:24 UTC
#### Challenge Name
React Optimize Re-Renders with shouldComponentUpdate

#### Issue Description
It seems submitted code true but there is a problem in last two tests resulting regular expression errors.
[Problem 1 async last part, assert](https://github.com/freeCodeCamp/freeCodeCamp/blob/16dcfb41833498e0a6efd788735b413900970817/seed/challenges/03-front-end-libraries/react.json#L2132)
[Problem 2 async last part, assert](https://github.com/freeCodeCamp/freeCodeCamp/blob/16dcfb41833498e0a6efd788735b413900970817/seed/challenges/03-front-end-libraries/react.json#L2133)

#### Browser Information
* Browser Name, Version: Opera 49.0.2725.64
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```js
class OnlyEvens extends React.Component {
  constructor(props) {
    super(props);
  }
  shouldComponentUpdate(nextProps, nextState) {
    console.log('Should I update?');
     // change code below this line
    return !(nextProps['value'] % 2);
     // change code above this line
  }
  componentWillReceiveProps(nextProps) {
    console.log('Receiving new props...');
  }
  componentDidUpdate() {
    console.log('Component re-rendered.');
  }
  render() {
    return <h1>{this.props.value}</h1>
  }
};

class Controller extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: 0
    };
    this.addValue = this.addValue.bind(this);
  }
  addValue() {
    this.setState({
      value: this.state.value + 1
    });
  }
  render() {
    return (
      <div>
        <button onClick={this.addValue}>Add</button>
        <OnlyEvens value={this.state.value}/>
      </div>
    );
  }
};
```
#### Screenshot
![image](https://user-images.githubusercontent.com/8544658/34325469-7a198a44-e8a3-11e7-9809-538ef33ef9f0.png)

**Comment by Bouncey** [comment] 2017-12-24 10:13
Thanks @SanD94 for raising this issue.

We need the two tests pointed out by @SanD94 fixed. They are currently malformed. This is just a syntax issue.

**Comment by no-stack-dub-sack** [comment] 2017-12-25 22:45
@Bouncey I think this and the other issues, like you said, should be simple syntax fixes. These were working when we first ported them over, but I think some of Berkeley's syntax changes (or my attempts to fix some of the formatting issues as a result of these changes), are responsible. 

This may be the base with any `async` test that has regexp, so maybe whoever takes on this issue can also run a quick search through the JSON for any `async` tests that have regexp to hopefully catch any remaining issues.

**Comment by SanD94** [comment] 2017-12-26 05:46
@no-stack-dub-sack Searching may not be needed because I solved all the challenges for React and found all issues related to `async` tests.

**Comment by StephenMayeux** [comment] 2017-12-27 15:39
I'll take a stab at this bug and then will create another issue addressing the tests with async.

**Comment by StephenMayeux** [comment] 2017-12-27 17:07
It was a very simple bug to fix. Please see my PR above. @SanD94 do the regex errors still persist for `async` tests in React challenges?

**Comment by SanD94** [comment] 2017-12-27 21:40
@StephenMayeux I don't know how to test your code unless it is merged with staging branch but it seems to solve this issue. You had better check other similar issues regarding react.js tests ( #16314, #16316) so that all of the problems with tests are solved.

**Comment by StephenMayeux** [comment] 2017-12-27 22:03
Shall I create different PRs for those other issues, or just wrap them up
into this PR?

sm

**Comment by SanD94** [comment] 2017-12-28 06:17
You can wrap them up because of their simplicity.

**Comment by no-stack-dub-sack** [comment] 2017-12-28 16:33
@StephenMayeux I see what you did now, and I have no idea how this even happened, clearly we didn't write the tests that way, was probably a result of a regex find and replace when the async assertion syntax was updated. But I agree with @SanD94, feel free to wrap these up in one PR.

@SanD94 you can always pull down someone else's branch to test their changes using these instructions found on the PR (they're instructions for merging via the command line, but the first couple of commands are just for checking out and testing:

![image](https://user-images.githubusercontent.com/18563015/34416674-88713ade-ebc2-11e7-8b5f-ce20e25f519e.png)

in this case:
```shell
git checkout -b StephenMayeux-fix/16312-React-Challenge-shouldComponentUpdate staging
git pull https://github.com/StephenMayeux/freeCodeCamp.git fix/16312-React-Challenge-shouldComponentUpdate
```
  
Also, @SanD94 you said you completed the entire react section, and these are the only problems you found? If so, that's good to know, we have not gone through them since these changes were made and I was wondering if any other problems would turn up. Did you also complete Redux and React-Redux, or just React? Thanks!

**Comment by SanD94** [comment] 2017-12-28 22:09
@no-stack-dub-sack  I did complete what you all mentioned. However, I didn't check the tests when sending wrong code which would give the expected error. I just know that when sending correct answers, tests accept them. Do we need something for each test to raise error?

By the way, thanks for the information, I'll do it when I have time :)

**Comment by StephenMayeux** [comment] 2017-12-29 15:31
@SanD94 Sounds good. I'll wrap this one up today. Thank you!

**Comment by r1chard5mith** [comment] 2018-01-12 02:41
Hi. I was looking at this, prompted by a user in the forum yesterday: https://forum.freecodecamp.org/t/issue-with-a-react-lesson-on-beta/168144

I was about to submit a (my first) PR for the fix to just this one challenge and then I found this thread. Did it get done or does it still need doing?

**Comment by raisedadead** [comment] 2018-01-12 21:40
Hi @r1chard5mith 

Thanks for your interest in contributing.

We have pinged @StephenMayeux on their PR for this issue #16341 , if they are unable to revert or update in a few days, please feel free to make a pull request.

However, please make a note of the discussion on the PR thread as well, so that we do not miss anything.

Also, we have several other open issues tagged help wanted if you are looking forward to working on an issue.

Happy contributing!

**Comment by StephenMayeux** [comment] 2018-01-13 00:26
@raisedadead @r1chard5mith I'm so sorry but I haven't checked my messages. This PR fixes #16341 but not the other two that were mentioned (#16316 and #16314). I cannot do those right now, so I recommend someone else take over. The fix for this one is really simple, it's just of matter of moving some JSON inside the right pair of quotes.

**Comment by r1chard5mith** [comment] 2018-01-13 00:40
OK, I'll take this and look at #16316 and #16314 in conjunction to see if they can all be done in one PR. If the other problems turn out to be materially different, should they be in separate PRs? 

@StephenMayeux - did you find a better way to test the tests than just to edit them inside the object and reload the whole app? I was hoping there might somehow be a way to extract them and then stuff them back afterwards.

**Comment by r1chard5mith** [comment] 2018-01-13 02:38
I found a weird problem with this and am looking into it now but I'm new here so if anyone can confirm, I'd appreciate.

I applied a fix to the test (function) string, the same as in this previous PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/16341/files

And noticed that the closing `};` was then rendered to the screen as part of the test message. Then I noticed that that the same thing seems to be happening with all the other 'async' functions in this section. You can see what I mean here: https://beta.freecodecamp.org/en/challenges/react/render-with-an-ifelse-condition

![screen shot 2018-01-13 at 1 36 42 pm](https://user-images.githubusercontent.com/7539224/34902004-d4c7ed14-f866-11e7-9a75-ce6c93a017dd.png)

What's really weird to me about this is that if I omit it, the function errors as expected but if I include it, it *both* closes the function and gets rendered ?? I guess it's something to do with the way the functions are packed into a string. Any ideas?

**Comment by r1chard5mith** [comment] 2018-01-13 04:26
Ok, well, I went ahead and pushed the fix for this. I tried to find the source of the other error I mentioned about but without luck - I suspect it needs to be fixed at the point that the tests are getting called (and I don't know where that is yet) rather than here - *or* it needs some sort of fancy character-escaping trick that I don't know. Should I file it as a new issue? (or maybe it already exists but I couldn't find it)

**Closed** 2018-01-16 05:55 UTC
Labels: beta, bug, help wanted, status: confirmed, type: tests

**Comment by r1chard5mith** [comment] 2018-01-16 07:06
I'm pretty annoyed that you closed this by taking the original pull request after telling me I could take it. Nobody replied to the comments I left above and now the issue is closed. There's no wonder this is a year behind schedule if you're squandering people's effort in this way.

**Comment by raisedadead** [comment] 2018-01-16 08:48
Hi @r1chard5mith , I understand that you are contributing for first time. I'll clarify your confusion.

> No, I don't understand, sorry. You changed my commit? 

Yes, we accepted a PR for this issue i.e #16312 made by @StephenMayeux i.e #16341
One of our contributors requested them to take the below two issues in conjuction to #16312

#16314 
#16316

They are not obligated to do that, because their PR for this issue #16312 was approved, with a mere request to update other issues above, since they were at it.
But, since they correctly made a very valid PR, we are obligated to accept theirs first.

So, doing that we, introduced a conflict in your PR which took up addressing all three.
Ideally we should have directed you to make changes only for #16314 and #16316.

We reget that, but please understand that this can happen, its possible to miss things inadvertently.

So, to fix up the commit, I updated your PR to resolve the commit.

> How am I supposed to be able to see what you changed? 

I updated your PR to resolve the conflict, which basically means, I kept their and your changes together, so that the PR is accepted, post review.
Hence, I requested for a review on your PR #16489.

Also, I requested for a sanity check, from you so that the code is the expected what you had done in your PR.

You are able to check file changes on the files tab of the pull request page.


> You appear to have taken the other PR, #16341 which I originally asked about? 

See above for clarification.

> So, I wasted my time doing this?

&&

> I'm pretty annoyed that you closed this by taking the original pull request after telling me I could take it. Nobody replied to the comments I left above and now the issue is closed. There's no wonder this is a year behind schedule if you're squandering people's effort in this way.

You absolutely did not waste any time! We thank you for taking so much time and efforts to contribute to this code base. 
Please understand just like you every contributor including the maintainers are doing this for the greater good for the community, spending time of their busy lives, just like you.

We sincerely thank you for contributing, and giving us that valuable time of yours.

I understand its little tough when you are getting started, and easily get frustrated, but trust me, we are there to help you help us.

Its easy, to vent the frustration, and we are okay to acknowledge that and clarify the actions, but may I suggest all it takes is just asking for clarification, when you are in doubt of something.

It may take us a while, but we will get back. 

I hope this clears up any confusion. You are more than welcome to make a contribution, and we will be happy to take it, if you are still interested, if not its still OK.

Happy contributing! and sorry about any confusion.

**Comment by r1chard5mith** [comment] 2018-01-16 09:53
I appreciate you taking the time to write that and I apologise for venting my frustration. I understand that you can only reply when you have time to do so, but I will point out that you wrote "if they are unable to revert or update in a few days, please feel free to make a pull request.However, please make a note of the discussion on the PR thread as well, so that we do not miss anything." which I took to mean that you still wanted all three issues dealt with in one PR, which I made. 

Also, with respect, you say "may I suggest all it takes is just asking for clarification, when you are in doubt of something." but I can count three questions I've asked in this very thread which have, as yet, gone unanswered. 

When I look at the files tab, it only shows changes from the original, it doesn't show me what *you've* changed. I can see the change count has gone from 5 to 7 but I can't tell if you've edited anything else without manually comparing it with my copy. I saw the setting to allow maintainer edits but I assumed changes would get marked explicitly as coming from another person.

**Comment by raisedadead** [comment] 2018-01-16 10:28
> When I look at the files tab, it only shows changes from the original, it doesn't show me what you've changed. I can see the change count has gone from 5 to 7 but I can't tell if you've edited anything else without manually comparing it with my copy. I saw the setting to allow maintainer edits but I assumed changes would get marked explicitly as coming from another person.

Yes, I think this is the point of confusion, because no code was changed at all by me except for a simple rebase, of the commit.

Meaning, your commit was used as it is with all your changes only.

Anyways, thanks for reverting back, I urge you to simply push the changes and open a new PR.
Since you have deleted, the branch on GitHub, unfortunately you will do this over again.
And, in future when unsure, do not delete a branch, unless the query is sorted, over a chat / comments etc.

We will happy and eager to take a look, and get your PR merged.

And, I will personally take more care in reverting back with clearer guidelines, sincerest apologies for all the confusion.

Happy contributing!

**Comment by StephenMayeux** [comment] 2018-01-16 14:54
> There's no wonder this is a year behind schedule if you're squandering people's effort in this way.

@r1chard5mith I know it's frustrating but that comment was unnecessary, man. You've used freeCodeCamp to attain the Front End and Data Visualization certificates and have picked up a lot of useful skills along the way. And the core group of contributors have volunteered thousands if not tens of thousands of hours to get this ready so that people like us can learn. It's not perfect, but be thankful.

**Comment by raisedadead** [comment] 2018-01-16 19:55
Hi, @StephenMayeux its okay, now. 

I have gone ahead and retrieved the changes from my local copy.

I personally did not want @r1chard5mith 's efforts go waste, and they should get their well deserved credits for working on it, in the first place. We are super excited to welcome everyone, especially when when they are contributing to this code-base for first time. 

**The commit reflects them as an author.**

@r1chard5mith @StephenMayeux 
Please feel free to take a look at the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/16515 and suggest changes, I'll be sure to make them.

Happy contributing!

**Comment by r1chard5mith** [comment] 2018-01-16 21:55
Thanks for your opinion @StephenMayeux, and for taking the time to look through my profile, but I haven't actually received any of the certificates. I was just playing for fun and it's beside the point in this case. 

I understand that your time is valuable. So is mine. Did you see the question I asked you above?  Do you know a better way to edit and test the tests from the challenges?

@raisedadead - I'm happy for the PR to go through on this occasion, because we already went round the houses on this. In future I'll be sure to uncheck the 'allow maintainer edits' setting, because in general I'm not comfortable about having my name on things I don't have authority over. 

Should I file a new issue for the bug I mentioned? (see the screenshot above)

**Comment by raisedadead** [comment] 2018-01-17 05:44
> Should I file a new issue for the bug I mentioned? (see the screenshot above)

Yes please.

**Comment by no-stack-dub-sack** [comment] 2018-01-19 00:52
@r1chard5mith to answer one of your questions above: no, unfortunately there is no better way to test your changes to seed files than to edit the seed, reseed the database, and restart the server. Yes, the feedback loop is pretty slow, and if you're just experimenting with stuff to see what works, it can get pretty frustrating. That said, it really does encourage you to think carefully about your changes because the desire becomes so strong to minimize the number of times you have to do this!

Also, I want to make sure we don't lose track of the other issue you raised on this thread (about the weird rendering of async challenges, which I've noticed before when we first implemented them - but at that point, getting them working and in the codebase was enough). That said, I'm going to open this issue, but I will be sure to tag you in it, so you can follow what's going on and suggest any solutions you might have.
