### ISSUE TITLE
"proceed to next challenge button error"

### ISSUE THREAD

**Issue by Cbhansen** [FreeCodeCamp/FreeCodeCamp#11296] opened 2016-10-20 21:57 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3Ared%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Issue Description

When completing the challenge, and hitting submit, I can not proceed to next challenge. The "proceed to next challenge" text does not appear. Preventing me from using the button to the next challenge. Tried refresh. 
#### Browser Information

Firefox browser.
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment] 2016-10-21 00:57
@Cbhansen thanks for the issue. Sorry to hear you're having issues submitting. I'm unable to reproduce your issue. I was able to run your code (it is correct) and I get the proceed to next challenge modal. The only thing I can suggest is trying to solve the challenge in another browser or computer. I'll leave this issue open in case someone is able to reproduce.

**Comment by SimShaffer** [comment] 2016-10-25 18:22
I figured it out, I had the code right but instead of making a thick border like i was supposed to I made it a thin. I am pretty sure at least I completed the challenge so I don't have the code in front of me but I am pretty sure that's what happened. Thank you though!

    On Thursday, October 20, 2016 9:01 PM, Eric Leung <notifications@github.com> wrote:
 

 @Cbhansen thanks for the issue. Sorry to hear you're having issues submitting. I'm unable to reproduce your issue. I was able to run your code (it is correct) and I get the proceed to next challenge modal. The only thing I can suggest is trying to solve the challenge in another browser or computer. I'll leave this issue open in case someone is able to reproduce.—

**Comment by Cbhansen** [comment] 2016-10-25 19:01
Hello Eric,
Thanks for replying. It's appreciated. I was able to resolve the issue by
switching from Firefox to Chrome.

**Comment by systimotic** [comment] 2016-10-28 09:32
This must've been a very weird issue where some state got stuck somewhere. The code from the link shared in the original report does work for me on Firefox. Sorry for the trouble Chris! @erictleung I think this can be closed.

**Comment by erictleung** [comment] 2016-10-28 16:03
Mmm sounds like we're still having some issues with Firefox. 

@systimotic thanks, I'll go ahead and close it.

Happy coding all!

**Closed by erictleung** 2016-10-28 16:03 UTC
