### ISSUE TITLE
test cases

### ISSUE THREAD

**Issue by Megabyteceer** [FreeCodeCamp/FreeCodeCamp#4326] opened 2015-11-12 10:51 UTC
Challenge [Bonfire: Friendly Date Ranges](http://www.freecodecamp.com/challenges/bonfire-friendly-date-ranges)

Strange test cases. I think they is expired:
friendly(["2015-07-01", "2015-07-04"]) should return ["July 1st","4th"]
friendly(["2016-03-01", "2016-05-05"]) should return ["March 1st","May 5th"]

"July 1st","4th"
"March 1st","May 5th"

User can't understand that it is 2015 and 2016 years.

**Comment by ltegman** [comment] 2015-11-12 16:29
Thanks for the report -- this challenge could definitely use come cleanup!

Closing as a duplicate of #1886

Thanks and happy coding!

**Closed by ltegman** 2015-11-12 16:29 UTC
