### ISSUE TITLE
Beta freeCodeCamp's signup redirect bug

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#12695] opened 2017-01-21 17:38 UTC
#### Issue Description
It looks likes there's a bug in the Beta FreeCodeCamp's [signup](https://beta.freecodecamp.com/en/signup)

When user signups for the first time, it directs to a blank page. I would've assumed it would return back to the homepage (or at least returns back to page where it was before clicking the sign-up page)

#### Browser Information
* Browser Name, Version: Chrome/55.0.2883.95
* Operating System: Macintosh; Intel Mac OS X 10_11_6
* Mobile, Desktop, or Tablet: MacBookPro 

#### Screenshot
<img width="1236" alt="screen shot 2017-01-21 at 9 24 42 am" src="https://cloud.githubusercontent.com/assets/10217112/22176357/47cf7700-dfbd-11e6-9513-e55ae07a4758.png">
<img width="623" alt="screen shot 2017-01-21 at 9 23 29 am" src="https://cloud.githubusercontent.com/assets/10217112/22176361/4ffdcf3a-dfbd-11e6-8b8b-db01ca8243f0.png">

**Comment by systimotic** [comment] 2017-01-21 17:49
Hi @KenzoM!

Thanks a lot for reporting this issue, especially with screenshots.
It looks like this is a duplicate of #12681, so I'm closing this issue in favour of that.

Thanks for helping QA the beta, happy coding!

**Closed by systimotic** 2017-01-21 17:49 UTC
