### ISSUE TITLE
Remember me/stay logged in option

### ISSUE THREAD

**Issue by ChristianLapinig** [FreeCodeCamp/FreeCodeCamp#5124] opened 2015-12-10 05:50 UTC
This might not be that big of an issue, but I was wondering why there isn't an option for a user to stay signed in?

**Comment by ltegman** [comment] 2015-12-10 15:32
We agree that this is an issue! Closing as a duplicate of #3513. Thanks and happy coding!

**Closed by ltegman** 2015-12-10 15:32 UTC
