### ISSUE TITLE
Sections of map should have their own URL

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15712] opened 2017-08-02 13:33 UTC
If I want to go to the debugging section, I should be able to do this by going to:

http://beta.freecodecamp.com/en/javascript-algorithms-data-structures/debugging

And this should show me a simple view like this:

![freecodecamp](https://user-images.githubusercontent.com/985197/28875978-2bea47f8-775d-11e7-8367-33931132f862.png)

That way campers can link to specific sections of the challenge map.

**Comment by knrt10** [comment] 2017-08-05 10:32
I am intrested in this issue can this be assigned to me and can you direct me to the files that need to be changed.

**Comment by QuincyLarson** [comment] 2017-08-05 17:28
@knrt10 I think this would involve changing a lot of files - I'm not sure exactly what they are. Figuring that out would be a big part of the task. @BerkeleyTrue is the most familiar with all of this and is probably the best person to tackle this since he's also overhauling the rest of our URL logic.

**Comment by systimotic** [comment] 2017-09-04 11:01
@QuincyLarson I understand you want this to happen really bad, but one issue is enough 😜 Closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/15753

**Closed by systimotic** 2017-09-04 11:01 UTC
Labels: beta
