### ISSUE TITLE
Comment out HTML challenge: pressing hotkey "ctrl+/" on any trailing comment "-->" doesn't undo/redo existing comment

### ISSUE THREAD

**Issue by afable** [FreeCodeCamp/FreeCodeCamp#10378] opened 2016-08-28 22:50 UTC
#### Challenge Name
https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A

#### Issue Description
Pressing hotkey "ctrl+/" on a single line with the trailing part of an HTML comment "-->" doesn't undo/redo existing comment. In fact it just keeps adding comments. "ctrl+/" hotkey seems to work otherwise.

#### Browser Information

* Browser Name, Version: Chrome, Version 52.0.2743.116 m (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![untitled](https://cloud.githubusercontent.com/assets/1513169/18037372/0c8d07a0-6d37-11e6-80c1-e0305a669737.png)

**Comment by afable** [comment] 2016-08-28 22:51
Not a big issue, more like a feature request since the challenge doesn't really talk about using the ctrl+/ hotkey but I just thought I'd point it out (and try submitting a bug for the first time).

**Comment by afable** [comment] 2016-08-28 22:57
Now that I think about it, this behaviour will probably happen on all challenges so maybe it would be nicer to fix.

**Comment by erictleung** [comment] 2016-08-28 23:15
@afable thanks for the issue. I didn't know about this hotkey. However, I'm unable to reproduce that behavior. Thanks for pointing out that you're on a Windows machine. I'm unable to reproduce this behavior on Chrome on a Mac.

cc/ @FreeCodeCamp/issue-moderators can anyone else reproduce?

**Comment by afable** [comment] 2016-08-28 23:27
@erictleung my mistake. It's actually the trailing part of a comment "-->" that produces this issue (looking at the img I uploaded must've made my brain lapse and put the wrong information). The bug report has been updated. Please test with using "ctrl+/" on a single line with the trailing part of a comment "-->" to see if you can reproduce.

**Comment by erictleung** [comment] 2016-08-29 03:24
@afable ok, I'm now able to reproduce this "feature." I'm not sure how we would prevent this from happening though.

**Comment by BKinahan** [comment] 2016-08-29 10:57
This is a feature of CodeMirror, so the issue belongs here: https://github.com/codemirror/CodeMirror/issues

**Comment by afable** [comment] 2016-08-29 15:50
Should I close this issue or leave it open as blocked since it's a CodeMirror feature?

**Comment by atjonathan** [comment] 2016-08-30 15:13
Closing as this belongs to CodeMirror.

**Closed** 2016-08-30 15:13 UTC
