### ISSUE TITLE
Python for Everybody - Objects: A Sample Class - Correct answer option is not given

### ISSUE THREAD

**Issue by souravjamwal77** [freeCodeCamp/freeCodeCamp#38965] opened 2020-05-30 19:04 UTC
**Describe your problem and how to reproduce it:**
In the Problem, _A Sample Class _ in **Python for Everybody** the correct option for the answer is not given.
The correct answer should be **2 and 4**, but it's not given in the options for answers.

**Add a Link to the page with the problem:**
**Problem:** Python for Everybody - Objects a Sample Class

https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/objects-a-sample-class

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 83.0.4103.61 (Official Build) (64-bit)
* Operating System: Ubuntu 20.04 (Focal Fossa) - Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2020-05-31 00-21-38](https://user-images.githubusercontent.com/25997760/83337091-3854bd00-a2d6-11ea-9de2-daedadb1bcdc.png)

**Comment by Sky020** [comment] 2020-05-30 20:32
Thank you, for pointing this out, but an issue has already been raised, and a PR is likely to fix.

I am closing this as it is a duplicate of #38931

**Closed by Sky020** 2020-05-30 20:32 UTC
Labels: scope: learn, status: needs help for triage

**Comment by souravjamwal77** [comment] 2020-05-31 03:47
Thanks
