### ISSUE TITLE
Correct answer not accepted!

### ISSUE THREAD

**Issue by tangent8** [FreeCodeCamp/FreeCodeCamp#6957] opened 2016-02-13 04:58 UTC
$(".target:nth-child(2)").addClass("animated bounce"); is not the correct jQuery/JavaScript for this answer. 

Target is merely the place holder for a class.

The parent class for both these elements (#left-well and #right-well) is well. 
`      <div class="well" id="left-well">
      <div class="well" id="right-well">`

Therefore, the answer should be:
$(".well:nth-child(2)").addClass("animated bounce");

**Comment by alistermada** [comment] 2016-02-13 05:17
`$(".well:nth-child(2)").addClass("animated bounce");` would make the wells themselves bounce since they are both the second child of their parent.

The instructions ask that the second child of each well be given the `bounce` class. `$(".target:nth-child(2)").addClass("animated bounce")` does exactly that. Note: Each button has a `target` class and is a child of a div with the `well` class.

**Comment by tangent8** [comment] 2016-02-13 16:36
Then maybe the instructions themselves need to be rewritten.  Search the forums, I was not the only one to experience confusion in what was being asked here.

Instructions: Make the second child in each of your well elements bounce. You must target the children of element with the target class.
Me: This implies that we are referencing the element well, since only it has child elements.
`      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>`

**Comment by bugron** [comment] 2016-02-16 05:41
@tangent8 @alistermada actually, none of your code should pass tests because challenge wants you to bounce **all** you buttons and not only ones that are second children.
> For example, let's make **all** of your button elements bounce. Just add this code inside your document ready function:

We check if buttons have `bounce` class using https://api.jquery.com/hasclass but `.hasClass` "Determines whether **any** of the matched elements are assigned the given class.". So we need a way to check if **all** buttons have that class and not **any** of them. That may look like an additional check in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/99ea090998f2b1610413deb4f20a0da04d4048e5/seed/challenges/01-front-end-development-certification/jquery.json#L107) like this: `$("button.animated.bounce").length === $("button").length`.

**Comment by sludge256** [comment] 2016-02-16 08:03
@bugron I believe they're discussing [Target a Specific Child of an Element Using jQuery](http://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery) not [Target HTML Elements with Selectors Using jQuery](http://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery).

**Comment by bugron** [comment] 2016-02-16 08:14
@sludge256 Oh, my bad. Closing this issue then. See [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084). @tangent8 thanks for posting.

**Closed by bugron** 2016-02-16 08:14 UTC

**Comment by JoshFisk** [comment] 2016-02-16 08:22
Here are the three possible correct solutions depending on how you interpret the instructions:
$(".target:nth-child(2)")
For every class, if the second child has a target class, add that child to the list

$(".well .target:nth-child(2)")
For each well class, if a descendent second child has a target class, add that child to the list. 

$(".well > .target:nth-child(2)")
For each well class, if a second child has a target class, add that child to the list. 

Ex: http://codepen.io/joshfisk/pen/dGrqQb

The problem is the instructions are describing the last one, but giving an example of the first one. This means that people who know more about jQuery will mess up, and people who know nothing will pass it, but learn the wrong thing.

**Comment by JambaDog** [comment] 2016-04-01 02:02
This problem is poorly worded. I had to go to the jquery website to actually figure out what the function did.
