### ISSUE TITLE
Claim Your Front End Development Certificate Step 3

### ISSUE THREAD

**Issue by stgisi** [FreeCodeCamp/FreeCodeCamp#7987] opened 2016-04-08 15:09 UTC
#### Claim Your Front End Development Certificate

https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate

#### Step 3 displaying challenge map multiple times (infinite loop?), loading prompt never finishes

After reaching step 3 where my profile is checked to see if I've completed all Front End Dev challenges, I receive an error 'Oops! There was an issue.'

#### Browser Information

* Google Chrome, 49.0.2623.110  and Firefox 45.01
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot
https://gyazo.com/0e10378398c445a1dc2f73f3d2f62fe3
https://gyazo.com/2443b85e5a3ab91aaefc7b8598363c63
https://gyazo.com/6e5660840a48d40d9d244862a57e52b1

**Comment by erictleung** [comment] 2016-04-08 15:13
Possible duplicate of #7963.

**Comment by BerkeleyTrue** [comment] 2016-04-08 16:08
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2016-04-08 16:08 UTC
