### ISSUE TITLE
Target a Specific Child of an Element Using jQuery Says to use class "target" instead of "animated bounce"

### ISSUE THREAD

**Issue by sirk1989** [FreeCodeCamp/FreeCodeCamp#7264] opened 2016-02-26 15:53 UTC
The questions says; 
"Make the second child in each of your well elements bounce. You must target the children of element with the **target** class."

The expected test results say;
"The second element in your target elements should **bounce**."

So i think the question is supposed to say something similar to the following;
"Make the second child in each of your well elements bounce. You must target the children of element with the **bounce** class."

Chrome 48.0.2564.116 m
Windows 7

**Comment by techtolentino** [comment] 2016-03-03 01:53
@sirk1989 actually, I think the way it's phrased is correct. The challenge wants you to use the `.target` class and apply `:nth-child( )` to it. So you are in fact using the `target` class.

Your suggestion _You must target the children of element with the bounce class_ would make me think to do `$(".bounce:nth-child( )")` - because it's saying _**children** of the **element with the bounce class**_.

Thoughts?

**Comment by ltegman** [comment] 2016-03-03 01:55
Thank you @techtolentino, that's correct :smile: Closing as not a bug. Thanks and happy coding!

**Closed by ltegman** 2016-03-03 01:55 UTC

**Comment by sirk1989** [comment] 2016-03-03 07:52
OK yeah fair enough a re-read of it today makes more sense.
