### ISSUE TITLE
Can we change the hint links of Chinese curriculum to English posts?

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#42175] opened 2021-05-18 10:50 UTC
Now the hint links in the Chinese curriculum are pointing to invalid Chinese forum posts. We discussed with Quincy before and agreed that we didn't want to translate the hints. Can we just update them to English forum posts? Thanks!

**Comment by paulywill** [comment] 2021-05-18 13:47
All the links, or just s few of them?

**Comment by miyaliu666** [comment] 2021-05-19 02:58
> All the links, or just a few of them?

All 'Get a Hint' links in the Chinese curriculum challenges.

**Comment by niteshseram** [comment] 2021-05-24 07:06
Hello, Can I work on this issue?

**Comment by ShaunSHamilton** [comment] 2021-05-24 07:58
@niteshseram 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sembauke** [comment] 2021-08-12 13:16
Closing this as a duplicate of #43067

**Closed by Sembauke** 2021-08-12 13:16 UTC
Labels: help wanted, scope: curriculum, scope: i18n
