### ISSUE TITLE
Global Scope and Functions - test for var not working correctly

### ISSUE THREAD

**Issue by mikeAttia** [FreeCodeCamp/FreeCodeCamp#10594] opened 2016-09-09 15:56 UTC
Challenge [global-scope-and-functions](https://www.freecodecamp.com/en/challenges/basic-javascript/global-scope-and-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Even though I didn't use the "var" keyword in the code, it is not checking that item!!

```js
    
    
// Declare your variable here
var myGlobal = 10;

function fun1() {
// Assign 5 to oopsGlobal Here
oopsGlobal = 5;
}

// Only change code above this line
function fun2() {
var output = "";
if (typeof myGlobal != "undefined") {
  output += "myGlobal: " + myGlobal;
}
if (typeof oopsGlobal != "undefined") {
  output += " oopsGlobal: " + oopsGlobal;
}
console.log(output);
}

    ```

**Comment by dhcodes** [comment] 2016-09-09 16:02
Confirmed. Final test does not pass despite correct code.

**Comment by atjonathan** [comment] 2016-09-09 16:18
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10594.

**Closed by atjonathan** 2016-09-09 16:18 UTC
Labels: confirmed, help wanted, tests
