### ISSUE TITLE
Reverse Browser Lock Up

### ISSUE THREAD

**Issue by hiowowdy** [FreeCodeCamp/FreeCodeCamp#4812] opened 2015-11-30 17:41 UTC
I began the challenge for reverses in the object oriented part of Java. As soon as I began typing "function" the screen froze and I was unable to navigate away from the page, or perform any actions within the page. I can still operate outside of that page, even while the page is frozen, so I don't think it's the browser (chrome). I quit chrome, logged out and restarted my computer and the issue persists. Hoping something can be done about it so I can continue on. Having lots of fun and love your service !

**Comment by ltegman** [comment] 2015-11-30 17:50
Closing as a duplicate of #4228. However, typing function is not required to complete this challenge since `reverse` does not take a callback.

Thanks and happy coding!

**Closed by ltegman** 2015-11-30 17:50 UTC

**Comment by hiowowdy** [comment] 2015-11-30 17:54
I mean, I have to type out the stipulations of the function. I can't even
get the cursor to move there to create the code, let alone get the page to
run it were I able to type it out. The entire page is frozen, and all
buttons are disabled

**Comment by ltegman** [comment] 2015-11-30 17:55
Take a look at #4228. It describes exactly the problem you are having.
