### ISSUE TITLE
Convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by Hazelpepper** [freeCodeCamp/freeCodeCamp#35602] opened 2019-03-15 01:11 UTC
**Describe your problem and how to reproduce it:**
Code for convertion Celsius to Fahrenheit. 

When inputting my code, I kept getting the exclamation in a yellow triangle next to the code. I wrote: var fahrenheit = celsius * 9/5+32;
The triangle would pop up and when I hover over it, it kept saying
 "fahrenheit" is already defined. I

I finally rewrote the same code again and hit submit, despite the triangle, and it said it was correct. I am not sure why I keep seeing the yellow triangle indicating something is wrong, even though it says correct when I hit the test button.

**Add a Link to the page with the problem:**
[http://warmups.devmountain.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20var%20fahrenheit%20%3D%20celsius%20*%209%2F5%2B32%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(10)%3B%0A
![Screen Shot 2019-03-14 at 6 57 31 PM](https://user-images.githubusercontent.com/48573274/54401023-557a7d00-468b-11e9-8f2e-05ec40fadd5d.png)
![Screen Shot 2019-03-14 at 6 57 31 PM](https://user-images.githubusercontent.com/48573274/54401042-69be7a00-468b-11e9-8697-d62c2442e998.png)

](url)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome 72
* Operating System: macOSMohave Version 10.14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Hazelpepper** [comment] 2019-03-15 01:11
sorry, I didn't mean to add the screenshot twice.

**Comment by RandellDawson** [comment] 2019-03-15 01:41
These kinds of questions are better for the forum.  You `var fahrenheight` twice.  It was already declared above the line:
```
// Only change code below this line
```
Try removing the `var` from line 6.

I am closing this issue, as it is not a bug, but a user code issue.

**Closed by RandellDawson** 2019-03-15 01:41 UTC
