### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by CodeCity** [FreeCodeCamp/freecodecamp#672] opened 2015-05-27 23:27 UTC
The CSS is correct but no matter which way it is written, the answer is incorrect. 

margin-top is not working correctly. 

  .green-box {
    background-color: green;
    margin-right: 20px;
    margin-bottom: 20px;
    margin-left: 40px;
    margin-top: 20px;
  }

  .green-box {
   margin: 20px 20px 20px 40px;
  }

The instructions say to make margin-top: 20px. By experimenting I determined it should be margin-top: 40px.

**Comment by terakilobyte** [comment] 2015-05-28 11:02
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:02 UTC
