### ISSUE TITLE
Unable to run test after changes to resize cat image

### ISSUE THREAD

**Issue by CherylU** [FreeCodeCamp/FreeCodeCamp#6225] opened 2016-01-16 21:15 UTC
Challenge [Size your Images](http://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I attempt to press the "Run Test" button or the CTRL+ENTER keys to run the test and move to the next, but I am unable to.  What did I do wrong? 

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Cortellc** [comment] 2016-01-17 00:08
I am stuck at the same spot :(

**Comment by CherylU** [comment] 2016-01-17 03:09
I moved onto the next challenge. 

I even cookies and pasted the next challenge's code back onto this issue and it still didn't work.  

I'll email you again when and if I get it to work.

Maybe we should do it on Firefox?

**Comment by Cortellc** [comment] 2016-01-17 04:15
Hey!

I appreciate you reaching out to me. I opened it up in Internet explorer (
not by choice ha) and my code worked perfectly.

Maybe chrome won't be the best for this site.

Again, thanks for following back up! 😊

Cathy

On Saturday, January 16, 2016, Cheryl U <notifications@github.com> wrote:

> I moved onto the next challenge.
>
> I even cookies and pasted the next challenge's code back onto this issue
> and it still didn't work.
>
> I'll email you again when and if I get it to work.
>
> Maybe we should do it on Firefox?
>
> Sent from my iPhone
>
> > On Jan 16, 2016, at 4:09 PM, Cathy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I am stuck at the same spot :(
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6225#issuecomment-172286434>
> .
>


-- 

Cathy Cortell

IT Recruiter at Accentuate staffing

(919)961-1284 Cell

(919)844-2900 Work

Cortellcathy@gmail.com

**Comment by ltegman** [comment] 2016-01-17 19:53
I'm not able to repro this unfortunately, so I can't do any investigation into the cause.

**Comment by Spaulq** [comment] 2016-01-17 23:59
I too, amhaving the same problem here.

**Comment by CherylU** [comment] 2016-01-18 01:47
Try running it in Internet Explorer or Firefox.

**Comment by Spaulq** [comment] 2016-01-18 03:54
Thanks, i have been using firefox.

**Comment by Spaulq** [comment] 2016-01-18 04:45
<img src="https://bit.ly/fcc-relaxing-cat" class="smaller-image"> 
It worked in firefox while doing this.

**Comment by CherylU** [comment] 2016-01-18 04:54
For some reason, it didn't work on Chrome.  It worked on Firefox and on I.E.

**Comment by sonalkr132** [comment] 2016-01-23 07:32
Not reproduceable on `Google Chrome 46.0.2490.80` or `Mozilla Firefox 41.0.2`

**Comment by CrystalCJoseph** [comment] 2016-02-01 01:08
Same problem in Chrome

**Comment by CherylU** [comment] 2016-02-01 01:15
Try it on Firefox or I.E.  It'll work.

**Comment by CrystalCJoseph** [comment] 2016-02-01 16:50
I tried Firefox and that wouldn't work either. LOL I just went on to the next challenge - had the code correct at least - but I'll try I.E. when I get home. Thanks!

Sincerely,



 	
Crystal Joseph
about.me/crystal.joseph

**Comment by raisedadead** [comment] 2016-02-01 17:06
@CrystalCJoseph @CherylU Can you guys try Reset + Hard Refresh?

First copy your code, some where.
Next click reset button on the challenge page.
Finally do a hard refresh (Ctrl + F5).

Then paste your code back and try running the tests.

**Comment by CrystalCJoseph** [comment] 2016-02-04 17:53
😁 Tried that too, the button still will not work. 

Sincerely,



 	
Crystal Joseph
about.me/crystal.joseph

**Comment by raisedadead** [comment] 2016-02-04 18:08
Thanks @CrystalCJoseph Can you post a screenshot of browser console? 
Press F12 to open the developer tools, and take a screenshot of the console and network tabs like below:

 
![1](https://cloud.githubusercontent.com/assets/1884376/12824679/646f901e-cb98-11e5-9642-0d38f64606e5.PNG)
![2](https://cloud.githubusercontent.com/assets/1884376/12824678/646ec418-cb98-11e5-8f82-f4009f52625d.PNG)

**Comment by CrystalCJoseph** [comment] 2016-02-07 01:40
Okay, attached you will find both Firefox and Chrome screenshots :)

On Thu, Feb 4, 2016 at 12:10 PM, Mrugesh Mohapatra <notifications@github.com
> wrote:

> Thanks @CrystalCJoseph <https://github.com/CrystalCJoseph> Can you post a
> screenshot of browser console?
> Press F12 to open the developer tools, and take a screenshot of the
> console and network tabs like below:
>
> [image: 1]
> <https://cloud.githubusercontent.com/assets/1884376/12824679/646f901e-cb98-11e5-9642-0d38f64606e5.PNG>
> [image: 2]
> <https://cloud.githubusercontent.com/assets/1884376/12824678/646ec418-cb98-11e5-8f82-f4009f52625d.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6225#issuecomment-179973344>
> .
>



-- 
Sincerely,
*Crystal Claire Joseph*

**Comment by raisedadead** [comment] 2016-02-07 09:10
@CrystalCJoseph 

Umm, Github doesn't let you attach images via email! You have to visit this [issue page here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6225).
And drag and drop those screenshots in to the comment box.

Thanks again for helping us out!

**Comment by CrystalCJoseph** [comment] 2016-02-08 03:42
Oh I had replied via email and attached them that way, not realizing where you were actually viewing this. Sorry lol  When I'm at my computer I'll drop the pics in

**Comment by CrystalCJoseph** [comment] 2016-02-08 03:48
Chrome - Console
![chrome - console](https://cloud.githubusercontent.com/assets/11810503/12878075/c69599c6-cde3-11e5-8036-a1c0941975e2.png)

Chrome - Network
![chrome - network 01](https://cloud.githubusercontent.com/assets/11810503/12878092/13bf6f88-cde4-11e5-9930-3b9d60091e54.png)
![chrome - network 02](https://cloud.githubusercontent.com/assets/11810503/12878095/1f897962-cde4-11e5-9e7f-ec7f71f743d7.png)


Firefox- Console 
![firefox - console](https://cloud.githubusercontent.com/assets/11810503/12878101/3923dc50-cde4-11e5-9dda-19a8b675b858.png)

Firefox- Network 
![firefox - network 01](https://cloud.githubusercontent.com/assets/11810503/12878106/4db55dc4-cde4-11e5-96dd-2d9ff901b6c2.png)
![firefox - network 02](https://cloud.githubusercontent.com/assets/11810503/12878114/707dbf36-cde4-11e5-8671-9c46792d44f5.png)

**Comment by CrystalCJoseph** [comment] 2016-02-08 03:51
Sorry @raisedadead I was just replying to the email on my phone, so I didn't realize the photos wouldn't go into the comment. But, there they are in my last comment so I hope it helps

**Comment by raisedadead** [comment] 2016-02-08 07:32
@CrystalCJoseph Thanks for the screenshots.

From your Chrome Console log is appears that your facing a CSP issue, many campers faced recently ([read more](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5999)).

Since you are blocked by issue on both Chrome and Firefox, I recommend you go through the wiki link below, and try `browsec`. It may resolve your case at least.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc

Let me know, how it goes.

**Comment by CrystalCJoseph** [comment] 2016-02-16 04:22
Hey @Raisedadead I Installed Browsec on Chrome but I am still experiencing the same problem with the button. Though Browsec is cool so thanks for the tip on that extension!

**Comment by kreddibletrout** [comment] 2016-03-21 02:56
Ug.
I'm glad I got it right. I'm sad that I got so very frutrated for DAYS before coming here to find that... I'm not the only one and my code on this was correct.
Now I'm going to sift through this thread to find an answer. I hope.

**Comment by kreddibletrout** [comment] 2016-03-21 03:34
oh wow. I figured it out. I was wrong. carry on.

**Comment by raisedadead** [comment] 2016-04-17 07:47
Closing as we have moved to site wide SSL. All/Most URLs are now migrated to use `https`.
Please open fresh issue if this persists.

Thanks and Happy Coding!

**Closed by raisedadead** 2016-04-17 07:47 UTC
Labels: confirmed
