### ISSUE TITLE
Press Run Code 2x

### ISSUE THREAD

**Issue by vgibson15** [FreeCodeCamp/FreeCodeCamp#2983] opened 2015-09-02 03:55 UTC
Hi,

Prior to the changes I was able to press the Run Code 1x and received my positive feedback and move to the next challenge. Now I have to press it after I receive my postive feedback to go to the next challenge. Was this intentionally done? 

Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-margins-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Victoria

**Comment by bugron** [comment] 2015-09-02 04:01
@vgibson15 thanks for posting this issue! 
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772, so I'm closing it. You can continue further discussion there.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-02 04:01 UTC
