### ISSUE TITLE
RWD - Should Swap the order of "Building a Penguin" and "Building A Ferris Wheel"

### ISSUE THREAD

**Issue by bellhuffstutler** [freeCodeCamp/freeCodeCamp#46224] opened 2022-05-29 16:06 UTC
### Describe the Issue

I'm currently going though the Building A Penguin section of the new RWD course (I'm almost done with RWD again yay!) and There is a massive lack of information on how to do animations and the commands it actually wants you to do. 

The project feels like it was written when there was already a tutorial on keyframes and animations but then that got cut. I'll walk through the things I've noticed and needed to go off-site for, because I know the gameplan is to not have people have to leave the site to solve issues: 

1. Step 95: Define a new `@keyframes` named `wave`
This one I did figure out on my own, but it's not clear how you're supposed to actually make the name. (It took two attempts because I assumed i needed to do `@keyframes (wave) {}`

2. Step 96: Give `wave` four waypoints starting at `10%`, and incrementing by `10%`.
There is no information in the previous lessons on waypoints, and this is the first time the camper will be coming across this. In addition, the Hint is completely useless here, especially if you just have the waypoints inputted incorrectly, because it's simply "You should add a `10%` waypoint for `@keyframes wave`. Had to go offsite for this one.

3.  Step 100: Use the `wave` animation on the left arm. Have the animation last `3s`, infinitely iterate, and have a linear timing funtion.
This one is completely unsolvable without going off-site, or just failing each question, because the hints do tell you the pieces it wants to to add as it's missing. There has been no point up to this lesson where any of this is gone over, because this is the introduction to animation and keyframes. 

4. Just noticed in Step 103 (unrelated the the main step, but confusing if someone wants to look up what they did to replicate it in this step to learn better) that the animation property has been changed from how it tells you to do it in Step 100 to `animation: 3s linear infinite wave;` which is never explained or elaborated on, and the solution for 103 requires you to do it piece by piece. Also, as I'm now wrapping this one up, it is also not helpful in the step text, because we've never modified transition, and transition has it's own properties vs animation, and is not an animation with the name transition, which could very likely confuse campers.

5. Step 104: The last bit says "Congratulations! You have completed the Responsive Web Design certification!" but the Ferris Wheel is after this one. I'm going to go through the Ferris Wheel project, and honestly the best solution to everything might just be to move the Ferris Wheel project in front of this one, depending on how it is done

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-95

### Your code

Issues mentioned in Description

### Expected behavior

The things required to do in the keyframes and animation sections would be better explained 

### System

- Device: Desktop
- OS: EndevourOS
- Browser: Opera
- Version: 87.0.4390.36

**Comment by bellhuffstutler** [comment] 2022-05-29 16:30
Yeah, okay so I am now working though the ferris wheel project, and it 100% looks like the Ferris Wheel project is supposed to go before the Penguin project

it has very clear explanations of Keyframes and setting up an Animation, as well as adding an animation to an element, and also goes over the combined `animation` property.

Going to change the title of the thread

**Comment by jeremylt** [comment] 2022-05-29 20:34
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/45985

**Comment by bellhuffstutler** [comment] 2022-05-29 20:48
Thought I would have caught that, but I'm assuming it's because I didn't realize that was the issue until I finished the Ferris Wheel project

Sorry!
> Duplic

e of #45985 ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2FfreeCodeCamp%2FfreeCodeCamp%2Fissues%2F45985&recipient=cmVwbHkrQVpKVEZZQjRPN1lLU1FHSjc3N1haRDZBVUVGVVZFVkJOSEhFVkhYSEZBQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Closed** 2022-05-29 21:35 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
