### ISSUE TITLE
Duplicated page on device

### ISSUE THREAD

**Issue by moganrz** [FreeCodeCamp/FreeCodeCamp#2706] opened 2015-08-26 00:49 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue. 

I think the problem is happening on all Waypoint pages; the device right side of the screen where the CatPhotoApp page displays the information is being displayed duplicated;

Another point is that the HTML / CSS code is not completely displayed when the page is loaded, it is necessary to click or edit the code so that the code from the previous lesson is displayed correctly;

![duplicate](https://cloud.githubusercontent.com/assets/8672039/9483149/cbe9f67c-4b72-11e5-9b2a-698deaa06a4e.png)

![lost previous code](https://cloud.githubusercontent.com/assets/8672039/9483184/285ff19a-4b73-11e5-8601-6c5fbb58215b.png)

**Comment by BerkeleyTrue** [comment] 2015-08-26 00:54
can replicate. Can you try reset your code and do a hard refresh?

**Comment by moganrz** [comment] 2015-08-26 01:13
same error; bringing me the duplicate information and only part of the code;
but this problem did not interrupt the challenges, I keep doing them

**Comment by moganrz** [comment] 2015-08-26 01:20
It happened again, but now the challenge http://www.freecodecamp.com/challenges/waypoint-add-elements-within-your-bootstrap-wells
take a look

![duplicate2](https://cloud.githubusercontent.com/assets/8672039/9483489/7e76d82e-4b77-11e5-869b-fce5f583cf74.png)

**Comment by BerkeleyTrue** [comment] 2015-08-26 01:32
What browser are you using?

**Comment by benschenker** [comment] 2015-09-10 02:54
Hey @moganrz or @BerkeleyTrue, any updates on this?  I'm seeing some other complaints about this but cannot replicate.

**Comment by BerkeleyTrue** [comment] 2015-09-10 03:58
Have yet to replicate this on my end as well. We need to know what is special about these machines that might be the cause.

**Comment by BerkeleyTrue** [comment] 2015-09-11 00:12
We will keep this open as multiple users are experiencing this and we have not found the cause or a fix.

**Comment by BerkeleyTrue** [comment] 2015-09-11 00:13
@simonkrausgit Which browser where you using?

**Comment by benschenker** [comment] 2015-09-11 03:21
@moganrz, if you no longer want to get notifications for this then click unsubscribe on the right side of the page.

**Comment by simonkrausgit** [comment] 2015-09-11 03:23
@BerkeleyTrue Firefox on Ubuntu.

**Comment by BerkeleyTrue** [comment] 2015-09-11 04:55
That is two for FF.

**Comment by BerkeleyTrue** [comment] 2015-09-11 04:57
Actually two for FF on Ubuntu. @moganrz What OS and browser are you using?

**Comment by moganrz** [comment] 2015-09-11 11:43
@BerkeleyTrue Firefox on Ubuntu.

**Comment by awesomeaniruddh** [comment] 2015-09-11 11:52
That's three!

**Comment by BerkeleyTrue** [comment] 2015-09-11 15:20
Anyone on Ubuntu want to do some debugging for us?

**Comment by coreydeguia** [comment] 2015-09-16 00:49
I'm having troubles passing this as well and I'm using chrome. 
I'm wrapping the "button" with the proper div code and its not letting me pass. Any one want to try running my code? Here it is:

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
    
    <div class="row">
    
      <div class="col-xs-7"><input type="text" class="form-control" placeholder="cat photo URL" required>
      </div
      
      <div class="col-xs-5"><button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Submit</button></div>
    
    </div>
  </form>
</div>

**Comment by saadanerdetbare** [comment] 2015-09-19 15:51
I have this issue in FF 40.0.3 on Windows 10 x64.
I started with a `localStorage.clear();` and then did a hard refresh of the page
I don't know how much of this is related to the error in question but i get this
```
Content Security Policy: The page's settings blocked the loading of a resource at data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw== ("img-src * http://www.freecodecamp.com blob: http://104.236.218.15 http://*.freecodecamp.com http://www.freecodecamp.com http://freecodecamp.com https://www.freecodecamp.com https://freecodecamp.com https://freecodecamp.org http://*.freecodecamp.org http://www.freecodecamp.org ws://freecodecamp.com/ ws://www.freecodecamp.com/ http://*.gstatic.com http://*.google-analytics.com http://*.googleapis.com http://*.google.com http://*.gstatic.com http://*.doubleclick.net http://*.twitter.com http://*.twitch.tv http://*.twimg.com 'unsafe-eval' 'unsafe-inline' http://*.bootstrapcdn.com http://*.cloudflare.com https://*.cloudflare.com http://localhost:3001 ws://localhost:3001/ http://localhost:3001 http://localhost:3000 ws://localhost:3000/ http://localhost:3000 http://*.ionicframework.com https://syndication.twitter.com http://*.youtube.com http://*.jsdelivr.net https://*.jsdelivr.net http://*.ytimg.com http://*.bitly.com http://cdn.inspectlet.com/ https://cdn.inspeclet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/ http://*.googleapis.com http://*.gstatic.com https://hn.inspectlet.com/").
```
In the console when i load the page

**Comment by bschaden** [comment] 2015-10-10 03:52
Having double display issue on FF Windows 8.1. I haven't noticed the code initially missing yet, but I'm not very far into waypoints.

**Comment by trs4ece** [comment] 2015-10-20 05:40
I was having this same issue with FF on Win 10. After disabling and then individually enabling my extensions, I was able to determine that it was caused by the WOT extension.

Your mileage may vary, but try disabling all extensions and then do a few more tasks. Moving on to the next task seems important because the duplication will persist if you simply reload the page. I'm guessing it has something to do with the way that the solution is passed through the URL.

**Comment by Cheayo** [comment] 2015-10-30 16:19
I am having the same issue with Firefox on two different Win7 machines. FF 41.0.2 here, probably the same at home.

If I click on the code area, arrow down to the bottom, then arrow back up, the duplicate image disappears.

**Comment by bryan-hatton** [comment] 2015-11-02 01:58
I can replicate Cheayo's behavior with FF 41.0.2 on Win8 and Lubuntu. Additionally, for me, any kind of cursor motion or text insertion will cause the duplicate to disappear.

**Comment by t73biz** [comment] 2015-11-09 16:57
Using Firefox 41.0.1 on Linux Mint 17
I can replicate this as well.

**Comment by CoderBklyn** [comment] 2015-11-22 20:32
I am having this issue as well, using Firefox on windows 7

**Comment by BerkeleyTrue** [comment] 2015-11-25 19:48
PR #4696 might fix this issue.

**Comment by BerkeleyTrue** [comment] 2015-12-02 21:59
Is anyone still experiencing this?

**Comment by bugron** [comment] 2015-12-02 22:02
I'm not experiencing this anymore on Windows and latest FF.

**Comment by Cheayo** [comment] 2015-12-02 22:11
Doesn't look like it's happening anymore.

**Comment by ltegman** [comment] 2015-12-02 22:17
Woot! Closing :+1:

**Closed by ltegman** 2015-12-02 22:17 UTC
Labels: blocked, bug, firefox

**Comment by moganrz** [comment] 2015-12-02 22:51
It's not happening anymore on Ubuntu and lastest FF and Opera
