### ISSUE TITLE
signing back into FCC starts me back at the beginning of the new user challenges

### ISSUE THREAD

**Issue by Frithan** [FreeCodeCamp/FreeCodeCamp#6203] opened 2016-01-16 04:22 UTC
every time i log in i am taken back to the start of the new user challenges 
I'm using FF 43.0.4 on windows 10

**Comment by ahorton01** [comment] 2016-01-16 05:12
If you click on the "Map" button at the top right, it should show the entire curriculum with checkmarks by the challenges you already completed, so you can see where you left off. At least that worked for me. Full disclosure: I just started today. :-)
I'm using the same browser and OS.

**Comment by AkiraLaine** [comment] 2016-01-16 05:14
@Frithan Same here. It's suppose to give us the very next challenge we haven't completed.

**Comment by Frithan** [comment] 2016-01-16 05:14
yes i am awear of this, but the site used to take you back to where you left off

**Comment by Frithan** [comment] 2016-01-16 05:16
@ahorton01 yes i am awear of this, but the site used to take you back to where you left off

**Comment by AkiraLaine** [comment] 2016-01-16 05:17
@Frithan Have you clicked your link? It sends you to: http://codecamp.ucai.cn/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery

**Comment by Frithan** [comment] 2016-01-16 05:24
@AkiraLaine My link? i have not linked anything :/

**Comment by ahorton01** [comment] 2016-01-16 05:29
@Frithan and @AkiraLaine, for what it's worth, I saw some people discussing this same issue earlier today in the main chat room when I joined, and someone said that it was a functionality that had just recently been changed.

**Comment by juggernate** [comment] 2016-01-16 16:41
And now with the accordion map it is harder to find where you left off, see #6220

**Comment by ahorton01** [comment] 2016-01-16 18:13
I actually preferred the accordion. I was lost at first, but after seeing which module I was in, this definitely beats scrolling down all day.

**Comment by sludge256** [comment] 2016-01-18 08:11
Expected behavior is for it to redirect you to the last exercise you looked at (regardless of whether or not it has been completed). I have only been able to reproduce this by signing in from a private/incognito window.

**Comment by BerkeleyTrue** [comment] 2016-01-18 20:32
We use cookies to track the last challenge you were on. This is the only way we can redirect you properly. If you disable cookies then we have no way of knowing were you were last so it defaults to the first challenge.

**Comment by rasliche** [comment] 2016-01-20 13:57
What if instead of cookies to save the last challenge viewed, it just defaulted to sending you to the first unfinished challenge? While there are definitely drawbacks to this: experienced users constantly asked to learn what assigning variables are if they skipped them, I think the idea behind FCC is to get really new coders up to speed. I know that personally I would not have minded being redirected to the new challenges even though I was on the first set of ziplines since they seemed to fill in some holes. Just a thought, and I haven't looked into the code too much yet, but that seems an easier fix.

**Comment by BerkeleyTrue** [comment] 2016-01-20 16:09
> What if instead of cookies to save the last challenge viewed, it just defaulted to sending you to the first unfinished challenge?

This was what we used to do. And we would get constant complaints of it sending camper to the wrong challenge when in reality it was sending them to skipped challenges. That is a no go. It is hard to find a balance with these kind of automatic features.

**Comment by trueskawka** [comment] 2016-01-22 09:33
I use FCC on two different laptops, so the cookie approach doesn't work for me. At first, I thought all my progress was lost. Glad it wasn't, but the new feature is confusing.

**Comment by BerkeleyTrue** [comment] 2016-01-25 07:22
Closing. We'll be making changes according to #6382 

Happy Coding!

**Closed by BerkeleyTrue** 2016-01-25 07:22 UTC
Labels: Discussing
