### ISSUE TITLE
jQuery section throwing JavaScript errors

### ISSUE THREAD

**Issue by psabo** [FreeCodeCamp/FreeCodeCamp#2906] opened 2015-08-31 06:34 UTC
Challenge http://freecodecamp.com/challenges/waypoint-delete-your-jquery-functions has an issue. 

Browser: Chrome Version 44.0.2403.157
OS: OS X 10.9.5

While progressing through the jQuery section, I ran into a couple of errors. After inserting a new jQuery call, I get an "Unexpected token }" message. This is not totally unexpected I guess since I'm activity modifying script that will run on the page. However, occasionally this will cause the list of tasks to complete to disappear. The only way to make them reappear is to click reset my code.

![Screen shot of issue w/ dev tools]
(http://new.tinygrab.com/5be59a8681bef88463de4252954fa00fb07715e655.png)

Here's a screen shot of the page without the tasks listed.

![No tasks to complete]
(http://new.tinygrab.com/5be59a868129aa12d01a320e5ca3c2b24bcc8994c0.png)

**Comment by natac13** [comment] 2015-08-31 19:13
I am unable to reproduce this using Chrome on windows 7

**Comment by bugron** [comment] 2015-09-03 12:37
@psabo thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-03 12:37 UTC

**Comment by Rich-Hopkins** [comment] 2015-09-05 16:37
I have the same problem in IE11 on Windows 10.

**Comment by 4mifix** [comment] 2015-09-05 17:21
I got stuck here for days and it came to me clearly delete all of these jQuery functions (3) it should look like this
<script>
  $(document).ready(function() {
    
  });
</script>

**Comment by Rich-Hopkins** [comment] 2015-09-05 17:37
Hmmm... I've been somewhat successful in firefox. When the directions don't appear, I'm hitting ctrl-enter and they're showing up most of the time. Some of the time, I have to reset or reload the page.

**Comment by evanpizzolato** [comment] 2015-10-14 20:38
I'm having the same issue..i cannot move forward with any of the jQuery because of this issue.  Can someone please address it  and not just refer to another post which has gone unresolved and closed?
