### ISSUE TITLE
Changing timeout fails tests in React: Use the Lifecycle Method componentDidMount

### ISSUE THREAD

**Issue by drecali** [freeCodeCamp/freeCodeCamp#17988] opened 2018-08-08 01:55 UTC
#### Describe your problem and - if possible - how to reproduce it
In the "React: Use the Lifecycle Method componentDidMount" challenge, the last line of the instruction says:
> Watch what happens in the preview, and feel free to **change the timeout** to see the different effects.

When the timeout is 503 and above, all tests pass.
When the timeout is under 503, the final test fails, even though the preview is identical to the pass conditions.

It seems like this may be a bug and could be confusing for campers. The initial timeout is 2500 so I'm guessing that erasing one character to obtain either 250 or 500 would be a common change to the timeout. These values would then fail the tests and possibly confuse campers.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/use-the-lifecycle-method-componentdidmount

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.84 (Official Build) (64-bit)
* Operating System: Windows 7 (64-bit)

#### If possible, add a screenshot here
Fail at below 503
![image](https://user-images.githubusercontent.com/24983797/43811791-bad6e5fc-9b01-11e8-849f-66e25baa6ae9.png)

Pass at 503+
![image](https://user-images.githubusercontent.com/24983797/43811831-e5ef63a4-9b01-11e8-8827-c2f14a946544.png)

**Comment by ojeytonwilliams** [comment] 2018-08-24 14:01
Yep, the issue is that the third test sets some state, then waits 250ms before resolving and then repeats itself, waiting for a total of at least 500ms. If the user defined timeout is around that mark it can overwrite the state causing the test to fail. 

I think I can fix this, but the changes will need to go into the curriculum repository.

**Closed** 2018-08-30 09:36 UTC
