### ISSUE TITLE
http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps UX

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#4792] opened 2015-11-29 22:00 UTC
All of the base jumps refer us back to the "get set for basejumps" waypoint for a review of cloud9, etc to setup the appropriate environment. However, half the pages (as you step through the 14 pages for that waypoint) FORCE you to open an external site in order to progress to the next page. It's a horrible user experience the first time through, and even worse if you go back to review and just want to refresh your memory and end up with half a dozen pages open just to get to the info you wanted.

Also, all the base jumps say to go back to this section in order to review how to setup Heroko, and there's no instructions for Heroku.

**Comment by ltegman** [comment] 2015-11-29 22:05
We definitely agree with this and already have an open issue for it :+1: Closing as a duplicate of #4437 

Thanks and happy coding!

**Closed by ltegman** 2015-11-29 22:05 UTC
