### ISSUE TITLE
New login issue

### ISSUE THREAD

**Issue by jshaolin** [freeCodeCamp/freeCodeCamp#37800] opened 2019-11-20 20:59 UTC
At first, when trying to login to fCC Forum I got the "We're facing a known issue..." login error, a few days later I got the "Can't log in from that IP address". However, I was able to login a couple times. But now, I'm seeing this when login in through GitHub:

![Sin título3](https://user-images.githubusercontent.com/44646385/69277315-97a58680-0c3c-11ea-805f-16a4d52ad601.png)

After seeing all of the (versions of the) login issues reported here (and having experienced some of them myself), I wonder if they're actually being fixed, or if they just keep getting the message changed...

**EDIT:**
And yet, another new message...

![Sin título5](https://user-images.githubusercontent.com/44646385/69298581-d0f4eb00-0c6a-11ea-906e-1631102cd4c5.png)

**Comment by raisedadead** [comment] 2019-11-21 07:03
Duplicate of #37452 

I am posting details here: https://www.freecodecamp.org/forum/t/forum-is-currently-under-high-loads/326894/4

**Closed by raisedadead** 2019-11-21 07:03 UTC
Labels: type: bug
