### ISSUE TITLE
Make a Person Challenge - Instructions include deprecated "arity" property

### ISSUE THREAD

**Issue by ALamm** [FreeCodeCamp/FreeCodeCamp#7729] opened 2016-03-25 17:26 UTC
The instructions on this challenge need to be updated.  The **arity ** property is deprecated and not supported on any browser according to:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity

Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%0A%20%20%20%20return%20firstAndLast%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {
 
    return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by sludge256** [comment] 2016-03-25 18:26
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7366

**Closed by sludge256** 2016-03-25 18:26 UTC

**Comment by ALamm** [comment] 2016-03-25 18:52
Sorry I didn't see the duplicate.  

Just for the sake of clarity - I see the issue was "closed" but not
reflected on the live site.  

When do changes get pushed to the live server?

Thanks.
