### ISSUE TITLE
Introduction to JavaScript

### ISSUE THREAD

**Issue by profoundhub** [freeCodeCamp/freeCodeCamp#17520] opened 2018-06-10 12:57 UTC
#### Describe your problem and - if possible - how to reproduce it

Just spotted a spelling mistake: "arithemtic" ... it should be "arithmetic"

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript

**Comment by renojvarghese** [comment] 2018-06-10 15:41
I can make the quick fix

**Comment by profoundhub** [comment] 2018-06-12 02:39
Thanks, I'll let you know if I find anything else.

**Comment by Nirajn2311** [comment] 2018-06-12 02:39
If the issue is solve, please close it.

**Closed** 2018-06-15 07:45 UTC
