### ISSUE TITLE
[Beta] Applied Visual Design: Adjust the Width of an Element Using the Width Property

### ISSUE THREAD

**Issue by skhamoud** [freeCodeCamp/freeCodeCamp#12687] opened 2017-01-21 14:19 UTC
#### Challenge Name

Applied Visual Design: Adjust the Width of an Element Using the Width Property

#### Issue Description

When the instructions are done, test doesn't recognise it.

#### Browser Information

* Browser Name: Chrome,
* Operating System: Windows 10

**Comment by systimotic** [comment] 2017-01-21 14:23
Hi @skhamoud! Thank you for reporting this issue.

Can you please share your code? This challenge works fine for me in Chrome.

**Comment by skhamoud** [comment] 2017-01-21 16:00
```
<style>
  h4 {
    text-align: center;
  }
  p {
    text-align: justify;
  }
  .links {
    margin-right: 20px;
    text-align: left;
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
    </div>
  </div>
</div>
```
as instructed test doesn't work

**Comment by systimotic** [comment] 2017-01-21 16:08
@skhamoud 😕 Your exact code works fine for me in Chrome on Windows 10. If you open the console (you can do that by pressing `Ctrl + shift + J`), are there any errors?

**Comment by skhamoud** [comment] 2017-01-21 16:21
No errors whatsoever, that is weird, reloaded page, reset the editor, nothing the test doesn't pass, could it be cache related?

**Comment by systimotic** [comment] 2017-01-21 18:17
@skhamoud That's really weird...
I would ask you to try it in a different browser, but I believe right now Chrome is the only one that works 😅
Are you able to pass other challenges? Can you try it in incognito mode?

**Comment by rweston03** [comment] 2017-01-23 01:40
I'm using Chrome and Windows 10, but mine isn't working, either. My code looks exactly like the code above.

**Comment by gt6089** [comment] 2017-01-24 17:44
Also having this same problem, exactly as above. Tests don't pass, no errors in the console. Chrome, Windows 7.

**Comment by systimotic** [comment] 2017-01-24 20:19
Thank you for confirming @rweston03 @gt6089!

/cc @freeCodeCamp/moderators Can anybody help triage? I can not reproduce 😞

**Comment by Greenheart** [comment] 2017-01-25 12:25
@systimotic I can reproduce in Chrome 55.0.2883.87 (64-bit) for Ubuntu 16.04.

Seems like there could be some problem with the test case. I'll see if I find anything in the seed-files.

**Comment by Greenheart** [comment] 2017-01-25 12:35
Here's the test for this challenge:
```json
"tests": [
  "assert($('.fullCard').css('width') == '245px', 'message: Your code should change the <code>width</code> property of the card to 245 pixels by using the <code>fullCard</code> class selector.');"
],
```

Either there's a problem with `.css()`, or with the comparsion (we should probably use `===` instead of `===`)

**Comment by Greenheart** [comment] 2017-01-25 12:39
Hmm... Interestingly, the next challenge works without any trouble - Even though it uses a very similar test case.

```json
"tests": [
    "assert($('h4').css('height') == '40px', 'message: Your code should change the <code>h4</code> <code>height</code> property to a value of 40 pixels.');"
],
```

**Comment by systimotic** [comment] 2017-01-25 12:44
@Greenheart Thanks for confirming! Can you help debug by running `$('h4').css('height')` in the console? Make sure to switch context from `top` to `fcc-main-frame` first, and try in `fcc-test-frame` as well

**Comment by Greenheart** [comment] 2017-01-25 12:51
@systimotic You must mean `width` right? ;)

**Comment by systimotic** [comment] 2017-01-25 12:59
@Greenheart Whoops! Yeah, I did mean width!
Nice find! So it's a rounding error huh... My initial thought is to round down the result, but there may be a more fundamental problem. I'm thinking there may be a border, margin or padding set that's altering the width? What I really don't understand is that I can't replicate it while I'm using the exact same version of Chrome. Almost makes me suspect screen size comes into play...

**Comment by Greenheart** [comment] 2017-01-25 13:05
@systimotic Hahaha this is hilarious actually!

> Almost makes me suspect screen size comes into play...

1. I'm using 110% zoom, which alters the size of elements...
2. jQuery returns the **computed CSS value**, not the original value from our code.

And we end up with a float value :smile:

When I reset my browser zoom, things work as expected

**Comment by systimotic** [comment] 2017-01-25 13:09
@Greenheart Wow, great find! Yeah, those zoom issues are really annoying... How should we go about fixing this? Would this be a good place for one of those warnings about 100% zoom (like in the Size your Images challenge), or should we only do a code test?

**Comment by Greenheart** [comment] 2017-01-25 13:10
I'm not sure how to solve this but here's a few suggestions:

1. Add something like "Make sure that your browser zoom is set to 100%" either to the description, or as a test case
2. Find a way to bypass zoom levels and get the actual value the user specified in the code. RegEx-test on the `__source` that's sent into the `fcc-test-frame`?
3. Find a way to reset browser zoom for the `fcc-test-frame`

**Comment by Greenheart** [comment] 2017-01-25 13:10
I think a code test could be efficient :blush:

**Comment by wildlifehexagon** [comment] 2017-01-26 01:38
I'm getting the same error with 100% zoom. Also using Chrome and Windows 10.

**Comment by Greenheart** [comment] 2017-01-26 09:39
@wildlifehexagon So, even though you reset the browser zoom, you get the error? :blush:

[This challenge](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property) only passes for me when I have the zoom at the original 100%.

I can only reproduce the bug when the zoom is greater than 100 or less than 100.

**Comment by systimotic** [comment] 2017-01-26 10:09
To add to that, could you also try the tests mentioned in this comment https://github.com/freeCodeCamp/freeCodeCamp/issues/12687#issuecomment-275100288? Make sure to run them in the console, and switch the context to the iFrame.

**Comment by wildlifehexagon** [comment] 2017-01-28 01:34
@Greenheart I just tried it again, and oddly enough I got it to work on 80% zoom but nothing else.

**Comment by Greenheart** [comment] 2017-01-28 01:42
@wildlifehexagon Then it could have something to do with your monitor resolution, like @systimotic pointed out earlier.

@systimotic This should most likely be a regex-test on the __source instead of a dynamic retrieval of the width. Finally a new task... ;)

**Comment by wildlifehexagon** [comment] 2017-01-28 01:43
@systimotic Not 100% sure I'm doing this right, but when I input that code I get the following:

"245.00000610351563px"

**Comment by masters-george** [comment] 2017-01-30 01:12
<style>
  h4 {
    text-align: center;
  }
  p {
    text-align: justify;
  }
  .links {
    margin-right: 20px;
    text-align: left;
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

O/S: Windows 7
Browser: Chrome Version 54.0.2840.99 m -- Unfortunately the Library's computers don't provide console access for security reasons

**Comment by JohnOKeefe15** [comment] 2017-02-21 01:30
I have a partial fix for this bug. On my computer the current code:
```
"tests": [
  "assert($('.fullCard').css('width') == '245px', 'message: Your code should change the <code>width</code> property of the card to 245 pixels by using the <code>fullCard</code> class selector.');"
],
```
fails at all zoom levels except for 50%. If I change the code to the following test: 

```
"tests": [
  "assert(getComputedStyle(document.querySelector('.fullCard')).width = ' 245px', 'message: Your code should change the <code>width</code> property of the card to 245 pixels by using the <code>fullCard</code> class selector.');"
],
```
 it succeeds at all zoom levels except for 90%. Even though this is not a 100% fix it could reduce the number of failed tests that users encounter until a permanent solution is found. Is this worth submitting a pull request for or do you want to wait for a permanent solution?

**Comment by Greenheart** [comment] 2017-02-21 07:53
@JohnOKeefe15 Thanks for taking the time to find a solution! I had completely forgotten `getComputedStyle()` existed, so today I learned something ^^

I think a regex test would be more robust, as the source code should be the same no matter the browser zoom level.

I came up with the following. It can handle formatted as well as not so formatted solutions:
![width-regex-avd-fcc](https://cloud.githubusercontent.com/assets/6125097/23155403/bdacacd2-f812-11e6-8c52-2200c96a54e4.png)

`/.fullCard\s*{\s*width\s*:\s*245px/g`

What do you think?

Would you like to make an OSS contribution and update this test? Me and other contributors would be happy to guide you through the process! :blush:

**Comment by systimotic** [comment] 2017-02-21 12:50
@Greenheart My concern with this regex test is that it will fail if the camper decides to put the width declaration at some other place than the top. I think that that's very likely to happen.

**Comment by Greenheart** [comment] 2017-02-21 14:00
Yeah that's a good point! I thought about it yesterday but couldn't come up
with a full solution.

Basically, we need to check if the camper has the {, then [.|\s]*, then the
line we're looking for (width 245px), then any number if characters
again, [.|\s]* and then the closing bracket, }.

Sorry for the formatting, I'm on mobile :smile:

tisdag 21 februari 2017 skrev Timo <notifications@github.com>:

**Comment by JohnOKeefe15** [comment] 2017-02-21 21:49
@Greenheart I would love to make an OSS contribution and update this test. This would be my first time so I would love it if you could guide me through the process.

**Comment by Greenheart** [comment] 2017-02-21 21:59
@JohnOKeefe15 I'm glad to hear that! :smile:

You can get started by reading [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

When you're all set, [this is where you can find the current challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L83-L137) in the codebase.

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding! :smile:

**Comment by JohnOKeefe15** [comment] 2017-02-22 07:36
@Greenheart OK, I have my dev environment setup in Ubuntu. Unfortunately the problem does not occur on Chrome in Ubuntu so I cannot reproduce the problem. I will need to setup my dev environment in windows so I can hopefully reproduce it there. 

For the REGEX I have a solution created that will work no matter what line the camper puts the width declaration. The question is do I need to test for any characters they add after the declaration? 
What if they put `width: 245px; Stuff that will fail the CSS`? Do I just not worry about that or would that be considered a failure for the test purposes?

**Comment by Greenheart** [comment] 2017-02-22 19:28
@JohnOKeefe15 I think this issue was present in Firefox 50 & 51 for Ubuntu. But verifying your solution in multiple environments would be greatly appreciated if it's not too much work on your side! :+1:

> no matter what line the camper puts the width declaration

Excellent! I'd say that the important part is that they have the width declaration. As I think most people will try to write good code, a proper width declaration anywhere in their CSS-rule could be good enough.

Can the regex handle formatting issues that still are valid CSS like below:
* `width :     245px;`
* `width:245px;`

This coulb be solved by adding a couple of `\s*` (0 o rmore whitespace-characters) in regex.

What do you think? :blush:

**Comment by JohnOKeefe15** [comment] 2017-02-23 03:18
@Greenheart The REGEX I was writing was actually designed to handle all formatting including if they had it commented out or a comment after the semicolon. Since I do not have to worry about what they write after the semicolon I can simplify it slightly. Here is what I arrived at:
`.fullCard\s*{[\s\S]*\n*^\s*width\s*:\s*245px\s*;`

Look good?

**Comment by Greenheart** [comment] 2017-02-23 10:30
@JohnOKeefe15 Nice work! Would you like to submit a PR with your fix? :smile:

**Comment by JohnOKeefe15** [comment] 2017-02-24 02:51
Would love to submit a PR. I will do that later tonight.

**Comment by Greenheart** [comment] 2017-02-24 17:12
@JohnOKeefe15 Great! I can review it but I found a small problem - you've opened the PR against your fork of the freeCodeCamp. Could you open a PR against https://github.com/freeCodeCamp/freeCodeCamp instead?

And no problem, I really like to pay things forward like how I was introduced to the world of OSS one and a half year ago! :smile:

**Closed** 2017-03-01 11:07 UTC
Labels: beta, help wanted, tests

**Comment by chantelbok** [comment] 2018-07-19 22:32
I had this same problem and at 100% zoom in Chrome it did not work. I then went and checked in my display settings on my desktop and saw that I had custom scaling applied to text displays which I then turned off. Afterwards at 100% zoom it worked.
