### ISSUE TITLE
Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by thomaswtx** [freeCodeCamp/freeCodeCamp#15476] opened 2017-06-22 00:42 UTC
#### Challenge Name
https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description
Using the parameter "num" being passed into the function in a for loop causes a crash. Even when assigning the passed parameter to a separate variable and using it in the for loop crashed the program. Example, var newNum = num; for(i = 0; i < newNum; i++) -> crash as well as for(i = 0; i < num; i++) -> crash.

#### Browser Information

* Browser Name, Version:  Chrome, latest version
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code
function sumFibs(num) {
 
  var fibArr = [];
  var newNum = num;

  for(i = 0; i < newNum; i++)
    {     
      fibArr.push(1);
    }
  return fibArr;
}
sumFibs(4);

**Comment by JH108** [comment] 2017-06-22 15:52
I tested your code out and I think the issue is that your code is creating a for loop that will run 4,000,000 times when the third test case is called.  If you were to put a conditional in your code before the loop the browser no longer crashes in my tests.  Below is your example function with an added conditional to keep the third test case from running the loop. 
`function sumFibs(num) {
    var fibArr = [];
    var newNum = num;
    if (num > 1000) {
      return;
    }
    for(i = 0; i < newNum; i++) {
      fibArr.push(1);
    }
    return fibArr;
  }
  sumFibs(4);`
  
I hope this helps.

**Comment by Survivor75** [comment] 2017-08-11 10:11
Fibonacci Numbers grow very fast.
@JH108  is right. You need to do some semantic checking for that. Check out the following code : 
`
function sumFibs(num) {
  var fibs = [1,1];
  var sum = 0;
  var index = 0;
  
  for(index = 2; index < num; ++index)
    fibs.push(fibs[index-1]+fibs[index-2]);
  
  for(index = 0; fibs[index] <= num; ++index)
    if(fibs[index]%2 !== 0)
      sum += fibs[index];
  
  return sum;
}
`

**Comment by ananaymital** [comment] 2017-09-13 18:37
You can add "?run=disabled" at the end of the link. 
For Example: https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers?run=disabled 
and then reset your code. 
Note: You won't be able to run your code unless your remove disabled portion from the url(preferably done after resetting the code).

@BerkeleyTrue @erictleung I think it's safe to close this issue.

**Comment by erictleung** [comment] 2017-09-13 21:14
@ananaymital thanks! Closing as not an issue with the site. @thomaswtx please take a look at the `?run=disabled` advice above. Happy coding!

**Closed by erictleung** 2017-09-13 21:14 UTC
