### ISSUE TITLE
Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by srikarsams** [FreeCodeCamp/FreeCodeCamp#3672] opened 2015-10-09 14:17 UTC
I dont know what to do. It's saying that i need to add space after "view more". But i already added it
![11](https://cloud.githubusercontent.com/assets/11839935/10396209/cdc33b42-6ebe-11e5-8f00-afdf216a0a79.png)

**Comment by Mansuro** [comment] 2015-10-09 15:13
The test is not passing after you did that?

**Comment by bugron** [comment] 2015-10-10 17:30
@srikarsams thanks for posting this issue!
This is caused by the way we are checking if your `p` element contains the text **"View more "**. The test is as follows: `$(\"p\").text().match(/^\\s*View\\smore\\s/gi)`. `$("p").text()` returns **concatenated** text contents of all `p` elements, in this case:
`Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.View more cat photos`.
Note that "View more cat photos" is **at the end**.
Next we use a regular expression to check if your `p` element **begins** with "View more ". This is done because one were able to pass the test with this: `<p><a href="http://www.freecatphotoapp.com">cat photos</a>View more </p>` which is incorrect. So, what is the problem. `$("p").text()` doesn't begin with "View more " that is why you can't pass that test. If you move this `p` element before "Kitty inpsum dolor..." paragraph you'll be able to pass the test.
Also this is from the tests' section:
>Your <code>a</code> element **should be nested** within your new <code>p</code> element.

So the test wants you actually to put your existing `a` element in a new `p` element **only** and not move that new `p` element anywhere.
Hopefully this clarifies the issue. I'll let it open for a while, waiting for suggestions.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by bugron** [comment] 2015-10-24 17:24
Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Closed by bugron** 2015-10-24 17:24 UTC

**Comment by arvpande** [comment] 2015-12-02 02:50
Below is my HTML code, but I'm also observing the same issue, though I moved the new p element to top.


<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
<p>
  View more <a href="http://freecatphotoapp.com">cat photos</a>
  </p>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the

**Comment by arvpande** [comment] 2015-12-02 02:54
Below is the screen shot,
![screenshot from 2015-12-02 08 23 01](https://cloud.githubusercontent.com/assets/8789109/11520967/030dd9f4-98ce-11e5-91d2-7a037cdfe949.png)

**Comment by sunandakothapalli** [comment] 2016-01-05 20:43
Your a element should be nested within your new p element. -please help

**Comment by ckbrewer15** [comment] 2016-03-09 23:09
I was getting this same issue because I was creating a new href element when you're actually supposed to use the existing href in the code already, not create a new one. I just didn't read close enough.

**Comment by ckbrewer15** [comment] 2016-03-10 22:13
Remove the second link for cat photos. You are only suppose to have a single link. If you read closely the instructions say to use the current link, not make a new one.

**Comment by Zet358** [comment] 2016-04-22 17:57
![nesting](https://cloud.githubusercontent.com/assets/18613446/14750297/51fcfb56-08c4-11e6-9f4e-36636439848d.PNG)

I am new at it but above is what I did to clear the stage

**Comment by Zayne12** [comment] 2016-05-11 04:31
Thank you ckbrewer15, you're  the man bro!!!

**Comment by Zayne12** [comment] 2016-05-11 04:32
removing the other link like ckbrewer15 said fixed the issue!!!

**Comment by samuelsmith442** [comment] 2016-10-28 15:10
p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by IonZero1** [comment] 2016-12-14 22:20
```

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
`
```

**Comment by Milan-Varghese** [comment] 2019-08-14 17:36
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>View more
<a href="http://www.freecatphotoapp.com">cat photos</a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
`

**Comment by ranjith-git** [comment] 2020-04-19 06:46
<h2>CatPhotoApp</h2>
<main>

  <a href="http://freecatphotoapp.com" target="_blank">cat photos</a>

  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">

  <p>View more <a href="http://freecatphotoapp.com">cat photos</a></p>

  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  
</main>

**Comment by ranjith-git** [comment] 2020-04-19 06:47
<h2>CatPhotoApp</h2>
<main>

  <a href="http://freecatphotoapp.com" target="_blank">cat photos</a>

  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  <p>View more <a href="http://freecatphotoapp.com">cat photos</a></p>
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  
</main>

**Comment by rafs2n** [comment] 2021-06-16 15:36
Just remove the first anchor tag.
