### ISSUE TITLE
Cursor Skipping in Code Display

### ISSUE THREAD

**Issue by Will-Campbell** [FreeCodeCamp/FreeCodeCamp#7605] opened 2016-03-18 04:31 UTC
Challenge [Add Font Awesome Icons to all of our Buttons](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**I'm not sure if this is just on my machine or not:** When i'm trying to access a certain part of my code, the cursor keeps skipping over code when i try to navigate to the target area ( both mouse and directional keys), and as such i can not edit it to progress. 

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by Awdesh** [comment] 2016-03-18 04:41
I've tried your code in Windows/Mozilla environment and was not able to reproduce the workflow.

**Comment by alistermada** [comment] 2016-03-18 05:59
Seems to be related to issue #7528.

**Comment by raisedadead** [comment] 2016-03-18 08:16
@Will-Campbell Thanks a lot for the issue. And apologies for the inconvenience.

I have been unable to reproduce this, but as seen others have been reproducing this as well. We should start looking into this.

Thanks @alistermada for pointing out the related issue.

Closing this in favor of #7528 . Please continue the discussion there.

**Closed by raisedadead** 2016-03-18 08:16 UTC

**Comment by aishwarya217** [comment] 2016-04-12 08:44
Facing the same issue.

**Comment by monjardinsecret** [comment] 2016-06-15 07:11
having the same issue too
