### ISSUE TITLE
we want video to discuss how to use website to learn from it

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#45704] opened 2022-04-16 23:05 UTC
## Your code

```




```

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by nhcarrigan** [comment] 2022-04-18 14:44
Hey there! Thanks for opening this issue. Could you provide some more information about the video you are requesting?

**Comment by GAbdulWahab** [comment] 2022-04-18 18:35
@nhcarrigan  demo video discusses how open path learning  and learns if he does not understand try open video help 
 because when I came to learn from your website I do not understand how to use it  and how I benefit from it 
 this video should be Find it when anyone tries to open FreeCodeCamp  to learn how to code

**Comment by mattaminilari** [comment] 2022-04-24 17:49
I created a tutorial video on how to use the website, should I just upload it to YouTube?

**Comment by mattaminilari** [comment] 2022-04-24 18:51
https://vimeo.com/702608462

**Comment by moT01** [comment] 2022-05-03 19:38
Awesome video @mattaminilari 🎉

I'm not sure what to do with it though, I don't think there's really a spot for it on the website. The user who requested it has deleted their account. I guess you could make a forum post with a link to it - or maybe write a news article about it and apply as an author.

I'm really curious what happened at 4:10 to get that error in the preview. I couldn't reproduce it.

Seeing as how this isn't an issue that needs to be resolved, I think it's safe to close it. I will leave it open for now in case anyone else wants to weigh in.

**Comment by nhcarrigan** [comment] 2022-05-03 19:56
I think this is safe to close - if further discussion is warranted, we can always revisit it.

**Closed by nhcarrigan** 2022-05-03 19:56 UTC
Labels: scope: curriculum, type: feature request
