### ISSUE TITLE
Chrome Dev Tools: I can pass the challenge without submitting any answer

### ISSUE THREAD

**Issue by lyrakisk** [freeCodeCamp/freeCodeCamp#12940] opened 2017-01-28 17:29 UTC
#### Challenge Name
https://www.freecodecamp.com/videos/chrome-dev-tools-elements

#### Issue Description
At the questions section, I can pass the challenge without submitting any answer, just by dragging left or right the question.

#### Browser Information
* Browser Name, Version: Firefox 51.0.1 
* Operating System: Windows 7, 64 bit
* Mobile, Desktop, or Tablet: Desktop

#### Video 
https://www.youtube.com/watch?v=zWw9hlZO84U&feature=youtu.be

**Comment by Greenheart** [comment] 2017-01-28 23:06
@lyrakisk Thanks for reporting this!

I believe this is intentional by design, to make it easier to use on touch-devices. By dragging left or right you essentially choose your answer.

Technically, this could be clarified either by some instruction, or preferably, by adding arrow icons or swipe-animations to this component. However, I'm not sure it's necessary at the moment.

@freeCodeCamp/moderators What do you think?

**Comment by systimotic** [comment] 2017-02-02 18:33
I agree that this does look like it's intentional, and I also agree that it's confusing.
When I swipe/drag to a side, I don't know if the side I'm dragging to means I'm answering true or false.

**Comment by Greenheart** [comment] 2017-02-02 19:44
Maybe we could highlight the side that was selected? For example by temporarily adding a background color to either the true or the false button?

**Comment by QuincyLarson** [comment] 2017-02-07 07:43
We aren't planning to have this quiz functionality in the future. Instead, we plan to just pull in the videos directly from YouTube. So I'm closing this issue for now.

**Closed by QuincyLarson** 2017-02-07 07:43 UTC
Labels: discussing, UX
