### ISSUE TITLE
Russian Translation of HTML5 and CSS

### ISSUE THREAD

**Issue by troglotit** [FreeCodeCamp/FreeCodeCamp#7747] opened 2016-03-27 10:48 UTC
- [ ] Say Hello to HTML Elements
- [ ] Headline with the h2 Element
- [ ] Inform with the Paragraph Element
- [ ] Uncomment HTML
- [ ] Comment out HTML
- [ ] Fill in the Blank with Placeholder Text
- [ ] Delete HTML Element
- [ ] Change the Color of Text
- [ ] Use CSS Selectors to Style Elements
- [ ] Use a CSS Class to Style an Element
- [ ] Style Multiple Elements with a CSS Class
- [ ] Change the Font Size of an Element
- [ ] Set the Font Family of an Element
- [ ] Import a Google Font
- [ ] Specify How Fonts Should Degrade
- [ ] Add Images to your Website
- [ ] Size your Images
- [ ] Add Borders Around your Elements
- [ ] Add Roundede Corners with a Border Radius
- [ ] Make Circular Images with a Border Radius
- [ ] Link to External Pages with Anchor Elements
- [ ] Nest an Anchor Element within a Paragraph
- [ ] Make Dead Links usig the Hash Symbol
- [ ] Turn an Image into a Link
- [ ] Add Alt Text to an Image for Accessebility
- [ ] Create a Bulleted Unordered List
- [ ] Create an Ordered List
- [ ] Create a TextField
- [ ] Add Placeholder Text to a Text Field
- [ ] Create a Form Eleemnt
- [ ] Add a Submit Button to a Form Use HTML5 to Require a Field
- [ ] Create a Set of Radio Buttons
- [ ] Create a Set of Checkboxes
- [ ] Check Radio Buttons and Checkboxes by Default
- [ ] Nest Many Elements within a Single Div Element
- [ ] Give a Background Color to a Div Element
- [ ] Sset the ID of an Element
- [ ] Use an Id Attribute to Style an Element
- [ ] Adjusting the Padding of an Element
- [ ] Adjust the Margin of an Element
- [ ] Add a Negative Margin to an Element
- [ ] Add Different Padding to Each Side of an Element
- [ ] Add Different Margins to Each Side of an Element
- [ ] Use Clockwise Notation to Specify the Padding of an Element
- [ ] Use Clockwise Notation to Specify the Margin of an Element
- [ ] Style the HTML Body Element
- [ ] Inherit Styles from the Body Element
- [ ] Prioritize One Style Over Another
- [ ] Override Styles in Subsequent CSS
- [ ] Override Class Declarations by Styling ID Attributes
- [ ] Override Class Declarations with Inline Styles
- [ ] Override All Other Stlyes by using Important
- [ ] Use Hex Code for Specific Colors
- [ ] Use Hex Code to Color Elements White
- [ ] Use Hex Code to Color Elements Red
- [ ] Use Hex Code to Color Elements Green
- [ ] Use Hex Code to Color Elements Blue
- [ ] Use Hex Code to Mix Colors
- [ ] Use Hex Code to Color Elements Gray
- [ ] Use Hex Code for Specific Shades of Gray
- [ ] Use Abbreviated Hex Code
- [ ] Use RGB values to Color Elements
- [ ] Use RGB to Color Elements White
- [ ] Use RGB to Color Elements Red
- [ ] Use RGB to Color Elements Green
- [ ] Use RGB to Color Elements Blue
- [ ] Use RGB to Mix Color

I've written this by hand, so feel free to point out typos and missed items!

**Comment by troglotit** [comment] 2016-03-27 10:51
I'll take first, let's say, 10 items, (til "Use a CSS Class to Style an Element").

Feel free to take another items!

**Comment by LyashenkoGS** [comment] 2016-03-29 11:10
Hi there 
<ol>
 <li>Style Multiple Elements with a CSS Class Стилизируйте несколько элементов СSS классом</li>
 <li> Change the Font Size of an Element  Измените размер шрифта элемента</li>
 <li> Set the Font Family of an Element   Установите тип шрифта элемента</li>
 <li> Import a Google Font                 Импортируйте Google Font	</li>
 <li> Specify How Fonts Should Degrade      Укажите как должны изменятся шрифты</li>
 <li> Add Images to your Website           Добавьте картинки к Вашему сайту</li>
 <li> Size your Images                     Настройте размер Ваших картинок</li>
 <li> Add Borders Around your Elements     Добавьте рамки вокруг Ваших элементов</li>
 <li> Add Roundede Corners with a Border Radius  Добавьте скругление углов с  Border Radius</li>
 <li> Make Circular Images with a Border Radius Сделайте картинки круглыми с Border Radius</li>
 </ol>

**Comment by troglotit** [comment] 2016-03-31 04:56
@LyashenkoGS Hey! I'm a little upset to inform you that this issue was duplicated at #7752 and already closed. But you can review the translations at #7772.

**Comment by sludge256** [comment] 2016-03-31 05:03
@troglotit thanks for catching that.

Closing as duplicate of #7752

**Closed by sludge256** 2016-03-31 05:03 UTC
Labels: translation
