### ISSUE TITLE
Last test on the challenge includes 2 when it shouldn't

### ISSUE THREAD

**Issue by Psarna94** [FreeCodeCamp/FreeCodeCamp#4325] opened 2015-11-12 10:41 UTC
Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20arr%20%3D%20arr.filter(func)%3B%0A%0A%20%20return%20arr%3B%7D%0A%0Adrop(%5B1%2C%202%2C%203%5D%2C%20function(n)%20%7Breturn%20n%20%3C%203%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  // Drop them elements.
 arr = arr.filter(func);

  return arr;}

drop([1, 2, 3], function(n) {return n < 3; });

```

The last test case has a function showing n>2, however, the result set has a 2 in it.

**Comment by faizaanceg** [comment] 2015-11-12 10:45
Duplicate of #4278 . The question is correct and so is the test case

**Closed** 2015-11-12 16:28 UTC
