### ISSUE TITLE
"Unexpected token )"

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/freecodecamp#1450] opened 2015-08-02 03:36 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This waypoint loads with the error "Unexpected token )". Unable to submit because of this.

**Comment by BerkeleyTrue** [comment] 2015-08-02 13:57
I cannot reproduce. Can you try clearing your cache?

**Comment by wildlifehexagon** [comment] 2015-08-02 20:59
I tried clearing the cache but it didn't help. I'm using Chrome Version 44.0.2403.125 m on Windows 10.

**Comment by benmcmahon100** [comment] 2015-08-03 14:03
This is an issue I think i pushed a fix for this but i'll check and push it if not

**Comment by BerkeleyTrue** [comment] 2015-08-03 22:52
@benmcmahon100 where you able to fix this?

**Comment by BerkeleyTrue** [comment] 2015-08-03 23:21
Just pushed new stuff up. I'm still seeing this.

**Comment by benmcmahon100** [comment] 2015-08-03 23:39
Yep sorry on this!

**Comment by BerkeleyTrue** [comment] 2015-08-03 23:45
No worries, I think there is a typo somewhere with the first test on this challenge.

**Comment by benmcmahon100** [comment] 2015-08-03 23:50
the asset( part is actually missing :p

**Closed** 2015-08-03 23:54 UTC
Labels: Beta Site, confirmed, help wanted

**Comment by kyrize** [comment] 2015-08-04 00:16
Awesome. Thanks man.

**Comment by BerkeleyTrue** [comment] 2015-08-04 00:25
You are welcome! Fix is live!
