### ISSUE TITLE
Code won't work

### ISSUE THREAD

**Issue by ccsears** [FreeCodeCamp/FreeCodeCamp#3495] opened 2015-09-25 12:50 UTC
Challenge Bonfire: Seek and Destroy has an issue.
User Agent is: Mozilla/5.0 (Windows NT 6.1; rv:40.0) Gecko/20100101 Firefox/40.0.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

function destroyer(arr) {
  // Remove all the values

 var arr = arguments[0];
 var z = [];
 var j = 0;
 for (i = 1; i < arguments.length-1; i++) {
    z[j]=arguments[i];
    j = j+1;
  }

  var chris = 0;
  var leny = arr.length;
  for (i = 0; i < z.length; i++) {
   for (k = 0; k < z.length; k++) {
     chris = arr.indexOf(z[k]);
     if (chris != -1) {
       arr.splice(chris, 1);
     }
   }
  }

  return arr;
}

destroyer(["tree", "hamburger", 53], "tree", 53, "");

**Comment by ccsears** [comment] 2015-09-25 12:51
It passes all the test listed. I tried every test case and they ALL came back with a red "X". However in the black display box it had the CORRECT answer. Did you even run my solution?

**Comment by jhealy86** [comment] 2015-09-25 13:21
This is a duplicate of #3487. Please don't open duplicate issue reports, especially for ones that have been looked over and closed previously.

**Comment by bugron** [comment] 2015-09-25 13:59
@ccsears thanks for posting this issue!
Note that your issue is a duplicate of your another issue: #3487 so I'll close this one. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-25 13:59 UTC
