### ISSUE TITLE
fccss and fcces not being properly replaced on challenges

### ISSUE THREAD

**Issue by knifecake** [FreeCodeCamp/FreeCodeCamp#2243] opened 2015-08-19 23:25 UTC
The `fccss` and `fcces` keywords which stand for `<script>` and `</script>` are not being replaced properly. A quick search on the codebase revealed that it is `public/js/lib/coursewares/coursewaresHCJQFramework_0.1.9.js` who should be doing this but the code is commented out:

```
***
  codeStorage.updateStorage();
};
/*
var challengeSeed = challengeSeed || null;
var allSeeds = '';
(function() {
  challengeSeed.forEach(function(elem) {
    allSeeds += elem.replace(/fccss/g, '<script>').replace(/fcces/g,'</script>') + '\n';
  });
  editor.setValue(allSeeds);
  (function() {
    setTimeout(function() {
      editor.refresh();
    }, 200);
  })();
})();
*/
```

This results in challenges looking like this and not working properly, although manually inserting script tags allows the user to continue.

<img width="790" alt="screen shot 2015-08-20 at 1 19 23 am" src="https://cloud.githubusercontent.com/assets/1644991/9372005/eab0b1ba-46d9-11e5-8671-8e68e90b5557.png">

Issue #2242 describes the same problem.

**Comment by BerkeleyTrue** [comment] 2015-08-21 00:45
@benmcmahon100 Isn't this fixed?

**Comment by BerkeleyTrue** [comment] 2015-08-21 04:12
Closing as duplicate of #2242

**Closed by BerkeleyTrue** 2015-08-21 04:12 UTC
