### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by dmn88mia** [FreeCodeCamp/FreeCodeCamp#2347] opened 2015-08-20 19:24 UTC
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Section "Waypoint: Generate Random Whole Numbers with JavaScript"
Just a typo , the word "lot" 

but it's even more useful if we "lot" more useful to generate a random whole number.

**Comment by issyl0** [comment] 2015-08-22 16:53
Thanks for reporting this! It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:

**Comment by issyl0** [comment] 2015-08-22 17:02
Duplicate of #2086.

**Closed** 2015-08-22 17:03 UTC
