### ISSUE TITLE
Error in ES6: Declare a Read-Only Variable with the const Keyword

### ISSUE THREAD

**Issue by Ems2theLee** [freeCodeCamp/freeCodeCamp#17679] opened 2018-06-21 22:05 UTC
#### Describe your problem and - if possible - how to reproduce it
I'm getting an error with the final test, despite having made the simple changes called for on the page:
console.log should be changed to print the SENTENCE variable.

Additionally I get a note of "invalid regular expression flag s" in the test box when run. 

My code:
function printManyTimes(str) {
  "use strict";

  // change code below this line

  const SENTENCE = str + " is cool!";
  for(let i = 0; i < str.length; i+=2) {
    console.log(SENTENCE);
  }

  // change code above this line

}
printManyTimes("freeCodeCamp");

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword

#### Tell us about your browser and operating system

* Browser Name: Firefox 
* Browser Version: 60.0.2 (64-bit)
* Operating System: Windows 10 home

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/23280665/41747925-8abd15fc-7564-11e8-8849-2ce6a764a8b4.png)

**Comment by thomlom** [comment] 2018-06-22 06:06
It seems that the regex used to verify the `console.log` statement is incorrect. I got the fix 🙂

**Comment by thekholm80** [comment] 2018-06-24 01:31
Hi, using the code below I get the following test result, with the last test failing to pass:

```
// running test
Unexpected token ?
// tests completed
```
code:
```
function printManyTimes(str) {
  "use strict";

  // change code below this line

  const SENTENCE = str + " is cool!";
  for(let i = 0; i < str.length; i+=2) {
    console.log(SENTENCE);
  }

  // change code above this line

}
printManyTimes("freeCodeCamp");
```

**Comment by jargonfilter** [comment] 2018-06-24 22:15
Getting the exact same problem as @thekholm80 is getting.

**Comment by karan171996** [comment] 2018-06-25 10:11
Geeting the same error 
`// running test
Unexpected token ?
// tests completed`

code:
`function printManyTimes(str) {
  "use strict";

  // change code below this line

  const SENTENCE = str + " is cool!";
  for(let i = 0; i < str.length; i+=2) {
    console.log(SENTENCE);
  }

  // change code above this line

}
printManyTimes("freeCodeCamp");`

**Comment by karan171996** [comment] 2018-06-25 10:12
Getting the same error
`
// running test
Unexpected token ?
// tests completed
`

**Comment by chinnghiemtuc** [comment] 2018-06-25 11:53
Me too...when i check in esconsole.com it's okay.

**Comment by EdwardHanlon30** [comment] 2018-06-25 23:49
Unexpected token ?


Please fix this error

**Comment by hangngopham** [comment] 2018-06-26 00:57
I also got the exact same problem:Unexpected token ?

**Comment by aaldea** [comment] 2018-06-26 02:12
I know someone said they have the fix, but I am also getting the same error.

**Comment by valdinei11** [comment] 2018-06-26 18:02
I tested right now this challenge. My message error is different:
```
// running test
invalid regular expression flag s
// tests completed
```

**Comment by petervann** [comment] 2018-06-26 18:19
I just tested this:
```
function printManyTimes(str) {
  "use strict";
  // change code below this line
  const SENTENCE = str + " is cool!";
  for(let i = 0; i < str.length; i+=2) {
    console.log(SENTENCE);
  }
  // change code above this line
}
printManyTimes("freeCodeCamp");
```
And still get this response:
```
// running test
Unexpected token ?
// tests completed
```

**Comment by harrisalisha** [comment] 2018-06-26 18:22
same.. me too..

**Comment by thomlom** [comment] 2018-06-26 18:36
The problem is known and it is being fixed.

**Comment by hermanomark** [comment] 2018-06-27 04:12
ow! I'm not the only one :)

**Comment by jdmagic21** [comment] 2018-06-28 01:42
I was really looking forward to getting another green check circle. :)

**Comment by nyel-dev** [comment] 2018-06-28 04:14
Just stumbled upon this problem. Weird.

**Comment by badarshahzad** [comment] 2018-06-28 07:05
Wow! a number of comments already here. Count me in as I am also facing the same problem. :smile:

**Comment by Cyniikal** [comment] 2018-06-29 04:17
Also having the exact same problem "Unexpected token ?"

**Comment by Ems2theLee** [comment] 2018-06-29 06:44
@dilipsingh94 Go to the curriculum link on the top right and then click the lesson after this one in the ES6 unit to keep going. I don't think the certification can be completed till it's fixed, but you can keep working towards it while you wait.

**Comment by petervann** [comment] 2018-06-29 17:21
I was able to complete everything except this challenge and was able to claim the certification.

I keep checking back because I'd still like to pass this challenge, though.

**Comment by dilipsingh94** [comment] 2018-06-29 20:47
@Ems2theLee thanks

**Comment by MinSomai** [comment] 2018-06-30 13:06
same problem here.

**Comment by kalzimonium** [comment] 2018-07-02 04:13
It's still occurring. Hasn't been fixed yet.

**Comment by thomlom** [comment] 2018-07-02 05:32
What error do you guys get ? This is working fine for me and has been fixed on my side.

**Comment by Ems2theLee** [comment] 2018-07-02 05:43
@thomlom It's cleared for me now too. Might just need a hard refresh?

**Comment by dilipsingh94** [comment] 2018-07-02 05:47
@thomlom  thank it's working now

**Comment by petervann** [comment] 2018-07-02 06:19
Hey - wow - yes it is indeed working now!?!  I just passed that challenge!  Coolio and finally!?!  (FYI, though - I have two certs under my belt now, which means I have completed 10 projects, but my Welcome page says that I have only completed 5 out of 30 projects!?!  I was able to 'claim' both certs, so there is definitely a disconnect somewhere!?!)

**Comment by Ems2theLee** [comment] 2018-07-02 17:24
Seems to be working for everyone now, so I am going to close the issue. Thank you for taking care of it @thomlom!

**Comment by kalzimonium** [comment] 2018-07-03 00:49
Still not working for me.

**Comment by Ems2theLee** [comment] 2018-07-03 01:22
@kalzimonium Is it giving you the regex error or the unexpected token one? Could you screenshot your results?

**Comment by kalzimonium** [comment] 2018-07-03 12:32
Didn’t work last night at the time I posted that comment. Checked it out this morning and it was fixed. Thank you, sir. I’m good now :)

**Closed** 2018-07-03 15:00 UTC
