### ISSUE TITLE
Cannot open drop-down menu of each session on Map page

### ISSUE THREAD

**Issue by BerlinaLI** [freeCodeCamp/freeCodeCamp#16553] opened 2018-01-22 07:34 UTC
Cannot open drop-down menu of each session on Map. 
[https://beta.freecodecamp.org/en/challenges/functional-programming/understand-the-hazards-of-using-imperative-code](https://beta.freecodecamp.org/en/challenges/functional-programming/understand-the-hazards-of-using-imperative-code)

#### Description
On the Map page, I cannot open sub-nav of each big session.
like when i clicked Responsive Web Design, nothing shows up below. 
So I cannot select any challenge and review it.
<img width="316" alt="default" src="https://user-images.githubusercontent.com/8443821/35209537-88482f6a-ff89-11e7-9e42-f22eb1e6cd5e.png">

#### Browser Information
* Browser Name, Version:  chrome 63.0.3239.132(most up to date)
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet:

**Comment by Asjas** [comment] 2018-01-22 07:49
Hi @BerlinaLI 

It seems you are experiencing the same issue as reported here #16468 and #16433. The FCC team are investigating the issue. They last mentioned in #16468 that they will be updating the beta soon with fixes so the site will hopefully be more stable.

**Comment by raisedadead** [comment] 2018-01-23 05:29
Hi @BerlinaLI yup, this seems to be a known issue at certain times. And as @Asjas said we are planning a update on beta... unfortunately we do not have a timeline to confirm. Thanks for reporting.

Closing as Duplicate of #16468

**Closed by raisedadead** 2018-01-23 05:29 UTC
