### ISSUE TITLE
Misspell

### ISSUE THREAD

**Issue by HanzoCode** [FreeCodeCamp/FreeCodeCamp#1879] opened 2015-08-17 17:55 UTC
There is 
Try looking at the lastLetterOfLastName variable declaration if you get stuck.

but should be 

Try looking at the lastLetterOfFirstName variable declaration if you get stuck.

**Comment by AryanJ-NYC** [comment] 2015-08-17 17:56
Duplicate of #1877.

**Closed** 2015-08-26 00:13 UTC
