### ISSUE TITLE
Your twitch Example site is not working.

### ISSUE THREAD

**Issue by nfabacus** [FreeCodeCamp/FreeCodeCamp#10783] opened 2016-09-17 19:33 UTC
#### Twitch TV challenge
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description
Your example site https://codepen.io/FreeCodeCamp/full/Myvqmo/ is not working.  link to each Twitch Channel is 404.  Also, channel information is not displayed properley - it just says "Account Closed" for all the channels.

#### Browser Information
Chrome on MAC desktop

**Comment by phyrenight** [comment] 2016-09-17 20:25
Twitch recently did an update and now all Kraken api request require a client id to work.You can find further info [here](https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.4t65wm79d)

**Comment by phyrenight** [comment] 2016-09-17 20:48
This might be caused by the new update to Twitch's api. Twitch made it so all kraken api request need a client id. You can find further info on this [here](https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.4t65wm79d).

**Comment by dhcodes** [comment] 2016-09-18 21:45
Closing as duplicate of #10740. Thanks

**Closed by dhcodes** 2016-09-18 21:45 UTC

**Comment by nfabacus** [comment] 2016-09-21 20:54
I have fixed my own site. But, the link you have on your site  https://codepen.io/FreeCodeCamp/full/Myvqmo/ is still not working.  I just wonder you may want to update the code?
