### ISSUE TITLE
A bug!

### ISSUE THREAD

**Issue by PrateekCoder** [FreeCodeCamp/FreeCodeCamp#2328] opened 2015-08-20 15:17 UTC
Hi, guys appreciate your effort i just found a bug, well it is the streak bug, i came back on freecodecamp after more than 3 weeks and when i checked my profile it says your current streak as 35 days and you longest streak as 35 days. though the calender which shows the days i have done coding on freecodecamp is showing the correct data.

**Comment by jbmartinez** [comment] 2015-08-21 03:06
Duplicate of #2290. Thanks for reporting

**Closed** 2015-08-21 03:51 UTC
