### ISSUE TITLE
error when `npm install` on `npm run synk-protect`

### ISSUE THREAD

**Issue by cmal** [FreeCodeCamp/FreeCodeCamp#11675] opened 2016-11-16 07:04 UTC
```
[freecodecamp@0.1.0] scripts.prepublish: "npm run snyk-protect"

> freecodecamp@0.1.0 snyk-protect /Users/yuzhao/gits/FreeCodeCamp
> snyk protect

super fail Error: EMFILE: too many open files, open '/Users/yuzhao/.config/configstore/snyk.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.1.4.0@configstore/index.js:34:26)
    at Object.Configstore.get (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.1.4.0@configstore/index.js:81:13)
    at postAnalytics (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.1.19.1@snyk/lib/analytics.js:39:19)
    at analytics (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.1.19.1@snyk/lib/analytics.js:33:10)
    at /Users/yuzhao/gits/FreeCodeCamp/node_modules/.1.19.1@snyk/cli/index.js:40:13
    at tryCatch (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.3.3.1@es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/Users/yuzhao/gits/FreeCodeCamp/node_modules/.3.3.1@es6-promise/dist/es6-promise.js:425:13)
All packages installed (2 packages installed from git, use 6m, speed 0B/s, json 0(0B), tarball 0B)


```

**Comment by raisedadead** [comment] 2016-11-17 05:00
@cmal please provide details of your OS.

By the looks of it, is there an orphaned process already running? you could kill all your terminals and check with a fresh clone (clean setup, purging all you `node_modules`).

Hit us up in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need any help, with that.

**Comment by cmal** [comment] 2016-11-18 13:09
Though the same error still complains when run `npm install`, `gulp` works for me now.

**Comment by raisedadead** [comment] 2016-11-18 13:53
> please provide details of your OS

I can't seem to reproduce the issue on mine... :disappointed:

**Comment by cmal** [comment] 2016-11-18 16:55
I asked this question on the gitter channel you provide me. Someone told me to set nlimit -n to a large number. Though still getting fatal error messages, npm install seems completed and gulp can run now.

**Comment by raisedadead** [comment] 2016-11-18 17:06
@cmal thanks and good to know that you have been following up on the chat. Just checked.

Just go through the CONTRIBUTING guide for setup instructions if you haven't already. Make sure that you have all the pre-requisites installed on your system whatever operating system you are on.

If still facing please comment, with your **OS version** details etc.

Closing as not a bug in the codebase. most likely a configuration issue.

**Closed by raisedadead** 2016-11-18 17:06 UTC

**Comment by cmal** [comment] 2016-11-19 00:23
> [freecodecamp@0.1.0] scripts.prepublish: "npm run snyk-protect"
> 
> > freecodecamp@0.1.0 snyk-protect /Users/yuzhao/gits/FreeCodeCamp
> > snyk protect
> 
> An unknown error occurred. Please include the trace below when reporting to Snyk:
> 
> Error: ENFILE: file table overflow, scandir '/Users/yuzhao/gits/FreeCodeCamp/node_modules/watchpack/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/randomatic/node_modules/is-number/node_modules/kind-of/node_modules'
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "snyk-protect"
> npm ERR! node v7.1.0
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! freecodecamp@0.1.0 snyk-protect: `snyk protect`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the freecodecamp@0.1.0 snyk-protect script 'snyk protect'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the freecodecamp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     snyk protect
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs freecodecamp
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls freecodecamp
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/yuzhao/gits/FreeCodeCamp/npm-debug.log
> Error: Run "sh -c npm run snyk-protect" error, exit code 1
>     at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> npminstall version: 2.2.1

Above is the final errors. Maybe someone would found the problem.
