### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by ChristianLe87** [FreeCodeCamp/FreeCodeCamp#2859] opened 2015-08-29 22:10 UTC
The: "Add the img-responsive class to your top image." doesn't work

**Comment by jasonfavors** [comment] 2015-08-30 03:01
Unable to reproduce.  Can you provide more specifics as to what isn't working?

Assuming you're referring to the following challenge: http://freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap

**Comment by BerkeleyTrue** [comment] 2015-08-30 06:02
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-30 06:02 UTC
