### ISSUE TITLE
It passes the check, but doesn't redirect me to next lesson.

### ISSUE THREAD

**Issue by Progern** [FreeCodeCamp/FreeCodeCamp#6636] opened 2016-02-01 10:59 UTC
Challenge [Use HTML5 to Require a Field](http://www.freecodecamp.com/challenges/use-html5-to-require-a-field#_=_) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" required placeholder="cat photo URL">
  <button type="submit">Submit</button>
</form>

```

I've tried hard refresh, logging in and logging out, deleting the required fields, and then adding them again, it just doesn't go on.
![default](https://cloud.githubusercontent.com/assets/16916594/12715555/99e9abe2-c8e3-11e5-8b76-e422aa9892fb.png)

**Comment by AkiraLaine** [comment] 2016-02-01 11:07
Might be related to #6633

**Comment by bugron** [comment] 2016-02-01 11:08
@Progern thanks for posting this issue!
I'm going to close this issue as a duplicate of #6633 but, please, comment there your issue and post a screenshot of your browser's console and Network tab too, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-02-01 11:08 UTC
