### ISSUE TITLE
[develop] Error loading editor with Safari

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41893] opened 2021-04-22 14:29 UTC
Using `npm run develop` and Safari, trying to load a challenge that has the editor gives an error...
![Screen Shot 2021-04-22 at 8 22 03 AM](https://user-images.githubusercontent.com/20648924/115730367-dc5eb100-a34b-11eb-8a35-652ac4e766d6.png)

This pops up on the page and it is stuck. You can't close the pop up or get to the challenge in any way. I frequently saw this pop up on firefox as well, but you were able to close it and continue to the challenge. It didn't show up on firefox after a few quick tries, so I think it may not be an issue with it anymore.

I don't think it's a huge issue - a workaround is to build the site locally, then the popup doesn't show.

**Comment by ShaunSHamilton** [comment] 2021-04-22 15:11
Tom, where is the trace for the error? Can you find the line (culprit) in the source?

**Comment by raisedadead** [comment] 2021-04-22 15:17
The staging site is ready at https://www.freecodecamp.dev/learn is ready with 824d5f9fdf1e279c8f331a81cc94eeba5565515a if you want to test this on a prod build for differences.

**Comment by raisedadead** [comment] 2021-04-28 06:50
Hey @moT01 did you get anywhere in grabbing traces or pointers to identify the root cause?

**Comment by moT01** [comment] 2021-05-05 03:30
[Here's what I see in my console](https://raw.githubusercontent.com/moT01/moT01/master/console.png). Looks like maybe the loadable and reach-router packages?

**Comment by raisedadead** [comment] 2021-05-05 06:33
Thanks, and can you give us the exact (explaining to a 5yr old) steps to reproduce this as well. Will give it a shot on.

**Comment by Sembauke** [comment] 2021-05-05 13:23
I've seen `component (DevOverlay) while rendering a different component (InnerLoadable)` on I believe Firefox.

**Comment by moT01** [comment] 2021-05-05 13:24
Run the site with `npm run develop`. Then, using Safari, go to the very first challenge.

**Comment by Sembauke** [comment] 2021-05-05 13:44
> I've seen `component (DevOverlay) while rendering a different component (InnerLoadable)` on I believe Firefox as well.

![image](https://user-images.githubusercontent.com/46919888/117150840-cffd3e00-adb8-11eb-9a6d-836e250562d8.png)

**Comment by raisedadead** [comment] 2021-05-05 14:01
So, I tried this and it looks like a dev-only issue and by visiting the page you are requesting things "too quickly" that gatsby's now "on-demand hyper-optimized dev-only" mode is not able to cope with.

This is DX issue and doesn't affect end users at all. I would close this a non-issue unless someone is interested in digging deep into this.

**Comment by moT01** [comment] 2021-05-05 14:08
The only problem with it is that when Safari specific issues come up, you have to `npm run build` to test/debug/fix things - which takes quite a while longer. Not a huge problem, but a fix would be nice.

**Comment by Nirajn2311** [comment] 2021-05-14 20:07
I just tried it using Safari and din't face this issue.

**Comment by ojeytonwilliams** [comment] 2021-05-14 20:23
@moT01 spotted an issue in the Monaco patch notes. It should be fixed now.

**Closed** 2021-05-15 07:01 UTC
Labels: type: bug
