### ISSUE TITLE
Why do i get this reply  "Error: Plugin failed to initialize" Please help me. I want to proceed with the next chapters

### ISSUE THREAD

**Issue by Amanuel1D** [FreeCodeCamp/FreeCodeCamp#4902] opened 2015-12-02 06:39 UTC
Challenge [Waypoint: Target HTML Elements with Selectors Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.3; .NET4.0C; .NET4.0E)</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target

**Comment by ltegman** [comment] 2015-12-02 07:01
Closing as a duplicate of #4882. We have a PR in the works for this.

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 07:01 UTC
