### ISSUE TITLE
[beta] Copying solution copies the lines numbers in the code editor

### ISSUE THREAD

**Issue by marvellousdesign** [freeCodeCamp/freeCodeCamp#12873] opened 2017-01-26 08:46 UTC
#### Issue Description

I'm able to copy my solutions, but it also selects and copy the lines numbers too on the code editor for a challange.

#### Browser Information

* Browser Name, Version: Firefox 50.1.0
* Operating System: OSX 10.9.5
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 ​
2

var myStr = ""; // Change this line

3

​

4

​

5

```
#### Screenshot

![screen shot 2017-01-26 at 12 34 47 am](https://cloud.githubusercontent.com/assets/24817921/22324860/529e7b12-e360-11e6-93e9-347286c57be8.png)

**Comment by systimotic** [comment] 2017-01-26 10:14
Hi @marvellousdesign! Thank you for reporting this issue.

I can not reproduce this on the same version of Firefox on Windows 10. Now matter how hard I try (Ctrl+a, select the text, select the numbers), I can't select the numbers.
Can you consistently do this? Does it happen on all challenges? Does it also happen in other browsers?

**Comment by marvellousdesign** [comment] 2017-01-26 11:50
I updated my browser to Firefox 51.0 and I don't see this issue. Doesn't happen on Chrome. I've been using Freeter, it has a webpage wiget and it does happen there sometimes, not always.

**Comment by systimotic** [comment] 2017-01-26 13:10
That's really weird 😕 
@freeCodeCamp/moderators Can anybody reproduce?

**Comment by Greenheart** [comment] 2017-01-26 14:07
I can't reproduce with Firefox 50.1 (51 isn't published to the official Ubuntu repo yet).

To me it sounds like the issue is about the Freeter webpage widget. I wonder what browser it's based on - if we are lucky, some upstream fix might fix this issue.

**Comment by raisedadead** [comment] 2017-01-26 15:33
Cant reproduce on Chrome, Firefox on macOS. Closing. Please comment if issue still persists to reopen.

**Closed by raisedadead** 2017-01-26 15:33 UTC
Labels: beta
