### ISSUE TITLE
Submit and go to next challenge doesn't bring user to next challenge

### ISSUE THREAD

**Issue by null-interrupt** [freeCodeCamp/freeCodeCamp#12499] opened 2017-01-13 01:59 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery

#### Issue Description

The tests come out correct, the popup to submit and go to next challenge comes up, and when clicked it brings me back to the same challenge.

#### Browser Information

FireFox, 50.0.2
Arch Linux kernel 4.8.12-2-ARCH
Desktop
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

<script>
  $(document).ready(function() {
$("button").addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
 
 
```
#### Screenshot

![screenshot 32](https://cloud.githubusercontent.com/assets/25070702/21916037/ef3d05ee-d8fa-11e6-991b-ea79cdffd934.png)

**Comment by erictleung** [comment] 2017-01-13 23:03
@null-interrupt thanks for the issue. I'm unable to reproduce your issue, unfortunately. Other users have noted that disabling some browser plugins may help allow you pass the challenges.

**Comment by samsidx** [comment] 2017-01-15 11:06
Please have a look at this: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12376

**Comment by raisedadead** [comment] 2017-01-17 14:59
Closing, please comment with more details, after trying and disabling your browser add-ons, particularly Adblockers and LastPass, etc.

**Closed** 2017-01-18 06:02 UTC
