### ISSUE TITLE
Login with multiple users

### ISSUE THREAD

**Issue by michaelachrisco** [FreeCodeCamp/FreeCodeCamp#10840] opened 2016-09-22 02:34 UTC
#### Issue Description

If a user logs in and works some code camp challenges and logs out, then another user logs in, that other user can see the previous users code and must reset the exercise. 

#### Browser Information

Firefox

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 
Linux (Ubuntu 1604)

#### Screenshot

First user
![screenshot from 2016-09-21 19-22-12](https://cloud.githubusercontent.com/assets/398491/18735370/2d39eea6-8032-11e6-96f3-228d310a3b23.png)

Logoff
![screenshot from 2016-09-21 19-22-42](https://cloud.githubusercontent.com/assets/398491/18735372/32868e00-8032-11e6-8573-9cddd830ca3f.png)

Second user (did not complete the challenge) 
![screenshot from 2016-09-21 19-23-14](https://cloud.githubusercontent.com/assets/398491/18735376/39c292f4-8032-11e6-8488-5a72871a132f.png)

**Comment by Bouncey** [comment] 2016-09-22 09:43
Could this be managed with applying the user id into the localStorage key for the challenge?

**Comment by dhcodes** [comment] 2016-09-22 17:23
Closing as duplicate of #10413. Should be fixed by the new update per that thread.

**Closed by dhcodes** 2016-09-22 17:23 UTC
Labels: accounts, UX

**Comment by michaelachrisco** [comment] 2016-09-22 17:39
When can we expect this update to be live? Ill let our local group know as we are encountering this issue via Pair Programming sessions.

**Comment by dhcodes** [comment] 2016-09-22 18:51
@michaelachrisco I think they are shooting for the end of the month. As a stop-gap, if you have each person in the local group open a new Chrome incognito window before logging it, there shouldn't be any code in the editor.

**Comment by michaelachrisco** [comment] 2016-09-23 21:46
Thanks @dhcodes Will do!
