### ISSUE TITLE
Bug in "Target the Parent of an Element Using jQuery"

### ISSUE THREAD

**Issue by parthm17** [FreeCodeCamp/FreeCodeCamp#3006] opened 2015-09-02 23:14 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I solved the whole thing and the error is still there saying "Your left-well element should have a red background." when it is red already and the code is correct too, please check it!!

**Comment by bugron** [comment] 2015-09-03 03:38
Hi @parthm17, next time open an issue with a normal title. And provide more information on your issue.

**Comment by MarufSarker** [comment] 2015-09-03 11:42
As from your description and after checking the Waypoint, it seems everything is fine.

In the "challenge" it is asked to use "#target1" as jQuery selector and "parent()" as a function/method to select the parent element of the "target1" element, here "#left-well" it is.

There is also an example in the description provided, try to follow that, and then click the "Run Code" button or press "Ctrl + Enter" to see if it works or not.

**Comment by bugron** [comment] 2015-09-03 12:14
@MarufSarker is totally right and I think he can't pass the test due to improper use of **parent()** function. The problem is that many of our campers don't read instructions attentively. There are a lot of duplicate issues closed similar to this one so I'll close this too, but @parthm17 feel free to reopen it if you steel have a problem.

**Closed by bugron** 2015-09-03 12:14 UTC
