### ISSUE TITLE
"Create my GitHub Issue" goes to blank page or error page for only this challenge

### ISSUE THREAD

**Issue by ElisabetK** [freeCodeCamp/freeCodeCamp#12562] opened 2017-01-17 00:17 UTC
https://www.freecodecamp.com/challenges/make-images-mobile-responsive

#### Issue Description
When attempting to report a possible bug for this challenge, I get only a blank page in Edge (Windows 10), or a Unicorn (This page is taking way too long to load) error on Chrome (Windows 10).  This has happened at various times today, in both browsers. I have tried this with other challenges and have no issue reaching the bug report page.

Windows 10
Edge and Chrome
Laptop

https://github.com/freecodecamp/freecodecamp/issues/new?&body=Challenge%20%5BMake%20Images%20Mobile%20Responsive%5D(https%3A%2F%2Fwww.freecodecamp.com%2Fchallenges%2Fmake-images-mobile-responsive)%20has%20an%20issue.%0AUser%20Agent%20is%3A%20%3Ccode%3EMozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F55.0.2883.87%20Safari%2F537.36%3C%2Fcode%3E.%0APlease%20describe%20how%20to%20reproduce%20this%20issue%2C%20and%20include%20links%20to%20screenshots%20if%20possible.%0A%0AMy%20code%3A%0A%60%60%60html%0A%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%20%20%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%3C%2Fa%3E%0A%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%3Cform%20action%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A%0A%60%60%60%0A%0A

**Comment by no-stack-dub-sack** [comment] 2017-01-17 01:49
@ElisabetK Hmmm, I'm unable to reproduce this issue, but then, I'm not on a Windows machine. You are talking about the "Create my Github Issue" button within the "Bug" modal, correct?

The link you posted seems to work, and takes you to a blank issue page.

**Comment by raisedadead** [comment] 2017-01-17 05:27
@ElisabetK please provide some screenshots. Also please check that some browser add ons could be causing issue with page, for example we have had LastPass, AdBlocker etc. conflicting the challenge pages, in the past.

**Comment by raisedadead** [comment] 2017-01-20 12:03
Closing, please comment with more information.

**Closed by raisedadead** 2017-01-20 12:03 UTC
