### ISSUE TITLE
Expecting answers to be saved for reference

### ISSUE THREAD

**Issue by awakekat** [FreeCodeCamp/FreeCodeCamp#2934] opened 2015-08-31 18:36 UTC
All Challenges: Especially in the Javascript where I feel I am not learning anything and guessing at the answers. Why are the solutions not saved??!! I was hoping to have them saved so that I could go back and reference them now that I have to create the code for the harder challenges. Sorry but I am having a hard time with Javascript - it is probably why I have avoided it for 20 years!! No solutions saved, umm yeah not cool.

**Comment by awesomeaniruddh** [comment] 2015-08-31 22:15
Your bonfires are saved and can be accessed from your profile:

http://freecodecamp.com/awakekat

**Comment by BerkeleyTrue** [comment] 2015-09-01 05:47
Closing as duplicate of #2894 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-09-01 05:47 UTC
