### ISSUE TITLE
Code delivering correct results but tests aren't passing? 

### ISSUE THREAD

**Issue by Makzin** [FreeCodeCamp/FreeCodeCamp#11252] opened 2016-10-17 21:19 UTC
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase()%3B%20%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%20%20var%20wordArr%20%3D%20str.split('%20')%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20wordArr.length%3B%20i%2B%2B)%20%7B%20%0A%20%20%20%20%20%20%20%20var%20firstLetter%20%3D%20wordArr%5Bi%5D.slice(0%2C1)%3B%20%0A%20%20%20%20%20%20%20%20result%20%2B%3D%20firstLetter.toUpperCase()%20%2B%20wordArr%5Bi%5D.slice(1)%20%2B%20%22%20%22%3B%0A%20%20%20%20%7D%20%0A%20return%20result%3B%0A%7D%20%0A%0A%20%20%0A%20%20%0A%20%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  str = str.toLowerCase(); 
  var result = "";
    var wordArr = str.split(' ');
    for (var i = 0; i < wordArr.length; i++) { 
        var firstLetter = wordArr[i].slice(0,1); 
        result += firstLetter.toUpperCase() + wordArr[i].slice(1) + " ";
    } 
 return result;
} 

  
  
 
titleCase("I'm a little tea pot");

```

**Comment by Bouncey** [comment] 2016-10-17 23:00
That's weird...

Maybe the tests could do with being deep equal?

**Comment by RamiroPinol** [comment] 2016-10-17 23:48
It seems the problem is the last " " added to the sentence.
Your code returns "I'm a little tea pot ", should be "I'm a little tea pot"

**Comment by dhcodes** [comment] 2016-10-18 00:47
@RamiroPinol is correct. The results have an space at the end. Remedy that and your tests will pass. Closing as resolved.

**Closed by dhcodes** 2016-10-18 00:47 UTC
