### ISSUE TITLE
Waypoint: Construct JavaScript Objects with Functions does not run test

### ISSUE THREAD

**Issue by gcastro1970** [FreeCodeCamp/FreeCodeCamp#4217] opened 2015-11-06 19:54 UTC
I can place my code in and it reacts correctly but when I run the test nothing happens. It does not pass or fail, like I have not done anything. I have refreshed, reset the code, closed it out and reopened through the map, and shut down firefox and completely restarted. It still does not seem to be working.
![won trun](https://cloud.githubusercontent.com/assets/8890723/11007139/8f4458a8-848d-11e5-85e6-6a0e49930fa8.JPG)

**Comment by SaintPeter** [comment] 2015-11-06 19:58
Please copy and paste your code as text and/or use the "Bug" button.  I suspect a syntax error, but can't confirm because I can't copy and paste code from an image.

I was able to pass with:
```js
var MotorBike = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};
```

**Comment by gcastro1970** [comment] 2015-11-06 20:33
I have tried that, but the problem is not a matter of pass or fail. It does not appear to be testing the code.

**Comment by SaintPeter** [comment] 2015-11-07 03:00
Note that a syntax or logic error can cause the code to not run at all. Without your specific code I cannot reproduce your issue.  I was able to successfully complete the task in Chrome and Firefox.

Closing as unable to reproduce.  

Feel free to re-open when you can share your specific code.  Thanks and happy coding!

**Closed by SaintPeter** 2015-11-07 03:00 UTC

**Comment by gcastro1970** [comment] 2015-11-07 14:59
I posted a screen shot with my code. I am able to run it today and did notice a difference that may have something to do with this.
![willrun](https://cloud.githubusercontent.com/assets/8890723/11015708/d5466b8e-852d-11e5-8783-255a8f5da4a4.JPG)
