### ISSUE TITLE
waypoint: remove an element using jquery has an issue

### ISSUE THREAD

**Issue by patrickmac110** [FreeCodeCamp/FreeCodeCamp#2258] opened 2015-08-20 01:36 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. 
script tags appear as fccss
![screenshot 2015-08-19 at 9 34 39 pm](https://cloud.githubusercontent.com/assets/5874812/9373596/3f593e1e-46ba-11e5-8ca6-a2c0bd87beb3.png)

**Comment by benschenker** [comment] 2015-08-20 02:08
Thanks for posting an issue,

This is a duplicate of #2242 and others though in general try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by BerkeleyTrue** [comment] 2015-08-21 04:12
Closing as duplicate #2242

**Closed by BerkeleyTrue** 2015-08-21 04:12 UTC
