### ISSUE TITLE
Not detecting colour in code

### ISSUE THREAD

**Issue by Nuthi-Sriram** [freeCodeCamp/freeCodeCamp#35012] opened 2019-01-31 15:00 UTC
**Describe your problem and how to reproduce it:**
1.Attempt CSS challenge "Change the Color of Text"
2. ``<style>
    h2{color:blue;}
    </style>
``
3.Colour changes, but the test doesn't detect it

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-selectors-to-style-elements

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Ubuntu 18.10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/46497115/52062657-ec392180-2596-11e9-8429-10cf68c84173.png)

**Comment by rupali317** [comment] 2019-01-31 15:07
If you are talking about the console which shows the text "your test output will go here", then that is the expected behavior.

**Comment by raisedadead** [comment] 2019-01-31 17:07
The challenge does ask to create your style block at the top. However, I can imagine the instructions can be improved a bit to make it clear why the styles "cascade".

I am not sure if we do so already in a different challenge.

In any case, @Nuthi-Sriram did you happen to reach out to the [Forum](https://forum.freecodecamp.com) to get advice?

**Comment by aravindvnair99** [comment] 2019-02-04 04:57
> The challenge does ask to create your style block at the top. However, I can imagine the instructions can be improved a bit to make it clear why the styles "cascade".
> 
> I am not sure if we do so already in a different challenge.
> 
> In any case, @Nuthi-Sriram did you happen to reach out to the [Forum](https://forum.freecodecamp.com) to get advice?

@raisedadead I too was facing the same issue until last night. But looks like it's been fixed now.

**Comment by raisedadead** [comment] 2019-02-04 05:52
Going to close this. Please reachout to the support forum [Forum](https://forum.freecodecamp.com)

**Closed by raisedadead** 2019-02-04 05:52 UTC
Labels: status: blocked
