### ISSUE TITLE
Console output function case is incorrect

### ISSUE THREAD

**Issue by jdsandifer** [freeCodeCamp/freeCodeCamp#13769] opened 2017-03-06 02:40 UTC
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(num)%20%7B%0A%20%20return%20num%20*%205%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line
function timesFive(num) {
  return num * 5;
}


```

The code above passes the test, but the console output shows the function in lower case only: `timesfive(5) === 25` instead of `timesFive(5) === 25` like it should.

**Comment by systimotic** [comment] 2017-03-07 09:05
Hi @jdsandifer! Thank you for reporting this issue.

It appears that this issue is a duplicate of #9583. That issue was fixed recently. The changes are present in the beta, and will be released as soon as the beta is released. 👍 

I'm closing this as a duplicate.. Happy coding!

**Closed by systimotic** 2017-03-07 09:05 UTC
