### ISSUE TITLE
Google font

### ISSUE THREAD

**Issue by traanhn** [freeCodeCamp/freeCodeCamp#14093] opened 2017-03-25 22:49 UTC
Challenge [use-a-google-font](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<link href="https://fonts.googleapis.com/css?family=Open+Sans"
      rel="stylesheet">

<style>
  body {
    font-family:"Open Sans",sans-serif;
  }
  h4 {
    text-align: center;
    background-color: rgba(45, 45, 45, 0.1);
    padding: 10px;
    font-size: 27px;
    text-transform: uppercase;
  }
  p {
    text-align: justify;
  }
  .links {
    text-align: left;
    color: black;
    opacity: 0.7;
  }
  #thumbnail {
    box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
  .cardText {
    margin-bottom: 30px;
  }
</style>

<div class="fullCard" id="thumbnail">
  <div class="cardContent">
    <div class="cardText">
      <h4>Alphabet</h4>
      <hr>
      <em><p>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by traanhn** [comment] 2017-03-25 22:50
I cannot run this code in freecodeCamp.
Please help !

**Comment by hay-dee** [comment] 2017-03-26 03:14
@traanhn I copy-pasted your code and it seems to be working fine for me. Could you elaborate more about your problem? Is it not loading after clicking on Run Tests?

**Comment by erictleung** [comment] 2017-03-26 06:52
@traanhn thanks for the issue. Please elaborate and give us more details on how you ran this code and why you cannot run this code. Thanks!

**Comment by traanhn** [comment] 2017-03-26 09:32
Hi, I wrote the code above and hit the run test button but the message appear error so I dont know what happened with my code

**Comment by erictleung** [comment] 2017-03-27 01:42
@traanhn I see. Your code does pass for me. Does the error message appear after you finish the previous challenge or just when you just go to the challenge directly from the URL? Also, can you confirm which browser you're using?

**Comment by hay-dee** [comment] 2017-03-27 11:05
@erictleung I suspected it might've been a case of "correct code but failing the test", so i decided to check out the assert test. Had a little bit of trouble locating it as the challenge was recently removed/merged in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/13960). Nevertheless, from the files changed, we can see that the assert test was using the .css() jQuery method. Completing the challenge in mozilla firefox will thus cause testing errors as discussed [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/10749). I believe this issue will be resolved once the mentioned issue is resolved. 😄

**Comment by raisedadead** [comment] 2017-04-24 19:20
@hay-dee thanks. 
This means the fix is upstream in staging? And hasn't been deployed to the beta website, correct?

**Comment by hay-dee** [comment] 2017-04-26 11:48
@raisedadead I don't think that there has been a fix for the .css() jQuery method working in mozilla firefox yet, as issue #10749 is still open. However, I feel that this issue can be seen as a duplicate of #10749.

**Comment by raisedadead** [comment] 2017-04-26 13:53
Ah, cool.. that makes sense. Thanks.

**Closed by raisedadead** 2017-04-26 13:53 UTC
Labels: beta
