### ISSUE TITLE
Program Freezes. Get message that pages are unresponsive.

### ISSUE THREAD

**Issue by maryeb** [FreeCodeCamp/FreeCodeCamp#2237] opened 2015-08-19 21:49 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Every time I try to type my answer into this challenge I only get as far as typing  $($   before the program freezes and I get a pop-up saying the pages are unresponsive. I have tried rebooting, changing browsers, changing computers, but the problem has persisted for many hours.

**Comment by jbmartinez** [comment] 2015-08-21 21:30
Duplicate of #1960

**Closed** 2015-08-21 21:59 UTC
