### ISSUE TITLE
My code supposed to work, seems like a server Sass->CSS bug.

### ISSUE THREAD

**Issue by Zooll8** [freeCodeCamp/freeCodeCamp#14104] opened 2017-03-26 21:51 UTC
Challenge [store-data-with-sass-variables](http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
To reproduce issue just copy/paste included code into page with challenge and run it,
![image](https://cloud.githubusercontent.com/assets/23126351/24335536/17e7c5ca-124d-11e7-9ae1-4f5152eb6d23.png)

Same code in jsfiddle: 
![2017-03-26_17-56-20](https://cloud.githubusercontent.com/assets/23126351/24335578/fcc18dca-124d-11e7-9c29-72fc9a4980f1.png)

```html


<style>
  $text-color: red;
  
  .header{
    text-align: center;

  }
  .blog-post, h2{
    color: $text-color;
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>

```

edited: attached screenshot
edited-2: attached jsfiddle
edited-3: added "edited" part at the end

**Comment by HKuz** [comment] 2017-03-27 21:37
@Zooll8 - thanks for raising this issue. Unfortunately, the Beta site isn't compiling the Sass code for these challenges to work right - I believe a fix is in the works. I'm going to close this as a duplicate of #12699 , but feel free to join the discussion over in the comments there. 

Thanks for your QA help on the Beta site! 🎉

**Closed by HKuz** 2017-03-27 21:37 UTC
