### ISSUE TITLE
Random Quote Example Page is Dead

### ISSUE THREAD

**Issue by ogora** [freeCodeCamp/freeCodeCamp#14908] opened 2017-05-17 01:38 UTC
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.

I am trying to do the random quote project challenge but  the example project is dead and looks nothing like what is on the video. See attached screenshot
![codepen freecodecamp random quote machine](https://cloud.githubusercontent.com/assets/11918016/26135108/3d99c230-3a81-11e7-831e-0b18a7a7f2fb.png)
. I am not sure  if this the way it supposed to be or is there something wrong?

**Comment by S1ngS1ng** [comment] 2017-05-17 02:41
Same thing happens in freeCodeCamp.cn. [Here is our issue](https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/288)

We are actually using another link, which is http://codepen.io/freeCodeCamp/full/bELoPJ

I also noticed that the original project should be http://codepen.io/hezag/pen/ZGxOLX

Welp, here is something pretty weird.

- Even with the EXACT SAME url, one is working, the other one is not.

![2017-05-16_22-34-03 1](https://cloud.githubusercontent.com/assets/13592559/26136148/37749360-3a88-11e7-9926-a1d5c76d2a50.png)

- After logging in, still the SAME url. Though, it is not working anymore.

![2017-05-16_22-36-18](https://cloud.githubusercontent.com/assets/13592559/26136186/804ed118-3a88-11e7-9938-483f6a1c2242.png)

**Comment by raisedadead** [comment] 2017-05-17 04:37
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14875

**Closed by raisedadead** 2017-05-17 04:37 UTC
