### ISSUE TITLE
Not validating properly

### ISSUE THREAD

**Issue by jamc92** [FreeCodeCamp/FreeCodeCamp#3141] opened 2015-09-07 03:30 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-check-the-length-property-of-a-string-variable has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

lastNameLength is equal to eight but it doesn't take it within the length property but with the 8 value itself.
![screenshot-www freecodecamp com 2015-09-06 22-57-17](https://cloud.githubusercontent.com/assets/1733996/9708796/0df681f8-54eb-11e5-90fb-3778f354eeae.png)
![screenshot-www freecodecamp com 2015-09-06 22-59-01](https://cloud.githubusercontent.com/assets/1733996/9708798/13f0e918-54eb-11e5-8670-af91bf85b973.png)

**Comment by awesomeaniruddh** [comment] 2015-09-07 08:54
Uh, you are supposed to use this code:
```
lastNameLength = lastName.length;
```

This is not a bug, but an issue with your code. When having any issues regarding code not validating (when you are 100% confident that it is correct), please go to the FreeCodeCamp Help Chat first (link: https://gitter.im/FreeCodeCamp/Help). There are always friendly people hanging out there who will help you out with the issue. If they believe that the code should work too, then in that case you may report an issue (after reading the contribution guidelines: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

I believe that solves your issue. If it does, please close it :)

Thanks for cooperating.

**Comment by bugron** [comment] 2015-09-07 16:54
@jamc92 thanks for posting this issue!
Closing this issue because you need to fix your code. And @natac13 offered the solution. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-07 16:54 UTC

**Comment by dht0my** [comment] 2015-09-23 08:34
Hello

The challenge ask you to use .length function on a Variable. But in order to pass this waypoint you have to do something more that it is not asked of you. You have to set lastNameLength = 8; 
Can somebody explain me why? Thank you.
