### ISSUE TITLE
Passes even though it shouldn't

### ISSUE THREAD

**Issue by S-Lynne** [FreeCodeCamp/FreeCodeCamp#4204] opened 2015-11-06 05:52 UTC
Challenge [Bonfire: Truncate a string](http://www.freecodecamp.com/challenges/bonfire-truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20if%20(str.length%20%3C%3D%203)%20%7B%0A%20%20%20%20str%20%3D%20str.slice(0%2Cnum).concat(%22..%22)%3B%0A%20%20%7D%0A%20%20if%20(str.length%20%3E%20num)%20%7B%0A%20%20%20%20str%20%3D%20str.slice(0%2Cnum-3).concat(%22...%22)%3B%0A%20%20%7D%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20return%20str%3B%0A%7D%0A%0Atruncate(%22A-1%22%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  if (str.length <= 3) {
    str = str.slice(0,num).concat("..");
  }
  if (str.length > num) {
    str = str.slice(0,num-3).concat("...");
  }
  // Clear out that junk in your trunk
  return str;
}

truncate("A-1", 2);

```
Hi! This code passes when it shouldn't. The challenge asks for users to truncate if str.length is longer than num.length, but this configuration truncates str as long as it is shorter than 3 characters, regardless of the length of num. This could be resolved by making another test parameter truncate("A-", 2) which does not truncate.

**Comment by SaintPeter** [comment] 2015-11-06 17:29
Can you please show what you get and what you think you should get?

**Comment by S-Lynne** [comment] 2015-11-06 17:33
If truncate("A-",2) is tested, I should get "A-". Instead I get "A-..."

**Comment by SaintPeter** [comment] 2015-11-06 17:40
Duplicate of #4066

**Comment by ltegman** [comment] 2015-11-06 18:23
Closing as a duplicate.

**Closed by ltegman** 2015-11-06 18:23 UTC
