### ISSUE TITLE
Streak is displaying but not tallying properly

### ISSUE THREAD

**Issue by GillianTrethewey** [freeCodeCamp/freeCodeCamp#12654] opened 2017-01-20 14:58 UTC
#### Challenge Name
https://www.freecodecamp.com/gilliantrethewey

#### Issue Description
I have been consistently working on the challenges daily and making sure the squares turn dark green each day. The work is showing up properly, but the tally at the base is not correct; it is remaining at 17 days despite the streak lengthening daily, and it also is saying Current Streak is 1 day.

#### Browser Information
Using Chrome for Mac (Desktop).

#### Screenshot
![screen shot 2017-01-20 at 9 49 04 am](https://cloud.githubusercontent.com/assets/7611178/22153723/755eaee2-def6-11e6-8fc3-4e0faa3b9f00.png)

**Comment by raisedadead** [comment] 2017-01-20 15:07
Hi @GillianTrethewey yup, this is a known issue. 

Closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12589 and https://github.com/freeCodeCamp/freeCodeCamp/issues/7468

Please feel free to follow along, but rest assured, your data is not lost, it's still being saved correctly in the database.

**Closed by raisedadead** 2017-01-20 15:07 UTC
