### ISSUE TITLE
Typo: Double "add and" in the description.

### ISSUE THREAD

**Issue by sbarantatar** [FreeCodeCamp/FreeCodeCamp#2140] opened 2015-08-19 00:46 UTC
<img width="257" alt="screen shot 2015-08-18 at 9 44 53 pm" src="https://cloud.githubusercontent.com/assets/13680558/9346381/88f747b4-45f2-11e5-9da1-f8e3a0e62a62.png">
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by saadanerdetbare** [comment] 2015-08-19 00:52
duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1982

**Closed** 2015-08-26 00:10 UTC
