### ISSUE TITLE
"Clone an Element Using jQuery Function clone()" will work twice.

### ISSUE THREAD

**Issue by yccai** [FreeCodeCamp/FreeCodeCamp#10394] opened 2016-08-30 12:34 UTC
#### Challenge Name 

Clone an Element Using jQuery
https://www.freecodecamp.com/challenges/clone-an-element-using-jquery
#### Browser Information

* Browser Name, Version: 360 Safe Browser
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 <script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/12369807/18089169/241193ee-6ef1-11e6-859b-80acee52ef18.png)

**Comment by dhcodes** [comment] 2016-08-30 13:37
@yccai thanks for the issue. This is a duplicate of #5072 which will be fixed in the upcoming update when the site moves to React. You can see that it's already fixed on the [beta site](https://beta.freecodecamp.com/en/challenges/jquery/clone-an-element-using-jquery).

**Closed** 2016-08-30 14:45 UTC

**Comment by yccai** [comment] 2016-08-31 00:39
@dhcodes Thanks for your answer.
