### ISSUE TITLE
Incorrect Challenge Completion Calculation

### ISSUE THREAD

**Issue by M1ll3r** [freeCodeCamp/freeCodeCamp#40908] opened 2021-02-04 02:24 UTC
I found a minor discrepancy when going through one of the recent challenges. Specifically, it was at the conclusion of the "CSS Flexbox" challenge (within the "Responsive Web Design Certification"). The challenge incorrectly displays the amount completed. The challenge shows the completed amount as 65% (first image). However, I had actually fully completed the CSS Flexbox challenge (second image)

There were no issues with the site and nothing to prevent moving forward, this was just a cosmetic item. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/use-the-align-self-property 

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 88.0.4324.104 (Official Build) (64-bit)
* Operating System: 
![image (2)](https://user-images.githubusercontent.com/14935263/106835754-22617e00-6655-11eb-837d-b580fdcd1c71.png)
![image (1)](https://user-images.githubusercontent.com/14935263/106835757-22fa1480-6655-11eb-8013-c1de9c172de3.png)

Microsoft Windows 10 Pro

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Screenshots attached

Thanks,
Preston

**Comment by ShaunSHamilton** [comment] 2021-02-04 15:18
Thank you, for taking the time to open this.

Unfortunately, I am unable to reproduce this issue. Would you mind checking if you still come across this?

**Comment by M1ll3r** [comment] 2021-02-04 19:35
Hey Shaun. You are correct... it does not occur now. I had tested this
repeatedly just to be sure it was not something I was doing wrong. However,
I tested this today and it is no longer occurring. Not sure what to say...
:/

Thanks,
Preston

**Comment by M1ll3r** [comment] 2021-02-04 19:42
Shaun... something to note. Just for curiosity sake, I went back and chose
the prior challenge before the one in question (CSS Grid: Using Media
Queries). When I completed said challenge, it automatically calculates as
the entire CSS Grid challenge is 100% complete, even though there is one
additional challenge in the set. I am not sure if this is due to already
completing the entire challenge and moving on to the Responsive Web Design
Projects or something else.

Preston

**Comment by ShaunSHamilton** [comment] 2021-02-04 22:26
Hey Preston,

Thank you, for doing that. Glad to hear it is working for you again.

> When I completed said challenge, it automatically calculates as
the entire CSS Grid challenge is 100% complete, even though there is one
additional challenge in the set. I am not sure if this is due to already
completing the entire challenge and moving on to the Responsive Web Design
Projects

This is the designed and expected behaviour. So, no worries there.

I am going to close this issue. If you come across this again, feel free to reach out again, and we can reopen this, and dig more.

**Closed by ShaunSHamilton** 2021-02-04 22:26 UTC
Labels: scope: learn, status: needs help for triage, type: bug
