### ISSUE TITLE
is not going to the next lesson

### ISSUE THREAD

**Issue by johnpallis1990** [FreeCodeCamp/FreeCodeCamp#6833] opened 2016-02-08 20:22 UTC
Challenge [Use RGB to Color Elements White](http://www.freecodecamp.com/challenges/use-rgb-to-color-elements-white#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3Argb(255%2C%20255%2C%20255)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 OPR/35.0.2066.37</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color:rgb(255, 255, 255);
  }
</style>

```

**Comment by AkiraLaine** [comment] 2016-02-09 07:01
Hey @johnpallis1990! What browser/OS are you using? Can you confirm that it is still not going to the next challenge?

**Comment by sludge256** [comment] 2016-02-09 07:02
I think this was due to the site slowdown earlier today.

**Comment by QuincyLarson** [comment] 2016-02-10 04:50
@johnpallis1990 Thank you for submitting this. I agree, this is probably caused by our major server issues. I'm closing this issue.

**Closed by QuincyLarson** 2016-02-10 04:50 UTC
Labels: blocked
