### ISSUE TITLE
Oops! Something went wrong. Please try again later

### ISSUE THREAD

**Issue by mcpurser** [FreeCodeCamp/FreeCodeCamp#12106] opened 2016-12-19 01:03 UTC
#### Issue Description
I started FCC a few days ago, and have successfully done HTML & CSS both at my house, and at a friend's house. As I'm located in Utah, all of these places use Google Fiber.

I settled into a Starbucks today, to work. I keep getting the error message "Oops! Something went wrong. Please try again later" when I click on my map. 

A couple of times, I could click onto my next challenge and complete it. But, when I tried to continue onto the next challenge, it would take me back to the map page and say, "Oops! Something went wrong. Please try again later".  It would show (by making it lighter green) that I had completed the challenge. So, that part works. 

However, for the most part, I cannot click on the next challenge and start working. I just get the error, "Oops! Something went wrong. Please try again later" 

I have tried logging out and logging back in, and quitting Chrome to retry. 

#### Browser Information
Google Chrome on a Macbook in a Starbucks. (This Starbucks has Google Fiber, just like my house, and my friend's house). 

* Browser Name, Version: Google Chrome, Version 54.0.2840.98 (64-bit)
* Operating System: OS X El Capitan 10.11.6
* Mobile, Desktop, or Tablet: Macbook Pro 13-inch (early 2011)

#### Screenshot
![screen shot 2016-12-18 at 5 52 00 pm](https://cloud.githubusercontent.com/assets/11012244/21298215/de756c1a-c54a-11e6-8b0e-cf1b9e2d4d0e.png)

**Comment by QuincyLarson** [comment] 2016-12-19 05:13
@mcpurser thanks for reporting this. We're not sure what could be causing it, though I was able to replicate it myself. We're looking into this.

**Comment by QuincyLarson** [comment] 2016-12-19 05:54
@mcpurser I think we may have fixed this. Can you confirm whether you're still getting this?

**Comment by bottled-ant** [comment] 2016-12-19 15:04
I am having the same issue to for a few days to, just tryed to login and the issue is still unresolved "in my case at least"

**Comment by QuincyLarson** [comment] 2016-12-19 15:08
@bottled-ant are you sure that this is the same issue? Does it happen when you complete a challenge?

**Comment by bottled-ant** [comment] 2016-12-19 15:36
yes, and also it redirects me to map with the same message error, when i try to login or register a thing that i never could do issue (#12101)

**Comment by mcpurser** [comment] 2016-12-19 19:12
@QuincyLarson At least on my end, I am no longer having this issue. Thank you.

**Comment by mcpurser** [comment] 2016-12-19 19:13
@QuincyLarson .... @bottled-ant his issue sounds slightly different to mine. I never had trouble registering or logging in.

**Comment by QuincyLarson** [comment] 2016-12-19 19:19
OK - so to be clear, when you complete a challenge, you are getting an
"oops" error and being sent back to the map?

- Quincy Larson
teacher at FreeCodeCamp.com

Follow my writing about technology:
medium.com/@quincylarson
quora.com/profile/Quincy-Larson
<http://quora.com/profile/Quincy-Larson/answers?sort=views>

**Comment by texas2010** [comment] 2016-12-24 23:10
@mcpurser, do you still have an issue with this?

by the way, @QuincyLarson have a question for you. 
> OK - so to be clear, when you complete a challenge, you are getting an
"oops" error and being sent back to the map?

**Comment by QuincyLarson** [comment] 2016-12-25 01:07
@texas2010 it's been 5 days and @mcpurser hasn't responded. I'm going to go ahead and close this issue, as I think it is resolved.

**Closed by QuincyLarson** 2016-12-25 01:07 UTC

**Comment by vimniky** [comment] 2017-02-05 07:47
<img width="695" alt="screen shot 2017-02-05 at 3 42 44 pm" src="https://cloud.githubusercontent.com/assets/11426875/22624534/df548b9e-ebb9-11e6-95a4-a6dbdfd7c446.png">

Still  seeing this over and over again !
It's very frustrated .

**Comment by QuincyLarson** [comment] 2017-02-05 15:30
@vimniky could you email team at freecodecamp com - this sounds like an issue with your specific account, and I may be able to fix it for you manually.
