### ISSUE TITLE
Confirm The Ending. Do not use the built-in method .endsWith() to solve the challenge should not accept code below but it does.

### ISSUE THREAD

**Issue by mtyrio** [FreeCodeCamp/FreeCodeCamp#11703] opened 2016-11-18 09:46 UTC
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20if%20(str.endsWith(target))%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20return%20false%3B%0A%20%20return%20str%3B%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.endsWith(target)){
    return true;
  }
  else return false;
  return str;
}

confirmEnding("Bastian", "n");

```

**Comment by systimotic** [comment] 2016-11-18 09:57
Hi @mtyrio! Thank you for reporting this issue. 
That's a good find. This issue has been reported before in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10282, and has been fixed since. I confirmed that it is working as expected on the staging branch. That means that it's already resolved, but not yet on the live site.

I'm closing this issue as a duplicate of #10282
Happy coding!

**Closed by systimotic** 2016-11-18 09:57 UTC
Labels: duplicate
