### ISSUE TITLE
found empty white space while learning

### ISSUE THREAD

**Issue by jippy89** [freeCodeCamp/freeCodeCamp#36064] opened 2019-05-16 13:28 UTC
**Describe the bug**
I found a white space under the learning platform

**To Reproduce**
Go to this [curriculum](https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/jump-straight-to-the-content-using-the-main-element) then try to scroll down.

**Expected behavior**
No white-space(?)

**Screenshots**
![white-space-on-mozilla](https://user-images.githubusercontent.com/33748953/57857052-835d7880-7818-11e9-8878-65c67d986110.png)

**Desktop (please complete the following information):**
 - OS: 
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.4
Codename:	Illyria
```
 - Browser: Mozilla Firefox
 - Version 66.0.5 (64-bit)

**Additional context**
So far I only found the whitespace there, it's not on HTML, and other curicculum before it (haven't tested after). I have found issue #35279 but I don't know wheter it's been done or not. It has been merged on Feb 19 but the problem still exist.

**Comment by moT01** [comment] 2019-05-16 17:24
Not seeing it on high sierra 10.13.6 - same version of firefox. If you are using any browser extensions - you could try disabling them.

**Comment by jippy89** [comment] 2019-05-17 00:57
None of my browser extensions is active, you can see it's on top right, which is deactivated.

**Comment by jippy89** [comment] 2019-05-17 01:03
Ohhhh! The whitespace came out _**AFTER**_ I open mozilla dev tools! If I didn't open it, the whitespace won't come out.

**Comment by mattschlosser** [comment] 2019-05-17 13:40
A white space appears for me after the donation modal pops up.

**Comment by thecodingaviator** [comment] 2019-05-19 17:42
I believe the issue is non-existent then. I'm closing it. @jippy89 feel free to add further clarification and reopen it

**Closed by thecodingaviator** 2019-05-19 17:42 UTC
