### ISSUE TITLE
Cannot claim certificate with all projects complete

### ISSUE THREAD

**Issue by igorasilveira** [freeCodeCamp/freeCodeCamp#17627] opened 2018-06-19 01:54 UTC
#### Challenge Name

Claim APIs and Microservices Projects Certificate

#### Issue Description

I've completed all projects of the certification but I've been unable to claim the certificate. When I try to claim it a message says Looks like you have not completed the neccessary steps. Please return to the challenge map.
However, there is no indication on which challenge is missing.
Also, on this certificate I have complete all the challenges swell.

Any help would be appreciated.

Thank you,

Igor

#### Browser Information

Browser Name, Version: Safari and Chrome
Operating System: MacOS High Sierra 10.13
Mobile, Desktop, or Tablet: Desktop

#### Screenshot 1 - Profile Page

![captura de ecra 2018-06-19 as 02 51 09](https://user-images.githubusercontent.com/22747386/41571570-ba59fcb2-736b-11e8-9553-f6e9f92899c8.png)

#### Screenshot 2 - Curriculum Page

![captura de ecra 2018-06-19 as 02 51 29](https://user-images.githubusercontent.com/22747386/41571571-ba783470-736b-11e8-8566-9c747bd4a21a.png)

**Comment by Asjas** [comment] 2018-06-19 06:58
Hi @igorasilveira 

This issue is a duplicate of #17522. I would suggest closing this and typing a comment in issue #17522 so that the problem is contained in one issue and not spread out across multiple issues.

**Closed** 2018-06-19 10:57 UTC
