### ISSUE TITLE
the kitten picture challenges end at a pretty ugly end result: (would your boss accept this?)

### ISSUE THREAD

**Issue by RufusVS** [freeCodeCamp/freeCodeCamp#13660] opened 2017-02-28 22:24 UTC
#### Challenge Name
https://www.freecodecamp.com/challenges/line-up-form-elements-responsively-with-bootstrap
#### Issue Description
The final product of the kitten picture tasks is quite ugly (at least on firefox).   The "Loving" choice in personality section drops down a line instead of staying on the row.   And the button text on some buttons overflow or are too far to the right.
#### Browser Information
* Browser Name, Version: 
Firefox, 51.0.1 (64 bit)
* Operating System: 
MacOS
* Mobile, Desktop, or Tablet: 

#### Screenshot

![screen shot 2017-02-28 at 5 18 53 pm](https://cloud.githubusercontent.com/assets/6877082/23436954/54072028-fdda-11e6-8ead-3d8ea0a23351.png)

**Comment by erictleung** [comment] 2017-02-28 22:32
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/7842. Feel free to continue the conversation over there in case your concerns haven't been addressed yet. Happy coding!

**Closed by erictleung** 2017-02-28 22:32 UTC
