### ISSUE TITLE
localhost:3000 redirect gives error due to missing token

### ISSUE THREAD

**Issue by cmccormack** [freeCodeCamp/freeCodeCamp#34472] opened 2018-11-27 22:55 UTC
**Describe the bug**
When connecting to localhost:3000 to test the redirect to localhost:8000 an error is thrown in the Node console:
```js
{ Error: Access token is required for this request
// Stack trace }
2018-11-27T22:30:33.454Z 403 GET 19.815 ms - /internal/api/users/get-public-profile?username=404
```

**To Reproduce**
1. From root - `cd api-server/ && npm run babel-dev-server`
2. After db has loaded go to browser URL `localhost:3000`
3. Error will appear in Node console

**Expected behavior**
No error should appear and I assume redirect to `localhost:8000` should happen

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Chrome
 - Version 70.0.3538.110

**Additional context**
@Bouncey requested I share this error during troubleshooting of a different issue

**Comment by raisedadead** [comment] 2019-01-16 15:09
Closing. Can't reproduce any more.

**Closed by raisedadead** 2019-01-16 15:09 UTC
