### ISSUE TITLE
The lesson will not allow me to advance past this challenge. 

### ISSUE THREAD

**Issue by Jar36** [FreeCodeCamp/FreeCodeCamp#10644] opened 2016-09-09 23:33 UTC
Challenge [target-the-children-of-an-element-using-jquery](https://www.freecodecamp.com/en/challenges/jquery/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<script>
$(document).ready(function() {
  $("#target1").css("color", "red");
  $("#target1").prop("disabled", true);
  $("#target4").remove();
  $("#target2").appendTo("#right-well");
  $("#target5").clone().appendTo("#left-well");
  $("#target1").parent().css("background-color", "red");
  $("#right-well").children().css("color", "orange");
});
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
<h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row">
  <div class="col-xs-6">
    <h4>#left-well</h4>
    <div class="well" id="left-well">
      <button class="btn btn-default target" id="target1">#target1</button>
      <button class="btn btn-default target" id="target2">#target2</button>
      <button class="btn btn-default target" id="target3">#target3</button>
    </div>
  </div>
  <div class="col-xs-6">
    <h4>#right-well</h4>
    <div class="well" id="right-well">
      <button class="btn btn-default target" id="target4">#target4</button>
      <button class="btn btn-default target" id="target5">#target5</button>
      <button class="btn btn-default target" id="target6">#target6</button>
    </div>
  </div>
</div>
</div>

    ```

**Comment by dhcodes** [comment] 2016-09-10 02:20
Thanks for submitting! Closing as a duplicate of #10557

**Closed by dhcodes** 2016-09-10 02:20 UTC
