### ISSUE TITLE
Basic Javascript less than lessons buggy

### ISSUE THREAD

**Issue by just1witness** [freeCodeCamp/freeCodeCamp#15727] opened 2017-08-03 18:25 UTC
Criteria that is done correctly is not passing on a couple lessons in this area, please refer to screenshot. 

LESSON: Comparison with the less than operator.

![fccbug](https://user-images.githubusercontent.com/29514150/28937231-3991e392-7858-11e7-89c3-ded81ef94254.png)

**Comment by benogrencodes** [comment] 2017-08-03 19:58
Didn't take a look at the code too in-depth, but why are you using if twice? I haven't done FreeCodeCamp, but I'd use if for the first statement, then else if, then else.

That might be doing it.

**Comment by just1witness** [comment] 2017-08-03 22:03
These lessons are actually before the if, if else and else lessons. 

It says < still needs to used at least twice when it was used twice. It should be a pass, but it fails that criteria.

**Comment by erictleung** [comment] 2017-08-04 01:27
@just1witness thanks for the issue. I tried with the exact same code and challenge and had no issues.

**Challenge**:

https://www.freecodecamp.org/challenges/comparison-with-the-less-than-operator

**Code**:

```js
function testLessThan(val) {
  if (val < 25) {  // Change this line
    return "Under 25";
  }
  
  if (val < 55) {  // Change this line
    return "Under 55";
  }

  return "55 or Over";
}

// Change this value to test
testLessThan(10);
```

Can you give more information about the browser you're using, its version, and your operating system? That might help us diagnose the issue here. Thanks!

**Comment by just1witness** [comment] 2017-08-04 12:29
I am using firefox 54.0.1 64bit, and windows 10 operating system.

I think it's worth noting that the lesson allows you to advance even though it says you failed the criteria in question.

**Comment by erictleung** [comment] 2017-08-09 08:07
@just1witness thanks for the clarification. This might be a Firefox specific bug, but I can't verify this.

/cc @freeCodeCamp/moderators I'm unable to reproduce. If anyone has a Windows machine with Firefox, let us know if you can reproduce this error. Thanks!

**Comment by just1witness** [comment] 2017-08-09 12:50
I should also clarify that I added a screen shot of this lesson, but the lessen directly before this one does it too.

**Comment by AgmasGold** [comment] 2017-08-09 17:28
I am using firefox 54.01 **32-bit** on windows 10, and have no issues with this lesson.
![2017-08-09 18_27_47-](https://user-images.githubusercontent.com/30874283/29134984-8260af0e-7d30-11e7-9261-5b5e2723b3c1.png)

**Comment by joshhazelhurst123** [comment] 2017-08-17 10:32
I am using firefox 54.01 32 bit on windows 10, and I also did not have any issues with the lesson.

**Comment by QuincyLarson** [comment] 2017-08-18 22:19
@AgmasGold @joshhazelhurst123 Thanks for attempting to reproduce this issue. It sounds like this was a quirk that may only be affecting @just1witness. I am going to close this issue and we can reopen and investigate further if someone else encounters this.

**Closed by QuincyLarson** 2017-08-18 22:19 UTC
