### ISSUE TITLE
Text cursor points to wrong place

### ISSUE THREAD

**Issue by MikeYermolayev** [FreeCodeCamp/FreeCodeCamp#8735] opened 2016-05-20 19:57 UTC
#### Challenge Name
All challenges in which there is a lot of code
For example Warn your Users of a Dangerous Action

#### Issue Description
Sometime when I go to next challenge something strange occurs. I'm pointing to one place, but it seems that in fact cursor is on other line that I want. The everything become normal after I press something. 
Please look at video for more details.

#### Video
http://screencast.com/t/EdA4BFQBfEm0

#### Browser Information
* Browser Name, Version:  Google Chrome Canary 52.0.2743.0 (64-bit)
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

**Comment by ltegman** [comment] 2016-05-20 21:19
Closing as a duplicate of #8253. This is a known issue in CodeMirror.

**Closed by ltegman** 2016-05-20 21:19 UTC
