### ISSUE TITLE
Add Flex Superpowers to the Tweet Embed - Does not pass in Firefox

### ISSUE THREAD

**Issue by dan9d9** [freeCodeCamp/freeCodeCamp#37774] opened 2019-11-17 20:45 UTC
Challenge does not pass in Firefox. Console returns: 

> // running tests
> Your .follow-btn should have a display property set to flex.
> // tests completed

even though the follow-btn has display set to flex. Challenge with identical answers passes in Chrome.

https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 70.0.1
* Operating System: Windows 10 Pro

<img width="960" alt="2019-11-17 21_41_17-Learn CSS Flexbox_ Add Flex Superpowers to the Tweet Embed _ freeCodeCamp org" src="https://user-images.githubusercontent.com/52566135/69013663-11aae680-0983-11ea-8d14-5ceccb55eed9.png">

**Comment by RandellDawson** [comment] 2019-11-17 21:18
@dan9d9 Not able to reproduce the issue in Firefox.  Please post the entire code you used for this chalelnge and not a screenshot of a partial code section.

Thank you.

**Comment by dan9d9** [comment] 2019-11-18 09:08
Here's the code I'm inputting. It's the default code with only `display: flex` added in the spots it needs to be:

```
<style>
  body {
    font-family: Arial, sans-serif;
  }
  header {
    display: flex;
  }
  header .profile-thumbnail {
    width: 50px;
    height: 50px;
    border-radius: 4px;
  }
  header .profile-name {
    display: flex;
    margin-left: 10px;
  }
  header .follow-btn {
    display: flex;
    margin: 0 0 0 auto;
  }
  header .follow-btn button {
    border: 0;
    border-radius: 3px;
    padding: 5px;
  }
  header h3, header h4 {
    display: flex;
    margin: 0;
  }
  #inner p {
    margin-bottom: 10px;
    font-size: 20px;
  }
  #inner hr {
    margin: 20px 0;
    border-style: solid;
    opacity: 0.1;
  }
  footer {
    display: flex;
  }
  footer .stats {
    display: flex;
    font-size: 15px;
  }
  footer .stats strong {
    font-size: 18px;
  }
  footer .stats .likes {
    margin-left: 10px;
  }
  footer .cta {
    margin-left: auto;
  }
  footer .cta button {
    border: 0;
    background: transparent;
  }
</style>
<header>
  <img src="https://freecodecamp.s3.amazonaws.com/quincy-twitter-photo.jpg" alt="Quincy Larson's profile picture" class="profile-thumbnail">
  <div class="profile-name">
    <h3>Quincy Larson</h3>
    <h4>@ossia</h4>
  </div>
  <div class="follow-btn">
    <button>Follow</button>
  </div>
</header>
<div id="inner">
  <p>I meet so many people who are in search of that one trick that will help them work smart. Even if you work smart, you still have to work hard.</p>
  <span class="date">1:32 PM - 12 Jan 2018</span>
  <hr>
</div>
<footer>
  <div class="stats">
    <div class="Retweets">
      <strong>107</strong> Retweets
    </div>
    <div class="likes">
      <strong>431</strong> Likes
    </div>
  </div>
  <div class="cta">
    <button class="share-btn">Share</button>
    <button class="retweet-btn">Retweet</button>
    <button class="like-btn">Like</button>
  </div>
</footer>
```

Furthermore, here's the forum post that brought this to my attention: https://www.freecodecamp.org/forum/t/put-the-display-flex-in-the-right-place/326649

And the code that this user is inputting. The only difference here is that this user has added `display: flex` to the `.follow-btn button' element as well as the `.follow-btn` element, but in my testing this code still passes in Chrome, but not in Firefox.

```
<style>
 body {
   font-family: Arial, sans-serif;
 }
 header {
display:flex;
 }
 header .profile-thumbnail {
   width: 50px;
   height: 50px;
   border-radius: 4px;
 }
 header .profile-name {

   margin-left: 10px;
   display: flex;
 }
 header .follow-btn {

   margin: 0 0 0 auto;
   display: flex;
 }
.follow-btn button {
 display:flex;
   border: 0;
   border-radius: 3px;
   padding: 5px;
   
 }
 header h3, header h4 {
display: flex;
   margin: 0;
 }
 #inner p {
   margin-bottom: 10px;
   font-size: 20px;
 }
 #inner hr {
   margin: 20px 0;
   border-style: solid;
   opacity: 0.1;
 }
 footer {
display: flex;
 }
 footer .stats {
display: flex;
   font-size: 15px;
 }
 footer .stats strong {
   font-size: 18px;
 }
 footer .stats .likes {
   margin-left: 10px;
 }
 footer .cta {
   margin-left: auto;
 }
 footer .cta button {
   border: 0;
   background: transparent;
 }
</style>
<header>
 <img src="https://freecodecamp.s3.amazonaws.com/quincy-twitter-photo.jpg" alt="Quincy Larson's profile picture" class="profile-thumbnail">
 <div class="profile-name">
   <h3>Quincy Larson</h3>
   <h4>@ossia</h4>
 </div>
 <div class="follow-btn">
   <button>Follow</button>
 </div>
</header>
<div id="inner">
 <p>I meet so many people who are in search of that one trick that will help them work smart. Even if you work smart, you still have to work hard.</p>
 <span class="date">1:32 PM - 12 Jan 2018</span>
 <hr>
</div>
<footer>
 <div class="stats">
   <div class="Retweets">
     <strong>107</strong> Retweets
   </div>
   <div class="likes">
     <strong>431</strong> Likes
   </div>
 </div>
 <div class="cta">
   <button class="share-btn">Share</button>
   <button class="retweet-btn">Retweet</button>
   <button class="like-btn">Like</button>
 </div>
</footer>
```

**Comment by ojeytonwilliams** [comment] 2019-11-18 09:42
Both solutions work for me, so it's possibly a conflict with a browser extension.  @dan9d9 could you try running the tests with them all off?  Using incognito mode might be enough, depending on how they're configured.

**Comment by dan9d9** [comment] 2019-11-18 09:55
@ojeytonwilliams 
You're right. It's uBlock Origin that's causing the conflict. Turning it off allows the challenge to pass, but having it on results in the 
`// running tests
Your .follow-btn should have a display property set to flex.
// tests completed`
error being displayed.

**Comment by ojeytonwilliams** [comment] 2019-11-18 10:18
@dan9d9 Thanks for investigating that!

@RandellDawson these kinds of problems seem to occur mostly in the css sections.  Do you think it would be worth putting warnings about browser extensions in the first challenges of those sections?

**Comment by moT01** [comment] 2019-12-16 15:13
Some sort of warning for that is probably a good idea, since extension issues have come up more than a few times. Not sure where, the intro is probably best but there's a plan to rework those.

**Comment by ojeytonwilliams** [comment] 2019-12-16 17:31
If they're removed, I'd say the first challenge of the section is the best place.

**Comment by moT01** [comment] 2020-03-11 02:24
Closing in favor of that new issue specific for adding a warning.

**Closed by moT01** 2020-03-11 02:24 UTC
Labels: scope: curriculum, status: needs investigation

**Comment by avishek2004** [comment] 2021-05-22 01:50
use this code to solve the problem....thanks





<style>


  body {
    font-family: Arial, sans-serif;
  }
  header {
    display: flex;
flex-direction: row;
  }
  header .profile-thumbnail {
    width: 50px;
    height: 50px;
    border-radius: 4px;
  }
  header .profile-name {
    display: flex;
    margin-left: 10px;
  }
  header .follow-btn {
    display: flex;
    margin: 0 0 0 auto;
  }
  header .follow-btn button {
    border: 0;
    border-radius: 3px;
    padding: 5px;
  }
  header h3, header h4 {
    display: flex;
    margin: 0;
  }
  #inner p {
    margin-bottom: 10px;
    font-size: 20px;
  }
  #inner hr {
    margin: 20px 0;
    border-style: solid;
    opacity: 0.1;
  }
  footer {
    display: flex;
flex-direction: row;
  }
  footer .stats {
    display: flex;
    font-size: 15px;
  }
  footer .stats strong {
    font-size: 18px;
  }
  footer .stats .likes {
    margin-left: 10px;
  }
  footer .cta {
    margin-left: auto;
  }
  footer .cta button {
    border: 0;
    background: transparent;
  }
</style>
<header>
  <img src="https://freecodecamp.s3.amazonaws.com/quincy-twitter-photo.jpg" alt="Quincy Larson's profile picture" class="profile-thumbnail">
  <div class="profile-name">
    <h3>Quincy Larson</h3>
    <h4>@ossia</h4>
  </div>
  <div class="follow-btn">
    <button>Follow</button>
  </div>
</header>
<div id="inner">
  <p>I meet so many people who are in search of that one trick that will help them work smart. Even if you work smart, you still have to work hard.</p>
  <span class="date">1:32 PM - 12 Jan 2018</span>
  <hr>
</div>
<footer>
  <div class="stats">
    <div class="Retweets">
      <strong>107</strong> Retweets
    </div>
    <div class="likes">
      <strong>431</strong> Likes
    </div>
  </div>
  <div class="cta">
    <button class="share-btn">Share</button>
    <button class="retweet-btn">Retweet</button>
    <button class="like-btn">Like</button>
  </div>
</footer>

**Comment by avishek2004** [comment] 2021-05-22 01:51
`<style>
  body {
    font-family: Arial, sans-serif;
  }
  header {
    display: flex;
flex-direction: row;
  }
  header .profile-thumbnail {
    width: 50px;
    height: 50px;
    border-radius: 4px;
  }
  header .profile-name {
    display: flex;
    margin-left: 10px;
  }
  header .follow-btn {
    display: flex;
    margin: 0 0 0 auto;
  }
  header .follow-btn button {
    border: 0;
    border-radius: 3px;
    padding: 5px;
  }
  header h3, header h4 {
    display: flex;
    margin: 0;
  }
  #inner p {
    margin-bottom: 10px;
    font-size: 20px;
  }
  #inner hr {
    margin: 20px 0;
    border-style: solid;
    opacity: 0.1;
  }
  footer {
    display: flex;
flex-direction: row;
  }
  footer .stats {
    display: flex;
    font-size: 15px;
  }
  footer .stats strong {
    font-size: 18px;
  }
  footer .stats .likes {
    margin-left: 10px;
  }
  footer .cta {
    margin-left: auto;
  }
  footer .cta button {
    border: 0;
    background: transparent;
  }
</style>
<header>
  <img src="https://freecodecamp.s3.amazonaws.com/quincy-twitter-photo.jpg" alt="Quincy Larson's profile picture" class="profile-thumbnail">
  <div class="profile-name">
    <h3>Quincy Larson</h3>
    <h4>@ossia</h4>
  </div>
  <div class="follow-btn">
    <button>Follow</button>
  </div>
</header>
<div id="inner">
  <p>I meet so many people who are in search of that one trick that will help them work smart. Even if you work smart, you still have to work hard.</p>
  <span class="date">1:32 PM - 12 Jan 2018</span>
  <hr>
</div>
<footer>
  <div class="stats">
    <div class="Retweets">
      <strong>107</strong> Retweets
    </div>
    <div class="likes">
      <strong>431</strong> Likes
    </div>
  </div>
  <div class="cta">
    <button class="share-btn">Share</button>
    <button class="retweet-btn">Retweet</button>
    <button class="like-btn">Like</button>
  </div>
</footer>`
