### ISSUE TITLE
Broken Streak

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5842] opened 2016-01-04 06:31 UTC
My "current streak" seems to be broken and gives me a value of 0 when it should be 21

![image](https://cloud.githubusercontent.com/assets/11958359/12084538/edffef20-b308-11e5-8d5a-f7a695e7b8fd.png)

**Comment by sludge256** [comment] 2016-01-04 06:55
This seems to occur when the next day rolls around for the server and I believe it gets "fixed" later in the day.

**Comment by BerkeleyTrue** [comment] 2016-01-05 01:36
Closing as duplicate of #5799

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2016-01-05 01:36 UTC
