### ISSUE TITLE
File Metadata Microservice Instruction Inconsitencies

### ISSUE THREAD

**Issue by bobmatyas** [freeCodeCamp/freeCodeCamp#37553] opened 2019-10-26 01:35 UTC
The File Metadata Microservice project as part of the APIs and Microservices projects has inconsistent instructions.

On the freeCodeCamp project URL:

https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice

There are two user stories:

- I can submit a FormData object that includes a file upload.
- When I submit something, I will receive the file size in bytes within the JSON response.

However, on the Glitch project it says:

- I will receive the file name, and size in bytes within the JSON response.

When you try the sample Glitch project, it actually returns a JSON response with the name, file type, and size. 

I'd be happy to do a PR to fix this, but I wasn't sure how to best address these inconsistencies.

**Comment by erictleung** [comment] 2020-05-09 06:18
Thanks for bringing up this issue.

@freeCodeCamp/moderators I have not completed this myself, but based on the example Glitch and the boiler plate repository, I say we should update the `/learn` site to be consistent with the rest.

In other words, we should update the user story in `/learn` with

```diff
- When I submit something, I will receive the file size in bytes within the JSON response.
+ When I submit something, I will receive the file name, and size in bytes within the JSON response.
```

If there are any concerns, feel free to comment.

**Comment by Sky020** [comment] 2020-05-09 09:23
@erictleung , there are many inconsistancies between the latter projects and lessons, and the tests. I suggest we open a new issue thread as a _todo_, and compile all of the miss-alignments.

Specifically, I struggled to go through the Advanced Node and Express lessons, because of poorly done tests, and the versions not being kept up to date.

**Comment by erictleung** [comment] 2020-05-09 21:23
@Sky020 thanks for chiming in. I haven't gone through them yet so I can't be sure. I can close this issue and open a new issue for tracking inconsistencies with the five projects in "APIs and Microservices Projects".

Are there any other project groups that have inconsistencies we should focus on?

**Comment by Sky020** [comment] 2020-05-09 21:44
>Are there any other project groups that have inconsistencies we should focus on?

Other than, the _Information Security and Quality Assurance_ projects not having tests at all, no.

The issue is more-so in the lessons. Over half of _Advanced Node and Express_ do not pass without looking at the tests.

**Closed** 2020-09-11 23:03 UTC
Labels: scope: learn, status: discussing
