### ISSUE TITLE
Iterate over Arrays with map - can't pass the Waypoint

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#3543] opened 2015-09-30 06:48 UTC
Challenge [Waypoint: Iterate over Arrays with map](http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Use map to add three to each value in the array
var array = [1,2,3,4,5];
// Only change code below this line.
array = array.map(function(val){
  return val + 3;
})
// Only change code above this line.
(function() {return array;})();
```

This is what I get:
![image](https://cloud.githubusercontent.com/assets/11958359/10186266/349bb73e-679b-11e5-9587-52bb0d33cbcb.png)

**Comment by Mansuro** [comment] 2015-09-30 07:28
I can't reproduce the error. Otherwise, for the second case, you are asked to `Use the map function to add 3 to every value in the variable array`

**Comment by AkiraLaine** [comment] 2015-09-30 07:59
@Mansuro My bad! I modified the issue :D

**Comment by avastu** [comment] 2015-09-30 08:00
Also, you're missing a semicolon after the closing parenthesis of your ```arr = arr.map(...``` function.

**Comment by bugron** [comment] 2015-10-06 19:23
Closing this issue as @Mansuro and @avastu are correct. Thanks for posting.

**Closed by bugron** 2015-10-06 19:23 UTC

**Comment by auranga** [comment] 2016-03-04 02:37
//Use map to add three to each value in the array
var oldArray = [1,2,3,4,5];
console.log(array);
// Only change code below this line.
var newArray = oldArray.map(function(num){
  return num + 3;
});



// Only change code above this line.
(function() {return(newArray);})();

**Comment by Navankur94** [comment] 2016-05-14 18:01
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(val) {
 return val+3;
});
var newArray=(function() 
{
  return(newArray);
})();

**Comment by albertRubtsov** [comment] 2016-05-21 14:42
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(val){return val +=3;});

**Comment by omega-lova** [comment] 2016-06-23 20:54
@albertRubtsov thank you, yours being the most concise. One question about the return line, it makes sense to use += but how come the example demonstrated `return val *4;`

instead of `return val *= 4;` ?

**Comment by arun1595** [comment] 2016-06-23 22:21
This is not the place for discussing solutions for challenges. Please discuss in the [Help Chatroom](https://gitter.im/FreeCodeCamp/Help)

**Comment by kolbasavert** [comment] 2016-09-25 08:58
var oldArray = [1,2,3,4,5];

// Only change code below this line.
var newArray = oldArray.map(function(val){
  return val += 3 ;
});

**Comment by texas2010** [comment] 2016-09-25 17:47
@kolbasavert 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
