### ISSUE TITLE
Another Pass even if it's not correct

### ISSUE THREAD

**Issue by BatairAlai** [FreeCodeCamp/FreeCodeCamp#3821] opened 2015-10-20 22:42 UTC
I know how to finish the challenge correctly but this is what was showing up when I was messing around trying to make multiple radio buttons with less code.
![fccbug](https://cloud.githubusercontent.com/assets/4963608/10623146/32400b24-7741-11e5-964c-ce4e3ec7b428.PNG)

````
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
<label>
  <input type="radio" name="indoor-outdoor">
        Indoor Outdoor
</label>
````

**Comment by ltegman** [comment] 2015-10-21 06:35
This is the exact code that passed for you? I am unable to pass the challenge with this code myself.

**Comment by BatairAlai** [comment] 2015-10-23 19:32
Sorry for the late response. Yes, it is what worked. If it helps, I'm on FireFox 41.0.2. I messed with the indentation for the line that Indoor Outdoor was on and it would work once, and then say it doesn't accept the answer until I messed with the spacing a little.

**Comment by ltegman** [comment] 2015-11-11 21:56
Unfortunately I can't for the life of my reproduce this and the way the test cases are written it should never be possible to pass the tests with that code. If you see more issues like this I would suggest switching to Chrome since that is the only browser officially supported by FCC.

Closing as unable to repro.

Thanks and happy coding!

**Closed by ltegman** 2015-11-11 21:56 UTC

**Comment by BatairAlai** [comment] 2015-11-12 03:42
Alright no problem! I actually have switched back to Chrome. Firefox was
crashing too many times for me.
