### ISSUE TITLE
"Stealing" solutions from others.

### ISSUE THREAD

**Issue by LuckyWasTaken** [FreeCodeCamp/FreeCodeCamp#8369] opened 2016-04-30 20:32 UTC
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.

You can "steal" anyone's algorithm code by going to random user's page, opening their solution and pressing "Run tests" button.
Video related: https://www.youtube.com/watch?v=Myrzcr2fWiE
(I'm so sorry I did that "No repeats please" challenge this way for video. Please, mark this as undone so i can do it by myself. I've discovered this bug on "Exact Change" problem, so my code there is also overwritten.)

**Comment by raisedadead** [comment] 2016-04-30 21:45
I think this is the way it is going to work, yes a camper can accidentally as well as intentionally "steal" code from others pages, but that's by design.

Now its really up to a camper to choose to follow the academic honesty policy or not, remember that to get past and get those actual certifications you have to complete the challenges such as algorithms and projects (CodePens which mostly cannot be copied just bluntly without anyone noticing it).

So, if campers do just copy the solution they would simply lose the learning, and gain nothing out of it, the whole point of being on Free Code Camp is to learn.

This has already been discussed a couple of times on #7600 and #7603 

At the same time, we cannot simply remove the option of visiting anyone else's solutions, because that the way the portfolio works.

Coming to your query:
> (I'm so sorry I did that "No repeats please" challenge this way for video. Please, mark this as undone so i can do it by myself. I've discovered this bug on "Exact Change" problem, so my code there is also overwritten.)

You simply, do your own solution and submit it again, if its correct its going to be update to your profile, we always store the latest submission to the challenges on your profile, so the only way this gets undone, is by you submitting with your solution.

Closing, as nothing more can be done on FCC's side.

Thanks and Happy coding!

**Closed by raisedadead** 2016-04-30 21:45 UTC
Labels: confirmed

**Comment by diomed** [comment] 2016-06-19 17:19
this is the worst loophole ever. it's like a complete cheetsheat.
Isn't there a way with user permissions that you could limit displaying solutions to ordinary members,
and allow them to people who need to check up the code???
There should be, because this is simply ridiculous.

**Comment by erictleung** [comment] 2016-06-19 17:22
@diomed refer back to @raisedadead's comment above.

**Comment by diomed** [comment] 2016-06-19 18:19
I've read that comment and I'm suggesting user permissions, coz this is not right.

**Comment by heldersepu** [comment] 2016-06-27 02:15
I noticed that under the [setting](https://www.freecodecamp.com/settings) there is an option:
Privacy Settings
Make all of my solutions private
(this disables your certificates)

**Comment by raisedadead** [comment] 2016-06-27 05:07
@diomed yeah, you can hide your solutions with the "Make all of my solutions" private, as @heldersepu pointed. 

Hope that helps, but the point remains the same, if people copy paste just to clear the challenges, its not going to help 'em in the certifications, where individual projects will be evaluated.

**Comment by heldersepu** [comment] 2016-06-27 12:48
Maybe by default that setting should be enabled ?!?

And yes @raisedadead you are right, we can not "fix" cheaters...
Sooner or latter that comes back and bites them in the rear (it could be in the certifications or worst case during a job interview)

**Comment by raisedadead** [comment] 2016-06-27 13:12
@heldersepu we have left the default the other way round, because after you hit the halfway club and you get an opportunity to pair with another camper and work on real projects for non-profit. There in it's a mandate that campers' profiles are evaluated. 

They can't be unless the profile was private, and I am afraid that we may not be planning to change this. So the current option is to make your profile private should you choose to.

**Comment by heldersepu** [comment] 2016-06-27 14:46
@raisedadead if that is the only reason, it looks like you guys killed the fly with a sledgehammer. 

I will default it to enabled, when the time comes (hit halfway club) for the campers' profiles to be evaluated, reach out to the camper to change the setting, and once evaluation is complete change it back.

**Comment by raisedadead** [comment] 2016-06-27 14:52
I have no idea what to say.

**Comment by heldersepu** [comment] 2016-06-27 15:16
Do you guys have any system where you can put something like this to a vote?

It's just way too easy to copy someone's else code:
https://www.freecodecamp.com/LuckyWasTaken

**Comment by raisedadead** [comment] 2016-06-27 16:45
We do have a system where we can flag such users, warn them and subsequently ban them, which means they will not get the certifications and wont be able to participate in the projects.

Their profiles can reported privately to the email team@freecodecamp.com or reported in the Chat room, we prefer the former, or you could ping any of the org members on Gitter as well.

And to vote for this I am guessing we can re-open this issue and take a vote?
