### ISSUE TITLE
Feature request: independent scroll bar for the code mirror window

### ISSUE THREAD

**Issue by vohsalab** [FreeCodeCamp/freecodecamp#957] opened 2015-06-17 14:32 UTC
This is feature request, really. 
I suggest to implement independent scroll bar for the code mirror window. It's gonna be much easier to scroll down to the 100th line of code and still see what you should implement and additional information on it

**Comment by LumenTeun** [comment] 2015-06-17 15:41
This is a duplicate of #716.

**Comment by BerkeleyTrue** [comment] 2015-06-17 17:41
@LumenTeun Thanks!

**Closed by BerkeleyTrue** 2015-06-17 17:41 UTC
