### ISSUE TITLE
Fix Create a JavaScript Slot Machine 

### ISSUE THREAD

**Issue by dconner09** [FreeCodeCamp/FreeCodeCamp#10598] opened 2016-09-09 16:09 UTC
Help me with this Issue this code is not passing

   slotOne = Math.floor(Math.random() * (3-1+1))+1;
   slotTwo = Math.floor(Math.random() * (3-1+1))+1;
   slotThree = Math.floor(Math.random() * (3-1+1))+1;

#### Challenge Name

assert((function(){if(editor.match(/Math\.floor\(\s*Math\.random\(\)\s*\*\s*\(\s*3\s*\-\s*1\s*\+\s*1\s*\)\s*\)\s*\+\s*1/gi) !== null){return editor.match(/slot.*?=.*?\(.*?\).*?/gi).length >= 3;}else{return false;}})(), 'You should have used Math.floor(Math.random() * (3 - 1 + 1)) + 1; three times to generate your random numbers.')

#### Issue Description
All checks pass but the fourth one and I used the code three times.

#### Browser Information
HP Desktop using google chrome
#### Your Code

   slotOne = Math.floor(Math.random() * (3-1+1))+1;
   slotTwo = Math.floor(Math.random() * (3-1+1))+1;
   slotThree = Math.floor(Math.random() * (3-1+1))+1;

**Comment by dhcodes** [comment] 2016-09-09 16:15
Thanks for the issue, but it is a duplicate of #10578

**Closed by dhcodes** 2016-09-09 16:15 UTC
Labels: question

**Comment by dconner09** [comment] 2016-09-09 16:17
so this is a bug right

**Comment by dhcodes** [comment] 2016-09-09 16:32
@dconner09 yes, you can check issue #10578 for updates regarding it being fixed.
