### ISSUE TITLE
#target5 button is cloned and appended two times after "Run tests" in result (mobile phone view)

### ISSUE THREAD

**Issue by arnosha** [FreeCodeCamp/FreeCodeCamp#12058] opened 2016-12-15 16:39 UTC
Challenge [Clone an Element Using jQuery](https://www.freecodecamp.com/challenges/clone-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

![monosnap 2016-12-15 19-34-10](https://cloud.githubusercontent.com/assets/24529297/21232765/df6b7f00-c2fd-11e6-8fb9-12050f6c50a1.png)
 As you can see on the screenshot there are two instances of #target5 button in the result. I believe it's incorrect. Issue is also affecting at least next challenge - https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery this one

**Comment by raisedadead** [comment] 2016-12-15 17:31
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072

Thanks for reporting @arnosha 
This a very old and known issue, we have fixed it in the react version of the website, which will be released again soon.

Until then please ignore this issue and continue.

Happy Coding!

**Closed by raisedadead** 2016-12-15 17:31 UTC

**Comment by arnosha** [comment] 2016-12-15 17:41
Thanks, I wasn't able to find #5072 because I didn't look at closed ones.

**Comment by raisedadead** [comment] 2016-12-15 17:44
@arnosha sure thing, no problem. It's quite an old one, lol took me a while to find out as well. 😅

**Comment by areshz** [comment] 2017-03-06 04:49
Amazing! Was about to report the same :)
