### ISSUE TITLE
Friendly Date ranges: test cases not displaying

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#7726] opened 2016-03-25 03:50 UTC
#### Issue Description

 When submitting answer for Friendly Date Range test cases do not display completely. They are cut off by the window. See attached.
![selection_017](https://cloud.githubusercontent.com/assets/12101566/14037499/dba2c374-f201-11e5-9795-3ecb5f2c96eb.png)
#### Browser Information

FireFox (latest version) Ubuntu 14.04
#### Code

not relevant. Can be reproduced by submitting the starter code.

**Comment by raisedadead** [comment] 2016-03-25 07:31
Thanks for the issue @jstoebel 
Can you tell us your screen size (resolution) as well? May be relevant for anyone looking into this.

/cc @hallaathrad

**Comment by jstoebel** [comment] 2016-03-25 11:32
1366 X 768

**Comment by erictleung** [comment] 2016-05-14 17:37
Somewhat related to #8390. As I suggested with the Pig Latin challenge, a quick fix would be to change the function name.

Also, is this still a problem? Or is it maybe browser specific? I wasn't able to reproduce this now with Chrome and Safari on a Mac.

**Comment by raisedadead** [comment] 2016-05-14 17:56
Can't reproduce on Chrome, Firefox, and Edge on Windows 10 either.
Has to be Firefox and Ubuntu as per Original Post.

**Comment by darwinrc** [comment] 2016-05-14 23:52
I could reproduce it using Ubuntu 16.04 with a 1360 x 768 resolution. With 1920x1080 the dates are fully rendered.
![selection_007](https://cloud.githubusercontent.com/assets/1463967/15271246/fa4a62b6-1a04-11e6-8ecc-cdf9a149edc9.jpg)
![selection_008](https://cloud.githubusercontent.com/assets/1463967/15271248/00607faa-1a05-11e6-9d19-5df427c44313.jpg)

**Comment by QuincyLarson** [comment] 2017-01-04 03:17
We've removed this challenge completely so I'm closing this issue.

**Closed by QuincyLarson** 2017-01-04 03:17 UTC
Labels: discussing, firefox, UX
