### ISSUE TITLE
It says that heads dose not equal dose not return  0 if flip = 0

### ISSUE THREAD

**Issue by professor95** [FreeCodeCamp/FreeCodeCamp#5396] opened 2015-12-21 00:27 UTC
Challenge [Waypoint: Use Conditional Logic with If and Else Statements](http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-if-and-else-statements#?solution=var%20flip%20%3D%20Math.random()%20%3C%200.5%20%3F%200%20%3A%201%3B%20%2F%2F%20Code%20produces%200%20or%201%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20if%20(flip%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20return%20'heads'%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20'tails'%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A%0AmyFunction()%3B%0Avar%20result%20%3D%20myFunction()%3Bif(typeof%20flip%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20flip%20%3D%3D%3D%20%22number%22%20%26%26%20typeof%20result%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20result%20%3D%3D%3D%20%22string%22)%7B(function(y%2Cz)%7Breturn%20'flip%20%3D%20'%20%2B%20y.toString()%20%2B%20'%2C%20text%20%3D%20'%20%2B%20z%3B%7D)(flip%2C%20result)%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var flip = Math.random() < 0.5 ? 0 : 1; // Code produces 0 or 1

function myFunction() {

  // Only change code below this line.
  if (flip === 0) {
    return 'heads';
  } else {
    return 'tails';
  }
  // Only change code above this line.
}

myFunction();
var result = myFunction();if(typeof flip !== "undefined" && typeof flip === "number" && typeof result !== "undefined" && typeof result === "string"){(function(y,z){return 'flip = ' + y.toString() + ', text = ' + z;})(flip, result);}

```

**Comment by SaintPeter** [comment] 2015-12-21 02:03
I am unable to reproduce.  This code seems to run just fine.

It looks like you modified the flip function, which is weird . . . but it still passes.

What is the issue?

**Comment by ltegman** [comment] 2015-12-24 21:55
Closing as no repro. Please feel free to reopen with more specific details of what the problem is if you are still seeing and issues.

**Closed by ltegman** 2015-12-24 21:55 UTC
