### ISSUE TITLE
Applied Visual Design: Learn How the CSS @keyframes and animation Properties Work

### ISSUE THREAD

**Issue by Murrium123** [freeCodeCamp/freeCodeCamp#18060] opened 2018-08-29 01:34 UTC
#### Describe your problem and - if possible - how to reproduce it
I have written the right answer to the problem but when I submit it, the engine keeps running the test but it doesnt end. It doesnt tell me whether I did it right or wrong, it just says running tests. I tried redoing it and resetting it but it wont let me pass it. 

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}
@keyframes rainbow {
  0% {
    background-color: blue;
  }
  50%{
    background-color:green;
  }
  100% {
    background-color: yellow;
  }
}
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-how-the-css-keyframes-and-animation-properties-work

#### Tell us about your browser and operating system

* Browser Name: Edge 17 on Windows
* Browser Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
* Operating System: Windows

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/26815710/44759726-08312680-ab12-11e8-8335-674ad4579b27.png)

**Comment by huyenltnguyen** [comment] 2018-08-29 02:06
@Murrium123 I think you would need to switch to Chrome or Firefox in order to use FCC. There have been a number or reports of FCC not working correctly on Edge / IE and Safari.

**Comment by prj1999** [comment] 2018-09-17 12:40
@Murrium123  It is working on Chrome and Firefox. May be it is not compatible on edge.So switch on to Chrome or Firefox.

**Comment by thecodingaviator** [comment] 2018-11-21 15:53
yes, so the problem is on user side and not here, so @Murrium123 / @ezioda004 I think it would be befitting to close the issue

**Comment by ezioda004** [comment] 2018-11-21 16:21
Closing as its not an issue in the challenge itself.

**Closed by ezioda004** 2018-11-21 16:21 UTC
