### ISSUE TITLE
Feature request: Ability to delete unwanted solution from profile. 

### ISSUE THREAD

**Issue by zngit** [FreeCodeCamp/FreeCodeCamp#3889] opened 2015-10-25 11:27 UTC
When i started using freecodecamp, i didn't know that each user can create a personal profile and all his solutions will be present there. 
As a result, my profile page is filled with many redundant solutions because sometimes i comeback and relearn old problems and submit the results many times. 

It would be nice if there is a button that allows user to delete unwanted or dated solutions.
Thanks.

**Comment by bugron** [comment] 2015-10-25 12:11
@zngit thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1342 so I'll close this.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-25 12:11 UTC
