### ISSUE TITLE
Javascript Section already shows waypoint cleared

### ISSUE THREAD

**Issue by shaikhatik0786** [FreeCodeCamp/FreeCodeCamp#2902] opened 2015-08-31 04:14 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screenshot_6](https://cloud.githubusercontent.com/assets/4403762/9571963/c1745704-4fc4-11e5-8560-e3647598b4da.png)

It shows that I have already cleared this waypoint, although I haven't even started yet, infact I ain't even given any input.
The text editor section is still completely empty, but still shows completed???

**Comment by AkiraLaine** [comment] 2015-09-01 08:22
@shaikhatik0786 I can't reproduce this bug. Can you check that you are still getting the bug?

**Comment by shaikhatik0786** [comment] 2015-09-01 17:40
Well, unfortunately, I couldn't wait for it, so I went ahead with clearing it.

**Comment by benschenker** [comment] 2015-09-08 23:21
I'll close this for now, but please reopen if you can replicate this issue.

**Closed by benschenker** 2015-09-08 23:21 UTC
