### ISSUE TITLE
TypeScript Migration

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#43778] opened 2021-10-08 14:31 UTC
## Co-ordination

As discussed in the last contributors [meeting](https://forum.freecodecamp.org/t/office-hour-contributors-may-13-2021/458257/4) we're looking to migrate our client to TypeScript. 

No files will be assigned

**PRs will be prioritised by quality, then by date opened**

## Guidelines

Take a look at the [Codebase Best Practices](https://contribute.freecodecamp.org/#/codebase-best-practices) - **kebab-case file names**

### Small is beautiful

If a file can be migrated on its own, that's perfect.  That makes the PR incredibly easy to review and minimises the chance we break anything.

### PropTypes can go

None of the components in the client directories are intended to be consumed by JavaScript components - eventually everything will be `tsx`.  With that in mind static type checking should be enough.

### React Guidelines

So, we're all on the same page: https://github.com/typescript-cheatsheets/react#readme has some useful advice.  Mostly the linters will warn us, but this is definitely worth a look.

### un-typed packages

If the package does not come with types attached, then please `npm i` the definitions (if they exist) from DefinitelyTyped.  Usually they're just published as `@types/name-of-package`.

### Do Not Ignore Linting, Unless **Absolutely** Necessary

We hope to leverage the type-safety that comes with TypeScript. So, do not ignore the compiler's warnings/errors. If you are stuck, feel free to reach out for help.

### Keeping Git History

Sometimes changing the file from `<filename>.js` -> `<filename>.tsx?` causes the original file to be deleted, and a new one created, and other times the filename just changes - in terms of Git. Ideally, we want the file history to be preserved.

The best bet at achieving this is to:
1) Rename the file
2) Commit with the flag `--no-verify` to prevent husky from complaining about the errors
3) Refactor to TS for migration, in a separate commit.

**Note:** _Editors like VSCode are still likely to show you the file has been deleted and a new one created. If you use the CLI to `git add .`, then VSCode will show the file as renamed in stage_

### Tests are running

We will not be merging any PRs with failing tests.

### Files that should not be migrated (yet)

- `gatsby-node.js`
- `gatsby-config.js` and related
- `redux/*`

To finish migrating the client, we would need additional tooling to handle gatsby-config, gatsby-node and files they import. This could either be an extra tsc compilation step or potentially via ts-node. However, I'm not sure if ts-node would integrate nicely with gatsby develop or gatsby build, so the compilation approach is probably easier.

Before going ahead with this, we should profile gatsby develop and gatsby build to make sure that the time to develop and build the site do not increase too much.

### More guidelines may get added

As we do this, chances are we'll revise the approach.  Any thoughts/comments/critiques are welcome, but I wanted to keep this straightforward for now.

**List of Files To Migrate**

- [ ] /client/src/templates/Challenges/utils/worker-executor.js
- [ ] /client/src/templates/Challenges/utils/worker-executor.test.js
- [ ] /client/src/templates/Challenges/rechallenge/transformers.js
- [ ] /client/src/\_\_mocks\_\_/react-i18next.js

**Comment by Pranav2612000** [comment] 2021-10-10 08:10
I'll also like to help with this. I can see a couple of PRs already. How do I know which unassigned files are still pending?

**Comment by ieahleen** [comment] 2021-10-14 08:23
@mendaomn files are not assigned anymore, just go for it

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

P.S. Abbiamo anche un canale italiano, e sitamo lavorando a tradurre freeCodeCamp in italiano! Ci piacerebbe avere anche te!

**Comment by StanleyDharan** [comment] 2021-10-14 15:35
Ill take on: /client/src/components/landing/index.js

**Comment by ieahleen** [comment] 2021-10-15 06:49
@StanleyDharan I suggest you put it in a draft, if you want precedence on it, a closed PR is not counted

**Comment by ShaunSHamilton** [comment] 2021-10-16 18:18
@oakj Whilst TypeScript is not all that different compared to JavaScript, I would not easily recommend using a migration as your first experience into TypeScript, unless you are already familiar with another strongly typed language.

There is nothing stopping you from trying, and you are more than welcome to get help from the freeCodeCamp community in your learning process. So, I will leave you with some available resources:

- [freeCodeCamp forum](https://forum.freecodecamp.org/)
- [Contributor Docs](https://contribute.freecodecamp.org/)
- [freeCodeCamp Chat](https://chat.freecodecamp.org/)
- [TypeScript Docs](https://www.typescriptlang.org/docs/)

**Comment by oakj** [comment] 2021-10-16 18:56
@ShaunSHamilton Thanks the reply! Appreciate the resources also. Will definitely go through the contributor docs and typescript docs!

**Comment by hishamss** [comment] 2021-10-21 21:54
@ShaunSHamilton I would like to work on migrating **client>utils>challenge-types.js** to TS, but I noticed that 2 variable has the same value in this file :
const zipline = 3;
const frontEndProject = 3;

is this intentional or a mistake?

**Comment by ashiskumar-1999** [comment] 2021-11-12 08:13
Hey @ShaunSHamilton, Can I take on these files migration?
/client/src/client/frame-runner.js
/client/src/templates/Challenges/classic/MultifileEditor.js
/client/src/components/landing/index.js

**Comment by ieahleen** [comment] 2021-11-12 11:41
@ashiskumar-1999 please check that there are not already PRs open for those, but otherwise you are free to go with them, files are not assigned and are always up for grabs in a first come first serve basis

**Comment by ashiskumar-1999** [comment] 2021-11-13 12:12
Thanks, @ieahleen, Let me check then.

**Comment by ashiskumar-1999** [comment] 2021-11-14 06:08
Hey @ieahleen, There are no PR open on the /client/src/client/frame-runner.js and 
/client/src/templates/Challenges/classic/MultifileEditor.js files right now. Can I work on this?

**Comment by Ismailtlem** [comment] 2021-11-14 10:29
Hi @ashiskumar-1999 ,

just go ahead, there is no need to ask for permission

**Comment by foolhardy21** [comment] 2021-11-26 11:26
Hi, please let me know if I have to correct something. I would like to contribute more.

**Comment by kamatheuska** [comment] 2021-12-09 20:39
@Ismailtlem @moT01  Hi there! I was wondering if we can think on a better way to check if there is an open PR for a certain file.

When I [created this PR]( https://github.com/freeCodeCamp/freeCodeCamp/pull/44251#issuecomment-989482443), and used the method suggested above (or somewhere else, I don't remember xD) to check for that, and there were none listed.

It was a fairly small contribution and I have no issue with it not being merged, that's fine!

Still, maybe some sync is needed. No need for permissions, but some coordination to see which files need to be migrated yet? :)

Cheers, keep the hard work! I really appreciate it since I got my first dev job thanks to FCC :)

**Comment by Ismailtlem** [comment] 2021-12-10 13:01
Hi @kamatheuska 

You can use this tool https://tools.freecodecamp.org/ to check if some file is included in a PR or not

**Comment by kamatheuska** [comment] 2021-12-10 14:28
Yeah, I used that one, and no PR's were created at that time for the files migrated in my PR. I could have used wrongly, since I cannot find any docs on how to write a query for it.

**Comment by ShaunSHamilton** [comment] 2021-12-10 14:44
@kamatheuska The two PRs which migrated the same components were
- https://github.com/freeCodeCamp/freeCodeCamp/pull/43966 `landing/index.tsx` (opened 22/10)
- https://github.com/freeCodeCamp/freeCodeCamp/pull/43889 `landing/landing.test.tsx` (opened 15/10)

The important thing to remember about using the above mentioned tool is to use the original name of the file to search (not the migrated name):
<img width="647" alt="image" src="https://user-images.githubusercontent.com/51722130/145591960-07e685e3-06ed-4ed2-a400-a3e191b144be.png">


I hope this was not too inconvenient for you. We do try to respect all contributor's time and effort.

**Comment by kamatheuska** [comment] 2021-12-10 15:02
That's awesome  feedback, thanks! @ShaunSHamilton

**Comment by Ismailtlem** [comment] 2022-02-19 16:55
Why shouldn't we migrate format.js to .ts ?

**Comment by ShaunSHamilton** [comment] 2022-02-19 19:41
@Ismailtlem I think this includes the `format.js` file: 
https://github.com/freeCodeCamp/freeCodeCamp/issues/42256#issuecomment-882546081

**Comment by Dripcoding** [comment] 2022-02-25 21:32
I'll work on migrating these files.

 /client/src/templates/Challenges/utils/frame.js
 /client/src/tests/integration/handled-error.test.js

**Comment by Dripcoding** [comment] 2022-03-19 03:47
has anyone run in to this issue while working on migrations?

`"Cannot use import outside of module"`

When I try to use commonjs, the linter complains about the types I've created. I have a feeling it's some sort of config issue but googling hasn't yielded much.

PR for reference: https://github.com/freeCodeCamp/freeCodeCamp/pull/45456

**Comment by ojeytonwilliams** [comment] 2022-03-19 09:22
That happens when the js file gets used by node. Unless the file has the .mjs extension or the package is declared as a module, you have to use `require`.

Typescript can be configured to emit `require` though: https://www.typescriptlang.org/tsconfig#module

**Comment by alcaidet** [comment] 2022-04-01 04:10
Hello, I would love to help contribute to this and would like to work on migrating these files now:

 /client/i18n/configForTests.js
 /client/i18n/locales.test.js

**Comment by raditotev** [comment] 2022-05-20 13:18
@Sembauke I can see a few more files from the description haven't been migrated. Are you sure you want to close this issue?

**Comment by Sembauke** [comment] 2022-05-20 13:20
It was done automatically :)

If you want to migrate more files, please do!

**Comment by a2937** [comment] 2022-08-12 15:46
I'd like to migrate the worker-executor, if I knew what underlying libraries were used.

**Comment by ojeytonwilliams** [comment] 2022-08-16 07:52
Hi @a2937 worker-executor has no dependencies - it's a standalone module for managing workers.

**Comment by a2937** [comment] 2022-08-16 20:18
Thank you very much. I didn't have prior experience using Web Workers before in JavaScript. Also now I have another slight hiccup. What exactly is eventify? I believe it's some sort of EventListener/Dispatcher but don't know the exact class name at the minute. And secondly I assume the done method right here

 https://github.com/freeCodeCamp/freeCodeCamp/blob/4e5eb183e998614b62cb384d63053273174900d2/client/src/templates/Challenges/utils/worker-executor.js#L51-L58 

refers to the promise method defined here. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/4e5eb183e998614b62cb384d63053273174900d2/client/src/templates/Challenges/utils/worker-executor.js#L96

**Comment by Karorule** [comment] 2022-09-13 11:02
am a beginner

**Comment by Karorule** [comment] 2022-09-13 11:03
if you could teach me coding and programming

**Comment by wojtekxtx** [comment] 2022-09-24 18:43
Im affraid that shit is always be shit, no matter what.

TS tries to shitbade dicks like `js`. Dickora !!!!!!!!!!!!!!!!!!

Simple test? Sure:

FUCK

**Comment by wojtekxtx** [comment] 2022-09-24 18:54
This DDD was started on 8 october 2021. Till this day ( almost full year later ) it isnt done? Jesus! Any newbie developer with not so great knowledge would have finished migration long ago. Its plain simple.

And before you say things like: "there are countless files to migrate". True, but what? There are tools that automates migrstion. These tools **works**.

**Comment by ShaunSHamilton** [comment] 2022-09-24 19:02
@wojtekxtx Fun fact: If you read through, this was started [on the 26th of May 2021](https://github.com/freeCodeCamp/freeCodeCamp/issues/42256).

We welcome contribution from yourself. Also I would be interested in seeing an example of these tools.

**Comment by wojtekxtx** [comment] 2022-09-24 20:47
> Also I would be interested in seeing an example of these tools.

Dont be lazy. Use Google.

> this was started [on the 26th of May 2021](https://github.com/freeCodeCamp/freeCodeCamp/issues/42256).

I took date from header section of this issue........ if this was started earlier, than its even worse than I previously wrote.

**Comment by bradtaniguchi** [comment] 2022-09-25 00:33
> I do not touch projects that are of questionable reputation

???

Then why comment on this issue?🤔

**Comment by wojtekxtx** [comment] 2022-09-25 09:08
@bradtaniguchi By touching I meant: **developing code** for this wannabe serious project.

**Comment by bradtaniguchi** [comment] 2022-09-25 19:55
> @bradtaniguchi By touching I meant: **developing code** for this wannabe serious project. Nothing did I say about comments.

Do you have any examples of where freeCodeCamp is a "wannabe serious" project in regards to the current TypeScript migration? 

I think having some clear code examples and advice on how to improve the TS migration wouldn't be too difficult for a pro such as yourself :)

**Comment by wojtekxtx** [comment] 2022-09-25 21:22
@bradtaniguchi 
> Do you have any examples of where freeCodeCamp is a "wannabe serious" project in regards to the current TypeScript migration?

Oh hell yeah; todays date - this issue creation date = (almost) a year. Year spent on what? Exactly thats my point. You ( project as a whole ) need one year for something that could easily be done in........ 2 weeks max! 

Irony is that this is project that aims in helping people learning to code properly ( according tol standards etc ) and its members needs close to a year just to finish WPM-type task. **Just fucking ridiculous**.

**Comment by bradtaniguchi** [comment] 2022-09-25 21:57
> its members need close to a year just to finish WPM-type task.

I believe all tasks have been accomplished by unpaid volunteers that devote their time and expertise. The fact it's getting done at all is really awesome IMO. It's not exactly easy to migrate over to a large and expansive codebase such as freeCodeCamp to TS, when there's "multiple hands in the pot" all at once. Getting it done in any form or fashion will be a big win.

> I will reiterate: Im NOT going to show where code could be improved as Im not going to devote my time to project(s) of such low quality as freecodecamp.

I thought it was just code contributions you don't have time/effort for? Any feedback or "code reviews" would be appreciated. Even a basic code critique would be useful, especially if the product is of such "low quality". Such efforts shouldn't take any more time it takes than to respond, however such a response would positively help the platform moving forward.

Otherwise anyone can see the date this issue has been created, but very few actually contribute to the platform.

**Comment by wojtekxtx** [comment] 2022-09-26 08:48
@bradtaniguchi 

>  It's not exactly easy to migrate

Once you get proper toolset, Its a breeze. Im not saying that this is obstacle-free, ofc one or two can popup out-of-the-blue (normal thing), but overall its rather smooth.
Have done many migrations of even larger codebases in my life. All succesful.  From my experience, codebase of size of freecodecamp takes about 2 months from planning to completion. Some 75% of this 2 month's is taken by designing WFP. Once you get it done **right**, migrating code is a breeze.

> I believe all tasks have been accomplished by unpaid volunteers that devote their time and expertise. 

Does not matter; this only confirms that this migration has no WFP, and/or plan drawn in WFP is not being strictly followed. For project of this size, especially expansive one (your words), is clear path to disaster. Sorry but thats what it is.

>  when there's "multiple hands in the pot" all at once.

Exactly. Thats what well-thought WFP solves.

**Comment by Sboonny** [comment] 2022-11-17 08:43
While talking to Oliver about `nav-link.tsx` theme and how the `connect` function in it expect `Action<any>` result.

Here is a picture for clearance.

![image](https://user-images.githubusercontent.com/88248797/202397478-66a8f793-0754-4466-b09b-3e6f66956c75.png)

So I am wondering if it's okay to add `action.js` to the list of migration and for me to add generic types to it, or is there a reason for it to not be in the list currently?

**Comment by Sembauke** [comment] 2024-01-10 15:18
I am going ahead and close this as completed. These workers and transformers are not worth migrated due to the TypeScript gymnastics.

**Closed by Sembauke** 2024-01-10 15:18 UTC
Labels: help wanted, platform: learn
