### ISSUE TITLE
tab completion seems to be broken in Waypoint editor

### ISSUE THREAD

**Issue by smiller171** [FreeCodeCamp/FreeCodeCamp#4883] opened 2015-12-02 00:44 UTC
A few days ago when I started I was able to use tab completion in the waypoint editor (typing p then TAB would autocomoplete `<p></p>`) This behavior seems to have stopped working.

**Comment by ltegman** [comment] 2015-12-02 00:48
Closing as a duplicate of #4875

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 00:48 UTC
