### ISSUE TITLE
Potentially faulty test case

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2590] opened 2015-08-23 15:42 UTC
reported: https://www.facebook.com/groups/free.code.camp.bengaluru/761870870602896/?ref=notif&notif_t=group_activity
Screen shot: https://scontent.fsnc1-1.fna.fbcdn.net/hphotos-xpf1/t31.0-8/11888635_963123300399960_4127102090052504172_o.jpg

**Comment by ahstro** [comment] 2015-08-23 15:51
I'm not sure, but it looks like the code looks for spaces and capitalizes the character at the next index? I'm pretty sure that the `sHoRt AnD sToUt` test case is the only one that fails because it's the only one where the supplied string starts with a lower case letter, and since the first character isn't preceeded by a space it's ignored by the campers code.

**Comment by benschenker** [comment] 2015-09-06 04:05
Hey it looks like this is a duplicate of #2424.

Closing this.

**Closed by benschenker** 2015-09-06 04:05 UTC

**Comment by ahstro** [comment] 2015-09-07 19:05
@benschenker I don't think this is a duplicate of that issue actually. If you read the camper's code, you'll see that they understood the need to lower-case everything that's not the first character, they just have a bug in their code. This issue should be closed, and the camper should be redirected to the RSAP wiki page.
