### ISSUE TITLE
diplay issue in curriculum 

### ISSUE THREAD

**Issue by bestpain** [freeCodeCamp/freeCodeCamp#18119] opened 2018-09-11 05:14 UTC
#### Describe your problem and - if possible - how to reproduce it
i am not able to view the whole webpage...if i press select the screen(ctrl+a) then i can view it,looks like font color problem.

#### Tell us about your browser and operating system

* Browser Name: firefox Quantum
* Browser Version: 62.0 (64-bit)
* Operating System: windows 7 64 bit

#### If possible, add a screenshot here

![1](https://user-images.githubusercontent.com/36075994/45339297-7e706700-b5af-11e8-9eb8-e490ad877e8f.png)
![2](https://user-images.githubusercontent.com/36075994/45339300-8203ee00-b5af-11e8-8b23-dfb4c2ba8b4d.png)
![3](https://user-images.githubusercontent.com/36075994/45339305-87f9cf00-b5af-11e8-9274-f28dbc3d19d8.png)

**Comment by div3125** [comment] 2018-09-11 08:50
Duplicate of #18110 which has been resolved. You can recheck and close this issue.

**Closed** 2018-09-11 11:01 UTC
