### ISSUE TITLE
freeCodeCamp for Teachers 

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#42655] opened 2021-06-28 09:07 UTC
I have been thinking about how to make freeCodeCamp more suitable for teachers.  I don't see good support for teachers who want their students to learn through freeCodeCamp. (There may be already). 

Where I studied there wasn't much lesson material to teach because it was mostly outdated or given on paper and then lost forever. There were some lousy programs to teach us, but not much I can remember or want to get back to. Most of the teachers would not have a clue what they were actually teaching.

**The idea**
So to make freeCodeCamp more attractive for teachers Is to give them the ability to teach their class through fcc. That would mean teachers would have to be able to:

1.  Sign up their school and teachers for free through a validation process
2.  Sign up the class they are teaching.
3.  A link to invite students to their class.
4.  A dashboard where teachers can manage their students, (see their name, assign assignments, see completed challenges and completed certifications).
5.  Give teachers the ability to set a certain date for an assignment.
6.  Give the teachers the ability to see project links from their current students.

This gives a basic idea of what I am thinking I would like your opinion on this idea.

**Comment by raisedadead** [comment] 2021-06-28 10:28
Duplicate of #17899 - We would consider reopening the older thread; fair warning, we are short-staffed on the team to build and support it in-house.

**Closed by raisedadead** 2021-06-28 10:28 UTC
Labels: type: feature request

**Comment by Sembauke** [comment] 2021-06-28 10:34
OK.
