### ISSUE TITLE
"Use the provided code three times" doesn't work

### ISSUE THREAD

**Issue by sumit1sen** [FreeCodeCamp/FreeCodeCamp#2837] opened 2015-08-29 04:39 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
After adding:
   $($('.slot')[0]).html('<img src= "' + images[slotOne - 1] + '">');
    $($('.slot')[1]).html('<img src= "' + images[slotTwo - 1] + '">');
    $($('.slot')[2]).html('<img src= "' + images[slotThree - 1] + '">');

only the final 3 tests. pass. The first test fails even though I have used the provided code three times.

**Comment by bugron** [comment] 2015-08-29 06:48
@sumit1sen thanks for posting this issue!
Actually your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2597. The problem is that there are spaces around the '-' sign i.e. `slotOne - 1` instead of `slotOne-1` and the same for `slotTwo` and `slotThree`. Remove those spaces and you'll pass the test. Also there is a pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2800 which is pending for approval.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed** 2015-08-29 19:13 UTC

**Comment by alberto-decaro** [comment] 2015-09-11 21:39
+1

**Comment by h4r1m4u** [comment] 2015-10-05 18:23
I don't know if this is the right place to post, but this is not yet resolved. The whitespaces around the minus sign (' - ') still invalidate the code and it doesn't pass the test.
