### ISSUE TITLE
The example app for "Zipline: Stylize Stories on Camper News" is stuck in a loop of fetching a non existing image

### ISSUE THREAD

**Issue by TFarla** [FreeCodeCamp/FreeCodeCamp#1204] opened 2015-07-05 16:24 UTC
![ss 2015-07-05 at 06 22 32](https://cloud.githubusercontent.com/assets/4613944/8512433/d6eea912-2342-11e5-98b4-2522234564a0.jpg)

Steps to reproduce
================
1. Go to the [app](http://codepen.io/GeoffStorbeck/full/Wveezv)
2. Open the console

**Comment by LumenTeun** [comment] 2015-07-06 17:22
I can not reproduce this, the story must have been removed or the code fixed or something? Did this make the instructions for the Zipline hard to understand in any way, or did the goal of the challenge still come across clear?

**Comment by alexlincoln** [comment] 2015-07-06 21:25
I was also able to reproduce this bug by simply visiting the page

![2015-07-06-132806_1144x939_scrot](https://cloud.githubusercontent.com/assets/6338358/8533561/d76c22e0-23ea-11e5-9744-6969cb07d4bc.png)

**Comment by benmcmahon100** [comment] 2015-07-06 22:13
This issue cannot really be fixed as Geoff Storbeck created and still hosts this pen. However it's not an issue as the demo still works perfectly regardless of what the console is doing. This issue can be closed primarily as there is very little that can be done about it I'm afraid

**Comment by alexlincoln** [comment] 2015-07-06 22:18
@benmcmahon100 We can fork and replace it [here](http://codepen.io/GeoffStorbeck/pen/Wveezv)

That error seems to come from [here](http://www.freecodecamp.com/stories/hotStories), which we should be able to update/fix. What do you think?

**Comment by benmcmahon100** [comment] 2015-07-06 22:34
@alexlincoln Go for it if you want to and you know how to do the fix! I can't go and take credit for your idea! If you want/need my to do it I can sort it out though

**Comment by alexlincoln** [comment] 2015-07-06 22:38
Yeah so the reason it went in an infinite loop was because each time an error occured, it would always replace the `src` string with the same one. It's fixed [here](http://codepen.io/anon/pen/ZGxJZg) by replacing bad images with a random 404 image. I'll submit a PR shortly to update it on the zipline.

**Comment by benmcmahon100** [comment] 2015-07-06 22:39
Awesome work!

**Comment by BerkeleyTrue** [comment] 2015-08-26 00:23
wait, @alexlincoln Did you submit a PR to fix this?

**Comment by alexlincoln** [comment] 2015-08-26 02:20
@BerkeleyTrue Yes, but it was never merged

**Comment by BerkeleyTrue** [comment] 2015-08-26 02:36
You closed the PR after two days, right?

**Closed** 2015-08-27 02:51 UTC
Labels: blocked
