### ISSUE TITLE
It looks something is missing when clicking the index.html button in the new RWD certification

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#49575] opened 2023-03-03 13:03 UTC
### Describe the Issue

A learner reported on the forum that when clicking the index.html button, submit and reset buttons disappeared. Is it designed like so?

Here's the [post](https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app/594106/3).

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2

### Your code

I believe the code is not the cause, but here's the code:

```
<html>
  <body>
    <h1>CatPhotoApp</h1>
    </h2>Cat Photos</h2>
  </body>
</html>
```

### Expected behavior

All buttons should be shown to guide learners.

### Screenshots

![image](https://user-images.githubusercontent.com/19358186/222725777-3b188e05-8b7c-42b4-9e28-9960c6960fee.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome, Edge

**Comment by jeremylt** [comment] 2023-03-03 15:15
It isn't happening for me. Can you see what browser and browser extensions they are using?

**Comment by ShaunSHamilton** [comment] 2023-03-03 17:28
We have had a few reports of this, but it has not been reproducible by anyone on the dev team - an intermittent bug.

I am going to close this as a duplicate of: https://github.com/freeCodeCamp/freeCodeCamp/issues/49475

**Closed by ShaunSHamilton** 2023-03-03 17:28 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
