### ISSUE TITLE
Practically copied what it says. Still no advance

### ISSUE THREAD

**Issue by wrannikko** [FreeCodeCamp/FreeCodeCamp#11926] opened 2016-12-05 06:22 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20Color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.1; HTC Desire 625 Build/LMY47O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    Color: red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by jihdeh** [comment] 2016-12-05 07:06
@wrannikko that's not a bug, you have to add the class name to the `h2` element. Check the instructions correctly.

**Comment by wrannikko** [comment] 2016-12-05 07:08
Thanks but I already solved it

**Comment by erictleung** [comment] 2016-12-05 07:54
Closing as resolved. Happy coding!

**Closed by erictleung** 2016-12-05 07:54 UTC
