### ISSUE TITLE
Challenges not moving forward

### ISSUE THREAD

**Issue by nicolefrazier** [FreeCodeCamp/FreeCodeCamp#2361] opened 2015-08-20 20:51 UTC
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I repeatedly click the Run code (ctrl + enter) button on the Waypoints (starting at 119) and it brings up the confirmation that my code passed, however, it won't allow me to move to the next challenge.  I am having to go to the Map and drill down to the next challenge.

I am using Google Chrome 44.0.2403.155.

I was able to pass the Waypoint using Firefox v40.0.

![image](https://cloud.githubusercontent.com/assets/11296370/9395081/ceffe756-4751-11e5-8c3c-603f7c85b79d.png)

Thanks,
Nicole

**Comment by benschenker** [comment] 2015-09-03 04:13
Hey @nicolefrazier thanks for reporting this!

A couple of weeks ago we had multiple issues of this nature, but thankfully most have been fixed by now.

I'm going to close this as I cannot reproduce it, but feel free to reopen it if you can still reproduce this.

**Closed by benschenker** 2015-09-03 04:13 UTC
