### ISSUE TITLE
Weird validation for portfolio inputs in the setting page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49132] opened 2023-01-25 14:15 UTC
### Describe the Issue

Validations are weirdly strict in imageUrl, but can still accept broken result, but lenient on URL section, although it doesn't accept broken URL.

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/settings
2. Type "https.com" in URL section
3. Type "https://github.com/freeCodeCamp/cdn/blob/main/build/chapter/puppy-small.jpg" in the image section
4. Go to your portfolio
5. See broken Media component

Note: I know that the correct URL is https://cdn.freecodecamp.org/chapter/orange-graphics-small.jpg, the issue is that I can spend time creating an item in portfolio, and it results in broken image later without knowing why.
![image](https://user-images.githubusercontent.com/88248797/214584980-f7a782cd-97ee-43f6-940b-c5dc8ee5614d.png)

### Expected behavior

- stricter validation on URL
- lenient validation on imageURL, maybe shows how image looks instead, so it becomes harder to break it in the portfolio page
![image](https://user-images.githubusercontent.com/88248797/214584806-309c0ac0-1902-4173-b2ad-7e9c6e90834c.png)

### Screenshots

![image](https://user-images.githubusercontent.com/88248797/214585811-d7bb8a0a-3d17-48b1-9e24-f3c915b81ee5.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment] 2023-01-25 23:39
I do not see a bug here. The validation does what majority of the WWW uses when validating such an input - is the input a valid URL - does it match the URL spec. We already go a bit overboard with the validation, as I would have simply used the [isURL](https://www.npmjs.com/package/validator) validator, and left the rest.

The URL validation is done here: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/8d8a4d172e2770ce1d1d44cc309e48152abcb0e5/client/src/components/settings/portfolio.tsx#L184-L202

---

We have had similar to what you are proposing ideas before: https://github.com/freeCodeCamp/freeCodeCamp/issues/40050

**Comment by BalanaguYashwanth** [comment] 2023-02-09 02:22
<img width="862" alt="image" s@Sboonny c="https://user-images.githubusercontent.com/36238382/217700607-a9685083-aad0-4da4-9261-d9feb8f002ea.png">
Hey @Sboonny ,

Can you close this ticket because i am not able to reproduce this issue, refer image

**Comment by BalanaguYashwanth** [comment] 2023-02-09 16:37
Hello @Sboonny,

Is this issue still active ?

From above image i can see issue is solved, let me know any updates ?

Reference - https://github.com/freeCodeCamp/freeCodeCamp/issues/49132#issuecomment-1423523686

**Comment by Sboonny** [comment] 2023-02-09 16:48
Your image indicate the existance of the issue, as campers couldn't know that the link they just copied into their image, isn't a valid image.

**Comment by BalanaguYashwanth** [comment] 2023-02-09 17:24
ok

**Comment by Nirajn2311** [comment] 2023-03-01 15:26
We need to show a small preview of the image the user enters so that they know if the link will actually display the image or not.

**Comment by Sboonny** [comment] 2023-03-01 16:07
Sembauke, mentioned that the about section validation doesn't stop the submit action, and campers can still add about that is bigger than 255 words

**Comment by bbsmooth** [comment] 2023-03-01 16:15
If the goal here is to let people know that the URL they put in the Picture input does/does not link to an image then we need to make sure everyone has access to this information. Showing a small preview of the image is fine, but that only helps people who can see the image. So we will need to make sure we include text that gives the same information (it can be sr-only text).

**Comment by ojeytonwilliams** [comment] 2023-03-02 11:44
To clarify slightly, because I was confused:

This issue is about the Portfolio Settings part of https://www.freecodecamp.org/settings, specifically adding and updating new portfolio items. It is not about the Personal Information section.

However, since we correctly validate the Picture field in the Personal Information section, I propose we reuse that logic for the Image field of the portfolio item.  That way, the a11y concerns @bbsmooth raised should be taken care of.

**Comment by Sboonny** [comment] 2023-03-20 11:07
I found a weird bug while trying to create styles for cards without `image`.

Campers can bypass validation entirely through following this:

If you have an empty portfolio item, and edit an existing one, you can have and empty portfolio item in your profile.

[rec-tab (25).webm](https://user-images.githubusercontent.com/88248797/226321821-c6e79955-35cd-4e91-b851-637a2d7888e4.webm)


Here is a live URL with empty portfolio item https://www.freecodecamp.org/Sboonny

**Comment by Anujvaid45** [comment] 2023-04-15 09:14
Hello @Sboonny 
The basic aim of this issue is to preview the image to user before uploading it in the portfolio section 
I am interested to work upon this issue
So it would be nice if you will let me know whether I am following right path or not in understanding the issue
Thank You!

**Comment by Sboonny** [comment] 2023-04-17 03:19
Welcome, @Anujvaid45.

Yes you are following the right path, if you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Anujvaid45** [comment] 2023-04-18 11:18
Hello @Sboonny 
So I was working on this issue and as mentioned on uploading the image url we wanted to display the preview of image right?
So I have accordingly made changes in my code and its previewing the image after validating the url
So is there anything else required to be done in this issue or should I improve the preview css?

**Comment by Sboonny** [comment] 2023-04-18 11:25
When I see the changes, I can give if there is something missing or if it needs an additional changes.

**Comment by Anujvaid45** [comment] 2023-04-18 18:04
Hello @Sboonny 
I have made the changes in code and you can see the result while adding image url in the portfolio section|
So could you please see that and also suggest the required changes
Meanwhile my tests are getting failed in the pull request, so meanwhile I am trying to solve those

**Comment by ShaunSHamilton** [comment] 2024-04-11 09:56
@ojeytonwilliams and @Nirajn2311 I am just wanting clarification:

Is the solution to show a preview of the image added? Or, to just follow the same logic we use in the "Personal Information" section to validate the URL?

**Comment by ojeytonwilliams** [comment] 2024-04-11 10:18
> Or, to just follow the same logic we use in the "Personal Information" section to validate the URL?

That should be enough.

**Comment by Sembauke** [comment] 2024-10-29 08:33
The Portfolio already seems to have image validation, are we talking about checking if the source directly links to an image by fetching the URL?

**Comment by ojeytonwilliams** [comment] 2024-11-04 09:42
Yep, same as in settings.

**Closed** 2024-11-19 09:08 UTC
Labels: help wanted, platform: learn, type: feature request
