### ISSUE TITLE
Anchor elements missing href attribute in challenge guide

### ISSUE THREAD

**Issue by tannercd** [freeCodeCamp/freeCodeCamp#38876] opened 2020-05-23 02:49 UTC
**Describe the bug**
I found a few more broken links in the challenge guide for Intermediate Algorithm scripting.

**To Reproduce**

1. Go to [freeCodeCamp Challenge Guide: Sorted Union](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-sorted-union/16077) 
2. Click solution number 4, labeled 'JS While Loop'. 
3. Encounter the anchor element missing its href attribute

**Next Bug**

4. Go to [freeCodeCamp Challenge Guide: Smallest Common Multiple](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-smallest-common-multiple/16075) 
5. Click solution 1 and scroll to the list element in relevant links 'String.length' 
6. Encounter the anchor element is missing its href. 

**Next Bug**

7. Go to [freeCodeCamp Challenge Guide: Missing letters](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-missing-letters/16023)
8. Scroll to right under the problem explanation in Relevant links and view the 'String.fromCharCode' 
9. Encounter this anchor element is missing href attribute. 
10. On same page, click solution number 1,
11. Go to relevant links and view list item 'String.length'
12. Encounter the anchor element is missing an href attribute. 
13. Lastly for this page, Click solution number 3
14. Encounter the error within relevant links 'JS Regex Resources' missing href attribute. 

**Expected behavior**
Anchor elements are expected to have href attributes set for expected hyperlink behavior.

**Screenshots**
Screenshots are not necessary for this issue to be resolved. To reproduce section specifies exactly where bugs are located.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by rajat641** [comment] 2020-05-23 04:52
Hi @tannercd , 
I could reproduce all the issues you have mentioned and I found that `<a href="proper_link">` is missing in the code.
I am fixing it now.

**Comment by tannercd** [comment] 2020-05-23 06:22
Hi @rajat641 ,

Ok great. Thank you for providing the fix. Let me know if I should close the issue myself or if you will close it upon completion.

**Comment by rajat641** [comment] 2020-05-23 06:49
Hi @tannercd ,
I'll close this upon completion.

**Comment by rajat641** [comment] 2020-05-27 03:19
Hi @moT01 ,
Can you give me a little hint on how to reproduce this locally??

**Comment by scissorsneedfoodtoo** [comment] 2020-05-27 04:39
Hi @tannercd, thanks for reporting this and for your detailed rundown. Makes it much easier to fix these broken links.

@rajat641, these all seem to be related to challenge guides on the forum. The permissions to edit each post are quite high, so a moderator will have to go in and fix each link.

I'll go through each of these and fix the links.

**Comment by scissorsneedfoodtoo** [comment] 2020-05-27 04:44
Just finished updating these links. Thanks again for creating this issue, @tannercd.

Could you or @rajat641 go through and confirm all the links are working and pointing to relevant guide articles?

Will close this issue for now, but please @ mention me if you notice any issues.

**Closed by scissorsneedfoodtoo** 2020-05-27 04:44 UTC
Labels: type: bug

**Comment by tannercd** [comment] 2020-05-27 04:47
Hi @scissorsneedfoodtoo, you're welcome. I tried to provide as much detail as possible since I'm not able to update the wiki at my current permission level.

I just checked out each of the updated links and everything is working. All bugs fixed. Thank you for closing this issue. Cheers!

**Comment by rajat641** [comment] 2020-05-27 05:02
Thanks a lot @scissorsneedfoodtoo . I was trying to understand the code for 2-3 hours and ended up finding nothing and So I commented here. It saved my time.

**Comment by scissorsneedfoodtoo** [comment] 2020-05-27 06:06
Thanks for confirming all the links are working @tannercd. Your details made it really easy to find and fix them. Please feel free to open another issue if you find more broken links and @ mention me.

Sure, no problem @rajat641. Sorry for the confusion. The code in this repo mostly pertains to the /learn app. The Ghost theme for /news is in another repo and /forum is run on Discourse, and is almost completely independent from the other two applications.

It's a little extra confusing because we usually encourage people to raise issues here in the main repo since it's the most visible. Hope that helps clear the air a little bit, and looking forward to your next contribution :+1: :+1:

**Comment by tannercd** [comment] 2020-05-27 06:33
No problem @scissorsneedfoodtoo . I'm glad I was able to help. If I find anymore broken links on the forum or challenge guides I will create an issue and @ mention you. Thanks again!

**Comment by scissorsneedfoodtoo** [comment] 2020-06-02 07:44
@tannercd, great! Please do.
