### ISSUE TITLE
Waypoint: Constructing Strings with Variables

### ISSUE THREAD

**Issue by MiLeung** [FreeCodeCamp/FreeCodeCamp#5618] opened 2015-12-31 06:00 UTC
Challenge [Waypoint: Constructing Strings with Variables](http://www.freecodecamp.com/challenges/waypoint-constructing-strings-with-variables#?solution=%2F%2F%20Example%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20ourStr%20%3D%20%22Hello%2C%20our%20name%20is%20%22%20%2B%20ourName%20%2B%20%22%2C%20how%20are%20you%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myName%20%3D%20%22Michael%22%3B%0Avar%20myStr%20%3D%20%22My%20name%20is%22%20%2B%20myName%20%2B%20%22%20and%20I%20am%20swell!%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName = 'Michael';
var myStr = 'My name is' + myName + ' and I am swell!';



```

This waypoint only works with double quotes.  Should be both double and single quotes.

**Comment by ltegman** [comment] 2015-12-31 06:10
Closing as a duplicate of #5583. Thanks and happy coding!

**Comment by SaintPeter** [comment] 2015-12-31 06:10
Not a duplicate #5583 - totally different issue.

**Closed** 2015-12-31 06:28 UTC
Labels: QA
