### ISSUE TITLE
#Target5 getting duplicated.

### ISSUE THREAD

**Issue by DarthOpto** [FreeCodeCamp/FreeCodeCamp#12286] opened 2016-12-30 21:17 UTC
#### Challenge Name
Target the Parent/Childern of an Element using jQuery
https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery

#### Issue Description
The ```$("#target5").clone().appendTo("#left-well");``` is duplicating the target 5 button in the left well. 

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.95 (64-bit)
* Operating System: Mac OSx Sierra 10.12.12
* Mobile, Desktop, or Tablet: Macbook Pro

#### Your Code

```js
 <script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");

  });
</script>
 
 
```

#### Screenshot
<img width="1018" alt="screen shot 2016-12-30 at 14 14 56" src="https://cloud.githubusercontent.com/assets/7504395/21572780/64df41ec-ce9a-11e6-865b-cba00de99ca8.png">

**Comment by raisedadead** [comment] 2016-12-30 22:49
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072, please search through closed issues as well before reporting.

**Closed by raisedadead** 2016-12-30 22:49 UTC
