### ISSUE TITLE
Beta d3 output from previous problem is shown to user.

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#13007] opened 2017-01-31 17:16 UTC
#### Data Visualization with D3: Work with Data in D3
http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-data-in-d3

#### Issue Description
Complete a previous challenge, go to the next challenge in the flow.  You'll see the previous output of the challenge you completed before.

#### Browser Information
* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

**Comment by lynxlynxlynx** [comment] 2017-05-01 18:14
Likely a duplicate of #12726 in the sense of the same underlying issue causing them.

**Comment by QuincyLarson** [comment] 2018-06-03 13:54
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Closed by QuincyLarson** 2018-06-03 13:54 UTC
Labels: beta
