### ISSUE TITLE
zipline-build-a-simon-game incorrectly showing complete.

### ISSUE THREAD

**Issue by wamacdonald89** [FreeCodeCamp/FreeCodeCamp#2601] opened 2015-08-23 19:48 UTC
The zipline-build-a-simon-game shows as complete even though I have not completed or submitted a solution. May have some relation to the recent update.

**Comment by denmch** [comment] 2015-08-24 21:05
Duplicate of/related to #1800

**Closed** 2015-08-26 00:02 UTC
