### ISSUE TITLE
Adjusting the Padding of an Element 

### ISSUE THREAD

**Issue by ahsan-AJ** [FreeCodeCamp/FreeCodeCamp#10631] opened 2016-09-09 21:23 UTC
Challenge [adjusting-the-padding-of-an-element](https://www.freecodecamp.com/en/challenges/html5-and-css/adjusting-the-padding-of-an-element#?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-15px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2030px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2030px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.injected-text {
  margin-bottom: -25px;
  text-align: center;
}

.box {
  border-style: solid;
  border-color: black;
  border-width: 5px;
  text-align: center;
}

.yellow-box {
  background-color: yellow;
  padding: 10px;
}

.red-box {
  background-color: red;
  padding: 10px;
}

.green-box {
  background-color: green;
  padding: 10px;
}
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
<h5 class="box red-box">padding</h5>
<h5 class="box green-box">padding</h5>
</div>

    ```
  The challenge says "Change the padding of your green box to match that of your red box."
Initially the padding of the red box is 20 px and the padding of the green box is 10 px.
So, we need to change the padding of the green box to 20 px to pass the challenge.

    But when we do so,the Run Tests is not successful. Below the challenge it says "Your green-box class should give elements 20px of padding." . Even though I have changed the padding of green box class to 20px it is still passing it

![screenshot 24](https://cloud.githubusercontent.com/assets/13553103/18403367/c365bfba-76fd-11e6-9896-9025d4d5a491.png)

**Comment by ArielLeslie** [comment] 2016-09-09 21:28
Copy of Issue #10582

**Comment by ahsan-AJ** [comment] 2016-09-09 21:30
This problem is happening in the next challenge "Adjust the Margin of an Element" as well.

**Comment by dhcodes** [comment] 2016-09-10 02:19
@ahsan-AJ Thanks! closing as duplicate of #10582

**Closed by dhcodes** 2016-09-10 02:19 UTC
