### ISSUE TITLE
Global Scope and Functions on beta.freecodecamp 

### ISSUE THREAD

**Issue by myleschatman** [freeCodeCamp/freeCodeCamp#12706] opened 2017-01-21 20:58 UTC
Answer is not accepted on the Beta Freecodecamp. "Do not declare oopsGlobal using the var keyword" is the only issue showing up.

Challenge [Global Scope and Functions](https://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%0A%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20oopsGlobal%20%3D%205%3B%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declare your variable here
var myGlobal = 10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal = 5;
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

**Comment by systimotic** [comment] 2017-01-21 21:11
Hi @myleschatman! Thank you for reporting this issue.

Your code works fine for me. Can you refresh and try again?
Do you see any errors in the console? I'm not sure how to open it in Safari, but I know it's `Cmd + Shift + J` in Firefox and Chrome.

Some other things to try:
- Run in incognito mode
- Try in a different browser

**Comment by myleschatman** [comment] 2017-01-21 21:20
Hello @systimotic. Thank you for this suggestions. I tried all of your suggestions in the Chrome Browser as well in Incognito Mode and still receiving the same issue. Here is an image of the console window.

<img width="1680" alt="incognito" src="https://cloud.githubusercontent.com/assets/3689853/22177871/2909f146-dfdc-11e6-96e0-94a2ea26493b.png">

**Comment by systimotic** [comment] 2017-01-21 22:13
@myleschatman Sorry, I wasn't paying attention and missed that you were talking about the beta! 😅
I can confirm that this issue is occurring on beta.

The tests for this challenge are [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L2489), but this particular test hasn't been changed from the current live version.
I suspect this might have something to do with the tail not being run anymore, or with an update to the testing framework.

**Comment by myleschatman** [comment] 2017-01-21 22:19
@systimotic Ah ok! That makes a lot of sense. Thanks for the update. :)

**Comment by systimotic** [comment] 2017-01-21 22:52
I found the source of the issue!
`var oopsGlobal;` is in the head [here](https://github.com/freeCodeCamp/freeCodeCamp/blame/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L2451). This is now an issue because the head and tail are now included in the tests (https://github.com/freeCodeCamp/freeCodeCamp/issues/10258)

Removing the definition from the head fixes the browser tests, but it breaks the CI tests.

@freeCodeCamp/moderators 
What would work, is moving `var oopsGlobal;` to the beginning of the `solution`, although that seems a bit hacky to me. Should I go through with that?

**Comment by raisedadead** [comment] 2017-01-27 16:36
Needs a bot more creative solution though, will take a look when I can, but keeping open for others to pitch in.

**Comment by systimotic** [comment] 2017-01-27 22:41
@raisedadead I noticed that on other challenges where the head or tail were causing issues, the solution was removed entirely. Should we also do that here?

Also, [this](https://gitter.im/FreeCodeCamp/Contributors?at=588b995c5309d6b358771a8e) would also be helpful for the challenges where the head or tail is causing an issue.

**Comment by rmdawson71** [comment] 2017-01-31 18:01
Experiencing the same issue.

**Comment by rmdawson71** [comment] 2017-02-04 20:05
Any status on when this will be fixed?

**Comment by QuincyLarson** [comment] 2017-02-05 15:53
@rmdawson71 I think @raisedadead plans to tackle this. I'm going to assign him to the issue. He has a lot of other things he's working on currently, but this will be fixed before we ship to production.

**Comment by masters-george** [comment] 2017-02-10 06:43
Ran into same problem running with Chrome on Ubuntu Linux 16.10. Here is my code:


// Declare your variable here

var myGlobal = 10;
function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal = 5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

**Closed** 2017-09-02 01:14 UTC
Labels: beta, help wanted
