### ISSUE TITLE
loopProtect triggers in HTML

### ISSUE THREAD

**Issue by Kimkykie** [freeCodeCamp/freeCodeCamp#12683] opened 2017-01-21 10:05 UTC
Challenge [add-an-accessible-date-picker](http://beta.freecodecamp.com/en/challenges/applied-accessibility/add-an-accessible-date-picker) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The code result includes additional lines of code
Browser: Google Chrome
![bugfcc](https://cloud.githubusercontent.com/assets/16070564/22173627/32a45ba8-dfda-11e6-91ef-3b00bc38fa2b.PNG)

```html
    
    
<body>
<header>
  <h1>Tournaments</h1>
</header>
<main>
  <section>
    <h2>Mortal Combat Tournament Survey</h2>
    <form>
      <p>Tell us the best date for the competition</p>
      <label for="pickdate">Preferred Date (MM-DD-YYYY):</label>
      
      <!-- Add your code below this line -->
      <label for="date">Enter date (MM-DD-YYYY):</label>
      <input type="date" id="pickdate" name="date">
      
      <!-- Add your code above this line -->
      
      <input type="submit" name="submit" value="Submit">
    </form>
  </section>
</main>
<footer>&copy; 2016 Camper Cat</footer>
</body>

    ```

**Comment by systimotic** [comment] 2017-01-21 14:36
I can confirm that this is happening. I think it's being triggered by the word "for" in the text. The loopProtect code should probably be updated to only check for loops inside of script tags.

**Comment by OFFLlNE** [comment] 2017-02-01 13:45
I deleted cache.
But still seeing this issue. On like 4-6 challenges in a row

I will reopen just in case till someone can tell me why does it still happen despite the new merge.

**Comment by Greenheart** [comment] 2017-02-01 14:02
@OFFLlNE I don't know if it made it into the new push to the beta site since Berkeley said he pushed at [22:35 (UTC + 1)](https://gitter.im/FreeCodeCamp/CoreTeam?at=5891033dfba5bfea06b197eb) but I merged two hours after his message.

I think this will be fixed in at most 2-3 days :blush:

**Comment by OFFLlNE** [comment] 2017-02-01 14:04
Great, think it deserves to be open meanwhile.

**Comment by systimotic** [comment] 2017-02-26 00:09
@OFFLlNE This works for me now, can you check whether it works for you as well and close?

**Comment by Greenheart** [comment] 2017-02-27 17:49
I'm closing as I just verified that this is fixed in Chrome 56 and Firefox 51.

Thanks to everyone involved! :smile:

**Closed by Greenheart** 2017-02-27 17:49 UTC
