### ISSUE TITLE
Js bug with properties functions

### ISSUE THREAD

**Issue by moromer90** [freeCodeCamp/freeCodeCamp#15238] opened 2017-06-07 07:22 UTC
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20if%20(myObj.hasOwnProperty(checkProp))%7B%0A%20%20return%20myObj%5BcheckProp%5D%3B%0A%20%20%7D%20else%20return%20%22Not%20found%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22house%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp)){
  return myObj[checkProp];
  } else return "Not found";
}

// Test your code by modifying these values
checkObj("house");

```

**Comment by indefinite0212** [comment] 2017-06-07 07:34
hi @moromer90 there's something wrong with your code. if you need help solving JavaScript challenges you should ask first at [JavaScript help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) before posting a git hub issue.
happy coding 😄

**Comment by moromer90** [comment] 2017-06-07 07:57
No the code is OK. the problem is that your test-check-application doesn't differ caps in test-answears.
So if the result should be "Test fullfilled successfully" and you wrote "test fullfilled successfully" -> the program doesn't pass that reply as correct.

**Comment by raisedadead** [comment] 2017-06-07 09:14
Hi @moromer90 

Thanks for reporting, while your code is arguably correct, but unfortunately, this is expected.
As a developer, you are expected to return the **exact output**. This is very important in programming.

While both results look similar, they are actually NOT.

Closing this as not a bug.

**Closed by raisedadead** 2017-06-07 09:14 UTC
