### ISSUE TITLE
4 diffrent solution doesn't work - i tried on IE, FF, Chrome.

### ISSUE THREAD

**Issue by paulcrowski** [FreeCodeCamp/FreeCodeCamp#7694] opened 2016-03-22 13:20 UTC
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=function%20repeat(str%2C%20num)%20%7B%0A%20%20var%20newstr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20newstr.push(str)%3B%0A%20%20%7D%0A%20%20return%20newstr.join(%27%27)%3B%0A%7D%0A%0Arepeat(%22abc%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
4 diffren solution doesn't work - i tried on IE, FF, Chrome. On console log, jsfiddle it is correct, but here the code doesn't pass after run test, some other users from chat have the same problem.
I have reloaded page, I used diffrent browsers it doesnt help.

My code:
```javascript
function repeat(str, num) {
  var newstr = [];
  for (var i = 0; i < num; i++) {
    newstr.push(str);
  }
  return newstr.join('');
}

repeat("abc", 3);

```

**Comment by alistermada** [comment] 2016-03-22 13:44
Apparently the name of the function for this challenge was changed a few days ago. Change `repeat(str, num)` to `repeatStringNumTimes(str, num)` and it should work.

**Comment by sludge256** [comment] 2016-03-22 16:37
Pressing `Reset`should load a current version of the challengeSeed (correct starting code).

**Comment by paulcrowski** [comment] 2016-03-22 16:42
Thank you for your help, I haven't noticed. I made it in my editor a few days ago and pasted, later I tried code from wiki and the same, now I will know how to check for me was the most important result ;-)

thank you

**Comment by sludge256** [comment] 2016-03-22 16:45
@paulcrowski Please confirm the issue is resolved by closing it. Thank you.

**Closed** 2016-03-22 16:46 UTC
Labels: blocked
