### ISSUE TITLE
Wrong code preview

### ISSUE THREAD

**Issue by andykennedyhope** [FreeCodeCamp/FreeCodeCamp#8752] opened 2016-05-22 01:16 UTC
###### Target Even Numbered Elements Using jQuery
[https://www.freecodecamp.com/challenges/target-even-numbered-elements-using-jquery](url)
**_Previous challenges have same issue (and probably next ones)_**

#### Issue Description

One of the jquery code is rendered twice in the #preview .iphone .iframe-scroll.
the problem appears when first loading the challenge and after a successful challenge test.
#### Browser Information

* Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0
* Linux
* Desktop 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well"); // This one is rendered twice
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

#### Screenshot

![git_fcc_issue](https://cloud.githubusercontent.com/assets/19495861/15451584/044a5e8c-1fba-11e6-91e4-0434b3621738.png)

**Comment by erictleung** [comment] 2016-05-22 01:47
@andykennedyhope closing as duplicate of #5072.

**Closed by erictleung** 2016-05-22 01:47 UTC
