### ISSUE TITLE
The first time I click in the code editor, the cursor position is wrong

### ISSUE THREAD

**Issue by jfromero** [freeCodeCamp/freeCodeCamp#14493] opened 2017-04-19 14:59 UTC
Hi!

I think this issue it's happening in all challenges. The first time I click in the code editor, the cursor position is wrong. If I try to write something, the text appears in another part. You can test e.g in "Warn your Users of a Dangerous Action" challenge

Thanks a lot and best regards.

**Comment by dhcodes** [comment] 2017-04-19 15:11
@jfromero Thanks for reporting an issue. This is a duplicate of a long-known issue with the editor. See: https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. It will be fixed when the beta site replaces the current site.

**Closed by dhcodes** 2017-04-19 15:11 UTC
