### ISSUE TITLE
Submit button does not permit navigation to the next challenge after successfully completing task.

### ISSUE THREAD

**Issue by risedindustries** [freeCodeCamp/freeCodeCamp#13782] opened 2017-03-06 21:23 UTC
Challenge [Inherit Styles from the Body Element](https://www.freecodecamp.com/challenges/inherit-styles-from-the-body-element#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%20%20font-family%3A%20Monospace%0A%20%20%20%20%20%20%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch1%3E%20Hello%20World%20%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    color: green;
    font-family: Monospace
      
  
</style>

<h1> Hello World </h1>
```

**Comment by OFFLlNE** [comment] 2017-03-06 21:26
Thank you for reporting the issue
Here are a couple suggestions:
1. Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2. Try the challenge in incognito mode. A plugin might be interfering with the tests.
3. Try the challenge in a different browser. There may be an issue with your version of browser.
Please try these things in order and let us know what did and didn't work. I can't reproduce your issue right now, so any extra information will be helpful in finding out what's causing your issue.

**Comment by OFFLlNE** [comment] 2017-03-08 14:10
Closing since no reply in over 2 days

**Closed by OFFLlNE** 2017-03-08 14:10 UTC

**Comment by dk0r0y333** [comment] 2017-03-12 04:06
you're missing the closing }
