### ISSUE TITLE
Settings Item in Navbar

### ISSUE THREAD

**Issue by andresmonc** [freeCodeCamp/freeCodeCamp#18089] opened 2018-09-05 18:14 UTC
#### Describe your problem and - if possible - how to reproduce it
On certain pages on screens with a smaller view width (between 957-1099) the settings item in the navbar will appear below the Navbar itself in a new row.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings
https://www.freecodecamp.org/quincylarson

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version:  68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 7 

#### If possible, add a screenshot here

![capture](https://user-images.githubusercontent.com/41450290/45112550-8a6eab80-b10d-11e8-8974-55b6ef1fa68f.PNG)

**Comment by Nirajn2311** [comment] 2018-09-19 19:16
Duplicate of #18154

**Comment by andresmonc** [comment] 2018-09-19 19:31
I think #18154 is a duplicate of #18089

**Closed** 2018-09-25 16:55 UTC
