### ISSUE TITLE
Duplicate display in simulated phone

### ISSUE THREAD

**Issue by BuckeyeDan** [FreeCodeCamp/FreeCodeCamp#3194] opened 2015-09-09 13:15 UTC
Challenge http://freecodecamp.com/challenges/waypoint-create-a-form-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Upon the load of this lesson, it was obvious there are two complete renderings of the simulated image in the simulated phone.  This is in several lessons.

![capture](https://cloud.githubusercontent.com/assets/14185539/9762696/2e7e1a5a-56d3-11e5-8632-e9bbf7cc2d16.JPG)

**Comment by benschenker** [comment] 2015-09-10 02:48
Hey @BuckeyeDan thanks for posting!

I cannot replicate this on my machine, have you tried [A Hard Refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) or opening it in an incognito window?

**Comment by benschenker** [comment] 2015-09-10 04:04
It looks like this is a duplicate of #2706, please see that discussion for updates (and post any progress/issues related to this there!)

**Closed by benschenker** 2015-09-10 04:04 UTC
Labels: blocked
