### ISSUE TITLE
Learn Relational Databases courses don't open 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#54147] opened 2024-03-19 19:29 UTC
### Describe the Issue

The start button opens an "about:blank" page in my browser rather than navigating me to GitPod unlike the NPM backend challenges. 

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```
N/A
```

### Expected behavior

GitPod should have opened up and created a new repository for me to start CodeRoad in. 

### System

- Device: Desktop
- OS: Windows 10 
- Browser: Firefox
- Version: 124.0

**Comment by a2937** [comment] 2024-03-19 19:31
My browser was blocking it. Never mind.

**Comment by moT01** [comment] 2024-03-20 15:33
What was the issue @a2937? Was there a setting or something you needed to change?

**Comment by a2937** [comment] 2024-03-20 16:23
There was a setting in Firefox I had to change. I unfortunately forgot what I had setting I had to change. It might have had something to do with my protection settings.

**Comment by jdwilkin4** [comment] 2024-03-20 18:11
It looks like the issue is resolved so I am going to go ahead and close this 👍

**Closed by jdwilkin4** 2024-03-20 18:11 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
