### ISSUE TITLE
Functional tests crashing Replit

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#49634] opened 2023-03-09 04:07 UTC
### Describe the Issue

Most (if not all) of the QA projects that have functional tests have crashing issues on Replit including the last part of the "Quality Assurance and Testing with Chai" curriculum challenge. I believe it's the `chai-http` stuff that is crashing the server when running on Replit.

We can force a server restart by adding an `after` function to the tests.

```
after(function() {
  chai.request(server)
    .get('/')
});
```

I have not confirmed or tested this with all the projects only a few of them. I'm also not sure if having the `after` function will have any unintended consequences.

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/

### Your code

```

```

### Expected behavior

Replit not causing the tests to fail because it has crashed.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

I might add a few forum links. But it is an extremely common issue.

**Comment by ShaunSHamilton** [comment] 2023-03-09 12:30
The issue is all of the integration tests with `chai-http` are throwing without being caught:
```bash
18) Functional Tests
       Integration tests with chai-http
         Send {surname: "Colombo"}:
     Uncaught AssertionError: assert.fail()
```

Ideally, we need to handle the error, whilst still failing the tests.

**Comment by lasjorg** [comment] 2023-03-09 22:07
@ShaunSHamilton I don't think that is the issue because the server will crash with passing tests. It seems to be caused by the HTTP methods in the tests, at least the GET method.

As an example, here is the metric-imperial-converter fCC demo project on Replit

https://replit.com/@lasjorg/metric-imperial-converter-demo-project

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter

Without the `after` function at the bottom of `2_functional-tests.js` it will just crash and never restart so you can't pass.

**Comment by scissorsneedfoodtoo** [comment] 2023-03-31 09:57
Thanks for taking the time to report this, @lasjorg, and for those helpful details.

I think this issue can be closed once https://github.com/freeCodeCamp/boilerplate-mochachai/pull/92 is merged.

I think this issue can be closed now that https://github.com/freeCodeCamp/boilerplate-mochachai/pull/92 is merged and the updated descriptions for the Quality Assurance and Testing with Chai project in https://github.com/freeCodeCamp/freeCodeCamp/pull/49878 are live.

By the time they get to this project, learners should know that they can chain `.keepOpen()` to `chai.request(...)` to prevent `chai-http` from closing the connection to the server automatically.

They should also be able to look at the Mocha docs and use `teardown` for the current TDD style tests to keep the connection to the server open.

I forked your completed project above and added this after the functional tests. It seemed to work as expected, and kept the server open after all the tests ran:

```
teardown(function() {
  chai.request(server)
    .get('/')
});
```

Here's a link to my fork of your project: https://replit.com/@scissorsneedfoo/metric-imperial-converter-demo-project-fork#tests/2_functional-tests.js

There are still a couple of projects (Personal Library, Secure Real Time Multiplayer Game) that still have some example functional tests that use `chai-http`, but they don't seem to kill the connection to the server automatically.

I think the fix for those would be to move the descriptions for the tests over to Learn, and simplify the unit / functional test files like most of the other boilerplates.

**Closed by scissorsneedfoodtoo** 2023-03-31 09:57 UTC
Labels: type: bug, help wanted, scope: curriculum

**Comment by lasjorg** [comment] 2023-03-31 16:42
@scissorsneedfoodtoo I have not looked into this fix yet or tested anything.

But given the explanation, I'm not sure I understand why this would only affect Replit? As far as I know, all the projects and tests worked fine locally and I believe on Glitch(*).

I assume the keepOpen is somewhat equivalent as a fix to the after function, if so, I get why it would fix the Replit issue. I just don't understand the problem as stated in the PRs, or why that would only affect Replit.

But I guess this is all irrelevant as long as it fixes the Replit issue.

---
(*) Except for one test with a `//` in a test for an invalid request get gets stripped by Glitch, which is a side issue not related to this issue. Don't remember off hand which challenge it is.
