### ISSUE TITLE
'Ask for help' button doesn't work

### ISSUE THREAD

**Issue by raditotev** [freeCodeCamp/freeCodeCamp#17322] opened 2018-05-31 07:58 UTC
When clicking on **Ask for help** button nothing happens.
[URL](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package)
Browser: Chrome 66

![image](https://user-images.githubusercontent.com/5617443/40769753-b04904f8-64b0-11e8-907e-1bff34acbfe8.png)

**Comment by johnkennedy9147** [comment] 2018-05-31 09:28
I can recreate this - applies in both the "Apis And Microservices" and "Information Security And Quality Assurance" sections. Other sections the button works. Weirdly if you click it in one of those two sections and then navigate to a section where it works the modal pops up when the page loads.

**Comment by GiovanniBonino** [comment] 2018-06-09 15:59
Did you manage to submit this challenge? 
I try uploading all twich.com urls possible related to the project but none seems to work. I also tried submitting a link to a github repository containing the project files but it didn't work either.

**Comment by raditotev** [comment] 2018-06-11 13:33
Read carefully the instructions. More info info [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/13095).

**Comment by moT01** [comment] 2019-02-19 16:11
Should be resolved with PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35280

**Comment by moT01** [comment] 2019-02-19 16:14
I am actually going to close this, since it's a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/35155 - and the other one has more details.

**Closed by moT01** 2019-02-19 16:14 UTC
