### ISSUE TITLE
my waypoints are being automatically done!!!!

### ISSUE THREAD

**Issue by AaishaMuhammad** [FreeCodeCamp/FreeCodeCamp#2413] opened 2015-08-21 12:28 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

hi. not only does the above one have an issue, since i started all my activities are being automatically done!! it just will open, and then will tick everything done, do everything that has to be done and say 'go to my next challenge'! i even cleared the cached files and images, still doesnt work.

i am using google chrome, and i just created a new account, on my prev account and on the same PC i have done the challenges that i am talking about, but i wanted to restart as i was forgetting everything.

**Comment by AaishaMuhammad** [comment] 2015-08-21 12:32
alright i solved the problem. before i started the account, today i on my old account was doing these activities, and now when i came to the one i didnt do, its not doing them,

**Comment by benschenker** [comment] 2015-08-21 16:20
Glad you solved the issue!

Please close this if you feel the issue is resolved.

**Closed** 2015-08-21 16:43 UTC
