### ISSUE TITLE
Validating Search bar content before making request

### ISSUE THREAD

**Issue by shakti97** [freeCodeCamp/freeCodeCamp#37386] opened 2019-10-18 05:32 UTC
How to reproduce?
      Go to the search bar , press space and hit enter, you will see the loading starts and it makes request for searching which should not be there until and unless some content is there in the search bar.

I would like to work on it if its needed

**Comment by thecodingaviator** [comment] 2019-10-18 11:40
I cannot reproduce this. You're talking about the search bar on the top left. Right?

**Comment by codingride** [comment] 2019-10-18 18:15
Search bar value needs to be trimmed before being submitted. 
Example:
`value.trim()`

**Comment by shakti97** [comment] 2019-10-20 05:14
> I cannot reproduce this. You're talking about the search bar on the top left. Right?

yes, should i send a short video
issue is: until and unless there is no content in the search bar there should be no making of request for searching,

**Comment by thecodingaviator** [comment] 2019-10-20 07:18
> > I cannot reproduce this. You're talking about the search bar on the top left. Right?
> 
> yes, should i send a short video
> issue is: until and unless there is no content in the search bar there should be no making of request for searching,

Please send in a GIF, I'm not sure what you mean.

**Comment by MathewtheCoder** [comment] 2019-10-20 09:01
I was able to reproduce this issue. Please see the below gif.
![Oct-20-2019 14-26-27](https://user-images.githubusercontent.com/10682672/67157161-0a71c800-f346-11e9-9e8a-e0b8ed45ff3a.gif)

**Comment by shakti97** [comment] 2019-10-20 12:07
yes, please see the above gif @thecodingaviator

**Comment by thecodingaviator** [comment] 2019-10-20 13:36
Oh, okay. I was missing something before.

**Comment by shakti97** [comment] 2019-10-20 13:42
@thecodingaviator I have sent a pr, have a look on that :)

**Comment by raisedadead** [comment] 2019-10-20 13:46
@scissorsneedfoodtoo please check and see if we need to update this on the news?

**Comment by moT01** [comment] 2019-10-20 14:48
Is this really a problem? So it searches for a space. I'm not against fixing this, but I'm not sure if it's better or worse. You can put a space in google search and it will search - you don't get any results, but you can search.

While taking a look at this, I did notice that the search on the main page will bring up suggestions when you put a space in the search - but on the news page, putting a space in the search doesn't bring up any suggestions. Just a little discrepancy - probably not much of a problem.

**Comment by ojeytonwilliams** [comment] 2019-10-20 16:38
I do not think this is a bug; it's a feature that we should keep. It allows you to see an unfiltered list of news articles without having to navigate away unless you want to.

As Tom said, it's not ideal that news's search behaves differently, but the behaviour discussed here is more useful.

**Comment by raisedadead** [comment] 2019-10-20 18:31
Thanks @moT01 and @ojeytonwilliams for weighing in. I'll defer to your opinions and close this.

**Closed by raisedadead** 2019-10-20 18:31 UTC
Labels: type: bug

**Comment by scissorsneedfoodtoo** [comment] 2019-10-21 07:24
@raisedadead, on News we're using https://github.com/algolia/autocomplete.js/blob/master/README.md for the search bar. Like @moT01 and @ojeytonwilliams mentioned, it's unfortunate that it behaves differently. There may be a way to simulate this over on News, though.
