### ISSUE TITLE
Functional Programming: Pass Arguments to Avoid... - Correct answer not accepted

### ISSUE THREAD

**Issue by nikkilr88** [freeCodeCamp/freeCodeCamp#16304] opened 2017-12-23 19:49 UTC
#### Challenge Name

Functional Programming: Pass Arguments to Avoid External Dependence in a Function

#### Issue Description

Correct answer is not accepted when space between function name and params is not removed.

#### Browser Information

* Browser Name, Version: Chrome  63.0.3239.84 (Build oficial) (64 bits)
* Operating System: Win10
* Mobile, Desktop, or Tablet:  Desktop 

#### Your Code

Not accepted:
```js
function incrementer (val) {
  return val+1;
  // Add your code above this line
}
```
Accepted:
```js
function incrementer(val) {
  return val+1;
  // Add your code above this line
}
```

#### Screenshot

![fireshot capture 162 - learn to code i freecodecamp_ - https___beta freecodecamp org_en_c](https://user-images.githubusercontent.com/24983331/34322308-5228cb18-e7e9-11e7-93c3-9fb87a0bc0af.png)

![fireshot capture 164 - learn to code i freecodecamp_ - https___beta freecodecamp org_en_c](https://user-images.githubusercontent.com/24983331/34322309-556298a4-e7e9-11e7-828f-c67ce26aa85c.png)

**Comment by PedroFlaxh** [comment] 2017-12-23 22:13
Must be an issue with the regex. I'll try to fix it.

**Comment by Bouncey** [comment] 2017-12-24 10:54
Please @PedroFlaxh 

The RegEx shouldn't be so ridgid

**Comment by PedroFlaxh** [comment] 2017-12-24 11:56
Alright @Bouncey !

**Comment by sagarjhaa** [comment] 2017-12-25 16:05
Hi All, 
I am a first timer and knows how to code ,would really like to work on this error.

**Comment by PedroFlaxh** [comment] 2017-12-26 16:15
@sagarjhaa don't get me wrong but I think that since the issue was already assigned to me I should have been the one fixing it.

I was away for Christmas and didn't have the chance of looking at the code.

**Comment by sagarjhaa** [comment] 2017-12-26 17:01
@PedroFlaxh I am really new to this and didn't see anybody under Assignee so worked on it. So sorry.

**Comment by PedroFlaxh** [comment] 2017-12-26 17:25
That's ok! The issue seems fixed and that was the main goal.

Have a nice 2018.

**Comment by d-hamon** [comment] 2018-01-11 06:35
Sorry but the issue is still no fixed

Not accepted :

`// Add your code below this line
function incrementer (val) {
  return val+1;
  // Add your code above this line
}`

**Comment by sagarjhaa** [comment] 2018-01-11 15:41
@d-hamon I have created the Pull request but still waiting for it to be accepted.

**Closed** 2018-01-15 16:38 UTC
Labels: beta, first timers welcome, help wanted, type: tests

**Comment by AngieJudilla** [comment] 2018-08-07 06:58
function incrementer(val) {
  return fixedValue+1;
  // Add your code above this line
}

**Comment by Felixr91** [comment] 2018-08-14 11:49
Can anyone explain why the code doesn't work with "num++"?

`// the global variable
var fixedValue = 4;

// Add your code below this line
function incrementer (num) {
  return num+1;
  
  // Add your code above this line
}

var newValue = incrementer(fixedValue); // Should equal 5
console.log(fixedValue); // Should print 4`

**Comment by Felixr91** [comment] 2018-08-14 11:51
Can anyone explain why this code doesn't work with "num++"? 

Thanks!

    // Add your code below this line
    function incrementer (num) {
    return num++;
  
    // Add your code above this line

**Comment by huyenltnguyen** [comment] 2018-08-14 18:47
@Felixr91 There are two ways to use the increment operator: `num++` and `++num`. The difference between them is when the value is returned. You can read about them here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Increment_()

To fix your code, you can either do
```
num++;
return num;
```
or
```
return ++num;
```

**Comment by AngieJudilla** [comment] 2018-08-15 03:35
:)

**Comment by Felixr91** [comment] 2018-08-15 05:08
huyenltnguyen Thanks for sharing the increment page of MDN. I haven't reviewed this section in some time.

**Comment by huyenltnguyen** [comment] 2018-08-15 06:12
@Felixr91 Glad I can help! To be honest, I had to revisit the page, too, after I saw your comment 😄
