### ISSUE TITLE
Potential issue with dev sign in

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39501] opened 2020-09-01 07:46 UTC
@RandellDawson and @ahmadabdolsaheb found themselves unable to log in locally.  Ahmad's issue was fixed by `npm run seed`, but Randy's was not.  Could you explain a bit in this issue if the problem persists?

It might be nothing, but it could be a sign something isn't quite right.

**Comment by Sky020** [comment] 2020-09-01 12:22
I am able to log in, and save settings. I did however get a bunch of errors on the landing page, which I resolved by adding:
```
ALGOLIA_ADMIN_KEY=123abc
ALGOLIA_APP_ID=X5V7KWJ4RB
ALGOLIA_API_KEY=a45d2b80c97479bbda5cf5c55914230f
```
Back to `.env`

Possibly useful to take a look at what changes #39443 made, and correct the setup for the changes.

**Comment by Sky020** [comment] 2020-09-01 12:28
Here are the errors I am getting without the above _env_ vars
![image](https://user-images.githubusercontent.com/51722130/91851321-de59ef80-ec56-11ea-9f0d-0c4dd52ec6c4.png)

Slightly more verbose:
![image](https://user-images.githubusercontent.com/51722130/91851376-f5004680-ec56-11ea-8404-f7156032c165.png)

**Comment by raisedadead** [comment] 2020-09-01 12:46
Thanks for confirming, we should add some defaulting logic to this actually in dev mode.

Speaking of which @scissorsneedfoodtoo do you know if we have a test instance of Algolia, I do not see any on the dashboard.

**Comment by RandellDawson** [comment] 2020-09-01 13:14
The only way I was able to finally clear up the errors I was seeing, was to clear my cache for localhost.  Before that, I had tried:
1. resyncing master
2. running the following commands:
```bash
cp sample.env .env
npm run clean
npm ci
npm run seed
npm run develop
```

**Comment by raisedadead** [comment] 2020-09-01 13:26
Thanks @RandellDawson this additional information helps. The secrets were changed (by me) on the `sample.env` which have led the sessions (in the local db on your end) to go stale. 

The client is sending the session details to the API, the API is also correctly seeing them in the db, but because the keys (which encrypted) the tokens in the first place has changed it is erroring out.

This is kind of expected. The fix is to purge the cache on the browser (techically you need to purge the db, where the keys are, but clearing the cache should be enough).

**Comment by RandellDawson** [comment] 2020-09-01 13:42
> techically you need to purge the db, where the keys are, but clearing the cache should be enough

Wouldn't the `npm run seed` have purged the db?

**Comment by raisedadead** [comment] 2020-09-01 13:46
Nope. It will only "seed" the user collection if it is not present already. It would not create/remove anything else by design.

**Comment by RandellDawson** [comment] 2020-09-01 13:48
Should we add something to `npm run seed` that purges the local db and then seeds it?

**Comment by raisedadead** [comment] 2020-09-01 13:59
> It would not create/remove anything else by design.

Like I said, this behaviour is intentional. The DB is not a ephemeral entity. It should not be mutated after intial setup. That is the only way you would catch potential bugs from reaching production.

**Comment by ojeytonwilliams** [comment] 2020-09-01 14:24
Oh, so because I don't keep my browser cache, it kept requesting a new token?

**Comment by raisedadead** [comment] 2020-09-01 14:30
> Oh, so because I don't keep my browser cache, it kept requesting a new token?

Yes.

**Comment by scissorsneedfoodtoo** [comment] 2020-09-02 12:25
@raisedadead, we do have a test instance of Algolia, but I accidentally created it under my account rather than a general team account, so only I have access to it.

I'll create a test instance under the team account and create a PR to update the keys in sample.env.

**Comment by raisedadead** [comment] 2020-09-03 06:12
I am not in favor of adding our keys (although these are client side keys for algolia) to version control. Instead the search feature sould be mocked/disabled in developement.

**Comment by scissorsneedfoodtoo** [comment] 2020-09-03 08:11
@raisedadead, sure, that sounds good. I think it'll throw errors for now, but there's probably a good way to disable search altogether in development.

**Comment by Twaha-Rahman** [comment] 2020-09-25 21:55
Let's mock the search feature. We can test then.

**Comment by scissorsneedfoodtoo** [comment] 2020-09-27 09:52
Hey @Twaha-Rahman, thank you for all of your help with testing. It's been awesome to see how quickly the testing coverage has improved with each of your PRs.

I'm all for mocking the search bar. Now that Cypress is in place, it will be good to make sure things like the up and down keys and mouse entering / leaving the dropdown is working as expected. I haven't looked much into it, but it should be possible to pass a mock Algolia response to the `SearchHits` component somehow.

**Closed** 2020-09-27 10:55 UTC
