### ISSUE TITLE
Homepage requires scrolling

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17602] opened 2018-06-16 14:15 UTC
Reaching 'Go to the coding curriculum' button requires scrolling. this should be the case imo

**Comment by eolculnamo2** [comment] 2018-06-16 15:58
We could adjust the make a BEM modification to the  big breaks class making the margin top 40px and margin bottom 35px. I think it would look better this way.

**Comment by moT01** [comment] 2018-06-16 16:28
@supuun can you specify what the problem is and what you want to see happen?

**Comment by supuun** [comment] 2018-06-16 17:10
This is what I'm talking about:
![sss](https://user-images.githubusercontent.com/11631221/41500800-6c87f854-71a9-11e8-9a2e-f47a95b39610.PNG)
![ss](https://user-images.githubusercontent.com/11631221/41500799-6c5f72c6-71a9-11e8-863b-988a12495032.png)
the whole page doesn't fit on my laptop's screen

**Comment by Nirajn2311** [comment] 2018-06-16 19:29
I think that the text size should be decreased or whitespace between the lines should be removed.
Open for beginners.

**Comment by supuun** [comment] 2018-06-17 11:12
as far as I'm concerned, the font isn't responsive.

**Comment by thecodingaviator** [comment] 2018-11-21 10:43
I don't think this should be done, there are other things that we want the user to see too. So @jooji-san please close the issue :)

**Closed** 2019-01-24 11:31 UTC
