### ISSUE TITLE
Problem with Waypoint 104

### ISSUE THREAD

**Issue by elliottmaas** [FreeCodeCamp/FreeCodeCamp#3191] opened 2015-09-09 11:29 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I am having a problem with Waypoint: Declare Javascript Variables (104). No matter what is entered as a variable, this error pops up after running tests. 

<img width="1100" alt="screen shot 2015-09-09 at 7 25 28 am" src="https://cloud.githubusercontent.com/assets/13491203/9760544/0a3c3e42-56c4-11e5-9d83-a1be08e0079a.png">

**Comment by awesomeaniruddh** [comment] 2015-09-09 11:36
The challenge is working fine for me. Can you post your code?

**Comment by elliottmaas** [comment] 2015-09-09 11:37
// var ourName = "Free Code Camp";
// var myName = "Elliott";

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.

if(typeof(myName) !== "undefined"){(function(v){return v;})(myName);}

**Comment by awesomeaniruddh** [comment] 2015-09-09 11:38
Uh, you *haven't* declared a variable. You're commenting the declaration out :)

Please remove the two slashes before `myName = "Elliott";`

**Comment by elliottmaas** [comment] 2015-09-09 11:39
Oh, yes, I literally just figured that out. Sorry about that!

**Comment by awesomeaniruddh** [comment] 2015-09-09 11:40
Since the issue is now resolved, I'm closing it :)

From next time onwards, please go to Gitter first to get your code checked before opening an issue :)

**Closed** 2015-09-09 11:40 UTC
