### ISSUE TITLE
Text Alignment issue on popup when turning ON the night mode in settings page

### ISSUE THREAD

**Issue by BalanaguYashwanth** [freeCodeCamp/freeCodeCamp#49311] opened 2023-02-09 17:18 UTC
### Describe the Issue

If you check below image, when turning ON the night mode on account settings page, I saw alignment text issue at update preference popup.

Reference link - https://www.freecodecamp.org/settings

<img width="1512" alt="Screenshot 2023-02-09 at 10 48 59 PM" src="https://user-images.githubusercontent.com/36238382/217889804-4a91df82-4298-49b8-82db-81b00397d162.png">

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to 'account settings page'
2. Click on 'menu'
3. Scroll down and ON the night mode
4. See popup with text alignment issue 

### Expected behavior

The alignment should be centered and after 3 or 5 seconds it should close automatically

<img width="1512" alt="Screenshot 2023-02-09 at 10 43 02 PM" src="https://user-images.githubusercontent.com/36238382/217888593-0c9967c9-7e2a-4cdd-a58a-b2922f4e8cc0.png">

### System

- Device: Mac
- OS: [iOS 14]
- Browser: [brave]
- Version: [e.g. 22]

**Comment by balaji-sivasakthi** [comment] 2023-02-09 19:44
Could you give me the resolution of your screen?

**Comment by Nirajn2311** [comment] 2023-02-09 20:26
Hi, that's the intended behaviour of the alert in the site. So I'll be closing this issue.

**Closed by Nirajn2311** 2023-02-09 20:26 UTC
Labels: type: bug, status: waiting triage

**Comment by BalanaguYashwanth** [comment] 2023-02-10 01:27
Mainly it looks for user alignment is not proper, you can ask few other users @Nirajn2311
