### ISSUE TITLE
unexpected text in place of <script> and </script>

### ISSUE THREAD

**Issue by salahis** [FreeCodeCamp/FreeCodeCamp#2317] opened 2015-08-20 13:31 UTC
This happens on several pages under the jQuery section.
Example:
http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery

fccss <---- <sript> was expected
  $(document).ready(function() {
    $("button").addClass("animated bounce");
    $(".well").addClass("animated shake");

  });
fcces <---- </sript> was expected

**Comment by benschenker** [comment] 2015-08-20 13:59
Thanks for posting an issue,

This is a duplicate of #2242 and others though in general try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by BerkeleyTrue** [comment] 2015-08-21 03:57
Closing as duplicate

**Closed** 2015-08-21 03:57 UTC
