### ISSUE TITLE
Cursor Control is Wonky 

### ISSUE THREAD

**Issue by rthidden** [FreeCodeCamp/FreeCodeCamp#2343] opened 2015-08-20 18:29 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. The cursor will not go all the way down to the bottom of the blackboard. 
2. The arrow keys on the keyboard are trying to operate the instruction scroll and the cursor on blackboard at the same time.

**Comment by arya45** [comment] 2015-08-26 08:30
+1 I had the same issue, but it works if you start typing something: the cursor works fine then. But yeah, this needs fixing.

**Comment by benschenker** [comment] 2015-09-07 03:34
Hey @rthidden thanks for posting this!

It looks like this is a duplicate of #1941, so keep an eye there for updates.

**Closed by benschenker** 2015-09-07 03:34 UTC
