### ISSUE TITLE
Camper in Delhi encountering CSP issues in Chrome

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6050] opened 2016-01-11 07:20 UTC
![](https://www.evernote.com/l/AqSoM_IxTuBCKIkOBGWvqJAObmrZCWo4BtkB/image.png)

**Comment by SaintPeter** [comment] 2016-01-11 18:11
Closing as duplicate of #5999 

I have updated that issue title to be more descriptive.

**Closed by SaintPeter** 2016-01-11 18:11 UTC
Labels: help wanted
