### ISSUE TITLE
Testing issue for ES6

### ISSUE THREAD

**Issue by traanhn** [freeCodeCamp/freeCodeCamp#14807] opened 2017-05-10 12:31 UTC
Challenge [understand-the-differences-between-import-and-require](http://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

import { capitalizeString } from "string_functions"
capitalizeString("hello!");

```

**Comment by erictleung** [comment] 2017-05-10 16:16
@traanhn thanks for the issue. Yes, there appears to be an issue with this challenge. Two big things:

1. The challenge test doesn't have a test message
2. There are two notes right next to each other

So we either move the notes around or consolidate them somehow. Additionally, the challenge test should have a useful message to go along with it.

**Comment by erictleung** [comment] 2017-05-10 16:18
@traanhn also, this appears to be a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12739 and https://github.com/freeCodeCamp/freeCodeCamp/issues/14372. So I'm closing this issue in favor of those pre-existing ones. Happy coding!

**Closed by erictleung** 2017-05-10 16:18 UTC
