### ISSUE TITLE
Regular expressions contain too much plus, and a misleading description

### ISSUE THREAD

**Issue by Blauelf** [FreeCodeCamp/FreeCodeCamp#2331] opened 2015-08-20 15:55 UTC
Challenge http://freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the description, `/the+/gi` is used to search for all "the" and "The" in a string. While stated differently, I would consider the `+` being part of the pattern. As I understand it, the `+` will only affect the character or group directly in front of it (as do `*`, `?` and `{}`), so in the example `e` (will also match a "theeee"), which is probably not what the author wanted. Even worse, the assertions want me to write `/and+/gi`, where `/and/gi` would be sufficient and less misleading.

These extra plusses won't change anything if you just count matches, as these words cannot overlap (example if they did: `"abaaba".match(/aba+/gi)` will return only one match, `"abaaba".match(/aba/gi)` will return two), but might change results if you evaluate the whole matches for example for total length.

I also do not quite agree with the description of the "g" flag, though I would not call that false, just imprecise. I would describe it as "After finding a pattern match, continue search after that match, so that the found patterns cannot overlap" or similar, to make clear that without the "g" flag, only the first match is returned.

**Comment by denmch** [comment] 2015-08-20 18:17
Duplicate of #1938 & #2163

**Comment by bugron** [comment] 2015-08-23 07:08
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2184
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2163
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Closed** 2015-08-24 18:23 UTC
