### ISSUE TITLE
openweathermap needs an api key

### ISSUE THREAD

**Issue by michaelkebe** [FreeCodeCamp/FreeCodeCamp#3737] opened 2015-10-14 08:04 UTC
The example codepen does not work. Looks like the openweathermap API needs a key to access.

http://www.openweathermap.org/api

The Javascript console says:
```
http://api.openweathermap.org/data/2.5/weather?lat=48.1270&lon=11.3665&units=metric&callback=jQuery2130876683295937255_1444809427340&_=1444809427342 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by awesomeaniruddh** [comment] 2015-10-14 13:03
Thanks for posting the issue, but this is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3714

Hence, I will have to close the issue. Feel free to continue the discussion in the other issue.

Happy coding!

**Closed by awesomeaniruddh** 2015-10-14 13:03 UTC
