### ISSUE TITLE
Small bug with last questions in video quiz

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9861] opened 2016-07-23 11:10 UTC
#### Challenge Name

Video quiz. 
#### Issue Description

After clicking true/false for the last question I always get a question from the next section for a second or so.
#### Browser Information
- Browser: Chrome, Latest
- OS: Windows7-x64
- Device: Laptop
#### Video

https://youtu.be/2va4l6gb4u4

**Comment by dhcodes** [comment] 2016-07-24 03:16
I just tested and can confirm this behavior.

**Comment by systimotic** [comment] 2016-11-30 20:54
@dhcodes @SamAI-Software 
Hi there! This issue is really old, and I can't seem to reproduce this anymore.
Because of the combination of those two things, I'm closing this issue. If you can still reproduce, please reopen!

**Closed by systimotic** 2016-11-30 20:54 UTC
