### ISSUE TITLE
top contributor link in non english profiles broken

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43225] opened 2021-08-17 21:29 UTC
The top contributor link in user profiles of non English languages is broken

To reproduce:
go to https://www.freecodecamp.org/espanol/mot01
click the `top contributor` (`Contribuyente principal`) link
page hangs

It tries to take you to https://www.freecodecamp.org/espanol/top-contributors
Chinese goes to https://chinese.freecodecamp.org/top-contributors, which gives a 404

English goes to https://freecodecamp.org/top-contributors, which redirects to the news article

**Comment by moT01** [comment] 2021-08-18 15:37
Well, I don't think that article is translated to any other languages - so probably going to the English version for all of them would be fine for now.

But, I suppose ideally, we would check 'if translated article exists, go there, else go to English'

**Comment by ieahleen** [comment] 2021-08-18 15:41
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by nhcarrigan** [comment] 2021-08-18 18:04
As a quick fix, are we pointing all languages to the English path?

**Comment by nhcarrigan** [comment] 2021-08-18 19:27
Okay here's my proposed approach:

https://github.com/freeCodeCamp/freeCodeCamp/blob/21fbbe69d55f00b481df5b05b4edcbb01ab59c93/client/src/components/profile/components/Camper.tsx#L132
Change the `to` value here to `{t('links:top-contributors')}`

Add `"top-contributors": "https://freecodecamp.org/top-contributors"` to each of the `links.json` files in the `client/i18n/locales/` languages.

This will render the correct English link in all languages, and allow us to change the link for a specific language if the article is translated.

Provided no one objects, I think this is straightforward enough that we could open to `first timers only`.

**Comment by bips03** [comment] 2021-08-21 19:31
Has the issue been fixed? I am an amateur in this. Would love to know if the issue is resolved :)

**Comment by ieahleen** [comment] 2021-08-21 19:35
@bips03 not yet, but there is a PR open that once merged is going to fix this issue

**Closed** 2021-08-23 15:50 UTC
Labels: type: bug, first timers only
