### ISSUE TITLE
Missing "tracks" property causes code to fail

### ISSUE THREAD

**Issue by charlottejoy** [FreeCodeCamp/FreeCodeCamp#8265] opened 2016-04-23 23:46 UTC
Not sure if this is how it started, but when I reset my code, the "tracks" part of 5439 is missing. Like this:

>  5439: {
>       album: "ABBA Gold"
>     }

Since it's above the "only change code below this line" part, it took me a while to realize why my code wasn't passing. Don't know if anyone else is having this issue.

Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%2C%0A%20%20%20%20%20%20tracks%3A%5B%5D%2C%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20if(prop!%3D%3D%22tracks%22%20%26%26%20value!%3D%3D%22%22)%7B%0A%20%20%20collection%5Bid%5D%5Bprop%5D%3D%20value%3B%0A%20%7D%0Aelse%20if(prop%3D%3D%22tracks%22%20%26%26%20value!%3D%3D%22%22)%7B%0A%20collection%5Bid%5D.tracks.push(value)%3B%0A%7D%0Aelse%20if%20(value%3D%3D%3D%22%22)%7B%0A%20%20delete%20collection%20%5Bid%5D%5Bprop%5D%3B%0A%7D%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold",
      tracks:[],
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
 if(prop!=="tracks" && value!==""){
   collection[id][prop]= value;
 }
else if(prop=="tracks" && value!==""){
 collection[id].tracks.push(value);
}
else if (value===""){
  delete collection [id][prop];
}
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by BKinahan** [comment] 2016-04-24 09:13
I tried your code and it passes all tests with or without a `tracks` property within record `5439`, but there probably should be a `tracks` property there in case users want to form their own tests since the instructions don't mention that a `tracks` property should be created if it does not exist (and if the input calls for adding to it).

**Comment by alistermada** [comment] 2016-04-24 09:20
Seems to be related to #7394.

**Comment by charlottejoy** [comment] 2016-04-26 15:11
That's it, some of the tests wouldn't run without it and yes it does seem related. 
Thanks for taking a look and for pointing out the extra space. 
Have a great day!

**Comment by mkincaid11** [comment] 2016-05-03 20:47
there was no mention anywhere in the previous exercises about space related issues. I had the correct code but it wouldn't complete until I removed the space in the quotes from " " to ""

**Comment by crashuniverse** [comment] 2016-06-09 06:05
Duplicate of #8970 or #8691

This report seemed to have skipped our attention. Weeks later, we observed it first at #8970 and a very thorough discussion and attempt has been made to clarify this for students with an update in instructions.

In a different issue somewhere else at #8691, a fail safe mechanism is being implemented while testing for student's submitted solution against existent arrays.

@charlottejoy If you feel comfortable with instructions and progress happening in other threads, you can recommend to close this issue.

**Comment by atjonathan** [comment] 2016-06-09 07:15
@crashuniverse, Thanks for catching this!

**Closed** 2016-06-09 07:15 UTC
