### ISSUE TITLE
waypoint #113 bug

### ISSUE THREAD

**Issue by palakjain855** [FreeCodeCamp/FreeCodeCamp#3027] opened 2015-09-03 17:16 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![Uploading Screen Shot 2015-09-03 at 22.45.36.png…]()
i am doing correctly but the objective is being crossed

**Comment by palakjain855** [comment] 2015-09-03 17:18
i am doing correctly but the objective is being crossed
![screen shot 2015-09-03 at 22 45 39](https://cloud.githubusercontent.com/assets/14000427/9665411/bf4bcf0e-528d-11e5-8e78-a433fdb3a76e.png)

**Comment by natac13** [comment] 2015-09-03 17:28
@palakjain855 It looks like you are just copying the code from the description, which is targeting the wrong element. Your code targets the parent of the `#left-well` where you need to be targeting the `#left-well` itself which happens to be the parent of......**answer element**???

**Comment by bugron** [comment] 2015-09-03 17:29
@palakjain855 thanks for posting this issue!
Closing as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2980
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2337

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-03 17:29 UTC
