### ISSUE TITLE
Issue with testing - Bonfire larget numbers in Arrays

### ISSUE THREAD

**Issue by agatita** [FreeCodeCamp/FreeCodeCamp#3755] opened 2015-10-15 12:55 UTC
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays#?solution=var%20result%20%3D%20%5B%5D%3B%0Avar%20max%20%3D%200%3B%0A%0Afunction%20largestOfFour(arr)%0A%7B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%0A%20%20%20%20%20%20%7B%20for%20(j%20%3D%200%3B%20j%20%3C%20arr%5Bi%5D.length%3B%20j%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%20if%20(max%20%3C%20arr%5Bi%5D%5Bj%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20max%20%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20result.push(max)%3B%0A%20%20%20%20%20%20%20max%20%3D%200%3B%0A%20%20%20%20%20%20%7D%0A%20%20return%20result%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.64 Safari/537.36</code>.

Hello, sorry to disturb but I don't understand why testing fails with this code, my results seem good.
Do you have any idea please? I've already read closed issues but it was not the same case.
Thank you for your help

here are 2 screens with the good results : 
![image](https://cloud.githubusercontent.com/assets/7646061/10514162/6ce13418-734c-11e5-807b-7b8d9a896f1e.png)
![image](https://cloud.githubusercontent.com/assets/7646061/10514178/9468e2b0-734c-11e5-939e-f623118a61ba.png)

My code:
```
var result = [];
var max = 0;

function largestOfFour(arr)
{
  for (i = 0; i < arr.length; i++)
      { for (j = 0; j < arr[i].length; j++)
        { if (max < arr[i][j])
            { 
              max = arr[i][j];
            }
        }
       result.push(max);
       max = 0;
      }
  return result;
}

largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);
```

**Comment by ltegman** [comment] 2015-10-15 13:19
The reason you can't find any issues is that your logic is solid! The problem with your code is that you are initializing your variables in the global scope. `var result = [];` happens one time when the code first loads, so after you've called `largestOfFour` once the `result` array you're pushing onto in your function is not empty.

For this reason and others global variables are something you should avoid whenever possible. Better practice would be to declare your `result` and `max` variables within your `largestOfFour` function. This means they'll be fresh every time you run the function, other functions won't have access to them, and they'll get removed from memory once the function has completed running.

Closing this issue since the problem is not with tests, but feel free to reply if you need any further clarification.

Thanks and happy coding!

**Closed by ltegman** 2015-10-15 13:19 UTC

**Comment by agatita** [comment] 2015-10-15 13:24
Thank you very much Logan!
