### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by lickyourlips** [FreeCodeCamp/freecodecamp#691] opened 2015-05-28 07:30 UTC
According to this waypoint's requirements, the green-box class should give the _top_ of elements _20px_ of margin. However, in practice it marks that value as incorrect, accepting a value of _40px_ instead.

**Comment by terakilobyte** [comment] 2015-05-28 11:02
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:02 UTC
