### ISSUE TITLE
Unable to open curriculum(learn.freecodecamp.org) after clicking Go to my curriculum(freecodecamp.org)

### ISSUE THREAD

**Issue by iamzakofficial** [freeCodeCamp/freeCodeCamp#17398] opened 2018-06-02 20:17 UTC
![image](https://user-images.githubusercontent.com/9195137/40880515-e41a3e56-66cb-11e8-8234-394be79a4b7f.png)

**Comment by Kiyani-g** [comment] 2018-06-02 20:39
same problem

**Comment by raisedadead** [comment] 2018-06-02 20:46
Is this a possible duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17360? Can you guys confirm you general region as in the other thread?

**Comment by iamzakofficial** [comment] 2018-06-02 20:47
i tried onProxy, it works on proxy.

**Closed by raisedadead** 2018-06-02 20:46 UTC

**Comment by Kiyani-g** [comment] 2018-06-02 20:57
how proxy works ? i still have problem

**Comment by Kiyani-g** [comment] 2018-06-02 20:57
how to use proxy?

**Comment by iamzakofficial** [comment] 2018-06-02 21:17
install chrome extension browsec, turn it on and then open freecodecamp
