### ISSUE TITLE
"Change the presentation of a bar chart" Chrome test failure

### ISSUE THREAD

**Issue by psyfry** [freeCodeCamp/freeCodeCamp#42564] opened 2021-06-18 22:18 UTC
**Affected page**
Add a link to the coding challenge with the problem.
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/change-the-presentation-of-a-bar-chart

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
<style>
  .bar {
    width: 25px;
    height: 100px;
    /* Add your code below this line */
    margin: 2px;
    
    /* Add your code above this line */
    display: inline-block;
    background-color: blue;
  }
</style>
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];

    d3.select("body").selectAll("div")
      .data(dataset)
      .enter()
      .append("div")
      .attr("class", "bar")
      .style("height", x => (x*10 + "px")); // Change this line
  </script>
</body>



```

**Expected behavior**
Add a clear and concise description of what you expected to happen.
Solution should work in Chrome and Firefox. Currently fails in chrome but passes in Firefox.
In Chrome, "The fifth div should have a height of 250 pixels and a margin of 2 pixels." test passes while every other test fails. 
Tested both again with the official solution and had the same issue with chrome. 

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

**System (please complete the following information):**
 - Device: Desktop
 - OS: Fedora 34
 - Browser: Chrome, Firefox
 - Version: [e.g. 22]
Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Firefox 89.0.1 (64-bit)

**Additional context**
Tested 1080p and 1440p screens and got same result, Firefox passes and Chrome fails

**Comment by ShaunSHamilton** [comment] 2021-06-19 08:26
Hello there,

Thank you, for taking the time to open this. However, I am unable to reproduce this - the code passes in Chrome for me.

Therefore, I am going to close this as the most likely cause for the test failing in one of your browsers is a browser extension interfering with the tests. We recommend disabling all browser extensions with access to `freecodecamp.org`.

If this has been closed in mistake, please reopen with more information.

**Closed by ShaunSHamilton** 2021-06-19 08:26 UTC
Labels: scope: curriculum, status: waiting triage, type: bug
