### ISSUE TITLE
Browser Compatibility Bug - Waypoint: Style the HTML Body Element

### ISSUE THREAD

**Issue by TheFlagCourier** [FreeCodeCamp/FreeCodeCamp#4908] opened 2015-12-02 07:58 UTC
**Synopsis**
The following snippet of code does not work for it's intended challenge under certain browsers.

```html
<style>
  body{
    background-color: black;
  }
</style>
```

_**Challenge**_: [Waypoint: Style the HTML Body Element] (http://www.freecodecamp.com/challenges/waypoint-style-the-html-body-element?solution=%3Cstyle%3E%0A%20%20body{%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20}%0A%3C%2Fstyle%3E%0A)

Browsers Effected: Firefox (42.0), Edge (20.10240.16384.0)

Confirmed Working (non-issue) in Google Chrome (ver unknown) by  @h4r1m4u on FreeCodeCamp/Help (Gitter).

**Comment by bugron** [comment] 2015-12-02 13:00
@TheFlagCourier thanks for posting. We have a PR which will fix this. Closing as a duplicate of #4865.

**Closed by bugron** 2015-12-02 13:00 UTC
