### ISSUE TITLE
Bug in challenge#178

### ISSUE THREAD

**Issue by appi147** [freeCodeCamp/freeCodeCamp#15575] opened 2017-07-01 08:17 UTC
#### Challenge Name

https://www.freecodecamp.org/challenges/comparisons-with-the-logical-and-operator

#### Issue Description

The above challenge requires only one `if` statement. If I put second `if` statement under comments, then also solution is not accepted.
#### Browser Information

* Browser Name, Version: Chrome 59.0.3071.115
* Operating System: Ubuntu 17.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js


function testLogicalAnd(val) {
  // Only change code below this line

  if (val<=50&&val>=25) {
  //  if () {
      return "Yes";
    //}
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);


```

#### Screenshot
![screenshot from 2017-07-01 13-41-47](https://user-images.githubusercontent.com/22685364/27760358-8d123d50-5e63-11e7-8474-1cd52ba16064.png)

**Comment by Bouncey** [comment] 2017-07-01 16:26
@appi147 thanks for taking the time to raise this issue.

This is the same as issue #11360

The issue is with using RegExp's for the multiple `if's assertion. 

We are looking into implementing AST traversal to remedy this post the beta release

Closing as a duplicate :sparkles:

**Closed by Bouncey** 2017-07-01 16:26 UTC
