### ISSUE TITLE
Learn Form Validation by Building a Calorie Counter - Step 69

### ISSUE THREAD

**Issue by webro1989** [freeCodeCamp/freeCodeCamp#56082] opened 2024-09-12 14:19 UTC
### Describe the Issue

hi!

`document.querySelectorAll("#breakfast input[type='number']");`

 the above line of code is correct. the challenge step should be corrected. because it is not passing with inner qoute marks around type attribute value `'number'`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-69

### Your code

```

function calculateCalories(e) {
  e.preventDefault();
  isError = false;
  const breakfastNumberInputs = document.querySelectorAll("#breakfast input[type='number']");


}


```

### Expected behavior

the challenge step should be passed with quote marks around the type attribute value `number` .

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment] 2024-09-12 16:47
Thank you for opening this Issue, it seems to be a duplicate of #56081, as such I will be closing this in favor of the other one

**Closed by ilenia-magoni** 2024-09-12 16:47 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
