### ISSUE TITLE
Some project url related issue

### ISSUE THREAD

**Issue by Bhavna777** [freeCodeCamp/freeCodeCamp#39547] opened 2020-09-09 10:49 UTC
When I enter any random url on the freecodecamp solution of :-- 1) Scientific Computing with Python Certificate, 2) Data Analysis with Python Certificate, 3) Machine learning with Python certificate, then without checking my project it redirect me to next project(challenge).

**Comment by Sky020** [comment] 2020-09-09 11:39
Hello there,

The tests have not been written yet, for them on the client side. This is a known issue, and you are welcome to open a PR adding tests.

Duplicate of #37185

**Closed by Sky020** 2020-09-09 11:39 UTC
Labels: scope: learn, status: needs help for triage
