### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by lisandroalves** [FreeCodeCamp/freecodecamp#671] opened 2015-05-27 23:24 UTC
The challenge asks the user to make the top margin 20px when the challenge itself only accepts 40px as the correct answer

**Comment by terakilobyte** [comment] 2015-05-28 11:01
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:02 UTC
