### ISSUE TITLE
Email Password Reset Form Not Working

### ISSUE THREAD

**Issue by lui8906** [FreeCodeCamp/freecodecamp#15] opened 2015-01-10 05:12 UTC
Password form button does not respond to click. Additionally the jumbotron div that is meant to have a white background for the form is too short (only approx 96px and form is 317px).

**Comment by terakilobyte** [comment] 2015-01-12 18:00
Lui8906 can you confirm the issue is resolved so we can close it?

**Comment by lui8906** [comment] 2015-01-12 20:54
Still when I am at the reset form after recieving the email and following the link, I put in a matching password and the button does not do anything or provide any feedback, are there password requirements? etc..

**Comment by terakilobyte** [comment] 2015-01-12 22:57
Ok, thanks. To confirm, this is on password reset, after requesting to reset password? I'll look into it, thanks.

**Comment by lui8906** [comment] 2015-01-13 00:01
Yep

**Comment by FreeCodeCamp** [comment] 2015-01-13 06:44
We've fixed this with our recent pull request.

**Closed by FreeCodeCamp** 2015-01-13 06:44 UTC
