### ISSUE TITLE
Streak days counter with wrong values

### ISSUE THREAD

**Issue by lucasarvelo** [freeCodeCamp/freeCodeCamp#16712] opened 2018-02-14 00:25 UTC
#### Issue Description
Inaccurate track of the streak days on the profile page.
The calendar keeps the track of the challenges but the streak days value was reset in 7 days.

#### Browser Information
* Browser Name, Version: Chrome, Version 64.0.3282.140 (Official Build) (64-bit)
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot
![streak_days_tracking_issue1](https://user-images.githubusercontent.com/6098495/36181522-2a1f8782-10f3-11e8-9a15-9583cb761355.JPG)

**Comment by TJBarrettJR** [comment] 2018-02-14 04:10
Hey, it looks like this might be a duplicate of [this](#7925) active issue.

**Comment by raisedadead** [comment] 2018-02-14 06:40
Yes thanks @TJBarrettJR

**Closed by raisedadead** 2018-02-14 06:40 UTC
