### ISSUE TITLE
Logging out in espanol redirects to english home page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41898] opened 2021-04-22 18:36 UTC
If I am signed in as a user while on freecodecamp.org/espanol and log out, I am redirected to the english home page. chinese.freecamp.org redirects to the chinese page.

**Comment by JustinSingleton303** [comment] 2021-04-22 21:31
wrong endpoint in server code?  Thats what I would assume, but am not sure how to locate where the correct endpoint would be placed in the code.

**Comment by raisedadead** [comment] 2021-04-23 07:38
Here is the endpoint:

https://github.com/freeCodeCamp/freeCodeCamp/blob/73e5c4d935578e76c01e0248a7e6d042c99fb52b/api-server/src/server/boot/authentication.js#L70-L84

and most likely the issue is with the redirect "predictor" utility:

https://github.com/freeCodeCamp/freeCodeCamp/blob/73e5c4d935578e76c01e0248a7e6d042c99fb52b/api-server/src/server/utils/redirection.js#L61-L71

However we would want @ojeytonwilliams to confirm the cause before we open this up for contributions.

**Comment by ojeytonwilliams** [comment] 2021-04-23 09:31
@raisedadead yes, that's the issue.  To fix it we can grab the `pathPrefix` from `getRedirectParams` and combine that with `origin` to get the desired redirect.

**Comment by JustinSingleton303** [comment] 2021-04-23 17:56
Should that be done in the getRedirectParams function or should the path be put together from the data set returned by getRedirectParams in api.get?

**Comment by raisedadead** [comment] 2021-04-23 18:01
You need to construct the URL from the values you get from the `getRedirectParams` as a consumer of the function and not change its existing behavior. In simple terms the change is required within the endpoint handler.

**Comment by JustinSingleton303** [comment] 2021-04-23 18:46
That makes sense.

**Comment by JustinSingleton303** [comment] 2021-04-24 03:52
I got the codebase installed locally is there a way to run just authentication.js?

**Comment by raisedadead** [comment] 2021-04-24 12:21
Not sure what you mean by running only one file? 

The API server is an express based application (Loopback 3). You need to start up at least the api-server app. If you want to do that, you should be able to do that by navigating to `api-server` directory and using the run-script commands in its package.json

**Comment by JustinSingleton303** [comment] 2021-04-24 20:16
I'm trying to figure out what gets passed in pathPrefix, from getRedirectParams, when one signs out from the Spanish page. But when running the site locally, switching to Espanol leads to a "This site can't be reached" error. 

Just for clarity's sake, I realize now that authentication.js is not meant to be run alone and I am using the "npm run develop" command to try and recreate this bug locally.  Is this a bad approach?

**Comment by raisedadead** [comment] 2021-04-26 11:07
Ah - right. Sorry about sending you on a goose-chase.

When you build locally, we do not have a way yet to **develop** both `english` and `espanol` at the same time alongside the API app.

I am going to untag this from help-wanted and assign this @ojeytonwilliams instead. 

Oliver, you should be able to test / reproduce and recommend a fix on our staging instance - not sure because this may be needing access for "close to prod" type setup.

**Comment by ojeytonwilliams** [comment] 2021-04-26 11:15
I was just in the process of going through the steps, when you commented Mrugesh!  I'll leave them here for the curious:

Unfortunately testing locally is quite a pain, because we use [pathPrefix](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/) since `/espanol/learn` is entirely separate from `/learn`.

It's a bit of a slow, memory intensive process, but you can do this:

1. set `CLIENT_LOCALE=espanol` in your .env file
2. `npm run build`
3. `npm run develop:server &`
4. `cd client && npx gatsby serve -p 8000 --prefix-paths`

Then you can go to `http://localhost:8000/espanol/settings/`

**Closed** 2021-06-17 18:24 UTC
Labels: platform: api, type: bug
