### ISSUE TITLE
Error on practice HTML5 and CSS -> 17. Waypoint: Size your Images

### ISSUE THREAD

**Issue by vigyanhoon** [FreeCodeCamp/FreeCodeCamp#3378] opened 2015-09-20 17:04 UTC
Challenge [Waypoint: Add Borders Around your Elements](http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

problem url: http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements

passes every test except:
Give your image a border width of 10px.

Tried hard refresh, opening in new browser etc.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
    
  }
  
  .thick-green-border{
    border-color: green;
    border-style: solid;
    border-width: 10px;
  }
  

</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by bugron** [comment] 2015-09-20 17:08
@vigyanhoon thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3204 so I'll close it. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-20 17:08 UTC
