### ISSUE TITLE
Receiving credit for already completed lesson

### ISSUE THREAD

**Issue by jrg626** [FreeCodeCamp/FreeCodeCamp#3288] opened 2015-09-14 01:49 UTC
I went back to complete some of the new challenges in html/css and jquery sections that were added with the most recent update. When I complete the challenge and click to next, it takes me to a lesson I have already completed (next in line on the map) rather than the next incomplete lesson and gives me credit (items completed number in the corner) for doing it again. 

Issue: I am getting credit for lessons I have already completed in past when I do them again.

**Comment by bugron** [comment] 2015-09-14 04:11
@jrg626 thanks for posting this issue!
Yes, this is a problem. Anyway, I'll close this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3009, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-14 04:11 UTC
