### ISSUE TITLE
Waypoint: Increment a Number with Javascript

### ISSUE THREAD

**Issue by HoBi** [FreeCodeCamp/FreeCodeCamp#5631] opened 2015-12-31 09:43 UTC
Challenge [Waypoint: Increment a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++; 
```

This code returns `87`, but in test is number `88`, for which works `myVar = ++myVar;`, but that does not pass "Use the ++ operator".

**Comment by Mr-Kumar-Abhishek** [comment] 2015-12-31 10:46
This is conceptually same as #5632

**Comment by ltegman** [comment] 2015-12-31 18:12
Closing as a duplicate of #5632. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 18:12 UTC

**Comment by anyacoleman** [comment] 2016-09-06 15:39
myVar = myVar++;  // did nor work
myVar ++; // This is work

**Comment by egossick** [comment] 2016-10-28 18:55
Here is the correct solution:
var myVar = 87;

// Only change code below this line
myVar++;

**Comment by texas2010** [comment] 2016-10-28 18:58
@egossick 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
