### ISSUE TITLE
style element created but not able to finish task

### ISSUE THREAD

**Issue by arulchellappa** [FreeCodeCamp/FreeCodeCamp#4827] opened 2015-12-01 04:21 UTC
style element created but not able to finish task

**Comment by ltegman** [comment] 2015-12-01 04:57
Please more details, like which challenge you are working on and what your code looks like.

**Comment by ltegman** [comment] 2015-12-01 05:26
Closing as a duplicate of #4833. Please continue further discussion in that thread.

Thanks and happy coding!

**Closed by ltegman** 2015-12-01 05:26 UTC
Labels: blocked
