### ISSUE TITLE
Profile shows longest streak from 2017 and not from current year.

### ISSUE THREAD

**Issue by d4mer** [freeCodeCamp/freeCodeCamp#17743] opened 2018-06-28 07:11 UTC
#### Describe your problem and - if possible - how to reproduce it
On my public profile, the longest streak calendar is from 2017 and not the current month/year.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/d4mer

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 10

#### If possible, add a screenshot here

![ffc](https://user-images.githubusercontent.com/6909228/42018739-475542cc-7ab3-11e8-9db7-f97fb71ecdda.PNG)

**Comment by conradkay** [comment] 2018-07-01 03:16
Confirmed to have happened on all OS's and browser version.

**Comment by lalov1** [comment] 2018-07-24 20:43
@d4mer Is your profile locked down? I can't view it.

**Comment by dianadonisa** [comment] 2018-07-25 11:31
Describe your problem and - if possible - how to reproduce it
On my public profile, the longest streak calendar is from 2016 and not the current month/year.

Add a Link to the page with the problem
https://www.freecodecamp.org/diamaria

Tell us about your browser and operating system
Browser Name: Chrome
Browser Version:
Operating System: Windows 10

If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/5104677/43198420-df5695c4-900e-11e8-953b-7cb46925fa0c.png)

**Comment by d4mer** [comment] 2018-07-25 12:04
It should be public. But Ill check it and correct if necessary

**Comment by d4mer** [comment] 2018-07-25 12:52
It is now public

**Comment by avjgit** [comment] 2018-08-08 18:57
Same here: https://www.freecodecamp.org/avjgit
Shows 7 days streak from 2016, and now in 2018 it is 10 day streak.
Any chances for this to be fixed?

**Comment by avjgit** [comment] 2018-08-09 18:48
Looks like this is the code: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/account/show.jade

And calendar start is set to today - 150 days:
`                        start: new Date().setDate(new Date().getDate() - 150),`

**Comment by RandellDawson** [comment] 2019-02-22 10:01
Closing this issue as it is a duplicate of issue #17822 which is being used as the single source for this issue.  Please make further inquiries there.

**Closed by RandellDawson** 2019-02-22 10:01 UTC
