### ISSUE TITLE
"Target the Parent of an Element Using jQuery" challenge is running jQuery twice

### ISSUE THREAD

**Issue by ronaldo127** [FreeCodeCamp/FreeCodeCamp#7224] opened 2016-02-24 17:52 UTC
The following link is running its jQuery twice: http://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery

#### Issue Description
* It happens when I load it first time. Looking at my screenshot you can notice that there are 3 target5
* For reproduction of this bug you just need open this link

#### Browser Information
* FirefoxESR, 31 ESR
* Windows 7 enterprise, Service Pack 1

#### Your Code

```js
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");

  });
</script>

<!-- Only change code above this line. -->

<body>
  <div class="container-fluid">
    <h3 class="text-primary text-center">jQuery Playground</h3>
    <div class="row">
      <div class="col-xs-6">
        <h4>#left-well</h4>
        <div class="well" id="left-well">
          <button class="btn btn-default target" id="target1">#target1</button>
          <button class="btn btn-default target" id="target2">#target2</button>
          <button class="btn btn-default target" id="target3">#target3</button>
        </div>
      </div>
      <div class="col-xs-6">
        <h4>#right-well</h4>
        <div class="well" id="right-well">
          <button class="btn btn-default target" id="target4">#target4</button>
          <button class="btn btn-default target" id="target5">#target5</button>
          <button class="btn btn-default target" id="target6">#target6</button>
        </div>
      </div>
    </div>
  </div>
</body>

```

#### Screenshot
![sem titulo2](https://cloud.githubusercontent.com/assets/1185943/13295119/12a0c15e-db06-11e5-886b-e74b390970a6.png)

**Comment by eshacker** [comment] 2016-02-24 20:03
It's reproducible in FireFox ESR 38.6.0 too.

**Comment by sludge256** [comment] 2016-02-24 20:08
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072

**Closed by sludge256** 2016-02-24 20:08 UTC
