### ISSUE TITLE
[beta] Challenge word-blanks has an issue - Tests not defined

### ISSUE THREAD

**Issue by khamp19** [freeCodeCamp/freeCodeCamp#14630] opened 2017-04-28 10:05 UTC
Code preview at left showing: "test1 is not defined" "test2 is not defined". Code printed to browser console completes challenge.

Challenge [word-blanks](http://beta.freecodecamp.com/en/challenges/basic-javascript/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result = "In other news " + myAdjective + ' ' + myNoun + ' ' + "today " + ' ' + myVerb + ' ' + myAdverb;
  console.log(result);

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by minukumari** [comment] 2017-04-28 13:00
![word blanks](https://cloud.githubusercontent.com/assets/26218290/25529685/c17ddb9e-2c40-11e7-867d-c3fdde9802dc.PNG)

**Comment by texas2010** [comment] 2017-04-28 15:18
@minukumari 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by JBallin** [comment] 2017-05-31 18:54
I tested (copied exact code) on Safari, Chrome, and Firefox on my Mac and couldn't reproduce your issue.

My output:
```
// running test
// tests completed
```

I vote to close this issue unless @khamp19 can provide further evidence. Screenshot?

**Comment by rossfaarley** [comment] 2017-06-12 14:38
I had exactly the same issue. Reloading fixed it

**Comment by QuincyLarson** [comment] 2018-06-03 13:55
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Closed by QuincyLarson** 2018-06-03 13:55 UTC
Labels: beta
