### ISSUE TITLE
JQuery pages won't run

### ISSUE THREAD

**Issue by grntlngdn** [FreeCodeCamp/FreeCodeCamp#3142] opened 2015-09-07 04:08 UTC
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue.
Each page of JQuery is starting with the phone blank, and the section where the objectives are checked off doesn't appear (and pressing run makes no difference). Running the correct code (I assume) to complete the objectives doesn't change this. Deleting the script and pressing run allows the phone to fill in and the objectives section to appear. The appearance of the phone doesn't change once you add back the script and run again, but the objectives disappear. In no case is feed back given upon pressing run.
[screen shots 1-3](http://imgur.com/a/Hehwz).

**Comment by grntlngdn** [comment] 2015-09-07 04:30
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3143

**Comment by bugron** [comment] 2015-09-07 17:12
@grntlngdn thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-07 17:12 UTC
