### ISSUE TITLE
Can't Pass Challenge: Specify How Fonts Should Degrade

### ISSUE THREAD

**Issue by BananaCustard** [FreeCodeCamp/FreeCodeCamp#11657] opened 2016-11-14 19:48 UTC
#### Challenge Name
Specify How Fonts Should Degrade

#### Issue Description
The challenge asks to comment out the call to Google Fonts to degrade fonts from Lobster to Monospace. My h2 element is correct (I've compared it to other people's code after searching the issue) yet it won't let me pass. My h2 element is formatted just like the example CSS style.

I've tried refreshing/resetting, clearing my cache and cookies, disabling extensions, and running in private mode but nothing has worked so far.

#### Browser Information

* Browser Name, Version: Mozilla Firefox v. 49.0.2
* OS: Ubuntu 16.04 LTS (64bit)
* Desktop

#### My Code

```
<!--
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

#### Screenshot
![screenshot from 2016-11-14 14-18-10](https://cloud.githubusercontent.com/assets/16827617/20279276/e5c2d0e2-aa75-11e6-93ac-ced939e000c5.png)

**Comment by IsaacAbrahamson** [comment] 2016-11-14 22:02
Your code works for me. Are you getting any errors in the console?

Can anyone else reproduce?

**Comment by miljkovicmisa** [comment] 2016-11-14 22:10
have you tried putting Lobster in single quotes? Maybe it is a validation bug for a specific device/browser pair?

**Comment by BananaCustard** [comment] 2016-11-14 23:46
I just tried on a Windows machine w/ Firefox and it worked.

There weren't any console errors I was aware of when I used Ubuntu but I'll check again in a few hours before I close the topic. It's strange and I'd like to try to figure out the problem in case it happens again.
Every previous challenge had worked perfectly fine.

**Comment by IsaacAbrahamson** [comment] 2016-11-14 23:56
@BananaCustard, try the exercise somewhere else, maybe CodePen, to see if you can recreate the issue.

Instead of using
`<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">`
try using this:
`<link href="//fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">`
or
`@import url(http://fonts.googleapis.com/css?family=Lobster);
Tell us if any of those work. Try using Google chrome and see if it works, it may be a bug with firefox on linux:
https://support.mozilla.org/en-US/questions/958143?page=1
https://bugzilla.mozilla.org/show_bug.cgi?id=857922

**Comment by Abhar10** [comment] 2016-11-16 22:24
Your code works fine for me in chrome.

**Comment by ChaituVR** [comment] 2016-11-17 05:23
Your code works for me in FireFox 49.0.2 in Ubuntu 14.04

**Comment by Deejavum** [comment] 2016-11-19 23:14
Same problem @BananaCustard Did you pass the challenge?

**Comment by raisedadead** [comment] 2016-11-24 13:25
Unless  confirmed as reproducible, please do not label otherwise. 
Refer: https://forum.freecodecamp.com/t/free-code-camp-issue-labels/19556

**Comment by IsaacAbrahamson** [comment] 2016-11-24 17:29
@raisedadead Thanks for correcting me, I am still trying to learn GitHub properly.

**Comment by raisedadead** [comment] 2016-11-27 14:52
Closing as not reproducible. 

@BananaCustard can you confirm again if this is still causing an issue? Do you have the font installed locally on your machine? If yes, then uninstalling and trying the issue should be a work around. Let us know how it goes.

**Closed by raisedadead** 2016-11-27 14:52 UTC
