### ISSUE TITLE
when going to the next challenge

### ISSUE THREAD

**Issue by mjohnson24** [FreeCodeCamp/FreeCodeCamp#9488] opened 2016-07-01 14:22 UTC
When im going to the next challenge and have to type in the note pad document, i cant click the cursor and start typing where it wants me to. i have to hit enter or something first then the cursor will allow me to click anywhere in the document to start typing my challenge.

Challenge [Create a Set of Radio Buttons](https://www.freecodecamp.com/challenges/create-a-set-of-radio-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

```

**Comment by atjonathan** [comment] 2016-07-01 14:25
Duplicate of #7847, please follow the discussion there.

**Closed by atjonathan** 2016-07-01 14:25 UTC
