### ISSUE TITLE
Free code camp question:Only add one class with each of your three selectors.<bug>

### ISSUE THREAD

**Issue by gracexu222** [freeCodeCamp/freeCodeCamp#13844] opened 2017-03-10 21:18 UTC
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
  $("button").addClass("animated");
  $(".btn").addClass("shake");
  $("#target1").addClass("btn-primary");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by OFFLlNE** [comment] 2017-03-10 21:55
@gracexu222 Thank you for reporting the issue
Here are a couple suggestions:
1.Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2.Try the challenge in incognito mode. A plugin might be interfering with the tests.
3.Try the challenge in a different browser. There may be an issue with your version of browser.
Please try these things in order and let us know what did and didn't work. I can't reproduce your issue right now, so any extra information will be helpful in finding out what's causing your issue.

If You won't reply in 24 hours if it helped, then I will close this issue ;)

**Comment by erictleung** [comment] 2017-03-10 23:06
@gracexu222 thanks for the issue. Your code passes. Can you elaborate on what the bug is with that challenge test?

**Closed** 2017-03-13 23:33 UTC
Labels: blocked
