### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by claudiocoding** [freeCodeCamp/freeCodeCamp#12735] opened 2017-01-22 14:09 UTC
Challenge [create-a-media-query](https://beta.freecodecamp.com/en/challenges/responsive-web-design/create-a-media-query) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0</code>.

i get  the following error message: "Your p tag should have the font-size of 10px when the device height is smaller than 800px."

```html
    
    
<style>
@media (max-height: 800px) { 
  p {font-size: 10px;}
}
</style>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>

    ```

**Comment by systimotic** [comment] 2017-01-22 14:17
Hi @claudiocoding! Thank you for reporting this issue.

It looks like this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/10749. 
That means that your code is correct, but we have an issue where CSS tests don't work in Firefox. You should be able to pass the challenge with the same code in a different browser.

Happy coding!

**Closed by systimotic** 2017-01-22 14:17 UTC
