### ISSUE TITLE
Replace Tic Tac Toe example

### ISSUE THREAD

**Issue by mindwars** [FreeCodeCamp/FreeCodeCamp#5437] opened 2015-12-24 10:53 UTC
This http://codepen.io/alex-dixon/full/JogOpQ/ example doesnt fullfill user stories, i can beat the game.

Here, I'm the 'x' one.
![screenshot_1](https://cloud.githubusercontent.com/assets/4236131/11993741/477ca3d8-aa3d-11e5-91cb-1d1642d66cff.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4236131/11993745/4bec0468-aa3d-11e5-8970-66ef69c872fb.png)

**Comment by wakqasahmed** [comment] 2015-12-27 07:56
I agree to this.. Here is another scenario (I am also 'x')

<img width="1280" alt="screen shot 2015-12-27 at 11 52 23 am" src="https://cloud.githubusercontent.com/assets/4486133/12009448/c83e776c-ac90-11e5-878e-da37574fab5c.png">

**Comment by ltegman** [comment] 2015-12-27 18:17
Confirmed. If anyone has a completed version of this zipline that fulfills the user story they would like to volunteer I think it should be swapped out.

**Comment by chrisdziewa** [comment] 2015-12-30 18:13
@ltegman you can use mine if you'd like, although I'm not sure if you want the extra features on there. [My tic tac toe game](http://codepen.io/chrisdziewa/full/dYKaGJ/)

**Comment by denmch** [comment] 2016-01-08 07:17
Just a note that this is a little unfair to Alex's Zipline since it was originally a "Bonus User Story." At some point (fairly recently?) the text was modified.

**Comment by erictleung** [comment] 2016-04-17 17:22
@denmch is right. The user story for the challenge is different that what is in the video. This has been noted several times before in #7186 and #5294. I'm not sure what we plan on doing to account for the updates in the site.

/cc: @FreeCodeCamp/issue-moderators

**Comment by BerkeleyTrue** [comment] 2016-08-15 03:13
I've updated this issue. It is clear that this version has a lot of faults. We need a new version to replace this one.

**Comment by BerkeleyTrue** [comment] 2016-08-18 21:44
@erictleung Have you taken a look at http://codepen.io/chrisdziewa/full/dYKaGJ/ as a replacement?

**Comment by erictleung** [comment] 2016-08-20 07:23
@BerkeleyTrue looks good to me 👍 

@raisedadead I think you have access to the FCC codepen? Can we use http://codepen.io/chrisdziewa/full/dYKaGJ/ as the example game?

**Comment by raisedadead** [comment] 2016-08-20 15:04
@BerkeleyTrue and @erictleung updated the official pen. Closing as resolved. Thanks.

**Closed by raisedadead** 2016-08-20 15:04 UTC
Labels: codepen, confirmed, help wanted
