### ISSUE TITLE
Code Editor issues

### ISSUE THREAD

**Issue by sophiaelisa** [FreeCodeCamp/FreeCodeCamp#2248] opened 2015-08-20 00:00 UTC
<img width="1248" alt="screen shot 2015-08-19 at 4 55 58 pm" src="https://cloud.githubusercontent.com/assets/11863735/9372439/4dc233ce-4693-11e5-8307-886f53602bff.png">

Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I entered my comments into the code editor, however, the left panel is responding by pretty much telling me my code has an error. I don't see anything wrong with my line of code, and this is also the first time that the left panel has said why my code is incorrect, which I've noticed that it never had mentioned reasons for any of my code errors in my code editor in the previous lessons.

**Comment by keodren** [comment] 2015-08-20 05:02
I had the same issue. 
I went back to "Map" and click around a bit, and then back into this 'waypoint' and it just showed it as successful without doing anything.

**Comment by BerkeleyTrue** [comment] 2015-08-21 04:04
Closing as duplicate of #2137

**Closed by BerkeleyTrue** 2015-08-21 04:04 UTC
