### ISSUE TITLE
$($) kills page.  reloading doesn't fix.

### ISSUE THREAD

**Issue by FaithKent** [FreeCodeCamp/FreeCodeCamp#2395] opened 2015-08-21 06:40 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When typing the solution, typing "$" "(" automatically generates a closing parenthesis, then typing the next "$" leaves "$($)" in the window, which is executed automatically, and freezes the page.  From the behavior, I would assume an infinite loop.  Copy-pasting the code suggestion bypasses the issue.

Reloading the page, once the error has occurred, reloads the problematic code -- there is no user-accessible way to force a reset when the page isn't responding

**Comment by MyganAshton** [comment] 2015-08-21 08:29
I think I just did the same thing.  :(   Darn!

**Comment by benschenker** [comment] 2015-08-21 14:19
Hey thanks for posting this!

Take a look at #2286 as this is the main thread for this issue.

You may need to clear your cache.

**Comment by jbmartinez** [comment] 2015-08-21 21:23
Duplicate of #1960

**Closed** 2015-08-21 21:59 UTC
