### ISSUE TITLE
cannot scroll down in the "Map" during a lesson.

### ISSUE THREAD

**Issue by eduedix** [FreeCodeCamp/FreeCodeCamp#7162] opened 2016-02-20 12:51 UTC
#### Issue Description
* When Issue Happens
When I want to scroll down in the Map during a lesson.
* Steps To Reproduce
1. Open a lesson.
2. Click Map
3. Try to scroll down.

#### Browser Information
* Browser Name, Version
Safari 9.0.3
* Operating System
OSX 10.11.3

**Comment by AkiraLaine** [comment] 2016-02-21 01:30
I can scroll through the Map while doing a challenge.

Could you tell us which challenge specifically? I don't think it's the challenge itself, but rather system/browser related. (What browser are you using?)

**Comment by hallaathrad** [comment] 2016-02-21 01:39
I can chip in here... This is a known issue. The issue was created by the way we've solved the same issue for ipads (which are entirely unusable otherwise) I'm trying to solve it a.s.a.p. but meanwhile you can use a different browser and get by. Thus, I guess we can close it as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7088.

**Closed by hallaathrad** 2016-02-21 01:39 UTC
