### ISSUE TITLE
An error after finishing any challange

### ISSUE THREAD

**Issue by saeidalidadi** [FreeCodeCamp/FreeCodeCamp#7056] opened 2016-02-16 04:43 UTC
Every time that I finish a challenge, I go back to the page of my profile emmediatly and face with this error message:
Oops! Something went wrong. Please try again later.

**Comment by sludge256** [comment] 2016-02-16 04:45
Duplicate of #6958 
Thanks for the report.

**Closed by sludge256** 2016-02-16 04:45 UTC
