### ISSUE TITLE
Can't complete Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by storbeck** [FreeCodeCamp/FreeCodeCamp#5566] opened 2015-12-30 19:07 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%2010%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 10;
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction


// now remove the console.log line to pass the test


```

This is returning `undefined` with error `Remove the second console log` but it seems the code is correct

**Comment by ltegman** [comment] 2015-12-30 19:09
Closing as a duplicate of #5559. Thanks and happy coding!

**Closed by ltegman** 2015-12-30 19:09 UTC
