### ISSUE TITLE
Does not accepts correct answer

### ISSUE THREAD

**Issue by sqro2** [freeCodeCamp/freeCodeCamp#10611] opened 2016-09-09 17:42 UTC
Challenge [write-reusable-javascript-with-functions](https://www.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

`````` js




// Example
function ourReusableFunction() {
console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction(){
console.log("Hi World");
}
reusableFunction();


    ```
Dev console outputs "Hi World" .But code is not being accepted.
![bug-0](https://cloud.githubusercontent.com/assets/21281781/18396837/2c859c10-76e3-11e6-8d7d-766a25d8a0f1.PNG)

``````

**Comment by Axfinity** [comment] 2016-09-09 17:46
![bug-0](https://cloud.githubusercontent.com/assets/21281781/18396871/5a966c24-76e3-11e6-8b7b-023c324fa043.PNG)

**Comment by ArielLeslie** [comment] 2016-09-09 17:46
![image](https://cloud.githubusercontent.com/assets/6234475/18396846/d92bcf04-7682-11e6-8ac7-5f8bfd874f97.png)

Code passes in Chrome.
I suspect that this is another instance of the Firefox issue. #10595

**Comment by Axfinity** [comment] 2016-09-09 17:47
the funny thing is that right now im using chrome and not working

**Comment by Axfinity** [comment] 2016-09-09 17:47
see my user agent info

**Comment by Axfinity** [comment] 2016-09-09 17:52
and why each of the functions is executed twice in your case?

**Comment by dhcodes** [comment] 2016-09-09 17:55
@Axfinity thanks for the issue. I have not been able to replicate it; it passes in Chrome. I'll leave it open so others can test it.

As to why the functions are executed twice, it's because the code in the editor is executed for each test.

**Comment by Axfinity** [comment] 2016-09-09 17:58
all right. Im gonna try in opera now

**Comment by Dave1089** [comment] 2016-09-09 18:00
Code passes fine in the Chrome!

**Comment by Axfinity** [comment] 2016-09-09 18:00
works perfectly in opera.Something wrong with my chrome version i guess

**Comment by kennyklee** [comment] 2016-09-09 18:08
It fails for me in Chrome as well.

Chrome Version 52.0.2743.116 (64-bit)
Mac El Capitan 10.11.6

http://d.weblife.us/rxQm

**Comment by kennyklee** [comment] 2016-09-09 18:13
Weird, I deleted the code, re-typed, and started working.  I mucked around, copy/pasted code, and it started failing again.

I can't reproduce an consistent pattern.

**Comment by Axfinity** [comment] 2016-09-09 18:15
this is just weird

**Comment by kennyklee** [comment] 2016-09-09 18:16
I think it has something to do with the test suite.  Look how many times the tests are running now.

![screen shot on 2016-09-09 at 11-15-28](https://cloud.githubusercontent.com/assets/1432489/18397847/d541dad6-767e-11e6-906f-e94292e88692.png)

**Comment by Axfinity** [comment] 2016-09-09 18:20
here is another one- I don't see anything wrong with these codes either.Output correct values but does not consider as correct answer-
![bug-1](https://cloud.githubusercontent.com/assets/21281781/18397940/1af39bb4-76e8-11e6-9a67-af00a58ef6db.PNG)

**Comment by kennyklee** [comment] 2016-09-09 18:41
I am seeing failed tests elsewhere as well.  All points to test suite.

**Comment by Binkythebomb** [comment] 2016-09-09 20:29
I've had both the issues listed above, in teh case of the Reusable Functions, try putting the whole thing on one line, then seperate each section with a fresh carraige return (it worked for me, removed a few unseen spaces).
Also, try using the browsers console (F12) and take a look at the JS tab. If it's working there then it's a Dev Console bug.  Best to just save your work and move onto the next.

**Comment by northless** [comment] 2016-09-09 23:22
Heys, yep, your solution of removing the spaces solved my issue.....something is faulty with the test case anyway.
The same code that failed then was a pass after removing the spaces. 
Cheers for that tip!
--> // Only change code below this line
function reusableFunction(){console.log("Hi World");}
reusableFunction();

**Comment by QuincyLarson** [comment] 2017-01-04 06:26
@kennyklee @northless @Binkythebomb @sqro2 would any of you be interested in trying to improve the tests for this challenge to prevent this from happening?

**Comment by kennyklee** [comment] 2017-01-04 06:40
@QuincyLarson If the man himself reaches out, I'm going to say yes. 👍  My day job is running a startup (product side, no coding), but I would say I'm intermediate level with JS.  Any tips on how to get started..specifically around tests?

**Comment by QuincyLarson** [comment] 2017-01-05 04:32
@kennyklee awesome! Thrilled to have your help with this. Please let me know if I can answer any questions about this, and yes - the contributors chat room is the best place to get help.

**Comment by dhcodes** [comment] 2017-08-02 16:44
I've revisited this on Chrome and Firefox, using various line-breaks and it seems to be working. Closing for now; please reopen if this is still an issue.

**Closed by dhcodes** 2017-08-02 16:44 UTC
Labels: discussing

**Comment by ArielLeslie** [comment] 2018-09-10 19:39
@devcshort The problem that you are running into is a new one, unrelated to this Issue. As of 09/10/18 there appears to be an issue with all challenges which require a `console.log()` statement.

**Comment by devcshort** [comment] 2018-09-10 19:53
@ArielLeslie Sorry about that!  I'll take a look at the new issue. Thank you
