### ISSUE TITLE
[beta] challenge passes without any code

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#12864] opened 2017-01-26 05:26 UTC
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-flexdirection-property-to-make-a-row

#### Issue Description

I guess since the default value for `flex-direction` is row, this test can pass without doing anything at all. Maybe a reg-ex is in order to make sure the user enters code?

**Comment by ajain17** [comment] 2017-01-26 16:20
Confirmed its an issue. Needs to be fixed.

**Comment by ajain17** [comment] 2017-01-26 16:23
Should I create a PR? I fixed it on my local

**Comment by HKuz** [comment] 2017-01-26 19:15
@no-stack-dub-sack, I'm reviewing and consolidating all the Flexbox section issues now. This looks like a duplicate of #12814 - so I'm going to close this issue. I'll put all the action items over in issue #12803 ( @ajain17 - see [my comment here](https://github.com/freeCodeCamp/freeCodeCamp/issues/12868#issuecomment-275481639) about adding to your PR 😄)

**Closed by HKuz** 2017-01-26 19:15 UTC
Labels: beta

**Comment by ajain17** [comment] 2017-01-26 19:18
@HKuz Sure. Could you give me links to all the issues I should be addressing in my pr? I see that even issue https://github.com/freeCodeCamp/freeCodeCamp/issues/12864 is caused by same thing.

**Comment by no-stack-dub-sack** [comment] 2017-01-27 05:59
@HKuz - thanks for pointing out the duplicate, I ran a search too before opening this but didn't find it - wow, with all these issues things are getting a bit difficult to keep track of - you're doing a great job with this! Perhaps we can consolidate all the recent issues opened on flex box challenges into your issue and close those to to clean up the tracker a bit?

**Comment by HKuz** [comment] 2017-01-27 16:17
@no-stack-dub-sack - no worries, that original one had a generic name making it hard to find. I only noticed it because I was consolidating the Flexbox issues to try and fix a bunch at once. There's an open PR from @ajain17 that I plan to look at today, which should close most of them and clean up the tracker a little. But agreed, my head is spinning trying to stay on top of and keep track of everything!
