### ISSUE TITLE
Iterate with JavaScript For Loops has no for loop in the initial code

### ISSUE THREAD

**Issue by snowy73** [FreeCodeCamp/FreeCodeCamp#2032] opened 2015-08-18 07:33 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. The initial code has a comment as `//...using a "for loop" like above.` but there is no for loop in the initial code. Please add the for loop example on the left panel to the above of the initial code.

**Comment by bugron** [comment] 2015-08-22 22:35
That example is already provided A few lines above than Run code button's position. Do you see that pink text, that's it.

**Comment by benschenker** [comment] 2015-08-23 05:29
Hey @snowy73 thanks for posting a bug report!

This looks like a duplicate of #2444 which looks like it was fixed in e33a929.  I still see the issue in my browser, but I am assuming the merged fix has just not yet been deployed to production.

Please see our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for any future issues.

**Closed** 2015-08-24 18:24 UTC
