### ISSUE TITLE
A Link in Missing Letters Module Does Not Show Actual Reference

### ISSUE THREAD

**Issue by albert2309** [FreeCodeCamp/FreeCodeCamp#8453] opened 2016-05-04 14:07 UTC
#### Challenge Name

[Missing Letters](https://www.freecodecamp.com/challenges/missing-letters)

#### Issue Description

The  String.charCodeAt() link does not direct users to [actual link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) as you can see from the provided screenshot on the right side. 

#### Browser Information

* Browser Name, Version: Chrome Version 49.0.2623.112
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

http://imgur.com/xu2mmNq

**Comment by raisedadead** [comment] 2016-05-04 14:59
Duplicate of #8423 
Fixed in #8425

**Comment by raisedadead** [comment] 2016-05-04 15:00
This has been fixed and will soon reach the Main Website. Sorry for the inconvenience!

**Closed by raisedadead** 2016-05-04 14:59 UTC

**Comment by albert2309** [comment] 2016-05-04 16:03
@raisedadead  It's okay! I should have searched the issue first. Thanks for responding!
