### ISSUE TITLE
Code editor issue after the new update

### ISSUE THREAD

**Issue by Utkarsh9714** [freeCodeCamp/freeCodeCamp#57114] opened 2024-11-10 07:13 UTC
### Describe the Issue

Unable to use the code editor on freeCodeCamp's website. I was doing course of "Javascript Algorithms and Data Structures (beta) Certification". Once after the website is updated, I am unable to see my code editor on my screen. I am using a regular laptop screen. 

### Affected Page

[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/](url) 

### Steps to Reproduce

1. Go to the given URL.
2. Click on any project
3. Once the project is loaded I didnt found any code editor, I guess same will happen with you ppl

### Expected behavior

The expected behavior is the normal working of website as it was before the update. 

### Screenshots

![Image](https://github.com/user-attachments/assets/979fc717-a809-4192-8a3e-7d3e21e74416)
Same happens with the project certificates:
![Image](https://github.com/user-attachments/assets/57938fb1-c971-4a55-ae94-aeb895a4dfa1)

### System

- Device: Laptop Sony Vaio
- OS: Linux lubuntu 22.04
- Browser: Chrome
- Version: 125.0.6422.60 (Official Build) (64-bit)

**Comment by gikf** [comment] 2024-11-10 08:06
Do you have any browser extensions that might affect this? Are there any errors in the browser's console? Could you try different browser?

**Comment by YETI1064** [comment] 2024-11-17 10:43
I didn’t find any issue, maybe you are using older version of browser. I tried to figure out this issue but didn’t found any.
I am using Version 130.0.6723.92 (Official Build) (arm64).

**Comment by Sembauke** [comment] 2024-11-18 09:21
![Image](https://github.com/user-attachments/assets/84275c94-2113-4020-a7a2-acaa09bdf39d)
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-14
I can produce some kind of issue on the above step. @gikf  could you confirm?

**Comment by gikf** [comment] 2024-11-18 09:32
> I can produce some kind of issue on the above step. [@gikf](https://github.com/gikf) could you confirm?

Empty space on the right, when preview is turned off, yes - [Image](https://github.com/user-attachments/assets/ea771e4f-b088-4c83-a8f4-693242306916).
Missing editor - no.

**Comment by Sembauke** [comment] 2024-11-19 07:13
Closing this as can't reproduce, and opening an issue for the above.

**Closed** 2024-11-19 07:12 UTC
Labels: status: waiting triage
