### ISSUE TITLE
"Get set for our algorithm challenges" overview page does not progress. Link is broken.

### ISSUE THREAD

**Issue by jdbarras** [FreeCodeCamp/FreeCodeCamp#10692] opened 2016-09-10 22:19 UTC
#### Challenge Name
Get set for our algorithm challenges

#### Issue Description
This isn't a challenge, it is just the overview/instruction page for basic-algorithm-scripting. It loads page 1/4 but the "Go to my next step" button is broken so you cannot navigate to pages 2, 3, and 4. You have to just skip to the first challenge. That means you don't get that satisfying green checkbox on the map. 

Tested with Chrome and IE

**Comment by P1xt** [comment] 2016-09-10 22:37
I think this might be a duplicate. I confirmed similar behavior on this bug that was reported a while ago:

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10688

**Comment by ltegman** [comment] 2016-09-11 01:38
Closing as a duplicate of #10688. @jdbarras could you please let us know in that thread if clearing your browser cache solves the issue for you?

**Closed by ltegman** 2016-09-11 01:38 UTC

**Comment by jdbarras** [comment] 2016-09-11 14:25
@ltegman not sure as it simply worked today without any action being taken. I don't know if clearing the cache would have worked yesterday though because when it didn't work on Chrome I tried it on IE, which I haven't ever used on codecamp with the same result. 

In any case it's working now, thanks.
