### ISSUE TITLE
show the weather:  'public' api key use

### ISSUE THREAD

**Issue by eghan** [freeCodeCamp/freeCodeCamp#15320] opened 2017-06-11 20:11 UTC
I was able to solve this, without using a private API key in a public space, by using--

https://forecast.weather.gov/MapClick.php?lat=" + position.coords.latitude + "&lon=" + position.coords.longitude + "&unit=0&lg=english&FcstType=json"

If others can verify that this works broadly and still fulfills  project goals, perhaps this can be changed in the master description which currently asks you to get a private API key and then use it in public space.

I'd make the change myself, but I'm not sure that I'm correct.

#### Challenge Name

https://www.freecodecamp.com/challenges/show-the-local-weather

#### Issue Description

the use of private API keys in public space.

#### Browser Information

* Browser Name, Version: Chrome, Version 58.0.3029.110 (64-bit)
* Operating System:  Windows 7 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

https://codepen.io/Eghan/pen/owbyoP

**Comment by raisedadead** [comment] 2017-06-11 21:55
@eghan awesome work! Thanks a lot for looking into this. @freeCodeCamp/moderators can any check if this is a good solution too? I'll confirm as well soon.

@Marmiz Maybe you would be interested in testing this out?

**Comment by raisedadead** [comment] 2017-06-11 21:57
We want to test this approach. Potential contributors please check the proposed solution in the opening post and revert on this thread.

**Comment by Marmiz** [comment] 2017-06-12 02:36
I was unable to make your pen working @eghan. The reason is that the API does not return any data.

After a quick look into the API docs seems that it only returns forecast for the US territories:
>Search results are provided by Esri and include the 50 United States. We are working with Esri to include U.S. territories and other regions.

Can you please confirm this is the case?
someone else from outside the US can confirm it's not working for them as well?

Even just in the website http://www.weather.gov/ playing around with the search input does not produce any result outside the US. (eg: Paris does not point to the French's capital)

**Comment by raisedadead** [comment] 2017-06-12 18:40
I can confirm the same result as @Marmiz above from Pune, India. 

@eghan 
I believe we should close this, but feel free to document your findings on the forum wiki or as a post (for users from US to benefit).

Thanks to both of you for the contribution! Happy coding!

**Closed by raisedadead** 2017-06-12 18:40 UTC
Labels: help wanted
