### ISSUE TITLE
More dark grey than light gray in the exercice 

### ISSUE THREAD

**Issue by dfo44100** [FreeCodeCamp/FreeCodeCamp#1850] opened 2015-08-17 13:01 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![waypoint__use_hex_code_for_specific_shades_of_gray___free_code_camp](https://cloud.githubusercontent.com/assets/11556975/9305283/7c141002-44f0-11e5-936b-9cff98a1c1e0.jpg)

**Comment by AryanJ-NYC** [comment] 2015-08-17 13:07
Duplicate of and closed as per #1844.

**Closed** 2015-08-17 13:08 UTC
