### ISSUE TITLE
FCC curriculum is not loading in Philippines 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#42201] opened 2021-05-21 05:19 UTC
There have been a couple of posts in the forum and reddit page about users in the Philippines not being able to access the website.

https://forum.freecodecamp.org/t/website-not-loading-tried-everything/460889
https://www.reddit.com/r/FreeCodeCamp/comments/nfe7id/site_cant_be_reached/

Users are saying that the website does not load for them or they are getting this message. 
"you appear to be offline, your progress may not be saved."

I know that this message has appeared in the past and usually resolved itself pretty quickly. 
But it has been a couple days now and the problem is still there.

Here is a screenshot from one of the users in the Philippines when they try to access the page. 

![image](https://user-images.githubusercontent.com/67210629/119088488-a00b8880-b9bd-11eb-8d51-ed0013bd4a81.png)

**Comment by raisedadead** [comment] 2021-05-21 09:28
Since this is not a technical issue with the codebase yet, we are requesting more information on the forum thread here: https://forum.freecodecamp.org/t/website-not-loading-tried-everything/460889/11?u=raisedadead

**Comment by raisedadead** [comment] 2021-05-22 10:05
Closing this in favour of the ongoing discussion on the forum. So far we do not have anything that points issues with the code or the infrastructure.

**Closed by raisedadead** 2021-05-22 10:05 UTC
Labels: scope: curriculum, type: bug, type: showstopper

**Comment by sitiocoder** [comment] 2021-06-03 03:32
Hi, I am from the Philippines and I can confirm FCC is now accessible. Thanks for looking this up. Appreciate.

**Comment by ngbeken1monday** [comment] 2021-08-13 12:22
2.Given the following form defined below:Modify this form in the following fashion:a) Add a function connected to the button to display all the data associated with the components in the form. This function is to be called whenever the user clicks the button.
b) Modify the form so that when the user clicks in each of the fields, their contents are highlighte
