### ISSUE TITLE
[Bug]  Wrong redirection in to the most recent challenge in old users

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#6231] opened 2016-01-17 00:20 UTC
Steps to reproduce:
1. Login with an user in level 282.
2. Go to http://freecodecamp.com

Actual: Redirect to challenge 0.
Expected:  Redirect to most recent challenge. One challenge after my last challenge finished. Never redirect to a challenge that the user has already finished.

**Comment by robwelan** [comment] 2016-01-17 01:31
happening to me too... :-(

**Comment by Em-Ant** [comment] 2016-01-17 17:20
+1

**Comment by BerkeleyTrue** [comment] 2016-01-18 17:29
We use cookies to store which challenge you visited last. If you are clearing your cookies then we have no idea which challenge you completed last, so we send you do the default, which is the first challenge.

**Comment by bugron** [comment] 2016-01-19 12:53
Closing this issue as it's a duplicate of #6203.

**Closed by bugron** 2016-01-19 12:53 UTC
Labels: blocked
