### ISSUE TITLE
Expand community dropdown menu on click on smaller screens

### ISSUE THREAD

**Issue by adityaparab** [freeCodeCamp/freeCodeCamp#15844] opened 2017-09-04 07:02 UTC
#### Challenge Name

This is a global issue. Not specific to particular challenge

#### Issue Description

On smaller screens (width less than 768px) the top navigation menu is converted to a Menu button.
When menu is clicked, it shows navigation items. Point to `Community` submenu with your mouse. The submenu expands automatically. Now point to `About` and try going to the next primary menu item `Donate`. When the `About` menu loses focus, the Community submenu collapses and user has to go up again to click `Donate` button.

#### Browser Information

* Browser Name, Chrome - Version 60.0.3112.113 (Official Build) (64-bit): 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot

Step 1 : Point to About Menu

![issue-1](https://user-images.githubusercontent.com/5561498/30015084-d99f2bce-916c-11e7-8b35-70c7a1b13413.png)

Step 2 : Try to click Donate

![issue-2](https://user-images.githubusercontent.com/5561498/30015090-e5e90148-916c-11e7-8a28-e60b57370237.png)

#### Additional info:
This is correct behaviour for bigger screens where menu is fully visible. The collapsed submenu should expand on click (as opposed to on hover)

**Comment by systimotic** [comment] 2017-09-05 07:54
Thanks for reporting this @adityaparab! I just ran into https://github.com/freeCodeCamp/freeCodeCamp/issues/13450, and it looks like this is a duplicate of that, so I'm closing this issue.

Happy coding!

**Closed by systimotic** 2017-09-05 07:54 UTC
