### ISSUE TITLE
Waypoint: Sift through Text with Regular Expressions - misleading instructions

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#2184] opened 2015-08-19 12:28 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions 

Instructions for this and the next couple of lessons are some what misleading when explaining what + does in regex syntax.

Instructions state + is need to find 'one or more occurrences of this pattern' which is not correct. In the example given + would find the letters an followed by 1 or more d's, and not multiple and's.

Also, the tests expect and+ when + is not required to find an the occurrences of and in the sentence.

**Comment by denmch** [comment] 2015-08-19 13:38
Duplicate of #1938

**Comment by bugron** [comment] 2015-08-23 07:08
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2163
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Closed** 2015-08-24 18:23 UTC
