### ISSUE TITLE
Instructions don't specify "green box"

### ISSUE THREAD

**Issue by Risle** [FreeCodeCamp/FreeCodeCamp#2946] opened 2015-09-01 06:34 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Last paragraph of instructions reads: "Use Clockwise Notation to give <em>an element</em> a margin of 40px on its top and left side, but only 20px on its bottom and right side."

But only changing the margin of the green box validates. So the sentence should be changed to: "Use Clockwise Notation to give <em>the green box</em> a margin of 40px on its top and left side, but only 20px on its bottom and right side."

**Comment by awesomeaniruddh** [comment] 2015-09-01 09:24
I agree. On it.

**Comment by bugron** [comment] 2015-09-01 14:20
@Risle thanks for posting this issue!
@awesomeaniruddh I can't find such a [fix](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json#L3056). 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by awesomeaniruddh** [comment] 2015-09-01 14:22
Hmmm, maybe I was looking at the wrong challenge then. I'll fix it then.

**Comment by benschenker** [comment] 2015-09-01 17:58
It looks like this is a duplicate of #2198.

**Closed** 2015-09-01 18:54 UTC
Labels: duplicate
