### ISSUE TITLE
Project Euler: Problem 2: Even Fibonacci Numbers test answers off by one count

### ISSUE THREAD

**Issue by alhazen1** [freeCodeCamp/freeCodeCamp#17798] opened 2018-07-02 05:43 UTC
#### Describe your problem and - if possible - how to reproduce it
**Two test cases have the wrong answers**
Instructions state that the first 10 numbers of Fibonacci series are 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
The first test is to determine the sum of the even numbers in the first 10 Fibonacci series with an expected answer of 188.
I get 44 - I only see three even numbers in the first 10 of series - 2,8 and 34. You would have to get to the 11th in the series to have the evens sum to 188

Similarly the third test case appears to be off by one count as well.

The second test is only correct because the next number in the series happens to be odd.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-2-even-fibonacci-numbers/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Linux Ubuntu

#### Here is a working solution with some console.log test output
https://repl.it/@alhazen1/Project-Euler-Problem-2-Even-Fibonacci-Numbers

Thanks for all you folks do.

**Comment by najuste** [comment] 2018-07-08 11:38
Oh, didn't even notice that(!) I started with 0 :/
BUT three is another bug (even if you go with one extra iteration for all other tests)
regarding the test case: '`fiboEvenSum(43) should return 1485607536.`' 

The instructions state that '_...terms in the Fibonacci sequence [are those, ] whose values do not exceed four million, find the sum of the even-valued terms_.'
And the tests pass fine if you go along with one extra iteration (which is already a bug as alhazen1 noted) and if you omit the instruction that the term should not be over 4 million.

**Comment by barrykeegan** [comment] 2019-02-27 21:02
I'm trying to understand this problem, but it's a bit hard because there appears to be two sets of tests related to this problem (maybe that's the case for all problems) but I can only see one set. It's the set that isn't obviously apparent that are causing an off-by-one submission failure.

The tests displayed on this page:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-2-even-fibonacci-numbers.english.md
are all in agreement with tests I've performed of my solution of the problem as I and, it would seem, alhazen1 understand it.

However the tests visible at the bottom left of this page:
https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-2-even-fibonacci-numbers/
show different solutions.

For example the first link above has the solution of fiboEvenSum(10) as 44, whereas the actual problem page states it should be 188. The first link above has the solution of fiboEvenSum(23) as 60696, whereas the actual problem page states it should be 60696 - which is only correct because, as alhazen1 points out, the next value in the series is odd. The first link above has the solution of fiboEvenSum(43) as 350704366, whereas the actual problem page states it should be 1485607536.

I don't know where the tests on the "learn." curriculum problem page are being pulled in from, but these appear to be the cause of this issue. I'm more than happy to assist with this bug, but I can't if I can't find the code that's causing it...

I'll dig around for a few more minutes, if I find a solution, I'll let you know...

**Comment by wang1998tina** [comment] 2019-04-24 20:49
I'd love to hop onto this issue if no one is working currently!

**Comment by RandellDawson** [comment] 2019-04-24 21:03
This may already have been resolved with the merge of PR #34722.  The current production does not reflect these changes, because the `master` branch has not been deployed to it.  

@scissorsneedfoodtoo, @NitronR Does #34722 make this issue obsolete?  If so, we can close it.

**Comment by scissorsneedfoodtoo** [comment] 2019-04-25 01:51
@RandellDawson, yes, this has been fixed. The changes from https://github.com/freeCodeCamp/freeCodeCamp/pull/34722 are up on the beta site: https://www.freecodecamp.rocks/learn/coding-interview-prep/project-euler/problem-2-even-fibonacci-numbers

**Closed by scissorsneedfoodtoo** 2019-04-25 01:51 UTC
Labels: scope: curriculum
