### ISSUE TITLE
Always Import Everything to Github - For more Job Opportunities

### ISSUE THREAD

**Issue by dardandemiri** [FreeCodeCamp/FreeCodeCamp#8242] opened 2016-04-22 09:49 UTC
#### Why is this important and How  to do it?

I see a lot of job seeking websites are asking for Github username, because they are interested to know what we have done till now with codding.

And that's where my idea comes from, we have so much code written in FCC and so little in Github!
Why not connect FCC with Github and whatever you Submit in FCC it would transfer the same code in Github too.

#### I wish this will get done soon.
Because I hate copy & paste it from FCC to Github ! 
It's so BORING !

#### His profile in FCC:
![image](https://cloud.githubusercontent.com/assets/6118247/14738577/9e498750-0882-11e6-8390-2f3dad041269.png)

#### His profile in Github:
![image](https://cloud.githubusercontent.com/assets/6118247/14738608/d44d0d22-0882-11e6-8acd-ed966392d309.png)

#### Imagine how Amazing it would be if he had the same contributions !

If I where a CEO of a Company I would hire him immediately!

**Comment by dardandemiri** [comment] 2016-04-22 10:04
![image](https://cloud.githubusercontent.com/assets/6118247/14738540/664a2dd2-0882-11e6-9136-4a067613fb82.png)

**Comment by raisedadead** [comment] 2016-04-22 11:14
Thanks @dardandemiri 
This is a duplicate of #5138

Which reminds me that I have to look into the original issue as well.

**Closed by raisedadead** 2016-04-22 11:14 UTC
