### ISSUE TITLE
Waypoint: Comment your JS code ==> Code is displayed

### ISSUE THREAD

**Issue by bchui** [FreeCodeCamp/FreeCodeCamp#2638] opened 2015-08-24 21:59 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It shows the following...
"undefined

assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');Create a // style comment that contains at least five letters
assert(editor.getValue().match(/(\/\*)...../g), 'Create a /\* \*/ style comment that contains at least five letters.');Create a /* */ style comment that contains at least five letters.
assert(editor.getValue().match(/(\*\/)/g), 'Make sure that you close the comment with a \*/');Make sure that you close the comment with a */"
<img width="419" alt="screen shot 2015-08-24 at 2 59 03 pm" src="https://cloud.githubusercontent.com/assets/13310037/9453664/b7e51d94-4a70-11e5-9032-4da977983252.png">

**Comment by rowansen** [comment] 2015-08-26 08:39
i`m also confused.

**Comment by brandy2377** [comment] 2015-08-26 16:05
Here is what you need to do:

assert(editor.getValue().match(/(\/\/)...../g));
       //This is a comment
assert(editor.getValue().match(/(\/\*)...../g));
/*This is a comment too*/
assert(editor.getValue().match(/(\*\/)/g));

**Comment by kettultim** [comment] 2015-08-27 22:35
@brandy2377 yes, you can still run the exercise but that doesn't change the fact that this is a bug. I've noticed this on every JS waypoint I've tried so far - actual JS script (used to run FCC) is displaying in the checklist text as a string. This needs to be fixed. Screenshot attached of another one:
<img width="384" alt="error" src="https://cloud.githubusercontent.com/assets/1346441/9534903/40c7e0f6-4d14-11e5-977c-1ea4f999cb02.png">

**Comment by kettultim** [comment] 2015-08-27 22:40
This issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999

**Comment by benmcmahon100** [comment] 2015-08-27 22:58
Closing as a dupe of #1999

**Closed by benmcmahon100** 2015-08-27 22:58 UTC
