### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by ghoal** [FreeCodeCamp/FreeCodeCamp#4229] opened 2015-11-07 13:39 UTC
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%3C!--%20--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!-- -->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```

**Comment by BerkeleyTrue** [comment] 2015-11-07 15:52
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!

**Comment by BerkeleyTrue** [comment] 2015-11-07 15:53
@ghoal Please change the title to something more descriptive.

**Comment by ltegman** [comment] 2015-11-07 19:15
Closing this issue since your code both appears to solve the problem and passes all the tests. Please reopen with further information if you are still having problems.

Thanks and happy coding!

**Closed by ltegman** 2015-11-07 19:15 UTC
