### ISSUE TITLE
The button will not properly submit my code

### ISSUE THREAD

**Issue by LatashaH** [FreeCodeCamp/FreeCodeCamp#6823] opened 2016-02-08 06:18 UTC
Challenge [Add Rounded Corners with a Border Radius](http://www.freecodecamp.com/challenges/add-rounded-corners-with-a-border-radius#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%C2%A0%20%20border-radius%3A%2010px%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.0.2; LG-D415 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.95 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 10px;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by alistermada** [comment] 2016-02-08 06:50
Hmm.. for some reason `border-radius` doesn't affect the image if it's declared below `border-style`. If you switch those two properties around it works.

However, there isn't anything wrong with your code. If you run the tests with your original code again it should work.

**Comment by LatashaH** [comment] 2016-02-08 06:59
Hi. After doing what you suggested it still didnt work. Is it my device or
what? Ive been having problems since yesterday.

**Comment by alistermada** [comment] 2016-02-08 07:02
@LatashaH  That's odd. When I clicked on the link to your code, it originally didn't work for me then I did what I described above and it worked.

I'm not sure. It might be device-specific. What browser and operating system are you using? Are you getting any errors in console?

**Comment by sludge256** [comment] 2016-02-08 07:08
While the link and the raw code posted the body of the post appear to contain the same code they produce different URLs.
Link URL:
```
http://www.freecodecamp.com/challenges/add-rounded-corners-with-a-border-radius#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20{%0A%20%20%20%20color%3A%20red%3B%0A%20%20}%0A%0A%20%20h2%20{%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20}%0A%0A%20%20p%20{%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20}%0A%0A%20%20.thick-green-border%20{%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%C2%A0%20%20border-radius%3A%2010px%3B%0A%20%20}%0A%0A%20%20.smaller-image%20{%0A%20%20%20%20width%3A%20100px%3B%0A%20%20}%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E
```
URL generated from code shown in this issue:
```
http://www.freecodecamp.com/challenges/add-rounded-corners-with-a-border-radius#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20{%0A%20%20%20%20color%3A%20red%3B%0A%20%20}%0A%0A%20%20h2%20{%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20}%0A%0A%20%20p%20{%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20}%0A%0A%20%20.thick-green-border%20{%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2010px%3B%0A%20%20}%0A%0A%20%20.smaller-image%20{%0A%20%20%20%20width%3A%20100px%3B%0A%20%20}%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E
```

There seems to be an unusual white space character before
```
    border-radius: 10px;
```
in the linked code as opposed to the pasted code.

**Comment by LatashaH** [comment] 2016-02-08 07:08
I am using an Android on Chrome. I do not not understand your last question.

**Comment by LatashaH** [comment] 2016-02-08 07:12
I must also add after skipping the exercise and the one after it...I had no
problems with completing the exercises that had nothing to do with
border-radius and etc.

**Comment by alistermada** [comment] 2016-02-08 07:15
@LatashaH I believe you can access the console on Android with Chrome by typing `about:debug ` in the address bar of the page.

**Comment by LatashaH** [comment] 2016-02-08 07:18
Ok. The suggestion you made about white space worked. But what was crazy
was that I had to put all of that information i.e. border info on one line
of code. Is that normal?

Thank you.

L.

**Comment by LatashaH** [comment] 2016-02-08 07:26
Ok. Thanks. Although to be honest, I am not familiar with what a console is
or does or anything at all. I am a novice, indeed.

**Comment by sludge256** [comment] 2016-02-08 07:32
You shouldn't have to put it all in one line, but for some reason an non-normal space was added to your code. Regular spaces are encoded as `%20` but you had a white-space character of `%C2%A0` in your code. Do you have any idea how that may have occurred?

**Comment by LatashaH** [comment] 2016-02-08 07:42
I have no idea because other people where able to use my code too and no
problems. I did notice that the system would not really clear things up and
etc; when I would clear out my code or refresh the page and it would save
bits of it after the fact. But I also noticed when I went forward in my
code the code displayed was not on one line. But there was no error saying
I had white space.

**Comment by sludge256** [comment] 2016-02-08 21:11
@FreeCodeCamp/issue-moderators 
Should we consider this resolved and close the issue? I am unable to reproduce the issue without knowing how the non-standard white space character was introduced.

**Comment by LatashaH** [comment] 2016-02-08 22:31
Yes. The issue is resolved.

**Closed** 2016-02-08 22:31 UTC

**Comment by xsstomy** [comment] 2016-02-25 02:51
same issue，
os x EI Capitan,10.11.3, chrome 48.0.2564.116 (64-bit)
i have no idea how it happened

**Comment by xsstomy** [comment] 2016-02-25 03:22
when i reload the page,click the button ,it works
