### ISSUE TITLE
Doesnt run test, does not appear the "to do" list

### ISSUE THREAD

**Issue by MTeresaArista** [FreeCodeCamp/FreeCodeCamp#9870] opened 2016-07-24 11:25 UTC
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addclass("shake");
    $("#target1").addClass("btn-primary");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
When I try to run the test for this excersice, it doesnt appear the "to do" list below the "run test, help," etc. buttons, also it doesnt run the test (I belive the code is correct and it doesnt let me check that).

Help?

**Comment by BKinahan** [comment] 2016-07-24 11:29
This is a duplicate of #9673; you have a capitalization error (`addclass`) that is causing the tests not to run correctly.

Note: you may need to refresh the page after correcting the error in order to allow the tests to run properly.

Happy coding!

**Comment by MTeresaArista** [comment] 2016-07-24 11:33
It still doesnt let me correct the test and doesnt show me the "To do" list below that.

Is that normal? All other excercise show me that and allow me to run the test, but not that expecific one

**Comment by BKinahan** [comment] 2016-07-24 11:37
@MTeresaArista Be sure to refresh the page. If it still doesn't work, use the Reset button and refresh again, then re-enter your code with the correct capitalization for `addClass`

**Comment by MTeresaArista** [comment] 2016-07-24 11:41
Thank you! It works now :+1: 

Have a nice day!

**Comment by bugron** [comment] 2016-07-24 11:47
@MTeresaArista thanks for posting, @BKinahan thanks for your help. Closing this PR as resolved.

**Closed by bugron** 2016-07-24 11:47 UTC
