### ISSUE TITLE
Tests not working == code matches sample template provided in item

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#14542] opened 2017-04-22 21:41 UTC
Challenge [use-for-to-create-a-sass-loop](http://beta.freecodecamp.com/en/challenges/sass/use-for-to-create-a-sass-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  @for $j from 1 to 6 {
  .text-#{$j} { font-size: 10px * $j; }
}
  
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>

```

The issue is consistent in both firefox and chrome

**Comment by arawwad** [comment] 2017-04-23 05:14
bug confirmed 
i used the same code as you did but i couldn't pass the challenge..
i compiled the file manually on my machine  and i got what i think the right answer

**Comment by lynxlynxlynx** [comment] 2017-04-27 11:28
Looking at the page source, the inline sass doesn't get compiled into css.

**Comment by Tennyx** [comment] 2017-05-22 15:21
Is there any way to force onto the next problem or are we stuck until this bug is fixed

**Comment by systimotic** [comment] 2017-05-27 09:45
I believe Sass and other libraries are not yet working in the beta. I'm not sure if there's a general open issue on that.

**Comment by huntinghawk1415** [comment] 2017-06-15 14:42
To force the answer, you could always use the syntax required to pass, and then use actual CSS syntax to force the text to change:
`<style>
  
  @for $j from 1 to 6 {
    .col-#{$j} {
      font-size: 10px * $j;
    }
  }  
  .text-1 {
    font-size: 10px;
  }
  .text-2 {
    font-size: 20px;
  }
  .text-3 {
    font-size: 30px;
  }
  .text-4 {
    font-size: 40px;
  }
  .text-5 {
    font-size: 50px;
  }
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>`

**Comment by systimotic** [comment] 2017-09-03 19:16
Hi all! Thanks for reporting and looking into this issue. I'm closing this as a duplicate of #12699. Happy coding!

**Closed by systimotic** 2017-09-03 19:16 UTC
Labels: beta
