### ISSUE TITLE
It keeps freezing!

### ISSUE THREAD

**Issue by MirkaG** [FreeCodeCamp/FreeCodeCamp#4657] opened 2015-11-22 22:47 UTC
In this challenge, the moment I write "function" the whole thing just freezes. I tried it over and over, refreshing, restarting, waiting days in between. It always freezes at the exact same point. I start typing the reverse code and as soon as I write function, it simply freezes

Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array;

// Only change code above this line.


```

**Comment by ltegman** [comment] 2015-11-22 22:50
Thanks for the report. This is a known issue that should hopefully be solved soon. However, you can pass this challenge without typing function because no callback is required for `reverse`.

Closing as a duplicate of #4228

Thanks and happy coding!

**Closed by ltegman** 2015-11-22 22:50 UTC

**Comment by meinnes** [comment] 2015-11-26 21:24
Got the same today, got over it without function. Thanks for the help!
