### ISSUE TITLE
Not able to scroll 

### ISSUE THREAD

**Issue by Akshaybagai52** [freeCodeCamp/freeCodeCamp#50883] opened 2023-07-04 06:53 UTC
### Describe the Issue

current Behaviour is this as attached screenshot there is no scroll present due to which user not able to see full content of the page

### Affected Page

https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-serve-static-assets/301518

### Steps to Reproduce

1. Go to 'any practice courses on freecodecamp' e.g = https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/start-a-working-express-server
2. Click on 'Get a Hint button'
3. Then https://forum.freecodecamp.org will open and now you are not able to scroll down in this page and also not able to sign in and sign up e,g = https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-serve-static-assets/301518

### Expected behavior

It should scroll and user able to see all the content 

### Screenshots

![Screenshot_3](https://github.com/freeCodeCamp/freeCodeCamp/assets/100753870/70a7fc00-92cd-4de2-944f-f27470a9ffe2)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment] 2023-07-04 07:11
Hello there,

I am unable to reproduce any issue with the forum UI/navigation.

Do you have any browser extensions that could be affecting the page? Would you mind filling in the **System** section of your issue description?

**Comment by Akshaybagai52** [comment] 2023-07-05 03:05
@ShaunSHamilton Are you able to scroll in this url = https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-serve-static-assets/301518

**Comment by ShaunSHamilton** [comment] 2023-07-05 09:21
> @ShaunSHamilton Are you able to scroll in this url = https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-serve-static-assets/301518

Yes.

**Comment by Akshaybagai52** [comment] 2023-07-05 09:44
@ShaunSHamilton I think you can close this it is not working in my pc but working in other pc I just checked and thanks for confirmation
Do you know what is the main reason of this in my pc?

**Comment by ShaunSHamilton** [comment] 2023-07-05 09:45
> Do you know what is the main reason of this in my pc?

Do you mind sharing your system info? Specifically, your User Agent could help debug.

**Comment by Akshaybagai52** [comment] 2023-07-05 10:16
@ShaunSHamilton 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/100753870/2bc8f36c-81fd-432f-aa96-7e54681d8a3d)

**Comment by ShaunSHamilton** [comment] 2023-07-05 14:25
@Akshaybagai52 Thank you, and can you share what you see here: https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by Sembauke** [comment] 2024-01-11 08:50
Closing this as can't reproduce

**Closed by Sembauke** 2024-01-11 08:50 UTC
Labels: other: device specific, platform: forum
