### ISSUE TITLE
Better Pic of Double Coding Error

### ISSUE THREAD

**Issue by vgibson15** [FreeCodeCamp/FreeCodeCamp#2982] opened 2015-09-02 03:49 UTC
Hi , 

The programming image that appears.
![bug](https://cloud.githubusercontent.com/assets/13035720/9622656/f206616a-50ea-11e5-87d8-df21ad8f756e.png)

![bug](https://cloud.githubusercontent.com/assets/13035720/9622652/d72af2fc-50ea-11e5-90c2-e592f89a0be1.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-negative-margin-to-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment] 2015-09-02 04:04
@vgibson15 thanks for posting this issue! 
Note that your issue is a duplicate of your own https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2981, so I'm closing it. You can continue further discussion there. **This issue is not challenge specific, it's global, so please, don't duplicate your issues, thank you**.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-02 04:04 UTC
