### ISSUE TITLE
Not getting checked as completed.

### ISSUE THREAD

**Issue by iAmNawa** [FreeCodeCamp/FreeCodeCamp#7849] opened 2016-04-01 21:18 UTC
#### Issue Description
Hello, the Video Challenges are not being marked as complete.  I did the first four or so of computer basics and nothing was checked. I exited the browser, tried the first one two more times and it was still not marked as complete.  Then I tried the first one of JavaScript lingo, completed the quiz, but still no green check mark.

#### Browser Information
Google Chrome, newest version
OS X El Capitan

**Comment by erictleung** [comment] 2016-04-01 21:23
Closing because duplicate of #7795.

**Closed by erictleung** 2016-04-01 21:23 UTC
