### ISSUE TITLE
The Challenge for randome numbers in a range has a false description

### ISSUE THREAD

**Issue by doxanthropos** [FreeCodeCamp/FreeCodeCamp#2117] opened 2015-08-18 20:03 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range : The text in the sidebar does not specify the task that is to be done, it only explains how to generate random ranges. In the code the task is described as such: 
![2015-08-18-215937_1280x800_scrot](https://cloud.githubusercontent.com/assets/2058212/9341224/db57eb60-45f4-11e5-8cf5-21dab33090d6.png)
"  // Make myFunction return a random number between zero and nine instead of a decimal
  // Only change code below this line."

**Comment by michael-krebs** [comment] 2015-08-18 21:08
duplicate of #1992

**Closed** 2015-08-26 00:10 UTC
