### ISSUE TITLE
Wiki Template URL Redirects to FCC Main Wiki Page

### ISSUE THREAD

**Issue by j7an** [FreeCodeCamp/FreeCodeCamp#9605] opened 2016-07-07 20:05 UTC
#### Issue Description

Going to the following URL: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki
This web page has a link called "template" for the Wiki template page. Clicking on this link (https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Wiki-Template) redirects to the original main wiki page.

It should be displaying the wiki template page

#### Browser Information

* Browser Name, Version: Latest Chrome
* Operating System: OS X
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

**Comment by ChaituVR** [comment] 2016-07-08 04:29
This is [ Wiki's ](https://github.com/FreeCodeCamp/wiki) issue ..  If you or anyone interested in contributing .. Go ahead and change the link in  https://github.com/FreeCodeCamp/wiki/blob/master/Home.md
 to  this 
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution
and open a new PR

**Comment by ChaituVR** [comment] 2016-07-08 04:59
Sorry , This is a duplicate of #9513

**Comment by raisedadead** [comment] 2016-07-08 09:38
Closing, please search issues before reporting.

**Closed by raisedadead** 2016-07-08 09:38 UTC
Labels: duplicate
