### ISSUE TITLE
Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by MiLeung** [FreeCodeCamp/FreeCodeCamp#5622] opened 2015-12-31 06:35 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%2010%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%2F%2Fconsole.log(myVar)%3B%0A%2F%2Fvar%20myVar%3B%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 10;
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
//console.log(myVar);
//var myVar;

// now remove the console.log line to pass the test


```

"remove the console.log line to pass the test" does not pass.  

Also, why would you have a bonfire where you delete code to pass?  When you write code, there is an infinite amount of different things you can type; any one can delete code without thinking.  The comments even tell you to delete the console.log().  Why?  This doesn't allow a camper to think.

**Comment by SaintPeter** [comment] 2015-12-31 06:41
We are aware of this issue.

If you can come up with a way to demonstrate how local variables work, we're open to suggestions.  I absolutely agree with you, but couldn't come up with an alternative.  In fact, I didn't even come up with it at all, @abhisekp did after I failed.

**Comment by MiLeung** [comment] 2015-12-31 07:05
https://repl.it/BbI2/0

Here's my shot.  There's a little repetition in the commenting, but hopefully it makes more sense.

**Comment by SaintPeter** [comment] 2015-12-31 07:10
The issue with your example is that it uses global scope.  Maybe it's only possible to demonstrate local as opposed to global, but I was trying to keep the introduction of the two separate.

**Comment by AkiraLaine** [comment] 2015-12-31 07:34
I also have this issue.

**Comment by MiLeung** [comment] 2015-12-31 07:35
"// now remove the console.log line to pass the test"

Is the issue.  Delete this comment.

**Comment by raisedadead** [comment] 2015-12-31 07:46
@SaintPeter The current check is looking for `/console\\.log/gi` which doesn't cover the case if the user has "console.log" in comments, I think we should consider this, and modify the assert to ignore commented code, at least for now until we find a more suitable example?

**Comment by abhisekp** [comment] 2015-12-31 12:03
The issue is discussed here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5559

A PR with the updated tests for a fix https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5578

**Comment by TheGreenHabi** [comment] 2015-12-31 12:26
Maybe we can task a user to write ```if``` check for variable.
Something like this:
```javascript
function localVar() {
    var localA = "A";
    
    function localVarB() {
        var localB = "B";
        return loc
    }
    
    console.log(localA);
    if (typeof localB === "undefined")
        return "localB is undefined";
}

localVar();
```

**Comment by abhisekp** [comment] 2015-12-31 12:29
@TheGreenHabi function inside function might be overwhelming for beginners

**Comment by TheGreenHabi** [comment] 2015-12-31 12:30
We can put local variable inside ```for``` loop, for example

**Comment by TheGreenHabi** [comment] 2015-12-31 12:31
or two separate functions

**Comment by srkchandru** [comment] 2015-12-31 18:44
Remove this comment:"// now remove the console.log line to pass the test".It worked for me!

**Comment by titoluyo** [comment] 2016-01-02 06:28
do the same as @srkchandru and works, that's weird.

**Comment by AkiraLaine** [comment] 2016-01-02 06:57
@srkchandru's method works.

**Comment by jaxxon33** [comment] 2016-01-02 13:42
I had to also delete the commented line containing 'console.log' to pass.

**Comment by ltegman** [comment] 2016-01-02 17:12
Closing this as a PR to fix it was merged. It should be live on the website soon. Thanks and happy coding!

**Closed by ltegman** 2016-01-02 17:12 UTC

**Comment by nf15** [comment] 2016-01-13 02:14
spent much time on this. Never found clear clue on here as well. Waypoint: Local Scope and Functions

**Comment by abhisekp** [comment] 2016-01-13 02:28
@nf15 isn't it fixed yet? It should be. Are you still having the error?

**Comment by Cezar13** [comment] 2016-05-06 06:38
function myFunction() { 
Here is the problem :) 
Should be 

**function myLocalScope() **
