### ISSUE TITLE
My code only works with //noprotect

### ISSUE THREAD

**Issue by keith24** [freeCodeCamp/freeCodeCamp#7764] opened 2016-03-28 07:00 UTC
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
//noprotect
function smallestCommons(arr) {
  for (var j=Math.max(...arr)+1;;){
    for (var i=2; i<=Math.max(...arr);){
      if (j%i!==0) {j++; i=2; }
      else {i++;}
    }
    console.log(j);
    return j;
  }
}
```

Without `//noprotect`, the loop breaks early.  I think this challenge should have a longer timeout, or at least a smaller test value than `13`.

**Comment by SaintPeter** [comment] 2016-04-18 01:00
I can't get this code to work under any circumstances.

We don't have strong support for ES6.  It's possible that our loop protect code is breaking your loops  To this I don't really have an answer.

**Comment by erictleung** [comment] 2016-04-18 01:19
@SaintPeter I was able to get his code to work on Chrome on Mac OS 10.10. The last test doesn't run for me. We could change the last test to avoid this problem (plus, I think this issue is a possible duplicate of #7072) and we could add more tests (which someone has pointed out in #7292).

**Comment by keith24** [comment] 2016-04-18 02:30
I added `console.log(j);` so I could watch the code count.  It passes all the tests for me except the last.  `j` on the last test gets up to 400-600 and then it just breaks.  `noprotect` fixes it, so it must be the loop protection.  

For it to work for me without `noprotect`, none of the tests should expect a return value more than ~400.  I think it'd be a good idea to add some with a minimum value other than 1.

**Comment by Quartzito** [comment] 2016-05-18 11:00
Having the same kind of issue here. Can make it work from [1,2] to [1,8] (using // noprotect for 7 and 8 cases) after that it just doesnt work and freezes.

**Comment by ChrisLegg** [comment] 2016-07-15 22:53
I had to add in // noprotect to get it to work for the final [23,18] case.  I'm assuming there is a far more efficient method than the one I used and that's part of the issue.

**Comment by hvuntokrul** [comment] 2016-08-05 15:04
Same here. Only passed with // noprotect
I guess they wanted us to use recursion :)

**Comment by virtual** [comment] 2016-08-08 23:51
Might be helpful to add that noprotect is necessary if you're trying to solve the last query without recursion. Thanks!

**Comment by QuincyLarson** [comment] 2017-01-04 06:15
No one has brought this up since August. Is this still an issue? If so, we may want to restructure the challenge so it can be completed without noprotect.

**Closed** 2017-02-06 22:19 UTC
Labels: decayed
