### ISSUE TITLE
jQuery Waypoint 2: Blank Input Window 

### ISSUE THREAD

**Issue by Fishuu** [FreeCodeCamp/FreeCodeCamp#3777] opened 2015-10-16 21:18 UTC
Hi!
I'm using Firefox 41.0.2 on Mac OSX Yosemite

So I started on the jQuery lesson and once completing "Waypoint 1: Learn how Script Tags and Document Ready Work Complete" and go to "Waypoint 2: Target HTML Elements with Selectors Using jQuery", the code input screen is completely empty.
![screen shot 2015-10-16 at 1 54 16 pm](https://cloud.githubusercontent.com/assets/13893619/10553130/6e0c4334-740d-11e5-8e47-369192fb08e2.png)

I tried reproducing this a few times: Completing Waypoint 1 and moving to Waypoint 2 with the same outcome.

This got me pretty confused why my code wasn't working... Finally decided to click "Reset" and the slew of code finally showed up.

![screen shot 2015-10-16 at 1 55 56 pm](https://cloud.githubusercontent.com/assets/13893619/10553188/cb4f71d8-740d-11e5-9b8d-f845f0a039cb.png)

If I click to Map > Waypoint 2 directly, it will also load without issues.

Another issue I have is why the checklist instructions don't show up in Firefox. Shows up in Chrome though!

**Comment by awesomeaniruddh** [comment] 2015-10-17 12:03
I was unable to reproduce the issue on Chrome (Windows 10). Seems to be an issue with Firefox.

**Comment by ltegman** [comment] 2015-10-17 17:05
Unfortunately I was unable to repro on Firefox 41 on OS X El Capitan, so I can't do any debugging on it.

**Comment by FireMorph** [comment] 2015-10-18 23:23
I'm on FF 41.0.2 and I don't have checklist instructions in whole jQuery chapter but If I press run tests they will show up.

**Comment by ltegman** [comment] 2015-11-11 21:11
Closing as no repro. Please try disabling any extensions and if you still experience issues we recommend using Chrome for the best Free Code Camp experience!

**Closed by ltegman** 2015-11-11 21:11 UTC
Labels: firefox
