### ISSUE TITLE
In correct styling syntax used in example for "Change the Color of Text"

### ISSUE THREAD

**Issue by RobertDiebels** [FreeCodeCamp/FreeCodeCamp#11848] opened 2016-11-28 17:26 UTC
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3A%20red%3B%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color: blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

Contains incorrect styling syntax. 

"color: blue" is not closed with a semicolon. I know this is nitpicking. But stuff like that will be hard to find later on.

**Comment by Marcelosilva10** [comment] 2016-11-28 19:59
```
 <h2 style="color: red;">CatPhotoApp</h2>
```

**Comment by erictleung** [comment] 2016-11-28 20:14
@RobertDiebels my two cents on the matter is that the code is fine i.e. no semi-colon is necessary because these are inline stylings, which shouldn't be used anyways. Nonetheless, I'll be closing this issue because it is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10403. Feel free to continue the discussion over on that issue. Happy coding!

**Closed by erictleung** 2016-11-28 20:14 UTC
