### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Toreador78** [FreeCodeCamp/freecodecamp#619] opened 2015-05-27 05:53 UTC
There is another one like #500. Alas, I can't load up a screenshot. :-/

**Comment by Stiino0** [comment] 2015-05-27 09:31
I get Syntax error, unrecognized expression even when the code is 100% correct (shows correctly in my previewed app)
Windows 7 PRO SP1 64bit
Firefox 38.0.1
![waypoint_check_radio_buttons_and_checkboxes_by_default_free_code_camp](https://cloud.githubusercontent.com/assets/11710334/7833037/dbc37e16-0463-11e5-9a77-873f7bd20dd7.png)

**Comment by terakilobyte** [comment] 2015-05-27 15:03
Thanks for the report, closing this issue as a duplicate of #585.

**Closed by terakilobyte** 2015-05-27 15:04 UTC
