### ISSUE TITLE
HTML challenge for 'Use Hex Code to Mix Colors' has issues.

### ISSUE THREAD

**Issue by marcmorales** [FreeCodeCamp/FreeCodeCamp#10630] opened 2016-09-09 21:11 UTC
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
code is correct but test run is not validating properly.

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: 	#FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by ArielLeslie** [comment] 2016-09-09 21:20
Copy of Issue #10523

**Comment by erictleung** [comment] 2016-09-09 22:49
@marcmorales thanks for the issue. As @ArielLeslie has pointed out, this is a duplicate of #10523. So closing this issue in favor of that one. Happy coding!

**Closed by erictleung** 2016-09-09 22:49 UTC
