### ISSUE TITLE
Sass challenges don't work

### ISSUE THREAD

**Issue by Azbo400** [freeCodeCamp/freeCodeCamp#12699] opened 2017-01-21 18:34 UTC
Challenge [storing-data-with-sass-variables](http://beta.freecodecamp.com/en/challenges/sass/storing-data-with-sass-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

```html
    
    
<style>
$text-color: red;

.header{
  text-align: center;
}
.blog-post h2 {
  color: $text-color;
}
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
<h2>Some random title</h2>
<p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
<h2>Header #2</h2>
<p>Here is some more random text.</p>
</div>
<div class="blog-post">
<h2>Here is another header</h2>
<p>Even more random text within a paragraph</p>
</div>
```

Hello Everyone, I think I found a bug in the challenge Storing Data With Sass Variables. I think I did everything right, but the h2 and the .blog-post elements colour doesn't change to red. I pass two of the user stories but not these:
Your .blog-post element should have a color of red.
Your h2 elements should have a color of red.

It also doesn't change red. But it passes the user stories:
Your code should have a Sass variable declared for $text-color with a value of red.
Your code should use the $text-color variable to change the color for the .blog-post and h2 items

Thank you in advance, and the new things in Beta seem amazing keep up the great work! Can't wait to work through more of them! 👍

**Comment by systimotic** [comment] 2017-01-21 19:50
@Azbo400 Thank you for reporting this issue. It looks like we don't actually support compiling the Sass yet 😅

**Comment by Azbo400** [comment] 2017-01-21 20:25
@systimotic Oh haha, that makes sense! Thank you 😄

**Comment by HKuz** [comment] 2017-01-21 21:05
Oh sorry! We should have given folks a head's up that this section wouldn't work properly. Thanks for the issue, @Azbo400

**Comment by Azbo400** [comment] 2017-01-21 21:43
@HKuz That's fine, no problem. 😃

**Comment by ppmakeitcount** [comment] 2017-01-22 06:18
Yeah. Its not working. Will there be any notification when it is fixed?

**Comment by ChrisD1986** [comment] 2017-01-22 07:28
We don't support the "saas" yet! Lmao!!!

On Jan 22, 2017 12:19 AM, "Pramod Potdar" <notifications@github.com> wrote:

Yeah. Its not working. Will there be any notification when it is fixed?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/12699#issuecomment-274311826>,
or mute the thread

**Comment by rudolphh** [comment] 2017-02-06 07:45
They don't want any sass from you. Jokes

**Comment by betaalpha987** [comment] 2017-03-12 18:24
I agree that it'd be a good idea to warn people that Sass doesn't work yet.

In the meanwhile, I recommend folks follow the Sass official page's guide to installing a Sass compiler and following their guide (and / or FCC's Sass tutorials) on their own machines. The guide starts here: http://sass-lang.com/install

**Comment by ahmadabdolsaheb** [comment] 2018-06-01 14:55
The Challenge storing-data-with-sass-variables has needs to have its last two tests refactored to test for the use of the assigned variable

**Comment by QuincyLarson** [comment] 2018-06-03 20:35
@ahmadabdolsaheb Awesome - good call. Do you have any idea how to go about refactoring them?

**Comment by ahmadabdolsaheb** [comment] 2018-06-03 23:48
@QuincyLarson I'm on it

**Comment by ahmadabdolsaheb** [comment] 2018-06-04 16:02
the following might come handy if anyone wants to tackle this issue.
the location of the tests to be refactored:
https://github.com/freeCodeCamp/freeCodeCamp/blob/6d7092928e852755fa0d4d9489b3c8748b466a94/seed/challenges/03-front-end-libraries/sass.json#L25

the are four tests that should be replaced with the following two.

```
"tests": [
        {
          "text": "Your code should have a Sass variable declared for <code>$text-color</code> with a value of red.",
          "testString": "assert(code.match(/\\$text-color:\\s*?red;/g), 'Your code should have a Sass variable declared for <code>$text-color</code> with a value of red.');"
        },
        {
          "text": "Your code should use the <code>$text-color</code> variable to change the <code>color</code> for the <code>.blog-post</code> and <code>h2</code> items.",
          "testString": "assert(code.match(/\\.blog-post\\s*?\,\\s*?h2\\s*?{\\s*?color:\\s*?\\$text-color\\s*?;/g), 'Your code should use the <code>$text-color</code> variable to change the <code>color</code> for the <code>.blog-post</code> and <code>h2</code> items.');"
        }
 ]
```
please test the solution before making a PR

**Comment by anku255** [comment] 2018-06-16 07:57
@ahmadabdolsaheb 

> please test the solution before making a PR

How should I go about testing it? If I make changes in the seed files that reside in `freecodecamp` repo then it won't reflect in the `learn` repo because it uses `@freecodecamp/curriculum` node module to get the challenges.

Even if I make the changes in `curriculum` repo locally, it won't reflect in the `learn` repo.

**Comment by mattszcz** [comment] 2018-06-20 22:03
I'm going through the Sass lessons now.
I'll post any additional lessons that are broken.

Additional Sass lessons with broken tests:
https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop

**Comment by mattszcz** [comment] 2018-06-25 17:41
I also have confirmed intermittent test passing (by spamming "Run the tests") on:
https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables
https://learn.freecodecamp.org/front-end-libraries/sass/use-each-to-map-over-items-in-a-list

but not on the other 2 broken Sass lessons (these always fail to pass):
https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

**Comment by MikeForde** [comment] 2018-07-10 11:48
I struggled initially with same issues but so far I've got all to pass (up and including the @while example - not tried the others yet) - the issue seems to be white space
For some e.g. the @while example even needed to remove any indenting of the SASS bit

Try deleting any blank lines between the code and - if that doesn't solve it - not indenting the SASS code at all.
[using FCC with Safari 11.0.2]

**Comment by jacobvarner** [comment] 2018-07-10 23:28
@MikeForde This worked for me when switching to Safari to get passed this one module. However, I still could not get it to work in any way while running it in Chrome 67.

**Comment by MikeForde** [comment] 2018-07-12 10:48
No agreed, there's more to it than white space. What I did notice is that - with the @while example - if I keep pressing the "Run the Tests" button then - if there are no actual errors - after 4-5 presses, it works, whereas if there is a genuine error it never passes. Not exactly ideal behaviour but would suggest a low-level error rather than one linked to an actual syntactic error in the code being submitted by the user.

**Comment by 2series** [comment] 2018-07-13 09:42
Hi all, whatever the issues are, they appear to be fix. Passed the challenge first time & i'm using Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by Chaoticonomist** [comment] 2018-07-13 17:06
Nope, still happening to me when I try the tests. Seem to only affect some users.

**Comment by CQW-Code** [comment] 2018-07-17 21:25
Ran into the same issue-- FireFox 56.0.2.
Cleared all the whitespaces out; indenting etc checked.
Last two tests still failed.  Attempting to "spam" the Run Test button.. so far no luck.

**Comment by mahmoud-coo6** [comment] 2018-07-19 19:20
here trick for Sass: Use @for to Create a Sass Loop : 
there is no second chance because there is bug in this challenge for sure..

<style type='text/sass'>

  @for $j from 1 through 5 {
  .text-#{$j} { font-size: 10px* $j; }
}

</style>

<p class="text-1" style="font-size:10px;">Hello</p>
<p class="text-2" style="font-size:20px;">Hello</p>
<p class="text-3" style="font-size:30px;">Hello</p>
<p class="text-4" style="font-size:40px;">Hello</p>
<p class="text-5" style="font-size:50px;">Hello</p>

**Comment by dikiaap** [comment] 2018-07-22 11:44
You may add your style attribute to div tag. This works for me.

```html
<div class="blog-post" style="color: red;">
```

![screenshot from 2018-07-22 18-38-20](https://user-images.githubusercontent.com/8542502/43045238-39a93126-8ddf-11e8-8c7e-6fd6b78d4a13.png)

**Comment by dikiaap** [comment] 2018-07-22 13:01
@mahmoud-coo6 Does your method work on [Apply a Style Until a Condition is Met with @while](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/)?
I have a warning here: `Your .text-1 class should have a font-size of 5px.`
I'm pretty sure the font-size is 5px.

**Comment by flyfishingbarbara** [comment] 2018-07-25 23:44
i had add background style to the div tags..... to get these bugged sass challenges to pass their test....!!
```
<div class="blue-bg" style="background-color: blue"></div>
<div class="black-bg" style="background-color: black"></div>
<div class="red-bg" style="background-color: red"></div>
```

**Comment by mahmoud-coo6** [comment] 2018-07-27 12:17
here the solution @flyfishingbarbara  : there some time not worked because there is bug in website
<style type='text/sass'>
  
  @each $color in blue,black, red {
  .#{$color}-bg { background-color: $color;}
}
  
  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
![35435](https://user-images.githubusercontent.com/25306641/43320117-06bcf3d6-91b0-11e8-9871-af2dbcdeb60f.png)

**Comment by drex44** [comment] 2018-08-27 05:05
the issue is back with `@for` and `@each`.
![screenshot_2018-08-27 sass use for to create a sass loop learn freecodecamp](https://user-images.githubusercontent.com/5825883/44641510-da9a8f00-a9e4-11e8-85cc-3fa7b51b9492.png)

![screenshot_2018-08-27 sass use each to map over items in a list learn freecodecamp](https://user-images.githubusercontent.com/5825883/44641479-ba6ad000-a9e4-11e8-9655-33014b22b3aa.png)

**Comment by Rock-son** [comment] 2018-09-04 11:27
It wouldn't work on Chrome 68.0.3440.106 and not on Opera 55.0 but it worked flawlessly on Firefox 59.0.2 (all 64-bit). Last three exercises did need a bit of "Run the Test" button spaming though

**Comment by paulywill** [comment] 2018-10-31 21:05
@raisedadead @ValeraS 
Does this close this issue? 
https://github.com/freeCodeCamp/freeCodeCamp/pull/27716

**Closed** 2018-11-01 01:47 UTC
Labels: hacktoberfest, help wanted, type: bug, type: critical path

**Comment by ZTYZZ** [comment] 2019-03-24 02:11
lol,  I met the same problem...

**Comment by RandellDawson** [comment] 2019-03-24 02:43
@ZTYZZ Do you experience the same problem on the [beta site](https://www.freecodecamp.rocks/learn/front-end-libraries/sass/)?

**Comment by nmichalakis** [comment] 2019-12-04 15:01
On Firefox Developer Edition (72.0b2 (64-bit)) it does not work.

**Comment by RandellDawson** [comment] 2019-12-04 15:29
@nmichalakis What errors are you seeing in the browser console?

**Comment by nmichalakis** [comment] 2019-12-04 20:30
@RandellDawson i found the "bug" if there is a space between the variable name and the ":" it does not compile correctly. Is this something that happens on plain .scss files too? 
So for example if i run 
$var-name : color; (a space before and after ":" ) it does not compile but if i run the same
$var-name: color (no space right after $var declaration, it works!)
![Screenshot 2019-12-04 at 22 30 18](https://user-images.githubusercontent.com/25632631/70178881-b3e9fe80-16e5-11ea-8c31-cd9d92c03b25.jpg)
![Screenshot 2019-12-04 at 22 26 46](https://user-images.githubusercontent.com/25632631/70178883-b3e9fe80-16e5-11ea-85c7-45229991bffe.jpg)

**Comment by raisedadead** [comment] 2019-12-05 16:35
Please open a fresh issue with these details. Thanks.

**Comment by Ukmandal** [comment] 2020-06-19 04:59
SASS use-each-to-map-over-items-in-a-list beta challenge impossible
---------------------------------------------------------
@each $color in blue, black, red {
.#{$color}-bg {background-color: $color;}
}
