### ISSUE TITLE
Sass - Store Data with Sass Variables: Tests are bugged (also possible typo)

### ISSUE THREAD

**Issue by Oddert** [freeCodeCamp/freeCodeCamp#17366] opened 2018-06-01 11:27 UTC
I wasn't sure if this should be opened as a new issue given its the same as this closed one from the beta course, apologies if this is a duplicate.
https://github.com/freeCodeCamp/freeCodeCamp/issues/12699

#### Describe your problem and - if possible - how to reproduce it
An issue with 'Sass - Store Data with Sass Variables' has reemerged on the new Sass section (non beta). Adding the '$text-color' variable and assigning the color red changes the output but when the test runs, it can detect the variable is used but does not recognize that the elements now have a color of red.

Also there is a minor typo with the console markdown, showing two close 'code' tags. Both issues are shown in the screenshot.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10 Home (Version 1803)

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/23362989/40837709-3dd0d520-6593-11e8-9e6d-66b67639759d.png)

**Comment by ahmadabdolsaheb** [comment] 2018-06-01 14:43
Thanks @Oddert for reporting and looking into this issue. The tests need to be refactored. I am closing this as a duplicate of #12699 so it could addressed properly.  Happy coding!

**Closed by ahmadabdolsaheb** 2018-06-01 14:43 UTC
