### ISSUE TITLE
Stacked Methods Do Not Pass with removeJSComments

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41951] opened 2021-04-30 13:45 UTC
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array

Forum post: https://forum.freecodecamp.org/t/bug-found-in-this-challenge/458226

Is some part of the code processing chain causing this challenge to fail with the following code?

This fails

```
var filteredList = watchList.map(movie => ({
   title: movie["Title"],
   rating: movie["imdbRating"]
}))
.filter(r => {
  return parseFloat(r.rating) >= 8.0;
})
```

This passes:
```
var filteredList = watchList.map(movie => ({title: movie["Title"],rating: movie["imdbRating"]})).filter(r => {
  return parseFloat(r.rating) >= 8.0;
})
```

The match for .filter is failing. But it doesn't seem to me like it should be the regex that is the issue `assert(code.match(/\.filter/g));` so maybe we inadvertently broke something, somehow?

**Comment by Sembauke** [comment] 2021-04-30 15:16
It fails because the  `code.match(/\.filter/g)` is not looking for inlined possibilities.

filter is inlined:
`````
}))
.filter(r => {
  return parseFloat(r.rating) >= 8.0;
}) 
```

**Comment by ShaunSHamilton** [comment] 2021-04-30 16:41
To those confused by the error, I believe is was introduced in https://github.com/freeCodeCamp/freeCodeCamp/pull/41873 as mentioned here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39925

Essentially, the transpiled code is converted to something like:
```javascript
watchList.map().
  filter();
```

**Comment by lasjorg** [comment] 2021-04-30 17:20
@ShaunSHamilton Are we sure no other code is affected by this? I mean our test code might not trigger it as seen with this challenge (I assume the tests would have failed otherwise).

**Comment by ShaunSHamilton** [comment] 2021-04-30 18:01
> Are we sure no other code is affected by this?

@lasjorg No, we are not. However, it comes up on the forum so rarely.

**Comment by gikf** [comment] 2021-04-30 18:04
I can confirm one commit earlier than commit from https://github.com/freeCodeCamp/freeCodeCamp/pull/41873 - https://github.com/freeCodeCamp/freeCodeCamp/commit/ebe8f9934580f453531829a265969283c76c7514 doesn't have this issue.

**Comment by gikf** [comment] 2021-04-30 18:46
Here's list of challenges, using similar match pattern, which can be affected depending how one format their code. 22 in total.

- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-last-character-in-a-string.md (1 hit)
	Line 42
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string.md (1 hit)
	Line 42
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/add-elements-to-the-end-of-an-array-using-concat-instead-of-push.md (2 hits)
	Line 33
	Line 39
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs.md (1 hit)
	Line 34
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/combine-an-array-into-a-string-using-the-join-method.md (2 hits)
	Line 30
	Line 36
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/combine-two-arrays-using-the-concat-method.md (1 hit)
	Line 28
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype.md (1 hit)
	Line 32
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype.md (1 hit)
	Line 28
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/remove-elements-from-an-array-using-slice-instead-of-splice.md (2 hits)
	Line 33
	Line 39
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/return-part-of-an-array-using-the-slice-method.md (1 hit)
	Line 31
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.md (1 hit)
	Line 48
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/split-a-string-into-an-array-using-the-split-method.md (1 hit)
	Line 36
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-every-method-to-check-that-every-element-in-an-array-meets-a-criteria.md (1 hit)
	Line 33
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.md (1 hit)
	Line 49
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md (1 hit)
	Line 61
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data.md (1 hit)
	Line 69
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-some-method-to-check-that-any-elements-in-an-array-meet-a-criteria.md (1 hit)
	Line 33
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.md (2 hits)
	Line 42
	Line 42
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/extract-matches.md (1 hit)
	Line 54
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-anything-with-wildcard-period.md (1 hit)
	Line 34
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end.md (1 hit)
	Line 30
- https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/use-capture-groups-to-search-and-replace.md (1 hit)
	Line 40

**Comment by nhcarrigan** [comment] 2021-04-30 18:47
@gikf thanks for the list. 

I might go ahead and look in to the option the `generator` has to not add white-space for formatting.

**Comment by ojeytonwilliams** [comment] 2021-04-30 21:37
One option would be to keep a copy of the original user code around as another variable. Would that help at all?

Unfortunately I don't think Babel can *only* remove comments with zero side-effects.

**Comment by lasjorg** [comment] 2021-05-01 02:19
@ojeytonwilliams @nhcarrigan Did we look at other libraries?

I tested a tiny bit using [strip-comments](https://www.npmjs.com/package/strip-comments) and it seemed to work. I only tested the challenge from this issue (without the PR) and the other challenge linked to in the other issue and then I just ran the `test:curriculum` script. Not really sure how to test it.

**Comment by ojeytonwilliams** [comment] 2021-05-01 06:19
@lasjorg  Nope, I don't think so. That library looks promising though.

For testing purposes we could simply write unit tests that include strings that we know the old, Babel, approach modified and see if the new library handles them correctly.

Would you be interested in creating a PR?

**Comment by lasjorg** [comment] 2021-05-01 16:54
@ojeytonwilliams I tested the lib against the unit tests we have (`npm test`). It is preserving the indentation before/after the comment which the tests do not expect (fails removeJSComments tests 2 and 4). Preserving the indentation and whitespace does seem more correct even if it leaves the code with some odd formatting. It literally just removes the comments and doesn't touch any whitespace (as far as I can tell).

Input:

```
function nonMutatingPush(original, newItem) {
  /* This is a 
    multi-line comment 
    that should be removed. */
  return original.push(newItem);
}
```

Output:

```
function nonMutatingPush(original, newItem) {
    return original.push(newItem);
}
```

The 4 space indentation is the 2 in front of the comment block and the 2 before the return statement.

The library comes with [unit tests](https://github.com/jonschlinkert/strip-comments/blob/master/test/JavaScript.js) which I would expect covers a lot of cases.

---

I will create PR so we can better test it.

**Comment by lasjorg** [comment] 2021-05-04 17:59
Looks like another one: https://forum.freecodecamp.org/t/command-chaining-bug-in-functional-programming-section-possible-incorrect-solution/458829

The first solution on the hints page to [Use the reduce Method to Analyze Data](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data) is failing.

**Comment by Sembauke** [comment] 2021-05-13 08:18
Closing this, tracking further in  #42101

**Comment by ShaunSHamilton** [comment] 2021-05-31 18:10
Reopening as related to a different fix.

**Comment by ShaunSHamilton** [comment] 2021-05-31 18:16
For those wanting to help with this, the quick fix is to update the regex tests in [these lessons](https://github.com/freeCodeCamp/freeCodeCamp/issues/41951#issuecomment-830292785) to allow for white space between the `.` (period) and method name.

_Note: Every lesson must be updated, before this issue can be closed_

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by lasjorg** [comment] 2021-05-31 23:16
@ShaunSHamilton This should get fixed with https://github.com/freeCodeCamp/freeCodeCamp/pull/42254 which is a comment removal implementation using our [own fork](https://github.com/freeCodeCamp/strip-comments) of the strip-comments lib.

**Comment by Sembauke** [comment] 2021-06-01 09:34
> @ShaunSHamilton This should get fixed with #42254 which is a comment removal implementation using our own fork of the strip-comments lib.

can this still be closed then?

**Comment by ShaunSHamilton** [comment] 2021-06-01 13:52
@Sembauke Thank you, for keeping up with this. I was a bit out of the loop with what was happening between this issue and the Safari issue. I will close this, once tested on `.dev`

**Comment by ShaunSHamilton** [comment] 2021-06-01 16:01
I have tested on staging, and the original issue appears to have been resolved. Thank you, all involved 🎉

**Closed by ShaunSHamilton** 2021-06-01 16:01 UTC
Labels: help wanted, scope: curriculum, type: bug
