### ISSUE TITLE
Cursor can't select the last line of the code when initially typing

### ISSUE THREAD

**Issue by mmargarita94** [freeCodeCamp/freeCodeCamp#14160] opened 2017-03-30 21:32 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/create-a-form-element
However, this issue has come up on all of my challenges. It didn't happen at first, but then it started happening some challenges ago and persisted, though I'm not sure on which one specifically.

#### Issue Description
Whenever I begin the challenge and try to start typing the code, the cursor will not move to the last line of the code. For example, on this challenge the last line of the code is [<input type="text" placeholder="cat photo URL">]. When I try to select this element or I try to place my cursor somewhere in the middle of it (say, on the word 'text'), the cursor won't move and I can't select. It only begins working properly when I hit backspace as though to delete the element. That's when the browser suddenly recognizes the element and then I can freely move the cursor. Also, it should be noted that when I do hit backspace on the line before this input element, the browser deletes not something from the previous line but something from the bugged line below. 

#### Browser Information

* Browser Name, Version: Chrome,  57.0.2987.110
* Operating System: MacOS Sierra, 10.12.4
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<form action="/submit-cat-photo">
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text" placeholder="cat photo URL">


```

**Comment by erictleung** [comment] 2017-03-30 23:44
@mmargarita94 sounds like your issue is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. Please take a look at the issue thread over there for some work arounds. Happy coding!

**Closed by erictleung** 2017-03-30 23:44 UTC
