### ISSUE TITLE
Infinite loop in components triggers crash

### ISSUE THREAD

**Issue by Nicolascrd** [freeCodeCamp/freeCodeCamp#40287] opened 2020-11-22 09:43 UTC
**Describe your problem and how to reproduce it:**
If one component ask for another one and the other one asks for the first, it's an infinite loop.
In the JS/Algorithms challenges, FCC signals the user that he is creating a infinite loop, but that's not the case in React with component calling each other.
I don't if it it the same everywhere but when I do this, my computer crashes. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/pass-props-to-a-stateless-functional-component

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox 
* Browser Version: 82.0.3
* Operating System: Ubuntu 20.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by DhairyaBahl** [comment] 2020-11-22 15:06
@Nicolascrd I would like to work on this issue. kindly assign it to me. Thank you !! :)

**Comment by Sky020** [comment] 2020-11-22 15:06
Thank you, for taking the time to report this. We are aware of this.

As such, I am closing this issue as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36118

**Closed by Sky020** 2020-11-22 15:06 UTC
Labels: scope: learn, status: needs help for triage

**Comment by ieahleen** [comment] 2020-11-22 18:13
@DhairyaBahl The issues are not assigned, but only the issues with "help wanted" or "first timers
only" are up for grubs and the first comprehensive pull request is reviewed - check our contributing guidelines at contribute.freecodecamp.org

**Comment by ojeytonwilliams** [comment] 2020-11-22 23:18
Just to expand a little on what @ieahleen said, the original issue https://github.com/freeCodeCamp/freeCodeCamp/issues/36118, is tagged with "help wanted".  If you'd like to help, please take a look at that issue.  There's a fair bit of discussion about what's happening and how it might be solved.

**Comment by DhairyaBahl** [comment] 2020-11-23 06:35
@ieahleen Thanks you for telling me . I will read the contributor guidelines which I forgot to read. :)
