### ISSUE TITLE
Beta: "Show my Public Profile" button isn't working properly.

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15188] opened 2017-06-03 09:14 UTC
Whenever I try to click on "Show my public profile" button, it redirects me to the "Map" section of the website, with an error Toast - "Something went wrong".
![image](https://cloud.githubusercontent.com/assets/29104610/26752330/184847d4-486b-11e7-9fbc-7c97b48ff8a6.png)

**Comment by IshtmeetSinghRissam** [comment] 2017-06-03 13:46
It logs me out too, on the same tab, but cookies/cache session might still be available so it doesn't logs me out from other tabs. But, when I refresh - I am logged in again automatically.

**Comment by systimotic** [comment] 2017-09-04 10:37
Thanks for reporting this issue! 
I'm closing this as a duplicate of #13075. Happy coding!

**Closed by systimotic** 2017-09-04 10:37 UTC
Labels: beta
