### ISSUE TITLE
code not accepted because comments contain switch statement

### ISSUE THREAD

**Issue by mmclau14** [freeCodeCamp/freeCodeCamp#15529] opened 2017-06-25 22:16 UTC
#### Issue Description

challenge not accepted even though it is correct.

#### Browser Information

* Browser Name, Version: Chrome: 58.0.3029.110
* Operating System: OSX: Sierra
* Mobile, Desktop, or Tablet: Desktop / Laptop

#### Your Code

```js

// Setup
function phoneticLookup(val) {
//   var result = "";

  // Only change code below this line
  var hash = {
    alpha:"Adams",
    bravo:"Boston",
    charlie:"Chicago",
    delta:"Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
//   switch(val) {
//     case "alpha": 
//       result = "Adams";
//       break;
//     case "bravo": 
//       result = "Boston";
//       break;
//     case "charlie": 
//       result = "Chicago";
//       break;
//     case "delta": 
//       result = "Denver";
//       break;
//     case "echo": 
//       result = "Easy";
//       break;
//     case "foxtrot": 
//       result = "Frank";
//   }

  // Only change code above this line
  return hash[val];
}

// Change this value to test
phoneticLookup("charlie");



```

**Comment by MiloATH** [comment] 2017-06-26 03:19
This issue has appeared in other challenges. There was a promising potential solution using AST traversal, but I don't think it was ever added #11456. The other option was to use a more clever regex to take this into account. This was discussed as well #11360.

**Comment by tommygebru** [comment] 2017-06-26 15:57
@mmclau14 try to compare the commented switch statement with your current code again, at a glance I can see that most of the `arguments ` are not within parentheses this may be the problem you are facing 
- For more help try sharing your code and ask for hints, tips, and code review in the [Freecodecamp Chatrooms](https://gitter.im/FreeCodeCamp/home) found here, specifically you want to join[ HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript)

Happy Coding! :tada: :smile: :tada:

**Comment by MiloATH** [comment] 2017-06-26 21:27
@tommygebru The code is valid. The tests use regex to check the code. So the code in the comments is failing the test.

**Comment by erictleung** [comment] 2017-06-26 21:30
@mmclau14 thanks for the issue. This appears to be a duplicate of older issues that @MiloATH has pointed out (thanks for searching for them!). Closing as a duplicate issue. Happy coding!

**Closed by erictleung** 2017-06-26 21:30 UTC

**Comment by mmclau14** [comment] 2017-06-27 13:00
ya. the code is definitely valid and i was able to test simply by removing the commented block. thanks for the quick response guys!
