### ISSUE TITLE
Instructions disappear when entering comment block

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1808] opened 2015-08-16 23:39 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue:

When I open a comment block with '<!--', the numbered instructions disappear.

**Comment by michael-krebs** [comment] 2015-08-16 23:55
duplicate of #1672

**Closed** 2015-08-26 00:14 UTC
