### ISSUE TITLE
Testing objects for properties

### ISSUE THREAD

**Issue by CoderBug** [FreeCodeCamp/FreeCodeCamp#10847] opened 2016-09-22 09:46 UTC
![s](https://cloud.githubusercontent.com/assets/22156630/18743592/93a2007a-806e-11e6-8b1d-ee17141a21b7.png)
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20if%20(myObj.hasOwnProperty(checkProp)%20%3D%3D%3D%20true)%20%7B%0A%20%20%20%20return%20myObj%5BcheckProp%5D%3B%0A%20%20%7Delse%0A%20%20return%20%22Not%20found%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22house%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp) === true) {
    return myObj[checkProp];
  }else
  return "Not found";
}

// Test your code by modifying these values
checkObj("house");

```
submitting "house" results in "Not found" but it wont pass me :/

**Comment by Bouncey** [comment] 2016-09-22 11:12
@CoderBug The devil is in the details. 

Please check your code against the require return values. 

You are almost there, but our tests are really choosy about what should be capitalised and what shouldn't.

I am closing this issue as it is for code help, and not an issue with freeCodeCamp itself

Happy coding and thanks for contributing :tada:

**Closed by Bouncey** 2016-09-22 11:12 UTC

**Comment by LakunleD** [comment] 2016-09-25 18:13
The problem is the  letter F  in "Not Found". Change it to UpperCase F and it would pass

**Comment by saitejs** [comment] 2016-11-01 14:30
add double quotes on checkProp like this =>  "checkProp" in your if statment

**Comment by rudyg123** [comment] 2016-11-08 02:53
Note: checkProp should not be enclosed in quotes because the if statement evaluates the variable which contains the string to be evaluated vs. the string literal "checkProp."
