### ISSUE TITLE
console.log of an array is misleading

### ISSUE THREAD

**Issue by ozgunbal** [freeCodeCamp/freeCodeCamp#34417] opened 2018-11-22 07:06 UTC
**Describe the bug**
In the challenge pages, console.log of an array logged without brackets. It avoids to understand if array is nested or not:
```js
console.log([1,2,3,4]);
// 1,2,3,4
console.log([[1,2],[3,4]])
// 1,2,3,4
```

**To Reproduce**
1. Go to any challenge with an editor (e.g: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/copy-an-array-with-the-spread-operator)
2. `console.log([[1,2],[3,4]])`
3. Observe the console

**Expected behavior**
Showing brackets in the console.

**Screenshots**
![fcc-array-console-bug](https://user-images.githubusercontent.com/16080180/48886727-1c00d600-ee3e-11e8-8ce0-440cda294652.png)

**Desktop**
 - OS: Ubuntu 18.04 LTS
 - Browser Firefox
 - Version 63.0

_and_

 - OS: Windows 10
 - Browser Google Chrome
 - Version 70.0

**Comment by thecodingaviator** [comment] 2018-11-22 14:43
I don't think this is an error with our system at FCC. This is an error in the code-compiler that we implement. Maybe @Bouncey can elaborate on this

**Comment by matkoniecz** [comment] 2018-11-24 05:17
What is the behaviour of standard browser consoles in Chrome and Firefox?

**Comment by thecodingaviator** [comment] 2018-11-24 06:18
Chrome:
![image](https://user-images.githubusercontent.com/34807532/48965194-c31c7380-efde-11e8-85b2-aa4f3ec43647.png)

**Comment by Bouncey** [comment] 2018-12-06 11:10
Well, isn't that interesting...

Thanks for reporting this bug. This would be an issue with `proxyLogger`.

**Comment by generally23** [comment] 2018-12-31 20:00
not a bug though. works as expected for me in all powerful browsers

**Comment by mohanrajoria** [comment] 2019-02-26 17:30
@thecodingaviator Right, its not an issue with FCC, instead it should be fixed in MonacoEditor.

**Closed** 2019-03-01 14:43 UTC
Labels: help wanted, platform: client, type: bug
