### ISSUE TITLE
Global variable conflicts with algorithm.

### ISSUE THREAD

**Issue by krishnakumar360** [freeCodeCamp/freeCodeCamp#9199] opened 2016-06-17 11:04 UTC
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20count%3D1%3B%0Afunction%20factorialize%28num%29%20%7B%0A%20%20for%28var%20i%3D1%3B%20i%3C%3Dnum%3Bi%2B%2B%29%7B%0A%20%20%20%20%0A%20%20%20%20count%3D%20count%20*%20i%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20return%20count%3B%0A%20%20%0A%7D%0A%0Afactorialize%280%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var count=1;
function factorialize(num) {
  for(var i=1; i<=num;i++){

    count= count * i;

  }
  return count;

}

factorialize(0);

```

**Comment by raisedadead** [comment] 2016-06-17 11:18
@krishnakumar360 : Thanks for reporting this.

Your code is correct but using the `var count=1` in the global scope is causing the test cases to fail.
Moving it to the function's scope should let you pass the challenge.

```js
function factorialize(num) {
  var count = 1;
  for(var i=1; i<=num; i++) {
   count = count*i;
...
```

The reason being that we run multiple test cases in on the code, using a global var like this persists the last value and hence the test cases fail.

Nevertheless this is valid code and we should be addressing this.

**Comment by BKinahan** [comment] 2016-06-21 13:30
@raisedadead Is it truly valid code? Functions should be reusable in many cases, and users should learn about side effects caused by operating on global variables.

**Comment by flipsyde606** [comment] 2016-06-21 13:36
@raisedadead I concur with @BKinahan. Maybe we can have two calls to factorialize() in the challenge to explicitly portray the effects of using global variables in functions, if used.

**Comment by BKinahan** [comment] 2016-06-21 13:52
Note that almost all of the algorithm challenges do not work if global variables are used, the only exception that comes to mind being Counting Cards which sets up a global variable for the user to illustrate a case when it is useful to track a value between function calls (and there it is reset between *sets* of function calls in each test). 

Any changes to be made here regarding global variables or how the user should be made aware of them as @flipsyde606 suggests would need to justify a change to most of the other similar challenges.

**Comment by raisedadead** [comment] 2016-06-21 14:09
> Maybe we can have two calls to factorialize() in the challenge to explicitly portray the effects of using global variables in functions, if used.

@flipsyde606 @BKinahan thanks a lot for the inputs.

While you guys are correct, this challenge may not be the correct place to illustrate that thought, and as @BKinahan has already noted, this being true for almost all challenges we would have to add a case to all challenges which doesn't make sense.

So, we should be handling the global variable declarations in the code runner (just like we check for loops) and possibly throw an error on the console? (with the exceptions of course for challenges that truly require global vars)

/cc @FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment] 2016-07-12 18:18
Do we have a way forward with this?

**Comment by BKinahan** [comment] 2016-07-20 19:02
I don't think there's an easy solution to this. 

It doesn't seem feasible to detect a global variable declaration and throw an error as @raisedadead suggested since valid code such as this would cause a false positive:
```js
var count;
function factorialize(num) {
  count = 1;
  for(var i=1; i<=num;i++){
    count= count * i;
  }
  return count;
}
```
(As long as the variable is assigned an initial value with the function before use as an operand, it works correctly regardless of global declaration, with or without initialization. I can't think of a way to detect that.)

The best we can do in that regard is probably to ensure that there is sufficient reinforcement of the concepts of scope and side-effects early in the algorithm section of the course, and continue not passing code that is not reusable due to improperly handled variables.

In terms of something practical that can be applied across all the challenges, it may be worthwhile to consider changes to what output users see when running tests.

Currently a user who includes a function call at the end of the code editor will see the output for that call. For example, `factorialize(5)` will correctly output 120 and display it, and yet the test for the input `5` will be marked as incorrect because of the other calls before it. But the user doesn't see these calls or their effects, so they can only conclude that there is a problem with the tests, especially as they try the other inputs and confirm that their code works correctly. (Notably, if the user does not include a function call in the editor, the output varies depending on any other code in the editor, eg blank for the example above or `1` if `var count;` is replaced by`count = 1;` ).

So the only way a user with a problematic global variable in their code can stumble upon the source of the problem is by including multiple function calls in their editor (a similar process to what @flipsyde606 mentions above) and seeing the incorrect output.

All of that is to say, it may be useful to alter the output display to include input-output pairs to illustrate what results the tests are *actually* giving when they are run as a full set, for example:
(with correct code):
```js
factorialize(5): 120
factorialize(10): 3628800
factorialize(20): 2432902008176640000
factorialize(0): 1
```
(and with a problematic global variable):
```js
factorialize(5): 120
factorialize(10): 435456000
factorialize(20): 1.0594217768725671e+27
factorialize(0): 1.0594217768725671e+27
```
(though these may be off by a factor of 120; I believe there's another call to `factorialize(5)` to make sure it's a number, which in itself may be a reason to run that test *after* all the others...)

A user would immediately see that these numbers are way off, even if they don't immediately connect the dots about the cause, and will probably (hopefully) ask about their code in a help chat rather than assuming a bug in the challenge and reporting an issue.

There are problems with this approach as a general solution. Some challenges have a large number of tests, or long outputs, which would not be easily displayed in the output section. Still, it may be a useful addition to certain challenge tails, particularly if they have a recurring confusion about global variable use and a few custom output lines could illustrate the problem clearly.

Hopefully this was readable and useful 😄

**Comment by raisedadead** [comment] 2016-07-20 19:26
@BKinahan thanks again for looking into this, and whoa that was a huge post. However I think we can try a hack for this, I'll have to double check and get back on this but to the best of my knowledge the final code that is asserted for each test case runs within an `eval` method.

So it is possible (theoretically speaking) to append `//# sourceURL=functionNameXX` where `XX` is an incremental no added to the function name in discussion, at the top of the seed code.

This will enforce a challenge execution in separate execution context for each `eval` (chrome for instance will do this in separate VMs)

Maybe hackish but should do the trick.

**Comment by raisedadead** [comment] 2016-07-20 19:28
And if this doesn't then we can wrap the entire seed code within a named container functions.

**Comment by Locheed** [comment] 2016-07-28 09:55
Just spend some time figuring out why my test fails and it was this problem with a global variable.

Just a thought, how about adding a note to descriptions, that "Using global variables in this test will cause the test to fail." I think it's would help in this kinda situation, but doesn't give too many tips for an exercise.

**Comment by wjhurley** [comment] 2016-12-11 09:04
Should this issue be closed?

**Comment by raisedadead** [comment] 2016-12-11 12:19
> Should this issue be closed?

Nope we need a way to detect global variables, stop the execution of tests and show a warning to users why the code can't be run.

or

Execute the tests in some isolated mechanism , that avoids this conflict.

**Comment by systimotic** [comment] 2017-01-22 20:41
Hi all! It looks like this issue is a duplicate of #9063, so I'll close this in favour of that. If I got this wrong, please reopen!

**Closed by systimotic** 2017-01-22 20:41 UTC
Labels: discussing, help wanted
