### ISSUE TITLE
jQuery broken test

### ISSUE THREAD

**Issue by sparsh-99** [freeCodeCamp/freeCodeCamp#38980] opened 2020-06-01 02:29 UTC
**Describe your problem and how to reproduce it:**
1. Write your code
2. Click 'Run the Tests'
3. When it passes all your tests, again click on 'Run the Tests'
4. This time, it will show an error.

#### Note:- Error may not be generated from the second time clicking. So, go for 3rd time, the error will definitely come up.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/jquery/target-html-elements-with-selectors-using-jquery

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 83.0.4103.61
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**1st-time click on 'Run the Tests'**

![Screenshot (489)](https://user-images.githubusercontent.com/56729873/83370545-62dd6d80-a3dd-11ea-86d1-1bd4767b3e76.png)

**2nd-time click on 'Run the Tests '**

![Screenshot (490)](https://user-images.githubusercontent.com/56729873/83370598-84d6f000-a3dd-11ea-8c4c-20b1250cdf58.png)

### Additional Context:
I would love to work on it. Please assign it to me
Thank You

**Comment by Sky020** [comment] 2020-06-01 11:41
Hello there,

This issue has been discussed on: https://www.freecodecamp.org/forum/t/problem-with-jquery-remove-classes-from-an-element-with-jquery/396303

And, if you are passing the tests, and returning to fail, it is not much of an issue. So, I will leave the same comment as I did in the forum:
>To solve, refresh the page. Perhaps, it might be useful to some, if the tests and seed code were rewritten, but refreshing the page, and ensuring the code is correct is a suitable fix.

I will leave this issue open, but, seeing as this challenge has existed for a long time, this issue rarely arises, and the workaround is as simple as refreshing, I do not recommend a PR be opened for this.

**Comment by sparsh-99** [comment] 2020-06-01 17:05
Okay

**Comment by ojeytonwilliams** [comment] 2020-06-01 17:54
While I agree that this isn't the highest priority (as there is a work around), it's still a bug.  Someone should not have to refresh the page to reliably pass the tests.

That said, it might not be easy to fix.  It's possibly a case of re-writing the tests to be async and `await`ing `$(document).ready()` in the tests, but I'm not sure.

**Comment by hassaanp** [comment] 2020-06-02 08:29
I believe this should be fixed with the following assert:
```
assert($(document).ready(function() {$(".btn-default").length === 0}));
```

**Comment by ojeytonwilliams** [comment] 2020-06-02 10:27
Unfortunately not, since that is basically `assert(anObject)` which passes.  `testString` needs to return an async function.

**Comment by hassaanp** [comment] 2020-06-02 11:09
oh yeah, you are right, my bad.

what about enclosing the assert inside the `document.ready` method?

**Comment by Sky020** [comment] 2020-06-02 11:52
I am unable to reproduce this locally. Is there a chance that there is some cache reason for this behaviour?

**Comment by hassaanp** [comment] 2020-06-02 11:57
Yes it cant be reproduced locally. I dont think its a cache issue. I believe the latency is too less - the document is loaded instantly whereas the actual environment is slower so we are able to get the mentioned behavior.

**Comment by ojeytonwilliams** [comment] 2020-06-03 12:44
I am curious as to what's going on here.  My suspicion is that it's a timing issue, that for some runs the test gets evaluated before `document.ready`, but I'm not sure.

> what about enclosing the assert inside the `document.ready` method?

Since document ready is asynchronous, the assert will be called at some point after the test has already passed.  Take a look here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/1244e9775f664707bc54d5f977a9b29a34615784/client/src/client/frame-runner.js#L63-L67
you can see if the test throws during the initial (synchronous) evaluation, the error is caught and the test fails.  If instead it doesn't throw and returns a function, then that function should return a Promise.  Finally that Promise is `await`ed.  If it doesn't throw, then the whole thing passes.

The formulation you're talking about won't throw during the first evaluation and does not return a function to be awaited.  It should (I think) always pass.

**Comment by ojeytonwilliams** [comment] 2020-06-05 14:03
Given that this has been reported for several challenges, I think it's reasonable to assume that all the challenges that rely on `document.ready` could have the problem.

**Comment by hassaanp** [comment] 2020-06-09 06:54
@ojeytonwilliams agreed. It would be interesting to figure out a fix for this. I will try on my end but I hope other contributors are actively looking for ways to resolve this.

**Comment by ojeytonwilliams** [comment] 2020-06-09 07:25
Yep, it would be good to understand why this is happening.  That may not be easy to discover, though, so I'd be happy with a PR that just modifies the tests to wait for `document.ready`.

**Comment by lasjorg** [comment] 2020-06-14 04:47
Some observations:

1. If I have Disable Cache turned on under the network tab it always works for me. If I disable it, I can make the tests reliably fail.

2. As long as all the files have 0ms delay (memory cache) the test fails, the minute a vendors~chai js file has just a 1ms delay it passes the test (disk cache vs memory cache), [demo gif](https://imgur.com/a/Q12NjzF).

3. The two challenges that are not using jQuery for the assert tests always pass for me. Not sure if it's simply the DOM querying that is the issue, or jQuery itself.

https://www.freecodecamp.org/learn/front-end-libraries/jquery/delete-your-jquery-functions
https://www.freecodecamp.org/learn/front-end-libraries/jquery/learn-how-script-tags-and-document-ready-work


How is the browser cache locally disabled? It always does a network fetch and is never fetching from disk or memory. Can that be disabled?

As far as I can tell because there is always a fetch delay locally the tests never fail. Which makes it hard to test.

**Comment by ojeytonwilliams** [comment] 2020-06-14 09:56
Nice QAing @lasjorg!

Presumably that tiny delay is enough for all the changes to appear in the DOM.

> How is the browser cache locally disabled? It always does a network fetch and is never fetching from disk or memory. Can that be disabled?

Good question.  I tried building the site (`npm run build:client`) and serving it using [serve](https://github.com/vercel/serve), but it's still not cached.  It might be getting cached when you use .org because of the cdn, but I'm not sure.  If that's right, it's something that we will have to deploy to test.

**Closed** 2020-06-15 13:11 UTC
Labels: scope: learn, status: discussing, status: fix in progress

**Comment by ojeytonwilliams** [comment] 2020-06-16 08:28
I'm pretty sure this is now fixed on .dev - I can no longer reproduce the problem. @lasjorg could take a quick look and confirm/deny?

**Comment by lasjorg** [comment] 2020-06-16 18:33
@ojeytonwilliams Nice job, all the jQuery challenges pass for me now. Ran all of them in Chrome and a few in Firefox. Passed first try every time. :+1:

**Comment by ojeytonwilliams** [comment] 2020-06-16 20:52
Nice. Thanks for all your help. Looks like we've got to the bottom of it.
