### ISSUE TITLE
Video attached to "Data Visualization Projects: Visualize Data with a Bar Chart" isn't working

### ISSUE THREAD

**Issue by mmullen200** [freeCodeCamp/freeCodeCamp#15483] opened 2017-06-22 15:43 UTC
<img width="842" alt="screen shot 2017-06-22 at 8 41 36 am" src="https://user-images.githubusercontent.com/12685280/27443028-c2f8e0f2-5726-11e7-9c69-b8bc995d130e.png">
Challenge [visualize-data-with-a-bar-chart](http://beta.freecodecamp.com/en/challenges/data-visualization-projects/visualize-data-with-a-bar-chart) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by albert2309** [comment] 2017-06-23 03:09
Correct video: 
https://www.youtube.com/watch?v=nss_5sZpjIE&t=5s

**Comment by mmullen200** [comment] 2017-06-23 03:22
That's not the correct video. The project in beta.freecodecamp.com doesn't
deal with GDP. The beta project also doesn't list any user stories.

**Comment by raisedadead** [comment] 2017-07-13 20:56
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12753

**Closed by raisedadead** 2017-07-13 20:56 UTC
