### ISSUE TITLE
babel preset causes challenge to fail with correct solution

### ISSUE THREAD

**Issue by nikrb** [freeCodeCamp/freeCodeCamp#34841] opened 2019-01-09 17:38 UTC
**Describe the bug**

[This Challenge](http://localhost:8000/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays) on latest master fails locally with the correct solution.
Curriculum test passes.

[The live challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays) passes ok.

came to light in this pr #26531. [Valera's comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/26531/#issuecomment-452721463)
> This is a problem with the used babel presets in the client application

**To Reproduce**
1. go to the challenge on local
2. enter the correct solution `[a, b] = [b, a]`
3. click the "Run the tests" button
4. Results window shows test fails (see screenshot below)

**Expected behavior**
test should pass with correct solution

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/16709534/50865256-db80fb80-139c-11e9-8ba3-dd1092457f81.png)
![screeny](https://user-images.githubusercontent.com/16709534/50865285-fbb0ba80-139c-11e9-837e-6ed7692a6cdb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS
 - Browser chromium
 - Version 68.0.3440.106 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Comment by ojeytonwilliams** [comment] 2019-03-08 14:47
@nikrb I just checked this out on rocks and my local machine and I can't reproduce it.  Are you still seeing the problem?

**Comment by RandellDawson** [comment] 2019-03-08 14:59
@nikrb I can confirm this is no longer an issue when testing locally and on freecodecamp.rocks, so I am closing this issue.

**Closed by RandellDawson** 2019-03-08 14:59 UTC
Labels: scope: curriculum
