### ISSUE TITLE
React and Redux: Use Provider to Connect Redux to React browser freezing 

### ISSUE THREAD

**Issue by krishnadevz** [freeCodeCamp/freeCodeCamp#38603] opened 2020-04-22 07:16 UTC
**when we go to solve React and Redux: Use Provider to Connect Redux to React browser freezing for seeing that issue do following things** 
```js
render(
return(
<AppProvider/>
)
)
```
* After doing above thing for testing react redux code browser is freezing and it happens with me second time we need to fix react compiler freezing problem

**Tell us about your browser and operating system:**
* Browser Name: firefox
* Browser Version: 75.0 (64-bit
* Operating System: Windows 10 home 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/42638797/79951376-31948800-8496-11ea-9539-3c630b672f92.png)🔽

**Comment by krishnadevz** [comment] 2020-04-22 07:46
```js
render(){
  return(
    <Provider store={store}>
    <DisplayMessages/>
</Provider>
  )
} 
```
**by above code challenge completes fine but after browser freezing we have open it in another browser that's all from my side**

**Comment by ojeytonwilliams** [comment] 2020-04-22 08:58
Hi, @krishnadevz, could you show the code that freezes the browser? I tried the above snippets and could not reproduce the problem.

Also, I suspect this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36118.  Is there anything different here?

**Comment by krishnadevz** [comment] 2020-04-22 09:05
![giddfdf](https://user-images.githubusercontent.com/42638797/79962867-3cefaf80-84a6-11ea-93ab-922e921ca253.gif)
not a difference but challenge is different that's all

**Comment by ojeytonwilliams** [comment] 2020-04-22 09:14
Thanks for confirming and providing the code - I see why it's freezing.  

Since it's the problem with recursion again, I'm closing this.  We can track the problem in https://github.com/freeCodeCamp/freeCodeCamp/issues/36118

**Closed by ojeytonwilliams** 2020-04-22 09:14 UTC
Labels: scope: curriculum, status: needs investigation
