### ISSUE TITLE
Int Algorithm Scripting "Missing Letter" - helpful links "String.charCodeAt()" link is incorrect

### ISSUE THREAD

**Issue by mathewjcohen** [FreeCodeCamp/FreeCodeCamp#8445] opened 2016-05-04 06:51 UTC
Intermediate Algorithm Scripting challenge "Missing Letter" - helpful links "String.charCodeAt()" url link is incorrect.

**Comment by theflametrooper** [comment] 2016-05-04 07:25
@mathewjcohen Duplicate of #8425. This will be fixed the next time we push `staging` to `master`! Sorry!

**Closed by theflametrooper** 2016-05-04 07:25 UTC
