### ISSUE TITLE
Dependency handling in boilerplates on Replit, and update status for Python Projects

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#46824] opened 2022-07-09 07:56 UTC
### Describe the Issue

When using boilerplate code forked to the replit, replit used to install dependencies on the first run using the _standard_ packager. That's not a case anymore for the boilerplates, probably due to some missing required configuration. Replit seems to have changed their dependency handling, relying more on the `replit.nix` file defining the environment. This affects both JS and Python boilerplates.

### JS

`npm install` seems to do the job, when run manually. It doesn't run when loading replit or pressing the _Run_ button.

### Python

Manual trying to use `poetry install` doesn't seem to work. Changing `replit.nix` (added by the replit on forking) and adding required modules to the `deps` does the trick, for example, the _Arithmetic Formatter_ requires adding
```
pkgs.python38Packages.pytest
```
_Medical Data Visualizer_ at least:
```
pkgs.python38Packages.pandas
pkgs.python38Packages.seaborn
```

I wasn't able to make poetry work, even after adding poetry package to the `replit.nix`, the `poetry install` installation was interrupted by error.

---

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter
https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/meet-the-node-console

### Your code

N/A

### Expected behavior

Ideally camper should not be required to make any manual actions to use the dependencies required by boilerplate.

### System

N/A

**Comment by RandellDawson** [comment] 2022-07-09 08:30
I forked the boilerplate or the Arithmetic Formatter project and add a `replit.nix` file that looks like:
```
{ pkgs }: {
  deps = [
    pkgs.python38Full
    pkgs.python38Packages.pytest
  ];
  env = {
    PYTHON_LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
      # Needed for pandas / numpy
      pkgs.stdenv.cc.cc.lib
      pkgs.zlib
      # Needed for pygame
      pkgs.glib
      # Needed for matplotlib
      pkgs.xorg.libX11
    ];
    PYTHONBIN = "${pkgs.python38Full}/bin/python3.8";
    LANG = "en_US.UTF-8";
  };
}
```
Next, I confirmed that using the import GitHub feature on repl.it did not change the `replit.nix` file in any way when it is imported and was able to run everything like it used to be.  So, I guess we just need to figure out what each boilerplate needs as far a `replit.nix` file and request help specifying what needs to be put into each one.

**Comment by gikf** [comment] 2022-07-09 08:57
For python boilerplates that would be:

https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter
```
pkgs.python38Packages.pytest
```

https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer
```
pkgs.python38Packages.pandas
pkgs.python38Packages.seaborn
```

https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator
```
pkgs.python38Packages.numpy
```

https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer
```
pkgs.python38Packages.pandas
```

https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer
```
pkgs.python38Packages.pandas
pkgs.python38Packages.seaborn
```

https://github.com/freeCodeCamp/boilerplate-sea-level-predictor
```
pkgs.python38Packages.pandas
pkgs.python38Packages.scipy
```

That's not exhaustive list, but some other dependencies are used by these modules (ie. matplotlib is used by seaborn), so they also will be installed.

**Comment by lasjorg** [comment] 2022-07-11 00:38
I made a few PRs but I might wait until I know if it's the correct fix or not. But every boilerplate I tried so far seems broken on import.

The language auto-detect on import is also failing on some of them. It looks like it is based on the percentage GitHub gives in the Languages statistics. If I add a `.gitattributes` and exclude the HTML files it fixes the auto-detect done by Replit.

.gitattributes
`*.html linguist-vendored`

Ref: https://proandroiddev.com/removing-noise-from-your-github-language-stats-e96113f8183d

**Comment by RandellDawson** [comment] 2022-07-11 17:21
To fix the issue for the Node challenges, I think we can just change the `.replit` file to be:
```js
language = "nodejs"
run = "npm install; npm start"
```

This will cause the import to occur when the Run button is clicked.

**Comment by lasjorg** [comment] 2022-07-12 01:21
I'm not sure there is much in the process that can be improved. It is pretty simple. You click the link and it imports the repo, you click the Run button and it (should) install the dependencies and run the code.

Replit just changed something and now the dependencies install fails for some users (me included, it just doesn't install the dependencies when I click Run). There are also some language auto-detection issues.

Here is a screen recording that shows the two main issues, the language auto-detection, and dependencies not installing (which we both have fixes for).

![flow](https://user-images.githubusercontent.com/28780271/178386800-7348fd1d-b67c-44d5-bd03-9de087bbb00b.gif)

---

As an aside. The config code I have in my PRs is from the [Replit docs Node.js example](https://docs.replit.com/programming-ide/configuring-repl#nodejs). They do not use npm install with the run command, but that might work as well.

I also included a `.gitattributes` file to help the language auto-detection on import. Specifying the language in the `.replit` file doesn't seem to work (last I tested it) if the repo language statistics don't match it.

**Comment by lasjorg** [comment] 2022-07-12 01:37
As for some other issues we have seen with Replit.

- Sometimes users fail challenges with their own IP and pass when using a VPN.
- We see SSL issues from time to time with the full page preview when it doesn't get a secure connection. The iframes used always seems to work with SSL (project preview and in-editor preview).

Both issues look related to the geolocation of the user. I don't really have any specific evidence for this other than the fact that a VPN sometimes fixes the issue.

**Comment by gikf** [comment] 2022-07-12 12:04
I've double checked and `npm install` might not work in every case, if there's `package-lock.json`. Like in case of https://github.com/freeCodeCamp/boilerplate-express and required newer version of `fcc-express-bground` package than `npm install` installs.

The changes that @lasjorg did in https://github.com/freeCodeCamp/boilerplate-express/pull/96 covered the appropriate version of package, but also with them dependencies were again installed on the first press of _Run_ button :man_shrugging:.

**Comment by lasjorg** [comment] 2022-07-12 14:14
I think the package version issue might have to do with the lockfile not having the correct version. I have refreshed the lockfile in all the PRs for good measure and to avoid any warnings about npm versions.

As for the config, I would prefer to use the syntax shown in the docs and have all the configs use the same syntax.

**Comment by RandellDawson** [comment] 2022-07-12 14:55
@lasjorg So why are we seeing the problem with the NPM Node challenges where the fcc-express-background package is older when users start a brand new project on repl.it?

**Comment by lasjorg** [comment] 2022-07-12 15:55
It really isn't a new issue, I have seen it happen many times in the past. It might have gotten worse now but I'm not even so sure of that. It might be related to the amount of users doing the challenges and their locations, plus the issue appears transient.

I'm not sure there is a good solution for it on our end. It seems like a bug Replit needs to fix so maybe we should open a support ticket with them? The main issue is reproducibility and the transient nature of the issue.

---

The lock file is just common practice. I don't see boilerplate repos in general suggesting to use ci in their install instructions. That is more a development thing when working on the repo.

**Comment by lasjorg** [comment] 2022-07-12 16:11
I'm not sure why.

Some of them also have really old files that, as far as I know, are no longer needed, the package.json file is often old and the information should be updated, and the main branch is still named gomix, etc. Usually when I have done a PR for some issue I have updated things like the package.json file, etc.

A lot of them really should be looked at and updated as needed. We also do not have any real guidelines for them.

**Comment by lasjorg** [comment] 2022-07-15 16:00
What is the status of this?

- Using `npm install` in the run command will cause dependencies to install/reinstall every time the Replit starts. In my opinion, this isn't a great option. I believe it also affect nodemon restarts and the Replit auto restart on saving, i.e control/command + S.
-  The config change I have suggested should work, with the caveat that it will auto install some dependencies we now have as part of the initial challenge requirements. See next bullet point.
- The challenges that have dependencies install requirements with specific versions should be updated to include the dependencies in the starting boilerplate. For example, the mongo/mongoose challenge. The requirement is causing issues way too often (see forum) and the version requirement is self-imposed by us. Doing so should fixe the issue of the `.replit` config doing auto installs of the dependencies. We may need more eyes on this on a per project update.
- When updating the boilerplates `.replit` config I suggest we take the opportunity to do any other updates needed.
    - Update the package.json file. Here is [an example](https://github.com/freeCodeCamp/fcc-express-bground-pkg/pull/11/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) of such a change. I suggest we keep the format somewhat similar although the `bugs`, `homepage`, and `author` fields are not strictly needed.
    - Refresh the package.lock.json to make sure it contains the latest dependencies.
    - Remove any old files no longer needed. For example, there are some very old Glitch related configs that I believe we no longer need.
    - If on import the Replit does not auto-detect the correct language, add a `.gitattributes` file with `*.html linguist-vendored` to exclude the HTML. This should fix the auto-detect.
    - At some point, I'd suggest renaming the main branch to `main` on all of them.
    - Do anything else I might have left out here?

---

Here is an example of a config, `entrypoint` should be adjusted as needed (usually it will be `index.js` or `server.js`).

```
run = "npm start"
entrypoint = "server.js"

[packager]
language = "nodejs"

  [packager.features]
  packageSearch = true
  guessImports = true
  enabledForHosting = false
```

**Comment by RandellDawson** [comment] 2022-07-15 16:32
I think you have everything covered.  The only thing I am concerned about is we will have to either delete or modify the first challenge in the Mongoose section if we are going to automatically install the latest packages (if I am understanding what you want to do here).  Also, we will need to update the 2nd to last challenge dealing with removing records, since in the latest version of Mongoose, the `Model.remove()` is no longer present or the challenge will fail using what we have taught them (and the Guide)  In fact, we should probably update all the challenges that have deprecated methods.

**Comment by lasjorg** [comment] 2022-07-15 16:59
Yes, for mongo/mongoose we have to update the initial challenge page. But that shouldn't be an issue, it is also mentioned in the PR.

As for the other update you suggested. I'm not suggesting we update the dependencies to the latest version, only that we provide the version we require in the initial package files. We do so only because of the age of the challenge and its tests.

If we update the dependencies to the latest version we may also have to update the tests, and if we update from deprecated methods to the new methods the challenge pages need to be updated as well.

For now, I might suggest we just add the required version of the dependencies to the initial boilerplate code.

---

It wouldn't be a bad idea to update the dependencies, tests, and challenges pages (if needed) so people can use the latest version of a library. But that might be a bit out of scope for what we are trying to fix here. It would require more work than just updating the dependencies, the tests might need updating and the challenge pages if new methods are used.

**Comment by lasjorg** [comment] 2022-07-15 17:23
It seems easier to me to just let it auto-install the dependencies and make sure we include the correct versions in the boilerplate. The PR is already done for this, we just have to update the initial challenge page and remove the install instructions when/if it is merged.

**Comment by moT01** [comment] 2022-07-15 17:23
I think I would vote to keep using the mongo version that we suggest to install. Auto install it when running the repl - and slightly modify the first challenge.

**Comment by lasjorg** [comment] 2022-07-15 17:27
Also, just in case anyone missed it I did open an issue for this. Just in case we want to talk about it more in-depth without "polluting" this issue.

https://github.com/freeCodeCamp/freeCodeCamp/issues/46885

**Comment by moT01** [comment] 2022-07-15 17:30
I'll make a PR to modify that first challenge.

There's a lot going on around these replit issues - I'm looking over them to catch up. If you all want to get on a call to discuss it together, I'm available - chat/discord/forum.

**Comment by lasjorg** [comment] 2022-07-15 18:47
Prettier does some funky formatting of the config file. I have started to add a `.prettierignore` file to the PRs. Just to account for anyone that has the Prettier code editor extension installed (Prettier isn't a dep in most, if not all the repos).

**Comment by moT01** [comment] 2022-07-20 15:34
Since we have [this other issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/46910) to track all the node boilerplates, I think we can probably close this when we fixed up all the python projects. We could do another quick audit of those to make sure we got them all, and close this I think.

**Comment by scissorsneedfoodtoo** [comment] 2022-07-22 09:23
Hi everyone, thank you all for your help digging into this and for your updates to the different boilerplate repos.

To make things a bit easier to audit, I renamed this issue so, along with general discussion on dependency handling, we can track the update status for the Python project boilerplates.

## Scientific Computing with Python ✅

[Arithmetic Formatter](https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter) ✅
PR: https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter/pull/11

Note: The other projects for this certification (Time Calculator, Budget App, Polygon Area Calculator, and Probability Calculator) do not need additional packages. Just the Arithmetic Formatter project uses pytest, which needs to be installed after cloning the project to Replit.

## Data Analysis with Python ✅

[Mean-Variance-Standard Deviation Calculator](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator) ✅
PR: https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator/pull/7

[Demographic Data Analyzer](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/demographic-data-analyzer) ✅
PR: https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer/pull/9

[Medical Data Visualizer](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer) ✅
PR: https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/20

[Page View Time Series Visualizer](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer) ✅
PR: https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer/pull/9

[Sea Level Predictor](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/sea-level-predictor) ✅
PR: https://github.com/freeCodeCamp/boilerplate-sea-level-predictor/pull/8

**Comment by gikf** [comment] 2022-07-22 10:19
There are two more python projects in the Information Security, but they also don't need additional dependencies.

**Comment by scissorsneedfoodtoo** [comment] 2022-07-22 10:56
Gah, I knew I missed a couple.

Thanks for catching those, @gikf. I'll go ahead and add them to the list, too.

**Comment by RandellDawson** [comment] 2022-07-28 16:04
It appears replits are yet again having their .replit file changed even though we specify the run command in it. The reason it is happening is when the project loads from the starter link, the user see the following in the preview pane and then when the user clicks Done, the run command changes to:

run = "python venv/lib/python3.10/site-packages/setuptools/package_index.py"

and then shows the user’s error above once the Run button is clicked. I tested this myself.

![9edf38317d021adf885cce64d498d36e5c592eb2](https://user-images.githubusercontent.com/5313213/181585016-8145e6b7-1138-45ce-b494-0351fc36eb49.png)

**Comment by lasjorg** [comment] 2022-07-28 17:24
I tried using their configs from their Python template. If I copy them to the boilerplate it seems to work. I would assume it includes some things not needed for our boilerplate(s).

But it still does not help with the import.

When I import the boilerplate with those configs I get this screen.

![github-import](https://user-images.githubusercontent.com/28780271/181598135-34708b9e-5619-42f0-856c-bdef52d697b4.png)


If I comment out the interpreter part from `replit.nix` and add the run command to `.replit` I get this screen.

![github-import-run-no-interp](https://user-images.githubusercontent.com/28780271/181599336-725343dd-0e7d-4134-a17e-768fb10c14a7.png)

**Comment by gikf** [comment] 2022-07-28 17:50
Some option might be including on each project page steps for starting boilerplate on replit manually. As an alternative or in case things _go wrong_ with the automatic setting up.


- Start new replit using `Python` template
- `git clone` boilerplate repository
```
git clone https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer.git
```
- Move files from cloned folder to the root folder
```
mv boilerplate-demographic-data-analyzer/*.* boilerplate-demographic-data-analyzer/.* .
```

**Comment by RandellDawson** [comment] 2022-07-28 22:09
Also, we are seeing [issues like this](https://forum.freecodecamp.org/t/loading-nix-environment-doesnt-stop/535791/2).

**Comment by gikf** [comment] 2022-08-19 05:05
Reopening, as with further replit changes all python boilerplates are broken. On the import from github, multiple _missing_ configuration options are added to `.replit` file.

Examples of errors:
https://global.discourse-cdn.com/freecodecamp/original/4X/a/b/e/abe86bcec235f1490f6f0540db2c57e53d239159.png
https://global.discourse-cdn.com/freecodecamp/original/4X/b/f/6/bf60b515e53fa9227000318283afc74f8c32af38.png

I haven't investigated closely how this can be fixed yet. Manual replit setup as described above is still working as a temporal solution.

**Comment by gikf** [comment] 2022-08-19 17:50
This is quite _funny_. The reason why boilerplates using only built-in modules are not working, is the version of nix channel, which is added automatically by replit. For some reason `stable-22_05` is causing errors, while changing it (or even removing) to ie. `stable-21_11` works. Therefore adding the latter in boilerplates maybe can protect against some strange shenanigans with the nix channels in future.

There's also kind of good news. It looks like python projects imported from github can now give consistent environment with projects that are started from new replit. This means we can use `.replit` file that's similar to the examples from replit, and get rid of adding modules in the `replit.nix` file.
I've tested this approach by importing boilerplate from github, changing `.replit` file, removing `replit.nix`, and then forking replit again.

While testing I've also encountered an issue with dependency resolving conflict, but this can be quickly changed. [Error](https://user-images.githubusercontent.com/60067306/185677786-7f511701-c62a-40f3-8d78-fd8523b4422c.png)


### Proposed actions:
#### Projects using only built-in modules:
- Add nix channel `stable-21_11` to the `.replit` file.

#### Projects using external modules:
- Add to `.replit` file more configuration, based on the replit example, with `stable-21_11` nix channel, and make installing dependencies automatic.
- Change in `pyproject.toml` to require python at least in `3.8` version.
- Remove `replit.nix`.

**Comment by mmatsumoto1026** [comment] 2022-08-22 23:20
Hello,

In fact, when I opened [this PR](https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer/pull/10), I encountered the issue which is mentioned by RandellDawson above, and I also found that Replit showed code example which use "channel = "stable-21_11"" in .replit file in [the Replit document](https://docs.replit.com/programming-ide/configuring-repl) .

I contacted customer support to report the issue which seems to be caused by nix channel id "channel = "stable-22_05", automatically added when I clone the [repo](https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer), and they also had recognized the issue.

Then, they seems to pushed fix to solve it and now, when the repo is cloned, it will be added "channel = "stable-21_11"" in .replit file so the issue have been solved. 

![initial_nix_channel_id_has_changed](https://user-images.githubusercontent.com/44451585/186035965-88f8793a-78cd-4372-9f8c-9a46d5b72103.png)

**Comment by scissorsneedfoodtoo** [comment] 2022-10-27 05:20
Hey everyone, thank you for re-opening this and for all the extra testing and details you all did.

I just imported this project into Replit and everything seems to work as expected, so I think it's safe to close this.

Going forward, someone at Replit has mentioned that they're making a lot of changes on their end, and recommends that we remove the `.replit` and `replit.nix` files wherever possible. We should be able to do this in most of the boilerplate repos. This seems to work fine, and Replit is able to generate the `.replit` and `replit.nix` files automatically, and install whatever packages are necessary for each project.

There will be a couple of exceptions, though, like with the [Rust in Replit](https://github.com/freeCodeCamp/Rust-In-Replit) project boilerplate. For that project, there are some commands that need to run when the project is imported. The recommendation for repos that need special commands is to leave the `.replit` and `replit.nix` files in the repo, but to make sure the only difference between them and the autogenerated `.replit` and `replit.nix` files are the commands that need to run.

I've been working on an issue with all the boilerplate repos that need to be updated, and will make sure this info is included there as well for extra context.

**Closed by scissorsneedfoodtoo** 2022-10-27 05:20 UTC
Labels: type: bug, status: discussing, scope: curriculum, type: showstopper
