### ISSUE TITLE
Goal doesn't account for commented code

### ISSUE THREAD

**Issue by greenfreq** [freeCodeCamp/freeCodeCamp#12252] opened 2016-12-28 23:22 UTC
Less of a bug in that the student can just erase the commented code and pass the challenge.  That said, if you comment out the second if statement, you will be met with the "You should have only one if statement" even though the code effectively has only one if statement.

Maybe the pattern matching doesn't take into account commented code.

Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%2020%20%7C%7C%20val%20%3C%2010)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%2F*%0A%20%20if%20(val)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A*%2F%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val > 20 || val < 10) {
    return "Outside";
  }
/*
  if (val) {
    return "Outside";
  }
*/
  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```

**Comment by raisedadead** [comment] 2016-12-29 07:35
Agreed, this has been a long persisting problem. I know it's a minor inconvenience, however, we should look handling comments more elegantly.

**Comment by pleabargain** [comment] 2017-01-19 11:19
Please do! I put comments in often and often the PASS fails because of comments in code:

example : working code with comments = FAIL= https://gist.github.com/pleabargain/d202e745c906e71daad69eda1eb2648c

working code minus comments is pass: 
https://goo.gl/h9wi7b

thank you!

**Comment by Undigon** [comment] 2017-01-23 20:01
+1. "Using objects for lookups" would benefit, as you could comment out the code and create the object from there.

**Comment by raisedadead** [comment] 2017-12-08 19:44
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/11360

**Closed by raisedadead** 2017-12-08 19:44 UTC
Labels: enhancement, tests
