### ISSUE TITLE
Live-updating broken for local FCC instance

### ISSUE THREAD

**Issue by BKinahan** [freeCodeCamp/freeCodeCamp#10022] opened 2016-07-31 19:52 UTC
Live-updating on file save is not working correctly. Saving a file does cause an open page to refresh, but changes do not take effect until the database is re-seeded and `gulp` is run again. A simple `gulp` restart has no effect.

Observed on latest staging with updated npm and all the correct post-reactification packages.

`(Macintosh; Intel Mac OS X 10_11_6)`

**Comment by dhcodes** [comment] 2016-07-31 19:54
Confirmed on my end. Same workflow required to see updates.

**Comment by Bouncey** [comment] 2016-10-18 10:38
Could this be fixed by implementing `sever/utils/getFromDisk$.js` in the gulp file again?

@BerkeleyTrue 
cc/ @FreeCodeCamp/issue-moderators

**Comment by BerkeleyTrue** [comment] 2016-10-21 05:33
This issue will require some sort of websocket to re-initiate the 'fetchChallenges' action after the db has been re-seeded. getFromDisk is not practical anymore.

**Comment by robbawebba** [comment] 2017-01-25 16:19
Not sure if this issue is blocked or not since it's been awhile since the last comment, but just wanted to let you know that I'm experiencing this issue. I've tried removing `node_modules` and re-installing npm packages, and still the only way to see changes to the seed challenges is by running `gulp` again.

**Comment by systimotic** [comment] 2017-01-25 16:31
@robbawebba Nope, this issue has never been fixed. I'm taking a look at it, but I don't expect that I'll be able to solve this. I think this is way above my level.

**Comment by robbawebba** [comment] 2017-01-25 17:49
@systimotic same here 😅 Thanks for a response!

**Comment by raisedadead** [comment] 2017-01-25 18:08
This is broken because the challenges are now sent to the client via a bundle.js (webpack) for react and while we might take a look at this in future, this is not a priority for now. 

But that said its open for any one to take a look.


Current work around is, you simply need to stop the server, `node seed` and start with gulp again

**Comment by Bouncey** [comment] 2017-03-13 23:42
This feature is unable to be re implemented right now. See #11313 for details

:crying_cat_face: :crying_cat_face:

**Comment by raisedadead** [comment] 2017-03-14 09:58
Closing as a wontfix.

**Closed by raisedadead** 2017-03-14 09:58 UTC
Labels: wontfix
