### ISSUE TITLE
Waypoints - left panel contents "twitch" when I type in editor console

### ISSUE THREAD

**Issue by aelfa** [FreeCodeCamp/FreeCodeCamp#1955] opened 2015-08-17 22:22 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This happens on all Waypoints I've tried since the update. It did not happen prior. Here's a video of the behavior:
http://www.screencast.com/t/925RcgPZ

Mac OS X Yosemite
10.10.4 (14E46)
Safari Version 8.0.7 (10600.7.12)

**Comment by BerkeleyTrue** [comment] 2015-08-21 00:46
Duplicate of #2137

**Closed by BerkeleyTrue** 2015-08-21 00:46 UTC
