### ISSUE TITLE
[BETA] - Front End Libraries - Sass - Apply a Style Until a Condition is Met with @while

### ISSUE THREAD

**Issue by Dereje1** [freeCodeCamp/freeCodeCamp#17195] opened 2018-05-20 15:39 UTC
#### Describe your problem and - if possible - how to reproduce it
Challenge passes for all `.text` classes except `text-1` , while the font-size is correctly changed for `text-1` in the HTML page. Here is my solution code:
```
  $x: 1;
  @while $x < 11 {
    .text-#{$x} { font-size: #{5*$x}px;}
    $x: $x + 1;
  }
```
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![screenshot 27](https://user-images.githubusercontent.com/23533048/40280481-37a5aa42-5c22-11e8-8330-39fe83aa15ae.png)

**Comment by rajatkantinandi** [comment] 2018-05-21 19:14
Well I used font-size: 5px*$x;
Which worked fine..

**Comment by Dereje1** [comment] 2018-05-21 19:31
That still does not pass for the `.text-1` class, at least for me, could you post your entire code?

**Comment by rajatkantinandi** [comment] 2018-05-22 02:54
here is the source code
``` html
<style type='text/sass'>
  $x:1;
  @while $x<13{
  .text-#{$x} {font-size:5px*$x;}
  $x:$x+1;
  }
  
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>
```
### Quick Tips
Place you cursor somewhere in the SAAS code & press Ctrl+Enter
Otherwise it is not working.

here is the screenshot
![image](https://user-images.githubusercontent.com/17743895/40339694-3d59b938-5d99-11e8-8fa6-9f56c87aa152.png)

**Comment by Dereje1** [comment] 2018-05-22 17:21
Still no go for me after trying your code

**Comment by scissorsneedfoodtoo** [comment] 2018-05-25 07:18
I noticed this too. @rajatkantinandi's code is correct, but I had to submit it multiple times to pass all the checks. It also seems like all styling is dropped when the tests are run, leading to the default font-size, then Sass is recompiled and displayed. I'm thinking that the tests are firing and failing sometime during that process.

**Comment by rajatkantinandi** [comment] 2018-05-25 18:54
@scissorsneedfoodtoo 
Maybe you are right because at least I had to submit twice to pass the test.

**Comment by QuincyLarson** [comment] 2018-06-03 16:42
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by dCremins** [comment] 2018-06-06 13:50
Having the same problem. Even tried setting .text-1 manually after the loop to no luck.
<img width="847" alt="screenshot 2018-06-06 09 49 31" src="https://user-images.githubusercontent.com/16244264/41042179-fbb0d5f2-696e-11e8-9f8b-71c7ef4e6901.png">

**Comment by kamatheuska** [comment] 2018-06-27 18:54
The issue is still ongoing: 
![fccsasswhile](https://user-images.githubusercontent.com/26850124/41993566-34cbc552-7a4c-11e8-9372-f75205499aa7.png)

**Comment by QuincyLarson** [comment] 2018-06-28 19:50
@dCremins @kamatheuska Thanks for reporting that this is still a problem. I've reopened the issue and given it the "help wanted" label.

**Comment by lynxlynxlynx** [comment] 2018-07-14 14:53
This is also tracked in #12699

**Comment by chenjacky131** [comment] 2018-07-19 02:14
try run test multiple times or try in another browser. that works for me

**Comment by carl-parrish** [comment] 2018-08-30 13:27
Was not able to get it to pass until I tried the CTRL+Enter as suggested above. Since I haven't had to do that for any other test it was extremely frustrating.

**Comment by aheggie** [comment] 2018-09-02 21:06
To synthesise a few responses for people who are still feeling stuck (based on my experience):

In Chrome it did not work, even if I pressed Ctrl-Enter
In Firefox it did not work with the button, but pressing Ctrl-Enter did work

Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
Firefox: 61.0.2 (64-bit)

**Comment by LudwigJedde** [comment] 2018-09-10 11:40
write :
$x:1;
  @while $x<11{
  .text-#{$x} {font-size:5px*$x;}
  $x:$x+1;
  }

and... it's good !

**Comment by thecodingaviator** [comment] 2018-10-18 18:34
Guys I'm not sure what the problem is since I'm not able to replicate it, can someone elaborate ?

**Comment by lynxlynxlynx** [comment] 2018-10-18 20:00
Read the linked bug if you are interested in the details.

**Comment by ValeraS** [comment] 2018-11-12 11:55
In production, tests begin before the compilation of the sass code is complete. It's resolved in the master branch.

**Comment by thecodingaviator** [comment] 2018-11-21 08:38
The issue has been fixed this can be closed.

cc: @ezioda004

**Comment by ezioda004** [comment] 2018-11-21 09:38
Fixed in master, closing.

**Closed by ezioda004** 2018-11-21 09:38 UTC
Labels: status: resolved \ shipping

**Comment by vinc01100101** [comment] 2019-04-20 07:58
hi i am still having this issue

**Comment by LonelyDaoist** [comment] 2019-06-21 02:29
The issue is still happening, I don't think it's fixed

**Comment by thecodingaviator** [comment] 2019-06-21 07:34
Yes, because the fixes haven’t been pushed to production

**Comment by javascriptWriter** [comment] 2019-08-08 10:18
still not fixed

**Comment by cherry-geqi** [comment] 2019-08-13 07:03
still not fixed

**Comment by kamilwyremski** [comment] 2019-08-16 22:52
Today still not fixed in Chrome.
In Firefox is working.

**Comment by javascriptWriter** [comment] 2019-08-19 08:21
Actually, if you are looking for certificates no need to complete this..but
its completely based on project

*Thanks & Regards*
*Abidh K Muhammed*
