### ISSUE TITLE
Tests pass with different results

### ISSUE THREAD

**Issue by jsoningram** [FreeCodeCamp/FreeCodeCamp#2823] opened 2015-08-28 22:09 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-drop-it has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Instructions: Drop the elements of an array (first argument), starting from the front, until the predicate (second argument) returns true. 

```
function drop(arr, func) {
  while (arr.length > 0) {
    if (func(arr[0])) {
      break; 
    }
  arr.shift();
  }
  return arr;
}

drop([1, 2, 3], function(n) {return n < 3; }); // returns [1,2,3] and all tests pass
```
```
function drop(arr, func) {
  // Drop them elements.
  return arr.filter(func);
}

drop([1, 2, 3], function(n) {return n < 3; }); // returns [1,2] and all tests pass
```

**Comment by awesomeaniruddh** [comment] 2015-08-31 14:09
How is this an issue?

**Comment by benschenker** [comment] 2015-09-08 20:30
Hey @jsoningram thanks for posting this!

It looks like this is a duplicate of #2533, so keep an eye there for updates on this.

**Closed by benschenker** 2015-09-08 20:30 UTC
