### ISSUE TITLE
Does not work on Firefox. Same issue as previous challenge.

### ISSUE THREAD

**Issue by Monochrome19** [freeCodeCamp/freeCodeCamp#14982] opened 2017-05-21 20:08 UTC
Challenge [use-a-css-class-to-style-an-element](https://beta.freecodecamp.com/en/challenges/basic-css/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  .red-text {
    color: red;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by JavaRabbit** [comment] 2017-05-21 23:17
First timer here.

I was able to repro this bug which displays "Something went wrong. Please try again later" in both Firefox and Chrome.  This possibly indicates that this bug is not browser specific.

This bugs occurs during the first loading of the webpage 
https://beta.freecodecamp.com/en/challenges/basic-css/use-a-css-class-to-style-an-element

However, subsequent reload or refreshing of the webpage does not yield this bug. 

To repro in either Chrome or Firefox:
1) clear browser cache if necessary
2)  Load https://beta.freecodecamp.com/en/challenges/basic-css/use-a-css-class-to-style-an-element
3) After the page has almost completed loading, a bottom right corner pop up will show up with the text "Something went wrong. Please try again later".

However this bug does not affect the performance of the page itself.  The coding challenge can still be completed successfully. (See screen shot).

Using Firebug on Firefox, this looks like an XMLHttpRequest timeout.  Probably something is timing out, and the pop up is now showing up as a result.
![on_firefox_bug_repro](https://cloud.githubusercontent.com/assets/3488191/26288168/f053219c-3e40-11e7-8374-38b5f63aba14.png)
![on_firefox_xml_timeout](https://cloud.githubusercontent.com/assets/3488191/26288169/fafb4264-3e40-11e7-90cb-9a7c48d8ff7f.png)
![chrome](https://cloud.githubusercontent.com/assets/3488191/26288173/038c4ca2-3e41-11e7-83c9-745d4383624f.png)

**Comment by systimotic** [comment] 2017-05-27 09:24
Closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14981

**Closed by systimotic** 2017-05-27 09:24 UTC
Labels: beta
