### ISSUE TITLE
The ";" after every line in JavaScript challenges

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [freeCodeCamp/freeCodeCamp#45157] opened 2022-02-17 23:20 UTC
## Affected page
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/initializing-variables-with-the-assignment-operator](url)

## Code:
Incorrect:
`var a = 9`
Correct:
`var a = 9;`

## Expected behavior
The console and challenges (![image](https://user-images.githubusercontent.com/97681427/154587139-514855f4-ae9c-4e0f-9e5d-becafcd99adf.png))
Should return an error describing that the person has a bug because they didn't add a semicolon at the end of the line.

## Screenshots
This accepted the answer:
![image](https://user-images.githubusercontent.com/97681427/154587581-17d4fc29-79d6-44f3-878a-5aa133a80b7b.png)
But I made a `console.log()` element to clarify the bug:
![image](https://user-images.githubusercontent.com/97681427/154587818-274cbf9b-3c30-4ee5-b15f-4f4aa0564f35.png)
## System

- Device: Laptop
- OS: Google Chrome OS 64-bit
- Browser: Chrome
- Version: 97

## Additional context
So far I found that this works on most challenges (I didn't check all of them because I was lazy and didn't complete all of them yet) in the JavaScript curriculum.

**Comment by ShaunSHamilton** [comment] 2022-02-18 01:39
Hello there,

Thank you, for taking the time to open this. However, this is not a bug.

JavaScript does not require the semi-colon like some other languages do. All the code with/without it in the curriculum is valid.

As such, I am going to close this issue.

**Closed by ShaunSHamilton** 2022-02-18 01:39 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
