### ISSUE TITLE
Dodger Blue Task Never Completes

### ISSUE THREAD

**Issue by rbarton65** [FreeCodeCamp/FreeCodeCamp#10656] opened 2016-09-10 02:10 UTC
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The Task "Give your h1 element with the text I am dodger blue! the color dodger blue" does not complete with the below code:

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by dhcodes** [comment] 2016-09-10 02:15
@rbarton65 thanks for the issue. Closing as duplicate of #10523

**Closed by dhcodes** 2016-09-10 02:15 UTC
