### ISSUE TITLE
Certificate not printable on a single page

### ISSUE THREAD

**Issue by JESii** [freeCodeCamp/freeCodeCamp#35695] opened 2019-03-27 13:15 UTC
I just finished the JavaScript Algorithms and Data Structures program, received my certificate and tried to print it. It doesn't fit on a single page in either landscape or portrait mode.
I'm on MacOS, 10.14.3, using Chrome browser.
![image](https://user-images.githubusercontent.com/486/55078572-b2950c00-5057-11e9-96d5-7bef2afddb25.png)

Notice also that my name overlaps the certificate date:
![image](https://user-images.githubusercontent.com/486/55078695-f1c35d00-5057-11e9-9d75-fe024e9c4ca6.png)

**Comment by thecodingaviator** [comment] 2019-03-27 16:54
Scale it using the scale option in Chrome

**Comment by chaomt** [comment] 2019-03-31 21:04
It seems that this is not a bug, just about scalability. Should it be closed?

**Comment by thecodingaviator** [comment] 2019-04-01 13:39
I'm closing this issue since this is not something we can fix on our side anyway

**Closed by thecodingaviator** 2019-04-01 13:39 UTC
