### ISSUE TITLE
Code can't pass for a specfic version of Google Chrome browser

### ISSUE THREAD

**Issue by Narcissus91** [freeCodeCamp/freeCodeCamp#50372] opened 2023-05-13 05:13 UTC
### Describe the Issue

When I come to the 4th step of the course "Learn CSS Variables by Building a City Skyline", the code still can't pass, even though I tried several times. 

Then I switched the browser from Google Chrome to Firefox. The code passes. 

By the way, today, I switched to my notebook to do the course (Respoonsive Web Design). Usually, I do the course on my another desktop computer. This kind of issues never happened before.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-4

### Steps to Reproduce

1. Go to 'Step 4' of the course'Learn CSS Variables by Building a City Skyline'.
2. Give the meta tag as hinted.
3. Click on the button 'Check Your Code'.
4. See error 'your code does not pass'

### Expected behavior

I expect the code passes.

### Screenshots

The code can't pass on Google Chrome browser.
![图片](https://github.com/freeCodeCamp/freeCodeCamp/assets/40660165/ef88eb96-9ec0-446f-91ea-8f91fb522c7f)

The version of my Google Chrome browser is :
![图片](https://github.com/freeCodeCamp/freeCodeCamp/assets/40660165/8e011d8e-1a40-425f-9544-0dea5acc57bc)

The code passes on Firefox browser:
![图片](https://github.com/freeCodeCamp/freeCodeCamp/assets/40660165/b1d6d6cb-ba96-4942-84a8-24b5998d6a62)

### System

- Device: [Notebook Lenovo Thinkpad L470]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [Version 76.0.3809.132 (Official build) (32-bit)]

### Additional context

Another thing is that my Chrome browser is not supported for the freeCode Camp Forum. So I guess this isssue is related to my Chrome browser's version.

![图片](https://github.com/freeCodeCamp/freeCodeCamp/assets/40660165/ca54d476-4c89-4812-b45c-3674b89be6ac)

**Comment by Sboonny** [comment] 2023-05-13 12:36
Does the issue persist if you update to the latest version?

**Comment by Narcissus91** [comment] 2023-05-13 12:48
> Does the issue persist if you update to the latest version?

No, the issue doesn't recur after I update the browser to the lastes version.

**Comment by Sboonny** [comment] 2023-05-14 09:08
I am going to close the issue, because it seems like it's caused by using an old version, as far as I know it isn't possible for us to create tests that work in all versions of chromium.

**Closed** 2023-05-14 09:08 UTC
Labels: type: bug, status: waiting triage
