### ISSUE TITLE
Code should not pass with wrong font-size rule

### ISSUE THREAD

**Issue by 00090** [FreeCodeCamp/FreeCodeCamp#11941] opened 2016-12-06 08:14 UTC
#### Issue Description

One of the requirement to pass the test is "Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%." however is passes with "30px" as well that was given with example

#### Browser Information

* Browser Name, Version: Firefox 50.0.2
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Desktop

#### The Code

```js
 <style>
  p {font-size: 30px;}
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p> 
``` 

first time reporting for a bug

**Comment by ajain17** [comment] 2016-12-06 15:10
I can replicate it at my end. I'll look into it.

**Comment by dhcodes** [comment] 2016-12-06 16:21
Confirmed on staging as well.

**Comment by ajain17** [comment] 2016-12-06 19:28
I'm seeing a weird issue. The test fails on my local host if the font size is 30px (because it needs it to be 16px) but on the website, it passes with 30px . I'm not sure why that would be?

**Comment by dhcodes** [comment] 2016-12-06 19:40
If you are talking about staging on your local, then it would usually make sense because staging has fixes that are not currently on the live site. In this case though, the code above passed on my local version too. Maybe someone else can test it too.

**Comment by ajain17** [comment] 2016-12-06 19:41
@dhcodes So I thought. Thanks for confirming. If another person confirms that it works expectedly on localhost then we can close the issue.

**Comment by ndaljr** [comment] 2016-12-07 14:23
I just took a look at this on the live website and the tests pass as long as the requested font size is equal or greater than 16px. This test fails on my local staging version.

**Comment by ajain17** [comment] 2016-12-07 15:07
@ndaljr On the live website, tests pass for me also. but on local staging, they fail unless font size is 16px. Like dhcodes said, it could be because staging has fixes that are not currently on the live site.

**Comment by systimotic** [comment] 2016-12-07 21:14
@dhcodes 😕 Maybe your staging is out of date? My guess would be that you did `git pull --rebase upstream staging`, but didn't run `node seed` (because I know I would forget 😅)
This should have been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11306
I can confirm this works as expected on my local setup as well. 👍 

I'm removing the labels, blocking for Dylan to confirm whether this issue is still reproducible on his local setup.

**Comment by dhcodes** [comment] 2016-12-07 21:29
@systimotic alas, you are correct. My bad.
![fail-whale](http://www.wired.com/wp-content/uploads/2010/06/CSSfailwhale.jpg)

**Comment by dhcodes** [comment] 2016-12-07 21:29
closing as resolved in staging.

**Closed by dhcodes** 2016-12-07 21:29 UTC
