### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by escapeplan4** [FreeCodeCamp/FreeCodeCamp#3139] opened 2015-09-07 02:14 UTC
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
cod isn't working although I've wrote it right.
![12](https://cloud.githubusercontent.com/assets/8931882/9708081/f389faa8-5516-11e5-8353-a46e7a2a614c.jpg)

**Comment by kettultim** [comment] 2015-09-07 06:21
You have a space at the beginning of your a tag. Remove that space and rerun and it works perfectly. e.g. <a href instead of < a href

For future reference - this is not a bug and should not have been added to the Github issue queue as it could easily be resolved by seeking out help from fellow devs beforehand.

See https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug for all the things you should try before submitting an issue on Github. Thanks!

**Closed** 2015-09-07 14:14 UTC
