### ISSUE TITLE
Challenge(Passing Values to Functions with Arguments): Allow template literals in the log

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#51922] opened 2023-10-11 21:43 UTC
### Describe the Issue

As implemented now you can not pass template literals to the console.log. Not sure if we really care or not.

Doesn't work:
```
function functionWithArgs(param1, param2){
  console.log(`${param1 + param2}`);
};
```

Works:

```
function functionWithArgs(param1, param2){
  console.log(Number(`${param1 + param2}`));
};
```

I was able to make it pass using a `replace` for the assert but that doesn't seem that great. I tried a few other things that didn't seem to work and just left it alone.

```
assert(logOutput.replace(/["|\\]/g, '') == 3);
assert(logOutput.replace(/["|\\]/g, '') == 16);
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments

### Your code

```



```

### Expected behavior

Allow template literals to be used in the console.log

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/javascript-basico-passar-valores-para-funcoes-com-argumentos/643696

**Comment by ShaunSHamilton** [comment] 2023-10-12 14:25
One things we could do is not stringify the message:

https://github.com/ShaunSHamilton/freeCodeCamp/blob/fc25bff205e4d2fd79d5fc7bba4234a6ad4aa546/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments.md#L78-L79

It shouldn't really matter for this challenge's tests.

**Comment by lasjorg** [comment] 2023-10-12 20:10
I'm not really sure why we use stringify on the parameter. But when I was removing it didn't seem to change anything.

What seems odd is when I do a `replace(/"/g, '')` on the `message` it doesn't work, but if I do it on `logOutput` in the assert it does work. It seems like it is a double string at that point. Converting `message` to a number also do not work (I guess for the same reason).

**Comment by naomi-lgbt** [comment] 2024-04-26 06:43
I'm not sure this is an issue?

If I'm understanding correctly, the problem is that this code prints a **string** to the terminal:

```js
function functionWithArgs(arg1, arg2) {
  console.log(`${arg1 + arg2}`)
}
```

But the sum of two numbers should be a number, not a string.

**Comment by ahmaxed** [comment] 2024-10-24 10:59
I think this is an non-issue as well. So closing it accordingly. Let me know if this issue has been closed by mistake.

**Closed by ahmaxed** 2024-10-24 10:59 UTC
Labels: status: discussing, scope: curriculum
