### ISSUE TITLE
Pressing "e" transfers focus to code editor, even when typing into the search bar

### ISSUE THREAD

**Issue by ColinAmos** [freeCodeCamp/freeCodeCamp#36569] opened 2019-08-06 23:27 UTC
**Describe the bug**
When typing into the search bar on any lesson page, typing "e" triggers a focus hotkey that transfers focus to the code editor, such that what the user then types will go to the code editor instead of the search bar.

**To Reproduce**
1. Go to any lesson page (ex: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements)
2. Click on the search bar at the top
3. Type a search term or phrase that contains "e" (ex: "search for me")

**Expected behavior**
Typing "e" in the search bar should input an "e" into the search string while maintaining focus on the search bar.

**Screenshots**
![pic2 2](https://user-images.githubusercontent.com/35937916/62583839-ebec4c80-b87f-11e9-8051-34bddef9928b.png)

![pic3 2](https://user-images.githubusercontent.com/35937916/62583841-ed1d7980-b87f-11e9-9c2b-40b724d53a10.png)

**Desktop:**
 - OS: Windows 10
 - Chrome (also happens on Firefox)
 - Version 75.0.3770.142

**Comment by ammrat13** [comment] 2019-08-08 23:04
Pull request #31591 and [its corresponding fix](github.com/freeCodeCamp/freeCodeCamp/commit/457bd4de171e8e47e0f344cd7e8722b1c433758b) may be related to this.

**Comment by RandellDawson** [comment] 2019-08-08 23:44
@ColinAmos I believe this has been fixed on the master branch.  However, I can not replicate the same problem on production which you are experiencing.  In the next couple of days, there will be a beta site up an running with the current master.  Once it is up and running, I will send you a link to it and have you see if the problem still exists on it.  Keep in mind the new search feature is much different and only searches through the news articles and not the site.

**Comment by ammrat13** [comment] 2019-08-08 23:48
Can confirm. I just tried running `master` locally and was unable to reproduce.

**Comment by moT01** [comment] 2019-08-09 13:41
I can reproduce this on production - but it looks like it has been fixed on master.

**Closed** 2019-08-11 14:46 UTC
Labels: status: resolved/shipping
