### ISSUE TITLE
[Beta Guide] Side menu should be revamped

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#35411] opened 2019-02-25 21:33 UTC
### Describe your problem and how to reproduce it:
I think the side menu of guide should be revamped. Here are my suggestions:

- [ ] There should be a scroll bar on the side menu
- [ ] Selecting an article should **not** take me back to the top of the menu

I think solving the first issue will automatically solve the second one. I am open for discussion on possible ways of improving Guide's side menu. 

### Tell us about your browser and operating system:
 - OS: Windows 10 Pro 32 bit
 - Browser: Chrome
 - Version: Latest stable

**Comment by raisedadead** [comment] 2019-02-26 08:51
Duplicate of #35411 and #35249

Please look through open issues before reporting. Also, if your issue does not cover something, it should be discussed in the original threads. 

Thanks.

**Closed by raisedadead** 2019-02-26 08:51 UTC
