### ISSUE TITLE
Twice click `Run Code` button for every challenge.Is it friendly?

### ISSUE THREAD

**Issue by zoorz** [FreeCodeCamp/FreeCodeCamp#2868] opened 2015-08-30 05:20 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Twice click `Run Code` button to submit the code. Is it friendly to users?

![image](https://cloud.githubusercontent.com/assets/1608741/9565804/7a75dc5c-4f19-11e5-8352-8f6088f64f1c.png)

**Comment by BerkeleyTrue** [comment] 2015-08-30 05:56
Closing as duplicate of #2772

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-30 05:56 UTC
