### ISSUE TITLE
Potential bug not accepting below submission, could also be incorrect submission.

### ISSUE THREAD

**Issue by Burtonia** [FreeCodeCamp/FreeCodeCamp#4297] opened 2015-11-11 04:31 UTC
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0Avar%20myCar.nickname%20%3D%20%22twin%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;

};

// Only change code below this line.

var myCar = new Car();
var myCar.nickname = "twin";

```

**Comment by SaintPeter** [comment] 2015-11-11 04:35
The problem is that you're trying to declare `myCar` twice.  You only need one `var`.  The code editor gives you a visual indication when there is an obvious error:
![image](https://cloud.githubusercontent.com/assets/553494/11083983/815a172c-87ea-11e5-9ec6-20e8a1708dcf.png)

Mouse over to get details.

When you have a question about your code, we encourage you to hit the "Help" button and ask in help chat.

Closing as there is no site issue.

**Closed by SaintPeter** 2015-11-11 04:35 UTC

**Comment by Burtonia** [comment] 2015-11-11 15:35
Thank you, and my apologies!

Alex,
