### ISSUE TITLE
Slot Machine - Random number format

### ISSUE THREAD

**Issue by n8sb** [FreeCodeCamp/FreeCodeCamp#2109] opened 2015-08-18 18:58 UTC
From challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine

The format below is required and seems redundant:
```javascript
Math.floor(Math.random() * (3 - 1 + 1)) + 1;
```
But shouldn't this work better as it is more succinct:
```javascript
Math.floor((Math.random() * 3) + 1);
```

**Comment by benschenker** [comment] 2015-08-26 23:11
Hey @n8sb thanks for this!

Looks like this is a duplicate of #1869, keep tabs on progress there

**Closed by benschenker** 2015-08-26 23:11 UTC
