### ISSUE TITLE
"Wrap your text input element within a form element" task issue

### ISSUE THREAD

**Issue by Cu7ious** [FreeCodeCamp/freecodecamp#1060] opened 2015-06-22 19:53 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-form-element has an issue.

"Wrap your text input element within a form element" task marked as completed while form element doesn't wrap the input http://take.ms/sHn4I

**Comment by alexlincoln** [comment] 2015-07-05 21:08
I was also able to reproduce this bug. 

![2015-07-05-131048_1064x963_scrot](https://cloud.githubusercontent.com/assets/6338358/8513410/3ebef7c8-231f-11e5-9c80-baa2cd7b2842.png)

**Comment by alexlincoln** [comment] 2015-07-05 21:37
It also looks like it doesn't need the `input` element at all to pass...

![2015-07-05-134019_1176x923_scrot](https://cloud.githubusercontent.com/assets/6338358/8513510/5a14b644-2323-11e5-970e-56ef67939439.png)

**Comment by benmcmahon100** [comment] 2015-07-05 21:41
I can confirm that this has been fixed in staging and will be deployed within a week!

**Comment by alexlincoln** [comment] 2015-07-05 21:50
Ah great, thanks @benmcmahon100

**Comment by alexlincoln** [comment] 2015-07-05 22:01
@benmcmahon100 great, thanks for letting me know

**Comment by alexlincoln** [comment] 2015-07-05 22:28
@benmcmahon100 one quick thing I found while looking for that fix and perhaps I'm mistaken/picky

[In this test](https://github.com/FreeCodeCamp/freecodecamp/blob/staging/seed/challenges/basic-html5-and-css.json#L1720) we're checking that the `form` element of course exists, that the `input` element is as a child of the `form` element, and that we have at least one `input` element within that form.

Now after testing that, it appears it work as intended. However, if we checked the truthiness of both the first condition `$('form')` and second condition `$('form').children('input')`, regardless if it existed or not it will come out as `true` in this instance, which shouldn't happen. 

Consider the following [jsfiddle](https://jsfiddle.net/uu6pnjj3/1/)

Running that will likely result in the following:
```
[prevObject: jQuery.fn.init[1], context: document, selector: "form"]
[prevObject: jQuery.fn.init[0], context: document]
This is: true // this shouldn't happen since neither element exists at all
````
Luckily the last condition prevents this test from the acting in the opposite intended behavior. If I could correct this (or perhaps I'm just picky), I'd likely condense it to `$('form').length > 0 && $('form').children('input').length > 0`, which will check that a form exists and that a input element exists inside that form, which satisfies the requirement.

**Comment by benmcmahon100** [comment] 2015-07-05 22:48
I think you may have looked in the wrong branch! The new stuff coming out is in staging. Master is the currently deployed version.

**Comment by alexlincoln** [comment] 2015-07-05 22:52
@benmcmahon100 I grabbed it from the `staging` branch

**Comment by benmcmahon100** [comment] 2015-07-05 22:59
Ah yes i thought you were saying that they were the only tests! Like you were saying that shouldn't be an issue but if you want you can either put up a pull request less those two extra checks or i can put it up for you if that's needed!

**Closed** 2015-08-11 19:47 UTC
