### ISSUE TITLE
embedded html editor does not edit where the cursor is located

### ISSUE THREAD

**Issue by wallnutmonkeys** [FreeCodeCamp/FreeCodeCamp#10364] opened 2016-08-27 13:53 UTC
On all pages that have an embedded html editor, there is a bug where, when you put your cursor on a given line and try to edit (add a character, delete a character etc), the modification is applied to the next line instead of the line where the cursor is located.

#### Challenge Name

https://www.freecodecamp.com/challenges/line-up-form-elements-responsively-with-bootstrap

#### Issue Description

Occurred on all pages having an embedded html editor. To reproduce, place cursor on a given line a press a key to insert a character a the cursor position, the character will be added to the next line.

#### Browser Information

firefox 47.0
Ubuntu 14.04
Desktop

**Comment by BKinahan** [comment] 2016-08-27 21:41
This is a duplicate of issue #7847. Please follow along there.

Happy coding!

**Closed by BKinahan** 2016-08-27 21:41 UTC

**Comment by deepverma3003** [comment] 2017-03-14 05:35
Unable to edit the last lines of a long code. The cursor does not go to the last 2-3 lines
