### ISSUE TITLE
bonfire: Chunky Monkey - Tests doesn't work

### ISSUE THREAD

**Issue by andresmachado** [FreeCodeCamp/FreeCodeCamp#2922] opened 2015-08-31 14:48 UTC
Challenge http://freecodecamp.com/challenges/bonfire-chunky-monkey has an issue. 
I'm solving the Bonfire but the assert tests doesn't work, as you can see in screenshoot.

Here's the code that I'm using:

var newArray = [];

function chunk(arr, size) {
  for (var i = 0; i < arr.length; i += size) {
    var tempArray = arr.slice(i, i + size);
    newArray.push(tempArray);
   }
  return newArray;
}

chunk(['a', 'b', 'c', 'd'], 2);

![capturar](https://cloud.githubusercontent.com/assets/6772382/9581447/f4717c66-4fd5-11e5-9a04-504690920796.PNG)

**Comment by catapixel** [comment] 2015-09-01 18:59
@andresmachado your challenge is failing because you are declaring your newArray variable outside of the function so it is not being reset each time the function is called. If you move your ```var newArray = [];``` to the line after the function declaration and before your for loop begins your tests will pass successfully.

```
function chunk(arr, size) {
  var newArray = [];
  for (var i = 0; i < arr.length; i += size) {
    var tempArray = arr.slice(i, i + size);
    newArray.push(tempArray);
   }
  return newArray;
}
```

**Comment by andresmachado** [comment] 2015-09-01 19:17
Thanks @catapixel! Worked fine!

**Comment by bugron** [comment] 2015-09-04 17:06
@andresmachado thanks for posting this issue!
Closing this issue as the problem is solved.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-04 17:06 UTC
