### ISSUE TITLE
Escaped quotes test regex broken

### ISSUE THREAD

**Issue by BKinahan** [freeCodeCamp/freeCodeCamp#10258] opened 2016-08-17 21:54 UTC
On the current staging, two challenges ("Escaping Literal Quotes in Strings" and "Quoting Strings with Single Quotes") do not pass all tests with standard solution code. 

Namely, tests asserting regex match lengths for non-escaped double quotes are failing:
`code.match(/[^\\\\]\"/g).length === 2` in the former challenge and 
`code.match(/\"/g).length === 4` in the latter.

(Note: each of these is only one half of their respective test, and it might be beneficial in this case to split each test into two parts so users know where to look for their mistake instead of counting every quotation mark, as well as speeding up debugging if something breaks the regex again later on.)

**Comment by dhcodes** [comment] 2016-09-08 14:54
@BKinahan Any idea of the cause of this? I'm working on the "Quoting Strings with Single Quotes" challenge. Would splitting the test into two fix it?

**Comment by BKinahan** [comment] 2016-09-08 17:04
@dhcodes Splitting it into two tests is how I found that the two quoted-above halves of the tests are what are causing the trouble, but I'm not sure of the exact cause. I'm reasonably sure it has to do with escaping though, and you might gain some insight by adding to the tail or tests some code which logs the results of the calls to `match` so you can see what the results actually are. If I recall each was matching more times than it was supposed to.

Good luck!

**Comment by BerkeleyTrue** [comment] 2016-09-08 20:50
Looks like several changes done internally now effect the number of quotes in the original code.

First is head/tail is now included in the `code`. If this has not always been the case then that will require a new issue to be opened.

The other is now all JS code is pushed through babel, which adds `"use strict";` key. This won't change as it is a requirement for the new challenges coming down the pipeline.

Can someone confirm that `code` did not contain the head/tail previously?

![escaping_literal_quotes_in_strings___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/18366215/aa527c90-75ca-11e6-93c2-ddec89033041.png)

**Comment by BerkeleyTrue** [comment] 2016-09-08 20:57
After reviewing the code, looks like to quickest solution is to change the number of expected to 12 as changing the internals is far more involved.

**Comment by BerkeleyTrue** [comment] 2016-09-08 21:57
I've made those changes here https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10518

**Comment by BKinahan** [comment] 2016-09-09 11:00
The PR above only addresses the problem in Escaping Literal Quotes in Strings. Quoting Strings with Single Quotes still isn't working for a similar reason.

**Comment by BerkeleyTrue** [comment] 2016-09-10 01:54
Escaping Literal Quotes in Strings seems to be broken in production but not in dev.

**Comment by marie-nws** [comment] 2016-09-13 21:24
Not sure if this is the place to comment. But the Quoting Strings with Single Quotes still seems to be buggy and won't pass.

**Comment by leontranter** [comment] 2016-11-14 11:13
I'm stuck on the Quoting Strings with Single Quotes challenge. I'm 100% certain I've got the right answer in but it's failing two tests (remove all the backslashes, you should have two single quotes and four double quotes). Very frustrating, can't get past this problem :(

**Comment by dhcodes** [comment] 2017-08-02 17:19
Tested on Chrome and Firefox after new updates. Both are working. Closing this issue unless it crops up again.

**Closed by dhcodes** 2017-08-02 17:19 UTC
Labels: discussing
