### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by garrettvorce** [FreeCodeCamp/FreeCodeCamp#7205] opened 2016-02-23 15:43 UTC
Challenge [Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/decrement-a-number-with-javascript#?solution=var%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar--%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 11;

// Only change code below this line
myVar--;
/*Typed  "--;" after myVar, said I was missing a semicolon. Fixed upon pasting from "i--;" */

```

**Comment by ltegman** [comment] 2016-02-23 19:28
I'm not able to reproduce this. Are you able to reproduce this error again? If so please paste in the code that _doesn't_ work, rather than the fixed code.

**Comment by Isarian** [comment] 2016-02-24 16:30
@garrettvorce Is it possible you did the following?

```
var myVar = 11;

// Only change code below this line
myVar = myVar--;
```

That code won't work, it needs to be just "myVar--"

**Comment by techtolentino** [comment] 2016-02-26 01:35
I can't reproduce this error either, I don't think there's a bug with this specific challenge.

**Comment by ltegman** [comment] 2016-02-26 01:48
Closing as no repro. If you can provide consistent repro steps please feel free to reopen. Thanks and happy coding!

**Closed by ltegman** 2016-02-26 01:48 UTC
Labels: blocked
