### ISSUE TITLE
Repeated problems with cursor, in editor only. 

### ISSUE THREAD

**Issue by KittSmith** [FreeCodeCamp/FreeCodeCamp#8253] opened 2016-04-23 06:01 UTC
Style Text Inputs as Form Controls
https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls

#### Issue Description

My cursor will not move through the code editor properly. I will try to select a spot in the code and I just can't. This has been an issue through multiple challenges. A hard refresh fixes it some of the time but it just keeps happening. It isn't my equipment either. I have tried restarting my computer. I have a mouse, touchscreen, and keyboard and none of them work properly while trying to move through. 

#### Browser Information

* Browser Name, Version: Firefox, 45.0.2 
* Operating System: Windows !0
* Mobile, Desktop, or Tablet:  Desktop.

**Comment by raisedadead** [comment] 2016-04-23 07:05
@KittSmith thanks for reporting this, yes we have some ongoing issues with the code editor that we depend upon. 

Investigating.

@erictleung this looks similar to #8252

**Comment by erictleung** [comment] 2016-04-23 07:07
@raisedadead Yeah, even @BerkeleyTrue has [linked it to a CodeMirror issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7528#issuecomment-203452617) that has been made.

**Comment by raisedadead** [comment] 2016-04-23 07:12
Ah thanks for the update.

**Comment by QuincyLarson** [comment] 2016-04-23 08:20
+1 another camper just emailed me about this.

**Comment by KittSmith** [comment] 2016-04-23 20:28
Yeah, a few people were a bit mean about it in chat. " Erase your cookies, duh!" Like I haven't tried that. I figured something was up. It is frustrating. I hope y'all can fix it soon. I really enjoy learning with free code camp. Thanks for all the prompt responses. I am a stay at home mom so I might not get to touch the computer till the evening.

**Comment by cbogsin** [comment] 2016-04-25 00:57
I'm having the same problem - just to add to the data. Thanks for looking into it.

**Comment by KittSmith** [comment] 2016-04-25 05:01
Still having the same problem.

**Comment by KittSmith** [comment] 2016-04-25 05:01
I know y'all are working hard on it though. Not trying to be a butt about it, just sad.

**Comment by BerkeleyTrue** [comment] 2016-04-25 05:11
Thank you all for reporting. This is not a directly actionable issue here on Free Code Camp. This is a known issue with CodeMirror. Please comment here https://github.com/codemirror/CodeMirror/issues/1862.

If what you are seeing is not the same as the issue open a new issue with [CodeMirror](https://github.com/codemirror/CodeMirror/issues) with steps to reproduce.

**Comment by shornedo** [comment] 2016-04-26 14:10
Hi, having the same issue. Before after clicking around, eventually the cursor would move to the correct location. Now, since yesterday, I can't move forward to my next challenge because the cursor just won't work. Thanks for keeping us updated on the issue.

**Comment by bugron** [comment] 2016-05-27 11:23
Thanks everyone for your reports.
We have updated CodeMirror a couple of days ago (see https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8737) and, hopefully, this issue is solved with that update. I'm going to close it but, @KittSmith please, feel free to reopen if you still can reproduce this issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-05-27 11:23 UTC
