### ISSUE TITLE
Beta - "HTML/HTML 5 - Link to Internal Sections of a Page with Anchor Elements" loads empty preview

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16795] opened 2018-02-28 02:37 UTC
#### Issue Description

When arriving at the "HTML HTML 5 - Link to Internal Sections of a page with anchor elements" lesson, 
the preview loads an empty screen.

When you start to type in code the page suddenly refreshes and the preview pane is showing the contents from the previous challenge 

On page refresh an error appears on the dev console, screenshot is available below

Issue happens on both local copy of FCC and the current web based beta.

FYI: Some panels were removed to declutter the screenshot 

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

On Lesson Load:
![image](https://user-images.githubusercontent.com/22984739/36766743-32ec6b7e-1c05-11e8-80da-8508a9ee866b.png)

After typing in editor:
![image](https://user-images.githubusercontent.com/22984739/36767021-76d954f4-1c06-11e8-98ef-349ce6055aa1.png)

After Page Refresh:
![image](https://user-images.githubusercontent.com/22984739/36767238-a73ca064-1c07-11e8-9afb-2c99b0ee429d.png)

**Comment by vkWeb** [comment] 2018-02-28 07:55
@mstellaluna I'm not able to reproduce it. I loaded many challenges of HTML section and they all are loading with the preview. Also, that typing behaviour is expected. I think we should close this?

**Comment by mstellaluna** [comment] 2018-02-28 12:43
@vkWeb I am able to reproduce this error on two different computers and in the live copy and local copy of Beta. Please check with @Bouncey, @systimotic and/or @raisedadead  before closing this out.

**Comment by vkWeb** [comment] 2018-02-28 14:04
> I am able to reproduce this error on two different computers and in the live copy and local copy of Beta.

@mstellaluna No - I'm not a moderator, I cannot close issues 😅. Actually, I was asking you to close. 

> Please check with @Bouncey, @systimotic and/or @raisedadead before closing this out.

Okay, I'll try to confirm this in our contributor's chatroom.

**Comment by mstellaluna** [comment] 2018-02-28 14:15
@vkWeb sorry i don't close any issues, i don't get involved that is why i tagged the core team members.

**Comment by vkWeb** [comment] 2018-02-28 14:26
@mstellaluna Okay.

**Comment by Bouncey** [comment] 2018-02-28 14:41
@mstellaluna this is a security feature in chrome that we are resisting the urge to modify. We only set the iframe (preview) to `allow-scripts` when you decide to edit/run the code.

@raisedadead have I got that right? Is there anything we could do to aid UX?

**Comment by mstellaluna** [comment] 2018-02-28 14:47
@Bouncey the other challenges prior and after don't have this issue. the preview comes up as it should. this one particular one for some odd reason I need to type in the editor for it to show up... that's why I opened the issue

**Comment by raisedadead** [comment] 2018-02-28 16:35
@Bouncey @mstellaluna 

There are a couple of things going on here. And I guess this is a bit tricky problem

To reproduce:
1. Start a incognito window.
2. Visit any challenge with the Cat Photo image for example https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/turn-an-image-into-a-link
3. You should see this happening.

So, I think this is not limited to any challenge.

Because,
If you click a link for any other challenge with the image including the one in the discussion here, the behavior is as expected, with a proper render.

I think this could be a SSR issue.

**Comment by Bouncey** [comment] 2018-02-28 17:43
@BerkeleyTrue do we want to trigger the build pipeline on `appMount` to combat this?

**Comment by BerkeleyTrue** [comment] 2018-03-06 17:25
@Bouncey The current trigger is when the challenge loads, which for the initial load is SSR. Yes, appMount should be sufficient to trigger the preview after SSR.

**Comment by scissorsneedfoodtoo** [comment] 2018-05-01 09:31
Was going through the current PRs to see if I could help QA anything when I saw #16986. Pulled it, and when I did the tests that @raisedadead mentioned above the preview window loads correctly.

Just wanted to mention it here in case anyone sees this issue and starts working on it again.

**Comment by QuincyLarson** [comment] 2018-06-03 16:13
@scissorsneedfoodtoo Awesome - so if I understand you correctly, this is now fixed on https://learn.freecodecamp.org? If not, please reopen this.

**Closed by QuincyLarson** 2018-06-03 16:13 UTC
Labels: beta

**Comment by scissorsneedfoodtoo** [comment] 2018-06-04 00:37
@QuincyLarson, yes, this is working properly now on Learn!
