### ISSUE TITLE
Backend challenges are either not working or unclear

### ISSUE THREAD

**Issue by thomlom** [freeCodeCamp/freeCodeCamp#12851] opened 2017-01-25 19:34 UTC
Challenge [using-packagejson-the-core-of-any-nodejs-project-or-npm-package](http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The goal of the challenge is unclear : 

- You should precise that HyperDev has been renamed to Gomix
- We don't have links to any boilerplates or any tutorial to start a project on Gomix
- We don't know how to relate Gomix to the FCC challenges

It seems that all of the backend challenges feel the same.

**Comment by raisedadead** [comment] 2017-01-25 19:40
Duplicate of #12071 
@thomlom thanks for the report and we are working on getting the migration done as soon as possible.

/cc @Em-Ant

**Closed by raisedadead** 2017-01-25 19:40 UTC

**Comment by Em-Ant** [comment] 2017-01-25 20:03
@thomlom  I am very sorry. This is not the final version of the view. Read [this comment(]https://github.com/freeCodeCamp/freeCodeCamp/issues/12740#issuecomment-275216589) for more details. Please be patient.
