### ISSUE TITLE
Home page is routing to 'Learn How Free Code Camp Works' after logging out and logging back in regardless of last challenge completed

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#6839] opened 2016-02-09 02:12 UTC

**Comment by bugron** [comment] 2016-02-16 08:33
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6382. Thanks for posting.

**Closed by bugron** 2016-02-16 08:33 UTC
