### ISSUE TITLE
Exact change - Correct output but failing test case.

### ISSUE THREAD

**Issue by michaelzap94** [freeCodeCamp/freeCodeCamp#13319] opened 2017-02-13 14:57 UTC
#### Challenge Name
Exact Change

#### Your Code

```js
var denominations = 
  { 'ONE HUNDRED': 10000,
   'TWENTY': 2000,
  'TEN': 1000,
  'FIVE': 500,
  'ONE': 100,
  'QUARTER': 25,
  'DIME': 10,
  'NICKEL': 5,
  'PENNY': 1};
function checkCashRegister(price, cash, cid) {
  var change;
  // Here is your change, ma'am.
  var changeDue = Math.round((cash - price)*100);
  var availableFunds =0;
  cid.forEach(function(e){
    availableFunds += Math.round(e[1]*100);
  });

  if(changeDue>availableFunds){
    return "Insufficient Funds";
  }else if(changeDue==availableFunds){
    return "Closed";
  }
  for(var key in denominations){
    if(denominations[key]>changeDue){
      delete denominations[key]; 
    }
  }
 
  var availableCurrencies = cid.filter(function(e){
      return denominations.hasOwnProperty(e[0]);
  }).map(function(e){
      return [e[0],Math.round(e[1]*100)];
  }).reverse();
  
  var arr = [];
  availableCurrencies.forEach(function(e){
      var available = e[1];
      var initialAv = e[1];
      var currentDenom = denominations[e[0]];

  
    if(changeDue>0){
      while(available>=currentDenom&&changeDue>0&&changeDue>=currentDenom){

       
           changeDue = changeDue-currentDenom;
          available = available-currentDenom;
      }
      if(changeDue===0||available===0||changeDue<=currentDenom){
        var checkItWasUsed =initialAv-available;
        if(checkItWasUsed){
          var arrelement = [e[0], (checkItWasUsed/100)];
        arr.push(arrelement);
        }
      }
    }
  });
  
  if (arr.length < 1 || changeDue > 0) {
    return "Insufficient Funds";
  }

   return arr;
}


checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/9117805/22888177/b6524ba2-f1fc-11e6-9c70-5dd0143ca2f6.png)

**Comment by StevenRB** [comment] 2017-02-13 15:19
This reminds me of CS50's greedy algorithm.

**Comment by raisedadead** [comment] 2017-02-13 17:36
I am afraid that not all tests are passing with the code you have posted, can you check again, you would have to scroll on the side pane.

![image](https://cloud.githubusercontent.com/assets/1884376/22895020/05e280ee-f241-11e6-8349-2b3b5a8c042a.png)

**Comment by raisedadead** [comment] 2017-02-15 15:17
Please confirm if you were able to identify this as a false positive.

**Comment by michaelzap94** [comment] 2017-02-15 15:59
The result of my screenshot is the same as the expected result of the test that's failing.

**Comment by raisedadead** [comment] 2017-02-22 16:49
/cc @freeCodeCamp/moderators I can reproduce this, but would need assistance in finding the root cause.

Note: This has been moved to "Coding Interview Section" in the beta site.

**Comment by Greenheart** [comment] 2017-02-22 20:30
[Here's an experiment I did](https://repl.it/FuIM/2). I can reproduce this as well.

To find this issue, we need to do the following things:
1. Verify that the `result` of the provided solution and the `expected` array match 100%.
2. If they do, we can limit this search to the test case - or the underlying testing framework.

**Comment by raisedadead** [comment] 2017-02-23 03:36
@Greenheart thanks for the PoC. Yup we could update this test case to use deep equals.

**Comment by Greenheart** [comment] 2017-02-23 10:39
@raisedadead It seems to be using `assert.deepEquals()` [See here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-algorithm-questions.json#L203)

**Comment by raisedadead** [comment] 2017-02-23 12:04
Oh, I had not checked, my bad. But your PoC uses `assert.deepEquals()` as well. Hmm, interesting issue.

**Comment by Greenheart** [comment] 2017-02-23 13:16
@raisedadead It's not the exact equivalent to `assert.deepEquals()` - We should probably try to test the code using the **real** `assert.deepEquals()` algorithm before we can be sure that this issue is about the test case.

**Comment by raisedadead** [comment] 2017-02-23 15:33
Yup that makes sense.

**Comment by k-von** [comment] 2017-04-11 07:03
Hi, Has this issue been fixed, I seem to have the same problem with the fifth test. Correct output but doesn't pass.  Here's my code:


function checkCashRegister(price, cash, cid) {
  var change = [];
  var perfectChange = true;
  var denominations = {"PENNY": 0.01,
                       "NICKLE": 0.05,
                       "DIME": 0.10,
                       "QUARTER": 0.25,
                       "ONE": 1.00,
                       "FIVE": 5.00,
                       "TEN": 10.00,
                       "TWENTY": 20.00,
                       "ONE HUNDRED": 100.00
                      };
  var changed = cash - price;
  
  cid.reverse();
 
  cid.forEach(function(element,indx, array) {
    var billDenomination = (changed/denominations[element[0]]).toFixed(2);
 //   console.log('iteration changed: ' + changed);
 //   console.log('element: ', element);
     if (billDenomination >= 1 && element[1] !== 0 ) {
       
         
            if( element[1] - Math.floor(billDenomination)*denominations[element[0]] > 0) {
              perfectChange = false;
              change.push([element[0], Math.floor(billDenomination)*denominations[element[0]]]);
              changed = changed -Math.floor(billDenomination)*denominations[element[0]];
            } else if ( element[1] - Math.floor(billDenomination)*denominations[element[0]] < 0) {
              perfectChange = false;
              change.push([element[0], element[1]]);
              changed = changed - element[1];
            } else {
              change.push([element[0], element[1]]);
              changed = changed - element[1];
            }
            
           
          
 //      console.log(changed);
     }
  

  });
 // console.log('change: ',change);
  
  
  if (changed !== 0) {
    return "Insufficient Funds";
  }  else if (perfectChange === true) {
    return "Closed";
  } else {
  
  
  // Here is your change, ma'am.
  return change;
  }
}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

checkCashRegister(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);``

**Comment by augmt** [comment] 2017-04-14 12:57
@michaelzap94 Though your code can pass all the tests individually, it must work for all the tests in succession. Deleting entries from your `denominations` object is what's causing your code to return incorrect results.

@k-von Your code is fine but you need a way to deal with precision errors when subtracting decimals. Rounding to the nearest hundredth is one way to do so.

**Comment by ladiag** [comment] 2017-05-27 23:08
Hi, I have the same issue with my code and I don't succeed in finishing this exercise. Please advise.

Thanks in advance

Best,

`function checkCashRegister(price, cash, cid) {
  var soldeInit = 0;
  var solde = 0;
  var rendu = cash - price;
  var monnaie = [0.01, 0.05, 0.1, 0.25, 1, 5, 10, 20, 100];
  var portefeuille = [];
  var couple = [];
  cid.reverse();
  monnaie.reverse();
  
  for (var j = 0; j < cid.length; j++) {
    //console.log(somme(portefeuille) + " somme ptf");
    //console.log(rendu + " rendu");
    if ((rendu - monnaie[j] > 0) && (somme(portefeuille) !== rendu)) {
      couple.push(cid[j][0]);
      couple.push(Math.min((rendu / monnaie[j]).toFixed(0) * monnaie[j], cid[j][1]));
      portefeuille.push(couple);
      couple = [];
      rendu -= somme(portefeuille);
      rendu = rendu.toFixed(2);
    }
    else {
      couple = [];      
    }
  }
  
function somme(ptf) {
  var resultat = 0;
  for (var m = 0; m < ptf.length; m++) {
    resultat += ptf[m][1];
  }
  var total = resultat.toFixed(2);
  return total;
}

  //il faut vérifier si les multiples sont supérieurs à la réalité ou pas
  //il faut vérifier si j'ai chaque piece qu'il faut ou pas
  
  if (somme(portefeuille) < rendu) {
    console.log("Insufficient Funds");
    return "Insufficient Funds";
  }
  else if (somme(portefeuille) === somme(cid)) {
    return "Closed";
  }
  else {
    return portefeuille;
  }
}  `

**Comment by augmt** [comment] 2017-05-28 15:50
@ladiag, in your for loop you should not subtract `somme(portefeuille)` from `rendu`, just the change you've calculated for that step. Also keep in mind that `toFixed` rounds up, which is not what you always want.

If you are ever looking for help, consider [FreeCodeCamp's Gitter chatrooms](https://gitter.im/FreeCodeCamp/home). There are rooms full of campers for every kind of challenge.

**Comment by ladiag** [comment] 2017-05-28 16:04
Hello Hector,

Thanks for your answer. Actually, somme(portefeuille) and the change I have
calculated are the same in my for loop. And it works best for all the cases
apart from this very only one because of the rounding issue.

The issue is that I have one result that is never rounding and is rendu =
36.739999999999995, it makes all my formulas bug... Do you see what I mean ?

Thanks a lot for your assistance



---
Thibault de la Baronnière
T: +33 (0)6 61 97 52 24
Prendre rdv : calendly.com/tbb
@TdelaBaronniere <https://twitter.com/TdelaBaronniere>

2017-05-28 17:52 GMT+02:00 Hector Garcia <notifications@github.com>:

**Comment by QuincyLarson** [comment] 2017-06-17 05:18
This seems to be working fine so I'm closing this issue.

**Closed by QuincyLarson** 2017-06-17 05:18 UTC
Labels: help wanted
