### ISSUE TITLE
Issue with layout of the mobile preview in lessons

### ISSUE THREAD

**Issue by shaikhatik0786** [FreeCodeCamp/FreeCodeCamp#2802] opened 2015-08-28 11:54 UTC
Hmm, I don't know why, but I am getting issues with the preview layout in the bootstrap section.
First in the buttons section :  http://prntscr.com/89uesz

Then in the check box section: http://prntscr.com/89ujcq

I am sure there is no error with my code, but still I am pasting the code for it here
```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
```

**Comment by benschenker** [comment] 2015-09-08 05:30
Hey @shaikhatik0786 thanks for posting!

I think you are saying that http://freecodecamp.com/challenges/waypoint-responsively-style-radio-buttons  has the delete button cut off. Am I right?  I have confirmed this.

That seems to be a cosmetic issue with almost all of the waypoints after this one. We can probably fix it by changing the default markup.

I couldn't replicate the checkbox issue you refer to.

**Comment by joshaquino** [comment] 2016-02-04 08:36
I'm getting the same result, the Delete button is cutoff.

**Comment by YugHug** [comment] 2016-03-09 03:53
the checkboxes do look odd ("Loving") is situated oddly. I'm not sure how to paste code here.

**Comment by bugron** [comment] 2016-05-27 13:47
Closing this issue in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7842.

**Closed by bugron** 2016-05-27 13:47 UTC
Labels: bug, confirmed, help wanted
