### ISSUE TITLE
Right hand pane not updating

### ISSUE THREAD

**Issue by johnhalim22** [freeCodeCamp/freeCodeCamp#14731] opened 2017-05-05 15:15 UTC
Challenge [move-a-relatively-positioned-element-with-css-offsets](http://beta.freecodecamp.com/en/challenges/applied-visual-design/move-a-relatively-positioned-element-with-css-offsets) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<head>
<style>
  h2 {
    position: relative;
    
    
  }
</style>
</head>
<body>
  <h1>On Being Well-Positioned</h1>
  <h2>Move me!</h2>
  <p>I still think the h2 is where it normally sits.</p>
</body>

```
The right hand pane does not update in the beta version until you test your code. Kind of impossible to see what your code is doing. Tried in Chrome, IE, Edge, and Opera. Not sure if this is a browser/plugin issue.

![image](https://cloud.githubusercontent.com/assets/18270152/25751810/3cd49150-3184-11e7-8718-d39a57c70bd3.png)

**Comment by raisedadead** [comment] 2017-05-05 15:49
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12923

**Closed by raisedadead** 2017-05-05 15:49 UTC
