### ISSUE TITLE
"Clone an Element Using jQuery" Page Double Clone

### ISSUE THREAD

**Issue by cn808** [FreeCodeCamp/FreeCodeCamp#7019] opened 2016-02-15 04:46 UTC
I noticed that when I hit the "Run Test" button after completing the challenge, two "#target5" buttons appear on the "left-well".  Not sure if that's intentional or a bug.  Thanks.

**Comment by sludge256** [comment] 2016-02-15 05:29
Duplicate of #5072

**Closed by sludge256** 2016-02-15 05:29 UTC
