### ISSUE TITLE
Code in editor is rendered twice

### ISSUE THREAD

**Issue by robeth** [FreeCodeCamp/FreeCodeCamp#2760] opened 2015-08-27 03:14 UTC
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I visit challenge page, the HTML inside editor is rendered twice.

![catphotoapp](https://cloud.githubusercontent.com/assets/1451171/9511733/ea83859e-4ca3-11e5-823f-4e636292e702.png)

Notice there are two title CatPhotoApp.

This issue, however, is gone when click the `Run Code` button or press control + Enter.

![catphotoapp after run](https://cloud.githubusercontent.com/assets/1451171/9511769/4185f002-4ca4-11e5-96e2-0e09eac1a322.png)

Maybe there is something wrong with the onload/initial callback.

Additional info:
Browser: Mozilla Firefox 40.0
OS: Ubuntu 14.04

Thank you for the amazing learning resource :)

**Comment by robeth** [comment] 2015-08-27 03:20
Additional info:

Browser: Mozilla Firefox 40.0
OS: Ubuntu 14.04

**Comment by BerkeleyTrue** [comment] 2015-08-27 06:35
Closing as duplicate of #2706

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-27 06:35 UTC
