### ISSUE TITLE
use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements [beta]

### ISSUE THREAD

**Issue by computerluca** [freeCodeCamp/freeCodeCamp#12736] opened 2017-01-22 14:11 UTC
Challenge [use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements](http://beta.freecodecamp.com/en/challenges/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<body>
<header>
  <h1>Even Deeper Thoughts with Master Camper Cat</h1>
  <nav>
    <ul>
      <li><a href="">Home</a></li>
      <li><a href="">Blog</a></li>
      <li><a href="">Training</a></li>
    </ul>
  </nav>
</header>
<form>
  <label for="search">Search:</label>
  
  
  <input type="search" name="search" id="search" tabindex="1">
  <input type="submit" name="submit" value="Submit" tabindex="2" id="submit">
  
  
</form>
<h2>Inspirational Quotes</h2>
<blockquote>
  <p>&ldquo;There's no Theory of Evolution, just a list of creatures I've allowed to live.&rdquo;<br>
  - Chuck Norris</p>
</blockquote>
<blockquote>
  <p>&ldquo;Wise men say forgiveness is divine, but never pay full price for late pizza.&rdquo;<br>
  - TMNT</p>
</blockquote>
<footer>&copy; 2016 Camper Cat</footer>
</body>

```
    It shows me that the code is correct but the preview on the right shows an error
![schermata del 2017-01-22 14 57 40](https://cloud.githubusercontent.com/assets/2115202/22183074/70e2df6c-e0b5-11e6-916b-449147dbeca5.png)

**Comment by systimotic** [comment] 2017-01-22 14:19
Hi @computerluca! Thank you for reporting this issue.

It looks like this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12683
The word `for` in your HTML triggers loopProtect. I'm closing this issue in favour of the other one.

Happy coding!

**Closed by systimotic** 2017-01-22 14:19 UTC
