### ISSUE TITLE
Sudoku Solver Example Rejects Valid Input

### ISSUE THREAD

**Issue by diegoperezm** [freeCodeCamp/freeCodeCamp#48687] opened 2022-12-07 16:16 UTC
### Describe the Issue

The example Sudoku Solver rejects valid input.

### Affected Page

https://sudoku-solver.freecodecamp.rocks/

### Your code

Input the following and click "Solve":

```
........................................................8.................6......
```

### Expected behavior

It should produce a solved Sudoku puzzle.

### Screenshots

![valid-1](https://user-images.githubusercontent.com/12677127/206231768-fce2bce6-eec4-4eec-bd74-4adee283a82c.png)

### System

Device:  Laptop
OS:      Ubuntu 18.04.5 LTS
Browser: Chromium
Version: 90.0.4430.72

### Additional context

https://github.com/freeCodeCamp/demo-projects/tree/main/apps/sudoku-solver

**Comment by Nirajn2311** [comment] 2022-12-21 19:09
The recursion constraint is the cause of this bug - [Link to line in code](https://github.com/freeCodeCamp/demo-projects/blob/0a115e4203c91011e75a2c3661794ab27d583a13/apps/sudoku-solver/controllers/sudoku-solver.js#L204)

It stops the solving of the puzzle at 50000 recursion but this input takes around 250k recursions. We have two ways of going ahead here:
1. Increase the recursion limit
2. Update the algorithm used to more efficient

**Comment by ojeytonwilliams** [comment] 2023-01-05 14:21
If it's only 5 times slower, it's probably fine to keep using the inefficient algorithm.

**Comment by ojeytonwilliams** [comment] 2023-01-18 15:45
There are two issues needing attention

1. The algorithm could be improved
2. The initial state needs to be validated

**Comment by ShaunSHamilton** [comment] 2023-04-19 17:45
The recursion limit has been increased. However, as this is run on the server, and the server could serve dozens of Campers at the same time, it cannot be increased to the point of being able to brute force the examples given.

---

As such, to close this issue, the algorithm will need to be improved.

**Comment by Shenghan0329** [comment] 2023-04-22 21:41
Hello, for Sudoku-solving algorithm, the website [AnySudokuSolver](https://anysudokusolver.com/) has a non-recursive algorithm and input checks. The algorithm also works well for this input:

 `........................................................8.................6......`.

![image](https://user-images.githubusercontent.com/106292687/233807638-26d7256f-ab15-4b19-abcc-8d0927f516a7.png)
![image](https://user-images.githubusercontent.com/106292687/233807624-b4eaaf4d-50cd-400f-9f46-09e96ea2c090.png)


The codes from this website can be helpful for solving this issue, so I'm wondering if there is a copyright issue to use some of them in our contributions.

**Comment by gikf** [comment] 2023-04-26 20:33
I have additional proposition.

Puzzles with less than `17` clues (pre-filled numbers in the grid) cannot have a unique solution - https://phys.org/news/2012-01-mathematicians-minimum-sudoku-solution-problem.html. Why not exclude by default puzzles that cannot have unique solution? Expecting only _proper_ puzzles to be solved in project like this would not be unreasonable.

**Comment by ShaunSHamilton** [comment] 2023-04-27 09:16
@gikf That could definitely be one way to go.

However, thinking about this more, and realising this is a certification project example that already passes all the given user stories and tests, I do not think we should do anything more here.

This is not supposed to be the most perfectest sudoku app. This is supposed to be an example app that passes all the freeCodeCamp user stories.

Does anyone else agree? Or, should we improve this app beyond the expected requirements?

**Comment by gikf** [comment] 2023-04-28 11:13
I do agree, however I think there's need to more clearly indicate the _perfection_ is not the goal.

**Comment by sporadicus** [comment] 2023-05-14 06:22
> Does anyone else agree? Or, should we improve this app beyond the expected requirements?

If it's likely and/or desirable that the learner will look at the example app code, then it doesn't seem like a bad thing for that code to be exemplary in various ways (efficient, well-commented, &c.).

To that end, I took a stab at rewriting the solving code to be well-commented, declarative-ish, and functional-ish. To improve efficiency a bit, it also modified the blind brute-force solving algorithm to instead always attempt to solve cells with the fewest possible solutions. This change in approach generated many fewer recursions, but the usage of declarative and functional code made it significantly less efficient overall than the original code (in terms of running time) when starting from puzzle states like the default one, and about twice as efficient than the original when starting from a state with fewer cells of known values. To improve on this (in)efficiency, I then tried factoring out various aspects of the code's functional-ness.

All of the above is probably overkill but, if any of these code variations happen to be of any interest here, let me know and I'll be happy to post it—in case it's relevant, I'll list the variations' approximate relative run times below.

Let's use 't' to refer to the running time of the original code on the default puzzle starting state of:
`..9..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6..`
In the below table is each variation's run time (as a multiple of 't') for both the default starting state and for the starting state listed in OP's first comment:
`........................................................8.................6......`

<table>
    <tr>
        <th></th>
        <th>Default start state</th>
        <th>'8-6' start state</th>
    </tr>
    <tr>
        <td>Original code</td>
        <td>t [baseline]</td>
        <td>200t</td>
    </tr>
    <tr>
        <td>Mostly pure functions</td>
        <td>60t</td>
        <td>110t</td>
    </tr>
    <tr>
        <td>Mostly impure functions</td>
        <td>15t</td>
        <td>20t</td>
    </tr>
    <tr>
        <td>Impure + no structuredClone()</td>
        <td>6t</td>
        <td>12t</td>
    </tr>
</table>

(So, for example, the original code takes about 200 times longer to solve the puzzle containing only the '8' and '6' than it does to solve the app's default puzzle.)

**Comment by sporadicus** [comment] 2023-05-15 06:30
> Do you know why the code accepts this inputs (I have only replaced the 8 with a 1 (in the first example) and with a 2 (in the second example))

Hi @diegoperezm, the reason appears to simply be a function of the way that the original solving algorithm proceeds through evaluating possible solution values. When that particular algorithm is used to solve either of your revised starting states (i.e. replacing the '8' with a '1' or '2'), it happens to need many fewer recursions (around 300) than the 250,000+ recursions needed to solve the original "8-6" starting state. Your revised starting states ("8-1" and "8-2") are accepted because the number of recursions they require to be solved is below the "recursion limit" set in the code to prevent overconsumption of compute resources.

(I haven't played around with many variations of starting puzzle states (and I'm not a mathematician), so I can't say whether there's a reason for the difference in number-of-required-recursions between these starting values, beyond "it's just a function of the algorithm ¯\_(ツ)_/¯".)

**Comment by diegoperezm** [comment] 2023-05-15 17:20
Thanks a lot @sporadicus, it's really interesting. 

I've tried other combinations:
 Accepted combinations ("1-n"):

```
........................................................1.................2......
```

```
........................................................1.................3......
```
```
........................................................1.................4......
```
```
........................................................1.................5......
```
```
........................................................1.................6......
```
```
........................................................1.................7......
```
```
........................................................1.................8......
```
```
........................................................1.................9......
```

 Accepted combinations ("n-1"):

```
........................................................2.................1......
```
```
........................................................3.................1......
```

```
........................................................4.................1......
```

```
........................................................5.................1......
```

```
........................................................6.................1......
```

```
........................................................7.................1......
```

```
........................................................8.................1......
```

```
........................................................9.................1......
```

**Comment by moT01** [comment] 2024-06-20 14:54
Closing this as stale. cc @ilenia-magoni Thanks and happy coding 🎉

**Closed by moT01** 2024-06-20 14:54 UTC
Labels: type: bug, help wanted, scope: curriculum
