### ISSUE TITLE
Nothing happens and hints disappear when I hit "Run tests"

### ISSUE THREAD

**Issue by bildungsroman** [FreeCodeCamp/FreeCodeCamp#9289] opened 2016-06-22 11:50 UTC
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%24(%22button%22).addClass(animated)%3B%0A%20%20%24(%22.btn%22).addClass(shake)%3B%0A%20%20%24(%22%23target1%22).addClass(btn-primary)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
  $("button").addClass(animated);
  $(".btn").addClass(shake);
  $("#target1").addClass(btn-primary);
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by raisedadead** [comment] 2016-06-22 12:27
This is a possible bug that got introduced with the animate effect in #9151 
/cc @FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment] 2016-06-22 12:40
@helderspeu

**Comment by Bouncey** [comment] 2016-06-22 12:44
@raisedadead the only issue we had with this was the instructions scrolling on load. But I merged a patch for that this morning. I can't think of the reason for this? 

@heldersepu shall we try and comment out the fade in/out on testsuite?

**Comment by Bouncey** [comment] 2016-06-22 12:47
The challenge still passes with the correct code.

**Comment by heldersepu** [comment] 2016-06-22 12:58
@Bouncey Yes that's right it passes with the right code:
the addClass should be in quotes:
$("button").addClass("animated");

**Comment by raisedadead** [comment] 2016-06-22 13:01
I saw the animation for the instructions twice though, which looked like bit buggy to me.

**Comment by heldersepu** [comment] 2016-06-22 13:08
@raisedadead what do you mean by the animation for the instructions?
#9151 add an animation for the test results not the instructions...

**Comment by heldersepu** [comment] 2016-06-22 13:14
I think this issue brings a valid point ...

An invalid JS Code like:
`$("button").addClass(anima");`
will show: `SyntaxError: Invalid or unexpected token` 

but something like:
`$("button").addClass(anima);`
does not show any error, and we do get an error on the console
**Uncaught ReferenceError: anima is not defined**

**Comment by Bouncey** [comment] 2016-06-22 13:28
For some reason, if there is a syntax error, `#testsuite` fades out and remains hidden.

**Comment by Bouncey** [comment] 2016-06-22 14:05
I think this issue has #9184 in common. The 'fadeOut' had a more visual effect on the test suite

**Comment by heldersepu** [comment] 2016-06-22 14:23
Yes I agree #9184 is related!
Tests do not update on certain conditions and the fadeOut hides them

**Comment by Bouncey** [comment] 2016-06-22 14:43
I have a PR ready to go to remove the fade out/in, but haven't looked into the test updates

**Comment by heldersepu** [comment] 2016-06-22 14:57
I don't think the problem is on the fade out/in...
The fadeOut exposed an old problem: certain conditions the test are not updated

**Comment by heldersepu** [comment] 2016-06-22 15:02
Let's think about it...
From a user perspective if I hit the [Run tests] button I expect to see: 
 - the test results 
 - an error message if the test can not be executed 
Leaving behind the old tests is not a good experience

**Comment by Docwali777** [comment] 2016-06-27 15:57
I used this  and it worked -
I added a second another segment for  id "#target1"

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("animated shake");
    $("#target1").addClass("btn-primary");**

  });
</script>

**Closed** 2016-07-11 08:47 UTC
Labels: bug, help wanted, QA
