### ISSUE TITLE
wind-bow.hyperdev.space is down

### ISSUE THREAD

**Issue by tsalexey544** [FreeCodeCamp/FreeCodeCamp#11614] opened 2016-11-10 23:24 UTC
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

https://wind-bow.hyperdev.space is down.

**Comment by erictleung** [comment] 2016-11-11 02:29
@tsalexey544 thanks for the issue. As @Em-Ant has pointed out,

> Hyperdev is not reliable 24hr as a 'real' server. Sometimes it just happens...

Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11600 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11592.

The site appears to be up again. Happy coding!

**Closed by erictleung** 2016-11-11 02:29 UTC

**Comment by SylvioGiubine** [comment] 2016-11-14 01:24
Sorry, but not working !
