### ISSUE TITLE
Waypoint: Assignment with Minus Equals (result appears incorrect)

### ISSUE THREAD

**Issue by AlyxMoon** [FreeCodeCamp/FreeCodeCamp#5626] opened 2015-12-31 07:39 UTC
Challenge [Waypoint: Assignment with Minus Equals](http://www.freecodecamp.com/challenges/waypoint-assignment-with-minus-equals#?solution=var%20a%20%3D%2011%3B%0Avar%20b%20%3D%209%3B%0Avar%20c%20%3D%203%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20-%3D%206%3B%0Ab%20-%3D%2015%3B%0Ac%20-%3D%201%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var a = 11;
var b = 9;
var c = 3;

// Only modify code below this line

a -= 6;
b -= 15;
c -= 1;



```

The code and test is okay, but where the result of the test is shown, c is shown to have a value of '2' instead of just 2, making the result seem like it's a string when it's most definitely a number.

**Comment by ltegman** [comment] 2015-12-31 07:43
This is a known issue that has been difficult to solve since we refactored our code base. We currently have a PR in progress that is aiming to fix it though. Closing as a duplicate of #5097. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 07:43 UTC
