### ISSUE TITLE
'Uncaught TypeError' in bonfire test case error handling

### ISSUE THREAD

**Issue by Chrysallis** [FreeCodeCamp/FreeCodeCamp#1072] opened 2015-06-23 03:39 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-spinal-tap-case has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This error prevents the tests in the spinal tap case bonfire from running.

Screenshots: http://imgur.com/YE3xLwh, http://imgur.com/5SZehwu

Can be reproduced by attempting to run the following code in the editor:

    function spinalCase(str) {
      var regex = new RegExp(" _", "g");
      arr = str.split(regex);
      for(var i in arr) {
        arr[i] = arr[i][0].toLowerCase()+arr[i].substring(1);
      }
      var newstring = arr.join("-");
      regex = new RegExp("[A-Z]");
      while(regex.test(newstring)) {
        var j = newstring.search(regex);
        newstring = newstring.substring(0,j)+"-"+newstring[j].toLowerCase()+newstring.substring(j+1);
      }
      return newstring;
    }
    spinalCase('This Is Spinal Tap');

**Comment by Chrysallis** [comment] 2015-06-23 03:43
specifically, line 2 appears to be causing this error.

**Comment by benschenker** [comment] 2015-08-26 02:55
Hey @Chrysallis I'm unable to reproduce this error.  Closing but feel free to reopen if you still have problems

**Closed by benschenker** 2015-08-26 02:55 UTC
