### ISSUE TITLE
Bug in expected result

### ISSUE THREAD

**Issue by Bandianowe** [FreeCodeCamp/FreeCodeCamp#3332] opened 2015-09-16 16:20 UTC
otorhinolaryngology - the longest word has 19 characters, and expected number for this string length is 18

Challenge [Bonfire: Find the Longest Word in a String](http://freecodecamp.com/challenges/bonfire-find-the-longest-word-in-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function findLongestWord(str) {
  strarray = str.split(' ');
  strarray = strarray.map(function(val){
    return val.length;
  }).sort()
  last = strarray.length - 1;
  return strarray[last];
}

findLongestWord("What if we try a super-long word such as otorhinolaryngology");

```

**Comment by bugron** [comment] 2015-09-16 16:51
@Bandianowe Thanks for pointing this out! This is just a typo. Actually, `assert` checks if length of `otorhinolaryngology` is `19` (see [L200](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-bonfires.json#L200)).
Anyway your code is incorrect. The problem is that your `strarray` array isn't sorted as you actually expect. For more info [read this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description). So the correct solution would be something like this:
```javascript
function findLongestWord(str) {
  strarray = str.split(' ');
  strarray = strarray.map(function(val){
    return val.length;
  }).sort(function(a, b) {
    return a - b;
  });
  last = strarray.length - 1;
  return strarray[last];
}

findLongestWord("What if we try a super-long word such as otorhinolaryngology");
```

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Bandianowe** [comment] 2015-09-16 18:55
@bugron Hi Bugron, thanks for pointing that out!

**Comment by bugron** [comment] 2015-09-16 18:58
@Bandianowe Reopening this issue. It will be closed when that typo will be fixed.

**Closed** 2015-09-17 06:45 UTC
Labels: Easy, help wanted, Test Improvement
