### ISSUE TITLE
Incorrect objective

### ISSUE THREAD

**Issue by ryunacho** [FreeCodeCamp/FreeCodeCamp#2112] opened 2015-08-18 19:36 UTC
http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops
Currently asks the user, "Let's try getting a for loop to work by pushing values to an array."
Should be, "Let's try getting a while loop to work by pushing values to an array."

**Comment by michael-krebs** [comment] 2015-08-18 21:15
duplicate of #1802

**Closed** 2015-08-23 04:56 UTC
