### ISSUE TITLE
"Reuse JavaScript Code Using import" challenge throws

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41608] opened 2021-03-26 18:25 UTC
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/reuse-javascript-code-using-import

Forum thread: https://forum.freecodecamp.org/t/reuse-javascript-code-using-import/453041

`TypeError: unknown: (0 , s.extname) is not a function`

Not sure what is going on. Maybe it's related to some dependencies updates? I didn't look into it at all.

**Comment by ojeytonwilliams** [comment] 2021-03-26 19:08
> Not sure what is going on. Maybe it's related to some dependencies updates? I didn't look into it at all.

That's my suspicion.  This should have been caught by the tests, though, so I'll look into how that happened.

**Comment by RandellDawson** [comment] 2021-03-27 02:16
OK, after a binary search approach of testing various commits, the commit where this challenge displays this error is https://github.com/freeCodeCamp/freeCodeCamp/commit/ad9b1f89d8ef21c8ecd81c95717ed7e5582ff380

**Comment by raisedadead** [comment] 2021-03-27 04:33
I have reset the production branches at 92dfb3065cfc62febb49e5a269c01b8e961ae712 (one commit before the offending commit in discussion) and pushed out deployments which should be ready within the hour.

Nice work pin pointing the commit @RandellDawson 

I had my concerns with client breaking somewhere despite our best efforts testing this, @ojeytonwilliams IMHO I think we should rollback parts of the PR and deploy to staging.

Could you urgently look into rolling back bits investigative-ly i.e rolling back only babel changes, followed by the webpack & webpack-cli which I am still skeptical about.

For now once the deployment is out the deployment branches are pinned at 92dfb3065cfc62febb49e5a269c01b8e961ae712 until we get main stable again first thing after the weekend.

**Comment by RandellDawson** [comment] 2021-03-27 06:11
The most disturbing part is that our challenge tests did not break and warn us that something was wrong.

**Comment by raisedadead** [comment] 2021-03-27 06:21
Right. 

The challenge tests did not break because they are not run in a browser environment. #41602 aims to do something that is going to hopefully bring us closer to testing without missing things. I stress "hopefully" though.

It's not that we didn't do a thorough QA as well. Some of us tested quite a few things if you look at the original PR.

In any case, I have an early confirmation that going back one but the offending commit is going to save us the weekend. Oliver has confirmed he will take a look at expanding the tests.

**Comment by raisedadead** [comment] 2021-03-27 06:29
Hey @freeCodeCamp/dev-team, the staging deployment seems to have been fixed for both this issue and the client search. I am proceeding with a deployment further.

**Comment by raisedadead** [comment] 2021-03-27 06:43
Production is fixed for the challenge in the OP. Please close this when you are happy with the rollback.

**Comment by RandellDawson** [comment] 2021-03-27 06:44
Everything is working again on production.

**Closed by RandellDawson** 2021-03-27 06:44 UTC
Labels: scope: curriculum, status: resolved/shipping, type: bug, type: showstopper
