### ISSUE TITLE
Testing Objects for Properties

### ISSUE THREAD

**Issue by chandujstchandu** [FreeCodeCamp/FreeCodeCamp#10725] opened 2016-09-13 18:04 UTC
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0Areturn%20(myObj.hasOwnProperty(checkProp)%20%3F%20myObj%5BcheckProp%5D%20%3A%20%22Not%20Found%22)%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20value%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
return (myObj.hasOwnProperty(checkProp) ? myObj[checkProp] : "Not Found");
}

// Test your code by modifying these value
checkObj("gift");

```

**Comment by dhcodes** [comment] 2016-09-13 20:25
@chandujstchandu your code worked for me. Can you elaborate on the issue you're experiencing?

**Comment by dhcodes** [comment] 2016-09-15 19:24
Closing for now. Reopen if you want to add more info.

**Closed by dhcodes** 2016-09-15 19:24 UTC
Labels: Discussing

**Comment by CoderBug** [comment] 2016-09-22 09:43
![s](https://cloud.githubusercontent.com/assets/22156630/18743521/459d988a-806e-11e6-9fcd-846930f7e82a.png)

when input "house" i get result "Not found" but it wont pass me : /

**Comment by texas2010** [comment] 2016-09-22 14:47
@CoderBug, Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by LakunleD** [comment] 2016-09-25 18:14
The problem is the letter F in "Not Found". Change it to UpperCase F and it would pass

**Comment by Rahul22587** [comment] 2017-01-21 12:24
Can you defined that code because I didn't get that function?
what is checkProp function and if I will change that so it will work same?

**Comment by snntaylan** [comment] 2017-01-22 10:17
what is the problem in my code ?

// Setup
var myObj = {
gift: "pony",
pet: "kitten",
bed: "sleigh"
};

function checkObj(checkProp) {
// Your Code Here
if (myObj.hasOwnProperty(checkProp) === true) {
return myObj.checkProp;
} else {
return "Not Found";
}

}

// Test your code by modifying these values
checkObj("gift");

**Comment by ChrisD1986** [comment] 2017-01-22 10:33
What is the purpose of your code?

**Comment by snntaylan** [comment] 2017-01-22 10:43
@ChrisD1986, I need to write 'Testing Objects for Properties' in my code 

```
// Setup
var myObj = {
gift: "pony",
pet: "kitten",
bed: "sleigh"
};

function checkObj(checkProp) {
// Your Code Here
if (myObj.hasOwnProperty(checkProp) === true) {
return myObj.checkProp;
} else {
return "Not Found";
}

}

// Test your code by modifying these values
checkObj("gift");
```

**Comment by snntaylan** [comment] 2017-01-22 10:45
@ChrisD1986 I coudn't understand what is my problem to definition in my object ?

**Comment by GauravChandrawale** [comment] 2017-02-02 13:22
simply add this line
myObj.hasOwnProperty("house");

and comment rest of code ...
this is another method
