### ISSUE TITLE
I can't proceed to the next challenge

### ISSUE THREAD

**Issue by acolding** [FreeCodeCamp/FreeCodeCamp#8278] opened 2016-04-25 04:30 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by acolding** [comment] 2016-04-25 04:33
It keep's saying that the h2 element should be red and I thought that my code would allow for that.

**Comment by erictleung** [comment] 2016-04-25 04:38
Possibly related to #7753. @acolding are you using an Android or non-desktop/laptop device?

**Comment by bahadjrooy** [comment] 2016-04-25 04:45
<style>
  h2 {
    color: red;
  }
  .red-text{color:red;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by bahadjrooy** [comment] 2016-04-25 04:46
<code>
<style>
  h2 {
    color: red;
  }
  .red-text{color:red;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

</code>

**Comment by theflametrooper** [comment] 2016-04-25 08:34
I'm having the same problem. 

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by theflametrooper** [comment] 2016-04-25 08:34
@bahadjrooy What device are you using?
@erictleung Does everything work fine for you? What devices?

**Comment by erictleung** [comment] 2016-04-25 08:40
@theflametrooper I've ran into this before. I am able to reproduce this on my Android tablet. For whatever reason, my tablet will inject "invisible" characters into my solution, which will throw off the tests. For example, [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8221#issuecomment-212752833). The challenge works perfectly on my desktop/laptop browser.

**Comment by sludge256** [comment] 2016-04-25 08:42
It's the space to the left of `.red-text`.

**Comment by theflametrooper** [comment] 2016-04-25 11:33
@sludge256 I'm guessing we need to adjust the tests to allow spaces

**Comment by acolding** [comment] 2016-04-25 15:14
It's all o.k. now, I am able to proceed.

**Comment by lichuang2015** [comment] 2016-05-06 00:56
I have the same problem. After all test passed, it stuck in submit page, can't proceed.
My device is iPhone 6S, I tried to submit from Windows pc, also can't proceed, pls help.

**Comment by acolding** [comment] 2016-05-06 02:04
Yes, I was using an android but I switched over to my laptop which has a
Windows operating system and I was able to proceed. I think that I will be
using the laptop only from now on.

**Comment by raisedadead** [comment] 2016-06-27 05:15
Closing as duplicate of #7753

**Closed by raisedadead** 2016-06-27 05:15 UTC
Labels: confirmed, tests
