### ISSUE TITLE
FCC's built-in console doesn't show console.log() output (Chrome)

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#10977] opened 2016-09-29 13:48 UTC
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.

The text in the FCC pseudo-console gives the impression that `console.log()` outputs will appear there.
```text
/**
  * Your output will go here.
  * Any console.log() -type
  * statements will appear in
  * your browser's DevTools
  * JavaScript console as well.
  */
```
I thought that the last FCC update added this feature but in Chrome 53.0.2785.116 on Windows, the browser console is still the only way to see `console.log()` output.  I discovered this because students in the chat were confused.  If the FCC console is working as intended, I believe that the text should be clarified.

![image](https://cloud.githubusercontent.com/assets/6234475/18956253/04b848d8-8618-11e6-9ac5-c8d5a34f0177.png)

**Comment by karuppiah7890** [comment] 2016-09-29 14:47
Hey there. The console.log() statements will not show up in the output window ("FCC pseudo-console" in your words). Only the selected data shows up in the output windows, usually the return values of the functions (whose empty body is provided in the challenge) which are tested.

And generally the return value of the top-most function is displayed in the browser. There are challenges that do not have a function wrapping them, so the term "output" is used. 

I have confirmed the above info from the FCC Contributors gitter chat room. You can join there and ask more questions about this.

**Comment by dhcodes** [comment] 2016-09-29 14:52
Also fwiw, the console.log statements do show up in the browser Dev Tools and I think it's worth pointing campers there so they learn those tools as a side-effect.

**Comment by ArielLeslie** [comment] 2016-09-29 16:31
@karuppiah7890 My suggestion is that if this is the intended behavior (as your comment indicates), then the text 
```text
/**
  * Your output will go here.
  * Any console.log() -type
  * statements will appear in
  * your browser's DevTools
  * JavaScript console as well.
  */
```
should probably be changed.  Saying that  the statements will appear in the DevTools console "as well" is giving the impression that the statements can be seen in *both places*.

**Comment by karuppiah7890** [comment] 2016-09-29 17:12
@ArielLeslie I completely agree. I think it should be done. @dhcodes Your comments on this ?

**Comment by dhcodes** [comment] 2016-09-29 17:28
I agree with the change

**Comment by dhcodes** [comment] 2016-09-29 17:36
In [this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4e5fbe513049dcc05f0cf7a3820941ebc0e60e25/client/commonFramework/output-display.js) and [this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/da4e81b52df34fa21613d85dd6b6426d17d1ddaa/common/app/routes/challenges/redux/reducer.js),
remove ` as well` from:

```
/**
  * Your output will go here.
  * Any console.log() -type
  * statements will appear in
  * your browser's DevTools
  * JavaScript console as well.
  */
```

**Comment by BerkeleyTrue** [comment] 2016-09-29 17:39
This is the current behavior with React.

**Comment by dhcodes** [comment] 2016-09-29 17:41
@BerkeleyTrue you mean with React, it will show up in both the output box and the devtools console?

**Comment by BerkeleyTrue** [comment] 2016-09-29 17:53
@dhcodes Yes, console.logs from will show up in the output window. 

We run two different processes for each challenge, the main process that generates the output and the preview, and the test process, which will iterate through the tests.

The first process will actually proxy the calls to console.log so that it shows up in the output window.
The second will not and these will show up in the dev tools console.

**Comment by dhcodes** [comment] 2016-09-29 17:54
Sounds good. Let's close this then since it will be fixed by the React update?

**Closed by dhcodes** 2016-09-29 17:54 UTC
Labels: Discussing

**Comment by samdoj** [comment] 2018-06-18 22:38
I completely agree, though I think console.log(), console.warn(), and console.err() should be added.  It would be as easy as making wrappers for each to change the innerHTML of whatever id displays output.
