### ISSUE TITLE
Some bonfires passing all tests not marking as complete

### ISSUE THREAD

**Issue by hessproject** [FreeCodeCamp/freecodecamp#748] opened 2015-05-29 22:24 UTC
The code passes all tests, but no message displays confirming that the bonfire is completed/the bonfire is not checked off on the map. Screenshots attached of both the Sum of All Odd Fibonacci Numbers and the Binary Agents bonfire with the same issue. Only present on some bonfires, others are working fine.

Happening on both OSX and Linux Mint operating systems using Firefox

![screen shot 2015-05-29 at 5 52 35 pm](https://cloud.githubusercontent.com/assets/11321426/7893788/4d973cfe-062f-11e5-8e9d-ef2b9cbeecf3.png)
![screen shot 2015-05-29 at 5 50 52 pm](https://cloud.githubusercontent.com/assets/11321426/7893786/4d96d926-062f-11e5-96cd-0cfcb310767d.png)
![screen shot 2015-05-29 at 5 50 43 pm](https://cloud.githubusercontent.com/assets/11321426/7893787/4d970d42-062f-11e5-87be-1376a7840578.png)
![screen shot 2015-05-29 at 5 52 42 pm](https://cloud.githubusercontent.com/assets/11321426/7893789/4d9a5470-062f-11e5-8e8a-5be43850c9d9.png)

**Comment by QuincyLarson** [comment] 2015-05-29 22:26
@terakilobyte I went ahead and added you to this card because you're familiar with the bonfires and the firefox issues we're experiencing.

**Comment by terakilobyte** [comment] 2015-05-31 22:09
Regarding binary agents, I was able to reproduce these results with Firefox. However, when I solved it correctly the bonfire produced the correct behavior and offered to move on to the next challenge.

The fibonacci challenge also acts correctly (offering to move on with a valid solution). I'm unsure why the tests are showing as valid as I've duplicated this code exactly and in my version of firefox the challenge correctly shows failing tests.

Incidentally, you should be parsing the integer in the binary agents challenge as it's not base 10 (the default if you don't supply a radix), it is base 2. You are close in your fibonacci solution you have is flawed in the fact it doesn't take into account what happens if a the number passed in is itself a fibonacci. Using your current logic you'll need to go 1 number **beyond** what you want to get and then discard that number.

**Comment by QuincyLarson** [comment] 2015-06-01 01:54
Since we can't reproduce this, I will close this issue for now. Thanks for reporting it, @hessproject and thanks for attempting to isolate it, @terakilobyte.

**Closed** 2015-06-01 01:55 UTC
