### ISSUE TITLE
Escape Sequences in Strings(carriage return)

### ISSUE THREAD

**Issue by janathaworth** [FreeCodeCamp/FreeCodeCamp#10115] opened 2016-08-06 21:03 UTC
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line



```
 Why do we need carriage return instead of new line?

**Comment by erictleung** [comment] 2016-08-06 23:23
@janathaworth we wanted to vary the kinds of escape characters for individuals to try out. You can learn more about the differences here http://stackoverflow.com/a/1761086.

**Comment by erictleung** [comment] 2016-08-07 23:41
@janathaworth I'll be closing this issue as it is not a bug with the site. Please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) or to the [Curriculum Development Gitter room](https://gitter.im/FreeCodeCamp/CurriculumDevelopment) for more feedback on challenges. Happy coding!

**Closed by erictleung** 2016-08-07 23:41 UTC
