### ISSUE TITLE
String.charCodeAt() link is Broken!

### ISSUE THREAD

**Issue by rodionz** [FreeCodeCamp/FreeCodeCamp#8401] opened 2016-05-02 19:37 UTC
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

 **The link for "String.charCodeAt()" in the instruction is broken....**

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  
  return str;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

**Comment by theflametrooper** [comment] 2016-05-02 22:30
Duplicate of #8402.
Please follow this issue instead.

**Closed by theflametrooper** 2016-05-02 22:30 UTC
