### ISSUE TITLE
Oops! Something went wrong. Please try again later

### ISSUE THREAD

**Issue by JakeCage** [FreeCodeCamp/FreeCodeCamp#7012] opened 2016-02-15 01:08 UTC
I keep getting this problem after completing a task. Duplicate user problem?

**Comment by ltegman** [comment] 2016-02-15 01:09
Closing as a duplicate of #6958. We are aware of the problem and working on it. It's been hard to get to the bottom of. Thanks and happy coding!

**Closed by ltegman** 2016-02-15 01:09 UTC
