### ISSUE TITLE
Guide for web-applications link is broken

### ISSUE THREAD

**Issue by KarteekM** [freeCodeCamp/freeCodeCamp#35653] opened 2019-03-22 03:01 UTC
The link : 
https://learn.freecodecamp.org/challenges/get-set-for-our-dynamic-web-application-projects
is broken. It gives a 404 Page not found.
This link is mentioned as a reference for creating a new Github Repository and a new Heroku Project.

You can find the link as a reference in this page:
https://learn.freecodecamp.org/coding-interview-prep/take-home-projects/build-a-voting-app

Kindly provide the appropriate updated URL.

**Comment by thecodingaviator** [comment] 2019-03-22 19:11
Check the latest build over [here](https://freecodecamp.rocks/learn) and report if the problem is still there

**Comment by ojeytonwilliams** [comment] 2019-03-25 15:18
@KarteekM Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #35039, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding.

**Closed by ojeytonwilliams** 2019-03-25 15:18 UTC
