### ISSUE TITLE
[beta][curriculum] Basic JavaScript: Use the Conditional (Ternary) Operator

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#14821] opened 2017-05-11 06:48 UTC
Basic JavaScript: Use the Conditional (Ternary) Operator
https://beta.freecodecamp.com/en/challenges/basic-javascript/use-the-conditional-ternary-operator

I tested my solution in replit
https://repl.it/HsKg/0

refreshing the tab or resetting the code didnt help...

Here is the error that appeared in the js console
![image](https://cloud.githubusercontent.com/assets/7606025/25936130/2378f2f4-35db-11e7-92d3-b44bbb060fc0.png)

**Comment by Margaret2** [comment] 2017-05-11 15:02
Hi, your solution is incorrect. Please click the links VarCI-bot posted to ask for help if you need it.

**Comment by raisedadead** [comment] 2017-05-11 15:29
Invalid return of string vs boolean. Closing as not a bug.

**Closed by raisedadead** 2017-05-11 15:29 UTC
Labels: question

**Comment by tommygebru** [comment] 2017-05-11 21:31
Sorry guys forgot to remove this issue, perhaps we can amend the challenge to refer to a boolean, I mistook it and wrote strings instead :)

**Comment by mmatthews1981** [comment] 2018-08-09 23:19
I'm not sure where to complain about this, so I'll start here. The solution is fairly straightforward, but I don't think it's a good example. If one of my junior devs wrote this line I'd flag it as an anti-pattern for returning raw boolean values instead of returning a boolean expression. I think the question should be changed to something more like "use a ternary operator to return the higher argument".
