### ISSUE TITLE
Reverse a string not working.

### ISSUE THREAD

**Issue by BeauAngel15** [freeCodeCamp/freeCodeCamp#14829] opened 2017-05-11 22:46 UTC
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0A%20%20return%20str%3B%0A%7D%0A%0AreverseString(%22hello%22).split('').reverse('').join('')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
  return str;
}

reverseString("hello").split('').reverse('').join('');

```
when I type "hello" it returns "olleh" and so on so it should be right, right?

**Comment by no-stack-dub-sack** [comment] 2017-05-11 23:11
@BeauAngel15 What I think the problem is is that the function itself should return the reversed string. You are reversing the string that the function returns. 

Try transforming `str` within the function itself and I think you will have better luck. 

For now, I am closing this as not a bug. If you have questions about your solutions and aren't sure there's a bug, the gitter chatrooms or the freeCodeCamp forum are great places to start! 

Good luck and happy coding!

**Closed by no-stack-dub-sack** 2017-05-11 23:11 UTC
