### ISSUE TITLE
 Intermediate Algorithm Scripting: Sum All Primes

### ISSUE THREAD

**Issue by NiteshTyagi** [freeCodeCamp/freeCodeCamp#17726] opened 2018-06-26 18:28 UTC
#### Describe your problem and - if possible - how to reproduce it
Not pass the test case sumPrimes(977) even the logic is correct
#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-primes
#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System: window 8

**Comment by NiteshTyagi** [comment] 2018-06-26 18:29
` function sumPrimes(num) {
  var arr=[];
  var d=0;
  //noprotect
  for(var i=1;i<=num;i++)
  {  //noprotect
    var c=0;
     //noprotect
    for(var j=1;j<=i;j++)
    {
       //noprotect
      if(i%j===0)
      c++;
    }
    if(c==2)
    {
       //noprotect
      arr[d]=i;
      d++;
    }
  }
    var num=arr.reduce(function(total,curr){
        return total+curr;
    });
           //document.write(arr+"<br>"+num);
  return num;
}


sumPrimes(977);`

**Comment by moT01** [comment] 2018-07-27 13:56
@NiteshTyagi were you able to get this to pass? Or have any idea what the problem is?

**Comment by lynxlynxlynx** [comment] 2018-10-11 20:55
duplicate of 17374, can be closed.

**Comment by moT01** [comment] 2018-10-12 12:09
Thank you for reporting this issue.

Closing this as a duplicate, if you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Closed by moT01** 2018-10-12 12:09 UTC
