### ISSUE TITLE
Add issue template for Typo/Formatting Inconsistency/Unclear Instructions

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39021] opened 2020-06-07 06:53 UTC
**Is your feature request related to a problem?**

Currently there's no issue template for **Typo or Formatting Inconsistency or Unclear Instructions** so all the Typo or Formatting Inconsistency or Unclear Instructions has to be reported as a bug. This isn't optimal as some maintainer later on has to come in to change the labels.

**Describe the solution you'd like**

I'd propose to have another issue template for **Typo or Formatting Inconsistency or Unclear Instructions** that any people can use to report these issues across all of FCC's codebase. Any issue created by this issue template will have a **First Timers Welcome**  label which will increase the contribution from new comers and improve the speed of the whole process.

**Additional context**

![image](https://user-images.githubusercontent.com/39026437/83962256-cb38bd00-a8bd-11ea-813d-894944d27992.png)

**Comment by nhcarrigan** [comment] 2020-06-07 06:57
I agree with this. Should it also include the "unclear instructions" items? Technically they are not a bug, since they aren't an "error in a computer program"...

**Comment by UnevenCoder** [comment] 2020-06-07 06:58
I agree 2 , labeling should be thought through again

**Comment by Twaha-Rahman** [comment] 2020-06-07 07:02
> I agree with this. Should it also include the "unclear instructions" items? Technically they are not a bug, since they aren't an "error in a computer program"...

Updated the issue to add **Unclear Instructions** too

**Comment by nhcarrigan** [comment] 2020-06-07 07:15
I do wonder about automatically adding the "first timers welcome" label, though. 
Just in case the issue is more in depth than anticipated, I wouldn't want a first time contributor to be discouraged if the work needed to be passed on to someone else.

**Comment by Twaha-Rahman** [comment] 2020-06-07 07:18
I think we can decide about the label after some discussion....

**Comment by Sky020** [comment] 2020-06-07 13:15
Those labels are being discussed: https://www.freecodecamp.org/forum/t/lack-of-clarity-in-github-labels/400114

As for the templates: I agree, we could do with including templates for typos and clarification. I suppose the reason one was not made is that, in general, we do not expect an issue to be opened, but a PR to fix, if it truly is just a typo.

**Comment by raisedadead** [comment] 2020-06-09 15:35
> ... the Typo or Formatting Inconsistency or Unclear Instructions has to be reported as a bug. This isn't optimal as some maintainer later on has to come in to change the labels.

Can you elaborate with an example for more context?

**Comment by Ieahleen** [comment] 2020-06-09 17:21
The only template I think is missing is the one to report issues in guide or news articles, as this doesn't fit in any of the existing templates, where instead miswording for a challenge can still be considered a bug for that challenge

**Comment by raisedadead** [comment] 2020-06-09 18:30
> The only template I think is missing is the one to report issues in guide or news articles,

A PR is welcome for adding a template.

**Comment by Ieahleen** [comment] 2020-06-09 18:56
> > The only template I think is missing is the one to report issues in guide or news articles,
> 
> A PR is welcome for adding a template.

Wasn't it being worked on? It was discussed in last mods meeting.
Anyway, I have no idea how.

**Comment by raisedadead** [comment] 2020-06-09 19:06
> Wasn't it being worked on? It was discussed in last mods meeting.

I am not sure, if it is or who is supposed to (I will check with @scissorsneedfoodtoo). But if it's not here yet, its safe to work on it.

You would add a template in this directory:
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/.github/ISSUE_TEMPLATE

You can copy paste an existing template, and work from there if it makes it easier and change the contents as needed. It would automatically add the template to the list when its merged.

**Comment by Ieahleen** [comment] 2020-06-09 20:13
> You can copy paste an existing template, and work from there if it makes it easier and change the contents as needed. It would automatically add the template to the list when its merged.

That I have done, I just need ideas on how to finish it - and which tags to use

**Comment by scissorsneedfoodtoo** [comment] 2020-06-11 05:39
Hi @Ieahleen, thank you for your creating this template for guide/news articles. You're right that a template for these kinds of issues was discussed in the [last mod meeting](https://www.freecodecamp.org/forum/t/notes-for-the-may-8th-guide-meeting/385787).

Another thing we talked about was having links at the top of each guide article on the forum that will open an issue with the template you added automatically. These should be added to both the Guide posts on the forum and the ones that were ported to /news. Your template will be really helpful in doing that :+1: :+1:

**Comment by Twaha-Rahman** [comment] 2020-06-11 09:43
> > ... the Typo or Formatting Inconsistency or Unclear Instructions has to be reported as a bug. This isn't optimal as some maintainer later on has to come in to change the labels.
> 
> Can you elaborate with an example for more context? A typo is still a bug. I do not think we should automate labeling first timer issues. IMHO, Triage should be done by a human.
> 
> This is because:
> 
> 1. An issue reported may/or maynot be valid in the first place. A report itself does not make it ready for contribution. It may need thrid-party confirmation.
> 2. First timer issues need to be clear as water. Ideally with instructions on where and how to find the code and what to do to fix.
> 
> First timer issues are meant to be a learning experience. Automating it may lead to more confusion with a first timer, who have already found the whole contributing experience challenging in the first place.

After reading your take on the issue, I agree that we should not label it `First Timers Welcome`. But IMHO, I don't think a typo/formatting inconsistency can be classified as bug. That is why I was proposing to have a simple issue template for typo/formatting inconsistency as there's a lot of issue that are labeled as `bug`. I also think it would be a good idea add a  `Typo` label to the issue. New contributor will always look for simple problems to fix, so if they see an issue with the `Typo` label at a glance, I think they will feel reassured that it's a problem that they can fix and go ahead with the contribution process.

**Comment by raisedadead** [comment] 2020-06-11 10:54
> ... New contributor will always look for simple problems to fix,...

and

> ... they will feel reassured that it's a problem that they can fix and go ahead with the contribution process.

With respect, that's exactly the kind of approach we want to avoid. Personally am quite opinionated that anyone (and I mean anyone) can work on anything. Every issue is trivial and complex at the same time. If I had my way, we would add the `first timers welcome` label on every issue.

What really matters is are you asking the right questions when you are contributing? Especially if you are newcomer. I am very proud to say the mods and maintainers are very welcoming in the freeCodeCamp community when the right questions are asked.

We do not need to make things easier to find, we need to encourage participation. 

While adding labels is like saying "hey this one is easy pick this up", but it's also saying "Everything else is for someone who is an expert, do not look into it". It's subconsicous discouragment of someone's interest.

We would rather want newcomers to ask questions, and not the unhelpful: "Can I work on this?" types but the ones like, "hey how does this script work?", "what's the purpose of that file".

Conversations like that is the learning experience we should strive for.

**Comment by ojeytonwilliams** [comment] 2020-06-11 11:01
@raisedadead if you have a chance, could you take a look at https://www.freecodecamp.org/forum/t/lack-of-clarity-in-github-labels/400114 ?

There's a bit of discussion about the labels we use, but having read your last comment, I'm no longer sure it would be setting the right tone.

**Comment by raisedadead** [comment] 2020-06-11 11:12
Thanks for sharing that thread. I have clarified the intent.

**Comment by raisedadead** [comment] 2020-07-02 17:21
Closing this but please reopen if you still this should be discussed more.

**Closed by raisedadead** 2020-07-02 17:21 UTC
Labels: type: feature request
