### ISSUE TITLE
First instruction is unclear

### ISSUE THREAD

**Issue by abustamam** [FreeCodeCamp/FreeCodeCamp#2518] opened 2015-08-22 20:42 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The first step currently reads: 

> Add two div elements inside your `div class="well">` element both with the class `col-xs-6`

I believe it should be 

> Add two div elements with class `well` inside the div with class `col-xs-6`

For reference, this is the passing code:

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
      </div>
    </div>
  </div>
</div>
```

**Comment by benschenker** [comment] 2015-08-23 04:26
Hey @abustamam thanks for posting an issue!

It looks like this is a duplicate of a bunch of issues and was recently solved in #2459.

Try [a hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) or opening the lesson up in an incognito window.

In the future, please follow our bug reporting guidelines as that will help you resolve these problems quickly: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug

This issue can be closed, though reopen it if you find you are still having issues after completing the above steps

**Comment by benschenker** [comment] 2015-08-23 04:29
I am still seeing the issue, but it may have not been pushed to production yet.  The fix has been merged though :smile:

**Comment by BerkeleyTrue** [comment] 2015-08-23 04:43
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-23 04:43 UTC

**Comment by abustamam** [comment] 2015-08-23 16:17
Thanks for the clarification, and sorry for the dup!
