### ISSUE TITLE
Line not editable in 'Sift through Text with Regular Expressions'

### ISSUE THREAD

**Issue by marauderlabs** [FreeCodeCamp/FreeCodeCamp#8026] opened 2016-04-10 09:28 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/sift-through-text-with-regular-expressions

#### Issue Description

Unable to edit the code at line that says //Change this Line
Clicking by mouse or using arrow keys on keyboard don't work, unless you go and edit some other line
and return to the line.
Issue is seen in Firefox and Chrome on mac and not on safari.

#### Browser Information
* Browser Name, Version: Google Chrome, 49.0.2623.110 (64-bit), Mozilla Firefox 44.0.2.
* Operating System: Mac OS X 10.11.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
No user code required.
```

#### Screenshot
I've uploaded a video of the issue to understand it more, as an image won't suffice here.
https://youtu.be/2ScYLKg3xpU

**Comment by erictleung** [comment] 2016-04-10 16:28
Closing as duplicate of #7847. Happy coding!

**Closed by erictleung** 2016-04-10 16:28 UTC

**Comment by Charnarongthumwan** [comment] 2016-10-06 10:04
Thank you.
