### ISSUE TITLE
Program Execution Error in exercise

### ISSUE THREAD

**Issue by razetime** [FreeCodeCamp/FreeCodeCamp#3929] opened 2015-10-27 08:38 UTC
Challenge [Waypoint: Manipulate Arrays With unshift](http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2546.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
// ourArray now equals ["J", ["cat"]]
ourArray.unshift("happy");
// ourArray now equals ["happy", "J", ["cat"]]

var myArray = ["John", 23, ["dog", 3]];
myArray.shift();

// Add "Paul" to the start of myArray.
// Only change code below this line.
myArray.unshift("Paul")

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(y, z){return 'myArray = ' + JSON.stringify(y);})(myArray);

```
my code is all fine, but the website says Program Execution Error.
Any Help?
![untitled](https://cloud.githubusercontent.com/assets/11015319/10752989/c46f251c-7cb3-11e5-8cac-9689a788c9fd.png)

**Comment by ltegman** [comment] 2015-10-27 16:59
This is caused by the missing semicolon at the end of the line. The FCC code editor is very picky about semicolons in the javascript challenges.

Closing, but please feel free to follow up if you need further clarification.

Thanks and happy coding!

**Closed by ltegman** 2015-10-27 16:59 UTC
