### ISSUE TITLE
Last test case for Javascript Slot Machine does not pass

### ISSUE THREAD

**Issue by Himanshu54** [FreeCodeCamp/FreeCodeCamp#10578] opened 2016-09-09 14:05 UTC
Challenge [create-a-javascript-slot-machine](https://www.freecodecamp.com/en/challenges/basic-javascript/create-a-javascript-slot-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```
   slotOne=Math.floor( Math.random() * ( 3 - 1 + 1)) + 1;
   slotTwo=Math.floor( Math.random() * ( 3 - 1 + 1)) + 1;
   slotThree=Math.floor( Math.random() * ( 3 - 1 + 1)) + 1;
    ```
     
the code should pass but the last assert function return false

**Comment by crossphd** [comment] 2016-09-09 15:19
I'm having the same issue.

**Comment by dhcodes** [comment] 2016-09-09 15:23
I've confirmed this as well. I tested the Regex and it seems to catch the cases. This may have more to do with how the assert test is written. 
@FreeCodeCamp/issue-moderators

**Comment by ltegman** [comment] 2016-09-09 16:35
I'm closing this issue as the real issue is that these challenges are marked as beta and should not be showing up. They were marked this way because there were deemed too broken and counterproductive to be of use in their current state.

I have opened https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10602 to track beta challenges showing up in production.

**Comment by dhcodes** [comment] 2016-09-09 16:39
@ltegman the React update went live overnight.

**Comment by dconner09** [comment] 2016-09-09 16:40
whats the react update

**Closed** 2016-09-09 16:45 UTC
Labels: help wanted, tests

**Comment by dconner09** [comment] 2016-09-09 16:52
hey @BerkeleyTrue  if the slot machine challenge was removed why is it showing up now.

**Comment by BerkeleyTrue** [comment] 2016-09-09 16:59
@dconner09 Yes, that is the issue
