### ISSUE TITLE
News: Comments fail to load

### ISSUE THREAD

**Issue by colbyfayock** [freeCodeCamp/freeCodeCamp#36846] opened 2019-09-26 01:06 UTC
Seems to be an issue with comments trying to load. I'm seeing a 400 on GETs to the comments embed endpoint.
![image](https://user-images.githubusercontent.com/1045274/65650244-04ebc100-dfd8-11e9-8ef2-0a73c21716e6.png)
https://www.freecodecamp.org/news/what-is-gatsby-and-why-its-time-to-get-on-the-hype-train/

I tried poking at a few other pages and seeing the same thing, like https://www.freecodecamp.org/news/how-make-a-windows-10-usb-using-your-mac-build-a-bootable-iso-from-your-macs-terminal/

I'm not sure if this is the right URL, but if it is, it looks like the embed is set up wrong:
```
https://www.freecodecamp.org/forum/embed/comments?embed_url=%7B%7Burl%20absolute%3D%22true%22%7D%7D
```

**Comment by raisedadead** [comment] 2019-09-26 09:07
@colbyfayock thanks a lot for catching this. 

This is a regression that we introduced last night accidentally.
Here is what happened:

1. We implemented a feature that would now let you disable comments on any page that we want.
2. This also a involved a tad bit refactoring, where we broke the templating logic and hence like you found the broken URLs.
3. We have now reverted the feature momentarily on production and are currently fixing the bug on the feature itself.

Sorry about the inconvenience and thanks once again.

**Comment by ahmadabdolsaheb** [comment] 2019-09-27 12:36
This has been resolved after reverting the recent changes.

![image](https://user-images.githubusercontent.com/4591597/65769511-6167f100-e13c-11e9-9af3-7543f289e2c1.png)

**Comment by raisedadead** [comment] 2019-09-27 13:01
We are yet to deploy the feature that @scissorsneedfoodtoo is working on to fix. Re-opening.

**Comment by ahmadabdolsaheb** [comment] 2019-10-02 07:54
@raisedadead I think we can close this since we are no longer using the embed.

**Comment by raisedadead** [comment] 2019-10-02 08:10
> I think we can close this since we are no longer using the embed.

Yup, we do not. 

But there is no communication either about what happened to the comments. This should be left open or a feature issue should be opened with the explanation.

I'll defer to you.

**Comment by colbyfayock** [comment] 2019-10-02 10:17
@raisedadead  Is the intent to no longer show a link for the comments at all? i thought the hope was to show a link with a count instead of the widget

**Comment by ahmadabdolsaheb** [comment] 2019-10-02 10:30
@colbyfayock, a new solution is in the works that will create topics on the forum and display a link and comment count on each post. 

Additionally we are investigating ways we could have optional notifications sent to authors for new comments as well.
#36920

**Comment by birnan** [comment] 2019-10-02 10:38
We implemented a feature that would now let you disable comments on any page that we want.
This also a involved a tad bit refactoring, where we broke the templating logic and hence like you found the broken URLs.

**Comment by colbyfayock** [comment] 2019-10-10 13:22
fwiw, it's kind of a bummer that there's no longer even a link to the comments on the page. is there a reason why there wouldn't simply be a link to the comments while the main solution is being produced? completely removing a feature while the final solution is being developed isn't a great way to develop and maintain features.

for this particular case, this prevents easy access to the comments of a post, particularly for authors, where now I'm struggling to find it in the forums.

**Comment by raisedadead** [comment] 2019-10-14 16:47
The current functionality as it was implemented was fragile and completely broken to the point where we had to remove it. Discourse gives you very little control on what you can do with it out of the box. A custom solution needs dev and time.

As of now as @ahmadabdolsaheb has mentioned the new solution is in works. Unfortunately there is no ETA when it will be out. 

We understand the frustration and request your patience.

**Comment by moT01** [comment] 2020-09-08 18:31
Closing as stale. Feel free to create a new issue regarding comments on articles if desired. But this particular issue is no longer present since comments aren't there. Thanks and happy coding 🎉

**Closed by moT01** 2020-09-08 18:31 UTC
Labels: platform: news, status: fix in progress, type: bug
