### ISSUE TITLE
Close button (x) is not centered vertically in flash message

### ISSUE THREAD

**Issue by timagixe** [freeCodeCamp/freeCodeCamp#49081] opened 2023-01-21 09:44 UTC
### Describe the Issue

Close button (x char) is not aligned vertically in flash message that states `Saved! Your code was saved to your browser's local storage.`

### Affected Page

/learn routes (i.e. https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3)

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3'
2. Click inside of  `Code editor`
3. Save code to local storage (CTRL + S)
4. Flash message appears behind top navigation
5. See close button's vertical alignment is not centered (it is closer to top than to bottom).

### Expected behavior

Close button's vertical alignment should be centered (it should have the same spacing to top and bottom sides of flash message container.

### Screenshots

<img width="250" alt="Screen Shot 2023-01-21 at 11 33 42 AM" src="https://user-images.githubusercontent.com/60817786/213861293-32b267fe-9ba9-48d4-b963-f8ed0bcc4b54.png">

<img width="250" alt="Screen Shot 2023-01-21 at 11 33 53 AM" src="https://user-images.githubusercontent.com/60817786/213861302-8072dbce-b3cc-4c41-b954-6a605e50c6ac.png">

### System

- Device: Laptop
- OS: MacOS
- Browser: Chrome
- Version: v.109

**Comment by SanjeevSingh08** [comment] 2023-01-22 05:47
That is a bootstap property.  top:-2px. 
Can i work on this.
![image](https://user-images.githubusercontent.com/100428475/213902498-4cac700a-3f54-4a66-8b1f-242970e055a3.png)

**Comment by SanjeevSingh08** [comment] 2023-01-22 06:01
and yes there is one more issue-
As u can see the texts in the flash message are not aligned at the center.
![image](https://user-images.githubusercontent.com/100428475/213902800-69651f99-0ef5-4bd4-be43-a5a1dd0aac0b.png)

This one may look better than the previous one
![image](https://user-images.githubusercontent.com/100428475/213902904-427ce5e8-a869-41f4-94f8-7b0dda42f421.png)

**Comment by SanjeevSingh08** [comment] 2023-01-22 06:34
One more thing , the texts in the flash message do not resize as per the screen size.
[previous ui.webm](https://user-images.githubusercontent.com/100428475/213903833-4e86c2d9-f6a0-4e3f-83f4-9aa5a8ea75b0.webm)

I have made some changes , please have a look , This might look better.
[ui change.webm](https://user-images.githubusercontent.com/100428475/213903848-bf3ee61f-49e2-4c4a-99a3-fd3232534207.webm)

**Comment by Sboonny** [comment] 2023-01-22 08:02
duplicate of #48910, thank you for reporting the issue

**Comment by SanjeevSingh08** [comment] 2023-01-22 08:03
@Sboonny i have made a pull request regarding this. Please have a look .

**Closed by Sboonny** 2023-01-22 08:02 UTC
Labels: type: bug, scope: UI, platform: client, status: waiting triage
