### ISSUE TITLE
it worked for the wrong code

### ISSUE THREAD

**Issue by Wrapmeh** [FreeCodeCamp/FreeCodeCamp#3055] opened 2015-09-04 16:05 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Wrapmeh** [comment] 2015-09-04 16:06
![code](https://cloud.githubusercontent.com/assets/14084449/9688469/60a48d0e-52fd-11e5-9378-78b4e2b2a47a.PNG)

**Comment by bugron** [comment] 2015-09-04 16:24
@Wrapmeh thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2111 so I'll close it. You can continue further discussion there.
And, please, provide the description of your issue next time, thanks!.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-04 16:24 UTC
