### ISSUE TITLE
Achivements not saved 

### ISSUE THREAD

**Issue by yogin25** [FreeCodeCamp/freecodecamp#43] opened 2015-01-19 15:16 UTC
Hi,
i was working on firefox and all my achievements was saved when i come back to working on them. then i moved to google Chrome, after logging with the same account, it brings me to the first challenge and all my achievements was lost.

Thanks for the great work you've done

**Comment by QuincyLarson** [comment] 2015-01-19 17:06
Thanks for creating this issue, and for your kind words! I was unable to reproduce this issue on OSX Yosemite using edge Firefox and edge Chrome. Could you tell me specifically which versions of these browsers you're using? 

One possible cause of this is that you signed in with different SSO options (i.e. Twitter, Facebook) and that those accounts weren't linked (you can link them on the account page). Please verify this is not the case. Thanks!

**Comment by QuincyLarson** [comment] 2015-01-22 19:56
I haven't gotten a response and haven't been able to reproduce this, so I'm going to go ahead and close it. If you can reliably reproduce it, please let me know and we can pair on your machine and figure out what could be causing it. Thanks!

**Closed by QuincyLarson** 2015-01-22 19:56 UTC

**Comment by serhiicss** [comment] 2015-01-22 19:58
I am having similar problem. My progress is not lost, but once I login to FCC it takes me to the first challenge instead of current one.

**Comment by yogin25** [comment] 2015-01-31 11:43
Hi,
Sorry to be late to respond.
I noticed the issue was closed, so if the information about what you asked me for already interest you, just contact me and i give you all what you need to know to fix that.

And again, thanks for the great work you've done

**Comment by serhiicss** [comment] 2015-01-31 12:09
It appears the issue has been resolved. Thank you for your time!
