### ISSUE TITLE
Link from challenge page to challenge issues

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#39166] opened 2020-07-02 14:33 UTC
When, as a learner, I notice an issue with a challenge, there's no link for me to follow to start sorting it out. Instead, I have to find my way through freecodecamp.org. This makes me less likely to report the issue.

I'd like a link to the challenge's existing issues, so I can see if the one I've noticed has already been reported, as this is the starting point for reporting an issue.

**Comment by PeterF521** [comment] 2020-07-02 14:48
I don't understand

**Comment by RandellDawson** [comment] 2020-07-02 15:34
@willnwhite It is always best to check with the forum first if you are having trouble with a challenge.  There are many times that users think something is wrong with the challenge tests, when in fact their code is incorrect.  If the members of the forum community determine your code runs fine, then you can always do a search on existing GitHub issues, to see if you find the same problem you are experiencing.

**Comment by raisedadead** [comment] 2020-07-02 17:03
Thanks for your report.

I agree with Randell. 

We get a lot of false positives on GitHub about the curriculum. This is because often users have code that breaks tests and the challenge may not have an issue.

We ask users to follow the read-search-ask method to verify if there is indeed a something broken with a challenge. In our experience this helps us drill down to the specifics of an issue and we have a good turn around time of resoving those.

I am going to close this as this workflow is by design, but please continue to add your thoughts here.

**Closed by raisedadead** 2020-07-02 17:03 UTC
Labels: type: feature request
