### ISSUE TITLE
My solution is right but console shows a mistake 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11379] opened 2016-10-26 11:22 UTC
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0AtestObj%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
testObj[playerNumber];   // Change this Line

```

**Comment by sepiropht** [comment] 2016-10-26 11:42
you should declare a player variable and pass it the result like this 
`var player = testObj[playerNumber]; `

**Comment by dhcodes** [comment] 2016-10-26 14:04
I agree in the sense that the tests require assigning `testObj[playerNumber]` to a variable `player` but don't explicitly say that in the directions. Additionally example one uses a similar approach to the one above.

At the very least, I think we should change:
>Use the playerNumber variable to lookup player 16 in testObj using bracket notation.

to:
>Use the playerNumber variable to lookup player 16 in testObj using bracket notation and then assign it to a new variable, `player`.

**Comment by Bouncey** [comment] 2016-10-26 14:15
Same issue as #11321 

Keeping this issue

**Comment by Bouncey** [comment] 2016-10-26 14:20
The issue is that `testObj[playerNumber]` is displayed in the output window without being assigned to anything, which is counter-intuitive with regards to the other challenges which would normally only display the contents of the specified variable or the output of the challenge function

**Comment by dhcodes** [comment] 2016-10-26 14:22
@Bouncey fwiw, it doesn't display when I run the tests with that code. Nothing displays.

**Comment by Bouncey** [comment] 2016-10-26 14:37
Weird. 

This is from my phone, but I'm pretty sure I saw the same on my desktop chrome
![img_1071](https://cloud.githubusercontent.com/assets/18572518/19730429/1fce6d2a-9b92-11e6-8af8-8428ae86eef2.PNG)

**Comment by dhcodes** [comment] 2016-10-26 19:57
Console doesn't seem to output it on staging on my end. Have you checked it on staging @Bouncey ?

**Comment by Dayfiri** [comment] 2016-10-26 21:05
var player = testObj[playerNumber]. That is all in it

**Comment by Bouncey** [comment] 2016-10-26 22:03
WOW that screen shot is big!

@dhcodes you are correct about resolved in staging.

@marienhof you deleted some of the seed code at some point, try pressing the reset button and trying again :+1:

**Closed by Bouncey** 2016-10-26 22:03 UTC
Labels: Discussing, resolved in staging
