### ISSUE TITLE
Waypoint: Add Borders Around your Elements

### ISSUE THREAD

**Issue by salesh** [FreeCodeCamp/FreeCodeCamp#3904] opened 2015-10-25 23:35 UTC
I have border
http://prntscr.com/8vc4j3

**Comment by BerkeleyTrue** [comment] 2015-10-26 00:07
Please explain your issue and the steps to reproduce it.

**Comment by ltegman** [comment] 2015-10-26 05:23
Closing as a duplicate of #3204. You may want to try making sure your browser is at 100% zoom to get this to pass and continue any discussion in that thread.

Thanks and happy coding!

**Closed by ltegman** 2015-10-26 05:23 UTC
Labels: blocked
