### ISSUE TITLE
After i press ctrl+enter(or) run tests with mouse it says something went wrong try again later

### ISSUE THREAD

**Issue by rajendra1903** [freeCodeCamp/freeCodeCamp#15149] opened 2017-06-01 04:09 UTC
Challenge [write-reusable-javascript-with-functions](https://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.2.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

 ourReusableFunction();

// Only change code below this line
function reusableFunction()
{
  console.log("Hi World");
  
}
reusableFunction();

```

after entering this code it accepted and said some thought and it should have taken me to the next assignment but it is saying SOMETHING WENT WRONG PLEASE TRY AGAIN LATER

**Comment by systimotic** [comment] 2017-09-04 10:35
Thanks for reporting this issue! It looks like this has been fixed, so I'm closing this. If you can still reproduce this, please add additional information and we'll reopen this issue.

Happy coding!

**Closed by systimotic** 2017-09-04 10:35 UTC
Labels: beta
