### ISSUE TITLE
Why is this failing?

### ISSUE THREAD

**Issue by oneofmygithub** [FreeCodeCamp/FreeCodeCamp#10609] opened 2016-09-09 17:26 UTC
Challenge [iterate-over-arrays-with-map]
   
    var oldArray = [1,2,3,4,5];
// Only change code below this line.
var newArray = oldArray.map(function(val){
return val+ 3;                            
});

**Comment by dhcodes** [comment] 2016-09-09 17:29
@oneofmygithub I believe this is a duplicate of issue #10548 . Thanks for reporting. Closing as duplicate.

**Closed by dhcodes** 2016-09-09 17:29 UTC

**Comment by oneofmygithub** [comment] 2016-09-09 17:33
yes, thank you. I know it's a duplicate, but I can't find the answer in the duplicate issue.

**Comment by dhcodes** [comment] 2016-09-09 17:35
@oneofmygithub that's because it's a bug in the challenge. It won't work correctly until the issue is fixed. I referenced that issue #10548 so you could follow up there as it is worked on.

**Comment by oneofmygithub** [comment] 2016-09-09 17:36
i see. thanks
