### ISSUE TITLE
It is not working in the beta version

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14818] opened 2017-05-11 04:02 UTC
Challenge [passing-values-to-functions-with-arguments](http://beta.freecodecamp.com/en/challenges/basic-javascript/passing-values-to-functions-with-arguments) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
function functionWithArgs(array1,array2){
  console.log(array1+array2);
}
functionWithArgs(1,2);
functionWithArgs(7,9);


```

**Comment by Margaret2** [comment] 2017-05-11 15:23
Your solution passes for me in Vivaldi. Have you tried refreshing the page?

**Comment by ooade** [comment] 2017-05-11 18:40
Nothing is wrong with this challenge. It says create a function called `functionWithArgs` not `ourFunctionWithArgs`.

**Comment by Margaret2** [comment] 2017-05-11 22:50
@ooade `ourFunctionWithArgs` is the starting example code. There's a comment that says `// Only change code below this line` and the correct solution is below that line

**Comment by ooade** [comment] 2017-05-12 01:41
@Margaret2 Oh, Yeah. But it works, even on Mozilla.

**Comment by lynxlynxlynx** [comment] 2017-08-05 16:07
Can confirm that it still works (also mozilla) & suggest closing.

**Comment by systimotic** [comment] 2017-09-04 12:58
Hi! Thanks for reporting and looking into this issue.

I'm closing this as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/15024. It's about the same problem but has a bit more info.

Happy coding!

**Closed by systimotic** 2017-09-04 12:58 UTC
Labels: beta
