### ISSUE TITLE
Correct code will not move forward

### ISSUE THREAD

**Issue by MrChristopherG** [FreeCodeCamp/FreeCodeCamp#4893] opened 2015-12-02 03:44 UTC
body {
    background-color: #000000;
  }
  
</style>
I am using the correct code but I am not able to get past this way point. I see others had this issue but I have tried what resolved other users issues with this, with no result. How can I get past this?

**Comment by ltegman** [comment] 2015-12-02 03:57
We are aware of this issue and a PR is pending. Closing as a duplicate of #4865.

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 03:57 UTC
