### ISSUE TITLE
Map has missing challenges

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#11547] opened 2016-11-06 10:53 UTC
Desktop view (chrome)

![missingmap](https://cloud.githubusercontent.com/assets/18572518/20036962/43697894-a40f-11e6-8604-9e6f425a00fd.png)

@BerkeleyTrue

**Comment by ashleypt** [comment] 2016-11-07 07:11
does this happen with other languages? is there code to default to english if there isn't a translation for some text?

I'd like to help fix this one if it's suitable for beginners

**Comment by ashleypt** [comment] 2016-11-07 14:30
Issue also occurs with english on staging and does NOT occur on master including with Spanish (might be due to browser cache? can anyone else reproduce the bug with english on staging?): 

![screenshot](https://cloud.githubusercontent.com/assets/14846527/20061133/79e0af8e-a539-11e6-8987-10227f4af2a2.png)

I'd like to work on this issue - any help would be appreciated

**Comment by ashleypt** [comment] 2016-11-07 15:29
Here are some errors I'm getting about the props when I open the map.

```
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isAllCollapsed` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `filter` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `clearFilter` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `updateFilter` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `collapseAll` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `expandAll` prop on `MapHeader`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `title` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `dashedName` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `blocks` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isOpen` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isHidden` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `message` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `toggleThisPanel` prop on `SuperBlock`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `title` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `dashedName` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `time` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isOpen` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isHidden` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `challenges` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `toggleThisPanel` prop on `Block`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `title` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `dashedName` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `block` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isLocked` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isRequired` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isComingSoon` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isCompleted` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isDev` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `isHidden` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `challenge` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `updateCurrentChallenge` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.printWarning @ bundle.js:2631
bundle.js:2631 Warning: You are manually calling a React.PropTypes validation function for the `closeMapDrawer` prop on `Challenge`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

**Comment by ashleypt** [comment] 2016-11-07 15:55
okay the text reappears if I set those to isBeta: false - those four are set to isBeta: true. something is wrong with how beta challenges are rendered.

**Comment by ashleypt** [comment] 2016-11-07 16:05
These two commits from https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10654 are suspect but I'm going to bed. Will figure out why beta challenges are not displaying tomorrow.

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10654/commits/26875725db41bb084d7fdf5ca1bb52b2ad2728a0

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10654/commits/a4f1722c29b7ad68bb959ce7eba5b041ad01a7e3

**Comment by ashleypt** [comment] 2016-11-07 17:10
here is the branch I'm using working on this. I also found a typo in utils.js

https://github.com/ashleypt/FreeCodeCamp/tree/fix/11547

**Comment by ashleypt** [comment] 2016-11-08 00:25
Some of the Challenges being rendered in Challenge.jsx have undefined titles. These are not the only ones but for some reason they are the only ones with blank bullets. Here are the non-blank dashedNames of the challenges with this problem (if !title) console.log dashedName:

For now I am going to solve this problem by returning null if the title is undefined. In the future we need to find out WHY these titles are coming across as undefined

```
create-a-javascript-slot-machine
bundle.js:133062 add-your-javascript-slot-machine-slots
bundle.js:133062 bring-your-javascript-slot-machine-to-life
bundle.js:133062 give-your-javascript-slot-machine-some-stylish-images
bundle.js:133062 slice-and-splice
bundle.js:133062 learn-sass-challenges
bundle.js:133062 learn-react-challenges
bundle.js:133062 learn-d3-challenges
bundle.js:133062 learn-accessibility-challenges
bundle.js:133062 learn-agile-challenges
bundle.js:133062 learn-computer-science-challenges
bundle.js:133062 learn-data-visualization-challenges
bundle.js:133062 learn-embedded-and-internet-of-things-challenges
bundle.js:133062 learn-game-development-challenges
bundle.js:133062 learn-gamification-challenges
bundle.js:133062 learn-machine-learning-challenges
bundle.js:133062 learn-math-for-programmers-challenges
bundle.js:133062 learn-mobile-javascript-development-challenges
bundle.js:133062 learn-devops-challenges
bundle.js:133062 learn-software-engineering-principles-challenges
bundle.js:133062 learn-statistics-challenges
bundle.js:133062 learn-tools-challenges
bundle.js:133062 learn-user-experience-design-challenges
bundle.js:133062 learn-visual-design-challenges
```

**Comment by raisedadead** [comment] 2016-11-08 11:44
@ashleypt apologies for the delay in responding. You may refer to https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11575#issuecomment-259115693

**Comment by raisedadead** [comment] 2016-11-08 19:13
> does this happen with other languages? 

I am guessing yes, and as you have already investigated for english too.

> is there code to default to english if there isn't a translation for some text?

Nope. And there is an open issue that is to be addressed. Refer #11545

**Comment by raisedadead** [comment] 2016-11-08 19:14
@Bouncey would like to guide @ashleypt further? Considering you have worked on the notification message with an open PR?

**Comment by BerkeleyTrue** [comment] 2016-11-08 19:20
I'm unable to replicate.

@raisedadead Are you seeing the same?
![settings___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/20113402/2b6dd59a-a5a5-11e6-9cf3-d8d0e0fc32e3.png)

**Comment by raisedadead** [comment] 2016-11-08 19:38
@BerkeleyTrue Yes, I can reproduce this is the latest `staging` for me:

![image](https://cloud.githubusercontent.com/assets/1884376/20114057/f8deed84-a618-11e6-9487-78beddecb497.png)

**Comment by BerkeleyTrue** [comment] 2016-11-08 19:39
So what is different between our setups?

**Comment by raisedadead** [comment] 2016-11-08 19:57
Strange, IDK to be honest, apart from the fact that I cleared the db completely.

**Comment by Bouncey** [comment] 2016-11-08 23:37
All the `learn-*` challenges are referenced in #9349, and are ok. 

> is there code to default to english if there isn't a translation for some text?

The challenges are all in english, it is only when there is a translation that the challenge changes. See [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/server/utils/map.js#L110).

@ashleypt Thank you for all your work, and I am sorry for my delay in offering help with this

@BerkeleyTrue Do we want the slot machine & slice and splice challenges on the map? If I edit the seed files to set `isBeta` to false, the challenge renders normally. I haven't got my head around [filterComingSoonBetaFromEntities](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/f04225a2b074a8c3e8f88b89d5c8b4e6bd8fd0ca/common/app/routes/challenges/utils.js#L268) yet, but I would guess it is in that area

**Comment by ashleypt** [comment] 2016-11-08 23:37
yeah you need to do this on the staging db to see it.

**Comment by BerkeleyTrue** [comment] 2016-11-08 23:45
> Do we want the slot machine & slice and splice challenges on the map?

@Bouncey in dev all challenges render.

**Comment by ashleypt** [comment] 2016-11-08 23:48
@BerkeleyTrue the bug probably doesn't occur in dev mode. marking those four challenges as isBeta: false also fixes it

**Comment by BerkeleyTrue** [comment] 2016-11-08 23:51
>  the bug probably doesn't occur in dev mode.

What mode are you in?

> marking those four challenges as isBeta: false also fixes it

It is an indication of where the problem may lie but it is does not fix the issue.

**Comment by ashleypt** [comment] 2016-11-08 23:54
@BerkeleyTrue the default one. I don't change it... maybe that is dev mode?

>doesnt fix issue

yeah I know... what could be causing this? I'm not really familiar with redux though ive played a bit with react

**Comment by BerkeleyTrue** [comment] 2016-11-08 23:56
@ashleypt I'm unable to reproduce so I could not investigate

If you are able to reproduce, could you investigate? Until we find the actual cause a PR cannot be submitted.

**Comment by ashleypt** [comment] 2016-11-09 00:02
@BerkeleyTrue sure, might take some time as im unfamiliar with the code base but I'll eventually get to the bottom of these pesky blank bullets and undefined titles :)

@Bouncey any tips or places to start in the code? I think I should watch a video on redux first...

**Comment by Bouncey** [comment] 2016-11-09 00:32
@ashleypt this is not a redux issue, i think this is about how the challenges are filtered, look around [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/f04225a2b074a8c3e8f88b89d5c8b4e6bd8fd0ca/common/app/routes/challenges/utils.js#L268)

If you want to see where that function is used, use the search in this repo to see where it shows up. I'd love to help more but I have to sleep .

Happy coding!

**Comment by BerkeleyTrue** [comment] 2016-11-09 00:48
@QuincyLarson is also unable to reproduce

**Comment by Bouncey** [comment] 2016-11-10 07:39
What are the differences in ENV?

I have recently deleted `node_modules` and `bower_components` and did a fresh install of both.
```sh
browser: chrome@latest
OS: Ubuntu 16.04
node: v6.9.1
npm: v3.10.8
mongod:
  db version v3.2.9
  git version: 22ec9e93b40c85fc7cae7d56e7d6a02fd811088c
```

**Comment by ashleypt** [comment] 2016-11-10 07:42
Yes, I also did fresh runs each time with git clean -fxd.

**Comment by mridulnagpal** [comment] 2016-11-19 18:08
Can I help with this Issue?

**Comment by ashleypt** [comment] 2016-11-20 01:11
yes im a bit overwhelmed right now. feel free to take over

**Comment by mridulnagpal** [comment] 2016-11-20 01:20
@ashleypt Could you please give me a little background of the problem I couldn't make it out from the comments please.

**Comment by ashleypt** [comment] 2016-11-20 01:55
some challenges marked isBeta, plus some not are passed with a blank title
prop in the jsx. they mention a few related functions here but my kb
batteries are out so i can't type much now (using mouse lol)

**Comment by raisedadead** [comment] 2017-01-21 08:45
Closing, can reproduce any longer, thanks @ashleypt and others for your TA on this.

**Closed by raisedadead** 2017-01-21 08:45 UTC
