### ISSUE TITLE
[beta] left-hand preview is not appearing

### ISSUE THREAD

**Issue by kattow88** [freeCodeCamp/freeCodeCamp#14873] opened 2017-05-14 18:33 UTC
#### Challenge Name: All lessons/challenges with a preview window
i.e.: http://beta.freecodecamp.com/en/challenges/jquery/delete-your-jquery-functions
http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property

#### Issue Description
HTML content is not appearing in the left-hand preview windows in beta. I tried clearing my cache and tested the issue in Safari, Chrome, and Firefox (having never previously logged in to FreeCodeCamp on Firefox) with identical results.

#### Browser Information

* Browser Name, Version: Safari 10.1, Chrome 58.0.3029.96, Firefox 53.0.2
* Operating System: OX 10.12.4
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![screen shot 2017-05-14 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/24527068/26036749/4e2b64b6-38a9-11e7-9fe5-805c7c9046c5.png)
![screen shot 2017-05-14 at 1 07 53 pm](https://cloud.githubusercontent.com/assets/24527068/26036751/4f7902c4-38a9-11e7-89ce-f0512131b63e.png)

**Comment by raisedadead** [comment] 2017-05-14 18:47
Duplicate of #12923

**Closed by raisedadead** 2017-05-14 18:47 UTC
