### ISSUE TITLE
Refactor all error handling in a standardized format

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#50424] opened 2023-05-18 15:08 UTC
We want to refactor all error handling in a standardized format, like so:

```js
{
  code: "FCC_ERR_USERNAME_VALIDATION",
  error: 'Bad Request',
  message: 'username must NOT have fewer than 3 characters',
  statusCode: 400
}
```

Here:

- `statusCode`: is an HTTP error code.
- `message`: is a descriptive error message or description for the developer for debugging purposes.
- `error`: is a category or of the error. Useful when filtering logs in monitoring tools.
- `code`: is a code that the client or the API consumer can use. 

To elaborate a bit more, the client can implement a look-up table and render a proper (even i18n-style) message to the end user using the `code`. 

For example, the client could render a message for the example `FCC_ERR_USERNAME_VALIDATION` above:  

> "Looks like you used a very short username, we require usernames that are at least 3 characters long"

and so on.

**Comment by Riya267** [comment] 2023-05-26 07:07
Hey there! I'm excited to dive into this project, and I just wanted to confirm if this amazing feature hasn't been developed yet. Can I jump in and start making valuable contributions to bring this feature to life?

**Comment by Riya267** [comment] 2023-08-18 15:37
@raisedadead  Is this up for grabs?

**Comment by ojeytonwilliams** [comment] 2024-06-10 15:45
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/50184 (which has more discussion)

**Closed by ojeytonwilliams** 2024-06-10 15:45 UTC
Labels: type: feature request
