### ISSUE TITLE
Waypoint telling campers to do the wrong thing

### ISSUE THREAD

**Issue by AlexWulkan** [FreeCodeCamp/FreeCodeCamp#2215] opened 2015-08-19 17:41 UTC
In the "Waypoint: Iterate with JavaScript While Loops" you're told to use a for loop.

This is what the text says:
"Let's try getting a for loop to work by pushing values to an array."

It should be:
"Let's try getting a while loop to work by pushing values to an array."

**Comment by michael-krebs** [comment] 2015-08-19 19:02
duplicate of #1802

**Closed** 2015-08-19 20:59 UTC
