### ISSUE TITLE
ES6: an Export Fallback with export default

### ISSUE THREAD

**Issue by Cunning0fDesires** [freeCodeCamp/freeCodeCamp#36346] opened 2019-06-29 11:54 UTC
**Describe your problem and how to reproduce it:**

My initial solution was the following:

export default function subtract(x,y) {
return x - y;
}

It didn't accept it.

But as I wrote it in one line, it worked:

export default function subtract(x,y) {return x - y;}

But the challenge itself says to write it as in my initial code. It should work

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-an-export-fallback-with-export-default

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  75.0.3770.100 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, e
![Screenshot_2](https://user-images.githubusercontent.com/51486985/60383828-11b35400-9a7f-11e9-8855-9798dc3c6c99.png)

tc. in this box):**

**Comment by RandellDawson** [comment] 2019-06-29 12:04
You do not have the correct solution.  It is not a bug in the challenge tests.  I suggest creating a topic on the forum so someone can help guide you to a solution.

Closing this issue, since it is a problem with your code vs. a bug.

Thank you

**Closed by RandellDawson** 2019-06-29 12:04 UTC

**Comment by Cunning0fDesires** [comment] 2019-06-29 12:07
I already solved it. The code itself is the same, the difference is how it's written - in one line or two. I changed the screenshot - check again. I don't need any guidance
