### ISSUE TITLE
waypoint-use-spans-for-inline-elements: does not recognise span - returns errors

### ISSUE THREAD

**Issue by JamesdashTaylor** [FreeCodeCamp/FreeCodeCamp#2689] opened 2015-08-25 21:11 UTC
Challenge http://freecodecamp.com/challenges/waypoint-use-spans-for-inline-elements has an issue. 

Errors produced per screenshot:

Your span element should be inside your p element.
Your span element should have the text love.
Your span element should have class text-danger.
Make sure your span element has a closing tag.

<img width="1492" alt="waypoint-use-spans-for-inline-elements-issue" src="https://cloud.githubusercontent.com/assets/10012353/9479641/16533e5a-4b76-11e5-859a-7e7d3d2c577c.png">

**Comment by kettultim** [comment] 2015-09-06 21:39
@JamesdashTaylor I'm not able to reproduce this (see screenshot) - can you try again if you're still experiencing this issue and if not, can you flag for closing please?
<img width="891" alt="screenshot at sep 06 10 38 09 p m" src="https://cloud.githubusercontent.com/assets/1346441/9706761/1a983346-54e8-11e5-995b-dfd89a979c1b.png">

**Closed** 2015-09-18 05:51 UTC
