### ISSUE TITLE
Text Edit Happens on Line Below

### ISSUE THREAD

**Issue by RobbWaddington** [freeCodeCamp/freeCodeCamp#14219] opened 2017-04-02 23:42 UTC
#### Issue Description

Anytime I attempt to edit text it starts on the line below where I have selected. This can be adding a space, letter, number. Any editing of any kind including backspaces happen on the next line as well.
 It only happens once and happens on any new/reloaded page. Occurs in both night mode and day mode. 

#### Browser Information

* Browser Name, Version: Chrome Version 57.0.2987.98 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![editingissuebefore](https://cloud.githubusercontent.com/assets/12226281/24592012/7c1aaa32-17dc-11e7-8df6-c026146fce87.png)

![editingissueafter](https://cloud.githubusercontent.com/assets/12226281/24592015/85beef62-17dc-11e7-836b-ad42cb808fc5.png)

**Comment by erictleung** [comment] 2017-04-03 03:00
@RobbWaddington sounds like a duplicate of this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. Please take a look at the thread there to see some ways around this odd bug. This has been fixed in the development version of freeCodeCamp. Closing this issue as a duplicate but if you think it is different than your issue, please comment back and we can try to help. Happy coding!

**Closed by erictleung** 2017-04-03 03:00 UTC
Labels: resolved in staging
