### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by denalove** [FreeCodeCamp/FreeCodeCamp#2998] opened 2015-09-02 18:11 UTC
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. 
The error is in the assert function. It says `toLowerCase()` is not a function

**Comment by bugron** [comment] 2015-09-02 18:24
@denalove thanks for posting this issue!
Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2644. Also there is a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2294, but unfortunately it has merge conflicts.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-02 18:24 UTC
