### ISSUE TITLE
Signing in and out repeatedly on the same page breaks flash message

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#51320] opened 2023-08-17 19:07 UTC
### Describe the Issue

If you sign in and out repeatedly on the same page, the flash message shows `flash.signin-success?messages=success[0]=flash.signin-success` instead of proper message string.

This issue happens on certain pages.

- As far as I have checked, it happens on:
    - https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1
    -  https://www.freecodecamp.org/settings
- Doesn't happen on:
    - https://www.freecodecamp.org/learn/
    - https://www.freecodecamp.org/learn/2022/responsive-web-design/

### Affected Page

Confirmed on https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1 and https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1 without signed in (or sign out there)
2. Sign in, check that the flash message is displayed properly.
3. Sign out
4. Sign in again,  check that the flash message is **not** displayed properly.

### Expected behavior

The message `Success! You have signed in to your account. Happy Coding!` or its translation is displayed properly

### Screenshots

Practice project
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/89fe9a14-6529-49e6-9369-f1b4bb3db918)

Settings
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/fe5420c9-8fec-4127-b4f2-c388c71e9f09)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 116.0.5845.96 (Official Build) (64-bit)

### Additional context

It seems to be caused by the corrupted query string in the URL.

**Comment by RockyPukar1** [comment] 2023-08-19 11:08
In the remote website the problem is persisting. But the local copy of this repository, when you signin or singout it redirects you to the learn page. So this has been a difficulty to find exactly from where this issue is getting emitted.

**Comment by raisedadead** [comment] 2023-08-20 05:50
Thanks for reporting, this is a `wontfix` until we refactor the client app to move away from the current API-redirection-based flow. Some of it will be eliminated in the new API's post-mvp iterations. I belive.

**Closed** 2024-02-21 10:11 UTC
Labels: type: bug
