### ISSUE TITLE
All results are up by plus two

### ISSUE THREAD

**Issue by rasheinstein** [FreeCodeCamp/FreeCodeCamp#1170] opened 2015-07-01 08:02 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-no-repeats-please has an issue. 
```
var k = 0;
function permAlone(str) {
   perm("",str);
   return k;
}
function perm(pre, str){
  if (str.length === 0){
    var x=true;
    for (var i = 0; i < pre.length-1; i++){
      if (pre.split("")[i] == pre.split("")[i+1]) x = false;
    }
    if (x === true) k += 1;
  }
  else{
    for (var i = 0; i < str.length; i++){
      perm(pre + str.charAt(i) , str.substring(0,i)+str.substring(i+1));
    }
  }
}
permAlone('aab');```
If I run the code outside fcc, I get the required results but in the challenges it moves all my results up by +2

**Comment by marhyorh** [comment] 2015-07-28 15:01
I went through the code and tested it, worked well on console but the only insignificant issue there is the use of the same variable in the "for loop", i'm also experiencing the same issue .. Remove the "permAlone('aab');" and continue ...

**Comment by benschenker** [comment] 2015-08-26 06:34
Hey @rasheinstein thanks for posting!

It looks like this is a duplicate of #1113.  If you are still having issues, look there for updates on this.

**Closed by benschenker** 2015-08-26 06:34 UTC
