### ISSUE TITLE
Incorrect Count of projects completed

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/freeCodeCamp#17334] opened 2018-05-31 14:39 UTC
#### Describe your problem and - if possible - how to reproduce it
on https://www.freecodecamp.org/ the count of completed projects is incorrect.

![image](https://user-images.githubusercontent.com/26827682/40788521-31b22d58-64e8-11e8-9f77-4fc729224878.png)
I have done 5 responsive web design and 5 JS projects (+ 3 js challenges)

JS projects not being counted I believe.

Due to:
in component-passport.js challenge type 5 not counted
``` javascript
          if ('completedChallenges' in user) {
            completedChallengeCount = user.completedChallenges.length;
            user.completedChallenges.forEach(item => {
              if (
                'challengeType' in item &&
                (item.challengeType === 3 || item.challengeType === 4)
              ) {
                completedProjectCount++;
              }
            });
```
#### Add a Link to the page with the problem
https://www.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Firefox 
* Browser Version: 60.0.1
* Operating System: Win 7

**Comment by raisedadead** [comment] 2019-04-04 09:01
This needs to be retested and confirmed once again one beta site. Hey @moT01 I think you could test this locally with your dataset?

**Comment by moT01** [comment] 2019-04-04 12:35
Still seeing it locally...
<img width="1025" alt="Screen Shot 2019-04-04 at 7 32 57 AM" src="https://user-images.githubusercontent.com/20648924/55555916-f0bfaa80-56ab-11e9-91c6-1592c84126e7.png">

Looks like there's something wrong with the legacy cert count as well, I either have 3 of 3 or 4 of 4.

**Comment by moT01** [comment] 2019-09-05 17:06
This information was removed with the recent redesign of the welcome page. So we can close this.

**Closed by moT01** 2019-09-05 17:06 UTC
Labels: help wanted, status: needs investigation
