### ISSUE TITLE
localhost:3000 redirects

### ISSUE THREAD

**Issue by sadikn** [freeCodeCamp/freeCodeCamp#36362] opened 2019-07-01 09:08 UTC
When I try to navigate to localhost:3000 in my "production current" branch from git it redirects me to "http://localhost:8000/404?messages=danger%5B0%5D%3DWe%2520couldn%2527t%2520find%2520path%2520%252F". Why is this happening and am I missing something?

**Comment by moT01** [comment] 2019-07-01 20:18
What is supposed to happen? `localhost:8000` should be your local development address - right?

**Comment by arantebw** [comment] 2019-07-02 07:23
> When I try to navigate to localhost:3000 in my "production current" branch from git it redirects me to "http://localhost:8000/404?messages=danger%5B0%5D%3DWe%2520couldn%2527t%2520find%2520path%2520%252F". Why is this happening and am I missing something?

I did encounter this as well when I was trying to pull-up the API Server which is ```localhost:3000/explorer```. Is this an expected behavior?

**Comment by ojeytonwilliams** [comment] 2019-07-03 13:12
Going to `localhost:3000/explorer` should pull up the LoopBack API explorer which looks like this:
![LoopBack](https://user-images.githubusercontent.com/15801806/60594232-c792e100-9da4-11e9-8d61-595af3c66d7c.png)

Generally speaking just navigating to a server url (i.e. port 3000) doesn't work, because you need to provide a token demonstrating that you're authenticated.

**Comment by raisedadead** [comment] 2019-07-17 15:21
I am closing this, for now for lack of information about the issue in the OP, will re-open if this is found to be a legitimate bug.

We can continue to discuss in the thread or over our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) and [Contributors category on the Forum](https://www.freecodecamp.org/forum/c/contributors) if this is just some general query about freeCodeCamp's codebase.

**Closed by raisedadead** 2019-07-17 15:21 UTC
