### ISSUE TITLE
challenge can't be resolved although code is working

### ISSUE THREAD

**Issue by tyrolCoder** [FreeCodeCamp/FreeCodeCamp#10575] opened 2016-09-09 13:34 UTC
Challenge [iterate-over-arrays-with-map](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi!
I did the coding as requested by using the .map notation; the result of the code looks good and the checkmarks show its passing the related tests;
The issue is, that the last check is not passed saying "You should only modify the array with map." although the code uses the .map notation;

May I ask you to have a look at the challenge - I've checked the forums and it seems there are currently more people with the same issue around without any solution...

Kind regards,
Toni

```js
    
    
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(test){
 test+=3;
return test;
});

console.log(newArray);

    ```

**Comment by atjonathan** [comment] 2016-09-09 15:36
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10548

**Closed** 2016-09-09 15:35 UTC

**Comment by mattattaq** [comment] 2016-09-09 23:33
I'm having the same issue:
```

var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray;

var plusThree = newArray.map(function(val){
  return val + 3;
});
console.log(oldArray);
console.log(plusThree);
```
