### ISSUE TITLE
Beta Challenge : Copy Array items using Slice (minified "react" error)

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15185] opened 2017-06-03 08:54 UTC
Challenge [copy-array-items-using-slice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/copy-array-items-using-slice) has an issue.

If I simply return the array by slicing it, like this - 

```js


function forecast(arr) {
  // change code below this line
  return arr.slice(2,4);
}

// do not change code below this line
console.log(forecast(['cold', 'rainy', 'warm', 'sunny', 'cool', 'thunderstorms']));

```

it returns a minified react error .
![image](https://cloud.githubusercontent.com/assets/29104610/26752211/2efaede0-4868-11e7-9d2f-4b84a27ddac2.png)

The function returns the same value, as expected when I copy paste into the console.

**Comment by IshtmeetSinghRissam** [comment] 2017-06-03 09:03
It was fixed after restarting browser, but should still be fixed.

**Comment by systimotic** [comment] 2017-09-03 20:44
## First-timers only
Check out [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

The issue is in the following line:
https://github.com/freeCodeCamp/freeCodeCamp/blob/885c73abac6bdc492f5fe913dd793332dbbb5dc3/seed/math-challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L254
The last `<code>` element in the message is never closed. It should be closed with `</code>` at the end of the message, right after the closing square bracket (`]`)

If you need help, please visit our [contributors chatroom](https://gitter.im/freeCodeCamp/Contributors). We're always happy to answer any questions!

Happy coding!

**Comment by zk433** [comment] 2017-09-03 21:05
I'll give it a go, Tim!

**Closed** 2017-09-04 10:03 UTC
Labels: beta, bug, first-timers-only, help wanted
