### ISSUE TITLE
[HACKTOBERFEST 2024] - Attribute Selectors Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56190] opened 2024-09-21 00:41 UTC
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Attribute Selectors quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-attribute-selectors`.

**All quiz questions need to relate to one of these topics:**

- what is an attribute selector
- targeting links by href and title
- targeting elements by lang or data-lang
- targeting lists by type

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment] 2024-09-21 00:41
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment] 2024-10-01 19:40
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by kalvakeerthi** [comment] 2024-10-01 19:43
Please assign this issue to me. I want to solve this issue

**Comment by jdwilkin4** [comment] 2024-10-01 19:47
Hi @kalvakeerthi ! 

I have already assigned you to this issue 
https://github.com/freeCodeCamp/freeCodeCamp/issues/56189

Let's keep this open for others who want to contribute 👍

**Comment by kalvakeerthi** [comment] 2024-10-01 19:48
I would like to work on this issue. Can you please assign this to me?

**Comment by kalvakeerthi** [comment] 2024-10-01 19:53
I would also like to work on this issue. Can you please assign this to me?

**Comment by jdwilkin4** [comment] 2024-10-01 20:06
Contributors can only be assigned to one issue for hacktoberfest

**Comment by devshah207** [comment] 2024-10-01 20:43
Hi @naomi-lgbt  @gikf  can you please assign me this issue??

**Comment by gikf** [comment] 2024-10-01 20:44
Hey @devshah207,

you are already assigned to different issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/56219.

**Comment by doosabhulaxmi** [comment] 2024-10-01 21:00
@naomi-lgbt hi i want to solve this issue please assign

**Comment by gikf** [comment] 2024-10-01 21:01
Hey @doosabhulaxmi,

you are already assigned to different issue. You cannot be assigned to multiple issues. Please stop requesting assignment.

**Comment by suryaanshah** [comment] 2024-10-02 00:49
Hello! I would like to work in this issue

**Comment by naomi-lgbt** [comment] 2024-10-02 01:35
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by a2937** [comment] 2024-10-08 22:22
### It has been seven days. The issue is now being unassigned.

**Comment by suryaanshah** [comment] 2024-10-09 01:12
Hello, sorry for taking some extra time. But I will submit the PR today itself. Can I get just one extra day?
Sorry for bothering! 
Thank you

**Comment by tg-100** [comment] 2024-10-09 02:40
Hi! Could you assign this issue to me?

**Comment by naomi-lgbt** [comment] 2024-10-09 03:32
@suryaanshah thanks for letting us know! I've reassigned the issue to you.

**Comment by thepiyush-303** [comment] 2024-10-14 10:36
Hello @naomi-lgbt 
can i work on this?

**Closed** 2024-10-16 17:49 UTC
Labels: hacktoberfest, frontend cert
