### ISSUE TITLE
Applied Visual Design, Challenge 14 broken (Set the font-size for Multiple Heading Elements)

### ISSUE THREAD

**Issue by jasper-schnabel** [freeCodeCamp/freeCodeCamp#41115] opened 2021-02-14 18:52 UTC
The solution is only partially accepted and therefore the challenge cannot be solved.

![issue](https://user-images.githubusercontent.com/67754783/107886100-fcae6180-6efd-11eb-80ea-c8eed5f9f15a.png)

[Link](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements)

* Browser Name: Firefox
* Browser Version: 85.0.2
* Operating System: Archlinux

**Comment by ShaunSHamilton** [comment] 2021-02-14 20:11
Hello there,

As in the other issue opened, the challenge, and code passes for me. I have tested this in both Firefox, and Chrome. So, I assume the issue is potentially with something like a browser extension affecting the tests on the page. In this case, I suggest you disable browser extensions with access to freecodecamp.org.

In general, I recommend you open a topic on the [forum](https://forum.freecodecamp.org/), and only once it is determined to be a bug there, open an issue on this repo. You can use the `Get Help > Ask for Help` button to create an auto-populated post with your current code.

As this is not an issue with this code base, I am going to close this issue.

Thank you

**Closed by ShaunSHamilton** 2021-02-14 20:11 UTC
Labels: scope: learn, status: needs help for triage
