### ISSUE TITLE
Test Case fails on a valid solution

### ISSUE THREAD

**Issue by abhishekgupta92** [freeCodeCamp/freeCodeCamp#14211] opened 2017-04-02 15:12 UTC
Challenge [write-reusable-javascript-with-functions](http://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();
```

Test Case
`"reusableFunction should output "Hi World" to the dev console"`
fails.

**Comment by Dayfiri** [comment] 2017-04-02 21:02
Hi @abhishekgupta92 
I found that challenge will pass if you comment out what was by default in the code.
```
// Example
/* function ourReusableFunction() {
  console.log("Heyya, World");
} */

function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();
//ourReusableFunction();

// Only change code below this line
```
This way the code passed for me.

**Comment by erictleung** [comment] 2017-04-02 23:06
@abhishekgupta92 thanks for the issue. I'm unable to reproduce your issue using both Firefox and Chrome with the code you've provided. And I agree that your code is valid.

**Comment by abhishekgupta92** [comment] 2017-04-03 09:32
@erictleung as @Dayfiri mentioned we need to comment what is written originally for this to work. As a learner, this isn't clear as it is explicitly written to only change the code after the code written by default.

`(// Only change code below this line).`

**Comment by raisedadead** [comment] 2017-04-24 19:32
@abhishekgupta92 I can pass the challenge with the code that you have provided in the opening post of this thread.

Is this still the case for you? Can you please provide any screenshots if this is not working for you?

Let us know in the comments.

**Comment by Krhefley** [comment] 2017-04-25 00:39
I ran into this as well, I got a "logOutput not defined" message. I refreshed the page, hit 'Run Tests' and it passed.
Screenshot of issue:
<img width="1268" alt="logoutput" src="https://cloud.githubusercontent.com/assets/8091753/25364053/ba540068-291c-11e7-97c8-47ef3da57df2.png">

**Comment by raisedadead** [comment] 2017-04-25 06:22
@Krhefley thanks for the update. That's a bit weird, keeping this open for a check.

/cc @BerkeleyTrue is it possible that there is an issue with the test runner, and would surface in certain conditions? I cannot reproduce though.

**Comment by anhtran1906** [comment] 2017-12-09 22:22
I tried to reproduce this issue on both Firefox (57.0.1) and Chrome (62.0.x) and all the tests passed. I even tried to do the previous challenge and moved on to this challenge and all the tests still passed. Is this still an error and should this issue be opened?

**Comment by raisedadead** [comment] 2017-12-10 06:36
Thanks everyone, I am closing this as not reproducible any more. Please log a fresh issue, if you happen to come across this.

**Closed by raisedadead** 2017-12-10 06:36 UTC
Labels: beta
