### ISSUE TITLE
Sass: Store Data with Sass Variables, Lesson code might be incorrect.

### ISSUE THREAD

**Issue by cotolany** [freeCodeCamp/freeCodeCamp#14861] opened 2017-05-13 17:35 UTC
Challenge [store-data-with-sass-variables](http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Steps to reproduce: 
1. Open lesson at "http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables"
2. Observe code near: "  .blog-post   h2 {" 

Expected result: 
Code should have a comma beween two selectors and read as ".blog-post , h2 {"
because of last 2 tests as:
3d. Your .blog-post element should have a color of red.
AND 
4th. Your h2 elements should have a color of red.

Actual result: code reads as ".blog-post  h2{"  that means - apply style only to h2 element wich is inside of .blog-spot class element.

```html


<style>
 
  $text-color: red;  
  
  .header{
    text-align: center;
  }
  
  .blog-post   h2 {
    color: $text-color;
    color: red; /* This is just a workaround to pass lesson untill tests will be corrected. */
  }
 
</style>

```
![image](https://cloud.githubusercontent.com/assets/27549363/26027721/eeddbdc2-3823-11e7-98ff-55d9dcded9d8.png)

**Comment by systimotic** [comment] 2017-09-03 19:18
Hi @cotolany! Thanks for reporting this issue. I'm closing this as a duplicate of #12699. Happy coding!

**Closed by systimotic** 2017-09-03 19:18 UTC
Labels: beta
