### ISSUE TITLE
Pointer is clippy

### ISSUE THREAD

**Issue by garritfra** [freeCodeCamp/freeCodeCamp#15991] opened 2017-10-19 12:28 UTC
#### Challenge Name
[responsively-style-radio-buttons
](https://www.freecodecamp.org/challenges/responsively-style-radio-buttons) (if relevant)

#### Issue Description

I have a problem where the cursor can't "reach" the far right area of the code editor. When I try to navigate to the right, the pointer breaks to the next line. Unfortunately I didn't do anything specific that could reproduce this bug. It just happenes sometimes.

It seems like the actual pointer is on a whole different position than the visual pointer

#### Browser Information

* Browser Name, Version: Google Chrome 61.0.3163.100
* Operating System: Windows 10 Professional
* Mobile, Desktop, or Tablet: Desktop

**Comment by dhcodes** [comment] 2017-10-19 19:53
This is fixed in beta. Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/7847

**Closed by dhcodes** 2017-10-19 19:53 UTC
