### ISSUE TITLE
While redoing HTML5/CSS waypoints, I am still receiving points

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#3043] opened 2015-09-04 01:51 UTC
Challenge http://freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I have finished the HTML5/CSS waypoints (before the updated extra waypoints), however, upon redoing them, I am still receiving points.

**Comment by bugron** [comment] 2015-09-04 03:04
@tesla809 thanks for posting this issue!
Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3009. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-04 03:04 UTC
