### ISSUE TITLE
Typo in Waypoint: Iterate with JavaScript While Loops

### ISSUE THREAD

**Issue by CoderNurse** [FreeCodeCamp/FreeCodeCamp#2107] opened 2015-08-18 18:38 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

At bottom of left instruction column, before green Run Code button, it says "Let's try getting a FOR loop to work by pushing values to an array."

"FOR" should be replaced with "WHILE".

**Comment by michael-krebs** [comment] 2015-08-18 21:15
duplicate of #1802

**Closed** 2015-08-23 04:56 UTC
