### ISSUE TITLE
Clarify phrasing: 'with a dollar sign in front of it' can be misinterpreted

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#56168] opened 2024-09-20 16:42 UTC
### Describe the Issue

In the Step 12 of module: "Learn Basic OOP by Building a Shopping Cart".
The phrase "**with a dollar sign in front of it**" might sound like the dollar sign should come **after** the price value, but it actually means **before** the price.

To avoid this ambiguity, a clearer way to phrase it could be:

"**Precede the price with a dollar sign ($)**."
Or "**Display the price with a dollar sign ($) before the value.**"
This wording explicitly states that the dollar sign should come before the price, avoiding any confusion.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-12

### Your code

-

### Expected behavior

-

### Screenshots

![Screenshot 2024-09-20 173208](https://github.com/user-attachments/assets/4ef00447-de8b-484d-8d04-53cc23c13e9a)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by RockyPukar1** [comment] 2024-09-27 07:54
The phrase

> and the dollar sign `"$"` followed by the value of the `price` variable

would be a good to avoid all these confusion which has been added to the pull request

**Comment by naomi-lgbt** [comment] 2024-10-04 00:39
This issue is open for contribution.

A PR which resolves this issue should:

- Update the instructions to read `` Give the first a `class` of `dessert-price`, and set the text to a dollar sign `"$"` followed by the value of the `price` variable. ``

**Comment by uday7981** [comment] 2024-10-06 18:59
Is this PR Still Open?

**Comment by ilenia-magoni** [comment] 2024-10-06 19:25
@uday7981 the issue is open for contribution, but there are already two PRs that aim to close this issue

**Closed** 2024-10-10 08:33 UTC
Labels: scope: curriculum, status: PR in works, new javascript course
