### ISSUE TITLE
Basic Javascript Waypoint#1 Commenting error.

### ISSUE THREAD

**Issue by RobynUblynd** [FreeCodeCamp/FreeCodeCamp#3164] opened 2015-09-08 16:40 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

If Comment is done in a block format it fails challenge.

![image](https://cloud.githubusercontent.com/assets/10080526/9741077/582261fc-5626-11e5-8fb0-7bd17c95a19a.png)

**Comment by ahstro** [comment] 2015-09-08 17:05
Thank you for reporting; there is a pending PR to fix this: #2185

Closing this as a duplicate of #1999, @RobynUblynd please read [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) so you know how to avoid them in the future.

**Closed by ahstro** 2015-09-08 17:05 UTC
