### ISSUE TITLE
Issue with lesson add font awesome to your profile

### ISSUE THREAD

**Issue by daniil-lyalko** [FreeCodeCamp/FreeCodeCamp#10721] opened 2016-09-13 13:43 UTC
Add Font Awesome Icons to all of our Buttons 

https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons

#### Issue Description

In this challenge as you know the buttons for Like, Info and Delete you add cool icons to the end of the text in each button.  I am wondering why for the trashcan on the delete button it goes off the previewer page and thus you cannot see it.  Makes it look not clean is this a bug or could there be something I am missing about how the .col-xs-4 work?

#### Browser Information

* Browser Name, Version: Chrome 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```html
<div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info<i class="fa fa-info-circle"></i></button>
    </div>
    <div class="col-xs-4"> 
      <button class="btn btn-block btn-danger">Delete<i class="fa fa-trash"></i></button>
    </div>
  </div>

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/20713384/18476038/8e32a1e6-7996-11e6-906f-687945604f78.png)

**Comment by dhcodes** [comment] 2016-09-13 14:28
Thanks for the issue @daniil-lyalko. Closing this as a duplicate of #7842.

**Closed by dhcodes** 2016-09-13 14:28 UTC

**Comment by kingdame** [comment] 2016-10-18 03:58
Thanks alot!!

**Comment by fahadabdullah91** [comment] 2016-10-18 14:21
Thanks bro, it's helped me .
