### ISSUE TITLE
TypeError : undefined is not a function in javascript comment section

### ISSUE THREAD

**Issue by avinashthakur** [FreeCodeCamp/FreeCodeCamp#4901] opened 2015-12-02 05:45 UTC
![screenshot from 2015-12-02 11 12 55](https://cloud.githubusercontent.com/assets/16112503/11523168/ea69445c-98e5-11e5-8094-8e5c31011d44.png)
Challenge [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code?solution=%2F%2FThis%20is%20a%20comment.) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/40.0.2214.94 Chrome/40.0.2214.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//This is a comment.
```

**Comment by ltegman** [comment] 2015-12-02 07:13
Closing as a duplicate of #4873. We have a PR in the works that will fix this.

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 07:13 UTC

**Comment by thethtutoo** [comment] 2015-12-02 12:04
Have you fixed it , sir? I am still seeing that error.

**Comment by bugron** [comment] 2015-12-02 12:36
No, this isn't fixed yet.

**Comment by nvkannan** [comment] 2015-12-02 17:17
Even i am facing the same issue...

**Comment by thethtutoo** [comment] 2015-12-03 08:12
Problem is still there. Is it solved?

**Comment by bugron** [comment] 2015-12-03 08:18
We've merged a PR which fixes this. Try clearing your browser's cache.
