### ISSUE TITLE
Codepen fails to load testable bundle

### ISSUE THREAD

**Issue by PabloPenia** [freeCodeCamp/freeCodeCamp#44925] opened 2022-01-26 18:03 UTC
```
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED
```

Since yesterday, codepen is failing to load the bundle to test our projects. Just checked old projects which I know the bundle was working and get the same result.

On my local machine works fine.

Using latest Brave browser.

**Comment by ShaunSHamilton** [comment] 2022-01-31 12:58
Hello there,

I am unable to reproduce any issue in CodePen on Brave. As such, I am going to close this issue.

If you are still struggling, I suggest you try hard refreshing your page, and/or a different browser.

**Closed by ShaunSHamilton** 2022-01-31 12:58 UTC
Labels: scope: curriculum

**Comment by PabloPenia** [comment] 2022-02-03 16:52
> Hello there,
> 
> I am unable to reproduce any issue in CodePen on Brave. As such, I am going to close this issue.
> 
> If you are still struggling, I suggest you try hard refreshing your page, and/or a different browser.

was a codepen issue, I reported there a week ago,  is working now. sorry I forgot to comment here
