### ISSUE TITLE
Code running twice when loading a new Waypoint, then displays normally when code is edited

### ISSUE THREAD

**Issue by mmmplanetcracker** [FreeCodeCamp/FreeCodeCamp#4312] opened 2015-11-12 00:10 UTC
Challenge [Waypoint: Import a Google Font](http://www.freecodecamp.com/challenges/waypoint-import-a-google-font?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When each Waypoint loads, the current code appears to be running twice.  When I edit the code, it refreshes and displays properly.  This has happened on every Waypoint for me so far (I just started from the very beginning today).

![waypoint import a google font free code camp - mozilla firefox_001](https://cloud.githubusercontent.com/assets/15256929/11106924/dbef7832-888d-11e5-9ee6-d664fe6967b8.png)

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment] 2015-11-12 00:14
Thanks for the report. Currently Chrome is the only browser officially supported by FCC. However, we do have a bug open to track this issue.

Closing as a duplicate of #2706 

Thanks and happy coding!

**Closed by ltegman** 2015-11-12 00:14 UTC
