### ISSUE TITLE
Link n Title for Exercise Is Missing on Map page, Basic Algorithm Scripting section.

### ISSUE THREAD

**Issue by pingspike** [freeCodeCamp/freeCodeCamp#12919] opened 2017-01-27 16:24 UTC
The Link and Title for this Exercise Is Missing on the Map page in the Basic Algorithm Scripting section.  Missing title n link for an exercise on Map page, Basic Algorithm Scripting section.
![image](https://cloud.githubusercontent.com/assets/1571403/22378151/34900a9a-e4e7-11e6-91bc-e13da1374ee8.png)

Issue On URL (Map page, Basic Algorithm Scripting section):  
https://beta.freecodecamp.com/en/map

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by ajain17** [comment] 2017-01-27 19:36
I can confirm this issue on the live site. However, it seems fixed on staging. So can we close this issue?

**Comment by HKuz** [comment] 2017-01-27 19:48
Thanks for the issue, @pingspike - it looks like this has been raised over in #12842 so I'm going to close this as a duplicate. Feel free to make any comments and join the discussion over on that issue. And thanks for the QA help on the Beta site!

@ajain17 - thanks for checking staging! Let me figure out what PR fixed it and I can close the other issue, too.

**Closed by HKuz** 2017-01-27 19:48 UTC
