### ISSUE TITLE
Change Solution URLs

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9123] opened 2016-06-13 18:32 UTC
Some challenge solution links are very long:

```
https://www.freecodecamp.com/challenges/turn-an-image-into-a-link#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20src%3D%22%3Cimg%20class%3D%22smaller-image%20thick-green-bordersrc%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3Ca%2F%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A
```

In #9110, GitHub can't even handle the URL.

I propose we change the URL from the above to:
`https://www.freecodecamp.com/atjonathan/challenges/turn-an-image-into-a-link`

**Comment by erictleung** [comment] 2016-06-13 19:24
I think this would be very convenient 👍  Or at the very least, making a URL shortener would be great alternative. The purpose of that extra long bit is to encode their exact code used in the challenge at the point of creating the issue.

**Comment by BerkeleyTrue** [comment] 2016-06-13 22:08
@atjonathan Can you clarify what the issue is? The example you gave is just removing the query string.

**Comment by atjonathan** [comment] 2016-06-14 07:20
@BerkeleyTrue 
> Some challenge solution links are very long
In #9110, GitHub can't even handle the URL.
> I propose we change the URL from the to:
https://www.freecodecamp.com/atjonathan/challenges/turn-an-image-into-a-link

I thought the issue, was explained in the description.

**Comment by BerkeleyTrue** [comment] 2016-06-14 13:01
Do you mean to cut out the query of the url when an issue is opened using the issue button?

**Comment by robjloranger** [comment] 2016-06-14 14:39
@atjonathan I think what you were missing is that without the long query string, you could not share your solution. The solution is encoded into the string.

**Comment by robjloranger** [comment] 2016-06-14 14:41
@erictleung, @BerkeleyTrue I agree that a URL shortener would be sweet. I have some ideas already, should I start a new issue for a feature request?

**Comment by atjonathan** [comment] 2016-06-14 17:52
@Rafase282 yeh!

**Comment by robjloranger** [comment] 2016-06-15 00:08
@atjonathan Quite a read and seems like no one could agree.
I think the idea of only the users most recent submission being stored for a given ``` freecodecamp.com/robjloranger/{challenge-name} ``` is a good idea. It minimizes storage use and is legible to receivers.
Perhaps a general url shortener could be separate and filter/reject submissions of the urls to code submissions

**Comment by Rafase282** [comment] 2016-06-15 00:35
:8ball:

**Comment by atjonathan** [comment] 2016-06-15 07:19
@robjloranger, yeh i'm thinking a URL shortener.

**Comment by QuincyLarson** [comment] 2017-01-04 05:54
@atjonathan me and @BerkeleyTrue have an idea to create a Redis-like interface similar to what they use on CodePen. This should solve this issue. It's on the roadmap, so I'm going to close this issue.

**Closed by QuincyLarson** 2017-01-04 05:54 UTC
Labels: discussing, feature request
