### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Buzzlightyear90** [FreeCodeCamp/freecodecamp#612] opened 2015-05-27 04:10 UTC
I selected the buttons as checked but the waypoint is not noticing that the buttons are checked.

**Comment by ShaklinSyed** [comment] 2015-05-27 04:20
Duplicate of #607

**Comment by terakilobyte** [comment] 2015-05-27 13:13
Thanks for the report. Closing this duplicate issue.

**Closed** 2015-05-27 13:13 UTC
