### ISSUE TITLE
myVar is undefined no matter what

### ISSUE THREAD

**Issue by pnjoku** [FreeCodeCamp/FreeCodeCamp#5651] opened 2015-12-31 15:04 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%2F%2Fconsole.log(myVar)%3B%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = "Foo";
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
//console.log(myVar);

// now remove the console.log line to pass the test


```

**Comment by duffn** [comment] 2015-12-31 16:23
The test is only checking to see if there is one `console.log` in the code. The thing is the comment also has `console.log` in it, so unless you remove the comment line as well, the test won't pass. 

I'll take fixing this one.

**Comment by pnjoku** [comment] 2015-12-31 17:02
I just removed the commented line and it still errored

**Comment by rugidRon** [comment] 2015-12-31 17:19
Delete all of the comments below myFunction(), including the second console.log(), and the test will pass.

**Comment by ltegman** [comment] 2015-12-31 17:20
@pnjoku In the code you posted there were two commented lines with `console.log` in it. You'll need to remove both. Closing as a duplicate of #5559. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 17:20 UTC

**Comment by sumitbhanu** [comment] 2016-01-01 06:27
I just removed all comments and still code passed even though i purposely wrote wronge code.
please fix these challenge

**Comment by tany007** [comment] 2016-01-02 10:41
put the code like this, it won't give error...

Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20%0A%20%20var%20myVar%20%3B%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  
  var myVar ;
  
  console.log(myVar);
}
myFunction();



```

**Comment by shantilise** [comment] 2016-02-04 18:12
@tany007 -- this solution worked for me as well today **after I refreshed the page**

**Comment by gcaggia** [comment] 2016-03-04 10:34
@shantilise -- Thank you, it was the solution !
