### ISSUE TITLE
Basic JavaScript # 40 (& 39) Suggestion to Avoid Currently Undetected Error

### ISSUE THREAD

**Issue by oyp** [FreeCodeCamp/FreeCodeCamp#2457] opened 2015-08-21 21:04 UTC
Challenge http://freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This challenge will allow you to pass even if your code for which section an image is forgotten. (The correct way to say this is passing me so I'll add some code).

Ex:
```
   $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[0]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[0]).html('<img src = "' + images[slotThree-1] + '">');
```
**Passes and allows you to go to the next challenge.
```
 $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree-1] + '">');
```
** But this is correct.

I understand the [#] isn't the focus here, but I wanted to say something just to avoid developing bad practices. Also I believe the previous Waypoint may have this issue as well.

![image](https://cloud.githubusercontent.com/assets/10967047/9418961/637ef9e6-481d-11e5-8427-e304f5d4c376.png)
![basic javascript 40 error](https://cloud.githubusercontent.com/assets/10967047/9418994/9c8f92f4-481d-11e5-8667-26bd23605223.png)

I sincerely appreciate all of the support FCC. Your application is pure awesome. :+1:

**Comment by benschenker** [comment] 2015-09-03 05:02
Thanks for posting this!

This is a duplicate of #2111 please see that issue for updates on this.

**Closed by benschenker** 2015-09-03 05:02 UTC
