### ISSUE TITLE
Preview editor re-renders incorrectly

### ISSUE THREAD

**Issue by ckrakosky13** [freeCodeCamp/freeCodeCamp#46057] opened 2022-05-18 20:25 UTC
### Describe the Issue

On Firefox, clicking a link inside the preview pane and pressing 'back' on your web browser causes the preview pane to reload with the entire content of the page (html, css, preview pane etc.)
![image](https://user-images.githubusercontent.com/44310729/169149220-5ce95127-f0f5-419d-b7e7-73cc77bdc5ee.png)

On Chrome, this issue is not present, BUT it still re-renders the preview pane incorrectly. Instead of being able to create multiple pages in one preview pane, Chrome renders blank content until the preview pane is closed and re-opened.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-57

### Steps to Reproduce

1. Go to the preview pane.
2. Click on a link (or create one in html first)
3. Press back in your browser.
4. Preview pane now contains the content of the page.
5. Repeat and create more panes.

### Expected behavior

I expected the page to maybe go blank or just go back to the last web page. I did not expect to be able to multiply the content of the page.

### Screenshots

![image](https://user-images.githubusercontent.com/44310729/169149220-5ce95127-f0f5-419d-b7e7-73cc77bdc5ee.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment] 2022-05-18 21:55
It happens on my Firefox too.

**Comment by ShaunSHamilton** [comment] 2022-05-18 22:03
I thought we fixed this, but we just closed the issue, because of lack of resolution: https://github.com/freeCodeCamp/freeCodeCamp/issues/41865

**Comment by Nirajn2311** [comment] 2022-05-21 06:01
One of the causes for this has been fixed ie. clicking on a link in preview and then clicking back button. But there is another way of causing this bug ie. submitting a form and then clicking back button which can be fixed in another PR.

**Comment by naomi-lgbt** [comment] 2022-08-31 14:24
Believe we would need to catch + prevent the default form submit behaviour of refreshing the page.

**Closed** 2022-10-11 22:54 UTC
Labels: type: bug, help wanted, platform: client, hacktoberfest
