### ISSUE TITLE
"SyntaxError: Unexpected token ;" due to having a ; after while (start <length)

### ISSUE THREAD

**Issue by SusanGrattan** [FreeCodeCamp/FreeCodeCamp#5162] opened 2015-12-12 04:08 UTC
Challenge [Bonfire: Chunky Monkey](http://www.freecodecamp.com/challenges/bonfire-chunky-monkey#?solution=function%20chunk(data%2C%20n)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20%20%20var%20result%20%3D%20%5B%5D%2C%20%0A%20%20%20%20%20%20%20%20i%2C%20%0A%20%20%20%20%20%20%20%20start%20%3D%20%200%2C%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20len%20%3D%20data.length%3B%0A%0A%20%20%20%20do%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20result.push(data.slice(start%2C%20start%2Bn))%3B%0A%20%20%20%20%20%20%20%20start%20%2B%3D%20n%3B%0A%0A%20%20%20%20%7D%20while%20(start%3C%20len)%3B%0A%0A%20%20%20%20return%20result%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(data, n) {
  // Break it up.
    var result = [], 
        i, 
        start =  0, 
        
        len = data.length;

    do {
        
        result.push(data.slice(start, start+n));
        start += n;

    } while (start< len);

    return result;
}

chunk(["a", "b", "c", "d"], 2);
```

**Comment by Chris-Cates** [comment] 2015-12-12 04:33
```
function chunk(data, n) {
  // Break it up.
    var result = [], 
        i, 
        start =  0, 

        len = data.length;

    while (start < len) {

        result.push(data.slice(start, start+n));
        start += n;

    }
    return result;
}

chunk(["a", "b", "c", "d"], 2);
```

should solve the issue hopefully?

**Comment by SaintPeter** [comment] 2015-12-12 04:37
Closing as this is not a site issue.

In the future, please try the [Help Chat Room](https://gitter.im/FreeCodeCamp/HelpBonfires) for code support.

**Comment by SusanGrattan** [comment] 2015-12-12 14:48
Sorry, someone in the chatroom who seemed to know a heck of a lot more than I do told me I should report it as it goes against JS syntax. =\ Didn't mean to waste your time.

**Comment by BerkeleyTrue** [comment] 2015-12-12 16:52
@SaintPeter This is proper javascript.

**Comment by SaintPeter** [comment] 2015-12-12 19:07
@BerkeleyTrue Then we're probably looking at an issue with loop protect not adding code properly - it's trying to add it after the while?

**Comment by BerkeleyTrue** [comment] 2015-12-12 19:16
@SaintPeter That might be the case.

**Comment by BerkeleyTrue** [comment] 2015-12-12 19:17
here is the output from loop protect:

```js
;loopProtect.protect({ line: 1, reset: true }); do {;
if (loopProtect.protect({ line: 1 })) break;

        
        result.push(data.slice(start, start+n));
        start += n;

    } ;loopProtect.protect({ line: 6, reset: true }); while (start< len){
if (loopProtect.protect({ line: 6 })) break;
;
}
```

**Comment by BerkeleyTrue** [comment] 2015-12-12 19:35
Looks like the issue exist on JSBin as well http://jsbin.com/dasizaguqu/edit?html,js,console,output

**Comment by ivantedja** [comment] 2016-01-07 16:27
I experienced it just now. From what I see, error occurred when empty spaces found between `do ... while` loop

works fine:
```
var i = 0;
do {
    i++;
} while (i < 3);
```

broken:
```
var i = 0;
do {

    i++;
} while (i < 3);
```

It only happened when the empty line is totally empty. Putting a single space will not trigger this error.

**Comment by SaintPeter** [comment] 2016-01-08 20:47
Have we come up with a way to fix the loop protect for this issue?
@ltegman You were just looking at the loop protect, right?

**Comment by ltegman** [comment] 2016-01-09 03:31
I forgot about this bug while I was digging around the other day, but I'll plan to take a look at this over the weekend :)

**Comment by bugron** [comment] 2016-02-16 16:24
This is still an issue. @ltegman @SaintPeter any updates?

**Comment by clarabee** [comment] 2016-04-14 17:07
This is also an issue on the Fibonacci challenge.

**Comment by augmt** [comment] 2016-06-17 03:00
loop-protect won't work as intended if it encounters an empty line in a do-while loop.

Amending [this code here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/0846d73580eab817706e0f52122cb20d7937f798/public/js/lib/loop-protect/loop-protect.js#L361-L364) to ensure that `line` is not empty while `lineNum < lines.length` may work but I haven't tested it extensively, only with [the code above](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5162#issue-121832025).

**Comment by restartedwill** [comment] 2016-07-13 19:04
This may also be related to the work being done with #9652, at least related to the semicolon issue.

**Closed** 2016-08-12 05:43 UTC
Labels: bug, confirmed, help wanted

**Comment by vincecampanale** [comment] 2016-11-17 03:58
I had the same issue. By removing the semicolon at the end of the while expression, the code ran as intended and passed the test, despite the little red x on the line indicating a lack of a semicolon (since the semicolon is technically correct).
