### ISSUE TITLE
Handle client updates more gracefully

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35259] opened 2019-02-17 11:38 UTC
When we update the client the previous build is no longer available.Therefore, chunk paths are no longer valid and a 404 page is returned were JSON is expected. The effects of which are unpredictable. This failed chunk requests make it all the way through to our monitoring application as an uncaught syntax error.

![Uncaught syntax error report](https://user-images.githubusercontent.com/18572518/52912283-3add0000-32a7-11e9-901e-4b22f8c9a8a2.png)

In the early days of learn.freecodecamp.org we had a serviceworker to handle this type of error, but we found that critical updates were not propagating in the speed required. In the interest of stability/usability, we removed the service worker.

There have been some developments in the plugin `gatsby-plugin-offline` to help with this issue and I would like to explore this again. See [issue comment proposing a fix](https://github.com/gatsbyjs/gatsby/issues/9087#issuecomment-459105021). 

The `onServiceWorkerUpdateReady` hook will allow us to refresh the page automatically, or provide a confirm box to inform the user that a refresh is required. It should also note that declining to refresh may cause instability in their current session. 

I propose we re-enable the offline plugin, with the `onServerWorkerUpdateReady` hook in use and monitor on .rocks for any issues.

cc/ @QuincyLarson @freeCodeCamp/dev-team for input

**Comment by raisedadead** [comment] 2019-02-17 11:52
Just to make sure, how impacted are we without this. Is the behaviour and perf going to be worse than current prod, if we do this after the sprint?

IMHO, we do not want to be doing too anything that we during our beta sprint that is does not have a clear path ahead.

Coming back to the issue: As long as we implement a "break the glass" to override/unregister the service worker, I am all in favor for exploring it. This failsafe should be really robust to invalidate the worker/cache/etc.

**Comment by QuincyLarson** [comment] 2019-02-18 14:06
@Bouncey I am in favor of doing this. 

We should silently update automatically rather than prompting the user. Otherwise people may say "no" and just think freeCodeCamp is broken.

**Comment by raisedadead** [comment] 2019-10-10 09:05
Hi Stuart, 

Revisiting this. 

I have been able to make a updates to cache which holds the chunks for 7 days and even considering to do it more aggressively by caching forever.

Don't ask me how its done, 😓 !

See: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/static/_headers

I believe we are able to introduce the SW back again, and I guess, we could introduce the notification on an update. We do not need the notification to be confirmed and we do not need to reload automatically because the older chunks are still available.

> We should silently update automatically rather than prompting the user. Otherwise people may say "no" and just think freeCodeCamp is broken.

This is not going to matter anymore and rather be counter productive. Automatic updates/reloads will break the state and result in data lose.

Since the chunks are available, it means a polite notification:

```txt
Hey, a new version of the platform is available. You can continue working. Just save your progress and reload the page when ready to get awesome new updates.
```

or something along that lines should be enough.

**Comment by raisedadead** [comment] 2020-09-18 11:40
Closing this, need to create fresh discussion. 

The implementation has changed quite a bit and we need to look at this from a fresh perspective. The need is still present.

**Closed by raisedadead** 2020-09-18 11:40 UTC
Labels: help wanted, platform: client, release: next/beta, status: on the roadmap
