### ISSUE TITLE
Examples in lookahead are unclear.

### ISSUE THREAD

**Issue by themagicbean** [freeCodeCamp/freeCodeCamp#37489] opened 2019-10-23 21:14 UTC
The explanation and examples are not clear.  Better would be:

Explanation, from https://www.stefanjudis.com/today-i-learned/the-complicated-syntax-of-lookaheads-in-javascript-regular-expressions/:

Positive and negative lookaheads:

x(?=y) – positive lookahead (matches 'x' when it's followed by 'y')
x(?!y) – negative lookahead (matches 'x' when it's not followed by 'y')

Updated example to show difference between two for each string:

let quit = "qu";
let noquit = "qt";
let quRegex= /q(?=u)/; // Will generate a result q only if q is followed by u, not otherwsie
let qRegex = /q(?!u)/; // Will generate a result q only if q is NOT followed by u
quit.match(quRegex); // Returns ["q"] because q is followed by u
quit.match(qRegex); // Returns ["null"] because q is followed by u
noquit.match(quRegex); // Returns ["null"] because q is not followed by u
noquit.match(qRegex); // Returns ["q"] because q is not followed by u

Source of page:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead;
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead.english.md

**Comment by raisedadead** [comment] 2019-10-23 22:17
Duplicate of #37481 ? Re-open if unrelated.

**Closed by raisedadead** 2019-10-23 22:17 UTC
Labels: scope: curriculum, status: needs investigation
