### ISSUE TITLE
Navigating to an invalid challenge URL just loads a blank page with a navbar - not a 404 page

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16257] opened 2017-12-22 05:30 UTC
#### Issue Description
When I attempt to visit an invalid challenge URL, I don't get a 404 error - instead I get just a navbar with nothing below it.

For example: http://beta.freecodecamp.org/en/challenges/javascript-algorithms-and-data-structures-projects/i-am-the-black-knight

#### Browser Information
Using Chrome Version 63.0.3239.84 (Official Build) (64-bit) on MacOS

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Screenshot

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34286539-e4d396da-e6a6-11e7-8150-4464211434c6.png)

**Comment by anbe6083** [comment] 2018-02-05 22:38
I get the same issue with Google Chrome: Version 63.0.3239.132 (Official Build) (64-bit). I'd like to take this on.

**Comment by QuincyLarson** [comment] 2018-02-06 05:03
@anbe6083 Sure - do you already have the freeCodeCamp codebase running on your computer?

**Comment by anhtran1906** [comment] 2018-02-08 03:18
@QuincyLarson I already have fCC codebase running on my local machine and have had 2 PR accepted. I am investigating on this problem and looked at some files such as Challenges.jsx, Challenge.jsx and understood these React components. However, I'm not sure where to look at for invalid link access. It would be great if you could point me to the right resource. I have background knowledge in React/Redux

**Comment by anhtran1906** [comment] 2018-02-15 04:41
@raisedadead hi I wonder if you could help me out with this task. I know where the problem is as above but I cannot add a viewType of type "invalid". Thank you so much

**Comment by anhtran1906** [comment] 2018-02-15 05:57
This is the UI/UX page I have right now for invalid URLs:
<img width="1113" alt="screen shot 2018-02-15 at 12 56 12 am" src="https://user-images.githubusercontent.com/20694114/36242658-267500aa-11eb-11e8-82af-b32ea1d79a7a.png">

**Comment by raisedadead** [comment] 2018-02-15 06:24
Ok, seems fine to me, please make a pull request and we can have more feedback there. Thanks for working on this.

**Comment by anhtran1906** [comment] 2018-02-15 18:44
@raisedadead I opened a PR. Please take a look. Thanks!

**Comment by vkWeb** [comment] 2018-02-26 15:53
@QuincyLarson @raisedadead I don't know why I'm not able to reproduce this issue anymore on live beta site but the PR is not yet merged. Navigating to an invalid URL shows me 404 page. Was it fixed earlier?

**Closed** 2018-03-06 18:15 UTC
Labels: beta, help wanted, platform: client
