### ISSUE TITLE
Site is still offline

### ISSUE THREAD

**Issue by gz4053** [FreeCodeCamp/FreeCodeCamp#9141] opened 2016-06-14 21:30 UTC
#### Issue Description

For the past couple of weeks I haven’t been able to access the site. While I can access the offline cloud flare  version of the homepage I receive the message error “522 connection timed out” and “Host Error”; I haven’t been having a problem on other sites. The site works on my phone when it’s disconnected to the home wifi but for some reason the home wifi produces a “host error”. Does anyone know how I could fix this?

This is my 2nd time submitting this problem. 

#### Browser Information

Mac (Safari, Chrome)
Android(Chrome)

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/14838949/16060432/aa36b55e-3255-11e6-87c2-3d9b44b03112.png)

![image](https://cloud.githubusercontent.com/assets/14838949/16060463/d6a7e5ae-3255-11e6-9f69-575b2c91baee.png)

**Comment by BKinahan** [comment] 2016-06-14 21:46
So this is a duplicate of #9020 (closed), which is a duplicate of #8808 (open).

If you have more information about the problem, please leave a comment on the open issue #8808.

**Comment by gz4053** [comment] 2016-06-14 21:50
Thanks

**Comment by erictleung** [comment] 2016-06-14 21:51
Closing to move conversation to #8808.

**Closed by erictleung** 2016-06-14 21:51 UTC
