### ISSUE TITLE
Issue with instructions of challenge: Scientific Computing with Python Projects - Budget App

### ISSUE THREAD

**Issue by MakuraGaeshi** [freeCodeCamp/freeCodeCamp#40073] opened 2020-10-23 23:11 UTC
**Describe your problem and how to reproduce it:**
In the README, the instructions for the check_funds method ask for a method that returns False when the amount-argument is less than the balance and returns True otherwise.

Meanwhile the test expects the method to work the opposite way round, expecting a return of False when the amount is 20 and the balance is 10

**Add a Link to the page with the problem:**
https://repl.it/@MakuraGaeshi/boilerplate-budget-app-5

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 86.0.4240.111
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot 2020-10-24 000720](https://user-images.githubusercontent.com/64079802/97060998-35ac7a00-158d-11eb-8242-cb7c5c41dba6.png)

**Comment by Sky020** [comment] 2020-10-23 23:35
Hello there,

Thank you, for taking the time to report this. We are aware of the issue here:

Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/39351

**Closed by Sky020** 2020-10-23 23:35 UTC
Labels: scope: learn, status: needs help for triage
