### ISSUE TITLE
cannot proceed to next task

### ISSUE THREAD

**Issue by BolajiZ** [freeCodeCamp/freeCodeCamp#12566] opened 2017-01-17 03:35 UTC
#### Challenge Name:using a css class to style an element
https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Browser Information

* Browser Name, Version: mozilla firefox
* Operating System: windows 8
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```html
 <style>
  .red-text{
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by Manish-Giri** [comment] 2017-01-17 05:00
@BolajiZ I cannot reproduce the problem. Your code works for me, in firefox.

**Comment by erictleung** [comment] 2017-01-17 06:07
@BolajiZ I'm also unable to reproduce your issue. I tested it on Firefox but on a Mac. Can you give us more information about your issue? Did you at least get the passing modal to pop up like this?

![image](https://cloud.githubusercontent.com/assets/2754821/22009432/10a0864e-dc38-11e6-9261-43d925faf4d3.png)

**Comment by BolajiZ** [comment] 2017-01-18 04:47
Yes the pop up sign came out but "go to my next challenge" didnt

**Comment by raisedadead** [comment] 2017-01-20 12:04
Try disabling, any add-ons like lastpass, adblockers etc. Or alternatively try in a incognito window with all addons disabled, probably some add-on is conflicting with the page.

Closing. Let us know how it goes.

**Closed by raisedadead** 2017-01-20 12:04 UTC
