### ISSUE TITLE
According to my source, this code is right but ends up being wrong with the system.

### ISSUE THREAD

**Issue by shyamalschandra** [FreeCodeCamp/FreeCodeCamp#8517] opened 2016-05-08 18:54 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20style%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2.red-text {
    color: red;
  }
</style>

<h2 style="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by BKinahan** [comment] 2016-05-08 19:33
I don't know who your source is, but your code is not correct. You haven't followed the requirements "Do not use inline style declarations" or "Your h2 element should have the class red-text". Review your code or seek further assistance in the [help chat room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by JAWL** [comment] 2016-05-08 19:35
Stop

**Comment by ltegman** [comment] 2016-05-08 20:15
Closing as not a bug. Thanks and happy coding!

**Closed by ltegman** 2016-05-08 20:15 UTC

**Comment by Arkadeep-De** [comment] 2016-05-10 04:44
My code:


<style>
  .red-text {
    color: red;
 }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

Facing same problem.

**Comment by cannelflow** [comment] 2016-05-10 04:53
@Arkadeep-De you can ask at https://gitter.im/FreeCodeCamp/FreeCodeCamp
