### ISSUE TITLE
I had the challenge all good but it says no

### ISSUE THREAD

**Issue by A-coder-beep** [freeCodeCamp/freeCodeCamp#39105] opened 2020-06-19 18:17 UTC
**Describe your problem and how to reproduce it:**
I have the challenge all good but nevertheless, he tells me that I did not do the Variable part myStr should contain the string: I am a "double quoted" string inside "double quotes". so I don't know what to do.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings

**Tell us about your browser and operating system:**
* Browser Name: Lenoco
* Browser Version: Chrome 83 windows 10
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/65826720/85167807-b3701a00-b269-11ea-92c8-2e495215d29d.png)
![image](https://user-images.githubusercontent.com/65826720/85167826-bcf98200-b269-11ea-9ecf-49bc34505508.png)

**Comment by nhcarrigan** [comment] 2020-06-19 18:23
Hello~!

It looks like the issue is related to your code, not the tests. As such, I recommend moving to the [FCC forums](https://freecodecamp.org/forum). GitHub issues are for reporting bugs in the FCC code or requesting features, and the forums are intended for getting help with your code not passing the tests. 🙂

**Comment by A-coder-beep** [comment] 2020-06-19 19:11
so i had the challenge false?

**Comment by A-coder-beep** [comment] 2020-06-19 19:12
but when i looked the vidéo i=and the code in the vidéo was the same than my code

**Comment by ojeytonwilliams** [comment] 2020-06-19 20:45
As @nhcarrigan suggested, the forums are the best place to get help. They're also great at determining if there's a problem with the site. If so, then please reopen this issue.

**Closed by ojeytonwilliams** 2020-06-19 20:45 UTC
Labels: scope: learn, status: needs help for triage
