### ISSUE TITLE
i dont know english, but i have screenshots

### ISSUE THREAD

**Issue by numfin** [FreeCodeCamp/FreeCodeCamp#4232] opened 2015-11-07 18:08 UTC
Challenge [Bonfire: Confirm the Ending](http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![2015-11-07_21-05-52](https://cloud.githubusercontent.com/assets/8134947/11016472/99968e3c-8593-11e5-9ece-c6d6054b8214.png)

**Comment by SaintPeter** [comment] 2015-11-07 19:16
Failed to state a problem, Closing.
[Quote Reference](https://www.goodreads.com/quotes/234986-walking-on-water-and-developing-software-from-a-specification-are)

Feel free to re-open if you want to describe what is wrong.

**Comment by ltegman** [comment] 2015-11-07 19:17
The problem is the text being displayed on the highlighted test.

**Comment by BerkeleyTrue** [comment] 2015-11-07 19:26
It could be that test is missing `message: ` part

**Closed** 2015-11-07 19:27 UTC
