### ISSUE TITLE
Beta - Cannot login with existing account using old sign-in method

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#17008] opened 2018-04-03 01:00 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/signin

#### Issue Description

If I enter my email address (or leave the field blank) and I select on 'Try old signin methods' and I select GitHub, I get the error "We could not find a user by the name of "github"" ...

For the fun of it, I tried with my GitHub username. same error

#### Browser Information

* Browser Name, Version: Chrome 65.0.3325.181 (Official Build) (64-bit)
* Operating System:  Windows 10 Pro 64-bit
* Mobile, Desktop, or Tablet:  Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/38223422-cf5f8748-36b8-11e8-96ec-b371e9ac13f0.png)

**Comment by raisedadead** [comment] 2018-04-03 14:34
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/16855

**Closed by raisedadead** 2018-04-03 14:34 UTC
Labels: beta
