### ISSUE TITLE
Unwritten 2 semi colons appearing on the screen. 

### ISSUE THREAD

**Issue by viraj89** [FreeCodeCamp/FreeCodeCamp#6017] opened 2016-01-10 11:52 UTC
I found the 2 semi colons on the screen during the on going html & css and bootstrap series in the front end course. 

I have randomly selected the below 2 waypoint links and the screenshots for the reference:-

1 - http://www.freecodecamp.com/challenges/waypoint-house-our-page-within-a-bootstrap-container-fluid-div

![q1](https://cloud.githubusercontent.com/assets/9387490/12221369/3b477406-b7be-11e5-8f36-a369d53e88d8.jpg)

2- http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements

![q2](https://cloud.githubusercontent.com/assets/9387490/12221370/4a6129b4-b7be-11e5-80d9-d2b4753d3d8b.jpg)

 Wondering about these semi colons. Of course, they aren't any obstacles during the course. Thought it might a confusion for a newbie.

**Comment by bugron** [comment] 2016-01-10 11:54
@viraj89  thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5973 so I'll close this one.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-01-10 11:54 UTC

**Comment by viraj89** [comment] 2016-01-10 11:56
@bugron thanks mate.
