### ISSUE TITLE
Checklist window disappeared, reload and/or exiting page or browser hasn't resolved issue.

### ISSUE THREAD

**Issue by michaelcaetano** [FreeCodeCamp/FreeCodeCamp#3128] opened 2015-09-06 19:42 UTC
Challenge http://freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screen shot 2015-09-06 at 3 39 40 pm](https://cloud.githubusercontent.com/assets/12666833/9706232/c9a89316-54ad-11e5-8aca-90703339e3ca.png)

**Comment by michaelcaetano** [comment] 2015-09-06 19:43
Checklist window under "RESET HELP BUG" has disappeared on me.

**Comment by michaelcaetano** [comment] 2015-09-06 19:58
run test button non-responsive

**Comment by benmcmahon100** [comment] 2015-09-06 20:35
What browser are you in?

**Comment by bugron** [comment] 2015-09-15 15:38
@michaelcaetano thanks for posting this issue!
This issue seems global so I'm closing it as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2904. You can continue further discussion there, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-15 15:38 UTC
Labels: blocked
