### ISSUE TITLE
HTML content rendered twice when new challenge is loaded

### ISSUE THREAD

**Issue by j-hannes** [FreeCodeCamp/FreeCodeCamp#4330] opened 2015-11-12 13:05 UTC
Seems like the HTML is appended twice to the phone viewer when a new challenge is loaded (see screen shot below). As soon as the exercise code is changed it is rendered correctly.

<img width="941" alt="screen shot 2015-11-12 at 13 57 22" src="https://cloud.githubusercontent.com/assets/1204339/11118913/f191e3e2-8945-11e5-8da3-7b91206f06a3.png">

**Comment by ltegman** [comment] 2015-11-12 16:34
Closing as a duplicate of #2706

Next time please try [searching for your issue on github](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github) before filing a new issue.

Thanks and happy coding!

**Closed by ltegman** 2015-11-12 16:34 UTC

**Comment by j-hannes** [comment] 2015-11-12 20:41
@ltegman I did search, but unfortunately with completely different keywords + the issue is on page 5 on the list. Quite surprised such a simple bug is already living that long. Anyway, thanks for the hint. ;)
