### ISSUE TITLE
Error in Quality Assurance Course - suiteSetup Hook

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#54550] opened 2024-04-26 21:41 UTC
### Describe the Issue

There seems to be a small error in the **FreeCodeCamp Quality Assurance** course regarding the usage of the suiteSetup hook. In the lesson about simulating actions using a headless browser ([Course](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/simulate-actions-using-a-headless-browser)), there's a code snippet provided:

```js
suiteSetup(function(done) {
  return browser.visit('/', done);
});
```

However, it appears that there's a mistake in this code. The done function should be called with parentheses, like this:

```js
suiteSetup(function(done) {
  return browser.visit('/', done());
});
```

By adding parentheses after `done` , we ensure that `done` is actually invoked as a function, signaling the completion of the setup. Without the parentheses, `done` is passed as a callback function, which could lead to unexpected behavior.

Update: The solution to this issue has been found in the forum discussion at this link: ([FCC Forum](https://forum.freecodecamp.org/t/simulate-actions-using-a-headless-browser/481003/4)).

Looking forward to hearing your insights!

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/simulate-actions-using-a-headless-browser

### Your code

```js
suiteSetup(function(done) {
  return browser.visit('/', done);
});
```

### Expected behavior

```js
suiteSetup(function(done) {
  return browser.visit('/', done());
});
```

### System

- Device: [PC]
- OS: [Windows11]
- Browser: [Chrome]
- Version: [124.0.6367.78]

**Comment by gikf** [comment] 2024-04-27 08:00
From my understanding the `browser.visit` uses the callback function once visit is completed. In here indicating completion of the setup at that point.

Otherwise, calling `done()` _earlier_ would not mean that setup is completed.

**Comment by ShaunSHamilton** [comment] 2024-04-27 10:07
Hello there,

I cannot reproduce any issue with the lesson. Also, as mentioned, `done` is a callback function that is supposed to be called by `browser.visit` - it should not be called beforehand.

You can see this in Zombie's docs: https://zombie.js.org/

As such, I am going to close this issue for now.

**Closed by ShaunSHamilton** 2024-04-27 10:07 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
