### ISSUE TITLE
the comment below the myFunction call also had to be removed in order to pass the test.

### ISSUE THREAD

**Issue by elifaz25** [FreeCodeCamp/FreeCodeCamp#5603] opened 2015-12-31 01:28 UTC

**Comment by abhisekp** [comment] 2015-12-31 01:35
@elifaz25 Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5559

**Comment by elifaz25** [comment] 2015-12-31 03:14
noted

**Comment by elifaz25** [comment] 2015-12-31 03:16
noted.

**Closed** 2015-12-31 03:16 UTC
