### ISSUE TITLE
Type cursor doesn't follow where clicked within editor

### ISSUE THREAD

**Issue by alternativeintelligence** [FreeCodeCamp/FreeCodeCamp#10003] opened 2016-07-30 20:30 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/call-out-optional-actions-with-button-info
Many challenges before and after.

#### Issue Description

The type cursor doesn't always end up where clicked by the mouse cursor. In some areas of text, you can't click anywhere within it. When it is possible to place the type cursor, it will automatically move to a random area within the text browser once provided with input from the keyboard.

#### Browser Information

* Browser Name, Version: Version 52.0.2743.82 m
* Operating System: Windows 10 Pro x64
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

#### Screenshot

Not applicable.

**Comment by raisedadead** [comment] 2016-07-30 20:35
Please search open issues before reporting, closing as a duplicate of #7847

**Closed by raisedadead** 2016-07-30 20:35 UTC
