### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by ronan696** [FreeCodeCamp/FreeCodeCamp#9328] opened 2016-06-23 18:48 UTC
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D'Here%20is%20a%20backslash%3A%20%5C%5C.%5Cn%20%5Ct%20%5Ct%20Here%20is%20a%20new%20line%20with%20two%20tabs.'%3B%20%2F%2F%20Change%20this%20line%0Aconsole.log(myStr)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I get the required output, as can be seen in the screenshot ---> https://snag.gy/FxkBG0.jpg
But for some reason my code does not get accepted.
My code:
```javascript

var myStr='Here is a backslash: \\.\n \t \t Here is a new line with two tabs.'; // Change this line
console.log(myStr);


```

**Comment by erictleung** [comment] 2016-06-23 19:06
@ronan696 the issue is that the string required has to be very precise. If you look closely, your string doesn't match the one in the box. It has one extra space on the "second" line (look at the `a` and the `H` in `Here`, they don't line up). Closing as duplicate of #9314. Happy coding!

**Closed by erictleung** 2016-06-23 19:06 UTC
