### ISSUE TITLE
Does not assert properly. 

### ISSUE THREAD

**Issue by ladorabl** [FreeCodeCamp/FreeCodeCamp#10536] opened 2016-09-09 08:12 UTC
Challenge [create-a-javascript-slot-machine](https://www.freecodecamp.com/en/challenges/basic-javascript/create-a-javascript-slot-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
     
     
<script>
 function runSlots() {
   var slotOne;
   var slotTwo;
   var slotThree;
  
   var images = ["//i.imgur.com/9H17QFk.png", "//i.imgur.com/9RmpXTy.png", "//i.imgur.com/VJnmtt5.png"];
  
   // Only change code below this line.
   slotOne = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
   slotTwo = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
   slotThree = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
   
   // Only change code above this line.
   
   
   if (slotOne !== undefined && slotTwo !== undefined && slotThree !== undefined) {
     $(".logger").html(slotOne + " " + slotTwo + " " + slotThree);
   }
   
   
   $(".logger").append(" Not A Win")
   return [slotOne, slotTwo, slotThree];
 }

 $(document).ready(function() {
    $(".go").click(function() {
      runSlots();
    });
  });
</script>

<div>
<div class = "container inset">
  <div class = "header inset">
    <img src="https://s3.amazonaws.com/freecodecamp/freecodecamp_logo.svg.gz" alt="learn to code JavaScript at Free Code Camp logo" class="img-responsive nav-logo">
    <h2>FCC Slot Machine</h2>
  </div>
  <div class = "slots inset">
    <div class = "slot inset">
      
    </div>
    <div class = "slot inset">
      
    </div>
    <div class = "slot inset">
      
    </div>
  </div>
  <br/>
  <div class = "outset">
    <button class = "go inset">
      Go
    </button>
  </div>
  <br/>
  <div class = "foot inset">
    <span class = "logger"></span>
  </div>
</div>
</div>

<style>
.container {
  background-color: #4a2b0f;
  height: 400px;
  width: 260px;
  margin: 50px auto;
  border-radius: 4px;
}
.header {
  border: 2px solid #fff;
  border-radius: 4px;
  height: 55px;
  margin: 14px auto;
  background-color: #457f86
}
.header h2 {
  height: 30px;
  margin: auto;
}
.header h2 {
  font-size: 14px;
  margin: 0 0;
  padding: 0;
  color: #fff;
  text-align: center;
}
.slots{
  display: flex;
  background-color: #457f86;
  border-radius: 6px;
  border: 2px solid #fff;
}
.slot{
  flex: 1 0 auto;
  background: white;
  height: 75px;
  margin: 8px;
  border: 2px solid #215f1e;
  border-radius: 4px;
}
.go {
  width: 100%;
  color: #fff;
  background-color: #457f86;
  border: 2px solid #fff;
  border-radius: 2px;
  box-sizing: none;
  outline: none!important;
}
.foot {
  height: 150px;
  background-color: 457f86;
  border: 2px solid #fff;
}

.logger {
  color: white;
  margin: 10px;
}

.outset {
  -webkit-box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
  -moz-box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
    box-shadow: 0px 0px 15px -2px rgba(0,0,0,0.75);
}

.inset {
  -webkit-box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
  -moz-box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
  box-shadow: inset 0px 0px 15px -2px rgba(0,0,0,0.75);
}
</style>

     ```

**Comment by erictleung** [comment] 2016-09-09 08:15
@ladorabl thanks for the issue but can you be more specific on the issue your are experiencing? We've unable to diagnose your problem without more information. Thanks!

**Comment by abhisekp** [comment] 2016-09-09 08:15
The test is broken. `CONFIRMED`

**Comment by abhisekp** [comment] 2016-09-09 08:17
Making a PR :+1:

**Comment by abhisekp** [comment] 2016-09-09 08:46
Duplicate of #10528

**Comment by BerkeleyTrue** [comment] 2016-09-09 16:19
Slot machine challenges are not meant to be in production. They will be removed

Happy Coding

**Closed by BerkeleyTrue** 2016-09-09 16:19 UTC
Labels: QA
