### ISSUE TITLE
YouTube - Make chapters displayed on progress bar

### ISSUE THREAD

**Issue by tavernhell** [freeCodeCamp/freeCodeCamp#39546] opened 2020-09-08 19:03 UTC
Take this video for example https://www.youtube.com/watch?v=RGOj5yH7evk
If in the description you change: ":emoji: (0:00) Introduction"  to "0:00 Introduction" (for all the timestamps of course), chapters would automatically be added ON the progress bar (it's a new YT feature), making it easier for the users to navigate the video.

**Comment by raisedadead** [comment] 2020-09-08 19:37
Can you add more details like OS, Browser, device details, etc. It seems to be fine on my end:

<img src="https://user-images.githubusercontent.com/1884376/92520014-92034680-f238-11ea-84ce-39cbe03012a4.png" width="400" />

**Comment by QuincyLarson** [comment] 2020-09-08 19:46
I can confirm the timestamps work fine on the iOS version of the YouTube app.

In mobile Safari, the timestamps don't work, but they don't work for any videos (including videos with timestamps but no emoji preceding them).

**Comment by nhcarrigan** [comment] 2020-09-08 19:47
![image](https://user-images.githubusercontent.com/63889819/92521084-7b75d480-f1d1-11ea-821f-52ba08d2671e.png)

I am able to confirm them on Chrome for Windows.

**Comment by raisedadead** [comment] 2020-09-09 09:11
Hi @tavernhell 

We are closing this for now, do let us know if you are still seeing the issue. Chances are you need to contact YouTube support if this persists.

**Closed by raisedadead** 2020-09-09 09:11 UTC
Labels: platform: YouTube, type: feature request

**Comment by tavernhell** [comment] 2020-09-09 11:29
> Hi @tavernhell
> 
> We are closing this for now, do let us know if you are still seeing the issue. Chances are you need to contact YouTube support if this persists.

Okay. I'm still not seeing them on Windows 10 using the latest Chrome release (when at work) but at home (with the same Windows and Chrome versions) I can see them. Weird, I'll contact YouTube support to get an answer regarding this. Thanks for the replies!
