### ISSUE TITLE
Annoying constant popup

### ISSUE THREAD

**Issue by p1xtcode** [FreeCodeCamp/FreeCodeCamp#6317] opened 2016-01-19 14:33 UTC
![fcc-print](https://cloud.githubusercontent.com/assets/16669905/12421276/08f54666-be87-11e5-90c0-94eb70be19c8.png)

Anytime I click inside the code editor, a "copy / paste" popup appears, obscuring the code.

How do I get rid of it?

**Comment by ltegman** [comment] 2016-01-19 15:02
Closing as a duplicate of #6290. Thanks and happy coding!

**Closed by ltegman** 2016-01-19 15:02 UTC
