### ISSUE TITLE
Challenge: CSS class style an element -  h2 element not changing to red???

### ISSUE THREAD

**Issue by LeeVulinovic** [FreeCodeCamp/FreeCodeCamp#8338] opened 2016-04-28 21:36 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.1; KFFOWI Build/LMY47O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment] 2016-04-28 23:46
Closing as duplicate of #8278 and #7753.

**Closed by erictleung** 2016-04-28 23:46 UTC
