### ISSUE TITLE
Typo in challenge instructions: wrong hex code.

### ISSUE THREAD

**Issue by amouratoglou** [FreeCodeCamp/FreeCodeCamp#7876] opened 2016-04-04 02:31 UTC
The challenge instructions have a typo:
 The hex code for orange is spelled with a extra 0 en the end:
#FFAA50**0**

The correct spelling is #FFAA50

Copy and paste from the challenge:

> Make the body element's background color orange by giving it the hex code value of #FFA500

Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23FFAA50%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 
![typo1](https://cloud.githubusercontent.com/assets/7943759/14237025/ecaf9cfc-fa15-11e5-80af-410d0078992c.png)
Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: #FFAA50;
  }
</style>

```

**Comment by erictleung** [comment] 2016-04-04 03:44
I don't think there's any error. The hex code `#FFA500` is still orange http://www.color-hex.com/color/ffa500 Closing as not a bug on the site. Happy coding!

**Closed by erictleung** 2016-04-04 03:44 UTC

**Comment by raisedadead** [comment] 2016-04-04 03:46
@amouratoglou @erictleung is correct. Also on a side note I do not see any typo with extra **0**.

**Comment by amouratoglou** [comment] 2016-04-04 11:10
@erictleung  
@raisedadead 
Im might be wrong, but have a look to this:

If you try to complete the challenge with #FFAA500 it wont go accept it, so there is something wrong in the verification of the challenge, something is strange at least. .

**Comment by raisedadead** [comment] 2016-04-04 11:26
@amouratoglou `#FFAA500` isn't correct code that the tests are expecting. Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by JustinRyanBlankenship** [comment] 2016-04-04 11:28
Unsubscribe

On Monday, April 4, 2016, Mrugesh Mohapatra <notifications@github.com>
wrote:

> @amouratoglou <https://github.com/amouratoglou> #FFAA500 isn't correct
> code that the tests are expecting. Please consult the Help Chat Room
> <https://gitter.im/FreeCodeCamp/Help> for any assistance to Coding.
>
> Happy Coding!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7876#issuecomment-205252937>
>


-- 
Regards,
*Justin Blankenship *

**Comment by raisedadead** [comment] 2016-04-04 11:31
@JustinRyanBlankenship 

Hello Justin!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching".

We are sorry for your inconvenience!
