### ISSUE TITLE
You should only be using filter to make the new array wont pass.

### ISSUE THREAD

**Issue by Hydrojaime** [FreeCodeCamp/FreeCodeCamp#10655] opened 2016-09-10 01:44 UTC
Challenge [filter-arrays-with-filter](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    
    
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
return val < 6;
});


    ```

**Comment by dhcodes** [comment] 2016-09-10 02:16
Thanks for the issue! Closing as duplicate of #10589

**Closed by dhcodes** 2016-09-10 02:16 UTC
