### ISSUE TITLE
Progress disappeared from the map after the last update

### ISSUE THREAD

**Issue by Timelady7** [FreeCodeCamp/FreeCodeCamp#3632] opened 2015-10-07 12:22 UTC
Hi,
A lot of the challenges I had already completed are not checked anymore on my map, since today's update (I was working on the Bonfire: Search and Replace).
I originally had completed : 
 -  all the Waypoints up to Object Oriented & Functional Programming (included) (except the Gear up for success, which I think are new),
 - the Basic Algorithm Scripting Bonfires,
 - the Intermediate Algorithm Scripting up to the 16 (included), except for the 15.

The solutions to the missing challenges are not in my portfolio anymore, but I still have all the brownie points I won by completing them.

Quincy told us on Gitter to put up screencap, I'm not sure of what (since it's missing stuffs), so I hope this will do : 
![capture d ecran 2015-10-07 a 14 19 17](https://cloud.githubusercontent.com/assets/13537285/10337213/97eb7302-6cfe-11e5-8124-1cc04a80c09b.png)

**Comment by bugron** [comment] 2015-10-07 12:25
@Timelady7 thanks for posting this issue!
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3629 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3630. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-07 12:25 UTC
