### ISSUE TITLE
Issue with higher order arrow functions challenge

### ISSUE THREAD

**Issue by confusingbits** [freeCodeCamp/freeCodeCamp#35003] opened 2019-01-30 16:37 UTC
**Describe your problem and how to reproduce it:**
The challenge series is about arrow function syntax, this particular challenge is using arrow functions in the context of the higher order built in array functions.

The problem is that filter (or map or reduce) have not been introduced yet, and won't be for some time until the functional javascript section. There is no reason to expect the student to understand how HOCs work and yet this challenge depends on that knowledge.

In this context, the challenge should be about rewriting a regular function to use arrow syntax within a higher order function, completely ignoring how filter works, and definitely not completing the functionality of the function parameter itself.

Or perhaps better suited, moving this particular challenge to the functional section after the functional array methods have been introduced.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment] 2019-01-31 20:05
This appears to be a duplicate of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/14903.  Please refer to the issue and make any additional comments/suggestions there.

Thank you.

**Closed by RandellDawson** 2019-01-31 20:05 UTC
