### ISSUE TITLE
Video Challenges- JavaScript Lingo- Question 3

### ISSUE THREAD

**Issue by jp5486** [FreeCodeCamp/FreeCodeCamp#6889] opened 2016-02-11 12:21 UTC
Video Challenges-
JavaScript Lingo: MDN and Documentation
[Question 3
](http://www.freecodecamp.com/videos/javascript-lingo-mdn-and-documentation)

The title and question for this part only states Question 3 with a passing answer of True. 
Question should be removed or updated.

**Comment by raisedadead** [comment] 2016-02-11 12:32
@jp5486 just fixed this for Issue #6781 via PR #6890 
You can close this.

**Comment by ltegman** [comment] 2016-02-11 17:15
Closing as a duplicate of #6826. Thanks and happy coding!

**Closed by ltegman** 2016-02-11 17:15 UTC
