### ISSUE TITLE
Broken links in forum

### ISSUE THREAD

**Issue by ccervan** [freeCodeCamp/freeCodeCamp#48590] opened 2022-11-25 02:18 UTC
### Describe the Issue

Hello! There are four broken links in the documentation about how to report a bug. 

These are the broken links:
https://www.freecodecamp.org/t/how-to-get-help-on-gitter/19130

https://www.freecodecamp.org/t/searching-for-existing-issues-in-github/18390

https://www.freecodecamp.org/t/refresh-your-browser-cache/19365

https://www.freecodecamp.org/t/removing-all-locally-stored-challenges/19129

### Affected Page

 https://forum.freecodecamp.org/t/how-to-report-a-bug-to-the-freecodecamp-open-source-community/19543

### Steps to Reproduce

Clicking on "Hard refresh", "Ask for help the Chat Rooms", "Clearing your browser's local storage" and "Searching for your issue on Github" will give a 404 error.

### Recommended fix or suggestions

Can they be updated? I saw on "News" (https://www.freecodecamp.org/news/how-to-report-a-bug-to-freecodecamp/)  how to do all the steps mentioned on the forum post but the forum is the first place I go when having issues while learning.

**Comment by Sboonny** [comment] 2022-11-25 06:54
I have edited the links, please check if the issue persists. For context, some of the old link were `.com` which I changed to `.org` and update some mismatch in URL. 

All should be sorted if I have done everything right, so I am closing this. if the issue is still there, please notify us and reopen the issue

**Closed by Sboonny** 2022-11-25 06:54 UTC
Labels: type: bug, status: waiting triage
