### ISSUE TITLE
"Submit and go to next challenge" should take you to the next not done challenge

### ISSUE THREAD

**Issue by jeremies** [freeCodeCamp/freeCodeCamp#37976] opened 2019-12-23 15:30 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes you don't do the challenges in the order proposed by freeCodeCamp but in a random way. Other times new exercises appear and are marked not done in your challenge list. When you do a challenge and click the button "Submit and go to next challenge (Ctrl + Enter)" it takes you to the next challenge (done or not done).

**Describe the solution you'd like**
I think it should take you to the next not done challenge.

**Additional context**
![image](https://user-images.githubusercontent.com/18210819/71365965-d793bc80-25a0-11ea-803b-256996939d05.png)

**Comment by RandellDawson** [comment] 2019-12-23 17:51
This is by design and allows users to work through the curriculum in order again even if they have already passed the challenge in the past.  If you want to skip forwards and backwards faster, you can click the `Esc` key on your keyboard and click `p` for previous and `n` for next.  This way you can easily skip any lesson you do not want to work/rework.

**Comment by moT01** [comment] 2019-12-29 21:50
Yea, I'm not sure I like this either. What if I completed a section and want to do it again? Every time I click submit, it will go to the next section or 20 challenges ahead and I'd have to navigate back somehow. Not a bad idea, but my vote is not to add this.

There is perhaps something to this though, maybe we could add something to those hotkeys for navigating to the next/previous uncompleted challenge.

**Comment by raisedadead** [comment] 2019-12-31 08:02
We do have hot keys and for the minute they are not publicised much. I do not this we would be complicating the navigation by moving to next not done challenge.

**Closed by raisedadead** 2019-12-31 08:02 UTC
Labels: type: feature request
