### ISSUE TITLE
Bonfire:Mutation

### ISSUE THREAD

**Issue by aadeshere** [FreeCodeCamp/FreeCodeCamp#1208] opened 2015-07-06 02:52 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
expect(mutation(['Mary', 'Aarmy'])).to.be.true;

it should return false on correctly running the code.
![screenshot_2015-07-06_08-36-38](https://cloud.githubusercontent.com/assets/4538948/8515005/2372b914-23ba-11e5-8394-9b2b14c42a68.png)

since the length of second string is greater than first string, it should return false on successfully running the code

**Comment by alexlincoln** [comment] 2015-07-06 04:39
Not a bug, the instructions state: `if the string in the first element of the array contains all of the letters of the string in the second element of the array`. Length of the string is irrelevant as long as the characters (letters) are there.

Consider the following solution: 

```javascript
function mutation(arr) {
  if(arr.length < 2) return new Error('Invalid array length');
  
  var first = arr[0].toLowerCase();
  var second = arr[1].toLowerCase();
  
  return second.split('').filter(function(ch) {
      return first.indexOf(ch) > -1;
  }).join('') === second;
}

mutation(['hello', 'hey']);
```

Best of luck

**Comment by pokica-hu** [comment] 2015-08-04 18:28
The length of the second string doesn't matter, the code has to check whether all of its character is included in the first string. Here's my code:
function mutation(arr) {
  found = 0;
  for (i=0;i<arr[1].length;i++) {
    charSearch = arr[1].substr(i,1).toLowerCase();
    xFound = arr[0].toLowerCase().indexOf(charSearch);
    if (xFound > -1) {
      found += 1;
    }
  }
  return (found===arr[1].length);
}

**Comment by benschenker** [comment] 2015-08-26 12:55
Hi @aadeshere, it seems that @pokica-hu, is right.

Closing this issue

**Closed by benschenker** 2015-08-26 12:55 UTC
