### ISSUE TITLE
It doesnt allow me to go next page

### ISSUE THREAD

**Issue by EdisonSim** [FreeCodeCamp/FreeCodeCamp#4246] opened 2015-11-08 16:16 UTC
Challenge [Waypoint: Comment out HTML](http://www.freecodecamp.com/challenges/waypoint-comment-out-html#?solution=%3C!--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3C!--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!--%3E%0A%3Cbr%3E%0A%3C!--%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!-->
<h1>Hello World</h1>
<!-->
<h2>CatPhotoApp</h2>
<!-->
<br>
<!-->
<p>Hello Paragraph</p>
```

**Comment by SaintPeter** [comment] 2015-11-08 17:32
In order to comment out code you need to open your comment with:
`<!--`
and close it with
`-->`

You need to wrap these tags around the elements that you are trying to comment out.

That might look like this:
```html
<!--
<h1>Hello World</h1>
-->
```

If you need further help, try the https://gitter.im/FreeCodeCamp/HelpBonfires chat room.

Closing as this is not a bug in the waypoint.

**Closed by SaintPeter** 2015-11-08 17:32 UTC

**Comment by EdisonSim** [comment] 2015-11-08 23:44
Got it now thanks alot
