### ISSUE TITLE
HTML Project Demos Describe Themselves as Such

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#51152] opened 2023-08-04 18:24 UTC
### Is your feature request related to a problem? Please describe.

Some learners seem to think that they need to replicate the demo projects for the Responsive Web Design certification exactly.

### Describe the solution you'd like

Perhaps we should add some text to the demo projects like

DEMO - YOU SHOULD NOT EXACTLY REPLICATE THIS DEMO PROJECT

or

DEMO - YOU SHOULD MAKE A SIMILAR PROJECT WITH DIFFERENT CONTENT

### Describe alternatives you've considered

N/A

**Comment by raisedadead** [comment] 2023-08-04 20:55
I prefer the simpler language:

DEMO - YOU SHOULD MAKE A SIMILAR PROJECT WITH DIFFERENT CONTENT

**Comment by jeremylt** [comment] 2023-08-05 00:02
Sounds good to me. I think wordsmithing to something simple that communicates the intent is ideal, especially with how multilingual our audience is.

**Comment by jdwilkin4** [comment] 2023-08-05 05:27
yeah, I agree with the change. 
Hopefully that will clear up the misunderstanding on having to replicate the projects

**Comment by Priyakaperla** [comment] 2023-08-05 13:53
I think 
DEMO : YOU SHOULD MAKE A SIMILAR PROJECT WITH DIFFERENT CONTENT

**Comment by Sboonny** [comment] 2023-08-05 14:03
Can we not have all caps, we can make it bold if needed.

**Comment by Priyakaperla** [comment] 2023-08-05 14:31
Yes, we can do that.

**Comment by a2937** [comment] 2023-08-06 17:59
I thought I saw something similar to that warning on those projects.

There's already 

`Fulfill the user stories and pass all the tests below to complete this project. Give it your own personal style. Happy Coding!` 

I'm surprised campers are getting confused by this. I mean it's nice to have extra warnings but what was the original malfunction?

**Comment by jeremylt** [comment] 2023-08-06 18:01
The 'original malfunction' is that people still regularly exactly clone the projects. That makes it harder to tell at a glance between copying and making their own projects.

**Comment by a2937** [comment] 2023-08-06 18:07
Sorry Jeremy. I wanted to know why campers thought it was acceptable to completely clone the projects. I wanted to know if it was them not reading that instruction or if the wording was too ambiguous; and to try to offer my own two cents on a possible solution.

**Comment by jeremylt** [comment] 2023-08-06 18:25
Ah, I misinterpreted 'original malfunction' as 'problem' but I think perhaps you are meaning what I would call 'root cause'?

I think the message isn't clear and direct and obvious enough.

**Comment by a2937** [comment] 2023-08-06 18:27
Yes

**Comment by raisedadead** [comment] 2023-08-07 08:58
Thanks, all. @jeremylt is correct here. The main thing is people don't read.

We should go with this exact notice. Its terse, clear, and specific:

```
DEMO - YOU SHOULD MAKE A SIMILAR PROJECT WITH DIFFERENT CONTENT
```

**Comment by jeremylt** [comment] 2023-08-07 14:06
I mostly used all caps because I forget that **bold** is an option. I'm all for any emphasis technique.

**Comment by moT01** [comment] 2023-08-08 20:31
Just a curiosity @jeremylt (or anyone), are we sure campers are confused and not deliberately cloning the project? I presume you had a forum discussion with someone that was confused, so I should probably just take your word for it - but there may be some that deliberately clone the project because they don't want to come up with something else.

**Comment by naomi-lgbt** [comment] 2023-08-08 20:32
I have seen a lot of campers who think that they need to duplicate the project, not create their own.

**Comment by jeremylt** [comment] 2023-08-08 20:33
Its not super infrequent (and usually with someone who appears to have english as a second language) that I run into a camper that's surprised when I tell them they can make the project about anything they want and it only has to match functional requirements.

**Comment by alexshibu1** [comment] 2023-08-16 15:29
I agree

**Comment by IoanaaCretu** [comment] 2023-09-28 22:32
I can confirm! When I followed the course I had the impression that we should try replicate the demo. I am surprised to find out😲

**Comment by smashed** [comment] 2023-09-30 18:13
My first thought is to always replicate the project. If I can make a suggestion, maybe something that combines both sentences.

Try not to replicate this demo project and create a similar project with your own content.

**Comment by jeremylt** [comment] 2023-09-30 18:16
I'm always an advocate for smaller, simpler sentences whenever possible.

**Comment by namankoolwal** [comment] 2023-10-16 11:51
> Its not super infrequent (and usually with someone who appears to have english as a second language) that I run into a camper that's surprised when I tell them they can make the project about anything they want and it only has to match functional requirements.

I was under the impression that we should try to replicate the demo, but I’m surprised to learn that we shouldn’t.. 
if I can make a suggestion then :-   
No need to copy, Make a similar project, Get Creative!

**Comment by jeremylt** [comment] 2023-10-16 13:48
I think actually want to say 'do not copy' instead of 'sometimes copy'

**Comment by jdwilkin4** [comment] 2024-04-08 01:36
I am going to go ahead and close this since it looks like a PR was merged a while back to resolve the issue.

**Closed by jdwilkin4** 2024-04-08 01:36 UTC
Labels: help wanted, type: feature request
