### ISSUE TITLE
Buggy Create Form Element

### ISSUE THREAD

**Issue by Ninajl** [freeCodeCamp/freeCodeCamp#15007] opened 2017-05-22 23:46 UTC
I believe it is buggy.
Here is my code:
```
<form action="/submit-cat-photo"> 
  <input type="text" placeholder="cat photo URL">
</form>
```
and it is not letting me pass this lesson.
I am assuming this is still an issue?

**Comment by jotisa** [comment] 2017-05-22 23:52
Are you really putting "cat photo URL" or the real url something with http in it?

**Comment by Ninajl** [comment] 2017-05-23 00:10
I am just following instructions from your site:

It states "Nest your text field in a form element. Add the
action="/submit-cat-photo" attribute to this form element."

I looked it up on
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data

and it looks like i could use a relative url.

ex: In this example, the data is sent to an absolute URL — http://foo.com:

<form action="http://foo.com">

Here, we use a relative URL — the data is sent to a different URL on the
server:

<form action="/somewhere_else">



- Nina Lisitsa

**Comment by huyenltnguyen** [comment] 2017-05-23 07:56
Hi @Ninajl! Your code works for me. Have you tried refreshing the page?

**Comment by Ninajl** [comment] 2017-05-23 16:17
Yes, I refreshed the page and used the reset button to trouble shoot the
issue. I have since just moved on to the next lesson using your map
feature. I can try it again today and let you know if it is still buggy.

- Nina Lisitsa

**Comment by jonathanihm** [comment] 2017-05-23 17:52
Hi @Ninajl 

Could you please post some more information on this, such as operating system, browser, and version?  I cannot reproduce this either and your code works for me as well.

**Comment by wendynieuwkamer** [comment] 2017-05-23 18:39
I have the exact same problem. On Chrome and Windows 10.

**Comment by jonathanihm** [comment] 2017-05-23 18:48
-insert Microsoft bashing comment here-

Microsoft is really making life hard for Google Chrome...

Thank you for the additional information!

**Comment by Ninajl** [comment] 2017-05-23 19:55
Hi Jonathan,

I can't explain it. It must have been stuck for some reason, because I went
back to that lesson today using the map feature, rewrote the proper code
and it passes the test.

OS X El Capitan version 10.11.16 Chrome

I appreciate your quick assistance and response!

Nina

- Nina Lisitsa

**Comment by jackbat1436** [comment] 2017-05-25 12:02
same problem here using win 10 and chrome.  I assume it is a chrome issue...

**Comment by texas2010** [comment] 2017-05-25 21:21
thanks for the report, and we confirm that this is a known issue, check #13727 

Closing as a duplicate.

**Closed by texas2010** 2017-05-25 21:21 UTC

**Comment by mehdifracso** [comment] 2017-06-01 21:32
it is chrome that is bloclking the code
