### ISSUE TITLE
Reloading Page Changes Output: Double Coning of #target5 without Reason.

### ISSUE THREAD

**Issue by HuskyNator** [FreeCodeCamp/FreeCodeCamp#7234] opened 2016-02-25 00:25 UTC
Code is Repeated twice leading to a second button.
This happens in "Target the Parent of an Element Using jQuery" (This might not be the only location)

HOW TO REPRODUCE:
1. use this link (only the code is necessary): http://goo.gl/6U2rQC
2. reload the page
(see how #target5 is in #left-well twice?, this shouldn't be the case)

Browser: Chrome & MicrosoftEdge
Windows 10
#### Your Code

```js
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color","blue");
  });
</script>

<!-- Only change code above this line. -->

<body>
  <div class="container-fluid">
    <h3 class="text-primary text-center">jQuery Playground</h3>
    <div class="row">
      <div class="col-xs-6">
        <h4>#left-well</h4>
        <div class="well" id="left-well">
          <button class="btn btn-default target" id="target1">#target1</button>
          <button class="btn btn-default target" id="target2">#target2</button>
          <button class="btn btn-default target" id="target3">#target3</button>
        </div>
      </div>
      <div class="col-xs-6">
        <h4>#right-well</h4>
        <div class="well" id="right-well">
          <button class="btn btn-default target" id="target4">#target4</button>
          <button class="btn btn-default target" id="target5">#target5</button>
          <button class="btn btn-default target" id="target6">#target6</button>
        </div>
      </div>
    </div>
  </div>
</body>

```
Screenshot:
https://www.dropbox.com/s/k53mljbfdyfbyq1/target%205.PNG?dl=0

**Comment by techtolentino** [comment] 2016-02-25 01:56
I'm not sure why this _shouldn't_ be the case, the code is actually telling it to be put there twice.

What is the suggested issue?

**Comment by ltegman** [comment] 2016-02-25 04:41
Closing as a duplicate of #5072. Thanks and happy coding!

**Closed by ltegman** 2016-02-25 04:41 UTC
