### ISSUE TITLE
tells me to remove second console.log after it has been removed

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/FreeCodeCamp#5641] opened 2015-12-31 12:49 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20%22foo%22%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = "foo";
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction

// now remove the console.log line to pass the test


```

**Comment by Mr-Kumar-Abhishek** [comment] 2015-12-31 12:56
:+1: I have stumbled across the same problem, the solution here is to remove all `console.log(myVar)` . Although a much bigger issue here is that it even recognizes commented out `//console.log(myVar); ` too, where ever it might be.

**Comment by Mrngilles** [comment] 2015-12-31 15:46
Same probleme here, removing all `console.log` allowed me to complete the task.
As mentionned, commenting out was also not recognized

**Comment by ChaituVR** [comment] 2015-12-31 17:36
Same problem with me too.. The test has passed when I removed that  commented out console.log.. "
// now remove the consoe.log line to pass the test
"
When I removed this line test has been passed

**Comment by ltegman** [comment] 2015-12-31 17:53
Closing as a duplicate of #5559. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 17:53 UTC
