### ISSUE TITLE
[TIP] When providing a screenshot to a github issue....

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12871] opened 2017-01-26 06:50 UTC
[TIP] When providing a screenshot to a github issue, compressing the image file will reduce the upload time from `10 seconds to 1 second`

**also** the file will not be rejected for having an "inappropriate file format" which it gave me as a default error message

**Comment by raisedadead** [comment] 2017-01-26 09:43
You should simply drag and drop the image in the github comment box. We rely on the native uploader provided by github than on any other third party services. 

In my experience, it has been a consistent option, and works reliably.

**Comment by no-stack-dub-sack** [comment] 2017-01-26 23:29
That or copying an image and just pasting it in if you are using a snipping tool like pressing CMD + SHIFT + 4 works well too, that way the image never even has to be saved to your computer

**Comment by tommygebru** [comment] 2017-01-27 05:02
Thanks guys i simply noticed that github had a hard time with my screenshots, they took really long and there was even a default error message for me once. So i used compressor.io before dragging and dropping into github!

**Comment by no-stack-dub-sack** [comment] 2017-01-27 05:42
@tommygebru Hey, if it works, it works! 👍  I think we can probably close this though since not a bug and not directly FCC related.

**Closed by no-stack-dub-sack** 2017-01-27 05:42 UTC
Labels: bike shedding
