### ISSUE TITLE
Fix minor navbar / landing UI inconsistencies

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37921] opened 2019-12-13 14:24 UTC
I've recorded a video for this as it's easier to explain it that way

https://youtu.be/BMbLgxX8Pec

**Comment by thecodingaviator** [comment] 2019-12-13 15:22
Contributors, refer to #37778 too

**Comment by ojeytonwilliams** [comment] 2019-12-13 15:26
The first issue (magnifying glass,  #37778 as @thecodingaviator noted) should be fixed by https://github.com/freeCodeCamp/news-theme/pull/87.  The second issue, the font weight, I don't see on my machine - not sure why.  There is a difference in padding, though, which means the vertical positioning is different.  News:
![image](https://user-images.githubusercontent.com/15801806/70810763-a2c77e80-1dc4-11ea-81e9-6c2aefe2a340.png)

and learn:
![image](https://user-images.githubusercontent.com/15801806/70810721-8cb9be00-1dc4-11ea-8259-cb405f9c615f.png)

It's only 1 higher, but learn is closer to the centre.  Which do you prefer?

**Comment by MSSR-code** [comment] 2019-12-24 06:20
Hi, can I work on this issue.

**Comment by ahmadabdolsaheb** [comment] 2019-12-25 15:28
@MSSR-code please go ahead.

**Comment by AshNaz87** [comment] 2020-01-22 12:49
@ahmadabdolsaheb Has this been fixed?

**Comment by ahmadabdolsaheb** [comment] 2020-01-23 07:13
@AshNaz87, there is one pr for the magnifying glass but not a completed solution yet, and there is nothing for the font.

Feel free to submit your solution or to the add the the following pr.
https://github.com/freeCodeCamp/news-theme/pull/87

**Comment by swatiparge** [comment] 2020-02-12 16:59
@ahmadabdolsaheb Has this been fixed?  Can I work on this?

**Comment by ahmadabdolsaheb** [comment] 2020-02-13 08:10
Not yet @swatiparge, please refer to #37701 for more discussion on the font issue.

Please look into the global.css in the theme repo for font selectors that we don't have on /learn that might be changing how the fonts look.

Feel free to submit your solution or to the add the the following pr.
freeCodeCamp/news-theme#87

**Comment by AshNaz87** [comment] 2020-02-13 10:09
@ahmadabdolsaheb Looks like it's been fixed

**Comment by ahmadabdolsaheb** [comment] 2020-02-17 05:25
I can still reproduce this on production, @AshNaz87 
<img width="1440" alt="Screen Shot 2020-02-17 at 8 24 22 AM" src="https://user-images.githubusercontent.com/4591597/74625910-fe184300-515e-11ea-997d-41bad81f0937.png">
<img width="1440" alt="Screen Shot 2020-02-17 at 8 24 14 AM" src="https://user-images.githubusercontent.com/4591597/74625914-007a9d00-515f-11ea-9cf7-ed2b8c55bf45.png">

**Comment by irina6793** [comment] 2020-03-15 17:36
Can I work on this issue?

**Comment by ahmadabdolsaheb** [comment] 2020-03-18 08:56
@irina6793, please go ahead.

**Comment by ahmadabdolsaheb** [comment] 2020-04-06 10:11
There are three different issues here:

1. news magnifying glass that has been discussed here: #37778
2. /learn and /news font mismatch that has been discussed here: #37701
3. landing and learn styles mismatch that has been addressed in production.

I am closing this issue as two of the discussed issues are duplicates and the third has been resolved.

**Closed by ahmadabdolsaheb** 2020-04-06 10:11 UTC
Labels: help wanted, scope: UI
