### ISSUE TITLE
"Go to current challenge" button don't work

### ISSUE THREAD

**Issue by smell-well** [freeCodeCamp/freeCodeCamp#43453] opened 2021-09-14 08:13 UTC
## Affected page

https://www.freecodecamp.org/learn
In this page, I want to click the "Go to current challenge" button. No matter which page I opened last time, it will only jump to this page (the skewX property).. I don't know how to fix.

## Screenshot

![image](https://user-images.githubusercontent.com/58506662/133220360-9ddebf95-4265-4494-a400-9f3a48f9e036.png)
![image](https://user-images.githubusercontent.com/58506662/133220633-0b35971f-7566-4ddc-aea7-161f732a3f0f.png)

## System

- Device: laptop
- OS: Windows 10
- Browser: edge
- Version: Version 93.0.961.47

**Comment by Shlok1999** [comment] 2021-09-14 08:38
This button takes you to the last opened challenge/ tutorial you visited as there can be multiple unfinished topics. What is the exact change you want?

**Comment by smell-well** [comment] 2021-09-14 10:42
> This button takes you to the last opened challenge/ tutorial you visited as there can be multiple unfinished topics. What is the exact change you want?
No matter which page I opened last time, it will only jump to this page (the skewX property). It was normally available before andI have completed all the courses in order.

**Comment by smell-well** [comment] 2021-09-14 10:48
when I learned the tutorial of skew, the network broke once. Don't if it is the reason that button always jump to the tutorial.

**Comment by moT01** [comment] 2021-09-16 16:15
I could not reproduce this. You could check your network tab in the dev tools - when you go to a new challenge, there should be a post request to `api.freecodecamp.org/update-my-current-challenge` - the challenge id will be in the request body. You can search the repo for that id to see what challenge it is. If the it should be the challenge you went to and not the skewX one. Looks like the response would be the same id. I'm not sure how that helps, I guess you could see if that request is being made and gets the expected response.

**Comment by scissorsneedfoodtoo** [comment] 2021-09-17 16:07
Thanks for your patience and for reaching out about this @smell-well. We've had some reports about this issue in our support inbox recently.

Usually the fix is to clear your browser's cache and cookies, then sign in again. Then once you complete another challenge, the "Go to current challenge" button should work as expected.

Could you try that and let us know if that fixes the issue?

**Comment by smell-well** [comment] 2021-09-18 03:59
@scissorsneedfoodtoo I have tried what you said and it did work. Thank you for your helping.

**Closed** 2021-09-18 04:01 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
