### ISSUE TITLE
[Beta] Settings page doesn't redirect to error for non-user

### ISSUE THREAD

**Issue by ciberstrigo** [freeCodeCamp/freeCodeCamp#15809] opened 2017-08-26 20:47 UTC
#### Challenge Name

http://beta.freecodecamp.com/en/settings

#### Issue Description

All buttons become blurred after complete page downloading.

#### Browser Information

* Browser Name, Version: Google Chrome Version 60.0.3112.101 (Official Build) (32-bit)
* Operating System: Microsoft Windows 10 32-bit
* Mobile, Desktop, or Tablet: Laplet

#### Your Code

```js



```
#### Screenshot

![photo_2017-08-26_23-38-43](https://user-images.githubusercontent.com/23608243/29744974-de7fe184-8ab8-11e7-87e4-af21bcb511c1.jpg)

**Comment by vivek28111992** [comment] 2017-08-26 20:54
Can I try this? I would also like to know what should be output of this page?

**Comment by ciberstrigo** [comment] 2017-08-26 21:38
@vivek28111992 
How are you going to try this? Screenshot with same page, but with stopped load. I think it should be like that...
![photo_2017-08-27_00-33-25](https://user-images.githubusercontent.com/23608243/29745313-edb1fe74-8abf-11e7-8b36-1e2e5c10de5d.jpg)

**Comment by vivek28111992** [comment] 2017-08-27 10:15
@ciberstrigo
From what I have seen, I can say that blur problem is due to css & text issue may be due to some other problem.

**Comment by erictleung** [comment] 2017-08-29 20:10
@ciberstrigo If you don't have an account or are not logged in, I can reproduce this blurring effect. Probably because if you don't have an account, you shouldn't have settings. Once I was logged in, I can see the settings. So closing as not an issue. Happy coding!

**Comment by ric026** [comment] 2017-08-29 20:19
Rico26

**Comment by systimotic** [comment] 2017-08-30 11:51
@erictleung I think this actually is an issue. As far as I'm aware, we used to have redirects with error messages set up for users accessing a page they can't access. Apparently, this isn't working in the beta.

**Comment by erictleung** [comment] 2017-08-30 15:20
@systimotic ah okay. Sounds good to me. In hindsight, I agree a non-user should get better feedback on what the screen is, like you say with a redirect with an error message 👍

**Comment by MaxKam** [comment] 2017-08-30 23:18
@vivek28111992 Are you still working on this? If not I'll take this issue.

**Comment by vivek28111992** [comment] 2017-08-31 08:32
@MaxKam you can take this issue

**Comment by BerkeleyTrue** [comment] 2017-09-26 03:39
I've just run into this issue. Normally, once the page loads client side, ReactRouter should redirect an unauthenticated user to the map page. Unfortunately some recent changed has broken this logic.

**Closed** 2017-12-15 21:53 UTC
Labels: beta, QA, UX
