### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by markrawls** [FreeCodeCamp/FreeCodeCamp#5589] opened 2015-12-30 22:30 UTC
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=function%20myFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0A%0AmyFunction(46%2C%202)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Simply running the code produces 
```
function myFunction(a, b) {
  console.log(a + b);
}
```

My code:
```javascript
function myFunction(a, b) {
  console.log(a + b);
}

myFunction(46, 2);
```

**Comment by ltegman** [comment] 2015-12-30 22:32
Closing as a duplicate of #5560. Thanks and happy coding!

**Closed by ltegman** 2015-12-30 22:32 UTC
