### ISSUE TITLE
Add Font Awesome Icons to all of our Buttons: "DELETE" cut off page

### ISSUE THREAD

**Issue by codemaiden** [FreeCodeCamp/FreeCodeCamp#10703] opened 2016-09-12 03:45 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons#?

#### Issue Description

when adding the trash glyphicon, "Delete" text is cut off due to padding from "container" class.

#### Browser Information

using macbook with 13inch screen
* Browser Name, Version: 
Google Chrome
* Operating System: El Capitan OSX 
Desktop

#### Screenshot
![screen shot 2016-09-11 at 11 44 24 pm](https://cloud.githubusercontent.com/assets/16691984/18424066/d1f9337c-7879-11e6-8488-55592f343713.png)

**Comment by ltegman** [comment] 2016-09-12 05:58
Closing as a duplicate of #7842. Thanks and happy coding!

**Closed by ltegman** 2016-09-12 05:58 UTC
