### ISSUE TITLE
Sivler background check failed.

### ISSUE THREAD

**Issue by hantsy** [FreeCodeCamp/FreeCodeCamp#10579] opened 2016-09-09 14:08 UTC
Challenge [give-a-background-color-to-a-div-element](https://www.freecodecamp.com/en/challenges/html5-and-css/give-a-background-color-to-a-div-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
.red-text {
  color: red;
}

h2 {
  font-family: Lobster, Monospace;
}

p {
  font-size: 16px;
  font-family: Monospace;
}

.thick-green-border {
  border-color: green;
  border-width: 10px;
  border-style: solid;
  border-radius: 50%;
}

.smaller-image {
  width: 100px;
}

.silver-background {
background-color: silver;
}

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="silver-background">
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
</div>

<form action="/submit-cat-photo">
<label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
<label><input type="radio" name="indoor-outdoor"> Outdoor</label>
<label><input type="checkbox" name="personality" checked> Loving</label>
<label><input type="checkbox" name="personality"> Lazy</label>
<label><input type="checkbox" name="personality"> Energetic</label>
<input type="text" placeholder="cat photo URL" required>
<button type="submit">Submit</button>
</form>

    ```

**Comment by erictleung** [comment] 2016-09-09 14:12
@hantsy closing as duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10535. Happy coding!

**Closed by erictleung** 2016-09-09 14:12 UTC

**Comment by hantsy** [comment] 2016-09-09 14:55
it seems it failed in Firefox, but it is ok in Google Chrome.
