### ISSUE TITLE
Cannot submit API Projects (Basic Node and Express Course)

### ISSUE THREAD

**Issue by YUANLIN327** [freeCodeCamp/freeCodeCamp#17746] opened 2018-06-28 14:07 UTC
#### Describe your problem and - if possible - how to reproduce it
When I tried to provide my solution by submitting url from glitch, it no longer worked anymore.
Check the link and it returns 404. I don't know why FCC uses _api/package.json, but it just doesn't work.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  54
* Operating System: Mac

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/12224909/42039255-fbc19664-7aba-11e8-8db6-c2bafd2b974e.png)

**Comment by robjloranger** [comment] 2019-02-22 19:40
The `_api` route should work fine. Free Code Camp is using this as it is part of the app you cloned.

See https://github.com/freeCodeCamp/boilerplate-npm/blob/58a9a55cf988d9f3df3a7fd476ab404b7dcc2188/server.js#L27-L35

There are similar issues being reported however, #17584 for example

**Comment by moT01** [comment] 2019-05-06 20:54
Closing as duplicate of issue mentioned above. Thanks and happy coding!

**Closed by moT01** 2019-05-06 20:54 UTC
Labels: scope: curriculum
