### ISSUE TITLE
UX 

### ISSUE THREAD

**Issue by oussamanidhal** [freeCodeCamp/freeCodeCamp#41643] opened 2021-03-28 21:05 UTC
**Describe the bug**
**Consistency** is one of the UX Design principal that every website should take care of that.
Sign out button above the title of the page "Account Settings for User Name" is not a good choice. I think that we should Remove this button or change the position at the bottom of the page. Because we have this button in the Menu

**To Reproduce**
1. Go to 'Freecodecamp.org'
2. Click on 'Menu'
3. Scroll down to 'Settings'
4. See an error. 

**Screenshots**
![contribution2](https://user-images.githubusercontent.com/48177890/112766740-04881800-900b-11eb-9f20-4ae6dca51f09.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser:  chrome
 - Version: 89.0.4389.90

**Comment by ShaunSHamilton** [comment] 2021-03-28 23:57
Hello there,

I am closing this as a duplicate of #41423

**Closed by ShaunSHamilton** 2021-03-28 23:57 UTC
Labels: type: bug
