### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-scope-your-variables has an issue 

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/freecodecamp#668] opened 2015-05-27 22:17 UTC
Ctrl+Enter doesn't seem to have any effect. It worked for the waypoints with code editors, but not for this one. (I haven't explored others to see if it works elsewhere.)

If I click the button manually on the page, ctrl+enter also doesn't work to move on to the next challenge.

**Comment by terakilobyte** [comment] 2015-05-27 23:03
Please try performing a hard refresh of your browser.

**Comment by terakilobyte** [comment] 2015-05-28 14:49
I'm going to close this issue as I can't reproduce this behavior and no update. You can reopen it if the problem still persists for you.

**Closed by terakilobyte** 2015-05-28 14:49 UTC
