### ISSUE TITLE
i think they miss this mistake

### ISSUE THREAD

**Issue by a-computer-lover** [FreeCodeCamp/FreeCodeCamp#12342] opened 2017-01-03 19:57 UTC
Challenge [Call out Optional Actions with Button Info](https://www.freecodecamp.com/challenges/call-out-optional-actions-with-button-info has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <button class="btn btn-block btn-primary">Like</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

In line 32 dot'S place is wrong
i reseted but it still appears. And i submit in chat, others have the same issue too
<p>Click here for <a href="#">cat photos</a>.</p>
dot should be in text!

**Comment by Manish-Giri** [comment] 2017-01-03 20:10
@a-computer-lover It's the default starter code from the [Make Dead Links](https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol) challenge.

**Comment by dhcodes** [comment] 2017-01-03 21:12
@a-computer-lover while it may look odd, having the `.` apart from the anchor link keeps the period from being part of the link. This is intended.

**Comment by raisedadead** [comment] 2017-01-04 04:29
@a-computer-lover Closing as this is an intended behaviour for the challenge.

**Closed by raisedadead** 2017-01-04 04:29 UTC
