### ISSUE TITLE
Broken test on React: Render a Class Component to the DOM

### ISSUE THREAD

**Issue by TommyBakkenMydland** [freeCodeCamp/freeCodeCamp#34337] opened 2018-11-15 12:01 UTC
**Describe your problem and how to reproduce it:**
On submit the sites crashes.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/render-a-class-component-to-the-dom

**Tell us about your browser and operating system:**
* Browser Name:  Chrome, Edge, IE
* Browser Version: Most Recent
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/44838160/48551697-92e61e00-e8d6-11e8-8836-d98fb0748009.png)

**Comment by ezioda004** [comment] 2018-11-15 12:06
Hi @TommyBakkenMydland,

The issue is that you're trying to render the class component (TypesOfFood) *inside* itself, hence it forms infinite recursion and crashes the browser.

**Comment by Nirajn2311** [comment] 2018-11-15 12:33
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding

**Closed by Nirajn2311** 2018-11-15 12:33 UTC
