### ISSUE TITLE
Forum Topic title needs different font color when title rolls up into nav bar

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35971] opened 2019-05-05 14:39 UTC
I am not sure when the change was made, but I notice when a forum topic title rolls up into  top (in the navbar), that its font color is black.  Against the green background of the navbar, it is difficult to read the text.  I suggest making the font-color white when the title rolls up into the navbar.

![example](https://user-images.githubusercontent.com/5313213/57195552-eaba2500-6f08-11e9-93c7-955e061f6bb2.gif)

**Comment by moT01** [comment] 2019-05-05 22:51
Looks like that might be reverted or changed on beta
https://www.freecodecamp.rocks/forum/t/canceled-april-ikeja-study-group-at-andela/30

**Comment by RandellDawson** [comment] 2019-05-05 23:07
I am not sure where the forum code is kept on GitHub.

**Comment by moT01** [comment] 2019-05-05 23:19
Not sure where it is either, maybe it's private or something - but that test forum is new with this latest beta I think.

**Comment by RandellDawson** [comment] 2019-05-05 23:34
The test forum has been there for about 2-3 months.

**Comment by RandellDawson** [comment] 2019-05-10 15:48
@raisedadead Is there a repo for the forum settings where we can submit a PR to make a change to this?

**Comment by raisedadead** [comment] 2019-05-10 18:26
This is currently a trade off, for the icons hamburger and search. Making the topic switch to `#ffffff` is going to gray out the icon. We are working on a brand new theme, that will hopefully fix this.

The icon fix was suggested by @cmccormack a few days ago.

**Comment by lionel-rowe** [comment] 2019-05-11 09:16
How is it affecting the hamburger/search icons? If I add the following custom CSS:
```css
.extra-info-wrapper .topic-link {
  color: #fff;
}
```
It changes the topic title color as intended with no changes (so far as I can see) to the icons or anything else.

**Comment by raisedadead** [comment] 2019-05-11 09:32
Thanks, I have added these in the forum. It's a temporary fix for now. I will however, add the themes to version control real soon in preparation of our  newer color schemes that we are planning to have soon.

Thanks for your help.

**Comment by raisedadead** [comment] 2019-05-11 10:21
Here is the new theme repo: https://github.com/freeCodeCamp/discourse-theme, this is not being used at the minute. We will deploy this when we get a chance to overhaul the look and feel as per our latest design guidelines.

@ahmadabdolsaheb is taking lead on this. He will be prep-ing and deploying the new theme to our staging instances for feedback before we use it on all our production forums.

For now, I have deployed the fix as suggested by @lionel-rowe in a previous comment, temporarily.

**Comment by RandellDawson** [comment] 2019-06-04 22:20
@ahmadabdolsaheb Have you had a chance to implement a permanent fix for this issue?

@raisedadead Technically, the issue I raised has been fixed on the forum now, but do you want to leave this issue open until a permanent fix is created?

**Comment by raisedadead** [comment] 2019-06-06 19:55
@ahmadabdolsaheb is working on a new theme as per our new design guidelines. It may be a while before we have the fix ready and deployed. You are free to leave the issue open for traceability.

Thanks.

**Comment by moT01** [comment] 2019-11-13 16:27
This looks like it's fixed with the new forum. Can you confirm and close this if it is @RandellDawson?

**Comment by RandellDawson** [comment] 2019-11-13 17:05
@moT01 Yes, this was fixed a while back with a temporary fix.  Now, I assume the new permanent fix is place. @ahmadabdolsaheb Can you confirm this?  If so, can you close this issue?

**Comment by raisedadead** [comment] 2019-11-13 19:31
We have just updated the color scheme. A much newer UI theme is in the works. Nonetheless this issue stands closed.

**Closed by raisedadead** 2019-11-13 19:31 UTC
Labels: platform: forum, scope: user interface
