### ISSUE TITLE
ES6: Understand the Differences Between import and require - failing test - require not defined

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16353] opened 2017-12-28 16:26 UTC
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/understand-the-differences-between-import-and-require

#### Issue Description
The challenge is failing the test after entering the import statement.
It states 'require is not defined'
But there are no instructions/requirements to use require.

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
`"use strict()";
import { capitalizeString } from "string_functions";
capitalizeString("hello!");`


```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34416524-eeba3bde-ebc1-11e7-9242-deab851f2952.png)

**Comment by systimotic** [comment] 2017-12-28 21:37
Thanks for all of the QA work @mstellaluna! I'm closing this as a duplicate of #16235

**Closed by systimotic** 2017-12-28 21:37 UTC
Labels: beta
