### ISSUE TITLE
Possible browser issue?

### ISSUE THREAD

**Issue by jecmstudios** [freeCodeCamp/freeCodeCamp#13508] opened 2017-02-22 08:00 UTC
This is the code that I have put in.  When I test the link myself, it does everything the challenge mentions.  I am just unable to complete this challenge.  Am I missing something?

Challenge [adjust-the-hover-state-of-an-anchor-tag](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  a {
    color: #000;
  }
  a:hover{
    color: #00F;
    text-decoration: none;
  }
  
</style>
<a href="https://atjonathan.github.io/catphotoapp">CatPhotoApp</a>

```

**Comment by donofriov** [comment] 2017-02-22 08:10
@jecmstudios That challenge is explicitly looking for the hover color to be blue. Try without using a Hexcode.

This doesn't seem to be a browser issue so it will most likely get closed out. When you get stuck you can always click the Help button on each challenge and/or join the full chat app at [Gitter](https://gitter.im/FreeCodeCamp/) for help questions

**Comment by BhaveshSGupta** [comment] 2017-02-22 08:16
I think we should add the test case to check even hex code or even rgba code

**Comment by donofriov** [comment] 2017-02-22 08:21
This test is looking for color:blue; and nothing else. If you open it up to hex code and/or rgba code you will have to define all the possibilities of blue. That wouldn't work so well because you would have to figure out where to draw the line between what's accepted as blue and what's not. I think this is a pretty simple test and you are guided to just using the word blue.

**Comment by BhaveshSGupta** [comment] 2017-02-22 08:47
If we write just blue as the color code test is not completed,  I found out that for the black color the test checks for RGB value for the black
![image](https://cloud.githubusercontent.com/assets/4209637/23203672/8728c874-f909-11e6-988d-f1a9e6a80077.png)

**Comment by donofriov** [comment] 2017-02-22 08:52
Hmm then this may be a browser bug, because I'm not seeing the same results:

![image](https://cloud.githubusercontent.com/assets/4457953/23203881/5c9f4d82-f8b2-11e6-9abd-59f9e25945c9.png)

**Comment by BhaveshSGupta** [comment] 2017-02-22 08:59
The test case check for RGB value $('a').css('color') == 'rgb(0, 0, 0)' may be this would be causing the issue.

**Comment by BhaveshSGupta** [comment] 2017-02-22 09:56
And if we want to anyone to write color in value then we should change color #000 to black which would make more sense then.

**Comment by raisedadead** [comment] 2017-02-22 11:44
@jecmstudios thanks for reporting.
@donofriov @BhaveshSGupta this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/13468

Closing, please feel free to continue on the other thread.

**Closed by raisedadead** 2017-02-22 11:44 UTC

**Comment by BhaveshSGupta** [comment] 2017-02-27 04:44
@raisedadead This issue is because of #10749, You can see the test case it uses jQuery's CSS method
