### ISSUE TITLE
React Challenges - Constant "Something Went Wrong" errors while your typing

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16387] opened 2018-01-01 16:22 UTC
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/react/create-a-complex-jsx-element

#### Issue Description

While attempting to do the React challenges, as your typing, the pop up "Something Went Wrong" consistently shows up on the screen and can take up the whole editor space. 

This affects all the React challenges ......

Is there a way to suppress these until the actual 'Run Tests' is executed?

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34469106-9986cec6-eee5-11e7-9663-a1995573a927.png)

**Comment by mstellaluna** [comment] 2018-01-01 16:29
It seems refreshing the page corrects the issue .....

**Comment by BerkeleyTrue** [comment] 2018-01-01 23:51
closing as duplicate of #16361

**Closed by BerkeleyTrue** 2018-01-01 23:51 UTC
Labels: beta
