### ISSUE TITLE
Waypoint: Change the CSS of an Element Using jQuery

### ISSUE THREAD

**Issue by CoderBklyn** [FreeCodeCamp/FreeCodeCamp#4892] opened 2015-12-02 03:40 UTC
THE CODE IS CORRECT BUT IT WONT ACCEPT IT AND ALLOW ME TO PASS, MULTIPLE USERS IN CHAT ARE HAVING THIS ISSUE
```
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by ltegman** [comment] 2015-12-02 03:56
We are aware of this problem and have a PR getting QA'd that will fix this issue. Closing as a duplicate of #4865

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 03:56 UTC
