### ISSUE TITLE
Tests do not work as intended

### ISSUE THREAD

**Issue by PSN221B** [freeCodeCamp/freeCodeCamp#39111] opened 2020-06-21 00:23 UTC
The first 3 test cases do not work. Clear the coding area (the one in the center) and still the 3 test cases will pass. The JQuery written to test the 3 cases is probably running on the example page layout (on the left).

Chrome and Mozilla both had the same problem.

[https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document](url)

**Comment by ptkpyitheim** [comment] 2020-06-21 03:09
So I tried doing
`$('head').length` in the console and it gives me undefined.

However, if I try just `$('head')` it gives me the content in the `head` tag of the HTML rendered on the browser. This doesn't necessarily checks what we write inside the "Code" for the task.

I wonder if there's another way to do this because apparently using jQuery code directly in our assert function of the tests don't seem to work.

**Comment by ojeytonwilliams** [comment] 2020-06-21 09:08
The preview lives in one iframe and the tests another. If you want to see what will happen in the tests, you can select the `fcc-main-frame` and query that.  

The problem with this challenge is that the user's source goes through a bit of processing before it's put into the iframe and will always have a html element with a head and a body (hence the tests always passing).  While jQuery is great for most tests,  anything involving html, head or body needs to be checked with regex.

**Comment by ojeytonwilliams** [comment] 2020-06-21 09:09
Related: #39101

**Comment by PSN221B** [comment] 2020-06-21 11:01
But with regex we end up with the problem of catastrophic backtracking, in case of any missing tag because of the .*? as pointed out in issue #39101.

**Comment by ojeytonwilliams** [comment] 2020-06-21 15:51
@PSN221B yep, you do need to be careful with the regex, but I don't think an exponential explosion is inevitable.

**Comment by raisedadead** [comment] 2020-06-22 10:35
Is this a confirmed bug? If yes can we triage as such. Thanks.

**Comment by ojeytonwilliams** [comment] 2020-06-22 17:06
It is certainly not working as intended.  The entirety of the user's code is inserted into the preview/test iframe's body at which point (I think) the `head` and `body` tags get stripped off.  Hence weird stuff like this https://github.com/freeCodeCamp/freeCodeCamp/pull/39112#issuecomment-647615569

In principle we can change this and, if we can do it, it would be an improvement. It will need careful QA, though.

**Comment by moT01** [comment] 2021-04-23 01:50
I believe this issue is resolved. The tests are using regex again, and I could not reproduce any issues. So I think it's safe to close. If anyone thinks I am wrong in closing this, feel free to leave a comment and it can be reopened. Thanks and happy coding 🎉

**Closed by moT01** 2021-04-23 01:50 UTC
Labels: help wanted, scope: curriculum, type: bug
