### ISSUE TITLE
Waypoint saying Lowest and Highest Range NOT equal to min and max.

### ISSUE THREAD

**Issue by ehutchllew** [FreeCodeCamp/FreeCodeCamp#10639] opened 2016-09-09 22:43 UTC
Challenge [generate-random-whole-numbers-within-a-range](https://www.freecodecamp.com/en/challenges/basic-javascript/generate-random-whole-numbers-within-a-range) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    
    
// Example
function ourRandomRange(ourMin, ourMax) {

return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

return Math.floor(Math.random() * (myMax - myMin + 1) + myMin); // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

    ```

**Comment by dhcodes** [comment] 2016-09-10 02:22
Thanks for the issue @ehutchllew. I believe it's a duplicate of #10613. Closing as duplicate.

**Closed by dhcodes** 2016-09-10 02:22 UTC
