### ISSUE TITLE
Padding and lay-out issues on the preview

### ISSUE THREAD

**Issue by andrewtdinh** [FreeCodeCamp/FreeCodeCamp#8599] opened 2016-05-13 03:34 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/line-up-form-elements-responsively-with-bootstrap

#### Issue Description

The Like, Info, and Delete buttons need more padding on the right side.  Also, the 'Loving' checkbox label should be on the same line as the checkbox that it labels.  Also, shouldn't the Submit button be on the same line as the text input?  

#### Browser Information

* Browser Name, Version:  Chrome, Version 50.0.2661.94 (64-bit)
* Operating System: Mac OSX, Yosemite, version 10.10.5
* Mobile, Desktop, or Tablet: Mac Book Pro 15"

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/11606611/15237189/74ec60b8-1880-11e6-90ea-66ae491915e1.png)

**Comment by erictleung** [comment] 2016-05-13 04:27
@andrewtdinh closing as essentially duplicate of #7842. Feel free to carry the discussion or pick up the issue over there. Happy coding!

**Closed by erictleung** 2016-05-13 04:27 UTC

**Comment by andrewtdinh** [comment] 2016-05-13 16:25
Alright.  Thank you, @erictleung!  I will bring the discussion over there.
