### ISSUE TITLE
Give user feedback after wrong submission

### ISSUE THREAD

**Issue by cragsify** [FreeCodeCamp/FreeCodeCamp#6875] opened 2016-02-10 23:39 UTC
Currently there is no User feedback when a user attempts to verify that a challenge is complete. The change from a tick to an X is very subtle and I would suggest implementing a screen flash. This would be especially helpful with people with slow/unreliable internet connections where it may take a while for the answer to verify.

**Comment by SaintPeter** [comment] 2016-02-11 03:40
This is something which we are planning to visit soon.  We're thinking that we may have "toasts" (little floaty pop-ups) that say something like "X of Y tests failed" or something like that.  Some sort of positive indication that the tests were run.  Even I have experienced issues where I was not sure that the tests had run at all.

**Comment by W12S12E12** [comment] 2016-02-11 15:02
one of http://www.codeproject.com/Articles/26235/GDI-Code-Generator

idea of https://github.com/trampgeek/moodle-qtype_coderunner
or https://github.com/harryaskham/Twitter-L-LDA/blob/master/WebLLDA/textwiseWordIDs.csv

**Comment by ltegman** [comment] 2016-02-11 17:18
Closing as a duplicate of #5111. Thanks and happy coding!

**Closed by ltegman** 2016-02-11 17:18 UTC
Labels: on the roadmap
