### ISSUE TITLE
Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by bishals** [FreeCodeCamp/FreeCodeCamp#11916] opened 2016-12-04 13:41 UTC
**Challenge [Nest an Anchor Element within a Paragraph]
Now nest your existing a element within a new p element (just after the existing h2 element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text.**
```html
<h2 class="red-text">CatPhotoApp</h2>
<p>View more
<a href="http://www.freecatphotoapp.com">cat photos</a>
  </p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
```
I didn't find any error in this code but still it shows some error..
*Create a new p element around your a element.
*Your a element should be nested within your new p element.
*Your p element should have the text "View more " (with a space after it).
```

**Comment by srivasthavapippari** [comment] 2016-12-04 14:10
i too didn't get it

**Comment by Bouncey** [comment] 2016-12-04 16:22
@bishals I cannot reproduce your issue

Can you press the reset button and try again?

Happy Coding! :+1:

**Comment by ajain17** [comment] 2016-12-05 03:30
I can't reproduce it either. Are you clicking on "Run tests" after making your changes?

**Comment by wmcooper2** [comment] 2016-12-05 04:47
Doing a "hard refresh" on the page, then trying the challenge solved my problem.

**Comment by ajain17** [comment] 2016-12-12 16:20
@dhcodes Please close this issue.

**Comment by raisedadead** [comment] 2016-12-12 16:21
Done.

**Closed by raisedadead** 2016-12-12 16:21 UTC
