### ISSUE TITLE
Incorrect description of parent-child inheritance

### ISSUE THREAD

**Issue by jangeroo** [FreeCodeCamp/FreeCodeCamp#2238] opened 2015-08-19 22:11 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. The first sentence of the text is incorrect. `Many HTML elements have children elements from which they inherit properties` should read `Many HTML elements have children elements which inherit their properties`. Children inherit from parents, not the other way around.

**Comment by dokkillo** [comment] 2015-08-19 22:33
working in it

**Comment by benschenker** [comment] 2015-09-03 03:21
Thanks for posting this!

This is a duplicate of #2065 so keep an eye there for updates on this.

**Closed by benschenker** 2015-09-03 03:21 UTC
