### ISSUE TITLE
Production: About page is broken (oops message):

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#10522] opened 2016-09-09 06:46 UTC

**Comment by BerkeleyTrue** [comment] 2016-09-09 07:15
Can't reproduce on beta with production db. Beta does not show correct number of certificates

No actual error is reported to logs

**Comment by evaristoc** [comment] 2016-09-09 09:13
Confirmed on my side: Oops message

**Comment by P1xt** [comment] 2016-09-09 10:02
It looks a lot like what was on beta earlier this week got pushed to production. About page gives an oops, the double scrollbars are on the map page, UX is wonky on the challenges themselves and a number of challenges won't submit and/or the editor loses your changes on submit.

**Comment by ivantedja** [comment] 2016-09-29 16:30
confirmed in beta, indentation problem,see screenshots

![error](https://cloud.githubusercontent.com/assets/1907854/18962857/aa75fd7c-869c-11e6-8e51-305c0ea907f8.png)

![indentation](https://cloud.githubusercontent.com/assets/1907854/18962865/ae604bcc-869c-11e6-84f6-e596bbb62f79.png)

**Comment by systimotic** [comment] 2016-10-04 11:49
Am I looking at the wrong page, or has this been fixed? https://www.freecodecamp.com/about seems to work just fine.

**Comment by ivantedja** [comment] 2016-10-04 11:57
@systimotic it is in beta: https://beta.freecodecamp.com/about

**Comment by systimotic** [comment] 2016-10-04 12:23
Oops, sorry about that! I got confused because the title says production. I'm having a go at fixing it right now.

**Comment by systimotic** [comment] 2016-10-29 18:03
Fixed in #11053

**Closed by systimotic** 2016-10-29 18:03 UTC
