### ISSUE TITLE
Redirect to homepage after completing a challenge

### ISSUE THREAD

**Issue by JonSelig** [FreeCodeCamp/FreeCodeCamp#6958] opened 2016-02-13 08:38 UTC
After completing some challenges (using ctrl+enter twice) I get redirected to http://www.freecodecamp.com/map where a banner pops up and says "Oops! Something went wrong. Please try again later"

I'm on the beginning of the HTML5 and CSS section

Edit:
I just looked at the console after this happened again and here are the 2 error messages:
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (sidecar.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)

**Comment by alistermada** [comment] 2016-02-13 09:10
I just went directly to http://www.freecodecamp.com/map and got that error as well. No errors in console.

![image](https://cloud.githubusercontent.com/assets/12993334/13026898/28da1d00-d26c-11e5-8c42-1cdf20a58f56.png)

**Comment by alistermada** [comment] 2016-02-13 23:57
It seems this problem was only temporary according to the discussion in #6960. I'm still getting this problem, although not as frequently and with fewer error messages.

@BerkeleyTrue can you confirm this issue as well?

**Comment by hallaathrad** [comment] 2016-02-14 00:01
I can confirm, I've just checked and replicated exactly the same way as this morning.

**Comment by JoshFisk** [comment] 2016-02-14 08:20
If you go directly to a next challenge url it will sometimes work, and sometimes fail.
http://www.freecodecamp.com/challenges/next-challenge?id=bad87fee1348bd9aedd08835

**Comment by benninkcorien** [comment] 2016-02-14 11:00
I have the same problem since yesterday.

**Comment by 13thThief** [comment] 2016-02-14 18:08
**I am here to confirm that this issue still persists**
Though minimized now, I face this problem frequently when I use mouse to click to go to the next challenge instead of Ctrl+Enter which causes it to happen less frequently, but nevertheless it still happens more or less!

I just thought of sharing this Mouse-Keyboard thing. 

I am in the section of HTML-CSS-jQuery.

**_(:_**

**Comment by morganmay** [comment] 2016-02-14 23:55
I've encountered this issue in both Firefox and Chrome.

**Comment by michi-gato** [comment] 2016-02-15 15:58
+1 on this issue for the past 3 days on FF and Chrome. I'm able to open up the Map menu on the right hand side but multiple "Oops!" messages still pop up on the main Map page.

**Comment by ltegman** [comment] 2016-02-15 17:41
We're sorry for the huge inconvenience caused by this bug. We thought we may have gotten to the bottom of it yesterday, but it didn't turn out to solve the problem. This bug is turning out to be very hard to pinpoint because it doesn't show up in our dev environments and there's nothing showing up in the server logs. We're continuing to investigate though. Thanks for your patience!

**Comment by metaljacke1** [comment] 2016-02-16 02:46
Im having the same issue as well. Browser: Chrome.

**Comment by alaskaa** [comment] 2016-02-17 20:56
I'm having the same issue. I signed up on Monday and the error happens frequently but not all the time. Sometimes, it doesn't load my page at all and just produces another "Oops" message at the top. Browser: Chrome

**Comment by JoshFisk** [comment] 2016-02-19 03:35
I would like to report, that I am no longer having this issue.

**Comment by ltegman** [comment] 2016-02-19 03:48
Closing this as resolved thanks to the efforts of @BerkeleyTrue! :smile:

**Closed by ltegman** 2016-02-19 03:48 UTC
Labels: bug, confirmed
