### ISSUE TITLE
Submit Button does not take to next Challenge.

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/FreeCodeCamp#2865] opened 2015-08-30 02:14 UTC
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-white has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

After completing the challenge, the 'Submit Button' does not take user to the next Challenge

**Comment by jasonfavors** [comment] 2015-08-30 03:25
Unable to reproduce: http://screencast.com/t/5vsPIym3W

**Comment by awesomeaniruddh** [comment] 2015-08-30 08:05
Usually reloading the page, or clicking on the button multiple times fixes the issue.

**Comment by wildlifehexagon** [comment] 2015-08-31 00:52
I've noticed that it usually takes a few seconds before the "submit" button works.

**Comment by benschenker** [comment] 2015-09-08 06:31
Yes, we've had a bunch of issues filed for this.  It seems that you currently need to hit the button twice, but it does work.

Closing this, but please reopen if this is not resolved for you.

**Closed by benschenker** 2015-09-08 06:31 UTC
