### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by eelay234** [FreeCodeCamp/freecodecamp#597] opened 2015-05-27 01:34 UTC
The answers as follows for the Waypoints from "Waypoint: Create a Set of Radio Buttons" till "Waypoint: Check Radio Buttons and Checkboxes by Default" couldn't go through. Please check it out.
  
<label><input type='radio' name='indoor-outdoor' checked> Indoor</label>
  <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
  <br>
  <label><input type='checkbox' name='personality' checked> Loving</label>
  <label><input type='checkbox' name='personality'> Lazy</label>
  <label><input type='checkbox' name='personality'> Crazy</label>
  <br>

**Comment by QuincyLarson** [comment] 2015-05-27 01:38
@eelay234 Could you take a screen shot of this?

**Comment by gigantor84** [comment] 2015-05-28 05:20
It got it to work by not putting a space between the close quote on name and checked:
name='indoor-outdoor'checked>

This doesn't work:
name='indoor-outdoor' checked>

**Comment by terakilobyte** [comment] 2015-05-28 14:48
I'm unable to reproduce this in any of my available browsers. I'm going to go ahead and close this.

**Closed by terakilobyte** 2015-05-28 14:48 UTC
