### ISSUE TITLE
Delete button is not align properly  

### ISSUE THREAD

**Issue by mihirvaghela** [FreeCodeCamp/FreeCodeCamp#12169] opened 2016-12-22 17:21 UTC
Challenge [Responsively Style Radio Buttons](https://www.freecodecamp.com/challenges/responsively-style-radio-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by erictleung** [comment] 2016-12-22 17:55
@mihirvaghela can you be more specific on what you mean it doesn't align properly? A screenshot of your issue would also help describe what you mean by not aligning properly. Thanks!

Possibly related: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7842

**Comment by mihirvaghela** [comment] 2016-12-22 19:03
![screen shot 2016-12-22 at 2 00 56 pm](https://cloud.githubusercontent.com/assets/3821594/21437008/561d5442-c84f-11e6-96e7-b38f8bd8deed.png)
![screen shot 2016-12-22 at 2 01 05 pm](https://cloud.githubusercontent.com/assets/3821594/21437011/589ff08a-c84f-11e6-94b8-45d6737ec2c7.png)

**Comment by rholinshead** [comment] 2016-12-23 04:35
I'm seeing a similar issue on the "Add Font Awesome Icons to all of our Buttons" Challenge which proceeds this one. After adding the styling for the trash icon to the delete button, the icon doesn't show up on the button at all but clicking "Run Tests" succeeds. Seems to be an issue with the padding in the body and the container-fluid div.
![codecampnotrashicon](https://cloud.githubusercontent.com/assets/5060851/21447209/4a83cea4-c89f-11e6-976a-a4b4be324e62.png)

**Comment by dhcodes** [comment] 2016-12-23 13:46
This is a duplicate of #7842. That issue is still open so I think we should move discussion there.

**Closed by dhcodes** 2016-12-23 13:46 UTC
