### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by f3mlat** [FreeCodeCamp/freecodecamp#689] opened 2015-05-28 06:50 UTC
The way point requested clockwise notation for margin in this order 20px 20px 20px 40px but works only with 40px 20px 20px 40px

**Comment by terakilobyte** [comment] 2015-05-28 11:02
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:02 UTC
