### ISSUE TITLE
Bon Fire: Drop It- Javascript Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by Hemalatah** [FreeCodeCamp/FreeCodeCamp#4402] opened 2015-11-13 02:39 UTC
In the "BonFire: drop it", the fifth test case given is not correct. I hope there will ba some updates on it soon.

**Comment by faizaanceg** [comment] 2015-11-13 03:06
Duplicate of #4278 #4325 . 

The Bonfire and test cases are correct. If you read the description correctly, the function should stop once the predicate returns true. So the last 2 in `[1,2,3,9,2]` would actually be preserved.

**Comment by ltegman** [comment] 2015-11-13 03:31
@faizaanceg is correct. Thanks and happy coding!

**Closed by ltegman** 2015-11-13 03:31 UTC

**Comment by Hemalatah** [comment] 2015-11-13 03:39
yup! I understand and got the answer! Thanks much.
