### ISSUE TITLE
The menu is opened when loading the Curriculum

### ISSUE THREAD

**Issue by SofianeDjellouli** [freeCodeCamp/freeCodeCamp#18061] opened 2018-08-29 20:01 UTC
Hi,

The menu is always opened when loading [the Curriculum](https://learn.freecodecamp.org/) on the first title and the first subtitle. I think it's the first interaction I had with it. It happens even if I sign out and on mobile (Iphone).

* Browser Name:  Chrome
* Browser Version: Latest
* Operating System: Windows

![image](https://user-images.githubusercontent.com/38258952/44812243-ffeeef00-abd6-11e8-9535-fda4eac83b85.png)

**Comment by thecodingaviator** [comment] 2018-11-21 15:53
@iamj4james Please go ahead

**Comment by ritute** [comment] 2019-02-24 23:17
I think a good experience here would be to expand the section where you completed your most recent challenge, and in the case where you haven't completed any, none would open.

**Comment by ritute** [comment] 2019-02-28 01:32
This PR might fix this issue: #35421

**Comment by moT01** [comment] 2019-05-06 13:25
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/34236

**Closed by moT01** 2019-05-06 13:25 UTC
Labels: help wanted, ux: user interface
