### ISSUE TITLE
Geolocation will no longer work on http connection for chrome 50 browsers 

### ISSUE THREAD

**Issue by fkingn00bGG** [FreeCodeCamp/FreeCodeCamp#8996] opened 2016-06-06 21:44 UTC
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

We cannot use `navigator.geolocation.getCurrentPosition` with code pen because the connection is http therefore this exercise will not work. Perhaps add a note or suggest an alternate way. Also your example will not work for everyone using chrome 50 browser. 
[source](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only)

**Comment by erictleung** [comment] 2016-06-06 22:03
Closing as duplicate of #8988.

**Closed by erictleung** 2016-06-06 22:03 UTC
