### ISSUE TITLE
Incorrect assert message?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#40455] opened 2020-12-14 18:26 UTC
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/add-methods-after-inheritance
Forum post: https://forum.freecodecamp.org/t/own-property-challenge-issues/435424

> Dog should have the bark() method as an `own` property.

The test seems to be expecting that the method is on the prototype.

**Comment by ShaunSHamilton** [comment] 2020-12-14 19:18
I think this is a duplicate of: https://github.com/freeCodeCamp/freeCodeCamp/issues/38433

Not much discussion has happened on that issue, though.

**Comment by moT01** [comment] 2020-12-22 16:59
Yes, this is a duplicate. Thanks for reporting @lasjorg, but I am going to close this since there's more information over on the other one.

**Closed by moT01** 2020-12-22 16:59 UTC
Labels: scope: learn
