### ISSUE TITLE
Waypoint: Iterate over Arrays with map

### ISSUE THREAD

**Issue by tbraden30** [FreeCodeCamp/FreeCodeCamp#4020] opened 2015-10-30 03:25 UTC
its saying that 3 wasnt added to each value when in fact it was. I may have sent this twice but it wasnt listed when i rechecked nor did i send an email confirmation. So sorry if its overkill. 
Theo 
![untitled](https://cloud.githubusercontent.com/assets/15311351/10837822/cbdb8f1e-7e8b-11e5-9b77-8cac2c845986.png)

**Comment by bugron** [comment] 2015-10-30 03:26
@tbraden30 thanks for posting this issue!
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4019.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-30 03:26 UTC
