### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by clevadani** [FreeCodeCamp/FreeCodeCamp#3555] opened 2015-10-01 18:40 UTC
When I try to start the "Get Started with Free Code Camp" Waypoint, I keep getting this error "Oops! Something went wrong. Please try again later" making me unable to finish the waypoint.

**Comment by bugron** [comment] 2015-10-01 18:48
@clevadani thanks for posting this issue!
Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3554. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-10-01 18:48 UTC
