### ISSUE TITLE
Comment your JavaScript Code passes multi-line comment tests without any code

### ISSUE THREAD

**Issue by petercollingridge** [freeCodeCamp/freeCodeCamp#12722] opened 2017-01-22 10:22 UTC
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/basic-javascript/comment-your-javascript-code

#### Issue Description
Pressing Run tests without typing any code passes the tests:
* Create a `/*` `*/` style comment that contains at least five letters.
* Make sure that you close the comment with a `*/`.

I've tried running in an incognito window, signed out, and in a different browser and it has the same issue.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.95 (64-bit) (also on Firefox)
* Operating System: OSX EL Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
<img width="1129" alt="screen shot 2017-01-22 at 10 15 33" src="https://cloud.githubusercontent.com/assets/219302/22181821/46ca55d0-e08c-11e6-8b32-e4859d9d7375.png">

**Comment by ChrisD1986** [comment] 2017-01-22 10:29
create a comment the challenge /*comment*/ && //comment, has specified.

**Comment by richiethomas** [comment] 2017-01-23 01:16
I'm able to reproduce this error on my local.  If no one has claimed this yet, can I take a crack at fixing this?

**Comment by richiethomas** [comment] 2017-01-25 20:04
I believe I found the issue.  The two assertions which always pass are using RegEx patterns to check against a string stored in a variable called `code` in the file "basic-javascript.json".  I was able to log the string stored in `code` to the console.  It looks like this:
```

<script>

;/*fcc*/
"use strict";
;/*fcc*/


;/*fcc*/
</script>
<!--fcc-->
```

Looks like the `/*fcc*/` code comes from line 82 of "execute-challenge-saga.js".  As I'm new to the codebase, I'm not sure what its intention is but I'm guessing it cannot be safely removed yet.

As you can see, there is no single-line comment (i.e. `// This is a comment`), which is why the first test doesn't register a false positive.  But there are multi-line comments, which is why the 2nd two tests do register false positives.

Is there any way I suggest replacing the last 2 assertions with the following or something similar: `Write a multi-line comment containing the word "All work and no play makes Jack a dull boy"` on 3 consecutive lines.

A more specific assertion, including specific comment text, would likely make the regex much more likely to pass.

**Comment by petercollingridge** [comment] 2017-01-25 21:23
The question already asks for at least 5 characters in the comment, which the extra code inserted does not have. However the inserts code is matches as the regex `/(\\/\\*)[\\w\\W]{5,}(?=\\*\\/)/` matches the start of the first comment with the end of the last one. If it were changed to something like `(\\/\\*)([^\\*\\/]{5,})(?=\\*\\/)`, I think that would solve the problem as it would restrict the characters in between the start and end of the comment from not ending the comment. I think the final test for ending the comment would have to be removed (it's covered by the second test anyway).

**Comment by richiethomas** [comment] 2017-01-25 22:38
Just tested the regex you provided (everything on one line, everything on multiple lines, either the opening or closing tags on the same line as text and the other on a new line), and all these functioned as expected.  I did notice the following case passes:

```
/*
dd
dd
*/
```

There are 4 visible characters here, I assume the 5th character is the newline.  Do we want to count this as a character for the purposes of the test, or should we strip out newlines beforehand?

I'm happy to submit a PR with the updated regex if there are no other edge cases to consider.

**Closed** 2017-01-29 08:46 UTC
Labels: beta

**Comment by Shigosag** [comment] 2021-08-08 06:43
This worked for me: 
`/fiverr/`
`/*fiverr*/`
