### ISSUE TITLE
delete-your-jquery-functions should be merged with next challenge

### ISSUE THREAD

**Issue by IntegraterGithub** [freeCodeCamp/freeCodeCamp#41805] opened 2021-04-13 20:37 UTC
NOTE: This is not a major issue 
Hi, on the jquery course there is a challenge called delete-your-jquery-functions where you delete the jquery function however I think this is a waste of challenge as you aren't exactly learning anything new or practicing a skill therefore you could merge it with the next challenge instead.

**Comment by ShaunSHamilton** [comment] 2021-04-14 09:26
Hello there,

Thank you, for taking the time to open this. I would tend to agree with you. I suspect, when this was originally written, the intent was to prevent the previous/next challenge from being too cluttered/require too many steps.

I do not think anything will be done about these challenges though, as this is not a bug, and no more challenges for this version of the curriculum are being created/removed.

Majority of the work being done is being done on [version 7 of the curriculum](https://www.freecodecamp.org/news/python-curriculum-is-live/) - _I do not think that is the best link explaining the next version, but I cannot find the exact one_

I will leave this open as a feature request for others to comment.

**Comment by Sembauke** [comment] 2021-05-14 14:27
Hey @IntegraterGithub,

As Shaun stated:

> I do not think anything will be done about these challenges though, as this is not a bug, and no more challenges for this version of the curriculum are being created/removed.

So therefore I will close this issue

**Closed by Sembauke** 2021-05-14 14:27 UTC
Labels: scope: curriculum, status: discussing, type: feature request
