### ISSUE TITLE
UX Consistency 

### ISSUE THREAD

**Issue by oussamanidhal** [freeCodeCamp/freeCodeCamp#41644] opened 2021-03-28 21:11 UTC
**Describe the bug**
Consistency is one of the UX Design principal that every website should take care of that.
Sign out button above the title of the page "Account Settings for User Name" is not a good choice. I think that we should Remove this button or change the position at the bottom of the page. Because we have this button in the Menu

**Steps to reproduce the behavior:**
1.Go to 'Freecodecamp.org'
2.Click on 'Menu'
3.Scroll down to 'Settings'
4.See an error.

**Screenshots**
![contribution2](https://user-images.githubusercontent.com/48177890/112768102-32248f80-9012-11eb-95f6-4661f686cba2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 89.0.4389.90

**Comment by ShaunSHamilton** [comment] 2021-03-28 23:58
Hello there,

I am closing this as a duplicate of your previous issue which is a duplicate of #41423

**Closed by ShaunSHamilton** 2021-03-28 23:58 UTC
Labels: type: bug
