### ISSUE TITLE
CSS Grid: Divide the Grid Into an Area Template

### ISSUE THREAD

**Issue by tsabunkar** [freeCodeCamp/freeCodeCamp#38332] opened 2020-03-07 15:07 UTC
CSS Grid Challenge : Place the area template so that the cell labeled advert becomes an empty cell.

```
.container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
    grid-template-areas:
    /* Only change code below this line */
      "header header header"
      ".  content content"
      "footer footer footer";
    /* Only change code above this line */
  }
```
But still **not** able to pass the test case : container class should have a grid-template-areas property similar to the preview but has . instead of the advert area.

**Comment by moT01** [comment] 2020-03-07 16:12
Thanks for reporting @tsabunkar. I am closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/38310

**Closed by moT01** 2020-03-07 16:12 UTC
Labels: scope: curriculum, status: needs investigation
