### ISSUE TITLE
New campers shouldn't be able to create a freeCodeCamp account using GitHub auth

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#14486] opened 2017-04-19 04:07 UTC
Currently campers can still create a freeCodeCamp account using GitHub and this is leading to a lot of support issues. We need to update our authentication code to prevent account creation using GitHub.

![](https://www.evernote.com/l/Ar8k-uQxaX5Af6APYfeI12AjKeGO_M4d4PUB/image.png)

**Comment by philipjc** [comment] 2017-04-19 17:59
Can you clarify this please? So you want it completely removed, or just for new campers? Thanks.

**Comment by augmt** [comment] 2017-04-23 15:28
@philipjc New campers shouldn't be able to create a freeCodeCamp account through GitHub. But existing campers who have linked their GitHub accounts should still be able to sign in with GitHub.

Do you want to tackle this? If not, I'll submit a PR.

**Comment by philipjc** [comment] 2017-04-23 15:42
If you have a solution go for it 🙂

**Comment by raisedadead** [comment] 2017-04-23 19:19
@augmt Thanks a lot for your interest.
This should go in after passwordless (#9660) has been integrated.

**Comment by raisedadead** [comment] 2017-04-24 20:07
Closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/10407

**Closed by raisedadead** 2017-04-24 20:07 UTC
Labels: help wanted
