### ISSUE TITLE
Incorrect description in Waypoint (asks to deleted tails, but code says delete bark)

### ISSUE THREAD

**Issue by legend911** [FreeCodeCamp/FreeCodeCamp#3965] opened 2015-10-28 21:16 UTC
Challenge [Waypoint: Delete Properties from a JavaScript Object](http://freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"],
  "bark": "bow-wow"
};

delete ourDog.bark;

var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"],
  "bark": "woof"
};

// Only change code below this line.
delete myDog.bark;


// Only change code above this line.

(function(z){return z;})(myDog);

```

**Comment by legend911** [comment] 2015-10-28 21:17
This is just a problem with the description. 

You stated, "Let's delete the "tails" property from myDog."

But Code says, "Delete the property "bark" from myDog."

**Comment by ltegman** [comment] 2015-10-28 21:27
Closing as a duplicate of #3960.

Please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Thanks and happy coding!

**Closed by ltegman** 2015-10-28 21:27 UTC
