### ISSUE TITLE
CORS error on Codepen for challenge [show-relationships-with-a-force-directed-graph] 

### ISSUE THREAD

**Issue by skusku** [FreeCodeCamp/FreeCodeCamp#7617] opened 2016-03-18 16:07 UTC
Challenge [Show Relationships with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Just opened the pen and it spits out a CORS error.

**Comment by ltegman** [comment] 2016-03-18 17:02
I can confirm this. I assume it's due to the example using http instead of https.

**Comment by kalunlee136** [comment] 2016-03-18 20:34
@Itergman Yeah, I tried changing the API request to https and it works fine.

**Comment by 3316** [comment] 2016-03-20 16:16
This is not me. Do not own a Mac. Use cell phone only

**Comment by raisedadead** [comment] 2016-03-21 20:11
@kalunlee136 It would be awesome if you could send in a PR!

**Comment by kalunlee136** [comment] 2016-03-21 20:30
@raisedadead i don't think i can fix the codepen problem, because the issue is that the example API request inside the pen uses HTTP (that's why if you open the pen the graph doesn't show up). I think we would need the owner of the pen to change it. 

Though I can work on changing the Hint URL from the FCC challenge so people don't copy and paste the wrong URL.

**Comment by raisedadead** [comment] 2016-03-21 20:52
@kalunlee136 The original Pen is by Free Code Camp (account under control of @QuincyLarson) so if you can create a Pen that has `https` within its code, then we could either clone it under the Free Code Camp account or use your pen.

Next thing though still would be to update the example links protocol to `https` in the challenge story as well!

**Comment by kalunlee136** [comment] 2016-03-21 20:58
@raisedadead ok, sounds good. I'll work on this.

**Comment by raisedadead** [comment] 2016-03-22 20:35
Refer #7700 for similar issues.

**Comment by mutantspore** [comment] 2016-03-22 20:53
Yes, as the original author of the this D3 exercise, I have changed my original to https:// and can confirm that it works fine. I can't alter the official FCC version though. @QuincyLarson  will have to do that.

Unfortunately with the phasing out of FCC News this is a dooooomed project anyway. :(

**Comment by raisedadead** [comment] 2016-03-23 02:25
@mutantspore Thanks for fixing the original pen.
Yup we are trying to look for a alternate data set! 
Refer #7082

**Comment by raisedadead** [comment] 2016-04-15 18:49
Closing as resolved.

**Closed by raisedadead** 2016-04-15 18:49 UTC
Labels: confirmed, help wanted
