### ISSUE TITLE
Submission Link Error with Data Analysis with Python projects

### ISSUE THREAD

**Issue by garynks** [freeCodeCamp/freeCodeCamp#42650] opened 2021-06-27 17:08 UTC
I've noticed that the Data Analysis with Python projects section does not check for correct tests. You could paste any link in the solution link text box of any project and it will consider it as a correct answer.

**Comment by ShaunSHamilton** [comment] 2021-06-27 17:27
Hello there,

Thank you, for taking the time to open this. This is not a bug, but the expected behaviour - Campers are expected to follow the Academic Honesty Policy with all curriculum content.

The main discussion for this was held here: https://github.com/freeCodeCamp/freeCodeCamp/issues/37185

As such, I am closing this issue 🙂

**Closed by ShaunSHamilton** 2021-06-27 17:27 UTC
Labels: status: waiting triage, type: bug
