### ISSUE TITLE
Passing challenge, solution link not being checked

### ISSUE THREAD

**Issue by Bruno-366** [freeCodeCamp/freeCodeCamp#43701] opened 2021-10-03 18:41 UTC
## Affected page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator

## Your code

Solution Link

```

https://google.com


```

## Expected behavior

Right now, as long as I submit a valid URL, and press "I've completed this challenge", then it will mark the challenge as completed.

## Screenshots

![www freecodecamp org_learn_data-analysis-with-python_data-analysis-with-python-projects_mean-variance-standard-deviation-calculator](https://user-images.githubusercontent.com/81762173/135767114-edba72f3-c959-4014-8f51-8a75eb52791a.png)

![www freecodecamp org_learn_data-analysis-with-python_data-analysis-with-python-projects_mean-variance-standard-deviation-calculator (1)](https://user-images.githubusercontent.com/81762173/135767120-ed0f38e4-91ab-40f9-8dce-e065d6f55e33.png)

## System

- Device: Desktop
- OS: Windows 10
- Browser: chrome

**Comment by gangov** [comment] 2021-10-03 19:18
I guess it's up to one's morals not to post links like that, but I also get your idea on the need for verification. 

As a quick proposal for that, I'd say that we can whitelist only a few code-sharing platforms like Codepen, or directly GitHub and GitLab. In the long run, we can probably make a something that is inbuilt into the platform.

Looking forward to hearing your solutions to that @Bruno-366

**Comment by ShaunSHamilton** [comment] 2021-10-03 19:44
Hello there,

Thank you, for taking the time to bring this up. This is not a bug, however. This is expected behaviour.

Campers are required to agree to an [Academic Honesty Policy](https://www.freecodecamp.org/settings#honest-policy), before claiming a certification. This means, to the best of their ability, they need to accomplish the given task(s). The Python projects come with built-in tests which are expected to be passed, before submission.

Also, a certification can be revoked, if the expected tasks have not been completed. This is a form of validation.

As such, I am going to close this issue.

**Closed by ShaunSHamilton** 2021-10-03 19:44 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
