### ISSUE TITLE
print() is executing the ctrl+p command. 

### ISSUE THREAD

**Issue by arthuragnar** [freeCodeCamp/freeCodeCamp#14965] opened 2017-05-20 13:36 UTC
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#
has an issue. 
My code:
```javascript
function reverseString(str) {
  **print("anythin");**
}
reverseString("hello");
```
Issue: The above code  is executing the ctrl+p command.
Or even if I am just typing  print(); anywhere is the text editor. it is reproducing the same error. I am attaching the screenshot
![image](https://cloud.githubusercontent.com/assets/10372078/26276089/0b962818-3d8e-11e7-894c-1fba369686f6.png)

**To reproduce the issue:**
Execute the  above code.  or just type print() in editor and execute it.

This issue is not limited to this problem only but it is  reproducible at any problem.

**Comment by texas2010** [comment] 2017-05-21 14:29
@arthuragnar, why are you use print?   i think javascript dont have print keyword.  more like you trying to use console.log()??

**Comment by texas2010** [comment] 2017-05-21 14:33
print() https://developer.mozilla.org/en-US/docs/Web/API/Window/print 

you need to use this code. https://developer.mozilla.org/en-US/docs/Web/API/Console/log

so there don't have an issue. since you use wrong code.  

if you need a help. Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by arthuragnar** [comment] 2017-05-21 15:19
Thanks. 
But this issue is not specific  to this program. It is related to the text editor. The text editor should not behave in such manner.

**Comment by texas2010** [comment] 2017-05-21 15:24
@arthuragnar why do you use print()?  but javascript dont use print() for print message.  you have to use console.log. it will print in dev tools.

there has challenge already told people about console.log.

**Comment by texas2010** [comment] 2017-05-21 15:27
i just test it.  more like it need to ignore print() in future?

**Comment by arthuragnar** [comment] 2017-05-21 16:22
I use python more frequently, that's why I accidentally wrote print();

**Comment by texas2010** [comment] 2017-05-21 16:33
@arthuragnar yeah. you are right. I didn't realize about someone would use print().

@freeCodeCamp/moderators Do we need to fix this issue as ignore print() code as when someone writes it in the code editor? thought?

**Comment by dhcodes** [comment] 2017-05-21 16:43
This seems like a deep edge case. I think bike shedding imho.

**Comment by systimotic** [comment] 2017-05-26 11:54
Hi @arthuragnar! Thank you for reporting this issue.

As you're coming from Python, I can understand why you used `print()`. However, as described in [the MDN page linked earlier](https://developer.mozilla.org/en-US/docs/Web/API/Window/print), opening the print dialog is the correct behaviour when the `print()` function is called in Javascript. Therefore, I believe your code does what it should do, and this is not a bug with freeCodeCamp.

As this is not a bug with freeCodeCamp, I'm closing this issue. Again, thank you for reporting this issue, bug reports help us make freeCodeCamp better.
Happy coding!

**Closed by systimotic** 2017-05-26 11:54 UTC
