### ISSUE TITLE
Nutrition Label 33

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49227] opened 2023-02-02 00:03 UTC
### Describe the Issue

The code below generates the confusing hint

> Your `p` element should have the text `Calories`.

The actual issue is that the `span` element is in the wrong place.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-33

### Your code

```html
    <div class="calories-info">
      <div class="left-container">
        <h2 class="bold small-text">Amount per serving</h2>
        <p>Calories</p>
        <span>230</span>
      </div>
    </div>
```

### Expected behavior

Clearer error message

### System

All

**Comment by depleur** [comment] 2023-02-02 04:19
I'm going to start working on this. Per my understanding, the span element is supposed to be under the .left-container class and not under the p element.

**Comment by Nirajn2311** [comment] 2023-02-02 04:28
That challenge needs another test to check whether the user has created a `span` element inside `.left-container` or not.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by depleur** [comment] 2023-02-02 04:31
Thanks for the labels Niraj. Yes, I think I can implement that.

**Comment by depleur** [comment] 2023-02-02 09:11
Do I only have to edit [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/afa7a5303dc1df647428deda687f632a7e61220a/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f5486b8fd4b71633f69b0.md)?

**Comment by Nirajn2311** [comment] 2023-02-02 10:33
Yes that's the file that has to updated

**Comment by anik-75** [comment] 2023-02-05 13:11
Is anyone working on this issue?

**Comment by SmogCoding** [comment] 2023-02-06 02:03
![image](https://user-images.githubusercontent.com/124175811/216865124-0b3ec0eb-256c-45a3-9358-9f6e70de7fed.png)
I have just tested it. What they want you to do is to be able to add the span after the .left-container. However, I want to know if this is an intended behaviour of the curriculum creators.

**Comment by jeremylt** [comment] 2023-02-06 02:05
Yes, that is the intended behavior. As I said above, the problem is that the error message doesn't help the user correct this particular coding issue.

**Comment by SmogCoding** [comment] 2023-02-06 02:08
Okay, so there might need to be an error message to tell the user. I'm sorry I misunderstood that. I will have a look now and try and create a test for this issue.

**Comment by SmogCoding** [comment] 2023-02-06 02:45
Is this the page where the tests are conducted? I have never contributed to open source, so this is new. However, I have a screenshot of which test might solve this issue.
![image](https://user-images.githubusercontent.com/124175811/216871672-be026fd0-fd89-4ced-851f-167ce001559a.png)

**Comment by SmogCoding** [comment] 2023-02-06 03:44
I am on the issue you now

**Comment by Kaushal-205** [comment] 2023-02-07 10:06
> I am on the issue now, @anik-75 can join in if you want. Or anyone else

I am also on this issue. but I don't understand actual problem

**Comment by npiyush97** [comment] 2023-02-07 12:14
@Kaushal-205  problem is even though p tag is correctly done error shows add p tag with calories. but should been for span tag.
I'm right ? @jeremylt

**Comment by balaji-sivasakthi** [comment] 2023-02-08 07:27
yes @npiyush97 we need to set the error message for span tag. if it is in wrong place and also we need to set the error message will be  **The `span` element is in the wrong place**.

**Comment by hbar1st** [comment] 2023-02-08 14:30
perhaps a better hint is:
` Your span element should have the text 230 and should be the last element in .calories-info.`

**Comment by balaji-sivasakthi** [comment] 2023-02-08 14:50
@hbar1st  yeah, it should be the right hint

**Comment by jeremylt** [comment] 2023-02-08 16:02
I think this is the issue:

---

You should have a new `span` element within your `.calories-info` element.
```js
assert(document.querySelector('.calories-info')?.querySelector('span'))
```
Your `p` element should come after your `.small-text` element.
```js
assert(document.querySelector('.small-text')?.nextElementSibling?.localName === 'p');
```
Your `p` element should have the text `Calories`.
```js
assert(document.querySelector('.left-container')?.lastElementChild?.innerText === 'Calories');
```
Your `span` element should come after your `.left-container` element.
```js
assert(document.querySelector('.left-container')?.nextElementSibling?.localName ==='span');
```

---

should be

---

You should have a new `span` element within your `.calories-info` element.
```js
assert(document.querySelector('.calories-info')?.querySelector('span'))
```
Your `p` element should come after your `.small-text` element.
```js
assert(document.querySelector('.small-text')?.nextElementSibling?.localName === 'p');
```
Your `span` element should come after your `.left-container` element.
```js
assert(document.querySelector('.left-container')?.nextElementSibling?.localName ==='span');
```
Your `p` element should have the text `Calories`.
```js
assert(document.querySelector('.left-container')?.lastElementChild?.innerText === 'Calories');

---

Checking for the location of the span *before* checking the contents of the p

**Comment by Vansh-Baghel** [comment] 2023-02-08 17:28
@jeremylt Hey I understood the issue, tested the issue as well, and there's no other problematic error message except this in this particular problem. Starting to work on fixing this.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:04
@jeremylt This issue is solved as per me. Raising a PR, do review it and let me know

**Comment by jeremylt** [comment] 2023-02-08 18:09
That's not the solution I recommended

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:15
`

> That's not the solution I recommended.
> 
> See #49299

What is happening in that issue? I didn't get it

**Comment by jeremylt** [comment] 2023-02-08 18:17
What's happening is nobody is reading the discussion in this issue, so I opened a PR for the fix myself.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:18
> That's not the solution I recommended.
> 
> See #49299

As per I thought, if the next element is not p , then it will reach `assert(document.querySelector('.small-text')?.nextElementSibling?.localName === 'p');` order first and if it is p, then it will reach next step which will check the innerText of the tag. Else in the next step, `assert(document.querySelector('.small-text')?.nextElementSibling?.innerText === 'Calories');` this could solve.
So if user tries to use any other element than p, it will be resolved from the above step.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:22
> What's happening is nobody is reading the discussion in this issue, so I opened a PR for the fix myself.

How does that change in order in that PR would fix this issue?

**Comment by jeremylt** [comment] 2023-02-08 18:23
The tests are executed **in order**.

**Comment by SmogCoding** [comment] 2023-02-08 18:25
Yeah, I noticed that the tests are run in order; however, if I put it correctly, it still doesn't show the error. It might be my code. However, I tried everything that made sense.

**Comment by jeremylt** [comment] 2023-02-08 18:27
Putting the correct solution won't generate an error, that's correct. The point of this issue is that one particular incorrect solution (the one given in the very first post) was giving a misleading hint, due to the order in which the tests were executed.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:31
I didnt really get the point of *the order*, like which order are we talking here? I am emphasizing on *the order* of the code logic written ie checking the innerText for p in the end after checking its perfect location.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:32
> Yeah, I noticed that the tests are run in order; however, if I put it correctly, it still doesn't show the error. It might be my code. However, I tried everything that made sense.

Could you explain wdym by **tests are run in order**?

**Comment by jeremylt** [comment] 2023-02-08 18:33
The learner sees the hint corresponding to the very first test case that fails.

Checking the location of both the span and p elements before checking their contents means we can check their contents however we like, making those tests less fragile.

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:40
> 

Ohhhh like checking the locations of span and p first and then checking the content is the approach we need to implement, right?

**Comment by Vansh-Baghel** [comment] 2023-02-08 18:49
@jeremylt  **Another bug**, The current logic checks the innerText of the last element of small-text class, which is not what we want right? 
We would also have to check if there is no other element inside that class or we could check the very next element's innerText the way I did in my commit.
![free2](https://user-images.githubusercontent.com/103327712/217623777-f45ad75a-36f4-4c42-b2ae-b2f531f30d82.png)

**Comment by Vansh-Baghel** [comment] 2023-02-08 19:00
> @jeremylt **Another bug**, The current logic checks the innerText of the last element of small-text class, which is not what we want right? We would also have to check if there is no other element inside that class or we could check the very next element's innerText the way I did in my commit. ![free2](https://user-images.githubusercontent.com/103327712/217623777-f45ad75a-36f4-4c42-b2ae-b2f531f30d82.png)

Let me write a logic for : If the next element is not p, then give hint "Only `p` elements could be used under `.small-text` class" 
And same must be for span

Your thoughts? @jeremylt

**Comment by Vansh-Baghel** [comment] 2023-02-08 19:17
I changed the order as required, and added another piece of code for the new bug. Hope its worthful.

**Comment by jeremylt** [comment] 2023-02-08 19:46
This really wasn't supposed to be this  complicated. My PR should have all the changes that are needed.

**Comment by Vansh-Baghel** [comment] 2023-02-08 19:54
@jeremylt you will face that issue.
Let me keep it simple: 
1. We are checking the content of the **last element** under a class.
2. If the last element is not p or span, it will throw the error for sure.

**Comment by jeremylt** [comment] 2023-02-08 19:55
I don't know what you are talking about. My PR fixes the problem brought up in this issue.

**Comment by Vansh-Baghel** [comment] 2023-02-08 19:56
> @jeremylt **Another bug**, The current logic checks the innerText of the last element of small-text class, which is not what we want right? We would also have to check if there is no other element inside that class or we could check the very next element's innerText the way I did in my commit. ![free2](https://user-images.githubusercontent.com/103327712/217623777-f45ad75a-36f4-4c42-b2ae-b2f531f30d82.png)

Did you see this?

**Comment by jeremylt** [comment] 2023-02-08 19:57
Did you read my PR?

**Comment by Vansh-Baghel** [comment] 2023-02-08 20:04
> Did you read my PR?

Yess, just few new changes made by u. With that code, user would be able to playaround with other html tags aswell. 
If that is not the concern, then go for it 👍

**Comment by BalanaguYashwanth** [comment] 2023-02-09 01:44
Is this issue open ?

**Comment by Sboonny** [comment] 2023-02-09 05:23
Is there a scenario in which a camper decide, that they need another `div` element below the `p` element?

> >  **Another bug**, The current logic checks the innerText of the last element of small-text class, which is not what we want right? We would also have to check if there is no other element inside that class or we could check the very next element's innerText the way I did in my commit. ![free2](https://user-images.githubusercontent.com/103327712/217623777-f45ad75a-36f4-4c42-b2ae-b2f531f30d82.png)
> 
> Did you see this?


If you think this is possible, please open a 2nd issue about this and the forum post which this did happen.

**Comment by Sboonny** [comment] 2023-02-09 05:24
> Is this issue open ?

Because of how this issue has been handle so far, I am removing the label for contribution and accepting this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/49299

**Comment by Vansh-Baghel** [comment] 2023-02-09 05:46
> Is there a scenario in which a camper decide, that they need another `div` element below the `p` element?
> 
> > > **Another bug**, The current logic checks the innerText of the last element of small-text class, which is not what we want right? We would also have to check if there is no other element inside that class or we could check the very next element's innerText the way I did in my commit. ![free2](https://user-images.githubusercontent.com/103327712/217623777-f45ad75a-36f4-4c42-b2ae-b2f531f30d82.png)
> > 
> > 
> > Did you see this?
> 
> If you think this is possible, please open a 2nd issue about this and the forum post which this did happen.

Hey @Sboonny, after I pushed my first commit, I changed the lastElementChild with the nextElementSibling which is also seen in the #49299 PR. So that bug won't happen, but the user will be able to add any other element below the p and span tags. 
If you don't want that user must add other elements than p and span tag, you could see my PR or pin me.

**Comment by Sboonny** [comment] 2023-02-09 07:18
Yes, I personally want the test to be lenient. There are elderly, people in high schools and non-native speaker, who don't need a strict test, but an explanation of concepts. Try to delete every code on the challenge, and only type the solution, we allow this to pass and this is by design.

![image](https://user-images.githubusercontent.com/88248797/217743800-e4c4d4d1-8681-4f97-8551-69befccfedfc.png)


TD;LR, we don't care if someone types 100 `div` elements testing something out, as long as they typed the solution of the concept correctly

**Comment by Vansh-Baghel** [comment] 2023-02-09 07:21
> 

Got it ✅

**Closed** 2023-02-09 11:45 UTC
Labels: type: bug, scope: curriculum

**Comment by bonheur832** [comment] 2023-09-17 12:13
> ![image](https://user-images.githubusercontent.com/124175811/216865124-0b3ec0eb-256c-45a3-9358-9f6e70de7fed.png) I have just tested it. What they want you to do is to be able to add the span after the .left-container. However, I want to know if this is the intended behaviour of the curriculum creators' implementation.

thank you alot! i had been stacked!

**Comment by SAI7075005348** [comment] 2023-09-17 17:18
<div class="calories-info">
      <div class="left-container">
        <h2 class="bold small-text">Amount per serving</h2>
        <p>Calories</p>
      </div>
      <span>230</span>
    </div>
![44444444444444](https://github.com/freeCodeCamp/freeCodeCamp/assets/130823472/51d6bc8e-e8e4-43c1-8c73-92fa0b124d96)
