### ISSUE TITLE
Page get hanged when writing the second $ sign

### ISSUE THREAD

**Issue by arsho** [FreeCodeCamp/FreeCodeCamp#2019] opened 2015-08-18 05:46 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. When I try to code on the selected area of problem "Bring your JavaScript Slot Machine to Life" browser get stuck while writing the second $. But if I copy paste the code rather than typing, it works well.

**Comment by jbmartinez** [comment] 2015-08-18 12:35
Duplicate of #1960

**Closed** 2015-08-25 16:29 UTC
