### ISSUE TITLE
Repl backend starter projects run command broken

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#43004] opened 2021-07-25 11:44 UTC
Edit: Seems to be back to normal again.

Edit2: I'm still getting some odd behavior. This might only affect projects started when the issue was there.

If I run the project with the server.js open it fails, if I run it with the .replit file open it works. If I switch back to server.js it still works?

https://replit.com/@lasjorg/boilerplate-mongomongoose#server.js

https://replit.com/@lasjorg/boilerplate-mongomongoose#.replit

![BP1](https://user-images.githubusercontent.com/28780271/126899390-d6038ab4-c9d5-459a-b9b1-ecb0cfcc07f1.png)
![BP2](https://user-images.githubusercontent.com/28780271/126899391-8e223d07-4b4c-4de5-8762-e0298d9e049c.png)

It is kind of hard to test because of how repl opens repls that aren't yours and I'm not sure if forking might fix the issue (so you can't reproduce it).

---

The projects I have tested with so far all seem to be broken. It tries to run `index.js` even with the start script configured to run `server.js`. If I rename `server.js` to `index.js` it runs, if I edit the `.replit` file run command to `run = "npm start server"` it also works.

Not sure if something changed or if it's just a hiccup. But right now, all the starter projects I have tested are broken.

Forum posts (up to 4 now in two days):

https://forum.freecodecamp.org/t/error-enoent-no-such-file-or-directory-open-home-runner-boilerplate-mongomongoose-index-js/470768

https://forum.freecodecamp.org/t/replit-terminal-shows-a-non-exciting-error-file/470821

https://forum.freecodecamp.org/t/replit-boilerplate-project-error/471050

https://forum.freecodecamp.org/t/advanced-node-and-express-how-to-use-passport-strategies-error-enoent/471045

**Comment by gikf** [comment] 2021-07-25 12:00
No issues with it for me, I've tried just these two:
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice
https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose

**Comment by lasjorg** [comment] 2021-07-25 12:20
Well, that didn't last long. It works again for me as well. Must have just been some temporary issue. It was definitely broken before in all the projects I tested.

**Comment by ShaunSHamilton** [comment] 2021-07-25 13:26
@lasjorg I have experienced this issue before, and mentioned it to the Replit team. This was the beginning of last year.

The only fix I have found is to re-clone the boilerplate (create a new REPL), or rename the `server.js` file to `index.js`. Unfortunately, this does not appear to be something we can reliably control.

I suggest closing this issue, as, until discovered otherwise, there is nothing known we can do (_short of a migration_)

**Comment by lasjorg** [comment] 2021-07-26 21:15
@ShaunSHamilton The behavior is not something I have seen before, or at least not to the extent we are seeing it right now. What was the reply back from the Replit team when reporting this? Did it get escalated or just dropped? It seems like an obvious bug on their end that needs to be fixed.

Not really sure I see how closing this issue is helpful. At least people can find the issue and we can track any progress.

**Comment by ShaunSHamilton** [comment] 2021-07-26 21:56
> Did it get escalated or just dropped?

As far as I am aware, it is still an open ticket on their end. I have gotten replies concerning a more recent ticket, but not this.

**Comment by gikf** [comment] 2021-07-27 03:39
From my understanding it still should be possible to run project manually (without using the RUN button) with:
```
npm install
npm start
```
But that's less convenient for beginners.

**Comment by ShaunSHamilton** [comment] 2021-09-01 16:19
I am closing this issue, as the issue is not unique to freeCodeCamp projects/boilerplates, and is not easily reproducible.

If more information comes forth, please request this issue be reopened. Thank you.

**Closed by ShaunSHamilton** 2021-09-01 16:19 UTC
Labels: type: bug, status: wontfix, scope: curriculum, scope: projects-backend
