### ISSUE TITLE
Challenges are not always reloaded automatically

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35566] opened 2019-03-11 13:14 UTC
**Describe the bug**
In development the curriculum files are watched.  Any changes to them should should cause the browser to reload with those changes.  The problem is that this does not always happen, only sometimes.

**To Reproduce**

1. Open a challenge page on a local site.  E.g. http://localhost:8000/learn/responsive-web-design/basic-css/use-a-css-class-to-style-an-element/
2. Edit and save the corresponding markdown file.  E.g. curriculum/challenges/english/01-responsive-web-design/basic-css/use-a-css-class-to-style-an-element.english.md
3. The page may not update and/or not reflect the changes when reloaded.

**Expected behavior**
In step 3, the browser should reload, mirroring the changed markdown.

**Screenshots**
In the first half of the gif the page fails to update.  Then, after a second change, it works as expected.
![Reload](https://user-images.githubusercontent.com/15801806/54126001-cbba7d80-4406-11e9-9cd1-7edf039ad2b5.gif)

This is the console output from during this process:
![ReloadingConsole](https://user-images.githubusercontent.com/15801806/54126194-484d5c00-4407-11e9-9c14-4ff3413f2fc6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 72.0.3626.119 (Official Build) (64-bit)

**Comment by madurachanna** [comment] 2019-04-17 04:52
not for me

**Comment by madurachanna** [comment] 2019-04-17 04:53
not for me

**Comment by raisedadead** [comment] 2019-07-19 10:47
Is this still an issue?

**Comment by ojeytonwilliams** [comment] 2019-07-19 14:43
I've not been working on the challenges much recently, but it seems much better now chokidar's using polling.

One problem remains: it doesn't update the challenge's tests until you hit reload.  So, yeah, it's minor, but there is still an issue.

**Comment by prolland006** [comment] 2020-11-13 14:54
I just tried to reproduce the problem on firefox and Chromium and it is working. Unable to reproduce the problem for me it is corrected and you can close it. 
I tried to set several times the .md and the web browser is reloaded each time.

**Comment by moT01** [comment] 2021-02-02 14:49
This looks to be fixed. I am going to close it. If I'm wrong, let me know and we can reopen it. Thanks and happy coding 🎉

**Closed by moT01** 2021-02-02 14:49 UTC
Labels: help wanted, scope: tools/scripts
