### ISSUE TITLE
rgb challenge

### ISSUE THREAD

**Issue by robert1108** [FreeCodeCamp/FreeCodeCamp#9709] opened 2016-07-13 12:42 UTC
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%20%0A%20%20%20%20color%3A%20rgb(225%2C0%2C0)%20%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3Argb(218%2C112%2C214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3Argb(160%2C82%2C45)%20%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3Argb(0%2C0%2C225)%20%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text { 
    color: rgb(225,0,0) ;
  }
  .orchid-text {
    color:rgb(218,112,214);
  }
  .sienna-text {
    color:rgb(160,82,45) ;
  }
  .blue-text {
    color:rgb(0,0,225) ;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by BKinahan** [comment] 2016-07-13 13:11
Funny, you have the same code as in the recent issue #9659 (with the same error)

Check your rgb values again.

Please seek code-writing assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Issues are for reporting bugs with the challenges or website.

Happy coding!

**Comment by erictleung** [comment] 2016-07-13 15:14
@robert1108 what @BKinahan suggest is correct. I would check your RGB values again.

@BKinahan I've seen this kind of "error" multiple times now. I'm sure you are fielding more questions in Gitter so do have a guess on where this "error" may come from?

**Comment by BKinahan** [comment] 2016-07-13 15:33
@erictleung I haven't seen this one in Gitter, but I usually spend time in HelpJavaScript rather than Help so I see fewer HTML questions.

@robert1108 Take a closer look. It might help to note that the largest value for an RGB color is 255, for example white is `rgb(255,255,255)`. Anyway, [Help Chat](https://gitter.im/FreeCodeCamp/Help) :D

**Comment by raisedadead** [comment] 2016-07-13 15:34
Closing as not a bug. @BKinahan thanks.
@robert1108 please confirm issues in the chat before reporting.

**Closed by raisedadead** 2016-07-13 15:34 UTC

**Comment by robert1108** [comment] 2016-07-13 15:38
I will next time .thanks 
I am new in here.

**Comment by robert1108** [comment] 2016-07-13 15:41
It is working now.

**Comment by gatewayJay** [comment] 2016-08-23 22:01
on lesson use RGB to mix colors. It's the last lesson on HTML5 and CSS. I put the code in and ran the test. Example: Give your h1 element with the text : I am red! the color red. I did that and it says correct. But when it says use RGB for the color red it still has an X on the box. Here is my code: 
<style>
.red-text {
color: rgb(255,0,0)
}
.orchid-text {
color: rgb(218,112,214)
}
.sienna-text {
color: rgb(160,82,45)
}
.blue-text {
color: rgb(0,0,255)
}
</style>
<h1 class="red-text">I am red!</h1>
<h1 class="orchid-text">I am orchid!</h1>
<h1 class="sienna-text">I am sienna!</h1>
<h1 class="blue-text">I am blue!</h1>

**Comment by gatewayJay** [comment] 2016-08-23 22:06
Ok just fixed it. thanks

**Comment by texas2010** [comment] 2016-08-23 22:07
@gatewayJay, you could go to the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help. 
GitHub Issues are for reporting bugs on the website only.


Happy Coding!
