### ISSUE TITLE
Javascript displayed but shouldn't - Above the exercise instructions .

### ISSUE THREAD

**Issue by millinet** [FreeCodeCamp/FreeCodeCamp#3319] opened 2015-09-15 09:14 UTC
No specific code to share, only the view that seems a bit weird - No input, first time the view is displayed. Text in light gray shouldn't be displayed?

![waypoint comment your javascript code free code camp](https://cloud.githubusercontent.com/assets/1710197/9872602/b38628e8-5b9a-11e5-91f9-c19069af251e.png)
Challenge [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

```

**Comment by millinet** [comment] 2015-09-15 09:21
The exercise is executed with no issue, but I keep having the "checking" rules on following exercises as well.
![waypoint declare javascript variables free code camp](https://cloud.githubusercontent.com/assets/1710197/9872783/e29a9cd0-5b9b-11e5-9b66-0774aa216785.png)

**Comment by ahstro** [comment] 2015-09-15 14:22
Closeing as a duplicate of, #2462, #2376, #2373, #2341, #2314, #2231, #2182, #2153, and probably a few more.
Please read the [contribution guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

**Closed by ahstro** 2015-09-15 14:22 UTC
