### ISSUE TITLE
The emulator is showing multiple renderings of the code

### ISSUE THREAD

**Issue by supercuteboy** [FreeCodeCamp/FreeCodeCamp#2867] opened 2015-08-30 03:25 UTC
For some reason the emulator keeps rendering multiple instances once I start writing code.

![multiple_renderings](https://cloud.githubusercontent.com/assets/5331095/9565567/a35d7904-4f00-11e5-886d-23c0855da300.jpg)

**Comment by BerkeleyTrue** [comment] 2015-08-30 06:01
Closing as duplicate of #2706 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-30 06:01 UTC
