### ISSUE TITLE
Quoting Strings with Single Quotes - Buggy, wont pass

### ISSUE THREAD

**Issue by ajdw** [FreeCodeCamp/FreeCodeCamp#10659] opened 2016-09-10 02:48 UTC
Challenge [quoting-strings-with-single-quotes](https://www.freecodecamp.com/en/challenges/basic-javascript/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';



```

> You should have two single quotes ' and four double quotes "

Am I just counting this wrong, or..?

**Comment by dhcodes** [comment] 2016-09-10 02:50
@ajdw Thanks for the issue. Closing as duplicate of #10258

**Closed by dhcodes** 2016-09-10 02:50 UTC

**Comment by AhmedTunuLashku** [comment] 2016-09-10 08:40
+1
