### ISSUE TITLE
the page freeze

### ISSUE THREAD

**Issue by negrolio** [FreeCodeCamp/FreeCodeCamp#2447] opened 2015-08-21 18:57 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![crashpage](https://cloud.githubusercontent.com/assets/7199377/9416403/d5c024a0-481b-11e5-9773-22755d583edc.png)

Hi, I started to do the exercise, only I could write $($) and the page freeze, then if i reload the page still be freezing. After a while, the computer start to work hard and then the page show broke it

**Comment by calskin** [comment] 2015-08-21 19:26
Same issue.

**Comment by nmwallace** [comment] 2015-08-21 19:40
Same issue here. 

Side note: I don't understand why you are using jQuery in a test for core javascript. Wouldn't it be more appropriate to teach the student how to manipulate the dom without it?

**Comment by jbmartinez** [comment] 2015-08-21 21:26
Duplicate of #1960. See #2286

**Closed** 2015-08-21 21:58 UTC
