### ISSUE TITLE
no semi colon after border radius = completion

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#860] opened 2015-06-08 15:34 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius has an issue. Please describe how to reproduce it, and include links to screen shots if 
![screenshot 5](https://cloud.githubusercontent.com/assets/12790960/8038584/50ca7756-0dd2-11e5-905d-25232b5e4d47.png)
possible.

**Comment by BerkeleyTrue** [comment] 2015-06-08 19:06
duplicate of #865

**Closed by BerkeleyTrue** 2015-06-08 19:06 UTC
