### ISSUE TITLE
target5 clone

### ISSUE THREAD

**Issue by sigursiguros** [FreeCodeCamp/FreeCodeCamp#6404] opened 2016-01-24 04:22 UTC
This clone seems to be cloning two target5 elements to the left well instead of one.
    $("#target5").clone().appendTo("#left-well");

**Comment by ltegman** [comment] 2016-01-24 04:27
Closing as a duplicate of #5072. Thanks and happy coding!

**Closed by ltegman** 2016-01-24 04:27 UTC
