### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by cdandro** [FreeCodeCamp/FreeCodeCamp#7377] opened 2016-03-03 14:36 UTC
#### Issue Description
Issue happens when logging in via email address. (only way I can login), I get a red error telling me there was a problem and the green success message telling me that I've logged in. After this everything seems to be working fine as I have been able to go through various areas without a problem.

#### Steps To Reproduce
Login using an email address, I happen to be using a gmail address.

#### Browser Information
Chrome Version 48.0.2564.116 m
Windows 7 Ent. Edition

![login_error](https://cloud.githubusercontent.com/assets/6656333/13497329/c25f5c50-e122-11e5-9684-0c2117daaab2.jpg)

**Comment by techtolentino** [comment] 2016-03-03 15:19
This is happening to me as well, every time I log in via Github. However, I think, as someone pointed out in the [FCC/Help](https://gitter.im/FreeCodeCamp/Help) Chat, it *might* be due to the FCC App trying to redirect you to your current challenge. However, it might throw an error toast because the cookies have expired?


One thing I tried, to test this:

- Auth in via Github
- Red error toast appears (I can close it and move on)
- Log Out
- Log back in again
- No red error toast, *and* I was redirected to my current challenge

**Comment by cdandro** [comment] 2016-03-03 15:36
I just tried logging in and it did not present the error. Also this time it did go to my current challenge. I logged out, back in via GitHub, and did not receive the error. Logged out and back in via email, no error. Each time I logged in it did go to current challenge.

When I received the red error I do not know if I had a current challenge (I don't know the last thing I was on). The error had been presenting for the past few days and over the last few days I was completing various items. 59 items completed on 2/29, 6 items completed on 3/1, and I updated a project on 3/2. Yesterday afternoon, after I took the attached screenshot, I was going back through Basic Algorithms, which would of reset my current challenge back to one of those.

**Comment by ltegman** [comment] 2016-03-03 18:54
@cdandro Hmm, I'm not personally able to repro this one. If you (or anyone else) sees this again could you please take a look at your browser console and take a screenshot if there are any error messages?

**Comment by cdandro** [comment] 2016-03-03 19:09
I just reproduced it a few times. I signed out, closed all Chrome windows, and relaunched Chrome. Opened the console, drove to FCC, signed in and received the error. My last worked on item was loading to the a incomplete project (Build a Personal Portfolio Webpage).

(ignore the imgur 404s, that is a firewall issue on myside)

![image](https://cloud.githubusercontent.com/assets/6656333/13505788/c4031a12-e148-11e5-9a3b-e4aa4076f5cb.png)

 I switched to a previously completed task, re completed it (ctrl-enter), and on the pop up moved to the next task (ctrl-enter again). Once that page was done loading, I signed out. Tried again and no error.

**Comment by ltegman** [comment] 2016-03-03 19:15
@cdandro Thanks for doing that. Unfortunately it looks like no errors related to this are getting printed on your end... We'll look into it and see if we can get to the bottom of it. Sorry for the inconvenience!

**Comment by techtolentino** [comment] 2016-03-04 01:17
Got the error toast again, but the console was clear.

- hit the FCC URL (first time logging in from my home Mac, all day)
- auth'd with Github
- presented with error toast
- **not** redirected to current challenge
- remained on `/map`

<img width="1440" alt="screen shot 2016-03-03 at 7 16 18 pm" src="https://cloud.githubusercontent.com/assets/6276074/13515134/7ba6706c-e174-11e5-86c2-013624a3ec23.png">

**Comment by cdandro** [comment] 2016-03-04 01:29
I was just able to reproduce the issue on my mac at home using chrome (Version 48.0.2564.116 (64-bit)).

**Comment by Em-Ant** [comment] 2016-03-07 00:50
![s](https://cloud.githubusercontent.com/assets/12955734/13558508/9b9a63c6-e406-11e5-8d8d-118268582e50.jpg)

I'm experiencing this too (several times).
Firefox 44.0.2 on Xubuntu 14.04. Logging in with github.

**Comment by sludge256** [comment] 2016-03-13 08:19
From what I've observed it happens when there is no `currentChalalengeId` cookie. In the past, this would redirect you to the first challenge, but it appears that this no longer happens.

**Comment by raisedadead** [comment] 2016-03-13 08:21
Confirmed this happens.

Another use case for `Oops! Something went wrong. Please try again later error`.
Steps:
1. Logout if you already are logged in.
2. Go to `freecodecamp.com\map`
3. Login
4. Go to a new tab and visit `freecodecamp.com` to get the error.

**Comment by benmcmahon100** [comment] 2016-04-05 21:39
I'll try to take a look at this!

**Comment by sic-f** [comment] 2016-04-06 10:21
Can't login as well using my Github account. Time is being wasted not being able to continue on with the course lol. Hurry up peeps I need to be great at Javascript already. Haha. :p

**Comment by heldersepu** [comment] 2016-06-14 22:06
Had same issue "Can't login as well using my Github account" ended up using the email option and then linking with  github

**Comment by benmcmahon100** [comment] 2016-06-15 14:05
@BerkeleyTrue any ideas on this?

**Comment by brandenbyers** [comment] 2016-07-18 06:32
I'm experiencing a similar "Oops! Something went wrong. Please try again later" when attempting to login via Github. I can't log in and don't have an email login connected to my account (that I am aware of).

Granted, I haven't logged in for over a year, so I may be lost in some kind of limbo (https://www.freecodecamp.com/brandenbyers) because I use to log in via Twitter.

**Comment by BerkeleyTrue** [comment] 2016-07-18 18:01
@brandenbyers Please send a support email to team@freecodecamp.com

I believe this issue was resolved a while back.

Happy Coding

**Closed by BerkeleyTrue** 2016-07-18 18:01 UTC
Labels: bug, confirmed
