### ISSUE TITLE
 [BETA] Trouble to make FCC beta challenge work/loading 

### ISSUE THREAD

**Issue by pocahontas123** [freeCodeCamp/freeCodeCamp#16212] opened 2017-12-18 16:53 UTC
Hi, every now and then , i have a terrible bug on FCC beta challenge.
When i start my journey, some time on the FCC challenge map, nothing is loading and i got the message “Some thing went work” every time i click on the left nav links.
It’s like some thing is not loading because when it work, the left links come from lowercase to uppercase.
But when it doesn’t work it stay in lowercase.
I tried on firefox/chrome. I did the CTRL+F5 on firefox and the equivalent CTRL+SHIFT+SUPPR on Chrome.
I tried ccleaner and restarting my browsers…

On firefox i have ghostery && ublock origin. On chrome i have many thing running like adblock / minerblock /no coin /privacy badger…

Finaly it always end up working but like 15-20 minutes after i tried to work :confused:

edit: some thing else i want to speak about.
Every time i decide to go back on a challenge i just finished. FCC doesn’t work anymore and give me a “something went wrong”. I can’t validate old and new challenges.
I have to CTRL+SHIFT+Suppr / clear code to make it work again.

**Comment by raisedadead** [comment] 2017-12-19 17:54
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/15972

**Closed by raisedadead** 2017-12-19 17:54 UTC
