### ISSUE TITLE
Comments in translated curriculum break challenge tests

### ISSUE THREAD

**Issue by jsdisco** [freeCodeCamp/freeCodeCamp#42890] opened 2021-07-16 07:44 UTC
The challenge asks to replace an if/else statement with a switch, the tests fail because the comment that the editor is prepopulated with contains the string "if".

**Affected page**

https://www.freecodecamp.org/italian/learn/javascript-algorithms-and-data-structures/basic-javascript/replacing-if-else-chains-with-switch

```
function chainToSwitch(val) {
  var answer = "";

  // Modifica il codice solo sopra questa riga
switch (val) {
  case "bob": answer= "Marley"; break;
  case 42: answer= "The Answer";break;
  case 1: answer= "There is no #1";break;
  case 99: answer= "Missed me by this much!";break;
  case 7: answer= "Ate Nine";break;
}

  // Modifica il codice solo sopra questa riga
  return answer;
}

chainToSwitch(7);

```

**Expected behavior**

The code above should pass, but doesn't (unless the comments are removed).

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Comment by raisedadead** [comment] 2021-07-16 08:19
This seems the challenge tests are not happy with the translated comment for some reason. Removing it as mentioned here seems to work: https://forum.freecodecamp.org/t/469535

Any ideas @freeCodeCamp/dev-team?

**Comment by ShaunSHamilton** [comment] 2021-07-16 08:33
Last I checked, we fixed the bugs with removing comments. So, we should be able to just add this helper to the tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/curriculum-helpers.ts#L10

**Comment by ojeytonwilliams** [comment] 2021-07-16 08:34
We did, yeah, but for some reason the comments are not automatically getting removed here.  I think they should be.

**Comment by ShaunSHamilton** [comment] 2021-07-16 09:02
Only the last comment is being removed:
```js
function chainToSwitch(val) {
  var answer = "";
  // Modifica il codice solo sotto questa riga

  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7) {
    answer = "Ate Nine";
  }

  
  return answer;
}

chainToSwitch(7);
console.log(code);
```

Bizarrely, a comment is not removed, if it appears immediately after an empty string.

**Comment by ojeytonwilliams** [comment] 2021-07-16 09:19
Yeah, there's definitely a problem with `strip-comments`.  It's not working in this case.

**Comment by ojeytonwilliams** [comment] 2021-07-16 09:53
This should be fixed by https://github.com/freeCodeCamp/strip-comments/pull/13

**Comment by ieahleen** [comment] 2021-07-19 13:01
Other challenge with same issue

https://www.freecodecamp.org/italian/learn/javascript-algorithms-and-data-structures/basic-javascript/introducing-else-statements

(reported here https://forum.freecodecamp.org/t/i-need-help-with-that-test/469960)

**Comment by Sembauke** [comment] 2021-07-25 12:42
@ieahleen Would you like to try again to see if the issue is still valid?

**Comment by ieahleen** [comment] 2021-07-25 15:28
it works, closing the issue

**Closed by ieahleen** 2021-07-25 15:28 UTC
Labels: help wanted, scope: curriculum, type: bug
