### ISSUE TITLE
Not detecting colour in code

### ISSUE THREAD

**Issue by Nuthi-Sriram** [freeCodeCamp/freeCodeCamp#35011] opened 2019-01-31 14:41 UTC
**Describe your problem and how to reproduce it:**

1. Attempt CSS challenge "Change the Color of Text"

2. `<h2 style="color: red;">CatPhotoApp</h2>`

3. Colour changes, but the test doesn't detect it.

**Add a Link to the page with the problem:**

[Basic CSS: Change the Color of Text](https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Ubuntu 18.10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/46497115/52061820-3caf7f80-2595-11e9-9892-089343d13031.png)

**Comment by raisedadead** [comment] 2019-01-31 17:02
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/35012

**Comment by raisedadead** [comment] 2019-01-31 17:03
Sorry my bad. The other issue is different. The issue title threw me off

**Comment by raisedadead** [comment] 2019-01-31 17:11
Could not reproduce. 

Can you share the entire editor code in here? You can format them with:

` ``` `
`<Your code here>`
` ``` `

Thanks.

**Comment by Nuthi-Sriram** [comment] 2019-02-03 17:19
[image: image.png]

**Comment by aravindvnair99** [comment] 2019-02-04 05:00
> Could not reproduce.
> 
> Can you share the entire editor code in here? You can format them with:
> 
> `` ``` ``
> `<Your code here>`
> `` ``` ``
> 
> Thanks.

@raisedadead I too was facing the same issue until last night. But looks like it's been fixed now.

**Comment by raisedadead** [comment] 2019-02-04 05:52
Thanks @aravindvnair99 I am going to close this. Please reach out to our support [Forum](https://forum.freecodecamp.com) in case you get this again. They will be able to help in debugging issue better

**Closed by raisedadead** 2019-02-04 05:52 UTC
Labels: status: blocked
