### ISSUE TITLE
clicking outside of search results should collapse search results

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17267] opened 2018-05-29 19:53 UTC
![responsive_web_design_projects___freecodecamp](https://user-images.githubusercontent.com/985197/40681928-15dce152-6350-11e8-81e0-7ce6bfecd71a.png)

**Comment by TomerPacific** [comment] 2018-11-11 19:45
@jonathan-grah ,
is this still relevant? I would like to fix it.

**Comment by TomerPacific** [comment] 2018-11-13 17:46
@jonathan-grah ,
I'm on it.

**Comment by QuincyLarson** [comment] 2018-12-30 03:01
@TomerPacific Thanks! If you have time to get your local dev environment working, and want to tackle this, please let us know here on this GitHub issue.

I've assigned the "Help Wanted" label so this is open to anyone interested in tackling it.

**Comment by kanpeki** [comment] 2019-01-14 21:19
@jonathan-grah Hi, I would like to take a look at this. I've managed to set up the env, but I have a question regarding the expected behaviour: should the search bar clear when clicking outside the search results,  besides the hits window closing?

**Comment by jonathan-grah** [comment] 2019-01-16 15:04
@kanpeki, no I don't think we should clear the search bar, let's keep it as it is for now 👍 Thanks for your help, let me know if you need any help 😄

**Comment by QuincyLarson** [comment] 2019-01-24 13:20
@kanpeki I agree with @jonathan-grah - when a user clicks outside of the results, we should should just close the search bar dropdown and leave their current query string as is in there.

**Comment by hilliarj** [comment] 2019-02-09 21:11
@kanpeki Are you still working on this? I would like to try to see if I could fix this as well.

**Comment by thesidbatra** [comment] 2019-04-01 06:14
@Bouncey https://github.com/freeCodeCamp/search-assets/pull/11 can you update the semantic version of `search-assets` and publish the module? because these latest changes can't be seen

**Comment by jragard** [comment] 2019-06-24 13:23
I can't reproduce the persistent dropdown menu in my local environment (just got the docker build up and running yesterday), but I can see that it still won't go away on the live site.

**Comment by danyalasif** [comment] 2019-08-20 08:29
@jragard Tested it on gitpod local environment, works as intended. Still does not work on live site. 

The search width is too wide too, so it's not working responsively either.

![image](https://user-images.githubusercontent.com/7072946/63331144-7cca2a00-c34e-11e9-8414-26fc0c9ffe45.png)

**Comment by ahmadabdolsaheb** [comment] 2019-08-20 09:13
this issue has been resolved in the new site. thank you all for reporting and contributing to resolve this issue.

**Closed by ahmadabdolsaheb** 2019-08-20 09:13 UTC
Labels: help wanted
