### ISSUE TITLE
Improve Accessibility of Audio Content with the audio Element

### ISSUE THREAD

**Issue by Myst** [freeCodeCamp/freeCodeCamp#17623] opened 2018-06-18 18:34 UTC
#### Describe your problem and - if possible - how to reproduce it
It asks you to close audio element, even though if you closed it. This only happens if you add an "id" to the audio tag. If you dont add the "id" tag it runs without any problem.

Not Running code:
```
<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    <audio id="test" controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" />
    </audio>   
  </main>
</body>
```
Running Code:
```
<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    <audio controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" />
    </audio>   
  </main>
</body>
```
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.87
* Operating System: Windows 7

#### If possible, add a screenshot here
Code with "id" not running
![image](https://user-images.githubusercontent.com/6627480/41554959-e80f420e-72fb-11e8-9f6b-63f194bc6f1a.png)

Code without "id" running
![image](https://user-images.githubusercontent.com/6627480/41555012-0a92c5ee-72fc-11e8-9edd-d4ae47e6a082.png)

**Comment by Nirajn2311** [comment] 2018-06-18 19:03
Duplicate of #17577

**Comment by Myst** [comment] 2018-06-19 16:32
@Nirajn2311 I know, but you should see I found the error, is not wrong to add an id, so that's a bug and should be fixed

**Comment by Nirajn2311** [comment] 2018-06-19 16:36
Yeah I get it, but it is more organised and easier to solve issues if there was only one of each type and duplicates confuse people.
I think someone is already working on it.

**Closed** 2018-06-29 19:31 UTC
