### ISSUE TITLE
Not recognising correct answer

### ISSUE THREAD

**Issue by javathehut** [freeCodeCamp/freeCodeCamp#13173] opened 2017-02-05 22:47 UTC
Challenge [adjust-the-width-of-an-element-using-the-width-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  h4 {
    text-align: center;
  }
  p {
    text-align: justify;
  }
  .links {
    margin-right: 20px;
    text-align: left;
  }
  .fullCard {
  

>   width: 245px; <---- This is what was required, and what I did, but it wasn't accepted as correct. 

    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment] 2017-02-05 22:53
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12687. Happy coding!

**Closed by erictleung** 2017-02-05 22:53 UTC
