### ISSUE TITLE
Unable to run test after clicking link on the preview

### ISSUE THREAD

**Issue by marauderlabs** [FreeCodeCamp/FreeCodeCamp#7495] opened 2016-03-11 06:21 UTC
#### FreeCodeCamp Issue template

To Use this Template:
- Fill out what you can
- Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help
#### Issue Description
- On page 'Link to External Pages with Anchor Elements' of 'HTML5 and CSS' under 'Front End Development Certification'
- After creating the link in the solution, click on the link displayed in the preview window, with or without control clicked. The original link won't open. Now, try submitting the solution either with the button or with 'ctrl-enter'. None of them work, until the page is refreshed.
#### Browser Information
- Google Chrome, v48.0.2564.116 m
- Windows 7 Enterprise
#### Your Code

```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


<a href="http://freecatphotoapp.com">cat photos</a>
```
#### Screenshot

![fcc](https://cloud.githubusercontent.com/assets/850807/13694536/3d929400-e77c-11e5-9bb1-b23f5f54d168.PNG)

**Comment by drk7891** [comment] 2016-03-11 06:42
Can confirm. 'Run Test' works before clicking link, but does not after clicking.

Only way to fix this I found was to close the tab and navigate back to the same page

User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by AishwaryaT** [comment] 2016-03-22 22:13
I confirm the same. I was able to run test before clicking the preview and not after that.

**Comment by GuominWu** [comment] 2016-03-23 18:37
I run into the same problem using Google Chrome, but its working when I switch to Firefox.  Not sure if it has anything to do browsers

**Comment by Willair** [comment] 2016-03-30 03:59
Can also confirm, just ran into this issue myself after trying to click the link in the preview. Closing the browser or tab and going back allows you to then run the test and move on.

**Comment by amru82** [comment] 2016-04-07 10:14
Same here.

**Comment by aakanksha-02** [comment] 2016-06-03 14:07
Only way to fix this ---> close the tab and navigate back to the same page

**Comment by Eugav** [comment] 2016-06-12 19:50
+1

**Comment by systimotic** [comment] 2016-10-30 11:01
Thanks for reporting and confirming everyone! I'm closing this as a duplicate of #8185. I realize this was reported earlier, but the other one now has more information.  
If I misunderstood this issue, and it's actually a different issue, feel free to add more information and reopen. Happy coding!

**Closed by systimotic** 2016-10-30 11:01 UTC
