### ISSUE TITLE
i am trying to size-image 100px its not working 

### ISSUE THREAD

**Issue by shiva1726** [freeCodeCamp/freeCodeCamp#15063] opened 2017-05-26 18:33 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by jodylecompte** [comment] 2017-05-26 18:34
Hey @shiva1726,

Can you provide the challenge and the code you are experiencing issues with, please? This will allow us to determine if the issue is the code or the challenge.

**Comment by Coder12344** [comment] 2017-05-26 18:42
I'm having the same problem, the challenge is called sizing your images

**Comment by Coder12344** [comment] 2017-05-26 18:45
I put the class inside like that <img class=smaller-image...> and in my style section I have .smaller-text{ width=100px}

**Comment by Coder12344** [comment] 2017-05-26 18:45
<img class="smaller-text"

**Comment by Coder12344** [comment] 2017-05-26 18:47
@jodylecompte

**Comment by systimotic** [comment] 2017-05-26 18:48
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Closed by systimotic** 2017-05-26 18:48 UTC

**Comment by mogakas** [comment] 2017-05-26 20:26
<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
   .smaller-image{
    width: 100px;
  }
</style>

i have the same problem too...thats my code

**Comment by systimotic** [comment] 2017-05-27 09:14
@mogakas Please use the "Help" button if you need coding help. To be able to figure out what's wrong, people will need to see all of the code, not just the CSS.
