### ISSUE TITLE
Example problen

### ISSUE THREAD

**Issue by florianpnn** [FreeCodeCamp/FreeCodeCamp#3058] opened 2015-09-04 18:14 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue.

The example gives us :
```
$(".target:nth-child(3)").addClass("animated bounce");
```

While the working code should be :
```
$(".target :nth-child(3)").addClass("animated bounce");
```
only a space is missing.

**Comment by bugron** [comment] 2015-09-04 18:27
@florianpnn thanks for posting this issue!
Actually `$(".target :nth-child(3)").addClass("animated bounce");` won't work because 
>Make the **second** child in each of your well elements bounce.

This means the working code is `$(".target:nth-child(2)").addClass("animated bounce");`.

Also I'm closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-04 18:27 UTC
