### ISSUE TITLE
Test 5 failing

### ISSUE THREAD

**Issue by abhi911kumar** [freeCodeCamp/freeCodeCamp#38795] opened 2020-05-12 05:44 UTC
I finished the coding as per the demo application but when I run the test it fails only at Test 5 "I can retrieve a full exercise log of any user by getting /api/exercise/log with a parameter of userId(_id). The app will return the user object with added array log and count (total exercise count)."

The result from the demo application and the one created by me are both same with no difference other than value. Please check it and tell me if I am doing it wrong or there is really a bug as I am not able to know what test case is running here.

**Comment by scissorsneedfoodtoo** [comment] 2020-05-12 06:02
@abhi911kumar, could you post a link to your live project so we can take a look?

**Comment by abhi911kumar** [comment] 2020-05-12 06:07
Please find the link to my live project https://abhi911kumar-freecode-exercisetracker-1.glitch.me

**Comment by scissorsneedfoodtoo** [comment] 2020-05-12 06:42
Thanks for posting a link to your project.

Here's what the sample solution at https://fuschia-custard.glitch.me/ returns:

```json
{
  "_id": "_______",
  "username": "scissorsneedfoodtoo",
  "count": 2,
  "log": [
    {
      "description": "pushups",
      "duration": 30,
      "date": "Tue May 12 2020"
    },
    {
      "description": "pullups",
      "duration": 20,
      "date": "Tue May 12 2020"
    }
  ]
}
```

But your project returns:

```json
{
  "user": [
    {
      "_id": "_______",
      "username": "scissorsneedfoodtoo"
    }
  ],
    "log": [
      {
        "description": "pullups",
        "duration": 20,
        "date": "Tue May 12 2020"
      },
      {
        "description": "pushups",
        "duration": 30,
        "date": "Tue May 12 2020"
      }
    ],
  "count": 2
}
```

All the data is there, but it needs to be returned in a JSON object like the one above. Our tests don't expect a `user` array with an object containing the `id` and `username`. 

I'll close this for now. Please feel free to reach out on the forum for help with these projects. If you do find a bug, please open another issue.

**Closed by scissorsneedfoodtoo** 2020-05-12 06:42 UTC
Labels: scope: learn, status: needs help for triage

**Comment by bavern** [comment] 2020-05-12 06:54
JSON object like the one above.?

**Comment by abhi911kumar** [comment] 2020-05-12 06:58
Made the changes to the JSON object but still, the Test is failing. Please feel free to tell me what is the problem now.

**Comment by abhi911kumar** [comment] 2020-05-12 07:07
> Thanks for posting a link to your project.
> 
> Here's what the sample solution at https://fuschia-custard.glitch.me/ returns:
> 
> ```json
> {
>   "_id": "_______",
>   "username": "scissorsneedfoodtoo",
>   "count": 2,
>   "log": [
>     {
>       "description": "pushups",
>       "duration": 30,
>       "date": "Tue May 12 2020"
>     },
>     {
>       "description": "pullups",
>       "duration": 20,
>       "date": "Tue May 12 2020"
>     }
>   ]
> }
> ```
> 
> But your project returns:
> 
> ```json
> {
>   "user": [
>     {
>       "_id": "_______",
>       "username": "scissorsneedfoodtoo"
>     }
>   ],
>     "log": [
>       {
>         "description": "pullups",
>         "duration": 20,
>         "date": "Tue May 12 2020"
>       },
>       {
>         "description": "pushups",
>         "duration": 30,
>         "date": "Tue May 12 2020"
>       }
>     ],
>   "count": 2
> }
> ```
> 
> All the data is there, but it needs to be returned in a JSON object like the one above. Our tests don't expect a `user` array with an object containing the `id` and `username`.
> 
> I'll close this for now. Please feel free to reach out on the forum for help with these projects. If you do find a bug, please open another issue.

**Made the changes to the JSON object but still, the Test is failing. Please feel free to tell me what is the problem now.**

**Comment by bavern** [comment] 2020-05-12 07:12
Reply to this email directly,   Test is  ,,  link to your project. Here's
what the sample solution at https ?

Abhishek Mallick <notifications@github.com> ezt írta (időpont: 2020. máj.
12., K, 9:08):

**Comment by bavern** [comment] 2020-05-12 07:16
And  builds features that helpp,

Simon Bauer <sbauer265@gmail.com> ezt írta (időpont: 2020. máj. 12., K,
9:11):

**Comment by scissorsneedfoodtoo** [comment] 2020-05-12 08:18
@abhi911kumar, awesome, the JSON your app returns seems to match the solution project now.

I suspect the problem is that your project doesn't handle all cases where there is no date.

The 5th test makes a request with the following:

```
const addRes = await fetch(url + '/api/exercise/add', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}`
});
```

The 4th test makes this request:

```
const addRes = await fetch(url + '/api/exercise/add', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}&date=1990-01-01`
});
```

When I tried to add an exercise to my user using Postman, your project returned an `INVALID DATE` error. If there is no date present, it should use the current date.

**Comment by bavern** [comment] 2020-05-12 10:07
Our tests don't expect a user array with an object containing the id,,

**Comment by abhi911kumar** [comment] 2020-05-15 13:49
> @abhi911kumar, awesome, the JSON your app returns seems to match the solution project now.
> 
> I suspect the problem is that your project doesn't handle all cases where there is no date.
> 
> The 5th test makes a request with the following, which doesn't include a date:
> 
> ```
> const addRes = await fetch(url + '/api/exercise/add', {
>   method: 'POST',
>   headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
>   body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}`
> });
> ```
> 
> The 4th test makes this request that does include a date:
> 
> ```
> const addRes = await fetch(url + '/api/exercise/add', {
>   method: 'POST',
>   headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
>   body: `userId=${_id}&description=${expected.description}&duration=${expected.duration}&date=1990-01-01`
> });
> ```
> 
> When I tried to add an exercise to my user using Postman, your project returned an `Invalid date` error. If there is no date present, it should use the current date.
> 
> Hope that helps you pass the last test.

Thank you so much for the help it solved my problem. Yes, I was missing handling the undefined date param in POST call.

This solved my problem. Thanks a ton :)

**Comment by scissorsneedfoodtoo** [comment] 2020-05-20 06:51
@abhi911kumar, sorry that I'm just seeing this now. But awesome! Glad that you were able to solve the issue in the end.
