### ISSUE TITLE
wrong tase case Bonfire: Search and Replace

### ISSUE THREAD

**Issue by 4000D** [FreeCodeCamp/FreeCodeCamp#5971] opened 2016-01-08 09:52 UTC
Challenge [Bonfire: Search and Replace](http://www.freecodecamp.com/challenges/bonfire-search-and-replace#?solution=function%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20return%20str.split('%20').map(function(e)%20%7B%0A%20%20if(e%20%3D%3D%20before)%0A%20%20%20%20return%20after%3B%0A%20%20return%20e%3B%0A%7D).join('%20')%3B%0A%7D%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myReplace(str, before, after) {
  return str.split(' ').map(function(e) {
  if(e == before)
    return after;
  return e;
}).join(' ');
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```

Wrong Test Case
myReplace("He is Sleeping on the couch", "Sleeping", "sitting") should return "He is Sitting on the couch".
myReplace("His name is Tom", "Tom", "john") should return "His name is John".
myReplace("Let us get back to more Coding", "Coding", "bonfires") should return "Let us get back to more Bonfires".

**Comment by royshouvik** [comment] 2016-01-08 11:59
Hi @4000D this one is a bit tricky but the test cases are correct. Note in the challenge description 
> NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"

**Comment by SaintPeter** [comment] 2016-01-08 20:58
Closing as this is not a bug in the site.

In the future, please use the [HelpBonfires](https://gitter.im/FreeCodeCamp/HelpBonfires) Chat Room for code related questions.

Thanks and Happy Coding!

**Closed by SaintPeter** 2016-01-08 20:58 UTC
