### ISSUE TITLE
Template Post when clicking "Ask for Help" in Responsive Web Development

### ISSUE THREAD

**Issue by alfonsusac** [freeCodeCamp/freeCodeCamp#47452] opened 2022-09-05 12:49 UTC
### Describe the Issue

I feel like the base template for asking help in the Responsive Web Development Certification is a bit unintuitive.

First let me point out a couple of points:

1. The code block of HTML starts with `/* file: index.html */` as opposed to the HTML comments of `<!-- file: index.html -->`. This will makes it harder to copy paste people's code and find the problem as some may overlook this comment which can cause the checker to fail (As seen in this post https://forum.freecodecamp.org/t/learn-css-colors-by-building-a-set-of-colored-markers-step-7/551034).
2. Some text that I assume function as a heading uses inconsistent formatting. Such as how `**Tell us What's happening:**` is different from `     **Your code so far**` (there is a tab which can look like a code block after posting it.

Template:
~~~
**Tell us what's happening:**
Describe your issue in detail here.


      **Your code so far**
      
```html
/* file: index.html */

```

```css
/* file: styles.css */

```




      **Your browser information:**

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36</code>

**Challenge:**  Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 22

**Link to the challenge:**
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-22
~~~

What I propose:
~~~
### Tell us what's happening:
Describe your issue in detail here.


### Your code so far
```html
<!-- file: index.html -->

```

```css
/* file: styles.css */

```




### Your browser information:

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36</code>

### Challenge:
Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 22

### Link to the challenge:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-22
~~~

### Affected Page

https://forum.freecodecamp.org/c/html-css/423

### Steps to Reproduce

1. Go to 'Any step in Responsive Web Development'
2. Check the code several times until the "Ask for Help" appears
3. Click on 'Create a help post in the forum'
4. Minor Inconvenience

### Expected behavior

It should be intuitive and consistent such that the user won't be confused to how to format the page. At least that's what I'm hoping

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment] 2022-09-05 15:28
> Some text that I assume function as a heading uses inconsistent formatting. Such as how **Tell us What's happening:** is different from **Your code so far** (there is a tab which can look like a code block after posting it.

We have tried fixing this multiple times:
https://github.com/freeCodeCamp/freeCodeCamp/blob/921a8fdc4eb59f151cb51a52a6e32751cf73bcd5/client/src/templates/Challenges/redux/create-question-epic.js#L63-L76

It is caused by the `dedent` function, and I have never found a reliable way around it.

**Comment by ieahleen** [comment] 2022-09-06 16:36
> ```html
> 
> 
> ```

This can probably be obteined changing here
https://github.com/freeCodeCamp/freeCodeCamp/blob/921a8fdc4eb59f151cb51a52a6e32751cf73bcd5/client/src/templates/Challenges/redux/create-question-epic.js#L17-L29

Changing the `fileName` definition on lines 23-25 with a different behaviour if `fileType === 'html'`.

At this point it shouldn't be a ternary anymore, nested ternaries are pretty difficult to read.

Something like
```js
let fileName;
if (!moreThanOneFile) {
   fileName = "";
} else if (fileType === 'html') {
   fileName =  `<!-- file: ${challengeFile.name}.${challengeFile.ext} -->\n`;
} else {
   fileName =  `/* file: ${challengeFile.name}.${challengeFile.ext} */\n`;
}
```

maybe there are better solutions 🤷

**Comment by bbsmooth** [comment] 2022-09-06 20:47
Just a thought. Do we need to allow the user to even edit their "code so far"? A lot of times they will delete it for some reason and then we just end up asking them to put it back in. Maybe don't give them the chance in the first place? Then the only thing we would be asking them for is a description of their problem. And a lot of times they just skip over this completely and we just end up asking them to tell us what their problem is. So we could do a check to make sure they at least added some original text for the description when they submit.

**Comment by ShaunSHamilton** [comment] 2022-09-06 21:12
@bbsmooth Currently, without writing a Discourse plugin, we cannot do any validation on the submissions.

**Comment by ieahleen** [comment] 2022-09-07 19:57
As this is already about changing that part of the template, maybe this can aslo be added in.

When `challengeFile.ext` is `js`, `fileType` should be `javascript` for the forum code highlighting

https://github.com/freeCodeCamp/freeCodeCamp/blob/921a8fdc4eb59f151cb51a52a6e32751cf73bcd5/client/src/templates/Challenges/redux/create-question-epic.js#L26

```javascript
    const fileType = challengeFile.ext === 'js' ? 'javascript' : challengeFile.ext;
```

![image](https://user-images.githubusercontent.com/26656284/188965085-611277ad-6796-444a-8072-42753488280c.png)

**Comment by naomi-lgbt** [comment] 2022-09-08 19:20
>  without writing a Discourse plugin

From what I have read, we can't install more plugins on a managed instance anyway.

**Comment by moT01** [comment] 2022-09-16 14:58
The above PR fixed the comments in the code snippets. Looks like we just need to update the template to use headings. 

Here's what the template currently look like:
![Screen Shot 2022-09-16 at 9 52 31 AM](https://user-images.githubusercontent.com/20648924/190668719-d4e1a186-52e4-4fd6-8059-9f209032aef7.png)

Here's what @alfonsusac's suggestion would look like:
![Screen Shot 2022-09-16 at 9 54 17 AM](https://user-images.githubusercontent.com/20648924/190668734-dc46d8dc-1eb8-4b48-8579-5168526cfadc.png)

I would maybe change them to level 2 headings and add a semi-colon after "Your code so far":
![Screen Shot 2022-09-16 at 9 54 38 AM](https://user-images.githubusercontent.com/20648924/190668851-7f2ffde2-e80f-4306-b2e3-3b438f198c47.png)

I am in favor of this change. I like the last suggestion there, but @alfonsusac's works for me.

**Comment by ShaunSHamilton** [comment] 2022-09-16 16:12
I am happy with changing them to level 2 headings. _Personally, they look a bit big, but otherwise it makes sense._

However, this does not solve the dedent issue:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/51722130/190683338-7e8ad012-3935-4f7a-94e2-58e699bfd6c9.png">

**Comment by alfonsusac** [comment] 2022-09-16 17:14
I prefer them at level 3 headings. When I open the forum and and see the template I just want to look at the content as soon as possible lol. This will make it so that the headings does not take much attention but still separated with other content.

**Comment by bbsmooth** [comment] 2022-09-16 18:20
I just want to point out that heading levels should not be determined by looks but rather by their position in the heading hierarchy. If a heading looks out of place or is distracting in some way then this can be fixed with CSS. But the actual heading level number should be appropriate for where it is on the page.

**Comment by ieahleen** [comment] 2022-09-26 13:43
I think that with #47578 this can be considered fixed

**Comment by moT01** [comment] 2022-12-07 15:09
Do we still want to add the headings or is this fixed? I'm in favor of the headings I think, not quite sure what the appropriate level is. That should be the last thing though - adding a help wanted label.

**Comment by KSSaiTeja** [comment] 2023-09-17 02:47
i'm interested on this issue. please tell me how can i start working on this

**Comment by ieahleen** [comment] 2023-10-12 16:26
@bbsmooth I think this needs one last look from you, what level of headings are semantically appropriate?

**Comment by bbsmooth** [comment] 2023-10-12 17:17
Based on the current heading structure that is used when you view the actual post, I would suggest that these headings should be `h3`.

**Comment by ieahleen** [comment] 2023-10-13 12:33
> Additionally I think its a marginally better to combine the `Challenge` and `Link to Challenge` section such as:
> 
> ```
> ### Challenge information:
> Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 22
> https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-22
> ```
> 
> ## Preview:
> ### Challenge information:
> Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 22 https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-22

What do we think of this? Would this make sense as a change?

**Comment by Dario-DC** [comment] 2023-10-13 13:19
> > ```
> > ### Challenge information:
> > Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 22
> > https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-22
> > ```

It looks good 👍

**Comment by ieahleen** [comment] 2023-10-13 13:36
Ok, I will make that change, and finally make the PR, thank you for your input

**Closed** 2023-10-14 09:08 UTC
Labels: type: bug, help wanted
