### ISSUE TITLE
Waypoint 48: Inherit Styles from the Body Element

### ISSUE THREAD

**Issue by paolo215** [FreeCodeCamp/FreeCodeCamp#4836] opened 2015-12-01 05:40 UTC
```<style>
  body {
    background-color: black;
    color: green;
    font-family: Monospace;
  }
</style>
    <h1>Hello World</h1>
```

This is posted by Sha Duv on Facebook FCC Portland group. We both got this result:

![http://i.imgur.com/sIvlo8J.png](http://i.imgur.com/sIvlo8J.png)

**Comment by ltegman** [comment] 2015-12-01 05:50
Closing as a duplicate of #4833. Please continue further discussion in there.

Thanks and happy coding!

**Closed by ltegman** 2015-12-01 05:50 UTC

**Comment by balajichari31** [comment] 2017-06-09 19:00
Well this is the right way, if am not left :)
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{
    color: pink;
  }
  .blue-text{
    color:blue;
  }
  
</style>
<h1 class =  "pink-text blue-text">  Hello World!</h1>

**Comment by balajichari31** [comment] 2017-06-09 19:01
![image](https://user-images.githubusercontent.com/19181631/26990442-2bbb8250-4d74-11e7-9f0d-03a2b1ac4391.png)
