### ISSUE TITLE
"HTML Entities" link returns 403 access forbidden

### ISSUE THREAD

**Issue by noamoss** [FreeCodeCamp/FreeCodeCamp#11689] opened 2016-11-17 18:00 UTC
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities) has an issue.

The side link toward 'html entities' side link is borken.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
![screenshot-dev w3 org 2016-11-17 19-59-22](https://cloud.githubusercontent.com/assets/3581741/20401187/70c4ea36-ad00-11e6-8f75-e2e6efeb21dc.png)

**Comment by avirajkhare00** [comment] 2016-11-17 18:37
I think that link is no more valid and moved to some other address. You can try cached version of this page from google - https://webcache.googleusercontent.com/search?q=cache:jB8ohKWhRugJ:https://dev.w3.org/html5/html-author/charref+&cd=1&hl=en&ct=clnk&gl=in

**Comment by Bouncey** [comment] 2016-11-17 23:08
@noamoss the link works for me

**Comment by raisedadead** [comment] 2016-11-18 04:20
Can't reproduce, maybe it was a tempory issue. 
@noamoss can you please re-check and confirm? thanks.

**Comment by systimotic** [comment] 2016-11-18 08:15
I can confirm that this issue was present at the time of reporting. I checked, but didn't have time to take any further action. The cache link shared was from a day earlier, and the page was also still the top result on Google, so I assumed at the time that it was potentially a temporary issue.
I also got the 403 yesterday, but I can reach the page fine now.

I'm closing this issue, as it appears to be resolved. If it doesn't work for you @noamoss, please reopen this issue.
Happy coding!

**Closed by systimotic** 2016-11-18 08:15 UTC
