### ISSUE TITLE
Seems like a bug to me, right ?

### ISSUE THREAD

**Issue by solurus** [FreeCodeCamp/FreeCodeCamp#9543] opened 2016-07-04 17:15 UTC
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
here is the link for printscreen snap: https://www.dropbox.com/s/y4r9s2n6gs7d4xu/Screenshot%202016-07-04%2019.16.18.png?dl=0 
My code:
```html
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by BKinahan** [comment] 2016-07-04 17:19
No bug here! You deleted the h2's style element, but you also deleted the h2 :)

The style element looks fine, though. Reset the code and try again without removing the entire h2 element; that way it will still show up in the preview on the right.

**Comment by erictleung** [comment] 2016-07-04 18:30
@solurus what @BKinahan says is correct. You still need the `h2` element to pass the challenge. Your style code block looks good though. Closing as not a bug with the site. Happy coding!

**Closed by erictleung** 2016-07-04 18:30 UTC
