### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by SJ-Hadley** [FreeCodeCamp/freecodecamp#710] opened 2015-05-28 19:07 UTC
The page isn't recognizing that I have specified a border width and style. The code is rendered properly in the "Cat Photo App", but I can't advance to the next challenge. The code in question:

  .thick-green-border {
    border-color: green;
    border-style: solid;
    border-width: 10px;
  }

**Comment by matejhegedus** [comment] 2015-05-28 20:34
This is a duplicate of #704.

**Comment by QuincyLarson** [comment] 2015-05-31 21:15
Thanks for reporting this, @s-j-hadley. We've now fixed this.

**Closed by QuincyLarson** 2015-05-31 21:15 UTC
