### ISSUE TITLE
Display incorrect in Win7_IE10 and OSX10.9_Safari7

### ISSUE THREAD

**Issue by georgebakerus** [FreeCodeCamp/FreeCodeCamp#7840] opened 2016-04-01 03:42 UTC
![fccportfolio_win7_ie10](https://cloud.githubusercontent.com/assets/6006592/14197240/bd34aa84-f791-11e5-89f0-36d37b6127bf.jpg)
![fccportfolio_osx9_safari7](https://cloud.githubusercontent.com/assets/6006592/14197243/c1a0047e-f791-11e5-8d08-e26f505ac7c3.jpg)

Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by erictleung** [comment] 2016-04-01 19:44
I can't reproduce this. I don't have Windows 10 but at least for Windows 7, all browsers work. I can try and verify the Safari issue later.

**Comment by erictleung** [comment] 2016-04-02 17:39
Turns out I don't have OSX 10.9 so I couldn't verify either issue..I'll keep this open in case other people get issues.

**Comment by raisedadead** [comment] 2016-04-17 07:37
I can confirm this via native testing on OSX 10.9 and Safari 7.
Here is the full user-agent string :
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.76.4 (KHTML, like Gecko) Version/7.0.4 Safari/537.76.4`

/cc @hallaathrad : Do you know if these older browsers have some form of 'shims' or 'polyfill' techniques to get this working?

**Comment by hallaathrad** [comment] 2016-04-17 10:54
Hmmm I've just checked on my Windows 10, all browsers seem to handle it fairly well in their latest versions (including Firefox 45, like the OP). However, cannot check Safari on OSX 10.9.

Arguably, the screenshots are from a cross-browser testing tool, which in my experience hasn't been reliable enough for production testing. Therefor I have machines to actually run natively.
Will try to get the Safari test going, but thus far, I still cannot reproduce.

**Comment by hallaathrad** [comment] 2016-04-17 19:06
Aaaand thanks to @raisedadead, we should've found a solution to whatever issues you were having related to this. @georgebakerus please reopen this issue if you are still having the same problem.

Closing as fixed meanwhile (and hopefully forever)

**Closed by hallaathrad** 2016-04-17 19:06 UTC
Labels: blocked

**Comment by raisedadead** [comment] 2016-04-17 19:13
Thanks to @hallaathrad for doing the fixes. After all he is the CSS Ninja at FCC 😉 !
