### ISSUE TITLE
Typo in Learn Recursion by Building a Decimal to Binary Converter - Step 47

### ISSUE THREAD

**Issue by Vietos94** [freeCodeCamp/freeCodeCamp#54392] opened 2024-04-15 02:10 UTC
### Describe the Issue

I believe the “or” in the 2nd part of the instruction shouldn't be there.

> The call stack is a collection of function calls stored in a stack structure. When you call a function, it is added to the top **or** of the stack, and when it returns, it is removed from the top / end of the stack.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-47

### Steps to Reproduce

...

### Recommended fix or suggestions

...

**Comment by jdwilkin4** [comment] 2024-04-15 03:51
Hi @Vietos94 ! 

This is a duplicate of this open issue here 

https://github.com/freeCodeCamp/freeCodeCamp/issues/54386

I am going to close this issue 👍

**Closed by jdwilkin4** 2024-04-15 03:51 UTC
Labels: type: bug, status: waiting triage
