### ISSUE TITLE
Beta issue in Basic CSS: Adjust the Padding of an Element, code won't load in phone

### ISSUE THREAD

**Issue by amy33amy33** [freeCodeCamp/freeCodeCamp#13888] opened 2017-03-13 04:07 UTC
Challenge [adjust-the-padding-of-an-element](http://beta.freecodecamp.com/en/challenges/basic-css/adjust-the-padding-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Code will not reload on phone display, If coming from previous assignment, phone will display previous assignment's code, if not, phone will display blank page. Phone code will load properly upon submitting challenge.

```html


<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px;
  }

  .green-box {
    background-color: green;
    padding: 10px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by raisedadead** [comment] 2017-05-11 15:31
Duplicate of #12923

**Closed by raisedadead** 2017-05-11 15:31 UTC
Labels: beta
