### ISSUE TITLE
On tablet maybe doesn't work?

### ISSUE THREAD

**Issue by AlexMogoryan** [FreeCodeCamp/FreeCodeCamp#5028] opened 2015-12-05 16:56 UTC
Challenge [Waypoint: Override Styles in Subsequent CSS](http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%C2%A0%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; Lenovo B6000-H Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="pink-text blue-text">Hello World!</h1>


```

**Comment by ltegman** [comment] 2015-12-05 20:50
Closing as a duplicate of #5027. Does not seem to be tablet specific. Thanks and happy coding!

**Closed by ltegman** 2015-12-05 20:50 UTC
