### ISSUE TITLE
Local Weather App - FCC Zipline Demo doesn't show weather information

### ISSUE THREAD

**Issue by MartinDelille** [FreeCodeCamp/FreeCodeCamp#3925] opened 2015-10-26 23:36 UTC
I'm about to work on the *Zipline: Show the Local Weather* challenge but it appear the example failed to display weather information: http://codepen.io/AdventureBear/full/yNBJRj

Checking the console log reveal the following error:

    Failed to load resource: the server responded with a status of 401 (Unauthorized) http://api.openweathermap.org/data/2.5/weather?lat=45.9000&lon=6.1167&units=metric&callback=jQuery213018545346311293542_1445901807518&_=1445901807520

The link http://api.openweathermap.org/data/2.5/weather?lat=45.9000&lon=6.1167&units=metric&callback=jQuery213018545346311293542_1445901807518&_=1445901807520 display the following error:

    Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by ltegman** [comment] 2015-10-26 23:42
This Zipline is currently in limbo as openweathermap has locked down their API to require an API key.

Closing as a duplicate of #3714, please continue any discussion in that thread.

Thanks and happy coding!

**Closed by ltegman** 2015-10-26 23:42 UTC
