### ISSUE TITLE
Seeing "fccss","fcces" instead of <script>, </script>

### ISSUE THREAD

**Issue by MaxRubyDev** [FreeCodeCamp/FreeCodeCamp#2257] opened 2015-08-20 01:35 UTC
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. 

This issue is also replicated on http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery

Where the <script> tag should be, the letters "fccss" appear; and
where the </script> tag should be, the letters "fcces" appear.

I assume "fccss" starts for "FCC Start Script" and
I assume "fcces" starts for "FCC End Script".  

This wasn't clear and I couldn't complete the waypoint until I realized the bug.  (Was it intentional?) 

![bug](https://cloud.githubusercontent.com/assets/8146817/9373589/22734e3e-46ba-11e5-9715-047a27d45c91.jpg)

And yes, I'm using Chrome on a Mac.

**Comment by benschenker** [comment] 2015-08-20 02:08
Thanks for posting an issue,

This is a duplicate of #2242 and others though in general try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by BerkeleyTrue** [comment] 2015-08-21 04:03
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 04:03 UTC
