### ISSUE TITLE
The Longest Streak was broken when it reached 32 days

### ISSUE THREAD

**Issue by ch3rn0v** [FreeCodeCamp/freecodecamp#1649] opened 2015-08-07 20:59 UTC
The Longest Streak of my profile http://www.freecodecamp.com/chernov seems to be broken, though I didn't miss a day. I noticed this issue when I've finished this Zipline challenge:http://www.freecodecamp.com/challenges/zipline-show-the-local-weather has an issue.

Maybe the reason for it is that my current streak is over 31 day.

**Comment by ahstro** [comment] 2015-08-07 22:42
I think it's more likely that you didn't get a streak according to server time, as explained in #479.
The active issue, where all related discussion should be held, is #1075, so please close this in favor of that one. Thanks :)

**Comment by BerkeleyTrue** [comment] 2015-08-07 23:29
Hello @ch3rn0v 

This is a duplicate of #1075

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-07 23:29 UTC

**Comment by ch3rn0v** [comment] 2015-08-08 08:56
Thank you for the information, got it.
