### ISSUE TITLE
Waypoint: Passing Values to Functions with Arguments: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by MiLeung** [FreeCodeCamp/FreeCodeCamp#5621] opened 2015-12-31 06:24 UTC
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(a%2C%20b)%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0AmyFunction(2%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(a, b){
  console.log(a + b);
}
myFunction(2, 3);

```

myFunction() works fine in Chrome's dev tools.

**Comment by ltegman** [comment] 2015-12-31 06:25
Closing as a duplicate of #5560. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 06:25 UTC
