### ISSUE TITLE
[beta] Adjusting the color of various elements to complementary colors on Firefox

### ISSUE THREAD

**Issue by Barterr** [freeCodeCamp/freeCodeCamp#13645] opened 2017-02-28 15:15 UTC
Challenge doesn't count as complete on Firefox, same code works on Chrome just fine.

Challenge [adjusting-the-color-of-various-elements-to-complementary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjusting-the-color-of-various-elements-to-complementary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background-color: white;
  }
  header {
    background-color: #09A7A1;
    color: white;
    padding: 0.25em;
  }
  h2 {
    color: #09A7A1;
  }  
  button {
    background-color: #FF790E;
  }
  footer {
    background-color: #09A7A1;
    color: white;
    padding: 0.5em;
  }
</style>
<header>
  <h1>Cooking with FCC!</h1>
</header>
<main>
  <article>
    <h2>Machine Learning in the Kitchen</h2>
    <p>Join this two day workshop that walks through how to implement cutting-edge snack-getting algorithms with a command line interface. Coding usually involves writing exact instructions, but sometimes you need your computer to execute flexible commands, like <code>fetch Pringles</code>.</p>
    <button>Sign Up</button>
  </article>
  <article>
    <h2>Bisection Vegetable Chopping</h2>
    <p>This week-long retreat will level-up your coding ninja skills to actual ninja skills. No longer is the humble bisection search limited to sorted arrays or coding interview questions, applying its concepts in the kitchen will have you chopping carrots in O(log n) time before you know it.</p>
    <button>Sign Up</button>
  </article>
</main>
<br>
<footer>&copy;2016 FCC Kitchen</footer>

```

**Comment by fonsecapontes** [comment] 2017-03-02 01:02
I tested and this occurs because the result rgb in chrome is different in firefox.

Exemple: The color #09A7A1: 
Chrome: RGB(9, 167, 161)
Firefox: RGB(8, 169, 164)

Maybe change the challenge can fix this. What is your opinion?

**Comment by systimotic** [comment] 2017-03-16 20:22
Thanks for reporting @Barterr, and for investigating @fonsecapontes!

This issue is a duplicate of #10749. I'm closing this in favour of that.

**Closed by systimotic** 2017-03-16 20:22 UTC
Labels: beta
