### ISSUE TITLE
variable names should be more descriptive.

### ISSUE THREAD

**Issue by geeknabil** [freeCodeCamp/freeCodeCamp#39994] opened 2020-10-17 07:16 UTC
for better learning quality in some challenges variable names should be more descriptive specially first few challenges on javascript basics section.

**Comment by nhcarrigan** [comment] 2020-10-17 07:18
Hello~!

While I agree that variable names in general should be descriptive, the variables in the beginning lessons serve little practical purpose. The point of the lessons is to demonstrate some fundamental concepts, and using short variable names helps keep the focus on the lesson material in my opinion.

**Comment by Sky020** [comment] 2020-10-18 13:43
Thank you, for bringing this up. Although, a few examples of where/how you specifically would expect to see improvement would help.

I agree with @nhcarrigan , and worry that creating such an issue could easily delve into _bike-shedding_ with how _best_ to name things.

**Comment by murtaza63** [comment] 2020-11-08 11:30
I 100% agreed with   geeknabil .

**Comment by murtaza63** [comment] 2020-11-08 11:31
I  agree with geeknabil .

**Comment by RandellDawson** [comment] 2020-11-08 22:54
@geeknabil @murtaza63 I you could make some specific suggestions for specific challenges, we could have something more concrete to discuss.  Otherwise, I agree with @Sky020 and @nhcarrigan here.

**Comment by moT01** [comment] 2021-02-03 20:20
I think it's safe to close this for now. Without further specification on what the problem is, I don't think there's anything we need to do. If there's still concern around this, feel free to a leave a comment with more details and we can reopen it. 

Thanks and happy coding 🎉

**Closed by moT01** 2021-02-03 20:20 UTC
Labels: status: discussing, type: feature request
