### ISSUE TITLE
D3 - Common Issues with Dataset

### ISSUE THREAD

**Issue by PizzaPokerGuy** [freeCodeCamp/freeCodeCamp#13292] opened 2017-02-11 23:39 UTC
D3 Challenges Dataset identifier dataset has already been declared error.

Essentially the D3 challenges won't run after 1 failed attempt.

Challenge [work-with-dynamic-data-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<body>
  <script>
    let dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      // Add your code below this line
      
      .text((d) => d + ' USD');
      
      // Add your code above this line
  </script>
</body>

```

**Comment by PizzaPokerGuy** [comment] 2017-02-11 23:40
Note that I tried changing const to let to see if this would fix this issue. It did not.

**Comment by zachnagatani** [comment] 2017-02-13 20:01
@PizzaPokerGuy I got it to work by removing the declaration entirely.

**Comment by PizzaPokerGuy** [comment] 2017-02-13 20:10
It can also past by clearing the cache and doing a hard reload for those looking to push through for the Beta.

**Comment by hessproject** [comment] 2017-02-20 21:40
Just wanted to mention that this seems to carry over to later challenges from previous challenges that use the same const declarations, not just after a failed attempt.

**Comment by systimotic** [comment] 2017-03-16 21:03
Hi everyone! Thanks for reporting and looking at this issue.

I'm closing this issue as a duplicate of #12762 
Happy coding!

**Closed by systimotic** 2017-03-16 21:03 UTC
Labels: beta, bug
