### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by spinningbackfist** [FreeCodeCamp/freecodecamp#681] opened 2015-05-28 02:18 UTC
Hey folks,

In the Waypoint: Use Clockwise Notation to Specify the Margin of an Element challenge, it is asked to fulfill the following:

Your green-box class should give the left of elements 40px of margin.
 Your green-box class should give the bottom of elements 20px of margin.
 Your green-box class should give the top of elements 20px of margin.
 Your green-box class should give the right of elements 20px of margin.

However, the third one (top of elements), only was checked as "accepted" when I entered the value of 40px instead of 20px. Could you please verify?

**Comment by spinningbackfist** [comment] 2015-05-28 02:21
![image](https://cloud.githubusercontent.com/assets/12635861/7851494/288295f8-04c7-11e5-8a46-cad88287916b.png)

**Comment by terakilobyte** [comment] 2015-05-28 11:02
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:02 UTC
