### ISSUE TITLE
need to remove BOTH console.log statments

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#5591] opened 2015-12-30 22:51 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20%22spam%22%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

challenge only passed when I removed BOTH console.log statements. Removing only the second one as requested did not work.
My code:
```javascript
function myFunction() {
  var myVar = "spam";
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
// now remove the console.log line to pass the test


```

**Comment by ltegman** [comment] 2015-12-30 22:52
Closing as a duplicate of #5559. Thanks and happy coding!

**Closed by ltegman** 2015-12-30 22:52 UTC

**Comment by shahidfoy** [comment] 2015-12-31 00:00
yea i got the same thing here
