### ISSUE TITLE
Claim Certification of APIs and Microservices Projects

### ISSUE THREAD

**Issue by kevintd** [freeCodeCamp/freeCodeCamp#17522] opened 2018-06-10 16:46 UTC
I completed all projects and subjects for APIs and Microservices Cert, but when I claim the cert the message "it looks like you have not completed the necessary steps. Please complete the required challenges to claim the APIs and Microservices"

Please let me know what i have to do to get the cert. 

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: Version 67.0.3396.79 (Official Build) (64-bit)
* Operating System: MAC OS

![screen shot 2018-06-09 at 2 09 07 am](https://user-images.githubusercontent.com/4203786/41171154-77be9a86-6b8a-11e8-9198-18acc6b9d93a.png)
![screen shot 2018-06-09 at 2 07 12 am](https://user-images.githubusercontent.com/4203786/41171155-77efa720-6b8a-11e8-920d-d96798af519d.png)

Thanks

**Comment by janosimas** [comment] 2018-06-11 23:30
same here

**Comment by dinomar** [comment] 2018-06-12 10:59
I'm having the same problem.

**Comment by lngchn** [comment] 2018-06-13 23:56
I have the same problem. Even after resubmitting all the solutions, it still doesn't work.

**Comment by eolculnamo2** [comment] 2018-06-16 02:03
Any errors in the console?

**Comment by lngchn** [comment] 2018-06-16 03:52
No errors in the console on my side. I'm using Chrome.

**Comment by MrcRjs** [comment] 2018-06-17 21:17
I have the same problem, I see 2 errors in the console but they seem to be unrelated.
![captura de pantalla 2018-06-17 a la s 16 13 37](https://user-images.githubusercontent.com/10587527/41512137-d9dfed9e-7249-11e8-934a-54fa1d45e5db.png)

**Comment by AndrewJBateman** [comment] 2018-06-18 08:15
I have the same errors, using Chrome too. 
![image](https://user-images.githubusercontent.com/27190679/41525159-57751c98-72e0-11e8-8a6b-6150a29a36ec.png)

**Comment by kevintd** [comment] 2018-06-18 08:50
This is my error message:
"Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com <URL> *.bootstrapcdn.com *.googleapis.com *.gstatic.com <URL> <URL> 'self' <URL> <URL>".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGVUABEAAAAAxuQAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC4AAAA0ArgC7UdQT1MAAAGwAAAQ6AAALgxKsqRTR1NVQgAAEpgAAAH3AAAELqI5y+RPUy8yAAAUkAAAAE8AAABgaGyBu2NtYXAAABTgAAABlAAAAkQkRATXY3Z0IAAAFnQAAABeAAAAugDsQf1mcGdtAAAW1AAABZcAAAvNb3/BHGdhc3AAABxsAAAACAAAAAgAAAAQZ2x5ZgAAHHQAAEApAAB3CtbiupxoZWFkAABcoAAAADYAAAA2BkubWWhoZWEAAFzYAAAAIAAAACQHFARfaG10eAAAXPgAAAI6AAAEEk4TN4Nsb2NhAABfNAAAAhIAAAISiLhpam1heHAAAGFIAAAAIAAAACACigzgbmFtZQAAYWgAAACUAAABHhQGLdJwb3N0AABh/AAAAq4AAASRk5y6n3ByZ...QxUajCCFt4p9HP4fzdSWs2XhWl5HvJazrIrFUyB0l5dpqcW10lV2wukjMLuAvyMHNiYpgPsrCVXZDKrkpll6UWkh7kABVAFVCDe7UFmxagDegA+hLHRPbqtMo7ZHCpKdT6tPGXybzo0+RXBLoPZt1tELcXxCmAAyZwYTJvdDFZKnDER44X2451rDqCyunIsRWvLSx6wnWqwPj/uX5/KuEy6DL0z6A/Fn79VihxMFJsrlAFy4DpZOcvNlMeNp+BRDLj0r+XFdRxdSNSNxiI/AL3ojKdAAB4AWPw3sFwIihiIyNjX+QGxp0cDBwMyQUbGdictkUwWDAwsDJogTgOPN4c9iz6bMos4iysHFChUDZXJnMWTSZZJrAQt9M+YQYBBh4GTgY2kEZOoJiA0z4GBxiEiDEzuGxUYewIjNjg0BGxkTnFZaMaiLeLo4GBkcWhIzkkAqQkEggceHw5HFkM2VRZJFlYebR2MP5v3cDSu5GJwWUDW9xG1hQXAFAmKZU=' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGz8ABEAAAAA09gAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC8AAAA0AsQC9UdQT1MAAAGwAAATuAAANLwBEyF1R1NVQgAAFWgAAAIWAAAEZqfk0PVPUy8yAAAXgAAAAFAAAABgaNCCw2NtYXAAABfQAAABkwAAAkQk8AV7Y3Z0IAAAGWQAAABiAAAAugGiQq9mcGdtAAAZyAAABZcAAAvNb3/BHGdhc3AAAB9gAAAACAAAAAgAAAAQZ2x5ZgAAH2gAAESvAAB8yu28l3FoZWFkAABkGAAAADYAAAA2BmibVWhoZWEAAGRQAAAAIAAAACQHMQRzaG10eAAAZHAAAAJDAAAEImBmMbxsb2NhAABmtAAAAhoAAAIaflxdR21heHAAAGjQAAAAIAAAACACjgzgbmFtZQAAaPAAAACdAAABKBQEL8lwb3N0AABpkAAAAsMAAAS9pi3QFXByZ...w76a3jVVUpJzXkBsRtNQoHWTV2mt2UusrulbnIrkvAXNBDFtTVIB8Uoau4pSruq4q7qq2dHpQADUAT0IJ5ra0yPUAfMACMFY6pOtegV/9D7UtTZx72tTeXI4JdcUXh7Pb67D7I/S05AwjAAiYsNie6WOwc4MiYCORSEx+ZExuCvQpiNSRmAdL8wDs2AslUOgp8HfnSYyfCYjrE7w8QDucyS0aXjH0zGk7FX991RgON6L7Qma6pQ+SzA0Qw1x9+HgNFtrBk+F9RsmDpTShvNJL4BDWtP8IAeAFj8N7BcCIoYiMjY1/kBsadHAwcDMkFGxnYnLZFMFgwMLAyaIE4DjzeHPYs+mzKLOIsrBxQoVA2VyZzFk0mWSawELfTPmEGAQYeBk4GNpBGTqCYgNM+BgcYhIgxM7hsVGHsCIzY4NARsZE5xWWjGoi3i6OBgZHFoSM5JAKkJBIIHHh8ORxZDNlUWSRZWHm0djD+b93A0ruRicFlA1vcRtYUFwBQJimV' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGvEABEAAAAA0agAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC8AAAA0AsQC9UdQT1MAAAGwAAATnQAANLwGhihmR1NVQgAAFVAAAAIWAAAEZqfk0PVPUy8yAAAXaAAAAE4AAABgaTSDymNtYXAAABe4AAABkwAAAkQk8AV7Y3Z0IAAAGUwAAABiAAAAugJwQ3lmcGdtAAAZsAAABZcAAAvNb3/BHGdhc3AAAB9IAAAACAAAAAgAAAAQZ2x5ZgAAH1AAAEOIAAB6jmYk+R5oZWFkAABi2AAAADYAAAA2BoebUWhoZWEAAGMQAAAAIAAAACQHUgSVaG10eAAAYzAAAAJGAAAEImg2Kylsb2NhAABleAAAAhoAAAIaOTEY3W1heHAAAGeUAAAAIAAAACACwAz0bmFtZQAAZ7QAAACiAAABNBUeMO1wb3N0AABoWAAAAsMAAAS9pi3QFXByZ...w76a3jVVUpJzXkBsRtNQoHWTV2mt2UusrulbnIrkvAXNBDFtTVIB8Uoau4pSruq4q7qq2dHpQADUAT0IJ5ra0yPUAfMACMFY6pOtegV/9D7UtTZx72tTeXI4JdcUXh7Pb67D7I/S05AwjAAiYsNie6WOwc4MiYCORSEx+ZExuCvQpiNSRmAdL8wDs2AslUOgp8HfnSYyfCYjrE7w8QDucyS0aXjH0zGk7FX991RgON6L7Qma6pQ+SzA0Qw1x9+HgNFtrBk+F9RsmDpTShvNJL4BDWtP8IAeAFj8N7BcCIoYiMjY1/kBsadHAwcDMkFGxnYnLZFMFgwMLAyaIE4DjzeHPYs+mzKLOIsrBxQoVA2VyZzFk0mWSawELfTPmEGAQYeBk4GNpBGTqCYgNM+BgcYhIgxM7hsVGHsCIzY4NARsZE5xWWjGoi3i6OBgZHFoSM5JAKkJBIIHHh8ORxZDNlUWSRZWHm0djD+b93A0ruRicFlA1vcRtYUFwBQJimV' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAG1gABEAAAAA1pAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC8AAAA0AsQC9UdQT1MAAAGwAAATbgAANLZecgbjR1NVQgAAFSAAAAIWAAAEZqfk0PVPUy8yAAAXOAAAAFAAAABgaZiEs2NtYXAAABeIAAABkwAAAkQk8AV7Y3Z0IAAAGRwAAABkAAAAugNSRFZmcGdtAAAZgAAABZcAAAvNb3/BHGdhc3AAAB8YAAAACAAAAAgAAAAQZ2x5ZgAAHyAAAEVdAAB/iLdLXbRoZWFkAABkgAAAADYAAAA2BqubS2hoZWEAAGS4AAAAIAAAACQHdQS4aG10eAAAZNgAAAJBAAAEInDeJANsb2NhAABnHAAAAhoAAAIa+cTXSm1heHAAAGk4AAAAIAAAACACwAzxbmFtZQAAaVgAAACbAAABKBPHL31wb3N0AABp9AAAAsMAAAS9pi3QFXByZ...mt41VVKSc15AbEbTUKB1k1dprdlLrK7pW5yK5LwFzQQxbU1SAfFKGruKUq7quKu6qtnR6UAA1AE9CCea2tMj1AHzAAjBWOqTrXoFf/Q+1LU2ce9rU3lyOCXXFF4ez2+uw+yP0tOQMIwAImLDYnuljsHODImAjkUhMfmRMbgr0KYjUkZgHS/MA7NgLJVDoKfB350mMnwmI6xO8PEA7nMktGl4x9MxpOxV/fdUYDjei+0JmuqUPkswNEMNcffh4DRbawZPhfUbJg6U0obzSS+AQ1rT/CAHgBY/DewXAiKGIjI2Nf5AbGnRwMHAzJBRsZ2Jy2RTBYMDCwMmiBOA483hz2LPpsyiziLKwcUKFQNlcmcxZNJlkmsBC30z5hBgEGHgZOBjaQRk6gmIDTPgYHGISIMTO4bFRh7AiM2ODQEbGROcVloxqIt4ujgYGRxaEjOSQCpCQSCBx4fDkcWQzZVFkkWVh5tHYw/m/dwNK7kYnBZQNb3EbWFBcAUCYplQ==' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAJd6ABIAAAABdegAAAAAAACWIAAAAVoAAAKDAAAAAAAAAABHUE9TAACDdAAAEl0AAGmo7AqzQkdTVUIAAJXUAAAASgAAAFjau94BTFRTSAAAgzwAAAA4AAABSbMu+GZPUy8yAAAB7AAAAFoAAABgq5xp5lZETVgAAH2EAAADdwAABeBvDHaKY21hcAAAAkgAAAE7AAADVCy12qZjdnQgAACBDAAAAD4AAAA+Aq0JQWZwZ20AAIFMAAABAgAAAXMGWZw3Z2FzcAAAgPwAAAAQAAAAEAATAAlnbHlmAAANwAAAb8MAAOvMFZp2kmhlYWQAAAG0AAAANgAAADb6oXEzaGhlYQAAA4QAAAAhAAAAJAdwBB9obXR4AAADqAAAAr8AAAUUlCcxVmxvY2EAAAs0AAACjAAAAoxSy42GbWF4cAAAAZQAAAAgAAAAIANdBEFuYW1lAAAGaAAAAXwAAANEtvYOJHBvc...hAORYwzQHEUmCaiYGNgYfREUj7MDoBSX+gKCODJwCKqQdxAAB42n2S3WvCMBTF3/tXXPK0wUyqgzGkrYyBL8Mx0LHn2NxqMB9dkrb636/xa4pskIdAzj3n/C7JJlutoEXnpTU5GdKUAJrSCmlWOflcTAfPZFIkmcbABQ/8WlpkjZHfDUoBUuSktJrqXWVN8FRzt/FSW+OtobWzW6n5wNiWD7ytAvWo5dIqQbtqI8OIVm/NiLAia9EI68BwjTmZ7abRi0DjVE7WIdRjxrquO4f0gSxOCfSlk3XoixVZwG0AxWN/NKRYrKWH/nD4wmUcg8pZDUdvCtNGKZCmsk7zaAB8aZsAIY5F+Tj5I3h/Y5ec7IaTJRmLfYqMXXVUskTj8V+wVmJ31E1Uv97h02MaYUtb75xcrcMN6uvpBe7Ke5j1zWB+rPYAo3SYUnjpYfcSDw49uhYFPVe8dHZcYGS7Cfk4MMJ7zwjznvGw3PMA2Oo6+tf/wpSdPlSR/ADe7uPx' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAKD5ABIAAAABjrQAAAAAAACfoAAAAVkAAAKCAAAAAAAAAABHUE9TAACLrAAAE6UAAGmo3w+nD0dTVUIAAJ9UAAAASgAAAFjau94BTFRTSAAAi3wAAAAvAAABSW5js1FPUy8yAAAB7AAAAFoAAABgq5xp3FZETVgAAIXAAAADdwAABeBvDHaKY21hcAAAAkgAAAE7AAADVCy12qZjdnQgAACJSAAAADgAAAA4BiEDumZwZ20AAImAAAABAgAAAXMGWZw3Z2FzcAAAiTgAAAAQAAAAEAAaAAlnbHlmAAANvAAAeAEAAQTc9heJHWhlYWQAAAG0AAAANgAAADb6hXFDaGhlYQAAA4QAAAAhAAAAJAdUBBdobXR4AAADqAAAArsAAAUUhLg2g2xvY2EAAAswAAACjAAAAowhImIQbWF4cAAAAZQAAAAgAAAAIANdBGZuYW1lAAAGZAAAAXwAAAM9wTILRnBvc...A5FjDNAcRSYJqJgY2Bh9ERSPswOgFJf6AoI4MnAIqpB3EAAHjafZLda8IwFMXf+1dc8rTBTKqDMaStjIEvwzHQsefY3GowH12Stvrfr/FrimyQh0DOPef8LskmW62gReelNTkZ0pQAmtIKaVY5+VxMB89kUiSZxsAFD/xaWmSNkd8NSgFS5KS0mupdZU3wVHO38VJb462htbNbqfnA2JYPvK0CdbhqFHe0qzYyjGj11owIK7IWjbAODNeYk9luGq0INE7lZB1CPWas67pzRp/H4pRAXzpZh75XkQXcBlA81kdDisVaeugPhy9cxjGonNVw9KYwbZQCaSrrNI8GwJe2CRDiWJSPkz+C9zd2icluMFmSsdinyNhVRyVLNB7/BWsldkfdRPXbHT49phG2tPXOydU63KC+nl7grryHWd8M5sdqDzBKhymFlx52L/Hg0KNrUdBzxUtnxwVGtpuQjwMjvPeMMO8ZD8s9D4CtrqN//S9M2ek/FckP9vfjlA==' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

settings:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIt0ABEAAAABQDwAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHUE9TAAABgAAACLoAABJKv3bHbEdTVUIAAAo8AAAAUwAAAHCOOI56T1MvMgAACpAAAABcAAAAYNmuqmljbWFwAAAK7AAAAIEAAAC0jBiQAGN2dCAAAAtwAAAAKwAAAC4G9xijZnBnbQAAC5wAAAOBAAAG5XJackBnYXNwAAAPIAAAAAwAAAAMABIAGGdseWYAAA8sAABYNwAAw2DADxfjaGVhZAAAZ2QAAAA2AAAANvyc8iNoaGVhAABnnAAAAB8AAAAkD7YHdWhtdHgAAGe8AAACCwAAA25yNU6fa2VybgAAacgAAB0cAABXGD87P7Jsb2NhAACG5AAAAb4AAAG+rN9/im1heHAAAIikAAAAIAAAACAB1wf5bmFtZQAAiMQAAADJAAABeBwnOJpwb3N0AACJkAAAAZYAAAJBVuQNNnByZ...CRYydOnTl34dKVazdu3bn34NGTZy9evXn34dOXbz9+/fkXEhYRFROXkCwRBA/LYUABAAD3Td3+ZW3bnTp2LrFt2+bEPMdOztkNF+T65bd2KTb8ESNSumJ54aIIy35KdORYtFT/9Fp3KEOJUyfO5Cg3bFCFm26Jc9uoO4aMmDRm3IRNd82YMq3SPQfizZs1575tu/576IFHnnjsqSzPvPDcS6+88dpb72x576MPPvnisybZvvnqux927GmxoEq1RWuW1KjVoFGfOvX6/dWhU1u4ZF+X7nA5XAlXw7VwPdw4H4tfqI8Pe2lepoGBowGUdmFxLS3K50ovSixL1UtOLE7lTclMLUotziwG87gSk0tLIBL8yZlFyaW5aTmpFWA+Z1FmXjpEUUlmTgpEEQDcm4MFAAC5CAAIAGMgsAEjRCCwAyNwsBRFICCwKGBmIIpVWLACJWGwAUVjI2KwAiNEswkKAwIrswsQAwIrsxEWAwIrWbIEKAZFUkSzCxAEAisA' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".
"

**Comment by utarit** [comment] 2018-06-18 15:50
I have the same error

**Comment by MrcRjs** [comment] 2018-06-18 18:19
@Bouncey do you know if this bug is related to the [verifyCert()](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/boot/certificate.js#L255) function?
f916204b

**Comment by igorasilveira** [comment] 2018-06-19 10:58
On the same issue here...

**Comment by mouri11** [comment] 2018-06-21 05:08
I am having the same issue here. Posted about it on freecodecamp forum [here](https://forum.freecodecamp.org/t/cannot-claim-certificate/199354/8?u=mouri11).
Errors on opening the settings page are as follows:
```
GET blob:https://www.freecodecamp.org/cbe97e53-af5e-4569-963f-0aa6937c5927 0 ()
splitSelector.splitSelector @ inject.preload.js:373
__webpack_require__ @ bootstrap 459d30130528313280ec:19
(anonymous) @ common.js:103
__webpack_require__ @ bootstrap 459d30130528313280ec:19
exports.textToRegExp @ bootstrap 459d30130528313280ec:62
(anonymous) @ bootstrap 459d30130528313280ec:62
```
```
createAlgoliasearch.js:107 Refused to connect to 'https://qmjyl5wyti-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.26.0%3Breact-instantsearch%205.0.1%3BJS%20Helper%202.24.0&x-algolia-application-id=QMJYL5WYTI&x-algolia-api-key=4318af87aa3ce128708f1153556c6108' because it violates the following Content Security Policy directive: "connect-src 'self' https://search.freecodecamp.org https://*.algolianet.com https://glitch.com https://*.glitch.com https://*.glitch.me https://*.cloudflare.com".

(anonymous) @ createAlgoliasearch.js:107
d._request @ createAlgoliasearch.js:59
n @ AlgoliaSearchCore.js:300
s._jsonRequest @ AlgoliaSearchCore.js:441
s.search @ AlgoliaSearchCore.js:595
m._search @ algoliasearch.helper.js:1204
m.search @ algoliasearch.helper.js:150
O @ createInstantSearchManager.js:179
(anonymous) @ createInstantSearchManager.js:252
(anonymous) @ createWidgetsManager.js:24
Promise.then (async)
t.defer @ utils.js:73
o @ createWidgetsManager.js:22
registerWidget @ createWidgetsManager.js:31
AlgoliaSearchBox(Translatable(t)) @ createConnector.js:110
_constructComponentWithoutOwner @ ReactCompositeComponent.js:295
_constructComponent @ ReactCompositeComponent.js:282
mountComponent @ ReactCompositeComponent.js:185
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createContentMarkup @ ReactDOMComponent.js:657
mountComponent @ ReactDOMComponent.js:524
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
T @ ReactMount.js:102
perform @ Transaction.js:141
k @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
(anonymous) @ render.js:24
(anonymous) @ rx.all.js:63
t @ rx.all.js:11772
n._subscribe @ rx.all.js:11789
vt.subscribe.vt.forEach @ rx.all.js:2034
t.next @ rx.all.js:3675
t.onNext @ rx.all.js:1762
(anonymous) @ rx.all.js:63
n.next @ rx.all.js:11810
t.onNext @ rx.all.js:1762
n.next @ rx.all.js:2145
t.onNext @ rx.all.js:1762
(anonymous) @ rx.all.js:63
n.next @ rx.all.js:11810
t.onNext @ rx.all.js:1762
n.next @ rx.all.js:4571
t.onNext @ rx.all.js:1762
(anonymous) @ rx.all.js:63
n.next @ rx.all.js:11810
t.onNext @ rx.all.js:1762
n.next @ rx.all.js:4571
t.onNext @ rx.all.js:1762
(anonymous) @ rx.all.js:63
n.next @ rx.all.js:11810
t.onNext @ rx.all.js:1762
(anonymous) @ rx.all.js:2760
t @ rx.all.js:1051
Ve.invokeCore @ rx.all.js:980
Ve.invoke @ rx.all.js:968
n @ rx.all.js:1209
(anonymous) @ rx.all.js:63
r.schedule @ rx.all.js:1225
n._subscribe @ rx.all.js:2095
vt.subscribe.vt.forEach @ rx.all.js:2034
(anonymous) @ index.js:70
n @ bootstrap 5a88bedc3e2a906faaba:19
(anonymous) @ bootstrap 5a88bedc3e2a906faaba:62
(anonymous) @ bootstrap 5a88bedc3e2a906faaba:62
```
Using Chrome 67.0.3396.87 (Official Build) (64-bit)
@QuincyLarson It has been quite long since this problem has arisen. Please look into it.

**Comment by sdabhi23** [comment] 2018-06-21 07:12
Facing the same problem. Please have a look @QuincyLarson @raisedadead

**Comment by janosimas** [comment] 2018-06-21 13:43
@raisedadead I see you closed the issue. is it online already? 
It didn't work for me, I tried claiming and completing the projects again and claiming.

**Comment by QuincyLarson** [comment] 2018-06-21 14:17
@Bouncey Can you confirm whether this has been deployed yet? It sounds like people are still having trouble claiming this certification.

**Comment by raisedadead** [comment] 2018-06-21 14:36
@janosimas thanks for reaching out. The build is in progress. It typically can take a few ours for us to deploy things as we QA and merge

**Comment by Bouncey** [comment] 2018-06-21 14:37
This process can be tracked on freecodecamp/learn#190. It takes around ~25 minutes from the PR being merged in learn until it is live.

**Comment by sagarjaspal** [comment] 2018-06-21 17:46
Still having the same problem!!

**Comment by igorasilveira** [comment] 2018-06-21 23:31
Same here also still..

**Comment by AndrewJBateman** [comment] 2018-06-22 07:45
Still having the same problem.

**Comment by Bouncey** [comment] 2018-06-22 09:21
Hi @AndrewJBateman, I have just checked your account and I can't see why you wouldn't be able to claim the certification.

If you are still unsuccessful, please let me know.

**Comment by PABlond** [comment] 2018-06-22 09:51
I am facing the same problem.

**Comment by sdabhi23** [comment] 2018-06-22 10:50
Still having the same problem!

**Comment by Bouncey** [comment] 2018-06-22 10:54
Reopening

**Comment by Bouncey** [comment] 2018-06-22 11:54
@igorasilveria @AndrewJBateman @PABlond @sdabhi23, we have pushed some fixes in to production. Can you please confirm if your issue is fixed or not?

Many thanks

**Comment by PABlond** [comment] 2018-06-22 11:58
Well done! This issue is resolved for me !

**Comment by janosimas** [comment] 2018-06-22 12:10
works for me too

**Comment by Bouncey** [comment] 2018-06-22 12:17
Woo Hoo!! :tada: :tada: 

Great work everyone!

:sparkles: :sparkles: :sparkles: :sparkles:

**Closed by Bouncey** 2018-06-22 12:17 UTC
Labels: platform: server, type: bug, type: critical path

**Comment by mouri11** [comment] 2018-06-22 12:18
Successfully claimed certificate. Thanks.

**Comment by psitronic** [comment] 2018-06-22 12:37
@Bouncey I have just successfully claimed it. However, this morning (four hours ago) I could not do it ...

**Comment by Bouncey** [comment] 2018-06-22 12:53
@psitronic sorry about that.

This re-opening of this issue was caused by our production code being out of sync with the repositories. All is well now though :+1:

**Comment by sdabhi23** [comment] 2018-06-22 13:42
Resolved for me too!
