### ISSUE TITLE
Inifinite while loop not elegantly surfaced to user.

### ISSUE THREAD

**Issue by vanillakernel** [FreeCodeCamp/FreeCodeCamp#4732] opened 2015-11-26 14:12 UTC
When the while loop is infinite (say by not incrementing the iterator), the error is not surfaced, and the last test does not appear.The current behavior does not indicate that there is a problem with the code; the experience just breaks silently.

This may be expected behavior, as the infinite evaluation will preclude the second test running, but there may be a more elegant way to surface this issue. Let me know how best to follow up on this, or if it is duplicated elsewhere.

![screen shot 2015-11-26 at 6 13 13 am](https://cloud.githubusercontent.com/assets/13111622/11424788/cf92a53c-9404-11e5-90f5-e58f2e443b24.png)

Challenge [Waypoint: Iterate with JavaScript While Loops](http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops?solution=var%20myArray%20%3D%20%5B%5D%3B%0Avar%20i%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Awhile%20(i%20%3C%205)%7B%0A%20%20myArray.push(i)%3B%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof(myArray)%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myArray%3B%7D)()%3B%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myArray = [];
var i = 0;

// Only change code below this line.

while (i < 5){
  myArray.push(i);
  
}

// Only change code above this line.

if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}


```

**Comment by ltegman** [comment] 2015-11-26 17:09
Thanks for the report! We are aware of the problem and hope to have a solution in the near future. Closing as a duplicate of #3732

Thanks and happy coding!

**Closed by ltegman** 2015-11-26 17:09 UTC

**Comment by vanillakernel** [comment] 2015-11-26 17:16
Thanks for the update!
