### ISSUE TITLE
Update my Email button strange hover effect

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9818] opened 2016-07-20 18:54 UTC
![](https://www.evernote.com/l/Ar8YI0Qxs9pLL4EOxRD_kV-sFIFqaGZVIIgB/image.png)

**Comment by raisedadead** [comment] 2016-07-20 18:58
Duplicate of #9817

**Closed by raisedadead** 2016-07-20 18:58 UTC
Labels: beta
