### ISSUE TITLE
Test fails on "Only change the first line"

### ISSUE THREAD

**Issue by HosfordDotMe** [freeCodeCamp/freeCodeCamp#13103] opened 2017-02-03 06:01 UTC
Challenge [subtract-one-number-from-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/subtract-one-number-from-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
This fails due to the difference in lines even if code has not been changed. It also fails when changing 0 to 33.

```js


var difference = 45 - 0;



```

<img width="710" alt="screen shot 2017-02-03 at 1 00 14 am" src="https://cloud.githubusercontent.com/assets/555977/22581176/30f9ca32-e9ac-11e6-89b2-99691dde105e.png">
<img width="693" alt="screen shot 2017-02-03 at 12 59 49 am" src="https://cloud.githubusercontent.com/assets/555977/22581177/31024018-e9ac-11e6-8f18-446c52256cd4.png">

**Comment by HosfordDotMe** [comment] 2017-02-03 06:02
#10633 Previously discussed here.

**Comment by hisener** [comment] 2017-02-03 07:37
I can reproduce this one. Related file: [basic-javascript](seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json)

**Comment by dnahol** [comment] 2017-02-03 09:13
I'll take this one!

**Comment by dnahol** [comment] 2017-02-03 09:57
Can someone help me understand the purpose of the "Only change first line" test? I don't see a use for it. 
"assert((code).match(/difference/g).length === 1,'message: Only change the first line');"

So I took it out. And everything works fine now. 
<img width="1125" alt="screen shot 2017-02-03 at 1 51 44 am" src="https://cloud.githubusercontent.com/assets/2976514/22586895/0e7e56e6-e9b4-11e6-9c9b-bc8ccf286043.png">

**Comment by hisener** [comment] 2017-02-03 10:44
@dnahol The previous challenge, [Add Two Numbers](http://beta.freecodecamp.com/en/challenges/basic-javascript/add-two-numbers-with-javascript), doesn't have a test case like this one. These two challenges look like very similar. I think it's ok.

**Comment by dnahol** [comment] 2017-02-03 10:57
Thanks @hisener. That's a good point. I will remove it then.

**Comment by erictleung** [comment] 2017-02-03 16:00
This issue stems probably because the "solution" in the `.json` file is included in the code the regex checks (see similar discussion https://github.com/freeCodeCamp/freeCodeCamp/pull/11987#discussion_r92950694). The code is to check that you don't just create another variable `difference` and assign it to 12. So I think it's necessary. Just need to either remove the solution or change the test to check for two instances.

**Comment by dnahol** [comment] 2017-02-03 16:59
@erictleung Thank you! That makes sense!

**Comment by hisener** [comment] 2017-02-03 17:00
@erictleung It makes sense, then let's make it 3 and add this test case to addition, multiplication, division challenges.

**Comment by hisener** [comment] 2017-02-09 15:14
@dnahol I can take this if you don't?

**Comment by dnahol** [comment] 2017-02-09 17:31
@hisener I got it. But maybe you want to take the others you mentioned?

**Comment by hisener** [comment] 2017-02-10 11:18
@dnahol I think all changes make more sense into a single commit.

**Comment by macengr** [comment] 2017-03-31 23:21
This still is a problem, as of 31 March 2017

**Comment by mapedersen** [comment] 2017-04-16 14:20
This is still a problem!

**Comment by Ellyria** [comment] 2017-05-24 12:40
This is still a problem on May 24. Deleting the blank first line so that the code is on the first line doesn't solve it either.

**Comment by rcohane** [comment] 2017-11-06 19:56
There are different bugs in the live and beta version of the site. On the live site, when you change a line other than the first one and don't reference the "difference" variable, "Only change the first line" is still green. If you do use the "difference" variable in a different line in the program then the checkpoints work properly.

![screen shot 2017-11-06 at 2 50 31 pm](https://user-images.githubusercontent.com/21317235/32460789-dd69f3a8-c301-11e7-968a-7a7b2a1fefd0.png)
![screen shot 2017-11-06 at 2 50 15 pm](https://user-images.githubusercontent.com/21317235/32460791-dea71c5a-c301-11e7-95aa-4139a6cd78db.png)




On the beta version, if you only subtract one number from 45 and it's the wrong number, "Only subtract one number from 45" is still red.

![screen shot 2017-11-06 at 2 50 52 pm](https://user-images.githubusercontent.com/21317235/32460808-ea6352de-c301-11e7-964c-a77c2faa6dac.png)

**Comment by rcohane** [comment] 2017-12-06 04:19
I would like to work on the bug on the beta site. The bug has to do with the following test: 

`assert(/var\\s*difference\\s*=\\s*45\\s*-\\s*33;?/.test(code),'message: Only subtract one number from 45.');`

The test only allows for 33 to be subtracted from 45, but the test is just supposed to be checking that one number is subtracted from 45. The actual number shouldn't matter since the value of the difference variable is already being checked in the other test

**Comment by raisedadead** [comment] 2017-12-10 07:16
@rcohane are you still interested in fixing this?

**Comment by rcohane** [comment] 2017-12-10 15:09
@raisedadead Yes, I changed the test to:

`"assert(/var\\s*difference\\s*=\\s*45\\s*-\\s*[0-9]*;{1}/.test(code),'message: Only subtract one number from 45.');". `

Now it checks that only one number is subtracted from 45 and that number doesn't have to be 33. I'll create a pull request.

**Comment by raisedadead** [comment] 2017-12-10 15:13
@rcohane awseome. thanks for working on this.

**Closed** 2017-12-11 20:37 UTC
Labels: beta, help wanted

**Comment by theshivanjali** [comment] 2019-02-25 09:15
![image](https://user-images.githubusercontent.com/24565124/53326533-d86daa80-390b-11e9-80c2-b55fa1868e76.png)
i am still getting an issue. what's the solution for this problem?

**Comment by rcohane** [comment] 2019-02-25 16:03
@theshivanjali please try removing the space between the 33 and semicolon

**Comment by raisedadead** [comment] 2019-02-25 16:36
Hi @theshivanjali 

Thanks for reporting this issue. 

Please use the [Chat Rooms](https://www.freecodecamp.org/forum/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://www.freecodecamp.org/forum) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
