### ISSUE TITLE
Multiple line commenting

### ISSUE THREAD

**Issue by SpudMillions** [FreeCodeCamp/FreeCodeCamp#3178] opened 2015-09-08 22:40 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When running the test on a multiple line comment such as:

/* 
comment 
*/

the code does not pass.  /* comments */ are usually used when you want to span a comment across multiple lines, this would be a great area to talk about the difference between the two.  To fix the bug you could add your regex expression to check continuous lines for the /* */ comment

**Comment by BerkeleyTrue** [comment] 2015-09-08 23:19
Closing as duplicate of #1999

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-09-08 23:19 UTC
