### ISSUE TITLE
The results aren't correct

### ISSUE THREAD

**Issue by diklabero** [FreeCodeCamp/FreeCodeCamp#8033] opened 2016-04-10 15:26 UTC
#### Challenge Name
Sum All Odd Fibonacci Numbers

https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

The results for the challenge aren't correct.
For example:
"sumFibs(75024) should return 60696." makes no sense,,, the sum result is smaller than the index number

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment] 2016-04-10 16:12
@diklabero you are not only adding up only Fibonacci numbers, but you are also only adding the odd ones. So your numbers you are actually adding up are less than you think. Closing as not a bug with the site. Happy coding!

**Closed by erictleung** 2016-04-10 16:12 UTC

**Comment by diklabero** [comment] 2016-04-10 16:25
Sorry, now I understand.
I thought that the argument is the position, not the number itself...
All clear now, thanks!
