### ISSUE TITLE
Developer News profiles doesn't show image in Twitter cards

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36500] opened 2019-07-24 04:30 UTC
When authors link to their Developer News profile, their profile image should be the image that appears in the tweet - or at least some sort of freeCodeCamp logo. Currently it just shows the broken image-style card instead of the full size Twitter card that our articles show.

<img width="1407" alt="David_Clinton_-_Developer_News_and_Card_Validator___Twitter_Developers" src="https://user-images.githubusercontent.com/985197/61765206-ba648300-ada1-11e9-8e29-9cfb1858ee6f.png">

**Comment by raisedadead** [comment] 2019-07-25 09:25
Duplicate of https://github.com/freeCodeCamp/news-theme/issues/18

**Closed by raisedadead** 2019-07-25 09:25 UTC
