### ISSUE TITLE
Create a new p element around your a element

### ISSUE THREAD

**Issue by madpopTechie** [freeCodeCamp/freeCodeCamp#14100] opened 2017-03-26 16:53 UTC
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%3Cp%3Eview%20more%20%3Ca%20href%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3E%0A%20%20%20%20cat%20photos%0A%20%20%3C%2Fa%3E%0Afor%20you%20to%20follow%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<p>view more <a href="http://www.freecatphotoapp.com">
    cat photos
  </a>
for you to follow</p>
```

**Comment by lynxlynxlynx** [comment] 2017-03-26 17:02
No bug here, your code is lacking. Either reset to get the whole template back and restart, or add another (the "new" in the instructions) paragraph to your snippet.

**Comment by Dayfiri** [comment] 2017-03-26 19:24
@madpopTechie Hello there.
The code is pretty sensitive in what it asks from you. It wont lets you pass because you need to write
`View more ` instead of `view more `.
I passed the challenge right now so I'm sure it is not a bug.
For any future help that you need with exercises, feel free to ask at [help room](https://gitter.im/FreeCodeCamp/Help?source=all-rooms-list).
Happy coding ;)

**Comment by OFFLlNE** [comment] 2017-03-27 21:13
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Closed by OFFLlNE** 2017-03-27 21:13 UTC
