### ISSUE TITLE
Beta: Last 5 challenges in the ES6 section aren't working properly.

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15186] opened 2017-06-03 08:59 UTC
All those challenges are showing an error of "exports/require not defined". These challenges include

http://beta.freecodecamp.com/challenges/es6/understand-the-differences-between-import-and-require
http://beta.freecodecamp.com/challenges/es6/use-export-to-reuse-a-code-block
http://beta.freecodecamp.com/challenges/es6/use--to-import-everything-from-a-file
http://beta.freecodecamp.com/challenges/es6/create-an-export-fallback-with-export-default
http://beta.freecodecamp.com/challenges/es6/import-a-default-export

Here's the screenshot of what that error is - 

![image](https://cloud.githubusercontent.com/assets/29104610/26752234/b7e0fda2-4868-11e7-9c6d-88d8302e5d76.png)

**Comment by MiloATH** [comment] 2017-06-04 01:31
This is related to #14372.

**Comment by systimotic** [comment] 2017-09-04 12:41
Thanks for reporting and looking into this issue!
I'm closing this as a duplicate of #14372. If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Happy coding!

**Closed by systimotic** 2017-09-04 12:41 UTC
Labels: beta
