### ISSUE TITLE
Validate US Telephone numbers has a testing error

### ISSUE THREAD

**Issue by BleedingEnergy** [FreeCodeCamp/FreeCodeCamp#12092] opened 2016-12-17 23:20 UTC
#### Challenge Name
Validate US Telephone numbers
https://www.freecodecamp.com/challenges/validate-us-telephone-numbers

#### Issue Description
One of the tests contains a number, that is correct by format, but should result in false. The reason seems to be, that this specific area code prefix does not exist according to this overview: http://www.allareacodes.com/650

Either the challenge needs to be extended into including external databases or the test needs to be adapted.

#### Browser Information
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by spieg** [comment] 2016-12-17 23:27
Is it in the specs to test for area codes? 
Now that is a bit much because I think the specs aren't all that great.
My feeling is, if it;s not in the specs, it should pass the test.
Otherwise you're testing the specs, not the code. And in the real world that would be great, but not here.

**Comment by raisedadead** [comment] 2016-12-18 06:43
Hi @BleedingEnergy, thanks for reporting!

> Challenge 312 

Challenges are not numbered those are brownie points, which you earn by solving challenges and helping people in the chat rooms.

And @spieg you are perfectly correct in the argument. The aim of the challenge in not to be 'factually correct', we are aiming to teach a concept. 

I am afraid we will close this a wont fix.

Happy coding!

**Comment by BleedingEnergy** [comment] 2016-12-21 17:24
Hi,
just in case I was missunderstood, I would like to reformulate the issue: 

One of the tests is a number, that is invalid in the real world (since the area code prefix does not exist), but correct by testing against the concept. It should therefore pass the test, but it doesn't. 

The reason for this seems to be, that the compared output of the test is taken from a real world number test, which includes the databases for valid numbers. 

I would understand, the won't fix closing, if it were the other way around. Would be great, if you could check again :-)

**Comment by raisedadead** [comment] 2016-12-21 18:49
Hi @BleedingEnergy,

Apologies, but yes the opening post leads to the analogy that we made prior closing.
We would be glad to re-open this thread and continue the discussion, mind pointing me to the exact test case, with actual and expected behaviours.

Thanks.

**Comment by BleedingEnergy** [comment] 2016-12-22 11:22
Hi raisedadead,
upon reviewing my code and checking the testcase `(telephoneCheck("(6505552368)")` should return `false)`, I noticed the additional brackets `"(number)"`. They were the reason the testcase should resultu in false.

However, if you could change the number inside of the brackets from 65055**5**2368 to 65055**6**2368, this might prevent the error from happening to someone else. 555 is not a valid area prefix for 650, while 556 is :-)

**Comment by raisedadead** [comment] 2016-12-22 11:44
@FreeCodeCamp/moderators can any one tag help wanted, upon analyzing as valid change?

**Comment by systimotic** [comment] 2016-12-23 22:37
Hello humans! I hope you're all having a good day.
It took me a bit to understand what was going on, but I could see how this could cause confusion if you miss that the brackets are what should make the test fail.
While I don't think changing it is essential, I believe it could be a minor improvement. It could prevent people from being in the same situation as @BleedingEnergy, and I don't see how it could cause issues.

**Comment by yesthatguy** [comment] 2017-01-02 21:19
I'll take this and make the minor change.

**Closed** 2017-01-06 06:03 UTC
Labels: help wanted
