### ISSUE TITLE
Issue in CSS Flexbox: Add Flex Superpowers to the Tweet Embed

### ISSUE THREAD

**Issue by nosapaath** [freeCodeCamp/freeCodeCamp#40276] opened 2020-11-20 20:38 UTC
**Describe your problem and how to reproduce it:**
We are required to modify with the .follow-btn class in this lesson, however, there is already a .follow-btn class in the root with a !important that sets the content display to none; 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 86.0.4240.198 (Official Build) (x86_64)
* Operating System: MAC OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="206" alt="Screen Shot 2020-11-20 at 12 36 24 PM" src="https://user-images.githubusercontent.com/39566508/99847589-2806f780-2b2d-11eb-9e02-b33e5d2a1e9f.png">
<img width="280" alt="Screen Shot 2020-11-20 at 12 35 34 PM" src="https://user-images.githubusercontent.com/39566508/99847602-2ccbab80-2b2d-11eb-92c4-406358d26635.png">

**Comment by Sky020** [comment] 2020-11-20 22:34
Hello there,

Thank you, for taking the time to open this. However, there is already an issue about this, and a PR awaiting to close it. So, I am closing this as a duplicate of #39608

**Closed by Sky020** 2020-11-20 22:34 UTC
Labels: scope: learn, status: needs help for triage

**Comment by nosapaath** [comment] 2020-11-20 23:18
Sweet! Thanks for taking the time to let me know.
Nosa
