### ISSUE TITLE
Alternatives to open weather api

### ISSUE THREAD

**Issue by Lapz** [freeCodeCamp/freeCodeCamp#12514] opened 2017-01-13 20:54 UTC
#### Challenge Name

[https://www.freecodecamp.com/challenges/show-the-local-weather](url)

#### Issue Description

For the weather challenge it is recommend to use the open weather api but when using the service on google Chrome the content will not be served on codepen.io due to new security changes in Chrome. So I suggest that we look for alternatives.

#### Browser Information

Browser Name, Version: 
Google Chrome	55.0.2883.95 (Official Build) (64-bit)

![security](https://cloud.githubusercontent.com/assets/19998186/21945197/d870155e-d9d1-11e6-8958-a240a7863ef5.jpeg)

**Comment by erictleung** [comment] 2017-01-13 23:09
@Lapz thanks for the issue. I think one way around this is to use the `http` version of the codepen URL. This, I think, will allow the api to work. But it might be nice to suggest other alternatives as well. I was able to use [Wunderground's API](https://english.wunderground.com/weather/api/) with no issues. I'll leave this issue open for discussion.

**Comment by raisedadead** [comment] 2017-01-14 05:43
Hey @erictleung closing this a duplicate of #9079

**Closed by raisedadead** 2017-01-14 05:43 UTC
Labels: discussing

**Comment by eghan** [comment] 2017-06-11 20:15
I think I have a solution over here -> https://github.com/freeCodeCamp/freeCodeCamp/issues/15320

could someone verify that this works ok and fits project goals?
