### ISSUE TITLE
Abbreviated hex colors not passing test (FCC Beta)

### ISSUE THREAD

**Issue by ivmilicevic** [freeCodeCamp/freeCodeCamp#15695] opened 2017-07-31 09:24 UTC
#### Challenge Name
Applied Visual Design: Create a Gradual CSS Linear Gradient
http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient

#### Issue Description

This challenge requires setting up linear gradient with starting color of #CCFFFF and end color of #FFCCCC, Abbreviated hex values of #CFF and #FCC respectively render correctly but don't pass built in tests. I don't know if this is desired behaviour, but challenge "Basic CSS: Use Abbreviated Hex Code" teaches that it is possible to use shorter color codes, but it is not recognized in later challenges.

#### Browser Information

* Browser Name, Version: Chrome 59, Opera 46
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by dhcodes** [comment] 2017-07-31 13:56
Closing as duplicate of #13871

**Closed by dhcodes** 2017-07-31 13:56 UTC
