### ISSUE TITLE
Heat Map Failing automated tests

### ISSUE THREAD

**Issue by TaraBryn** [freeCodeCamp/freeCodeCamp#45381] opened 2022-03-08 02:39 UTC
## Affected page

[testable-projects-fcc](https://github.com/freeCodeCamp/testable-projects-fcc) 

## Your code

```
yarn start
yarn test
```

## Expected behavior

I forked and cloned this repository, and after installing the dependencies and running `yarn start`, before making any changes to the code, I ran `yarn test` just to test it, and it failed number 9 right out of the box.

## Screenshots

![test-result-12-D3__Heat_Map-FINAL](https://user-images.githubusercontent.com/28311501/157155135-83261036-e956-4384-af55-a17f8cfc4d57.png)

## System

- Device: Desktop
- OS: WSL2 [Ubuntu 18.04]
- Browser: firefox
- Version: 97.0.2

**Comment by ShaunSHamilton** [comment] 2022-03-08 11:42
Hello there,

Thank you, for taking the time to open this. About 4 hours after you opened this, we merged a PR that affected that project.

Would you mind double-checking it is still failing?

**Comment by TaraBryn** [comment] 2022-03-08 12:33
Hello, @ShaunSHamilton I just updated my local copy and it's still giving me the same error

![test-result-12-D3__Heat_Map-FINAL](https://user-images.githubusercontent.com/28311501/157238950-b4be66b2-274d-4290-a40b-45517c386110.png)

**Comment by ShaunSHamilton** [comment] 2022-03-08 12:49
Thank you, for double-checking. Unfortunately, I am unable to reproduce any issues with the `Heat Map` project/tests.

I have tested on both the LTS for Firefox and Chrome.

Do you have any browser extensions with access to the webpage? Also, are you serving the bundle along with your page? Or, just using it as a module?

**Comment by TaraBryn** [comment] 2022-03-08 13:45
@ShaunSHamilton I don't think there would be any extensions interfering unless they come pre-packed with firefox. I'm brand new to linux, and I used `apt-get install firefox` to install it and was using it basically right out of the box (if I'm being honest, I don't even know how to open the program myself beyond using it as a tool for testing). As for serving the bundle, yes, I believe that's what `yarn start` does in the repository, no? Since I'm not particuarly familiar with linux it could well be a setting somewhere on my end.

**Comment by ShaunSHamilton** [comment] 2022-03-08 13:50
That all mostly sounds about right.

The only suggestion I can think of is for you to debug, by altering the tests to get more useful output, and see where what is going wrong.

Are you looking to contribute to the repo/project in any specific way (e.g. closing an issue)? If so, I recommend trying a different browser, and, if that does not work, potentially it might help working in an environment like Gitpod.

---

I am going to close this as device-specific, and we can reopen, if others encounter a similar issue.

**Closed by ShaunSHamilton** 2022-03-08 13:50 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
