### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/freecodecamp#632] opened 2015-05-27 11:25 UTC
Checkpoints still showing syntax errors...

![error](https://cloud.githubusercontent.com/assets/10119077/7834847/3111df3c-0439-11e5-9665-92ccfeca2115.PNG)

**Comment by terakilobyte** [comment] 2015-05-27 13:12
Thanks for the report. Closing this as it's a duplicate of #585

**Closed by terakilobyte** 2015-05-27 13:12 UTC
