### ISSUE TITLE
Testing issue ES6

### ISSUE THREAD

**Issue by traanhn** [freeCodeCamp/freeCodeCamp#14808] opened 2017-05-10 12:35 UTC
Challenge [use-export-to-reuse-a-code-block](http://beta.freecodecamp.com/en/challenges/es6/use-export-to-reuse-a-code-block) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


export const foo = "bar";
export const boo = "far";

```

**Comment by erictleung** [comment] 2017-05-10 16:19
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/14372. Happy coding!

**Closed by erictleung** 2017-05-10 16:19 UTC
