### ISSUE TITLE
Sign In button displays instead of Settings icon even when authenticated on Beta Site

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35347] opened 2019-02-22 07:54 UTC
I could not find the following issue reported yet regarding the beta site.

I notice if I have already authenticated, the `Sign In` button still shows on the main home page. When I click on `Learn`, I can immediately see I am logged in and have access to the Settings button. I would think the Settings button should show in place of the `Sign In` button once you have been authenticated. Is this a known issue?

You can see in the video below that I am already authenticated while on the Learn page (the Settings icon is in upper right-hand corner).  Next, I click on the freeCodeCamp logo and the `Sign In` button replaces the Settings icon.  Lastly, I click back on Learn and the Settings Button displays as it should.

![learn_freecodecamporggoogl](https://user-images.githubusercontent.com/5313213/53227732-f8fbe300-3633-11e9-90b4-ca5beb053e60.gif)

Just for comparison's sake, the following is what it looks like when authenticated in the current production site.  It is not the Settings icon, but it at least shows the word `Settings` instead of `Sign In`.

**Comment by Ensive** [comment] 2019-02-23 17:29
Looking into it

**Comment by Ensive** [comment] 2019-02-23 18:01
Hi @RandellDawson 
Looking at the code seems like it is intended behaviour.
After testing on production site, I found when you already signed in: clicking on "freecodecamp" logo won't lead you to a home page layout, but to the "welcome" layout. 

Looks like this:
![freecodecamp_production_behaviour_sign_in_vs_setttings](https://user-images.githubusercontent.com/3208083/53289726-6fb6ee80-37a2-11e9-8c58-3c364bb9ffbe.gif)

So, how do you expect to get this issue fixed? In which way:
• Redirecting to "welcome" layout
• Or to landing page, but with "settings" shown?

**Comment by raisedadead** [comment] 2019-02-23 18:23
> • Redirecting to "welcome" layout

This one please. Thanks.

**Comment by Ensive** [comment] 2019-02-24 06:23
@raisedadead 
Okay. I will take care.
Do you have an idea where should I start?

How shall we do the redirect:
• gatsby `navigate`
• Using <RedirectWelcome /> component
• just put a `/welcome` path on the logo when use is signed in (for internal pages)

What would you suggest?

**Comment by raisedadead** [comment] 2019-02-24 09:10
Let me confirm that for you.

Hey @Bouncey, just checking the user's signed in state from the actions and navigating them to `/welcome` on click should be the way to go here? Correct?

**Comment by Bouncey** [comment] 2019-02-24 21:40
This is the intended design and flow for the landing page. You would notice that if you are authenticated, clicking sign in navigates you directly to /welcome instead of taking you to Auth0.

cc/ @QuincyLarson for some clarification.

**Comment by RandellDawson** [comment] 2019-02-24 22:13
@Bouncey That is fine if that is intended.  I just noticed it because it seemed strange to me in my opinion.  On the production site it shows "Settings" if already authenticated and viewing the landing page.  I was just reporting that production and beta are behaving differently.

**Comment by Ensive** [comment] 2019-02-27 18:34
Okay. I will see what I can do with this one here.

**Comment by raisedadead** [comment] 2019-02-27 20:07
I am going to close this. @QuincyLarson please re-open if this is not intended behaviour.

**Closed by raisedadead** 2019-02-27 20:07 UTC
Labels: platform: client, release: next/beta, status: discussing
