### ISSUE TITLE
Refactor step 12 of HTML cat photo app project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54767] opened 2024-05-13 16:02 UTC
### Describe the Issue

We are still getting a ton of questions about how to do step 12 of the cat photo app project.
https://forum.freecodecamp.org/search?q=step%2012%20cat%20photo%20app%20%23html-css

So I am not entirely sure how to best update this.
Maybe there needs to be a different code example?
Maybe the hints need to be updated?

Maybe something else?

There are too many people lost on this step so I should be updated to make it clearer on what needs to be done.
So I am opening this up for discussion

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment] 2024-05-13 17:07
I'm really not sure at this point, but I've been wondering too. On one hand, the first step anywhere that asks for composition of knowledge instead of copy-paste with minor modification will be hard for users. On the other hand, the example at this point is pretty darn close to copy-paste with minor modification. I really am out of ideas of what to do here.

**Comment by hbar1st** [comment] 2024-05-13 19:23
if I may chime in on this one (I have chimed in before on this step). 
I'd like to see:
a step betw. steps 11 and 12 to ask for a 2nd link directly below the one created in step 11.
This will help them practice anchor tags by typing in what the line of code for the prior link did but with new words and targets

a step to create a paragraph element with some words (They should recall how to do this)

and then one more step to make them move the paragraph opening tag so it surrounds the links and the text 

and then step 12.

I guess I'm suggesting that we need more breakdown and revision for "nesting" and "links" and then combining them through edits and through a brand new composition as per step 12.

**Comment by jeremylt** [comment] 2024-05-13 19:36
I'm not sure if that helps or not? Note: I have noticed that users get a little annoyed when we ask them to create something and immediately delete it, so if we are going to make them create more paragraphs and links, maybe make it text that sticks around?

I think no matter what we do, we're doing to hit a lot of questions the very first time we ask users to combine two pieces of information since a lot of the early steps are pretty close to copy-paste of the examples. I don't know how much giving them more small examples does a lot to get them over that hurdle.

**Comment by hbar1st** [comment] 2024-05-13 20:16
hi Jeremy, I think I didn't suggest that we ask them to remove anything. Rather to add more code and 'move' code.
I've expressed this suggestion before in the past. I hope there is more openness to try to new suggestions at this point.

**Comment by jeremylt** [comment] 2024-05-13 20:19
Sure, and I'm participating in the discussion with my view of potential issues we may encounter when making a new round of changes to this Step

**Comment by jdwilkin4** [comment] 2024-05-13 20:48
So I looked at the legacy lesson of this here 
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

and it looks like it uses a similar example but then it breaks it down further on how it works.

so we could try that?

I tried looking through the forum and it looks like the legacy challenge got a lot of responses too.
So maybe this is just one of those things that will be confusing to beginners at first.

But maybe a walkthrough of the example like the legacy content did might help 🤔

**Comment by jeremylt** [comment] 2024-05-13 21:03
Hmm, larger explanations sorta fights the design of the smaller steps, right?

Maybe we rearrange things so they build the link into a paragraph in parts starting with the link instead of the paragraph.

Step 4) Change text to be "Everyone loves cute cats online!"

Step 11) Change anchor text to "cat photos"

Step 12) *new* Add the words "See more " before the anchor element and " in our gallery" after the anchor element

Step 13) *new* Add p tags to turn that into a paragraph

Step 14) *new* Turn the text "cute cats" into another link to a different picture like the current Step 12

Step 15) Continue with the current Step 14 (Don't need Step 13 anymore where we delete an old anchor)

Final code before proceeding to Step 14:
```html
<html>
  <body>
    <main>
      <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->
      <p>Everyone loves <a href="https://cdn.freecodecamp.org/curriculum/cat-photo-app/cute-cat.jpg">cute cats</a> online!</p>
      <p>See more <a href="https://freecatphotoapp.com">cat photos</a> in our gallery.</p>
      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
    </main>
  </body>
</html>
```

If we want to keep a step about deleting stuff, we can delete that comment after we have added the links

**Comment by jdwilkin4** [comment] 2024-05-13 21:10
I think that refactoring should work.

**Comment by jdwilkin4** [comment] 2024-05-13 21:19
I have opened this up for help wanted.

**Comment by tarun9142** [comment] 2024-05-14 01:52
I think a small screenshot of how the final text should look like will work.

**Comment by jeremylt** [comment] 2024-05-14 01:55
I don't think we should provide a screenshot of the answer. We already have an example there for users to look at and it's not quite enough.

**Comment by tarun9142** [comment] 2024-05-14 02:07
the problem is that the users have problem with what they have to do, with a screenshot they would know how the final result should look like and with the help of code example they would know how to do that, So i think a screenshot will be helpful

**Comment by jeremylt** [comment] 2024-05-14 02:10
No, we can't update the instructions to include a screenshot of the answer to copy.

**Comment by tarun9142** [comment] 2024-05-14 02:20
i am not asking to provide an answer to copy. We can provide a screenshot like this
![Screenshot 2024-05-14 074642](https://github.com/freeCodeCamp/freeCodeCamp/assets/79507487/c708ef0e-8c4c-4b71-8221-192e542ac167)

or we can provide a screenshot of whole page.

**Comment by jeremylt** [comment] 2024-05-14 02:28
Hmm, I'd be concerned about putting that in a screenshot. That's not super accessible.

**Comment by ilenia-magoni** [comment] 2024-05-14 11:03
We can add a quote block or something with a link example, but I am against a screenshot

**Comment by pyukey** [comment] 2024-05-22 02:40
I have a thought, although it involves a slight restructuring as to how the course is presented. The main reason I think people struggle on this step is that everything up to this point has been presented as you make the HTML tag and _then_ place contents in that tag, but here is the first time you ask them to make the _content first_ and then place it inside a tag.
Presenting this content-first mindset at the start of the course might help.
Very simply, we could have it as
**Step 1**: HTML content is what we wish to display on the website. `Cat photos`
**Step 2**: We place that content inside of tags to give it specific attributes. `<u> Cat photos </u>`
**Step 3**: We can repeat this process by nesting tags `<h1> <u> Cat photos </u> </h1>`
**Step 4**: Tags can be given attributes to specify more details `idk how to build on step 3`

Now, if they have the text `cat photos`, and they know the tag `<a>`, they should be able to see that you place the content inside the tag.

**Comment by anishlukk123** [comment] 2024-07-04 20:18
I have a thought, although it involves a slight restructuring as to how the course is presented. The main reason I think people struggle on this step is that everything up to this point has been presented as you make the HTML tag and then place contents in that tag, but here is the first time you ask them to make the content first and then place it inside a tag.
Presenting this content-first mindset at the start of the course might help.
Very simply, we could have it as
Step 1: HTML content is what we wish to display on the website. Cat photos
Step 2: We place that content inside of tags to give it specific attributes. <u> Cat photos </u>
Step 3: We can repeat this process by nesting tags <h1> <u> Cat photos </u> </h1>
Step 4: Tags can be given attributes to specify more details idk how to build on step 3

Now, if they have the text cat photos, and they know the tag <a>, they should be able to see that you place the content inside the tag.




has this been agreed to

**Comment by shah-azman-sakin-alam** [comment] 2024-07-06 19:45
I think it needs to be worded right and it should say to first put a anchor tag inside p like this <a></a> and to insert cat photos as is, and then outside the anchor tag on the right it should say to type " in our gallery" and in right at start of p tag to type "See more "

**Comment by jeremylt** [comment] 2024-07-06 20:13
> Hmm, larger explanations sorta fights the design of the smaller steps, right?
> 
> Maybe we rearrange things so they build the link into a paragraph in parts starting with the link instead of the paragraph.
> 
> Step 4) Change text to be "Everyone loves cute cats online!"
> 
> Step 11) Change anchor text to "cat photos"
> 
> Step 12) *new* Add the words "See more " before the anchor element and " in our gallery" after the anchor element
> 
> Step 13) *new* Add p tags to turn that into a paragraph
> 
> Step 14) *new* Turn the text "cute cats" into another link to a different picture like the current Step 12
> 
> Step 15) Continue with the current Step 14 (Don't need Step 13 anymore where we delete an old anchor)
> 
> Final code before proceeding to Step 14:
> ```html
> <html>
>   <body>
>     <main>
>       <h1>CatPhotoApp</h1>
>       <h2>Cat Photos</h2>
>       
>       <p>Everyone loves <a href="https://cdn.freecodecamp.org/curriculum/cat-photo-app/cute-cat.jpg">cute cats</a> online!</p>
>       <p>See more <a href="https://freecatphotoapp.com">cat photos</a> in our gallery.</p>
>       <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
>     </main>
>   </body>
> </html>
> ```
> 
> If we want to keep a step about deleting stuff, we can delete that comment after we have added the links

We agreed upon an approach here

**Comment by shah-azman-sakin-alam** [comment] 2024-07-06 23:40
> > Hmm, larger explanations sorta fights the design of the smaller steps, right?
> > Maybe we rearrange things so they build the link into a paragraph in parts starting with the link instead of the paragraph.
> > Step 4) Change text to be "Everyone loves cute cats online!"
> > Step 11) Change anchor text to "cat photos"
> > Step 12) _new_ Add the words "See more " before the anchor element and " in our gallery" after the anchor element
> > Step 13) _new_ Add p tags to turn that into a paragraph
> > Step 14) _new_ Turn the text "cute cats" into another link to a different picture like the current Step 12
> > Step 15) Continue with the current Step 14 (Don't need Step 13 anymore where we delete an old anchor)
> > Final code before proceeding to Step 14:
> > ```
> > <html>
> >   <body>
> >     <main>
> >       <h1>CatPhotoApp</h1>
> >       <h2>Cat Photos</h2>
> >       
> >       <p>Everyone loves <a href="https://cdn.freecodecamp.org/curriculum/cat-photo-app/cute-cat.jpg">cute cats</a> online!</p>
> >       <p>See more <a href="https://freecatphotoapp.com">cat photos</a> in our gallery.</p>
> >       <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
> >     </main>
> >   </body>
> > </html>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If we want to keep a step about deleting stuff, we can delete that comment after we have added the links
> 
> We agreed upon an approach here

true but we'd need to do that for every bad explaination in freeCodeCamp, and i haven't finished my css one, i can say its way horrible i can't even count how many

**Comment by jeremylt** [comment] 2024-07-06 23:54
No, this Issue has nothing to do with other steps. Please keep to the topic of this Issue.

**Comment by mishraRj** [comment] 2024-10-11 14:39
Hi,
I observed the issue and I want to make some changes in this repo, I need access to make changes plz permit me to make changes to raise the PR.

**Comment by ilenia-magoni** [comment] 2024-10-11 15:58
@mishraRj please learn to raise PR from your own repo, you can't have write access to this repo

**Comment by mishraRj** [comment] 2024-10-11 18:58
Good Day, Maintainers!

I have just raised a PR addressing the issue of wrapping text inside anchor (`a`) tags. I've aimed to clarify this concept in an easy-to-understand way for beginners.

I would appreciate it if you could take some time to review my PR. Thank you!

**Comment by mishraRj** [comment] 2024-10-12 07:08
> Step 15) Continue with the current Step 14 (Don't need Step 13 anymore where we delete an old anchor)

Sir I have a general doubt. If we changes the specific steps like you mentioned Step 4,11,12,13,14 and 15, then will not it affect the final step result of this cat photo exercise ?

I mean in final step i.e, 69 there isn't any line "Everyone loves cute cats" but according to your refactoring line will be added in step 4

> Hmm, larger explanations sorta fights the design of the smaller steps, right?
> 
> Maybe we rearrange things so they build the link into a paragraph in parts starting with the link instead of the paragraph.
> 
> Step 4) Change text to be "Everyone loves cute cats online!"
> 
> Step 11) Change anchor text to "cat photos"
> 
> Step 12) _new_ Add the words "See more " before the anchor element and " in our gallery" after the anchor element
> 
> Step 13) _new_ Add p tags to turn that into a paragraph
> 
> Step 14) _new_ Turn the text "cute cats" into another link to a different picture like the current Step 12
> 
> Step 15) Continue with the current Step 14 (Don't need Step 13 anymore where we delete an old anchor)
> 
> Final code before proceeding to Step 14:
> 
> <html>
>   <body>
>     <main>
>       <h1>CatPhotoApp</h1>
>       <h2>Cat Photos</h2>
>       
>       <p>Everyone loves <a href="https://cdn.freecodecamp.org/curriculum/cat-photo-app/cute-cat.jpg">cute cats</a> online!</p>
>       <p>See more <a href="https://freecatphotoapp.com">cat photos</a> in our gallery.</p>
>       <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
>     </main>
>   </body>
> </html>
> If we want to keep a step about deleting stuff, we can delete that comment after we have added the links


I have a question regarding the changes we've made to the steps. If we modify specific steps, such as Steps 4, 11, 12, 13, 14, and 15, will this not affect the final result of the Cat Photo exercise?

For instance, in the final step (Step 69), the line "Everyone loves cute cats" is not included. However, according to the refactoring we discussed, this line is being added in Step 4. How will this discrepancy be addressed to ensure that the final output matches the expected result outlined in Step 69?

Thank you!

**Comment by mishraRj** [comment] 2024-10-12 07:24
Dear Maintainer's Team,

I hope this message finds you well!

I have recently committed new changes to my pull request, addressing the conditions provided for the modifications. Specifically, I made adjustments in Step 4 and Steps 11 to 15 to refactor them as per the guidelines shared.

I kindly request you to review my new commits at your earliest convenience. If you have any suggestions or feedback for further improvements, I would greatly appreciate your guidance.

As someone who is new to the world of open-source projects, I am fully committed to learning and contributing effectively, and I am putting in my utmost effort to do so.

Thank you for your time and support!

Best regards,
Rajat Mishra

**Comment by jeremylt** [comment] 2024-10-12 14:25
You don't need to keep writing long messages to this issue if you have an open PR.

**Comment by ilenia-magoni** [comment] 2024-10-17 17:07
questions: for the Everyone loves cute cats online!, should that also have a step to add the `target` attribute?

**Comment by jeremylt** [comment] 2024-10-17 17:10
Maybe no so users can play with the difference between the two?

**Closed** 2024-10-21 14:57 UTC
Labels: scope: curriculum, status: PR in works
