### ISSUE TITLE
Use Conditional Logic with If and Else - Test Cases do not catch obvious, critcal errors

### ISSUE THREAD

**Issue by walejandromt** [FreeCodeCamp/FreeCodeCamp#5050] opened 2015-12-07 00:25 UTC
Challenge [Waypoint: Use Conditional Logic with If and Else Statements](http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-if-and-else-statements#?solution=var%20flip%20%3D%20Math.floor(Math.random()%20*%20(1%20-%200%20%2B%201))%20%2B%200%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20x%20%3D%200%3B%0A%20%20%0A%20%20if%20(x%20%3E%200)%7B%0A%20%20%20%20return%20%22tails%22%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%20%22tails%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0Avar%20result%20%3D%20myFunction()%3Bif(typeof%20flip%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20flip%20%3D%3D%3D%20%22number%22%20%26%26%20typeof%20result%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20result%20%3D%3D%3D%20%22string%22)%7B(function(y%2Cz)%7Breturn%20'flip%20%3D%20'%20%2B%20y.toString()%20%2B%20'%2C%20text%20%3D%20'%20%2B%20z%3B%7D)(flip%2C%20result)%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0;

function myFunction() {

  // Only change code below this line.

var x = 0;
  
  if (x > 0){
    return "tails";
  }else{
    return "tails";
  }

  // Only change code above this line.

}

var result = myFunction();if(typeof flip !== "undefined" && typeof flip === "number" && typeof result !== "undefined" && typeof result === "string"){(function(y,z){return 'flip = ' + y.toString() + ', text = ' + z;})(flip, result);}

```

**Comment by SaintPeter** [comment] 2015-12-07 00:50
You are supposed to be testing the `flip` variable, not `x`.  From the instructions:
> Create if and else statements to return the string "heads" if the flip variable is zero, or else return the string "tails" if the flip variable is not zero.

Your code might look like:
```js
  if(flip === 1) {
    return "tails";
  } else {
    return "heads";
  }
```

In the future I encourage you to ask for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) before opening an issue.  Issues are for actual bugs with the site.

Closing as this is not an issue with the site.

**Comment by walejandromt** [comment] 2015-12-07 00:55
if you write this code

var x = 0;

  if (x > 0){
    return "tails";
  }else{
    return "tails";
  }

its no corrent but the site mark that is true sorry my english

me marca que esta buena, yo creo que si es un error saludos

**Comment by walejandromt** [comment] 2015-12-07 00:56
The site is right given me

**Comment by SaintPeter** [comment] 2015-12-07 04:43
Ah, I understand now.  Even with that horribly broken code the test pass.  Confirmed.

**Comment by LenaBarinova** [comment] 2015-12-09 00:04
@SaintPeter, my pull request for this issue didn't pass ```travis continuous integration```. I believe the issue is not in my changes, several pull requests failed at that time (according to the travis log). Is there a way to re-run this ```continuous integrations``` task?

**Closed** 2015-12-09 00:45 UTC
Labels: help wanted

**Comment by SaintPeter** [comment] 2015-12-09 00:48
@LenaBarinova There is/was a known issue with the npm version requirements that were causing problems.  I believe they have been resolved.  I accepted your PR regardless because it tested good locally.

**Comment by LenaBarinova** [comment] 2015-12-09 00:52
@SaintPeter thanks!
