### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by Octavio21** [freeCodeCamp/freeCodeCamp#12470] opened 2017-01-11 06:19 UTC
When using the mouse pointer and clicking on a certain section within the code editor, many times it would not work like a normal editor. Within the editor it will take me to either the beginning or end of the row and I would have to use my arrow keys if i wanted to edit something in the middle of the row.
This only happens randomly and in multiple computers wondering if it might be a browser issue.

**Comment by erictleung** [comment] 2017-01-11 06:43
@Octavio21 thanks for the issue. This is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. This will be resolved soon when updates get pushed. Until then, please take a look at the issue thread I linked for solutions to overcome this bug. Happy coding!

**Closed by erictleung** 2017-01-11 06:43 UTC
