### ISSUE TITLE
The "Go to next challenge" button doesnt load the next challenge

### ISSUE THREAD

**Issue by samoguche** [FreeCodeCamp/FreeCodeCamp#6685] opened 2016-02-02 22:10 UTC
After rounding up the first phase of the basic html, it doesnt load the next challenge.

**Comment by raisedadead** [comment] 2016-02-02 22:14
@samoguche Is this a possible duplicate of #6633 ? If yes, Do you mind closing this issue and continue the discussion there, with screenshots of the error?

Thanks.

**Comment by AkiraLaine** [comment] 2016-02-03 08:30
@samoguche Are you using Chrome? If yes, please us FireFox and tell us if that solved the issue.

**Comment by bugron** [comment] 2016-02-16 07:29
Hopefully, this is fixed not. @samoguche thanks for posting. Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Closed by bugron** 2016-02-16 07:29 UTC
Labels: blocked
