### ISSUE TITLE
Duplicate challenges on profile page

### ISSUE THREAD

**Issue by oharrison** [FreeCodeCamp/FreeCodeCamp#3472] opened 2015-09-23 12:15 UTC
I think it would be better if only the most recent version of a project is shown on one's profile page. Let the discussion begin! 

![fcc-issue](https://cloud.githubusercontent.com/assets/10459779/10044696/f2e3a110-61ca-11e5-98f3-0100007b0452.png)

**Comment by awesomeaniruddh** [comment] 2015-09-23 13:28
Thanks for reporting the issue @oharrison, but I must close it because it is a duplicate of this issue:

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1179

Feel free to continue the discussion there :)

**Closed by awesomeaniruddh** 2015-09-23 13:28 UTC
