### ISSUE TITLE
[challenge] Element gets doubled after a success 

### ISSUE THREAD

**Issue by ai3gtmc** [freeCodeCamp/freeCodeCamp#15897] opened 2017-09-18 03:27 UTC
#### Challenge Name

https://www.freecodecamp.org/challenges/clone-an-element-using-jquery

#### Issue Description

The #target5 gets doubled on the left well after a success run test, the test passes but the UI shows 2 of them even though there's only on inside the script.

#### Browser Information

* Browser Name, Version: Chrome, Safari
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot

![screen shot 2017-09-18 at 12 22 18](https://user-images.githubusercontent.com/9110413/30528253-1d1ac1e2-9c6c-11e7-9a41-324434c6800a.jpg)
![screen shot 2017-09-18 at 12 22 26](https://user-images.githubusercontent.com/9110413/30528254-1d1b41da-9c6c-11e7-93af-bdb71a924d20.jpg)

**Comment by dhcodes** [comment] 2017-09-18 20:01
Hi, @ai3gtmc. Thanks for the issue. This is fixed in the beta which will rollout eventually. Closing as duplicate of #15174

**Closed by dhcodes** 2017-09-18 20:01 UTC
