### ISSUE TITLE
S3 outage - images won't load

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13653] opened 2017-02-28 19:17 UTC
I am however able to see the alt message sometimes, but the svg log is failing to load.
''learn to code javascript at freeCodeCamp logo"
This is for all challenges and the website in general in beta

**Comment by tommygebru** [comment] 2017-02-28 19:32
also the "results" phone templates are gone too...

**Comment by systimotic** [comment] 2017-02-28 20:05
@tommygebru Thanks for reporting. We are aware of this issue. This is caused by an outage at AWS S3, where all of our images are hosted. https://status.aws.amazon.com/
A big part of the internet is affected by this. All we can do is wait and hope the AWS team fixes it soon, which I'm sure they will.
https://twitter.com/ossia/status/836651123092176897

**Comment by tommygebru** [comment] 2017-02-28 20:15
@systimotic thanks for responding, I switched computers, because I thought it was my issue

**Comment by systimotic** [comment] 2017-02-28 21:20
**Update at 1:12 PM PST** from the AWS status page. Everything should be back to normal for us!
After refreshing your browser, images should load again. If not, please clear your cache and try again. I'm closing this issue. If it comes backup, please comment and reopen!

**Closed by systimotic** 2017-02-28 21:20 UTC
