### ISSUE TITLE
usage of .endsWith() in Confirm the Ending challenge 

### ISSUE THREAD

**Issue by a-kile** [FreeCodeCamp/FreeCodeCamp#12054] opened 2016-12-15 04:11 UTC
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20if%20(str.endsWith(target))%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20return%20false%3B%0A%7D%0A%0AconfirmEnding(%22He%20has%20to%20give%20me%20a%20new%20name%22%2C%20%22name%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.3.2883.75 Safari/537.36</code>.

In the context of the challenge, it is mentioned that we should not use the build-in "endsWith()" method, but when I used this method here, the problem actually got accepted, which contradicts the conditions given in the context. The test case at the last "Do not use the built-in method .endsWith() to solve the challenge." also accepted this answer.

I confirmed this again after checking it after multiple refreshes in Google chrome and in Mozilla Firefox Developer Edition.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.endsWith(target)){
    return true;
  }
  return false;
}

confirmEnding("He has to give me a new name", "name");

```

**Comment by Manish-Giri** [comment] 2016-12-15 04:47
@a-kile 
> This challenge can be solved with the .endsWith() method, which was introduced in ES2015. But for the purpose of this challenge, we would like you to use one of the JavaScript substring methods instead

Not using `.endsWith()` is a recommendation, so that you can implement the algorithm using any of the other two recommended functions. I don't think it's a mandatory requirement, which is why your solution passes.

**Comment by a-kile** [comment] 2016-12-15 04:54
@Manish-Giri , Check at the test cases clearly, the last test case asks you to "not" use that method

**Comment by Manish-Giri** [comment] 2016-12-15 05:10
@a-kile Oh yes, you're right. I didn't check test cases. 

This [regex](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/d0024f85b6fa5056e8b3d2281b6411e9e1dacbfb/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L380) seems to be failing.

**Comment by robbawebba** [comment] 2016-12-15 08:12
I'll take this one up

**Comment by robbawebba** [comment] 2016-12-16 20:14
@a-kile were you able to reproduce this issue with the code you provided in the description? I am unable to reproduce the error with the same code:
```javascript
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.endsWith(target)){
    return true;
  }
  return false;
}

confirmEnding("He has to give me a new name", "name");
```

I also tried `return str.endsWith(target);` but the test that checks for `.endsWith()` still fails as expected.

**Comment by aaronedwarda** [comment] 2016-12-17 03:14
@robbawebba I have encountered the same situation. I was just exploring the `endsWith()` method and clicked submit to see what came though in the console and it passed all of the test cases for me as well.

**Comment by a-kile** [comment] 2016-12-17 07:01
@robbawebba Yup, I tried it several times.

**Comment by robbawebba** [comment] 2016-12-19 23:47
@a-kile sorry I misspoke. I am able to reproduce the error online, but not locally during development. @Manish-Giri when you found the source of the problem to be [this regex](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/d0024f85b6fa5056e8b3d2281b6411e9e1dacbfb/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L380), were you able to reproduce the problem in a dev environment?

**Comment by robbawebba** [comment] 2016-12-28 23:25
I just noticed that another issue was submitted 5 days ago about the same problem (#12198) and was closed because the changes were already added to staging with PR #10286, as I noticed and commented about earlier, so this issue could probably be closed as resolved in staging. Happy holidays and happy coding!

**Comment by erictleung** [comment] 2017-01-06 08:37
@robbawebba thanks for double checking! I'll close this issue as resolved in staging. Happy coding all!

**Closed by erictleung** 2017-01-06 08:37 UTC
Labels: help wanted, tests
