### ISSUE TITLE
Need to decide on a consistent use of Notes in the curriculum challenges' Description and Instructions sections

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35464] opened 2019-02-28 21:50 UTC
I have created this issue so we can come to a final conclusion about the best format of notes when they are added to the `Description` or `Instructions` sections of a challenge file.

Below are all the combinations I have seen scattered throughout the curriculum.  There may be others, so please let me know and I will update the list.  This only applies if there is a single note.  For multiple notes (which in my opinion starts to get unnecessary), see later in this topic.

Example 1:
```html
Note
the note goes here
```

Example 2:
```html
<strong>Note</strong>
the note goes here
```

Example 3:
```html
Note:
the note goes here
```
 
Example 4:
```html
<strong>Note:</strong>
the note goes here
```

Example 5:
```html
Note: the note goes here
```

Example 6:
```html
<strong>Note:</strong> the note goes here
```

Example 7:
```html
<strong>Note:&nbsp;</strong> the note goes here
```

Regarding situations where two or more separate notes are added, I have seen:

Example 1:
```html
Notes
* the note goes here
* the note goes here
```

Example 2:
```html
<strong>Notes</strong>
* the note goes here
* the note goes here
```

Example 3:
```html
<strong>Notes:</strong>
* the note goes here
* the note goes here
```
If everyone can cast a vote for their preference of both a single note and multiple notes, this will help us in deciding on one way and then we can update the Styling Guide for challenges in the documentation.

**Comment by RandellDawson** [comment] 2019-02-28 21:51
I will cast my vote as I prefer Example 7 for single notes, because it takes up less space and Example 3 because I like the `Notes` to be bold.

**Comment by thecodingaviator** [comment] 2019-03-01 08:02
I'll vote for number 6 for the single notes and number 3 for multiple notes. I don't really see the need for extra space between `Notes:` and whatever comes after it, a simple space is fine

**Comment by rupali317** [comment] 2019-03-01 12:59
Also to add on, perhaps we can have a background-color for all Note sections as we want users to pay  attention to those sections particularly. Something like this:

![image](https://user-images.githubusercontent.com/5875663/53639479-53182c00-3c64-11e9-8c8a-0b1f869fe121.png)

**Comment by thecodingaviator** [comment] 2019-03-01 13:56
@rupali317 This is the style guide contain freeCodeCamp's Brand colors: https://design-style-guide.freecodecamp.org/ . We try to deviate as least as possible from this and I'm yet to see a major deviation

**Comment by RandellDawson** [comment] 2019-03-01 17:06
@rupali317 Also, the note is not the most important thing in the challenge.  The actual instruction is.  We don't want to highlight anything that is not relative to the instruction.  Most of the time, these notes are FYIs.

**Comment by moT01** [comment] 2019-03-03 19:09
I vote for example 6 and example 3, The [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md#formatting-challenge-text) says to use something in none of the examples for single notes, the output would be the same as example 2, I think - Also, the guide doesn't say anything about multi-notes

**Comment by RandellDawson** [comment] 2019-03-03 21:25
@moT01 , @thecodingaviator I am willing to settle for #6, but technically colons (in English language) should have two spaces afterwards.

**Comment by Manish-Giri** [comment] 2019-03-03 22:47
6 and 3.

**Comment by Nirajn2311** [comment] 2019-03-04 03:49
I vote for example 6 in single notes and example 3 in multiple notes.

**Comment by RandellDawson** [comment] 2019-03-04 03:55
I think it is settled then.  6 and 3.  @raisedadead What do you think?

**Comment by raisedadead** [comment] 2019-03-05 10:43
Agreed, with you all. Thanks. Please proceed with pull requests.

**Comment by rupali317** [comment] 2019-03-05 13:02
I would like to work on this. Is there a way to assign my name under the assignee? I am not able to do so

**Comment by raisedadead** [comment] 2019-03-05 13:46
Hi @rupali317 Go ahead with PR. 

We cannot assign you the issue. It's unfortunately a limitation from GitHub. Feel free to make a PR. We usually allow the first open and valid PR to go in as a fix.

Thanks.

**Comment by moT01** [comment] 2019-03-05 16:32
The suggestion in the PR above says to make a multi-note different from the example - so I did some testing to see the outputs and thought I should share.<br>
**these codes....**
<img width="570" alt="screen shot 2019-03-05 at 10 26 56 am" src="https://user-images.githubusercontent.com/20648924/53820447-6a3f6e00-3f31-11e9-9541-640132b5c67d.png">

**produce the following...**<br>
<img width="415" alt="screen shot 2019-03-05 at 10 27 51 am" src="https://user-images.githubusercontent.com/20648924/53820461-6e6b8b80-3f31-11e9-9b1e-bdd057f3bd98.png">

The first two here produce the same result (same as example 3 above)... I'm not sure I like that extra space in there - I suppose it's fine, but I made a few others to see if I could make it look more like how I think it should look. So basically, I'm saying, I'm having second thoughts on how we should do the multi-notes.

**Comment by rupali317** [comment] 2019-03-05 16:34
@RandellDawson  I found more cases  for single note. Perhaps you can update the list

Case 1:

```
<b>NOTE:</b> note goes here
```

Case 2:

```
<p>Note that:</p> 
note goes here
```

Case 3:

```
<strong>Note</strong>: note goes here
```

Case 4:

```
<strong>Note</strong><br>note goes here
```

**Comment by thecodingaviator** [comment] 2019-03-05 16:38
@RandellDawson Are you going ahead with a PR to put it somewhere into the docs?

**Comment by moT01** [comment] 2019-03-05 16:39
Are you converting them to the suggested style @rupali317? And have you come across many multi-notes?

**Comment by rupali317** [comment] 2019-03-05 16:43
In challenges like https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-bracket-notation,

we have this sentence: Note that property names with spaces in them must be in quotes (single or double). 

So, should that sentence also be converted to: 
```
<strong>Note:</strong> property names with spaces in them must be in quotes (single or double).
```
or can we ignore such cases?

**Comment by rupali317** [comment] 2019-03-05 16:45
@moT01  yes i am following the example 6 for single note (as voted)
Have not come across multiple notes yet. Will re-check.

**Comment by RandellDawson** [comment] 2019-03-05 16:46
@moT01 Good points.  Maybe multiple notes should just be different sentences in the same style as for a single note.

```html
<strong>Note(s):</strong> First note goes here. Second note which is a bit longer goes here. Third note which is the longest note of all goes here.
```

Which ends up looking like:

<strong>Note(s):</strong> First note goes here. Second note which is a bit longer goes here. Third note which is the longest note of all goes here.

**Comment by moT01** [comment] 2019-03-05 16:50
That's a judgement call @rupali317, I think it could be converted. I would hold off on the mult-notes for a little bit, and if you're going to make a PR try and keep them to maybe one section or so at a time if you could.

**Comment by rupali317** [comment] 2019-03-06 13:42
I have a doubt:
in https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/avoid-colorblindness-issues-by-carefully-choosing-colors-that-convey-information,
Is the note section considered multi-note or single note? The note section has more than one sentence. Does it qualify as multi-note then?

**Comment by moT01** [comment] 2019-03-06 14:04
That one looks like you could probably just put the two sentences together in a single note. Since they are so related. And we aren't sure yet what we want a multi-note to look like.

**Comment by cmccormack** [comment] 2019-03-07 16:55
@moT01 I agree if they are related a single paragraph note will be fine.  However, if it gets to long it may be more difficult for the user to parse the information, and should then be broken up into individual lines.  Any Notes section with more than one sentence should still be described as Notes

My opinion on the multi-line notes - we should use markdown bullets.  It may put a bit of space between items, but they are much simpler to manage when making changes to the markdown.  They automatically insert line breaks after each item and don't require verbose HTML wrapping the text.  Visually it also looks like a bulleted list.  Spacing between bullets can be modified in CSS if needed.  It's also easy to replace the bullet with numbers if the order of the note matters.

Note vs Notes should be explicit, Note(s) is only useful if you expect someone to add a second Note and they will forget to update Note to Notes, something we should quickly catch in review with the requirement of multiple reviewers.

After some conversation with @RandellDawson I agree that it really doesn't make sense to have too many notes in a document - we should work to insert the notes into the curriculum, or provide a place for additional information that may not be directly related to the exercise but provide valuable insights/information/resources.

**Comment by RandellDawson** [comment] 2019-03-07 16:57
@cmccormack I believe the Guide is the place where extra information is supposed to go, to avoid cluttering up the challenge itself.

**Comment by cmccormack** [comment] 2019-03-07 17:11
@RandellDawson that may be the case but the way it's conveyed is not great IMO.  The only link to the guide article is Get a Hint, something many won't click, especially if it's a fairly simple exercise.  I also don't see the guide article at all when I search for the exercise title, something we should look into, unless that is by design.

**Comment by moT01** [comment] 2019-03-07 17:17
I see guide links when searching for a lesson title (none of the links work right now) - perhaps you searched for a lesson where the guide article is still a stub, and they don't show up or something.

**Comment by RandellDawson** [comment] 2019-03-07 17:18
> I also don't see the guide article at all when I search for the exercise title, something we should look into, unless that is by design.

The search indexes have not been updated in over 18 months, so that could be part of this problem.

**Comment by RandellDawson** [comment] 2019-03-07 17:20
I just remember that Quincy prefers not to have links going to other places when a user is on the challenge.  He believes the challenge should stand on its own or rely on previously introduced material as much as possible.

**Comment by RandellDawson** [comment] 2019-03-07 17:21
We want people to stay on the challenge until they just can not, which is where the Get a Hint or Ask for Help buttons come into play.

**Comment by moT01** [comment] 2019-05-05 17:23
So the single note structure was added to the guide with the PR above. The multinote issue wasn't exactly concluded - do we want to continue the conversation? I'm thinking we can close this, and mods should just keep notes small when we can. And multinotes can just be combined into a single paragraph after a `Note:`

**Comment by RandellDawson** [comment] 2019-05-05 20:30
@moT01 I don't know how many multi-notes there actually are, but I say we just combine them like you suggest in the same paragraph.  I can create a PR to reflect this.  Then, as we come across the multi-notes, we can first figure out if there even needs to be a multi-note and then probably just make it a single paragraph.  How does that sound?

**Comment by moT01** [comment] 2019-05-05 21:29
A PR to describe this in the guide? Sure

**Closed** 2019-06-05 13:30 UTC
Labels: help wanted, scope: curriculum, status: work in progress
