### ISSUE TITLE
Cursor selection jumps around code....

### ISSUE THREAD

**Issue by WilliamDecker** [FreeCodeCamp/FreeCodeCamp#8218] opened 2016-04-20 20:34 UTC
I had this issue, but a friend of mine started FreeCodeCamp and had a similar issue.  It wasn't browser specific to Chrome or Firefox (occurring in both), but what seems to happen is if you select something say 3/4 down the page (for reference my monitor is 1366x768, also happened in my 1920x1080 monitor) your cursor will be close to, but not where you selected.  It's a minor issue but sufficiently annoying when you try to select something specific in a challenge and your cursor is jumping around, or you're typing not where you think you were, and then messing up your code.

The coding window in the later challenges (I'm currently on Seek and Destroy) don't seem to have these same issues and I noticed it did go away.  Since a friend of mine had the same issue I figured I should submit it.

Challenge [Create a Text Field](https://www.freecodecamp.com/challenges/create-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>
Te
<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text">
```

**Comment by theflametrooper** [comment] 2016-04-20 20:53
@WilliamDecker I have had the same issue!

**Comment by theflametrooper** [comment] 2016-04-20 21:21
Closing as duplicate of #7847

**Closed by theflametrooper** 2016-04-20 21:21 UTC
Labels: bug, confirmed
