### ISSUE TITLE
Froze page when I typed "$($" for the lesson, so I closed the tab, signed back on, and saw this.

### ISSUE THREAD

**Issue by ninjatc** [FreeCodeCamp/FreeCodeCamp#2244] opened 2015-08-19 23:28 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-08-19 at 4 24 33 pm](https://cloud.githubusercontent.com/assets/5223483/9372046/eaf742f6-468e-11e5-8a8e-d81179be61a4.png)

**Comment by ninjatc** [comment] 2015-08-19 23:30
It seems all Javascript slot machine lessons are now broken for me.

**Comment by benschenker** [comment] 2015-08-26 13:43
Hey @ninjatc thanks for posting this.  It looks like this is a duplicate of #1960, which has been resolved.

**Closed by benschenker** 2015-08-26 13:43 UTC
