### ISSUE TITLE
Waypoint: Create Bootstrap Wells

### ISSUE THREAD

**Issue by ulmas** [FreeCodeCamp/FreeCodeCamp#2430] opened 2015-08-21 16:51 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells.

The first checkmark says:
Add two div elements inside your div class="well"> element both with the class col-xs-6

...but that's not what needs to be done to accomplish the task, so it's a little confusing.

It should be more like this:
Under each of your two divs with class col-xs-6, add one div element with class "well.

And also, the 2nd checkmark is probably useless:
Nest both of your div class="col-xs-6" elements within your div class="row" element.

**Comment by benschenker** [comment] 2015-08-21 17:03
Thanks for posting an issue.

This is a duplicate of #1968 and others, so keep an eye there for fixes.

**Comment by BerkeleyTrue** [comment] 2015-08-21 19:24
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 19:24 UTC
