### ISSUE TITLE
When I hit ctrl-enter to test my code, the directions disappear, so I cannot see which step I've messed up - IF I've messed a step up.

### ISSUE THREAD

**Issue by Rich-Hopkins** [FreeCodeCamp/FreeCodeCamp#3092] opened 2015-09-05 15:58 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment] 2015-09-05 16:13
@Rich-Hopkins thanks for posting this issue!
Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-05 16:13 UTC
