### ISSUE TITLE
Can not pass test even though using == operator

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13061] opened 2017-02-02 04:54 UTC
Challenge [comparison-with-the-equality-operator](http://beta.freecodecamp.com/en/challenges/basic-javascript/comparison-with-the-equality-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**UPDATE:  If I exit the problem and then come back in directly using the MAP instead of coming from the previous challenge, all tests pass.**

Test says to use == even thought I am.
 
![image](https://cloud.githubusercontent.com/assets/5313213/22537552/63963a3a-e8c0-11e6-87d0-f8ea43a2bb3a.png)

```js


// Setup
function testEqual(val) {
  if (val==12) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testEqual(10);

```

**Comment by ajain17** [comment] 2017-02-02 15:31
I'm unable to replicate it on live site on chrome/safari/firefox on Mac

**Comment by dhcodes** [comment] 2017-02-02 16:27
Unable to replicate on Mac Chrome.

**Comment by Holyloch** [comment] 2017-06-15 18:17
I did a reset using firefox and challenge worked. Also does not work with a semicolon on second line; reset or no.

**Comment by systimotic** [comment] 2017-09-05 21:19
I can't reproduce this issue on the latest beta, neither when coming from the previous challenge or after reload, so I'm closing. If anybody does run into this issue again, please comment to let us know and we'll reopen.

Happy coding!

**Closed by systimotic** 2017-09-05 21:19 UTC
Labels: beta
