### ISSUE TITLE
Global Scope and Functions 

### ISSUE THREAD

**Issue by zbierek** [FreeCodeCamp/FreeCodeCamp#10560] opened 2016-09-09 10:36 UTC
I have problem with last test in this challenge:
<em>Using var, declare a global variable myGlobal outside of any function. Initialize it with a value of 10.
Inside function fun1, assign 5 to oopsGlobal without using the var keyword.</em>

I have done everything like this:
<em>
```js
// Declare your variable here
var myGlobal = 10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal=5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}
```
</em>
and everything is ok till this point: 
<strong>Do not declare oopsGlobal using the var keyword</strong>

#### Challenge Name

https://www.freecodecamp.com/en/challenges/basic-javascript/global-scope-and-functions

#### Browser Information

mozilla  firefox 44.0.2, safari

* Operating System: 
Vista
* Mobile, Desktop, or Tablet: 
iphone 5s

**Comment by claudiocoding** [comment] 2016-09-09 12:24
same here

// Declare your variable here
var myGlobal = 10;

function fun1() {
  oopsGlobal =5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

result "Do not declare oopsGlobal using the var keyword"

**Comment by earendillo** [comment] 2016-09-09 13:36
I have the same issue (Win10, chrome):

// Declare your variable here

var myGlobal = 10;
function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal = 5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

when I run the code I have "Do not declare oopsGlobal using the var keyword." not marked.

**Comment by phgilliam** [comment] 2016-09-09 19:15
I am having the exact same problem.
Chrome Version 53.0.2785.101 (64-bit)

Checked my code against somebody who had previously passed the challenge.

**Comment by northless** [comment] 2016-09-09 23:30
Yep, same here....i guess i'll wait till tomorrow...every test from the last few lessons had a bug, and this one can't be resolved with the "hacks" used for the previous ones..

**Comment by claudiocoding** [comment] 2016-09-10 07:51
today is a good day for Global Scope and Functions ;)

**Comment by northless** [comment] 2016-09-10 08:13
indeed it is...nothing a rollback in the test code didn't solve 🎯 , onwards!

**Comment by EssaAlshammri** [comment] 2016-09-13 15:20
I just did it now and it pass successfully 
chrome version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04

**Comment by atjonathan** [comment] 2016-09-13 15:42
Confirmed.

**Closed by atjonathan** 2016-09-13 15:42 UTC
Labels: confirmed, help wanted, tests

**Comment by wickedkittenz** [comment] 2016-11-25 09:13
copy & paste oopsGlobal from the text below to your variable and it works.

**Comment by flyingstone2** [comment] 2017-02-13 15:53
I copied and pasted oppsGlobal and then it worked on my code.  I passed..  For the last few lessons it would not take my code.  I cleared my history from my computer and now it is working today.  The problem is,  LOL, that now I have no history on the map from freedcodecamp where you track your progress!!!!

**Comment by nmarino05** [comment] 2017-06-27 17:40
I tried a couple of different codes and came to this code and it partially worked. I have my code written exactly as those above had done theirs and the program will not accept the oopsGlobal value of 5. The last couple of lessons were also buggy in the same manner.
