### ISSUE TITLE
Page crashes when I type the word Function

### ISSUE THREAD

**Issue by MichelleEverywhere** [FreeCodeCamp/FreeCodeCamp#4469] opened 2015-11-16 08:25 UTC
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20array%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array;

// Only change code above this line.


```

**Comment by faizaanceg** [comment] 2015-11-16 09:02
Ah, crap :/ @SaintPeter Is it because we moved the display to the tail ? Should I move it back to the seed?

**Comment by ltegman** [comment] 2015-11-16 17:51
Closing as a duplicate of #4228. However this waypoint does not require typing function, so you should be able to pass it anyways.

Thanks and happy coding!

**Closed by ltegman** 2015-11-16 17:51 UTC
