### ISSUE TITLE
freecodecamp.rocks ssl not working???

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#50517] opened 2023-05-25 13:26 UTC
### Describe the Issue

When I go to the demo projects, I get something like:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/5313213/1a3f6df1-75bc-4076-a2f6-ccfe8609a311)

### Affected Page

https://random-quote-machine.freecodecamp.rocks/

### Steps to Reproduce

1. Go to `https://random-quote-machine.freecodecamp.rocks/`
2. See error

### Expected behavior

Expect to see actual demo project.

### Screenshots

See above.

### System

n/a

**Comment by moT01** [comment] 2023-05-25 13:55
I haven't been able to reproduce this after a quick try. It automatically redirects me to https. I disabled the `Upgrade navigations to HTTPS and warn you before loading sites that don't support it` in chrome and it still redirected me. Same when setting firefox to `Don’t enable HTTPS-Only Mode`.

**Comment by raisedadead** [comment] 2023-05-26 10:45
Closing. I could not reproduce this.

**Closed by raisedadead** 2023-05-26 10:45 UTC
Labels: type: bug, status: blocked
