### ISSUE TITLE
Test invalid

### ISSUE THREAD

**Issue by lucgauer** [FreeCodeCamp/FreeCodeCamp#11586] opened 2016-11-08 20:02 UTC
I think the first test:
"telephoneCheck("555-555-5555") should return a <b>boolean</b>."

Must be

"telephoneCheck("555-555-5555") should return a <b>true</b>."

Challenge [Validate US Telephone Numbers](https://www.freecodecamp.com/challenges/validate-us-telephone-numbers#?solution=%0Afunction%20telephoneCheck(str)%20%7B%0A%20%20validPatterns%20%3D%20%5B%0A%20%20%5D%3B%0A%0A%20%20for%20(var%20i%20in%20validPatterns)%20%7B%0A%20%20%20%20if%20(validPatterns%5Bi%5D.test(str))%20%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20return%20false%3B%0A%7D%0A%0AtelephoneCheck(%22555-555-5555%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function telephoneCheck(str) {
  validPatterns = [
  ];

  for (var i in validPatterns) {
    if (validPatterns[i].test(str)) {
      return true;
    }
  }

  return false;
}

telephoneCheck("555-555-5555");

```

**Comment by vijeth-aradhya** [comment] 2016-11-08 20:12
Yes, the default function which returns true for any string is also giving "boolean" for the first test case.

To reproduce the bug, just clear the code in the editor and run the tests directly.

Here is the screenshot -

![sc](https://cloud.githubusercontent.com/assets/15227565/20115274/af47141c-a61d-11e6-8436-66dff7c6fd19.png)

**Comment by raisedadead** [comment] 2016-11-08 20:18
@lucgauer @vijeth-aradhya thanks.

I am afraid the first test case is correct. 
It's a generic test that states the function should either return a `true` or a `false`, which are booleans.

The default code is indeed returning `true` which is a boolean, and hence valid, and expected.

You can't return any other truthy/falsy values other than true/false.

Please reach out to [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for further guidance.

Closing as not a bug, with the code base.

**Closed by raisedadead** 2016-11-08 20:18 UTC
