### ISSUE TITLE
Build JavaScript Objects Doesn`t Move to the Next Challenge After Passing Test

### ISSUE THREAD

**Issue by Jose26** [FreeCodeCamp/FreeCodeCamp#6640] opened 2016-02-01 12:03 UTC
Challenge [Build JavaScript Objects](http://www.freecodecamp.com/challenges/build-javascript-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

After running the test and passing it, I click the "Submit and move on to the next Challenge" button. However, I am not taken to the next challenge and the pop up box "orb" continues to move. 
My code:
```javascript
// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

// Only change code below this line.

var myDog = {
  "name": "Tobi",
  "legs": 4,
  "tails": 1,
  "friends": ["Family!"]
};

```

**Comment by bugron** [comment] 2016-02-01 12:07
@Jose26 thanks for posting this issue!
I'm going to close this issue as a duplicate of #6633 but, please, comment there your issue and post a screenshot of your browser's console and Network tab too. Also, try using Firefox and report back if that fixes the issue for you, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>**

**Closed by bugron** 2016-02-01 12:07 UTC
