### ISSUE TITLE
++ operator.

### ISSUE THREAD

**Issue by sathishjayapal** [FreeCodeCamp/FreeCodeCamp#5704] opened 2016-01-01 13:16 UTC
Trying the ++ operator.,I had to put ++ twice for the value to change.

Challenge [Waypoint: Increment a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0AmyVar%3DmyVar%2B%2B%3B%0Aconsole.log(myVar)%3B%0AmyVar%3DmyVar%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar++;
myVar=myVar++;
console.log(myVar);
myVar=myVar;



```

**Comment by smrajagopal** [comment] 2016-01-01 13:56
@sathishjayapal 
Duplicate of #5632 . Also, you may take a look at #5631 
Please read the following before opening a new issue :-)
- [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
- [Search for a similar issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues)
Have a good day !

@ltegman : This issue can be closed.

**Comment by ltegman** [comment] 2016-01-01 16:30
Thanks and happy coding!

**Closed by ltegman** 2016-01-01 16:30 UTC
