### ISSUE TITLE
Waypoints HTML5 & CSS: Waypoints 54-69

### ISSUE THREAD

**Issue by dshgna** [FreeCodeCamp/FreeCodeCamp#2844] opened 2015-08-29 11:56 UTC
Even as a developer with quite some experience with web development, I found the HTMK5 and CSS3 waypoints interesting. However, this changed in the last 15 waypoints which covered just two topics: hex code and rgb values: with a lot of repetition(e.g. three waypoints for how to change colour to red, blue and green).

I think reducing the number of waypoints will be more productive to the user.

**Comment by shaikhatik0786** [comment] 2015-08-29 13:56
@dshgna : hmm, yeah I believe the same. But maybe for a user, who just started with coding, and specially HTML, it would be like a fun game of them. I guess that's what they had in mind and purposely did that.

**Comment by benschenker** [comment] 2015-09-08 06:23
Hey @dshgna thanks for posting this.  

This is a duplicate of #2681, which is a closed issue.  The short answer is that its easy to skip challenges that are too repetitive.

**Closed by benschenker** 2015-09-08 06:23 UTC

**Comment by georgiel** [comment] 2015-09-15 14:29
@benschenker I disagree with that thought entirely. 

It is a bad UX to expect the user to skip, if enough users complain then it means that there's a problem that needs solving. Solve it instead of being lazy.

**Comment by benschenker** [comment] 2015-09-16 00:04
@georgiel, your enthusiasm for UX is very much appreciated, and I do agree that it is annoying.  If you'd like to discuss this further, feel free to open up a dialogue in gitter (or even send a private message to one of the maintainers).

It is important to understand that there are users of many different backgrounds who are going through this (over 100,000 last time I checked).

Please keep our [Code of Conduct](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct) in mind here, your tone is concerning.
