### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue.

### ISSUE THREAD

**Issue by memerr** [FreeCodeCamp/FreeCodeCamp#2627] opened 2015-08-24 17:17 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue.
Please describe how to reproduce it, and include links to screenshots if possible.

If you just type this:
$("button").removeClass();
without the "btn-default" as a parameter for the removeClass function, the "Go to my next challenge" already gets enabled.

![screen shot 2015-08-25 at 1 16 19 am](https://cloud.githubusercontent.com/assets/6985314/9446917/03b3876e-4ac7-11e5-9a81-0346179a9c44.png)

**Comment by benschenker** [comment] 2015-09-06 04:16
Hey @memerr thanks for posting this!

It looks like this is a duplicate of #1898, keep an eye there for updates.

**Closed by benschenker** 2015-09-06 04:16 UTC
