### ISSUE TITLE
Inaccurate instruction wording

### ISSUE THREAD

**Issue by Enrique-Ruiz** [FreeCodeCamp/FreeCodeCamp#2087] opened 2015-08-18 15:59 UTC
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This isn't a bug but a problem with the wording in the instructions.  The exercise is for a while loop, but at the bottom of the instructions it says "Let's try getting a FOR loop to work..."  

Nothing major but I figure you would like to correct it for clarity.

Thanks!
Enrique

**Comment by michael-krebs** [comment] 2015-08-18 16:03
duplicate of #1802 which has been fixed

**Closed** 2015-08-23 04:57 UTC
