### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by VilkaDawa** [freeCodeCamp/freeCodeCamp#12512] opened 2017-01-13 20:00 UTC
Challenge [Center Text with Bootstrap](https://www.freecodecamp.com/challenges/center-text-with-bootstrap) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```
Hello,

I can't put my cursor on the h2 element lign to modify the part to make it "text-center". My cursor goes everywhere else, but not there... 

Thank you very much for your help.

**Comment by VilkaDawa** [comment] 2017-01-13 20:02
It's really a bug...

**Comment by VilkaDawa** [comment] 2017-01-13 20:15
Okay, we found the solution : apparently it's a matter of wide opened web page, and semi-opened web page. Some challenged may need to be first semi-opened on the screen, and after wide opened, for the whole system to work.

**Comment by dhcodes** [comment] 2017-01-13 21:55
@VilkaDawa it could be a duplicate of #7847. Glad you got it working. Closing as resolved.

**Closed by dhcodes** 2017-01-13 21:55 UTC
Labels: question
