### ISSUE TITLE
Help with waypoint 33 in HTML

### ISSUE THREAD

**Issue by amench30** [FreeCodeCamp/FreeCodeCamp#3065] opened 2015-09-04 20:31 UTC
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it
![capture](https://cloud.githubusercontent.com/assets/9329252/9693932/225d3bde-5309-11e5-81fc-24afcf1e752f.PNG)
, and include links to screenshots if possible.

**Comment by quatridunull** [comment] 2015-09-04 21:22
Hi. Looks like a typo - "label" not "lable".

**Comment by amench30** [comment] 2015-09-04 21:39
Thank you

**Comment by ahstro** [comment] 2015-09-05 01:10
@amench30 In the future, don't use the GitHub issues for help, instead refer to these [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck) [articles](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter). And remember to close this issue :)

**Comment by bugron** [comment] 2015-09-05 04:35
@amench30 if your problem is solved remember in future to close your issue.
Closing this issue as the problem is solved.

**Closed by bugron** 2015-09-05 04:35 UTC
