### ISSUE TITLE
You can not do #100DaysOfCode in FCC, with this BUG !!! 

### ISSUE THREAD

**Issue by dardandemiri** [freeCodeCamp/freeCodeCamp#16988] opened 2018-03-30 18:36 UTC
#### A bug that makes the amazing 100DaysOfCode Challange useless

Here is my profile: https://www.freecodecamp.org/dardandmr

#### My 69 Days of Streak is broken for no reason 

@QuincyLarson please bro, what is this, and can we reverse this?!
I have submitted the work two hours after 24:00, I don't think that it is a Time zone error, even if it is how is it possible that so many people here in FCC have not fixed this error?
![image](https://user-images.githubusercontent.com/6118247/38149004-247f583c-3459-11e8-82c4-373c48de2556.png)

I am really disappointed, I was so motivated with this 100DaysOfCode Challange, and I have finished all the Front-End Projects and everything else, I have only 4 Advanced Algorithms to solve to claim my Front End Certificate, stayed so many hours without sleep just to keep the streak going... 

#### Screenshot
![image](https://user-images.githubusercontent.com/6118247/38148711-e24562d2-3457-11e8-80c8-01d973fbdd26.png)
![image](https://user-images.githubusercontent.com/6118247/38149372-9b79af68-345a-11e8-8731-3371b7274afb.png)

**Comment by raisedadead** [comment] 2018-03-30 20:05
Duplicate of #7925

**Closed by raisedadead** 2018-03-30 20:05 UTC
