### ISSUE TITLE
Pomodoro Clock 

### ISSUE THREAD

**Issue by tbraden30** [FreeCodeCamp/FreeCodeCamp#4257] opened 2015-11-09 03:24 UTC
Hi,
I am having problems uploading my codepen Pomodoro Timer. The green submit button doesn't work. Then when I hit ctrl enter, the box opens and I'm able to paste my link but not submit. Frustrated cuz I worked very hard on this. please help.

**Comment by SaintPeter** [comment] 2015-11-09 03:33
Duplicate of #4253 

This is a known issue and a patch is pending.

**Closed by SaintPeter** 2015-11-09 03:33 UTC
