### ISSUE TITLE
CSS Rendering issue on Chrome on Android

### ISSUE THREAD

**Issue by AdriaanLouw** [FreeCodeCamp/FreeCodeCamp#7753] opened 2016-03-27 21:45 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; SM-T231 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.105 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by raisedadead** [comment] 2016-03-27 21:58
Your code passes for me.
Request you to please confirm in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room, prior reporting as an issue. 

Thanks and Happy Coding!

**Comment by Gero1369** [comment] 2016-03-28 03:51
I've got the same issue. Using Chrome 49 on a mobile device (Samsung Galaxy Note 4).
My code:
<style>
.red-text {
    color: red;
  }
</style>

<h2 class="red-text"> CatPhotoApp </h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

All except the first box are marked good (h2 text is red is not green).

**Comment by sludge256** [comment] 2016-03-28 04:01
@raisedadead If you click the link the font color is not red despite having "correct" code.

@AdriaanLouw @Gero1369 Are either of you using a custom keyboard/keyboard app?

@AdriaanLouw In your case if you delete the first two spaces on line 2 the h2 element will change font colors. It seems you entered a non-standard white-space character or characters.

**Comment by Gero1369** [comment] 2016-03-28 04:06
I'm using the default keyboard afaik. My OS was recently upgraded, but I'd doubt that has anything to do with the problem.
Thx!

**Comment by sludge256** [comment] 2016-03-28 04:13
@Gero1369 Does your h2 element stay black instead of changing to red?

If so, please try pressing "Reset" and typing out the code again. If that doesn't work try copying and pasting your own code (or the code in the first post) into the code editor.

**Comment by Gero1369** [comment] 2016-03-28 04:17
Yes. It's black. I'll try typing out the code again after a reset. Thx.
Will reply in a few with results.

**Comment by Gero1369** [comment] 2016-03-28 04:23
I removed all the whitespace in the CSS and was able to pass the tests.  Thx!

**Comment by raisedadead** [comment] 2016-03-28 13:25
@sludge256 Thanks. I couldn't reproduce this, sorry about closing this as well in the first place, there wasn't any relevant info when this was first opened.

I'll leave you to sort this out.

But the looks of this is this device/browser specific?
Thanks again!

**Comment by NatashaVanNiekerk** [comment] 2016-03-31 23:45
I'm having the same problem as @Gero1369 
Please help.

**Comment by jincarrey** [comment] 2016-04-02 05:43
use this code:


<style>
  .red-text {
    font-color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by abhayIII** [comment] 2016-04-09 15:39
This is an issue that I believe shows up only if you are using a particular browser in your mobile device. For me, it is chrome browser on my Moto E android device. It might be blank spaces, I don't know for sure but it definitely is an issue.

**Comment by mayunited12** [comment] 2016-04-13 01:20
the solution is to also add a class to your HTML element like this
<h2 class="red-text">CatPhotoApp</h2>

**Comment by mayunited12** [comment] 2016-04-13 01:22
The solution is to also add a class to your HTML, like this;
"<h2 class="red-text">CatPhotoApp</h2>"

**Comment by mayunited12** [comment] 2016-04-13 01:26
![ww](https://cloud.githubusercontent.com/assets/18395772/14480271/1493caa8-011f-11e6-8f16-8f80051657cd.png)

The solution is to also add class to your HTML

**Comment by chandramaniadil** [comment] 2016-04-13 15:15
the code which works for  this challenge is :
![image](https://cloud.githubusercontent.com/assets/13946653/14498585/99a701a8-01b8-11e6-80a5-6f9c94c62fdc.png)

**Comment by raisedadead** [comment] 2016-04-13 15:25
@chandramaniadil @mayunited12 @jincarrey Thanks.

But,
**The issue here is not about the code being incorrect. Requesting everyone from posting more code snippets**

The code editor (code mirror) seems broken on the specific devices as pointed out by @Gero1369  and @abhayIII.

**Comment by mduvanel** [comment] 2016-04-14 06:14
I have the same bug on Android 5.0.0 running Google Chrome 49.0. I also have a custom SwiftKey keyboard.

**Comment by abhayIII** [comment] 2016-04-14 09:03
Let's get this issue closed. 

The solution as pointed above is either to switch to desktop sires or to remove blank spaces after the flower brackets. Trust me this is not an isolated issue. This keeps coming up every now and then. The only thing that seems to work is to remove blank spaces.

**Comment by chandramaniadil** [comment] 2016-04-14 10:32
but that sometimes moves cursor up and delete some code too. @abhayIII

**Comment by raisedadead** [comment] 2016-04-14 12:44
@abhayIII I completely agree and understand the frustration.

**Here is what you happens when you use a visit the** [URL mentioned in the issue](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A)

![image](https://cloud.githubusercontent.com/assets/1884376/14527752/b278f734-0269-11e6-888b-eef590801f4c.png)

THIS DOES NOT PASS THE CHALLENGE

**And here is what happens you do a reset and remove all white spaces and just type in the code.**

![image](https://cloud.githubusercontent.com/assets/1884376/14527590/af6230d4-0268-11e6-8bec-d7834eadcac0.png)

THIS PASSES THE CHALLENGE

**Problem:**
There is an extra `" &npsp;"` on the DOM, which of course messes up the rendering.

**Comment by Shreyas1994** [comment] 2016-05-28 02:56
Its problem occurring in google chrome remove white spaces in line 2&3 it will work fine

**Comment by fortyxtwo** [comment] 2016-06-09 18:53
I spent over an hour on this to no avail. Copied the same exact code from this thread and it passed.

**Closed** 2016-11-04 13:11 UTC
Labels: chrome, device specific
