### ISSUE TITLE
alert showing h2 should be blue though it's already blue in style attribute

### ISSUE THREAD

**Issue by surjadeepBanerjee** [FreeCodeCamp/FreeCodeCamp#3988] opened 2015-10-29 10:26 UTC
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%E2%80%89%E2%80%89h2%20%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color:blue;}
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Em01** [comment] 2015-10-29 11:10
This is an indentation related issue. Resolved by the following which makes the instructions incorrect if pasted into the code mirror:
```
<style>
 h2 {color:blue;}
</style>
```

**Comment by ltegman** [comment] 2015-10-29 14:37
The problem isn't actually with the indentation, it's with the type of whitespace characters that are included a user copies and pastes from the sidebar. The sidebar uses thin space characters instead of regular space characters for indentation which causes invalid markup when copied and pasted in the browser.

@BerkeleyTrue or @QuincyLarson, is there a reason that thin space characters are used to indent sidebar code instead of non-breaking spaces? This isn't the first time I've seen this cause confusion.

**Closed** 2015-11-02 07:01 UTC
Labels: QA
