### ISSUE TITLE
ES6: Create an Export Fallback with export default - test failing - exports not defined

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16357] opened 2017-12-28 17:58 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/es6/create-an-export-fallback-with-export-default

#### Issue Description

The challenge is failing tests as it is looking for keyword 'exports' instead of 'export'.
Error: "exports is not defined" 

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
`"use strict()";
export default function subtract(x,y) {return x - y;}`


```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34418907-a9e10954-ebce-11e7-9e6b-825aa9ded6c0.png)

**Comment by systimotic** [comment] 2017-12-28 21:43
Thanks for all of the QA work @mstellaluna! I'm closing this as a duplicate of #16235

**Closed by systimotic** 2017-12-28 21:43 UTC
Labels: beta
