### ISSUE TITLE
Incomplete Instructions for jQuery Waypoint 10

### ISSUE THREAD

**Issue by paulopadopalos** [FreeCodeCamp/FreeCodeCamp#2781] opened 2015-08-27 18:13 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. The instructions on screen 

for this challenge are not clear. They read:
<img width="299" alt="screen shot 2015-08-27 at 19 11 50" src="https://cloud.githubusercontent.com/assets/2212251/9528958/84178d54-4cef-11e5-988a-c2246bce8091.png">
"Now let's remove an HTML element from your page using jQuery. jQuery has a function called .remove() that will remove an HTML element entirely."

However, the instructions don't tell you which element to remove. Only by running the sample code and inspecting the errors can you get details

**Comment by junhaoyap** [comment] 2015-08-27 18:40
I was about to post about this too, +1 ditto.

This would be ok if instructions below the "reset, help, bug" are shown be default but they now only show after running the code which might be confusing.

**Comment by bugron** [comment] 2015-08-27 21:00
@paulopadopalos thanks for posting this issue!
Note that your issue is a duplicate of closed https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2727 issue.
Also this issue was resolved with merged pull request https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2727

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Closed** 2015-08-28 03:20 UTC
