### ISSUE TITLE
two #target5 buttons are displayed in left well before code refresh

### ISSUE THREAD

**Issue by ArKajaia** [freeCodeCamp/freeCodeCamp#14473] opened 2017-04-18 12:19 UTC
Challenge [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.

**In the result section of the page two #target5 buttons are displayed in the left-well before I refresh the code. Sometimes second #target5 reappears in mid coding.**

![capture](https://cloud.githubusercontent.com/assets/18306824/25130302/c0682eb2-2452-11e7-93fc-54a8b8527a0b.PNG)

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    **$("#target5").clone().appendTo("#left-well");**
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by dhcodes** [comment] 2017-04-18 14:34
Closing as duplicate of #14438 and also this is resolved in staging. Thanks for submitting!

**Closed by dhcodes** 2017-04-18 14:34 UTC
Labels: resolved in staging
