### ISSUE TITLE
lesson 167

### ISSUE THREAD

**Issue by oashtari** [FreeCodeCamp/FreeCodeCamp#9894] opened 2016-07-26 13:56 UTC
Return a Value from a Function with Return

https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(num)%7B%0A%20%20return%20num*5%3B%0A%7D%0AtimesFive(10)%3B%0A

#### Issue Description

No matter what value I give my argument in this challenge, the code returns 25 as the answer.

#### Browser Information

* Browser Name, Version: Safari 9.1.1
* Operating System: MacOS X El Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 function timesFive(num){
  return num*5;
}
timesFive(10);
```

#### Screenshot

<img width="514" alt="screen shot 2016-07-26 at 6 56 11 am" src="https://cloud.githubusercontent.com/assets/10235113/17140656/15673bf0-52fe-11e6-905f-b76677f80a21.png">

**Comment by bugron** [comment] 2016-07-26 14:01
@oashtari thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9583 so I'll close this one. You can continue further discussion there.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-07-26 14:01 UTC
