### ISSUE TITLE
Error moving from one Bonfire to the next

### ISSUE THREAD

**Issue by aelfa** [FreeCodeCamp/freecodecamp#1729] opened 2015-08-11 21:55 UTC
Challenge http://beta.freecodecamp.com/challenges/bonfire-sorted-union has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

After solving Sorted Union, I clicked the option to go to the next challenge from the green success pop-up. This error was displayed. 

![screen shot 2015-08-11 at 3 53 21 pm](https://cloud.githubusercontent.com/assets/7513132/9211729/34d82ff6-4041-11e5-93a2-b2d30bc82d53.png)

**Comment by BerkeleyTrue** [comment] 2015-08-11 22:00
This is a duplicate of #1725 

Happy coding!

**Closed by BerkeleyTrue** 2015-08-11 22:00 UTC
