### ISSUE TITLE
"Frequently asked questions" section can be improved

### ISSUE THREAD

**Issue by PriyansuMaurya** [freeCodeCamp/freeCodeCamp#51071] opened 2023-07-27 17:27 UTC
### Is your feature request related to a problem? Please describe.

Currently, all the questions and answers are shown directly, which takes up a lot of space. Besides, it creates a bad user experience, as users may only have a few questions.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/101447544/6a902010-feb5-477e-bf22-f58e63fb3782)

### Describe the solution you'd like

I would propose implementing this change as it will make it easier for the user to find the answer they want without having to sift through unnecessary and distracting answers.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/101447544/43c871a1-0121-4664-bc56-2c04f2ab6f1d)

### Describe alternatives you've considered

We could also utilize the existing feature that already exists in the codebase.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/101447544/ce87cedb-25b5-4637-ace6-dbae7f254cf4)

**Comment by SaabK** [comment] 2023-07-28 12:01
I approve 👍

**Comment by ebrahim95** [comment] 2023-07-30 05:38
Can I work on this?

**Comment by aniik8** [comment] 2023-07-30 21:45
Anyone got assigned to this??

**Comment by github4ansh** [comment] 2023-07-30 22:06
Yeah! your proposal is pretty intuitive to user, but also reading the current FAQs most of them seems to be the benefits of freecodecamp so instead of having separate minimalist FAQs section we can also show the answers as features at the top so it will cover user queries and also act as catalyst for them to know what freecodecamp actually stands for.

**Comment by raisedadead** [comment] 2023-07-31 10:52
> Currently, all the questions and answers are shown directly, which takes up a lot of space. Besides, it creates a bad user experience, as users may only have a few questions.

The About page reads as it does by design. 

It is NOT verbose like other "about" pages in the wild. It follows a QA pattern in which we want anyone reading the page to get all their questions answered. It's a 5-minute read with short, succinct answers if you missed it.

Collapsing it further makes the page lose its purpose.

If a user is in a rush (your reference to bad UX), they won't bother clicking through the link to the About page in the first place. 

They will do a search-engine search.

Closing as not planned.

**Closed by raisedadead** 2023-07-31 10:52 UTC
Labels: type: feature request
