### ISSUE TITLE
Wasteful double clicking to submit lessons

### ISSUE THREAD

**Issue by KHam0425** [FreeCodeCamp/FreeCodeCamp#2836] opened 2015-08-29 03:28 UTC
If you click once, and all checks pass green, then it should auto submit.  As it is, you're clicking once to check all tasks, clicking again to initiate the submit window, waiting for the popup animation, then clicking "Submit", waiting for animations, then loading to next lesson.  3 clicks and a 4-6 second delay between each lesson.  On the HTML section, that's 4.6-6.9 minutes of completely dead time, and 207 mouse clicks instead of 69.  I suppose I could try to fix it myself, but I just started the course :P.

**Comment by bugron** [comment] 2015-08-29 06:54
@KHam0425 thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2834
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2659

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by KHam0425** [comment] 2015-08-29 07:01
I'm not sure I agree with this being a duplicate of #2834  and #2659, but I agree there is clear overlap with #2772.  However, I did search before posting, but it did not return the similarity in issue #2772 .

**Comment by BerkeleyTrue** [comment] 2015-08-30 06:09
Closing as duplicate of #2772 

This a regression due to patching used to solve several other issues. We would never intent to have a user click a button twice for no reason.

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-30 06:09 UTC
