### ISSUE TITLE
Clicking a link in the "phone" causes the tests to break.

### ISSUE THREAD

**Issue by joshoates** [FreeCodeCamp/FreeCodeCamp#4623] opened 2015-11-22 06:36 UTC
Challenge [Waypoint: Link to External Pages with Anchor Elements](http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%20%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0AWe%20love%20free%20%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3E%20cat%20photos%3C%2Fa%3E.%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
To reproduce this bug on this waypoint, do the following:

1. **Copy** code below and paste in workspace.
*Result: Code is populated in workspace.*

2. **Hover** over the newly created anchor link "*cat photos*" on the right side of page (inside the fake iPhone screen).
*Result: cursor changes in order to show a link.*

3. **Click** the "*cat photos*" anchor text.
*Result: After clicking the link, nothing happens.*

4. **Click** the green "*Run Tests*" button.
*Result: The list of tests will disappear and the page seemingly does nothing. No matter how many times you click the "Run Tests" button you cannot proceed.*

**Workaround:** Refresh the page (your tests will be validated), and then click "Run Tests" to continue.   

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
  
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
We love free <a href="http://freecatphotoapp.com"> cat photos</a>. 
```

**Comment by SaintPeter** [comment] 2015-11-22 06:39
It might be more accurate to say that clicking a link in the "phone" causes the tests to break.

I did confirm this.  I believe this will be fixed with the new instance of the test infrastructure.  For the moment, don't click the links.

**Comment by joshoates** [comment] 2015-11-22 06:47
Agreed. Changed the name of the title accordingly. Clicking the link in the phone is unimportant and not needed for this exercise. I just wanted to make everyone aware of a possible scenario a new camper (like myself) might encounter. Thanks for validating and giving the suggestion on the title!

**Comment by SaintPeter** [comment] 2015-11-22 06:48
I'm going to leave this open so other campers can see it.  As I say, we've got a complete revamp of the testing environment coming "Real Soon Now"(:tm:).

**Comment by bugron** [comment] 2016-01-10 21:15
I'm not able to reproduce this anymore. Closing. @joshoates thanks for letting us know and for excellent formed issue description!

**Closed by bugron** 2016-01-10 21:15 UTC
Labels: in progress, on the roadmap
