### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mustard81** [FreeCodeCamp/FreeCodeCamp#2266] opened 2015-08-20 02:27 UTC
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/12478585/9374199/0bbe33e4-46b9-11e5-8016-97378dad439b.png)

You'll see where <script></script> should be there's that funky fcss-thing. It happened last page too.

**Comment by benschenker** [comment] 2015-08-20 02:32
Thanks for posting an issue,

This is a duplicate of #2242 and others though in general try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by Mustard81** [comment] 2015-08-20 02:38
Thank you much!

**Closed** 2015-08-21 04:02 UTC
