### ISSUE TITLE
Completing waypoints 1-18 produces poor results on the simulated phone.

### ISSUE THREAD

**Issue by emadera52** [FreeCodeCamp/FreeCodeCamp#5741] opened 2016-01-02 05:11 UTC
The image below compares the code as it exists at the end of waypoint 18 on a 333px wide Chrome window, a 255px wide Firefox window and the simulator. To get the first two images I copied the code and added the necessary bootstrap / fontawesome files, and I added links above the <style> block as follows.
    <link rel="stylesheet" href="bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <script type="text/javascript" src="jquery.min.js"></script>
    <script type="text/javascript" src="bootstrap.min.js"></script> 
A partial work around would be to use shorter button and label names. The delete button would still be chopped off, but at least things would line up. On Glitter, the advice I got was to get used to narrow phones. :) The last smart phone I had that was less than 333px wide was the original Galaxy Ace at 320px. So I'm thinking that a 350px wide simulation would cover most phones in use these days.

I have a lot of development experience, but I'm just getting started when it comes to web development, so I may have missed something obvious. In any case, I like what you're doing here. It is just what I was looking for.

![fcc-cat-site](https://cloud.githubusercontent.com/assets/6283463/12073249/ce9b6982-b0da-11e5-95b9-6e2103038b6f.jpg)

**Comment by emadera52** [comment] 2016-01-02 05:14
I have no idea why the comment is not formatted. I have submitted issues on Github before and never seen this. Sorry.

**Comment by prashcr** [comment] 2016-01-02 13:07
Strange indeed, it seems to be formatted fine after copy pasting what you posted.

The image below compares the code as it exists at the end of waypoint 18 on a 333px wide Chrome window, a 255px wide Firefox window and the simulator. To get the first two images I copied the code and added the necessary bootstrap / fontawesome files, and I added links above the block as follows.<br> <link rel="stylesheet" href="bootstrap.min.css"><br> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"></p> <pre><code>&lt;script type=&quot;text/javascript&quot; src=&quot;jquery.min.js&quot;&gt;&lt;/script&gt; &lt;script type=&quot;text/javascript&quot; src=&quot;bootstrap.min.js&quot;&gt;&lt;/script&gt; </code></pre> <p>A partial work around would be to use shorter button and label names. The delete button would still be chopped off, but at least things would line up. On Glitter, the advice I got was to get used to narrow phones. :) The last smart phone I had that was less than 333px wide was the original Galaxy Ace at 320px. So I&#39;m thinking that a 350px wide simulation would cover most phones in use these days.</p> <p>I have a lot of development experience, but I&#39;m just getting started when it comes to web development, so I may have missed something obvious. In any case, I like what you&#39;re doing here. It is just what I was looking for.</p> <p><img src="https://cloud.githubusercontent.com/assets/6283463/12073249/ce9b6982-b0da-11e5-95b9-6e2103038b6f.jpg" alt="fcc-cat-site"></p>

**Comment by bugron** [comment] 2016-02-17 05:34
@emadera52 thanks for posting this issue!
Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2802.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2016-02-17 05:34 UTC
