### ISSUE TITLE
Expanding or collapsing tree items in the Curriculum View modal causes the browser to unintentionally navigate 

### ISSUE THREAD

**Issue by mattszcz** [freeCodeCamp/freeCodeCamp#17311] opened 2018-05-31 00:57 UTC
#### Describe your problem and - if possible - how to reproduce it
Clicking “View the Curriculum” button then expanding or collapsing a tree item navigates the browser to new URLs without the user intending to do so. The back button must then be used to return the user to their original page. 

#### Add a Link to the page with the problem
Every page has this problem.
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: ChromeOS

#### If possible, add a screenshot here
Here's a video https://drive.google.com/file/d/1KyoknCG7TyVlKbg6xGLApMjeas_pFeBk/view

**Comment by mstellaluna** [comment] 2018-06-01 00:02
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17331

**Closed by mstellaluna** 2018-06-01 00:02 UTC
