### ISSUE TITLE
Waypoint: Local Scope and Functions (checker issue)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#5702] opened 2016-01-01 12:00 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20%22loo%22%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 5841.83.0) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.138 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = "loo";
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction

// now remove the console.log line to pass the test
```

checker responds:
```javascript
Remove the second console log
```

That's what's causing the issue, when the line is removed checker returns success:
```javascript
// now remove the console.log line to pass the test
```

So it may be optimal to do it like this:
```javascript
function myFunction() {
  var myVar = "loo";
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar); // now remove this whole line to pass the test
```

By the way, commenting second console log line produces checker error also, but this is probably known, because of instructions to remove the line to pass the test.

**Comment by smrajagopal** [comment] 2016-01-01 13:44
@rfprod: 
This is a duplicate of #5559 .
Please read the following before opening a new issue :-)
- [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
- [Search for a similar issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues)
Have a good day !

@ltegman: This issue can be closed

**Comment by DDaems** [comment] 2016-01-01 14:02
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1902
 
Here is a proper regex that resolves this issue:
`function myFunction[\s\S]+myFunction\(\s*\d+\s*,\s*\d+\s*\)`

I'm having a bit of a hangover, so i'm browsing on my laptop. Because of this, I'm not creating a PR. If someone else wants try, keep in mind that you still need to do the escaping. ;-)

**Comment by ltegman** [comment] 2016-01-01 16:23
Closing as a duplicate. Thanks and happy coding!

**Closed by ltegman** 2016-01-01 16:23 UTC

**Comment by dianedangelo** [comment] 2016-10-04 23:30
I've been reading all the fixes for this. None of them are working for me! No matter what I can't pass this one!!
