### ISSUE TITLE
The pop up window won't disappear from my screen even when I click to close it. Code Camp has been working fine for the past three weeks without a pop up window. Someone mentioned it might be because I am using safari, but not sure why it has just appeared now

### ISSUE THREAD

**Issue by jamescarless91** [FreeCodeCamp/FreeCodeCamp#6329] opened 2016-01-19 22:12 UTC
![screen shot 2016-01-19 at 20 07 13](https://cloud.githubusercontent.com/assets/16451955/12433578/c2c6a8ce-bef9-11e5-89ae-ec2c3ac0b290.png)

**Comment by sludge256** [comment] 2016-01-19 22:26
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256

**Closed by sludge256** 2016-01-19 22:26 UTC
