### ISSUE TITLE
Doctype isn't case sensitive in challenge.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [freeCodeCamp/freeCodeCamp#41894] opened 2021-04-22 15:52 UTC
The layout of the bug-template changed dramatically, so I'm a little afraid I clicked on the wrong button. I couldn't find a better option though, so here's the issue:

**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/declare-the-doctype-of-an-html-document

**Your code**
This is what get's accepted:

```html
<!dOcTyPe html>
<html>
  <h1>Bug</h1>
</html>
```

**Expected behavior**
Only uppercase `!DOCTYPE` should be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/59611881/115744822-320a7c00-a393-11eb-8b1c-63868a0869a7.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 88.0

**Comment by ShaunSHamilton** [comment] 2021-04-22 16:42
Hello there,

It appears the test was specifically designed to accept any casing for the text. In one sense, it does not matter, because browsers automatically convert lowercase to uppercase.

I will leave this open for others to comment, but I do not see a bug here.

**Comment by raisedadead** [comment] 2021-04-22 17:01
> The layout of the bug-template changed dramatically, so I'm a little afraid I clicked on the wrong button.

You did not! We did change the template - streamlining it a little bit for our purposes. Thanks for reporting.

**Comment by lasjorg** [comment] 2021-04-23 14:15
As said, it is [case-insensitive](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) so I don't really see the need for the test to be case-sensitive. I agree that it's not a bug.

Although, the formatting presented in this issue would not be accepted as proper formating (from a code hygiene point of view). So I guess it comes down to if we should be checking code formatting and not just correctness.

**Comment by raisedadead** [comment] 2021-04-23 14:37
> I guess it comes down to if we should be checking code formatting and not just correctness.

We do not need to do that. It's beyond the scope of the curriculum. However I am pretty sure code-style topics like linting, formatting is covered in our non-curricular resource like articles on `/news`

Closing, but please continue to add feedback.

**Closed by raisedadead** 2021-04-23 14:37 UTC
Labels: scope: curriculum, type: bug
