### ISSUE TITLE
jQuery syntax crashes challenge "Bring your JavaScript Slot Machine to Life"

### ISSUE THREAD

**Issue by apositivejam** [FreeCodeCamp/FreeCodeCamp#1964] opened 2015-08-17 23:59 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In typing this suggested code to solve the challenge, the automatic closing of parentheses leads the student to type

$($)

which immediately causes the script to become unresponsive. This is on Firefox for Mac v39.0.3

**Comment by jbmartinez** [comment] 2015-08-18 02:51
Duplicate of #1960

**Closed** 2015-08-25 16:29 UTC
