### ISSUE TITLE
Javascript Waypoint 39

### ISSUE THREAD

**Issue by TimCoding** [FreeCodeCamp/FreeCodeCamp#2146] opened 2015-08-19 02:24 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi!

When I'm working on this way point I can only get as far as entering $($('.slot')[0]).html(slotOne) before it freezes up and crashes. I tried making it work on Safari and Google but they both crashed.

**Comment by jbmartinez** [comment] 2015-08-21 21:28
Possible duplicate of #1960

**Comment by BerkeleyTrue** [comment] 2015-08-21 21:58
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 21:58 UTC
