### ISSUE TITLE
Does not detect the closing </ol> tag 

### ISSUE THREAD

**Issue by Pk13055** [FreeCodeCamp/FreeCodeCamp#11721] opened 2016-11-19 23:33 UTC
Challenge [Create an Ordered List](https://www.freecodecamp.com/challenges/create-an-ordered-list#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%20style%3D%27list-style-type%3Aupper-roman%27%3E%0A%20%20%3Cli%3E%20Dogs%20%3C%2Fli%3E%0A%20%20%3Cli%3E%20Work%20%3C%2Fli%3E%0A%20%20%3Cli%3E%20Humans%20%3C%2Fli%3E%0A%3C%2Fol%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol style='list-style-type:upper-roman'>
  <li> Dogs </li>
  <li> Work </li>
  <li> Humans </li>
</ol>
```

**Comment by Pk13055** [comment] 2016-11-19 23:40
UPDATE: Without specifying list-style-type, the code got accepted. Could someone tell me why is this the case?

**Comment by no-stack-dub-sack** [comment] 2016-11-20 01:09
@Pk13055 Based on this test's code, it looks like the reason why the code you posted above does not pass is because it uses [regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) to test that the user's input matches the expected code. The test fails because before it looks for a closing tag, it looks for an opening one, and is only designed to match an `<ol>` opening tag without any styling.

**Comment by Pk13055** [comment] 2016-11-22 11:31
@no-stack-dub-sack Shouldn't  regex validators match starting tags phrases only? Wouldn't something like "^[ol]" work? (Not too sure about the syntax) 
Also, where can I look up the proposed changes?

**Comment by dhcodes** [comment] 2016-11-22 16:40
@Pk13055 you can see the tests for this challenge in the codebase here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L2079

I am sort of indifferent as to changing it since it does seem like an edge case imho.

**Comment by no-stack-dub-sack** [comment] 2016-11-22 16:53
@dhcodes I agree, def an edge case, and am sort of indifferent as well, however it does seem like an easy enough case to modify so that the above code would pass.

**Comment by Bouncey** [comment] 2016-11-22 17:58
> most campers who are new to coding will not even think to apply this kind of styling to their lists so early on in their coding journey.

I vote for a `wontfix`

**Comment by Pk13055** [comment] 2016-11-22 18:17
@no-stack-dub-sack Is it worth the effort? I'm willing to take up the issue.

**Comment by systimotic** [comment] 2016-11-22 21:22
@Pk13055 It depends. Updating the regex to allow your solution should be fairly simple. Allowing any character in the place of the attributes should do the trick.
The problem is that it becomes rather difficult when you also want to check whether there's nothing there that could break the HTML. We'd have to limit the allowed characters and make sure all the quotes are in the right places. That would still only handle some cases, it would leave some other edge cases of odd things you can do unsolved.
For that reason, combined with the fact that it's very unlikely other campers will think of adding attributes, it might be better to leave it as is.

Regex is not a perfect tool for checking whether the code is what we want, but it's the best one we have at hand.

**Comment by dhcodes** [comment] 2016-11-22 21:41
Closing as `wontfix` edge-case. Will revisit if this becomes a recurring issue. Thanks for bringing it up @Pk13055

**Closed by dhcodes** 2016-11-22 21:41 UTC
