### ISSUE TITLE
Repeat of #43283 - Typo in Basic Node and Express introduction

### ISSUE THREAD

**Issue by y-arjun-y** [freeCodeCamp/freeCodeCamp#45619] opened 2022-04-04 12:25 UTC
## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/#basic-node-and-express

## Expected behavior

This is a repeat of #43283, it should say  "like `/blog`".

## Screenshots

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58625220/161542833-ce31db6a-8bf3-4763-b56d-c99ea765a398.png">

## System

- Device: MacBook Air (M1, 2020)
- OS: macOS Monterey 12.0.1
- Browser: Chrome
- Version: 99.0.4844.84

**Comment by ojeytonwilliams** [comment] 2022-04-04 15:55
Hi @y-arjun-y thanks for reporting this.  The problem is almost certainly something to do with hydration because if you go to https://www.freecodecamp.org/learn/ and then click through to Back End Development and APIs `/blog` appears as expected.  However, if you reload the page, it disappears.

**Comment by ojeytonwilliams** [comment] 2022-04-04 16:11
Actually, scratch that theory: `<pre>/blog</pre>` is in the page source and somehow it's removed on page load.

**Comment by ArielLeslie** [comment] 2022-04-05 19:41
"direct" should also be "directing". 
>which handles things like directing people to the correct page when the visit a certain endpoint like `/blog`

Overall though it's a fairly confusing description of routing.

**Comment by lem0n4id** [comment] 2022-04-06 00:04
> click through to Back End Development and APIs `/blog` appears as expected. However, if you reload the page, it disappears.

Not sure if it's just me, but the bug doesn't seem to be reproducible. 

I tried on both Firefox 98.0.2 (64-bit) and Chrome Version 99.0.4844.84 - Windows 10
<details><summary>Screenshots</summary>

#### Firefox
![image](https://user-images.githubusercontent.com/61219881/161870032-a7036458-da17-45fa-90d7-5cdf08263999.png)

#### Chrome
![image](https://user-images.githubusercontent.com/61219881/161870323-c918ac2c-4760-4f06-9642-3e1ae97a1aec.png)

</details>

**Comment by y-arjun-y** [comment] 2022-04-06 03:59
@lem0n4id It has come back for me too, not sure if that's the case for everyone else in this thread:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58625220/161893067-3c61cb1e-15c4-48dd-b918-b28d8a7953c4.png">

**Comment by ojeytonwilliams** [comment] 2022-04-06 07:58
It's not clear why it's started working again, but I can no-longer reproduce the issue with `/blog`.

That said, the issue @ArielLeslie brought up (direct should be directing) is good for first timers, so I'll open this up.

**Comment by Sboonny** [comment] 2022-04-07 11:33
I would like to be assigned this
> (direct should be directing)

**Closed** 2022-04-07 14:26 UTC
Labels: scope: curriculum, first timers only
