### ISSUE TITLE
freeCodeCamp Activity Calendar

### ISSUE THREAD

**Issue by georgelilis** [FreeCodeCamp/FreeCodeCamp#4461] opened 2015-11-15 22:00 UTC
The last 2-3 days my activity calendar is blank. It shows no activity although it says i have completed 217 items so far.
When i open chrome's console it has an error that might help in solving the problem which says "Uncaught TypeError: Cannot read property 'getTime' of undefined".

I tried to open the page with firefox which i rarely used but never with freeCodeCamp in case it was a cache problem but still didn't work.

I attached the screenshot below for your convenience.

![freecodecamp screenshot](https://cloud.githubusercontent.com/assets/15311969/11171275/e29f156a-8bf4-11e5-8569-ea913bd3fbec.jpg)

**Comment by SaintPeter** [comment] 2015-11-15 22:53
Duplicate of #4427

**Closed by SaintPeter** 2015-11-15 22:53 UTC
