### ISSUE TITLE
Hint links in Chinese curriculum

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#41256] opened 2021-02-25 09:12 UTC
**Describe the bug**
The hint links jump to the Chinese forum and show nothing now.

**Expected behavior**
They should fall back to the English counterparts.

**Comment by Sembauke** [comment] 2021-05-22 16:02
Closing this one as a duplicate of #42175

**Closed by Sembauke** 2021-05-22 16:02 UTC
Labels: scope: curriculum, type: bug
