### ISSUE TITLE
Despite the colour change, the validator reports incorrectly.

### ISSUE THREAD

**Issue by Titash** [freeCodeCamp/freeCodeCamp#15227] opened 2017-06-06 03:30 UTC
![issue1](https://cloud.githubusercontent.com/assets/4498199/26812643/8cd652e4-4a96-11e7-9718-09624fbb9ab3.png)
![issue2](https://cloud.githubusercontent.com/assets/4498199/26812644/8cda879c-4a96-11e7-9694-a9d1581197e7.png)

Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  h2 {color: blue;}
</style>
<h2>Blue</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by IshtmeetSinghRissam** [comment] 2017-06-06 12:47
Reload the page, it will work fine.

**Comment by ausinesayia** [comment] 2017-06-20 09:27
i have the same issue and am using crome? what  is the next step?

**Comment by ausinesayia** [comment] 2017-06-20 09:30
also the reloading have done with no fruit?

**Comment by prabodh1194** [comment] 2017-06-20 11:25
works fine for me

**Comment by lynxlynxlynx** [comment] 2017-08-05 15:58
Of course, there were older reports, so this one itself is a duplicate of at least #15090. Someone please close.

**Closed** 2017-08-06 20:04 UTC
Labels: beta
