### ISSUE TITLE
Update expressworks challenge description

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/FreeCodeCamp#2972] opened 2015-09-01 21:21 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Steps 18 & 19 on this way point: 

"session & cookie" and JSON Me are not in the current expressworks steps. 

I'd recommend updating the description to simply have the student complete all the steps.  PARAM PAM PAM for example, seems like a very useful exercise for the basejumps, but it's not included in the way point steps.

**Comment by bugron** [comment] 2015-09-01 21:29
@CharlesMilam thanks for posting this issue!
I'm closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2603. You can continue further discussion there.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-01 21:29 UTC
