### ISSUE TITLE
Not showing check list

### ISSUE THREAD

**Issue by dfuruya** [FreeCodeCamp/FreeCodeCamp#3179] opened 2015-09-08 23:36 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When attempting to Run a test, the checklist below the button disappeared, and will not re-appear when trying to Reset. It does, however, re-appear when refreshing the browser page.
![screen shot 2015-09-08 at 4 33 34 pm](https://cloud.githubusercontent.com/assets/12400009/9750049/bf880f56-5647-11e5-89e8-1b09e25c7a1c.png)

**Comment by awesomeaniruddh** [comment] 2015-09-09 00:06
@dfuruya Thanks for posting the issue!

I was unable to reproduce the issue, so it might be something on your end. Try doing a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache). If the issue does not persist, then please close the issue, but if it does, then please post the answers to the following questions:

Has this happened before on any other waypoints? Which browser are you using?
This information will help us determine the exact cause of the issue.

**Comment by bugron** [comment] 2015-09-09 03:41
@dfuruya thanks for posting this issue!
This issue seems global so I'm closing it as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2904. You can continue further discussion there, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-09 03:41 UTC
Labels: blocked

**Comment by zill24** [comment] 2017-02-03 13:20
also got this issue
