### ISSUE TITLE
Waypoint: Write Reusable Javascript With Functions instructional text differs from example code

### ISSUE THREAD

**Issue by tsedlmeyer** [FreeCodeCamp/FreeCodeCamp#2056] opened 2015-08-18 12:31 UTC
Challenge http://freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The method of defining a function in the text differs from the method used in the code window. This may confuse campers.

<img width="1275" alt="screen shot 2015-08-18 at 8 28 28 am" src="https://cloud.githubusercontent.com/assets/1650358/9329912/8d6fb32c-4583-11e5-88e6-64aec8694fef.png">

**Comment by jbmartinez** [comment] 2015-08-18 12:58
Duplicate of #1936

**Closed** 2015-08-26 00:13 UTC
