### ISSUE TITLE
Waypoint: Use appendTo to Move Elements with jQuery

### ISSUE THREAD

**Issue by ChrisLegg** [FreeCodeCamp/FreeCodeCamp#5002] opened 2015-12-03 22:21 UTC
The code to complete the waypoint, according to the example text, is:

```
$("#target2").appendTo("#right-well");
```

After going to the Gitter Help channel I was able to pass this waypoint using

```
$("#target2").appendTo($("#right-well"));
```

In the course of an hour or so in the help channel, there were at least 5 other people experiencing the same issue.

**Comment by BerkeleyTrue** [comment] 2015-12-03 22:26
Closing as duplicate of #4958

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-12-03 22:26 UTC
