### ISSUE TITLE
Minor design suggestion/bug report

### ISSUE THREAD

**Issue by JC713** [FreeCodeCamp/freecodecamp#1119] opened 2015-06-25 13:28 UTC
Hello, today I was doing some waypoints and as my code got longer and longer, I was unable to keep up with the objectives and info on the left side as I scrolled down.

Can we get the objectives and info on the left side to scroll with the page like the phone/app on the right side does? This is very crucial when working with a lot of code. I have attached a video to exemplify this:

https://www.dropbox.com/s/6eutki529kdlpmz/Design%20Suggestion.mov?dl=0

Sorry if the video is bad quality; Dropbox compresses videos a ton.

**Comment by georgekuka** [comment] 2015-06-27 06:11
Yup, noticed the exact same thing. I fixed it by...

Adding the css below to class "CodeMirrow-scroll"
```css
overflow: auto;
max-height: 750px;
```

Height could be anything, I'm sure there's a responsive solution to have it extend the height of browser window.

**Comment by LumenTeun** [comment] 2015-06-30 02:12
This is a duplicate of #716, please keep relevant discussion in there and close this issue. Thank you :)

**Comment by JC713** [comment] 2015-06-30 02:50
Sorry. I jump to reporting these errors and don't take the time to search. I'll do that next time :) !

**Comment by LumenTeun** [comment] 2015-06-30 10:26
No problem, but remember to search in the future, it saves everyone a lot of time :) Please close this issue so no one else starts writing in here.

**Closed** 2015-06-30 17:00 UTC
