### ISSUE TITLE
Code editor not working properly

### ISSUE THREAD

**Issue by kbakermemphis** [FreeCodeCamp/FreeCodeCamp#12241] opened 2016-12-27 19:02 UTC
#### Issue Description

The code editor won't let me select or even navigate down to the last two lines of code. The 3rd line from the bottom it will let me select 2/3s of the line and the 4th line up will let me select about 3/4.

#### Browser Information

* Browser Name, Version: Google Chrome Version 55.0.2883.87 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by kbakermemphis** [comment] 2016-12-30 21:26
That was it! Just had to hit enter, thanks.

**Comment by erictleung** [comment] 2016-12-31 06:23
@kbakermemphis no problem! Sorry about the editor issues. The problem is with the code editor built-in and it has issues with really wide lines of code. So just a heads up of where this issue may pop up again. Closing as issue is duplicate of #7847. Happy coding!

**Closed by erictleung** 2016-12-31 06:23 UTC
