### ISSUE TITLE
Slip of points

### ISSUE THREAD

**Issue by anirban93** [FreeCodeCamp/FreeCodeCamp#5107] opened 2015-12-09 15:13 UTC
My code is here:
```javascript
function palindrome(str) {
  var ping = str.toLowerCase();
  var pong = ping.replace(' ','');
  //alert(pong);
  var chong = pong.split('');
  var kong = chong.reverse();
  var dhong = kong.join('');
  alert(dhong);
  
  if (dhong === pong)
    return true;
  // Good luck!
  else
    return false;
}
palindrome("never odd or even");
```
I didn't remove "all non-alphanumeric characters (punctuation, spaces and symbols)" and i passed a different string which is a palindrome but it's not when i didn't remove blank spaces quite well.
But, i have added a alert for debugging(as console wasn't working for a while). when the code started checking all strings i checked "prevent this window from creating additional dialog" 
![](https://cloud.githubusercontent.com/assets/5820924/11688880/454cf250-9eb9-11e5-8d3d-1ccfe372fb59.JPG)

And, guess, i've passed.
![](https://cloud.githubusercontent.com/assets/5820924/11688838/16953904-9eb9-11e5-8bee-57e108797201.JPG)

**Comment by anirban93** [comment] 2015-12-09 15:19
And, i confirm this as a cool bug.. I just tried `alert(str);` in next stage named "Finding longest word in a string" and it passed me there too!

**Comment by ltegman** [comment] 2015-12-09 16:29
Interesting. This appears to be Firefox specific, because I can not repro in Chrome, but I can in Firefox.

**Comment by bugron** [comment] 2016-01-10 20:46
Closing this issue as I'm not able to reproduce this issue in FF 42 and FF 43.

**Closed by bugron** 2016-01-10 20:46 UTC
Labels: bug, confirmed, firefox
