### ISSUE TITLE
All items in the map page is shown as "1" when using IE11.

### ISSUE THREAD

**Issue by LuckyOreo** [FreeCodeCamp/FreeCodeCamp#2714] opened 2015-08-26 02:14 UTC
I am not sure whether supporting IE is a priority but I have noticed that the numerical list in the map page using IE11 shows up as "1".

![fccslotmachinebug](https://cloud.githubusercontent.com/assets/13142234/9484174/9bfe7ce0-4b76-11e5-871e-11c90936f623.jpg)

**Comment by BerkeleyTrue** [comment] 2015-08-26 02:32
Closing as duplicate of #1354 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-26 02:32 UTC
