### ISSUE TITLE
Error on Basic CSS: Override Class Declarations with Inline Styles

### ISSUE THREAD

**Issue by revisualize** [freeCodeCamp/freeCodeCamp#17950] opened 2018-07-29 21:03 UTC
#### Describe your problem and - if possible - how to reproduce it
When working on Basic CSS: Override Class Declarations with Inline Styles if you use the following code the app window displays a bunch of random code.

Code to reproduce error:

<style>
  body {
    background-color: black;
    font-family: monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style=">Hello World!</h1>

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/override-class-declarations-with-inline-styles

#### Tell us about your browser and operating system

* Browser Name: Firefox and Chrome
* Browser Version:  Latest for both
* Operating System:  Windows 10 Home

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/1588399/43370656-ea7d9318-9337-11e8-8b44-63058cd39b39.png)

**Comment by revisualize** [comment] 2018-07-29 21:06
It's also doing the same thing on:

Basic CSS: Override All Other Styles by using Important
https://learn.freecodecamp.org/responsive-web-design/basic-css/override-all-other-styles-by-using-important

I changed this line: 
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

To:
<h1 id="orange-text" class="pink-text blue-text" style=">Hello World!</h1>

And it did the same thing.

**Comment by jocharles57** [comment] 2018-07-30 07:02
It shows the code if you leave off the last quote mark in the h1 class attribute, too. Like so:

`<h1 id="orange-text" class="pink-text blue-text>Hello World!</h1>`

Note that I've not closed the `class="pink-text blue-text` string.

**Comment by thecodingaviator** [comment] 2018-11-21 15:35
Yes, so it's showing the wrong thing because you're unwantedly wanting it to. @revisualize / @ezioda004 please close the issue

**Comment by rupali317** [comment] 2019-01-15 05:23
I tried to reproduce @revisualize and @jocharles57 comments. I omitted the closing double quote. I am seeing a blank screen instead of the code.

**Environment:**
- Chrome Version 71.0.3578.80 (Official Build) (64-bit) 
- Windows 10

**Screenshot:**
![free_code_camp_basic_style_ovverride](https://user-images.githubusercontent.com/5875663/51160230-0a7cfd00-18c8-11e9-968f-fbcf835c3d41.PNG)

If I am missing anything, let me know
Perhaps you can try to reproduce again. If it is not reproducible, we can close it

**Comment by thecodingaviator** [comment] 2019-01-15 05:58
@rupali317 I don't think we need to reproduce it. If you've written code to make something happen, however mistakenly, you cannot get the right results.

cc: @ezioda004 please close

**Comment by thecodingaviator** [comment] 2019-01-16 06:36
We cannot make the screen stop for some time before the code is executed for a challenge alone. It would either happen for the whole curriculum or not.

How we render pages is that after a set amount of time after the user stops typing, we display the output, so stopping it till the user wants is not possible

**Comment by ezioda004** [comment] 2019-01-16 07:09
Hi @rupali317,

The code gets executed as soon as someone types something on the client side. Sadly, this is something we cannot configure for just 1 challenge.

I'm closing this as its not a bug/issue.

**Closed by ezioda004** 2019-01-16 07:09 UTC
