### ISSUE TITLE
"Create a Form Element" Error

### ISSUE THREAD

**Issue by twodeux** [freeCodeCamp/freeCodeCamp#14310] opened 2017-04-08 20:24 UTC
Create a Form Element
https://www.freecodecamp.com/challenges/create-a-form-element#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%22%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%3E%3C%2Fform%3E%0A

Chrome blocks the code visualiser
This was a very simple nesting exercise but for some reason I cannot see the results of my coding because apparently the form tag is seen as malicious? I tried resetting my code but nothing seems to work.

Google Chrome, macOS Sierra, Macbook Pro 

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

My Code
```
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo"><input type="text" placeholder="cat photo URL"></form>




```
Screenshot
<img width="1279" alt="screen shot 2017-04-08 at 10 23 30 pm" src="https://cloud.githubusercontent.com/assets/24417739/24832180/0e3dfd0c-1caa-11e7-8b75-6e7c1cb03b5e.png">

**Comment by mendozra** [comment] 2017-04-09 04:00
I'm sort of reproducing a similar issue:

 
![image](https://cloud.githubusercontent.com/assets/7257940/24834560/7b788d8a-1cb7-11e7-8a71-1fe6e1f61337.png)

**Comment by hariscalculator** [comment] 2017-04-10 05:39
problem is in google chrome your code is good

**Comment by heyDante** [comment] 2017-04-10 06:00
If you are having this error, try using different browser instead (firefox).

**Comment by kartickey** [comment] 2017-04-14 13:04
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
<input type="text" placeholder="cat photo URL">
</form>

https://i.gyazo.com/d7b7247148b6be9a91f72cc3b938d50d.png

you can see here the code is working fine for me

**Comment by mendozra** [comment] 2017-04-15 14:42
Yea, looks this was a browser related issue and not a code problem.  Thanks
all for your time a help

On Apr 14, 2017 9:06 AM, "kartickey" <notifications@github.com> wrote:

<style> .red-text { color: red; }

h2 {
font-family: Lobster, Monospace;
}

p {
font-size: 16px;
font-family: Monospace;
}

.thick-green-border {
border-color: green;
border-width: 10px;
border-style: solid;
border-radius: 50%;
}

.smaller-image {
width: 100px;
}
</style>
CatPhotoApp

Click here for cat photos <#m_2584339231067837758_>.

[image: A cute orange cat lying on its back.] <#m_2584339231067837758_>

Things cats love:

   - cat nip
   - laser pointers
   - lasagna

Top 3 things cats hate:

   1. flea treatment
   2. thunder
   3. other cats

https://i.gyazo.com/d7b7247148b6be9a91f72cc3b938d50d.png

you can see here the code is working fine for me

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/14310#issuecomment-294150246>,
or mute the thread

**Comment by LarrisUK** [comment] 2017-04-16 13:44
Somebody else opened an issue on this a couple of days ago: #14394 

Is there any chance FCC can provide a workaround for the problem seeing that [Chrome is by far the most widely used web browser in the world? ](https://www.w3schools.com/browsers/). I'm obviously new to all this, but what happens in 'the real world' when we design a web page and it doesn't work for the end user?-  Add a disclaimer on the site saying 'Sorry, you have to install another browser in order for this feature to work'??

I want to continue using Chrome for my learning, so can someone give any advice on how to proceed? Should I wait for a fix, or is there a way to bypass this and move on to the next lesson?
If I do part of the course in a different browser, will it still be registered against my account that I completed these modules? (I'm guessing yes, but want to check)

**Comment by heyDante** [comment] 2017-04-16 15:26
Well just login with your freeCodeCamp account on Mozilla and complete the lesson, after that you can continue on Chrome as usual. 
I bet it's just this specific exercise creating problems on Chrome.

**Comment by LarrisUK** [comment] 2017-04-19 12:27
I did it, it worked, and have decided just to carry on learning in Firefox. 
Now I never have to resort to IE again, even in an emergency.

**Comment by erictleung** [comment] 2017-04-23 20:47
Closing as duplicate of an even earlier issue https://github.com/freeCodeCamp/freeCodeCamp/issues/13727. Take a look at the thread over there for possible workarounds. I think there are some people working on a solution. A possible workaround is to just use a different browser for this challenge and any others that involve forms. Happy coding!

**Closed by erictleung** 2017-04-23 20:47 UTC
