### ISSUE TITLE
Unable to check account closed & Missing user story

### ISSUE THREAD

**Issue by jaylane** [freeCodeCamp/freeCodeCamp#15222] opened 2017-06-05 18:53 UTC
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I'm working on this project now and since it is suggested to use the third party api in lieu of registering for a twitch.tv api key, I don't think one of the user stories works now. The json response for one of the suggested closed account users (comster404) is as follows:

{"stream":null,"_links":{"self":"https://api.twitch.tv/kraken/streams/comster404","channel":"https://api.twitch.tv/kraken/channels/comster404"}}

this is the same response as an active offline account, so I don't see a way to distinguish between the two.

Another minor issue is that the video shows a bonus user story to search for users via text input which isn't shown in the current project objective list.

**Comment by Fubinator** [comment] 2017-06-05 20:17
I think that is intended behaviour. You can call the "https://wind-bow.glitch.me/twitch-api/channels/" endpoint to see if a channel still exists. If it does not exist the response's status code is 404. That would be a way to distinguish wether the channel exists or is just offline.

**Comment by raisedadead** [comment] 2017-06-11 22:02
Sorry to get back late on this, although this was reported earlier. I am closing this in favor of #15321

**Closed by raisedadead** 2017-06-11 22:02 UTC
