### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by vortle86** [FreeCodeCamp/freecodecamp#688] opened 2015-05-28 05:38 UTC
Directions say :Let's try this again, but with margin this time. Use Clockwise Notation to give an element a margin of **40 pixels on its top and left side**, but only 20 pixels on its bottom and right side.

But criteria say 
Your green-box class should give the **top of elements 20px of margin.**
 Your green-box class should give the left of elements 40px of margin.
 Your green-box class should give the bottom of elements 20px of margin.
 Your green-box class should give the right of elements 20px of margin.

Accepts 
margin:40px 20px 20px 40px; 

So just need to correct the px in the criteria for match to 40px on top.
Cheers!

**Comment by terakilobyte** [comment] 2015-05-28 11:03
Thanks, closing this as a duplicate of #665

**Closed by terakilobyte** 2015-05-28 11:03 UTC
