### ISSUE TITLE
Make Images Mobile Responsive

### ISSUE THREAD

**Issue by govindakrgupta** [freeCodeCamp/freeCodeCamp#14001] opened 2017-03-19 13:49 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![screenshot_1](https://cloud.githubusercontent.com/assets/25879813/24081393/d3d5aee8-0c6f-11e7-90fe-a8f66fa67bc3.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/25879813/24081394/d3fb0666-0c6f-11e7-9ffa-b22b7614c2c0.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/25879813/24081395/d4008a1e-0c6f-11e7-8732-bdcc32059b90.jpg)

**Comment by mnedariya** [comment] 2017-03-19 14:41
@govindakrgupta u were putting wrong code for that try this :-
<a href="#"><img class="img-responsive"src="https://bit.ly/fcc-running-cats" alt="Running cats."></a>

**Comment by almesh** [comment] 2017-03-19 15:35
تم الإرسال من جهاز Samsung

Hi @govindakrgupta
The issue tracker is for reporting bugs only. If this is a request for help with a challenge, please use the help chat room or try looking through the forum for help with a specific challenge.
If this is the case, please close this issue.
Happy Coding.
--

Automated response by Var.CI 🤖

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@VarCI-bot in #14001: Hi @govindakrgupta

The issue tracker is for reporting bugs only. If this is a request for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

If this is the case, please close this issue.

Happy Coding.


--
_Automated response by [Var.CI](https://var.ci)_ :robot:"}],"action":{"name":"View Issue","url":"https://github.com/freeCodeCamp/freeCodeCamp/issues/14001#issuecomment-287617946"}}}

**Comment by govindakrgupta** [comment] 2017-03-20 06:13
thank you soo much it hepl me alot!!!

**Comment by mnedariya** [comment] 2017-03-20 06:45
close this resipository if u got the mistake @govindakrgupta

**Comment by systimotic** [comment] 2017-03-20 08:36
Hi all! I'm closing this as an issue in the solution, not a bug in freeCodeCamp. `http` was used instead of the requested `https`

If you're looking for coding help, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Happy coding!

**Closed by systimotic** 2017-03-20 08:36 UTC
Labels: tests
