### ISSUE TITLE
Incorrect Challenge Test Case result on Chrome

### ISSUE THREAD

**Issue by zairmubashar** [freeCodeCamp/freeCodeCamp#11332] opened 2016-10-23 01:06 UTC
#### Challenge Name

FEDC -> Basic Javascript -> Nest one Array within Another Array
https://www.freecodecamp.com/challenges/nest-one-array-within-another-array
#### Issue Description

`var myArray = [myArray];` is treated as a correct solution. Sometimes it isn't immediately treated as correct, but upon running tests a second time it is. I haven't ever had to run tests more than twice to have this treated as correct.
#### Browser Information

- Browser Name, Google Chrome - Version 54.0.2840.59 (64-bit)
- Operating System: Linux Mint 17.3 Xfce 64-bit
- Mobile, Desktop, or Tablet: Laptop on a desk top.

I did try this bug on a Windows machine with Firefox. It isn't present. It _is_ present on Chrome however. I've used incognito mode in all cases. Windows Chrome version: 54.0.2840.71 m (64-bit)
#### Your Code

Full challenge code:

``` js
// Example
var ourArray = [["the universe", 42], ["everything", 101010]];

// Only change code below this line.
var myArray = [myArray]; 
```

**Comment by erictleung** [comment] 2016-10-23 05:34
@zairmubashar thanks for the issue. I wasn't able to fully reproduce your error but I think I know what is going on. The reason why it takes two tries for your code to work is that the tests are run right after each other and the values from the previous test run are still saved.

In other words, when you run the tests the first time, you get an array `myArray = [myArray]`, which when you `console.log()` it, it will return `[undefined]`.

However, when you run it again, you'll run `myArray = [myArray]` once more using the previous `myArray`, which will not change `myArray` to being a multi-dimension array of `[[undefined]]`, which satisfies the challenge.

This issue may or may not be fixed with the new changes upcoming.

cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment] 2016-10-23 10:59
Looks like the trouble with using global vars?

**Comment by Dayfiri** [comment] 2016-10-23 17:37
@raisedadead I would say it is a problem in assignment that doesn't require specific value inside the nested array. It passes when you give it to him `[[one_array]]` inside another.

1. Here we passed `ourArray` in myArray variable
![value_names](https://cloud.githubusercontent.com/assets/16082563/19628148/88198500-9957-11e6-9f07-a7db0e978ad9.png)

2. Here we passed myArray in myArray 
![value_no_names](https://cloud.githubusercontent.com/assets/16082563/19628160/ccb7bbdc-9957-11e6-829b-5bcc748a4dfd.png)

Both are good. And here is picture from Codepen with this assignment
![codpen](https://cloud.githubusercontent.com/assets/16082563/19628171/07f59480-9958-11e6-9fc9-ed17500ccccd.png)

And parser find it ok to let it pass on:
`Array [ Array[1] ]` example

**Comment by zairmubashar** [comment] 2016-10-23 19:38
@erictleung I think you're right, though it only takes two tries after I've already set ```myArray``` to something like ```1``` and failed the tests. I think that's because the default line ```var myArray = [];``` actually already sets ```myArray``` to ```[]``` before the user has a chance to play with the code.

I used
```js
// Example
var ourArray = [["the universe", 42], ["everything", 101010]];

// Only change code below this line.
var myArray = [myArray];
console.log(myArray);
```
to arbitrary nest ```myArray``` in the method you suggested. I did notice that each run logged ```myArray``` twice, but with 2 different values! The first was the arbitrarily nested array, while the second was always ```[undefined]``` (the keyword undefined). Firefox always returns ```[undefined]``` twice.

**Comment by Bouncey** [comment] 2016-10-31 00:06
You would get `[undefined]`, because the lexer hasn't had a chance to assign anything to `myArray`. 

Doing the same in my console might explain it better:
```js
let myArray = [myArray];
console.log(myArray); // Uncaught ReferenceError: myArray is not defined
```

If however you do:
```js
let myArray = [];
myArray = [myArray];
console.log(myArray); // [[]]
```

It is not a bug with FreeCodeCamp, but a feature(?) of the language.

I hope this clears up the issue.

**Closed** 2017-01-14 12:47 UTC
Labels: decayed
