### ISSUE TITLE
Test suite errors in Advanced Node and Express - Registration of New Users

### ISSUE THREAD

**Issue by daniel-vera-g** [freeCodeCamp/freeCodeCamp#18056] opened 2018-08-28 14:29 UTC
The `Advanced Node and Express` course is a little bit confusing since it has a lot of backdoors that enable errors and don't let pass the tests.
Currently, I am stuck at https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users/

This is my code:

```js
'use strict';

const express     = require('express');
const bodyParser  = require('body-parser');
const fccTesting  = require('./freeCodeCamp/fcctesting.js');
const session     = require('express-session');
const passport    = require('passport');
const mongo       = require('mongodb').MongoClient;
const ObjectID    = require('mongodb').ObjectID;
const LocalStrategy = require('passport-local');

const app = express();

fccTesting(app); //For FCC testing purposes
app.use('/public', express.static(process.cwd() + '/public'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.set('view engine', 'pug')

app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: true,
}));
app.use(passport.initialize());
app.use(passport.session());

mongo.connect(process.env.DATABASE, (err, db) => {
    if(err) {
        console.log('Database error: ' + err);
    } else {
        console.log('Successful database connection');

        passport.serializeUser((user, done) => {
          done(null, user._id);
        });

        passport.deserializeUser((id, done) => {
            db.collection('users').findOne(
                {_id: new ObjectID(id)},
                (err, doc) => {
                    done(null, doc);
                }
            );
        });
      
        passport.use(new LocalStrategy(
          function(username, password, done) {
            db.collection('users').findOne({ username: username }, function (err, user) {
              console.log('User '+ username +' attempted to log in.');
              if (err) { return done(err); }
              if (!user) { return done(null, false); }
              if (password !== user.password) { return done(null, false); }
              return done(null, user);
            });
          }
        ));
      
      
        function ensureAuthenticated(req, res, next) {
          if (req.isAuthenticated()) {
              return next();
          }
          res.redirect('/');
        };
      

        app.route('/')
          .get((req, res) => {
            res.render(process.cwd() + '/views/pug/index', {title: 'Hello', message: 'login', showLogin: true, showRegistration: true});
          });
      
        app.route('/login')
          .post(passport.authenticate('local', { failureRedirect: '/' }),(req,res) => {
               res.redirect('/profile');
          });
      
        app.route('/profile')
          .get(ensureAuthenticated, (req, res) => {
               res.render(process.cwd() + '/views/pug/profile', {username: req.user.username});
          });
      
        app.route('/register')
          .post((req, res, next) => {
              db.collection('users').findOne({ username: req.body.username }, function (err, user) {
                  if(err) {
                      next(err);
                  } else if (user) {
                      res.redirect('/');
                  } else {
                      db.collection('users').insertOne(
                        {username: req.body.username,
                         password: req.body.password},
                        (err, doc) => {
                            if(err) {
                                res.redirect('/');
                            } else {
                                next(null, user);
                            }
                        }
                      )
                  }
              })},
            passport.authenticate('local', { failureRedirect: '/' }),
            (req, res, next) => {
                res.redirect('/profile');
            }
        );
      
        app.route('/logout')
          .get((req, res) => {
              req.logout();
              res.redirect('/');
          });

        app.use((req, res, next) => {
          res.status(404)
            .type('text')
            .send('Not Found');
        });

        app.listen(process.env.PORT || 3000, () => {
          console.log("Listening on port " + process.env.PORT);
        });  
}});
```

My Index page has the title `Home Page` and my profile page `Profile Page`.

Here are the errors(very helpful..): 
![image](https://user-images.githubusercontent.com/28257108/44729365-f6825b80-aade-11e8-8a5f-fd8c85b2a11d.png)

I've tried:
* https://gist.githubusercontent.com/JosephLivengood/6c47bee7df34df9f11820803608071ed/raw/f18557c4726673ca44e3b8a89f07438deb4e4a1f/server.js
* https://forum.freecodecamp.org/t/advanced-node-registration-of-new-users/204585/6
* https://github.com/freeCodeCamp/freeCodeCamp/issues/17820
* https://forum.freecodecamp.org/t/advanced-node-and-express-registration-of-new-users/208071/8

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04 LTS

I've experinced also other Issues in the past parts of the course, like for example that you need to change the title of the index.pug & profile.pug pages. The problem is that this is not mentioned anywhere. 

**UPDATE**

I tested it also with the official solution given two lessons forward in https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/clean-up-your-project-with-modules/

Code: https://delicious-herring.glitch.me

And it also does not work.

**Comment by Moto42** [comment] 2018-12-08 23:15
The further you go into the curriculum, the more out of date it becomes.

I can't seem to get to your code, and this is many months late, BUT this might help others googling their problem too...

If you are getting an error "collection.db is not a function, This should help.

Goto package.json
In your dependencies, change the version of "mongodb" to "2.2.33".

The code in the base project uses an out of date version of mongoDB, but doesn't warn you of this when it asks that you install and add it to your dependencies.

**Comment by moT01** [comment] 2019-05-06 17:56
Thanks for the detailed issue description, but this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17820 - So I think it's safe to close this. Thanks and happy coding!

**Closed by moT01** 2019-05-06 17:56 UTC
Labels: help wanted, scope: curriculum

**Comment by SamVarejao** [comment] 2020-02-10 19:27
The HOW :
mongo.connect( ... (err, client) => {
   const db = client.db("yourDataBaseName");
... })
The WHY:
As mentioned before, some FCC challenges are out of date, and Mongo changed a bit since these lessons came out/ were updated.
MORE INFO: http://mongodb.github.io/node-mongodb-native/3.0/quick-start/quick-start/
