### ISSUE TITLE
html element lesson: url image(the cat) not working.

### ISSUE THREAD

**Issue by aseds** [FreeCodeCamp/FreeCodeCamp#4746] opened 2015-11-28 01:00 UTC
http://bit.ly/fcc-relaxing-cat

this link does not open

**Comment by SaintPeter** [comment] 2015-11-28 01:03
Works fine for me. It is hosted on Amazon's services.  It sounds like it's a local networking issue.  Could be related to proxies or VPN, or possibly a plugin you are running in your browerser.

Closing as unable to reproduce.

Thanks and Happy Coding!

**Closed by SaintPeter** 2015-11-28 01:03 UTC

**Comment by aseds** [comment] 2015-12-01 22:20
it worked after maybe three lessons. and thank you.
