### ISSUE TITLE
Preview is blank, won't update when typing in code and the "Run tests" button is unresponsive

### ISSUE THREAD

**Issue by Aki-hiko** [FreeCodeCamp/FreeCodeCamp#10681] opened 2016-09-10 19:06 UTC
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello,

The code preview on the right hand side of the page is completely blank and will not update when new code is typed into the editor. Also the "Run Tests" button is unresponsive.  I have tried to use three web browsers: Goggle chrome, Firefox and Safari. All three web browsers have the exact same problem so I think perhaps there is something wrong with the FCC site currently or there is something wrong on my end. Is this a common issue? Any help would be appreciated.

Thank you

<img width="1648" alt="fcc problem" src="https://cloud.githubusercontent.com/assets/17350098/18412900/3685216c-7757-11e6-9e0a-063233bea35b.png">

My code:
```

<style>
  .red-text {
    color: blue;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Aki-hiko** [comment] 2016-09-10 19:09
I am reporting an issue with the site itself. I have no problem with the challenge. 

Note: I realize the code in the screen shot should be "Class="red-text" not "blue-text". The issue remains.

**Comment by P1xt** [comment] 2016-09-10 19:40
@Aki-hiko Don't worry about @VarCI-bot It's a bot. Your issue is a real bug so you can safely ignore the bot.

Your issue might be a duplicate of this one though:

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678

It sounds like you're experiencing the same bug that others reported earlier. Anecdotally, it's been reported that while you're waiting for the bug to be fixed, if you refresh your browser a few times, you may be able to proceed for a while.

**Comment by JesterMan** [comment] 2016-09-10 20:03
A work around that performs for me is to refresh the browser until the tests show up and the display functions. (Usually not more than 3 refreshes).

The tests will usually be marked as passing at this point, but you'll need to run them again.

When that stops working (around 5 lessons), I close the browser window and open https://www.freecodecamp.com/ in a new window.

**Comment by QuincyLarson** [comment] 2016-09-11 05:40
This issue has now been fixed. If you notice this problem again, please reopen it with an explanation of the problem. Thanks for reporting this.

**Closed by QuincyLarson** 2016-09-11 05:40 UTC
Labels: question
