### ISSUE TITLE
Pressing enter on search bar deletes query

### ISSUE THREAD

**Issue by coder077** [freeCodeCamp/freeCodeCamp#35434] opened 2019-02-27 02:02 UTC
**Describe the bug**
When typing a search for a new query in the main learn site  learn.freecodecamp.org, it redirects to a new tab. This new tab https://search.freecodecamp.org/ has the same query but if you type any query on it and press enter, it completely deletes the query and returns a blank result.

**To Reproduce**
1. Go to learn.freecodecamp.org and type in any query in the search bar. You will be redirected to a new tab.
2. Click on the search bar and press enter or write any new query and press enter.
3. You will see that the query in the search bar disappears and no result is given.

**Expected behavior**
Once we get to the https://search.freecodecamp.org/ site and press enter, we expect the query to remain and receive a list of results instead of a blank.

**Screenshots**
<img width="1054" alt="screen shot 2019-02-26 at 9 00 16 pm" src="https://user-images.githubusercontent.com/18624843/53459989-8f038500-3a09-11e9-8edc-0e435e185d43.png">

After pressing enter:
<img width="1136" alt="screen shot 2019-02-26 at 9 01 10 pm" src="https://user-images.githubusercontent.com/18624843/53460031-acd0ea00-3a09-11e9-8683-518cbba20da8.png">

**Desktop (please complete the following information):**
 - OS:  iOS, Ubuntu
 - Browser chrome

**Comment by RandellDawson** [comment] 2019-02-27 02:07
Closing this issue, because it is a duplicate of #29311

**Closed by RandellDawson** 2019-02-27 02:07 UTC
