### ISSUE TITLE
learn-how-script-tags-and-document-ready-work has an issue

### ISSUE THREAD

**Issue by wsroberts** [FreeCodeCamp/FreeCodeCamp#3155] opened 2015-09-08 01:33 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

For this problem, I used the following code:
 
```html
<script type="text/javascript">
$(document).ready(function(){
});</script>
```

The last 3 learning 'goals' will show checked and complete, but the first one: "Create a script element" will not for some reason. Not sure why. Thanks for your time

williamroberts643@hotmail.com

**Comment by wsroberts** [comment] 2015-09-08 01:34
<script type="text/javascript">
$(document).ready(function(){
});</script>

**Comment by BerkeleyTrue** [comment] 2015-09-08 16:27
Please read:
 https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue
and
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting

**Comment by benschenker** [comment] 2015-09-09 03:58
@wsroberts can you post a screenshot here?

This may be a duplicate of #1858.

**Comment by bugron** [comment] 2015-09-09 04:04
@wsroberts you are unable to pass that test because of `type="text/javascript"` attribute.

**Closed** 2015-09-18 05:52 UTC

**Comment by Myates87** [comment] 2017-05-02 14:13
I tried this multiple times with no pass. I would copy the code and paste it into editor. Submit my answer and .. nothing. I told myself "just type it out so you might be able to remember it or recall it later". Hand typed it and boom worked.
