### ISSUE TITLE
[beta] First CSS challenges won't work in Firefox

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#12677] opened 2017-01-21 06:53 UTC
#### Issue Description

I can't pass the first challenge (Basic Css: Change the Color of Text). The `<h2>` is clearly red, but the test won't pass.

I tried the next challenge (Basic Css: Use CSS Selectors to Style Elements), and out of the five tests, one won't pass (again it seems it can't pick up the `<h2>`'s color). 

#### Browser Information

* Browser Name, Version: Firefox 50.1.0
* Operating System: Windows 7 Professional Service Pack 1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/17902987/22172707/28c9c7e4-dfe9-11e6-97cd-004eceb471a4.PNG)

**Comment by systimotic** [comment] 2017-01-21 13:20
@kevcomedia Can you check whether this is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/10595?

**Comment by kevcomedia** [comment] 2017-01-21 23:33
I tried the challenges referred to in #10595 in the live site in Firefox, and in beta in both Firefox and Chrome.

Out of all the challenges listed there, only one worked in _Firefox: Beta_:
- Basic Css: Change the Font Size of an Element

All of the challenges worked in _Firefox: Live site_ and _Chrome: Beta_.

**Comment by systimotic** [comment] 2017-01-22 10:10
@kevcomedia Awesome, thanks for testing. That does mean that it's the same issue as #10749, so I'll close this issue.
The reason that one challenge is passing now is because the CSS test was rewritten into a RegEx test.

**Closed by systimotic** 2017-01-22 10:10 UTC
Labels: beta

**Comment by masters-george** [comment] 2017-01-29 22:09
Problem is also reproducible in Chrome, and Opera on Windows and Linux machines. See attached screen shot for an example.

![clipboard02](https://cloud.githubusercontent.com/assets/24727860/22408362/88dd54a4-e62c-11e6-9a4e-25c91cd99280.jpg)

**Comment by systimotic** [comment] 2017-01-29 22:31
@masters-george Can you share a screenshot of the test not passing in Chrome? The shared screenshot shows Firefox, which we know is broken (see #10749). It would also be helpful to see which tests exactly aren't passing, with what code.
Thanks for trying out the beta and reporting bugs!

**Comment by masters-george** [comment] 2017-01-30 00:14
Hi Timo,

Thanks for getting back to me. I just ran some tests at our public library
using their windows computers with chrome. Chrome on Windows7 is OK. I am
suspecting the issue is with Chrome on Linux. I'll run some further tests
tonight. This new course is pedagogically improved over the production
course.

On Jan 29, 2017 2:33 PM, "Timo" <notifications@github.com> wrote:

@masters-george <https://github.com/masters-george> Can you share a
screenshot of the test not passing in Chrome? The shared screenshot shows
Firefox, which we know is broken (see #10749
<https://github.com/freeCodeCamp/freeCodeCamp/issues/10749>). It would also
be helpful to see which tests exactly aren't passing, with what code.
Thanks for trying out the beta and reporting bugs!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/12677#issuecomment-275951737>,
or mute the thread

**Comment by masters-george** [comment] 2017-01-30 04:49
Timo,

Just completed tests on both my Linux machines. It appears to be
network-related. I replicated the problem then rebooted the network
gateway. Problem went away. Go ahead and close the issue. The beta course
appears to be working on both Ubuntu Linux 16.04 and 16.10 using Chrome. I
did not retest with Opera.

George Masters
instructional Designer /Trainer
408.242.4632

**Comment by TheRealChrisEdwards** [comment] 2017-02-19 07:21
Still having problems with Basic CSS challenges:
1. Change the Color of Text
2. Use CSS Selectors to Style Elements  
posted my info & screenshots in [#10595](https://github.com/freeCodeCamp/freeCodeCamp/issues/10595)
