### ISSUE TITLE
Cypress with Firefox keeps crashing 

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39679] opened 2020-09-24 18:39 UTC
![image](https://user-images.githubusercontent.com/1884376/94185731-4c46af00-fec3-11ea-99a6-208fb6bc460a.png)

**Comment by raisedadead** [comment] 2020-09-24 18:44
Dropping Firefox support temporarily with [`1bb0bdb` (#39677)](https://github.com/freeCodeCamp/freeCodeCamp/pull/39677/commits/1bb0bdb80abebcf4cfc203622c9e64d49d8cba6c). This was causing me to slow down with the PRs and rapid testing we are doing on the staging.

I will let someone else investigate this.

**Comment by ojeytonwilliams** [comment] 2020-09-24 21:11
@Twaha-Rahman any thoughts on this one?  I'll take a look when I can, but I figured you might have some insight.

**Comment by Twaha-Rahman** [comment] 2020-09-25 02:31
I'll look into it soon. Will let you know when I get to the bottom of it.

**Comment by Twaha-Rahman** [comment] 2020-09-25 06:35
Mrugesh shared two links to the CI runs that failed and both of them failed for the `leran/challenges/output.js`. So, I was looking at the test and saw a lot of explicit timeout increasing... this is probably the reason why it fails on Firefox. Because the timeout were increased by watching the time it took on Chrome and manually adjusting it. But Firefox normally needs a few more seconds to finish running (this is due to [Firefox's controlled GC cycle in Cypress](https://docs.cypress.io/guides/references/configuration.html#firefoxGcInterval)).

I think increasing the timeout limit should do the trick.

**Comment by ojeytonwilliams** [comment] 2020-09-25 08:56
> So, I was looking at the test and saw a lot of explicit timeout increasing

We do wait for the editor, but everything after that should be basically instantaneous.

> But Firefox normally needs a few more seconds to finish running (this is due to Firefox's controlled GC cycle in Cypress).

Thanks for investigating that, but it should be fixed for Firefox 80 (https://github.com/cypress-io/cypress/issues/6187) and that's what we run the tests on.

Also, [this config](https://github.com/marketplace/actions/cypress-io#firefox) suggests we should be using ` options: --user 1001` which could be a factor, but would have thought that would make things fail entirely rather than run slowly.

> I think increasing the timeout limit should do the trick.

That could work, yeah.  The strange thing is the dev mode works perfectly locally and the CI should be even faster, since it uses the built site.

**Comment by Twaha-Rahman** [comment] 2020-09-25 15:44
> Thanks for investigating that, but it should be fixed for Firefox 80 ([cypress-io/cypress#6187](https://github.com/cypress-io/cypress/issues/6187)) and that's what we run the tests on.

The bug is fixed on Firefox but Cypress still manually triggers GC as it is said in the Cypress docs (also when you run the tests locally in Firefox, it'll show you a message about GC. This is because Cypress doesn't manually run GC on `open` but when it's run in CI using `run` then Cypress manually triggers GC).

> Also, [this config](https://github.com/marketplace/actions/cypress-io#firefox) suggests we should be using ` options: --user 1001` which could be a factor, but would have thought that would make things fail entirely rather than run slowly.

I agree. I don't think this is the reason.

> The strange thing is the dev mode works perfectly locally and the CI should be even faster, since it uses the built site.

I couldn't reproduce the bug locally... maybe we should try to reproduce it in CI by running it repeatedly?

**Comment by ojeytonwilliams** [comment] 2020-09-25 17:02
> The bug is fixed on Firefox but Cypress still manually triggers GC as it is said in the Cypress docs (also when you run the tests locally in Firefox, it'll show you a message about GC. This is because Cypress doesn't manually run GC on open but when it's run in CI using run then Cypress manually triggers GC).

Right, but would this make a test fail?  If it runs between tests, which is the default, it should just make the whole run a bit slower.  If it's included in the timeout for a particular test, that would be a massive oversight.  My assumption is that the only timeout you might hit because of this is the limit for the entire run.

> I couldn't reproduce the bug locally... maybe we should try to reproduce it in CI by running it repeatedly?

Sure.  I'll let @raisedadead decide when he wants to do this, though, since it makes deploying a bit of a headache (if you're being bombarded with fail negatives, I mean).

**Comment by raisedadead** [comment] 2020-09-27 18:23
I am open to creating a new branch on the upstream if you need to test it on CI by adding random commits? In theory you should be able to test it on a fork as well.

**Closed** 2020-12-14 17:50 UTC
Labels: scope: tools/scripts, type: bug
