### ISSUE TITLE
challenge does not complete testing in Safari

### ISSUE THREAD

**Issue by cwkatzmann** [FreeCodeCamp/FreeCodeCamp#7033] opened 2016-02-15 16:09 UTC
Challenge [Make Object Properties Private](http://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function%28%29%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function%28change%29%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function%28%29%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function%28%29%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function%28%29%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car%28%29%3B%0A%0Avar%20myBike%20%3D%20new%20Bike%28%29%3B%20%7B%0A%20%20var%20gear%20%3D%201%3B%0A%0A%20%20this.setGear%20%3D%20function%28newGear%29%20%7B%0A%20%20%20%20gear%20%3D%20newGear%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20this.getGear%20%3D%20function%28%29%20%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%20%20%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/537.86.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Using Safari 9.0.3 (9537.86.4.4). 

Console indicates that it is testing the challenge, but then freezes. Challenge tests and code passes on Chrome.

My code:

``` javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.

};

var myCar = new Car();

var myBike = new Bike(); {
  var gear = 1;

  this.setGear = function(newGear) {
    gear = newGear;
  };

  this.getGear = function() {
    return gear;
  };

}
```

**Comment by ltegman** [comment] 2016-02-15 17:26
This code _passes_ for you in Chrome? When I run it in Chrome it fails every test but one. There's a lot of issues with this code, but our test runner still shouldn't crash when it runs this code. It looks like it's being caused by the unassigned object literal at the bottom and this is the console error I get:
![make_object_properties_private___free_code_camp_and_challenge_does_not_complete_testing_in_safari_ _issue__7033_ _freecodecamp_freecodecamp](https://cloud.githubusercontent.com/assets/1381313/13055753/fbe174d2-d3c5-11e5-9f08-4e2b0755f0af.png)

We'll probably need to run this code in an unminified dev environment to really get to the bottom of what is making it throw.

**Comment by cwkatzmann** [comment] 2016-02-15 17:37
Ah, seems I re-wrote it correctly (I can only assume?) when I tried in Chrome. Did not copy-paste... the below code passes the tests in both Safari and Chrome.

Still, the console does not complete testing when the original code I provided is run.

`var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
var gear = 1;
  
  this.setGear = function(newGear) {
    gear = newGear;
  };
    
  this.getGear = function() {
    return gear;
  };
};

var myCar = new Car();

var myBike = new Bike();
`

**Comment by crashuniverse** [comment] 2016-06-08 18:41
@cwkatzmann For readability you can select a text like _var myCar = new Car();_ and click insert code button which looks like < > on top right corner of edit / add comment. Once you do this var myCar = new Car(); looks like `var myCar = new Car();`. Much better, right?

**Comment by crashuniverse** [comment] 2016-06-08 18:56
This works for me on Chrome and Safari, both. When I say this, I mean the correct code written in 2nd comment in this thread excluding the issue description. This should be verified in May 2015 to see if it is still valid.

**Comment by atjonathan** [comment] 2016-06-08 19:28
@cwkatzmann @crashuniverse, I updated the comment to use code blocks and javascript syntax highlighting.

**Comment by dhcodes** [comment] 2016-08-12 15:44
I'm digging through some old issues and just wanted to add to this that I have run the second set of code in Safari and it passes with no console errors. Safari version 9.1.2.

May need more information though.

**Comment by QuincyLarson** [comment] 2017-01-04 06:16
@dhcodes thanks for confirming this. I'm closing this since no one has complained further about it.

**Closed by QuincyLarson** 2017-01-04 06:16 UTC
Labels: bug, help wanted
