### ISSUE TITLE
Feature Request: Navigating through Challenges

### ISSUE THREAD

**Issue by WillzMu** [freeCodeCamp/freeCodeCamp#34733] opened 2018-12-23 15:27 UTC
When doing a challenge for a particular module, if I want to go back to a previous challenge for reference, I have to go to "Curriculum" then scroll to find that challenge.

My feature request is to have a forward and back button for someone to easily scroll through challenges maybe above the description section.

Thank you

**Comment by moT01** [comment] 2019-02-09 18:55
Thanks for reporting this suggestion @WillzMu - however, this appears to be a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17509 - make sure to do a search before creating a new issue to see if someone else already created something related. You may have done that, sometimes they're tough to find.  Thanks and happy coding!

**Closed by moT01** 2019-02-09 18:55 UTC
