### ISSUE TITLE
Oops! Something went wrong. Please try again later

### ISSUE THREAD

**Issue by D-blaze** [FreeCodeCamp/FreeCodeCamp#6903] opened 2016-02-11 19:11 UTC
I keep getting this error: "Oops! Something went wrong. Please try again later" when clicking on my map in Basic JavaScript. Also the site seems generally slow and has been for over a week.

Thanks

Dave

**Comment by ltegman** [comment] 2016-02-11 19:15
We recently deployed an update to the site intended to resolve the speed issues, but it may cause temporary slowdowns while migration occurs. Closing as a duplicate of #6901. Thanks and happy coding!

**Closed** 2016-02-11 19:15 UTC
