### ISSUE TITLE
Button "close map aside" does not work

### ISSUE THREAD

**Issue by osmarpixuri** [FreeCodeCamp/FreeCodeCamp#6588] opened 2016-01-29 22:02 UTC
Clicking the button "close map aside" does not collapse the map on the screen's side, overlapping all other pages.

**Comment by SaintPeter** [comment] 2016-01-29 22:35
You have not provided any information about your system or browser.

This is almost certainly a duplicate of one of several bugs:
#6566
#6189

Closing as presumed duplicate.

**Closed by SaintPeter** 2016-01-29 22:35 UTC
