### ISSUE TITLE
No explaination of multiple Classes - CSS Markers Step 16

### ISSUE THREAD

**Issue by bellhuffstutler** [freeCodeCamp/freeCodeCamp#46136] opened 2022-05-24 16:52 UTC
### Describe the Issue

 So I looked up how to do it, so I don’t need help with the issue, but as far as I can tell, there’s no way to solve Step 16 of the CSS Markers lessons without using outside sources.

It tells you to add a second class to the div, but at no point up to that lesson have you ever done that, nor is there any indication that what you actually do is add it to the first class with simply a space. The error message is also incredibly unhelpful in that regard.

Any time we’ve done multiples of things, it’s been with commas, or adding a second one, so presumably someone would just either add another class variable and fail, or try with a comma and fail.

the screenshot shows an example of how this could be both confusing and frustrating, because i have both the classes in the div, and have been given no explanation of why it doesn’t work:
![image](https://user-images.githubusercontent.com/106115808/170089175-eae99131-fc21-4e01-b3e5-a0a960c2f324.png)

I am really enjoying the new style of lessons, and i can’t wait for the rest of the lessons to catch up, and i was just hoping pointing this out could help, or at least be a way for someone to show me where there was this concept covered before this lesson.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-16

### Steps to Reproduce

Simply do <div class="marker, one"></div> 

the error message is unhelpful when the concept of multiple classes hasn't been explained yet. 

### Recommended fix or suggestions

Rewording the request (i.e. 'Replace the class "one" with "marker one"') or add a hint in the error message (i.e. "To use multiple classes, they are seperated by a whitespace)

**Comment by lasjorg** [comment] 2022-05-24 17:42
@bellhuffstutler Thank you for opening this.

I should have looked first before telling you to open an issue for this as there is already an issue open for it. That is my bad, sorry. I will close this as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/46097

But again, do feel free to open issues if you spot any other problems. Just check the issues first to make sure it isn't a duplicate. I realize it can be a little difficult sometimes, try doing a search first.

**Closed by lasjorg** 2022-05-24 17:42 UTC
Labels: type: bug, status: waiting triage

**Comment by bellhuffstutler** [comment] 2022-05-24 18:00
I will keep that in mind thanks!
