### ISSUE TITLE
change color style

### ISSUE THREAD

**Issue by scottpepperman** [FreeCodeCamp/FreeCodeCamp#11931] opened 2016-12-05 16:20 UTC
Here's how you would set your h2 element's text color to blue:

```
<h2 style="color: blue">CatPhotoApp</h2>
```

Change your h2 element's style so that its text color is red.Challenge 

my answer

```
<h2>"style="color: red">CatPhotoApp</h2>
```

so whats wrong?

[Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%3E%22color%3A%20red%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8743.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2>"color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by voronovmax** [comment] 2016-12-05 17:23
Hi,

The code for h2 tag should be:
<h2 style="color: red">CatPhotoApp</h2>

**Comment by erictleung** [comment] 2016-12-05 17:24
@scottpepperman Thank you for reporting this issue. Your code is incorrect. Please take a look at the two pieces of code you've written and compare the two. There is a difference that makes one correct and the other one not.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Closed by erictleung** 2016-12-05 17:24 UTC

**Comment by mht2** [comment] 2016-12-17 18:03
I know the issue is closed but I am also experiencing no success in getting this code snippet to work.  Make the following h2 text style red.
=======
<h2> style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
======
Result is this error with a red x next to the error statement:

Your h2 element should be red.

**Comment by mht2** [comment] 2016-12-17 18:06
My copy/paste didn't pick up the entire statement.  It's:

<h2 style="color: red">CatPhotoApp</h2>
