### ISSUE TITLE
Waypoint Manipulate Arrays With Shift missing keyword var

### ISSUE THREAD

**Issue by iheartkode** [FreeCodeCamp/FreeCodeCamp#4868] opened 2015-12-01 17:37 UTC
<code>removedFromOurArray = ourArray.shift(); // removedFromOurArray now equals "Stimpson" and ourArray now</code>
Is missing the var keyword.

<img width="928" alt="bug" src="https://cloud.githubusercontent.com/assets/7018580/11508661/d16f4f6e-980e-11e5-89a7-c7f70dfe4c38.PNG">

**Comment by bugron** [comment] 2015-12-01 17:43
@iheartkode thanks for posting. Closing this issue as a duplicate of #4864.

**Closed by bugron** 2015-12-01 17:43 UTC

**Comment by iheartkode** [comment] 2015-12-01 21:30
I even searched for this and found nothing, odd.
