### ISSUE TITLE
Auto refreshing editor runs bad code and crashes the browser.

### ISSUE THREAD

**Issue by AlexWulkan** [FreeCodeCamp/FreeCodeCamp#2222] opened 2015-08-19 18:34 UTC
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This exercise tells you to write ```$($(".slot")[0]).html(slotOne);```. So what happens when you do that?

Well, you start off by typing a dollar sign: ```$```
Then add parantheses (both parentheses are added automatically): ```$()```
Then add another dollar sign inside the parantheses: ```$($)```

Now when you do that is locks up the whole page. I don't know much jQuery yet, but the browser keeps on chugging like it's an infinite loop. This is a big downside to the constanly refreshing editor, it runs EVERYTHING. Even if the code is not complete yet and will crash the browser.

**Comment by michael-krebs** [comment] 2015-08-19 19:07
This is a duplicate of #2121

**Closed** 2015-08-26 00:10 UTC
