### ISSUE TITLE
Beta-CSS Grid- Align Elements Using Align Property - flex-end pushes elements off screen

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16839] opened 2018-03-06 14:02 UTC
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-flexbox/align-elements-using-the-alignitems-property

#### Issue Description

In the 'bonus' section, it suggests to try the other settings for align-items.
The align-items: flex-end pushes the elements in the preview out of view
Is there a way to make this preview area smaller so it stays in view?

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

my laptop 15" screen:
![image](https://user-images.githubusercontent.com/22984739/37036124-b1bc1be0-211c-11e8-9387-50ab24dd3ca8.png)

my secondary 17" monitor: 
![image](https://user-images.githubusercontent.com/22984739/37036255-16df5794-211d-11e8-8c5c-2e5f44ac1f7b.png)

**Comment by raisedadead** [comment] 2018-03-06 14:31
Looks like this is a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/16804

**Closed** 2018-03-07 23:16 UTC
Labels: beta
