### ISSUE TITLE
Lost most of my work last night version 2

### ISSUE THREAD

**Issue by anthonygallina1** [FreeCodeCamp/FreeCodeCamp#3651] opened 2015-10-08 09:22 UTC
I lost most of my work last night when there were problems on the server. I think this is the 4th time this has happened with my account. My points number reflects over 300 while my map does not.
I have been working at this for close to a year, if not over a year.
And the issue was closed even though my map is not restored to where it should be.

Lost most of my work last night #3629

Help please

**Comment by bugron** [comment] 2015-10-08 12:44
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3630.

**Closed** 2015-10-08 12:44 UTC

**Comment by hashemn** [comment] 2016-03-30 08:42
I completed 50 html and css lesssons and after a week i sign in and see all my work gone. I don't want to start again from beginning.
