### ISSUE TITLE
Manipulating Complex Objects - question

### ISSUE THREAD

**Issue by RomingArt** [freeCodeCamp/freeCodeCamp#12894] opened 2017-01-27 00:59 UTC
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
];

  {
    "artist": "Daft Punk",
    "title": "Homework",
    "release_year": 1997,
    "formats": [ 
      "CD", 
      "Cassette", 
      "LP" ],
    "gold": true
  }
];
```

Hello everyone, I been trying to pass this section for about two days, and I asked for help on github but no one responds. I been manipulating the code multiple times, and I even used the same example in the instructions but no luck passing the section if you could please explain in detail what I did wrong or what  is wrong with the code thank yo in advance.

**Comment by no-stack-dub-sack** [comment] 2017-01-27 03:59
@RomingArt Sorry that you were not getting the help you were looking for - were you in the gitter chat rooms?

The key to this challenge is in the instructions here: 
> Note
You will need to place a comma after every object in the array, unless it is the last object in the array.

Also, you should take a look at how many square brackets you have ( `[ ]` ) - if you have an odd number, something is up. All brackets, curly or square, need to have a matching opening or closing bracket. Here, you have an unnecessary closing bracket, and you are adding your object in the wrong place:

![image](https://cloud.githubusercontent.com/assets/18563015/22360061/85050b42-e41a-11e6-8ab3-04c061641a98.png)

The array that the challenge is referring to begins and ends where I've pointed out in the above image. You need to add your new object as a second element on that array. So where that comment is, it literally wants you to put it directly where it is, not under it. Where you originally had it, is actually _outside_ the `myMusic` array. And don't forget the note from the instructions that I pointed out up top! 😄  Good luck and I hope this helps. I'm closing this issue, but feel free to respond here anyway.

As it seems like you realize, this is mostly for reporting bugs, so try your best to seek help elsewhere first, but in situations like this, if you were unable to get help, you did the right thing!

**Comment by RomingArt** [comment] 2017-01-29 05:52
Hello everyone, thank you for your feedback, but I am still not able to pass this section, and I tried the code of @HasanFaraaz but it still does not let me pass.

**Comment by no-stack-dub-sack** [comment] 2017-01-29 19:20
@RomingArt, if you copied @HasanFaraaz's solution exactly, the code will not pass because there is an issue with his comment. As I can see, there is still not a bug with this challenge. Did my explanation not help any?

**Comment by HasanFaraaz** [comment] 2017-01-29 19:26
@RomingArt I have edited the code now, i had put a comment which I thought would be ignored(the comment was made bold & italic) now it should be fine. @no-stack-dub-sack

**Comment by no-stack-dub-sack** [comment] 2017-01-29 19:28
@HasanFaraaz Within code blocks on github, markdown does not work, so the bold and italic didn't come through, instead just the literal markdown:
```
_**ignored markdown**_
```

**Closed** 2017-01-29 19:32 UTC
Labels: question

**Comment by sintimmisa** [comment] 2018-05-25 12:34
try this 

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },    //note the comer here
  // Add record here
  
   {  
                "artist": "Paco de Lucia",
                "title": "Live in America",
                "release_year": 1992,
                "formats" : [  "CS", "8T", "LP" ]


             } 
];
