### ISSUE TITLE
Bonfire: Truncate a string - Last Argument is Broken

### ISSUE THREAD

**Issue by sinithwar** [FreeCodeCamp/FreeCodeCamp#5108] opened 2015-12-09 16:33 UTC
The code pretty much speaks for itself. I don't really know what to say about it.
![codebebroken](https://cloud.githubusercontent.com/assets/10654080/11691349/70645e7a-9e4f-11e5-8495-1cdd464706fb.png)

**Comment by ltegman** [comment] 2015-12-09 16:39
I can see your point, but I don't know that this is something we can solve. It's always going to be possible for users to code to the specific test cases unless we have an near infinite number of test cases or we start creating random tests. Random tests are an interesting idea, but they'd be a pretty big time investment for not a lot of gain.

I'm leaving this open for discussion, but I don't think there's ultimately a way to prevent users from going this route if they want to.

**Comment by sinithwar** [comment] 2015-12-09 16:48
Itegman, the backend code is messing up. Look at the last argument case. In the code, I've only added a singular period, whatever is happening behind the scenes is adding two more on top of this. Additionally, the spelling of the word itself is wrong. I had written an algorithm that would have solved this naturally, but it kept messing up because of the issues with the final argument case and it was only when I targeted that word specifically did I find the solution.

**Comment by mifuyne** [comment] 2015-12-09 16:50
That's your code doing it actually. You wrote two if statements, which the code will go through even if it fulfills the first.

You might want to use else if with your second if statement if the two conditions are meant to be mutually exclusive.

**Comment by sinithwar** [comment] 2015-12-09 16:52
mifune, I did actually write an if else statement. I had to separate it into separate arguments to narrow down the result to find out what was causing the issue. It's a bug.

**Comment by ltegman** [comment] 2015-12-09 16:53
@sinithwar Please copy and paste the code you are seeing this with so we can confirm it's not your code then.

**Comment by sinithwar** [comment] 2015-12-09 16:55
```
  if(str === "Abolutely Longer"){
    str = "Ab.";
  }
  if (str.length > num && str.length != 2){
    str = str.slice(0, num-3) + '...';
  }else if(str.length > num && num === 1){
    str = str.slice(0, num-2) + '...';
  }
```
If you notice, the str is checking for a Misspelled String, so it only works in case it is misspelled.

**Comment by ltegman** [comment] 2015-12-09 16:58
@sinithwar as @mifuyne said your code is wholly responsible for what is happening. You're making `str = "Ab."` and then running and `if-statement` that returns true because that string is both longer than num (`2`) and has a length that is not equal to `2`.

Closing as not a bug with the site. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) in the future for help with challenges.

Thanks and happy coding!

**Comment by sinithwar** [comment] 2015-12-09 17:02
I will reiterate.

The str is checking for a Misspelled String, so it only works in case it is misspelled.
``` "Absolutely Longer" != "Abolutely Longer" ```
If it didn't have a bug, the if statement would not work.

**Comment by ltegman** [comment] 2015-12-09 17:05
Sorry, I misunderstood your bug. There is indeed a misspelling in the passed argument.

**Comment by sinithwar** [comment] 2015-12-09 17:09
Additionally, when I wrote the initial code for that word it was on the end of the else if statement as
```
else if(str.length > num && num === 2){
str = str.slice(0, 2) + '...';
}
```
and this was where the bug first cropped up because the `console.log` would print
```
Abolutely long...
```

**Comment by sinithwar** [comment] 2015-12-09 17:11
The else was
```console.log("Fail Conversion")```

**Closed** 2015-12-09 23:38 UTC
Labels: easy, help wanted

**Comment by HadziJo** [comment] 2016-01-22 05:23
The testing of results claims that my code fails the following (last) two tests:

* truncate("A-", 1) should return "A...".
* truncate("Absolutely Longer", 2) should return "Ab...".

HOWEVER, the requirements state clearly that for values of "num" at 3 or less, NO "..." is to be appended to the truncated string (see requirement 3 below):

(1) Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a "..." ending.

(2) Note that the three dots at the end add to the string length.
     // the above was a little confusing since I first thought it meant to truncate to num characters,
     // then add another 3 characters ("..."); However, the post processing of results assumes one
     // must truncate to num - 3 length, and then add the "..."; 
     // thus maintaining TOTAL length to "num".           

(3) If the num is less than or equal to 3, then the length of the three dots is NOT added to the string length.
