### ISSUE TITLE
Give feedback of why the progressBar isn't filling for signout campers

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#51407] opened 2023-08-28 08:58 UTC
When the user isn't signed and finish a step, they see the image below, but the progress will never increase without feedback why.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/a6620cd1-99fd-4910-be4a-283cd663778c)

I think we should do one of the two:

- Hide the progressbar for unsigned users.
- Add a paragraph of why the progress bar isn't saved for signed out campers

**Comment by Sboonny** [comment] 2023-08-28 14:52
from our discussion:

the button was hard to read for me, so I didn't recognize its content.

a third option is making it bold, but we need to account for where the button is used and how it aligns with the other similar buttons.

**Comment by naomi-lgbt** [comment] 2023-08-28 16:42
Could we not render the progress bar conditionally? Only show it if the user is authenticated?

**Comment by tothricsaj** [comment] 2023-08-28 17:28
Sorry for just jump in but I investigated the code and I found that the progress bar 100% complete in singed in mode despite of just the first lesson is completed. Is it feature or a bug? Or it is only in the local environment?
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/16375198/cd185574-b044-4ff5-a256-6453587e22a9)

**Comment by tothricsaj** [comment] 2023-08-28 17:32
> Could we not render the progress bar conditionally? Only show it if the user is authenticated?

I believe it is feasible but I am new with the code, yet.

**Comment by ahmaxed** [comment] 2023-08-29 09:37
The empty progress bar serves as a reminder that the progress is not being saved. If it is getting misunderstood, I don't mind not showing it at all.

@tothricsaj, that is an issue and a strange case indeed since we have an e2e test for that particular case.
Although it is related to our current discussion, the issue would be better addressed if it was a ticket of its own.

Could you please open an issue and provide as much context as possible so reproduce and look into it?

**Comment by piyushpatil4270** [comment] 2023-09-12 19:55
I think @naomi-lgbt   is right. Can't we just conditionally render the progress bar only if user is authenticated.

**Comment by Sboonny** [comment] 2023-09-19 16:14
> Could we not render the progress bar conditionally? Only show it if the user is authenticated?

if we hide the progress bar, we may need to hide it in the completion modal too, for consistency.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/a98efa56-d195-4eee-a755-5feb18822546)

> If it is getting misunderstood

I didn't misunderstand the progress bar, when my focus moved to the progress bar, I haven't noticed the content on the sign-in button, and when Ahmad pointed me to it, I found it hard to read with how thing the text is.

**Comment by moT01** [comment] 2023-09-19 22:12
I kind of like keeping it visible for unauthed users. It lets them know what they are missing out on. I suppose it stays at 0% complete cause they aren't authed, usually it would show a few percent after completing the first challenge. I would like it to say the 1% or 4% complete or whatever. Not quite sure how to best convey that they need to sign in to save the progress. I feel like it's pretty clear - but could maybe be better.

**Comment by bbsmooth** [comment] 2023-09-19 22:48
From an accessibility standpoint, I think it makes more sense to remove the progress bar if it isn't going to be updated when the user is not logged in. I think there is potential for confusion, especially for screen reader users, since they will automatically hear "0% complete" after every successful submission.

**Comment by moT01** [comment] 2023-09-20 00:21
I wouldn't leave to say zero. I would make it say whatever it would be with one challenge done - but yea, it would repeat 1% complete at the end of each challenge then. I would be fine removing it if that's the consensus, but like I said - I kinda think it might make people more inclined to sign up.

**Comment by VaibhavSharma24** [comment] 2023-09-29 05:41
I agree with @moT01 i think keeping the progress bar shows user that they need to sign in in order to increase their progress bar everytime you see it kinds of reminds us to sign in to save the progress if it will get removed the user will not get the feel of what they are missing.

**Comment by jash-j3** [comment] 2023-10-03 12:56
Is this issue open for PR?

**Comment by ahmaxed** [comment] 2023-10-11 14:26
I would prefer leaving as it. At this point we cannot measure the user behavior and decide on the right variation IMHO.
In the interest of saving the participants' time, I will close this issue for now. 
Please let me know if you think this issue has been closed by mistake.

**Closed** 2023-10-11 14:29 UTC
Labels: scope: UI, platform: learn
