### ISSUE TITLE
Create a form element

### ISSUE THREAD

**Issue by ccastor108** [freeCodeCamp/freeCodeCamp#15113] opened 2017-05-29 13:41 UTC
when I try to do the challenge of "create a form element" the picture of the cell phone turns from my "webpage" to the "page not found" symbol. I have tried to do this challenge on three different days with three different browsers it is definitely an error on the website

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by angler225** [comment] 2017-05-29 14:08
What is your code?

**Comment by OFFLlNE** [comment] 2017-05-29 15:06
@ccastor108 Thank you for reporting the issue, as @angler225 said, could you please provide us with your code so we could give you further instructions or understand the bug better.

**Comment by raisedadead** [comment] 2017-05-29 15:31
Duplicate of #13727, please search for open issues before reporting.

Thanks and happy coding.!

**Closed by raisedadead** 2017-05-29 15:31 UTC

**Comment by maxi114** [comment] 2017-06-21 14:17
<form action = "/submit cat photo" <input type="text" placeholder="cat photo URL"></form>

is this right
