### ISSUE TITLE
Issue @ #57 in HTML/CSS. 

### ISSUE THREAD

**Issue by moxlisp** [FreeCodeCamp/FreeCodeCamp#2893] opened 2015-08-30 23:58 UTC
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-green has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Unless I'm doing something wrong, the following code does not evaluate as correct.  It's the same code as the previous challenge (red background) except for the values.

<style>
  body {
    background-color: green;
    color: #00FF00;
    
  }
</style>

**Comment by iheartkode** [comment] 2015-08-31 00:28
<style>
  body {
    background-color: #00FF00;
  }
</style>
Worked for me.

**Comment by jameskopacz** [comment] 2015-08-31 02:52
@iheartkode It looks like the error messages of the way point is causing confusion.

> [X] Give your body element the background-color of green.
> [X] Use the hex code for the color green instead of the word green. For example body { color: #00FF00; }.

With those errors someone will use the code:
```
body {
    background-color: green;
    color: #00FF00;
}
```
Which fails since all the way point is looking for is ```body { background-color: #00FF00; } ```

**Comment by iheartkode** [comment] 2015-08-31 02:57
Ahh I see.

**Comment by bugron** [comment] 2015-08-31 05:52
@moxlisp thanks for posting this issue!
@jameskopacz I thinks instructions are clear.
This is from waypoint description section.

>Make the **body element's background color green** by giving it the hex code value of **#00FF00**.

And this is from tests section.

>Give your body element the **background-color** of **green**.
>Use the **hex code** for the color green **instead** of the word **green**. For **example** body **{ color: #00FF00; }**.

So as you can see that instruction in description is duplicated in tests section and there is nothing said about **color** of body element itself. It is all about the **background-color** of body element and it says that you should use **#00FF00** instead of **green**.
So the only correct code is  `body { background-color: #00FF00; } `.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by jameskopacz** [comment] 2015-08-31 06:44
This didn't make sense to me. The OP believed their code should have worked since it worked before.

So I looked at the previous challenges and it looks like they set the user up to fail the green one. The following code passes the tests.

http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-white
```
body { background-color: white; color: #FFFFFF; } 
```

http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-red
```
body { background-color: red; color: #FF0000; } 
```

If you don't read the text but just code based on the Pass/Fail hints you could end up writing the above code and passing. So you pass twice then run into what looks like a problem that's exactly the same and wonder why it isn't working.

**Comment by moxlisp** [comment] 2015-09-06 23:23
thanks all for the replies. realize my mistake now. @jameskopacz hit the issue exactly. I was just blindly copy and pasting a strip of code that had been working until I encountered the red challenge aka Guardian of CopyPasting

**Comment by jwjb** [comment] 2015-09-06 23:35
This is what I did to pass all tests.

![screen shot 2015-09-06 at 4 32 56 pm](https://cloud.githubusercontent.com/assets/3523591/9707224/1c46e670-54b5-11e5-9fc4-5106e756431e.png)

**Comment by awesomeaniruddh** [comment] 2015-09-06 23:44
Since your issue has now been resolved, please close it ;)

**Comment by bugron** [comment] 2015-09-07 17:29
Closing this issue as the problem is solved. Thanks all for replies.

**Closed by bugron** 2015-09-07 17:29 UTC

**Comment by AnushreeDhar** [comment] 2018-06-05 11:41
![image](https://user-images.githubusercontent.com/31166006/40973710-db4c5bf6-68e2-11e8-9689-afd35dd9a6e0.png)
<style>
  body {
    color: green;
    
    font-family: monospace;
  }
  h1{
      color:green;
  }
 

</style>
<h1 style="color: green"> Hello World </h1>
