### ISSUE TITLE
.css("color", "") attribute selector questions are not registering the solutions.

### ISSUE THREAD

**Issue by paul-thomas0** [freeCodeCamp/freeCodeCamp#10557] opened 2016-09-09 09:34 UTC
Challenge [target-the-children-of-an-element-using-jquery](https://www.freecodecamp.com/en/challenges/jquery/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

`````` html


<script>
$(document).ready(function() {
   $("#target1").css("color", "red");

});
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
<h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row">
  <div class="col-xs-6">
    <h4>#left-well</h4>
    <div class="well" id="left-well">
      <button class="btn btn-default target" id="target1">#target1</button>
      <button class="btn btn-default target" id="target2">#target2</button>
      <button class="btn btn-default target" id="target3">#target3</button>
    </div>
  </div>
  <div class="col-xs-6">
    <h4>#right-well</h4>
    <div class="well" id="right-well">
      <button class="btn btn-default target" id="target4">#target4</button>
      <button class="btn btn-default target" id="target5">#target5</button>
      <button class="btn btn-default target" id="target6">#target6</button>
    </div>
  </div>
</div>
</div>

    ```

``````

**Comment by sn1p3r46** [comment] 2016-09-09 11:44
**I confirm, same here:**
![issuex](https://cloud.githubusercontent.com/assets/2912521/18385868/62096c4a-7693-11e6-844f-a85d19965772.png)
Challenge [change-the-css-of-an-element-using-jquery](https://www.freecodecamp.com/en/challenges/jquery/change-the-css-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.


```html
    
    
<script>
$(document).ready(function() {
  $("#target1").css("color","red");
});
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
<h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row">
  <div class="col-xs-6">
    <h4>#left-well</h4>
    <div class="well" id="left-well">
      <button class="btn btn-default target" id="target1">#target1</button>
      <button class="btn btn-default target" id="target2">#target2</button>
      <button class="btn btn-default target" id="target3">#target3</button>
    </div>
  </div>
  <div class="col-xs-6">
    <h4>#right-well</h4>
    <div class="well" id="right-well">
      <button class="btn btn-default target" id="target4">#target4</button>
      <button class="btn btn-default target" id="target5">#target5</button>
      <button class="btn btn-default target" id="target6">#target6</button>
    </div>![issuex](https://cloud.githubusercontent.com/assets/2912521/18385868/62096c4a-7693-11e6-844f-a85d19965772.png)
  </div>
</div>
</div>

    ```

**Comment by francois94** [comment] 2016-09-09 12:40
Same problem on firefox, works fine on chrome.

**Comment by sn1p3r46** [comment] 2016-09-09 13:22
Yeah, works on Chromium too.
The problem is on FireFox 

Console out:
`TypeError: window.__console is undefined:`
```
<anonymous>       change-the-css-of-an-element-using-jquery:19705:3
change-the-css-of-an-element-using-jquery:19705
jQuery.Callbacks/fire()
change-the-css-of-an-element-using-jquery:3191
jQuery.Callbacks/self.fireWith()
change-the-css-of-an-element-using-jquery:3321
.ready()
change-the-css-of-an-element-using-jquery:3540
completed()
change-the-css-of-an-element-using-jquery:3556
```
`udefined`

**Comment by dhcodes** [comment] 2016-09-09 15:42
Confirmed. Works in Chrome and Safari. First test does not pass in Firefox.

**Comment by systimotic** [comment] 2016-10-05 08:26
These seem to work for me on Firefox 49.0.1, Windows 10. I'm guessing this may have been resolved? Could you check @dhcodes?

**Comment by dhcodes** [comment] 2016-10-05 15:24
Not working here @systimotic

**Comment by systimotic** [comment] 2016-10-06 20:29
That's really weird. It works perfectly in both the beta and the live version for me. 😕

**Comment by systimotic** [comment] 2017-01-22 19:47
Closing in favour of #10749

**Closed by systimotic** 2017-01-22 19:47 UTC
Labels: confirmed, firefox, help wanted

**Comment by neuswcjr** [comment] 2017-01-24 02:37
Not working on Edge.
