### ISSUE TITLE
Portfolio page: streak value can be displayed incorrectly

### ISSUE THREAD

**Issue by junhaoyap** [FreeCodeCamp/freecodecamp#1309] opened 2015-07-16 02:29 UTC
![screen shot 2015-07-16 at 10 26 13 am](https://cloud.githubusercontent.com/assets/6291947/8714253/701a41f4-2ba5-11e5-8a44-b595cf5c2f6d.png)

As per screenshot above, I did not do any challenge on one of the days but the streak did not get cut off.

**Comment by BerkeleyTrue** [comment] 2015-08-07 15:59
Hello @junhaoyap 

This is a duplicate of #1075 and is current being fixed.

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-07 15:59 UTC
