### ISSUE TITLE
Make a Person - Test Suite Uses User Global Variables

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#50368] opened 2023-05-12 17:08 UTC
### Describe the Issue

A user can fail with correct code because the tests secretly rely upon global variables accessible to the user.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person

### Your code

```js
const Person = function(firstAndLast) {
  // Only change code below this line

  this.getFirstName = function () {
    return firstAndLast.split(" ")[0];
  };


  this.getLastName = function () {
    return firstAndLast.split(" ")[1];
  };

  
  this.setFirstName = function (first) {
    firstAndLast = first + " " + firstAndLast.split(" ")[1];
  };
  

  this.setLastName = function (last) {
    firstAndLast = firstAndLast.split(" ")[0] + " " + last;
  };

  this.setFullName = function (fullName) {
    firstAndLast = fullName;
  };

  // Complete the method below and implement the others similarly
  this.getFullName = function() {
      return firstAndLast;
    };
};
```

This code fails because the user has the correct solution but deleted the instantiation of the `bob` object.

### Expected behavior

Tests should instantiate any data they need.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.md

We should update the seed code to

```js
const Person = function(firstAndLast) {
  this.getFullName = function() {
    return "";
  };

  return firstAndLast;
};

const bob = new Person('Bob Ross');
bob.getFullName();
```

We should then add

---

## --after-user-code--

```js
const _test_bob = new Person('Bob Ross');
```

---

and modify the test suite to use `_test_bob` instead of `bob`.

### System

All

**Comment by EggSaled** [comment] 2023-05-13 06:53
Hello,

Just to clarify, did you want to add `_test_bob` in the user code block? Because I noticed when I attempted to reproduce the bug you encountered that two test cases still passed, despite `bob` not being initialized in the user's code. I checked the lesson's markdown file and found out that those two test cases did have their own `bob` initialized. I was thinking of adding `_test_bob` to all the test cases instead.

For reference, here's the code for one of the test cases that still passed, despite the bug.
```
assert.strictEqual(
  Object.keys((function () {
    let bob = new Person('Bob Ross');
    bob.setFirstName('Haskell');
    bob.setLastName('Curry');
    bob.setFullName('John Smith');
    return bob;
  })()).length,
  6
 );

```

**Comment by jeremylt** [comment] 2023-05-13 12:17
Those tests initiate their own values so they are fine

**Comment by naomi-lgbt** [comment] 2023-05-15 20:17
Opening this up for contribution.

**Comment by anoy007** [comment] 2023-05-16 10:08
Hi @naomi-lgbt 
assign this issue for branch bugfix/50368.
I have resolved it, need to create PR for same

**Comment by jeremylt** [comment] 2023-05-16 14:36
We don't assign issues. The first PR that fully covers the issue will be accepted.

**Comment by anoy007** [comment] 2023-05-16 14:57
Hi @jeremylt 
ok !!
I have raised PR .

thanks for reply.

**Closed** 2023-05-16 18:46 UTC
Labels: type: bug, help wanted, scope: curriculum
