### ISSUE TITLE
Switching among chapters of a course

### ISSUE THREAD

**Issue by velagandulasaiteja** [freeCodeCamp/freeCodeCamp#47316] opened 2022-08-18 05:20 UTC
### Is your feature request related to a problem? Please describe.

When you open this URL - https://www.freecodecamp.org/learn , you see list of available courses. In this screen, you choose a course and proceed to learn further. For example, Iet us consider a scenario where I choose to learn "javascript-algorithms-and-data-structures" course. When I click on "JavaScript Algorithms and Data Structures Certification", it will redirect to this URL - https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/. Here, at this screen you see list of chapters with respect to that course.  Let us assume, we have 10 chapters in that specific course. You started going through each chapter of that course without break and currently you are at 9th chapter. Now if you want to switch to the 2nd chapter, if you click back button screen will redirect to 8th chapter and you have to click back button 6 times to reach 2nd chapter. Alternatively, you have to go to home screen, choose the course and then go to 2nd chapter. In this way, switching among chapters of a course is not proper.

### Describe the solution you'd like

I believe, side navigation bar at left is the best solution. Side navigation bar will have list of chapters with respect to the selected course. When user wants to switch to other chapter in a course, user clicks on side navigation bar, side navigation bar will display all the chapters of that course, user can easily pick the required chapter. 

### Describe alternatives you've considered

When user clicks back button, website should redirect to screen where you find list of chapters.

### Additional context

[allscreens.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/9367855/allscreens.pdf)

**Comment by moT01** [comment] 2022-08-18 13:12
I believe that what you are calling "chapters", we would refer to as "blocks". There are breadcrumbs you can click on each lesson to get back to the main page of a course:
![Screen Shot 2022-08-18 at 8 04 03 AM](https://user-images.githubusercontent.com/20648924/185402709-29e513b6-0ad6-4862-96aa-86f969a985f0.png)

I'm all for improving the UI/UX, but I'm not sure if I like another side menu. Perhaps we could change up those breadcrumbs so that highlighted link is a drop down or something.

**Comment by jeremylt** [comment] 2022-08-18 15:31
I think throwing in yet another menu would increase clutter.

**Comment by ahmadabdolsaheb** [comment] 2022-08-19 15:32
The breadcrumbs currently link to the current block(grid of steps) and superblocks( list of chapter cards) so it provides sufficient navigational options. We can improve the design of it make it more visible.

**Comment by dhairyapatel1506** [comment] 2022-08-21 06:22
While this is definitely a genuine issue (that I myself face), I agree with @moT01 and @jeremylt that a side navigation bar isn't the best solution. The page is already divided into two parts in the lessons, so another side menu would only clutter things up and leave even lesser room for development. I think the drop-down idea suggested by @moT01 is great.

**Comment by velagandulasaiteja** [comment] 2022-08-22 03:02
@moT01 @jeremylt @ahmadabdolsaheb @dhairyapatel1506  Thank you for your inputs. I agree drop down idea will be the good solution.

**Comment by ahmadabdolsaheb** [comment] 2022-08-29 12:22
Breadcrumbs are an established design pattern for nested content.  Adding a dropdown would not shorten the user journey considerably since choosing the right block ( chapter or project ) would be two clicks away. If a dropdown is added, we need to add a dropdown indicators which would further reduce the usable space in the crammed breadcrumbs navigation. 

Since switching between blocks is possible and only two clicks away, I suggest improving the styles of the breadcrumbs if necessary to make it more conventional. 

In my opinion, a dropdown is not needed.

**Comment by dhairyapatel1506** [comment] 2022-08-31 06:06
@ahmadabdolsaheb Dropdown Indicators are never so big that they cause any significant change in space. It just needs to be as big as the text in the breadcrumbs to be perfectly visible. And as for the user journey, yes, both ways do require two clicks but with the dropdown menu the user wouldn't have to go to another page to access the blocks. The main reason for this feature-request is that while studying a specific block/chapter, some users (like myself) tend to forget certain concepts from previous blocks. Opening a new page just to access the blocks, and checking them out one by one to see which block contains the particular concept requires constantly switching between 3 or more tabs. The current block, the course page with all the blocks in that course, and the new page/pages for each block opened to recall the concepts. Adding a dropdown menu will reduce this number of tabs by 1.

An alternative solution can be to add a block name (based on the concept taught in that block) for each block in the course page so that it's easier for the user to recall what block a particular concept is in, saving them a great deal of time.

Or, both these ideas could be combined to create a dropdown menu **with** the block names. This would require increasing the width of the dropdown menu to accommodate the block/chapter names. For this, the block names must be kept as small as possible but at the same time providing the right information. This would save the users a great deal of time of switching between blocks and provide more time for learning.

Example of a dropdown indicator:
![fccBreadcrumbs (1)](https://user-images.githubusercontent.com/101339040/187599007-3a84cc4a-5069-46bd-8350-1aff242e6619.png)

**Comment by ahmadabdolsaheb** [comment] 2022-08-31 09:46
Thank you for your explanation and the context. The issue is that the breadcrumbs is used across the curriculum and consumed by different viewports. So you could run to the following situations:

<img width="1065" alt="Screen Shot 2022-08-31 at 12 30 12 PM" src="https://user-images.githubusercontent.com/4591597/187647672-8af055dc-77d1-44ee-9b66-db6a8c486174.png">
<img width="373" alt="Screen Shot 2022-08-31 at 12 30 32 PM" src="https://user-images.githubusercontent.com/4591597/187647797-32803b0a-e28e-414a-890d-22fcde6e3031.png">

Since the switching between challenges and blocks currently is possible, I am leaning toward leaving the breadcrumbs as it is.

I understand that you would need to go back to review certain concepts. Currently there is no easy way to do that for the new responsive web design other than remembering the number of the challenge or the order of challenges. Out of curiosity,
How often do you need to do that and did you need to do it during the new responsive web design certificate.

If there are enough students experiencing the same inconvenience, we might need to improve our information architecture, introduce notes, subject tags, etc.

**Comment by dhairyapatel1506** [comment] 2022-09-06 13:22
I understand your point now. And to answer your question, I do find myself going back and forth the blocks very often but that may vary for every person and course. For example, I've just started learning web development and I find html and css overwhelming because of all the things you're required to remember (and all of it just to make the site look a certain way!). So a lot of times I don't remember some of these things and need to go back for a quick glance. The problem is that it barely takes me 2-3 seconds to recap what I'd forgotten, but much of my time is wasted in going through all of the blocks trying to find what I'm looking for. The only quick alternative I'm left with is to look up the related concept on google.

**Comment by ahmadabdolsaheb** [comment] 2022-09-12 12:52
I understand that this is somehow unrelated to this issue, but to my understanding the new responsive web design steps are designed to be explanatory. So ideally students should not need to back and forth to complete a project. If you don't mind, could you share with me an instance where you had to go back to review a concept before completing a step.

**Comment by moT01** [comment] 2022-10-05 15:45
Thanks for your interest @ebenezer0311, but no - we are still discussing this issue, and I think we will end up leaving this as it is for now.

Your best bet is to look for an issue with a `help wanted` or `first timers only` label. Those are all open for contribution - although, some may have an open PR to fix the issue so you may want to avoid those. If you find an issue without one of those labels that you want to work on, feel free to tag me and I can help figure out what we want to do with it.

**Comment by ahmadabdolsaheb** [comment] 2022-10-10 14:13
Thank you all for your feedback. The breadcrumb in its current form allows sufficient navigation to related challenges and courses. 

As a result, I am closing this issue. Please let me know if this issue has not been addressed properly.

**Closed by ahmadabdolsaheb** 2022-10-10 14:13 UTC
Labels: status: discussing, type: feature request
