### ISSUE TITLE
It only gives You 2 points on this waypoint the next one gives 1 point

### ISSUE THREAD

**Issue by FabioSeves** [FreeCodeCamp/freecodecamp#1732] opened 2015-08-12 00:57 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment] 2015-08-12 02:16
closing as a duplicate of #1731

**Closed by BerkeleyTrue** 2015-08-12 02:16 UTC
