### ISSUE TITLE
HTML issue

### ISSUE THREAD

**Issue by iamgurki** [freeCodeCamp/freeCodeCamp#38072] opened 2020-01-15 14:44 UTC
Hi my short name is Gurki, I have issue with this challenge cause he can’t letting me go forward, I had watched a lot video on YouTube and get help but I am only who is stuck in this bug?
Could you give a look on the screenshots I have attached? Thanks for your attention
![FDB242D3-53A9-4818-B2E5-7A7F03A76662](https://user-images.githubusercontent.com/59924506/72442717-526d8300-37ad-11ea-9962-1b765e73234f.jpeg)
![5B4A0DAD-5C36-49F0-A3F0-6CE98E27C143](https://user-images.githubusercontent.com/59924506/72442719-53061980-37ad-11ea-807e-8d4efabb0d2d.jpeg)

**Comment by ojeytonwilliams** [comment] 2020-01-15 15:05
Hi Gurki, I'd take a closer look at the first failing test - it gives you a hint about what you need to do.

I'm closing this issue, though, since it's not caused by a bug in the challenge.  If you have any further problems, don't hesitate to ask on the [forums](https://www.freecodecamp.org/forum/c/curriculum-help/509) - they're the best place for this kind of thing.

**Closed by ojeytonwilliams** 2020-01-15 15:05 UTC
