### ISSUE TITLE
Test cases can be tricked!

### ISSUE THREAD

**Issue by ShyamVKansagra** [freeCodeCamp/freeCodeCamp#15123] opened 2017-05-30 10:09 UTC
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
  return str;
}

reverseString("hello");

```
All test cases are visible, so I can just do like this: if test case this(some scenario), return this(expected answer).

e.g. if "Hello" should output "olleH", I can do if(str == "Hello"){return "olleH"; } and hence I can pass all test cases without actually coding anything.

I would suggest hide some test cases and only show result for them whether it has passed or failed.

**Comment by dhcodes** [comment] 2017-05-30 13:42
@ShyamVKansagra Thanks for the issue. This is a duplicate of #8048. Please read the thread there.

**Closed by dhcodes** 2017-05-30 13:42 UTC
Labels: wontfix
