### ISSUE TITLE
"No Result found" Message should be shown on search result page. 

### ISSUE THREAD

**Issue by code123-tech** [freeCodeCamp/freeCodeCamp#43395] opened 2021-09-07 08:29 UTC
The Search Result page should show an appropriate message to the user when no result is found on the search query.

When I made a query "responsiveness".
![query](https://user-images.githubusercontent.com/53444217/132310830-2ad14258-35ae-475c-9877-ebdb3cc76740.JPG)

Search Result page should show a message that "Result is not found", but it is showing as follows:
![noResult](https://user-images.githubusercontent.com/53444217/132311273-e33c0c84-a30c-4978-8a04-d970aa20efb1.JPG)

**Comment by ShaunSHamilton** [comment] 2021-09-07 12:07
Hello there,

Thank you, for taking the time to report this. However, I am unable to reproduce what you have shown:
![image](https://user-images.githubusercontent.com/51722130/132341839-66c23abd-e715-40c2-bfcc-d449b9177421.png)

Pressing `Enter` does nothing, because there are no results. Would you mind sharing the steps to reproduce?

**Comment by code123-tech** [comment] 2021-09-07 12:28
@ShaunSHamilton, Please go to this [link ](https://www.freecodecamp.org/) and then search any query.

**Comment by Sembauke** [comment] 2021-09-07 12:30
This happens when you press enter with `no results found` @ShaunSHamilton

**Comment by ShaunSHamilton** [comment] 2021-09-07 13:38
@code123-tech Thank you, for that.

It appears the behaviour is different for `/` and `/learn`. @ahmadabdolsaheb Which behaviour do we want?

**Comment by Pulkit007** [comment] 2021-09-07 17:50
Hey I am very new to contributing.
Can someone please guide me how should I get started?

**Comment by Sembauke** [comment] 2021-09-08 08:22
Hey @Pulkit007 ,

I would recommend reading how to [ set freecodecamp up locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) and read our contributor guidelines.

Happy coding :smile:

**Comment by gurnoor-garry** [comment] 2021-09-10 11:15
Hey 
Is anyone working on this project or could it be assigned to me?

**Comment by gikf** [comment] 2021-09-10 11:47
Hey @gurnoor-garry 

Issues are typically not assigned to anyone other than long-time contributors. You can read more about this at https://contribute.freecodecamp.org/#/FAQ?id=how-can-i-get-an-issue-assigned-to-me. 

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by ahmadabdolsaheb** [comment] 2021-09-13 06:26
Thanks for opening this issue. We have reduced the size of the JS chunks which we ship to the users on the landing page in an effort to improve our SEO. Therefore, some functionalities including the Algolia  search dropdown have been removed to make the page load faster.

Since this is an expected behaviour, I will be closing this issue accordingly.

**Closed by ahmadabdolsaheb** 2021-09-13 06:26 UTC
Labels: type: bug, help wanted, platform: client, platform: news
