### ISSUE TITLE
Proposal: Brownie Points for Zipline/BaseJump Commits

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#2617] opened 2015-08-24 05:12 UTC
**Problem**
Ziplines and BaseJumps are typically multi-day or even multi-week projects.  Campers who are working on them may still be "coding daily", but unless they are active posting news or on the chat rooms, they are not getting brownie/activity points.  Even the most dedicated camper will break their activity streak if they are diligent on their project.

**Proposal**
Give one brownie point per day for any day with a commit on their current active base jump or zipline.  The GitHub API allows for [commits to be pulled for a repo](https://developer.github.com/v3/repos/commits/).  Site to maintain a list of "active" repos for a user for a given zipline/basejump.

**Pre-Reqs**
There will need to be a method of associating a repo with a given zipline or basejump.  This will constitute a "pull list" that the FCC site will need to maintain.  Some sort of process will need to run hourly/daily to check the pull list against the GitHub API.  An internal list of commit/day pairs for which credit has already been given will need to be maintained.

**Pros**
* Rewards "Good behavior" by encouraging campers to code every day
* Encourages campers to learn/use Git and Github, get practical experience maintaining their projects.
* Keeps a streak alive for campers
* Another datapoint for researchers

**Cons**
* Possible to game the system by doing "crap" commits.
* More emphasis on brownie points, which don't really mean anything.

**Comment by SaintPeter** [comment] 2015-08-24 05:18
More thoughts:  
There is a [rate limit](https://developer.github.com/v3/#rate-limiting) of 5k requests/hour.  If there are more than 5k Campers working on Ziplines/BaseJumps (and who have registered a Repo), this may become an issue in the future and the 'pull list' will need to be batched or queued.

**Comment by AdventureBear** [comment] 2015-08-24 14:04
I like the idea of keeping the FCC streak going with or without brownie points. I've been working almost daily on mine as well and I'm sure my fcc streak has a long break

**Comment by benmcmahon100** [comment] 2015-08-25 01:33
This seems like a good idea but there are the technological limitations mentioned as well a s the massive slowdown that would be caused by the FCC servers requesting a data set for 90k(as of right now)+ campers a more light weight solution would be to add the users longest streak to their brownies which would be updated on login decreasing load

**Comment by SaintPeter** [comment] 2015-08-25 01:38
Just to be clear, we'd only be talking about a single "active" Zipline/Basejump at a time.  As soon as one was finished it would no longer be pulled.  Unless you have all 90k stuck in a basejump, that would  probably not be an issue.  I suspect the majority of those 90k have not gotten past Ziplines, based on the activity I see on the Chatrooms.  

There is no real time critical element to it - you can retroactively awards the brownies.

>  would be to add the users longest streak to their brownies which would be updated on login decreasing load

I'm not sure I understand what you're proposing here.

**Comment by benmcmahon100** [comment] 2015-08-25 12:00
I was proposing that you'd take their longest steak score as add it to the number of brownie points. The issue with the idea are dealing with zipline or basejump commits is that no matter how it's implemented its going to require a massive query on all user data and to only work off of active people it would then need to decide if they should be fall he's as active or not and then precede their commits. A more stable solution would be to only perform this calculation when the project is marked as complete but that may still be a large enough data process operation that it could cause a slowdown with some scale

**Comment by SaintPeter** [comment] 2015-08-25 17:30
Oh, that's interesting - a post- submit process that would "backdate" their Brownie points.

Algorithm:  

1. Zipline/Basejump is submitted with GitHub link
2. Fetch Commit List for date range `Prior Zipline/Basejump Submission Date` to `Present`
3. Process Commit list to day/commit pair object list:   

     ```javascript
      [ { 'date': "8/25/2015", 'commits': 2 },
        { 'date': "8/24/2015", 'commits': 1 },
        { 'date': "8/23/2015", 'commits': 2 } 
         /* . . . */ ]
      ```
4. For each day with one or more commits, add a single brownie point.
5. Recalculate streak.

I am not an expert, but this seems like it would be low impact.  It's single API call per submit.  This becomes an issue only if >5k people submit a Zipline/Basejump WITH GitHub repo.

As a sidenote, this may really only be practical for Basejumps, unless the user is working offline and pushing a single HTML file to GitHub.

---

The question is, practical considerations aside, is this something that we would see as a value for FCC and in keeping with the pedagogical goals of the site?

If so, I'll see if I can mock up some code.  Perhaps if we have a list of repos that prior users have submitted for their Basejumps we could do a test run againt.

**Comment by SaintPeter** [comment] 2015-11-08 21:22
In our copious free time, I'd still like to evaluate this.

I want to determine for a single zipline or basejump submission, how much overhead is there actually?

I continue to get feedback from campers that they want to be able to keep their streaks alive, but it's just not possible doing the Ziplines and Basejumps.

**Comment by BerkeleyTrue** [comment] 2015-11-11 06:35
@SaintPeter At this point campers should be focusing on their Github streak/points. Getting brownie points for commits effectively gives double points to the camper for the same work. There had been discussions early on whether we should sync with Github streaks but we decided against that as those two things represent different sets of work. 

For those campers who want to keep their streak alive they can help campers in the chat room.

**Comment by ArgonCode** [comment] 2015-11-14 06:53
I kinda like the idea that to gain some points while I am working on ziplines I have to check the chat-room and help others. I actually enjoy it, and otherwise would not think of it.

**Comment by ltegman** [comment] 2016-02-21 23:00
Closing this as moving onto Github streaks or helping people in the chatroom for an FCC streak should be the focus at this point.

**Closed by ltegman** 2016-02-21 23:00 UTC
Labels: Discussing
