### ISSUE TITLE
current streak restarted from 1 after 9 days.

### ISSUE THREAD

**Issue by tuxitop** [FreeCodeCamp/freecodecamp#1332] opened 2015-07-18 17:20 UTC
As you can see in the screenshot my current streak should be 10, but it has got back to 1 after 9 days of streak.
Here is my [profile page](http://www.freecodecamp.com/tuxitop).
![2015-07-18-214105_600x218_scrot](https://cloud.githubusercontent.com/assets/994867/8762709/56b35c76-2d96-11e5-9b1f-7a0358d9121d.png)

**Comment by fabricionoda** [comment] 2015-07-18 17:52
Friday 17, does not appear completed exercicies at this moment


Fabrício Noda
44 9184-2940

2015-07-18 14:20 GMT-03:00 Ali Mousavi <notifications@github.com>:

**Comment by tuxitop** [comment] 2015-07-18 18:32
​It looks completed here, as it is in the screenshot. It might be a
timezone problem then if it looks different there, and that would be a bug.

**Comment by BerkeleyTrue** [comment] 2015-08-07 15:58
hello @tuxitop 

This is a duplicate of #1075 and is currently being fixed.

Happy Coding!

**Closed by BerkeleyTrue** 2015-08-07 15:58 UTC
