### ISSUE TITLE
Reports of code editor performance degrading over time

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54736] opened 2024-05-10 19:45 UTC
### Describe the Issue

Opening for visibility.

I have not seen this happen myself, but I also haven't spent much time in the editor.

Link to threads reporting this.

https://forum.freecodecamp.org/t/code-editors-performance-degrades-over-time/685239

### Affected Page

https://www.freecodecamp.org/learn/

### Steps to Reproduce

Unknown, I guess usage over time.

### Expected behavior

Performance not degrading over time.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by zxc-w** [comment] 2024-05-11 04:56
I've experienced this issue multiple times. After the donation pop-up appears, the performance of the website becomes laggy. Even after refreshing the page, it returns to normal temporarily, but the lag returns once the donation pop-up reappears. 



![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/163780208/6eb39cf2-d49d-4a45-9253-e9cbc08df13d)

**Note**: the lag doesn't occur immediately after the pop-up, it becomes noticeable as you continue solving challenges, with delays in typing and overall slowness.

**Comment by ilenia-magoni** [comment] 2024-05-11 11:36
I have not noticed this in the dev environment, even if the pop-up is present there too (python course)

**Comment by juancaorg** [comment] 2024-05-11 13:57
I thought I was crazy or that my machine was "too old" for this, but I have experienced this too.

In my experience, it has happened after working a while on the editor or just doing a little bit of work on the editor, leaving it open, and then coming back. It becomes really slow and the only workaround that I have found is closing my browser completely and opening it again.

**Note:** As a current donor, the pop-up doesn't show up in my account and I don't think is related to that component itself.

**Comment by samhlking** [comment] 2024-05-14 12:54
Commenting to add I experience this every single time I use the editor for more than maybe 20 minutes. It doesn't just happen suddenly. It starts with a slight delay then gets worse and worse.

I just opened up Incognito with no extensions enabled, and I noticed the delay after around 15 minutes. Then by 25 minutes it was definitely worse. It isn't unusable, but if you type relatively quickly it is very noticeable that words on screen are being completed maybe 100ms after you actually type them, then gets a little worse from there.

**Info:**
Chrome/124.0.6367.158 (no extensions)
macOS Ventura
Responsive Web Design Certification (I have had delays throughout this entire course)

**Comment by gikf** [comment] 2024-05-14 20:30
I'm able to get the slowdown both in production and in development.

Reproducing it a bit loosely:
- Go through multiple steps (around 20?).
- At some point writing few characters in a row will start feel delayed/lagged.
- In console start appearing warnings, something like _[Violation] 'input' handler took 1123ms_.

Recorded performance showed then longer times of redux updates coming from (if I didn't mix up anything) the editor's `onChange`:
https://github.com/freeCodeCamp/freeCodeCamp/blob/4270793f1c83b92d42e63cf9e0680f16f8d776db/client/src/templates/Challenges/classic/editor.tsx#L867-L895

**Comment by ojeytonwilliams** [comment] 2024-05-15 08:38
Thanks, @gikf that's really helpful! 

Just so I'm on the same page: how did you record the performance and did you have campfire mode on while you were testing this? Also, did you complete and submit 20 steps or just navigate through them?

**Comment by gikf** [comment] 2024-05-15 08:54
Hey @ojeytonwilliams!

- It was the _Performance_ tab in the browser's developer tools. Not the profiler from react developer tools. Once I noticed the lagging, I turned on recording and did couple more steps. Then tried to make heads or tails out of it :eyes: 
- It doesn't seem to be related to campfire mode. I actually have campfire mode on in production, but when I was checking in development I believe it was off.
- Steps were completed/submitted. I haven't tried just navigating them.

**Comment by ojeytonwilliams** [comment] 2024-05-15 09:17
It's not easy to read, but it does seem to be `onChange` that's taking the time, which makes sense. That's what I see even when the editor is working normally.

I've yet to see the slowdown from 

* having the editor open for a long time
* typing a lot in a single page
* navigating through 80+ challenges

I'll try completing a lot of challenges next and see if I see what you saw, @gikf.

Regardless, it seems like either the amount of typing you need to do to complete a bunch of challenges OR the completion/submission process is the problem. That's my current guess.

**Comment by captain-baha** [comment] 2024-05-16 17:21
I'm seeing the same code editor latency after about 5 to 10 minutes of usage. I see it both in Chrome and Firefox browsers when testing in Windows 11 and Linux Fedora 40. The best solution I have is to do a [force cache reload](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) of the page when it starts happening.  Is the code editor overloading the cache to cause a slow down?

**Comment by hbar1st** [comment] 2024-05-19 16:33
I'm on Windows Chrome browser and the editor is super slow for me. I type and I can't see what I've typed in till seconds later (good thing I'm a good typist) and I click Submit and it takes a long pause to respond. I tried clearing cache but it fixes the issue for maybe a couple of steps max then back to the slow performance. Definitely something I didn't experience back in early 2023 when I last used the curriculum. If there's some data I can collect to help debug, let me know.

**Comment by hbar1st** [comment] 2024-05-21 16:55
The lag happens consistently to me on the ROG (js beta) pages. Everytime I recycle my browser the issue goes away temporarily.

**Comment by samhlking** [comment] 2024-05-21 18:26
> I guess what's left is the challenge pages that you are on when you experience the issue.

As I have [already commented](https://github.com/freeCodeCamp/freeCodeCamp/issues/54736#issuecomment-2110160419), I experienced this throughout the responsive web design cert, but I have since finished that course and moved onto the JavaScript one, and can confirm I am having the exact same issue on there.

The easiest way I've found to get rid of the delay is ```⌘ + Shift + r``` to reload page while ignoring cache.

**Comment by gikf** [comment] 2024-05-21 18:41
It might be needed for user to be logged in.

I've tried to reproduce it on Firefox.
- I've went from last steps of _[Learn HTML by Building a Cat Photo App](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app)_ to about 30 step of the _[Learn Basic CSS by Building a Cafe Menu](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-basic-css-by-building-a-cafe-menu)_ - without being logged in, no issues.
- Then after logging in, I started at the first step of _[Learn Basic CSS by Building a Cafe Menu](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-basic-css-by-building-a-cafe-menu)_, passing code was still in browser, so was just submitting it for the most part. By the 20th step  writing was again slowing down.

**Comment by lasjorg** [comment] 2024-05-22 02:58
I also see it when logged in. It literally became so bad that is spiked the CPU if I held down a key and just let it repeat.

It might somehow be related to the completion modal in the lower jaw, but I'm really not certain. That is at least also different depending on if you are signed in or not.

The problem is, it didn't seem as bad in dev mode for me, so I'm not confident. But I removed the progress component and did twice as many steps, and it didn't happen. But as said, I'm really not sure if I trust it in dev mode.

In the Performance log, looking at the bottom-up tab, `completedPercentageSelector` was the first one.

**Comment by ojeytonwilliams** [comment] 2024-05-22 14:16
Thanks everyone. I've finally reproduced it by doing ~20 responsive web design lessons while signed in.

It does seem like `completedPercentageSelector` is part of the problem, thanks @lasjorg. I'm not sure it's the root of the problem, but it's definitely getting called far too often.

My plan is to create a quick PR to stop the unnecessary calls and/or memoize the function. Hopefully that fixes it, but we'll have to see.

**Comment by lasjorg** [comment] 2024-05-23 01:37
@ojeytonwilliams I was briefly looking at the Progress component and saw ProgressInner

[`client/src/components/Progress/progress-inner.tsx`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Progress/progress-inner.tsx)

Something about that code doesn't sit right with me. The `lastShopwnPercent` and `myInterval` variable names seems a little like something that wasn't fully checked and tested.

If I just log when the component renders, it does so on every keystroke, and even just left-clicking inside the active editor section logs a re-render. This is after you have completed at least one challenge step.

![progress-bar](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/d16a1058-b7d1-4b94-a7a3-9bfdaa648d83)


Might not be related, but it doesn't seem right considering it isn't even shown. I'm a little skeptical of the Intersection observer and useEffect.

---

I know this isn't very constructive, but that's all I've got for now.

**Comment by ojeytonwilliams** [comment] 2024-05-24 11:26
I agree about the naming, it's a little sloppy. And, yes, something is going wrong meaning that it's getting re-rendered after challenge completion.

https://github.com/freeCodeCamp/freeCodeCamp/pull/54925 makes it a lot better, though. It's still rendering when you start a new challenge (and it shouldn't), but it no longer renders in response to, well, everything.

**Comment by lasjorg** [comment] 2024-05-26 16:28
I have unpinned the issue, considering it is closed as completed.

**Comment by newdevontheDL** [comment] 2024-05-27 11:34
Hi Guys i am still experiencing this on two separate machines both running windows 11 and Chrome

Browser extension installed , ublock origin and Ghostery

this is whilst going through the responsive web design curriculum, in both building a balance sheet and the cat painting projects

**Comment by hbar1st** [comment] 2024-06-29 19:52
hi @huyenltnguyen , I've been using the JS beta curriculum all day from a single tab today. I did end up running into the performance issue again but it took a -lot- longer to run into it, and it was not lagging as bad as it used to when I would type (one of the issues I saw was that I would type and it would take a bit of time for the editor to display what I typed). Now when it slows down, the lag is not nearly as long (and as I said, I ran through a lot of steps today before seeing the slow-down). 
This is just to let you know what I have observed as you've asked us to report back. Thanks for the fix(es) already done.

**Comment by ojeytonwilliams** [comment] 2024-06-30 08:29
Thanks for the follow-up, @hbar1st. Some slowdown is expected, since the 'fix' was to make rendering considerably more efficient. This delays and mitigates the slowdown, but clearly something is getting less efficient over time.

Since it's not too bad at the moment and it's hard to pin down the ultimate cause, I think we can leave this for now. We do plan to give the client some love before too long and that will give us another chance to squash the bug.

**Comment by newdevontheDL** [comment] 2024-07-21 07:57
Hi Guys

I am still running in to this issue, im currently working my way through learn-basic-javascript-by-building-a-role-playing-game.

and after about 10 mins the typing of text starts to lag, im having to refresh the page and it seems to make it go away for a while

**Comment by hbar1st** [comment] 2024-08-02 03:09
Other reports of slow performance
https://forum.freecodecamp.org/t/lesson-text-editor-really-slow-after-about-50-steps/704086?u=hbar1st

**Comment by ojeytonwilliams** [comment] 2024-08-02 07:49
Thanks @newdevontheDL, @hbar1st. I'll give this another look.

**Comment by ojeytonwilliams** [comment] 2024-08-02 09:45
https://github.com/freeCodeCamp/freeCodeCamp/pull/55726 should be another decent perf boost. Same deal as last time: while I expect this to be a lot better, there may still be deeper problems.

**Comment by ojeytonwilliams** [comment] 2024-08-06 10:23
Tentatively closing again, since https://github.com/freeCodeCamp/freeCodeCamp/pull/55726 has been merged and should help considerably.

**Closed by ojeytonwilliams** 2024-08-06 10:23 UTC
Labels: type: bug, scope: UI, type: showstopper, platform: learn
