### ISSUE TITLE
Make it clear that every JS statement should should end with ";" to be accepted.

### ISSUE THREAD

**Issue by ThekhoN** [FreeCodeCamp/FreeCodeCamp#3281] opened 2015-09-13 08:54 UTC
For the waypoints and bonfires,,, if it could be mentioned somewhere that we are to STRICTLY close every statement with a ";"..
That would be Great...

"Experienced" coders may know/be aware of the issue that the FCC JS parser will reject if we don't end every statement with ";" but new users who test their code in their browser console often leave out ";" while testing/running codes in the console[to save time? or slow typing]. 
So while the code works fine in their browser console..when they copy pasta their code into the FCC submit, it gets rejected and they waste a lot of time wondering why the hell their code ain't working.

Thanks.

**Comment by awesomeaniruddh** [comment] 2015-09-13 10:19
Thanks for reporting the issue @ThekhoN.

**Comment by ltegman** [comment] 2015-11-11 22:23
Closing this as the linter used in the editor currently flags missing semicolons and tells the user what the issue is.

Thanks and happy coding!

**Closed by ltegman** 2015-11-11 22:23 UTC
Labels: confirmed
