### ISSUE TITLE
Checkpoint: Stand in Line. Giving, RangeError: Maximum call stack size exceeded in Chrome

### ISSUE THREAD

**Issue by ShivamSarawagi** [FreeCodeCamp/FreeCodeCamp#6020] opened 2016-01-10 15:51 UTC
When I added my solution it was this error. Then after some research, I tried in Firefox and it worked.
So basically this is stack issue from chrome so I thought of reporting as other campers might get the same issue.

**Comment by dmytroyarmak** [comment] 2016-01-10 16:13
@ShivamSarawagi 
Can you please send here code of your submitted solution on which you got this error?

**Comment by ShivamSarawagi** [comment] 2016-01-10 16:36
@dmytroyarmak 
Please find the code below:
function queue(arr, item) {
  arr.push(item);
  return arr.shift();  // Change this line
}

**Comment by dmytroyarmak** [comment] 2016-01-10 16:53
@ShivamSarawagi 
Here is I tried your code and everithing works fine on Chrome.
http://www.freecodecamp.com/challenges/checkpoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20arr.push(item)%3B%0A%20%20return%20arr.shift()%3B%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(myArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0A

Can you try too again?

This kind of error is possible if there is recursion in your code, but you don't have it.

**Comment by OriBon** [comment] 2016-01-10 18:44
`Maximum call stack` error is solved by simply refreshing your page.
Your code is stored locally, so you should not lose your progress if you refresh the page.

**Comment by freeranger** [comment] 2016-01-10 22:26
Confirmed OriBon - I had the same issue, refreshed the page, issue gone

**Comment by sludge256** [comment] 2016-01-10 22:40
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5715

**Closed by sludge256** 2016-01-10 22:40 UTC

**Comment by jim3** [comment] 2016-01-18 21:28
I just had the same issue. Reloading the browser fixes it though.

**Comment by noamoss** [comment] 2016-01-20 21:53
+1
