### ISSUE TITLE
Issue with a challenge

### ISSUE THREAD

**Issue by duartenunes86** [freeCodeCamp/freeCodeCamp#49764] opened 2023-03-18 12:03 UTC
### Describe the Issue

On this https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-32
I write the correct answer and the system tells me the answer is not correct and asks Hint
You should give the label the text Input your age (years): . when it's done

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-32

### Your code

```

```

      <fieldset>
        <label>Upload a profile picture: <input type="file" /></label>
        <label>Input your age(years): <input type="number" min="13" max="120" /></label>
      </fieldset>

### Expected behavior

The code should have passed

      

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Chrome Windows at a library

**Comment by raisedadead** [comment] 2023-03-18 14:50
The issue is how the instructions wrap; the space needs to be seen.

```diff
- Input your age(years): 
+ Input your age (years): 
```

We should fix this.

**Comment by bbsmooth** [comment] 2023-03-18 17:14
I see this issue quite a bit. Could we use `white-space: nowrap` on `code` elements in the instructions?

**Comment by Sboonny** [comment] 2023-03-18 17:57
If we are changing CSS, then this is a duplicated issue of this issue #49359, be careful of white-space: nowrap, because it may case overflow with in a lot of steps, maybe other values 🤔.

I am closing this as duplicate, feel free to reopen this, if I am wrong

**Closed by Sboonny** 2023-03-18 17:57 UTC
Labels: type: bug, help wanted, scope: curriculum
