### ISSUE TITLE
Typo in Waypoint: Global Scope and Functions

### ISSUE THREAD

**Issue by storbeck** [FreeCodeCamp/FreeCodeCamp#5563] opened 2015-12-30 18:50 UTC
Challenge [Waypoint: Global Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-global-scope-and-functions#?solution=%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0Avar%20oopsGlobal%3B%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20oopsGlobal%20%3D%205%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The test case has a typo in it:
Do not decalre oopsGlobal using the var keyword

**Comment by ltegman** [comment] 2015-12-30 19:10
Closing as a duplicate of #5559. Thanks and happy coding!

**Comment by abhisekp** [comment] 2015-12-30 19:11
@ltegman hey! it's Global scope not local scope!

**Comment by storbeck** [comment] 2015-12-30 19:17
I don't think this is a duplicate. The referenced issue is for a different waypoint and a different issue. This has a typo in the test case. It says "decalre" but it should be "declare"

**Comment by ltegman** [comment] 2015-12-30 19:18
Whoops, sorry about that!

**Closed** 2015-12-30 19:30 UTC
Labels: confirmed, easy, help wanted, tests

**Comment by abhisekp** [comment] 2015-12-30 19:31
@SaintPeter I had rectified this before why didn't it appear? https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5519/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R1932
