### ISSUE TITLE
No help or bug buttons in my lessons

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1085] opened 2015-06-23 12:37 UTC
I just noticed in #1058 that there are two extra buttons in her screenshot, `Help` & `Bug`.

I've tested it in Chrome, Firefox and IE11 but no buttons for me? 

I'm on Windows 8.1.

![image](https://cloud.githubusercontent.com/assets/1038062/8306066/ccd71eb8-19ac-11e5-89b0-f939a09afd7a.png)

**Comment by ahstro** [comment] 2015-08-11 09:11
Could not reproduce. This is probably very dated by now and up for closing?

**Closed** 2015-08-11 15:55 UTC
