### ISSUE TITLE
Similar function dosen't works as the same way

### ISSUE THREAD

**Issue by Jamlet** [FreeCodeCamp/FreeCodeCamp#11728] opened 2016-11-20 15:23 UTC
#### Slasher Flick

https://www.freecodecamp.com/challenges/slasher-flick#?solution=function%20slasher(arr%2C%20howMany)%20%7B%0A%20%20arr.splice(0%2C%20howMany)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0A%0Afunction%20slasher(arr%2C%20howMany)%20%7B%0A%20%20return%20arr.splice(0%2C%20howMany)%3B%0A%7D%0A%0Aslasher(%5B1%2C%202%2C%203%5D%2C%202)%3B%0A

#### Two similar functions dosen't gives the same result.

Those functions dosen't gives the same result. The second one act like .slice function.

```js
function slasher(arr, howMany) {
  arr.splice(0, howMany);
  return arr;
}

function slasher(arr, howMany) {
  return arr.splice(0, howMany);
}
```

#### Browser Information

* Browser Name, Version: Versión 54.0.2840.99 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

**Comment by systimotic** [comment] 2016-11-20 15:41
Hi @Jamlet! Thanks for reporting this issue.
The behavior you're seeing is expected behavior. This is because `Array.prototype.splice()` alters the array it is called on. The return value are the elements that are deleted, but in this challenge you have to return the modified array.
`Array.prototype.slice()` essentially creates a new array using the values from the original array (between the specified boundaries), and returns that. It leaves the original array unharmed. 

As an example, while the first example is the working one for `.splice()`, the same thing would not work for slice:
```js
function slasher(arr, howMany) {
  arr.slice(howMany);
  return arr;
}
// does not work
```
For slice, the working version is
```js
function slasher(arr, howMany) {
  return arr.slice(howMany);
}
// works
```
which is similar to your second example, which doesn't work for splice.

Bonus fact: functions that don't touch anything that's not inside the functions are called 'pure functions'. `Array.prototype.slice()` is a pure function, where `.splice()` is not.
I have to admit that the similar naming and only slightly (but crucially) different functionality still confuses me from time to time. The MDN links provided are really helpful, as they explain what the function does and tell me the return value. I still consult them regularly. Ironically, I think writing this explanation has helped me to really understand the difference, so I might not have to anymore 😄

For coding help, the "Help" button is the place to be.

I hope this explanation is sufficient. As this works as it should, I'm closing this issue. If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Happy coding!

**Closed by systimotic** 2016-11-20 15:41 UTC
