### ISSUE TITLE
`dataset` is already declared

### ISSUE THREAD

**Issue by yrahul3910** [freeCodeCamp/freeCodeCamp#13936] opened 2017-03-15 14:15 UTC
Challenge [work-with-dynamic-data-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")      
      .text((d) => d + " USD");
      
      // Add your code above this line
  </script>
</body>

```
This would be the right solution, but it says `dataset` is already declared. The issue is resolved by renaming the variable.

**Comment by t3h2mas** [comment] 2017-03-15 14:46
Interesting. Looks like dataset is being declared each time a test is run, but the old const dataset is still around. Leading to the error. Refreshing the page, then running the test, proves the behavior.

In other words it looks like each time a test is ran, dataset declarations keep stacking up.

`const dataset = [...`
> run test
```
const dataset = [...
const dataset = [...
```

etc

**Comment by yrahul3910** [comment] 2017-03-15 14:53
They stack up indeed. On solving further challenges, I had to change the variable name in each challenge to get them to pass.

**Comment by ZZhaoTireless** [comment] 2017-03-15 19:21
Hi, I could try to take this issue.

**Comment by systimotic** [comment] 2017-03-16 20:56
Hi everyone! Looks like this issue is a duplicate of #12762, so I'm closing this in favour of that. Happy coding!

**Closed by systimotic** 2017-03-16 20:56 UTC
Labels: beta, help wanted, tests
