### ISSUE TITLE
The replit.com node/express boilerplate not functioning

### ISSUE THREAD

**Issue by DrinkiPoo** [freeCodeCamp/freeCodeCamp#42824] opened 2021-07-11 09:53 UTC
The replit boilerplate from Basic Node and Express (APIs and Microservices) does not boot up properly on my machine. I have shared this problem on [FCC forum](https://forum.freecodecamp.org/t/replit-node-express-boilerplate-not-working/468656), but we haven't been able to solve it as of yet. Node seems to be looking for an index.js file, but this project does not have an index.js.

I deleted and re-cloned the replit multiple times. This is the latest one and it does not work:
https://replit.com/@321nosrep/boilerplate-express#myApp.js

here is what the console spits out when I hit the run button:
```node
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/boilerplate-express/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/load
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/boilerplate-express/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/boilerplate-express/index.js'
}
 
(To exit, press ^C again or ^D or type .exit)
internal/fs/utils.js:269
    throw err;
    ^

internal/fs/utils.js:269
    throw err;
    ^

internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/boilerplate-express/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/boilerplate-express/index.js'
}
 
(To exit, press ^C again or ^D or type .exit)
internal/fs/utils.js:269
    throw err;
    ^

internal/fs/utils.js:269
    throw err;
    ^

internal/fs/utils.js:269
    throw err;
    ^

internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/boilerplate-express/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/boilerplate-express/index.js'
}
```

This is what it looks like:
![Screenshot_2021-07-11_13-42-32](https://user-images.githubusercontent.com/46773798/125190169-70f5f280-e25b-11eb-871e-aa9a07eef7a6.png)

I have tried running the replit instance on chrome, firefox and brave browsers, I have gotten the same result.

My machine info:
![Screenshot_2021-07-11_15-24-53](https://user-images.githubusercontent.com/46773798/125190342-507a6800-e25c-11eb-93a4-50c959558603.png)

**Comment by alirezaghey** [comment] 2021-07-11 11:33
Hello @DrinkiPoo 
I just forked the [replit boilerplate](https://replit.com/github/freeCodeCamp/boilerplate-express) and solved the [first challenge](https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/meet-the-node-console) without problem.
I happen to have the same Chrome version `91.0.4472.114 ` as you, but my OS is Ubuntu focal. Node and npm versions are `14.17.2` and `6.14.131`, but I don't think they have any impact on this problem. This seems to be more replit related.

Also, consider to add a link to the boilerplate replit to the issue. This may help streamline reproduction of the bug and reduce the risk of misunderstanding.

**Comment by DrinkiPoo** [comment] 2021-07-11 11:48
@alirezaghey 
I just edited the OP to add the replit link. Thanks!

**Comment by ShaunSHamilton** [comment] 2021-07-11 12:40
Hello there,

Thank you, for opening this issue. As discussed in the linked forum topic, this is a bug with the Replit setup which occasionally pops up.

The work around is to:
a) Try re-cloning the GitHub repo (create a new REPL)
b) Not use the GUI _RUN_ button, but the shell to execute the install and start commands:
```sh
npm ci
npm run start
```

As such, I am closing this issue. If you have any more questions or concerns, feel free to reach out on the forum or in [Chat](https://chat.freecodecamp.org/)

**Closed by ShaunSHamilton** 2021-07-11 12:40 UTC
Labels: scope: curriculum, scope: projects-backend, status: waiting triage, type: bug
