### ISSUE TITLE
[beta] D3 - const variables fail tests until browser refresh

### ISSUE THREAD

**Issue by SvetaSR** [freeCodeCamp/freeCodeCamp#16128] opened 2017-11-28 07:45 UTC
#### Data Visualization with D3: Work with Dynamic Data in D3
https://beta.freecodecamp.org/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3

#### Issue Description
When running the test twice, the second time always fail because the const variable (dataset) has already been declared on the first time. The test returns the following error:
`"Identifier 'dataset' has already been declared"`
The issue also occurs when moving from one exercise to the other. The second one will return this error, if the code was processed in the first exercise.

#### Browser Information

* Browser Name, Version: Chrome 62.0.3202.94 (Official Build) (64-bit)
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      // Add your code below this line
      
      .text((d) => d + " USD");
      
      // Add your code above this line
```js



```
#### Screenshot

![11-28-2017 9-43-27 am](https://user-images.githubusercontent.com/11496011/33307824-b21ff226-d420-11e7-8301-462b2333b06d.jpg)

**Comment by raisedadead** [comment] 2017-12-06 17:38
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/16087

**Closed by raisedadead** 2017-12-06 17:38 UTC
Labels: beta
