### ISSUE TITLE
If I tell the program to return 3 as the result, I get an "X" for the condition

### ISSUE THREAD

**Issue by MrNegimaki** [FreeCodeCamp/FreeCodeCamp#2212] opened 2015-08-19 17:09 UTC
Challenge http://freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment] 2015-09-02 16:17
Hey @MrNegimaki thanks for posting this issue!

I can't reproduce this so I will close this issue.  Take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some steps to take in the future before posting a bug

**Closed by benschenker** 2015-09-02 16:17 UTC
