### ISSUE TITLE
Optional Survey for Tests

### ISSUE THREAD

**Issue by Unr34ler** [freeCodeCamp/freeCodeCamp#13699] opened 2017-03-02 20:08 UTC
While doing tests sometimes I felt some test are too easy and others quite hard to solve. For some of them I could imagine, they are better split up into more tests to need better explanation. The goal might be to develop a more *even* learning curve or possibly add better links to external resources.

How about adding a small optional survey after each test like: 

**Was it easy or difficult to solve this test?**
* Too Easy
* Ok
* Too Difficult
 
This way you could determine which exercises may need more explanation or might be *boring*?

**Comment by erictleung** [comment] 2017-03-02 20:20
@Unr34ler thanks for the issue. This is a duplicate of a forgotten issue here https://github.com/freeCodeCamp/freeCodeCamp/issues/5441. 

Here's some words from Quincy about it

> I like still like the idea of just gathering better passive data, rather than asking people. We have a lot of data we're not analyzing, like the number of tries and the amount of time it takes to complete the challenge. I feel like we get a better understanding by looking at these data than pestering campers for subjective reviews.
>
>Once we're making better use of these data, I could definitely see randomly prompting campers with a thumbs up / meh / thumbs down option in toasts after completing challenges.

**Comment by Unr34ler** [comment] 2017-03-02 20:42
I could imagine there might be a way to make it less obvious, like ..

* Show it only if the user used the 'Help' button before
* Show it if the user keeps doing mistakes
* Show it randomly
* Show it below the *Ctrl+Enter* confirmation button with a very light design
* Or only activate it temporarily (eg. one week)

Those are just some quick ideas. Someone might have a better one.

**Closed** 2017-09-02 01:11 UTC
Labels: feature request
