### ISSUE TITLE
 chai JS not loading

### ISSUE THREAD

**Issue by Ankurlvv** [FreeCodeCamp/FreeCodeCamp#3930] opened 2015-10-27 10:13 UTC
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20%20%20%0A%20%20%20%20var%20arr%20%3D%20str.toLowerCase().split(%22%20%22)%3B%0A%20%20%0A%20%20%20%20console.log(arr)%3B%0A%20%20%20%20%0A%20%20%20%20var%20sentence%20%3D%20%22%22%3B%0A%20%20%20%20%0A%20%20%20%20arr.forEach(function(word)%7B%0A%20%20%20%20%20%20%20%20var%20first%20%3D%20word.charAt(0).toUpperCase()%3B%20%0A%20%20%20%20%20%20%20%20var%20rest%20%3D%20word.slice(1)%3B%0A%20%20%20%20%20%20%20var%20res%20%3D%20first%20%2B%20rest%3B%20%0A%20%20%20%20%20%20%20sentence%20%2B%3D%20res%20%2B%20%22%20%22%3B%20%0A%20%20%20%20%20%20%20%20%20console.log(sentence)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%20%20sentence%20%3D%20sentence.trim()%3B%0A%20%20%20%20%0A%20%20return%20sentence%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Everytyme i run test it says" chai is not defined"
The chai is not loading in my browser.

https://cdnjs.cloudflare.com/ajax/libs/chai/2.2.0/chai.min.js Failed to load
resource: net::ERR_INSECURE_RESPONSE
My code:
```javascript
function titleCase(str) {
    
    var arr = str.toLowerCase().split(" ");
  
    console.log(arr);
    
    var sentence = "";
    
    arr.forEach(function(word){
        var first = word.charAt(0).toUpperCase(); 
        var rest = word.slice(1);
       var res = first + rest; 
       sentence += res + " "; 
         console.log(sentence);
    });
    sentence = sentence.trim();
    
  return sentence;
}

titleCase("I'm a little tea pot");

```

**Comment by alayek** [comment] 2015-10-27 10:15
I have tested this code in my browser console (latest chrome in Linux), and it produces correct output.

I also opened the challenge and checked that chai JS was loading for me (might have been cached earlier).

**Comment by iTypeSlow** [comment] 2015-10-27 22:21
Tested code in Chrome on OS worked fine.

**Comment by ltegman** [comment] 2015-10-27 23:36
@Ankurlvv Have you tried refreshing the page or clearing the browser cache and refreshing? It's odd if this would be a continued problem for you after trying those two things since that library would have been used on many lessons before this one as well.

**Comment by BerkeleyTrue** [comment] 2015-10-27 23:43
>  net::ERR_INSECURE_RESPONSE

Sounds like it may be a firewall issue.

**Comment by Ankurlvv** [comment] 2015-10-29 12:38
@iTypeSlow  thanks for testing, @alayek  had also tested it , it works fine.

**Comment by Ankurlvv** [comment] 2015-10-29 12:38
@ltegman  I have done that still no progress

**Comment by Ankurlvv** [comment] 2015-10-29 12:39
@BerkeleyTrue  If this is firewall issue??

how we gonna correct it??

**Comment by BerkeleyTrue** [comment] 2015-10-29 14:53
@Ankurlvv You will have investigate in that case. We have no control of your firewall.

**Comment by bugron** [comment] 2015-10-30 18:53
Make sure that you're not behind any proxy server. Also this may be caused by ad-blocking, anonymization and other browser plugins which use proxies. Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Closed by bugron** 2015-10-30 18:53 UTC
