### ISSUE TITLE
Waypoint: clone an element using jQuery (appendTo)

### ISSUE THREAD

**Issue by chiffa** [FreeCodeCamp/FreeCodeCamp#4958] opened 2015-12-03 01:24 UTC
A bug seems to be present: Chrome 46.0.2490.86 m; Windows 8.1 with respect to `appendTo()` function.

`$("#target2").appendTo($("#right-well"));` does work, but not the `$("#target2").appendTo("#right-well");`, the latter being suggested in the tutorial. 

Hard reload and cache clearing did not seem to solve the problem.

**Comment by dcnr** [comment] 2015-12-03 02:54
I was about to open an issue similar to this. I think it's a typo on the example code used because according to the [jQuery API Doc on .appendTo()](https://api.jquery.com/appendTo/) it really should be:

```javascript
$( "h2" ).appendTo( $( ".container" ) );
```

The problem is that on the subsequent Waypoints, the erroneous code ```.appendTo("#right-well")``` is already used instead of ```.appendTo($("#right-well"))```.

**Comment by cspalding** [comment] 2015-12-03 04:05
Should be merged with #4965

**Comment by OldGitHubber** [comment] 2015-12-03 04:30
Thanks Chiffa.  Just spent an hour faffing around with this.

It is also a problem in its use in clone on the following challenge.  Now I can move one ...

**Comment by SaintPeter** [comment] 2015-12-03 04:54
Confirmed in Chrome
[Waypoint: Use appendTo to Move Elements with jQuery](http://www.freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target1%22).prop(%22disabled%22%2C%20true)%3B%0A%20%20%20%20%24(%22%23target4%22).remove()%3B%0A%20%20%20%20%24(%22%23target2%22).appendTo(%22%23right-well%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A)

@BerkeleyTrue - I can't figure this one out.  Maybe an issue with the course-ware, because this used to work.

I do get this JS error:
`Uncaught SyntaxError: Unexpected token }` from `(program):8`
But I can't figure out where that's at.

**Comment by BerkeleyTrue** [comment] 2015-12-03 06:16
In an attempt to reduce the need to constantly load jQuery into an iframe, I'm using a trick to allow the iframe to use the jQuery used on the main page. 

On page load jQuery sets its context to the main document object. In order to enable the same jQuery to work in the iframe document object I have to create a proxy to it that redefines its internal context to that of the iframe document object.

It looked like everything was hunky dory. What is happening is the appendTo('#target4') is internally using the none-proxied version of jQuery, which is tied to the main document object. That is why nothing happens here and why it does work if you use a selector (`$("#target2").appendTo($("#right-well"))` vs `$("#target2").appendTo("#right-well")`).

There are two options here. 

1. Change the challenge to only teach the selector version.
2. Switch to loading jQuery on every iFrame refresh

There are downsides to both

1) the appendTo method may not be the only method that will be effected in the same way
2) I can do this so it will only need to load jQuery once, I'll cash it and write it to the iframe, but there is an additional load that needs to happen.

**Comment by SaintPeter** [comment] 2015-12-03 07:57
I know that at least one camper was talking about expanding the jQuery curriculum - and rightly so, since we only cover a small portion - so having a fully functional jQuery seems like the way to go.  If you're fetching from the same source won't you just get a 304 with no real overhead?  Aside from memory usage, but no network usage.

**Comment by BerkeleyTrue** [comment] 2015-12-03 20:12
@SaintPeter You are correct. I'll have a PR ready in a sec.

**Comment by MariaTaborda** [comment] 2015-12-03 20:53
I did what @dcnr suggested and it worked!! have been dealing with this for an hour.
Thanks @dcnr

**Closed** 2015-12-03 22:32 UTC
Labels: QA

**Comment by PwnArt1st** [comment] 2016-06-21 02:40
issue not resolved, the appendTo requires what @dcnr suggested, however the tutorial still states otherwise.
