### ISSUE TITLE
[Beta] Learn How the CSS @keyframes and animation Properties Work

### ISSUE THREAD

**Issue by ninocka** [freeCodeCamp/freeCodeCamp#13773] opened 2017-03-06 12:09 UTC
Challenge [learn-how-the-css-keyframes-and-animation-properties-work](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-how-the-css-keyframes-and-animation-properties-work) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

---result of animation doesn't work (animation name&duration) @keyframes are ok;

```html


<style>
  
  div{
    height:40px;
    width: 70%;
    background:black;
    margin: 50 auto;
    border-radius: 5px;
  }

#rect {
  animation-name:rainbow;
  animation-duration:4s;
}


@keyframes rainbow {
  0% {
    background-color: blue;
   
    
  }
  50% {
    background-color: green;
   
  }
  100% {
    background-color: yellow;
  
    
  }
}
  
</style>
<div id="rect"></div>

```

**Comment by systimotic** [comment] 2017-03-07 09:53
Hi @ninocka! Thank you for reporting this issue.

This seems to work fine for me. Can you elaborate on what is wrong?

**Comment by cdrainxv** [comment] 2017-03-07 15:54
I tested it on firefox and the first two tests fail as they are jquery based. The rest will pass as they are regex based.

**Comment by systimotic** [comment] 2017-03-09 22:14
@cdrainxv Ah, of course, good catch! 
Closing as a duplicate of #10749 
If we misunderstood this issue, please clarify and reopen 🙂 
Happy coding!

**Closed by systimotic** 2017-03-09 22:14 UTC
Labels: beta, blocked

**Comment by AnThill71** [comment] 2017-06-22 21:10
My keyframe has the right animation name. but it keeps sending back an error saying that it doesn't have the correct name. and it won't give me my credit for the lesson. I'm using Chrome to access FCC
