### ISSUE TITLE
"Check for Palindromes" Bonfire

### ISSUE THREAD

**Issue by sleepynobowling** [FreeCodeCamp/FreeCodeCamp#3686] opened 2015-10-10 02:54 UTC
This challenge gave me a pass even though I had not yet filtered out the punctuation. The final test condition had failed, but I still got credit for completing the challenge. 

Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%0A%20var%20temp1%20%3D%20str.split(%22%22).reverse().join(%22%22).split(%22.%22).join(%22%22)%3B%0A%20var%20temp2%20%3D%20str.split(%22.%22).join(%22%22)%3B%0A%0A%20%20if%20(temp1.toLowerCase().replace(%2F%5B%5Cs%2C%5D%2Fg%2C%27%27)%20%3D%3D%3D%20%0A%20%20%20%20%20%20temp2.toLowerCase().replace(%2F%5B%5Cs%2C%5D%2Fg%2C%27%27))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%7D%0A%20%20else%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%7D%0A%0A%0A%0Apalindrome(%22A%20man%2C%20a%20plan%2C%20a%20canal.%20Panama%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  // Good luck!
  
 var temp1 = str.split("").reverse().join("").split(".").join("");
 var temp2 = str.split(".").join("");

  if (temp1.toLowerCase().replace(/[\s,]/g,'') === 
      temp2.toLowerCase().replace(/[\s,]/g,''))
    {
      return true;
    }
  else
    {
      return false;
      
    }
}



palindrome("A man, a plan, a canal. Panama");

```

**Comment by bugron** [comment] 2015-10-10 05:56
@sleepynobowling thanks for posting this issue!
I am not able to reproduce this issue neither in Chrome nor in Firefox even when clicking "Run tests" button multiple times.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by abhisekp** [comment] 2015-10-11 16:18
@sleepynobowling Just a question might be unrelated to the issue.
Do you think your computer runs slowly or freezes sometimes?

**Comment by sleepynobowling** [comment] 2015-10-12 03:44
@abhisekp No, my computer runs fine.

**Comment by sleepynobowling** [comment] 2015-10-12 03:50
@abhisekp Actually, when I go back to it, it doesn't give me the pass anymore. It definitely did the first time, though. The incorrect solution is still saved and displayed on my FCC portfolio.

**Comment by abhisekp** [comment] 2015-10-12 06:59
@sleepynobowling certainly it did. I checked your profile. It might be a timing issue or something related to async. Can't say anything about it. Just a wild guess.
This is a BUG indeed but UNCONFIRMED.

Let this issue be OPEN till time immemorial for someone else might get into such a bug in future.

**Comment by ltegman** [comment] 2015-11-11 22:10
Closing this as an isolated incident. Anyone is free to reopen this if they encounter it again.

Thanks and happy coding!

**Closed by ltegman** 2015-11-11 22:10 UTC
