### ISSUE TITLE
Run Test - Hangs after clicking link in the iphone Preview

### ISSUE THREAD

**Issue by tanveer12332** [freeCodeCamp/freeCodeCamp#8185] opened 2016-04-19 07:01 UTC
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
<a href="http://freecatphotoapp.com">cat photos</a>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

---

Edit by @raisedadead :
#### Issue Description:

Clicking on the link in the iphone preview area hangs the run test

**Comment by theflametrooper** [comment] 2016-04-19 07:11
Your anchor tag has the href attribute of `http://freecodecamp.com` instead of `http://freecodecamp.com`. This only the case in the challenge link at the top.Your code snippet runs fine.

**Comment by raisedadead** [comment] 2016-04-19 07:14
@theflametrooper Did you mean : 
> `http://freecatphotoapp.com` instead of `http://freecodecamp.com` 

@tanveer12332 
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by tanveer12332** [comment] 2016-04-19 07:18
no i click on href and run button is not working and state is hang so that is i think issue user is waiting to change next step but is not working i click rest but url link is broken becouse is click href .my english is not good.i think you understand

**Comment by raisedadead** [comment] 2016-04-19 07:25
No problems. And Yes I got what you are saying. I'll update the issue description as well.
Thanks @tanveer12332.

**Comment by tanveer12332** [comment] 2016-04-19 07:27
welcome

**Comment by raisedadead** [comment] 2016-04-19 07:28
@tanveer12332 Dont close this :wink:

**Comment by tanveer12332** [comment] 2016-04-19 07:48
ok

**Comment by BKinahan** [comment] 2016-04-19 09:06
After a little testing, the bug is not dependent on which URL is used, and does not occur if the link is opened in a new tab / window with a right-click context menu or using `target="_blank"`.

Is this challenge too early to require another attribute like that, or would asking the user to include the target resolve the issue?

**Comment by raisedadead** [comment] 2016-04-19 10:28
@BKinahan Thanks for investigating this. I actually like the idea of adding a script to the links that are rendered within the preview.

**Comment by CosineroLian** [comment] 2016-04-19 11:01
Hi guys, could anybody help ,me with this issue. I've done all the instruction, but seems i can't move to the next level  
![error](https://cloud.githubusercontent.com/assets/18549617/14636954/94ee49a4-0682-11e6-997b-a316374450f3.png)

**Comment by raisedadead** [comment] 2016-04-19 11:16
@CosineroLian GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by BKinahan** [comment] 2016-04-19 11:22
@raisedadead Adding the line `<script>document.querySelector("a").setAttribute("target", "_blank");</script>` at the bottom of the editor would work for this challenge, but other challenges using the preview will have the same issue if a user tries including a link other than the dead link `#` usually used.

I'm wondering if the script can be added to the preview itself somehow so it'll apply to each challenge using it, but I'm not sure which file(s) to look at for that.

**Comment by raisedadead** [comment] 2016-04-19 12:13
@BKinahan Check this:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/update-preview.js#L117

Not 100% Sure though.

**Comment by tanveer12332** [comment] 2016-04-19 13:25
CosineroLian
first you remove red-text class in h2 and add some style in ur style tag p{color:red;}

**Comment by breakpoint1025** [comment] 2016-06-21 03:24
I also met this issue.
After I clicked the link on the right iphone Preview window, Run Test - Hangs until hard refresh the page.

**Comment by systimotic** [comment] 2016-10-30 09:58
I just tested this on production and staging. I can't reproduce this on either. I assume this has been fixed. @raisedadead Can you confirm?

**Comment by raisedadead** [comment] 2016-10-30 10:47
@systimotic nope its still there.

Here are the precise steps that I did:

1. Load the challenge, use the solution in the description above. Hit Run tests. They Pass.

2. Load the challenge again, use the solution in the description above, click the link `cat photos` in the iPhone preview. Hit Run tests. They hang.

Let me know if its not the same for you, and BTW welcome to the team, I never got a chance to welcome you earlier, apologies. 😃 !

**Comment by systimotic** [comment] 2016-10-30 11:19
Thanks for the welcome, and the check!
I think we have found ourselves a very interesting situation here. I can reproduce this in Chrome, but not in Firefox. This might be one of the first times it's that way around! 😅 
Both browsers complain about the CSP, but that doesn't seem to be the issue. Fun fact: if you change the link to use `https`, it actually tries to load the page inside the phone because the CSP allows it as the frame source. It doesn't actually load though, because https isn't enabled on freecatphotoapp.com.  
![chrome errors](https://cloud.githubusercontent.com/assets/7262039/19836229/f41afabc-9e99-11e6-8c8b-32bd9b8fc12e.png)
These are the errors Chrome logs when I click the button after clicking the link. It seems like even though it doesn't actually change the iframe, it does mess something up. I can get Firefox to break in a similar way if I change to https, where it browses away from the normal source.
We should definitely look into some sort of link interception. Opening links in a new tab (as @BKinahan suggested) could definitely work.

**Comment by raisedadead** [comment] 2016-10-30 18:33
Yeah, either that, or simply making any links in the iPhone preview as dead is also fine I think.

**Closed** 2017-09-02 01:03 UTC
Labels: help wanted
