### ISSUE TITLE
Challenge not loading in the viewer on load; same issues with several other challenges.

### ISSUE THREAD

**Issue by marxcom** [freeCodeCamp/freeCodeCamp#14625] opened 2017-04-28 03:47 UTC
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  h4 {
    text-align: center;
  }
  p {
    
  }
  .links {
    margin-right: 20px;
    
  }
  .fullCard {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by raisedadead** [comment] 2017-04-28 18:00
Please provide some screenshots, and possibly the console logs (should be in the developer tools) for your browser.

**Comment by yergi** [comment] 2017-05-04 13:00
@raisedadead - I don't think I can replicate now that I've completed the challenges, as when I go back to a completed challenge it finds my response and loads that instead. However, I believe I know the issue @marxcom is referring to.

On many challenges, after I complete them and move on to the next challenge, the preview pane on the far right does not autoload the code for the new challenge. I have to submit the starting code (purposefully failing the challenge) for it to run and appear in the preview pane on the right. I had this occur on many challenges in the Basic CSS section as well as the Applied Accessibility section. Does that help?

**Comment by raisedadead** [comment] 2017-05-09 15:25
Thanks @yergi 
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12923

@marxcom please check for open issues before reporting.

**Closed by raisedadead** 2017-05-09 15:25 UTC
Labels: beta
