### ISSUE TITLE
Wrong number of keys

### ISSUE THREAD

**Issue by akgold** [FreeCodeCamp/freecodecamp#1214] opened 2015-07-06 20:48 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-make-a-person has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I believe this test should check if there are 7 keys (an object to hold the name + 6 getter and setter functions), rather than 6.
![image](https://cloud.githubusercontent.com/assets/394930/8532814/e26753fe-23fe-11e5-94c0-650ecc3aae84.png)

**Comment by benmcmahon100** [comment] 2015-07-06 22:10
This is not a bug. Please confer with people in https://gitter.im/FreeCodeCamp/FreeCodeCamp or https://gitter.im/FreeCodeCamp/help before posting a report of this nature. The three getters and three setters should be the constructor function should be the only outside accessible part of a new user object. All other variables should only be locally scope to the constructor function. (they don't have a this in front of them) If you need any further detail/explanations, please do not hesitate to ask to ask! Otherwise please close this issue as we are trying ti control the number at least a bit! :blush:

**Closed** 2015-07-07 17:41 UTC
