### ISSUE TITLE
the challenge is not passing even though the problem solve conditions are met

### ISSUE THREAD

**Issue by LuckyOreo** [FreeCodeCamp/FreeCodeCamp#2796] opened 2015-08-28 04:00 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the problem solve conditions are met as the results are: 
expect(where([10, 20, 30, 40, 50], 35)).to.equal(3);expected '3' to equal 3
expect(where([10, 20, 30, 40, 50], 30)).to.equal(2);expected '2' to equal 2
but it is not passing the challenge. 
now if i set by code to "return (Number(i));" , then it will pass, but should this be a fail condition?

![fccwheredoibelongbug](https://cloud.githubusercontent.com/assets/13142234/9538827/bf146e14-4d16-11e5-825b-80f6c94cf2aa.jpg)

**Comment by dokkillo** [comment] 2015-08-28 08:07
Hi @LuckyOreo 
I dont know the exact reason, but the problem is the assert is waiting for an number and you are returing and string, I resolved your problem using this:  return (parseInt(i)); assert will work.

But anyway, you are doing bad this bonfire, you must use Array.sort, really, if you use it, you will do this exercise in 3 lines, no loops, no foreach etc :)

Regards

**Comment by LuckyOreo** [comment] 2015-08-28 08:32
Hi @dokkillo, 
I know that the issue is with the return value being a character instead of an integer. But My question is should the comparison be using strict equality operator since JavaScript can handle comparison of different types.

**Comment by benschenker** [comment] 2015-09-08 05:18
Hey @LuckyOreo, sorry for the delay.

I think it makes sense to require an integer here as it is best not to rely on type coercion (it can lead to some pretty nasty bugs, and most linters will complain if you use `==`).

Looks like you solved your problem though! Closing this issue, feel free to reopen if you don't feel it is resolved.

**Closed by benschenker** 2015-09-08 05:18 UTC
