### ISSUE TITLE
Broken link -- Waypoint: Get Started with Angular.js

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/freecodecamp#1589] opened 2015-08-06 02:57 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-save-your-code-revisions-forever-with-git has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

From the Map page, clicking "Waypoint: Get Started with Angular.js" redirects me to the last challenge page I was on (in this case the Git waypoint), and it has this error message at the top:

"404: We couldn't find a challenge with the name `waypoint-get-started-with-angularjs` Please double check the name."

**Comment by wildlifehexagon** [comment] 2015-08-06 03:22
Actually, just noticed that none of the Angular.js waypoint links are working on the Map.

**Comment by zorfa** [comment] 2015-08-09 07:44
I too get the same error message:
"404: We couldn't find a challenge with the name `waypoint-get-started-with-angularjs` Please double check the name."

**Comment by ahstro** [comment] 2015-08-09 11:40
This is caused by the same bug that is being discussed in #1439; please close this and keep relevant discussion in there.

**Closed** 2015-08-09 16:31 UTC
