### ISSUE TITLE
Problem in nest-an-anchor-element-within-a-paragraph

### ISSUE THREAD

**Issue by azeemkhanreal** [FreeCodeCamp/FreeCodeCamp#8354] opened 2016-04-29 19:51 UTC
#### Challenge Name
nest-an-anchor-element-within-a-paragraph

#### Issue Description
Challenge complete but after click run test show problem that ""Your p element should have the text "View more " (with a space after it)."""

#### Browser Information
Google Chrome
Version 50.0.2661.94 m 
* Operating System: Windows 8
Desktop

#### Your Code
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
```

#### Screenshot
![screenshot 26](https://cloud.githubusercontent.com/assets/18741861/14927815/cbb752cc-0e71-11e6-82b6-0f354cf5f57d.png)

**Comment by theflametrooper** [comment] 2016-04-29 19:58
You have a duplicate of `<a href="http://www.freecatphotoapp.com">cat photos</a>` in your code. 
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help in future. Happy Coding!

**Closed by theflametrooper** 2016-04-29 19:58 UTC
