### ISSUE TITLE
[beta] const breaks following challenges

### ISSUE THREAD

**Issue by Renestl** [freeCodeCamp/freeCodeCamp#12680] opened 2017-01-21 09:26 UTC
Challenge [work-with-dynamic-data-in-d3](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The test case will not pass with the information below. However this same code does work in the next challenge "Add Inline Styling to Elements".

```html
    
    
<body>
<script>
  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
  
  d3.select("body").selectAll("h2")
    .data(dataset)
    .enter()
    .append("h2")
    .text((d) => (d + " USD"));

    
    // Add your code above this line
</script>
</body>

    ```

**Comment by OFFLlNE** [comment] 2017-01-21 09:39
@Renestl thank you for reporting the issue.
This exact code did let me pass on the tests (same Chrome version).

Here are a couple suggestions:

1. Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2. Try the challenge in incognito mode. A plugin might be interfering with the tests.
3. Try the challenge in a different browser.(if you have not already tried all ;)) 
Please try these things in order and let us know what did and didn't work. I can't reproduce your issue right now, so any extra information will be helpful in finding out what's causing your issue.

**Comment by Renestl** [comment] 2017-01-21 10:07
@OFFLlNE Thank you for your quick response. I was on my way back to state that it was not just that challenge. I did figure out that if I reloaded the page a few time after hitting submit, it would finally accept the answer. But I have to reload the 3 challenges after that one as well a few times to get it to work.
Same with incognito mode. I had to reload the page a couple of times before the answer was accepted.

I'm not sure what the issue is. I tried on my laptop which has the same version of Chrome and it worked the first time. However, I haven't been able to get the page to come up all the way in Firefox on either computer.

On Firefox, the editor refuses to load:
![screenshot_1](https://cloud.githubusercontent.com/assets/13346359/22173612/6fdc68e0-df8e-11e6-9bd5-c87272ce4d7f.png)

**Comment by OFFLlNE** [comment] 2017-01-21 10:26
@Renestl Thank you for all that information.
Someone who is more experienced with that kind of stuff might take a look sometime soon hopefully :)

**Comment by leonfeng** [comment] 2017-01-21 15:56
I have the same issue. Tried 3 different solutions and had to reload the page each time to pass the tests. Error message in console says:

> Uncaught SyntaxError: Identifier 'dataset' has already been declared
>     at <anonymous>:1:1
>     at c (bundle-0f6b2db….js:29)
>     at bundle-0f6b2db….js:29
>     at bundle-0f6b2db….js:1
>     at r.next (bundle-0f6b2db….js:4)
>     at r.Ye.internals.AbstractObserver.t.onNext (bundle-0f6b2db….js:2)
>     at r.<anonymous> (bundle-0f6b2db….js:1)
>     at t.n.next (bundle-0f6b2db….js:6)
>     at t.Ye.internals.AbstractObserver.t.onNext (bundle-0f6b2db….js:2)
>     at r.next (bundle-0f6b2db….js:4)

**Comment by petercollingridge** [comment] 2017-01-21 16:27
I also had a problem with this exercise, with it throwing an error:
Uncaught SyntaxError: Identifier 'dataset' has already been declared

When I removed the line `const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];` from the exercise it worked. I don't if the variable `dataset` is somehow being carried over from an earlier exercise.

**Comment by dhcodes** [comment] 2017-01-21 20:53
I think @petercollingridge has found the cause of the issue.

**Comment by petercollingridge** [comment] 2017-01-21 21:27
In a later exercise, [Display Shapes with SVG](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/display-shapes-with-svg), I also have to remove `const w`, `const h`, and `const svg` which were all defined in a previous exercise. I guess the problem could be avoided by replacing `const` with `var`, but maybe there is a way to avoid carrying the variables over, which would be a better solution.

**Comment by qualitymanifest** [comment] 2017-01-22 22:42
Came here to post this same error. Code works the first time it's submitted, then breaks if you try to submit it again or if you go to another challenge that has a `const` with the same name. If, after it breaks, you remove the `const` entirely, code works again. Refreshing can also fix it.

**Comment by systimotic** [comment] 2017-01-23 07:44
Looks like Quincy opened another issue and assigned Berkeley to it (#12762), so I'll close this in favour of that.

**Closed by systimotic** 2017-01-23 07:44 UTC
Labels: beta
