### ISSUE TITLE
NIGHT MODE won't work

### ISSUE THREAD

**Issue by anshuldawar** [FreeCodeCamp/FreeCodeCamp#9376] opened 2016-06-25 17:20 UTC
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").addClass("animated bounce");
    $("h3").html("<em>jQuery Playground</em>");
    });
  
    $(document).ready(function() {
      $("#target4").html("<>#target4</em>");
    });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by Bouncey** [comment] 2016-06-25 20:46
@anshuldawar there is an issue with your code. Please use the `Help` button under the `Run Tests` button. for help with it.
![screenshot from 2016-06-25 21-41-04](https://cloud.githubusercontent.com/assets/18572518/16359023/e5d3bf78-3b1d-11e6-8997-9b33ff9992d2.png)

If you have an issue with Night Mode, or you have noticed a bug with FreeCodeCamp, please click the `Bug` button and follow the guidelines. This will help us reproduce and diagnose the issue.

Many Thanks

**Comment by raisedadead** [comment] 2016-06-26 17:14
@anshuldawar Night mode works when you are logged in, please submit screen shots of the page, you can activate the same by using the shortcuts (G+T+N) or on your settings page as well.

**Comment by 4mifix** [comment] 2016-06-26 17:30
I have had this issue but have not had the time to address it, here is a screenshot of my issue. 

<img width="1280" alt="screen shot 2016-06-26 at 1 27 30 pm" src="https://cloud.githubusercontent.com/assets/6476249/16363742/25ee5094-3ba2-11e6-8e82-5046a256f6db.png">

**Comment by raisedadead** [comment] 2016-06-26 20:46
@4mifix this is a duplicate of #9196 we are aware of this and this happens only on chrome, while we are trying a fix, as a work around for now, you could use alternate browsers.

Thanks.

**Comment by raisedadead** [comment] 2016-06-29 06:05
@anshuldawar is this the same issue as in the comment above by @4mifix ?

**Comment by anshuldawar** [comment] 2016-06-30 18:20
@raisedadead 
![2016-06-30 1](https://cloud.githubusercontent.com/assets/10780826/16499275/468b4ff4-3f1d-11e6-8da2-0f18785e2e80.png)

![2016-06-30](https://cloud.githubusercontent.com/assets/10780826/16499293/508d7900-3f1d-11e6-828a-daf0eeff8fd4.png)

**Comment by raisedadead** [comment] 2016-06-30 18:57
@anshuldawar yes indeed this is a duplicate of #9196 
We are aware and working on this, as an alternative please use Firefox.

Closing as duplicate. Feel free to follow the original issue.

**Closed by raisedadead** 2016-06-30 18:57 UTC
Labels: blocked
