### ISSUE TITLE
Challenge says "keep trying", but code is correct

### ISSUE THREAD

**Issue by JasonShaneWatson** [freeCodeCamp/freeCodeCamp#14776] opened 2017-05-08 19:02 UTC
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  h4 {
    text-align: center;
  }
  p {
    text-align: justify;
  }
  .links {
    margin-right: 20px;
    
  }
  .fullCard {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by ivancsicsmarkus** [comment] 2017-05-08 21:55
Your code worked for me with a reload.

**Comment by raisedadead** [comment] 2017-05-09 15:37
I could not reproduce.

**Comment by lynxlynxlynx** [comment] 2017-08-05 16:09
Looks like these type of issues are being handled in #15024 and others, so consider closing.

**Comment by systimotic** [comment] 2017-09-04 12:57
Hi! Thanks for reporting and looking into this issue.

This was recently fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/15775, so I'm closing this as resolved.

Happy coding!

**Closed by systimotic** 2017-09-04 12:57 UTC
Labels: beta
