### ISSUE TITLE
Error Checking If h2 Is Blue

### ISSUE THREAD

**Issue by aglome** [freeCodeCamp/freeCodeCamp#15280] opened 2017-06-09 14:53 UTC
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

console output:
message: Your h2 element should be blue."

However, all h2 elements are renderd blue thanks to the style's `h2 {color: blue;}` so I have no idea why it won't let me advance in this challenge. In fact, the h2 is visually blue also when Ctrl + Enter is hit.

```html

<style>
  h2{
    color: blue;
  } 
</style>
<h2>CatPhotoApp</h2>
<main>
  ...
</main>

```

**Comment by tri-hoang** [comment] 2017-06-10 07:27
It seems like this bug only happens in Firefox.
I tried it in Chrome and it works just fine.

**Comment by lynxlynxlynx** [comment] 2017-08-05 15:55
This is a duplicate of #15227, so someone please close it.

**Closed** 2017-08-06 20:04 UTC
Labels: beta
