### ISSUE TITLE
Internal footer links handling broken when cors required from .dev site

### ISSUE THREAD

**Issue by parvathy-santhosh** [freeCodeCamp/freeCodeCamp#38355] opened 2020-03-11 17:27 UTC
**Describe the bug**
Internal footer links from the footer on FCC homepage are broken when accessed from 

**To Reproduce**
1. Go to 'freecodecamp.dev'
2. Scroll down to the footer
3. Click on any of the internal footer links such as any of the trending guides or most of the links under the title Our Non Profit
4. 404 Error, the link that gets referenced is not to the main .org site but merely tagged onto freecodecamp.dev/... This leads to broken links. The footer links have all been by default parsed together like external links and hence 

**Expected behavior**
The internal and external links were to be handled separately with the internal links handled by the GatsbyLink so as to redirect it to the appropriate domain...

**Desktop (please complete the following information):**
 - Browser: Google Chrome
 - Version 80.0.3987.132

**Additional context**

 It looks like this provision has been provided in [freeCodeCamp/client/src/components/helpers/Link.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/helpers/Link.js)  and [freeCodeCamp/client/src/components/Footer/FooterCol.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Footer/FooterCol.js) but the relevant provision has not been provided in declaring the boolean value `internal` in the file [freeCodeCamp/client/src/components/Footer/footerLinks.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Footer/footerLinks.json) and hence does not get implemented.

**Comment by ojeytonwilliams** [comment] 2020-03-11 18:48
I'm not sure this is actually a bug.  As I understand it, when you go to https://freecodecamp.dev/news you're seeing a 'dummy' version of news with only some of the pages - hence all the 404s.

Also, the links should be external because `internal` links are purely for links to other parts of the Gatsby site (learn, settings, certification and so on) and news is a separate Ghost site.

**Comment by ahmadabdolsaheb** [comment] 2020-03-12 09:25
Thanks for creating a detailed issue description, @parvathy-santhosh. 
I think the links are working as intended as @ojeytonwilliams pointed out. the reason we are getting 404 is that we have not got around making all of those pages for .dev/news because we mainly use .dev for testing. I am going to close this issue for now. If you think this issue has been closed by mistake, feel free to reopen this issue.

**Closed by ahmadabdolsaheb** 2020-03-12 09:25 UTC
Labels: type: bug
