### ISSUE TITLE
Skip button for step-style challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4662] opened 2015-11-23 07:07 UTC
For our step-style challenges, many campers are confused and don't realize that they just need to click the "open link in new tab" button to enable the "next step" button. 

We should add a small "skip step" button so that campers can keep going if, say, they already have a GitHub account.

![](https://www.evernote.com/l/Alw3pAklsxRCl4EYYf5cqvJZ-UguGRMTg64B/image.png)

**Comment by BerkeleyTrue** [comment] 2015-11-23 07:26
duplicate of #3690

**Closed by BerkeleyTrue** 2015-11-23 07:26 UTC
Labels: help wanted, ux
