### ISSUE TITLE
FreeCodeCamp streak doesn't update unless I do something after 6(PST)

### ISSUE THREAD

**Issue by Azbo400** [FreeCodeCamp/FreeCodeCamp#12210] opened 2016-12-24 23:27 UTC
FreeCodeCamp streaks not updating unless it is after around 6 PST

Hello Everyone. In FCC for some reason, if I do not get any brownie points after around 6 PST it does not update for that day. Even if it is after 6 and I already got 7 brownie points, for some reason it doesn't update unless I get another. 

Here is what I mean:
![image](https://cloud.githubusercontent.com/assets/12162628/21469070/90101574-c9ec-11e6-9616-2c613f090eaa.png)
As you may be able to see I got 9 brownies today and did something for 29 days but it doesn't update and only shows 28 days and if I don't do something after 6ish I loose the streak.

My browser info:
Chrome Version 55.0.2883.87 m (64-bit)
Windows 10

Thank you in advance!

Cheers,
Ryan

**Comment by erictleung** [comment] 2016-12-25 07:51
@Azbo400 thanks for the issue. This appears to be a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7925. Closing in favor of existing issue, but thank for your observations about what time it doesn't update for you. That will help in fixing the issue. Happy coding!

**Closed by erictleung** 2016-12-25 07:51 UTC
