### ISSUE TITLE
Button truncated/cut 

### ISSUE THREAD

**Issue by mh453** [FreeCodeCamp/FreeCodeCamp#8939] opened 2016-06-03 18:16 UTC
#### Responsively Style Checkboxes
https://www.freecodecamp.com/challenges/responsively-style-checkboxes

#### Issue Description
"Like", "Info" buttons are truncated and "delete" is cut off 

#### Browser Information
* Browser Name, Version: Google Chrome, Version 50.0.2661.102 m
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: 

#### Your Code
``` 
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
```
#### Screenshot
![capture](https://cloud.githubusercontent.com/assets/16688620/15788268/92ba4174-29be-11e6-8eb3-ab06c948ff30.PNG)

#### Possible Fix
You can  use btn-group which allows you to create a group of buttons next to each other we use btn-group btn-group-justified to take up the full width. W3 link - http://www.w3schools.com/bootstrap/bootstrap_button_groups.asp 
```
  <div class="btn-group btn-group-justified">
    <a href="#" class="btn btn-primary"><i class="fa fa-thumbs-up"></i> Like</a>
    <a href="#" class="btn btn-primary"><i class="fa fa-info-circle"></i> Info</a>
    <a href="#" class="btn btn-primary"><i class="fa fa-trash"></i> Delete</a>
  </div>
```
Or use btn-block to put each button on a new line.

**Comment by mh453** [comment] 2016-06-03 18:19
To look at my code and possible fix look at md file in edit view

**Comment by erictleung** [comment] 2016-06-03 20:15
Closing as duplicate of #7842. Someone else has [suggested that](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7842#issuecomment-204642391).

**Closed by erictleung** 2016-06-03 20:15 UTC
