### ISSUE TITLE
Add "Add Certification to LinkedIn" button to certifications

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37825] opened 2019-11-25 18:14 UTC
User story: As a logged-in user, when I view my own certifications that I've earned, there is a button up top that says "Add This Certification to your LinkedIn Profile"

Clicking this button uses the LinkedIn API to create the certification. LinkedIn auth may also be necessary and can be done just-in-time. 

Here's the API documentation: https://developer.linkedin.com/docs/guide/v2/people/profile-edit-api/certifications#

We also want to make sure this adds them to our LinkedIn alumni network (or that there's a step in the flow for them to join it). 

Here's our LinkedIn alumni network: https://www.linkedin.com/school/free-code-camp/people/?viewAsMember=true

**Comment by arjunnij** [comment] 2019-11-25 18:36
Hi Quincy - I am new to front-end development but have prior experience programming in low-level languages like C/C++. Is there documentation anywhere describing the freeCodeCamp code base? What would you recommend as a good entry point to start looking at? I'd like to try to implement this feature if possible.

**Comment by vanya829** [comment] 2019-11-28 13:44
@QuincyLarson Hi. Can I get this one to work with?

**Comment by vanya829** [comment] 2019-12-06 15:29
@QuincyLarson I check possibilities to create a certificate in LinkedIn and there are few ways of doing that:

- Add to profile button. https://addtoprofile.linkedin.com/ . The problem of this option is that "Add to profile button" doesn't support autofill of certificate data, so user have to put them manually (https://www.linkedin.com/help/linkedin/answer/61169?query=add%20to%20profile&src=li-other&veh=www.linkedin.com%7Cli-other)
- Create a certificate using API. This is a solution you are expecting. In this case, we can't do it just in one click, as we have to redirect a user to auth endpoint and only when he is logged in, we can send a request to create a certificate. So can you describe how do you see this interaction from a user perspective?

**Comment by raisedadead** [comment] 2020-02-11 07:25
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/36277

**Closed by raisedadead** 2020-02-11 07:25 UTC
Labels: status: on the roadmap
