### ISSUE TITLE
... always need to "Reset" before able to code.

### ISSUE THREAD

**Issue by opel22** [FreeCodeCamp/FreeCodeCamp#8469] opened 2016-05-05 08:35 UTC
#### Challenge Name
Responsive Design with Bootstrap
https://www.freecodecamp.com/challenges/responsively-style-checkboxes

#### Issue Description
When a new challange starts, I always have first to "Reset" the challange, if not, I'm not able to place the cursor where I would like to code, or, when clicked into the coding part, the cursor "jumps" to another part and my code is entered there.

#### Browser Information
* Chrom, Version 50.0.2661.94 m 
* Windows 10: 
* Desktop

#### Your Code
not relevant

#### Screenshot
not possible

regards
opel22

**_PS: in the jQuery-Part it is working again as expected._**

**Comment by raisedadead** [comment] 2016-05-05 11:34
Duplicate of #7847.
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) before submitting a bug report.

Thanks and happy coding!

**Closed by raisedadead** 2016-05-05 11:34 UTC
Labels: duplicate
