### ISSUE TITLE
The sign-in page should be translated

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#42314] opened 2021-05-31 08:48 UTC
My own account was always logged in, so I didn't notice the sign-in page is in English. Some Chinese users felt confused about this page. I didn't find where to translate this part on Crowdin.

**Comment by raisedadead** [comment] 2021-05-31 11:08
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/41112

**Closed by raisedadead** 2021-05-31 11:08 UTC
Labels: scope: i18n
