### ISSUE TITLE
Go to the next UNSOLVED challenge

### ISSUE THREAD

**Issue by guipsamora** [FreeCodeCamp/FreeCodeCamp#5829] opened 2016-01-03 22:05 UTC
Instead of going to the "NEXT" challenge when we click the green box "Submit and go to the next challenge", the page should go to the "NEXT UNSOLVED" challenge.

I know this is really a cherry on the cake type of issue but in major updates such as the last one, it is really annoying to go through each challenge even though I've already completed it.

**Comment by DDaems** [comment] 2016-01-03 22:55
duplicate of #5612

**Comment by guipsamora** [comment] 2016-01-03 23:05
Thanks for pointing out! :+1:

**Closed** 2016-01-03 23:42 UTC
