### ISSUE TITLE
Worng text

### ISSUE THREAD

**Issue by arvikumu** [FreeCodeCamp/FreeCodeCamp#2040] opened 2015-08-18 09:25 UTC
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Let's try getting a for loop to work by pushing values to an array."
In this text the 'for' should be replaced by 'while'.
![screenshot 2](https://cloud.githubusercontent.com/assets/13277303/9326655/f6b87e9c-45b8-11e5-85d8-56f4b35e83d6.png)

**Comment by michael-krebs** [comment] 2015-08-18 16:03
duplicate of #1802 which has been fixed

**Closed** 2015-08-23 04:57 UTC
