### ISSUE TITLE
jquery exercises

### ISSUE THREAD

**Issue by efkar** [FreeCodeCamp/FreeCodeCamp#2737] opened 2015-08-26 13:21 UTC
Challenge http://freecodecamp.com/challenges/waypoint-change-the-css-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

all jquery exercises constantly refreshes the page , couple of seconds later you passed the test popup shows up even though i cant change the code because of the refreshing issue.

If document.ready is present in the code deleting one letter of it solves the issue temporarily

**Comment by Mansuro** [comment] 2015-08-26 14:09
Duplicate of #2729

**Closed** 2015-09-08 04:41 UTC
