### ISSUE TITLE
Improve the navbar UI

### ISSUE THREAD

**Issue by kaleemullah786** [freeCodeCamp/freeCodeCamp#50610] opened 2023-06-04 12:42 UTC
### Describe the Issue

Navbar and its contents seem simple, redesigning the items and menu may improve the UI 

### Affected Page

https://www.freecodecamp.org

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org'
2. Play around with the navbar
3. Improve the menu
4. Good looking sign in/signup actions

### Expected behavior

enhance the design for a better look and feel 

### System

- Device: any
- OS: all
- Browser: all

**Comment by Samarth-Dengre** [comment] 2023-06-04 17:46
Hi @kaleemullah786, can you assign this issue to me

**Comment by kaleemullah786** [comment] 2023-06-05 01:13
Sure! please go ahead

**Comment by bbsmooth** [comment] 2023-06-05 03:39
> Navbar and its contents seem simple, redesigning the items and menu may improve the UI
> 2. Play around with the navbar
> 3. Improve the menu

This is a pretty broad and generic description. Can you be a little more specific about what you think needs improvement and how you would improve it?

**Comment by kaleemullah786** [comment] 2023-06-05 04:10
> > Navbar and its contents seem simple, redesigning the items and menu may improve the UI
> > 2. Play around with the navbar
> > 3. Improve the menu
> 
> This is a pretty broad and generic description. Can you be a little more specific about what you think needs improvement and how you would improve it?

redesigning the items i.e. changing the avatar and bringing the menu to it instead of having a separate one, bringing theme change action on the bar from the menu, improving hover and item styles all for better feel

**Comment by ahmadabdolsaheb** [comment] 2023-06-05 06:45
Thank you for the proposal, @kaleemullah786 
We have a related issue for exposing the platform links. https://github.com/freeCodeCamp/freeCodeCamp/issues/41373
I am open to specific (what, how) improvements to the main menu. Once those changes are discussed and mocked we could move to the implementation.

**Comment by ahmadabdolsaheb** [comment] 2023-06-05 07:09
Thank you for the mock. Could you please elaborate how the changes demonstrated in the mock would improve the ux?

**Comment by Samarth-Dengre** [comment] 2023-06-06 14:07
@kaleemullah786 I have made some minor changes:
1. Increased height of universal navbar
2. Removed toggle theme mode from the menu and placed it on the navbar
3. Merged menu and profile button when the user is logged in.

Here are the screenshots. If you want any changes in the UI of the navbar, please tell me.
![Screenshot (185)](https://github.com/freeCodeCamp/freeCodeCamp/assets/103602874/b6c001db-beb0-43cd-b948-557bb714a625)
![Screenshot (188)](https://github.com/freeCodeCamp/freeCodeCamp/assets/103602874/62b38d52-b82d-4a54-a9f0-69f4655b62cd)

**Comment by bbsmooth** [comment] 2023-06-06 15:51
> Merged menu and profile button when the user is logged in.

What would the accessible name be for this button? Since the button toggles a menu then I think it should be "Menu". But the icon doesn't look like a menu, so now you have a disconnect between the name and the appearance. I think we need to leave the looks of this button as is. Personally, I think we should drop the profile link completely from the top nav bar since we already have a link to the profile in the menu itself. It's basically a duplicate link that is very close to its counterpart, which is sort of frowned upon for accessibility.

**Comment by Samarth-Dengre** [comment] 2023-06-06 18:23
> > Merged menu and profile button when the user is logged in.
> 
> What would the accessible name be for this button? Since the button toggles a menu then I think it should be "Menu". But the icon doesn't look like a menu, so now you have a disconnect between the name and the appearance. I think we need to leave the looks of this button as is. Personally, I think we should drop the profile link completely from the top nav bar since we already have a link to the profile in the menu itself. It's basically a duplicate link that is very close to its counterpart, which is sort of frowned upon for accessibility.

So we can change the icon to a button, it is not a big deal.

**Comment by ahmadabdolsaheb** [comment] 2023-06-07 13:47
@Samarth-Dengre, thank you for the mocks.

1. Increased height of universal navbar
increasing the height of the navbar from 38 to hight 50s is a great idea. It makes sure the mobile users do not press on the menu while interacting with the editor.
3. Removed toggle theme mode from the menu and placed it on the navbar
We have debated this in the past. Currently the theme toggle is available only for signedin users, and it is not as important or frequently-used to expose it. If anything, we might move it to the settings page.
5. Merged menu and profile button when the user is logged in.
We have considered this in the past. You could see the extended discussion in https://github.com/freeCodeCamp/freeCodeCamp/issues/41373

**Comment by Vishal08122001** [comment] 2023-06-08 12:41
### Respected Sir,
### Can you assign this task to me so that, i can contribute in this issue?

**Comment by ChrisSJung** [comment] 2023-06-10 09:49
@ahmadabdolsaheb Hello! I have just changed the height of the navbar to 60px by changing the CSS variable 
"--header-height" from 38px to 60px. I sent a pull request. Thank you in advance for any feedback. 

- Chris

**Comment by ChrisSJung** [comment] 2023-06-10 21:53
The changes are all done.  There is a failed check in the lint:prettier. Would appreciate any feedback.

1. Navbar height changed to 60px
2. FCC Logo remains in right places throughout different viewports
3. Searchbar in the right place and works in all viewports
4. Button sizes (language, menu, sign-in) are all same and consistent in all viewports.

Thank you for reading this.

**Comment by ChrisSJung** [comment] 2023-06-10 22:14
Here are some screenshots:

![ffcnav_1](https://github.com/freeCodeCamp/freeCodeCamp/assets/97473473/555e8ddd-3c2f-4fbf-bfdd-4f1ca9e5e0fc)

![ffcnav_2](https://github.com/freeCodeCamp/freeCodeCamp/assets/97473473/878a1d4f-9261-44d1-b305-68861a791655)

![ffcnav_2b](https://github.com/freeCodeCamp/freeCodeCamp/assets/97473473/56360a04-acc7-40c7-bc8f-02f20d01fbee)

**Comment by ChrisSJung** [comment] 2023-06-10 22:15
![ffcnav_3](https://github.com/freeCodeCamp/freeCodeCamp/assets/97473473/34614849-b664-421b-90fb-5d66e8c23b6d)
![ffcnav_3b](https://github.com/freeCodeCamp/freeCodeCamp/assets/97473473/54234455-c219-4175-bb86-bd3e256a0d57)

**Comment by ahmadabdolsaheb** [comment] 2023-06-13 07:56
Thank you for the hard work, @ChrisSJung. The pr seems closed. If you are planning to continue working on that pr, re-open that pr and I will take a deeper look into prettier.

**Comment by jeffmchang** [comment] 2023-07-22 00:46
Is this issue still open to be worked on? Or has it been settled?

**Comment by ahmaxed** [comment] 2023-07-22 00:59
The issue is open and not being worked on ATM.

**Comment by AbhaysCode** [comment] 2023-07-26 11:51
As a beginner, I would like to contribute to this issue. However, @ahmaxed, I have a doubt: **why is this issue still open even though @ChrisSJung has already made the necessary changes?** Any help regarding this matter would be greatly appreciated.

**Comment by ChrisSJung** [comment] 2023-07-26 11:58
> As a beginner, I would like to contribute to this issue. However, @ahmaxed, I have a doubt: **why is this issue still open even though @ChrisSJung has already made the necessary changes?** Any help regarding this matter would be greatly appreciated.

Hi, this is because my changes was causing few errors and I tried to make adjustments, but it was not as responsive so my update is not applied and it is up for anyone to fix the original error stated by the op.

**Comment by ahmaxed** [comment] 2023-07-29 16:33
Not sure what it is, but If you are stuck and need help, feel free to ask questions in the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

**Comment by biswabaibhab007** [comment] 2023-08-01 15:34
Can I work on this issue?

**Comment by ahmaxed** [comment] 2023-08-04 08:02
@biswabaibhab007 there is an open pr for this issue. You are welcome to look into issues that don't have an open pull request associated with them.

**Closed** 2023-09-19 11:50 UTC
Labels: help wanted, scope: UI, type: feature request
