### ISSUE TITLE
Please add more information to Image Search Abstraction Layer

### ISSUE THREAD

**Issue by eliecerthoms** [freeCodeCamp/freeCodeCamp#10816] opened 2016-09-19 20:28 UTC
#### Challenge Name

https://www.freecodecamp.com/challenges/image-search-abstraction-layer
#### Issue Description

Because one comes from a previous database driven project, when doing the <a href="https://www.freecodecamp.com/challenges/image-search-abstraction-layer">Image Search Abstraction Layer</a> project, you get the idea that for this one you need to store the image links presented in the description of the project inside your own database, instead of using an external image search API to get the required information. 

My Solution would be to add at least a bullet saying `Use any image search API to complete this challenge` and even add some examples for which of these API's to use. I don't think it would make the challenge that much easier, and would help avoid confusion and countless hours wasted approaching the problem from a flawed perspective. (I almost made something completely different than what was asked)
#### Browser Information

- Browser Name, Version: Chrome 53.0.2785.116 m (64-bit)
- Operating System: Windows 10, 64 bit
- Mobile, Desktop, or Tablet: Desktop

**Comment by dhcodes** [comment] 2016-09-20 12:47
I could get onboard with this, especially considering the conversation in #5934. What do others think about adding @eliecerthoms's bullet above and suggestions to possibly use the Bing or Imgur api as suggestions (pointing out that campers can use any service they want). cc @FreeCodeCamp/issue-moderators

**Comment by Em-Ant** [comment] 2016-09-20 16:10
I agree with adding some suggestions to use some search service. 
This one is also going to need some user story revision. See https://github.com/FreeCodeCamp/CurriculumExpansion/issues/38.

**Comment by DavOnGit** [comment] 2016-09-23 13:15
Hi all,
i agree with __@Em-Ant__, we shoul'd explain that this project is about building an App that:
-  can do __image search__  using whichever __search engine API__ (pointing out that they should find and select the API service that best fits them)
- the App send query results JSON formatted with data about url,  alt, text...
- I can paginate through the responses by adding a ?offset=2 parameter to the query URL
- I can get a list of the most recently __submitted search strings__.

This can be done with a better introduction or maybe integrating user stories with clearer point and examples.
I think that istructions have to be crystal clear!
(sorry for bad english! :)

**Comment by QuincyLarson** [comment] 2016-09-24 07:28
@Em-Ant @DavOnGit great - this is the best time to update the user stories. Could you agree on what the final user stories should be, make sure that @Em-Ant's example project fulfills them, then post them here? I can update the seed files.

**Comment by Em-Ant** [comment] 2016-09-24 07:43
@DavOnGit the problem is that pagination is specific to Google search. We (me, @Greenheart @Rafase282 ) wanted to change that user story, in order to return a variable number of items. This will make the project easier to test, if we add automated testing requirements. 

#### Suggested user stories (from FreeCodeCamp/CurriculumExpansion#38):

- (Unchanged) I can get the image URLs, alt text and page urls for a set of images relating to a given search string.
- I can request a specific number of results by adding the ?results=<a-positive-integer> parameter to the URL.
- I can get a list of up to 10 of the most recently submitted search strings at the path /latest

Is that ok for you @FreeCodeCamp/issue-moderators ? If yes I'll change the example project in hyperdev.

**Comment by DavOnGit** [comment] 2016-09-24 15:06
I agree with the above @Em-Ant suggested user stories but what about adding a new bullet like:
- Use whichever libraries, APIs or package you need to fulfill user stories.

as suggested by @eliecerthoms?

**Comment by eliecerthoms** [comment] 2016-09-24 16:57
I also suggest a direct link to really free Image Search API's, since it was a pain to find one until I settled for Flickr's. Didn't test much of google because they said that from 5,000+ request they would start to charge me. I reckon a credit card was then needed so I aborted. (Don't have one) Microsoft's bing is good too, but the same case applies. Imgur was really difficult for me to implement, but it was free.

**Comment by dhcodes** [comment] 2016-09-24 18:05
@Em-Ant fwiw, I was able to do pagination using the Bing API I believe. https://battle-mouse.hyperdev.space/

**Comment by Em-Ant** [comment] 2016-09-24 18:46
@eliecerthoms I agree. I used google because i reverse-engineered the example project that was on fcc at that time. Setting up a google search account was quite difficult but it didn't require a credit card.
Are you sure a credit card is needed ? What do you recommend ?

**Comment by eliecerthoms** [comment] 2016-09-24 23:23
@Em-Ant No, I just thought it would be since they said they'd automatically charge once you surpassed 5000 requests. Thanks for clarifying this. I see now Imgur, Bing, Flickr and Google can be added as options in a bullet.

**Comment by systimotic** [comment] 2016-11-26 22:29
As the curriculum update is on the way, should this issue still be taken care of?
FreeCodeCamp/CurriculumExpansion#81 addresses this.

**Comment by systimotic** [comment] 2017-01-22 12:14
This challenge has been removed in the beta, so I'm closing this issue.

**Closed by systimotic** 2017-01-22 12:14 UTC
Labels: discussing
