### ISSUE TITLE
Cursor/position issue.

### ISSUE THREAD

**Issue by rkdnc** [freeCodeCamp/freeCodeCamp#13434] opened 2017-02-18 22:53 UTC
Not challenge specific, but when you start a new challenge, where you click in the text interpreter doesn't align where the cursor appears. You may click in one spot to begin typing, but end up a few rows down and mess up your code until you click again.

**Comment by raisedadead** [comment] 2017-02-19 08:12
Duplicate of #7847
Workaround is mentioned here https://github.com/freeCodeCamp/freeCodeCamp/issues/7847#issuecomment-270299746

**Closed by raisedadead** 2017-02-19 08:12 UTC
