### ISSUE TITLE
[using-the-justifycontent-property-in-the-tweet-embed]

### ISSUE THREAD

**Issue by computerluca** [freeCodeCamp/freeCodeCamp#12785] opened 2017-01-23 21:30 UTC
Challenge [using-the-justifycontent-property-in-the-tweet-embed](http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-justifycontent-property-in-the-tweet-embed) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
It makes me pass the challenge even if I have not inserted the css statement
    justify-content:center;

```html
    
    
<style>
body {
  font-family: Arial, sans-serif;
}
header, footer {
  display: flex;
  flex-direction: row;
}
header .profile-thumbnail {
  width: 50px;
  height: 50px;
  border-radius: 4px;
}
header .profile-name {
  display: flex;
  flex-direction: column;
  
  margin-left: 10px;
}
header .follow-btn {
  display: flex;
  margin: 0 0 0 auto;
}
header .follow-btn button {
  border: 0;
  border-radius: 3px;
  padding: 5px;
}
header h3, header h4 {
  display: flex;
  margin: 0;
}
#inner p {
  margin-bottom: 10px;
  font-size: 20px;
}
#inner hr {
  margin: 20px 0;
  border-style: solid;
  opacity: 0.1;
}
footer .stats {
  display: flex;
  font-size: 15px;
}
footer .stats strong {
  font-size: 18px;
}
footer .stats .likes {
  margin-left: 10px;
}
footer .cta {
  margin-left: auto;
}
footer .cta button {
  border: 0;
  background: transparent;
}
</style>
<header>
<img src="https://pbs.twimg.com/profile_images/378800000147359764/54dc9a5c34e912f34db8662d53d16a39_400x400.png" alt="Quincy Larson's profile picture" class="profile-thumbnail">
<div class="profile-name">
  <h3>Quincy Larson</h3>
  <h4>@ossia</h4>
</div>
<div class="follow-btn">
  <button>Follow</button>
</div>
</header>
<div id="inner">
<p>How would you describe to a layperson the relationship between Node, Express, and npm in a single tweet? An analogy would be helpful.</p>
<span class="date">7:24 PM - 17 Aug 2016</span>
<hr>
</div>
<footer>
<div class="stats">
  <div class="retweets">
    <strong>56,203</strong> RETWEETS
  </div>
  <div class="likes">
    <strong>84,703</strong> LIKES
  </div>
</div>
<div class="cta">
  <button class="share-btn">Share</button>
  <button class="retweet-btn">Retweet</button>
  <button class="like-btn">Like</button>
</div>
</footer>

    ```

**Comment by dhcodes** [comment] 2017-01-23 21:38
@computerluca Thanks for the issue. Are you on chrome or Firefox?

**Comment by computerluca** [comment] 2017-01-23 21:40
Chromium on Linux Ubuntu

**Comment by dhcodes** [comment] 2017-01-24 13:51
@computerluca your code will pass on Chrome. As the tests use `.css` assert methods, I believe this issue is caused by #10749 so I'm closing this one as a duplicate of that. Thanks again for submitting it so we can keep track of all the issues this is causing.

**Closed by dhcodes** 2017-01-24 13:51 UTC
Labels: beta
