### ISSUE TITLE
wrong spelling of bonfire falsy url path on View my solution link

### ISSUE THREAD

**Issue by rlynjb** [FreeCodeCamp/FreeCodeCamp#3806] opened 2015-10-19 20:36 UTC
Hi all, just wanted to file an issue for View My Solution link for Bonfire: Falsy Bouncer solution page. This is a mispelled url path.

- When View My Solution link is clicked for Bonfire: Falsy Bouncer, it takes me to this link below
http://www.freecodecamp.com/challenges/Bonfire:%20Falsey%20Bouncer?solution=....

and gives me this error
404: We couldn't find a challenge with the name `Bonfire: Falsey Bouncer` Please double check the name.
404: We couldn't find path /challenges

This seem to be the correct path:
http://www.freecodecamp.com/challenges/Bonfire:%20Falsy%20Bouncer?solution=....

Notice Falsey and Falsy

**Comment by ltegman** [comment] 2015-10-19 21:22
Thanks for the report! I can confirm this does indeed happen on any challenges where the name has changed since the user submitted their solution.

**Comment by Takumar** [comment] 2015-10-25 12:50
I have the same problem.
Also @camperbot have problem with that bonfire, when you try to find help, it answers only on command: "Bonfire: Falsey Bouncer".

**Comment by ltegman** [comment] 2015-10-26 19:51
@Takumar Unfortunately the Camperbot resources are maintained independently of the FCC repo. I have an open PR in the Camperbot repo to pull in new challenge data, but ultimately the only way to really keep them in sync will be to have Camperbot pull the data from FCC itself.

**Comment by gasperno** [comment] 2015-12-10 06:58
@ltegman This doesnot seem to be an issue anymore. When I click View My Solution, it is taking me to 
https://........falsy-bouncer. 
As the OP pointed out, this is not going to falsey-bouncer.
Even camper bot now responds for bonfire falsy bouncer. 
May be this issue can be closed.

**Comment by Takumar** [comment] 2015-12-10 10:52
@gasperno, camperbot is independent project, I've made changes in description of "Falsy bouncer" in [#12](https://github.com/FreeCodeCamp/camperbot/pull/12) so camperbot now reacts on command 'bonfire falsy' correct.
Issue with error 404, when you try to go to your solution of "Falsey bouncer" from your code portfolio still is not solved.

**Comment by ltegman** [comment] 2015-12-10 15:31
Yeah, this is still not resolved. If you go to the profile of the user who reported this issue and try clicking on their link to falsey bouncer you'll still get the error.

**Comment by Takumar** [comment] 2015-12-10 15:40
@gasperno and @ltegman if we want to find our solution to remind how it worked it is not so big problem, because we can copy link from our code portfolio and modify the link by hand to correct (new) name, i.e. http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer#?solution= ...
But it needs to be corrected someday for sure.

**Comment by bugron** [comment] 2016-01-20 13:54
@BerkeleyTrue can you resolve this issue for the camper who has reported so we can close it?

**Comment by BerkeleyTrue** [comment] 2016-01-20 15:56
It seems like just navigating to the challenge and re-submitting should overwrite the old name.

**Comment by bugron** [comment] 2016-01-20 16:31
Closing this issue then. @rlynjb feel free to reopen if you still experience problems after resubmitting, thanks.

**Closed by bugron** 2016-01-20 16:31 UTC
Labels: confirmed, help wanted
