### ISSUE TITLE
jQuery 1st waypoint: Need an extra empty line in order to validate.

### ISSUE THREAD

**Issue by airyz** [FreeCodeCamp/FreeCodeCamp#2113] opened 2015-08-18 19:43 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When you use the following it doesnt validate as correct.  It needs an extra line between the opening and closing lines.

$(document).ready(function() {
});

Workaround for anyone stuck here, use this:
$(document).ready(function() {

});

**Comment by michael-krebs** [comment] 2015-08-18 21:10
duplicate of  #2081

**Comment by BerkeleyTrue** [comment] 2015-08-21 04:15
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 04:15 UTC
