### ISSUE TITLE
Can’t login to my fcc account using github. Need Help!

### ISSUE THREAD

**Issue by a2-zubair** [freeCodeCamp/freeCodeCamp#38151] opened 2020-02-02 13:28 UTC
Hi, I can't login to my fcc account using github since yesterday. I also email to support team of fcc. But I don't get any response yet. I'm still facing the problem to login. All four login buttons doesn't working from my browser (I'm using Firefox 72.0.2). 

I also try with chrome browser but the problem remain same. I don't know is it a bug or not?. I don't know that am i the only person facing this problem? But two days ago I did login successfully to my account using github. 

Can you help on this? How can I login to my account?

**Comment by a2-zubair** [comment] 2020-02-02 13:35
The remain like this 

![image](https://user-images.githubusercontent.com/6688141/73608964-1df22780-45f3-11ea-9989-3f0ad0af0e3c.png)

I clicked all the buttons but no action happen.

**Comment by a2-zubair** [comment] 2020-02-02 14:02
my web console show me this result.

![image](https://user-images.githubusercontent.com/6688141/73609329-b3db8180-45f6-11ea-911f-bd29f8fe2639.png)

**Comment by raisedadead** [comment] 2020-02-03 10:13
Hi @scissorsneedfoodtoo @ahmadabdolsaheb can you update/check the policy. I think this is a firefox only thing.

/cc @freeCodeCamp/dev-team

**Comment by raisedadead** [comment] 2020-02-03 10:13
@a2-zubair can you try using Chrome and see if the same issue is reproducible?

**Comment by scissorsneedfoodtoo** [comment] 2020-02-03 10:44
@raisedadead, just tried this on Firefox and it's working on my end.

@a2-zubair, are you using any ad blockers? If so, try disabling them or whitelist the sign in page and try again.

**Comment by raisedadead** [comment] 2020-02-03 10:54
@a2-zubair I just tested this on the same version of Firefox as you and was unable  to reproduce.

**Comment by raisedadead** [comment] 2020-02-03 16:30
Hi @a2-zubair I am going to close this for now. But please feel free to continue the discussion here. Once we determine this is not isolated to your system / browser or network and is something that we need to fix in the codebase, we will re-open.

Please get back to us with any additional information.

**Closed by raisedadead** 2020-02-03 16:30 UTC
Labels: type: DevOps

**Comment by a2-zubair** [comment] 2020-02-03 18:43
Hi @raisedadead @scissorsneedfoodtoo @ahmadabdolsaheb I sorry for late reply. Yes, I am facing same problem using chrome (Version 79.0.3945.130) browser. Here you can see my web console image

![image](https://user-images.githubusercontent.com/6688141/73679074-e44d1980-46e3-11ea-9fd1-3e805c7f75c2.png)

after clicking sign in button below see image

![image](https://user-images.githubusercontent.com/6688141/73679213-29714b80-46e4-11ea-9484-88d64f80ddf7.png)

all four buttons I clicked but didn't happen any action. When I tried chrome incognito mode I found this message from my web console.

![image](https://user-images.githubusercontent.com/6688141/73679455-98e73b00-46e4-11ea-9939-30c8bb0d9a0a.png)

after passing the "I'm robot" part, I get the same result.

![image](https://user-images.githubusercontent.com/6688141/73679665-10b56580-46e5-11ea-9192-573986a5bd29.png)

@scissorsneedfoodtoo In Firefox i'm not sure that i'm using any ad blocker. I can tell you what extension i'm using 

1. Privacy Pass (Enable).  (One download and Search Extension enable)

and this are disable extensions

![image](https://user-images.githubusercontent.com/6688141/73680497-8a9a1e80-46e6-11ea-86f2-dc68834e309b.png)

I use them when I need. If you need any other info please ask me. One thing I want to say that I can use github to login to my fcc forum account. In there I don't face any problem to login but only fcc learn platform I am facing this kind of unusual problem.

**Comment by a2-zubair** [comment] 2020-02-03 19:37
Good news!! I can login now!!

![image](https://user-images.githubusercontent.com/6688141/73684628-c507b980-46ee-11ea-9579-7f60fd6545e1.png)

**Comment by a2-zubair** [comment] 2020-02-03 20:12
Thanks to the dev team and support team. 👍

**Comment by scissorsneedfoodtoo** [comment] 2020-02-04 05:41
#@a2-zubair, glad that you were able to sign in! Thank you for all of those additional details. Those will be helpful in the future if other users have similar issues signing in.

**Comment by a2-zubair** [comment] 2020-02-28 02:07
@raisedadead @scissorsneedfoodtoo @ahmadabdolsaheb 
Hi guys, How do you doing? I have facing login problem once again. Below I share my problem, please take a look.

![1](https://user-images.githubusercontent.com/6688141/75503289-7dc7cc80-59ff-11ea-9884-5afb3d876030.jpg)
.
.
.
![2](https://user-images.githubusercontent.com/6688141/75503326-90da9c80-59ff-11ea-9f06-f874cf769d5c.jpg)
.
.
.
Also I tried to login fcc forum but I couldn't found any option for github. How can I login with my github? Here you can see below

![3](https://user-images.githubusercontent.com/6688141/75503900-24609d00-5a01-11ea-9271-87da7623534c.jpg)

**Comment by raisedadead** [comment] 2020-02-28 04:06
Hi I am unable to reproduce the issue in the screenshot, are you sure nothing on your network or a browser extension is blocking this.

Also we have removed GitHub login from forum in favor of the login using freeCodeCamp.org

You can always send yourself a forget password link on your email, in case you want to login directly to the forum.

**Comment by a2-zubair** [comment] 2020-02-28 05:18
@raisedadead Hi, thanks for your reply. No, I'm not use any blocking extension. I don't know why I'm facing this problem second time in one month. You know that I'm using Firefox 73.0.1

But here is the chrome result, please take look below :

![4](https://user-images.githubusercontent.com/6688141/75512412-99d96700-5a1b-11ea-88d8-3a0f5de9d235.jpg)

after passing "I'm robot" I got this : 

![5](https://user-images.githubusercontent.com/6688141/75512459-bb3a5300-5a1b-11ea-971d-abe0003aed58.jpg)

and this

![6](https://user-images.githubusercontent.com/6688141/75512480-cf7e5000-5a1b-11ea-9e30-6600e593378e.jpg)

almost similar from the last time. By the way I don't have any installed extension in chrome.

**Comment by raisedadead** [comment] 2020-02-28 06:47
Could this be your Internet Service Provider? Network (School or Work)? Can you share the general region you are in like City or Country (do no share specifics)? Is there any possibility of any censorship?

**Comment by scissorsneedfoodtoo** [comment] 2020-02-28 07:31
@a2-zubair, I'm not able to reproduce this on the latest versions of Chrome or Firefox either.

It's possible that you're getting the old headers somehow, which is why you're getting those errors about the CORS policy and $ not being defined. That or there is an ad blocker running that we can't see.

Could you open an incognito window and try signing in there?

**Comment by raisedadead** [comment] 2020-02-28 09:59
> It's possible that you're getting the old headers somehow,

Their ISP / network etc. could be caching things disrespecting our CDN, for reasons of bandwidth. This is something we do not have control over mostly.

**Comment by a2-zubair** [comment] 2020-03-01 04:46
@scissorsneedfoodtoo @raisedadead Hi guys, thanks for your reply and support and  sorry for late reply. I don't know why this problem is happening? is it my ISP network or anything from my firefox browser like tracker and content blocking is enabled or something. But I also tried to login using chrome but same problem I faced there.

So, I don't know how to solve it but I found a way to login my account using github. I like to share with you guys. Please take a look below and give me your feedback on it :

![1](https://user-images.githubusercontent.com/6688141/75619610-958e8480-5ba8-11ea-9a55-fa61dd1b81c3.jpg)

![2](https://user-images.githubusercontent.com/6688141/75619613-a3dca080-5ba8-11ea-8ed7-b78d6179e3b2.jpg)

![3](https://user-images.githubusercontent.com/6688141/75619615-ac34db80-5ba8-11ea-805b-02f393965dbe.jpg)

![4](https://user-images.githubusercontent.com/6688141/75619617-b0f98f80-5ba8-11ea-8667-bd4162a55aac.jpg)

![5](https://user-images.githubusercontent.com/6688141/75619626-b656da00-5ba8-11ea-93a1-276c0fa59e8e.jpg)

I'm not sure this is a permanent solution for this problem.

**Comment by raisedadead** [comment] 2020-03-01 07:37
I am afraid we are unable to assist here, this seems to be something specific to your setup, system and network. 

Apologies and good luck.
