### ISSUE TITLE
[beta] Challenge view formatting for lg screen size (>1200px)

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#10027] opened 2016-08-01 12:23 UTC
No further break-point from 1200px +, which differs from production.

Screenshots at 1900px

From production site:
![production](https://cloud.githubusercontent.com/assets/18572518/17293820/8d703ffc-57ea-11e6-96c3-f4b93d585a3a.png)

From beta:
![beta](https://cloud.githubusercontent.com/assets/18572518/17293825/97c65892-57ea-11e6-80a0-7a70ac770eb1.png)

**Comment by raisedadead** [comment] 2016-08-01 13:26
Hey can you pull and check if this still is solves it
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9987

**Comment by Bouncey** [comment] 2016-08-03 05:19
Pulling down now

**Comment by raisedadead** [comment] 2016-08-03 05:43
@Bouncey this is already merged in staging, you just need to sync your staging to test, note that the CSS may not be rendered properly, you would have to trigger a rebuild. Once you start the server via `gulp` hit save on any LESS page, that will recompile the static things

**Comment by BerkeleyTrue** [comment] 2016-08-13 23:27
Is this still an issue?

**Comment by atjonathan** [comment] 2016-08-14 09:06
Cannot reproduce, closing as stale.

**Closed by atjonathan** 2016-08-14 09:06 UTC
Labels: beta, blocked, UX
