### ISSUE TITLE
Bonfire: No repeats please (probably timeout issues)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#6003] opened 2016-01-09 20:43 UTC
Challenge [Bonfire: No repeats please](http://www.freecodecamp.com/challenges/bonfire-no-repeats-please) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not sure if this will be helpful (did not use RegExp in this solution) so I beg your pardon in advance if it is not.

My code (this code with console.logs commented works fine):
```javascript
function permAlone(str) {
  function factorial(n){
    var f = n;
    for (var i=n-1;i>0;i--){f *= i;}
    return f;
  }
  var fact = factorial(str.length);
  var permuts = [];
  var tmpArr = [];
  var counter = 0;
  var strArr = str.split("");
  (function fillPermutsArr(){
    //console.log("> function");
    for (var p=0;p<strArr.length;p++){
    //console.log("\tstrArr: "+strArr+" | iteration: "+p);
      var zeroIndexChar = strArr.splice(p,1)[0];
      //console.log("\tchar: "+zeroIndexChar+" | strArr, spliced: "+strArr+" | iteration: "+p);
      tmpArr.push(zeroIndexChar);
      //console.log("\ttmpArr, pushed: "+tmpArr+" | iteration: "+p);
      if (strArr.length === 0){
        permuts.push(tmpArr.join().split(","));
        //console.log("=> push permut, permuts: "+JSON.stringify(permuts)+" | iteration: "+p);
      }else{
        //console.log("~ recursion");
        fillPermutsArr();
      }
      //console.log("\tstrArr: "+strArr+" | iteration: "+p);
      strArr.splice(p,0,zeroIndexChar);
      //console.log("\tstrArr, spliced: "+strArr+"| iteration: "+p);
      //console.log("\ttmpArr: "+tmpArr+" | iteration: "+p);
      tmpArr.pop();
      //console.log("\ttmpArr, popped: "+tmpArr+" | iteration: "+p);
      //console.log("~ loop body bottom reached | strArr: "+strArr+" | iteration: "+p);
      if (p == 2){
        //console.log("=> done, permuts: "+JSON.stringify(permuts)+" | iteration: "+p);
      }
    }
  })();
  if (fact == permuts.length){
    for (var q=0;q<permuts.length;q++){
      var letterOccurrenceCounter = 0;
      for (var u=1;u<permuts[q].length;u++){
        if (permuts[q][u-1] == permuts[q][u]){letterOccurrenceCounter++;}
      }
      if (letterOccurrenceCounter === 0){counter++;}
    }
    return counter;
    //return "factorial: "+fact+" | "+"counter: "+counter+" | "+JSON.stringify(permuts);
  }else{
    return "ERROR: factorial and formed permutations array lengths are not equal";
  }
  //return counter;
}
permAlone('abc');
//permAlone('aab');
//permAlone("aabb");
//permAlone("abcdefa");
//permAlone("abfdefa");
//permAlone("zzzzzzzz");
```
Bugs, presumably of timeout origin, start running around when any console.log is uncommented.
The worst case of this bug infestation (if all console.logs are uncommented) is inability of result checker to test user submitted script result versus test cases correctly (this mostly relates to the longest input strings like ```zzzzzzzz```).

I ended up using jsfiddle to see logs and finish it: https://jsfiddle.net/exskfk50/
log with all console.logs uncommented:
```
> function 
	strArr: a,b,c | iteration: 0 
	char: a | strArr, spliced: b,c | iteration: 0 
	tmpArr, pushed: a | iteration: 0 
~ recursion 
> function 
	strArr: b,c | iteration: 0 
	char: b | strArr, spliced: c | iteration: 0 
	tmpArr, pushed: a,b | iteration: 0 
~ recursion 
> function 
	strArr: c | iteration: 0 
	char: c | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: a,b,c | iteration: 0 
=> push permut, permuts: [["a","b","c"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: c| iteration: 0 
	tmpArr: a,b,c | iteration: 0 
	tmpArr, popped: a,b | iteration: 0 
~ loop body bottom reached | strArr: c | iteration: 0 
	strArr: c | iteration: 0 
	strArr, spliced: b,c| iteration: 0 
	tmpArr: a,b | iteration: 0 
	tmpArr, popped: a | iteration: 0 
~ loop body bottom reached | strArr: b,c | iteration: 0 
	strArr: b,c | iteration: 1 
	char: c | strArr, spliced: b | iteration: 1 
	tmpArr, pushed: a,c | iteration: 1 
~ recursion 
> function 
	strArr: b | iteration: 0 
	char: b | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: a,c,b | iteration: 0 
=> push permut, permuts: [["a","b","c"],["a","c","b"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: b| iteration: 0 
	tmpArr: a,c,b | iteration: 0 
	tmpArr, popped: a,c | iteration: 0 
~ loop body bottom reached | strArr: b | iteration: 0 
	strArr: b | iteration: 1 
	strArr, spliced: b,c| iteration: 1 
	tmpArr: a,c | iteration: 1 
	tmpArr, popped: a | iteration: 1 
~ loop body bottom reached | strArr: b,c | iteration: 1 
	strArr: b,c | iteration: 0 
	strArr, spliced: a,b,c| iteration: 0 
	tmpArr: a | iteration: 0 
	tmpArr, popped:  | iteration: 0 
~ loop body bottom reached | strArr: a,b,c | iteration: 0 
	strArr: a,b,c | iteration: 1 
	char: b | strArr, spliced: a,c | iteration: 1 
	tmpArr, pushed: b | iteration: 1 
~ recursion 
> function 
	strArr: a,c | iteration: 0 
	char: a | strArr, spliced: c | iteration: 0 
	tmpArr, pushed: b,a | iteration: 0 
~ recursion 
> function 
	strArr: c | iteration: 0 
	char: c | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: b,a,c | iteration: 0 
=> push permut, permuts: [["a","b","c"],["a","c","b"],["b","a","c"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: c| iteration: 0 
	tmpArr: b,a,c | iteration: 0 
	tmpArr, popped: b,a | iteration: 0 
~ loop body bottom reached | strArr: c | iteration: 0 
	strArr: c | iteration: 0 
	strArr, spliced: a,c| iteration: 0 
	tmpArr: b,a | iteration: 0 
	tmpArr, popped: b | iteration: 0 
~ loop body bottom reached | strArr: a,c | iteration: 0 
	strArr: a,c | iteration: 1 
	char: c | strArr, spliced: a | iteration: 1 
	tmpArr, pushed: b,c | iteration: 1 
~ recursion 
> function 
	strArr: a | iteration: 0 
	char: a | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: b,c,a | iteration: 0 
=> push permut, permuts: [["a","b","c"],["a","c","b"],["b","a","c"],["b","c","a"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: a| iteration: 0 
	tmpArr: b,c,a | iteration: 0 
	tmpArr, popped: b,c | iteration: 0 
~ loop body bottom reached | strArr: a | iteration: 0 
	strArr: a | iteration: 1 
	strArr, spliced: a,c| iteration: 1 
	tmpArr: b,c | iteration: 1 
	tmpArr, popped: b | iteration: 1 
~ loop body bottom reached | strArr: a,c | iteration: 1 
	strArr: a,c | iteration: 1 
	strArr, spliced: a,b,c| iteration: 1 
	tmpArr: b | iteration: 1 
	tmpArr, popped:  | iteration: 1 
~ loop body bottom reached | strArr: a,b,c | iteration: 1 
	strArr: a,b,c | iteration: 2 
	char: c | strArr, spliced: a,b | iteration: 2 
	tmpArr, pushed: c | iteration: 2 
~ recursion 
> function 
	strArr: a,b | iteration: 0 
	char: a | strArr, spliced: b | iteration: 0 
	tmpArr, pushed: c,a | iteration: 0 
~ recursion 
> function 
	strArr: b | iteration: 0 
	char: b | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: c,a,b | iteration: 0 
=> push permut, permuts: [["a","b","c"],["a","c","b"],["b","a","c"],["b","c","a"],["c","a","b"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: b| iteration: 0 
	tmpArr: c,a,b | iteration: 0 
	tmpArr, popped: c,a | iteration: 0 
~ loop body bottom reached | strArr: b | iteration: 0 
	strArr: b | iteration: 0 
	strArr, spliced: a,b| iteration: 0 
	tmpArr: c,a | iteration: 0 
	tmpArr, popped: c | iteration: 0 
~ loop body bottom reached | strArr: a,b | iteration: 0 
	strArr: a,b | iteration: 1 
	char: b | strArr, spliced: a | iteration: 1 
	tmpArr, pushed: c,b | iteration: 1 
~ recursion 
> function 
	strArr: a | iteration: 0 
	char: a | strArr, spliced:  | iteration: 0 
	tmpArr, pushed: c,b,a | iteration: 0 
=> push permut, permuts: [["a","b","c"],["a","c","b"],["b","a","c"],["b","c","a"],["c","a","b"],["c","b","a"]] | iteration: 0 
	strArr:  | iteration: 0 
	strArr, spliced: a| iteration: 0 
	tmpArr: c,b,a | iteration: 0 
	tmpArr, popped: c,b | iteration: 0 
~ loop body bottom reached | strArr: a | iteration: 0 
	strArr: a | iteration: 1 
	strArr, spliced: a,b| iteration: 1 
	tmpArr: c,b | iteration: 1 
	tmpArr, popped: c | iteration: 1 
~ loop body bottom reached | strArr: a,b | iteration: 1 
	strArr: a,b | iteration: 2 
	strArr, spliced: a,b,c| iteration: 2 
	tmpArr: c | iteration: 2 
	tmpArr, popped:  | iteration: 2 
~ loop body bottom reached | strArr: a,b,c | iteration: 2 
=> done, permuts: [["a","b","c"],["a","c","b"],["b","a","c"],["b","c","a"],["c","a","b"],["c","b","a"]] | iteration: 2
```

**Comment by patsul12** [comment] 2016-01-09 21:45
So i tried this on your jsfiddle with the line
`permAlone('zzzzzzzz");`
And it caused my browser to hang and force quit the script, most likely this is because you are trying to print out thousands of log statements on the longer strings and the browser just can't handle that.

So basically what I'm saying is i'm not sure if this is something we could even account for or prevent from happening.

**Comment by SaintPeter** [comment] 2016-01-10 00:43
The many thousands of console.log statements will almost assuredly cause the timeout.  This is not shocking or unexpected.  We cannot protect you from doing something that takes a long amount of time, because of the Halting problem - basically, no one can tell in advance if code will halt or even if it WILL halt at all.

I am closing this issue as it is not a bug with the site, it is a fundamental mathematical problem with computer science.  

Thanks and Happy Coding!

**Closed** 2016-01-10 02:08 UTC
