### ISSUE TITLE
$ is not defined error

### ISSUE THREAD

**Issue by keshavaranjan** [FreeCodeCamp/FreeCodeCamp#3829] opened 2015-10-21 08:17 UTC
Challenge [Waypoint: Say Hello to HTML Elements](http://freecodecamp.com/challenges/waypoint-say-hello-to-html-elements#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
```
![image](https://cloud.githubusercontent.com/assets/15226392/10631226/0f78abf0-77fa-11e5-9f9c-18519d890411.png)

I am not able to move to next challenge, as I am getting $ is not defined error. Is it something related to browser compatibility? I am using Google Chrome(Version 46.0.2490.71 m).

**Comment by ltegman** [comment] 2015-10-21 13:54
Closing as a duplicate of #3818. Before filing a bug next time please try [Searching for Your Issue on Github](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github).

Thanks and happy coding!

**Closed by ltegman** 2015-10-21 13:54 UTC

**Comment by rraabebbit** [comment] 2015-10-23 15:47
I have the same problem...Maybe is about the China's Great Firewall...

**Comment by zhouhaner** [comment] 2015-10-23 15:52
yes,China's Great Firewall is great.
But we have shadowsock

**Comment by ForrestAlfred** [comment] 2015-10-23 15:54
just use VPN,  天行VPN is recommended. free, and easy to use,  especially in mac. 
I 've bought a variety of cheap VPN,  it's a nice choice,  free but even better than those need to be payed.  
PS. I use it on my iPhone, too. And about 3 years.

**Comment by imcaffrey** [comment] 2015-10-24 05:21
The same problem here. You might need Lantern
