### ISSUE TITLE
Link to solutions not showing up on certification page

### ISSUE THREAD

**Issue by elidrissidev** [freeCodeCamp/freeCodeCamp#45533] opened 2022-03-25 22:12 UTC
## Affected page

Example on two of my certificates:
- [Frontend development libraries](https://www.freecodecamp.org/certification/elidrissidev/front-end-development-libraries)
- [Data visualization](https://www.freecodecamp.org/certification/elidrissidev/data-visualization)

## To reproduce

1. Visit the above links

## Expected behavior

I should see a link to the submitted CodePen solution URL on the certificate page.

## Screenshots

![Screenshot from 2022-03-25 23-11-17](https://user-images.githubusercontent.com/67818913/160208949-1be6bf05-ad74-4725-b219-0512ce10807a.png)

## System

- Device: Desktop
- OS: Manjaro Linux
- Browser: Chromium
- Version: Chromium 99.0.4844.82

## Additional context

Tried also on Firefox on my desktop, and Chrome on my Android phone.

**Comment by gikf** [comment] 2022-03-26 10:22
I also can't see links to solutions on the certifications above. I was unable to reproduce this on `main` or `prod-current`.

@elidrissidev can you see solution buttons in the _Certifications_ section of settings?

**Comment by elidrissidev** [comment] 2022-03-26 10:46
@gikf I think I figured it out. It was the _My Timeline_ setting that I had set to "Private". I did go through them yesterday but didn't think that would be the problem.

I suggest renaming it (e.g. "Solutions"), or adding a hint text that explains that it controls solution link visibility. What do you think?

**Comment by gikf** [comment] 2022-03-26 11:07
Looks like you are right, _My Timeline_ setting affects this. I've found this is already tracked as part of another issue - #40403. If you'd have any additional insight feel free to add it there. As for this issue, I'm gonna close it now.

Thank you and happy coding.

**Closed by gikf** 2022-03-26 11:07 UTC
Labels: type: bug, status: waiting triage
