### ISSUE TITLE
Basic JavaScript: Passing Values to Functions with Arguments - just occurring on my machine

### ISSUE THREAD

**Issue by anthonytranDev** [freeCodeCamp/freeCodeCamp#15535] opened 2017-06-26 11:20 UTC
![screenshot 267](https://user-images.githubusercontent.com/26009168/27537040-df0a65b8-5a69-11e7-9454-9f3531fbae6b.png)
Challenge [passing-values-to-functions-with-arguments](https://beta.freecodecamp.com/en/challenges/basic-javascript/passing-values-to-functions-with-arguments) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(a, b){
  console.log(a + b);
}
functionWithArgs(1,2);
functionWithArgs(7,9);
```
It doesn't work after I have refreshed the page
It only lets me pass the challenge if I, open a new tab, then paste in previous URL of challenge
![screenshot 268](https://user-images.githubusercontent.com/26009168/27537115-3c855c52-5a6a-11e7-9cf5-b38cd36e8db7.png)

**Comment by erictleung** [comment] 2017-06-26 21:23
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/15024.

**Closed by erictleung** 2017-06-26 21:23 UTC
