### ISSUE TITLE
Link to CodePen (Build a Personal Portfolio Webpage) - 404 (Page Not Found) Error?

### ISSUE THREAD

**Issue by kimbah** [FreeCodeCamp/FreeCodeCamp#11856] opened 2016-11-29 03:20 UTC
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The link to the CodePen gives a 404 error?

**Comment by erictleung** [comment] 2016-11-29 03:39
@kimbah I can't reproduce. Can you give a screenshot? And is it the entire CodePen page or just parts of the portfolio web page?

**Comment by kimbah** [comment] 2016-11-29 04:03
Hi,

Thanks for quick reply. Think it may be a Chrome issue because I just discovered it does not happen in Firefox (??).

Here’s the screen shot below.

Thanks and regards,

Kim Hughes

**Comment by kimbah** [comment] 2016-11-29 04:12
Sorry quick follow up. In Firefox and Safari link takes you to website itself okay but not the CodePen page (i.e. the Pen itself)??? Chrome takes you to CodePen but has the 404 Page Not Found error.

Thanks and regards,

Kim Hughes

**Comment by Manish-Giri** [comment] 2016-11-29 04:54
@kimbah If I understand it correctly, you want to see the demo app? To do that, see the objective 1 on the left 
> Objective: Build a CodePen.io app that is functionally similar to this: https://codepen.io/FreeCodeCamp/full/YqLyXB/.

Click on that link, that will take you to the demo. By default, all challenge links will take you to the challenge description page on FCC itself, not the demo apps directly.

**Comment by kimbah** [comment] 2016-11-29 05:06
Thanks Eric,


That link still takes me to a 404 page as below:

**Comment by kimbah** [comment] 2016-11-29 05:08
Eric,

I meant to add the link to the CodePen,io takes me here:

**Comment by raisedadead** [comment] 2016-11-29 11:05
@kimbah please use the GitHub interface for adding comments and screenshots. Replies from your email client don't show tge screenshots.

**Comment by kimbah** [comment] 2016-11-29 11:23
No worries will do,

**Comment by kimbah** [comment] 2016-11-29 12:27
![screen shot 2016-11-29 at 1 05 21 pm](https://cloud.githubusercontent.com/assets/15304551/20709692/c51dc998-b671-11e6-8e8f-de6dcc8c5abd.png)
![screen shot 2016-11-29 at 1 07 05 pm](https://cloud.githubusercontent.com/assets/15304551/20709693/c5f770bc-b671-11e6-8f10-1e8fda9bd671.png)

**Comment by raisedadead** [comment] 2016-11-29 12:37
Please open up your [Chrome dev tools](https://developer.chrome.com/devtools) and share the errors that you see on the `Console` tab.

**Comment by kimbah** [comment] 2016-11-30 23:24
Found fix/workaround for the problem - running Chrome in incognito mode fixes it. I tried starting Chrome with the switch "--allow-running-insecure-content" but this did not fix the problem so I'm thinking its maybe a Chrome extension thats causing the problem???

**Comment by raisedadead** [comment] 2016-12-01 06:38
@kimbah yes, most probably. You can start by disabling them one by one to isolate the extension causing the problem. Particularly ad blockers, or theme changing extensions, and VPN extensions.

Closing as not an issue wth the code base. Happy Coding!

**Closed by raisedadead** 2016-12-01 06:38 UTC
Labels: codepen

**Comment by kimbah** [comment] 2016-12-01 10:24
Thanks Eric appreciate the support.

Regards,
Kim

**Comment by Deryckaus** [comment] 2017-03-16 14:31
i get the the problem in both edge and chrome , so im not so sure its a browser issue?
my thumbnails appear with the correct image though???
