### ISSUE TITLE
Compiler error for - str = str.replace(/\//g,""); works fine in Dev tools

### ISSUE THREAD

**Issue by iamgururaj** [FreeCodeCamp/FreeCodeCamp#3763] opened 2015-10-15 19:58 UTC
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase().replace(%2F%5Cs%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C.%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%2C%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C(%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C)%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C%5C%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C%2F%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F-%2Fg%2C%22_%22)%3B%0A%20%20var%20s2%20%3D%20str.split(%22%22).reverse().join(%22%22)%3B%0A%20%20return%20str%3D%3D%3Ds2%3B%0A%7D%0A%0Apalindrome(%22eye%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  str = str.toLowerCase().replace(/\s/g,"");
  str = str.replace(/\./g,"");
  str = str.replace(/,/g,"");
  str = str.replace(/\(/g,"");
  str = str.replace(/\)/g,"");
  str = str.replace(/\\/g,"");
  str = str.replace(/\//g,"");
  str = str.replace(/-/g,"_");
  var s2 = str.split("").reverse().join("");
  return str===s2;
}

palindrome("eye");


```

**Comment by ltegman** [comment] 2015-10-16 01:08
Thanks for the report! I can confirm this regular expression causes a problem in both Chrome and Firefox. Haven't had time to dig into the code and find out why.

**Comment by abhisekp** [comment] 2015-10-17 00:02
Here is screenshot for the error in FCC but works fine in https://repl.it/BRTG/1
![](http://i.imgur.com/Mbyd7pb.png)

**Comment by ankitaggarwal011** [comment] 2015-10-18 10:56
The line of concern in sample code is Line 8 (str = str.replace(/\//g,"");).

So, when one clicks on Run Tests, it calls the binded bonfireExecute method, which in turn passes the editor code to the submit method in the sandBox object. Then, this code is processed before sending to the plugin for evaluation of the code. 

During this processing, the comments ('//') are removed. This is where the problem lies, since the method removeComments is unable to distinguish between the '//' in Line 8 above from JavaScript comments.

Fixing the removeComments function (https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework.js#L769) will fix this issue. It's also unclear why comments are actually removed from the code.

I don't think it would be possible to cover all cases only with the regex without actually parsing the code. This is a good post on this matter (http://james.padolsey.com/javascript/removing-comments-in-javascript/).

It's possible to resolve this issue with improved regex, but it would break again for some other code samples. I think it's best to keep the comments in the code.

I can submit the PR on this with improved regex code and it would solve this problem, but it's not an actual solution. Please let me know what you think. @ltegman @iamgururaj @awesomeaniruddh.

**Comment by abhisekp** [comment] 2015-10-18 11:53
@ankitaggarwal011 I'm also in favor of not removing the comments from code. It's unnecessary.
But the decision lies in the hands of @BerkeleyTrue or @QuincyLarson

**Comment by ankitaggarwal011** [comment] 2015-10-22 05:29
Is there anyone from FreeCodeCamp Team following on this?
@QuincyLarson @BerkeleyTrue @ltegman @awesomeaniruddh. Thanks.

**Comment by BerkeleyTrue** [comment] 2015-10-22 05:47
> Is there anyone from FreeCodeCamp Team following on this?

Yes, I see all.

> It seems unnecessary to remove comments.

Yes. But it was put there for a reason, so removing it without knowing why is not possible. I don't know the reason it was put there in the first place so it cannot be removed.

**Comment by abhisekp** [comment] 2015-10-22 07:02
@BerkeleyTrue maybe @QuincyLarson or @benmcmahon100 could add some light :bulb:

**Comment by ankitaggarwal011** [comment] 2015-10-22 07:11
@BerkeleyTrue, seems like a we have got a deadlock here :)

I found something in PR requests https://github.com/FreeCodeCamp/FreeCodeCamp/pull/1435 which may be helpful, but yes @QuincyLarson would be able help more. Let's wait for him to review this.

Let me know if the goal to solve only this particular issue, I can submit a PR with improved regex, but it may hit a problem again in the future.

**Comment by jlslew** [comment] 2015-10-22 15:32
`removeComments` was added in PR #47, 2nd commit.  Since then, the file has been moved/renamed/merged but the function and its content hasn't been modified.

> Yes. But it was put there for a reason, so removing it without knowing why is not possible. I don't know the reason it was put there in the first place so it cannot be removed.

@terakilobyte should know why...

**Comment by benmcmahon100** [comment] 2015-10-22 18:42
The fact that you cannot remove the last closing comment does not need to be fixed. I put it there to fix another issue. The way you remove a comment is you just remove the opening part before the closing. Please do not further discuss the fact that this is the case as that is not what the issue is about. If the initial poster or someone who can replicate this please post a screenshot of what is meant by "complied error" as js is interpreted not compiled so I'm not sure what the Initial issue means

**Comment by benmcmahon100** [comment] 2015-10-22 18:44
As for the removal of comments in the js by the by the framework this is because of the fact that the code is evaluated as a single line string. i.e. a // comment would of course cause an issue in a piece of code written on a single line.

**Comment by BerkeleyTrue** [comment] 2015-10-22 19:20
@benmcmahon100 to the rescue :+1: 

> fact that the code is evaluated as a single line string.

Unfortunately, this is true because we use `eval` to process your code. This is the same reason why forgetting to add semi-colons at the end of a line will throw errors.

**Comment by benmcmahon100** [comment] 2015-10-22 19:49
Quick potential fix - JSON.stringify it and that should escape the // so that it's safe. (probably)

**Comment by BerkeleyTrue** [comment] 2015-10-22 19:56
Not sure you can eval escaped strings

**Comment by abhisekp** [comment] 2015-10-23 00:34
I wonder how do CodeAcademy solve this issue.

**Comment by ankitaggarwal011** [comment] 2015-10-23 06:40
@benmcmahon100, the issue is that removing single line comments in few cases also removes the genuine '//' used in either regex or strings. 

@benmcmahon100 @BerkeleyTrue @abhisekp, maybe I am missing something, but I couldn't understand how comments would affect the single line of string being evaluated using eval().
Since the code string would have newline characters after single line comment, so this shouldn't cause a problem. Please correct me if I am wrong. Thank you.

Example: 
var code = "console.log(5);//Hello\nconsole.log(10);/*World*/console.log(15);"
eval(code);

Result:
=> 5
=> 10
=> 15

**Comment by abhisekp** [comment] 2015-10-23 07:04
@ankitaggarwal011 exactly my thoughts.

**Comment by benmcmahon100** [comment] 2015-10-23 12:39
It's passed as a script to the webworker and not a string as far as i know which means the single line comment issue still exists. Also you shouldn't use regex for the sake of using regex. Just do String.replace("/",""); and that will work perfectly. If you insist on using regex just remove all non work characters using the word selector.

**Comment by ankitaggarwal011** [comment] 2015-10-23 14:29
@benmcmahon100, I guess there are alternate ways to write code for a particular problem and yes it can be solved by informing op to change his code, but anyhow this is a bug in the current version of the software and I believe it should be improved. 
If this bug is not important at the current stage, we can drop this now, but the bug has to be solved in the future versions or it will reoccur in some other use cases.

Regarding the issue that the code is passed as a script to a webworker, I tried to run this piece of code with comments in my local environment with removeComments function turned off, and the results were coming out absolutely fine. So, I am still not sure what exactly would be the issue with removing comments. Is there a corner case I am missing? Maybe someone else (@abhisekp) can validate this as well. Please correct me if I am wrong anywhere. Thank you.

```js
/* Comment 1 */
function palindrome(str) {
  // Comment 2
  str = str.toLowerCase().replace(/\s/g,"");
  str = str.replace(/\./g,"");
  str = str.replace(/,/g,""); // Comment 3
  str = str.replace(/\(/g,"");
  str = str.replace(/\)/g,"");
  str = str.replace(/\\/g,"");
  str = str.replace(/\//g,""); // Comment 4 /* Comment 5 */
  str = str.replace(/-/g,"_");
  var s2 = str.split("").reverse().join("");
  return str===s2;
}
// Comment 6
palindrome("eye");
```

**Comment by BerkeleyTrue** [comment] 2015-10-23 16:11
@ankitaggarwal011 Can you right some tests to demonstrate that with this framework?

**Comment by ankitaggarwal011** [comment] 2015-10-23 16:55
@BerkeleyTrue, I tried this on my local machine as described above, but I am not sure how to write tests regarding this. 
Is there some guide about writing tests for this framework which you can refer me or some other similar material? I will need some help here. Thanks.

**Comment by BerkeleyTrue** [comment] 2015-10-24 02:44
I'm still wary of removing this code. There might be an edge case that we are not considering which will result in a break somewhere else. @ankitaggarwal011 A better solution for now is to change the RegExp to fit this use case. This is of course is a temporary patch but I have some changes in mind that will make this argument moot.

**Comment by ankitaggarwal011** [comment] 2015-10-24 05:18
@BerkeleyTrue, Even though we have considered almost all cases, I understand that it may still introduce some new bug, but then again that's continuous development. 
However, if you have a solution in your mind that alleviates these conditions and as long as you are going to address this issue in the future versions, I guess that's absolutely fine.
I can submit a PR with improved regex to temporarily fix this problem. It would solve this particular use case and maybe a few more cases :+1:

**Comment by BerkeleyTrue** [comment] 2015-10-24 07:20
Excellent, thank you @ankitaggarwal011

**Comment by ankitaggarwal011** [comment] 2015-10-24 07:26
@BerkeleyTrue, I have created the PR request #3873 to fix this particular use case, it would also be able to solve most of the similar use cases as well. Please review the same. Thanks. :+1:

**Closed** 2015-11-02 06:13 UTC
