### ISSUE TITLE
Longest streak missed one day

### ISSUE THREAD

**Issue by yeonhoo** [freeCodeCamp/freeCodeCamp#15164] opened 2017-06-01 20:22 UTC
#### Issue Description

I completed some challenges in 2017/06/31 and that would give me 5 days of Longest Streak. 
However, "challenge submit history table" shows I haven't done any challenge in 2017/06/31
and "calendar-like history marked as green rounded squared days you've done challenges" shows I did done challenges.

So there is a bug in "history table", how can I claim for my missed one day!? 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2868876/26698689/4d84c0dc-46ed-11e7-92dc-1acc23250aaf.png)

![image](https://cloud.githubusercontent.com/assets/2868876/26698698/60060a36-46ed-11e7-9d1b-93106a56b4e0.png)

![image](https://cloud.githubusercontent.com/assets/2868876/26698706/69d755c4-46ed-11e7-9080-e831f72ae58f.png)

**Comment by raisedadead** [comment] 2017-06-02 14:51
Closing as a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/7925

**Closed by raisedadead** 2017-06-02 14:51 UTC
