### ISSUE TITLE
Missing curly bracket - challenge approval

### ISSUE THREAD

**Issue by megrutter** [FreeCodeCamp/FreeCodeCamp#2738] opened 2015-08-26 13:47 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. 

When completing this challenge, before I had placed the closing curly bracket, the challenge updated to finished. 

![error1](https://cloud.githubusercontent.com/assets/13981222/9495030/6bba7154-4bd7-11e5-80ce-69c89b766c7d.jpg)

**Comment by benschenker** [comment] 2015-09-06 05:51
Hey @megrutter thanks for posting this!

It looks like this is a duplicate of #2084, so keep an eye there for updates.

**Closed by benschenker** 2015-09-06 05:51 UTC
