### ISSUE TITLE
Moving on produces a 502 Bad Gateway error

### ISSUE THREAD

**Issue by kurzninja** [FreeCodeCamp/freecodecamp#1587] opened 2015-08-06 02:13 UTC
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue.

Solving this bonfire and attempting to move on produces a 502 Bad Gateway error.

**Comment by BerkeleyTrue** [comment] 2015-08-06 03:38
Hello @kurzninja 

This is a duplicate of #1386 

Happy Coding!

-Berkosaurus

**Closed by BerkeleyTrue** 2015-08-06 03:38 UTC
