### ISSUE TITLE
Flashing screen when inputting script element

### ISSUE THREAD

**Issue by megrutter** [FreeCodeCamp/FreeCodeCamp#2746] opened 2015-08-26 18:28 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. When typing in the jQuery script element (after typing in the closing script), the screen began to flash back and forth and the "lesson finished" popped up before I finished the lesson. 

![error2](https://cloud.githubusercontent.com/assets/13981222/9502300/7ba7c590-4bfe-11e5-9f07-a06a3374bc09.png)

**Comment by benschenker** [comment] 2015-09-08 04:46
Hey @megrutter thanks for posting!

I am unable to replicate this and I think this may be a duplicate of #2729, which has been fixed.

**Closed by benschenker** 2015-09-08 04:46 UTC
