### ISSUE TITLE
MAP page on beta: No Super Blocks 

### ISSUE THREAD

**Issue by seifsg** [freeCodeCamp/freeCodeCamp#15777] opened 2017-08-19 19:17 UTC
#### Issue Description
Map page for the beta site just shows that text.
Maybe we need a beta status/health page.

#### Browser Information

* Browser Name, Version: Tested on Chrome and FireFox latest
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/6075316/29489522-3edabc5c-8523-11e7-8f97-63d25926e82f.png)

**Comment by vivek-agrawal27** [comment] 2017-08-22 14:57
Please try reloading it several times by pressing ctrl+f5. It happens with the beta version frequently. Currently, it's very unstable.

**Comment by systimotic** [comment] 2017-09-02 19:22
Thanks for reporting!

I can't reproduce this. This may have been resolved, so I'm closing this issue.
If anybody is able to reproduce this, we'll reopen this issue. If you do run into this issue again, please open the console and share any errors here.

Happy coding!

**Closed by systimotic** 2017-09-02 19:22 UTC
