### ISSUE TITLE
Applied Visual Design: Adjust the Height of an Element Using the height Property - correct solution does not pass

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/freeCodeCamp#18045] opened 2018-08-24 02:08 UTC
#### Describe your problem and - if possible - how to reproduce it
When you provide the correct code the test still fails, this is do to the tests passing the true height of the element and not what the CSS is set to. This issue occurs mainly on smaller resolutions because the height of the element is smaller and converted by the browser.

In my Dev Tools it was saying the true height of the element was 24.99px and when I would scroll out the browser converted the true height to 25.01px. I had to find a sweet spot in my zoom level to where it was exactly 25px.

The fix is to change the test to use regex and not use `assert($('h4').css('height') == '25px'`

Additional users having issues: https://forum.freecodecamp.org/t/applied-visual-design-adjust-the-height-of-an-element-using-the-height-property/199328/5

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property/

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: 
* Operating System:

**Comment by TomerPacific** [comment] 2018-08-25 05:10
I would like to take this issue, if anyone doesn't have any objections.

**Comment by nathanhannig** [comment] 2018-08-28 18:35
Go fo it.

I also noticed the same when zoomed in very far on your screen resolution for 
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays

**Comment by prj1999** [comment] 2018-09-17 13:02
@nathanhannig I have used height:25px and text-size-adjust:auto in h4 tag. text-size-adjust basically control text inflation or deflation for smaller resolutions.It worked for all resolutions.Hope it will resolve your issue.
![screenshot 42](https://user-images.githubusercontent.com/38538265/45624411-e7704700-baa7-11e8-825a-8a3b05cfdcd4.png)

**Comment by thecodingaviator** [comment] 2018-11-21 15:51
@nathanhannig / @ezioda004 please close the issue, it's fixed afaik

**Comment by tdreid** [comment] 2018-12-11 23:37
`text-adjust-size: auto;` doesn't get the tests to pass for me.

Also, if that is necessary to pass the challenge shouldn't it be pointed out and explained for the benefit of the learner?

**Comment by lasjorg** [comment] 2019-10-03 17:52
I can't reproduce this bug, I tried zooming and messing with the viewport but nothing makes it trigger, so it is really hard to test.

However, this issue may either be caused by what values are returned by `getComputedStyle`, or simply the fact that it isn't guaranteed to return an integer.

> [getComputedStyle: Notes](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#Notes)
> 
> The values returned by getComputedStyle are [resolved values](https://developer.mozilla.org/en-US/docs/Web/CSS/resolved_value). These are usually the same as CSS 2.1’s [computed values](https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value), but for some older properties like width, height, or padding, they are instead the same as [used values](https://developer.mozilla.org/en-US/docs/Web/CSS/used_value).

And here is the jquery docs on height().

> [jquery: height()](https://api.jquery.com/height/)
> 
> The number returned by dimensions-related APIs, including .height(), may be fractional in some cases. **Code should not assume it is an integer. Also, dimensions may be incorrect when the page is zoomed by the user;** browsers do not expose an API to detect this condition.


Using `offsetHeight` might return a more reliable result as it also rounds (returns a `long`).

> [offsetHeight](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight)
> 
> This property will round the value to an integer.

`document.querySelector('h4').offsetHeight === 25`

Another option would be to do the rounding in the test or remove the CSS style test and just have the regex.

**Comment by RandellDawson** [comment] 2019-11-01 21:10
@lasjorg Appears the fix did not work for everyone (even those using Chrome).

See this [latest forum topic](https://www.freecodecamp.org/forum/t/is-there-a-glitch-in-this-challenge/325152/35) where at least two people are still reporting issues.  You can see that for some at least one user, the `document.querySelector('h4').offsetHeight` returns `26` even though the window.getComputedStyle returned `24.9844px`.

**Comment by lasjorg** [comment] 2019-11-02 17:34
I see different numbers at diffrent zoom levels in Chrome as well. At zoom level 90%, 67%, and 50% I get `26`, at 33% I get, `24`.

I believe the fix might be to use `scrollHeight` instead.

@RandellDawson  I can't login to the forum at all because of the login issues. So if you can test this for me in the forum thread I'd really appreciate it.

**Comment by lasjorg** [comment] 2019-11-02 19:49
**Update:**

Using `scrollHeight` at 50% zoom I still get 26 and at 33% I get, `24`. Not sure how likely it is a user will zoom out that far but we may have to use `.getBoundingClientRect().height` and do the rounding ourselves.

This works for me on all zoom levels:
`Math.round(document.querySelector('h4').getBoundingClientRect().height) === 25`

The problem is, I'm not affected by the initial bug using offsetHeight was supposed to fix. So it's impossible for me to really test this. Worse case, I guess we have to use a regex only.

**Comment by RandellDawson** [comment] 2019-11-07 17:50
@lasjorg How close are we to a cross-browser way to test this?  If it is getting too complicated, maybe we should use regex against the code as a fix for now and keep the discussion going in this issue.

**Comment by lasjorg** [comment] 2019-11-07 19:16
@RandellDawson The PRs for the [height](https://github.com/freeCodeCamp/freeCodeCamp/pull/37687) and [width](https://github.com/freeCodeCamp/freeCodeCamp/pull/37688) challenges should fix it. I also added a note to the challenges about the zoom.

As said in the PR for the height challenge I don't have any confirmation for that one and because I still can not login to the forum I have been unable to get a confirmation. I was planning to ask [the same user](https://www.freecodecamp.org/forum/t/is-there-a-glitch-in-this-challenge/325152/62) that helped with the other challenge. But I believe both should work regardless of browser zoom.

**Comment by lasjorg** [comment] 2019-11-07 21:33
BTW, both challenge tests already have a regex in place. So if we do just want a regex all we need to do is remove the first part of the conditional assert. Please let me know in the PRs if that is a preferred solution.

How much work is it to push updates now? It's been made much easier correct?

**Comment by moT01** [comment] 2019-11-13 13:33
I vote to just regex it - When we do that rounding, it makes room for invalid input; maybe something like `height: 24.9px` would pass.

**Comment by lasjorg** [comment] 2019-11-14 01:30
I think just having a regex is the safer choice as well. And considering the test already have a regex it makes the first part of the conditional assert a bit pointless anyway.

Will update the two PRs (height/width) to just use the regex already in place.

**Comment by ojeytonwilliams** [comment] 2019-11-14 08:11
> How much work is it to push updates now? It's been made much easier correct?

@lasjorg To production?  Yeah, it is. Mrugesh has made it very streamlined.  The [devops docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/devops.md) cover it.

**Closed** 2019-11-26 03:40 UTC
Labels: scope: curriculum
