### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by ShaklinSyed** [FreeCodeCamp/freecodecamp#607] opened 2015-05-27 02:42 UTC
Gives an error while trying to add checked to first radio and checkbox
Syntax error, unrecognized expression
Syntax error, unrecognized expression

code for form
```
<form action="/submit-cat-photo">
  <label><input type='radio' name='indoor-outdoor' checked> Indoor</label>
  <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
  <br>
  <label><input type='checkbox' name='personality' checked> Loving</label>
  <label><input type='checkbox' name='personality'> Lazy</label>
  <label><input type='checkbox' name='personality'> Crazy</label>
  <br>
  <input type='text' placeholder='cat photo URL' required>
  <button type='submit'>Submit</button>
</form>
```

**Comment by gigantor84** [comment] 2015-05-27 05:46
Same issue:
<form action="/submit-cat-photo">
  <label><input type='radio' name='indoor-outdoor' checked > Indoor</label>
  <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
  <br>
  <label><input type='checkbox' name='personality' checked > Loving</label>
  <label><input type='checkbox' name='personality'> Lazy</label>
  <label><input type='checkbox' name='personality'> Crazy</label>
  <br>
  <input type='text' placeholder='cat photo URL' required>
  <button type='submit'>Submit</button>
</form>

but I get 2 syntax errors.

**Comment by terakilobyte** [comment] 2015-05-27 14:16
Thanks for the report. Closing this as a duplicate of #585 as it all stems from the same problem.

**Closed** 2015-05-27 14:16 UTC
