### ISSUE TITLE
style issue

### ISSUE THREAD

**Issue by catfish68** [FreeCodeCamp/FreeCodeCamp#4824] opened 2015-12-01 04:01 UTC
Hello i have a style issue,  I have it as 
<style>
 h2 {color: blue;}
</style> 

The system recognizes everything but the closing style tag

**Comment by ltegman** [comment] 2015-12-01 04:44
Please give us more details, like what challenge you are on.

**Comment by ltegman** [comment] 2015-12-01 05:27
Closing as a duplicate of #4833. Please continue further discussion in that thread.

Thanks and happy coding!

**Closed by ltegman** 2015-12-01 05:27 UTC
