### ISSUE TITLE
Unable to submit work for the "Simon" Zipline

### ISSUE THREAD

**Issue by daniel-chung** [FreeCodeCamp/FreeCodeCamp#4253] opened 2015-11-09 01:24 UTC
Hello,

I'm having difficulty submitting work for the "Simon" zipline. In fact, I'm unable to click on the "I've completed this challenge" and the "Bug" buttons. While the pop-up window comes up when I press ctrl+enter, I'm unable to submit the form.

Thing's I've tried:
* Using 3 different browsers (Chrome, Firefox, Safari)
* Doing a hard refresh
* Clearing local storage

Thanks and please let me know if you need more info!

(sorry if this is a repost, but my first issue somehow got lost)

**Comment by george-stepanek** [comment] 2015-11-09 01:42
Hi, I'm seeing this issue too; it appears to be on all of the Ziplines and Basejumps.

I've tried Chrome and Edge on Windows 10. It was working fine yesterday, but not today.

**Comment by ltegman** [comment] 2015-11-09 02:48
Thanks for the heads up! This is caused by a recent commit that included a large refactor of our codebase. I've put in a patch that will hopefully be accepted soon.

**Comment by SaintPeter** [comment] 2015-11-09 20:00
This should be fixed now.

**Closed by SaintPeter** 2015-11-09 20:00 UTC
Labels: QA

**Comment by daniel-chung** [comment] 2015-11-10 02:26
Awesome. Thanks all for your help!
