### ISSUE TITLE
Next Challenge Error HTML img to Arrays

### ISSUE THREAD

**Issue by Eiseldora** [FreeCodeCamp/FreeCodeCamp#1901] opened 2015-08-17 19:35 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
When I complete the challenge it takes me to this challenge: http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift

**Comment by ahstro** [comment] 2015-08-22 20:58
This is a duplicate of #1892

**Comment by BerkeleyTrue** [comment] 2015-08-23 00:27
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Closed by BerkeleyTrue** 2015-08-23 00:27 UTC
