### ISSUE TITLE
The preview iframe for challenges shows duplicate code

### ISSUE THREAD

**Issue by t73biz** [FreeCodeCamp/FreeCodeCamp#4276] opened 2015-11-09 16:37 UTC
The preview iframe on the right of the code window shows duplicate code.
![preview-iframe](https://cloud.githubusercontent.com/assets/169922/11039473/73866be6-86cd-11e5-960d-feba8376fd30.png)

When I checked the source code for the iframe, I did see the code duplicated twice as well. 
This occurs on many, if not all challenges that I have taken so far. A refresh of the screen seems to temporarily resolve the issue at times, until I go to the next challenge. At which time, the code duplicates again.

Using Firefox 41.0.1 on Linux Mint 17

**Comment by ltegman** [comment] 2015-11-09 16:46
Thanks for the report! I'm closing this as a duplicate of #2706. Please continue any discussion there.

Thanks and happy coding!

**Closed by ltegman** 2015-11-09 16:46 UTC
