### ISSUE TITLE
Creating a Freecode Camp Forum Account

### ISSUE THREAD

**Issue by Yettymaer** [freeCodeCamp/freeCodeCamp#37780] opened 2019-11-19 14:43 UTC
<img width="580" alt="Screenshot 2019-11-19 at 14 39 48" src="https://user-images.githubusercontent.com/53909341/69155902-7dec2e00-0ada-11ea-990a-677aee83f0cf.png">

Apologies if this has been reported but the issue was last updated 29 days ago and wasn't sure if it has been fixed. I have been attempting to create an account on the Forum for the past 2 weeks and always get the message 'We are facing a known issue'. As a result, i am unable to ask questions or seek help. Is there a temporary fix to this, please? Thanks

**Comment by Mada75** [comment] 2019-11-19 18:23
I've not been able to login either, the [previous](https://github.com/freeCodeCamp/freeCodeCamp/issues/37452) report is still open so I assume they're aware and haven't been able to fix it yet

**Comment by raisedadead** [comment] 2019-11-19 21:14
Duplicate of #37452

**Closed by raisedadead** 2019-11-19 21:14 UTC
Labels: type: bug
