### ISSUE TITLE
Add night mode toggle for signed out users

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40870] opened 2021-02-02 00:54 UTC
The night mode toggle [added to the nav menu here](https://github.com/freeCodeCamp/freeCodeCamp/pull/40823), is only functional for authenticated users. It says, "Sign in to change theme." if you are logged out. We should try and make night mode available for everyone. It's kind of tricky since it's part of the user object in redux - but there's a way.

**Comment by aashiqahmed98** [comment] 2021-02-02 06:49
saving the display mode in localstorage,makes the gotcha!

**Comment by ahmadabdolsaheb** [comment] 2021-02-02 11:15
@moT01, it this a duplicate of #36819?

**Closed** 2021-02-02 13:52 UTC
Labels: type: feature request
