### ISSUE TITLE
Aftr execution task "Clone an Element Using jQuer" there is an extra button

### ISSUE THREAD

**Issue by TimKolo** [FreeCodeCamp/FreeCodeCamp#6458] opened 2016-01-26 07:14 UTC
steps:
- perform a task
- click on the button "run tests"

actual result: there are 3 buttons "target5"
Expected Result: there are 2 buttons "target5"

**Comment by erictleung** [comment] 2016-01-26 07:18
Looks like a duplicate of #5072.

**Closed** 2016-01-26 07:21 UTC
