### ISSUE TITLE
Drum Machine Demo Project : ".drum-pad"  elements moves from the position  while clicking on "E" and "D" named drum-pad elements

### ISSUE THREAD

**Issue by YagneshP** [freeCodeCamp/freeCodeCamp#40976] opened 2021-02-07 22:04 UTC
**Describe your problem and how to reproduce it:**
In the drum machine example project while clicking on element "E" and element "D" the positions of the other elements are getting changed from their original position

**Add a Link to the page with the problem:**
[Codepen Link of Freecodecamp Drum Machine Project](https://codepen.io/freeCodeCamp/full/MJyNMd)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 88.0.4324.146
* Operating System: Window10 64-bit
![drum-machine](https://user-images.githubusercontent.com/29221654/107160805-81c9d180-6966-11eb-9878-a6e11969c6a4.gif)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ShaunSHamilton** [comment] 2021-02-07 22:34
Thank you, for taking the time to open this.

I am unable to reproduce this in the same browser. Do you have any browser extensions enabled with access to the site?

**Comment by YagneshP** [comment] 2021-02-07 23:19
Yes! I have

**Comment by RandellDawson** [comment] 2021-02-08 05:01
@YagneshP Try disabling your browser extensions temporarily while viewing the Demo project and let us know if that fixes the issue.

**Comment by raisedadead** [comment] 2021-02-08 07:54
As a quick note, you can also try opening the challenge in an incognito window (which disables all extensions by default).

**Comment by YagneshP** [comment] 2021-02-08 16:04
@RandellDawson @ShaunSHamilton Yes, issue is fixed after disabling extension. Can you please give information why it was happening?

**Comment by ShaunSHamilton** [comment] 2021-02-08 16:16
@YagneshP Glad to hear the issue is fixed on your side.

Typically, browser extensions (e.g. ad-blockers) work by injecting the current webpage with its own JavaScript. This script can do almost anything on the page including altering the styling of elements - which is why an adblocker is able to _"hide"_ ads on the page.

Unfortunately, sometimes other content on a webpage is affected, even when it should not be.

freeCodeCamp highly recommends disabling all browser extensions, whilst you are on the related platforms. Remember, freeCodeCamp does not have ads anyway. Whilst CodePen is not a part of freeCodeCamp, it is important to keep in the back of your mind that browser extensions can cause unexpected behaviour.

Hope this clarifies.

---

As this issue is outwith freeCodeCamp, I am closing it. Feel free to open a topic on the [forum](https://forum.freecodecamp.org/) if you have any questions.

**Closed by ShaunSHamilton** 2021-02-08 16:16 UTC
Labels: scope: learn, status: blocked
