### ISSUE TITLE
ES6 import lessons specify "same directory," but including ./ fails tests

### ISSUE THREAD

**Issue by VirtuaBoza** [freeCodeCamp/freeCodeCamp#17886] opened 2018-07-15 21:24 UTC
#### Describe your problem and - if possible - how to reproduce it
In the ES6 lessons "**Understand the Differences Between import and require**" and "**Use * to Import Everything from a File**," you're asked to import from a file in the same directory. As noted in the former, "In most cases, the file path requires a ./ before it; otherwise, node will look in the node_modules directory first trying to load it as a dependency."
However, if you include the ./ (specifying that node should look in the same directory), you fail the tests.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/understand-the-differences-between-import-and-require
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10 Education (64-bit)

**Comment by thecodingaviator** [comment] 2018-10-18 09:49
@raisedadead / @Bouncey can you have a look? I tried this and without a `./` it's fine but with `./` I get `Cannot read property 'capitalizeString' of undefined` . I think the problem is that our code is testing for it in the same directory, but it's in node_modules so it does not work

**Comment by thecodingaviator** [comment] 2018-10-18 09:50
See this for more info https://github.com/freeCodeCamp/curriculum/issues/95

**Comment by ezioda004** [comment] 2018-10-23 16:57
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17436, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding.

**Closed by ezioda004** 2018-10-23 16:57 UTC
