### ISSUE TITLE
String.prototype.charCodeAt() link is invalid

### ISSUE THREAD

**Issue by DanRom624** [FreeCodeCamp/FreeCodeCamp#8402] opened 2016-05-02 20:15 UTC
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  
  return str;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

The issue is not within the code, actually... It is on the challenge's explanation page.
It seems that the link to "String.charCodeAt()" is broken.

I think it should be the following:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

Stay well
DR

**Comment by LouisDell** [comment] 2016-05-02 21:07
I would like to fix this as an intro to collaborating on open source projects. I'll follow the contributor's guide.

**Comment by LouisDell** [comment] 2016-05-02 21:28
Can I just fix the link on GitHub without going through the all the tasks laid out in the guide?

**Comment by sludge256** [comment] 2016-05-02 22:31
@LouisDell I think that should be fine as long as you're aware of the potential pitfalls.

>Method 2: Editing via the GitHub Interface

>Note: Editing via the GitHub Interface is not recommended, since it is not possible to update your fork via GitHub's interface without deleting and recreating your fork.

>Read the Wiki article for further information

**Comment by vicrec** [comment] 2016-05-02 22:32
> String.charCodeAt() link is Broken!

Same here.

Have a nice day 
Vic

**Comment by erictleung** [comment] 2016-05-03 03:21
Are you guys still having this issue? I just checked and couldn't reproduce the results. Some changes were recently pushed up to the live site so maybe things were fixed with it.

**Comment by raisedadead** [comment] 2016-05-03 06:22
Yup. Can't Reproduce it Either.

**Comment by raisedadead** [comment] 2016-05-03 06:26
@theflametrooper : lol you had me confused with title change.

Refer original comment
> String.charCodeAt() link is Broken!
Please adjust to correct title. Simply MDN link broken should be fine.

@vicrec @DanRom624 
Most probably you have a stale copy of the page.
Try the common troubleshooting steps
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by sludge256** [comment] 2016-05-03 06:55
I think this fixed it when the new master was pushed to production.
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8163

**Comment by theflametrooper** [comment] 2016-05-03 07:17
@sludge256 is correct!

**Closed** 2016-05-03 07:18 UTC
Labels: resolved
