### ISSUE TITLE
Reduce size of website

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#37742] opened 2019-11-12 06:29 UTC
The pages that we are working with right now are very heavy on slow internet connections with ~12MB of resources being loaded.

For people with good internet, this works but in places where the internet is not so fast, this is a huge problem.

![image](https://user-images.githubusercontent.com/34807532/68647266-78736e80-0543-11ea-88a6-795295defa43.png)

![image](https://user-images.githubusercontent.com/34807532/68647361-b83a5600-0543-11ea-8ee8-6e46884a7526.png)

![image](https://user-images.githubusercontent.com/34807532/68647394-c8523580-0543-11ea-87cb-12347f7304ab.png)

**Comment by ojeytonwilliams** [comment] 2019-11-12 09:10
Agreed.  I think the main thing we need is better [code splitting](https://www.gatsbyjs.org/docs/how-code-splitting-works/) since about 1/3 to 1/2 (depending on the page) of the download is the 1.1MB `app` file.  That's common to each page and I doubt it needs to be that big.

**Comment by Josef37** [comment] 2019-11-25 11:59
I'm trying to start contributing a little to this great project. :)

So I did some analysis on the bundle sizes.
I installed the `gatsby-plugin-webpack-bundle-analyzer` on the client and configured it to output webpack stats in `gatsby-config.json`
```
{
  resolve: 'gatsby-plugin-webpack-bundle-analyzer',
  options: {
    generateStatsFile: true,
    production: true
  }
}
```
Then I ran the analyzer by 
```
cd ./client
npx webpack-bundle-analyzer ./public/stats.json
```
These are the stats file and a screenshot of the analyzer (so you can run the command yourself without building the client)

[stats.zip](https://github.com/freeCodeCamp/freeCodeCamp/files/3886417/stats.zip)

![webpack-bundle-analyzer](https://user-images.githubusercontent.com/14334266/69537962-7b2d8500-0f81-11ea-88d6-9bc5d2e5abae.PNG)

I have to get familiar with the project, before I can figure out how to improve this. But maybe you can help me / or improve it yourself with the analysis. 

PS: I guess at least for the landing page some of the babel utilities aren't required (the standalone itself is 375 KB gzipped, which I think is just used for live coding).

**Comment by ojeytonwilliams** [comment] 2019-11-25 12:40
@Josef37 I didn't know that tool existed, it's really neat!  It looks like it will be invaluable when prioritising which code needs to be split.

> PS: I guess at least for the landing page some of the babel utilities aren't required (the standalone itself is 375 KB gzipped, which I think is just used for live coding).

Yep, that's my understanding too.  `babel/standalone` shouldn't be getting into the main app, since it's just used in the challenges.

**Comment by ojeytonwilliams** [comment] 2020-01-15 15:23
So, dynamically loading `@babel/standalone` cuts the main app from 6,473,158 bytes to 1,339,200 which is pretty great.  However, it increases the size of the total download from 4 MB to 4.3, on the challenge pages.  My guess is there's some code that was being shared that's now duplicated in the split bundles.

@raisedadead is this a good compromise?  It's slightly slower if someone goes directly to a page, but it'll seem faster if they navigate from elsewhere in learn.

Also, I discovered that the editor relies on `typescript.worker` and that that is not minified.  It's the biggest file, at 1.5 MB, so if we can convince webpack to minify it, that should save a lot.

**Comment by raisedadead** [comment] 2020-01-15 16:16
Yeah. Why not? I think that's a fair compromise. Not sure about the worker, do we have the ability to propose a PR? If not let's start a thread with them

**Comment by ojeytonwilliams** [comment] 2020-01-15 18:35
I'm not yet sure where the problem is, but I'll submit an issue once I can reproduce it in a test site.

**Comment by ahmadabdolsaheb** [comment] 2021-04-17 13:01
Here is current breakdown for learn.
<img width="1440" alt="Screen Shot 2021-04-17 at 3 53 07 PM" src="https://user-images.githubusercontent.com/4591597/115114032-d6588100-9f95-11eb-9c22-4ee1a0247da6.png">

My main concern in the app chunk at the moment which is the largest script that loads on landing page.

<img width="667" alt="Screen Shot 2021-04-17 at 3 53 54 PM" src="https://user-images.githubusercontent.com/4591597/115114078-1a4b8600-9f96-11eb-9b8d-6a5ceee15c0b.png">

**Comment by ahmadabdolsaheb** [comment] 2021-04-20 06:21
Here seem to be the three main issues to fix regarding this chunk.
1. Some modules are imported as whole which means treeshaking is not happening properly: 
     - [ ] React-boostrap: some unused components are being imported. 
     - [ ] Lodash: `babel-plugin-transform-imports` does not work, we could use `lodash-es` to remove unused methods.
     - [ ] rxjs/_ems5: dependency of redux-observable, rxjs, redux-saga. ( investigation needed)
     - [ ] elliptic: dependency of an encryption library. (investigation needed).
2. Some modules are used on specific pages and should be imported dynamically.
     - [ ] react-calendar-heatmap
     - [ ] two of the unused locals should be removed. shouldn't this be SSRed?
3. Some modules are duplicates:
    - [ ] bn.js
    * etc.
4. Some modules are removable:
   - [ ] redux-observable
   - [ ] rxjs
   * etc.

**Comment by ahmadabdolsaheb** [comment] 2021-04-20 11:32
crypto-browserify and its dependencies seems to be a large part of the chunk.

**Comment by ahmadabdolsaheb** [comment] 2021-04-21 02:20
@raisedadead, the projects builds fine without them. I know some of them are mentioned in the Gatsby v2 to v3 migration guide, but there is a change that we don't need them.

**Comment by ojeytonwilliams** [comment] 2021-04-21 07:24
It's worth checking if we still need them, but at the time I added them they were all necessary.

**Comment by ojeytonwilliams** [comment] 2021-05-28 14:32
One part of the main app bundle is Gatsby itself.  This seems unavoidable if we want to support a wide range of browsers. Reason being it's composed of core-js polyfills that're needed by some browsers.

We can reduce the bundle size a bit if we target fewer or more modern browsers, but obviously that comes with a chance that we exclude people. For reference it goes from 512.67kb -> 486.93kb if we restrict it to just the latest version of Chrome for Android, so it's only a small part of the current bundle, but this includes a few large packages that we don't need: https://github.com/freeCodeCamp/freeCodeCamp/pull/42242, https://github.com/freeCodeCamp/freeCodeCamp/pull/41944

@ahmadabdolsaheb pointed out that we might be able to ship both compatible, polyfilled bundles AND ones with only modern JavaScript, as discussed in https://web.dev/publish-modern-javascript/ 

However, looking at https://github.com/gatsbyjs/gatsby/discussions/2114 it seems like this is still a WIP.  Also, Next experimented with it, but removed it here: https://github.com/vercel/next.js/pull/19275

**Comment by raisedadead** [comment] 2022-03-22 19:01
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.

**Closed by raisedadead** 2022-03-22 19:01 UTC
Labels: help wanted, other: decayed, type: feature request
