### ISSUE TITLE
TyperError: indexOf() is not a function

### ISSUE THREAD

**Issue by D3V4N5H** [freeCodeCamp/freeCodeCamp#15111] opened 2017-05-29 10:46 UTC
Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20var%20a%3Darr%5B0%5D.toLowerCase%3B%0A%20%20var%20b%3Darr%5B1%5D.toLowerCase%3B%0A%20%20%0A%20%20var%20f%3D0%2Ci%3D0%2Cx%3D0%2Cy%3D0%3B%0A%20%20while(f%3E-1)%7B%0A%20%20%20%20f%3Db.indexOf(a%5Bi%5D)%3Bi%2B%2B%3B%0A%20%20%7D%0A%20%20if(f%3C0)x%3D1%3B%0A%20%20%0A%20%20i%3D0%3Bf%3D0%3B%0A%20%20while(f%3E-1)%7B%0A%20%20%20%20f%3Da.indexOf(b%5Bi%5D)%3Bi%2B%2B%3B%0A%20%20%7D%0A%20%20if(f%3C0)y%3D1%3B%0A%20%20%0A%20%20if(x%3D%3D1%7C%7Cy%3D%3D1)%20return%20true%3B%0A%20%20else%20return%20false%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function mutation(arr) {
  var a=arr[0].toLowerCase;
  var b=arr[1].toLowerCase;
  
  var f=0,i=0,x=0,y=0;
  while(f>-1){
    f=b.indexOf(a[i]);i++;
  }
  if(f<0)x=1;
  
  i=0;f=0;
  while(f>-1){
    f=a.indexOf(b[i]);i++;
  }
  if(f<0)y=1;
  
  if(x==1||y==1) return true;
  else return false;
}

mutation(["hello", "hey"]);
```

**Comment by rjkmurray** [comment] 2017-05-29 10:53
It was supposed to be merged with the master but I became the master and like some things it is a work in progress.  I need to section of what will work with  what 


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Devansh Trivedi <notifications@github.com> Date: 2017-05-29  8:16 AM  (GMT-03:30) To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [freeCodeCamp/freeCodeCamp] TyperError: indexOf() is not a function (#15111) 
Challenge Mutations has an issue.

User Agent is: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36.

Please describe how to reproduce this issue, and include links to screenshots if possible.
My code:
function mutation(arr) {
  var a=arr[0].toLowerCase;
  var b=arr[1].toLowerCase;
  
  var f=0,i=0,x=0,y=0;
  while(f>-1){
    f=b.indexOf(a[i]);i++;
  }
  if(f<0)x=1;
  
  i=0;f=0;
  while(f>-1){
    f=a.indexOf(b[i]);i++;
  }
  if(f<0)y=1;
  
  if(x==1||y==1) return true;
  else return false;
}

mutation(["hello", "hey"]);

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"TyperError: indexOf() is not a function (#15111)"}],"action":{"name":"View Issue","url":"https://github.com/freeCodeCamp/freeCodeCamp/issues/15111"}}}

**Comment by xRahul** [comment] 2017-05-29 12:00
@D3V4N5H Can you explain what the issue is?
In your code, you're assigning the function `toLowerCase` to `var a`-
```
var a=arr[0].toLowerCase;
```

whereas, you should be using the function-
```
var a=arr[0].toLowerCase();
```

Is there a different error?

**Comment by dhcodes** [comment] 2017-05-30 19:15
@D3V4N5H there is an error in your code. @xRahul is correct that your issue is cause by not having `()` on your methods. Please consider asking for help in the HelpJavascript room on Gitter.

**Closed by dhcodes** 2017-05-30 19:15 UTC
