### ISSUE TITLE
Javascript algorithms and data structures: "You should use const to declare a shifted variable."

### ISSUE THREAD

**Issue by agibson1083** [freeCodeCamp/freeCodeCamp#55740] opened 2024-08-04 09:53 UTC
### Describe the Issue

Hi, there are a few occasions on the introductory JavaScript course where you have to declare a variable. But what the course actually wants is for you to declare a constant (const). The instructions are:

> Directly below your numbers array, **declare a shifted variable** and assign it the result of calling .shift() on the numbers array. On the next line, log the shifted variable to the console.

but if you use `let` or `var` you get the error:

> You should use const to declare a shifted variable.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-108

### Your code

```
const numbers = [1, 2, 3];
let shifted = numbers.shift()
console.log(shifted)

const unshifted = numbers.unshift(5);
console.log(unshifted);


```

### Expected behavior

> // running tests
// tests completed
// console output
1
3
[ 5, 2, 3 ]

### System

- Device: Laptop
- OS: Debian 12
- Browser: Firefox
- Version: 115.13.0esr

**Comment by Alforoan** [comment] 2024-08-05 15:03
May I take this please?

**Comment by Lewis-00** [comment] 2024-08-05 21:12
> May I take this please?

Have you started? Or I can take care of it

**Comment by Alforoan** [comment] 2024-08-05 21:35
> > May I take this please?
> 
> Have you started? Or I can take care of it

You can take care of other issues. Thanks

**Comment by gikf** [comment] 2024-08-06 08:17
Hey @Alforoan, @Lewis-00

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create pull request. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by naomi-lgbt** [comment] 2024-08-19 19:36
Straight from MDN:

> The const declaration declares block-scoped local variables. The value of a constant can't be changed through reassignment using the [assignment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment), but if a constant is an [object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#objects), its properties can be added, updated, or removed.

They may not be reassignable, but they *are* still variables. Nothing to fix here, IMHO.

**Closed by naomi-lgbt** 2024-08-19 19:36 UTC
Labels: type: bug, scope: curriculum, status: waiting triage, new javascript course
