### ISSUE TITLE
Typo on Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by leftynaut** [FreeCodeCamp/FreeCodeCamp#2614] opened 2015-08-24 04:58 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue.

Typo - "You should have multiplied the result of Math.random but 10 to make it a number that\'s greater then zero');"

Correction - "You should have multiplied the result of Math.random by 10 to make it a number that\'s greater then zero');"

**Comment by michael-krebs** [comment] 2015-08-24 07:02
Thanks for reporting, but this is a duplicate of #2592 and has since been fixed

**Closed** 2015-08-25 23:13 UTC
