### ISSUE TITLE
Erroneous "your code should not have any divs" error on Firefox Developer Edition

### ISSUE THREAD

**Issue by geochronology** [freeCodeCamp/freeCodeCamp#41854] opened 2021-04-19 00:19 UTC
**Describe your problem and how to reproduce it:**
When doing the `nav`, `header`, and `figure` coding challenges on Firefox Developer Edition, I get an error "Your code should not have any divs" even when there are not any divs

**Add a Link to the page with the problem:**
* https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-nav-landmark
* https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/improve-chart-accessibility-with-the-figure-element

**Tell us about your browser and operating system:**
* Browser Name: Firefox Developer Edition 
* Browser Version: 88.0b9
* Operating System: macOS Big Sur 11.2.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="939" alt="Screen Shot 2021-04-18 at 5 19 33 PM" src="https://user-images.githubusercontent.com/54387644/115166902-420c1e00-a06a-11eb-8feb-79a65ca773fd.png">

**Comment by ieahleen** [comment] 2021-04-19 07:20
Please try deactivating your browser extensions

**Comment by ahmadabdolsaheb** [comment] 2021-04-22 10:48
I was not able to reproduce this. Could you try after deactivating your browser extensions?

**Comment by lasjorg** [comment] 2021-04-23 14:05
I have seen this reported before ([forum search](https://forum.freecodecamp.org/search?q=Your%20code%20should%20not%20have%20any%20div%20tags)) but I'm not really sure what the issue is. It seems to affect all the challenges that start out with a `div` that needs to be changed to a semantic element. Resetting the challenge and copy-pasting the code usually fixes it. Or switching browsers.

The tests are just using a simple jQuery selector and checking the `length` property (`assert($('div').length == 0)`). Switching to a native selector might help mitigate the issue but that's just speculation.

**Comment by raisedadead** [comment] 2021-04-26 11:56
Hi @geochronology 

Can you confirm the issue is reproducible only on Firefox developer edition and other browsers on your machine are fine? We would like to identify if and why the behavior would be different.

Thanks.

**Comment by lasjorg** [comment] 2021-04-26 18:09
I don't think it is browser-specific, but I can't reproduce it so it's pretty hard to test. I'm guessing either the output in the test frame is stale somehow, or the jQuery selector for some reason fails.

**Comment by raisedadead** [comment] 2021-04-26 19:02
Cool. I am going to close this for now. 

@geochronology if you are still facing this, please confirm after you have tried this on the same browser with the extensions disabled. The easiest way is to use a private/incognito window.

We can re-open this if confirmed a bug.

**Closed by raisedadead** 2021-04-26 19:02 UTC
Labels: scope: curriculum, status: waiting triage
