### ISSUE TITLE
Waypoint: Make Unique Objects by Passing Parameters to our Constructor

### ISSUE THREAD

**Issue by genesisjoec** [FreeCodeCamp/FreeCodeCamp#4917] opened 2015-12-02 17:43 UTC
I'm getting the error: "Error plug in failed to initialize // Testing Challenge "

```
var Car = function() {
  //Change this constructor
  this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};

//Try it out here
var myCar = new Car(3,2,1);

// Only change code above this line

(function() {return JSON.stringify(myCar);})();
```

**Comment by ltegman** [comment] 2015-12-02 17:47
Closing as a duplicate of #4882. We have a PR in the works that should solve this.

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 17:47 UTC
