### ISSUE TITLE
Missing double quote in Build a Telephone Number Validator

### ISSUE THREAD

**Issue by kreid415** [freeCodeCamp/freeCodeCamp#55269] opened 2024-06-21 17:45 UTC
https://github.com/freeCodeCamp/freeCodeCamp/blob/68158893aa03c43cbcfda263d1e2d1c3e1d821f8/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-telephone-number-validator-project/build-a-telephone-number-validator.md?plain=1#L30

**Comment by sureshkrishnan-v** [comment] 2024-06-21 18:00
hey, I am new to open source I am willing to contribute can I handle this issue please and can anyone guide me on how to contribute?

**Comment by ilenia-magoni** [comment] 2024-06-21 18:01
Is this issue present also in the English file? the other languages files can't be touched directly

**Comment by ilenia-magoni** [comment] 2024-06-21 18:02
I've edited the first post to link to the English file where the issue is also present.

Also that is a quote, not a parenthesis

**Comment by sureshkrishnan-v** [comment] 2024-06-21 18:04
hey, I am new to open source I am willing to contribute can I handle this issue please and can anyone guide me on how to contribute?

**Comment by ilenia-magoni** [comment] 2024-06-21 18:04
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-telephone-number-validator-project/build-a-telephone-number-validator.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by gagan-bhullar-tech** [comment] 2024-06-21 18:35
can i work on this

**Comment by sureshkrishnan-v** [comment] 2024-06-21 18:47
I have sent the PR mam kindly review it, please @ilenia-magoni

**Comment by gagan-bhullar-tech** [comment] 2024-06-21 18:53
Created a PR. Please review.

**Comment by sureshkrishnan-v** [comment] 2024-06-21 19:05
fix : Missing double quote in Build a Telephone Number Validator (https://github.com/freeCodeCamp/freeCodeCamp/pull/55270)

**Comment by sureshkrishnan-v** [comment] 2024-06-21 19:06
fix: Missing double quote in Build a Telephone Number Validator #55270

**Comment by sureshkrishnan-v** [comment] 2024-06-21 19:17
#55270  fix:Missing double quote in Build a Telephone Number Validator

**Closed** 2024-06-21 19:24 UTC
Labels: type: bug, scope: curriculum, first timers only, new javascript course
