### ISSUE TITLE
Anonymous Message Board -  fcc test suite for the project passes without requiring any api implementation

### ISSUE THREAD

**Issue by pmayur** [freeCodeCamp/freeCodeCamp#40415] opened 2020-12-10 19:41 UTC
**Describe your problem and how to reproduce it:**
Implementing project only the following cases are enough for all tests to pass
- Only allow your site to be loaded in an iFrame on your own pages.
- Do not allow DNS prefetching.
- Only allow your site to send the referrer for your own pages.

to reproduce the same
- clone the boiler plate for the project
- implement the above test cases using helmet js
- create a repl.it by importing the github repository
running the repl.it and using the link as solutions link is enough for test cases to pass

**Add a Link to the page with the problem:**
[Boilerplate for the project](https://github.com/freeCodeCamp/boilerplate-project-messageboard/)
[My Implementation which passed the test cases](https://github.com/pmayur/fcc-is-anon-message-board/tree/passing)

**Tell us about your browser and operating system:**
* Browser Name: Firefox developer edition
* Browser Version: 84.0b8 (64-bit)
* Operating System: Ubuntu 20.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
all the test cases were passed, although no requests by the fcc test suite were made to any project api's, except for the ones dealing with checking the response headers

![fcc-issue](https://user-images.githubusercontent.com/25099080/101821052-6ea8aa00-3b4d-11eb-9466-8e73d0f67849.png)

**Comment by nhcarrigan** [comment] 2020-12-10 19:45
This occurs because, at the moment, there are not tests present for the routing:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md

**Comment by Sky020** [comment] 2020-12-10 19:59
Thank you, for taking the time to open this issue. We are aware of this.

As such, I am closing this as a duplicate of #37185

**Closed by Sky020** 2020-12-10 19:59 UTC
Labels: scope: learn, status: needs help for triage
