### ISSUE TITLE
Assertions check againt "replace" function; default boilerplate code has function "myReplace"

### ISSUE THREAD

**Issue by jdistler** [FreeCodeCamp/FreeCodeCamp#3594] opened 2015-10-05 20:57 UTC
Challenge [Bonfire: Search and Replace](http://freecodecamp.com/challenges/bonfire-search-and-replace) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The default code uses a "myReplace" function name, however the assertions by default run against a "replace" function name. Thus either the default assertions or the default boilerplate code must be altered to run against the correct default function name.

My code:
```
function myReplace(str, before, after) {
 return str;
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```

**Comment by ltegman** [comment] 2015-10-05 21:10
This is a duplicate of #3574, clearly effecting quite a few students. If someone could pull this change from staging into the master branch that would be awesome!

**Comment by BerkeleyTrue** [comment] 2015-10-05 21:14
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Closed by BerkeleyTrue** 2015-10-05 21:14 UTC
