### ISSUE TITLE
Challenge passed with incomplete code

### ISSUE THREAD

**Issue by matthew02** [FreeCodeCamp/FreeCodeCamp#2472] opened 2015-08-22 02:52 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue.

I am allowed to continue to the next challenge with the single condition still in a state of failure. I can skip along without adding a return statement or modifying the existing return statement.

Additionally, the state of the condition appears to randomly alternate between pass/fail without actually having changed the code in any way (see attached screenshots). I couldn't reproduce the behaviour with a specific set of steps, but moving the caret around would eventually cause it (doesn't take long) as would highlighting different text selections (seems to be only when a line feed is included in the selection).

~~Finally, it seems like we are short-circuiting our function here by adding the return statement in the specified area in the code. All of the code below `// Only change code above this line.` never executes and includes a redundant return statement that would have returned a completely different data type. This may be irrelevant to the intent of the exercise, but it feels like it could be confusing.~~

After moving to the next challenge, I see that I had missed the point entirely and I should have copied the conditional verbatim from the description into our code. I guess I was freestyling. I was confused by the statement `If all three numbers match, we should change the value of win to the number that we have three of or leave it as null.` in the description and thought I was to add a variable called `win` and set it to either `null` or the winning number. Sorry for wasting anyones time reading through that. The first two paragraphs may still be relevant, though.

I'm fairly new at this so please tell me if protocol decrees that I should have broken this report up into separate reports.

![fail](https://cloud.githubusercontent.com/assets/416065/9422165/bc1d308c-484e-11e5-9bd6-2bb742e2ec69.png)
![pass](https://cloud.githubusercontent.com/assets/416065/9422164/bc1c1ea4-484e-11e5-9cb1-60ae6b2aabec.png)
![pass 2](https://cloud.githubusercontent.com/assets/416065/9422166/bc1e94a4-484e-11e5-81f4-38249344d4c7.png)

**Comment by benschenker** [comment] 2015-09-05 23:33
Hey @matthew02 thanks for posting!

Looks like this is a duplicate of #2281, keep an eye there for updates

**Closed by benschenker** 2015-09-05 23:33 UTC
