### ISSUE TITLE
ES6 Declare a Read-Only Variable does not pass tests due to error in test

### ISSUE THREAD

**Issue by RobAnthony01** [freeCodeCamp/freeCodeCamp#17694] opened 2018-06-22 16:53 UTC
Edit the code to sole the problem and run the tests.
You will get an error as the Regex expression is incorrect

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.2
* Operating System: Windows 10

**SOLUTION**

The Regex in the test needs to be updated to: `/console.log\\(\\s*?SENTENCE\\s*?\\)\\s*?;/g`

As there are escaped characters in the string and the backslashes need to be in the final Regex, they need to be doubled. At the moment they are just single backslashes and this is creating the problem.

I would be happy to fix this but I'm not sure where the file is any more!

**Comment by thomlom** [comment] 2018-06-23 15:13
Hey @RobAnthony01 , your issue is a duplicate of #17679. I've submitted a PR to correct that problem 🙂 
By the way, the file containing this test is in the [curriculum repo](https://github.com/freeCodeCamp/curriculum), in `challenges/02-javascript-algorithms-and-data-structures/es6.json`

**Comment by RobAnthony01** [comment] 2018-06-23 16:00
Thanks. I did a search but couldn't find it in the open issues.Glad it's getting fixed.On 23 Jun 2018 16:18, Thomas Lombart <notifications@github.com> wrote:Hey @RobAnthony01 , your issue is a duplicate of #17679. I've submitted a PR to correct that problem 🙂
By the way, the file containing this test is in the curriculum repo, in challenges/02-javascript-algorithms-and-data-structures/es6.json

**Closed** 2018-06-23 16:01 UTC
