### ISSUE TITLE
Unit test of: "Give your h1 element with the text I am dodger blue! the color dodger blue ...

### ISSUE THREAD

**Issue by d-m-h** [FreeCodeCamp/FreeCodeCamp#10590] opened 2016-09-09 15:37 UTC
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
<style>
.dodger-blue-text {
  color: #1e90ff;
}
</style>

<h1 class="dodger-blue-text" style="color: rgb(30, 144, 255)">I am dodger blue!</h1>

**Comment by ArielLeslie** [comment] 2016-09-09 15:43
Copy of Issue #10523

**Comment by dhcodes** [comment] 2016-09-09 16:06
Closing as duplicate of #10523

**Closed by dhcodes** 2016-09-09 16:06 UTC
