### ISSUE TITLE
Fix Testing on Challenge: "Applied Visual Design: Create a Horizontal Line Using the hr Element"

### ISSUE THREAD

**Issue by tesla809** [freeCodeCamp/freeCodeCamp#18117] opened 2018-09-11 02:43 UTC
#### Describe your problem and - if possible - how to reproduce it
The default code that is not supposed to be manipulated is causing the tests to fail. When one is asked to "Add an hr tag underneath the h4 which contains the card title." and one does (simple enough) the tests fails. 

`
<style>
 ...
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4><s>Google</s>Alphabet</h4>
      
      
      <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</em></p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>
`
The test fails because it checks for <em><p> in that order, instead of the default order of <p><em>... etc. There is no way that the user will know that this is the issue unless they experiment with the ordering of the tags which is not intuitive or they ask for help in the fourm and come across this blog post by SpaceCatInd (see: https://forum.freecodecamp.org/t/trouble-with-create-a-horizontal-line-using-the-hr-element-lesson/214232).

While a great hack to get over with the lesson, too much of the user's time is lost when a simple fix of the testing will do.

#### Add a Link to the page with the problem
Applied Visual Design: Create a Horizontal Line Using the hr Element
See:
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: MacOS

**Comment by randelldawson** [comment] 2018-09-11 06:00
@tesla809 Could you close this issue as it is a duplicate of [#18030](https://github.com/freeCodeCamp/freeCodeCamp/issues/18030)?

In the future, please perform a search for open issues related to what you are reporting before opening a new issue.

Thank you.

**Comment by moT01** [comment] 2018-09-13 13:52
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to the issue mentioned above, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Closed by moT01** 2018-09-13 13:52 UTC
