### ISSUE TITLE
Email address update crash

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#15876] opened 2017-09-12 00:21 UTC
Someone posted the following in the forum regarding updating their email ([link to post](https://forum.freecodecamp.org/t/e-mail-address-update-crash/147405)):

> I want to update my e-mail but when I typing new e-mail address I see the following answer:
> 
> ![image](https://discourse-user-assets.s3.amazonaws.com/original/3X/9/b/9b7ed8fb304afc9241250e5c4a88f14b2df065dc.png)
>
> There is no text on the blue line. I can only close this page or “Go back to Settings”.
> New mail box is empty (spam list too).
> 
> Can you help me?

I tried this myself and confirmed the empty blue bar.

I'm not sure if this is related to #15822, but it's the only open issue I found about updating emails.

**Comment by raisedadead** [comment] 2017-09-13 08:49
@kevcomedia Thanks for reporting, are they facing it on production i.e `freecodecamp.org` ? #15822 is unrelated because it's about a new auth mechanism which is under development and is not available on the live site yet.

The easiest way is to reach out to team@freeCodeCamp.org for help.

Thanks.

**Comment by kevcomedia** [comment] 2017-09-13 09:18
Yes, it's indeed on `freecodecamp.org`.

That thread still hasn't received any responses yet. I've just sent @QuincyLarson an invite to that thread.

I don't think emailing `team@freecodecamp.org` would be easiest because Quincy said a few days ago that those who send an email will now receive an auto-response that links to the Support category in the forum.

**Comment by raisedadead** [comment] 2017-09-13 11:51
Thanks. And Agreed. 

But individual account issues would still need to be taken up by those having access to the DB and in most cases over private emails because they would not be wanting to expose emails/credentials on the forum.

In any case coming to the reported issue:
> I tried this myself and confirmed the empty blue bar.

Can you confirm that your settings page shows your updated email or not? Did you happen to by any chance see this on any other browser, than your default? If yes please guide with the browser that you tried and got the error in the first place.

I can't seem to reproduce locally. But we did merge a pull request recently about authentication changes.

/cc @BerkeleyTrue maybe something weird here.

**Comment by kevcomedia** [comment] 2017-09-13 14:58
Looks like the empty blue bar appears when you enter your current email address. I entered a different email address and successfully updated. I did all that in Firefox.

But I'm not sure if this is due to that recent PR that you mentioned. OP did say they entered a new email address when they tried to update. I asked them if they have already updated their email.

**Comment by raisedadead** [comment] 2017-09-17 11:19
Related https://github.com/freeCodeCamp/freeCodeCamp/issues/15888#issue-258246390

**Comment by raisedadead** [comment] 2017-09-17 11:34
@QuincyLarson @BerkeleyTrue I cannot seem to reproduce this locally. 
/cc @WebTeenager

**Comment by WebTeenager** [comment] 2017-09-17 15:57
Hi.
I used to updated e-mail just Google Chrome v60 x64. And nothing happend - same blue bar and no one letter in my new e-mail box.
I dowloaded Mozilla and  one minute ago I've changed my mailbox to a new one in Mozilla successfully.

**Comment by raisedadead** [comment] 2017-09-17 16:27
@WebTeenager it's highly possible that it could be happening due some browser add-on or extension that you may have on chrome.

You could test this theory by opening up an incognito window with all add-ons disabled.

If that is the case, then it's definitely down to your browser.

**Comment by QuincyLarson** [comment] 2017-09-17 16:29
@raisedadead other than @WebTeenager and @kevcomedia has anyone else reported this issue? I've messaged @BerkeleyTrue and asked if he can look into this. Something may have changed in Chrome - or some of the recent changes he made around authentication may be affecting this.

**Comment by WebTeenager** [comment] 2017-09-17 18:20
I opened the browser in incognito mode and updated my e-mail successfully.
But then I tried to close all Google extensions (reboot browser) and repeat the update of the e-mail. Met the sam problem.

**Comment by QuincyLarson** [comment] 2017-09-18 04:23
@WebTeenager Thanks for the additional information. We're looking into this to see if we can reproduce this and fix it.

**Comment by QuincyLarson** [comment] 2017-09-19 23:14
@BerkeleyTrue and I have reproduced this locally. The backend works fine here - this is just an issue with the view logic. Is anyone interested in fixing this?

**Comment by raisedadead** [comment] 2017-09-23 16:25
Okay, so going through the old issues, I now remember this is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/14604

**Comment by raisedadead** [comment] 2017-09-23 16:27
I have closed the other, but investigation still needs to go into the https://github.com/freeCodeCamp/freeCodeCamp/issues/14604#issuecomment-297601857

The code location has probably changed. Will update more.

**Comment by piggito** [comment] 2017-10-02 06:49
I checked the issue in freecodecamp.org and noticed that we get a HTTP 500 response from https://www.freecodecamp.org/api/users/<code>/update-email but the content is a valid message: {"message":"juan3789@gmail.com is already associated with this account."}

It should be enough to change the HTTP 500 to a regular 200 response to solve the issue. I tried to check it in staging branch but I think there is the beta version there which doesn't seem to have this issue.
@QuincyLarson how did you replicate the issue locally?

**Comment by raisedadead** [comment] 2017-10-02 07:23
@piggito thanks for looking into this, this functionality has been removed from the staging (beta.freeCodeCamp.org / beta), and has been replaced with passwordless auth.

However, it exists on the production website (freeCodeCamp.org).

I can't seem to reproduce locally, but some have managed to reproduce.

It's a weird issue because the request is being received two times for some reason, I believe its a browser caching of the request, but I think I might be incorrect.

**Comment by piggito** [comment] 2017-10-02 13:29
@raisedadead thanks for your answer, is master branch the current version in production? I was trying to check this funcionality in local but using this branch I can't access the settings page. It is redirecting me to Map page, do you know why it could be happening?

**Comment by QuincyLarson** [comment] 2017-10-02 21:59
@piggito You'll want to branch off of the backup/master branch. That's what's currently in production.

**Comment by piggito** [comment] 2017-10-03 04:46
I tested locally but I couldn't reproduce the problem.
After digging in code it seems like this change solved the issue https://github.com/freeCodeCamp/freeCodeCamp/commit/b6e30f4e16bce00ca2022d5db07f1184e1f07003#diff-5d81af95449574544e7317f3eda2badeL519
is this in prod (freeCodeCamp.org) already?

**Comment by QuincyLarson** [comment] 2017-10-03 05:28
@piggito Yes - the code you're referring to should be in production. @BerkeleyTrue and I were able to reproduce the issue locally, though I can't remember exactly how. As far as I know, this is still an active issue.

**Comment by piggito** [comment] 2017-10-05 02:53
@QuincyLarson I was finally able to reproduce the issue locally, I needed to use `NODE_ENV='production' gulp`
I created a PR with the fix

**Comment by raisedadead** [comment] 2017-10-05 04:24
@piggito can you please have a look at the related https://github.com/freeCodeCamp/freeCodeCamp/issues/14604#issuecomment-297601857 the staging branch as well?

**Comment by piggito** [comment] 2017-10-05 11:04
@raisedadead I will create another PR for this issue cause the previous one had comments. Then, I will check  https://github.com/freeCodeCamp/freeCodeCamp/issues/14604#issuecomment-297601857

**Comment by piggito** [comment] 2017-10-06 21:24
@QuincyLarson @raisedadead @BerkeleyTrue please I need someone to answer my comment in the previous PR to help me fix the changes https://github.com/freeCodeCamp/freeCodeCamp/pull/15939#issuecomment-334445796

**Comment by piggito** [comment] 2017-10-11 19:38
@BerkeleyTrue please can you check the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/15947

@raisedadead I think we should reopen https://github.com/freeCodeCamp/freeCodeCamp/issues/14604 I have added a comment https://github.com/freeCodeCamp/freeCodeCamp/issues/14604#issuecomment-335048892

**Comment by BerkeleyTrue** [comment] 2017-10-13 20:08
PR merged.

@piggito Thanks for your help! It will be live latter today.

Happy Coding

**Comment by QuincyLarson** [comment] 2017-10-13 22:58
@piggito Awesome! Thanks again!

**Comment by QuincyLarson** [comment] 2017-10-16 02:09
@piggito just emailed me asking us to re-open this issue until they've made this change on the Staging branch.

**Comment by raisedadead** [comment] 2017-12-06 18:56
The issue with regards to this discussion is now resolved on both staging and production. 
Closing.

The PR attached to this issue is still open for discussion though.

**Closed by raisedadead** 2017-12-06 18:56 UTC
Labels: bug, help wanted
