### ISSUE TITLE
[.dev] Clicking 'sign-in' displays two loading elements

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36659] opened 2019-08-21 16:00 UTC
When I click the `sign-in` button, it displays two loading elements. Not sure if this is really much of a problem, but it feels a little weird.
![Screen Shot 2019-08-21 at 10 55 11 AM](https://user-images.githubusercontent.com/20648924/63448026-b2c8e600-c402-11e9-9ed3-0febadcf1c2b.png)

**Comment by raisedadead** [comment] 2019-08-26 10:12
That is intended by design. The navbar is indeed a separate component. I would swap the button loader with a skeleton animation to make it nicer.

**Comment by QuincyLarson** [comment] 2019-09-11 20:24
@moT01 Agreed. We are removing the "sign in" button from the navigation anyway so this shouldn't be an issue. I'm going to go ahead and close this issue.

**Closed by QuincyLarson** 2019-09-11 20:24 UTC
Labels: help wanted, platform: client, release: next/beta, ux: user interface
