### ISSUE TITLE
Challenge statement for "Change the Font Size of an Element" is unclear.

### ISSUE THREAD

**Issue by QuocAnhVu** [FreeCodeCamp/FreeCodeCamp#6687] opened 2016-02-03 01:09 UTC
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2633.3 Safari/537.36</code>.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

This challenge fails if the second p has class .red-text. This was not specified in the instructions, and may cause otherwise correct code to fail, confusing future students.

**Comment by QuocAnhVu** [comment] 2016-02-03 01:10
Just kidding. I didn't read.

**Comment by ltegman** [comment] 2016-02-03 03:06
In the future please close the issue if you realize it is not a bug. Thanks and happy coding!

**Closed by ltegman** 2016-02-03 03:06 UTC

**Comment by MatisyahuCS** [comment] 2016-02-03 13:46
OMG, I was going crazy for it. Thanks!
