### ISSUE TITLE
Sign in button on Safari not working

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#3947] opened 2015-10-28 02:49 UTC

**Comment by ltegman** [comment] 2015-10-28 03:47
Could you give us more information about what you mean by "not working" and how we can reproduce this error?

**Comment by benschac** [comment] 2015-10-28 16:29
Surely, Shirley.

When I try to click this button:

![screen shot 2015-10-28 at 12 27 55 pm](https://cloud.githubusercontent.com/assets/2502947/10795295/74dd1b8c-7d6f-11e5-9475-11248e3ee1d5.png)
(Sign in)

on Safari, nothing happens.

**Comment by ltegman** [comment] 2015-10-28 17:28
FCC doesn't officially support any browsers besides Chrome, so you may want to install the Chrome browser (if you haven't already) and use that for FCC. This is odd though, because I'm not able to repro this in Safari myself. Do you see any errors in the console when you click the Sign In button?

**Comment by benschac** [comment] 2015-10-28 17:31
Ah, yeah.  Ya'll should use modernizer or something to notify users about
your support when on other browsers.

I can't figure out how to open up safari's console.  Nor do I want to
figure it out since it's not supported.


Thanks.

On Wed, Oct 28, 2015 at 1:28 PM, Logan Tegman <notifications@github.com>
wrote:

> FCC doesn't officially support any browsers besides Chrome, so you may
> want to install the Chrome browser (if you haven't already) and use that
> for FCC. This is odd though, because I'm not able to repro this in Safari
> myself. Do you see any errors in the console when you click the Sign In
> button?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3947#issuecomment-151918431>
> .
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com

**Comment by ltegman** [comment] 2015-10-29 02:21
Closing this, but I'll open another issue for letting users know when they're not using Chrome that Chrome is the only officially supported browser.

Thanks and happy coding!

**Closed by ltegman** 2015-10-29 02:21 UTC
Labels: blocked
