### ISSUE TITLE
Js calculator test suite

### ISSUE THREAD

**Issue by Jrejoire** [freeCodeCamp/freeCodeCamp#39673] opened 2020-03-20 10:58 UTC
#### Issue Description

The test suite doesn't work for half of the questions of my Js calculator (from 8 to 15). I can verify them directly in the app but the test suite doesn't.

#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Windows
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen

https://codepen.io/Jrej/pen/RwPyyLV

Thanks for your help

**Comment by moT01** [comment] 2021-02-02 18:11
It doesn't appear that there is an issue that needs fixing here, the test suite is working as intended. If anyone feels I am wrong in closing this, feel free to leave a comment and we can reopen it. Thanks and happy coding 🎉

**Closed by moT01** 2021-02-02 18:11 UTC
Labels: scope: learn, scope: projects-frontend
