### ISSUE TITLE
Test validating solid border on class before class is put on img tag

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1012] opened 2015-06-20 05:51 UTC
Challenge http://www.freecodecamp.org/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I think the test for this is wrong, but I didn't spend much time than looking at it except to note it was doing a global & ignore case search. Which should probably be swapped to checking the img's style I'd assume.

![waypoint-add-borders-around-your-elements](https://cloud.githubusercontent.com/assets/3256176/8266193/b85049f4-16d4-11e5-9c25-b459617eac56.png)

**Comment by jbmartinez** [comment] 2015-08-16 21:58
Duplicate of #1090

**Closed** 2015-08-26 00:15 UTC
