### ISSUE TITLE
HTTPS not working for freeCodeCamp.com redirect

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38207] opened 2020-02-12 23:30 UTC
It seems HTTPS is not currently working on freeCodeCamp.com. This could be confusing some people who are still going to that domain, and it may be affecting backlinks.

For anyone reading this, freecodecamp.com redirects to freeCodeCamp.org. But some people still  mistakenly link to freeCodeCamp.com or visit it. So we need the https to work here.

<img width="1201" alt="Privacy_error" src="https://user-images.githubusercontent.com/985197/74387100-4cbf8900-4dbd-11ea-9e55-2fba99c3dbea.png">

**Comment by raisedadead** [comment] 2020-02-13 08:07
Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/38201

**Closed by raisedadead** 2020-02-13 08:07 UTC
Labels: type: bug
