### ISSUE TITLE
Bug in tests for Cat Photo App Step 49

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#46705] opened 2022-06-29 05:06 UTC
### Describe the Issue

The tests for the formatting are too strict and won't let valid code pass.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-49

### Your code

```
          <fieldset>
            <label for="indoor-outdoor">
              <input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor
            </label>
            <label for="outdoor-indoor">
              <input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor
            </label>
          </fieldset>
```

### Expected behavior

The above code should pass.

This code passes:

```
<fieldset> <label><input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor</label>
          <label><input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor</label> </fieldset>
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Sboonny** [comment] 2022-06-29 07:24
here is failing test, in this markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804e1.md
 
>Both radio buttons should still be located between opening and closing `label` element tags.
>
> ```js
> const labelChildNodes = [...$('label')].map((node) => [...node.childNodes]);
> assert(
>   labelChildNodes.filter((childNode) => childNode[0].nodeName === 'INPUT')
>     .length === 2
> );
> ```

but why it's failing is alluding me. 

Anyway, I am in support of changing it to make it pass

**Comment by YaaseenIbrahim** [comment] 2022-06-29 14:03
This code works:
`<fieldset> <label><input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor </label> <label><input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor </label> </fieldset>`

But this code doesn't:
`<fieldset> <label> <input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor </label> <label> <input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor </label> </fieldset>`

Those 2 codes are exactly the same expect the second one has a little empty space between `<label>` and `<input>`. So something about the empty space makes the thing declare it as 'no longer between the opening and closing of the `<label>`'  I dont know if this helps but that seems to be how to reproduce this bug. As even in the original buggy code that @nhcarrigan showed us there is empty space between the `<label>` and `<input>`:

> ### Your code
> ```
>           <fieldset>
>             <label for="indoor-outdoor">
>               <input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor
>             </label>
>             <label for="outdoor-indoor">
>               <input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor
>             </label>
>           </fieldset>
> ```
 But if you do the same code and remove the empty space between those 2 tags, then the code passes:
 ```
           <fieldset>
             <label for="indoor-outdoor"><input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor
             </label>
             <label for="outdoor-indoor"><input id="outdoor" type="radio" name="indoor-outdoor" value="outdoor"> Outdoor
             </label>
           </fieldset>
 ```
As you can see the code passes:
![image](https://user-images.githubusercontent.com/65892296/176455739-353430f2-0b14-484d-998f-5eec1f13efcd.png)

 So the empty space is messing stuff up. Again idk if this helps its my first time contributing so idk what im doing lol but i hope it helps somewhat in fixing the issue.

**Comment by Sboonny** [comment] 2022-06-29 15:34
@YaaseenIbrahim finding this, without debugging is impressive, good job.

> the empty space makes the thing declare it as 'no longer between the opening and closing

Yeab, this is helpful 🤍

>  idk if this helps its my first time contributing so idk what im doing lol but i hope it helps somewhat in fixing the issue.

**Comment by gikf** [comment] 2022-06-29 19:22
Test expects `input` to be first child node of the `label`. When there's text (spaces) before it, first node will be node with spaces. To check for `input` in all child nodes, and to ensure there's only one input per label, assertion can be changed to something like:

```js
  labelChildNodes.filter(
    childNodes =>
      childNodes.filter(node => node.nodeName === 'INPUT').length === 1
  ).length === 2;
);
```

**Closed** 2022-06-30 12:29 UTC
Labels: type: bug, help wanted, scope: curriculum
