### ISSUE TITLE
Sandbox is being executed/eval'd twice erroneously

### ISSUE THREAD

**Issue by prashcr** [FreeCodeCamp/FreeCodeCamp#5750] opened 2016-01-02 11:16 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20'hello'%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.  
  
The code shown below should just print console.log() once, and pass the test.  
However, when I run the code, the sandbox seems to execute twice.
I tested this by putting new statements in, and it's clear to me that the code is being executed twice for some reason.
I tried running the code at least 10 times, it's been executed twice every time.

My code:
```javascript
function myFunction() {
  var myVar = 'hello';
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction


// now remove the console.log line to pass the test
```

**Comment by prashcr** [comment] 2016-01-02 11:22
![screen shot 2016-01-02 at 7 18 37 pm](https://cloud.githubusercontent.com/assets/7514066/12074314/3091f4b6-b186-11e5-9506-05f15e2a9ab7.png)
![screen shot 2016-01-02 at 7 18 31 pm](https://cloud.githubusercontent.com/assets/7514066/12074315/331425ec-b186-11e5-90a1-e6eafc3a76f1.png)

**Comment by smrajagopal** [comment] 2016-01-02 12:53
:+1:

I have noted this particular behaviour in a lot of waypoints actually!

**Comment by ltegman** [comment] 2016-01-02 17:19
Closing as a duplicate of #5072 since they both come from the same root cause. Thanks and happy coding!

**Closed by ltegman** 2016-01-02 17:19 UTC

**Comment by denmch** [comment] 2016-01-02 18:03
I don't think this is a duplicate of #5072. The reason it doesn't pass is that the test is simply looking for the phrase `console.log` anywhere in the code, even in comments. It fails if `console.log` appears more than once.

`console.log` actually appears 3 times: (1) within the function, (2) outside the function, and (3) in the final comment instructing you to remove the second instance. If you delete that comment as well, the test passes as expected.

**Comment by ltegman** [comment] 2016-01-02 18:13
@denmch We have a fix in for that problem that should be deployed to the website shortly :smile:

**Comment by denmch** [comment] 2016-01-02 18:17
@ltegman :+1:
