### ISSUE TITLE
Browser hangs on Challenge submit modal

### ISSUE THREAD

**Issue by Robledano** [FreeCodeCamp/FreeCodeCamp#12145] opened 2016-12-21 09:53 UTC
Challenge [Make Circular Images with a Border Radius](https://www.freecodecamp.com/challenges/make-circular-images-with-a-border-radius) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

Hi, I use chrome and it will not let me continue. It tells me that it's fine, but it keeps loading the popup and I can not continue :(

I have refreshed and cleared the cache and it does not work either.

![sin titulo-1](https://cloud.githubusercontent.com/assets/5221465/21384656/bc55a0aa-c76b-11e6-8ef6-47b989434bed.png)

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-radius:50%;
    border-style: solid;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by codehakase** [comment] 2016-12-21 12:04
Have you tried using a different browser?

**Comment by Robledano** [comment] 2016-12-21 12:06
@codehakase Another browser and another OS :\

**Comment by Grozacorp** [comment] 2016-12-21 17:34
Yes, I have the same problem, and it persists if I skip this one and try to complete the next one (and the challenges after that one, too). Though, if I go back to previous challenges and reset them, there is no problem.

If I go back to this one after navigating away from it, the code that I had completed is still completed, too (it still shows "50%" instead of "10px"). It doesn't reset the code, but it doesn't give credit that it is completed.

**Comment by raisedadead** [comment] 2016-12-21 19:07
@Robledano @Grozacorp Apologies for the inconvenience that you guys have been facing. 

Can you share screenshots of your browser console? If you are on Chrome:
<kbd>Cmd</kbd> + <kbd>Option</kbd> + <kbd>J</kbd>

Post the screenshots of any errors that you might be getting on the console tab.

**Comment by Grozacorp** [comment] 2016-12-21 19:38
@raisedadead Sure! It looks like I'm getting two errors when I click submit.

![fcc_error](https://cloud.githubusercontent.com/assets/24691112/21403468/19c08de6-c77a-11e6-8a5a-73fa9f10cd1e.png)

**Comment by raisedadead** [comment] 2016-12-21 19:50
I remember pushing some fixes to the in #11945 for the first error for `optimizely`.
And unfortunately, I do not get the same on my end at all, and can't reproduce the issue.

I am not sure about the font error for the second one, which I do get on my side.
/cc @BerkeleyTrue do you have any idea?

@Robledano @Grozacorp Can you guys also confirm that no browser extensions or any VPN, or firewall that you might be using is conflicting?

To rule out any conflicting browser extensions simply open the challenge in an incognito window.

**Comment by Grozacorp** [comment] 2016-12-21 19:58
@raisedadead Yeah, there was no problem in incognito. So I went into my extensions and started disabling some of them. Found out that it was my adblocker, uBlock Origin, that was causing the problem. It worked flawlessly after disabling that.

I should have thought of trying that sooner heh.

**Comment by raisedadead** [comment] 2016-12-21 20:06
@Grozacorp maybe clearing your cache and cookies would be worth a try?

**Comment by Robledano** [comment] 2016-12-21 22:56
@raisedadead i installed the browser, disabled the blocker and still not working :(

![sin titulo-1](https://cloud.githubusercontent.com/assets/5221465/21409174/03fa7814-c7d9-11e6-97b9-8872057995b4.png)

**Comment by Grozacorp** [comment] 2016-12-22 06:23
@raisedadead @Robledano Alright, so, after clearing my cache didn't work, I went through all of my addons. I disabled one at a time and cleared my cache/cookies each time before retrying the challenge, and I went all the way down the list until I finally disabled LastPass.

Apparently it doesn't like LastPass. After I disabled that, it was working again. I re-enabled uBlock and other addons afterwards, and I was able to continue to complete challenges.

So, at least for me, it's working for me again. Thanks for all the help!

**Comment by raisedadead** [comment] 2016-12-22 07:19
@Grozacorp thanks for the update, glad that you resolved it.
@Robledano In any case this could be happening because of the below:

- Any extension that's intefering with the page like in @Grozacorp's case.
- Any VPN, ISP or Firewall that's interfering with the network.

Unfortunately I have been unable to reproduce this. There have been no other reports recently from more users, and leading us to believe this could be isolated to your case. 

To be conclusive:
1. If you can, try solving the challenge in `incognito` mode on a different device than yours.
2. If you can, try solving the challenge in a different network than yours.

Depepending on the results it can be determined which one is it.

Meanwhile I will close the issue, not being a bug in the codebase, but we will continue to support you via this thread.

Thanks.

**Closed by raisedadead** 2016-12-22 07:19 UTC
