### ISSUE TITLE
Running test with a comment at the end makes the test fail. 

### ISSUE THREAD

**Issue by LazaroFilm** [freeCodeCamp/freeCodeCamp#39346] opened 2020-07-31 13:39 UTC
**Describe your problem and how to reproduce it:**
Running the test will fail if you have anything commented after the code.
Deleting the comment line allows us to pass the test. 
The presence of a comment should not affect the output of the test. 

```
(function() {
  console.log("A cozy nest is ready");
})();
// makeNest();
```
**Add a Link to the page with the problem:**
**Object Oriented Programming: Understand the Immediately Invoked Function Expression (IIFE)**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-immediately-invoked-function-expression-iife

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 84.0.4147.105 (Official Build) (64-bit)
* Operating System: Catalina 10.15.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by JoshuaPelealu** [comment] 2020-07-31 13:50
It looks like this is caused because the test is removing every whitespace and make the code one line, then test it with a regex, that test if the string ends with a `)` parentheses

**Comment by JoshuaPelealu** [comment] 2020-07-31 14:04
This can be easily fixed by changing the regex string from instead of testing if it ends with a `()` it will test if it's an IIFE function. I can do this.

**Comment by ojeytonwilliams** [comment] 2020-07-31 14:21
@LazaroFilm thanks for reporting this, it's definitely not working as intended.

@JoshuaPelealu, that's my assessment, too.  A PR would be very welcome.

**Closed** 2020-09-01 23:48 UTC
Labels: scope: learn, status: fix in progress
