### ISSUE TITLE
White empty tab space on the website

### ISSUE THREAD

**Issue by arjunan-k** [freeCodeCamp/freeCodeCamp#46658] opened 2022-06-25 06:51 UTC
### Describe the Issue

While opening the Freecodecamp website there is a white tab space on the right side of website if zoomed in. This is due to the scroll button on the right side. This is mostly common in the sites. But raising the issue to let you know if this is a bug that you were not aware of.
![white tab issue](https://user-images.githubusercontent.com/104669486/175761776-809b1808-ec0c-4aec-b8bd-022565f7e6c5.png)

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/'
2. Zoom in max
3. Scroll to top right corner near the 'Sign in' icon
4. See error of white tab on the right side of site.

### Expected behavior

I think that even it is zoomed in, the site details should fill that page. That is scroll button right after the website without white tab.
![corrected](https://user-images.githubusercontent.com/104669486/175762047-a39e7541-e2a1-4250-847e-5f56a610c428.png)

### System

- Device: Laptop
- OS:  Windows 11
- Browser: Chrome
- Version: 102

### Additional context

This is due to the absence of html body tag I think

```
html,body {
    margin:0;
    padding:0;
    overflow-x:hidden;
}
```

**Comment by neeraj2713** [comment] 2022-06-25 16:02
can i work on this issue?

**Comment by JordanMooree** [comment] 2022-06-25 18:00
I can't reproduce this issue. I zoomed in 500% on:
Device: Desktop Monitor (1440p)
OS: Windows 10
Browser: Chrome
Version: 102

![image](https://user-images.githubusercontent.com/27147016/175785270-b0c48d98-5e04-48ba-a19d-47dda509d87a.png)

Can anyone else reproduce this?

**Comment by JordanMooree** [comment] 2022-06-25 18:13
Hello @neeraj2713, once this issue gets help from moderators and users to reproduce and confirm its validity and fix, we will most likely label it as `Help Wanted` or `first timers only`. You do not need permission to work on `Help Wanted` or `first timers only` tagged issues.

For now, we will wait until we confirm the validity of this issue. In the meantime, feel free to browse through our issues filter them by the tags I mentioned above at https://github.com/freeCodeCamp/freeCodeCamp/issues/ and contribute to any you like.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by ShaunSHamilton** [comment] 2022-06-25 20:06
Hello there,

Would you mind sharing the resolution and width of your monitor?

I ask this, because zoomed in at that level, most monitors are not wide enough (high enough res) to cause the _Sign in_ button to appear.

**Comment by arjunan-k** [comment] 2022-06-26 11:09
@JordanMooree 
Hlo sir, please try to scroll to the top most right after zooming in max. In the screenshot you just shared, I think that you have scrolled till menu button. there is still a 'Sign in ' button after that.
When I design websites sometimes I came across this issue. I think that this is due to the auto margin and padding of the body tag.
```
html,body {
    margin:0;
    padding:0;
    overflow-x:hidden;
}

```
Still not sure this is due to my screen. I using a laptop of screen size 39.62 cm (15.6") diagonal, FHD (1920 x 1080), 144 Hz, IPS, micro-edge.

**Comment by arjunan-k** [comment] 2022-06-26 11:10
@ShaunSHamilton
hlo sir,
Still not sure this is due to my screen. I using a laptop of screen size 39.62 cm (15.6") diagonal, FHD (1920 x 1080), 144 Hz, IPS, micro-edge.

**Comment by salehmalik121** [comment] 2022-06-27 19:03
cant reproduce this issue.

**Comment by moT01** [comment] 2022-07-06 15:02
I can't reproduce it either.

**Comment by nhcarrigan** [comment] 2022-07-06 15:04
Going to close this as can't reproduce.

If anyone is able to reproduce again with some additional relevant information, feel free to let us know and we can re-open as needed.

**Closed by nhcarrigan** 2022-07-06 15:04 UTC
Labels: type: bug, scope: UI, status: waiting triage
