### ISSUE TITLE
Instruction clarification needed for Bonfire - Where do I belong

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#3385] opened 2015-09-20 20:48 UTC
The instructions doesn't properly state about the input array whether it is sorted or not.
The instructions must specify that the input arrays maybe unsorted. This will ensure that campers learn about `Array.prototype.sort` and sort the array in their code.

**Comment by tamienne** [comment] 2015-09-23 07:10
The instructions do say it's sorted..
"Return the lowest index at which a value (second argument) should be inserted into a **sorted** array (first argument)."

The issue is that there are 2 test that pass in arrays that are not sorted.

Either reword the instructions to be something like...
"Return the lowest index at which a value (second argument) should be inserted into the array (first argument) once the array is sorted."

or fix the tests to pass in a sorted array.

I would suggest to update the instructions and change one of the unsorted tests that return 0 to be a different index. like: assert(where([2, 20, 10], 11) === 2

Unless this bonfire isn't really about sorting but just inserting into the first location that it is between?

what result are you looking for when doing a "where([1, 9, 3, 20, 3], 6);"? 3 (after you sort) or 1 (unsorted)

**Comment by abhisekp** [comment] 2015-09-23 09:24
@tamienne that's already done in different PR #3383 :smiley:

**Comment by tamienne** [comment] 2015-09-23 14:12
Great!

**Comment by bugron** [comment] 2015-10-24 17:04
Closing this issue as changes form PRs https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3384 and https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3386 are pulled in.

**Closed by bugron** 2015-10-24 17:04 UTC
