### ISSUE TITLE
mobile response images

### ISSUE THREAD

**Issue by coyforce** [FreeCodeCamp/FreeCodeCamp#1300] opened 2015-07-15 06:47 UTC
The system fails to give credit to the user if they add img-responsive class to the first image as well as the new image

**Comment by awesomeaniruddh** [comment] 2015-09-12 13:20
Hmm, the user is *not* supposed to add the `img-responsive` class to the first image. Honestly, there is only so much the tests can do: the user must follow the instructions in the description of the challenge. Anyone has any thoughts on this?

**Comment by bugron** [comment] 2015-09-14 20:20
@coyforce thanks for posting this issue!
Note that your issue is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1078 so I'll close it. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-14 20:20 UTC
Labels: Test Improvement
