### ISSUE TITLE
The Profiles tab is no longer exist in the chrome dev tool

### ISSUE THREAD

**Issue by anirugu** [freeCodeCamp/freeCodeCamp#15738] opened 2017-08-06 14:23 UTC
On this challenge https://www.freecodecamp.org/videos/chrome-dev-tools-profiles, The Profile tab is no longer exists in latest chrome dev tool.

The latest chrome dev tool has a tab called "Memory" which have the feature mentioned in the video. Anything could be done to show this changes in the text shown on the page. 

It doesn't take time to find out where is this functionality in tool but it would be great if user got the information through the page.

**Comment by andmckvr13** [comment] 2017-08-07 11:38
I would like to help fix this. Simple to replace 'Profiles' with 'Memory'. Perhaps though there should be some type message on the page though for users.

**Comment by erictleung** [comment] 2017-08-09 08:03
I'm fine with changing this to mentioning "Memory" instead of "Profiles".

The link needs to be changed also to I think this https://developers.google.com/web/tools/chrome-devtools/memory-problems/.

**Comment by andmckvr13** [comment] 2017-08-09 08:12
@erictleung  great. I will work on this issue then and get it to you ASAP

**Comment by andmckvr13** [comment] 2017-08-10 19:40
@erictleung the staging branch seems to be a bit out of date compared to the master. The video-challenges folder can be found on the master branch, but not on the staging branch which is used for making the changes and the PR. Is there a way I can make contributions to this?

**Comment by erictleung** [comment] 2017-08-10 21:14
@andmckvr13 thanks for digging around. I guess I've been out for a bit and forgot that we *might* be removing video challenges from the site (possible duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/12753). 

cc/ @freeCodeCamp/moderators can someone verify that these video challenges will be removed? I don't see them on the beta site so I'm assuming this is true.

**Comment by texas2010** [comment] 2017-08-10 21:43
I could remind this. because fcc site will have offline mode later. so no video.

**Comment by raisedadead** [comment] 2017-08-11 11:16
@erictleung video challenges are being deprecated in favor of the content being directly made available over our youtube channel. That's what was discusses a while ago and I think @QuincyLarson can confirm

**Comment by dhcodes** [comment] 2017-08-11 17:57
Reference: https://github.com/freeCodeCamp/freeCodeCamp/issues/12753

**Comment by QuincyLarson** [comment] 2017-08-11 18:34
@raisedadead @dhcodes Our current thinking is we'd make these videos searchable, and perhaps dynamically add them to the challenge map, but they would just be plain embeds - they won't have comprehension questions afterward. 

I recommend we update the description on the YouTube video itself. We could add a simple note like this:  

> Note: Chrome's "Profiles" tab has been renamed to "Memory"

Would that suffice?

**Comment by dhcodes** [comment] 2017-08-12 02:20
Sounds good @QuincyLarson but I don't have access to edit the Youtubes.

**Comment by QuincyLarson** [comment] 2017-08-12 20:04
@dhcodes OK - I've made the change: https://www.youtube.com/watch?v=fvfqnFYXF_8&list=PLWKjhJtqVAbmfoj2Th9fvxhHIeqFO7wOy&index=34

**Closed by QuincyLarson** 2017-08-12 20:04 UTC
Labels: help wanted
