### ISSUE TITLE
Able to pass Restrict Possible Usernames with incorrect code

### ISSUE THREAD

**Issue by AnonymousLords** [freeCodeCamp/freeCodeCamp#17761] opened 2018-06-29 18:15 UTC
This is the Regex challenge --> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

The specification of the code you will write is:

> 1) The only numbers in the username have to be at the end. There can be zero or more of them at the end.

Yet it never actually checks for it, meaning you could cheat with the code below:

```
let username = "JackOfAllTrades";
let userCheck = /\w[a-z]/gi; // Change this line
let result = userCheck.test(username);
```

--> https://repl.it/@John_Nicole/Regular-Expressions-17761

If you actually tested for that, a username like 1JackOfAllTrades would fail this regex.

**Comment by tyler-otj** [comment] 2018-08-21 06:50
Your "cheat" is the most similar cheat solution to mine, so I figured I'd post here..
You can omit the \w and it will still work. I passed all tests with:
``let userCheck = /[a-zA-Z]/ig; // Change this line``

**Comment by TomerPacific** [comment] 2018-11-05 19:17
joshalling,
mind if I take this issue on?

**Comment by joshalling** [comment] 2018-11-06 14:41
@TomerPacific Yeah, feel free to submit a PR for this.

**Comment by Ashish34** [comment] 2018-11-08 08:59
Able to pass the test case.
let username = "JackOfAllTrades";
let userCheck = /\w\D/; // Change this line
let result = userCheck.test(username);

**Comment by TomerPacific** [comment] 2018-11-08 19:06
@joshalling ,
I tried browsing the repository to find where the solutions to challenges are found, but couldn't find them. Can you point me in the right direction?

**Comment by Nirajn2311** [comment] 2018-11-09 07:13
@TomerPacific the solutions are in the same .md file as the challenges are in

**Comment by TomerPacific** [comment] 2018-11-09 09:29
@Nirajn2311 ,
it's wierd. I am not seeing the solution locally, but only on freeCodeCamp's repository. Thanks for the heads up.

**Comment by bikingbadger** [comment] 2018-12-11 13:40
Duplicate of #17733

**Comment by moT01** [comment] 2018-12-11 13:50
Closing in favor of the duplicate mentioned

**Closed by moT01** 2018-12-11 13:50 UTC
