### ISSUE TITLE
I have the width set to 100 px, not sure why it is not passing. Help Appreciated. 

### ISSUE THREAD

**Issue by Modullah** [FreeCodeCamp/FreeCodeCamp#9589] opened 2016-07-06 20:37 UTC
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20%0A%20%20%20%20.smaller-image%20%7B%0A%20%20%20%20%20%20%20width%3A%20100px%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20class%3D%22smaller-image%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
   
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
    
    .smaller-image {
       width: 100px;
    }
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" class="smaller-image">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Modullah** [comment] 2016-07-06 21:06
Pretty sure this is a bug. I found a way to submit the task and move on to the next challenge. I simply invoked the smaller-image class since the challenge forces you to invoke the .smaller-image class you create. Then I wrote, width = 100  in the img tag. I was able to pass the challenge thankfully but was unable to pass it the way the prompt suggests it.

**Comment by arun1595** [comment] 2016-07-06 21:19
It's not a bug with your site, but with your code.
```
 p {
    font-size: 16px;
    font-family: Monospace;
    
    .smaller-image {
       width: 100px;
    }
  }
```
See, you have nested the `.smaller-image` inside `p`. This is not a valid CSS rule and this style of nesting is only used in preprocessors like LESS and SASS. 
The challenge is to get you practise writing `classes` and applying them to your `html` elements. The test only checks whether the width of the image is 100px and not whether you used `classes` or `inline styling` to achieve that. However, Inline styling is not a good practice and you should avoid using it.

**Comment by Modullah** [comment] 2016-07-06 21:29
Wow, I looked at it forever and couldn't find the issue. Thank you for pointing out the brackets. I did have a good laugh when you said the bug was in my code though lol. True enough and thanks again for the explanation as well :).

**Comment by dwd2010** [comment] 2016-07-06 23:32
closed as not bug.
Happy Coding!

**Closed by dwd2010** 2016-07-06 23:32 UTC

**Comment by mack318** [comment] 2016-07-12 17:02
Crazy but i did the same thing.   look closely at the opening curly bracket for the p element, then look for the closing bracket ???  right there under the image style we created.  
![mistake](https://cloud.githubusercontent.com/assets/6243323/16775895/b3890e22-4817-11e6-8375-d5a98be88403.png)

**Comment by dwd2010** [comment] 2016-07-12 17:06
@mack318, you forget to create class in img element.

**Comment by mack318** [comment] 2016-07-12 17:17
you rock dwd2010.   yes I did forget that too, and didn't even notice

**Comment by dwd2010** [comment] 2016-07-12 17:22
@mack318, if you need a help with challenges. 
You could go to [Help chat room](https://gitter.im/FreeCodeCamp/Help). People will help you.

Happy Coding!
