### ISSUE TITLE
[beta] Declaring Variables in Data Visualization

### ISSUE THREAD

**Issue by Sirjustin** [freeCodeCamp/freeCodeCamp#13267] opened 2017-02-09 22:59 UTC
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-data-in-d3

#### Issue Description

Not sure if this is related to the local memory issues..

The tests fail if you leave the variable as dataset because it says that it has already been declared as a variable.  But if you change the variable it works fine. 

#### Browser Information

PC Chrome

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/12264222/22806645/27a821d2-eef1-11e6-89e2-240590507535.png)

**Comment by Sirjustin** [comment] 2017-02-09 23:00
Data Visualization with D3: Work with Data in D3

**Comment by fonsecapontes** [comment] 2017-03-04 02:00
I maked the test and it pass.

The issue is the local memory of your pc.

**Comment by lynxlynxlynx** [comment] 2017-04-18 07:56
Hit the same thing. Also #14329 is exhibiting the same problem, so could be closed as a duplicate if we start a list of problematic challenges. Reloading the page works, while reseting doesn't fix the problem.

**Comment by lynxlynxlynx** [comment] 2017-04-18 11:43
And I guess both are duplicates of #12762

**Comment by systimotic** [comment] 2017-09-04 12:51
Hi! Thanks for reporting and looking into this issue.

This is a known issue. We're working on resolving it through #12762. I'm closing this as a duplicate.

Happy coding!

**Closed by systimotic** 2017-09-04 12:51 UTC
Labels: beta
