### ISSUE TITLE
Code is fine but returning "SyntaxError: Illegal return statement"

### ISSUE THREAD

**Issue by estermer** [FreeCodeCamp/FreeCodeCamp#7901] opened 2016-04-05 04:25 UTC
#### Issue Description
I was writing my code for a problem and testing an output of one of my variables when I got the error message that says "SyntaxError: Illegal return statement". 

I figured it it might be some additional code messing it up so I commented out things progressively until I finally just decided to comment out everything in the scope of the function and just return a plane number, and it is still giving me this error.

I tried the hard refresh and clearing the local storage, and I still cannot get the issue to clear.

#### Browser Information
*I am using the most updated version of Google Chrome 2016
* I am using Windows 8

#### Your Code

```js
function sumPrimes(num) {  
  //var primes = [];
  //var x = 2;
  
  //do {
    
   // var wilsonTheorem = 0;
    
    //for (var i = 1; i <= 13; i++){
      
      //wilsonTheorem += (i-1);
      
      
   // }
    
   /* if (wilsonTheorem%x > 2){
      primes.push(x);
    }
    
    x++;
    
  } while (primes.length != num);*/
  
  
  return 5;
}

sumPrimes(3);
```

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/17515551/14271213/8ff87678-fac4-11e5-8b7c-7d1dc7756d1e.png)

**Comment by erictleung** [comment] 2016-04-05 04:37
Mmm this is weird. I think the JavaScript engine the editor is using has issues with multi-line comments because if I change it to the following, it'll return `5` like expected.

```
   /* if (wilsonTheorem%x > 2){
      primes.push(x);
    }

    x++;

  } while (primes.length != num);
  */
```

**Comment by raisedadead** [comment] 2016-04-05 05:05
Yeah Eric, We have had these kind of problems many a times, the core issue here is the code isn't passed as actual JavaScript but a string that is concatenated in a `head + code + tail` format, where `head` and `tail` are scaffolding/support code for the challenge and `code` is the challenge seed.
Then this is passed through the `loopProtect` library and other validations.

All this is later evaluated in a `eval` method when its actually tested/executed.

Problems start where the parsing goes haywire in corner cases such as this one, after all the code from the code mirror is a string, whilst in comparison to the JavaScript Interpreters that work when you run the above code directly in browser's console in.

Well have to dig deep to find  quick fix for this, but until then this is the way it works sadly :disappointed:

**Comment by erictleung** [comment] 2016-04-05 05:52
@raisedadead thanks for that explanation! I've been meaning to explore the code base a bit more deeply. I'll be closing this as this is actually a duplicate of an earlier issue #7072.

**Closed by erictleung** 2016-04-05 05:52 UTC
