### ISSUE TITLE
Microsoft Edge does not support current platform

### ISSUE THREAD

**Issue by Merinac** [freeCodeCamp/freeCodeCamp#17966] opened 2018-08-01 22:37 UTC
I currently use Microsoft edge as my primary web browser which, surprisingly, doesn't support the freecodecamp testing module. Once "Run the tests" has been clicked, the button darkens, "// running test" appears in the lower console, and it stops there. This applies to every lesson available. However, if I attempt the same lesson on chrome, it works just fine.

**Comment by Nirajn2311** [comment] 2018-08-02 11:38
I checked it and only “Run the tests” button is not working.

**Comment by jooji-san** [comment] 2018-08-03 09:04
It's only works in chrome and they are aware of that

**Comment by ArielLeslie** [comment] 2018-08-04 01:29
Free Code Camp has bee updated to use newer technologies. It makes the application much faster and it means that we can go much longer without having to do a huge migration like the recent one. However, Edge and Safari are very bad about choosing not to adhere to standards and support new functionality in JS and CSS. Right now, that means that both Edge and Safari exhibit lots of unexpected behavior. If you become a web developer you will come to hate these browsers with every fiber of your being.

**Comment by miksh7** [comment] 2018-09-11 16:47
"Run the test" fails on Edge with
SCRIPT5007: Unable to get property 'next' of undefined or null reference

**Comment by RandellDawson** [comment] 2019-01-31 17:57
This has recently been discussed in the Gitter channel and was told to post the console results for Edge for the first challenge. 

The very first challenge has never worked (from what I can remember since at least December 2016) with a passing solution using Edge or Internet Explorer 11. Those two browsers will not pass many of the HTML section's challenges. For over 2 years, the FCC forum and GitHub mods on the forum have been telling people to not use Edge or IE 11, because of what we thought was a conscious decision by FCC to not support those browsers.

---

Below is a screen shot of Edge browser on the first challenge. Notice it just says `// running tests`.

![image](https://user-images.githubusercontent.com/5313213/52074185-2e824480-253e-11e9-9bbb-0c42983328bb.png)

---

Also, experience the same issue with the most current version of the `master` branch on GitHub.

![image](https://user-images.githubusercontent.com/5313213/52074263-55d91180-253e-11e9-8ba4-d09f7dc29400.png)

---

Below is a screenshot of the console:

![image](https://user-images.githubusercontent.com/5313213/52074364-8ae56400-253e-11e9-96a2-2d5af34015e7.png)

**Comment by raisedadead** [comment] 2019-01-31 18:14
Can someone with access to a Windows 10 and latest Edge browser take a dig at this?

/cc @freeCodeCamp/dev-team

**Comment by raisedadead** [comment] 2019-01-31 18:16
If conclusive results are found that we are unable to have a majority of the platform unusable on Edge, we would want to warn users with a modal or something as soon as we have it detected programmatically.

**Comment by RandellDawson** [comment] 2019-01-31 18:20
It appears to be only on the HTML and CSS (SASS) related challenges.

**Comment by RandellDawson** [comment] 2019-01-31 18:21
I wonder how many users have visited FCC for the first time and could not figure out what was wrong and just left.

**Comment by thecodingaviator** [comment] 2019-02-01 06:36
I’ll check it once on edge today. If we add a modal, we also need to make sure that it is added such that when edge moves to chromium, we can remove it

**Comment by thecodingaviator** [comment] 2019-02-01 14:58
![image](https://user-images.githubusercontent.com/34807532/52130331-df343500-265f-11e9-8d48-8012c7041f4d.png)
Yeah, the problem is still there. My Windows and Edge are both up to date.

**Comment by raisedadead** [comment] 2019-02-01 15:17
Thanks everyone. Ok now that we know the issue is still current. Can we have some investigation into this? Let's keep the thread for potential solution.

**Comment by RandellDawson** [comment] 2019-02-02 18:52
I am on vacation through Monday, so I can not review til Monday evening.

**Comment by thecodingaviator** [comment] 2019-02-03 05:57
I'll test it locally and try to review whatever I can

**Comment by thecodingaviator** [comment] 2019-02-03 06:32
There's another problem in edge, when I click on any link the cursor appears there as if the content is editable but on typing anything or pressing backspace, it does what nothing and goes back to the previous page respectively:
![image](https://user-images.githubusercontent.com/34807532/52173493-92f60b80-27ab-11e9-9e17-0f18134d49dd.png)
![image](https://user-images.githubusercontent.com/34807532/52173494-9ab5b000-27ab-11e9-88f0-a5c5d5a07e90.png)

**Comment by raisedadead** [comment] 2019-02-03 16:50
We have landed the fixes on master. Please report fresh issues on separate threads, if any.

**Closed** 2019-02-03 16:49 UTC
Labels: help wanted, other: device specific, platform: client, type: bug

**Comment by SambariManikanta09** [comment] 2021-08-16 14:31
Hey, The issue is I couldn't sign in, either by GitHub or email on Edge. But when I tried with Google Chrome I was able to sign in, As my college computers don't allow to download Google chrome I have to work ok Edge
