### ISSUE TITLE
phoneticLookup("") returns 

### ISSUE THREAD

**Issue by thinkhuman** [FreeCodeCamp/FreeCodeCamp#6659] opened 2016-02-01 21:03 UTC
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20result%20%2B%3D%20lookup%5Bval%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";
  // Only change code below this line
  var lookup = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };
  result += lookup[val];
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("");

```

**Comment by HoBi** [comment] 2016-02-01 21:55
Duplicate of #6660.

**Comment by adibasy** [comment] 2016-02-01 22:05
ThinkHuman you need to take out the += and just make is =

**Comment by ltegman** [comment] 2016-02-01 22:18
Closing as a duplicate. Thanks and happy coding!

**Closed by ltegman** 2016-02-01 22:18 UTC
