### ISSUE TITLE
Progress without finishing

### ISSUE THREAD

**Issue by newsharpie** [FreeCodeCamp/FreeCodeCamp#2711] opened 2015-08-26 01:46 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-split-your-bootstrap-row has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I did the challenge wrong and it still tells me I did it right and proceeds to the  next challenge. Or I am pretty sure I am wrong
![pg1](https://cloud.githubusercontent.com/assets/7596245/9483856/9309e1f0-4b59-11e5-90c0-0eeab9483512.png)
![pg2](https://cloud.githubusercontent.com/assets/7596245/9483857/930f5af4-4b59-11e5-860b-7085c1289f69.png)

**Comment by abhisekp** [comment] 2015-09-06 16:17
@newsharpie I suppose this issue is resolved.

cc: @bugron

**Comment by bugron** [comment] 2015-09-06 16:32
@newsharpie thanks for posting this issue!
I can't reproduce this issue so I'll close it, but feel free to reopen if you still experience problems. Thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-06 16:32 UTC
