### ISSUE TITLE
Waypoint: Practice Functional Programming

### ISSUE THREAD

**Issue by abbynormative** [FreeCodeCamp/FreeCodeCamp#1415] opened 2015-07-29 18:37 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-practice-functional-programming has an issue. Please describe how to reproduce it, and include links to screen shots if possible:

I appreciate what you're trying to do by referring people to this tutorial, but it's not the greatest. In addition to not really providing detailed explanations of the functions they're trying to teach, there seem to be bugs in the answers provided at the site. For example, on exercise 20, when I click "show answer" and then run the code they provide, it does not let me move forward. I'm now stuck and can't complete this waypoint unless I do some digging through the source, and I'm certain that's not what you're trying to teach.
http://imgur.com/igv8e1h

**Comment by kurzninja** [comment] 2015-07-31 04:08
Quincy has stated to me that they are in the process of writing their own functional programming tutorial similar to this one but hopefully easier to understand, but that it would be "a long ways off".

**Comment by ahstro** [comment] 2015-08-08 13:27
This is a duplicate of #1410.

**Closed** 2015-08-26 00:14 UTC
