### ISSUE TITLE
the button and event "ctrl+enter" no found

### ISSUE THREAD

**Issue by walejandromt** [FreeCodeCamp/FreeCodeCamp#4293] opened 2015-11-11 03:04 UTC
in here the event freezen

Challenge [Waypoint: Change the Color of Text](http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text?solution=%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 style="color: blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by SaintPeter** [comment] 2015-11-11 03:30
I'm afraid I don't understand what your issue is.  Note that you are supposed to change the color to `red` from `blue.

Closing.  Feel free to re-open if you can explain what the issue is.

**Closed by SaintPeter** 2015-11-11 03:30 UTC

**Comment by walejandromt** [comment] 2015-11-11 03:32
thanks i see right now jejeje
