### ISSUE TITLE
Validation passes even when code is wrong

### ISSUE THREAD

**Issue by alexmihalache** [FreeCodeCamp/FreeCodeCamp#7454] opened 2016-03-07 23:15 UTC
Challenge [Construct JavaScript Objects with Functions](http://www.freecodecamp.com/challenges/construct-javascript-objects-with-functions#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Initially I ran the tests on the following code:**

var MotorBike = function() {
  this.wheels = 2,
  this.engines = 1,
  this.seats = 1
};

**Instead of:**
var MotorBike = function() {
  this.wheels = 2;
  this.engines = 1;
  this.seats = 1;
};

And the validation still passed - I assume it should have blocked me from moving onto the next section as I used the incorrect commas. 

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var MotorBike = function() {
  this.wheels = 2;
  this.engines = 1;
  this.seats = 1;
};

```

**Comment by crazymerlyn** [comment] 2016-03-08 20:07
Your code isn't wrong. You just merged three initializations into one.
For example `a = 1, b = 2, c = 3;` is a perfectly valid alternative for
```
a = 1;
b = 2;
c = 3;
```
Adding newlines doesn't change much. Test it yourself. See if 
```
a = 1,
b = 2,
c = 3
```
works.

**Comment by raisedadead** [comment] 2016-03-09 20:42
I agree with @crazymerlyn.

@alexmihalache your syntax is valid, with multiple initializations, moreover JavaScript doesn't strictly enforce you to add `;` at the end.

Although its not a good practice, as such a coding style could lead to errors crawling in, for example, if you happen to minify the code, its definitely going to throw errors.

The code editor does hint that something is wrong (in the syntax):
![image](https://cloud.githubusercontent.com/assets/1884376/13649608/7e1d88b8-e664-11e5-9d55-4099d1bfdd4f.png)

This is up to the developer to acknowledge or ignore. I feel enforcing any particular pattern as tests in the challenge is not really the motif of FCC. 

Closing this because IMO, this is not a bug in the challenge. However please feel free to continue to discuss this further. Of course we are welcome to any suggestion that will help you in following a standard practice.

**Closed by raisedadead** 2016-03-09 20:42 UTC
