### ISSUE TITLE
It will not let me proceed to the next challenge but I am pretty sure that my code is correct. When I click the "check my work" tab it disappears and nothing happens

### ISSUE THREAD

**Issue by slcohen3** [FreeCodeCamp/FreeCodeCamp#3500] opened 2015-09-25 19:20 UTC
Challenge [Waypoint: Give a Background Color to a Div Element](http://freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="gray-background">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<style>
  .gray-background {
    background:gray;
  }


<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

```

**Comment by jhealy86** [comment] 2015-09-25 19:53
The issue is in your code. The CSS class markup needs to be added in the style tag at the top of the code, not underneath the div.

**Comment by iheartkode** [comment] 2015-09-25 20:21
Can you close this once you resolve it? Thanks @slcohen3

**Comment by bugron** [comment] 2015-09-26 18:34
@slcohen3 thanks for posting this issue!
As @jhealy86 mentioned, your code is incorrect. Move `.gray-background` class declaration into your `style` tag.
Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-26 18:34 UTC
