### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by wazzuper** [FreeCodeCamp/FreeCodeCamp#10550] opened 2016-09-09 08:57 UTC
Hi there, I'm stuck here.

Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

My code:
```js

var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

```
So, what's the problem? I can't complete this task because of this error:

> You should use two double quotes (") and four escaped double quotes (\").

But.. I'm use them all, no?

**Comment by SashaCherkasova** [comment] 2016-09-09 09:03
Encountering same issue here on Safari 9.1

**Comment by rngadam** [comment] 2016-09-09 09:12
Related: 

https://github.com/FreeCodeCamp/FreeCodeCamp/commit/31e904f4ff116f3d951c5a67655d0e65460fb3ed

**Comment by saghipnt** [comment] 2016-09-09 12:42
me too...

**Comment by cloudrainsnow** [comment] 2016-09-09 12:51
I also have this problem. Using Mozilla 49.0.

**Comment by joordas** [comment] 2016-09-09 13:08
I have the same problem as well. Using chrome.

**Comment by AhmedTunuLashku** [comment] 2016-09-09 13:36
+1

**Comment by dhcodes** [comment] 2016-09-09 15:34
Reference to #10258

**Comment by BerkeleyTrue** [comment] 2016-09-09 15:53
Closing as duplicate of #10258

**Closed by BerkeleyTrue** 2016-09-09 15:53 UTC

**Comment by johnanthony797** [comment] 2016-09-09 20:13
+1

**Comment by uiuxmonkey** [comment] 2017-01-05 20:28
Please remove space before "\"  
var myStr= "I am a \"double quoted\" string inside \"double quotes\".";
