### ISSUE TITLE
Test text is sometimes invisible

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11003] opened 2016-09-30 19:41 UTC
#### Screenshot
I'm experiencing the following issue of test text disappearing:

![](https://www.evernote.com/l/Ar-C_lhBu4dJ_r4SQJS2l2HPKmTA_uU7bN0B/image.png)

**Comment by P1xt** [comment] 2016-10-01 15:24
@QuincyLarson The problem might be more than the test text not appearing. My experience running tests on beta has been that any tests that appear blank actually are blank. For instance, if you get a challenge where all tests are blank you can literally change nothing in the code, hit run tests, and pass the challenge.

**Comment by QuincyLarson** [comment] 2016-10-02 01:16
@P1xt yes - I think this is the issue. I am experiencing exactly what you described.

**Comment by BerkeleyTrue** [comment] 2016-10-04 05:39
closing as duplicate of #10966

**Closed by BerkeleyTrue** 2016-10-04 05:39 UTC
Labels: beta, bug
