### ISSUE TITLE
the exercise test is wrong

### ISSUE THREAD

**Issue by koouty** [FreeCodeCamp/FreeCodeCamp#5672] opened 2015-12-31 23:13 UTC
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%201%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 1;
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction


// now remove the console.log line to pass the test


```
After following the instructions.
1) inside the function creata a variable myVar, as this
```
function myFunction() {
var myVar = "abc";
console.log(myVar);
}
myFunction();
console.log(myVar);
```
after this remove the second console.log line:
```
function myFunction() {
var myVar = "abc";
console.log(myVar);
}
myFunction();
```
3) the exercise don't pass.

**Comment by ltegman** [comment] 2015-12-31 23:16
We are aware of this issue and have a PR in the works to fix it. Closing as a duplicate of #5559. Thanks and happy coding!

**Closed by ltegman** 2015-12-31 23:16 UTC

**Comment by koouty** [comment] 2015-12-31 23:21
Ok, I deleted the comments as you says in #5559 and passed the test. Thanks!

**Comment by NPKonstan** [comment] 2016-01-01 06:16
+1
