### ISSUE TITLE
"Add hr tag" challenge doesn't let me pass

### ISSUE THREAD

**Issue by hiimnew** [freeCodeCamp/freeCodeCamp#17997] opened 2018-08-09 09:50 UTC
The lesson won't let me pass even after I do it 100% right. I tried many ways to make it work also just tried on firefox it's also buggy there.

https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element/

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.84 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04

As @huyenltnguyen pointed out I would like to share "my code" :) just a simple `hr` tag

```HTML
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4><s>Google</s>Alphabet</h4>
      <hr> <!-- The only part I added and which should be enough to pass -->
      <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</em></p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>
```

**Comment by huyenltnguyen** [comment] 2018-08-09 11:40
Hi @hiimnew, could you paste your code here? It would help the debugging process.

**Comment by huyenltnguyen** [comment] 2018-08-09 19:16
@hiimnew Thanks for adding the code.

So I did a quick search and found that the issue has already been addressed (https://github.com/freeCodeCamp/freeCodeCamp/issues/17944). There is a bug in the second test case that needs to be fixed, but for now, you can pass the test if you wrap the `<em>` around the `<p>`, like this:
```
<em><p>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>
```

**Comment by hiimnew** [comment] 2018-08-09 21:35
Thanks for the info, and also thanks for your time.

**Comment by huyenltnguyen** [comment] 2018-08-10 01:34
You're welcome! Glad I can help.
Would you mind closing the issue, since it's a duplicate of #17944?

**Comment by hiimnew** [comment] 2018-08-10 19:12
This was my very first issue, I thought someone else needs to close it :D

**Closed** 2018-08-10 19:11 UTC
