### ISSUE TITLE
Page is broken and has to be refreshed several times.

### ISSUE THREAD

**Issue by TrueSkittles** [FreeCodeCamp/FreeCodeCamp#2979] opened 2015-09-01 23:31 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-understand-boolean-values has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Screen shot: https://gyazo.com/c3cb6f017d627dabc3e72c5a7c228d8d

When I am on any of the free code camp challenges the objectives do not appear and it can not be completed. The only way I can find to fix it is to refresh the page a bunch of times and hope it eventually works. I can work around it but it is frustrating and takes a lot longer (and time is something I am limited on already :( ). I am using Google Chrome and it appears to be updated to current. My OS is Windows 7.

**Comment by bugron** [comment] 2015-09-03 12:38
@TrueSkittles thanks for posting this issue!
It seems this is a global problem so I'm closing this issue as a duplicate of:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2906
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Closed by bugron** 2015-09-03 12:38 UTC
