### ISSUE TITLE
Unclear instructions in "Manipulate Arrays With unshift"

### ISSUE THREAD

**Issue by SparkyT** [FreeCodeCamp/FreeCodeCamp#7880] opened 2016-04-04 07:40 UTC
Challenge [Manipulate Arrays With unshift](https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.shift()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22J%22%2C%20%22cat%22%5D%0AourArray.unshift(%22Happy%22)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Happy%22%2C%20%22J%22%2C%20%22cat%22%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0AmyArray.shift()%3B%0AmyArray.unshift(%5B'Paul'%2C35%5D)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Instructions are to "Add ["Paul",35] to the beginning of the myArray variable using unshift()."
Test requires that ["John", 23] is shifted off the array first but this is not in the instructions.
Instructions could be clearer

My code:
```javascript
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();
myArray.unshift(['Paul',35]);

// Only change code below this line.



```

**Comment by erictleung** [comment] 2016-04-04 08:26
The comments in the editor say to ``// Only change code below this line.`` Following those rules will automatically remove the `["John", 23]` from the array because of the `myArray.shift()` command. The instructions for the challenge can then be followed naturally and use the `.unshift()` method to add `["Paul", 35]` to the beginning. Closing as not a bug issue. Happy coding!

**Closed by erictleung** 2016-04-04 08:26 UTC

**Comment by Python-git** [comment] 2018-07-08 07:46
actually its pretty unclear why is it that on one excersize it says to start your code where the only possible place would be would be where it states //change code below this line //!!
and on other exercises it wants you to to do the exact opposite. back an fourth. for a very very simple concept. more like manipulating the users of Arrays.
