### ISSUE TITLE
Seems to be isolated but FreeCodeCamp is offline. When I try to sign in the screen says "Error 522" below that it says "Host error". Does anyone know how I could fix this? (works with phone when not on WIFI)

### ISSUE THREAD

**Issue by gz4053** [FreeCodeCamp/FreeCodeCamp#9020] opened 2016-06-07 21:42 UTC
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by sludge256** [comment] 2016-06-07 21:52
Have you been able to access FCC in the past or is this your first time trying to sign in?

**Comment by gz4053** [comment] 2016-06-07 22:14
I have been able to access it thousands of times. I have been on it for months. I only noticed the problem in the last week.

**Comment by atjonathan** [comment] 2016-06-07 23:19
Duplicate of #8808, please leave a comment there. Happy Coding!

**Closed by atjonathan** 2016-06-07 23:19 UTC
Labels: blocked
