### ISSUE TITLE
Open Weather Map API httpRequest issues when used with codepen

### ISSUE THREAD

**Issue by NikhilChandrasenanNair** [freeCodeCamp/freeCodeCamp#13515] opened 2017-02-22 13:23 UTC
#### Challenge Name

http://codepen.io/Lihkinrian/pen/evOgVr?editors=0010

#### Issue Description

When i use http://codepen.io  i am getting an error "getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."  i am using http for both the request url and request origin url. But when i use https for the request origin url i.e the https://codepen.io//Lihkinrian/pen/evOgVr?editors=0010   and http for the api   i get "Mixed Content: The page at 'https://codepen.io/Lihkinrian/pen/evOgVr?editors=0010' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.openweathermap.org/data/2.5/weather?lat=10.0090639&lon=76.3614448&&appid=39809327b8276ac16891fe71210a0291'. This request has been blocked; the content must be served over HTTPS.". 

#### Browser Information

* Browser Name, Version: Chrome v56
* Operating System: windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code

```js

function getWeatherData() {    navigator.geolocation.getCurrentPosition(function(position) {
        var lat = position.coords.latitude,
            lon = position.coords.longitude,
            url = 'http://api.openweathermap.org/data/2.5/weather?lat=' + lat + '&lon=' + lon + '&&appid=39809327b8276ac16891fe71210a0291';     
      $.getJSON(url, function(data) {
          console.log(data);
      });    
    });
}

$(document).ready(function() {
    getWeatherData();
});


```

**Comment by raisedadead** [comment] 2017-02-22 16:22
Duplicate of #9079 , please refer workarounds.

**Closed by raisedadead** 2017-02-22 16:22 UTC

**Comment by greenfreq** [comment] 2017-02-22 20:03
Recommending someone look at the workarounds does not resolve the bug.
