### ISSUE TITLE
Cannot log into fcc forum

### ISSUE THREAD

**Issue by Deesteph55** [freeCodeCamp/freeCodeCamp#37731] opened 2019-11-10 18:38 UTC
I have not been able to log into fcc forum for a few days. It first said I could not log in with my account with my IP address. I thought maybe its because I am in a different country from where i normally use fcc. So i tried making a new account. Then it said Incorrect username, email or password. I clicked on the I forgot password option then it said "There are no accounts with the this email address." So it was never able to create a new account in the first place though it did not tell me so. 

I tried logging in with Github and it says sorry we are facing a known issue. How long before its fixed. I dont know where else to ask since i dont have access to the forum 
I am on a Windows 10 PC laptop using a Chrome browser

**Comment by TaraBryn** [comment] 2019-11-10 20:59
@Deesteph55 There is already [an open issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/37452) for the github problem, and I believe the message you get when trying to manually log in without github is related. If you wait an hour or so and try logging in manually (i.e., *not* with github) it might let you in. It's kind of hit or miss at the moment, so keep trying. I would also make sure that you are using the correct username. Since it says there is no email address associated with your account (maybe you can try and login with email rather than your username?) There are some posts on the forum suggesting to try and use a free proxy service to log into the site, but I was unable to get any of them to work.

**Comment by Deesteph55** [comment] 2019-11-10 21:36
@TaraBryn I saw that issue and it seemed closed or abandoned so thats why i made another one. do you know anything about the ip address problem?  Are other people experiencing it?

**Comment by RandellDawson** [comment] 2019-11-10 22:58
Closing as duplicate of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/37452

**Closed by RandellDawson** 2019-11-10 22:58 UTC
Labels: type: bug

**Comment by TaraBryn** [comment] 2019-11-10 23:09
@Deesteph55 here's a link to the official explanation of why this is happening: https://github.com/freeCodeCamp/freeCodeCamp/issues/37452#issuecomment-544744530
