### ISSUE TITLE
C9.io needs Credit card details (mandatory) for new user Sign ups.

### ISSUE THREAD

**Issue by srisathiyamca** [freeCodeCamp/freeCodeCamp#12071] opened 2016-12-16 11:23 UTC
Not able to create [Cloud9](https://c9.io) account.
Its asking credit card details to create an account.

**Comment by raisedadead** [comment] 2016-12-16 13:23
![image](https://cloud.githubusercontent.com/assets/1884376/21264174/e583f048-c3c0-11e6-84c5-2ccfe5085441.png)

**Comment by raisedadead** [comment] 2016-12-16 13:35
Duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9826

Well while, I know it's frustrating that they have made it mandatory to have credit card details on record for new users, rest assured they will not charge the card as long as you are restricting yourself to the free usage plan.

Please bear with us while we move to https://gomix.com/ for the backend challenges.

**Comment by Em-Ant** [comment] 2016-12-16 20:46
@srisathiyamca you don't have to wait for the new curriculum to be released to start building your apps in https://gomix.com/ . You can build all the micro-service APis and full-stack apps in it, many people are doing it already.

**Comment by raisedadead** [comment] 2016-12-17 06:59
@Em-Ant Can we have a migration guide, while we are at this? If you can help us with a few resources, we can tag this help wanted to create an article on forum wiki.

**Comment by Em-Ant** [comment] 2016-12-17 13:25
@raisedadead sure.

**Comment by dhcodes** [comment] 2017-04-11 15:32
I believe we can mark this resolved in staging and close this as it seems all the links now reference GoMix.

**Closed by dhcodes** 2017-04-11 15:32 UTC
Labels: beta, confirmed, help wanted, resolved in staging
