### ISSUE TITLE
Claiming C# trophy issues: Unclear instructions

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51632] opened 2023-09-22 14:59 UTC
### Describe the Issue

A _lot_ of people on the forums keep having trouble figuring out how to link their FreeCodeCamp and Microsoft accounts.

There's a huge pile of them in the forum: 

https://forum.freecodecamp.org/c/c-sharp/588 

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/write-your-first-code-using-c-sharp/write-your-first-c-sharp-code

### Your code

```



```
N/A 

### Expected behavior

I would like it to be easier for campers to know what to do here if the trophy claim thing didn't work. One of them even mentioned something about a bad link? 

### System

- Device: Desktop
- OS: Windows 10
- Browser: FireFox 
- Version: 117.0.1

### Additional context

While I was able to do this just fine, others aren't having an easy time.

**Comment by ojeytonwilliams** [comment] 2023-09-22 15:16
Thanks @a2937 it's definitely not working as intended at the moment.

While I wouldn't say it fixes the issue, necessarily, https://github.com/freeCodeCamp/freeCodeCamp/pull/51551 is an attempt to guide people a little better.

**Comment by moT01** [comment] 2023-09-27 19:11
https://github.com/freeCodeCamp/freeCodeCamp/pull/51654 will also help a little.

**Comment by ojeytonwilliams** [comment] 2023-09-28 10:41
Yep, I think this is close enough to be a duplicate, so I'm closing it in favour of https://github.com/freeCodeCamp/freeCodeCamp/issues/51455

**Closed by ojeytonwilliams** 2023-09-28 10:41 UTC
Labels: type: bug, scope: curriculum, status: waiting triage
