### ISSUE TITLE
Second assertion test format seems wrong for the Bonfire:Convert HTML Entities challenge

### ISSUE THREAD

**Issue by takcs50** [FreeCodeCamp/freecodecamp#1132] opened 2015-06-27 04:37 UTC
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Below is the test structure for the second code test:
assert.strictEqual('<>', '<>', 'should escape characters');should escape characters: expected '<>' to equal '<>'

I believe the assertion strictEqual is missing the convert function part.  I believe it should contain the following code assertion:
**assert.strictEqual(convert('<>'),** '<>', 'should escape characters');

![html-entities-test-code](https://cloud.githubusercontent.com/assets/9400740/8390462/6264e014-1c4b-11e5-9208-b9bc96702c92.PNG)

![html-entities-test-error](https://cloud.githubusercontent.com/assets/9400740/8390463/6883e896-1c4b-11e5-8aef-6616007fed7c.PNG)

Thank you for looking into the issue.

**Comment by LumenTeun** [comment] 2015-06-30 02:10
This is a duplicate of #1062, please keep discussion in there and close this issue. Thank you :)

**Closed** 2015-06-30 02:25 UTC
