### ISSUE TITLE
Please consider accessibility for the HTML coding challenges.

### ISSUE THREAD

**Issue by sarbbottam** [FreeCodeCamp/FreeCodeCamp#8518] opened 2016-05-08 20:26 UTC
For example, `alt` tag for `images` ...

**Comment by sarbbottam** [comment] 2016-05-08 20:29
... too early to comment, I could see it in following challenge https://www.freecodecamp.com/challenges/add-alt-text-to-an-image-for-accessibility

Wondering if they should be combined.

Please feel free to close the issue, if you feel otherwise. Thanks!

**Comment by sarbbottam** [comment] 2016-05-08 20:36
Please consider suggesting `label`, before placeholder https://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field

**Comment by ltegman** [comment] 2016-05-08 22:40
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4656. Please feel free to continue the discussion over there.

Thanks and happy coding!

**Closed by ltegman** 2016-05-08 22:40 UTC
