### ISSUE TITLE
Code in test runner doesn't behave as it does in regular js environment

### ISSUE THREAD

**Issue by javierglatstein** [FreeCodeCamp/FreeCodeCamp#3799] opened 2015-10-19 01:51 UTC
Challenge [Bonfire: Sum All Odd Fibonacci Numbers](http://freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers#?solution=var%20generator%3D%20(function()%7B%0A%20%20var%20previous%3D%5B%5D%3B%0A%20%20var%20latest%3D1%3B%0A%20%20return%20function()%7B%0A%20%20%20%20if(previous.length%20%3C%202)%7B%0A%20%20%20%20%20%20previous.push(latest)%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20latest%20%3D%20previous.reduce(function(previous%2C%20current)%7B%0A%20%20%20%20%20%20%20%20return%20previous%2Bcurrent%3B%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20previous.shift()%3B%0A%20%20%20%20%20%20previous.push(latest)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20latest%3B%0A%20%20%7D%3B%0A%7D)()%3B%0A%0Afunction%20sumFibs(num)%20%7B%0A%20%20var%20sum%3D0%3B%0A%20%20var%20fiboNumber%3Dgenerator()%3B%0A%20%20%0A%20%20while(fiboNumber%3C%3Dnum)%7B%0A%20%20%20%20if(fiboNumber%261)%7B%0A%20%20%20%20%20%20%20sum%2B%3DfiboNumber%3B%0A%20%20%20%20%7D%0A%20%20%20%20fiboNumber%3Dgenerator()%3B%0A%20%20%7D%0A%20%20return%20sum%3B%0A%7D%0A%0A%0A%0AsumFibs(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The test runner marks the tests as failed even though the return the expected values. I know the root cause of the issue is related to the code of the generator function being outside the sumFibs function.

The code executes correctly and running it inside other container, as chrome's console or karma test runner executes as expected.
I have also changed the values in the last line to execute each test scenario suggested in the problem and it gives the expected value.

Including the generator code into the sumFib function fixes the issue, however I think it's really important to avoid this kind of issues if people will be learning from this exercises.

My code:
```javascript
var generator= (function(){
  var previous=[];
  var latest=1;
  return function(){
    if(previous.length < 2){
      previous.push(latest);
    } else {
      latest = previous.reduce(function(previous, current){
        return previous+current;
      });
      previous.shift();
      previous.push(latest);
    }
    return latest;
  };
})();

function sumFibs(num) {
  var sum=0;
  var fiboNumber=generator();
  
  while(fiboNumber<=num){
    if(fiboNumber&1){
       sum+=fiboNumber;
    }
    fiboNumber=generator();
  }
  return sum;
}
sumFibs(4);

```

**Comment by ltegman** [comment] 2015-10-19 02:07
This is not a problem with the test. The problem is that when you don't instantiate the `generator` variable inside the `sumFibs` function you are creating a global variable that hangs around after your `sumFibs` function is done running. This means that every call to `sumFibs` after the first one is not starting with a fresh generator. If you run your code as it is and call `console.log(sumFibs(4))` twice in a row at the end you'll see a clear demonstration of the problem -- you don't get the same result.

You can pass the test if you remove the call to `sumFibs` from the last line of your code, but that's really just avoiding fixing the problem of the global variable. I'd recommend going with the solution that you've seen works, moving the declaration of the generator inside the `sumFibs` function. This way your `sumFibs` function will always get the correct result no matter how many times you run it.

Closing as not a problem with the tests, but feel free to follow up if you need further clarification.

Thanks and happy coding!

**Closed by ltegman** 2015-10-19 02:07 UTC
