### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11321] opened 2016-10-22 17:00 UTC
Console shows that there's a mistake.

Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0AtestObj%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
testObj[playerNumber];   // Change this Line

```

**Comment by PedroCSSilva** [comment] 2016-10-22 17:10
Yeah and there's a mistake on your code. Where's your "player" variable? This is the proper solution:

`// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line
`

**Comment by Bouncey** [comment] 2016-10-22 17:23
@PedroCSSilva what @marienhof is pointing out is that the output displays`testObj[playerNumber]` without it being assigned to player. 

I can confirm this issue, but I have a feeling it is resolved in the react release. I will check it what I get a chance.

**Comment by systimotic** [comment] 2016-10-22 20:01
@Bouncey It's actually being assigned to the player variable in both the live version and the React version. I think @marienhof accidentally removed it.

**Comment by Dayfiri** [comment] 2016-10-22 23:23
@systimotic I think that is true. I fresh opened FCC page without being signed in. Went to this assignment and the assignment was already written:
`var player = testObj[playerNumber];`
I just clicked the button to `run code` and I passed without even doing anything

**Comment by systimotic** [comment] 2016-10-22 23:34
Mmm, that's not what I got. That would also be an issue. For me, I get what I'm supposed to get, both when I load the page in a browser I usually don't use (= not logged in) or when I reset the challenge:
```
var playerNumber;       // Change this Line
var player = testObj;   // Change this Line
```

**Comment by Dayfiri** [comment] 2016-10-22 23:46
@systimotic It is alright now. I think there are cookies so it might be a problem. 
I entered a page from new browser (Opera), deleted everything from history. When I entered a page, it was alright. Here is an example:
![screenshot from 2016-10-23 01-44-20](https://cloud.githubusercontent.com/assets/16082563/19623239/8b3d5530-98c2-11e6-8ba2-e31590249f12.png)

**Comment by dhcodes** [comment] 2016-10-23 02:30
I'm still not clear what the issue is. @marienhof, can you elaborate?

**Closed** 2016-10-26 14:15 UTC
