### ISSUE TITLE
Arguments Optional tests area missing

### ISSUE THREAD

**Issue by lozadaOmr** [freeCodeCamp/freeCodeCamp#16637] opened 2018-02-04 15:37 UTC
#### Challenge Name

https://www.freecodecamp.org/challenges/arguments-optional

#### Issue Description

When the code to call the function is  `addTogether(2)([3]);` which raises `TypeError: addTogether(...) is not a function`.
If I refresh the browser or resume the challenge for later the tests area is not visible.
A valid input will make tests area visible again.

Tested by starting the challenge with `addTogether(2)([3]);` reload the browser the test disappears.
`addTogether(2,3);` and run the tests it will display the missing test area.

The missing test area only happens if the code for the challenge is `addTogether(2)([3]);` which raised the TypeError.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 59.0.3071.115 (Official Build) (64-bit)
* Operating System: elementary OS 0.4.1 Loki
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js

function addTogether() {
  return false;
}

addTogether(2)([3]);

```
#### Screenshot

![fcc](https://user-images.githubusercontent.com/2493327/35779072-67785444-0a02-11e8-80b3-2372d2d2ff62.png)

**Comment by jkao1** [comment] 2018-02-04 20:12
+1

**Comment by raisedadead** [comment] 2018-02-05 07:07
This is kind of due to the limitation on the challenge infrastructure in the production, while its agreed that the UX is due to the code being incorrect in the editor, it still should not happen.

We have moved to better platform on the beta. Until then this will remain as a limitation. 
I'll let other's pitch in if we do need to investigate and fix this in productions?

/cc @freeCodeCamp/moderators

**Comment by QuincyLarson** [comment] 2018-02-06 05:12
@jkao1 @lozadaOmr Are either of you able to reproduce this problem on [beta's version of Arguments Optional](https://beta.freecodecamp.org/en/challenges/intermediate-algorithm-scripting/arguments-optional)?

**Comment by lozadaOmr** [comment] 2018-02-06 12:01
@QuincyLarson Could not reproduce on beta version.

Although, I also attempted to change the code and hard reload chrome or
view the challenge from a link, noticed that the code gets reset to the default one.

Browser Information
- Google Chrome, Version 59.0.3071.115 (Official Build) (64-bit)
- elementary OS 0.4.1 Loki
- Laptop

**Comment by raisedadead** [comment] 2018-02-08 13:03
Hi @lozadaOmr in that case, I think we will have to close this. The fix for the issue is costly and we would rather focus on making the beta ready for now. Sincerest apologies for the inconvenience.

**Closed by raisedadead** 2018-02-08 13:03 UTC
