### ISSUE TITLE
$(...).css(...) is undefined in task item

### ISSUE THREAD

**Issue by Bravo13** [FreeCodeCamp/FreeCodeCamp#3242] opened 2015-09-11 10:47 UTC
Challenge http://freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64
![screenshot](http://content.screencast.com/users/Bravo13/folders/Jing/media/88e00ae0-d504-47cd-a1ad-d17491f1db6f/2015-09-11_1346.png)

**Comment by awesomeaniruddh** [comment] 2015-09-11 11:04
Thanks for posting the issue @Bravo13!

Can you please post your current code as well?

**Comment by Bravo13** [comment] 2015-09-11 12:02
After checking task problem is gone, so I can't reproduce it :(

**Comment by awesomeaniruddh** [comment] 2015-09-11 12:04
Oh, well. Are you able to complete the waypoint?

**Comment by Bravo13** [comment] 2015-09-11 14:38
yes, its ok

**Comment by BerkeleyTrue** [comment] 2015-09-11 18:24
Closing. @Bravo13 If it comes up again please paste the code that reprduces it, the OS you are using, and the browser.

Happy Coding!

**Comment by ahstro** [comment] 2015-09-12 17:40
Reopening because I can reproduce with some accuracy. Most of the time when loading the site in Firefox, `$(...).css(...) is undefined` will apprear instead of the intended message. However, from what I could see, the intended message always appear when clicking the `Run tests`-button. This doesn't appear to be a bug in Chromium.

**Comment by ltegman** [comment] 2015-12-02 21:47
We've had a number of big updates deployed recently and I can no longer repro this, so I think it has been resolved. Please let me know if you see otherwise!

Thanks and happy coding!

**Closed by ltegman** 2015-12-02 21:47 UTC
Labels: confirmed, firefox
