### ISSUE TITLE
Instructions and specifications do not match

### ISSUE THREAD

**Issue by iBrooks** [FreeCodeCamp/FreeCodeCamp#2432] opened 2015-08-21 17:00 UTC
Instructions say to add a div with class="well" inside the class="col-xs-6" elements

Specifications say to add divs with class="col-xs-6" elements

following instructions causes the specification to be met, even though the spec has not been met.
![screen shot 2015-08-21 at 12 56 37 pm](https://cloud.githubusercontent.com/assets/7727330/9414198/9ce04f96-4804-11e5-91ca-2626c256d6d0.png)

**Comment by benschenker** [comment] 2015-08-21 17:09
Thanks for posting an issue.

It looks like this is a duplicate of #1968 and others, so keep an eye there for fixes.

**Comment by iBrooks** [comment] 2015-08-21 17:16
oh I see! feel free to close this, that is most definitely the same bug.

**Comment by BerkeleyTrue** [comment] 2015-08-21 18:51
Closing as duplicate

**Closed by BerkeleyTrue** 2015-08-21 18:51 UTC
