### ISSUE TITLE
Factorial Challenge: Correct, but doesn't register?

### ISSUE THREAD

**Issue by LonePoop** [FreeCodeCamp/FreeCodeCamp#9438] opened 2016-06-29 03:53 UTC
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20total%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(var%20i%3D0%3B%20i%3Cnum%3B%20i%2B%2B)%7B%0A%20%20%20%20total%20%3D%20total%20*%20(num%20-%20i)%3B%0A%20%20%7D%0A%20%20return%20total%3B%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var total = 1;
function factorialize(num) {
  for (var i=0; i<num; i++){
    total = total * (num - i);
  }
  return total;
}

factorialize(5);

```

**Comment by arun1595** [comment] 2016-06-29 04:20
Duplicate of #9199

**Comment by jmacwanzc** [comment] 2016-06-29 05:23
@LonePoop You just need to declare the 'total' variable inside the function scope.

`function factorialize(num) {
  var total = 1;
  for (var i=0; i<num; i++){
    total = total * (num - i);
  }
  return total;
}
factorialize(5);`

**Comment by LonePoop** [comment] 2016-06-29 05:27
Thanks guys!

**Comment by raisedadead** [comment] 2016-06-29 06:02
Thanks all.

Closing in favor of the other thread.

**Closed by raisedadead** 2016-06-29 06:02 UTC

**Comment by MishaMaryn** [comment] 2016-07-01 22:50
RECURSION GUSY !!, https://msdn.microsoft.com/en-us/library/wwbyhkx4(v=vs.94).aspx 
function factorialize(num) {
return (num !== 0) ? num * factorialize(num - 1) : 1;
}

factorialize(5);
