### ISSUE TITLE
Help! Double #target5 on left!

### ISSUE THREAD

**Issue by tonystaark** [FreeCodeCamp/FreeCodeCamp#11858] opened 2016-11-29 14:36 UTC
Challenge [Target the Children of an Element Using jQuery]

Hi I can't seem to pass the challenge. Tried searching for other related posts on the bug issue but to no avail.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by tonystaark** [comment] 2016-11-29 14:37
![pic2](https://cloud.githubusercontent.com/assets/16837659/20713731/6444f566-b684-11e6-9c9c-0bb1aef6dc9d.png)

**Comment by erictleung** [comment] 2016-11-29 15:45
@tonystaark thanks for the issue. This is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072 and React-ification of the site should solve this problem soon https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7430. Closing as resolved in staging. Happy coding!

**Closed by erictleung** 2016-11-29 15:45 UTC
Labels: question

**Comment by tonystaark** [comment] 2016-11-30 01:22
Nope. I mentioned in my post that all posts I have searched before, including this can't solve my problem. Have tried the solution here for my challenge but it does not work.

**Comment by KarolinaMisiak** [comment] 2017-01-06 13:18
+1
 I have the same problem right now ;/
