### ISSUE TITLE
Free Code Camp Map

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/FreeCodeCamp#1354] opened 2015-07-22 15:42 UTC
I am using Internet Explorer 11 and all the options in the map and the text summary of videos (I have a limited cap on my ISP so unable to watch these) all have the number 1 next to them. Not sure if this is the way things were set up.

Sorry if has been mentioned before.

**Comment by BerkeleyTrue** [comment] 2015-07-22 17:27
Hello @CodingSpider , awesome name by the way!

Can you grab a screen cap and post it here?

**Comment by CodingSpider** [comment] 2015-07-22 17:55
I found the name with an online name generator :)

![free code camp](https://cloud.githubusercontent.com/assets/13453896/8832849/3a7cd374-30a3-11e5-83ad-1a7d7a8be097.jpg)
![map](https://cloud.githubusercontent.com/assets/13453896/8832854/4100e492-30a3-11e5-85ff-e88cec5936bf.jpg)

**Comment by BerkeleyTrue** [comment] 2015-07-22 19:55
Wow that is really weird. May be some `ol` bug in ie11 we are not accounting for...

**Comment by bugron** [comment] 2015-07-23 04:28
A few links:
http://seafoid.org/2009/05/how-internet-explorer-handles-list-ul-and-ol/
http://www.quirksmode.org/bugreports/archives/2005/07/IE_60_does_not_render_ordered_list_correctly.html
http://stackoverflow.com/questions/5584500/ordered-list-showing-all-zeros-in-ie9
http://stackoverflow.com/questions/14520480/numbers-of-an-ordered-list-turn-into-0-while-clicking-trough-jquery-tabs
http://www.maratz.com/blog/archives/2006/10/15/internet-explorer-ordered-list-non-incrementing-list-item/
http://www.kirupa.com/forum/showthread.php?297731-IE-and-Ordered-Lists-Bug-Why-can-t-IE-count
http://klalex.com/2011/06/broken-ordered-list-in-ie9/
http://community.sitepoint.com/t/problem-with-ordered-list-in-internet-explorer/4531
https://social.msdn.microsoft.com/forums/ie/en-us/79ad6d6b-9804-4f42-aa45-b629642f4f0a/ordered-list-showing-all-zeros-in-ie9

**Comment by BerkeleyTrue** [comment] 2015-07-23 04:50
@bugron Thanks for all the links. It would be awesome if you could summarize the solution, though.

**Comment by bugron** [comment] 2015-07-23 07:27
Ok, this behavior is caused by the div elements around the li element in ordered list of the Map. I mean ```<DIV class="row">``` and ```<DIV class="col-xs-12 col-sm-9 col-md-10">```. But this is not a specific behavior of FCC. The code below reproduces the problem.
```html
<!DOCTYPE html>
<html>
<head>
	<title>Exmple</title>
</head>
<body>
	<ol>
		<div>
			<li>item1</li>
		</div>
		<div>
			<li>item2</li>
		</div>
	</ol>
</body>
</html>
```
In **IE10** the result is
1. item1
1. item2
instead of 
1. item1
2. item2
So the conclusion is if the div element(s) is/are wrapped around the li element the problem is occurred.
I tested it in IE10 but I do believe that the same result will be in IE11. And I didn't find any solution of this problem except removing div elements around li element.

**Comment by Xunrel** [comment] 2015-07-23 07:42
@bugron That's correct. Due to W3C standards one can only use li elements.
Within the li elements you can then use other elements.
Sources:
[ol at W3C](http://www.w3.org/2010/04/xhtml10-strict.html#elem_ol)
[ul at W3C](http://www.w3.org/2007/07/xhtml-basic-ref.html#elem_ul)

**Comment by saadanerdetbare** [comment] 2015-08-05 02:11
I have been looking in to this matter and the first ~20% of the problem is quite easy to solve.
In server/views/challengeMap/show.jade the row declaration on line 32 has to be moved up before the ol declaration on line 30 
The row declaration on line 59 has to move up before the ol declaration on line 58 and the row declarations on lines 63, 67,and 71 has to be deleted.
The row declaration on line 90 has to move up before the ol declaration on line 87 and the row declaration on line 97 has to be deleted.
That is the easy part and will remove some of the div elements without any influence on the layout but it will not solve the problem. The rest will take some more digging in the stylesheet and i have not yet gone through that

**Comment by Craggle** [comment] 2015-08-07 05:10
One alternative is to manually recreate the list numbers using CSS counters. I've already tested this method on JSFiddle in IE11, and it circumvented the problem. 

However, there is a drawback. This method generates the list numbers as separate elements from their corresponding list items. Most notably, for smaller screens, multi-line list items will not auto-indent when wrapping to the next line. I suspect that this can be fixed with further CSS hacks, but I cannot be sure.

The resulting appearance may not be as clean, but it behaves properly in IE.

[MDN's page on CSS Counters](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Counters)
[CSS Counter Browser Support](http://caniuse.com/#search=counters)
[JSFiddle based on bugron's example](http://jsfiddle.net/x2sc5g2z/3/)

**Comment by QuincyLarson** [comment] 2015-08-20 07:54
@craggle @codingspider @saadanerdetbare @burgon Awesome - the CSS Counter seems like a super simple fix (2 CSS declarations). I don't have a windows machine - could one of you implement this, verify it fixes the issue, then create a pull request? Thank you all for doing so much research on this.

**Comment by bugron** [comment] 2015-08-20 11:23
I would like to try but I have troubles with running FFC locally on my Windows PC, unfortunately.

**Comment by CodingSpider** [comment] 2015-08-20 16:46
Sorry to have reported the problem in the first place Quincy :)  I have just updated to Windows 10 and have tried it with IE 11 and with edge, the page still shows single number as my original image. Unfortunately still trying to work out how to do a print screen or I would have updated to show.  I had moved onto Chrome using Win 7, still works well on Chrome though with Win 10.

**Comment by benmcmahon100** [comment] 2015-08-20 16:49
I think we found this issue and it's caused by the structure of the html. I don't think anything was done after that though

**Comment by harvindersaggu** [comment] 2015-12-04 09:34
We can use <div> for that

**Comment by LenaBarinova** [comment] 2015-12-04 16:56
I've tried locally adding to css:
```
ol {
    counter-reset: section;
    list-style-type: none;
    padding: 0;
}

li::before {
    counter-increment: section;
    content: counter(section) ". ";
} 
```
It worked on mobile MS Edge v 24.10586. I'll do more testing on other IE versions and create a pull request.

**Comment by ltegman** [comment] 2015-12-04 17:07
@LenaBarinova I think we already had a PR (#2667) submitted that used the approach and it was rejected since ultimately the issue is that we have HTML that doesn't adhere to the spec. We'll need to change the template itself.

**Comment by LenaBarinova** [comment] 2015-12-04 20:23
@ltegman I believe changing template is quite a task. I've tried fixing show.jade - counter works on IE, but the list doesn't look good. Do you know if someone is working on it?

**Comment by bugron** [comment] 2015-12-05 04:40
@LenaBarinova you can take it. I've tried a few times but I was not satisfied with the result every time. This is one of the oldest issues here and if you fix it that would be awesome.

**Comment by LenaBarinova** [comment] 2015-12-07 23:50
I'll try to look into this. I think both should be done here: adding counters in css as well as removing excess ```div``` around ```li``` elements in templates.

**Comment by LenaBarinova** [comment] 2015-12-08 05:52
@ltegman, @bugron, guys I need a second opinion.. Since this map is not a very standard use of list (we want to have progress bar in front of the numbers), I thought what if I replaced these lists with just rows having 3 bootstrap columns: first for progress bar, second for a number, third for a challenge title. I would use a variable in jade for a row number.

**Comment by BerkeleyTrue** [comment] 2015-12-08 05:58
@LenaBarinova There are plans to do away with the map entirely on the move to react.

**Comment by LenaBarinova** [comment] 2015-12-08 06:03
@BerkeleyTrue does it mean, that you would advise not to fix it until then?

**Comment by BerkeleyTrue** [comment] 2015-12-08 07:28
@LenaBarinova If you have a solution for the map then move on it and it will be live as soon as it is merged. But know that in a dozen (maybe less) weeks the map will be removed and will render this issue moot.

**Comment by LenaBarinova** [comment] 2015-12-08 07:43
I think it's worth a try, at least for a couple of months there will be working version on IE. I have all done, I'll create a pull request tomorrow after some more testing on different devices.

**Closed** 2015-12-08 23:47 UTC
Labels: bug, help wanted
