### ISSUE TITLE
Waypoint: Create a Form Element - showing correct even when opening form is not closed

### ISSUE THREAD

**Issue by rbtmarshall** [FreeCodeCamp/FreeCodeCamp#1314] opened 2015-07-16 19:35 UTC
32. Waypoint: Create a Form Element

When working on this challenge I was prompted to move onto the next challenge. Then I noticed that the text input box disappeared from the app.

So I looked back at what I input and noticed that I forgot to close the opening form tag
http://i.imgur.com/s5r5Zoq.png

I'm glad I didn't move along thinking I did it correctly, but also wondered how many others may have made the same mistake thinking they were correct.

**Comment by benschenker** [comment] 2015-08-26 05:06
Closing as duplicate of #1081

**Closed by benschenker** 2015-08-26 05:06 UTC
