### ISSUE TITLE
Are Brownie points supposed to work like this?

### ISSUE THREAD

**Issue by Oxyrus** [FreeCodeCamp/FreeCodeCamp#5957] opened 2016-01-07 19:30 UTC
Today while re-doing some Waypoints to refresh my knowledge I found that whenever you complete an already completed waypoint you still get brownie points and +1 activity in your graph, is it supposed to work that way?

**Comment by DDaems** [comment] 2016-01-07 19:52
`Brownie points` or mainly used to track your activity and be rewarding in return. If you would help someone on gitter they could thank you in return with a simple `@mention thanks` message. I garantee you if you would say `welcome`to everyone that joins the gitterchat at the start of there FCC curriculium that you will be swimming in `brownies` faster than you can imagine. :-)

Anyway, as far as i have read there is a discussion to include badges for tracking someones archievements. Atm `brownie points` & `certicates` or the only available rewards. Which imo is just fine.

**Comment by Oxyrus** [comment] 2016-01-07 19:56
Yes @DDaems I just ask if you're supposed to get brownie points everytime you complete a waypoint, even if it was completed by you before.

**Comment by sludge256** [comment] 2016-01-07 19:56
I am not able to reproduce this.

**Comment by Oxyrus** [comment] 2016-01-07 20:02
@sludge256 I was going to record a video showing it but seems like I don't get brownie points for it anymore, kinda weird.

**Comment by SaintPeter** [comment] 2016-01-07 21:12
Closing as unable to reproduce.

**Closed by SaintPeter** 2016-01-07 21:12 UTC
