### ISSUE TITLE
Certificate's style places top border above viewport on certain viewport sizes

### ISSUE THREAD

**Issue by JulianNF** [freeCodeCamp/freeCodeCamp#36382] opened 2019-07-05 09:41 UTC
# Issue Description

When viewing certificates, if:
* the viewport width is greater than 768px, and
* the viewport height is less than ~1000px,

then the top border of the certificate is rendered above the top of the viewport, and thus cut off. This looks unprofessional.

This issue does not appear to happen at smaller screen sizes as the media queries remove the `.container` div's border.

# Software

I'm seeing this issue on a 64-bit W10 machine, both in Chrome (75.0.3770) and Firefox (67.0.4).

# Proposed solution
1. For `@media (min-width: 768px)`, update the `.certificate-wrapper` to have `margin-top: 30px`.
2. For `@media (min-width: 992px)`, update the `.certificate-wrapper` to have `margin-top: 90px`.

**Comment by ojeytonwilliams** [comment] 2019-07-05 10:01
Hey, thanks for the report.  Could you take a screenshot of the problem?  I tried various window sizes and could not find one which cut off the border.  Generally it looks like this:
![Certificate](https://user-images.githubusercontent.com/15801806/60714952-3fcfe280-9f1c-11e9-9dac-4040258c34be.png)
In the console so you can see the size of the window.

**Comment by JulianNF** [comment] 2019-07-05 10:24
Sure thing!

![certificate - clipped top border](https://user-images.githubusercontent.com/21272816/60716437-ab677f00-9f1f-11e9-9c14-1a6870359465.png)

**Comment by ojeytonwilliams** [comment] 2019-07-05 10:59
Thanks!  I've finally managed to reproduce it - I just need to figure out why it only seems to be an issue on Windows.

**Comment by ojeytonwilliams** [comment] 2019-07-05 13:25
@JulianNF I had a look at this on master and discovered that the buggy behaviour isn't there any more.  In the process I found that there is some redundant css associated with this, which I'll see about removing.

However, I'm closing this, since the fix is on the way.  Thanks again for the report!

**Closed by ojeytonwilliams** 2019-07-05 13:25 UTC
