### ISSUE TITLE
Feature: Mark editable regions on help posts in forum

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46411] opened 2022-06-08 22:59 UTC
### Describe the Issue

The forum help posts submitted by users do not show the editable parts of the code. The snippets ('you code so far') have boilerplate code which makes it difficult to understand the actual edits made by the user.

### Steps to Reproduce

1. On any later step in the RWD project, click Ask For Help and look at the forum post contents.
2. The code snippet looks like so:

   ```html
   <html>
	  <body>
	    <main>
	      <h1>CatPhotoApp</h1>
	      <h2>Cat Photos</h2>
	      <!-- TODO: Add link to cat photos -->
	      <p>Click here to view more <a href="https://freecatphotoapp.com">this is what I changed</a>.</p>
	      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
	    </main>
	  </body>
	</html>
   ```

### Expected behavior

Instead of the above, maybe the code snippet should show what they changed:

```html
<html>
  <body>
    <main>
      <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->

<!-- User Editable Region -->

      <p>Click here to view more <a href="https://freecatphotoapp.com">this is what I changed</a>.</p>

<!-- User Editable Region -->

      <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
    </main>
  </body>
</html>
```

Maybe a nice to have will be to show some diff-style syntax highlighting, but the above should be a good starting point.

**Comment by nhcarrigan** [comment] 2022-06-09 01:20
The editor knows where the editable regions are, so we could probably include the `--fcc-editable-region--` markers in the forum post. 🤔

**Comment by ieahleen** [comment] 2022-06-09 10:09
sometimes users would go to change stuff outside of the defined editable region. Is there a way to point out that change when users change the lines in the editable region?

**Comment by ojeytonwilliams** [comment] 2022-06-09 11:08
> sometimes users would go to change stuff outside of the defined editable region. Is there a way to point out that change when users change the lines in the editable region?

In the editor? We used to have that functionality. It should be possible to implement it again.

**Comment by RandellDawson** [comment] 2022-08-02 18:16
> In the editor? We used to have that functionality. It should be possible to implement it again.

Why was it taken out?

**Comment by ojeytonwilliams** [comment] 2022-08-02 18:40
It was never fully implemented and I don't recall if it was reliable or not. From what I remember it just logged to the browser console.

**Comment by nawed2611** [comment] 2022-10-01 07:28
Hey, can i work on this issue?

**Comment by naomi-lgbt** [comment] 2022-10-01 08:08
Go for it!

**Comment by nawed2611** [comment] 2022-10-02 06:58
The page mentioned in the issue isn't loading up at the moment

**Comment by ieahleen** [comment] 2022-10-02 18:15
To update this, the breadcrumb is now present in the template. That part of the issue is solved.

We probably want to discuss how/if we want to highlight editable region and changes in respect of the seed code.

Maybe even a general test on the curriculum that checks if the test outside the editable region still matches the seed code

**Comment by ieahleen** [comment] 2022-10-02 18:17
@nawed2611 Sorry, this issue is not actually open for contributions

**Comment by nawed2611** [comment] 2022-10-03 08:18
<img width="316" alt="image" src="https://user-images.githubusercontent.com/83456083/193531487-ad022616-e4d0-46e3-a1b5-001ad8bb0aaa.png">

**Comment by Omkar0803** [comment] 2022-10-09 11:13
I would like to contribute, can assign me issues?

**Comment by KravMaguy** [comment] 2022-10-14 21:51
is this issue still seeking contributions? the links attached describing the issue dont exist.

**Comment by ieahleen** [comment] 2022-10-17 10:01
The links exist, the issue is open for contribution

**Comment by KravMaguy** [comment] 2022-10-17 11:04
Affected Page
https://forum.freecodecamp.org/t/the-submit-should-display-quiz-step-40/516112

**Comment by KravMaguy** [comment] 2022-10-17 11:09
>It's a bit difficult to dig through the code on some of the later steps in the RWD. See the >forum post for an example.

>Affected Page
>https://forum.freecodecamp.org/t/the-submit-should-display-quiz-step-40/516112

for me this link does not exist.

>Expected behavior
>Easier output for forum helpers to parse would be nice.

this is not described so clearly

**Comment by ieahleen** [comment] 2022-10-17 11:14
> for me this link does not exist.

ah, that one, it was deleted by the author. But you can see many cases on the forum of users failing tests because they changed code outside the editable region, helpers can't detect that situation easily.



> this is not described so clearly

that's the point of the issue... decide what to implement.

**Comment by naomi-lgbt** [comment] 2022-11-14 14:24
I believe the needs are two-fold.

The OP convers the first one, which is to show the editable region markers in the camper's code when they use the ask for help button.

The second is to have an indication of **where they've changed code** - to make it easier for our moderators to spot when the camper has edited code outside of the ERMs, specifically.

**Comment by jeremylt** [comment] 2022-11-14 18:58
I feel like just adding the markers for the editable region would be a big help. Adding a diff for any pieces outside of the editable region would be a nice follow-up.

**Comment by KravMaguy** [comment] 2022-11-14 19:38
markers for editable region and diff only for changes outside editable region. Ok

**Comment by jeremylt** [comment] 2022-11-14 19:39
How about we start with just the first half? That should be an easy win to get merged.

**Comment by raisedadead** [comment] 2022-11-14 21:09
And we do not want to add a hefty library (not unless it loads 'on-demand') for doing the diff.

**Comment by KravMaguy** [comment] 2022-11-14 21:51
> And we do not want to add a hefty library (not unless it loads 'on-demand') for doing the diff.

Yes ive understood as much, unfortunately, implementing a diffing algorithm from scratch is beyond my current level of knowledge and experience (unless someone exprienced in such matters can provide assistance), ill spin up something using the diff package and you can advise if it satisfies your requirements, or what changes are needed.

**Comment by KravMaguy** [comment] 2022-11-15 03:10
>How about we start with just the first half? That should be an easy win to get merged.

There is a bug in the last PR. it is not yet ready to be merged.

**Comment by raisedadead** [comment] 2022-11-15 08:21
I would say do this in two PRs. The first one just adds the markers and the follow-up could do the diff. That way we can get the markers out into the deployment quickly.

**Comment by KravMaguy** [comment] 2022-11-15 10:12
Ok, ive done the first PR, can you please test it, lmk if it works. I'm having problems on my machine terminal is always crashing and always having to reload the page after every change. Its only this one though, the other PR's I worked on never behaved like this.

**Comment by KravMaguy** [comment] 2022-11-15 11:54
> I would say do this in two PRs. The first one just adds the markers and the follow-up could do the diff. That way we can get the markers out into the deployment quickly.

this one actually has the second requirement on the third commit:

https://github.com/freeCodeCamp/freeCodeCamp/compare/main...KravMaguy:freeCodeCamp:feat/diff-outside-editable-regions

> I feel like just adding the markers for the editable region would be a big help. Adding a diff for any pieces outside of the editable region would be a nice follow-up.

They are both completed (markers for editable region and diff only for changes outside editable region) , the above link has the second requirement as well, what do you want me to do in a case where the user didnt make any changes

**Comment by ShaunSHamilton** [comment] 2022-12-16 18:58
Keep in mind, the diff is rendered on the forum. So, as previously mentioned, we can just use `diff` views with simple "does this line match" logic.

**Closed** 2022-12-22 15:50 UTC
Labels: status: discussing, type: feature request
