### ISSUE TITLE
Some Completed challenges are not marked

### ISSUE THREAD

**Issue by kvscse** [FreeCodeCamp/FreeCodeCamp#7807] opened 2016-03-30 06:06 UTC
I completed HTML5 and CSS challenges, then it was marked completed, but when I saw today, its unmarked.

![capture](https://cloud.githubusercontent.com/assets/9494120/14133305/974617ee-f66b-11e5-84d9-97909576b64e.JPG)

#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by raisedadead** [comment] 2016-03-30 12:37
Possible duplicate of #7795

**Closed** 2016-10-13 20:18 UTC
