### ISSUE TITLE
The returning value doesn't satisfy the function

### ISSUE THREAD

**Issue by akshaybharwani** [FreeCodeCamp/FreeCodeCamp#4307] opened 2015-11-11 20:04 UTC
When I run the filter function over the array argument with the function argument, all the tests for the bonfire run perfectly but the one I've mentioned below doesn't. As it is clear that the returning array would contain the values that are greater than 2 i.e. [3,9], the last test for the bonfire mentions that "drop([1, 2, 3, 9, 2], function(n) {return n > 2}) should return [3, 9, 2]". The returning value here should be corrected.

Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20arr%20%3D%20arr.filter(func)%3B%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%209%2C%202%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36 OPR/33.0.1990.58</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  // Drop them elements.
  arr = arr.filter(func);
  
  return arr;
}

drop([1, 2, 3, 9, 2], function(n) {return n > 2});

```

**Comment by ltegman** [comment] 2015-11-11 20:20
Filter is not a valid solution for this problem. The problem is asking you to keep removing elements until the predicate function returns true. This means that you shift 1 and 2 off and then once you hit 3 the predicate returns true and you stop, returning what's left of the array.

Closing as not a problem with the tests.

Thanks and happy coding!

**Closed by ltegman** 2015-11-11 20:20 UTC

**Comment by akshaybharwani** [comment] 2015-11-11 20:31
Oh. Thank you for the explanation. As there was only one conflicting test, I thought there was a bug. I will try and modify it.
