### ISSUE TITLE
Basic Javascript in beta- correct code won't pass without refresh on some challenges

### ISSUE THREAD

**Issue by lindakatcodes** [freeCodeCamp/freeCodeCamp#15024] opened 2017-05-24 04:23 UTC
Challenge [passing-values-to-functions-with-arguments](http://beta.freecodecamp.com/en/challenges/basic-javascript/passing-values-to-functions-with-arguments) has an issue.
User Agent is:  Chrome/58.0.3029.110 
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
function functionWithArgs(par1, par2) {
  console.log(par1 + par2);
}

functionWithArgs(1, 2);
```

This challenge as well as others (shopping list, write reusable javascript with functions, and a few other earlier ones I can't specifically name) all have an issue where I write the correct answer and try to run, and the tests all fail, regardless of it outputting the correct answer from my code. If I reload the page and then, using the code it saved for me, run the tests, it passes and goes on. This might be something that's already been solved but I didn't see anything specifically about this so I wanted to share in case it was an issue for anyone else. 

Using Chrome 58.0.3029.110 (64-bit), Windows 10 creator update, on an HP laptop. Happy to give any other details needed. I've attached a gif I made showing the issue.
![2017-05-23_23-02-13](https://cloud.githubusercontent.com/assets/16214572/26386810/904502aa-400e-11e7-9fee-262e7ecd9125.gif)

**Comment by erictleung** [comment] 2017-05-24 07:30
@lindakatcodes thanks for the issue. That is quite odd. I'm unfortunately unable to reproduce this bug.

cc/ @freeCodeCamp/moderators anyone else can replicate this? Or know if this is an existing issue?

**Comment by ginhton** [comment] 2017-05-24 15:20
Using the link provided above, I run the code and passed. 
Ubuntu 17.04, Chromium 56.0.2924.76.
I was wondering why the output of my console is just "//running test" and "//tests completed". Your output has more specific tests output which can be seen from your gif.

**Comment by dhcodes** [comment] 2017-05-24 20:37
I can replicate it. @erictleung try doing the challenge before this one and then this one.

**Comment by uijaz** [comment] 2017-05-28 11:09
Having the same issue with almost every other challenge.
Using Chrome 58.0.3029.110 (64-bit), Ubuntu 16.04.2 LTS , on a Lenovo laptop.
My code is fine, refreshing the challenge page passes the tests.  It started for me with "Divide one Decimal by Another with JavaScript" - [#14635](https://github.com/freeCodeCamp/freeCodeCamp/issues/14635)

**Comment by greencleanique** [comment] 2017-05-28 11:41
Okay thanks... Will move to a PC

-----Original Message-----

**Comment by valishah** [comment] 2017-06-07 19:58
Hi @all, Is it taken by anyone. Can i take up to fix if anything that i can help with ?

**Comment by erictleung** [comment] 2017-06-07 21:52
@valishah feel free to tackle the issue! I personally don't have the knowledge to solve this, but you can take a look at the [comment above](https://github.com/freeCodeCamp/freeCodeCamp/issues/15024#issuecomment-303844299) for a starting place.

**Comment by rossfaarley** [comment] 2017-06-12 15:13
Having the same issue as mentioned by @uijaz but on a mac using chrome 58.0.3029.110 (64-bit)

**Comment by CodingPower472** [comment] 2017-07-01 10:51
I can help out with this issue if @valishah can't figure it out.

**Comment by dhcodes** [comment] 2017-07-03 18:59
I'd say go for it @CodingPower472. It's been a bit of time.

**Comment by pigtails21** [comment] 2017-07-05 05:35
why are you sending me emails for luke @codecamp.com????? why

**Comment by texas2010** [comment] 2017-07-05 13:52
@pigtails21 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by mpontus** [comment] 2017-12-09 12:00
Unable to reproduce.

> Google Chrome is up to date
> Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by anhtran1906** [comment] 2017-12-10 01:19
I'm unable to reproduce as well. Using Chrome (62.0.x). This behavior also appears in #14211

**Comment by andyguo1023** [comment] 2017-12-10 04:31
Unable to reproduce using Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by raisedadead** [comment] 2017-12-10 06:35
Thanks everyone, I am closing this as not reproducible any more. Please log a fresh issue, if you happen to come across this.

**Closed by raisedadead** 2017-12-10 06:35 UTC
Labels: beta, help wanted
