### ISSUE TITLE
need 2 p elements with Kitty Ipsum text.

### ISSUE THREAD

**Issue by meub1** [FreeCodeCamp/FreeCodeCamp#4417] opened 2015-11-13 20:04 UTC
Challenge [Waypoint: Change the Font Size of an Element](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%20font-size%3D16px%3B%20face%3D%22Kitty%20Ipsum%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text" font-size=16px; face="Kitty Ipsum">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment] 2015-11-13 20:10
Closing this as there is not description of your problem. Please feel free to reopen with further detail of what the issue is.

Thanks and happy coding!

**Closed by ltegman** 2015-11-13 20:10 UTC
