### ISSUE TITLE
Script element not registering

### ISSUE THREAD

**Issue by jeffvk** [FreeCodeCamp/FreeCodeCamp#3007] opened 2015-09-02 23:24 UTC
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
After creating script element as told in problem. Checker says element not created.

**Comment by bugron** [comment] 2015-09-03 03:40
@jeffvk thanks for posting this issue!
Please, provide your code and screenshot, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by jeffvk** [comment] 2015-09-03 18:41
<script>
        $(document).ready(function() {});
  
</script>
This is the code that finally worked(thanks forum). You will notice I needed a line space after the end of the function before the closing script to get it to read correct. Without the line space, it does not read as correct and you cannot continue.

**Comment by ahstro** [comment] 2015-09-05 01:35
@jeffvk You need to wrap your code in ``` for others to be able to see it. I don't understand what you mean by "a line space after the end", I've tried it many different ways and it always passes.

**Comment by bugron** [comment] 2015-09-05 05:07
Seems the problem is solved so I'm closing this issue.

**Closed by bugron** 2015-09-05 05:07 UTC
