### ISSUE TITLE
Return statement  not displaying in Beta

### ISSUE THREAD

**Issue by vikramnr** [freeCodeCamp/freeCodeCamp#15623] opened 2017-07-11 02:20 UTC
#### Challenge Name

For all challenges.

#### Issue Description

In JS exercise console.log() is not displaying anything and also not displaying anything while using return statement also.  This is a very helpful feature which helps in debugging and also seeing what the results are and what should be actual results. Instead here it is always displaying the same conditions in test-cases which I think is not necessary.    

#### Browser Information

All browsers and OS

#### Screenshot

![image](https://user-images.githubusercontent.com/8538409/28048284-90a05158-660d-11e7-93f4-5963c1ff460d.png)

**Comment by vikramnr** [comment] 2017-07-11 02:21
If this not an issue please go ahead and close this.

**Comment by vikramnr** [comment] 2017-07-11 02:22
@VarCI-bot  This is not a question

**Comment by vikramnr** [comment] 2017-07-14 14:26
@VarCI-bot  Please remove the question label

**Comment by sanyamc** [comment] 2017-07-23 02:42
I am assuming you want to see console.log out put on the webpage itself.
Not sure why would we want to override a native browser api and show it on the webpage.
Instead we can clearly see the console.log statements in browser's dev tools. I have tried that in atleast 4 challenges and it works for various test cases. Using developer tools is an integral part of web development and we should use that instead of hacking console.log to display on the web page.

Above all i see following comment on the very first challenge which says that console.log is going to be in the dev tools.
![image](https://user-images.githubusercontent.com/1045176/28496049-cb49afc8-6f15-11e7-9f8f-888c59688e5b.png)

I suggest close it as by design.

**Comment by vikramnr** [comment] 2017-07-25 16:50
@sanyamc  When using FCC original site will displaying something that we put in return statement but that this not case in Beta site.  Please let me know if you understood otherwise.

**Closed** 2017-09-02 01:36 UTC
Labels: question
