### ISSUE TITLE
Issues with night mode on learn.freecodecamp.org

### ISSUE THREAD

**Issue by conradkay** [freeCodeCamp/freeCodeCamp#17782] opened 2018-07-01 00:11 UTC
Suggested labels:
 first timers welcome
 platform: client
 scope: settings
UX: user interface
###### At the homepage:
* (allpages) The searchbar looks a bit bright but it looks mostly ok.
* (many pages that are not tall enough) The bottom of the screen shows a bright "whitespot" that should be replaced with the closest elements background-color:
![screenshot](https://user-images.githubusercontent.com/24818636/42129826-897a8ada-7c9e-11e8-8f0e-960ead216264.png)

###### At "introduction to" pages:
* Some pages(such as: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5) have codeblocks that look very bad, and somewhat look like there is no anti-aliasing, I would recommend using whatever is used inside of coding lessons to show a line of code, or, for the time being, you could just make darkmode not apply to these code blocks in the introductions(or wherever else they may appear like this).
![screenshot 1](https://user-images.githubusercontent.com/24818636/42129848-9527d706-7c9f-11e8-847c-b221af73ecf0.png)

* There is also a whitespot at the bottom of the page on some.
* The "upcoming lessons" buttons have very little contrast, I would suggest changing the button to what the current "on hover" is(light grey with green text) as it is much more visually appealing, and the onhover could just be a darker green with a darker grey.
![bonkers](https://user-images.githubusercontent.com/24818636/42129830-adc8a67e-7c9e-11e8-8bc4-a3fe3e87c5bf.png)

###### At code editor:

* The "checkered" design on the challenge tests is a bit distracting, perhaps just making the grey just a bit lighter than the blackish-grey used for most of the website would be a major improvement.
![screenshot 2](https://user-images.githubusercontent.com/24818636/42129885-af1e9554-7ca0-11e8-8852-15bb1ca15e75.png)

#### Links
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
(replaceable with any challenge using code editor)

https://learn.freecodecamp.org/coding-interview-prep/algorithms
(replaceable with any "introduction to" page, but this one has the annoying whitespace at the bototm)

https://learn.freecodecamp.org/
(make sure to close all "windows" to see whitespace)

###### Tested on: Chrome 67.0.3396.99 MACOSX high Sierra and Ubuntu 18.04.

I think this would be a good "project" for someone to get familiar with the freecodecamp codebase, as they could navigate around and figure out how everything works and only having to change simple things like colors.
If you would like to contribute, make sure to check out https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md
for further instructions.

**Comment by thatnini** [comment] 2018-07-01 12:00
Some of these issues have already been reported and already have PRs for them:-

- whitespace at bottom of page - [freeCodeCamp/learn/#206](https://github.com/freeCodeCamp/learn/pull/206)
- codeblocks - [freeCodeCamp/learn/#213](https://github.com/freeCodeCamp/learn/pull/213)
- upcoming lessons - [freeCodeCamp/learn/#210](https://github.com/freeCodeCamp/learn/pull/210)

I've open a [PR](https://github.com/freeCodeCamp/learn/pull/214) to fix:- 
- highlighting text in editor
- challenge tests

Someone else can pick up:-
- searchbar
- buttons

**Comment by johnkennedy9147** [comment] 2018-07-01 12:30
closed as duplicate of multiple issues

**Closed by johnkennedy9147** 2018-07-01 12:30 UTC
